### PR TITLE
[Android] Speech to text on search dialog

### LINKED ISSUE #20920: Kodi 19.3 voice search not working with Nvidia shield Android 11 Update (Hotfix #3)
Hi, 
I have updated Nvidia shield 2019 Pro model do Android 11 version of Android TV and installed all 3 currently available hotfixes.
Fixes are available here:
https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/481434/shield-experience-upgrade-90-hotfix-image/
With the latest hotfix longpress button is now working, but voice search is still not.
In the known issues thread it is reported and I quote:
"Apps require updates to resolve these due to changes in Android 11:
Long press select in Kodi doesn't trigger voice search as it should"
This comment is provided below:
https://www.nvidia.com/en-us/geforce/forums/shield-tv/9/481782/shield-experience-upgrade-90-known-issues/
Thefore I am reporting this as a bug:

## Expected Behavior
Longpress of the Nvidia shield remote when searching should trigger the voice search and allow for usage of this function - search by voice.

## Actual Behavior
Longpress brings up the search mic "button" for a split-second and then disappears. No voice is recorded and the functionality does not allow for voice search as was possible prior to Nvidia shield being updated to Android TV 11.

## Possible Fix
N/A

### To Reproduce
1.) Open search menu in Kodi (magnifying glass)
2.) Press on "Search in Local Library"
3.) Longress the remote selection button.

### Your Environment
Used Operating system:
Nvidia Shield Pro 2019, Shield Experience 9 (Hotfix 3), Andorid TV 11

 - Operating system version/name:
 - Kodi version: 19.3

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Current support for speech recognition is provided via an ```Intent```, it starts a native activity that prompts the user for speech and sends the result to the dialog.

On Android TV 11 this dialog is not displayed. I've done several tests, even a test app and it doesn't work.

I propose to access directly to the speech recognition service through the ```SpeechRecognizer``` class.

I've added the class mappings to ```libandroidjni``` (xbmc/libandroidjni#30). 
To compile this PR it's necessary to dump this library into the project.

```RECORD_AUDIO``` permission must be declared in the manifest and Kodi must request this permission at runtime.
Also added a ```<queries>``` element to ensure it works when targeting API level 30.

## How has this been tested?
Tested on Android 9 and 11 and Android TV 11. Does not work on AFTV stick as the Google service is not available.

If it doesn't work at runtime, make sure the Google app has the microphone permission allowed.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [X] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/dialogs/GUIDialogKeyboardGeneric.cpp [hunk 1]
```diff
@@ -35,7 +35,7 @@
 
 #ifdef TARGET_ANDROID
 #include <androidjni/Intent.h>
-#include <androidjni/RecognizerIntent.h>
+#include <androidjni/SpeechRecognizer.h>
 #include <androidjni/ArrayList.h>
```
Comment (ksooo) [inline xbmc/dialogs/GUIDialogKeyboardGeneric.cpp:39]: All these includes are not needed anymore.

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp [hunk 2]
```diff
@@ -0,0 +1,104 @@
...
+void CJNIXBMCRecognitionListener::RegisterNatives(JNIEnv* env)
+{
+  jclass cClass = env->FindClass(s_className.c_str());
+  if(cClass)
+  {
+    JNINativeMethod methods[] =
+    {
+      {"_onReadyForSpeech", "(Landroid/os/Bundle;)V", (void*)&CJNIXBMCRecognitionListener::_onReadyForSpeech},
+      {"_onError", "(I)V", (void*)&CJNIXBMCRecognitionListener::_onError},
+      {"_onResults", "(Landroid/os/Bundle;)V", (void*)&CJNIXBMCRecognitionListener::_onResults},
```
Comment (ksooo) [inline xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:44]: Please use c++ style casts.

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp [hunk 3]
```diff
@@ -0,0 +1,104 @@
...
+  else if (i == CJNISpeechRecognizer::ERROR_NETWORK_TIMEOUT)
+    error = "Network operation timed out";
+  else if (i == CJNISpeechRecognizer::ERROR_NO_MATCH)
+    error = "No recognition result matched";
+  else if (i == CJNISpeechRecognizer::ERROR_RECOGNIZER_BUSY)
+   error = "RecognitionService busy";
+  else if (i == CJNISpeechRecognizer::ERROR_SERVER)
+    error = "Server sends error status";
+  else if (i == CJNISpeechRecognizer::ERROR_SPEECH_TIMEOUT)
+    error = "No speech input";
```
Comment (ksooo) [inline xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:83]: replace if / else / else if with switch / case

Those error strings should be localized, not hardcoded in English.

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp [hunk 4]
```diff
@@ -0,0 +1,104 @@
...
+
+  CLog::Log(LOGDEBUG, "CJNIXBMCRecognitionListener onError(): {}>{}", i, error);
+
+  CGUIDialogKaiToast::QueueNotification(CGUIDialogKaiToast::Info, "Speech to text", error);
```
Comment (ksooo) [inline xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:87]: localization for the toast header needed

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp [hunk 5]
```diff
@@ -0,0 +1,104 @@
...
+}
+
+void CJNIXBMCRecognitionListener::_onResults(JNIEnv* env, jobject thiz, jobject bundle)
+{
+  CJNIBundle b = CJNIBundle(jhobject::fromJNI(bundle));
+
+  CJNIArrayList results = b.getStringArrayList(CJNISpeechRecognizer::RESULTS_RECOGNITION);
+
+  std::string result = results.get(0);
```
Comment (ksooo) [inline xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:96]: const std::string

File: xbmc/platform/android/activity/XBMCApp.cpp [hunk 6]
```diff
@@ -1621,3 +1624,41 @@ void CXBMCApp::surfaceDestroyed(CJNISurfaceHolder holder)
...
+    if (CJNIContext::checkCallingOrSelfPermission("android.permission.RECORD_AUDIO") == CJNIPackageManager::PERMISSION_GRANTED) 
+    {
+      // must be called from the main thread
+      runNativeOnUiThread(StartRecognition, nullptr);
+    }
+    else
+    {
+      CLog::Log(LOGDEBUG, "CXBMCApp OnVoiceRecognition(): permission RECORD_AUDIO is not allowed");
+      std::string error = "Allow Microphone permission to Kodi app in Android Settings";
+      CGUIDialogKaiToast::QueueNotification(CGUIDialogKaiToast::Info, "Speech to text", error);
```
Comment (ksooo) [inline xbmc/platform/android/activity/XBMCApp.cpp:1641]: string localization!

File: xbmc/platform/android/activity/XBMCApp.cpp [hunk 7]
```diff
@@ -1621,3 +1624,41 @@ void CXBMCApp::surfaceDestroyed(CJNISurfaceHolder holder)
...
+    }
+  }
+  else
+  {
+    CLog::Log(LOGDEBUG, "CXBMCApp OnVoiceRecognition(): Google speech service no available");
+    CGUIDialogKaiToast::QueueNotification(CGUIDialogKaiToast::Info, "Speech to text", "Google speech service no available");
```
Comment (ksooo) [inline xbmc/platform/android/activity/XBMCApp.cpp:1647]: string localization

File: xbmc/platform/android/activity/XBMCApp.h [hunk 8]
```diff
@@ -15,6 +15,7 @@
 #include "JNIXBMCDisplayManagerDisplayListener.h"
 #include "JNIXBMCMainView.h"
 #include "JNIXBMCMediaSession.h"
+#include "JNIXBMCRecognitionListener.h"
```
Comment (ksooo) [inline xbmc/platform/android/activity/XBMCApp.h:18]: include not needed here, move to cpp file if needed by implementation

File: xbmc/platform/android/activity/XBMCApp.h [hunk 9]
```diff
@@ -31,6 +32,7 @@
 #include <androidjni/Activity.h>
 #include <androidjni/AudioManager.h>
 #include <androidjni/BroadcastReceiver.h>
+#include <androidjni/SpeechRecognizer.h>
```
Comment (ksooo) [inline xbmc/platform/android/activity/XBMCApp.h:35]: include not needed here, move to cpp file if needed by implementation

File: xbmc/platform/android/activity/XBMCApp.cpp [hunk 10]
```diff
@@ -72,6 +74,7 @@
 #include "cores/AudioEngine/Interfaces/AE.h"
 #include "cores/AudioEngine/Sinks/AESinkAUDIOTRACK.h"
 #include "cores/VideoPlayer/VideoRenderers/RenderManager.h"
+#include "dialogs/GUIDialogKaiToast.h"
```
Comment (ksooo) [inline xbmc/platform/android/activity/XBMCApp.cpp:77]: Doh! Making CXBMCApp dependent on high level gui components seems not correct. Usually, XBMCApp interacts with the upper layers of Kodi using messages.

CXBMCApp should only provide low level functionality, not have any GUI.

File: xbmc/platform/android/activity/XBMCApp.cpp [hunk 11]
```diff
@@ -1621,3 +1624,41 @@ void CXBMCApp::surfaceDestroyed(CJNISurfaceHolder holder)
...
   m_window.reset();
 }
+
+void CXBMCApp::OnVoiceRecognition()
+{
+  if (CJNISpeechRecognizer::isRecognitionAvailable(CXBMCApp::Get()))
+  {
+    if (CJNIContext::checkCallingOrSelfPermission("android.permission.RECORD_AUDIO") == CJNIPackageManager::PERMISSION_GRANTED) 
+    {
+      // must be called from the main thread
```
Comment (ksooo) [inline xbmc/platform/android/activity/XBMCApp.cpp:1634]: why?

File: xbmc/platform/android/activity/XBMCApp.cpp (hunk 7 above)
Comment (ksooo) [reply xbmc/platform/android/activity/XBMCApp.cpp:1647]: To get rid of the gui dependency here, OnVoiceRecognition should return an error code (an enum value) and the calling GUI code should raise the toast.

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp (hunk 3 above)
Comment (ksooo) [reply xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:83]: Not sure these errors are relevant for the end user. should those just be logged instead of confronting the user with technical stuff they do not understand?

**Comment by joseluismarti** [comment]
Thanks @ksooo, I'll make the changes you describe: strings localized, simplify user messages, take out the GUI code from CXBMCApp...

File: xbmc/platform/android/activity/XBMCApp.cpp (hunk 11 above)
Comment (joseluismarti) [reply xbmc/platform/android/activity/XBMCApp.cpp:1634]: This requirement is indicated in the [SpeechRecognizer](https://developer.android.com/reference/android/speech/SpeechRecognizer) documentation

File: xbmc/dialogs/GUIDialogKeyboardGeneric.cpp [hunk 12]
```diff
@@ -34,13 +35,7 @@
 #include <mutex>
 
 #ifdef TARGET_ANDROID
-#include <androidjni/Intent.h>
-#include <androidjni/RecognizerIntent.h>
-#include <androidjni/ArrayList.h>
 #include "platform/android/activity/XBMCApp.h"
-
-#define ACTION_RECOGNIZE_SPEECH_REQID 543
```
Comment (ksooo) [inline xbmc/dialogs/GUIDialogKeyboardGeneric.cpp:42]: Prefer constants over defines, because of type safety:

```c++
namespace
{
constexpr int ACTION_RECOGNIZE_SPEECH_REQID = 543;
}

File: xbmc/dialogs/GUIDialogKeyboardGeneric.cpp [hunk 13]
```diff
@@ -11,6 +11,7 @@
 #include "GUIDialogNumeric.h"
 #include "GUIUserMessages.h"
 #include "ServiceBroker.h"
+#include "dialogs/GUIDialogKaiToast.h"
```
Comment (ksooo) [inline xbmc/dialogs/GUIDialogKeyboardGeneric.cpp:14]: Include should be surrounded by `#ifdef TARGET_ANDROID`, because toasts are only needed on Android.

File: xbmc/platform/android/activity/XBMCApp.cpp (hunk 11 above)
Comment (ksooo) [reply xbmc/platform/android/activity/XBMCApp.cpp:1635]: okay, could you add a link to the documentation to the comment, please?

File: xbmc/platform/android/activity/XBMCApp.cpp [hunk 14]
```diff
@@ -1621,3 +1624,44 @@ void CXBMCApp::surfaceDestroyed(CJNISurfaceHolder holder)
...
+
+    CJNIIntent intent = CJNIIntent(CJNIRecognizerIntent::ACTION_RECOGNIZE_SPEECH);
+    intent.putExtra(CJNIRecognizerIntent::EXTRA_LANGUAGE_MODEL,
+                    CJNIRecognizerIntent::LANGUAGE_MODEL_FREE_FORM);
+
+    CJNISpeechRecognizer speechRecognizer =
+        CJNISpeechRecognizer::createSpeechRecognizer(CXBMCApp::Get());
+  
+    speechRecognizer.setRecognitionListener(CJNIXBMCRecognitionListener());
+    speechRecognizer.startListening(intent);
```
Comment (ksooo) [inline xbmc/platform/android/activity/XBMCApp.cpp:1665]: I would order the code  bit so that things that belong logically together are close together in the code.

```c++
     CJNISpeechRecognizer speechRecognizer =
         CJNISpeechRecognizer::createSpeechRecognizer(CXBMCApp::Get());

     speechRecognizer.setRecognitionListener(CJNIXBMCRecognitionListener());
     
     CJNIIntent intent = CJNIIntent(CJNIRecognizerIntent::ACTION_RECOGNIZE_SPEECH);
     intent.putExtra(CJNIRecognizerIntent::EXTRA_LANGUAGE_MODEL,
                     CJNIRecognizerIntent::LANGUAGE_MODEL_FREE_FORM); 
     speechRecognizer.startListening(intent);
```

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp [hunk 15]
```diff
@@ -0,0 +1,94 @@
...
+}
+
+void CJNIXBMCRecognitionListener::_onError(JNIEnv* env, jobject thiz, jint i)
+{
+  if (i == CJNISpeechRecognizer::ERROR_NO_MATCH)
+    CGUIDialogKaiToast::QueueNotification(CGUIDialogKaiToast::Info, g_localizeStrings.Get(39177),
+        g_localizeStrings.Get(39180));
+  else
+    CGUIDialogKaiToast::QueueNotification(CGUIDialogKaiToast::Info, g_localizeStrings.Get(39177),
+        g_localizeStrings.Get(39181));
```
Comment (ksooo) [inline xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:74]: Dependency to high level GUI layer here is not okay. Either you use messaging to signal the error or you need to drop the feature to interact with the user on errors.

**Review by ksooo — CHANGES_REQUESTED** [review]

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp (hunk 15 above)
Comment (ksooo) [reply xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:74]: Most probably you need to define and implement a new GUI_MSG_USER.

File: xbmc/dialogs/GUIDialogKeyboardGeneric.cpp (hunk 12 above)
Comment (joseluismarti) [reply xbmc/dialogs/GUIDialogKeyboardGeneric.cpp:42]: Hello, I've deleted this define because I think it's not needed

File: xbmc/dialogs/GUIDialogKeyboardGeneric.cpp (hunk 13 above)
Comment (joseluismarti) [reply xbmc/dialogs/GUIDialogKeyboardGeneric.cpp:14]: fine I'll add the #ifdef

File: xbmc/platform/android/activity/XBMCApp.cpp (hunk 14 above)
Comment (joseluismarti) [reply xbmc/platform/android/activity/XBMCApp.cpp:1665]: ok, I will reorder the code

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp (hunk 15 above)
Comment (joseluismarti) [reply xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:74]: These info toast are displayed to the user to give him some feedback on the speech recognition process. It's not possible to interact with these errors as the listening process has ended.

These messages only appear when the Speech Recognizer has not been able to match what it has heard or there has been an error (connection error...).

File: xbmc/dialogs/GUIDialogKeyboardGeneric.cpp (hunk 12 above)
Comment (ksooo) [reply xbmc/dialogs/GUIDialogKeyboardGeneric.cpp:42]: Even better.

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp (hunk 15 above)
Comment (ksooo) [reply xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:74]: I understand the purpose of the toasts, but from software architectural standpoint your implementation is wrong.  You are in a lower non gui layer, which must a) not directly call into upper gui layer of Kodi and b) you are in an arbitrary thread and Kodi guilib Must only be called from kodis main thread. We have AppMessenger to deal with both problems.

Comment (joseluismarti) [reply xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:74]: Ok, I'll make the changes to send the messages to ```CGUIDialogKeyboardGeneric```, as it does with the result, and this dialog will launch the Toast

Comment (ksooo) [reply xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:74]: Okay, but design the message format to work with enum  values, not directly with localized strings, please. Localized strings are also gui stuff that does not belong in the speech resolver listener class. I know this is a bit more work, but then we will end with a clean solution.

Comment (ksooo) [reply xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:74]: I would define a new message

`#define TMSG_SPEECH_RECOGNIZER_ERROR  TMSG_MASK_APPLICATION + 34` in xbmc/messaging/ApplicationMesenger.h

and an 

`enum class SpeechRecognizerError` for the possible error values, in a new separate header file in xbmc/speech/SpeechRecognizerErrors.h (speech would be a new subdir)

`CJNISpeechRecognizer::_onError` uses AppMessenger to post the new message, which dispatches to `CApplication::OnApplicationMessage` which calls new method `CGUIDialogKeyboardGeneric::OnSpeechRecognitionError` which maps the enum value to localisable strings and shows the toast.

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp [hunk 16]
```diff
@@ -0,0 +1,94 @@
...
+
+CJNIXBMCRecognitionListener::~CJNIXBMCRecognitionListener()
+{
+  remove_instance(this);
+}
+
+void CJNIXBMCRecognitionListener::_onReadyForSpeech(JNIEnv* env, jobject thiz, jobject bundle)
+{
+  CGUIDialogKaiToast::QueueNotification(CGUIDialogKaiToast::Info, g_localizeStrings.Get(39177),
+      g_localizeStrings.Get(39179));
```
Comment (ksooo) [inline xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:62]: Same approach as for ::_onError. define a new message TMSG_SPEECH_RECOGNIZER_READY, disapach via AppMessenger to Capp, then to `CGUIDialogKeyboardGeneric::OnSpeechRecognizerReady`, which displays the toast.

**Review by ksooo — CHANGES_REQUESTED** [review]

File: xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp [hunk 17]
```diff
@@ -0,0 +1,94 @@
...
+
+  CJNIArrayList results = b.getStringArrayList(CJNISpeechRecognizer::RESULTS_RECOGNITION);
+
+  const std::string result = results.get(0);
+
+  CGUIWindow* window = CServiceBroker::GetGUI()->GetWindowManager().GetWindow(
+      CServiceBroker::GetGUI()->GetWindowManager().GetActiveWindowOrDialog());
+  CGUIMessage msg(GUI_MSG_SET_TEXT, 0, window->GetFocusedControlID());
+  msg.SetLabel(result);
+  CServiceBroker::GetAppMessenger()->SendGUIMessage(msg, window->GetID());
```
Comment (ksooo) [inline xbmc/platform/android/activity/JNIXBMCRecognitionListener.cpp:91]: Same approach as for ::_onError. define a new message TMSG_SPEECH_RECOGNIZER_RESULTS, disapach via AppMessenger to Capp, then to CGUIDialogKeyboardGeneric::OnSpeechRecognizerResult, which does the SET_TEXT.

**Review by ksooo — CHANGES_REQUESTED** [review]

File: xbmc/platform/android/activity/XBMCApp.h [hunk 18]
```diff
@@ -262,6 +265,8 @@ class CXBMCApp
   static void RegisterDisplayListenerCallback(CVariant*);
   void UnregisterDisplayListener();
 
+  static void StartRecognition(CVariant*);
```
Comment (ksooo) [inline xbmc/platform/android/activity/XBMCApp.h:268]: Please give this a more meaningful name, like `StartSpeechRecognition`.

**Review by ksooo — DISMISSED** [review]

**Comment by ksooo** [comment]
@joseluismarti i know it is a bit more work than you might have thought, but the feature is worth the effort. So, if you need some assistance with the requested changes, I’m here. 😀

File: tools/depends/target/libandroidjni/LIBANDROIDJNI-VERSION [hunk 19]
```diff
@@ -1,5 +1,5 @@
 LIBNAME=libandroidjni
-VERSION=cb68ac77303d1edd95e39a6f72655cdb12f76fd2
+VERSION=76e1d4429ea23f8671cada828a29be9c2a7a3210
 BASE_URL=https://github.com/xbmc/libandroidjni/archive
 ARCHIVE=$(VERSION).tar.gz
 SHA512=070e803d8a6fed549fd9f1a92caea300fed1c6c1e3eba168b0b0cdc008e24644e9085c706715853289025e2f55f964c810c46f79fca464c71d3ffe37f7ae366e
```
Comment (fuzzard) [inline tools/depends/target/libandroidjni/LIBANDROIDJNI-VERSION:5]: @ksooo you'll need to update the SHA512 as well.

Comment (ksooo) [reply tools/depends/target/libandroidjni/LIBANDROIDJNI-VERSION]: yes, meanwhile I did

**Comment by ksooo** [comment]
Jenkins build this please

File: xbmc/platform/android/activity/JNIXBMCSpeechRecognitionListener.cpp [hunk 20]
```diff
@@ -0,0 +1,80 @@
...
+  CJNIBundle b = CJNIBundle(jhobject::fromJNI(bundle));
+  CJNIArrayList results = b.getStringArrayList(CJNISpeechRecognizer::RESULTS_RECOGNITION);
+
+  CLog::Log(LOGDEBUG, "CJNIXBMCSpeechRecognitionListener onResults(): {}", results.size());
+
+  std::vector<std::string> params;
+  for (int i = 0; i < results.size(); ++i)
+    params.emplace_back(results.get(i));
+
+  CServiceBroker::GetAppMessenger()->PostMsg(TMSG_SPECH_RECOGNITION_RESULTS, 0, 0, nullptr, params);
```
Comment (fuzzard) [inline xbmc/platform/android/activity/JNIXBMCSpeechRecognitionListener.cpp:79]: typo ;)

File: xbmc/platform/android/activity/JNIXBMCSpeechRecognitionListener.cpp [hunk 21]
```diff
@@ -0,0 +1,80 @@
...
+  CLog::Log(LOGDEBUG, "CJNIXBMCSpeechRecognitionListener onReadyForSpeech()");
+
+  CServiceBroker::GetAppMessenger()->PostMsg(TMSG_SPECH_RECOGNITION_READY);
+}
+
+void CJNIXBMCSpeechRecognitionListener::_onError(JNIEnv* env, jobject thiz, jint i)
+{
+  CLog::Log(LOGDEBUG, "CJNIXBMCSpeechRecognitionListener onError(): [{}]", i);
+
+  CServiceBroker::GetAppMessenger()->PostMsg(TMSG_SPECH_RECOGNITION_ERROR, i);
```
Comment (fuzzard) [inline xbmc/platform/android/activity/JNIXBMCSpeechRecognitionListener.cpp:65]: typo

File: xbmc/platform/android/activity/JNIXBMCSpeechRecognitionListener.cpp [hunk 22]
```diff
@@ -0,0 +1,80 @@
...
+CJNIXBMCSpeechRecognitionListener::~CJNIXBMCSpeechRecognitionListener()
+{
+  remove_instance(this);
+}
+
+void CJNIXBMCSpeechRecognitionListener::_onReadyForSpeech(JNIEnv* env, jobject thiz, jobject bundle)
+{
+  CLog::Log(LOGDEBUG, "CJNIXBMCSpeechRecognitionListener onReadyForSpeech()");
+
+  CServiceBroker::GetAppMessenger()->PostMsg(TMSG_SPECH_RECOGNITION_READY);
```
Comment (fuzzard) [inline xbmc/platform/android/activity/JNIXBMCSpeechRecognitionListener.cpp:58]: typo

File: xbmc/messaging/ApplicationMessenger.h [hunk 23]
```diff
@@ -83,6 +83,10 @@
 #define TMSG_RENDERER_UNINIT              TMSG_MASK_APPLICATION + 32
 #define TMSG_EVENT                        TMSG_MASK_APPLICATION + 33
 
+#define TMSG_SPECH_RECOGNITION_READY TMSG_MASK_APPLICATION + 34
```
Comment (fuzzard) [inline xbmc/messaging/ApplicationMessenger.h:86]: I was wrong, wasnt typos, but it should be fixed. EE for speech

File: xbmc/speech/CMakeLists.txt [hunk 24]
```diff
@@ -0,0 +1 @@
+set(HEADERS RecognizerErrors.h)
```
Comment (fuzzard) [inline xbmc/speech/CMakeLists.txt:1]: I would suggest this speech folder gets added to treedata

https://github.com/xbmc/xbmc/blob/master/cmake/treedata/common/subdirs.txt

cmake passes treedata to access all the CMakeLists.txt files. in this particular case, as its just a header, it "works", but if we do this wrong from the start, if there ends up being code compiled (ie cpp), someone will tear their hair out down the line because of it.

File: xbmc/platform/android/activity/JNIXBMCSpeechRecognitionListener.cpp [hunk 25]
```diff
@@ -0,0 +1,80 @@
...
+}
+
+void CJNIXBMCSpeechRecognitionListener::_onError(JNIEnv* env, jobject thiz, jint i)
+{
+  CLog::Log(LOGDEBUG, "CJNIXBMCSpeechRecognitionListener onError(): [{}]", i);
+
+  CServiceBroker::GetAppMessenger()->PostMsg(TMSG_SPECH_RECOGNITION_ERROR, i);
+}
```
Comment (fuzzard) [inline xbmc/platform/android/activity/JNIXBMCSpeechRecognitionListener.cpp:66]: Looks like the PostMsg you want is (6 arguments)
```
void PostMsg(uint32_t messageId, int param1, int param2, void* payload, std::string strParam, std::vector<std::string> params);
```
theres not a 5 argument function call with the vector<std::string>

**Comment by ksooo** [comment]
@fuzzard thanks for the review. This PR is very WIP and I will rewrite larger parts of it.

File: xbmc/speech/CMakeLists.txt (hunk 24 above)
Comment (ksooo) [reply xbmc/speech/CMakeLists.txt:1]: It's there already.

Comment (fuzzard) [reply xbmc/speech/CMakeLists.txt:1]: sorry, must have missed that, my bad

**Comment by ksooo** [comment]
Jenkins build this please

**Comment by a1rwulf** [comment]
> Jenkins is picking up the wrong commit again and again. No idea what to do.

@ksooo Usually closing and reopening the PR helps, not sure if you tried already.

**Comment by ksooo** [comment]
Jenkins build this please

**Comment by Rechi** [comment]
This PR currently adds a new compiler warning.
`xbmc/dialogs/GUIDialogKeyboardGeneric.h:28:7: warning: ‘CGUIDialogKeyboardGeneric’ has a field ‘CGUIDialogKeyboardGeneric::m_speechRecognitionListener’ whose type uses the anonymous namespace [-Wsubobject-linkage]`

**Comment by ksooo** [comment]
> This PR currently adds a new compiler warning.

 Thanks for the heads-up. Will be fixed.

**Comment by ksooo** [comment]
@joseluismarti all problems should be solved now. Code is ready for a runtime test.

**Comment by ksooo** [comment]
@joseluismarti and myself successfully runtime-tested on different devices. Jenkins is happy. I'd say, this PR is ready to go in.

@fuzzard any last words regarding the code changes?

**Comment by ksooo** [comment]
Jenkins LINUX errors are unrelated. Something with zlib dependency goes wrong (wrong checksum of the tar file it seems).

**Comment by ksooo** [comment]
From me pov the PR is ready for final review/test now, then it can go in.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
Jenkins is still moaning. Nothing we broke with this PR.

```
15:07:18 Error: failed to verify hash sum of zlib-1.2.12.tar.xz, expected type: sha512 value 12940e81e988f7661da52fa20bdc333314ae86a621fdb748804a20840b065a1d6d984430f2d41f3a057de0effc6ff9bcf42f9ee9510b88219085f59cbbd082bd, retrying..
15:07:18 download zlib-1.2.12.tar.xz retry 1
15:07:18 download zlib-1.2.12.tar.xz retry 2
15:07:21 download zlib-1.2.12.tar.xz retry 3
15:07:25 make[2]: *** [../../download-files.include:44: /home/jenkins/xbmc-tarballs/zlib-1.2.12.tar.xz.sha512] Error 1
```

**Comment by ksooo** [comment]
Heads-up: If nobody objects I will merge this PR as it is the next days.

**Comment by joseluismarti** [comment]
#20920
