### PR TITLE
[win32] fix wrong output size in case when system doesn't inform wind…

### LINKED ISSUE #14735: Resolution Whitelist issues (Win 10 | v18 latest nightlies and beta/rc)
### Describe the bug
Here is a clear and concise description of what the problem is:

Windows 10 using nightlies and beta 4. I'm seeing strange behaviour (both 4k and 1080p screen resolutions and videos) with resolution switching using the resolution whitelist feature.

**3840 x 2160 screen resolution playing 1080p videos...**

With my screen resolution set to 3840x2160, and with all 1920x1080 resolutions selected in the resolution whitelist, 1080p video displays in top left corner as 1920x1080, however screen resolution remains at 3840x2160.

Screenshot... https://imgur.com/FGsf2GV
Debug log... https://paste.kodi.tv/qaruxaluce.kodi

**1920 x 1080 screen resolution playing 4k videos...**

With my screen resolution set to 1920x1080, and with all 3840x2160 resolutions selected in the resolution whitelist, only the top left quarter of the 4k video displays, however screen resolution remains at 1920x1080.

Screenshot... https://imgur.com/G8ZMIGf
Debug log... https://paste.kodi.tv/okodawoxix.kodi

Forum post related to issue... https://forum.kodi.tv/showthread.php?tid=336934

**The whitelist feature works fine if run Kodi as a fullscreen window.
However behaves as above if i run true fullscreen.**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

With the screen resolution set 3840x2160, and with the 1920x1080 resolutions selected in the resolution whitelist, 1080 resolution videos should switch the display to 1920x1080.

With the screen resolution set 1920x1080, and with the 3840x2160 resolutions selected in the resolution whitelist, 4k resolution videos should switch the display to 3840x2160.

## Actual Behavior

**3840 x 2160 screen resolution playing 1080p videos...**

With my screen resolution set to 3840x2160, and with all 1920x1080 resolutions selected in the resolution whitelist, 1080p video displays in top left corner as 1920x1080, however screen resolution remains at 3840x2160.

Screenshot... https://imgur.com/FGsf2GV
Debug log... https://paste.kodi.tv/qaruxaluce.kodi

**1920 x 1080 screen resolution playing 4k videos...**

With my screen resolution set to 1920x1080, and with all 3840x2160 resolutions selected in the resolution whitelist, only the top left quarter of the 4k video displays, however screen resolution remains at 1920x1080.

Screenshot... https://imgur.com/G8ZMIGf
Debug log... https://paste.kodi.tv/okodawoxix.kodi

### To Reproduce

1. set screen resolution to 3840x2160
2. select all 1920x1080 resolutions in the resolution whitelist
3. set kodi to true fullscreen
4. play 1080p video

This results in... https://imgur.com/FGsf2GV

or

1. set screen resolution to 1920x1080
2. select all 3840x2160 resolutions in the resolution whitelist
3. set kodi to true fullscreen
4. play 4k video

This results in... https://imgur.com/G8ZMIGf

### Debuglog

The debuglog can be found here:

**3840 x 2160 screen resolution playing 1080p videos...**
Debug log... https://paste.kodi.tv/qaruxaluce.kodi

**1920 x 1080 screen resolution playing 4k videos...**
Debug log... https://paste.kodi.tv/okodawoxix.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

**3840 x 2160 screen resolution playing 1080p videos...**
Screenshot... https://imgur.com/FGsf2GV

**1920 x 1080 screen resolution playing 4k videos...**
Screenshot... https://imgur.com/G8ZMIGf

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Pro v1803
 - Kodi version: Nightlies and Beta 4
- GPU: NVidia GT 1030

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by afedchin**
…owing about desktop size change in true fullscreen.

this should fix #14735

### CODE REVIEW

File: xbmc/rendering/dx/DeviceResources.cpp [hunk 1]
```diff
@@ -195,13 +195,14 @@ bool DX::DeviceResources::SetFullScreen(bool fullscreen, RESOLUTION_INFO& res)
...
 
-  CLog::LogF(LOGDEBUG, "switching to/from fullscreen (%f x %f)", m_outputSize.Width,
-             m_outputSize.Height);
-
   BOOL bFullScreen;
-  bool recreate = m_stereoEnabled != (CServiceBroker::GetWinSystem()->GetGfxContext().GetStereoMode() == RENDER_STEREO_MODE_HARDWAREBASED);
-
   m_swapChain->GetFullscreenState(&bFullScreen, nullptr);
+
+  CLog::LogF(LOGDEBUG, "switching from %s (%.0f x %.0f) to %s (%d x %d)",
```
Comment (Rechi) [inline xbmc/rendering/dx/DeviceResources.cpp]: looking at the lines bellow, it looks like you wanted to avoid double spaces in this log line
```suggestion
  CLog::LogF(LOGDEBUG, "switching from %s(%.0f x %.0f) to %s(%d x %d)",
```

Comment (afedchin) [reply xbmc/rendering/dx/DeviceResources.cpp]: you are right. thanks

**Comment by afedchin** [comment]
jenkins build this please

File: xbmc/rendering/dx/DeviceResources.cpp [hunk 2]
```diff
@@ -198,7 +198,7 @@ bool DX::DeviceResources::SetFullScreen(bool fullscreen, RESOLUTION_INFO& res)
   BOOL bFullScreen;
   m_swapChain->GetFullscreenState(&bFullScreen, nullptr);
 
-  CLog::LogF(LOGDEBUG, "switching from %s (%.0f x %.0f) to %s (%d x %d)",
+  CLog::LogF(LOGDEBUG, "switching from %s(%.0f x %.0f) to %s(%d x %d)",
```
Comment (Rechi) [inline xbmc/rendering/dx/DeviceResources.cpp]: please squash this

**Comment by afedchin** [comment]
jenkins build this please
