### PR TITLE
[Password] Improve media lock checks (including recently added videos)

### LINKED ISSUE #25826: master lock code bypass
### Master Lock code work around
Here is a clear and concise description of what the problem is:

Hi,
My son has figured out a workaround for the master lock code to watch tv shows.
On the home screen he scrolls over to TV Shows and goes to up to recently added. He is able to play these files. He then marks these as played until the show he wants is shown.  This occurs on estuary and confluence.
Recently added could just be disabled , but it is a feature I enjoy.

Would it be possible to enable the master lock code for recently added?

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The recently added thumbnail is visible on the home screen, when selected the master lock code is requested

## Actual Behavior

The recently added thumbnail is visible on the home screen, when selected the video plays

### To Reproduce

1.  Go to TV shows on home screen
2. Select a recently added TV show
3. Video plays

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Fix #25826.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/GUIPassword.cpp [hunk 1]
```diff
@@ -479,6 +479,20 @@ bool CGUIPassword::CheckMenuLock(int iWindowID)
     return true;
 }
 
+bool CGUIPassword::IsVideoUnlocked()
+{
+  const std::shared_ptr<CProfileManager> profileManager =
```
Comment (thexai) [inline xbmc/GUIPassword.cpp:484]:
```suggestion
  const auto profileManager =
```

Comment (78andyp) [reply xbmc/GUIPassword.cpp]: Done

**Review by howie-f — COMMENTED** [review]
nice to see this working.
however it's still possible to play locked videos via json-rpc.
you know kids always have their remotes hidden somewhere :)
@78andyp any idea on how to also prevent this?

**Comment by 78andyp** [comment]
> nice to see this working. however it's still possible to play locked videos via json-rpc. you know kids always have their remotes hidden somewhere :) @78andyp any idea on how to also prevent this?

Hi
I have absolutely no idea how to do anything via json-rpc, and only a vauge idea of what it actually means!!
I'll see what I can learn!

**Comment by 78andyp** [comment]
Hi @howie-f 

The latest push should capture JSON-RPC play attemps as well.

I've put the code where it is, rather than the common `PlayFile` function (which is the first shared function between the local path and the json path) - as if you put it there it breaks the fact you've unlocked music/videos when you go into the seperate video/music screens.

Hope this is OK.

**Comment by howie-f** [comment]
thanks a bunch. i‘ll take a look at it and test soon. it may take a few days

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp [hunk 2]
```diff
@@ -474,6 +474,14 @@ int PlayOrQueueMedia(const std::vector<std::string>& params, bool forcePlay)
   // need some extended item properties to process resume successfully. Load them.
   item.LoadDetails();
 
+  // Check if video sources are locked - to capture recently added videos played from the home screen
+  if (VIDEO::IsVideo(item) && !g_passwordManager.IsVideoUnlocked())
```
Comment (ksooo) [inline xbmc/interfaces/builtins/PlayerBuiltins.cpp:478]: This method also handles music. Should a similar check for music be added?

File: xbmc/GUIPassword.h [hunk 3]
```diff
@@ -60,6 +60,8 @@ class CGUIPassword : public ISettingCallback
    */
   bool CheckSettingLevelLock(const SettingLevel& level, bool enforce = false);
   bool CheckMenuLock(int iWindowID);
+  bool IsVideoUnlocked();
```
Comment (ksooo) [inline xbmc/GUIPassword.h:63]: Could this method be cost?

File: xbmc/GUIPassword.h [hunk 4]
```diff
@@ -60,6 +60,8 @@ class CGUIPassword : public ISettingCallback
...
+  bool IsMusicUnlocked();
```
Comment (ksooo) [inline xbmc/GUIPassword.h:64]: Could this method be cost?

File: xbmc/PlayListPlayer.cpp [hunk 5]
```diff
@@ -984,7 +985,18 @@ void PLAYLIST::CPlayListPlayer::OnApplicationMessage(KODI::MESSAGING::ThreadMess
             return;
           }
           if (MUSIC::IsAudio(*item) || IsVideo(*item))
+          {
+            // Check if sources are locked - to capture media played via json-rpc
```
Comment (ksooo) [inline xbmc/PlayListPlayer.cpp:989]: Not sure this method is the right place to handle json rpc as this class here is fairly generic and handles much more than json rpc. I would try to do this check somewhere in xbmc/interfaces/json-rpc

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp (hunk 2 above)
Comment (78andyp) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:478]: Music (including recently added) seems to be password checked before this point.

File: xbmc/GUIPassword.h (hunk 3 above)
Comment (78andyp) [reply xbmc/GUIPassword.h:63]: No - due to  `IsMasterLockUnlocked(true)` being called

File: xbmc/GUIPassword.h (hunk 4 above)
Comment (78andyp) [reply xbmc/GUIPassword.h:64]: No - due to  `IsMasterLockUnlocked(true)` being called

File: xbmc/PlayListPlayer.cpp (hunk 5 above)
Comment (78andyp) [reply xbmc/PlayListPlayer.cpp:989]: Is that not a good thing? - any video should not be playable without a password check when video lock is on.

File: xbmc/GUIPassword.h (hunk 3 above)
Comment (ksooo) [reply xbmc/GUIPassword.h:63]: This is all a big mess. My next question would be why IsMasterLockUnlocked is not const. But this goes probably beyond the scope of this PR.

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp (hunk 2 above)
Comment (ksooo) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:478]: Then i would at least try to find the place similar to the place where the check is done for music. Having the check here only for video feels not right.

File: xbmc/PlayListPlayer.cpp (hunk 5 above)
Comment (ksooo) [reply xbmc/PlayListPlayer.cpp:989]: Then at least your comment is wrong.

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp (hunk 2 above)
Comment (78andyp) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:478]: The code path for playing recently added items is very different for some reason:

image

Playing from the movies menu:

image

There is nowhere in common with music and in the recently added play path, so it's in the best place I think.

File: xbmc/GUIPassword.h (hunk 3 above)
Comment (78andyp) [reply xbmc/GUIPassword.h:63]: Agreed. Beyond scope.

File: xbmc/PlayListPlayer.cpp (hunk 5 above)
Comment (78andyp) [reply xbmc/PlayListPlayer.cpp:989]: Changed.

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp (hunk 2 above)
Comment (ksooo) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:478]: > so it's in the best place I think.

Sorry, no. There are definitely ways to call this for music!

image

Example: Set default album select action to "Play" in estuary and click an album on music home screen recently added albums widget.

image

Comment (ksooo) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:478]: My suggestion was not to find a different place to check videos but to add the check for music.

Comment (ksooo) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp]: And for reasons I wrote in my other comment, I would remove the code comment here completely.

Comment (78andyp) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp]: Never seen those settings before!! - you are right - recently added albums then follow the same path - updated.
Comments removed as per above.

File: xbmc/PlayListPlayer.cpp [hunk 6]
```diff
@@ -986,7 +986,7 @@ void PLAYLIST::CPlayListPlayer::OnApplicationMessage(KODI::MESSAGING::ThreadMess
           }
           if (MUSIC::IsAudio(*item) || IsVideo(*item))
           {
-            // Check if sources are locked - to capture media played via json-rpc
+            // Check if sources are locked (eg. media played via json-rpc)
             if ((IsVideo(*item) && !g_passwordManager.IsVideoUnlocked()) ||
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/PlayListPlayer.cpp:989]: Sometimes I do think you are a pita!! But, I also get that you are trying to keep a massive codebase consistent and clean, and you know the code far better than I do, and everytime we chat like this I learn something - which is good!!

File: xbmc/PlayListPlayer.cpp [hunk 7]
```diff
@@ -984,7 +985,17 @@ void PLAYLIST::CPlayListPlayer::OnApplicationMessage(KODI::MESSAGING::ThreadMess
             return;
           }
           if (MUSIC::IsAudio(*item) || IsVideo(*item))
+          {
+            if ((IsVideo(*item) && !g_passwordManager.IsVideoUnlocked()) ||
```
Comment (ksooo) [inline xbmc/PlayListPlayer.cpp:989]: On more: Please take a look into implementation of IsVideo() and you will see that it is quite complex, thus expensive, cpu cycle wise. I suggest to calculate it only once and to store the result in a variable.

Comment (78andyp) [reply xbmc/PlayListPlayer.cpp:989]: I clearly have learnt something from you - I had just spotted that, thought the same thing and am fixing it now!

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp (hunk 2 above)
Comment (ksooo) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp]: The code you are trying to fix/improve is definitely a beast. I dealt with it earlier but I'm still far away from claiming for myself that I really understood all of it. ;-)

**Review by ksooo — COMMENTED** [review]
You see how "beautiful" the overall change now is? It is "symmetric", both fixed code parts do functionally the same,  which is a good sign for me.

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp (hunk 2 above)
Comment (howie-f) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp]: > The code you are trying to fix/improve is definitely a beast.

oh yeah, feels like profile manager is one big patchwork rug. i also had the pleasure

File: xbmc/PlayListPlayer.cpp [hunk 8]
```diff
@@ -983,8 +984,20 @@ void PLAYLIST::CPlayListPlayer::OnApplicationMessage(KODI::MESSAGING::ThreadMess
           {
             return;
           }
-          if (MUSIC::IsAudio(*item) || IsVideo(*item))
+          const bool isVideo{IsVideo(*item)};
```
Comment (howie-f) [inline xbmc/PlayListPlayer.cpp:987]: i guess it is `VIDEO::IsVideo` being called here

```suggestion
          const bool isVideo{VIDEO::IsVideo(*item)};
```

File: xbmc/GUIPassword.cpp [hunk 9]
```diff
@@ -479,6 +479,32 @@ bool CGUIPassword::CheckMenuLock(int iWindowID)
...
+
+  const bool isLocked{profileManager->GetCurrentProfile().musicLocked()};
+  if (!isLocked && !m_strMediaSourcePath.empty()) // check mediasource by path
+    return g_passwordManager.IsMediaPathUnlocked(profileManager, "music");
+
+  if (isLocked)
+    return IsMasterLockUnlocked(true); //Now let's check the PW if we need!
+  return true;
+}
+
```
Comment (howie-f) [inline xbmc/GUIPassword.cpp:507]: this looks hardly like code duplication.
can we introduce a member `bool CGUIPassword::IsMediaUnlocked(const std::string& mediaType)` ?
instead of `MusicUnlocked()` and `VideoUnlocked()` .... then call it like `IsMediaUnlocked(MediaTypeVideo)` ?

**Review by howie-f — COMMENTED** [review]
sorry it took me a while and i still haven't runtime tested. thanks @ksooo for jumping in. i have few suggestions

File: xbmc/GUIPassword.cpp (hunk 9 above)
Comment (78andyp) [reply xbmc/GUIPassword.cpp:507]: > this looks hardly like code duplication. can we introduce a member `bool CGUIPassword::IsMediaUnlocked(const std::string& mediaType)` ? instead of `MusicUnlocked()` and `VideoUnlocked()` .... then call it like `IsMediaUnlocked(MediaTypeVideo)` ?

Not sure that would save much code - still need to know if video or music as `.videoLocked()` or `.musicLocked()` as well as passing `"music"` or `"video"` to `IsMediaPathUnlocked()`

Comment (howie-f) [reply xbmc/GUIPassword.cpp:507]: right, and you don't have to. was only a suggestion ;)

Comment (78andyp) [reply xbmc/GUIPassword.cpp:507]: > right, and you don't have to. was only a suggestion ;)

Thanks, always appreciated :) Will make the other change to make it clearer.

File: xbmc/PlayListPlayer.cpp (hunk 8 above)
Comment (78andyp) [reply xbmc/PlayListPlayer.cpp]: Done

**Review by howie-f — APPROVED** [review]
i have to admit it is not trivial to include the json-rpc interface also.
for example you can use official ios remote, browse your library in the remote control app and happily play your (locked) media from there.

i'll still approve since it fixes one more hole in ProfileManager.
will adjust the pr description accordingly, thanks for your work on this

**Comment by 78andyp** [comment]
> i have to admit it is not trivial to include the json-rpc interface also. for example you can use official ios remote, browse your library in the remote control app and happily play your (locked) media from there.
> 
> i'll still approve since it fixes one more hole in ProfileManager. will adjust the pr description accordingly, thanks for your work on this

Thanks. I don't have any ios devices currently so I can't easily test that, sorry.
