### PR TITLE
Improving/fixing transparent control rendering

### LINKED ISSUE #21615: PR-21387 breaks grouplist position when using conditional fade animations
### Describe the bug
Here is a clear and concise description of what the problem is:

The PR https://github.com/xbmc/xbmc/pull/21387 breaks conditional fade animations because it sets visibility to false. 

This negatively impacts grouplist positioning because it is no longer possible to use a conditional fade to make an element transparent without changing its visibility.

This has two major implications for skins

1. The element no longer occupies space in the grouplist and the grouplist rubberbands and contracts to fill the space
2. When a list container visibility is set to false it no longer updates. If a skin uses a conditional fade to hide a container when `Container(ID).IsUpdating | Integer.IsEqual(Container(ID).NumItems,0)` and display a busy spinner instead, then the container will never update because it is never "visible" due to the fade animation.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should be possible to use a conditional fade animation such as below to make an element transparent on screen but still have the element be considered "visible" so that it continues to update and occupies space in the grouplist.

```
<animation effect="fade" start="100" end="0" condition="true">Conditonal</animation>
```

Only elements with visibility explicitly set to false should no longer occupy the space defined and no longer update.

## Actual Behavior

When using a conditional fade element the visibility is set to false, so the element no longer occupies space in the grouplist. This causes the grouplist to rubberband and contract rather than retaining its spacing. It also causes the container to never update.

## Possible Fix

Revert 21387 because opacity should not define element visibility in terms of spacing or updating. Controls are often used as spacers and can have 0% opacity but still need to be "visible" in terms of spacing and updating.

### To Reproduce
Apply this diff to Estuary (I'm using inprogress tvshows widget as the example so you might need to change the fadecondition System.IDleTime param to a different widget if you don't have in-progress shows) and then wait 2 seconds for IdleTime to kick in

```diff
diff --git a/xml/Home.xml b/xml/Home.xml
index 4192e93..8b8fde2 100644
--- a/xml/Home.xml
+++ b/xml/Home.xml
@@ -131,6 +131,7 @@
 							<param name="widget_header" value="$LOCALIZE[626]"/>
 							<param name="widget_target" value="videos"/>
 							<param name="list_id" value="6100"/>
+							<param name="fadecondition">System.IdleTime(2)</param>
 						</include>
 						<include content="WidgetListEpisodes" condition="Library.HasContent(tvshows)">
 							<param name="content_path" value="special://skin/playlists/recent_unwatched_episodes.xsp"/>
diff --git a/xml/Includes_Home.xml b/xml/Includes_Home.xml
index c420530..f6e8383 100644
--- a/xml/Includes_Home.xml
+++ b/xml/Includes_Home.xml
@@ -26,6 +26,7 @@
 		</definition>
 	</include>
 	<include name="WidgetListPoster">
+		<param name="fadecondition">false</param>
 		<definition>
 			<include content="CategoryLabel">
 				<param name="label">$PARAM[widget_header]</param>
@@ -39,6 +40,7 @@
 				<left>0</left>
 				<top>115</top>
 				<visible>Integer.IsGreater(Container($PARAM[list_id]).NumItems,0) | Container($PARAM[list_id]).IsUpdating</visible>
+				<animation effect="fade" start="100" end="0" time="1000" condition="$PARAM[fadecondition]">Conditional</animation>
 				<right>0</right>
 				<height>503</height>
 				<include content="WidgetListCommon">

```

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/9002263/kodi.log)

Log not really relevant. Screenshots below and diff will demonstrate the issue.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Here is what happens when the fade animation kicks in. The list loses its position and the other elements contract around it. The list never reloads.
Honeyview_screenshot00135

What should happen is the element retains its "visible" state but can no longer be seen. I've used 10% opacity to demonstrate but in actual use it would be 0% and not rendered but still occupying this space.

Honeyview_screenshot00136

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Nexus Nightly (anything from 7th June onwards).

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #21664: Slide-in screen navigation behaviour bug after Alpha 1
### Describe the bug

I have noticed a bug in the slide-in window behaviour (default skin) somewhere after Alpha 1, and reproducible in Alpha 2. When navigating to the Settings screen and returning to the main Movie/TV screens, the slide-in animation is no longer smooth, and just cuts off, leaving a jarring effect. This only happens when going from Settings->Movie/TV, and not the other way around, or between Movie/TV screens. Please see videos attached showing the issue.

## Expected Behavior

The screen slide-in behaviour should be smooth between windows.

## Actual Behavior

Screen slide-in is not smooth (see attached video clips).

### To Reproduce

1. Install Alpha 2.
2. Navigate between Settings window and Movie/TV windows.
3. Note jarring effect, where slide-in is not smooth.

### Debuglog

The debuglog can be found here:
[kodi.old.log](https://github.com/xbmc/xbmc/files/9077358/kodi.old.log)

### Screenshots 
Here are some links or screenshots to help explain the problem. I don't know how to insert video inline, so attaching the links here.

Alpha 1 and prior correct slide-in behaviour:
[https://drive.google.com/file/d/1UcICpdbn80J2qUZOKFTxh5wcCy2s3Uh-/view?usp=sharing](url)

Alpha 2 incorrect behaviour:
[https://drive.google.com/file/d/1W_Te6SZzwjPWIgAEU2ENokxAaHriBhDp/view?usp=sharing](url)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows 10 x64 21H2
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 20 Alpha 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by sarbes**
## Description
https://github.com/xbmc/xbmc/pull/21387 introduced focusing issues with skins. Originally, it was intended to avoid rendering/processing chunks of the GUI nodes which are transparent.

This PR limits the the scope of this to the actual rendering and dirty regions. 

## Motivation and context
See https://github.com/xbmc/xbmc/issues/21615 for details.

## How has this been tested?
Renderdoc shows the regions rendered with now change to the previous PR.

Also, I can't see any apparent issues.

For further testing, I'll provide a test build.

## What is the effect on users?
Undoes some skin breakage.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/guilib/GUIControl.h [hunk 1]
```diff
@@ -370,6 +371,7 @@ class CGUIControl
   float m_stereo;
   TransformMatrix m_transform;
   TransformMatrix m_cachedTransform; // Contains the absolute transform the control
+  bool m_isTransparent;
```
Comment (garbear) [inline xbmc/guilib/GUIControl.h:374]:
```c++
bool m_isTransparent{true};
```

and the constructors could be unmodified.

**Comment by garbear** [comment]
The logic looks technically correct. I don't like how we pass behavior as an optional param. Behavior should fully depend on params and state. That's an example of why our style guide recommends against optional parameters. I think if you do exactly this but with no optional params it'll be in a completed state.

File: xbmc/guilib/GUIControl.cpp [hunk 2]
```diff
@@ -472,8 +482,11 @@ float CGUIControl::GetHeight() const
   return m_height;
 }
 
-void CGUIControl::MarkDirtyRegion(const unsigned int dirtyState)
+void CGUIControl::MarkDirtyRegion(const unsigned int dirtyState, bool checkTransparency)
```
Comment (enen92) [inline xbmc/guilib/GUIControl.cpp:485]: is the new argument and the bail really required? I'd say that if you set the control dirty on process (after deciding on the transparency) you simply mark it as dirty and go with it

Comment (sarbes) [reply xbmc/guilib/GUIControl.cpp:485]: The bail is required, but the argument is not.

If the element is invisible, we don't want a dirty region to appear unnecessarily. If it comes to life after the animation, it still can be marked as dirty.

If a state change occurs from opaque to transparent, it should not set to be dirty (it was a bit late when I wrote this). And there lies a tiny flaw with this implementation, as it would still happen regardless. The surface might be marked as dirty before the animation says it is not visible. But this just creates a one frame "lag" in some special cases, which is not critical in my eyes.

File: xbmc/guilib/GUIControl.h (hunk 1 above)
Comment (sarbes) [reply xbmc/guilib/GUIControl.h:374]: I could compare the alpha of the cached transform each time to eliminate the bool. But thinking a bit more about the matter, I should rename it to m_isCulled. Then can also be used to signal if the element has been translated off screen by the animation.

From my understanding, we have three phases for controls.
1) Setup phase. Controls can be manipulated (by SetPosition() or similar) . That's done once on window load but might vary by the use of scripts.
2) Processing phase. Animations are calculated here. Dirty regions are also set here.
3) Rendering phase.

In phase 1, we don't know if the element is being rejected after the animation. So we have two options:
A) Don't mark it as dirty in phase 1 if it was not drawn in the last frame. If the state changes to true after the animation, it has to be marked as dirty in any case.
B) Mark it as being potentially dirty in phase 1 and do the actual marking via MarkDirtyRegion() in phase 2 after the animation.

I've gone with A, as it is the least invasive option. B would be technically correct, but would require more changes. Testing this would be a nightmare, as the whole dirty region rendering is a mess. In the end, B would only save a dirty region for one frame in case the control gets marked dirty in phase 1 but the animation rejects it at phase 2.

Comment (sarbes) [reply xbmc/guilib/GUIControl.h:374]: Having an invalid initial state would result in the element being marked as dirty the first time after its creation, even if the animation might cull it.

Comment (garbear) [reply xbmc/guilib/GUIControl.h]: It seems like both A and B have downsides. Feel free to merge solution A with solution B as a "follow-up" (which may never be completed but will at least document how things should be)

**Comment by jurialmunkey** [comment]
I built a WIN64 testbuild yesterday and just confirming that everything appears to be working properly from the skin side of things now (as expected since the visible check isn't being touched anymore). The build was done slightly before these latest changes went in but I would assume those don't change much if anything on the skin side. Just ping me if you want me to do another test when ready to merge.

**Comment by sarbes** [comment]
Thanks, but we only have to nail down the dirty regions issue. This opens a whole other can of worms...

File: xbmc/guilib/GUIControl.cpp [hunk 3]
```diff
@@ -125,6 +125,18 @@ void CGUIControl::DoProcess(unsigned int currentTime, CDirtyRegionList &dirtyreg
   if (Animate(currentTime))
     MarkDirtyRegion();
 
+  // if the control changed culling state from true tto false, mark it
```
Comment (enen92) [inline xbmc/guilib/GUIControl.cpp:128]:
```suggestion
  // if the control changed culling state from true to false, mark it
```

File: xbmc/guilib/GUIControl.cpp [hunk 4]
```diff
@@ -125,6 +125,18 @@ void CGUIControl::DoProcess(unsigned int currentTime, CDirtyRegionList &dirtyreg
...
+  const bool culled = m_transform.alpha <= 0.01f;
+  if (m_isCulled && !culled)
```
Comment (enen92) [inline xbmc/guilib/GUIControl.cpp:130]: can be simplified:

```suggestion
  if (m_isCulled && !culled)
  {
    MarkDirtyRegion();
  }
  m_isCulled = culled;
```

**Review by enen92 — COMMENTED** [review]
Just some minors. After those adjustments it's good to go I think.
Thanks for fixing this

File: xbmc/guilib/GUIControl.cpp (hunk 4 above)
Comment (sarbes) [reply xbmc/guilib/GUIControl.cpp:130]: No, it can't be simplified. If m_isCulled is true, MarkDirtyRegion() bails.

Should I add a new function MarkDirtyRegionIgnoreCulling() to make it clearer?

Also, it should mark both transitions as dirty (e.g. `m_isCulled != culled`).

Comment (enen92) [reply xbmc/guilib/GUIControl.cpp:130]: I mean you don't need the if/else check as you'll be updating m_isCulled regardless of it being false or true, afaics. Snippet I posted is exactly identical to yours.

Comment (enen92) [reply xbmc/guilib/GUIControl.cpp:130]: Nvm, I see what you mean now

**Review by garbear — APPROVED** [review]
I'm happy with the updated PR

**Review by enen92 — APPROVED** [review]
Can you apply clang-format changes (if they still apply) and squash the commits for merging?
Thanks for fixing this

**Review by howie-f — APPROVED** [review]
fixes the skin issues i noticed. thanks

**Comment by howie-f** [comment]
ping @sarbes do you have time to format and squash? otherwise i‘d take on that task

File: xbmc/guilib/GUIControl.cpp (hunk 3 above)
Comment (sarbes) [reply xbmc/guilib/GUIControl.cpp]: Done.

**Review by enen92 — APPROVED** [review]
