### PR TITLE
[Video] Folder Stacks

### LINKED ISSUE #16109: DVD Folder Stacking Broken
### Describe the bug
DVD Folder Stacking is broken.

Using the naming convention, such as "d:\movies\Gettysburg (1993) dvd1" and "d:\movies\Gettysburg (1993) dvd2", it will add these to as Videos with no information to the library (they will be listed as "video"), and will not correctly stacked.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

DVD Folder Stacking to work correctly.

## Actual Behavior

DVD Folders labeled dvd1 and dvd2 are added with placeholder metadata, and have to be manually edited, but can never be stacked.

## Possible Fix

I've looked at the code, and it appears that FileItem.StackFolders correctly identifies patterns, but it appears it does nothing does nothing with the data. 

It also appears that FileItem.StackFiles correctly handles ISO files such as d:\movies\Gettysburg (1993) dvd1.iso and d:\movies\Gettysburg (1993) dvd2.iso.

**What isn't clear** 

- **shoud StackFolders should do something with the stack, or does it expects StackFiles to do something to complete the stacking?**

- Stack Files uses regular expressions that expect a 4 part <title> <Volume> <Ignore period> <Extension>, and it uses the m_videoStackRegExps, not the m_folderStackRegExps that StackFolders uses. When it gets to the regular expression parsing, it looks at the video_ts.ifo file, and splits up the name as VI,  D, EO_TS, IFO, and not "Gettysburg (1993) 2", because it is looking at the file name, not the folder the file is in. 

It appears that if you change file1 and file2 in StackFiles to FilePath1 and FilePath2, that this could fix the problem, but it would likely break ISO stacking.

In looking through the history of this file, it looks like mkortstiege initially made significant changes to this, and would be a good candidate to know/understand what the intent of StackFolders and StackFiles is?

### To Reproduce

1. in a folder that your library has, make two copies of any dvd folder
2. rename the dvd folder as Movie (2019) dvd1 and another folder as Movie (2019) dvd2
2. start kodi and go to your movies and run update library.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Folder stacks are useful for those who have ISOs or DVD/Bluray folders.
They are currently broken.

There were several issues found, some of which have been fixed already:
- the code to generate folder stacks (`stack://`) was incomplete.
- folder stacks were then not recognised at various points in the play pathway (initially, transitioning from one item to another etc..)
- playing a stack from the main menu (not movie menu) was also broken (fixed in #24820)
- correct length of combined disc stack and streamdetails not saved correctly and not shown in bottom right (fixed in #27176).
- routine to determine potential NFO/art path was broken
- one of the regexs for file stacks was to relaxed (see discussion in comments of #24794)

## Motivation and context

Fixes #16109.

## How has this been tested?

Only locally currently.
With DVD/ISO/Bluray folders.
Also checked file stacks and individual DVD/Bluray/ISOs still play.

## What is the effect on users?

First some terminology:
FILE stack - means all the files in the stack are in the same folder.

FOLDER stack - means all the files of the stack are in different folders that are named to match a regex (see examples below).

REGULAR stack - consists of discrete media objects (eg. mkv) files - these could be a file stack (ie. all mkv files in one folder) or a folder stack (ie. a single mkv file in each directory, named as per regex - examples below). This can include bluray:// paths that resolve to a .mpls as that is a single playable discrete media object.

DISC stack - at least one part of the stack refers to a media object that has not yet been resolved (ie. an ISO/BDMV folder/VIDEO_TS folder where the title/playlist has not yet been chosen). This is most likely to be a folder stack (as per the examples below) but could be a file stack with multiple ISO files in the folder.

**Example 1 - Blurays**

Using the following directory structure:
```
├───The Lord of the Rings The Return of the King (2003) - Part 1
├───The Lord of the Rings The Return of the King (2003) - Part 2
│   ├───BDMV
│   └───CERTIFICATE
└───The Lord of the Rings The Return of the King (2003) - Part 3
```
Notes:
For folder stacks the FOLDER naming is important (as this is where the movie name is derived from) not the FILE naming.
In this case I'm using three different movies just so the transitions are obvious (Part 1 is Battle of Britian, Part 2 is Sunshine, Part 3 is Patriots Day)
There can only be one media file per folder/folder structure (ISO, index.bdmv, video_ts.ifo)

So this is a FOLDER stack forming a DISC stack.

In the database we have:
`stack://D:\Local Tests\Stacks\The Lord of the Rings The Return of the King (2003) - Part 1\BATTLE_OF_BRITAIN_F1.iso , D:\Local Tests\Stacks\The Lord of the Rings The Return of the King (2003) - Part 2\BDMV\index.bdmv , D:\Local Tests\Stacks\The Lord of the Rings The Return of the King (2003) - Part 3\PATRIOTS_DAY_BD.iso`

Note again the file names don't matter in this folder stack.

Initally, as with all discs the library just shows the information derived from the scraper.
image

Starting playing you are presented with the simple menu as normal. Whilst playing the first part the bar at the bottom just reflects the first part:
image

When the end of part 1 is reached the simple menu asks you to select the playlist for part 2. After that the bottom bar reflects both part 1 and 2 - the following is just after part 2 starts. You can move back and forth between both parts like a file stack, but you cannot yet move forward to part 3 as the playlist hasn't been selected yet.
image

Moving backwards:
image

If you stop DURING a part then, in the library, the media information at the bottom shows the total time of played parts and the progress bar reflects progress over the total known parts (in this case we've stopped after the picture above).
image

If you stop at the END of a part then the progress bar displays progress in term of parts (in this case we've stopped at the end of part 2 so the progress bar is 2/3rds of the way across):
image

Now playing the final part:
image

Part way through the final part:
image

And the library display is updated:
image

The stack has now been fully resolved (from the database):
`stack://bluray://udf%3a%2f%2fD%253a%255cLocal%2520Tests%255cStacks%255cThe%2520Lord%2520of%2520the%2520Rings%2520The%2520Return%2520of%2520the%2520King%2520(2003)%2520-%2520Part%25201%255cBATTLE_OF_BRITAIN_F1.iso%2f/BDMV/PLAYLIST/00000.mpls , bluray://D%3a%5cLocal%20Tests%5cStacks%5cThe%20Lord%20of%20the%20Rings%20The%20Return%20of%20the%20King%20(2003)%20-%20Part%202%5c/BDMV/PLAYLIST/00800.mpls , bluray://udf%3a%2f%2fD%253a%255cLocal%2520Tests%255cStacks%255cThe%2520Lord%2520of%2520the%2520Rings%2520The%2520Return%2520of%2520the%2520King%2520(2003)%2520-%2520Part%25203%255cPATRIOTS_DAY_BD.iso%2f/BDMV/PLAYLIST/00869.mpls`

From now on it will behave exactly like a regular stack - ie you can move back and forth between all parts during playback.

Resuming shows you the part you are in:
image

In effect the disc stack transforms into a regular stack once each part's playlist is chosen. It is now a FOLDER stack forming a REGULAR stack.

**Example 2 - DVDs**

Difference with DVDs. As the dvd:// vfs hasn't been implimented yet all of these are played through the menu as discrete media entities.

```
├───The Lord of the Rings Fellowship of the Ring (2001) - DVD1
│   └───VIDEO_TS
└───The Lord of the Rings Fellowship of the Ring (2001) - DVD2
```
There is a DVD ISO in the DVD2 folder. Again two different movies are used for illustration.

It is a FOLDER stack forming a DISC stack.

In the database it is:
`stack://D:\Local Tests\Stacks\The Lord of the Rings Fellowship of the Ring (2001) - DVD1\VIDEO_TS\VIDEO_TS.IFO , D:\Local Tests\Stacks\The Lord of the Rings Fellowship of the Ring (2001) - DVD2\ULTIMATE_AVENGERS.iso`

Again, as this is a folder stack, the file names don't matter.

Playing part 1 (DVD1) - the DVD menu is played and the main movie selected.
image
The progress bar is just for part 1

When part 1 finishes and returns to the menu you press stop and part 2 starts, again playing to the menu. Once the main title is played:
image
The progress bar is just for part 2.

But progress is shown for the entire stack, and the total time at the bottom right reflects the entire stack, in the library.
image

As there is yet no dvd:// vfs to record the title played it remains a DISC stack and the stack:// path in the database remains unchanged.

## Types of change

- [X] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] All new and existing tests passed

### CODE REVIEW

File: xbmc/video/VideoUtils.cpp [hunk 1]
```diff
@@ -189,61 +191,30 @@ std::tuple<int64_t, unsigned int> GetStackResumeOffsetAndPartNumber(const CFileI
...
-                break;
-              }
-            }
-          }
-        }
+        auto index{std::ranges::distance(
+            std::ranges::find_if(times | std::views::reverse, [offset](auto t)
+                                 { return t <= std::chrono::milliseconds(offset); }),
+            times.rend())};
+        if (index < static_cast<int>(times.size()))
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/video/VideoUtils.cpp]: OK

File: xbmc/application/Application.cpp [hunk 2]
```diff
@@ -2503,6 +2486,51 @@ bool CApplication::PlayFile(CFileItem item, const std::string& player, bool bRes
...
+        tinyxml2::XMLHandle hRoot(xmlDoc.RootElement());
+        if (hRoot.ToElement() && StringUtils::EqualsNoCase(hRoot.ToElement()->Value(), "nextpart"))
+        {
+          int nextItem;
+          std::from_chars(hRoot.ToElement()->GetText(),
+                          hRoot.ToElement()->GetText() + std::strlen(hRoot.ToElement()->GetText()),
+                          nextItem);
+          item = stackHelper->SetStackPartCurrentFileItem(nextItem);
+          stackSet = true;
+          options.startpercent = options.starttime = 0;
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/application/Application.cpp]: <nextpart> is always written with a number. It's not a user modifiable field.

File: xbmc/video/VideoDatabase.cpp [hunk 3]
```diff
@@ -6081,17 +6075,17 @@ bool CVideoDatabase::GetStackTimes(const std::string &filePath, std::vector<uint
...
     if (m_pDS->num_rows() > 0)
     { // get the video settings info
-      uint64_t timeTotal = 0;
+      std::chrono::milliseconds timeTotal{0ms};
       std::vector<std::string> timeString = StringUtils::Split(m_pDS->fv("times").get_asString(), ",");
       times.clear();
       for (const auto &i : timeString)
       {
-        const auto partTime = static_cast<uint64_t>(atof(i.c_str()) * 1000.0);
+        const std::chrono::milliseconds partTime{static_cast<long long>(std::stod(i) * 1000.0)};
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/video/VideoDatabase.cpp]: Needed as i is in seconds with a decimal point

File: xbmc/filesystem/StackDirectory.cpp [hunk 4]
```diff
@@ -229,5 +231,60 @@ namespace XFILE
...
+        {
+          URIUtils::RemoveSlashAtEnd(path);
+          if (first)
+            path = URIUtils::GetDiscBasePath(path);
+          else
+            path = URIUtils::GetParentPath(path);
+        }
+        first = false;
+      } while (std::ranges::adjacent_find(paths, std::not_equal_to<>()) != paths.end());
+    }
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/filesystem/StackDirectory.cpp]: If paths is empty then GetPaths return false.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 5]
```diff
@@ -1390,6 +1391,29 @@ void CVideoPlayer::Prepare()
   if (!discStateRestored)
     OpenDefaultStreams();
 
+  auto& components{CServiceBroker::GetAppComponents()};
+  const auto& stackHelper{components.GetComponent<CApplicationStackHelper>()};
+  if (stackHelper->GetRegisteredStack(fileItem) != nullptr)
+  {
+    if (stackHelper->GetRegisteredStackPartNumber(fileItem) >= stackHelper->GetKnownStackParts())
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp]: Nope - Only called at beginning of playback and GetKnownStackParts() is only called once.

**Comment by 78andyp** [comment]
Jenkins build this please.

**Comment by 78andyp** [comment]
Jenkins build this please

File: xbmc/application/ApplicationPlayerCallback.cpp [hunk 6]
```diff
@@ -159,68 +161,151 @@ void CApplicationPlayerCallback::OnPlayerCloseFile(const CFileItem& file,
...
+          // Update stack (for bookmark and % played)
+          stackHelper->SetStackPartStartTimeMs(file, startPartTime);
+          stackHelper->SetStackTotalTimeMs(file, totalTime);
+
+          // If adding part then update streamdetails as well
+          fileItem.GetVideoInfoTag()->m_streamDetails = file.GetVideoInfoTag()->m_streamDetails;
+
+          // Also update video info tag with total time of the stack (as this is read for the library display)
+          fileItem.GetVideoInfoTag()->m_streamDetails.SetVideoDuration(
+              0, static_cast<int>(totalTime.count()) / 1000);
```
Comment (garbear) [inline xbmc/application/ApplicationPlayerCallback.cpp]: Magic constant alert. The reader can't see time units for this line.

Comment (garbear) [reply xbmc/application/ApplicationPlayerCallback.cpp]: Probably use a std::chrono duration cast, then convert to int

Comment (78andyp) [reply xbmc/application/ApplicationPlayerCallback.cpp]: Thanks

**Comment by 78andyp** [comment]
@claude, review, thanks.

**Comment by 78andyp** [comment]
@claude, please review. Please check your previous comments as some are no longer relevant (code removed etc..)

File: xbmc/application/Application.cpp [hunk 7]
```diff
@@ -2321,13 +2322,12 @@ bool CApplication::PlayFile(CFileItem item, const std::string& player, bool bRes
...
   }
 
-  using enum CApplicationPlay::GatherPlaybackDetailsResult;
-
   CApplicationPlay appPlay{*stackHelper};
   const auto result{appPlay.GatherPlaybackDetails(item, player, bRestart)};
+  using enum CApplicationPlay::GatherPlaybackDetailsResult;
   if (result == RESULT_ERROR)
     return false;
-  else if (result == RESULT_NO_PLAYLIST_SELECTED)
```
Comment (ksooo) [inline xbmc/application/Application.cpp:2002]: Why this change? Using „else“ is correct and has no downsides. With your change future code changes here could lead to checking result twice needlessly.

**Comment by 78andyp** [comment]
@claude, review.

**Comment by 78andyp** [comment]
Hi @damienruscoe,

I've rewritten CStackDirectory and created a custom GetParentPath().

I'm struggling with JSON test 347 - `stack://user:pass@host:88888/`

I don't think this is valid - `stack://` is not a protocol per se, just a container for multiple (although there's no reason one should not work) other paths.

I'm not sure the element `user:pass@host:88888/` is valid in its own right - shouldn't it be something like `stack://file://user:pass@host:88888/` (properly encoded)??

**Comment by damienruscoe** [comment]
@78andyp  
> I'm struggling with JSON test 347 - `stack://user:pass@host:88888/`
>
> I'm not sure the element `user:pass@host:88888/` is valid in its own right - shouldn't it be something like `stack://file://user:pass@host:88888/` (properly encoded)??

The tests were assembled to ensure that I didnt inadventantly change the behavour when refactoring. `multipath` and `stack` protocols were both __special__ protocols which I was concerned about.

You're completly fine to change any of these tests when you are modifying the code as they were meant to be regression tests. They are meant to bring up these questions to the developer when things change.

You are the authority over me in the area of `stack://` and DVD/Bluray. It appears to me that user/pass dont belong with this protocol if they are only used when referencing iso files.

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@claude review.

**Comment by 78andyp** [comment]
@claude review.

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@claude review code and specifically comment if the issues recently pointed out by github-actions have been fixed.

File: xbmc/application/ApplicationStackHelper.cpp [hunk 8]
```diff
@@ -10,326 +10,526 @@
...
+  options.fullscreen =
+      CServiceBroker::GetSettingsComponent()->GetAdvancedSettings()->m_fullScreenOnMovieStart &&
+      !CMediaSettings::GetInstance().DoesMediaStartWindowed();
+}
+
+bool CApplicationStackHelper::UpdateDiscStackAndTimes(const CFileItem& playedFile)
+{
+  // Build stacktimes for disc image stacks after each disc is played
+  // Assumes the stack dynpaths have already been updated
+  if (m_stackMap.empty())
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/application/ApplicationStackHelper.cpp:225]: Fixed

File: xbmc/application/ApplicationStackHelper.cpp [hunk 9]
```diff
@@ -10,326 +10,526 @@
...
   }
   return 0;
 }
 
-void CApplicationStackHelper::ClearAllRegisteredStackInformation()
+std::shared_ptr<const CFileItem> CApplicationStackHelper::GetStack(const CFileItem& item) const
 {
-  m_stackmap.clear();
+
+  return GetStackPartInformation(item)->stackItem;
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/application/ApplicationStackHelper.cpp]: Done

File: xbmc/application/ApplicationStackHelper.cpp [hunk 10]
```diff
@@ -10,326 +10,526 @@
...
+
+CFileItem& CApplicationStackHelper::GetCurrentStackPart() const
+{
+  return *m_originalStackItems.Get(m_currentStackPosition);
+}
+
+std::chrono::milliseconds CApplicationStackHelper::GetStackPartEndTime(int partNumber) const
+{
+  return std::chrono::milliseconds(
+      GetStackPartInformation(m_stackPaths[partNumber])->stackItem->GetEndOffset());
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/application/ApplicationStackHelper.cpp]: Done

File: xbmc/application/ApplicationStackHelper.h [hunk 11]
```diff
@@ -8,208 +8,290 @@
...
-  const CFileItem& GetStackPartFileItem(int partNumber) const;
+  bool IsSeekingParts() const { return m_seekingParts; }
+
+  /*!
+  \brief Flag if currently seeking between parts
+  \param seeking true if currently seeking between parts, false if not
+  */
+  void SetSeekingParts(bool seeking) { m_seekingParts = seeking; }
+
+  CCriticalSection m_critSection;
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/application/ApplicationStackHelper.h]: Done

File: xbmc/FileItemList.cpp [hunk 12]
```diff
@@ -672,259 +699,166 @@ void CFileItemList::Stack(bool stackFiles /* = true */)
...
+        if (regExp.RegFind(file) == -1)
+          continue;
+
+        // Get components of file name
+        stackCandidates.emplace_back(
+            StackCandidate{.type = StackCandidateType::FILE_CANDIDATE,
+                           .title = regExp.GetMatch(1),
+                           .volume = regExp.GetMatch(2),
+                           .size = item->GetSize(),
+                           .index = static_cast<int>(&item - m_items.data())});
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/FileItemList.cpp]: Done

File: xbmc/FileItemList.cpp [hunk 13]
```diff
@@ -672,259 +699,166 @@ void CFileItemList::Stack(bool stackFiles /* = true */)
...
-        while (!bMatch && expr != folderRegExps.end())
+        bool fileFound{true};
+        if (item->IsFolder())
         {
-          //CLog::LogF(LOGDEBUG,"Running expression {} on {}", expr->GetPattern(), item->GetLabel());
-          bMatch = (expr->RegFind(item->GetLabel().c_str()) != -1);
-          if (bMatch)
+          // Look for media files in the folder
+          CFileItemList items;
+          CDirectory::GetDirectory(item->GetPath(), items,
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/FileItemList.cpp]: Done

File: xbmc/application/ApplicationStackHelper.cpp [hunk 14]
```diff
@@ -10,326 +10,526 @@
...
     }
   }
   return 0;
 }
 
-void CApplicationStackHelper::ClearAllRegisteredStackInformation()
+std::shared_ptr<const CFileItem> CApplicationStackHelper::GetStack(const CFileItem& item) const
 {
-  m_stackmap.clear();
+
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/application/ApplicationStackHelper.cpp]: Done

File: xbmc/video/guilib/VideoGUIUtils.cpp [hunk 15]
```diff
@@ -659,23 +659,25 @@ std::string GetResumeString(const CFileItem& item)
...
-      const std::string partString{StringUtils::Format(g_localizeStrings.Get(23051), partNumber)};
-      resumeString += " (" + partString + ")";
-    }
-    return resumeString;
+                                         TIME_FORMAT_HH_MM_SS)); // Resume from ##:##:##
   }
   else
   {
-    return g_localizeStrings.Get(13362); // Continue watching
+    resumeString = g_localizeStrings.Get(12023); // Resume from
```
Comment (ksooo) [inline xbmc/video/guilib/VideoGUIUtils.cpp]: Why this change in wording? "Continue watching" is used for example in context menu of a folder containing episodes of a tv show which are partially watched. There is no "from" a certain episode available for these folders. Or have you changed that?

File: xbmc/video/guilib/VideoGUIUtils.cpp [hunk 16]
```diff
@@ -659,23 +659,25 @@ std::string GetResumeString(const CFileItem& item)
...
+  }
+  if (partNumber > 0)
+  {
+    const std::string partString{
+        StringUtils::Format(g_localizeStrings.Get(23051), partNumber)}; // Part #
+    resumeString += startOffset > 0 ? " (" + partString + ")" : " " + partString;
   }
+  return resumeString;
```
Comment (ksooo) [inline xbmc/video/guilib/VideoGUIUtils.cpp:682]: If startOffset <= 0 and partNumber <= 0 now "Resume from" (without a part) will be returned which is wrong. Should be "Continue watching" like before.

**Review by ksooo — DISMISSED** [review]

File: xbmc/video/guilib/VideoGUIUtils.cpp (hunk 15 above)
Comment (78andyp) [reply xbmc/video/guilib/VideoGUIUtils.cpp]: Because 'Continue with 05:03:54 (Part 3)' doesn't make as much sense to me as 'Resume from 05:03:54 (Part 3)'.
We also use the word resume in Settings -> Media -> Videos:
image

File: xbmc/application/Application.cpp (hunk 7 above)
Comment (78andyp) [reply xbmc/application/Application.cpp:2002]: OK will change.

File: xbmc/video/guilib/VideoGUIUtils.cpp (hunk 15 above)
Comment (ksooo) [reply xbmc/video/guilib/VideoGUIUtils.cpp]: > Because 'Continue with 05:03:54 (Part 3)' doesn't make as much sense to me

You miss the point here, @78andyp.  I'm not talking about `"Continue with <some-time-value>"`, but a static string "Continue watching" which happens for example in library view in the context menu of partially watched seasons. There, we currently have no info from where to continue, hence the static string. As I wrote, with your change we will end up with context menu entries  containing "Resume from" without any part number/time stamp. This needs to be fixed. See my other explanation below.

Comment (78andyp) [reply xbmc/video/guilib/VideoGUIUtils.cpp]: OK. I see.

File: xbmc/video/guilib/VideoGUIUtils.cpp (hunk 16 above)
Comment (78andyp) [reply xbmc/video/guilib/VideoGUIUtils.cpp:682]: OK

File: xbmc/application/ApplicationMessageHandling.cpp [hunk 17]
```diff
@@ -683,6 +691,7 @@ bool CApplicationMessageHandling::OnMessage(const CGUIMessage& message)
 
       if (!isEpgPlaylistItem)
       {
+
```
Comment (ksooo) [inline xbmc/application/ApplicationMessageHandling.cpp]: remove this empty line please

Comment (78andyp) [reply xbmc/application/ApplicationMessageHandling.cpp]: Done

**Comment by 78andyp** [comment]
@ksooo, thanks for the comments.

**Comment by 78andyp** [comment]
Final call for reviews.

**Comment by 78andyp** [comment]
Will merge tomorrow morning unless objections.

**Comment by 78andyp** [comment]
@claude - looking at the changes in xbmc/application/ApplicationMessageHandling.cpp and working back from there is there a reason that the next stack part would play automatically on a windows system but not on an android system??

**Comment by garbear** [comment]
Maybe claude can't comment on closed PRs? It looks like you can invoke claude from issues, so maybe ask in a new issue?
