### PR TITLE
Check settings for nullptr

### LINKED ISSUE #18657: segfault in CLibInputSettings after linux windowing reorg
segfault after pull request #18534 (git 8d9b4565)

```
gdb ./kodi-gbm
GNU gdb (Ubuntu 9.2-0ubuntu2) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./kodi-gbm...
(No debugging symbols found in ./kodi-gbm)
(gdb) run -fs --standalone --debug
Starting program: /home/xbmc/kodi-gbm -fs --standalone --debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff222c640 (LWP 7911)]
[New Thread 0x7ffff1a2b640 (LWP 7912)]
[New Thread 0x7ffff122a640 (LWP 7913)]

Thread 1 "kodi-gbm" received signal SIGSEGV, Segmentation fault.
0x000055555606d530 in CLibInputSettings::CLibInputSettings(CLibInputHandler*) ()
(gdb) quit
```

Here is a clear and concise description of what the problem is:

Current build (git @8d9b4565) causes segault on Linux+GBM+GLES

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Runs smoothly

## Actual Behavior

segfault

## Possible Fix

unknown

### To Reproduce

1. build kodi
2. run kodi
3. crash

### Debuglog

The debuglog can be found here:

```
2020-10-27 21:56:18.425 T:7938     INFO <general>: -----------------------------------------------------------------------
2020-10-27 21:56:18.425 T:7938     INFO <general>: Starting Kodi (19.0-ALPHA2 (18.9.702) Git:20201027-ac48ff40d0). Platform: Linux x86 64-bit
2020-10-27 21:56:18.425 T:7938     INFO <general>: Using Release Kodi x64
2020-10-27 21:56:18.425 T:7938     INFO <general>: Kodi compiled 2020-10-27 by GCC 10.2.0 for Linux x86 64-bit version 5.8.14 (329742)
2020-10-27 21:56:18.425 T:7938     INFO <general>: Running on Ubuntu 20.10, kernel: Linux x86 64-bit version 5.8.0-25-lowlatency
2020-10-27 21:56:18.425 T:7938     INFO <general>: FFmpeg version/source: 4.3.1-Kodi
2020-10-27 21:56:18.425 T:7938     INFO <general>: Host CPU: Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz, 4 cores available
2020-10-27 21:56:18.425 T:7938     INFO <general>: special://xbmc/ is mapped to: /usr/share/kodi
2020-10-27 21:56:18.425 T:7938     INFO <general>: special://xbmcbin/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi
2020-10-27 21:56:18.425 T:7938     INFO <general>: special://xbmcbinaddons/ is mapped to: /usr/lib/x86_64-linux-gnu/kodi/addons
2020-10-27 21:56:18.425 T:7938     INFO <general>: special://masterprofile/ is mapped to: /home/xbmc/.kodi/userdata
2020-10-27 21:56:18.425 T:7938     INFO <general>: special://envhome/ is mapped to: /home/xbmc
2020-10-27 21:56:18.425 T:7938     INFO <general>: special://home/ is mapped to: /home/xbmc/.kodi
2020-10-27 21:56:18.425 T:7938     INFO <general>: special://temp/ is mapped to: /home/xbmc/.kodi/temp
2020-10-27 21:56:18.425 T:7938     INFO <general>: special://logpath/ is mapped to: /home/xbmc/.kodi/temp
2020-10-27 21:56:18.425 T:7938     INFO <general>: The executable running is: /usr/lib/x86_64-linux-gnu/kodi/kodi-gbm
2020-10-27 21:56:18.425 T:7938     INFO <general>: Local hostname: xbmc
2020-10-27 21:56:18.425 T:7938     INFO <general>: Log File is located: /home/xbmc/.kodi/temp/kodi.log
2020-10-27 21:56:18.425 T:7938     INFO <general>: -----------------------------------------------------------------------
2020-10-27 21:56:18.425 T:7938     INFO <general>: loading settings
2020-10-27 21:56:18.425 T:7938     INFO <general>: special://profile/ is mapped to: special://masterprofile/
2020-10-27 21:56:18.431 T:7938     INFO <general>: No settings file to load (special://xbmc/system/advancedsettings.xml)
2020-10-27 21:56:18.431 T:7938     INFO <general>: No settings file to load (special://masterprofile/advancedsettings.xml)
2020-10-27 21:56:18.431 T:7938     INFO <general>: Default Video Player: VideoPlayer
2020-10-27 21:56:18.431 T:7938     INFO <general>: Default Audio Player: paplayer
2020-10-27 21:56:18.431 T:7938     INFO <general>: Disabled debug logging due to GUI setting. Level 1.
2020-10-27 21:56:18.431 T:7938     INFO <general>: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
2020-10-27 21:56:18.431 T:7938    DEBUG <general>: CMediaSourceSettings: <games> tag is missing or sources.xml is malformed
2020-10-27 21:56:18.431 T:7938    DEBUG <general>: CSkinSettings: no <skinsettings> tag found
2020-10-27 21:56:18.431 T:7938     INFO <general>: creating subdirectories
2020-10-27 21:56:18.431 T:7938     INFO <general>: userdata folder: special://masterprofile/
2020-10-27 21:56:18.431 T:7938     INFO <general>: recording folder:
2020-10-27 21:56:18.431 T:7938     INFO <general>: screenshots folder:
2020-10-27 21:56:18.691 T:7938     INFO <general>: PulseAudio: Server not running
2020-10-27 21:56:18.691 T:7942    DEBUG <general>: Thread Lirc start, auto delete: false
2020-10-27 21:56:18.692 T:7942     INFO <general>: Loading special://xbmc/system/Lircmap.xml
2020-10-27 21:56:18.692 T:7943    DEBUG <general>: Thread libinput start, auto delete: false
2020-10-27 21:56:18.692 T:7938     INFO <general>: Running database version Addons33
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'mceusb'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'XboxDVDDongle'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'Microsoft_Xbox'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'PinnacleSysPCTVRemote'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'anysee'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'iMON-PAD'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'Antec_Veris_RM200'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'MCE_via_iMON'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'TwinHanRemote'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'linux-input-layer'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Linking remote mapping for 'linux-input-layer' to 'cx23885_remote'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'mediacenter'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'devinput'
2020-10-27 21:56:18.693 T:7938    ERROR <general>: GetDirectory - Error getting /usr/lib/x86_64-linux-gnu/kodi/addons
2020-10-27 21:56:18.693 T:7938    ERROR <general>: GetDirectory - Error getting special://xbmcbin/addons
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'devinput-32'
2020-10-27 21:56:18.693 T:7942     INFO <general>: * Adding remote mapping for device 'devinput-64'
2020-10-27 21:56:18.693 T:7942    DEBUG <general>: CIRTranslator::Load - no userdata Lircmap.xml found, skipping
2020-10-27 21:56:18.696 T:7938    DEBUG <general>: CAddonInfoBuilder::ParseXMLTypes: Binary addon found: audioencoder.kodi.builtin.wma
2020-10-27 21:56:18.699 T:7938    DEBUG <general>: CAddonInfoBuilder::ParseXMLTypes: Binary addon found: audioencoder.kodi.builtin.aac
2020-10-27 21:56:18.700 T:7938    DEBUG <general>: CAddonInfoBuilder::ParseXMLTypes: Binary addon found: screensaver.xbmc.builtin.dim
2020-10-27 21:56:18.701 T:7938    DEBUG <general>: CAddonInfoBuilder::ParseXMLTypes: Binary addon found: screensaver.xbmc.builtin.black
2020-10-27 21:56:18.704 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.tvshows.themoviedb.org' already present with version 3.1.0 at '/usr/share/kodi/addons/metadata.tvshows.themoviedb.org/' replaced with version 3.5.5 at '/home/xbmc/.kodi/addons/metadata.tvshows.themoviedb.org/'
2020-10-27 21:56:18.704 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.common.imdb.com' already present with version 3.1.5 at '/usr/share/kodi/addons/metadata.common.imdb.com/' replaced with version 3.1.6 at '/home/xbmc/.kodi/addons/metadata.common.imdb.com/'
2020-10-27 21:56:18.704 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.themoviedb.org' already present with version 5.1.7 at '/usr/share/kodi/addons/metadata.themoviedb.org/' replaced with version 5.2.2 at '/home/xbmc/.kodi/addons/metadata.themoviedb.org/'
2020-10-27 21:56:18.705 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.common.theaudiodb.com' already present with version 2.0.3 at '/usr/share/kodi/addons/metadata.common.theaudiodb.com/' replaced with version 2.0.3 at '/home/xbmc/.kodi/addons/metadata.common.theaudiodb.com/'
2020-10-27 21:56:18.705 T:7938  WARNING <general>: CAddonMgr::FindAddons: Addon 'metadata.generic.artists' already present with higher version 1.0.14 at '/usr/share/kodi/addons/metadata.generic.artists/' - other version 1.0.12 at '/home/xbmc/.kodi/addons/metadata.generic.artists/' will be ignored
2020-10-27 21:56:18.705 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.common.themoviedb.org' already present with version 3.2.3 at '/usr/share/kodi/addons/metadata.common.themoviedb.org/' replaced with version 3.2.6 at '/home/xbmc/.kodi/addons/metadata.common.themoviedb.org/'
2020-10-27 21:56:18.705 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.common.allmusic.com' already present with version 3.2.2 at '/usr/share/kodi/addons/metadata.common.allmusic.com/' replaced with version 3.2.2 at '/home/xbmc/.kodi/addons/metadata.common.allmusic.com/'
2020-10-27 21:56:18.706 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.common.fanart.tv' already present with version 3.6.3 at '/usr/share/kodi/addons/metadata.common.fanart.tv/' replaced with version 3.6.3 at '/home/xbmc/.kodi/addons/metadata.common.fanart.tv/'
2020-10-27 21:56:18.706 T:7938  WARNING <general>: CAddonMgr::FindAddons: Addon 'metadata.generic.albums' already present with higher version 1.0.14 at '/usr/share/kodi/addons/metadata.generic.albums/' - other version 1.0.13 at '/home/xbmc/.kodi/addons/metadata.generic.albums/' will be ignored
2020-10-27 21:56:18.707 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.artists.universal' already present with version 4.3.3 at '/usr/share/kodi/addons/metadata.artists.universal/' replaced with version 4.3.3 at '/home/xbmc/.kodi/addons/metadata.artists.universal/'
2020-10-27 21:56:18.707 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.common.musicbrainz.org' already present with version 2.2.4 at '/usr/share/kodi/addons/metadata.common.musicbrainz.org/' replaced with version 2.2.4 at '/home/xbmc/.kodi/addons/metadata.common.musicbrainz.org/'
2020-10-27 21:56:18.707 T:7938  WARNING <general>: CAddonMgr::FindAddons: Addon 'game.controller.default' already present with higher version 1.0.9 at '/usr/share/kodi/addons/game.controller.default/' - other version 1.0.8 at '/home/xbmc/.kodi/addons/game.controller.default/' will be ignored
2020-10-27 21:56:18.707 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'service.xbmc.versioncheck' already present with version 0.5.9+matrix.1 at '/usr/share/kodi/addons/service.xbmc.versioncheck/' replaced with version 0.5.9+matrix.1 at '/home/xbmc/.kodi/addons/service.xbmc.versioncheck/'
2020-10-27 21:56:18.708 T:7938    DEBUG <general>: CAddonMgr::FindAddons: Addon 'metadata.album.universal' already present with version 3.1.3 at '/usr/share/kodi/addons/metadata.album.universal/' replaced with version 3.1.3 at '/home/xbmc/.kodi/addons/metadata.album.universal/'
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: audioencoder.kodi.builtin.aac v1.0.2 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: audioencoder.kodi.builtin.wma v1.0.2 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: game.controller.default v1.0.9 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: game.controller.snes v1.0.9 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.audioengine v1.1.1 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.filesystem v1.1.6 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.general v1.0.5 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.gui v5.15.0 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.main v1.2.4 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.network v1.0.4 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.global.tools v1.0.4 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.audiodecoder v3.0.0 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.audioencoder v2.1.0 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.game v2.1.0 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.imagedecoder v2.1.1 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.inputstream v2.3.4 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.peripheral v2.0.0 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.pvr v7.0.1 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.screensaver v2.1.0 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.vfs v3.0.0 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.videocodec v1.0.4 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.binary.instance.visualization v3.0.0 installed
2020-10-27 21:56:18.710 T:7938     INFO <general>: CAddonMgr::FindAddons: kodi.resource v1.0.0 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.album.universal v3.1.3 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.artists.universal v4.3.3 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.common.allmusic.com v3.2.2 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.common.fanart.tv v3.6.3 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.common.imdb.com v3.1.6 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.common.musicbrainz.org v2.2.4 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.common.theaudiodb.com v2.0.3 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.common.themoviedb.org v3.2.6 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.generic.albums v1.0.14 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.generic.artists v1.0.14 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.local v1.0.0 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.themoviedb.org v5.2.2 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.themoviedb.org.python v1.3.0+matrix.1 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.tvdb.com v3.2.8 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.tvshows.themoviedb.org v3.5.5 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: metadata.tvshows.themoviedb.org.python v1.3.0 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: repository.xbmc.org v3.2.3 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: resource.images.studios.white v0.0.25 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: resource.images.weathericons.default v1.1.9 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: resource.language.en_gb v2.0.2 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: resource.uisounds.kodi v1.0.1 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: screensaver.xbmc.builtin.black v1.0.34 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: screensaver.xbmc.builtin.dim v1.0.61 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: script.extendedinfo v5.6.0 installed
2020-10-27 21:56:18.711 T:7938     INFO <general>: CAddonMgr::FindAddons: script.globalsearch v9.0.5 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.addon.signals v0.0.6+matrix.1 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.autocompletion v2.0.2 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.certifi v2019.11.28+matrix.1 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.chardet v3.0.4+matrix.3 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.idna v2.8.1+matrix.1 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.kodi-six v0.1.3.1 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.kodi65 v1.2.1 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.pil v5.1.0 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.pycryptodome v3.4.3 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.requests v2.22.0+matrix.1 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.routing v0.2.3+matrix.1 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.simplejson v3.17.0+matrix.2 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.urllib3 v1.25.8+matrix.1 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: script.module.youtube.dl v20.616.0 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: service.xbmc.versioncheck v0.5.9+matrix.1 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: skin.estouchy v3.0.3 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: skin.estuary v3.0.2 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: webinterface.default v19.x-2.4.7 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: xbmc.addon v18.9.702 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: xbmc.core v0.1.0 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: xbmc.gui v5.15.0 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: xbmc.json v11.17.0 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: xbmc.metadata v2.1.0 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: xbmc.python v3.0.0 installed
2020-10-27 21:56:18.712 T:7938     INFO <general>: CAddonMgr::FindAddons: xbmc.webinterface v1.0.0 installed
2020-10-27 21:56:18.713 T:7938    DEBUG <general>: CFavourites::Load - no system favourites found, skipping
2020-10-27 21:56:18.714 T:7938    DEBUG <general>: DBus method call to org.freedesktop.ConsoleKit.Manager.CanStop at /org/freedesktop/ConsoleKit/Manager of org.freedesktop.ConsoleKit failed: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.ConsoleKit was not provided by any .service files
2020-10-27 21:56:18.714 T:7938     INFO <general>: Selected Logind/UPower as PowerSyscall
2020-10-27 21:56:18.714 T:7938    ERROR <general>: DBus error: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
2020-10-27 21:56:18.714 T:7938     INFO <general>: LogindUPowerSyscall - UPower not found, battery information will not be available
2020-10-27 21:56:18.733 T:7938    DEBUG <general>: LogindUPowerSyscall - inhibit lock taken, fd 17
2020-10-27 21:56:18.734 T:7938    DEBUG <general>: DBus method call to org.freedesktop.UPower.EnumerateDevices at /org/freedesktop/UPower of org.freedesktop.UPower failed: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
2020-10-27 21:56:18.734 T:7938    DEBUG <general>: DBus method call to org.freedesktop.DBus.Peer.Ping at /org/freedesktop/UDisks2 of org.freedesktop.UDisks2 failed: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UDisks2 was not provided by any .service files
2020-10-27 21:56:18.734 T:7938    DEBUG <general>: DBus method call to org.freedesktop.UDisks.EnumerateDevices at /org/freedesktop/UDisks of org.freedesktop.UDisks failed: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UDisks was not provided by any .service files
2020-10-27 21:56:18.734 T:7938    DEBUG <general>: Selected UDev as storage provider
2020-10-27 21:56:18.734 T:7944    DEBUG <general>: Thread ActiveAE start, auto delete: false
2020-10-27 21:56:18.735 T:7945    DEBUG <general>: Thread AESink start, auto delete: false
2020-10-27 21:56:18.735 T:7946    DEBUG <general>: Thread FDEventMonitor start, auto delete: false
2020-10-27 21:56:18.738 T:7944     INFO <general>: CAESinkALSA - Unable to open device "default" for playback
2020-10-27 21:56:18.750 T:7944    DEBUG <general>: CAESinkALSA - HDMI device "hdmi:CARD=HDMI,DEV=0" may be unconnected (no ELD data)
2020-10-27 21:56:18.750 T:7944    DEBUG <general>: CAESinkALSA - HDMI device "hdmi:CARD=HDMI,DEV=1" may be unconnected (no ELD data)
2020-10-27 21:56:18.751 T:7944    DEBUG <general>: CAESinkALSA - HDMI device "hdmi:CARD=HDMI,DEV=2" may be unconnected (no ELD data)
2020-10-27 21:56:18.751 T:7944    DEBUG <general>: CAESinkALSA - HDMI device "hdmi:CARD=HDMI,DEV=3" may be unconnected (no ELD data)
2020-10-27 21:56:18.751 T:7944    DEBUG <general>: CAESinkALSA - HDMI device "hdmi:CARD=HDMI,DEV=4" may be unconnected (no ELD data)
2020-10-27 21:56:18.772 T:7944     INFO <general>: CAESinkALSA - Unable to open device "surround21:CARD=PCH,DEV=0" for playback
2020-10-27 21:56:18.772 T:7944     INFO <general>: Found 1 Lists of Devices
2020-10-27 21:56:18.773 T:7944     INFO <general>: Enumerated ALSA devices:
2020-10-27 21:56:18.773 T:7944     INFO <general>:     Device 1
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=0
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayName     : HDA Intel
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayNameExtra: HDMI #0
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_channels        : FL, FR
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2020-10-27 21:56:18.773 T:7944     INFO <general>:     Device 2
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=1
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayName     : HDA Intel
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayNameExtra: HDMI #1
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_channels        : FL, FR
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2020-10-27 21:56:18.773 T:7944     INFO <general>:     Device 3
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=2
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayName     : HDA Intel
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayNameExtra: HDMI #2
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_channels        : FL, FR
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2020-10-27 21:56:18.773 T:7944     INFO <general>:     Device 4
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=3
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayName     : HDA Intel
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayNameExtra: HDMI #3
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_channels        : FL, FR
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2020-10-27 21:56:18.773 T:7944     INFO <general>:     Device 5
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=4
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayName     : HDA Intel
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayNameExtra: HDMI #4
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_channels        : FL, FR
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2020-10-27 21:56:18.773 T:7944     INFO <general>:     Device 6
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceName      : @:CARD=PCH,DEV=0
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayName     : HDA Intel PCH
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_displayNameExtra: ALC283 Analog
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_deviceType      : AE_DEVTYPE_PCM
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_channels        : FL, FR
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_sampleRates     : 48000
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_dataFormats     : AE_FMT_S32NE
2020-10-27 21:56:18.773 T:7944     INFO <general>:         m_streamTypes     : No passthrough capabilities
2020-10-27 21:56:18.773 T:7945     INFO <general>: CActiveAESink::OpenSink - initialize sink
2020-10-27 21:56:18.773 T:7945    DEBUG <general>: CActiveAESink::OpenSink - trying to open device ALSA:hw:CARD=PCH,DEV=0
2020-10-27 21:56:18.773 T:7945     INFO <general>: CAESinkALSA::Initialize - Attempting to open device "hw:CARD=PCH,DEV=0"
2020-10-27 21:56:18.773 T:7945     INFO <general>: CAESinkALSA::Initialize - Opened device "hw:CARD=PCH,DEV=0"
2020-10-27 21:56:18.773 T:7945     INFO <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2020-10-27 21:56:18.773 T:7945     INFO <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
2020-10-27 21:56:18.773 T:7945    DEBUG <general>: CAESinkALSA::InitializeHW - Request: periodSize 2205, bufferSize 8820
2020-10-27 21:56:18.776 T:7945    DEBUG <general>: CAESinkALSA::InitializeHW - Got: periodSize 2205, bufferSize 8820
2020-10-27 21:56:18.776 T:7945    DEBUG <general>: CAESinkALSA::InitializeHW - Setting timeout to 200 ms
2020-10-27 21:56:18.776 T:7945    DEBUG <general>: CAESinkALSA::GetChannelLayout - Input Channel Count: 2 Output Channel Count: 2
2020-10-27 21:56:18.776 T:7945    DEBUG <general>: CAESinkALSA::GetChannelLayout - Requested Layout: FL, FR
2020-10-27 21:56:18.776 T:7945    DEBUG <general>: CAESinkALSA::GetChannelLayout - Got Layout: FL, FR (ALSA: FL FR)
2020-10-27 21:56:18.776 T:7945    DEBUG <general>: CActiveAESink::OpenSink - ALSA Initialized:
2020-10-27 21:56:18.776 T:7945    DEBUG <general>:   Output Device : Device not found
2020-10-27 21:56:18.776 T:7945    DEBUG <general>:   Sample Rate   : 44100
2020-10-27 21:56:18.776 T:7945    DEBUG <general>:   Sample Format : AE_FMT_S32NE
2020-10-27 21:56:18.776 T:7945    DEBUG <general>:   Channel Count : 2
2020-10-27 21:56:18.777 T:7945    DEBUG <general>:   Channel Layout: FL, FR
2020-10-27 21:56:18.777 T:7945    DEBUG <general>:   Frames        : 2205
2020-10-27 21:56:18.777 T:7945    DEBUG <general>:   Frame Size    : 8
2020-10-27 21:56:18.778 T:7938     INFO <general>: CKeyboardLayoutManager: loading keyboard layouts from special://xbmc/system/keyboardlayouts...
2020-10-27 21:56:18.779 T:7938    DEBUG <general>: CKeyboardLayoutManager: keyboard layout "English QWERTY" successfully loaded
2020-10-27 21:56:18.779 T:7938    DEBUG <general>: CKeyboardLayoutManager: keyboard layout "English AZERTY" successfully loaded
2020-10-27 21:56:18.779 T:7938    DEBUG <general>: CKeyboardLayoutManager: keyboard layout "English ABC" successfully loaded
2020-10-27 21:56:18.779 T:7938     INFO <general>: RetroPlayer[PROCESS]: Registering process control for GBM
2020-10-27 21:56:18.779 T:7938     INFO <general>: RetroPlayer[RENDER]: Registering renderer factory for DMA
2020-10-27 21:56:18.779 T:7938     INFO <general>: RetroPlayer[RENDER]: Registering renderer factory for OpenGL
2020-10-27 21:56:18.779 T:7938    DEBUG <general>: CDRMUtils::OpenDrm - drm devices found: 1
2020-10-27 21:56:18.782 T:7938    DEBUG <general>: CDRMUtils::FindConnector - failed to find connected connector
2020-10-27 21:56:18.782 T:7938    ERROR <general>: CWinSystemGbm::InitWindowSystem - failed to initialize Atomic DRM
2020-10-27 21:56:18.782 T:7938    DEBUG <general>: CDRMUtils::OpenDrm - drm devices found: 1
2020-10-27 21:56:18.785 T:7938    DEBUG <general>: CDRMUtils::FindConnector - failed to find connected connector
2020-10-27 21:56:18.785 T:7938    ERROR <general>: CWinSystemGbm::InitWindowSystem - failed to initialize Legacy DRM
2020-10-27 21:56:18.786 T:7938    DEBUG <general>: CDRMUtils::OpenDrm - drm devices found: 1
2020-10-27 21:56:18.786 T:7938    DEBUG <general>: CDRMUtils::OpenDrm - opened device: /dev/dri/card0
2020-10-27 21:56:18.786 T:7938    DEBUG <general>: CDRMUtils::PrintDrmDeviceInfo - DRM Device Info:
                                                     available_nodes: 0x05
                                                     nodes:
                                                       nodes[0]: /dev/dri/card0
                                                       nodes[2]: /dev/dri/renderD128
                                                     bustype: 0x00
                                                       pci:
                                                         domain: 0x00
                                                         bus:    0x0
                                                         dev:    0x2
                                                         func:   0
                                                     deviceinfo:
                                                       pci:
                                                         vendor_id:    0x8086
                                                         device_id:    0x1626
                                                         subvendor_id: 0x8086
                                                         subdevice_id: 0x2057
2020-10-27 21:56:18.786 T:7938    DEBUG <general>: CDRMUtils::OpenDrm - opened render node: /dev/dri/renderD128
2020-10-27 21:56:18.786 T:7938    DEBUG <general>: COffScreenModeSetting::InitDrm - initialized offscreen DRM
2020-10-27 21:56:18.826 T:7938    DEBUG <general>: CWinSystemGbm::InitWindowSystem - initialized DRM
2020-10-27 21:56:18.826 T:7938     INFO <general>: Found resolution 1280x720 with 1280x720 @ 50.000000 Hz
2020-10-27 21:56:18.827 T:7938     INFO <general>: EGL_VERSION = 1.5
2020-10-27 21:56:18.827 T:7938     INFO <general>: EGL_VENDOR = Mesa Project
2020-10-27 21:56:18.827 T:7938     INFO <general>: EGL_EXTENSIONS = EGL_ANDROID_blob_cache EGL_ANDROID_native_fence_sync EGL_EXT_buffer_age EGL_EXT_create_context_robustness EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_IMG_context_priority EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver EGL_WL_bind_wayland_display
2020-10-27 21:56:18.827 T:7938     INFO <general>: EGL_CLIENT_EXTENSIONS = EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_EXT_client_extensions EGL_KHR_debug EGL_EXT_platform_device EGL_EXT_platform_wayland EGL_KHR_platform_wayland EGL_EXT_platform_x11 EGL_KHR_platform_x11 EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
2020-10-27 21:56:18.827 T:7938    DEBUG <general>: EGL Config Attributes:
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_BUFFER_SIZE: 32
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_ALPHA_SIZE: 8
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_BLUE_SIZE: 8
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_GREEN_SIZE: 8
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_RED_SIZE: 8
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_DEPTH_SIZE: 16
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_STENCIL_SIZE: 0
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_CONFIG_CAVEAT: 0x3038
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_CONFIG_ID: 34
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_LEVEL: 0
2020-10-27 21:56:18.827 T:7938    DEBUG <general>:   EGL_MAX_PBUFFER_HEIGHT: 4096
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_MAX_PBUFFER_PIXELS: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_MAX_PBUFFER_WIDTH: 4096
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_NATIVE_RENDERABLE: 1
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_NATIVE_VISUAL_ID: 875713089
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_NATIVE_VISUAL_TYPE: 0x3038
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_SAMPLES: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_SAMPLE_BUFFERS: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_SURFACE_TYPE: 4
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_TRANSPARENT_TYPE: 0x3038
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_TRANSPARENT_BLUE_VALUE: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_TRANSPARENT_GREEN_VALUE: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_TRANSPARENT_RED_VALUE: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_BIND_TO_TEXTURE_RGB: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_BIND_TO_TEXTURE_RGBA: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_MIN_SWAP_INTERVAL: 1
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_MAX_SWAP_INTERVAL: 1
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_LUMINANCE_SIZE: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_ALPHA_MASK_SIZE: 0
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_COLOR_BUFFER_TYPE: 0x308e
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_RENDERABLE_TYPE: 77
2020-10-27 21:56:18.828 T:7938    DEBUG <general>:   EGL_CONFORMANT: 77
2020-10-27 21:56:18.831 T:7938    DEBUG <general>: Vaapi2 EGL interop test results: general yes, deepColor yes
2020-10-27 21:56:18.831 T:7938    DEBUG <general>: libva info: VA-API version 1.8.0
2020-10-27 21:56:18.831 T:7938    DEBUG <general>: libva info: User environment variable requested driver 'iHD'
2020-10-27 21:56:18.831 T:7938    DEBUG <general>: libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
2020-10-27 21:56:18.831 T:7938    DEBUG <general>: libva info: Found init function __vaDriverInit_1_8
2020-10-27 21:56:18.832 T:7938    DEBUG <general>: libva info: va_openDriver() returns 0
2020-10-27 21:56:18.832 T:7938     INFO <general>: VAAPI::Close - closing decoder context
2020-10-27 21:56:18.832 T:7938    DEBUG <general>: CUDMABufferObject::Register - unable to open /dev/udmabuf: Permission denied
2020-10-27 21:56:18.832 T:7938    DEBUG <general>: CDMAHeapBufferObject::Register unable to open /dev/dma_heap/reserved: No such file or directory
2020-10-27 21:56:18.832 T:7938    DEBUG <general>: CDMAHeapBufferObject::Register unable to open /dev/dma_heap/linux,cma: No such file or directory
2020-10-27 21:56:18.832 T:7938    DEBUG <general>: CDMAHeapBufferObject::Register unable to open /dev/dma_heap/system: Permission denied
2020-10-27 21:56:18.832 T:7938     INFO <general>: Checking resolution 16
2020-10-27 21:56:18.832 T:7938    DEBUG <general>: OnLostDevice - notify display change event
2020-10-27 21:56:18.832 T:7938    DEBUG <general>: CWinSystemGbmEGLContext::DestroyWindow - deinitialized GBM
2020-10-27 21:56:18.832 T:7938    DEBUG <general>: CGBMUtils::CreateSurface - created surface with size 1280x720
2020-10-27 21:56:18.835 T:7938    DEBUG <general>: CWinSystemGbmEGLContext::CreateNewWindow - initialized GBM
2020-10-27 21:56:18.835 T:7938     INFO <general>: CRenderSystemGL::InitRenderSystem - Version: 4.6 (Core Profile) Mesa 20.2.1, Major: 4, Minor: 6
2020-10-27 21:56:18.835 T:7938     INFO <general>: GL_VENDOR = Intel
2020-10-27 21:56:18.835 T:7938     INFO <general>: GL_RENDERER = Mesa Intel(R) HD Graphics 6000 (BDW GT3)
2020-10-27 21:56:18.835 T:7938     INFO <general>: GL_VERSION = 4.6 (Core Profile) Mesa 20.2.1
2020-10-27 21:56:18.835 T:7938     INFO <general>: GL_SHADING_LANGUAGE_VERSION = 4.60
2020-10-27 21:56:18.835 T:7938     INFO <general>: GL_EXTENSIONS = GL_3DFX_texture_compression_FXT1 GL_AMD_conservative_depth GL_AMD_draw_buffers_blend GL_AMD_gpu_shader_int64 GL_AMD_multi_draw_indirect GL_AMD_performance_monitor GL_AMD_pinned_memory GL_AMD_query_buffer_object GL_AMD_seamless_cubemap_per_texture GL_AMD_shader_trinary_minmax GL_AMD_texture_texture4 GL_AMD_vertex_shader_layer GL_AMD_vertex_shader_viewport_index GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_ARB_ES2_compatibility GL_ARB_ES3_1_compatibility GL_ARB_ES3_2_compatibility GL_ARB_ES3_compatibility GL_ARB_arrays_of_arrays GL_ARB_base_instance GL_ARB_blend_func_extended GL_ARB_buffer_storage GL_ARB_clear_buffer_object GL_ARB_clear_texture GL_ARB_clip_control GL_ARB_compressed_texture_pixel_storage GL_ARB_compute_shader GL_ARB_compute_variable_group_size GL_ARB_conditional_render_inverted GL_ARB_conservative_depth GL_ARB_copy_buffer GL_ARB_copy_image GL_ARB_cull_distance GL_ARB_debug_output GL_ARB_depth_buffer_float GL_ARB_depth_clamp GL_ARB_derivative_control GL_ARB_direct_state_access GL_ARB_draw_buffers GL_ARB_draw_buffers_blend GL_ARB_draw_elements_base_vertex GL_ARB_draw_indirect GL_ARB_draw_instanced GL_ARB_enhanced_layouts GL_ARB_explicit_attrib_location GL_ARB_explicit_uniform_location GL_ARB_fragment_coord_conventions GL_ARB_fragment_layer_viewport GL_ARB_fragment_shader GL_ARB_framebuffer_no_attachments GL_ARB_framebuffer_object GL_ARB_framebuffer_sRGB GL_ARB_get_program_binary GL_ARB_get_texture_sub_image GL_ARB_gl_spirv GL_ARB_gpu_shader5 GL_ARB_gpu_shader_fp64 GL_ARB_gpu_shader_int64 GL_ARB_half_float_pixel GL_ARB_half_float_vertex GL_ARB_indirect_parameters GL_ARB_instanced_arrays GL_ARB_internalformat_query GL_ARB_internalformat_query2 GL_ARB_invalidate_subdata GL_ARB_map_buffer_alignment GL_ARB_map_buffer_range GL_ARB_multi_bind GL_ARB_multi_draw_indirect GL_ARB_occlusion_query2 GL_ARB_parallel_shader_compile GL_ARB_pipeline_statistics_query GL_ARB_pixel_buffer_object GL_ARB_point_sprite GL_ARB_polygon_offset_clamp GL_ARB_program_interface_query GL_ARB_provoking_vertex GL_ARB_query_buffer_object GL_ARB_robust_buffer_access_behavior GL_ARB_robustness GL_ARB_sample_shading GL_ARB_sampler_objects GL_ARB_seamless_cube_map GL_ARB_seamless_cubemap_per_texture GL_ARB_separate_shader_objects GL_ARB_shader_atomic_counter_ops GL_ARB_shader_atomic_counters GL_ARB_shader_ballot GL_ARB_shader_bit_encoding GL_ARB_shader_clock GL_ARB_shader_draw_parameters GL_ARB_shader_group_vote GL_ARB_shader_image_load_store GL_ARB_shader_image_size GL_ARB_shader_objects GL_ARB_shader_precision GL_ARB_shader_storage_buffer_object GL_ARB_shader_subroutine GL_ARB_shader_texture_image_samples GL_ARB_shader_texture_lod GL_ARB_shader_viewport_layer_array GL_ARB_shading_language_420pack GL_ARB_shading_language_include GL_ARB_shading_language_packing GL_ARB_spirv_extensions GL_ARB_stencil_texturing GL_ARB_sync GL_ARB_tessellation_shader GL_ARB_texture_barrier GL_ARB_texture_buffer_object GL_ARB_texture_buffer_object_rgb32 GL_ARB_texture_buffer_range GL_ARB_texture_compression_bptc GL_ARB_texture_compression_rgtc GL_ARB_texture_cube_map_array GL_ARB_texture_filter_anisotropic GL_ARB_texture_float GL_ARB_texture_gather GL_ARB_texture_mirror_clamp_to_edge GL_ARB_texture_multisample GL_ARB_texture_non_power_of_two GL_ARB_texture_query_levels GL_ARB_texture_query_lod GL_ARB_texture_rectangle GL_ARB_texture_rg GL_ARB_texture_rgb10_a2ui GL_ARB_texture_stencil8 GL_ARB_texture_storage GL_ARB_texture_storage_multisample GL_ARB_texture_swizzle GL_ARB_texture_view GL_ARB_timer_query GL_ARB_transform_feedback2 GL_ARB_transform_feedback3 GL_ARB_transform_feedback_instanced GL_ARB_transform_feedback_overflow_query GL_ARB_uniform_buffer_object GL_ARB_vertex_array_bgra GL_ARB_vertex_array_object GL_ARB_vertex_attrib_64bit GL_ARB_vertex_attrib_binding GL_ARB_vertex_buffer_object GL_ARB_vertex_shader GL_ARB_vertex_type_10f_11f_11f_rev GL_ARB_vertex_type_2_10_10_10_rev GL_ARB_viewport_array GL_ATI_blend_equation_separate GL_ATI_texture_float GL_EXT_EGL_image_storage GL_EXT_EGL_sync GL_EXT_abgr GL_EXT_blend_equation_separate GL_EXT_demote_to_helper_invocation GL_EXT_draw_buffers2 GL_EXT_draw_instanced GL_EXT_framebuffer_blit GL_EXT_framebuffer_multisample GL_EXT_framebuffer_multisample_blit_scaled GL_EXT_framebuffer_object GL_EXT_framebuffer_sRGB GL_EXT_packed_depth_stencil GL_EXT_packed_float GL_EXT_pixel_buffer_object GL_EXT_polygon_offset_clamp GL_EXT_provoking_vertex GL_EXT_shader_framebuffer_fetch_non_coherent GL_EXT_shader_integer_mix GL_EXT_shader_samples_identical GL_EXT_texture_array GL_EXT_texture_compression_dxt1 GL_EXT_texture_compression_rgtc GL_EXT_texture_compression_s3tc GL_EXT_texture_filter_anisotropic GL_EXT_texture_integer GL_EXT_texture_sRGB GL_EXT_texture_sRGB_R8 GL_EXT_texture_sRGB_decode GL_EXT_texture_shadow_lod GL_EXT_texture_shared_exponent GL_EXT_texture_snorm GL_EXT_texture_swizzle GL_EXT_timer_query GL_EXT_transform_feedback GL_EXT_vertex_array_bgra GL_EXT_vertex_attrib_64bit GL_IBM_multimode_draw_arrays GL_INTEL_blackhole_render GL_INTEL_performance_query GL_INTEL_shader_integer_functions2 GL_KHR_blend_equation_advanced GL_KHR_context_flush_control GL_KHR_debug GL_KHR_no_error GL_KHR_parallel_shader_compile GL_KHR_robust_buffer_access_behavior GL_KHR_robustness GL_KHR_texture_compression_astc_ldr GL_KHR_texture_compression_astc_sliced_3d GL_MESA_framebuffer_flip_y GL_MESA_pack_invert GL_MESA_shader_integer_functions GL_MESA_texture_signed_rgba GL_NV_compute_shader_derivatives GL_NV_conditional_render GL_NV_copy_image GL_NV_depth_clamp GL_NV_packed_depth_stencil GL_NV_texture_barrier GL_OES_EGL_image GL_S3_s3tc
2020-10-27 21:56:18.854 T:7938    DEBUG <general>: OnLostDevice - notify display change event
2020-10-27 21:56:18.856 T:7938     INFO <general>: GL: Maximum texture width: 16384
2020-10-27 21:56:18.856 T:7938    DEBUG <general>: guilib: Fill viewport on change for solving rendering passes
2020-10-27 21:56:18.893 T:7943    DEBUG <general>: CLibInputHandler::DeviceAdded - keyboard type device added: Power Button (event2)
2020-10-27 21:56:18.893 T:7943    DEBUG <general>: CLibInputKeyboard::GetRepeat - could not get key repeat for event2 (Function not implemented)
2020-10-27 21:56:18.893 T:7943    DEBUG <general>: CLibInputKeyboard::GetRepeat - delay: 400ms repeat: 80ms for Power Button (event2)
2020-10-27 21:56:18.898 T:7943    DEBUG <general>: CLibInputHandler::DeviceAdded - keyboard type device added: Video Bus (event6)
2020-10-27 21:56:18.898 T:7943    DEBUG <general>: CLibInputKeyboard::GetRepeat - could not get key repeat for event6 (Function not implemented)
2020-10-27 21:56:18.898 T:7943    DEBUG <general>: CLibInputKeyboard::GetRepeat - delay: 400ms repeat: 80ms for Video Bus (event6)
2020-10-27 21:56:18.906 T:7943    DEBUG <general>: CLibInputHandler::DeviceAdded - keyboard type device added: Power Button (event1)
2020-10-27 21:56:18.906 T:7943    DEBUG <general>: CLibInputKeyboard::GetRepeat - could not get key repeat for event1 (Function not implemented)
2020-10-27 21:56:18.906 T:7943    DEBUG <general>: CLibInputKeyboard::GetRepeat - delay: 400ms repeat: 80ms for Power Button (event1)
2020-10-27 21:56:18.914 T:7943    DEBUG <general>: CLibInputHandler::DeviceAdded - keyboard type device added: Sleep Button (event0)
2020-10-27 21:56:18.914 T:7943    DEBUG <general>: CLibInputKeyboard::GetRepeat - could not get key repeat for event0 (Function not implemented)
2020-10-27 21:56:18.914 T:7943    DEBUG <general>: CLibInputKeyboard::GetRepeat - delay: 400ms repeat: 80ms for Sleep Button (event0)
2020-10-27 21:56:18.922 T:7943    DEBUG <general>: CLibInputHandler::DeviceAdded - pointer type device added: Nuvoton w836x7hg Infrared Remote Transceiver (event3)
2020-10-27 21:56:18.922 T:7943    DEBUG <general>: CLibInputHandler::DeviceAdded - keyboard type device added: Nuvoton w836x7hg Infrared Remote Transceiver (event3)
2020-10-27 21:56:18.922 T:7943    DEBUG <general>: CLibInputKeyboard::GetRepeat - delay: 500ms repeat: 125ms for Nuvoton w836x7hg Infrared Remote Transceiver (event3)
2020-10-27 21:56:18.964 T:7938    DEBUG <general>: CWinSystemGbmGLContext::PresentRender - Sending display reset to all clients
2020-10-27 21:56:18.964 T:7938     INFO <general>: load keymapping
2020-10-27 21:56:18.965 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/appcommand.xml
2020-10-27 21:56:18.965 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/customcontroller.AppleRemote.xml
2020-10-27 21:56:18.965 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/customcontroller.Harmony.xml
2020-10-27 21:56:18.966 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/customcontroller.SiriRemote.xml
2020-10-27 21:56:18.966 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/gamepad.xml
2020-10-27 21:56:18.967 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/joystick.xml
2020-10-27 21:56:18.967 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/keyboard.xml
2020-10-27 21:56:18.969 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/mouse.xml
2020-10-27 21:56:18.969 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/remote.xml
2020-10-27 21:56:18.970 T:7938     INFO <general>: Loading special://xbmc/system/keymaps/touchscreen.xml
2020-10-27 21:56:18.970 T:7938     INFO <general>: Loading special://masterprofile/keymaps/mce.xml
2020-10-27 21:56:18.970 T:7938     INFO <general>: Loading special://masterprofile/keymaps/mouse.xml
2020-10-27 21:56:18.970 T:7938     INFO <general>: Loading special://profile/keymaps/mce.xml
2020-10-27 21:56:18.970 T:7938     INFO <general>: Loading special://profile/keymaps/mouse.xml
2020-10-27 21:56:18.970 T:7938     INFO <general>: GUI format 1280x720, Display
2020-10-27 21:56:18.970 T:7938     INFO <general>: CLangInfo: loading resource.language.en_gb language information...
2020-10-27 21:56:18.971 T:7938    DEBUG <general>: trying to set locale to en_US.UTF-8
2020-10-27 21:56:18.971 T:7938     INFO <general>: global locale set to en_US.UTF-8
2020-10-27 21:56:18.971 T:7938     INFO <general>: CLangInfo: loading resource.language.en_gb language strings...
2020-10-27 21:56:18.976 T:7938    DEBUG <general>: LocalizeStrings: loaded 4118 strings from file resource://resource.language.en_gb/strings.po
2020-10-27 21:56:18.977 T:7938    DEBUG <general>: LocalizeStrings: loaded 3 strings from file /usr/share/kodi/addons/audioencoder.kodi.builtin.aac/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.977 T:7938    DEBUG <general>: LocalizeStrings: loaded 3 strings from file /usr/share/kodi/addons/audioencoder.kodi.builtin.wma/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.977 T:7938    DEBUG <general>: LocalizeStrings: loaded 18 strings from file /usr/share/kodi/addons/game.controller.default/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.977 T:7938    DEBUG <general>: LocalizeStrings: loaded 13 strings from file /usr/share/kodi/addons/game.controller.snes/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.977 T:7938    DEBUG <general>: LocalizeStrings: loaded 17 strings from file /home/xbmc/.kodi/addons/metadata.album.universal/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.977 T:7938    DEBUG <general>: LocalizeStrings: loaded 32 strings from file /home/xbmc/.kodi/addons/metadata.artists.universal/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.978 T:7938    DEBUG <general>: LocalizeStrings: loaded 17 strings from file /usr/share/kodi/addons/metadata.generic.albums/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.978 T:7938    DEBUG <general>: LocalizeStrings: loaded 15 strings from file /usr/share/kodi/addons/metadata.generic.artists/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.978 T:7938    DEBUG <general>: LocalizeStrings: loaded 9 strings from file /home/xbmc/.kodi/addons/metadata.themoviedb.org/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.978 T:7938    DEBUG <general>: LocalizeStrings: loaded 31 strings from file /usr/share/kodi/addons/metadata.themoviedb.org.python/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.978 T:7938    DEBUG <general>: LocalizeStrings: loaded 10 strings from file /home/xbmc/.kodi/addons/metadata.tvdb.com/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.978 T:7938    DEBUG <general>: LocalizeStrings: loaded 11 strings from file /home/xbmc/.kodi/addons/metadata.tvshows.themoviedb.org/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.978 T:7938    DEBUG <general>: LocalizeStrings: loaded 25 strings from file /usr/share/kodi/addons/metadata.tvshows.themoviedb.org.python/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.978 T:7938    DEBUG <general>: LocalizeStrings: loaded 3 strings from file /usr/share/kodi/addons/screensaver.xbmc.builtin.dim/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.979 T:7938    DEBUG <general>: LocalizeStrings: loaded 167 strings from file /home/xbmc/.kodi/addons/script.extendedinfo/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.979 T:7938    DEBUG <general>: LocalizeStrings: loaded 29 strings from file /home/xbmc/.kodi/addons/script.globalsearch/resources/language/resource.language.en_GB/strings.po
2020-10-27 21:56:18.980 T:7938    DEBUG <general>: LocalizeStrings: loaded 45 strings from file /home/xbmc/.kodi/addons/script.module.youtube.dl/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.980 T:7938    DEBUG <general>: LocalizeStrings: loaded 24 strings from file /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/language/resource.language.en_gb/strings.po
2020-10-27 21:56:18.980 T:7951    DEBUG <general>: Thread JobWorker start, auto delete: true
2020-10-27 21:56:18.980 T:7951    DEBUG <general>: Initialize, updating databases...
2020-10-27 21:56:18.981 T:7951     INFO <general>: Running database version Addons33
2020-10-27 21:56:18.981 T:7951     INFO <general>: Running database version ViewModes6
2020-10-27 21:56:18.981 T:7951     INFO <general>: Running database version Textures13
2020-10-27 21:56:18.982 T:7951     INFO <general>: Running database version MyMusic82
2020-10-27 21:56:18.984 T:7951     INFO <general>: Running database version MyVideos119
2020-10-27 21:56:18.985 T:7951     INFO <general>: Running database version TV37
2020-10-27 21:56:18.986 T:7951     INFO <general>: Running database version Epg13
2020-10-27 21:56:18.986 T:7951    DEBUG <general>: Initialize, updating databases... DONE
2020-10-27 21:56:18.989 T:7938     INFO <general>: start dvd mediatype detection
2020-10-27 21:56:18.989 T:7952    DEBUG <general>: Thread DetectDVDMedia start, auto delete: false
2020-10-27 21:56:18.989 T:7952    DEBUG <general>: Compiled with libcdio Version 0.20100
2020-10-27 21:56:18.990 T:7952    DEBUG <general>: Thread DetectDVDMedia 140084250670656 terminating
2020-10-27 21:56:18.998 T:7938    DEBUG <general>: CGBMUtils - using 4 buffers
2020-10-27 21:56:18.998 T:7938     INFO <general>: Unloaded skin
2020-10-27 21:56:18.998 T:7938     INFO <general>:   load skin from: /usr/share/kodi/addons/skin.estuary/ (version: 3.0.2)
2020-10-27 21:56:18.998 T:7938     INFO <general>:   load fonts for skin...
2020-10-27 21:56:18.999 T:7938     INFO <general>: Loading skin includes from /usr/share/kodi/addons/skin.estuary/xml/Includes.xml
2020-10-27 21:56:19.014 T:7938     INFO <general>: Loading fonts from /usr/share/kodi/addons/skin.estuary/xml/Font.xml
2020-10-27 21:56:19.019 T:7938    DEBUG <general>: LocalizeStrings: loaded 148 strings from file /usr/share/kodi/addons/skin.estuary/language/resource.language.en_gb/strings.po
2020-10-27 21:56:19.019 T:7938     INFO <general>:   load new skin...
2020-10-27 21:56:19.019 T:7938     INFO <general>: Loading custom window XMLs from skin path /usr/share/kodi/addons/skin.estuary/xml
2020-10-27 21:56:19.021 T:7938    DEBUG <general>: Load Skin XML: 2.05ms
2020-10-27 21:56:19.021 T:7938     INFO <general>:   initialize new skin...
2020-10-27 21:56:19.021 T:7938    DEBUG <general>: guilib: Fill viewport on change for solving rendering passes
2020-10-27 21:56:19.021 T:7938     INFO <general>: Loading skin file: Custom_1109_TopBarOverlay.xml, load type: LOAD_ON_GUI_INIT
2020-10-27 21:56:19.025 T:7938    DEBUG <general>: OpenBundle - Opened bundle /usr/share/kodi/addons/skin.estuary/media/Textures.xbt
2020-10-27 21:56:19.025 T:7938     INFO <general>: Loading skin file: DialogVolumeBar.xml, load type: LOAD_ON_GUI_INIT
2020-10-27 21:56:19.025 T:7938     INFO <general>: Loading skin file: DialogBusy.xml, load type: LOAD_ON_GUI_INIT
2020-10-27 21:56:19.026 T:7938     INFO <general>: Loading skin file: Pointer.xml, load type: LOAD_ON_GUI_INIT
2020-10-27 21:56:19.026 T:7938     INFO <general>: Loading skin file: DialogExtendedProgressBar.xml, load type: LOAD_ON_GUI_INIT
2020-10-27 21:56:19.027 T:7938     INFO <general>: Loading skin file: DialogSeekBar.xml, load type: LOAD_ON_GUI_INIT
2020-10-27 21:56:19.031 T:7938     INFO <general>: Loading skin file: DialogNotification.xml, load type: LOAD_ON_GUI_INIT
2020-10-27 21:56:19.032 T:7938     INFO <general>: Loading skin file: DialogBusy.xml, load type: LOAD_ON_GUI_INIT
2020-10-27 21:56:19.032 T:7938     INFO <general>: Loading resource://resource.uisounds.kodi/sounds.xml
2020-10-27 21:56:19.042 T:7938     INFO <general>:   skin loaded...
2020-10-27 21:56:19.042 T:7938    DEBUG <general>: Activating window ID: 12997
2020-10-27 21:56:19.042 T:7938    DEBUG <general>: ------ Window Init () ------
2020-10-27 21:56:19.042 T:7938    DEBUG <general>: Activating window ID: 12999
2020-10-27 21:56:19.042 T:7938    DEBUG <general>: ------ Window Init (Startup.xml) ------
2020-10-27 21:56:19.042 T:7938     INFO <general>: Loading skin file: Startup.xml, load type: LOAD_EVERY_TIME
2020-10-27 21:56:19.042 T:7938    DEBUG <general>: Activating window ID: 10000
2020-10-27 21:56:19.042 T:7938    DEBUG <general>: ------ Window Deinit (Startup.xml) ------
2020-10-27 21:56:19.042 T:7938    DEBUG <general>: ------ Window Init (Home.xml) ------
2020-10-27 21:56:19.042 T:7938     INFO <general>: Loading skin file: Home.xml, load type: KEEP_IN_MEMORY
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[library://video/movies/]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[special://skin/playlists/inprogress_movies.xsp]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[special://skin/playlists/recent_unwatched_movies.xsp]: refreshing..
2020-10-27 21:56:19.081 T:7953    DEBUG <general>: Thread JobWorker start, auto delete: true
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[special://skin/playlists/unwatched_movies.xsp]: refreshing..
2020-10-27 21:56:19.081 T:7954    DEBUG <general>: Thread JobWorker start, auto delete: true
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[special://skin/playlists/random_movies.xsp]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[videodb://movies/genres/]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[videodb://movies/sets/]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[library://video/tvshows/]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[videodb://inprogresstvshows]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[special://skin/playlists/recent_unwatched_episodes.xsp]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[special://skin/playlists/unwatched_tvshows.xsp]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[videodb://tvshows/genres/]: refreshing..
2020-10-27 21:56:19.081 T:7938    DEBUG <general>: CDirectoryProvider[videodb://tvshows/studios/]: refreshing..
2020-10-27 21:56:19.082 T:7938    DEBUG <general>: CDirectoryProvider[addons://]: refreshing..
2020-10-27 21:56:19.082 T:7938    DEBUG <general>: CDirectoryProvider[addons://sources/video/]: refreshing..
2020-10-27 21:56:19.082 T:7938    DEBUG <general>: CDirectoryProvider[addons://sources/audio/]: refreshing..
2020-10-27 21:56:19.082 T:7938    DEBUG <general>: CDirectoryProvider[addons://sources/game/]: refreshing..
2020-10-27 21:56:19.082 T:7938    DEBUG <general>: CDirectoryProvider[addons://sources/executable/]: refreshing..
2020-10-27 21:56:19.082 T:7938    DEBUG <general>: CDirectoryProvider[addons://sources/image/]: refreshing..
2020-10-27 21:56:19.082 T:7938    DEBUG <general>: CDirectoryProvider[library://video/]: refreshing..
2020-10-27 21:56:19.082 T:7938    DEBUG <general>: CDirectoryProvider[sources://video/]: refreshing..
2020-10-27 21:56:19.082 T:7938    DEBUG <general>: CDirectoryProvider[special://videoplaylists/]: refreshing..
2020-10-27 21:56:19.083 T:7938    DEBUG <general>: CDirectoryProvider[favourites://]: refreshing..
2020-10-27 21:56:19.083 T:7938    DEBUG <general>: CDirectoryProvider[addons://sources/game/]: refreshing..
2020-10-27 21:56:19.093 T:7938    DEBUG <general>: JSONRPC: JSON schema type definition references an unknown type Setting.Details.Setting
2020-10-27 21:56:19.093 T:7938  WARNING <general>: JSONRPC: Could not parse type "Setting.Details.SettingList"
2020-10-27 21:56:19.093 T:7938     INFO <general>: JSONRPC: Adding type "Setting.Details.SettingList" to list of incomplete definitions (waiting for "Setting.Details.Setting")
2020-10-27 21:56:19.093 T:7938     INFO <general>: JSONRPC: Resolving incomplete types/methods referencing Setting.Details.Setting
2020-10-27 21:56:19.106 T:7938     INFO <general>: JSONRPC v11.17.0: Successfully initialized
2020-10-27 21:56:19.106 T:7938    DEBUG <general>: LoadMappings - loaded node "Motorola Nyxboard Hybrid"
2020-10-27 21:56:19.106 T:7938    DEBUG <general>: LoadMappings - loaded node "CEC Adapter"
2020-10-27 21:56:19.106 T:7938    DEBUG <general>: LoadMappings - loaded node "Pulse-Eight CEC Adapter"
2020-10-27 21:56:19.106 T:7938    DEBUG <general>: LoadMappings - loaded node "iMON HID device"
2020-10-27 21:56:19.106 T:7938    DEBUG <general>: LoadMappings - loaded node "WETEK Play remote"
2020-10-27 21:56:19.106 T:7938    DEBUG <general>: LoadMappings - loaded node ""
2020-10-27 21:56:19.109 T:7957    DEBUG <general>: Thread PeripBusUSBUdev start, auto delete: false
2020-10-27 21:56:19.109 T:7957    DEBUG <general>: Process - initialised udev monitor
2020-10-27 21:56:19.113 T:7958    DEBUG <general>: Thread PeripBusCEC start, auto delete: false
2020-10-27 21:56:19.121 T:7959    DEBUG <general>: Thread PeripBusAddon start, auto delete: false
2020-10-27 21:56:19.121 T:7938    DEBUG <general>: Initialise - initialised peripheral on 'keyboard' with 1 features and 0 sub devices
2020-10-27 21:56:19.121 T:7938     INFO <general>: Register - new keyboard device registered on application->keyboard: Keyboard (0000:0000)
2020-10-27 21:56:19.121 T:7938    DEBUG <general>: Initialise - initialised peripheral on 'mouse' with 1 features and 0 sub devices
2020-10-27 21:56:19.121 T:7938     INFO <general>: Register - new mouse device registered on application->mouse: Mouse (0000:0000)
2020-10-27 21:56:19.127 T:7960    DEBUG <general>: Thread PeripEventScan start, auto delete: false
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: ContextMenuManager: addon menus reloaded.
2020-10-27 21:56:19.127 T:7938     INFO <general>: Loading player core factory settings from special://xbmc/system/playercorefactory.xml.
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerCoreConfig::<ctor>: created player VideoPlayer
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerCoreConfig::<ctor>: created player PAPlayer
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerCoreConfig::<ctor>: created player RetroPlayer
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: system rules
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: mms/udp
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: lastfm/shout
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: rtmp
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: rtsp
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: streams
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: aacp/sdp
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: mp2
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: dvd
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: discimage
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: sdp/asf
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: nsv
2020-10-27 21:56:19.127 T:7938    DEBUG <general>: CPlayerSelectionRule::Initialize: creating rule: radio
2020-10-27 21:56:19.127 T:7938     INFO <general>: Loaded playercorefactory configuration
2020-10-27 21:56:19.127 T:7938     INFO <general>: Loading player core factory settings from special://masterprofile/playercorefactory.xml.
2020-10-27 21:56:19.127 T:7938     INFO <general>: special://masterprofile/playercorefactory.xml does not exist. Skipping.
2020-10-27 21:56:19.127 T:7938     INFO <general>: removing tempfiles
2020-10-27 21:56:19.129 T:7938    DEBUG <general>: CRepositoryUpdater: closest next update check at 10/28/2020 5:56:06 PM (in 71987 s)
2020-10-27 21:56:19.137 T:7961    DEBUG <general>: Thread Timer start, auto delete: false
2020-10-27 21:56:19.137 T:7938    DEBUG <general>: CServiceAddonManager: starting service.xbmc.versioncheck
2020-10-27 21:56:19.139 T:7962    DEBUG <general>: Thread LanguageInvoker start, auto delete: false
2020-10-27 21:56:19.139 T:7938     INFO <general>: initialize done
2020-10-27 21:56:19.139 T:7962     INFO <general>: initializing python engine.
2020-10-27 21:56:19.139 T:7938     INFO <general>: Running the application...
2020-10-27 21:56:19.139 T:7938    DEBUG <general>: NetworkMessage - Starting network services
2020-10-27 21:56:19.140 T:7938     INFO <general>: CZeroconfAvahi::clientCallback: avahi server not available. But may become later...
2020-10-27 21:56:19.140 T:7938     INFO <general>: starting zeroconf publishing
2020-10-27 21:56:19.147 T:7964    DEBUG <general>: Thread EventServer start, auto delete: false
2020-10-27 21:56:19.147 T:7964     INFO <general>: ES: Starting UDP Event server on port 9777
2020-10-27 21:56:19.152 T:7964    DEBUG <general>: CheckIPv6: Could not create IPv6 socket: Address family not supported by protocol
2020-10-27 21:56:19.152 T:7964     INFO <general>: UDP: Listening on port 9777 (ipv6 : false)
2020-10-27 21:56:19.155 T:7938    ERROR <general>: JSONRPC Server: Failed to connect to sdpd
2020-10-27 21:56:19.158 T:7938     INFO <general>: JSONRPC Server: Successfully initialized
2020-10-27 21:56:19.158 T:7971    DEBUG <general>: Thread TCPServer start, auto delete: false
2020-10-27 21:56:19.212 T:7962    DEBUG <general>: CPythonInvoker(0, /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py): start processing
2020-10-27 21:56:19.215 T:7972    DEBUG <general>: Thread JobWorker start, auto delete: true
2020-10-27 21:56:19.295 T:7962    DEBUG <general>: -->Python Interpreter Initialized<--
2020-10-27 21:56:19.295 T:7962    DEBUG <general>:

2020-10-27 21:56:19.295 T:7962    DEBUG <general>: CPythonInvoker(0, /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py): the source file to load is "/home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py"
2020-10-27 21:56:19.295 T:7962    DEBUG <general>: CPythonInvoker(0, /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py): setting the Python path to /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib:/usr/lib/python38.zip:/usr/lib/python3.8:/usr/lib/python3.8/lib-dynload:/usr/local/lib/python3.8/dist-packages:/usr/lib/python3/dist-packages
2020-10-27 21:56:19.295 T:7962    DEBUG <general>: CPythonInvoker(0, /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py): entering source directory /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib
2020-10-27 21:56:19.295 T:7962    DEBUG <general>: CPythonInvoker(0, /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py): instantiating addon using automatically obtained id of "service.xbmc.versioncheck" dependent on version 3.0.0 of the xbmc.python api
2020-10-27 21:56:19.630 T:7938    DEBUG <general>: LogindUPowerSyscall - Received unknown signal NameAcquired
2020-10-27 21:56:19.702 T:7962    DEBUG <CSettingsManager>: requested setting (lastnotified_version) was not found.
2020-10-27 21:56:19.702 T:7962    DEBUG <general>: Version Check: Version 0.5.9+matrix.1 started
2020-10-27 21:56:19.768 T:7954    DEBUG <general>: CAddonDatabase: SELECT repo.id FROM repo .. took 0 ms
2020-10-27 21:56:19.770 T:7954    DEBUG <general>: CAddonDatabase: query  SELECT addons.*, repo.addonID AS repoID FROM addons JOIN addonlinkrepo ON addons.id=addonlinkrepo.idAddon JOIN repo ON repo.id=addonlinkrepo.idRepo WHERE addonlinkrepo.idRepo IN (1) ORDER BY repo.addonID, addons.addonID returned 533 rows in 2 ms
2020-10-27 21:56:19.793 T:7954    DEBUG <general>: CAddonDatabase::GetAddons took 26 ms
2020-10-27 21:56:19.795 T:7954    DEBUG <general>: ADDONS: repo: repository.xbmc.org - 533 addon(s) loaded
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: CAddonRepos::BuildUpdateOrOutdatedList: Building update list from installed add-ons
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = audioencoder.kodi.builtin.aac / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = audioencoder.kodi.builtin.wma / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = game.controller.default / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = game.controller.snes / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.album.universal / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.artists.universal / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.common.allmusic.com / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.common.fanart.tv / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.common.imdb.com / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.common.musicbrainz.org / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.common.theaudiodb.com / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.common.themoviedb.org / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.generic.albums / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.generic.artists / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.local / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.themoviedb.org / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.themoviedb.org.python / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.tvdb.com / Origin = repository.xbmc.org
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.tvshows.themoviedb.org / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = metadata.tvshows.themoviedb.org.python / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = repository.xbmc.org / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = resource.images.studios.white / Origin = repository.xbmc.org
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = resource.images.weathericons.default / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.797 T:7954    DEBUG <general>: ADDONS: update check: addonID = resource.language.en_gb / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = resource.uisounds.kodi / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = screensaver.xbmc.builtin.black / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = screensaver.xbmc.builtin.dim / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.extendedinfo / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.globalsearch / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.addon.signals / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.autocompletion / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.certifi / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.chardet / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.idna / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.kodi-six / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.kodi65 / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.pil / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.pycryptodome / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.requests / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.routing / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.simplejson / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.urllib3 / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = script.module.youtube.dl / Origin = repository.xbmc.org
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = service.xbmc.versioncheck / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = skin.estouchy / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = skin.estuary / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: ADDONS: update check: addonID = webinterface.default / Origin = b6a50484-93a0-4afb-a01c-8d17e059feda
2020-10-27 21:56:19.798 T:7954    DEBUG <general>: CAddonMgr::GetAvailableUpdatesOrOutdatedAddons took 31 ms
2020-10-27 21:56:19.808 T:7972    DEBUG <general>: CMultiPathDirectory::GetDirectory(multipath://special%3a%2f%2fprofile%2fplaylists%2fvideo/special%3a%2f%2fprofile%2fplaylists%2fmixed/)
2020-10-27 21:56:19.808 T:7972    DEBUG <general>: Getting Directory (special://profile/playlists/video)
2020-10-27 21:56:19.808 T:7972    DEBUG <general>: Getting Directory (special://profile/playlists/mixed)
2020-10-27 21:56:19.808 T:7972    DEBUG <general>: CMultiPathDirectory::MergeItems, items = 0
2020-10-27 21:56:19.809 T:7972    DEBUG <general>: CRecentlyAddedJob::UpdateMusic() - Running RecentlyAdded home screen update
2020-10-27 21:56:19.817 T:7972    DEBUG <general>: GetRecentlyAddedAlbumSongs() query: SELECT songview.*, songartistview.* FROM (SELECT idAlbum, dateAdded FROM album ORDER BY dateAdded DESC LIMIT 10) AS recentalbums JOIN songview ON songview.idAlbum = recentalbums.idAlbum JOIN songartistview ON songview.idSong = songartistview.idSong ORDER BY recentalbums.dateAdded DESC, songview.idAlbum DESC, songview.idSong, songartistview.idRole, songartistview.iOrder
2020-10-27 21:56:19.818 T:7972    DEBUG <general>: GetRecentlyAddedAlbums query: SELECT albumview.*, albumartistview.* FROM (SELECT idAlbum FROM album WHERE strAlbum != '' ORDER BY dateAdded DESC LIMIT 10) AS recentalbums JOIN albumview ON albumview.idAlbum = recentalbums.idAlbum JOIN albumartistview ON albumview.idAlbum = albumartistview.idAlbum ORDER BY dateAdded DESC, albumview.idAlbum desc, albumartistview.iOrder
2020-10-27 21:56:19.819 T:7972    DEBUG <general>: CRecentlyAddedJob::UpdateVideos() - Running RecentlyAdded home screen update
2020-10-27 21:56:19.834 T:7953    DEBUG <general>: CZeroconfAvahi::doPublishService identifier: servers.eventserver type: _xbmc-events._udp name:Kodi (xbmc) port:9777
2020-10-27 21:56:19.834 T:7953    DEBUG <general>: CZeroconfAvahi::doPublishService: client not running, queued for publishing
2020-10-27 21:56:19.834 T:7953    DEBUG <general>: CZeroconfAvahi::doPublishService identifier: servers.jsonrpc-tpc type: _xbmc-jsonrpc._tcp name:Kodi (xbmc) port:9090
2020-10-27 21:56:19.834 T:7953    DEBUG <general>: CZeroconfAvahi::doPublishService: client not running, queued for publishing
2020-10-27 21:56:19.893 T:7972    DEBUG <general>: CRecentlyAddedJob::UpdateTotal() - Running RecentlyAdded home screen update
2020-10-27 21:56:24.707 T:7962    DEBUG <general>: Version Check: Version installed {'major': 19, 'minor': 0, 'revision': '20201027-ac48ff40d0', 'tag': 'alpha', 'tagversion': '2'}
2020-10-27 21:56:24.707 T:7962     INFO <general>: CPythonInvoker(0, /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py): script successfully run
2020-10-27 21:56:24.707 T:7962    DEBUG <general>: onExecutionDone(0, /home/xbmc/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py)
2020-10-27 21:56:24.710 T:7962    DEBUG <general>: .
2020-10-27 21:56:24.716 T:7962     INFO <general>: Python interpreter stopped
2020-10-27 21:56:24.716 T:7962    DEBUG <general>: Thread LanguageInvoker 140083889948224 terminating
2020-10-27 21:56:49.711 T:7951    DEBUG <general>: Thread JobWorker 140084467246656 terminating (autodelete)
2020-10-27 21:56:49.834 T:7953    DEBUG <general>: Thread JobWorker 140084232959552 terminating (autodelete)
2020-10-27 21:56:49.978 T:7972    DEBUG <general>: Thread JobWorker 140083378255424 terminating (autodelete)
2020-10-27 21:56:50.921 T:7954    DEBUG <general>: Thread JobWorker 140084224566848 terminating (autodelete)
2020-10-27 21:57:52.213 T:7938     INFO <general>: Samba is idle. Closing the remaining connections
2020-10-27 21:59:19.524 T:7938    DEBUG <general>: ------ Window Init () ------
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

n/a

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

n/a

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubunto Groovy
 - Kodi version: 19.3prealpha (git 8d9b4565)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by lrusak**
This is part of a larger cleanup to check for nullptr for `CServiceBroker` items. However I consider this part a bug fix for V19.

On linux we allow running from the build directory but we look in the install directory for the settings definitions. This can result in a settings mismatch which can result in a segfault if `nullptr` isn't checked when requesting the setting. This will fix #18657 

Ultimately we shouldn't segfault if a setting doesn't exist or cannot be found.

The ones in this PR I just fixed by looking for `GetSetting\(.*\)->`. You will see a pattern that I tried to follow for all changed areas.

### CODE REVIEW

File: xbmc/network/upnp/UPnPInternal.cpp [hunk 1]
```diff
@@ -649,20 +661,28 @@ BuildObject(CFileItem&                    item,
...
-            std::string preferredLanguage = (CServiceBroker::GetSettingsComponent()->GetSettings()->GetSetting("locale.subtitlelanguage"))->ToString();
-            std::string preferredLanguageCode;
-            g_LangCodeExpander.ConvertToISO6392B(preferredLanguage, preferredLanguageCode);
+          std::string preferredLanguage{"en"};
 
-            for (unsigned int i = 0; i < subtitles.size(); i++)
-            {
-                ExternalStreamInfo info = CUtil::GetExternalStreamDetailsFromFilename(file_path.GetChars(), subtitles[i]);
+          /* trying to find subtitle with prefered language settings */
+          auto setting = settings->GetSetting("locale.subtitlelanguage");
```
Comment (fuzzard) [inline xbmc/network/upnp/UPnPInternal.cpp:667]: Is there a potential concern about the lifetime of settings pointer object in a multi threaded life?
Theres a few for loops scattered through some of the code paths up to this point. Do we need to worry that settings may get blown away by another thread (technically only on shutdown i guess really?) before getting called here?

**Comment by fuzzard** [comment]
Everything except the upnp commit looks solid imo.
I guess the upnp one may just be a calculated risk/assumption we carry maybe

File: xbmc/network/upnp/UPnPInternal.cpp (hunk 1 above)
Comment (lrusak) [reply xbmc/network/upnp/UPnPInternal.cpp:667]: I don't think so really. Settings is such a fundamental part that if it ever went away on use we _should_ fail.

**Comment by lrusak** [comment]
> Everything except the upnp commit looks solid imo.
> I guess the upnp one may just be a calculated risk/assumption we carry maybe

I agree. clang-format did me dirty on that one a bit. If desired I can move the formatting to another commit.

File: xbmc/network/upnp/UPnPInternal.cpp (hunk 1 above)
Comment (fuzzard) [reply xbmc/network/upnp/UPnPInternal.cpp:667]: all good then

**Comment by fuzzard** [comment]
I think it will be fine as is. Hide whitespace gets you to the actual changes ok

**Review by garbear — APPROVED** [review]
PR does what it says. No surprises when reading the diff. +1

**Review by DaveTBlake — APPROVED** [review]
Your button @lrusak
