### PR TITLE
[Xbox] Fix crash when DisplayInformation it's called from other thread

### LINKED ISSUE #25015: Kodi Omega Crashes on Xbox When Receiving JSON Command
### Describe the bug
Here is a clear and concise description of what the problem is:

After upgrading from v20.5 to v21 on my Xbox when attempting to navigate to the settings section of the official iOS remote app (by pressing the ...more button on the right hand pane) which makes a JSON command Kodi on my Xbox will freeze and then crash to the home screen within a few seconds.  I then get an error message on my iPhone.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The ...more button should run a JSON command on Kodi and return the settings available to the iOS app.

## Actual Behavior

Instead of the app receiving the results of the JSON command Kodi crashes on Xbox and the iOS app errors out.

### To Reproduce

1. With iOS app navigate to the settings pane (right most pane).
2. Press the ...more button.

1. Alternatively I presume just sending the JSON command `{"jsonrpc":"2.0","method":"Settings.GetSections","params":{"level":"expert"}, "id":2}` from any other device to Kodi on Xbox.

### Debuglog

The debuglog can be found here:  https://paste.kodi.tv/pidofupeje

### Screenshots 
Here are some links or screenshots to help explain the problem:

IMG-9148

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

JSON command triggering the issue:

`{"jsonrpc":"2.0","method":"Settings.GetSections","params":{"level":"expert"}, "id":2}`

What I derived from the debuglog (last two lines) before the crash occurs:

2024-04-14 20:28:43.901 T:7572 debug <CWebserver[8080]>: request received for /jsonrpc
2024-04-14 20:28:43.901 T:7940 error <general>: CActiveAESink::OutputSamples - sink returned error 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: Xbox One S
 - Kodi version: Omega

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
[Xbox] Fix crash when `DisplayInformation::GetForCurrentView()` it's called from other thread

Fixes https://github.com/xbmc/xbmc/issues/25015

## Motivation and context
As Microsoft says this method only is allowed in current thread (graphics thread):

> Gets the DisplayInformation instance associated with the current thread's CoreApplicationView. This DisplayInformation instance is tied to the view and cannot be used from other threads.

https://learn.microsoft.com/en-us/uwp/api/windows.graphics.display.displayinformation.getforcurrentview?view=winrt-22621

This always is fulfilled except when is invoked from JSON Command (web interface / remote controls) that produces the crash.

As only is affected `IsHDRDisplay` and `HasSystemSdrPeakLuminance` and those are hardware/system related proprieties that is not expected to change during same execution, the fix consists on use cached values when is called from another thread (JSON Commands only).

## How has this been tested?
Runtime tested Xbox Series S querying settings with web interface Chorus2. 

Confirmed crash before and not crash after.

## What is the effect on users?
Fix crash on Xbox when retrieving Settings with JSON commands / remote control apps or web interface. 

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/windowing/win10/WinSystemWin10.cpp [hunk 1]
```diff
@@ -692,7 +692,14 @@ float CWinSystemWin10::GetGuiSdrPeakLuminance() const
 */
 bool CWinSystemWin10::HasSystemSdrPeakLuminance()
 {
-  return CWIN32Util::GetSystemSdrWhiteLevel(std::wstring(), nullptr);
+  if (m_threadId == GetCurrentThreadId())
```
Comment (CrystalP) [inline xbmc/windowing/win10/WinSystemWin10.cpp:695]: Since the reason for this PR is multithreading, should catch cases where the window hasn't been initialized yet (just in case) to assert or log.

It doesn't look like any assumption can be made about the values of m_threadId, nothing in the doc says it cannot be 0
That would means a separate bool for validity or a more modern std::optional<DWORD>

Same comment for IsHDRDisplay().

**Review by CrystalP — COMMENTED** [review]
Quick and straightforward change.

File: xbmc/windowing/win10/WinSystemWin10.cpp (hunk 1 above)
Comment (thexai) [reply xbmc/windowing/win10/WinSystemWin10.cpp:695]: > the API cannot return errors and 0 is not a special value for "invalid".
> That would means a separate bool for validity or a more modern std::optional

This is not necessary because threadId never can be 0:

> The [CreateThread](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createthread) and [CreateRemoteThread](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createremotethread) functions also return an identifier that uniquely identifies the thread throughout the system. A thread can use the [GetCurrentThreadId](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getcurrentthreadid) function to get its own thread identifier. The identifiers are valid from the time the thread is created until the thread has been terminated. **Note that no thread identifier will ever be 0.**

https://learn.microsoft.com/en-us/windows/win32/procthread/thread-handles-and-identifiers

Comment (CrystalP) [reply xbmc/windowing/win10/WinSystemWin10.cpp:695]: OK I stand corrected. Is there a THREAD_INVALID or other define that would be a little better than hardcoding 0?

File: xbmc/windowing/win10/WinSystemWin10DX.cpp [hunk 2]
```diff
@@ -61,6 +61,10 @@ bool CWinSystemWin10DX::CreateNewWindow(const std::string& name, bool fullScreen
   m_deviceResources = DX::DeviceResources::Get();
   m_deviceResources->SetWindow(m_coreWindow);
 
+  m_uiThreadId = GetCurrentThreadId();
+  IsHDRDisplay();
+  HasSystemSdrPeakLuminance();
```
Comment (CrystalP) [inline xbmc/windowing/win10/WinSystemWin10DX.cpp:66]: I trust that you runtime tested that those calls are valid before the window creation.
Please add a comment that the calls exist to initialize the cached values. It's weird to throw away the returned values otherwise.

File: xbmc/windowing/win10/WinSystemWin10.cpp (hunk 1 above)
Comment (thexai) [reply xbmc/windowing/win10/WinSystemWin10.cpp]: Not that I know

**Review by CrystalP — APPROVED** [review]
LGTM

**Comment by thexai** [comment]
jenkins build this please

File: xbmc/windowing/win10/WinSystemWin10DX.cpp (hunk 2 above)
Comment (thexai) [reply xbmc/windowing/win10/WinSystemWin10DX.cpp:70]: Done
