### PR TITLE
[Video][Stacks] Fix file stacks only play first part of stack from home screen.

### LINKED ISSUE #24812: File stacks only play first part of stack from home screen in v21
### Describe the bug
Here is a clear and concise description of what the problem is:

File stacks only play first part of stack from home screen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The entire stack should play.

## Actual Behavior

Only the first part plays.

## Possible Fix

PR #24813 

### To Reproduce

Create a file stack (in this case 4 parts about 30m each)
Play from the home screen

image

(The info at the bottom is correct but the progress bar reflects only the first item).

On the play progress bar you can see it's only the first part.

image

In v20 (and with proposed fix) the whole stack is properly played.

image

### Debuglog

https://paste.kodi.tv/xocifelemo.kodi

### Screenshots 

As above.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 11 x64
 - Kodi version: 21b3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Alternative version of #24813. Fixes #24812.

Doesn't involve changing what was passed through the playchain as Path, it simply transmits DynPath as well (as a param) and then uses DynPath in stack related routines.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by ksooo — DISMISSED** [review]
Just had a quick look and think this needs to be fixed in a different way. For example setting item's dynpath at a “random” place feels not correct.

File: xbmc/FileItem.cpp [hunk 1]
```diff
@@ -1270,7 +1270,7 @@ bool CFileItem::IsAndroidApp() const
 
 bool CFileItem::IsStack() const
 {
-  return URIUtils::IsStack(m_strPath);
+  return URIUtils::IsStack(m_strPath) || URIUtils::IsStack(m_strDynPath);
```
Comment (enen92) [inline xbmc/FileItem.cpp:1273]: `return URIUtils::IsStack(GetDynPath())`

File: xbmc/utils/ExecString.cpp [hunk 2]
```diff
@@ -48,6 +48,9 @@ CExecString::CExecString(const std::string& function,
   if (!param.empty())
     m_params.emplace_back(param);
 
+  m_params.emplace_back(
```
Comment (enen92) [inline xbmc/utils/ExecString.cpp:51]: please drop

File: xbmc/utils/ExecString.cpp [hunk 3]
```diff
@@ -108,7 +111,7 @@ void SplitParams(const std::string& paramString, std::vector<std::string>& param
           if (quotaPos > 1 && quotaPos < parameter.length() - 1 && parameter[quotaPos - 1] == '=')
           {
             parameter.erase(parameter.length() - 1);
-            parameter.erase(quotaPos);
+            parameter.erase(quotaPos, 1);
```
Comment (enen92) [inline xbmc/utils/ExecString.cpp:114]: please drop

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp [hunk 4]
```diff
@@ -506,6 +506,10 @@ int PlayOrQueueMedia(const std::vector<std::string>& params, bool forcePlay)
       // If app player is currently playing, the queued media shall be played next.
       playNext = true;
     }
+    else if (StringUtils::EqualsNoCase(params[i], "dynpath"))
```
Comment (enen92) [inline xbmc/interfaces/builtins/PlayerBuiltins.cpp:509]: please drop

**Review by enen92 — CHANGES_REQUESTED** [review]
Most of the changes seem logical. I've runtime tested this without your dynpath hacks (I mean those comments I mention "please drop") and it seems to work just fine.
Any reason you decided to added that?

File: xbmc/utils/ExecString.cpp (hunk 3 above)
Comment (78andyp) [reply xbmc/utils/ExecString.cpp:114]: That's needed - it's a bug. That part of ExecString seems to exist to remove the quotes, but without the ,1 it removes the entire rest of the string.

**Comment by 78andyp** [comment]
> > parameter.erase(quotaPos);
> 
> Yeap it works fine for me. Here What's I'm running:
> 
> ```
> From 85f5ab9ee37284d40130b1078b771d208e3fa38b Mon Sep 17 00:00:00 2001
> From: 78andyp <drandypowell@live.co.uk>
> Date: Fri, 8 Mar 2024 00:52:31 +0000
> Subject: [PATCH] [Video][Stacks] Fix file stacks only play first part of stack
>  from home screen (alternative version).
> 
> ---
>  xbmc/FileItem.cpp                           |  2 +-
>  xbmc/application/ApplicationStackHelper.cpp | 31 +++++++++++----------
>  xbmc/interfaces/builtins/PlayerBuiltins.cpp | 12 +-------
>  3 files changed, 18 insertions(+), 27 deletions(-)
> 
> diff --git a/xbmc/FileItem.cpp b/xbmc/FileItem.cpp
> index fcbacd8bfe..239d4325ab 100644
> --- a/xbmc/FileItem.cpp
> +++ b/xbmc/FileItem.cpp
> @@ -1270,7 +1270,7 @@ bool CFileItem::IsAndroidApp() const
>  
>  bool CFileItem::IsStack() const
>  {
> -  return URIUtils::IsStack(m_strPath);
> +  return URIUtils::IsStack(GetDynPath());
>  }
>  
>  bool CFileItem::IsFavourite() const
> diff --git a/xbmc/application/ApplicationStackHelper.cpp b/xbmc/application/ApplicationStackHelper.cpp
> index f8070c0d1e..4e62388a62 100644
> --- a/xbmc/application/ApplicationStackHelper.cpp
> +++ b/xbmc/application/ApplicationStackHelper.cpp
> @@ -67,7 +67,8 @@ bool CApplicationStackHelper::InitializeStack(const CFileItem & item)
>    Clear();
>    // read and determine kind of stack
>    CStackDirectory dir;
> -  if (!dir.GetDirectory(item.GetURL(), *m_currentStack) || m_currentStack->IsEmpty())
> +  CURL path{item.GetDynPath()};
> +  if (!dir.GetDirectory(path, *m_currentStack) || m_currentStack->IsEmpty())
>      return false;
>    for (int i = 0; i < m_currentStack->Size(); i++)
>    {
> @@ -98,7 +99,7 @@ int CApplicationStackHelper::InitializeStackStartPartAndOffset(const CFileItem&
>        if (dbs.Open())
>        {
>          CBookmark bookmark;
> -        std::string path = item.GetPath();
> +        std::string path = item.GetDynPath();
>          if (item.HasProperty("original_listitem_url") && URIUtils::IsPlugin(item.GetProperty("original_listitem_url").asString()))
>            path = item.GetProperty("original_listitem_url").asString();
>          if (dbs.GetResumeBookMark(path, bookmark))
> @@ -143,7 +144,7 @@ int CApplicationStackHelper::InitializeStackStartPartAndOffset(const CFileItem&
>  
>      if (dbs.Open())
>      {
> -      haveTimes = dbs.GetStackTimes(item.GetPath(), times);
> +      haveTimes = dbs.GetStackTimes(item.GetDynPath(), times);
>        dbs.Close();
>      }
>  
> @@ -159,7 +160,7 @@ int CApplicationStackHelper::InitializeStackStartPartAndOffset(const CFileItem&
>        else
>        {
>          int duration;
> -        if (!CDVDFileInfo::GetFileDuration(GetStackPartFileItem(i).GetPath(), duration))
> +        if (!CDVDFileInfo::GetFileDuration(GetStackPartFileItem(i).GetDynPath(), duration))
>          {
>            m_currentStack->Clear();
>            return false;
> @@ -185,13 +186,13 @@ int CApplicationStackHelper::InitializeStackStartPartAndOffset(const CFileItem&
>        {
>          // have our times now, so update the dB
>          if (!haveTimes && !times.empty())
> -          dbs.SetStackTimes(item.GetPath(), times);
> +          dbs.SetStackTimes(item.GetDynPath(), times);
>  
>          if (item.GetStartOffset() == STARTOFFSET_RESUME)
>          {
>            // can only resume seek here, not dvdstate
>            CBookmark bookmark;
> -          std::string path = item.GetPath();
> +          std::string path = item.GetDynPath();
>            if (item.HasProperty("original_listitem_url") && URIUtils::IsPlugin(item.GetProperty("original_listitem_url").asString()))
>              path = item.GetProperty("original_listitem_url").asString();
>            if (dbs.GetResumeBookMark(path, bookmark))
> @@ -256,19 +257,19 @@ void CApplicationStackHelper::ClearAllRegisteredStackInformation()
>  std::shared_ptr<const CFileItem> CApplicationStackHelper::GetRegisteredStack(
>      const CFileItem& item) const
>  {
> -  return GetStackPartInformation(item.GetPath())->m_pStack;
> +  return GetStackPartInformation(item.GetDynPath())->m_pStack;
>  }
>  
>  bool CApplicationStackHelper::HasRegisteredStack(const CFileItem& item) const
>  {
> -  const auto it = m_stackmap.find(item.GetPath());
> +  const auto it = m_stackmap.find(item.GetDynPath());
>    return it != m_stackmap.end() && it->second != nullptr;
>  }
>  
>  void CApplicationStackHelper::SetRegisteredStack(const CFileItem& item,
>                                                   std::shared_ptr<CFileItem> stackItem)
>  {
> -  GetStackPartInformation(item.GetPath())->m_pStack = std::move(stackItem);
> +  GetStackPartInformation(item.GetDynPath())->m_pStack = std::move(stackItem);
>  }
>  
>  CFileItem& CApplicationStackHelper::GetStackPartFileItem(int partNumber)
> @@ -283,32 +284,32 @@ const CFileItem& CApplicationStackHelper::GetStackPartFileItem(int partNumber) c
>  
>  int CApplicationStackHelper::GetRegisteredStackPartNumber(const CFileItem& item)
>  {
> -  return GetStackPartInformation(item.GetPath())->m_lStackPartNumber;
> +  return GetStackPartInformation(item.GetDynPath())->m_lStackPartNumber;
>  }
>  
>  void CApplicationStackHelper::SetRegisteredStackPartNumber(const CFileItem& item, int partNumber)
>  {
> -  GetStackPartInformation(item.GetPath())->m_lStackPartNumber = partNumber;
> +  GetStackPartInformation(item.GetDynPath())->m_lStackPartNumber = partNumber;
>  }
>  
>  uint64_t CApplicationStackHelper::GetRegisteredStackPartStartTimeMs(const CFileItem& item) const
>  {
> -  return GetStackPartInformation(item.GetPath())->m_lStackPartStartTimeMs;
> +  return GetStackPartInformation(item.GetDynPath())->m_lStackPartStartTimeMs;
>  }
>  
>  void CApplicationStackHelper::SetRegisteredStackPartStartTimeMs(const CFileItem& item, uint64_t startTime)
>  {
> -  GetStackPartInformation(item.GetPath())->m_lStackPartStartTimeMs = startTime;
> +  GetStackPartInformation(item.GetDynPath())->m_lStackPartStartTimeMs = startTime;
>  }
>  
>  uint64_t CApplicationStackHelper::GetRegisteredStackTotalTimeMs(const CFileItem& item) const
>  {
> -  return GetStackPartInformation(item.GetPath())->m_lStackTotalTimeMs;
> +  return GetStackPartInformation(item.GetDynPath())->m_lStackTotalTimeMs;
>  }
>  
>  void CApplicationStackHelper::SetRegisteredStackTotalTimeMs(const CFileItem& item, uint64_t totalTime)
>  {
> -  GetStackPartInformation(item.GetPath())->m_lStackTotalTimeMs = totalTime;
> +  GetStackPartInformation(item.GetDynPath())->m_lStackTotalTimeMs = totalTime;
>  }
>  
>  CApplicationStackHelper::StackPartInformationPtr CApplicationStackHelper::GetStackPartInformation(
> diff --git a/xbmc/interfaces/builtins/PlayerBuiltins.cpp b/xbmc/interfaces/builtins/PlayerBuiltins.cpp
> index 18c84ed114..61fd216a1a 100644
> --- a/xbmc/interfaces/builtins/PlayerBuiltins.cpp
> +++ b/xbmc/interfaces/builtins/PlayerBuiltins.cpp
> @@ -527,17 +527,7 @@ int PlayOrQueueMedia(const std::vector<std::string>& params, bool forcePlay)
>    }
>    item.SetProperty("check_resume", false);
>  
> -  if (item.IsStack())
> -  {
> -    const VIDEO_UTILS::ResumeInformation resumeInfo =
> -        VIDEO_UTILS::GetStackPartResumeInformation(item, playOffset + 1);
> -
> -    if (item.GetStartOffset() == STARTOFFSET_RESUME)
> -      item.SetStartOffset(resumeInfo.startOffset);
> -
> -    item.m_lStartPartNumber = resumeInfo.partNumber;
> -  }
> -  else if (!forcePlay /* queue */ || item.m_bIsFolder || item.IsPlayList())
> +  if (!forcePlay /* queue */ || item.m_bIsFolder || item.IsPlayList())
>    {
>      CFileItemList items;
>      GetItemsForPlayList(std::make_shared<CFileItem>(item), items);
> -- 
> 2.43.2
> ```

You're right! Sorry, I must have gotten confused about what changes did what.
I'll force push an update now.
Thank you :)

File: xbmc/utils/ExecString.cpp (hunk 3 above)
Comment (78andyp) [reply xbmc/utils/ExecString.cpp:111]: Or would you like this in a seperate PR??

**Comment by ksooo** [comment]
Guys, please let me have a look at this issue. Not sure, but I think there could be a simpler fix possible. The changes made here seem a bit "invasive" so I'm hesitant to put this into v21.

**Comment by enen92** [comment]
@ksooo we've branched already, any PR targetting master is now effectively for v22 (anything for omega has to be backported). I agree this is too invasive for v21 although the changes from a logical POV are correct and perfectly fine for v22 at this point.

Probably we want a simple/localized fix for v21 even if it is some "hack", as long as properly fixed in master.

File: xbmc/FileItem.cpp [hunk 5]
```diff
@@ -1270,7 +1270,7 @@ bool CFileItem::IsAndroidApp() const
 
 bool CFileItem::IsStack() const
 {
-  return URIUtils::IsStack(m_strPath);
+  return URIUtils::IsStack(m_strDynPath);
```
Comment (enen92) [inline xbmc/FileItem.cpp:1273]: Please use `GetDynPath()` like in my patch since it defers to m_strPath if m_strDynPath is not yet populated.

Comment (78andyp) [reply xbmc/FileItem.cpp]: Done

**Review by enen92 — APPROVED** [review]
Thanks, it looks good for v22. Let's wait for ksooo review and for a more self contained v21 fix.

**Review by ksooo — COMMENTED** [review]
> we've branched already, any PR targetting master is now effectively for v22

okay for me, then.

File: xbmc/FileItem.cpp [hunk 6]
```diff
@@ -1270,7 +1270,7 @@ bool CFileItem::IsAndroidApp() const
 
 bool CFileItem::IsStack() const
 {
-  return URIUtils::IsStack(m_strPath);
+  return URIUtils::IsStack(GetDynPath());
```
Comment (ksooo) [inline xbmc/FileItem.cpp:1273]: Just saying that all (?) `CFileItem::Is`methods working on `m_strPath`. With this change this method now is the exception. Not saying this is wrong, but looks like a big inconsistency.

Comment (enen92) [reply xbmc/FileItem.cpp:1273]: I think in the end, if we think hard enough about obscure use-cases the others may be in fact wrong. It's not by chance that all these misbehaviours happen we we start moving constant paths to playlists (e.g. strm files) or paths are served from plugins which need resolution.
I mean it may cause regressions but from a logical POV IsStack applied to a CFileItem should look always first to the dynpath (may have been resolved) and only after that to the path (signature of the item). If that is not the intended behaviour the client code should invoke `URIUtils::IsStack` directly with the path it wishes to check.
I think the comment may not be necessary here

Comment (ksooo) [reply xbmc/FileItem.cpp:1273]: > if we think hard enough about obscure use-cases the others may be in fact wrong.

I tend to agree.

**Comment by enen92** [comment]
@78andyp Thanks for your contribution! Merging
