### PR TITLE
[Settings] Fix setting conditions regressions

### LINKED ISSUE #22918: Addon settings with multiple dependencies conditions fails
### Describe the bug
Here is a clear and concise description of what the problem is:

I have an addon with these settings conditions

```xml
                <setting id="enable_vp9_profiles" type="boolean" label="30137" help="">
                    <level>0</level>
                    <default>false</default>
                    <control type="toggle"/>
                </setting>
                <setting id="enable_vp9.2_profiles" type="boolean" label="30741" help="" parent="enable_vp9_profiles">
                    <level>0</level>
                    <default>false</default>
                    <control type="toggle"/>
                    <dependencies> <!-- Feature available on Kodi v21 or above -->
                        <dependency type="visible">
                            <and>
                                <or>
                                    <condition on="property" operator="is" name="InfoBool">String.StartsWith(System.BuildVersionCode,20.9)</condition> <!-- v21 pre-releases -->
                                    <condition on="property" operator="is" name="InfoBool">Integer.IsGreaterOrEqual(System.BuildVersionCode,21)</condition>
                                </or>
                                <condition setting="enable_vp9_profiles">true</condition>
                            </and>
                        </dependency>
                    </dependencies>
                </setting>
```

these seems to works correctly on Kodi v20 but on current master branch (Kodi 21) fails

the menu `enable_vp9.2_profiles` is shown correclty when the initial/saved value of `enable_vp9_profiles` setting is True before opening addon settings window,
if the initial/saved value of `enable_vp9_profiles` setting is False before opening addon settings window then the menu `enable_vp9.2_profiles` is kept hidden

Following video recording show the problem
https://www.dropbox.com/s/nk5g4lgwa8eczuw/Kodi21SettingsMenuBroken.mkv?dl=0

UPDATE:
another example that have same problem similar to above:

```xml
                <setting id="blackbars_minimizer_value" type="integer" label="30721" help="30724" parent="blackbars_minimizer_mode">
                    <level>0</level>
                    <default>0</default>
                    <constraints>
                        <minimum>0</minimum>
                        <step>1</step>
                        <maximum>50</maximum>
                    </constraints>
                    <dependencies>
                        <dependency type="visible">
                          <or>
                              <condition setting="blackbars_minimizer_mode">fixed</condition>
                              <condition setting="blackbars_minimizer_mode">relative</condition>
                          </or>
                        </dependency>
                    </dependencies>
                    <control type="slider" format="percentage"/>
                </setting>
```

### To Reproduce

1. add xml setting above to an addon
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/hiyodogife.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Kodi master branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Fix settings conditions regressions that are broken

## Motivation and context

the recent PR #22808 has introduced a regression that have broken settings conditions,
at least on python add-ons conditions dont works anymore correctly
the side effect can be shown here: https://www.dropbox.com/s/nk5g4lgwa8eczuw/Kodi21SettingsMenuBroken.mkv?dl=0

fix #22918

## How has this been tested?

i attached two examples in the issue #22918

## What is the effect on users?

Have a working conditions settings

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/settings/lib/SettingSection.h [hunk 1]
```diff
@@ -56,6 +56,14 @@ class CSettingGroup : public ISetting
    */
   SettingList GetSettings(SettingLevel level) const;
 
+  /*
+   * \brief Determine if there are visible settings assigned to the given setting level (or below)
+   *        and that meet the requirements conditions belonging to the setting group.
```
Comment (enen92) [inline xbmc/settings/lib/SettingSection.h:61]:
```suggestion
   *        and that they meet the requirements conditions belonging to the setting group.
```

**Review by enen92 — APPROVED** [review]
LGTM

File: xbmc/settings/lib/SettingSection.cpp [hunk 2]
```diff
@@ -158,13 +158,20 @@ SettingList CSettingGroup::GetSettings(SettingLevel level) const
...
   {
-    if (setting->GetLevel() <= level && setting->MeetsRequirements() && setting->IsVisible())
+    if (setting->GetLevel() <= level && setting->MeetsRequirements())
       settings.push_back(setting);
   }
 
   return settings;
 }
 
+bool CSettingGroup::ContainsVisibleSettings(SettingLevel level) const
```
Comment (CrystalP) [inline xbmc/settings/lib/SettingSection.cpp:168]: const SettingLevel level?

**Review by CrystalP — APPROVED** [review]
Oops sorry! It's not a situation I was aware of. The video was great to explain it.
Looks good to me.

File: xbmc/settings/lib/SettingSection.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/settings/lib/SettingSection.cpp]: done
