### PR TITLE
[video] Fix #14847 - Take 3 ;-)

### LINKED ISSUE #14847: Losing Resume Point once leaving directory when play next file automatically is ticked.
### Describe the bug
Here is a clear and concise description of what the problem is:

start watching something you get a resume point if you exit the video. you can resume multiple times fine but as soon as you leave the directory of the show it loses its video resume point so you need to start from the beginning again.

if you turn off play next video automatically then everything works fine you can leave and reenter and the video resume point is not lost. but with play next video automatically its broken and loses resume point once you leave the directory it also seems to only affect library added content in "tv shows" and "movies" if you browse via video tab and play video and leave reenter its fine also even with play next video automatically enabled. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

resume point should not be lost reset regardless if you leave the directory like old 17.6 behaviour hence we have some regression here which has appeared in all v18 builds alpha 1+ and has never been fixed.

## Actual Behavior

resume point is lost when you leave the directory if play next file automatically is ticked.

## Possible Fix

i wish i knew this is driving me crazy i assume its to do with play next file automatically code as with it unticked it all works fine.

### To Reproduce

1.  home screen select TV Shows hit enter the tv shows are listed pick any,  
2. episode list shows up with episodes for that tv show. start it skip forward 1/2 way now press stop, youll see a resume point.
3. now press back to exit episode list back to tv shows listing now select that tv show again. the episode you skipped 1/2 way through the resume point is lost if you select it now it starts from the beginning. 

### Debuglog

The debuglog can be found here:
https://paste.ubuntu.com/p/fMnKJMhsS5/
https://paste.ubuntu.com/p/5kXFkcMSnC/

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

https://trac.kodi.tv/ticket/17857
https://forum.kodi.tv/showthread.php?tid=331246

### Your Environment
Used Operating system:

 - [x] Android
 - [x] iOS
 - [x] Linux
 - [x] OSX
 - [x] Raspberri-Pi
 - [x] Windows
 - [x] Windows UWP

affects all platforms.

 - Operating system version/name:
 - Kodi version: 
v18 alpha1 -> beta 5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
CSaveFileState::DoWork: For videodb items, use m_strFileNameAndPath, not GetPath(). Fixes #14847.

Take 3. Supercedes #14862, fixes #14847 - this time without path manipulation of existing item.

@FernetMenta this one should actually be good to go - no hacks this time, imo. ;-)

### CODE REVIEW

File: xbmc/utils/SaveFileStateJob.cpp [hunk 1]
```diff
@@ -35,6 +35,8 @@ void CSaveFileState::DoWork(CFileItem& item,
 
   if (item.HasVideoInfoTag() && StringUtils::StartsWith(item.GetVideoInfoTag()->m_strFileNameAndPath, "removable://"))
     progressTrackingFile = item.GetVideoInfoTag()->m_strFileNameAndPath; // this variable contains removable:// suffixed by disc label+uniqueid or is empty if label not uniquely identified
+  else if (item.HasVideoInfoTag() && item.IsVideoDb())
+    progressTrackingFile = item.GetVideoInfoTag()->m_strFileNameAndPath; // we need the file url of the video db item to create the bookmark
```
Comment (FernetMenta) [inline xbmc/utils/SaveFileStateJob.cpp]: This could be a potential fix but SaveFileState stores more info than just bookmarks, doesn't it? If this is the case, those other infos can't be accessed anymore.
Another solution could be to use item's path to query bookmarks:
https://github.com/xbmc/xbmc/blob/master/xbmc/video/windows/GUIWindowVideoBase.cpp#L569
That would drop the 7 year old hack done for some reason nobody remembers and aligns DB items with the rest of the code.

Comment (ksooo) [reply xbmc/utils/SaveFileStateJob.cpp]: > This could be a potential fix but SaveFileState stores more info than just bookmarks, doesn't it? If this is the case, those other infos can't be accessed anymore.

 Yes and no, I checked that very careful and all other methods called with `progressTrackingFile` for videos are also expecting `filenenameandpath` instead `videodburl`. So, my fix also fixes the other places. It all turns down to the video database scheme...

> Another solution could be to use item's path to query bookmarks

 Yeah, that's the best approach, but unfortunately this will require a video database change that will break all existing bookmarks (and other stored data, like play count). Not a good idea for v18, but definitely good for v19.

Comment (FernetMenta) [reply xbmc/utils/SaveFileStateJob.cpp]: ok
