### PR TITLE
[ActiveAESink] Improves sinks enumeration names and fallback logic when exact sink name not exists

### LINKED ISSUE #21852: Passthrough output device randomly reverts from WASAPI to DIRECTSOUND, killing bitstream
### Describe the bug
Here is a clear and concise description of what the problem is:

I use Kodi on Windows in combination with a Denon AV receiver that is capable of playing all manner of bitstreamed audio formats up to and including Dolby Atmos.  In order for formats like Dolby Atmos to work, you must select "WASAPI: HDMI - DENON-AVRHD" in Settings -> System -> Audio -> Passthrough output device, and then tick the checkboxes for the formats your receiver supports.  In my case, all of them.

I leave "Audio output device" in the same area (System -> Settings -> Audio) set to "DIRECTSOUND: HDMI - DENON-AVRHD" as this provides the best compatibility for Kodi interface sounds.  However, this is a separate setting from "Passthrough output device"

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The passthrough output device in Settings -> System -> Audio should keep its setting.

## Actual Behavior

About once a month, I find that Kodi has stopped bitstreaming and is instead sending linear PCM audio, often downmixed (such as in the case of Dolby Atmos.)  The cure is always the same: I have to go into the settings and change "Passthrough output device" under System -> Audio back to WASAPI, as it has changed to DIRECTSOUND.

### To Reproduce

1.) Set Kodi passthrough output device to WASAPI.
2.) Use it for a few months.
3.) Observe that at random intervals, it will change itself to DIRECTSOUND.

### Debuglog

The debuglog can be found here:

I can't figure out how to generate this, any assistance would be appreciated.

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 21H2
 - Kodi version: 19.4

I am currently using Windows 11 21H2 and Kodi 19.4, however this issue has persisted across Windows 7, Windows 10, and Windows 11.  It has affected every version of Kodi 19.x including the most recent release at this time, 19.4.  It has done this on three different HTPCs (one Win 7, one Win 10, and my current Win 11 setup.)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
- Improves `CAESinkFactory::ParseDevice` returning values in a struct instead parameters by reference. Also avoids use same "device" parameter as input/output which is confusing and requires make a copy to avoids get overwrited in some places.
- Appends sink friendly name to sink string when is different from sink name. e.g:

  Before
  `WASAPI:{B12C1A75-F8A8-4071-8CFB-A285C619CCB8}`
    
  After
  `WASAPI:{B12C1A75-F8A8-4071-8CFB-A285C619CCB8}:HDMI - DENON-AVR (NVIDIA High Definition Audio)`

- When open sink by name (GUID in Windows) and exact match not found, fallback using friendly name.
- Saved settings are not modified unless user opens audio settings.
- When user opens audio settings current device name is "upgraded" and saved in settings, adding friendly name if available.
- Even if current device GUID not exist in system anymore, current setting is not lost because fallback to a device with same friendly name and saved as current "new" device.
- Fixes https://github.com/xbmc/xbmc/issues/21852

## Motivation and context
On Windows sink names are GUIDs and these may change sporadically with Windows Updates or audio drivers updates. When this happens, current logic is fallback to first audio device in list and this breaks passthrough probably because changes from `WASAPI:x` to `DIRECTSOUND:y`

For some users this is just a Kodi bug "Kodi changes sporadically to DIRECTSOUND and breaks passthrough". See https://github.com/xbmc/xbmc/issues/21852 and https://github.com/xbmc/xbmc/issues/22021

Or in forum: https://forum.kodi.tv/showthread.php?tid=373640 or https://forum.kodi.tv/showthread.php?tid=372205

This PR appends friendly device name to setting and, in this way, if GUID changes, same device can be still referenced by friendly name e.g.:

Device saved in settings is:
 `WASAPI:{B12C1A75-F8A8-4071-8CFB-A285C619CCB8}:HDMI - DENON-AVR (NVIDIA High Definition Audio)`

But current system device is:
`WASAPI:{555C1A75-F8A8-4071-8CFB-A285C619CCB8}:HDMI - DENON-AVR (NVIDIA High Definition Audio)`

Kodi can continue operate in this way and saved setting is not altered but a WARNING log message warns of this situation.
When the user realizes (if it happens) he can fix it in settings and if not, nothing happens... the next time the user enters in settings it will fix itself for the simple fact that the current setting has changed and the settings are saved when changes.

Since the current setting can only be one of the list and in the list there are only the devices that currently exist in the system.

After this, "new" saved setting is:
`WASAPI:{555C1A75-F8A8-4071-8CFB-A285C619CCB8}:HDMI - DENON-AVR (NVIDIA High Definition Audio)`

And the warning message in the logs disappears.

All this is designed for backward compatibility, that is, it is not mandatory that the settings have the friendly name. And it is also not expected that the audio device will change by the fact of starting to use Kodi with these changes nor is it expected any significant change in the operation except the improvement when the same exact device does not exist.

Even in the case that the setting does not (yet) have the friendly name there are some improvements in the logic: it will always be preferred to change to a device of the same driver first e.g. from `WASAPI:x` to `WASAPI:default` instead of switching to the first random device (DIRECTSOUND).

Please review commits separately as has useful descriptions.

## How has this been tested?
Runtime tested Windows x64 also in Shield (to look for side effects)

## What is the effect on users?
Avoids in some systems sporadically audio device settings are lost because Windows Updates or audio drivers updates.
In general it improves (much) the fallback logic when the current audio device is not available.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/AudioEngine/AESinkFactory.cpp [hunk 1]
```diff
@@ -38,41 +38,53 @@ bool CAESinkFactory::HasSinks()
...
       found = true;
     }
   }
 
   if (!found)
-    driver.clear();
+    dev.driver.clear();
+
+  pos = dev.name.find_first_of(':');
+  if (pos > 0)
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/AESinkFactory.cpp:66]: This (and the same in existing code earlier) is wrong and works by luck.
Try this function with device=WASAPI:default and you will see pos=18446744073709551615 here and the execution enters the block.
suggestion: `if (pos != std::string::npos)`

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 2]
```diff
@@ -837,6 +837,78 @@ void CActiveAESink::OpenSink()
...
+  // try other device with same driver and same friendly name
+  // is probably the same device renamed due driver update
+  if (!m_sink && !m_sinkInfoList.empty() && !dev.driver.empty() && !dev.friendlyName.empty())
+  {
+    for (const auto& sink : m_sinkInfoList)
+    {
+      if (sink.m_sinkName != dev.driver)
+        continue;
+
+      if (m_sink)
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:849]: When could this be happen? The CAESinkFactory::Create is followed by a break already.

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 3]
```diff
@@ -837,6 +837,78 @@ void CActiveAESink::OpenSink()
...
+        break;
+
+      for (const auto& d : sink.m_deviceInfoList)
+      {
+        if (d.m_displayName == dev.friendlyName || d.m_displayNameExtra == dev.friendlyName)
+        {
+          m_deviceFriendlyName = dev.friendlyName;
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:856]: There is an existing GetDeviceFriendlyName(dev.name) a bit earlier in the function with different logic (uses m_displayName), which way is correct? Maybe it's different for Windows and other platforms.

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 4]
```diff
@@ -837,6 +837,78 @@ void CActiveAESink::OpenSink()
...
+          device = dev.driver + ":" + d.m_deviceName;
+          m_sinkFormat = m_requestedFormat;
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:858]: Seems unnecessary, could it change since the earlier assignment in same function?

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 5]
```diff
@@ -837,6 +837,78 @@ void CActiveAESink::OpenSink()
...
+        {
+          bestMatch = d.m_deviceName;
+          break;
+        }
+      }
+    }
+  }
+  if (!m_sink && !bestMatch.empty())
+  {
+    GetDeviceFriendlyName(bestMatch);
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:900]: consistent with initial assignment to m_deviceFriendlyName but not the previous block (see comment on previous block)

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 6]
```diff
@@ -837,6 +837,78 @@ void CActiveAESink::OpenSink()
...
+    device = dev.driver + ":" + bestMatch;
+    m_sinkFormat = m_requestedFormat;
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:902]: seems unnecessary - same as previous block

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 7]
```diff
@@ -837,6 +837,78 @@ void CActiveAESink::OpenSink()
...
+
+  // try default device of same driver or first device of same driver
+  if (!m_sink && !m_sinkInfoList.empty() && !dev.driver.empty())
+  {
+    for (const auto& sink : m_sinkInfoList)
+    {
+      if (sink.m_sinkName != dev.driver)
+        continue;
+
+      if (!bestMatch.empty())
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:882]: Not effective for early exit because the different driver will cause the loop to continue before reaching this test.
If you really want it, should be placed after the block of `for (const auto& d : sink.m_deviceInfoList)` that may set it to not-empty.

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 8]
```diff
@@ -837,6 +837,78 @@ void CActiveAESink::OpenSink()
...
+
+        if (d.m_deviceName.find("default") != std::string::npos)
+        {
+          bestMatch = d.m_deviceName;
+          break;
+        }
+      }
+    }
+  }
+  if (!m_sink && !bestMatch.empty())
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:898]: separate from previous block with newline please

**Comment by lrusak** [comment]
I don't really have time to review but I did something similar earlier this year. Maybe there is some similarities -> https://github.com/lrusak/xbmc/commit/ab50136ff883cefe02034a15d33c9acbb8d61fe5

I also had some other AE stuff here if you are interested -> https://github.com/lrusak/xbmc/commits/ae-device-selection

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp (hunk 2 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp]: There are two nested loops and it takes two breaks to exit, but it is true that it is better to put it where you say.

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp (hunk 3 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp]: Yes for consistency better always use `GetDeviceFriendlyName` from deviceName

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp (hunk 5 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:901]: Changed all to use GetDeviceFriendlyName

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp (hunk 7 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp]: moved

**Comment by CrystalP** [comment]
Very good improvement for Windows, much better than having the sound device suddenly defaulting to first directsound output after a driver upgrade.

At a high level, looks fine by itself to me but I don't know how well it fits with AE's design.
The logic to find a sink with same friendly name or first/default sink of same driver is duplicated in the sink opening and the audio setting filler. Maybe could be solved by generalizing the arguments and extracting to shared functions.

At a low level, a few style improvements if you have the time:
- A new function like `std::vector<AE::AESinkInfo> CActiveAESink::GetDriverSinks(std::string_view driver) would help remove many copies (new and existing) of code similar to
```
for (auto itt = m_sinkInfoList.begin(); itt != m_sinkInfoList.end(); ++itt)
  {
    if (dev.driver == itt->m_sinkName)
```
- A proper split function in `CAESinkFactory::ParseDevice()`, like in commit https://github.com/lrusak/xbmc/commit/040262f0367127a6634b0ab821ff1e6de18448b5

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESettings.cpp [hunk 9]
```diff
@@ -183,9 +186,66 @@ void CActiveAESettings::SettingOptionsAudioDevicesFillerGeneral(
...
         foundValue = true;
     }
+
+    // partial match of device name OR device frienly name in same driver
+    if (!foundValue)
+    {
+      for (const auto& sink : sinkList)
+      {
+        if (sink.second.find(dev.driver) == std::string::npos)
+          continue;
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESettings.cpp:196]: not a problem in Windows due to the very different strings, but maybe sink.second should be parsed/split first for a more robust comparison with driver or name.
same note about sink.first used a bit later

**Comment by thexai** [comment]
> A new function like `std::vectorAE::AESinkInfo CActiveAESink::GetDriverSinks(std::string_view driver) would help remove many copies (new and existing) of code similar to

Maybe but is not really related to this PR

> A proper split function in CAESinkFactory::ParseDevice(), like in commit https://github.com/lrusak/xbmc/commit/040262f0367127a6634b0ab821ff1e6de18448b5

Note that `CAESinkFactory::ParseDevice` is not a regular string split only: driver and friendlyName are optional and also is check that driver is valid string:  i.e: if you change/hack WASAPI or DIRECTSOUD name stored in settings then is considered no valid and driver reset to "".

**Comment by thexai** [comment]
> The logic to find a sink with same friendly name or first/default sink of same driver is duplicated in the sink opening and the audio setting filler. Maybe could be solved by generalizing the arguments and extracting to shared functions.

Added a fourth commit that consolidates the changes in one place and improves some things. If accepted, the third commit replaces the previous two. The basic functionality is the same but with improvements:

- No attempt is made to open the audio device the first time if it is already known not to exist.
- Saving settings changes is not delayed until the user enters settings.
- The friendly name is also monitored, in case it changes keeping the same device name (this case was not contemplated in the previous commits).
- The logic is in one place so prevents future inconsistencies if it is modified/improved.

File: xbmc/cores/AudioEngine/AESinkFactory.cpp [hunk 10]
```diff
@@ -38,41 +38,55 @@ bool CAESinkFactory::HasSinks()
...
 
-      device = device.substr(pos + 1, device.length() - pos - 1);
+      dev.name = dev.name.substr(pos + 1, dev.name.length() - pos - 1);
       found = true;
     }
   }
 
   if (!found)
-    driver.clear();
+    dev.driver.clear();
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/AESinkFactory.cpp:64]: probably best to return here instead of continuing.
Otherwise when device = "foo:bar" and foo is not a registered driver, we'd end up with driver = "", name = "foo" and friendly name = "bar".

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 11]
```diff
@@ -728,6 +728,111 @@ void CActiveAESink::PrintSinks(std::string& driver)
...
+          // current "physical" name (not name saved in settings)
+          // in this way friendly name is updated over time (drivers updates, etc.)
+          const std::string friendlyName = d.GetFriendlyName();
+          if (!friendlyName.empty())
+          {
+            device.append(":");
+            device.append(friendlyName);
+          }
+
+          return device;
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:762]: Since the purpose of this function is to find best enumerated device, I think it would make sense to create a  member function CAEDeviceInfo::ToDeviceString() that returns a formatted device string instead of the 4x repetition of the string building code in this function.

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 12]
```diff
@@ -728,6 +728,111 @@ void CActiveAESink::PrintSinks(std::string& driver)
...
+        break;
+    }
+  }
+
+  // return first device of same driver
+  if (!firstDevice.empty())
+    return firstDevice;
+
+  // fallback to first device of the list
+  firstDevice = m_sinkInfoList[0].m_sinkName;
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:822]: Please check that m_sinkInfoList and sinkInfoList[0].m_deviceInfoList are not empty first

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp [hunk 13]
```diff
@@ -2670,6 +2674,43 @@ void CActiveAE::LoadSettings()
   m_settings.silenceTimeoutMinutes = settings->GetInt(CSettings::SETTING_AUDIOOUTPUT_STREAMSILENCE);
 }
 
+void CActiveAE::ValidateOutputDevices(bool saveChanges)
+{
+  bool changed{false};
+
+  std::string device = m_sink.ValidateOuputDevice(m_settings.device);
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp:2681]: Probably also needs a passthrough true/false parameter, see in CActiveAESink::EnumerateOutputDevices() how all device PCM and passthrough capabilities are tested.
We don't want to fallback passthrough to a non-passthrough capable device.

**Comment by CrystalP** [comment]
I like the last commit, is there a reason why the device is not validated in CActiveAESink::OpenSink()?
(thinking about a system update  or maybe an output plugged or unplugged while Kodi is running)
I don't have hdmi to test what happens during resolution / refresh rate change, we wouldn't want the validation to fail and find another device for a temporary and expected unavailability of an output.

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESettings.cpp (hunk 9 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESettings.cpp]: This is also solved with the last commit

File: xbmc/cores/AudioEngine/AESinkFactory.cpp (hunk 10 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/AESinkFactory.cpp:64]: Yes, for better compatibility is supposed driver is optional. Then these cases are now handled properly:

`{38C5D27A-785F-4088-8DBF-4FCBB40DC813}:HDMI - PA249 (NVIDIA High Definition Audio)`

`{38C5D27A-785F-4088-8DBF-4FCBB40DC813}`

For simplicity friendly name is discarted as anyway is "fixed" later in `ValidateOutputDevices`

```
driver = ""
device = {38C5D27A-785F-4088-8DBF-4FCBB40DC813}
friendlyName = ""
```

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp (hunk 11 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp]: Implemented

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp (hunk 12 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp]: Done but only is need check `m_deviceInfoList` because `m_sinkInfoList` is already check at top of method

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp (hunk 13 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp]: Good point, really is need with the latest changes

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 14]
```diff
@@ -728,6 +728,114 @@ void CActiveAESink::PrintSinks(std::string& driver)
...
+
+      if (!passthrough && d.m_onlyPassthrough)
+        continue;
+
+      if (d.m_deviceName.find("default") != std::string::npos)
+        return d.ToDeviceString(sink.m_sinkName);
+    }
+  }
+
+  if (m_sinkInfoList[0].m_deviceInfoList.empty())
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:832]: At this point, should probably look for any device for any driver. driver 0 may not have devices but driver 1 may.
If nothing is found then return {}
Could be integrated with the search of a default device for any driver in the previous block, same way it's done for the matching driver a bit earlier?

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 15]
```diff
@@ -728,6 +728,114 @@ void CActiveAESink::PrintSinks(std::string& driver)
   }
 }
 
+std::string CActiveAESink::ValidateOuputDevice(const std::string& device, bool passthrough)
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:731]: const

File: xbmc/cores/AudioEngine/AESinkFactory.cpp (hunk 10 above)
Comment (CrystalP) [reply xbmc/cores/AudioEngine/AESinkFactory.cpp:64]: Tried disabling the WASAPI driver and indeed the displayed name in the settings screen doesn't have the Directsound: prefix anymore, but guisettings.xml still has it => not a situation with no driver name.
Back compatibility is good but this may be excessive if there is no real use case. I grabbed old version as far as available on https://mirrors.kodi.tv (2015 - v15) to find out.
A fixed format driver:name:friendly name would be easier to work with.

**Comment by CrystalP** [comment]
After testing and thinking about it some more, I think there are a couple problems with the last commit's approach:

- it's not a good idea to change the setting automatically because it will cause problems when Kodi is started before a TV or receiver is considered active by Windows. The settings device won't be found and changed to the default device of the same driver, when the device is turned back on, the setting won't change back.

- Some calls to LoadSettings() are followed by ValidateOutputDevices() and others are not. The reason why not is not clear to me, and unless that reason is written down somewhere, it will be easy to make a mistake in future extensions. Could the validation be integrated inside LoadSettings() so it is always done?

- If the settings device fails to open with CAESinkFactory::Create(), the previous version tried to Create() with the alternative devices. Seemed like a good idea but I don't know if it would help in real situations. This last version doesn't allow it but it could be re-added: ValidateOutputDevice() could return a list of devices instead of a single name. ValidateOutputDevices would use the first one, and CAESinkFactory::Create() could loop over all the names until one works or the list is exhausted.

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp (hunk 14 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp]: done

**Comment by thexai** [comment]
> it's not a good idea to change the setting automatically because it will cause problems when Kodi is started before a TV or receiver is considered active by Windows. The settings device won't be found and changed to the default device of the same driver, when the device is turned back on, the setting won't change back.

Steps to reproduce this? in my system audio devices still enumerated when TV and AVR are turned off. Maybe you confused with "open device" but now (with latest commit) only validates that setting device stills enumerated.

> Some calls to LoadSettings() are followed by ValidateOutputDevices() and others are not. The reason why not is not clear to me, and unless that reason is written down somewhere, it will be easy to make a mistake in future extensions. Could the validation be integrated inside LoadSettings() so it is always done?

The reason is: only validates settings when is called `LoadSettings()` AND devices are enumerated i.e is a call to
`m_sink.EnumerateSinkList(false, "");` as if sink List are empty is useless compare settings names with nothing :)

> If the settings device fails to open with CAESinkFactory::Create(), the previous version tried to Create() with the alternative devices. Seemed like a good idea but I don't know if it would help in real situations. This last version doesn't allow it but it could be re-added: ValidateOutputDevice() could return a list of devices instead of a single name. ValidateOutputDevices would use the first one, and CAESinkFactory::Create() could loop over all the names until one works or the list is exhausted.

Maybe in a follow-up PR, I don't have more time right now....

File: xbmc/cores/AudioEngine/AESinkFactory.cpp (hunk 10 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/AESinkFactory.cpp:64]: > A fixed format driver:name:friendly name would be easier to work with.

The check for the possible lack of driver was already in the existent code and it is not complicated to maintain this.

```
  if (!found)
    driver.clear();
```

I honestly don't see any problem here.

Comment (CrystalP) [reply xbmc/cores/AudioEngine/AESinkFactory.cpp:64]: Blank driver is not a real use case and would be better treated as an error, but fine go ahead it's a detail.

**Comment by CrystalP** [comment]
> However, this PR is not intended to fix problems when the TV or AVR turned off. Only fixes issues when device names change (permanently) due to driver updates.

Not always easy to distinguish permanent and temporary.
1/ Device available with same driver / friendly name: OK to save, we are reasonably sure it's the same device. That's the main case of the PR.
2/ Device available with same driver / device GUID / different friendly name: maybe OK, at least the GUID is common. Is that what happens when plugging a different device in the same hdmi port? I don't have hardware to test. If yes then would be OK to save.

3/ Rules that look for default or first device of same driver, or any driver: dangerous and outside of the PR scope. The new device has nothing in common with original, the situation doesn't happen as consequence of a driver update, it will change the selected device without the user consent. We could end up there because something is turned off / unplugged. I don't think it's ok to save the updated setting.

Agreed that fixing the device off case is not in the scope of the PR but it shouldn't be made possibly worse. I'm not affected by that problem but can only imagine Kodi has a problem because the expected device cannot be enumerated on start. If the setting is not saved for 3/ maybe the PR helps a little with more relaxed rules to match the setting to an enumerated device.

> > Some calls to LoadSettings() are followed by ValidateOutputDevices() and others are not. The reason why not is not clear to me, and unless that reason is written down somewhere, it will be easy to make a mistake in future extensions. Could the validation be integrated inside LoadSettings() so it is always done?
> 
> The reason is: only validates settings when is called `LoadSettings()` AND devices are enumerated i.e is a call to `m_sink.EnumerateSinkList(false, "");` as if sink List are empty is useless compare settings names with nothing :)
ok, then should the validation be added inside the enumeration?

**Comment by thexai** [comment]
Even I can't reproduce the problems you mention, I modified conditions to save only in case of same device: 

Same driver and same friendly name with different GUID (main use case of PR) or same name GUID with different friendly name (same GUID is same audio device for sure because GUID are unique).

In all others cases (switch from WASAPI to DIRECTSOUND, or from WASAPI:x to WASAPI:default, etc.) is allowed use device temporally but changes are not saved.

**Comment by thexai** [comment]
> ok, then should the validation be added inside the enumeration?

Really not because when devices are enumerated settings are not yet loaded 

...and I don't see the need to do this either (add methods inside others).

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp [hunk 16]
```diff
@@ -2670,6 +2674,58 @@ void CActiveAE::LoadSettings()
...
+  {
+    CLog::LogF(LOGWARNING, "audio output device setting has been updated from '{}' to '{}'",
+               m_settings.device, device);
+
+    const AESinkDevice oldDevice = CAESinkFactory::ParseDevice(m_settings.device);
+    const AESinkDevice newDevice = CAESinkFactory::ParseDevice(device);
+
+    m_settings.device = device;
+
+    if (saveChanges && oldDevice == newDevice)
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp:2691]: The == operator doesn't follow usual expectations (equality of all members), so this condition works, but is not intuitive to read.
Maybe instead of == operator, a member function IsEquivalentTo() or IsSameDeviceAs(), or something like it.

**Comment by CrystalP** [comment]
Thanks, it's in pretty good shape and almost finished as far as I am concerned, with just the one style comment left.
Functionality seems OK and safe. You could squash the last commits / rewrite the commit messages for a last look.
A non-Windows review would be good but there is plenty of time to backtrack before v21 release if necessary.

**Comment by thexai** [comment]
@fritsch 
If you have something important to say, now is probably the time. If no one says anything against it, I will merge it on Sunday since it solves an important issue on Windows and it would be nice if it could be tested in Alpha 3. Although I think that the risk of break something on other platforms is minimal.

**Review by CrystalP — APPROVED** [review]
Very positive change for Windows.

**Comment by lrusak** [comment]
This should probably be tested on a few other platforms before merging.

File: xbmc/cores/AudioEngine/AESinkFactory.cpp [hunk 17]
```diff
@@ -38,41 +38,58 @@ bool CAESinkFactory::HasSinks()
...
 }
 
-void CAESinkFactory::ParseDevice(std::string &device, std::string &driver)
+AESinkDevice CAESinkFactory::ParseDevice(const std::string& device)
 {
-  int pos = device.find_first_of(':');
+  AESinkDevice dev{};
+  dev.name = device;
+
+  size_t pos = dev.name.find_first_of(':');
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/AESinkFactory.cpp:46]: What about using `StringUtils::Split` ?

File: xbmc/cores/AudioEngine/AESinkFactory.h [hunk 18]
```diff
@@ -42,15 +42,27 @@ struct AESinkRegEntry
   Cleanup cleanupFunc;
 };
 
+struct AESinkDevice
+{
+  std::string driver;
+  std::string name;
+  std::string friendlyName;
+
+  bool IsSameDeviceAs(const AESinkDevice& d) const
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/AESinkFactory.h:51]: Can this just be `operator==` ?

File: xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp [hunk 19]
```diff
@@ -733,6 +728,116 @@ void CActiveAESink::PrintSinks(std::string& driver)
...
+  // return first device of same driver
+  if (!firstDevice.empty())
+    return firstDevice;
+
+  firstDevice.clear();
+
+  // find the default of any driver or first of any driver
+  for (const auto& sink : m_sinkInfoList)
+  {
+    for (const auto& d : sink.m_deviceInfoList)
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAESink.cpp:821]: d for `device` ?

File: xbmc/cores/AudioEngine/AESinkFactory.h [hunk 20]
```diff
@@ -42,15 +42,27 @@ struct AESinkRegEntry
   Cleanup cleanupFunc;
 };
 
+struct AESinkDevice
+{
+  std::string driver;
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/AESinkFactory.h:47]: What about making these private and adding public setters and getters?

**Comment by thexai** [comment]
> This should probably be tested on a few other platforms before merging.

Just knowing the format of the audio device string stored in `guisettings.xml` on the other platforms would help to guess if it might cause problems.

Android already tested.

**Comment by fritsch** [comment]
I followed the discussion. All fine with me, sane argumentation. Therefore I did not jump in. Regressions we will determine ;-)

File: xbmc/cores/AudioEngine/AESinkFactory.h (hunk 18 above)
Comment (CrystalP) [reply xbmc/cores/AudioEngine/AESinkFactory.h:51]: It was until I made a comment in the opposite direction :-) because the code using it looked like
```
if (saveChanges && oldDevice == newDevice)
  SaveSettings(newDevice)
```
which is strange (to me).  It's not an equality of all members if you look closely. Instances with different name/friendly name members could be considered equal.
It's also possible this condition doesn't make sense on platforms other than Windows, maybe we need a platform or sink-specific condition instead.
But I'll go with the consensus.

File: xbmc/cores/AudioEngine/AESinkFactory.h (hunk 20 above)
Comment (CrystalP) [reply xbmc/cores/AudioEngine/AESinkFactory.h:47]: I think it could be part of a followup refactor PR to extensively replace the all-in-one device strings (similar to one of your commits).
There isn't much meat in AESinkDevice at this time and it's not the focus of the PR.

Comment (fritsch) [reply xbmc/cores/AudioEngine/AESinkFactory.h:47]: I agree with @CrystalP . We should not mixup refactors and functionality. This will only make it very hard to backport / cherry-pick parts of it. You can see that in the EAC3 backport scenario ... while the change would have been 8 lines, it was then  > 50. All good, if nothing happens, but not so much if a bug slips in.

**Comment by thexai** [comment]
I agree with fritsch and CrystalP: refactors and code improvements better separated to easy track regressions. Then lets merge as is without changing unnecessary things for now.

**Comment by howie-f** [comment]
commit https://github.com/xbmc/xbmc/pull/23650/commits/82465be609a0893ff44a9f7f717f3e3192cba0a6 breaks audio with my device (ALC662 rev3 Analog)

```
2023-09-05 22:03:32.115 T:2980     info <general>:     Device 3
2023-09-05 22:03:32.115 T:2980     info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=2
2023-09-05 22:03:32.115 T:2980     info <general>:         m_displayName     : HDA Intel
2023-09-05 22:03:32.115 T:2980     info <general>:         m_displayNameExtra: HDMI #2
2023-09-05 22:03:32.115 T:2980     info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2023-09-05 22:03:32.115 T:2980     info <general>:         m_channels        : FL, FR
2023-09-05 22:03:32.115 T:2980     info <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2023-09-05 22:03:32.115 T:2980     info <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2023-09-05 22:03:32.115 T:2980     info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2023-09-05 22:03:32.115 T:2980     info <general>:     Device 4
2023-09-05 22:03:32.115 T:2980     info <general>:         m_deviceName      : @:CARD=PCH,DEV=0
2023-09-05 22:03:32.115 T:2980     info <general>:         m_displayName     : HDA Intel PCH
2023-09-05 22:03:32.115 T:2980     info <general>:         m_displayNameExtra: ALC662 rev3 Analog
2023-09-05 22:03:32.115 T:2980     info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2023-09-05 22:03:32.115 T:2980     info <general>:         m_channels        : FL, FR
2023-09-05 22:03:32.115 T:2980     info <general>:         m_sampleRates     : 48000
2023-09-05 22:03:32.115 T:2980     info <general>:         m_dataFormats     : AE_FMT_S32NE
2023-09-05 22:03:32.115 T:2980     info <general>:         m_streamTypes     : No passthrough capabilities
2023-09-05 22:03:32.116 T:2981     info <general>: CActiveAESink::OpenSink - initialize sink
2023-09-05 22:03:32.116 T:2981     info <general>: CAESinkALSA::Initialize - Attempting to open device "@"
2023-09-05 22:03:32.127 T:2981     info <general>: CAESinkALSA - Unable to open device "sysdefault" for playback
2023-09-05 22:03:32.130 T:2981     info <general>: CAESinkALSA - Unable to open device "default" for playback
2023-09-05 22:03:32.130 T:2981     info <general>: CAESinkALSA - Unable to open device "front" for playback
2023-09-05 22:03:32.130 T:2981    error <general>: CAESinkALSA::Initialize - failed to initialize device "@"
```

here's the log when it was working

```
2023-09-05 22:11:18.541 T:3260     info <general>: Enumerated ALSA devices:
2023-09-05 22:11:18.541 T:3260     info <general>:     Device 1
2023-09-05 22:11:18.541 T:3260     info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=0
2023-09-05 22:11:18.541 T:3260     info <general>:         m_displayName     : HDA Intel
2023-09-05 22:11:18.541 T:3260     info <general>:         m_displayNameExtra: SAM SAMSUNG on HDMI #0
2023-09-05 22:11:18.541 T:3260     info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2023-09-05 22:11:18.541 T:3260     info <general>:         m_channels        : FL, FR
2023-09-05 22:11:18.541 T:3260     info <general>:         m_sampleRates     : 32000,44100,48000
2023-09-05 22:11:18.541 T:3260     info <general>:         m_dataFormats     : AE_FMT_RAW,AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2023-09-05 22:11:18.541 T:3260     info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2023-09-05 22:11:18.541 T:3260     info <general>:     Device 2
2023-09-05 22:11:18.541 T:3260     info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=1
2023-09-05 22:11:18.541 T:3260     info <general>:         m_displayName     : HDA Intel
2023-09-05 22:11:18.541 T:3260     info <general>:         m_displayNameExtra: HDMI #1
2023-09-05 22:11:18.541 T:3260     info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2023-09-05 22:11:18.541 T:3260     info <general>:         m_channels        : FL, FR
2023-09-05 22:11:18.541 T:3260     info <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2023-09-05 22:11:18.541 T:3260     info <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2023-09-05 22:11:18.541 T:3260     info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2023-09-05 22:11:18.541 T:3260     info <general>:     Device 3
2023-09-05 22:11:18.541 T:3260     info <general>:         m_deviceName      : hdmi:CARD=HDMI,DEV=2
2023-09-05 22:11:18.541 T:3260     info <general>:         m_displayName     : HDA Intel
2023-09-05 22:11:18.541 T:3260     info <general>:         m_displayNameExtra: HDMI #2
2023-09-05 22:11:18.541 T:3260     info <general>:         m_deviceType      : AE_DEVTYPE_HDMI
2023-09-05 22:11:18.541 T:3260     info <general>:         m_channels        : FL, FR
2023-09-05 22:11:18.541 T:3260     info <general>:         m_sampleRates     : 32000,44100,48000,88200,96000,176400,192000
2023-09-05 22:11:18.541 T:3260     info <general>:         m_dataFormats     : AE_FMT_S32NE,AE_FMT_S16NE,AE_FMT_S16LE,AE_FMT_RAW
2023-09-05 22:11:18.541 T:3260     info <general>:         m_streamTypes     : STREAM_TYPE_AC3,STREAM_TYPE_DTSHD,STREAM_TYPE_DTSHD_MA,STREAM_TYPE_DTSHD_CORE,STREAM_TYPE_DTS_1024,STREAM_TYPE_DTS_2048,STREAM_TYPE_DTS_512,STREAM_TYPE_EAC3,STREAM_TYPE_TRUEHD
2023-09-05 22:11:18.541 T:3260     info <general>:     Device 4
2023-09-05 22:11:18.541 T:3260     info <general>:         m_deviceName      : @:CARD=PCH,DEV=0
2023-09-05 22:11:18.541 T:3260     info <general>:         m_displayName     : HDA Intel PCH
2023-09-05 22:11:18.541 T:3260     info <general>:         m_displayNameExtra: ALC662 rev3 Analog
2023-09-05 22:11:18.541 T:3260     info <general>:         m_deviceType      : AE_DEVTYPE_PCM
2023-09-05 22:11:18.541 T:3260     info <general>:         m_channels        : FL, FR
2023-09-05 22:11:18.541 T:3260     info <general>:         m_sampleRates     : 48000
2023-09-05 22:11:18.541 T:3260     info <general>:         m_dataFormats     : AE_FMT_S32NE
2023-09-05 22:11:18.541 T:3260     info <general>:         m_streamTypes     : No passthrough capabilities
2023-09-05 22:11:18.541 T:3261     info <general>: CActiveAESink::OpenSink - initialize sink
2023-09-05 22:11:18.541 T:3261     info <general>: CAESinkALSA::Initialize - Attempting to open device "@:CARD=PCH,DEV=0"
2023-09-05 22:11:18.548 T:3261     info <general>: CAESinkALSA::Initialize - Opened device "sysdefault:CARD=PCH"
2023-09-05 22:11:18.548 T:3261     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-09-05 22:11:18.548 T:3261     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
```

**Comment by CrystalP** [comment]
The : separator is a problem. What's the value of the setting in `guisettings.xml`?

**Comment by howie-f** [comment]
only `ALSA:@` and i couldn't reactivate the correct device by selecting it in the gui. so i bisected to this commit.
now after i edit guisettings.xml manually to `ALSA:@:CARD=PCH,DEV=0` (taken from the nexus version) it's working again and i can also switch between devices.....

**Comment by thexai** [comment]
@howie-f 

The problem is `:` in the device name. This should be sufficient to fix this use case:

```diff
diff --git a/xbmc/cores/AudioEngine/AESinkFactory.cpp b/xbmc/cores/AudioEngine/AESinkFactory.cpp
index 6f27372de7..e2d0ddd43d 100644
--- a/xbmc/cores/AudioEngine/AESinkFactory.cpp
+++ b/xbmc/cores/AudioEngine/AESinkFactory.cpp
@@ -63,7 +63,7 @@ AESinkDevice CAESinkFactory::ParseDevice(const std::string& device)
   if (!found)
     dev.driver.clear();
 
-  pos = dev.name.find_first_of(':');
+  pos = dev.name.find_last_of(':');
 
   if (pos != std::string::npos)
   {

```

Although probably is better change separador to `|`

**Comment by Portisch** [comment]
This PR do also remove passthrough on CoreELEC devices. So I guess also on LibreELEC.
With the fix `find_last_of` above the passthrough options looks like back again.
But on Kodi start it switch back to default audio device.
So after Kodi update with this PR included the audio device must be changed one time to work again.

**Comment by Portisch** [comment]
Also before: `CAESinkALSA::Initialize - Opened device "surround71:CARD=AMLAUGESOUND,DEV=0"`
With this PR: `CAESinkALSA::Initialize - Opened device "surround71"`

Functions like `GetParamFromName` are broken now as no `CARD` or `DEV` is included in `device` anymore.

File: xbmc/cores/AudioEngine/AESinkFactory.h (hunk 18 above)
Comment (lrusak) [reply xbmc/cores/AudioEngine/AESinkFactory.h:51]: I'm not sure what you mean? I was saying to overload the operator== so that we can define the evaluation.
