### PR TITLE
[settings] Parser for oldsettings - Fix label settings starting with integers

### LINKED ISSUE #15064: Addon Settings: Labels starting with numbers
### Describe the bug
When using labels that start with a digit (0 - 9), the label is not displayed in the addon settings. For instance:

`<setting id="setting1234Q" type="bool" label="1234Q" />
`

Here Kodi 18 only shows an empty string in the settings dialog, instead of the string: "1234Q"

## Expected Behavior
The label should show as provided in the XML attribute. In this example "1234Q".

## Actual Behavior
An empty string is displayed instead of the string. Only happens in Kodi 18, older versions are fine.

## Possible Fix
This might be due to the detection of msg numbers in the translation file (.po files). Maybe the new code checks if the label starts with a number, and if so it assumes it is the ID of the entry int he translation file. This detection should be reverted to what Kodi 17 did. If this is done with regex, then the expression is not complete. Check if the ENTIRE string matches a number without any other characters, not that the string STARTS WITH a digit. This might be the case, since if I add a letter in front of the label (eg "a1234Q"), then it is displayed as intended.

### To Reproduce
1. Create a default addon
2. Create a XML element with a label that starts with a number.
3. The label is not displayed in the addon setting dialog.

### Debuglog
Nothing in debug log.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 7, Windows 10, Ubuntu 16, Ubuntu 18 (other OSs might have the same issue)
 - Kodi version:  18.0 RC2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This fixes a regression on addon settings (old parser) in which the label starts with an integer value. At the moment Kodi tries to parse the label as a localized string.
Closes https://github.com/xbmc/xbmc/issues/15064 

## Motivation and Context
`QueryIntAttribute` grabs the integer values at the start of the label and ignores the fact the label may have a few more characters after the int.

Not sure if a more elegant solution is possible - I currently just compare the grabbed int as a string with the whole value as string and only return if they are the same.

## How Has This Been Tested?
Using:
```
<setting id="testerror" type="bool" label="12MyLabel" default="true" /> -> 12MyLabel
<setting id="testonlynumber" type="bool" label="12" default="true" /> -> Temperature
<setting id="testonlystring" type="bool" label="MyLabel" default="true" /> -> MyLabel
```
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [x] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
Jenkins build this please

File: xbmc/addons/settings/AddonSettings.cpp [hunk 1]
```diff
@@ -1319,17 +1319,18 @@ bool CAddonSettings::ParseOldLabel(const TiXmlElement* element, const std::strin
...
     return false;
+  
+  // label value as a string
+  std::string labelString;
+  element->QueryStringAttribute("label", &labelString);
+
 
   // try to parse the label as a translation number
-  if (element->QueryIntAttribute("label", &labelId) == TIXML_SUCCESS && labelId >= 0)
+  if (element->QueryIntAttribute("label", &labelId) == TIXML_SUCCESS &&
```
Comment (Montellese) [inline xbmc/addons/settings/AddonSettings.cpp]: I would use `strtol()` to try to parse the `labelString` as an integer. If the `endptr` parameter is either `nullptr` or `'\0'` the `"label"` attribute is a pure number.

**Review by Montellese — APPROVED** [review]
