### PR TITLE
[python][xbmcgui] Fix ControlEdit constructor args

### LINKED ISSUE #22461: xbmcgui.ControlEdit issue, position & width not set when control is first created.
### Describe the bug
Here is a clear and concise description of what the problem is:

When using `xbmcgui.ControlEdit(200, 200, 400, 75, "Test")` it is not setting the position & height when it's created. You have to `setPosition(), setHeight(), setWidth()` after it has been created.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

```
edit = xbmcgui.ControlEdit(200, 200, 400, 75, "Test")
edit.getX()
> 200
edit.getY()
> 200
edit.getWidth()
> 400
edit.getHeight()
> 75
```

## Actual Behavior

```
edit = xbmcgui.ControlEdit(200, 200, 400, 75, "Test")
edit.getX()
> 0
edit.getY()
> 0
edit.getWidth()
> 0
edit.getHeight()
> 0

edit.setPosition(200, 200)
edit.setWidth(400)
edit.setHeight(75)
edit.getX()
> 200
edit.getY()
> 200
edit.getWidth()
> 400
edit.getHeight()
> 75
```

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/bohasaqewa.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 20.0-RC2 (19.90.905)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

The variable x,y,width,height was unset when set in the constructor

## Motivation and context

fix #22461

## How has this been tested?

Make a python xbmcgui.Window add the control by use:
```
ctr = xbmcgui.ControlEdit(100, 200, 400, 75, "Test")
self.addControl(ctr)
```

## What is the effect on users?

Create py control by set arguments by using constructor

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/interfaces/legacy/Control.cpp [hunk 1]
```diff
@@ -1036,6 +1036,11 @@ namespace XBMCAddon
       align(_alignment)
 
     {
+      dwPosX = x;
+      dwPosY = y;
+      dwWidth = width;
+      dwHeight = height;
+
```
Comment (fuzzard) [inline xbmc/interfaces/legacy/Control.cpp:1043]: Should these just be done as the default constructor arguments?

```
    ControlFadeLabel::ControlFadeLabel(long x, long y, long width, long height,
                                       const char* font, const char* _textColor,
                                       long _alignment) :
      strFont("font13"), textColor(0xffffffff), align(_alignment),
      dwPosX(x),
      dwPosY(y),
      dwWidth(width),
      dwHeight(height)
    {
```

Comment (CastagnaIT) [reply xbmc/interfaces/legacy/Control.cpp:1043]: I thought so too, but they are variables from the parent class, if i try do that compiler says:
`"dwPosX" is not a nonstatic data member or base class of class "XBMCAddon::xbmcgui::ControlEdit"`

Comment (garbear) [reply xbmc/interfaces/legacy/Control.cpp:1043]: When I initialize parent members, I group the stanza under the heading "Initialize Control" to both inform the reader where the variables are coming from, and also in the future if this happens with multiple parents, you can verify that the most basic parent initialization comes before the least basic.
