### PR TITLE
[Python] fix build against python 3.8

### LINKED ISSUE #16560: feature_python3 - not compatible with Python 3.8
### Describe the bug
Here is a clear and concise description of what the problem is:

xbmc/interfaces/python/PythonInvoker.cpp

There are a three references in the file above to the private interfaces of PyInterpreterState.

Example:

    s = state->interp->tstate_head;

Python 3.8 has finally removed the public interfaces to PyInterpreterState. The C documentation has always stated that there were never any public interfaces but projects such as Kodi used them anyway.

Announcement:
https://mail.python.org/pipermail/python-dev/2019-February/156344.html

Bug tracker to request a public interface:
https://bugs.python.org/issue35886

## Possible Fix
Work with upstream to create a real public interface.

Workaround:

Adding the following to the top of PythonInvoker.cpp will expose the structs again.

    #if PY_VERSION_HEX >= 0x03080000
    # define Py_BUILD_CORE
    # undef HAVE_STD_ATOMIC
    /* for access to the fields of PyInterpreterState */
    #  include "internal/pycore_pystate.h"
    # undef Py_BUILD_CORE
    # define HAVE_STD_ATOMIC
    #endif

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.4 / 19.x

### PR DESCRIPTION
**Pull request by ronie**
Today my Manjaro linux installation updated to python 3.8.0 and i was unable to compile Kodi.

As mentioned in https://github.com/xbmc/xbmc/issues/16560 we are not compatible with the current python version.
This PR implements the workaround as suggested in that issue report.

fixes https://github.com/xbmc/xbmc/issues/16560

### CODE REVIEW

**Review by jimfcarroll — COMMENTED** [review]
This seems like a really bad idea. I remember reviewing the code in PythonInvoker and thinking we need to move away from accessing the internal thread state structures internal to python and I think there were even warnings in the documentation that this could be changed without notice. You can take this for now to get 3.8 working but I'm going to see if there's a compliant way to do the same thing (get access to the chain of thread states).

**Comment by ronie** [comment]
thanx for the feedback. 
i've added it as a todo comment in the code.

File: xbmc/interfaces/python/PythonInvoker.cpp [hunk 1]
```diff
@@ -36,6 +36,17 @@
 #include "platform/posix/XTimeUtils.h"
 #endif
 
+// This is a workaround to compile Kodi against python 3.8
+//! @todo implement a compliant way to get access to the chain of thread states
+#if PY_VERSION_HEX >= 0x03080000
+# define Py_BUILD_CORE
+# undef HAVE_STD_ATOMIC
+/* for access to the fields of PyInterpreterState */
+#  include "internal/pycore_pystate.h"
```
Comment (Rechi) [inline xbmc/interfaces/python/PythonInvoker.cpp]: include style is wrong, this in not a Kodi header

Comment (ronie) [reply xbmc/interfaces/python/PythonInvoker.cpp]: thanx for the hint, updated.
