### PR TITLE
[Android] Fix system memory usage info

### LINKED ISSUE #18987: [v19.0b2] System memory usage is reported as 100% and used/total System memory is incorrect on a Sony Android TV
### Describe the bug
Here is a clear and concise description of what the problem is:

Using v19.0b2 with a Sony X950G the System Memory Usage is reported as 100% and detected used and total memory is incorrect.

## Actual Behavior

As reported by System Info/Hardware

Total memory: 4294965515MB (actual memory reported by AIDA64 is 2.5GB or 2315MB)
Free memory: 638MB (fluctuates)

System memory usage: 4294964877MB/4294965515MB - 100%

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should be able to properly detect the system memory and report memory usage.

As reported by System Info/Hardware

Total memory: 2315MB
Free memory: 638MB

System memory usage: 638MB/2315MB - 72%

### To Reproduce

1. Install Kodi v19.0 beta 2 on a Sony Android TV
2. Check system memory reported and usage in System info/Hardware under Settings

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/litasemamo.kodi

### Your Environment
Used Operating system:

 - [ X ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 9.0
 - Kodi version: 19.0 beta 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Fix system memory usage info

## Motivation and context
I have come across this while trying other things on android TV...

## How has this been tested?
Runtime tested Android TV (Sony AG9)

## What is the effect on users?
Fix wrong big numbers displayed on "System memory usage info" and 100% usage on Player Info

## Screenshots (if appropriate):

**Before:**
screenshot00000

**After:**
screenshot00001

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
Seems only affects ARM platforms (not ARM64) due `long` type not has same bit length on all platforms. 

And conversions from small type signed to unsigned big type can produce unexpected results.

File: xbmc/platform/android/MemUtils.cpp [hunk 1]
```diff
@@ -35,13 +35,14 @@ void GetMemoryStatus(MemoryStatus* buffer)
...
-  long availMem, totalMem;
+  long availMem = 0;
+  long totalMem = 0;
 
   if (CXBMCApp::get()->GetMemoryInfo(availMem, totalMem))
   {
     *buffer = {};
-    buffer->totalPhys = totalMem;
-    buffer->availPhys = availMem;
+    buffer->totalPhys = static_cast<uint64_t>(static_cast<unsigned long>(totalMem));
```
Comment (lrusak) [inline xbmc/platform/android/MemUtils.cpp:44]: Is the double casting actually needed?

Comment (thexai) [reply xbmc/platform/android/MemUtils.cpp:44]: The key point is convert first from `signed long` to `unsigned long` without changing bit length.

Probably the second cast to`uint64_t` is not necessary but in this case I prefer because it indicates what is intended.

Without any explicit cast compiler is doing implicit `uint64_t` cast and does not work in all cases.

Comment (thexai) [reply xbmc/platform/android/MemUtils.cpp]: Tested with only `static_cast<unsigned long>` and fix is maintained. 

Updated PR and backport.

**Review by lrusak — APPROVED** [review]
LGTM

**Comment by rahul84ipec** [comment]
I am newbie here and facing same issue on chromebook. Could anyone suggest how I may apply this solution on chromebook.

**Comment by thexai** [comment]
Install Matrix build from here:
http://mirrors.kodi.tv/nightlies/android/arm/Matrix/

This will be included in v19.4
