### PR TITLE
[video] Fix VIDEO_UTILS::Get*ResumeInformation …

### LINKED ISSUE #22176: Unnecessary contexts when playing episodes after "Continue watching" feature.
### Describe the bug
Here is a clear and concise description of what the problem is:

If there is  an episode in progress or a watched episode like these screenshots,

screenshot00000
screenshot00001

1.Playing next episodes pops up context like this screenshot.

screenshot00002

This is unnecessary because both "Continue watching" and "Play from beggining" lead to the same result.
I set default selection action to "Play", so should play the episode without showing any context as before.

2.Long press on unwatched episodes shows "Reset resume position" like this.

screenshot00003

This is also unnecessary because unwatched episodes have no resume point.
 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

no unnecessary context as before.

## Actual Behavior

some unnecessary contexts.

### To Reproduce

1. add a tvshow with some episodes files to your kodi library.(or test with your own pre-existing tvshows library)
2. set default select action to "Play" (Settings/Media/Videos) if the default select action is set to Resume, you may not see the context.
3. browse into the tvshow to view episodes list.
4. select an episode and mark as watched or play an episode and create resume point to make the episode in progress like screenshots above.
5. try to play other unwatched episode and check the context.
6. long press other unwatched episode and check the context.

### Debuglog

The debuglog can be 
[kodi.log](https://github.com/xbmc/xbmc/files/10063403/kodi.log)
found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 10 64bit
 - Kodi version: kodi20 beta1 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
… to handle bookmarks with end time but no resume position set properly and to check for not being a folder at the proper place.

Fixes #22176 

Runtime-tested on Android and macOS, latest master.

@enen92 if you find some tome for a review. Low regression risk for sure.

### CODE REVIEW

File: xbmc/video/VideoUtils.cpp [hunk 1]
```diff
@@ -635,7 +638,7 @@ ResumeInformation GetNonFolderItemResumeInformation(const CFileItem& item)
     db.GetResumeBookMark(path, bookmark);
     db.Close();
 
-    if (bookmark.IsSet())
+    if (bookmark.timeInSeconds > 0.0)
```
Comment (enen92) [inline xbmc/video/VideoUtils.cpp:641]: Is this intentional? https://github.com/xbmc/xbmc/blob/82f7b7bd86a56c5aec6d28b44cb5133027b99b04/xbmc/video/Bookmark.cpp#L26
Seems to be the same

Comment (ksooo) [reply xbmc/video/VideoUtils.cpp:641]: > Is this intentional? 

 Yes.
 
> Seems to be the same

 No. `IsSet` checks for `totalTimeInSeconds > 0.0`. What I'm interested in is whether there is actually a resume time (`timeInSeconds > 0.0`).

Comment (ksooo) [reply xbmc/video/VideoUtils.cpp:641]: Just spotted that there already is `CBookMark::IsPartWay()` which fits here. Will change.

**Review by enen92 — APPROVED** [review]

**Comment by ksooo** [comment]
@enen92 changed as requested. Please re-review.

**Comment by ksooo** [comment]
Ah, you already approved right after I force-pushed the requested change and I then requested another review. This is actually not needed. No further code changes after you approved.

**Review by enen92 — APPROVED** [review]
Black friday approval, 2 for the price of one (:
