### PR TITLE
[video] Remove non-working context menu manage / info dialog buttons for versions

### LINKED ISSUE #24466: Inconsistencies when deleting a video version
### Describe the bug
I think there is a conflict with the delete operation depending on the setting **Show videos with multiple versions as a folder**

If the setting is...

**Disabled:**
Using Context Menu►Manage►Manage versions I can highlight a version and select Remove. That single version is removed.

**Enabled:**
Enter the version folder in the movie listing. There you will see a list of available versions.

- Select a version then either using Delete on a keyboard or Context menu►Manage►Remove from library, you are asked do you want to remove Blade Runner from the library?
- Selecting Yes deletes all versions from the library.
- I would expect that single version to be deleted, not the entire version collection.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
The selected video version is deleted from the library

## Actual Behavior
All versions are deleted

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Context menu > Manage on versions:
- Removed: Edit title, Edit sort title, Link to TV show, Manage movie set, Choose art, Remove from library
- Remains: Manage versions

Removed from Info dialog opened on version:
- Choose art (use Versions Manager instead)
- Refresh - not applicable to versions at this time

## Motivation and context

Cleanup the GUI and remove options that don't work as expected

## How has this been tested?

with "Show videos with multiple versions as folder" and without, on movies with and without versions, inside the versions folders

## What is the effect on users?

Less cluttered GUI.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp [hunk 1]
```diff
@@ -1115,8 +1121,11 @@ int CGUIDialogVideoInfo::ManageVideoItem(const std::shared_ptr<CFileItem>& item)
     }
   }
 
-  if (type != MediaTypeSeason)
+  if (type != MediaTypeSeason && (item->m_bIsFolder || !item->IsVideoAssetNav()))
```
Comment (ksooo) [inline xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1132]: I have spotted the term `(type == MediaTypeMovie && (item->m_bIsFolder || !item->IsVideoAssetNav()))` at several places in this commit. Is this something that could be  factored out to a new `CFileItem` method?

Comment (CrystalP) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp]: Yes, good idea. I can remove IsVideoAssetNav() actually. At this point we only care about detecting the real files, excluding the "movies that are folders".
Also fixes a little glitch from previous PR in the process.

**Review by ksooo — APPROVED** [review]
Looks good to me.
