### PR TITLE
[subtitles][ass] Fix completely overlapping subtitle overlays

### LINKED ISSUE #18298: Subtitle with overlapping timestamp show/disappear incorrectly
### Describe the bug
Subtitle with overlapping timestamp show/disappear incorrectly.

e.g. The following subtitle has a line shown on screen at upper right between 1s to 9s. In addition, it has another subtitle shown at normal position every 2 seconds between 0 to 10s. When Kodi plays it, the subtitle on the upper right will disappear between 6s to 8s while it should be on screen all the time. This has been tested on Kodi 18.8 Windows, macOS and CoreELEC.

```
[Script Info]
Title: [Test]
Original Script: Tester
ScriptType: v4.00+
WrapStyle: 0
PlayResX: 1280
PlayResY: 720
YCbCr Matrix: TV.709
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,Calibri,50,&H00FFFFFF,&HF0FFFFFF,&H007B66D0,&H808060E3,-1,0,0,0,100,100,0,0,1,2,1.5,2,10,10,13,1
Style: TOP,Candara,40,&H00FFFFFF,&HF0FFFFFF,&H00169CE1,&HF0FFFFFF,-1,0,0,0,100,100,0,0,1,1.5,0,9,10,12,8,128

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:00:01.00,0:00:09.00,TOP,,0,0,0,,{\be3\blur3\fad(200,200)}Should be on screen from 1s to 9s
Dialogue: 0,0:00:00.00,0:00:02.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:04.00,0:00:06.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:08.00,0:00:10.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
```

## Expected Behavior

The subtitle on the upper right should show between 1s to 9s without disappearing.

## Actual Behavior

The subtitle on the upper right will disappear between 6s to 8s

## Possible Fix

I was suspecting this is caused by outdated [libass](https://github.com/libass/libass) library as [mpv](https://github.com/mpv-player/mpv) shows the subtitle correctly (which uses same libass library to render ass subtitle as Kodi but from master branch). I tried to compile Kodi with libass from master branch but the result is the same. I cannot guarantee I compiled Kodi with correct libass library correctly though.

### To Reproduce

1. Save the above subtitle to a file named `test.ass`.
2. Play any video longer than 10s with the test subtitle file.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ehiyudeqiw.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Kodi test video at 7s, subtitle on top is not showing:
kodi

mpv test video at 7s, subtitle on top is showing:
mpv

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10, macOS Catalina, CoreELEC
 - Kodi version: 18.8

### PR DESCRIPTION
**Pull request by enen92**
Superseeds https://github.com/xbmc/xbmc/pull/18330

## Description
When libass is asked to render subtitles, it does it sequentially. It means that if two subtitles/ass events belonging to the same ass track (kodi transforms them into 2 overlays) are contained within the same timeframe, a single call to libass render_images will render both overlay pictures. To accomplish this while avoiding multiple repetitions of the same images on screen, kodi turns the subtitle stream sequential, by modifying the previous added overlay stop PTS with the new overlay start PTS. All works well unless the added overlay is **completely** contained within a previous overlay (thus startPTS > oldOne but stopPTS < oldOne). In that case we should not add the overlay since the timeframe is already contained by old event.

The following example illustrates the problem:

```
Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:01.00,0:00:09.00,TOP,,0,0,0,,{\be3\blur3\fad(200,200)}Should be on screen from 1s to 9s
Dialogue: 0,0:00:04.00,0:00:06.00,Default,,0,0,0,,{\be3}Should show/hide every 2s

```

After kodi processes the overlay collection this becomes

```
Dialogue: 0,0:00:00.00,0:00:01.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
Dialogue: 0,0:00:01.00,0:00:06.00,TOP,,0,0,0,,{\be3\blur3\fad(200,200)}Should be on screen from 1s to 9s
Dialogue: 0,0:00:04.00,0:00:06.00,Default,,0,0,0,,{\be3}Should show/hide every 2s
```

The top subtitle that should have been displayed on screen from 1 to 9s is marked to end up at 6 seconds. Thus from 6 to "whatever new subtitle entry" timestamp, no other overlay will appear on screen.

Regarding the implementation:
~Note that the only way an overlay can have the "replace" property set to `true` and without the `stopPTS = 0` is exactly any ASS overlay. Thus, this fix should be well contained and should not introduce any regressions.~

## Motivation and Context
Fixes https://github.com/xbmc/xbmc/issues/18298

## How Has This Been Tested?
With the subtitle file provided in the issue report by @Doraemoe. I tested this subtitle added externally (used to be broken) or muxed into a mkv container (where the issue did not reflect previously). Both display correctly now.
Also tested other subtitled media (srt and pgs) and didn't spot any regressions.

@Doraemoe can I ask you to re-test again? This time should be the last :)

## Screenshots (if appropriate):

**Master:**
MASTER

**PR:**
PR

Note the top overlay showing as supposed.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by MediaBrasil** [comment]
@enen92 
I test here using ISO, it´s broken subtitle, the subtitle continues on screen, wait for the next string, something need fix in your code.

**Comment by enen92** [comment]
@mefiabrasil Either report a bug properly by providing details/subtitle track that helps understand your findings or refrain from posting.

**Comment by Doraemoe** [comment]
Hi @enen92, I have tried the same pgs subtitle from last time, while normal subtitle works fine, the lyrics part during ending theme is not showing at all, only the 🎵 symbol is on screen (starting at 1:25:00)

master:
correct

this branch:
error

**Comment by enen92** [comment]
@Doraemoe thanks for the feedback, you're right. This needs to be applied only do ASS subs and not to any subtitle marked as "replaced". Please re-test with the latest implementation/commit.
@MediaBrasil please retest your iso file and check if there's any different behaviour in respect to master

File: xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp [hunk 1]
```diff
@@ -24,6 +24,8 @@ void CDVDOverlayContainer::Add(CDVDOverlay* pOverlay)
 
   CSingleLock lock(*this);
 
+  bool add = true;
```
Comment (phunkyfish) [inline xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp:27]: I would maybe call the var `addToOverlays` instead of `add`. Only because the word `add` has many meanings. But just a suggestion. Entirely up to you.

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp:27]: Will do.
Maybe you can also think of a different name for this method. `Add()` implies that the method just adds the overlay into the container. However this method doesn't only add the overlay but also does some sort of preprocessing on the container itself. When trying to understand the code, the logic here got unnoticed for a while because of the name.

Comment (phunkyfish) [reply xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp:27]: ProcessAndAddOverlayIfValid()?

**Comment by Doraemoe** [comment]
@enen92 I have tested on my end and they all work correctly now. Thank you for working on this 👍

File: xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp (hunk 1 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp:27]: That sounds right. Will adjust whenever @MediaBrasil confirms he did not spot any regression in his iso file.

**Comment by MediaBrasil** [comment]
All fine now, thanks.

**Comment by enen92** [comment]
Added a second commit to rename `CDVDOverlayContainer::Add` to `CDVDOverlayContainer:ProcessAndAddOverlayIfValid` as discussed. Also changed the `add` var name to `addToOverlays`. @phunkyfish back to you :)

**Review by phunkyfish — APPROVED** [review]
👍
