### PR TITLE
[Android][Fix] System Info displays empty/incorrect CPU info values

### LINKED ISSUE #20619: KODI 19.3 cannot show the CPU info on Firetv 4k Max
### Describe the bug
On Firetv 4k Max, the system info of KODI 19.3 does not show the CPU info. all info is empty.
the info is showing in Kodi 18.9 on Firetv 4k Max.

## Expected Behavior
Show Cpu info

## Actual Behavior
Cpu info is empty.

### Screenshots 
Here are some links or screenshots to help explain the problem:
WechatIMG2

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Firetv 4k Max, Android 9
 - Kodi version: 19.3, armv7a 
 - Kodi nightlies version: kodi-20211129-01079c43-Matrix-armeabi-v7a

### PR DESCRIPTION
**Pull request by thexai**
## Description
Implements some basic CPU info methods for Android.

Fixes https://github.com/xbmc/xbmc/issues/20619

## Motivation and context
System Info - Hardware displays empty/incorrect CPU info values. It seems that the functionality for Android was never implemented or worked differently before.

## How has this been tested?
Runtime tested on Nvidia Shield Pro 2019 (ARM64) and Android TV (ARM)

## What is the effect on users?
Provides some basic CPU info: model name, mips, frequency. ~Corrects wrong temperature indication (-1 ºC).~ 

Also improves logs info:

**Before**
```
2021-12-08 10:13:28.812 T:12633    INFO <general>: FFmpeg version/source: 4.4-Kodi
2021-12-08 10:13:28.812 T:12633    INFO <general>: 4 CPU cores available
```

**After**
```
2021-12-08 10:16:45.296 T:13108    INFO <general>: FFmpeg version/source: 4.4-Kodi
2021-12-08 10:16:45.296 T:13108    INFO <general>: Host CPU: ARMv8 Processor rev 1 (v8l), 4 cores available
```

## Screenshots (if appropriate):

**Before**
screenshot00000

**After**
screenshot00001

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/platform/android/CPUInfoAndroid.cpp [hunk 1]
```diff
@@ -31,3 +59,47 @@ CCPUInfoAndroid::CCPUInfoAndroid()
   if (CAndroidFeatures::HasNeon())
     m_cpuFeatures |= CPU_FEATURE_NEON;
 }
+
+float CCPUInfoAndroid::GetCPUFrequency()
+{
+  std::string buffer(64, 0);
+
+  if (ReadFile("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq", buffer))
```
Comment (lrusak) [inline xbmc/platform/android/CPUInfoAndroid.cpp:67]: This is the max frequency not the actual frequency (in case of dynamic frequency adjustment).

Also you should just use `CSysfsPath`

Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.cpp:67]: > This is the max frequency not the actual frequency

I know but seems in line with is used for Windows (3600 MHz is max/nominal speed not actual):

Captura de pantalla 2021-12-08 173420

This data is not refreshed and it does not make much sense to show something that is not constant value. If it refreshed automatically while staying on the same screen (same as memory usage) then it would be nice to see how it changes.

> Also you should just use CSysfsPath

It uses `std::ifstream` to read files and this c++ seems have troubles in Android due some NDK limitation:
https://stackoverflow.com/questions/32826175/ftello-and-fseeko-android-build-errors

Seems is need `__ANDROID_API__ >= 24` to use this libraries. Because this I used very basic C implementation for file read.

Comment (lrusak) [reply xbmc/platform/android/CPUInfoAndroid.cpp:67]: > This data is not refreshed and it does not make much sense to show something that is not constant value. If it refreshed automatically while staying on the same screen (same as memory usage) then it would be nice to see how it changes.
> 

Are you sure?

> 
> > Also you should just use CSysfsPath
> 
> 
> 
> It uses `std::ifstream` to read files and this c++ seems have troubles in Android due some NDK limitation:
> 
> https://stackoverflow.com/questions/32826175/ftello-and-fseeko-android-build-errors
> 
> 
> 
> Seems is need `__ANDROID_API__ >= 24` to use this libraries. Because this I used very basic C implementation for file read.
> 
> 

That's fine then. What about using `CPosixFile` or just `CFile` then?

**Comment by thexai** [comment]
Updated to use `CPosixFile` and checked that `GetCPUFrequency()` only is called one time when open hardware info (not auto-refreshed).  Then is "better" show nominal/max CPU freq. instead of actual freq.  (as CPU capabilities only)

**Comment by lrusak** [comment]
> Updated to use `CPosixFile` and checked that `GetCPUFrequency()` only is called one time when open hardware info (not auto-refreshed).  Then is "better" show nominal/max CPU freq. instead of actual freq.  (as CPU capabilities only)
> 
> 
> 
> NOTE: real-time CPU frequency can be obtained with `/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` and it works fine on Shield but is not refreshed on Kodi GUI.

I wanted to give you the opportunity to look for yourself but if you read through the code you will find that it is only updated every 15s 🙃

**Comment by thexai** [comment]
>  it is only updated every 15s

15s is useless. And on Windows is indicated nominal frequency because my CPU is NOT working 3600 Mhz all the time:

Captura de pantalla 2021-12-15 104356

And when it is fully loaded it does not work at 3600 either:

Captura de pantalla 2021-12-15 104817

So what is indicated in Windows is **nominal** CPU frequency.

I still think that the way it is now is correct...

**Comment by thexai** [comment]
In other words: I do not intend to continue working on this PR. If you think it is better than what we have now it should be approved.

If someone wants to continue improving this: for example indicating the number of cores and the working frequency of each one, the maximum and minimum specification, change update interval to 1s, fix Windows behavior (if is different of the rest of platforms), implement read CPU temperature..... they are free to do it in another PR.

**Comment by lrusak** [comment]
> >  it is only updated every 15s
> 
> 
> 
> 15s is useless. And on Windows is indicated nominal frequency because my CPU is NOT working 3600 Mhz all the time:
> 

That's beside the point really. You said it was static, I pointed out that it's not. If you would like to change it to be quicker you can make a new PR for that 🙂.

I'm sorry that this review is taking so long but that's just how it goes sometimes.

File: xbmc/platform/android/CPUInfoAndroid.h [hunk 2]
```diff
@@ -8,17 +8,26 @@
 
 #pragma once
 
+#include "utils/CPUInfo.h"
 #include "utils/Temperature.h"
 
-#include "platform/posix/CPUInfoPosix.h"
+#include "platform/posix/filesystem/PosixFile.h"
 
-class CCPUInfoAndroid : public CCPUInfoPosix
```
Comment (lrusak) [inline xbmc/platform/android/CPUInfoAndroid.h:15]: Is there a reason to not use `CCPUInfoPosix`?

That class provides a fallback for reading a script from advancedsettings to allow a user to provide an override for the cpu temperature.

See, https://github.com/xbmc/xbmc/blob/ef37e9abaad7c8a188c4656e6b89499b5caecf4a/xbmc/platform/posix/CPUInfoPosix.cpp#L15

File: xbmc/platform/android/CPUInfoAndroid.h [hunk 3]
```diff
@@ -8,17 +8,26 @@
...
+class CCPUInfoAndroid : public CCPUInfo
 {
 public:
   CCPUInfoAndroid();
   ~CCPUInfoAndroid() = default;
 
   bool SupportsCPUUsage() const override { return false; }
   int GetUsedPercentage() override { return 0; }
-  float GetCPUFrequency() override { return 0; }
+  float GetCPUFrequency() override;
```
Comment (lrusak) [inline xbmc/platform/android/CPUInfoAndroid.h:28]: By overriding this you are actually removing functionality. You should passthrough to the CCPUInfoPosix method from this method if you want to do this. See the other comment I left.

File: xbmc/platform/android/CPUInfoAndroid.h [hunk 4]
```diff
@@ -8,17 +8,26 @@
...
+  bool GetTemperature(CTemperature& temperature) override;
```
Comment (lrusak) [inline xbmc/platform/android/CPUInfoAndroid.h:29]: By overriding this you are actually removing functionality. You should passthrough to the CCPUInfoPosix method from this method if you want to do this. See the other comment I left.

File: xbmc/platform/android/CPUInfoAndroid.h (hunk 2 above)
Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.h:15]: Yes, I have two reasons:

1) Eliminate wrong/nonsense temperature indication (-1 ºC).

2) Fallback script can't really be used on Android unless the device is rooted/unlocked.

3) 99.999% of people who use Android on Fire TV Stick or similar they are not interested (I guess) in writing a script to get the CPU temperature (even if could be used on rooted devices). On the contrary, there may be a significant percentage of people who worry and think that something is wrong if they only see empty fields and a temperature of -1 ºC. Because of this, there are even people who care enough to open an Github issue... 😉

File: xbmc/platform/android/CPUInfoAndroid.h (hunk 4 above)
Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.h:29]: Yes, -1ºC feature are removed (on purpose) ;-)

Comment (lrusak) [reply xbmc/platform/android/CPUInfoAndroid.h:29]: Then it should be fixed there to be invalid if -1 is set.

Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.h:29]: We do not need to fix (in this PR) a code that is not used in Android / this PR.

Comment (lrusak) [reply xbmc/platform/android/CPUInfoAndroid.h:29]: If you fix it then you won't even need some of the changes you made. If the whole point is to fix the -1 then just do it properly and you will fix it for all POSIX platforms.

Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.h:29]: There is no point in using class `CCPUInfoPosix` in android since this class only offers to read the temperature with a script that is not possible to use in Android. So it doesn't provides any useful functionality for Android.

Comment (lrusak) [reply xbmc/platform/android/CPUInfoAndroid.h:29]: Your fix might be breaking someone else's feature.

Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.h:29]: Sorry, I don't agree

**Review by lrusak — CHANGES_REQUESTED** [review]
I have provided a way to resolve the outstanding issues. If another reviewer has an opinion about the required changes then it would be good to hear it.

**Comment by thexai** [comment]
> I have provided a way to resolve the outstanding issues

Your way of resolve ​it is still wrong:

For example: -1 ºC temperature may be valid on a Posix/Linux system if someone uses extreme cooling (liquid nitrogen).

So your solution of marking the -1 ºC temperature as "invalid" is simply not correct and is poorly designed.

Although this is the least considering point 2 and that this PR is Android only

**Comment by thexai** [comment]
Now that `-1` temperature issue has resolved on another PR (https://github.com/xbmc/xbmc/pull/20690) we can continue with this 😄

**Comment by thexai** [comment]
jenkins build this please

**Comment by thexai** [comment]
@lrusak can you take a look again?

All changes you wanted are done: is used `CCPUInfoPosix` and is not overridden `GetTemperature` method.

All of this worked fine on Leia in a similar way.

File: xbmc/platform/android/CPUInfoAndroid.cpp [hunk 5]
```diff
@@ -8,17 +8,43 @@
...
   return std::make_shared<CCPUInfoAndroid>();
 }
 
 CCPUInfoAndroid::CCPUInfoAndroid()
 {
+  m_pPosixFile = std::make_unique<CPosixFile>();
+
+  if (m_pPosixFile && m_pPosixFile->Open(CURL("/proc/cpuinfo")))
+  {
+    std::vector<char> buffer(2048, 0);
```
Comment (enen92) [inline xbmc/platform/android/CPUInfoAndroid.cpp:30]: just out of curiosity why an `std::vector` instead of an `std::array` if this seems to have a fixed size and is not dynamically resized? Wouldn't a `std::array` fit better this use case, although performance improvements are pretty much negligible?

Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.cpp]: I agree. For small buffers it is better (and more logical) to use the stack. Vectors are allocated on heap is no reason for use it if amount of memory is very small and fixed.

File: xbmc/platform/android/CPUInfoAndroid.cpp [hunk 6]
```diff
@@ -8,17 +8,43 @@
...
+#include <array>
+
 std::shared_ptr<CCPUInfo> CCPUInfo::GetCPUInfo()
 {
   return std::make_shared<CCPUInfoAndroid>();
 }
 
 CCPUInfoAndroid::CCPUInfoAndroid()
 {
+  m_pPosixFile = std::make_unique<CPosixFile>();
```
Comment (enen92) [inline xbmc/platform/android/CPUInfoAndroid.cpp:26]: Any reason for storing the file pointer as a member? Isn't it only used in the scope of this method?
If so wouldn't a local variable be better?

File: xbmc/platform/android/CPUInfoAndroid.cpp [hunk 7]
```diff
@@ -31,3 +57,23 @@ CCPUInfoAndroid::CCPUInfoAndroid()
...
 }
+
+float CCPUInfoAndroid::GetCPUFrequency()
+{
+  float freq = 0.f;
+
+  if (!m_pPosixFile)
+    return freq;
+
+  if (m_pPosixFile->Open(CURL("/sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq")))
```
Comment (enen92) [inline xbmc/platform/android/CPUInfoAndroid.cpp:68]: Same here. Open with another URL will basically call reopen. It'd be a bit more clean if file was a local variable

**Review by enen92 — APPROVED** [review]
Can't spot anything wrong with this but ideally someone else should also take a look

File: xbmc/platform/android/CPUInfoAndroid.cpp (hunk 6 above)
Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.cpp:26]: The reason was to reuse the same `CPosixFile` instance since `GetCPUFrequency` is called periodically at regular intervals while user is in System info screen.

Although seems interval is long as 15 seconds so no much difference.

File: xbmc/platform/android/CPUInfoAndroid.cpp (hunk 7 above)
Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.cpp:68]: This is the method that is called at periodic intervals and is used previously obtained `CPosixFile` instance.

File: xbmc/platform/android/CPUInfoAndroid.h [hunk 8]
```diff
@@ -20,5 +25,8 @@ class CCPUInfoAndroid : public CCPUInfoPosix
 
   bool SupportsCPUUsage() const override { return false; }
   int GetUsedPercentage() override { return 0; }
-  float GetCPUFrequency() override { return 0; }
+  float GetCPUFrequency() override;
+
+private:
+  std::unique_ptr<CPosixFile> m_pPosixFile;
```
Comment (lrusak) [inline xbmc/platform/android/CPUInfoAndroid.h:31]: Please don't use Hungarian notation.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#87-variables

Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.h:31]: I'm sorry but I don't understand what you mean. Of course I can change the names of the variables if you wish. Can you be more specific and suggest a concrete change?

Comment (fuzzard) [reply xbmc/platform/android/CPUInfoAndroid.h:31]: hungarian notation prefixes the type (p for pointer in this example) to the variable name (PosixFile). What hes saying is dont do that, just do m_posixFile

Comment (thexai) [reply xbmc/platform/android/CPUInfoAndroid.h]: Thanks!  done

**Review by lrusak — APPROVED** [review]
