### PR TITLE
changed: Move filecache buffering logic from CDVDInputStreamFile to CFile (and fixes #16845)

### LINKED ISSUE #16845: cache setting is ignored when streaming bluray over smb
### Describe the bug
Here is a clear and concise description of what the problem is:

I have changed cache setting in `advancedsettings.xml`, so if I stream bluray over http, cache setting is working; if I stream mkv over smb, cache setting is working; but if I stream bluray over smb, then cache setting is not working -- it seems we are using default cache setting instead.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Cache setting in `advancedsettings.xml` should be respected when streaming bluray over smb.

## Actual Behavior

Cache setting in `advancedsettings.xml` doesn't work when streaming bluray over smb.

## Possible Fix

I did some debugging, the call chain is

` CDVDInputStreamBluray::Open -> bd_open_files -> CBlurayCallback::file_open -> CFile::Open(std::string) -> CFile::Open(CURL)`

In `CFile::Open(CURL)`, `IsInternetStream` is called, this function returns `false` for smb.  I don't have context to decide if this is expected bahavior.

After adding "smb" to `IsInternetStream`, I have the expected behavior.

### To Reproduce
1. Modify cache setting in `advancedsettings.xml`.
2. Add a Video location that is smb and contains a bluray. 
3. Open the bluray and pause, the observe the network usage to decide if the cache setting is working.

### Debuglog
The debuglog can be found here:
https://gist.github.com/oldk1331/3ad8030b8321b0eb932c32f609b4e564

As you can see in the log, it uses `CSMBFile::Open` instead of `CFileCache::Open`.

### Screenshots 
Here are some links or screenshots to help explain the problem:

None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I think this issue is easily reproducible.

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: `android-9 | linux`
 - Kodi version: `18.4 | 19-git`

### PR DESCRIPTION
**Pull request by arnova**
This moves the FileCache buffering logic to CFile to make it more flexible and easier to maintain. It also removes enabling filecache by default for *any* internet file, since I believe this is not required anymore(probably a PAPlayer codec/Xbox remnant?).

This PR also enables filecaching for DVD/BD (fixes #16845). At least for DVDs tests have shown that it seems to work properly, although this could use some more widespread testing (especially for BD, since I don't have any).

### CODE REVIEW

File: xbmc/filesystem/File.cpp [hunk 1]
```diff
@@ -282,23 +285,40 @@ bool CFile::Open(const CURL& file, const unsigned int flags)
...
+    */
     if (!(m_flags & READ_NO_CACHE))
     {
-      const std::string pathToUrl(url.Get());
-      if (URIUtils::IsInternetStream(url, true) && !CUtil::IsPicture(pathToUrl) )
-        m_flags |= READ_CACHED;
-
-      if (m_flags & READ_CACHED)
+      const std::string pathToUrl(file.Get());
+      if ((m_flags & READ_AUDIO_VIDEO) || URIUtils::IsDVD(pathToUrl) || URIUtils::IsBluray(pathToUrl))
```
Comment (Rechi) [inline xbmc/filesystem/File.cpp]: > The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

File: xbmc/filesystem/File.cpp [hunk 2]
```diff
@@ -282,23 +285,40 @@ bool CFile::Open(const CURL& file, const unsigned int flags)
...
       {
-        // for internet stream, if it contains multiple stream, file cache need handle it specially.
-        m_pFile = new CFileCache(m_flags);
+        const unsigned int iCacheBufferMode = CServiceBroker::GetSettingsComponent()->GetAdvancedSettings()->m_cacheBufferMode;
```
Comment (Rechi) [inline xbmc/filesystem/File.cpp]: > The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

File: xbmc/filesystem/File.cpp [hunk 3]
```diff
@@ -282,23 +285,40 @@ bool CFile::Open(const CURL& file, const unsigned int flags)
...
+        if ((iCacheBufferMode == CACHE_BUFFER_MODE_INTERNET && URIUtils::IsInternetStream(pathToUrl, true))
```
Comment (Rechi) [inline xbmc/filesystem/File.cpp]: if ((iCacheBufferMode == CACHE_BUFFER_MODE_INTERNET && URIUtils::IsInternetStream(pathToUrl, true))

File: xbmc/filesystem/File.cpp [hunk 4]
```diff
@@ -282,23 +285,40 @@ bool CFile::Open(const CURL& file, const unsigned int flags)
...
+        || (iCacheBufferMode == CACHE_BUFFER_MODE_TRUE_INTERNET && URIUtils::IsInternetStream(pathToUrl, false))
```
Comment (Rechi) [inline xbmc/filesystem/File.cpp]: if ((iCacheBufferMode == CACHE_BUFFER_MODE_INTERNET && URIUtils::IsInternetStream(pathToUrl, true))

**Review by Rechi — COMMENTED** [review]
Please follow the [current code guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

**Comment by MilhouseVH** [comment]
I have included this PR in the LibreELEC `#1217` [RPi](http://forum.kodi.tv/showthread.php?tid=343068&pid=2908906#pid2908906) and [x86_64](https://forum.kodi.tv/showthread.php?tid=343069) test builds.

**Comment by phunkyfish** [comment]
@MilhouseVH any negative feedback from users on this PR?

**Comment by MilhouseVH** [comment]
After some regressions were found I stopped testing this PR on 27 Dec 2019, and I'm not sure if the plan is to proceed with this PR - if so I can resume testing.

**Comment by arnova** [comment]
> After some regressions were found I stopped testing this PR on 27 Dec 2019, and I'm not sure if the plan is to proceed with this PR - if so I can resume testing.

What kind of regressions?

**Comment by MilhouseVH** [comment]
@arnova not specifically with this PR, but I think it coincided with the smb:// and other buffering regressions so I stopped testing this PR (and never resumed).

**Comment by MilhouseVH** [comment]
Added this PR in `#0311`.

**Comment by arnova** [comment]
@MilhouseVH  / @phunkyfish : I plan on tweaking this PR a bit. Please leave open.

**Comment by oldk1331** [comment]
This fixes #16845, right?

**Comment by RuralHunter** [comment]
@arnova Any progress?

**Comment by DaveTBlake** [comment]
@arnova understand you have been unable to get back to this yet so bumping to v20 since  v19 entering Beta phase with focus on testing and bug fixes.

**Review by wsnipex — APPROVED** [review]
looks good to me

**Review by DaveTBlake — APPROVED** [review]
This has been waiting around a long time, let's get it in :)

**Comment by arnova** [comment]
Build error unrelated
