### PR TITLE
[guilib] Fix bookmark deletion in presence of chapters

### LINKED ISSUE #26074: It is not possible to remove individual bookmark on video with chapters embeded
### Describe the bug

It is not possible to remove individual bookmark on video with chapters embeded.
I mean "the long press" on individual bookmark don't works on video  with chapters embeded.
You can add a new bookmark or clean all bookmarks.

## Expected Behavior

On video without chapters embeded it is possible to remove the bookmark you want with a long press.
The long press on your bookmark list displayed a context menu "remove" bookmark.

I expect the same behaviour with video with chapters embeded.

## Actual Behavior

On video with chapters embeded you can add bookmarks but "the long press" has no effect. there is no way to remove an individual bookmark.

### To Reproduce

Good behaviour : 

1. launch a video video without chapters embeded
2. from osd open "Bookmarks"
3. add all bookmarks you want
4. from the list bookmarks chose one and long press
5. you must see "remove" bookmark"

Bad behaviour : 

1. launch a video video with chapters embeded
2. from osd open "Bookmarks" (you must see chapters already embeded)
3. add all bookmarks you want
4. from the list bookmarks chose one and long press
5. the context menu "remove bookmark" is never displayed

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/yupafikose.kodi

### Screenshots 

Good behaviour (video without chapter) : 

Bad behaviour (video with chapter) : 

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This behaviour already exist from a long time. 
It is the same with Kodi v21

### Your Environment
Used Operating system:

 - [x] Windows

 - Operating system version/name:
 - Kodi version: Kodi (22.0-ALPHA1 (21.90.700) Git:20241208-d4d9954691). 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Fix the Delete functionality of the bookmark dialog to work correctly for videos that have chapters.
It was using the index of the selected list item as an index in the bookmarks array, ignoring the chapters present in the list.

## Motivation and context

Fix #26074

## How has this been tested?

Video with and without chapters, added multiple bookmarks at different positions relative to chapters to confirm correct indexes are used.

## What is the effect on users?

Bookmarks added to videos that have chapters can now be removed by user with the bookmarks dialog.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/video/dialogs/GUIDialogVideoBookmarks.cpp [hunk 1]
```diff
@@ -161,38 +161,67 @@ bool CGUIDialogVideoBookmarks::OnAction(const CAction &action)
...
-  }
+  const int bookmarkIdx{ItemToBookmarkIndex(item)};
+  if (bookmarkIdx >= 0)
+    Delete(m_bookmarks[bookmarkIdx]);
+}
+
+void CGUIDialogVideoBookmarks::Delete(const CBookmark& bm)
+{
+  CVideoDatabase videoDatabase;
+  videoDatabase.Open();
```
Comment (ksooo) [inline xbmc/video/dialogs/GUIDialogVideoBookmarks.cpp:220]: You should handle videodb open not succeeding. At least that’s what we’re doing in most places on our code base. There must be a reason for this.

Comment (CrystalP) [reply xbmc/video/dialogs/GUIDialogVideoBookmarks.cpp:219]: That pattern is all over the place in that dialog. I'll add a commit for all of them.

**Review by ksooo — APPROVED** [review]
LGTM, thx.
