### PR TITLE
[picture] Make picture viewer work with enabled smart redraw

### LINKED ISSUE #25100: Picture display/browsing does not work properly when SmartRedraw is active (linux)
### Describe the bug
When smartredraw is active via configuration in advancedsettings.xml,

`	  <smartredraw>true</smartredraw>
`

Kodi's picture browsing  functionality stops working properly. Thumbnails of pictures in the current picture folder are displayed as normal, but when clicking on one picture to display it, the picture is loaded but appears dimmed and kodi becomes unresponsive except to the Escape key which returns kodi to the home screen.

Doing the same but with smartredraw off, the picture is loaded and shown un-dimmed (as normal) and Kodi stays responsive, pressing the arrow keys allows the user to browse the photo collection.

## Expected Behavior
Normally (without this bug), when pressing Enter on a picture, it should be displayed "un-dimmed" and Kodi stays responsive, allowing browsing of the photo collection by pressing the arrow keys

## Actual Behavior
Kodi becomes unresponsive. 

### To Reproduce

1. activate smartredraw in advancesettings.xml
2. restart kodi
3. In the main menu click on Pictures and attempt to browse the photo collection
4. click on the any of the picture thumbnails
5. the picture opens but stays fully dimmed (so barely visible) and Kodi becomes unresponsive

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
The only way to restore Picture display functionality is to disable smartredraw and restart Kodi.

The issue with this of course is that Idle power consumption of the HTPC server increases significantly - smartredraw is generally great, save for this caveat - in my case: kodi is running in an always-on HTPC server and kodi is fully usable with smartredraw on, I have been using it for a year. Other than this glitch in Picture displays and known minor glitches in the Video overlay, no issues at all with smartredraw, and power savings that smartredraw generates are very large.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X] Linux

The issue can be reproduced 100% of the time as long as smartredraw is active. 

The issue is present in the Debian packages (in ubuntu) as well as in the latest Kodi flatpak (Kodi 21, Omega)

 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: issue reproduced in both Ubuntu 23.10 and Ubuntu 22.04 
 - Kodi version: 21

The kodi log shows some errors that appear related, that appear when the problem is triggered:

2024-05-01 00:09:44.135 T:22       info <general>: Skipped 2 duplicate messages..
2024-05-01 00:09:44.135 T:22       info <general>: Loading controller layout: /app/share/kodi/addons/game.controller.default/resources/layout.xml
2024-05-01 00:09:44.139 T:11       info <general>: Loading special://xbmc/system/Lircmap.xml
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'mceusb'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'XboxDVDDongle'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'Microsoft_Xbox'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'PinnacleSysPCTVRemote'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'anysee'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'iMON-PAD'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'Antec_Veris_RM200'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'MCE_via_iMON'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'TwinHanRemote'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'linux-input-layer'
2024-05-01 00:09:44.139 T:11       info <general>: * Linking remote mapping for 'linux-input-layer' to 'cx23885_remote'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'mediacenter'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'devinput'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'devinput-32'
2024-05-01 00:09:44.139 T:11       info <general>: * Adding remote mapping for device 'devinput-64'
2024-05-01 00:09:44.143 T:22       info <general>: Loading controller layout: /app/share/kodi/addons/game.controller.mouse/resources/layout.xml
2024-05-01 00:09:44.165 T:22       info <general>: Register - new joystick device registered on addon->peripheral.joystick/0: ASRock LED Controller
2024-05-01 00:09:46.302 T:7        info <general>: Loading controller layout: /app/share/kodi/addons/game.controller.keyboard/resources/layout.xml
2024-05-01 00:09:48.881 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:09:48.882 T:15       info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-01 00:09:51.307 T:7        info <general>: Loading skin file: MyPics.xml, load type: KEEP_IN_MEMORY
2024-05-01 00:09:54.010 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:09:59.138 T:15       info <general>: Skipped 1 duplicate messages..
2024-05-01 00:09:59.138 T:15       info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-01 00:10:04.267 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:10:09.393 T:15       info <general>: Skipped 1 duplicate messages..
2024-05-01 00:10:09.393 T:15       info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-01 00:10:11.421 T:7        info <general>: Loading skin file: SlideShow.xml, load type: KEEP_IN_MEMORY
2024-05-01 00:10:14.520 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:10:18.184 T:7        info <general>: NFS is idle. Closing the remaining connections.
2024-05-01 00:10:19.646 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:10:19.647 T:15       info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-01 00:10:24.773 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:10:29.900 T:15       info <general>: Skipped 1 duplicate messages..
2024-05-01 00:10:29.900 T:15       info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-01 00:10:35.030 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:10:40.157 T:15       info <general>: Skipped 1 duplicate messages..
2024-05-01 00:10:40.157 T:15       info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-01 00:10:45.287 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:10:50.414 T:15       info <general>: Skipped 1 duplicate messages..
2024-05-01 00:10:50.414 T:15       info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-01 00:10:55.544 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:11:00.671 T:15       info <general>: Skipped 1 duplicate messages..
2024-05-01 00:11:00.671 T:15       info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-01 00:11:05.800 T:15      error <general>: CActiveAESink::OutputSamples - failed
2024-05-01 00:11:10.927 T:15       info <general>: Skipped 1 duplicate messages..
2024-05-01 00:11:10.927 T:15       info <general>: CActiveAESink::OpenSink - initialize sink
2024-05-01 00:11:16.056 T:15      error <general>: CActiveAESink::OutputSamples - failed

### PR DESCRIPTION
**Pull request by neo1973**
## Description
Fixes the problem with the picture viewer and enabled smart redraw that has been reported in https://github.com/xbmc/xbmc/issues/25100. This PR also contains additional refactorings that I did to help me understanding the code better.

Fixes #25100.

## Motivation and context
See above.

## How has this been tested?
Browsing pictures and viewing slide shows. There are problems if videos are part of the slide show but that has already been the case before this PR and fixing those are not in scope.

## What is the effect on users?
Being able to watch pictures and picture slide shows.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

File: xbmc/pictures/GUIWindowSlideShow.cpp [hunk 1]
```diff
@@ -670,9 +682,7 @@ void CGUIWindowSlideShow::Process(unsigned int currentTime, CDirtyRegionList &re
 
   RenderPause();
   if (IsVideo(*m_slides.at(m_iCurrentSlide)) && appPlayer && appPlayer->IsRenderingGuiLayer())
-  {
```
Comment (enen92) [inline xbmc/pictures/GUIWindowSlideShow.cpp:673]: I'd keep the braces for readability

**Review by enen92 — APPROVED** [review]
Thanks, looks good!

File: xbmc/pictures/GUIWindowSlideShow.cpp (hunk 1 above)
Comment (neo1973) [reply xbmc/pictures/GUIWindowSlideShow.cpp]: Done. And thanks for giving it a look :slightly_smiling_face:
