### PR TITLE
[vp][dvdcodecs] Fix crash due to nullptr exception if the number of s…

### LINKED ISSUE #20968: Nexus crash in Video Library thumb creation
### Describe the bug
Here is a clear and concise description of what the problem is:

Nexus crashes in video library creating thumbs with 

```
2022-02-08 08:45:41.438 T:15740   ERROR <general>: SQL: [MyVideos120.db] SQLite error SQLITE_ERROR (no such column: NaN)
                                                   Query: INSERT INTO streamdetails (idFile, iStreamType, strVideoCodec, fVideoAspect, iVideoWidth, iVideoHeight, iVideoDuration, strStereoMode, strVideoLanguage,  strHdrType)VALUES (23,0,'h264',NaN,0,0,48,'','','') (no such column: NaN)
2022-02-08 08:45:41.438 T:15740   ERROR <general>: CVideoDatabase::SetStreamDetailsForFileId (23) failed
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

In issues with specific files should not cause program to abor.t

## Actual Behavior

Program aborts with Windows error
```
Faulting application name: kodi.exe, version: 19.90.101.0, time stamp: 0x62008fe1
Faulting module name: ntdll.dll, version: 10.0.22000.469, time stamp: 0x931cda92
Exception code: 0xc0000374
Fault offset: 0x000000000010c0a9
Faulting process id: 0x324
Faulting application start time: 0x01d81cf225662f16
Faulting application path: D:\Nexus\kodi.exe
Faulting module path: C:\WINDOWS\SYSTEM32\ntdll.dll
Report Id: d4eda958-ac76-46ee-8015-fd6e500cc028
Faulting package full name: 
Faulting package-relative application ID: 
```

### To Reproduce

Many files cause this issue just opening and scanning a video library

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/zudiqiwiwu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Windows 11

 - Kodi version:
Kodi Nexus nightlies.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
…treams is 0

## Description
Reported in https://github.com/xbmc/xbmc/issues/20968 this fixes a nullptr access if `m_pFormatContext->streams` is null (nb_streams = 0).

Fix https://github.com/xbmc/xbmc/issues/20968

### CODE REVIEW

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp [hunk 1]
```diff
@@ -521,15 +521,17 @@ bool CDVDDemuxFFmpeg::Open(const std::shared_ptr<CDVDInputStream>& pInput, bool
   bool isBluray = pInput->IsStreamType(DVDSTREAM_TYPE_BLURAY);
   // don't re-open mpegts streams with hevc encoding as the params are not correctly detected again
   if (iformat && (strcmp(iformat->name, "mpegts") == 0) && !fileinfo && !isBluray &&
+      m_pFormatContext->nb_streams > 0 && m_pFormatContext->streams &&
```
Comment (howie-f) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:524]: checking `m_pFormatContext->streams (!= nullptr)` could be sufficient. but better safe than sorry i guess

**Review by howie-f — APPROVED** [review]
:+1:

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp (hunk 1 above)
Comment (garbear) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:524]: It should be an error condition in external code that causes nb_streams > 0 and streams == nullptr. I suggest you fix the external code. But given the error could be introduced again, it's probably best to be defensive and do both checks here.

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:524]: Yeah the two added conditions is a bit nonsense...
Maybe we should just assert (or log) before and use nb_streams > 0 in the condition?
It comes down to the fact we want Kodi crashing or not in the hypothetical case there is some logic error in depends...

Comment (garbear) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:524]: Good point, I didn't realize `nb_streams` was from an ffmpeg call (though the snake case should have tipped me off).

Yes, guard against errant depends. I'll approve the PR.

BTW, I prefer being explicit and type-safe, so I use `!= nullptr` instead of casting a pointer to bool.

**Review by garbear — APPROVED** [review]

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp (hunk 1 above)
Comment (howie-f) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:524]: i thought m_pFormatContext->streams might be int unless i digged deeper. +1 for being explicit

**Comment by enen92** [comment]
- Added an assert and an error log line in case nb_streams > 0 and AVStream array is nullptr
- Used explicit comparisons to nullptr

**Comment by enen92** [comment]
Jenkins build this please

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp [hunk 2]
```diff
@@ -519,17 +520,28 @@ bool CDVDDemuxFFmpeg::Open(const std::shared_ptr<CDVDInputStream>& pInput, bool
 
   bool skipCreateStreams = false;
   bool isBluray = pInput->IsStreamType(DVDSTREAM_TYPE_BLURAY);
+
+  // this should never happen. Assert to catch any possible bug.
+  if (m_pFormatContext->nb_streams > 0)
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:525]: Missing `m_pFormatContext->streams == nullptr`

**Comment by garbear** [comment]
Is an assert due to a depends problem appropriate? I'm all for failing early but crash to desktop when a depends screws up is kinda extreme

**Comment by enen92** [comment]
Yeah I was unsure an kinda waiting for your feedback...
Removed the assert and decided to keep the log line only.

**Review by garbear — APPROVED** [review]
Looks good now

**Review by howie-f — APPROVED** [review]
go for it

**Comment by howie-f** [comment]
jenkins build this please

**Comment by enen92** [comment]
Jenkins build and merge

**Comment by enen92** [comment]
Jenkins build this please

**Comment by enen92** [comment]
Jenkins build and merge this time please :)

**Comment by garbear** [comment]
haha denied. spurious win64 test failure. Go ahead and merge.

**Comment by enen92** [comment]
I'll wait for the playlist stuff and rebase, that should work :)

**Comment by howie-f** [comment]
jenkins build and merge
your last chance 🔫
