### PR TITLE
[Android] MediaDrm: catch restoreKeys exceptions

### LINKED ISSUE #22312: [Android] Kodi 20/21 always crash at first video playback (N€tflix addon only)
### Describe the bug
Here is a clear and concise description of what the problem is:

When you play a n€tflix video kodi crashes,
the weird thing is that this happens always for the first video played only

this crash has been reported to me by different android users

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

regular playback

## Actual Behavior

crash and exit to android homescreen

### To Reproduce

Install N€tflix addon and play a video

if crash not happens, try this step before play a video:
Open addon Expert setting "ESN \ Widevine settings", in the new window opened press "Reset" button and Ok button.
(i have no idea if could be a kind of relation, it is a bit obscure this crash)

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/asuquvafub.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

From the log seems that the crash happens when InputStream Adaptive has read the manifest
and could be maybe in the middle of Widevine initialization, this is a my theory.

Here there is the Logcat: https://paste.kodi.tv/uzocuviqik.kodi

The logcat reveals stack trace error details at line 4850 and 5100
(there are other playback attempts above that lines, but prints always same errors)

seems that could be a null array somewhere and in the stacktrace is always specified Zeroconf,
`CZeroconfBrowserAndroidDiscover::CZeroconfBrowserAndroidDiscover(CZeroconfBrowserAndroid*)`

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11 NVIDIA Shield
 - Kodi version: master branch nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Catch and log possible exceptions when restoring persisted offline keys into a new session.

In particular, catches the exceptions that are thrown when trying to restore multiple offline licenses or restoring a license if a license has already been loaded.

`MediaDrm-JNI: Illegal state exception: Failed to restore keys: ERROR_DRM_LICENSE_STATE`

Fixes the issue described in https://github.com/xbmc/xbmc/issues/22312

## How has this been tested?
Install N€tflix addon and play a video, no crash and first video plays smoothly

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
@CastagnaIT can you confirm this fixes your issue when you have time

**Comment by CastagnaIT** [comment]
tested but crash still happens
addon is stuck at same point when call crypto session Encrypt method, that i suspect make crashes relative "encrypt" jni method

the `MediaDrm: restoreKeys exception` message is not printed to the log

**Comment by joseluismarti** [comment]
Hi CastagnaIT, it's strange, it works perfectly for me on Android 12 TV.

As you describe it failed to play the first video after setting up the account for the first time or reset ESN.

After the PR catch the exception and it works:

```
12-26 11:55:38.500 18558 21871 D Kodi    : 2022-12-26 11:55:38.500 T:21871   debug <general>: MediaDrm: restoreKeys exception
12-26 11:55:38.502 18558 21871 W System.err: android.media.MediaDrm$MediaDrmStateException: Failed to restore keys: ERROR_DRM_LICENSE_STATE
12-26 11:55:38.502 18558 21871 W System.err: ============================== Beginning of DRM Plugin Log ==============================
12-26 11:55:38.502 18558 21871 W System.err:   12-25 22:15:24.662 I [cdm_engine.cpp(374):AddKey] key_set_id = 
...
```

**Comment by CastagnaIT** [comment]
maybe behaviour is different with android 11 idk
but to me has crashed
(steps done always same: addon settings-> reset ESN-> playback a video)

**Comment by joseluismarti** [comment]
I tried to see if I could identify the issue on Android 11 in an emulator and the surprise is that there is no crash. The addon also works fine on AFTV.

Could this issue only occur on Nvidia Shield, maybe it has a different implementation/version of liboemcrypto?

**Comment by CastagnaIT** [comment]
is possible no idea...thats why i tried with my PR #22325 to catch the error on Encrypt/Decrypt

**Comment by joseluismarti** [comment]
Added exception catching in these methods.

It's just a test to see if it captures them, as I can't test it, we'll see what happens with the `Buffer` that the methods return.

File: xbmc/platform/android/media/drm/MediaDrmCryptoSession.cpp [hunk 1]
```diff
@@ -170,8 +185,17 @@ void CMediaDrmCryptoSession::RestoreKeys(const std::string& keySetId)
   if (m_mediaDrm && keySetId != m_keySetId)
```
Comment (CastagnaIT) [inline xbmc/platform/android/media/drm/MediaDrmCryptoSession.cpp:185]: here better check also m_sessionId to avoid dereference a nullptr
```suggestion
  if (m_mediaDrm && m_sessionId && keySetId != m_keySetId)
```

Comment (joseluismarti) [reply xbmc/platform/android/media/drm/MediaDrmCryptoSession.cpp]: Add the check

**Comment by joseluismarti** [comment]
I propose to leave this PR as it was, since fixes a concrete situation and do the backport.

@CastagnaIT and I are testing with the other case, if we manage to find the cause we will create a new PR.

File: xbmc/platform/android/media/drm/MediaDrmCryptoSession.cpp [hunk 2]
```diff
@@ -170,8 +170,17 @@ void CMediaDrmCryptoSession::RestoreKeys(const std::string& keySetId)
...
   {
     m_mediaDrm->restoreKeys(*m_sessionId, std::vector<char>(keySetId.begin(), keySetId.end()));
-    m_hasKeys = true;
-    m_keySetId = keySetId;
+    if (xbmc_jnienv()->ExceptionCheck())
+    {
+      CLog::Log(LOGDEBUG, "MediaDrm: restoreKeys exception");
```
Comment (CastagnaIT) [inline xbmc/platform/android/media/drm/MediaDrmCryptoSession.cpp:175]: I think its better print this as error
```suggestion
      CLog::Log(LOGERROR, "MediaDrm: restoreKeys exception");
```

**Review by CastagnaIT — APPROVED** [review]
for me ok
despite not work on Nvidia Shield android 11 we will see in future

just minor thing suggested if you can change

File: xbmc/platform/android/media/drm/MediaDrmCryptoSession.cpp (hunk 2 above)
Comment (joseluismarti) [reply xbmc/platform/android/media/drm/MediaDrmCryptoSession.cpp:175]: Yes, thanks
