### PR TITLE
[VFS] Don't attempt to load directory flags for unsupported urls.

### LINKED ISSUE #28137: Kodi master crashes when adding music UPNP source.
### Describe the bug
Here is a clear and concise description of what the problem is:

Set up a test UPNP source on an Asustor NAS.
Add source in Kodi.
Add that source to library.
Crash.

Error:
Image

From call stack it's the recursive function `CMusicInfoScanner::CountFiles()`
Image

Browsing the shared UPNP directory it does seem to be recusing (so the error is their end and not in Kodi per se).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crash, even if the UPNP server is sending nonsense.

Probably as a point of principle, all recursive functions should have a depth check.

## Actual Behavior

As above.

## Possible Fix

Uploading soon.

### To Reproduce

As above.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ebuwocosik.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #28159: Starting from 20260319-967b7fa5ab, UPNP cannot be accessed
dlna server: LG SmartShare (win64)
LG TV webOS 5
The last version that could use DLNA normally was org.xbmc.kodi_20260316-4ae96f83-master_arm.ipk; log:   https://privatebin.net/?837a9ea9a6bda4b0#EvMBcTpvGLY3GjUZc3gWnBwsiWA2qPnSxbM2vnmHks5s

The first version that could not use DLNA normally was org.xbmc.kodi_20260319-967b7fa5-master_arm.ipk; log:  https://privatebin.net/?58c2d97d1722f653#B3RtRE53CgcYjq8XMsgaJCJdgk9hyBLiC1F6HJ3nEySo

I was able to reproduce this issue on both win64 and Android 12 phones.

Since I cannot access paste.kodi.tv normally, I have not uploaded the complete logs. If you need the full logs, I can send them to you privately via site message.

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Prevent checking of directory flags for unsupported vfs urls. 

## Motivation and context

Fix #28159 
Fix #28137 
Fix https://github.com/xbmc/xbmc/pull/27989#discussion_r3085455728.

## How has this been tested?

Locally with UPNP source and examining log.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] All new and existing tests passed

### CODE REVIEW

File: xbmc/filesystem/DirectoryFactory.cpp [hunk 1]
```diff
@@ -132,7 +136,11 @@ IDirectory* CDirectoryFactory::Create(const CURL& url)
   bool canBeFileDirectory = true;
 
   struct __stat64 st = {};
-  if (CFile::Stat(URIUtils::SubstitutePath(url), &st) == 0)
+  constexpr std::array<std::string_view, 5> excludedProtocols{"upnp", "special", "addons",
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/filesystem/DirectoryFactory.cpp]: Done

File: xbmc/filesystem/DirectoryFactory.cpp [hunk 2]
```diff
@@ -132,7 +136,11 @@ IDirectory* CDirectoryFactory::Create(const CURL& url)
...
+                                                              "favourites", "sources"};
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/filesystem/DirectoryFactory.cpp]: Done

File: xbmc/filesystem/DirectoryFactory.cpp [hunk 3]
```diff
@@ -92,6 +92,10 @@
 #include "utils/StringUtils.h"
 #include "utils/URIUtils.h"
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/filesystem/DirectoryFactory.cpp:90]: Done

File: xbmc/filesystem/DirectoryFactory.cpp [hunk 4]
```diff
@@ -132,7 +133,11 @@ IDirectory* CDirectoryFactory::Create(const CURL& url)
   bool canBeFileDirectory = true;
 
   struct __stat64 st = {};
-  if (CFile::Stat(URIUtils::SubstitutePath(url), &st) == 0)
+  static constexpr std::array<std::string_view, 5> excludedProtocols{"upnp", "special", "addons",
+                                                                     "favourites", "sources"};
+  const bool exclude{std::ranges::any_of(excludedProtocols, [&url](std::string_view p)
+                                         { return p == url.GetProtocol(); })};
```
Comment (neo1973) [inline xbmc/filesystem/DirectoryFactory.cpp]: I suggest this alternative implementation:

```suggestion
  static constexpr auto excludedProtocols =
      make_set<std::string_view>({"upnp", "special", "addons", "favourites", "sources"});
  const bool exclude{excludedProtocols.contains(url.GetProtocol())};
```

**Review by neo1973 — APPROVED** [review]
Looks fine, I only have an optional suggestion for an alternative implementation.

File: xbmc/filesystem/DirectoryFactory.cpp (hunk 4 above)
Comment (78andyp) [reply xbmc/filesystem/DirectoryFactory.cpp]: Thank you. Haven't come across that. Looks tidier.

**Review by garbear — APPROVED** [review]
Looks fine, and we can add more problematic protocols that come up. I think of network protocols, and creating like 100 directories would go a lot slower if each path is also stat'd first. Not sure if this is a realistic use case.

File: xbmc/filesystem/DirectoryFactory.cpp [hunk 5]
```diff
@@ -132,7 +132,10 @@ IDirectory* CDirectoryFactory::Create(const CURL& url)
   bool canBeFileDirectory = true;
 
   struct __stat64 st = {};
-  if (CFile::Stat(URIUtils::SubstitutePath(url), &st) == 0)
+  static constexpr auto excludedProtocols =
+      make_set<std::string_view>({"upnp", "special", "addons", "favourites", "sources"});
```
Comment (garbear) [inline xbmc/filesystem/DirectoryFactory.cpp:136]: @78andyp `special://` shouldn't be in the list. In my home folder (e.g. addon_data) I can't read directories with playlist extensions (e.g. `special://home/saves/Metal Gear Solid (USA).m3u/`). What do you think about removing `special://`?

Comment (78andyp) [reply xbmc/filesystem/DirectoryFactory.cpp:136]: Of course. Sorry, I was looking at the log errors when selecting those directories (other than upnp which was separate). I'll post a PR now.

Comment (78andyp) [reply xbmc/filesystem/DirectoryFactory.cpp:136]: #28230
