### PR TITLE
[addons] platform dependent addon activation at startup

### LINKED ISSUE #19079: [UWP] Clean install prompts to enable/configure all packaged binary addons
### Describe the bug
Here is a clear and concise description of what the problem is:

Recent build (Matrix RC1) on Universal Windows will prompt to enable/configure all of the binary addons that ship as part of the .MSIX package.  I believe the commit that added this behavior is here:

**[addons] allow configure and enable add-ons at kodi startup**
https://github.com/xbmc/xbmc/commit/d021eda167a316da3d747a0cb326c53c5cda7a63

It's not a TON of addons, you can get through the process relatively easily, but I really don't think this is what the author intended and something should be tweaked for the builds that need to ship with binary addons included.

I do like and appreciate the behavior for the platforms where binary addons can be installed individually.

Thanks!

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
For the Kodi builds that need to ship with all the binary addons included (UWP, tvOS, etc) I wouldn't expect to be prompted to enable all of those addons during the initial startup.

## Actual Behavior

During initial startup of Kodi, I was prompted to enable/configure each binary addon that was packaged but disabled by default.

## Possible Fix

Perhaps for these builds this behavior can be omitted, or there could be some additional AddonDisabledReason other than NONE if the addon was pre-installed.  I really didn't look into it, just wanted to report the behavior.

### To Reproduce

1. Execute a clean install of the Universal Windows .MSIX package (Windows 10)
2. Launch Kodi
3. You will be prompted to enabled/configure all of the binary addons

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/kededodeja.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [X] Windows UWP

 - Operating system version/name:
 - Kodi version: (19.0-RC1 (18.9.910) Git:20210115-90a1e12804). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by howie-f**
## Description
PR https://github.com/xbmc/xbmc/pull/19033 allows to configure and enable add-ons at kodi startup for all platforms. This is not suitable for platforms like `TVOS` and `Windows UWP` where certain add-ons need to be shipped by default. ref. https://github.com/xbmc/xbmc/issues/19079

~~thus a new environment variable `ENABLEADDONS` is introduced per platform, which controls this behavior and allows a better finetuning:~~

- disabled add-ons are now only offered for Configuration/Activation on the Linux platform (including LibreElec).
- disabled incompatible add-ons (e.g. after migration) are still checked on all platforms.

EDIT:
env var approach has been discarded. the flag will be passed through `CPlatform` -> `CServiceManager` -> `CServiceBroker`

## How Has This Been Tested?
debian buster

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Comment by ksooo** [comment]
The name of the new env var "ENABLEADDONS" is totally misleading, imo. It implies to enable or disable addons completely, not, what it actually stands for.

**Comment by lrusak** [comment]
why not add a member to `CPlatform::m_enableAddonsAtStartup` or something, then allow `CServiceBroker` to get the m_platform member from `CServiceManager` (which holds the `CPlatform` object). Then you can just call through `CServiceBroker::GetPlatform()->EnableAddonsAtStartup();`

I think that would be better than setting env variables 😄 just a thought.

**Comment by ksooo** [comment]
I also think that an environment variable does not fit here. Whether enable and configure is supported is something that is fix for a platform, this nothing that can be customized by users. The latter is what environment vars are for. Same soffits for settings and advanced settings. Imo, the value needs to be compiled into the code.

**Comment by howie-f** [comment]
yes, for sure i know an env is pretty ugly here 🤡 will now dive into the magic of Platform / Broker / Manager

File: xbmc/platform/Platform.h [hunk 1]
```diff
@@ -34,4 +34,12 @@ class CPlatform
    * or initialisation (like setting environment variables for example)
    */
   virtual bool Init();
+
+  /**\brief Enables user interacted startup activation and configuration of disabled add-ons
+   */
+  void EnableConfigureAddonsAtStartup() { m_configureAddonsAtStartup = true; };
+  bool IsConfigureAddonsAtStartupEnabled();
```
Comment (ksooo) [inline xbmc/platform/Platform.h:41]: This member function could be `const`.

File: xbmc/platform/Platform.h [hunk 2]
```diff
@@ -34,4 +34,12 @@ class CPlatform
    * or initialisation (like setting environment variables for example)
    */
   virtual bool Init();
+
+  /**\brief Enables user interacted startup activation and configuration of disabled add-ons
+   */
+  void EnableConfigureAddonsAtStartup() { m_configureAddonsAtStartup = true; };
+  bool IsConfigureAddonsAtStartupEnabled() const;
```
Comment (ksooo) [inline xbmc/platform/Platform.h:41]: Thinking about this one more time, do we actually need two members functions and a new member?

I think defining 

```c++
virtual bool IsConfigureAddonsAtStartupEnabled() { return false; }
```

 here and ovverriding it 
 
 ```c++
bool IsConfigureAddonsAtStartupEnabled() override { return true; }
```

in xbmc/platform/linux/PlatformLinux.cpp  does the job. This also makes the new member `m_configureAddonsAtStartup` obsolete and also the call to `EnableConfigureAddonsAtStartup();` in xbmc/platform/linux/PlatformLinux.cpp.

Comment (lrusak) [reply xbmc/platform/Platform.h:41]: I agree with this. 😊

Comment (howie-f) [reply xbmc/platform/Platform.h:41]: sounds absolutely reasonable

Comment (howie-f) [reply xbmc/platform/Platform.h]: needs to be overridden in `PlatformPosix` as it's the base for `PlatformLinux`; virtual/override not necessary i think, but doesn't harm though?

File: xbmc/Application.cpp [hunk 3]
```diff
@@ -4192,9 +4192,12 @@ void CApplication::ConfigureAndEnableAddons()
...
   {
-    // only look at disabled addons with disabledReason == NONE
-    // usually those are installed from package managers or manually. omit add-ons of type dependecy
-    // also try to enable add-ons with disabledReason == INCOMPATIBLE at startup
+    // this applies to certain platforms only:
+    // look at disabled addons with disabledReason == NONE, usually those are installed via package managers or manually.
+    // also try to enable add-ons with disabledReason == INCOMPATIBLE at startup for all platforms.
+
+    bool isConfigureAddonsAtStartupEnabled =
+        CServiceBroker::GetPlatform().IsConfigureAddonsAtStartupEnabled();
```
Comment (ksooo) [inline xbmc/Application.cpp:4200]: If you replace this line by just `m_ServiceManager->GetPlatform()` you can even eliminate the `CServiceBroker` changes you introduced with this PR. ;-)

File: xbmc/platform/Platform.h [hunk 4]
```diff
@@ -34,4 +34,5 @@ class CPlatform
    * or initialisation (like setting environment variables for example)
    */
   virtual bool Init();
+  virtual bool IsConfigureAddonsAtStartupEnabled() { return false; };
```
Comment (ksooo) [inline xbmc/platform/Platform.h:37]: Please add documentation for the new member function.

File: xbmc/platform/posix/PlatformPosix.h [hunk 5]
```diff
@@ -16,6 +16,7 @@ class CPlatformPosix : public CPlatform
 {
 public:
   bool Init() override;
+  bool IsConfigureAddonsAtStartupEnabled() override { return false; };
```
Comment (ksooo) [inline xbmc/platform/posix/PlatformPosix.h:19]: No need for this. CPlatformPosix inherits the implementation from CPlatform.

**Review by ksooo — CHANGES_REQUESTED** [review]

File: xbmc/platform/Platform.h (hunk 2 above)
Comment (ksooo) [reply xbmc/platform/Platform.h]: > virtual/override not necessary 

`virtual` is absolutely necessary to make this work.
`override` could be omitted, but most probably produces a compiler warning. IIRC, out coding guidelines say that we have to use `override`

File: xbmc/platform/posix/PlatformPosix.h (hunk 5 above)
Comment (howie-f) [reply xbmc/platform/posix/PlatformPosix.h]: ok, then this was while i was playing with `bool XY override const { return false;};` ...declared override, but doesnt override.. build error. anyway, this one's boiling to a 2-liner i guess. cool

**Review by lrusak — APPROVED** [review]
LGTM

**Review by ksooo — COMMENTED** [review]
Cannot say anything about the correctness of the actual functional change. C++ looks good now. ;-)

**Comment by howie-f** [comment]
will do one final UWP check before merging this

**Review by ksooo — APPROVED** [review]

**Comment by ksooo** [comment]
May I ask a short question: Is this feature really platform dependent? I understood that it is also useful if users install addons by unzipping manually and copying the addons files/structure to userdata/addon_data directory ?! Or don't we consider this an official use case - in difference to Linux package manager?

**Comment by howie-f** [comment]
yes, this would be useful for all platform imo. it's also some kind of protection against silently side-loading add-ons.
i just wasn't aware that we need to ship certain add-ons on platforms `UWP` and `tvOS` where those lead to lots of annoying enable? - popup's. and i think manually unzipping/installing is not desired by their platform design, though i'm doing this all the time on linux.

to make this feature available for all platforms we would need a `addon-manifest.xml` per platform, where auto-enabled add-ons are defined. but then still a different problem remains, when we ship all `pvr.*` add-ons to a platform, we cannot/shouldn't enable them all at once. maybe this is something we can force for v20..

or an option to enable on platforms successively where it's appropiate..
wanted this inconvenience out for `UWP`/`tvOS` :)

**Comment by howie-f** [comment]
@lrusak indeed annoying that AndroidTV users are asked to enable `inputstream.adaptive` like described on freenode.
it shouldn't as Android is derived from Posix-Platform where configuration is disabled?
i'm surprised it happens there. i don't use Android. are we running into the PlatformLinux path where this is enabled  or do i miss something else?

**Comment by howie-f** [comment]
to be more explicit:
is it because of this? https://github.com/xbmc/xbmc/blob/a877cc223670d7e4a1b50ea0e558bf2044d62271/cmake/platform/android/defines.txt#L1

**Comment by CvH** [comment]
@howie-f we sadly discovered (a bit late) that this behaviour hurts us at LibreELEC, we intentionally include disabled plugins (drivers) that should not be activated at start in any way

a proposed solution to fix that https://github.com/LibreELEC/LibreELEC.tv/pull/5403

`disabled add-ons are now only offered for Configuration/Activation on the Linux platform (including LibreElec).`
we generally don't want that, no idea if this has additional drawbacks if we disable it for LE?

**Comment by howie-f** [comment]
@CvH understandable it hurts. sorry about that.
as this auto-enable feature was only implemented on the linux platform because we wanted to catch add-ons installed via package managers (pvr addons for example) or manually, i think it's just fine to patch this out for LE. i don't see any other impact
