### PR TITLE
[cores] Fix CDVDInputStreamBluray::Open check for item being resumable.

### LINKED ISSUE #23965: Blu-ray disks can't be played from the Videos menu if Default select action is set to resume
### Describe the bug

Playing a BD iso from the Videos menu:

kodi1

if the Blu-ray playback mode is set to Show Blu-ray menu:

kodi2

and the Default select action is set to resume:

kodi3

and no resume bookmark exists, doesn't work.

## Expected Behavior

The BD should play with all that conditions.

## Actual Behavior

It doesn't play with this error:

>2023-10-20 10:24:44.180 T:2924    error <general>: CDVDDemuxFFmpeg::Open - error probing input format, nfs://192.168.1.15/mnt/DOWNLOAD/News/Test.iso
>2023-10-20 10:24:44.180 T:2924    error <general>: CVideoPlayer::OpenDemuxStream - Error creating demuxer
>2023-10-20 10:24:44.180 T:2924     info <general>: CVideoPlayer::OnExit()

### To Reproduce

Try to play a BD with all the conditions explained above.

### Debuglog

[kodi.log](https://github.com/xbmc/xbmc/files/13052059/kodi.log)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64-bit
 - Kodi version: Kodi (21.0-BETA1 (20.90.801) Git:20231018-8262078680)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Not much to say, fixes #23965 

Runtime-tested on macOS, latest Kodi master.

@enen92 can you have a look? The change imo is straight forward, check whether you actually can resume before trying. `STARTOFFSET_RESUME` value only means that we want to resume, not that we actually can.

### CODE REVIEW

File: xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamBluray.cpp [hunk 1]
```diff
@@ -332,7 +332,7 @@ bool CDVDInputStreamBluray::Open()
     m_navmode = false;
     m_titleInfo = GetTitleLongest();
   }
-  else if (resumable && m_item.GetStartOffset() == STARTOFFSET_RESUME)
+  else if (resumable && m_item.GetStartOffset() == STARTOFFSET_RESUME && m_item.IsResumable())
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamBluray.cpp:335]: Just curious why an item can have a startoffset resume and not be resumable?

Comment (ksooo) [reply xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamBluray.cpp:335]: Look what I wrote in the PR description. This special value indicates that we want to resume only, not that there is actually a resume point set.

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamBluray.cpp:335]: Just a curious question, not judging...

**Review by enen92 — APPROVED** [review]
