### PR TITLE
[upnp] Fix url extension for JPEG_TN dlna_profile

### LINKED ISSUE #20845: Problem to get the KODI icon and display the ART albums.
### Describe the bug
Hello,
I am working on an android application which is able to drive UPNP / DLNA renderers.
I am using Cling, everything is ok with Kodi except two things:

1- I can't seem to get the baseUrl that allows me to get the KODI icon. Cling returns a null baseUrl to me. The uri returned for the icon is /icon256x256.png. For the other renderers I can get the bitmap with baseUrl + iconUri.

2- When I play a song in the KODI library to KODI, the album art url is not displayed. No problem if I play from another UPNP server.

Here is a clear and concise description of what the problem is:

1-  The baseURL returned by Cling  with:
````java
device.getDetails().getBaseURL()
````
is null for KODI.
The Uri of icon returned  is : /icon256x256.png 

2- For album art issue:
it seems that the problem is the same with other apps like bubleUpnp and HIFIcast ...
An example of xml send with  AVTransport: (track on KODI library server):
````xml
<DIDL-Lite xmlns="urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:upnp="urn:schemas-upnp-org:metadata-1-0/upnp/" xmlns:dlna="urn:schemas-dlna-org:metadata-1-0/" xmlns:sec="http://www.sec.co.kr/" xmlns:xbmc="urn:schemas-xbmc-org:metadata-1-0/">
	<item id="musicdb://albums/1/-2/1.mp3?albumid=1" parentID="musicdb://albums/1/" refID="musicdb://songs/1.mp3" restricted="1">
		<dc:title>Cocaine Man3</dc:title>
		<dc:creator>Various Artists</dc:creator>
		<upnp:artist>Baxter Dury</upnp:artist>
		<upnp:artist role="Performer">Baxter Dury</upnp:artist>
		<upnp:artist role="AlbumArtist">Various Artists</upnp:artist>
		<dc:publisher>Unknown</dc:publisher>
		<upnp:album>Floor Show</upnp:album>
		<upnp:genre>Electronic</upnp:genre>
		<upnp:albumArtURI dlna:profileID="JPEG_TN">http://192.168.0.15:1822/%25/4dbf27ff1b2385a67ab319f73258c69e/Cocaine%2520Man5.mp3</upnp:albumArtURI>
		<upnp:originalTrackNumber>7</upnp:originalTrackNumber>
		<upnp:lastPlaybackTime>2009-04-22T19:24:48-01:00</upnp:lastPlaybackTime>
		<upnp:playbackCount>0</upnp:playbackCount>
		<upnp:episodeSeason>0</upnp:episodeSeason>
		<res duration="0:03:48.000" protocolInfo="http-get:*:audio/mpeg:DLNA.ORG_PN=MP3;DLNA.ORG_OP=01;DLNA.ORG_CI=0;DLNA.ORG_FLAGS=01500000000000000000000000000000">http://192.168.0.15:1822/%25/17e12d0edbc2f0bc1203f3317e2c3a73/Cocaine%2520Man5.mp3</res>
		<res protocolInfo="xbmc.org:*:album.thumb:*">http://192.168.0.15:1822/%25/4dbf27ff1b2385a67ab319f73258c69e/Cocaine%2520Man5.mp3</res>
		<res protocolInfo="xbmc.org:*:icon:*">http://192.168.0.15:1822/%25/bafcf9c3cb0801dc3b8c484cfbd87238/DefaultAudio.png</res>
		<xbmc:rating>0.0</xbmc:rating>
		<xbmc:artwork type="album.thumb">http://192.168.0.15:1822/%25/4dbf27ff1b2385a67ab319f73258c69e/Cocaine%2520Man5.mp3</xbmc:artwork>
		<xbmc:artwork type="icon">http://192.168.0.15:1822/%25/bafcf9c3cb0801dc3b8c484cfbd87238/DefaultAudio.png</xbmc:artwork>
		<xbmc:userrating>0</xbmc:userrating>
		<upnp:class>object.item.audioItem.musicTrack</upnp:class>
	</item>
</DIDL-Lite>
````
There is no problem when the track is broadcast on KODI as a renderer from another upnp server. The art is displayed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

1- Get the KODI icon with BaseUrl / icon 256x256.png.

2- Display ART albums on the KODI player even when the track is in the KODI library.

## Actual Behavior

none

## Possible Fix

no idea

### To Reproduce

For albums art issue:
1.  Install KODI on android TV (MI BOX s for me) and buubleUPNP on android phone.
2. Allow upnp renderer in KODI
3.  play a track in KODI librairie to KODI renederer from bubleUPNP.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

KODI on MI Box s android tv (android PIE 29)
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This is quite an obscure use case but kodi can be used as the upnp renderer of its own upnp server/library. In such cases, kodi fails to display the artwork thumb in the video osd. This happens because even though the server thumb url is created by kodi and has the dlna_profile set to jpeg, the complete url has the extension of the media item (e.g. .flac, .mp3, etc). It works and downloads the image but kodi internal mechanisms to probe media (e.g. `GetMimeType()` won't flag the item as an image). Since we have full control of these server resources, just add `/thumb` to the url to avoid the possibility of flagging the image as audio/video.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/20845

## How has this been tested?
Runtime tested, bubleupnp on android, kodi as renderer, kodi as upnp source.

## What is the effect on users?
0.0000001% of users will have thumbs when using a upnp client as remote for kodi internal music library :)

## Screenshots (if appropriate):
**Before:**
image

**Now:**
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by enen92** [comment]
Jenkins build this please

File: xbmc/network/upnp/UPnPInternal.cpp [hunk 1]
```diff
@@ -609,19 +609,20 @@ BuildObject(CFileItem&                    item,
...
+          {
+            art.dlna_profile = "PNG_TN";
+          }
+          else
+          {
+            art.dlna_profile = "JPEG_TN";
+          }
+          art.uri = upnp_server->BuildSafeResourceUri(
+              rooturi, (*ips.GetFirstItem()).ToString(),
+              std::string(CTextureUtils::GetWrappedImageURL(thumb) + "/thumb").c_str());
```
Comment (garbear) [inline xbmc/network/upnp/UPnPInternal.cpp:624]: This needs documentation in the code about where "/thumb" comes from.

Comment (enen92) [reply xbmc/network/upnp/UPnPInternal.cpp:626]: done

**Review by garbear — APPROVED** [review]
Seems kinda hacky but I have no objections.

**Comment by enen92** [comment]
Yeap it is kind of a workaround to the problem but at the same time it's logical that client applications might infer a given remote file is an audio file if it ends up as .mp3 or .flac avoiding (for example) expensive and slow head requests.

**Comment by Montellese** [comment]
Shouldn't we also look into improving the client / renderer side to properly process the DLNA profile into a more accurate MIME type?

**Comment by enen92** [comment]
@Montellese imho I don't think so. The GetMimeType() method is used in a lot of places in Kodi. The likelihood of introducing regressions in other parts of the codebase (or making other parts slow) is quite high for the benefits that improvement can possibly bring. This issue doesn't only occur in Kodi - if you download one of the thumbs (extension .MP3 or .flac) your file browser will certainly associate it to a music player despite the fact the file is a picture. Behaviour could be different but at what performance cost?

**Comment by fiasko131** [comment]
@enen92 
"0.0000001% of users will have thumbs when using a upnp client as remote for kodi internal music library :)"

Not necessarily, in my development I can build playlists with various original files (DLNA, SMB, CLOUD, WEBDAV, FTP, internal...etc)
So it may concern 0.005% :))!

Not necessarily, in my development I can build playlists with various original files (DLNA, SMB, WEBDAV, FTP, internal...etc)
So it may concern 0.005% :))!

For me the workaraound is to point the url to an http server on the phone. (ex: http://LANIP:54467/art_downloaded_from_kodi.png)
