### PR TITLE
[Audio] TrueHD rework - totally new MAT packer implementation

### LINKED ISSUE #24944: TrueHD Atmos Dropouts/Cutouts on Kodi 20.5 (assuming only seamless branched sources)
### Describe the bug
When using some TrueHD Atmos tracks in passthrough, I get audio drop outs and cut outs. The issue seems to only occur for seamless branched sources around seamless branching points, and while usually around the same parts, it does not always occur at a given part, nor does it occur at the same exact points most times.

## Expected Behavior
Play the file with no dropouts/cutouts in audio, much like most TrueHD Atmos tracks already play.

## Actual Behavior
You play an affected file, and at first everything works well, before long the audio starts to have short dropouts before coming back, with some affected files having this occur more frequently then others.

## Possible Fix
From what I can see in the log files (but I'm inexperienced) it seems to be a sync issue, moreover, it seems the longer the file plays/is, the more likely you are to encounter this issue.

### To Reproduce
1. Load an affected file ([such as this sample](https://drive.google.com/file/d/1zkcp5aOYE4Wtulq726ehSzSXQMhvDuVM/view?usp=sharing)) or others mentioned on the Kodi Forum post linked below
2. Watch and wait to hear the audio dropouts occur, in the case of the sample file, it can come up when it mentions 'Pixar' with the cars going around, or when they mention 'the last thing they expect was lightning mcqueen' or a little after 'three cars, one champion'

### Debuglog
Original (Android, 20.5, large): https://paste.kodi.tv/atanowavek.kodi
New (Android, 20.5, only 5min of file used): https://paste.kodi.tv/lepusidepa.kodi
Windows 20.5 (5 minutes of file used): https://paste.kodi.tv/opowiniriq.kodi
Windows 20.5 (cut to the last minute file used): https://paste.kodi.tv/qivaxigaca.kodi

### Screenshots 
Not applicable as this is an audio issue

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Forum Discussion has occurred here: https://forum.kodi.tv/showthread.php?tid=376726

Files were tested using Gigabit Ethernet SMB share, the following files were tested:
Cars (2006) - Frequent Dropouts at the start of the file, and glitchy sound RZ50 makes due to dropouts
Cars 2 (2011) - Frequent Dropouts towards the last two thirds of the file, and glitchy sound RZ50 makes due to dropouts
Enchanted (2007) - No issues the whole way through
Fast and Furious 9 (2021) - No issues within 30 minutes (issue usually occurs by then if there is one)
Midway (2019) - No issues within 30 minutes (issue usually occurs by then if there is one)
Elemental (2023) - Two drops and then eventually changed to a glitchy sound the Onyko RZ50 makes due to dropouts for a second or two before correcting, all within the first 7 minutes
Aliens (1986) - No issues within 30 minutes (issue usually occurs by then if there is one)
The Suicide Squad (2021) - Two drops within 30 minutes

Troubleshooting performed previously:
    Recreate the file with the latest version of MakeMKV and DGDemux: Did not fix
    Try it in VLC (Android/Windows): No issues found
    Try it on Windows Kodi: Did not fix
    Try it on another AVR / Soundbar that supports TrueHD passthrough (Android platform): Did not fix on the two other systems tried

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 22H2 / Android 11 and 9? (before and after SHIELD upgrade 9)
 - Kodi version: 20.5 / 21 Beta 2 / 21 RC1 / 21 RC2 / 21 Stable

### PR DESCRIPTION
**Pull request by thexai**
## Description
 TrueHD rework - totally new MAT packer implementation

Based on LAVFilters: https://github.com/Nevcairiel/LAVFilters/blob/master/decoder/LAVAudio/BitstreamMAT.cpp
with some optimizations.

## Motivation and context
Initially I was trying to solve/debug the issues mentioned in https://github.com/xbmc/xbmc/issues/24944 with a specific test stream. While it may not fix all problems on rare (or even broken) streams, I have seen things wrong and limitations in the current TrueHD MAT packer implementation (which is the same as FFMpeg).

The new implementation is logically different but there are also some important conceptual differences:

**1)** The 8 bytes of the IEC header are now counted as padding, that is, when padding is written 16 more bytes are deducted than before: MAT frames have 61424 bytes but for padding they count as 61440. The other 8 bytes are obtained from `mat_end_code` now is 24 bytes length (16 before).

Previously, these bytes were also set to zero until complete 61440 bytes, but they were not used for the padding calculation.
This happens here:
https://github.com/xbmc/xbmc/blob/4d70847511fc1461a12218020b57c77b861c1a67/xbmc/cores/AudioEngine/Utils/AEPackIEC61937.cpp#L111C3-L111C104

the structure is:

`| IEC_HEADER (8 bytes) | MAT_FRAME (61424 bytes) | unused 8 bytes |`

8 + 61424 + 8 = 61440

these "unused" bytes before was filled with zeros but not counted as padding. Now the size when call `CAEPackIEC61937::PackTrueHD` is 61432 and these 8 bytes are part of `mat_end_code` (last memset call does nothing because all packet bytes already set).

**2)** Before it was not possible to generate padding with a length bigger than one MAT frame (61424 bytes). Now there is virtually no limit e.g. 300,000 bytes of padding can be written and are generated all necessary MAT frames (even if only contains padding) and queued. 

In fact, a workaround is currently used to minimize the problem and not consider invalid stream or a seek, but the necessary amount of padding is still not generated:

https://github.com/xbmc/xbmc/blob/4d70847511fc1461a12218020b57c77b861c1a67/xbmc/cores/AudioEngine/Utils/AEBitstreamPacker.cpp#L225-L230

This code is originally in FFmpeg:

`if (padding_remaining < 0 || padding_remaining >= MAT_FRAME_SIZE / 2)
`

This can happen, for example, if a stream is badly cut and is missing audio frames: as each TrueHD unit has timestamps, if eg. 40 frames are removed, the MAT packer needs to fill in the equivalent time of the missing frames with padding bytes.

e.g. 20 ms of stream missing ---> 61440 bytes of padding generated 

This is directly related to seamless branching Blu-Ray's since some demuxers removes audio units that overlap at the union of .m2ts segments (in itself you have to remove some data because there are repeated/overlapped TrueHD frames) https://github.com/domyd/mlp?tab=readme-ov-file#faq

This happens simply when converting from BDMV structure to MKV with any video converter tool...

**3)** Directly related to the previous point, there are specific instants when the MAT packer may generate more frames than are consumed and they need to be queued so that they are not overwritten/lost. This was not possible before.

## How has this been tested?
Runtime Windows x64 and Shield

## What is the effect on users?
More robust TrueHD passtrough audio. Even if still not fixes ALL issues on ALL streams (even the broken ones).

Many more cases are taken into account and it should work better. In the tests I have not found a single stream where this implementation works worse than before, but there are still some specific streams that have issues at very specific times (small cut/dropout) coinciding with unusually large padding blocks or stream discontinuities events.

Now these "unusual" events are properly registered in logs as warning/debug.

**EDIT:**
I'm not sure but this could also solve a/v sync problems that only some users have (and only with TrueHD). The reasoning/ guesswork is: almost all TrueHD streams usually start with padding bytes. Since padding > 61424 bytes is not supported now, the beginning of the audio is lost so it starts ahead. In some setups this is compensated by HDMI CEC/lipsync (if enabled)... in others it is not. This could improve if all streams now start with the necessary amount of padding.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fritsch** [comment]
@anssih as the original author for both ffmpeg and kodi MAT packer, this PR might be interesting to you, also towards ffmpeg upstream.

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp [hunk 1]
```diff
@@ -0,0 +1,440 @@
...
+    m_state.padding = 0;
+    m_state.matFramesize = -remaining;
+  }
+}
+
+void CPackerMAT::AppendData(const uint8_t* data, int size, Type type)
+{
+  // for padding not write anything, only skip bytes
+  if (type == Type::DATA)
+    memcpy(m_buffer.data() + m_bufferCount, data, size);
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:271]: Can you update just use m_buffer.size() instead of tracking it in m_bufferCount?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h [hunk 2]
```diff
@@ -0,0 +1,106 @@
...
+
+struct TrueHDMajorSyncInfo
+{
+  int ratebits{0};
+  uint16_t outputTiming{0};
+  bool outputTimingPresent{false};
+  bool valid{false};
+};
+
+enum class Type : bool
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.h:23]: Does this need to use a bool underlying type?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h [hunk 3]
```diff
@@ -0,0 +1,106 @@
...
+    int nSamplesOffset;
+  };
+
+  void WriteHeader();
+  void WritePadding();
+  void AppendData(const uint8_t* data, int size, Type type);
+  uint32_t GetCount() const { return m_bufferCount; }
+  int FillDataBuffer(const uint8_t* data, int size, Type type);
+  void FlushPacket();
+  static TrueHDMajorSyncInfo ParseTrueHDMajorSyncHeaders(const uint8_t* p, int buffsize);
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.h:64]: static?

Also maybe use std::optional instead of using the valid strict member?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h [hunk 4]
```diff
@@ -0,0 +1,106 @@
...
+  uint32_t m_bufferCount{0};
+  std::vector<uint8_t> m_buffer;
+  std::deque<std::vector<uint8_t>> m_outputQueue;
+};
+
+class CBitStream
+{
+public:
+  // opens an existing byte array as bitstream
+  void OpenBytes(const uint8_t* bytes, int _size)
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.h:79]: Can this just be the constructor?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h [hunk 5]
```diff
@@ -0,0 +1,106 @@
...
+      dat = dat * 2 + getbit(data[i / 8], i % 8);
+    }
+    index += bits;
+    return dat;
+  }
+  // skip bits from bitstream
+  void SkipBits(int bits) { index += bits; }
+
+private:
+  bool getbit(uint8_t x, int y) { return (x >> (7 - y)) & 1; }
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.h:101]: Return a uint8_t instead of a bool because this function is used in addition above.

File: xbmc/cores/AudioEngine/Utils/AEBitstreamPacker.cpp [hunk 6]
```diff
@@ -162,149 +131,26 @@ void CAEBitstreamPacker::Reset()
...
-    /* padding needed before this frame */
-    paddingRem = deltaBytes - m_thd.prevFrameSize;
-
-    // detects stream discontinuities
-    if (paddingRem < 0 || paddingRem >= MAT_FRAME_SIZE * 2)
-    {
-      m_thd = {}; // recovering after seek
-      return;
-    }
+    std::vector<uint8_t> mat{m_packerMAT->GetOutputFrame()};
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/AEBitstreamPacker.cpp:149]: If this returns a default constructed std::vector can the next line function? ie. Is it valid to not return output frames?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp [hunk 7]
```diff
@@ -0,0 +1,440 @@
...
+  // In average all frames are always padded to 2560 bytes, so that 24 frames fit in one MAT frame, however
+  // due to bitrate spikes single sync frames have been observed to use up to twice that size, in which
+  // case they'll be preceded by smaller frames to keep the average bitrate constant.
+  // A constant padding to 2560 bytes can work (this is how the ffmpeg spdifenc module works), however
+  // high-bitrate streams can overshoot this size and therefor require proper handling of dynamic padding.
+
+  TrueHDMajorSyncInfo info;
+
+  // get the ratebits and output timing from the sync frame
+  if (AV_RB32(data + 4) == 0xf8726fba)
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:62]: Define the constant?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp [hunk 8]
```diff
@@ -0,0 +1,440 @@
...
+void CPackerMAT::FlushPacket()
+{
+  if (GetCount() == 0)
+    return;
+
+  assert(GetCount() == MAT_BUFFER_SIZE);
+
+  // normal number of samples per frame
+  const uint16_t frameSamples = 40 << (m_state.ratebits & 7);
+  const uint32_t nMATSamples = (frameSamples * 24);
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:345]: MATSamples

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp [hunk 9]
```diff
@@ -0,0 +1,440 @@
...
+TrueHDMajorSyncInfo CPackerMAT::ParseTrueHDMajorSyncHeaders(const uint8_t* p, int buffsize)
+{
+  TrueHDMajorSyncInfo info;
+
+  if (buffsize < 32)
+    return {};
+
+  // parse major sync and look for a restart header
+  int majorSyncSize = 28;
+  if (p[29] & 1)
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:376]: What's the significance of index 29? And 1?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp [hunk 10]
```diff
@@ -0,0 +1,440 @@
...
+  {
+    int extensionSize = p[30] >> 4;
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:378]: What's the significance of index 30?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h [hunk 11]
```diff
@@ -0,0 +1,106 @@
...
+
+    uint16_t prevFrametime;
+    bool prevFrametimeValid;
+
+    uint32_t matFramesize;
+    uint32_t prevMatFramesize;
+
+    uint32_t padding;
+    uint32_t nSamples;
+    int nSamplesOffset;
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.h:55]: samplesOffset

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h [hunk 12]
```diff
@@ -0,0 +1,106 @@
...
+    bool outputTimingValid;
+
+    uint16_t prevFrametime;
+    bool prevFrametimeValid;
+
+    uint32_t matFramesize;
+    uint32_t prevMatFramesize;
+
+    uint32_t padding;
+    uint32_t nSamples;
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.h:54]: samples

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h [hunk 13]
```diff
@@ -0,0 +1,106 @@
...
+  uint32_t GetCount() const { return m_bufferCount; }
+  int FillDataBuffer(const uint8_t* data, int size, Type type);
+  void FlushPacket();
+  static TrueHDMajorSyncInfo ParseTrueHDMajorSyncHeaders(const uint8_t* p, int buffsize);
+
+  MATState m_state{};
+
+  bool m_logPadding{false};
+
+  uint32_t m_bufferCount{0};
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/PackerMAT.h:70]: Needed?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h (hunk 3 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.h:64]: Not uses any member variable but can be also const method. Changed.

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h (hunk 4 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.h:79]: Yes, changed

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp (hunk 7 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:62]: done

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp (hunk 9 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:376]: added code comment

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp (hunk 1 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:271]: Is for performance reasons: this works at very high rate 1200 times/second and I want avoid resize vector every ~0.83 ms

Vector is used only as buffer for allocate memory and easy transfer latter to `std::deque`. 

Vector "only" is resized one time every ~20 ms instead to clean and fill zeros.

Second reason is that is not filled sequentially (padding bytes are skipped): technically fist is filled with zeros and after are written only some non-contiguous areas.

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h (hunk 13 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.h:70]: Yes, to avoid resize vector many times in all intermediate operations

**Comment by thexai** [comment]
Applied all code review suggestions except vector resize, for performance reasons.

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h (hunk 3 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.h]: > Also maybe use std::optional instead of using the valid strict member?

If `std::optional` suppose any minimal overhead I want avoid it for performance reasons.

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h (hunk 11 above)
Comment (malard) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.h]: i think the N holds useful explination here, rather than saying this is an offset from "samples" (whatever that is), its saying the number of samples offset. Which I dont think is implied from the variable samplesOffset

Comment (lrusak) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.h]: I think clarity through language is better than through convention. So if it's desired to have it define the amount I would rather use numberOfSamplesOffset or samplesOffsetCount.

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h (hunk 12 above)
Comment (lrusak) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.h]: See other comment

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp (hunk 1 above)
Comment (lrusak) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:273]: Ah ok, would it possible to reserve an amount to avoid reallocations?

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h (hunk 11 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.h]: Added code comments to clarify the meaning of each variable

File: xbmc/cores/AudioEngine/Utils/PackerMAT.cpp (hunk 1 above)
Comment (thexai) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.cpp:274]: Already done it in L47:

```
CPackerMAT::CPackerMAT()
{
  m_buffer.reserve(MAT_BUFFER_SIZE);
}
```

File: xbmc/cores/AudioEngine/Utils/PackerMAT.h (hunk 11 above)
Comment (malard) [reply xbmc/cores/AudioEngine/Utils/PackerMAT.h]: > I think clarity through language is better than through convention. So if it's desired to have it define the amount I would rather use numberOfSamplesOffset or samplesOffsetCount.

I agree on this point, the n made sense to me as I understand the context, to others without it later could infer other meaning. We're on the same page! :)

**Comment by thexai** [comment]
Rebased only, no changes.

**Comment by thexai** [comment]
This has been tested for almost two weeks on the forum (https://forum.kodi.tv/showthread.php?tid=377117) by several users and they have not reported a single issue. They are familiar/intensive TrueHD users and some were still reporting rare/sporadic audio dropouts/cuts in the current implementation.

It is time to merge it to obtain a broader test base? LibreELEC / CoreELEC nightlies users...

@fritsch ?

**Review by fritsch — APPROVED** [review]
Better code we understand, works and is maintained.

**Comment by mitzsch** [comment]
Peeking into this issue. Although the audio cutouts are gone, at least they are gone on my end. (CoreElec nightly)
TrueHD Files with seamless branching encounter frame drops around the merging spots. (Not happening with DTS-HD files, so must be a TrueHD issue, Kodi.log shows `info <general>: CPackerMAT::PackTrueHD: seek detected, re-initializing MAT packer state`) Some frame drops are more noticeable than others, but in any case, they distract. So it seems it's not the end of things regarding trueHD passthrough

Coming from the MPV side of things, I currently maintain two ffmpeg versions, one with the "legacy" ffmpeg truehd code (... that falls apart on truehd audio tracks above 11mbit, mostly Disney titles; the code was also initially used by Kodi as far as I can tell) and one with the "upstream" truehd ffmpeg logic + patches made by a former Plex employee... (differs from the Kodi/lavfilter logic)

On my Windows HTPC system with mpv, the older legacy TrueHD code works perfectly fine with seamless branching files. In my region, there are also no trueHD tracks that exceed that 11mbit mark, so also not a problem for me...


Bold question: Would it be possible to just let the user decide which TrueHD logic he wants to use? Of course, that means the initial Kodi TrueHD code needs to be rebased... until all issues with TrueHD are fixed?

**Comment by thexai** [comment]
It doesn't make much sense to use older code when you know with absolute certainty that all previous code is worse in several ways. I don't feel like going into too much detail because everything is documented and there's information about all the changes (you just have to search). I'm not the one interested in this, so I don't need to prove anything... plenty of tests have been done, including what you suggest about using the older MAT code in the current branch (IT HAS ALREADY BEEN DONE).

> More research has been done to determine exactly what role the new MAT code plays in this: That is, the old MAT code moved to CDVDAudioCodecPassthrough has also been tested along with the rest of the improvements.

>
> See: https://github.com/thexai/xbmc/commit/7426e69b0d8d34839cb0d1474c9d2e993d10707c
>
> The result is that it improves a lot but does not completely eliminate all dropouts in Cars. So, the conclusion is that the old MAT code has limitations and is not capable of handling all TrueHD sources (although it works fine in 99.9% of the cases). This would affect all setups and all platforms since it does not depend on timings or performance things but on the MAT code itself.
> 
> Then the new MAT code is necessary to fix this completely.

https://github.com/xbmc/xbmc/pull/25312

If you can compile CoreElec yourself, you can include this diff.

You're assuming that a problem (which isn't even audio-related) is caused by the MAT code, which only modifies the audio stream. It's possible, but unlikely.

It could be anything else.

It could (or not) be that it's just because Blu-Ray's with TrueHD usually also have Dolby Vision, and perhaps it's a side effect of the dynamic metadata. Specifically, **v21.2** has a similar problem (it could be affecting you depending on the version you're using). 

See: https://github.com/xbmc/xbmc/pull/26731

That is fixed in the master branch and v21 nightly only (or future v21.3).

**Comment by thexai** [comment]
Based on your comment here:
https://github.com/mpv-player/mpv/issues/11538#issuecomment-2972755325

You have this issue with "all" video players:

mpv / Kodi / mpc / madVR

```
Software                            | metadata changed?      |  behavior?
--------------------------------------------------------------------------------------------
mpv-x86_64-v3-20250608-git-a418d21  | yes                    | visible stutter and registered frame drop

KODI 20.1                           | yes                    | visible stutter but no registered frame drop

KODI 21.2                           | yes                    | complete dropout of the signal - comes back after some time

KODI 22 ALPHA 1                     | yes                    | visible stutter but no registered frame drop

madVR 0.92.17 / build 208           | yes                    | visible stutter and registered frame drop (glitch)

```

Then maybe is not caused by the player 🙂

**Comment by mitzsch** [comment]
> Then maybe is not caused by the player 🙂

Good catch, but that is a completely different issue. The/My issue that you have linked has nothing to do with TrueHD/Atmos. The issue over there is most likely a Nvidia driver bug.... It's a video-only issue; it also happens with files that don't have audio... The issue arises when the different parts of the movie have different HDR metadata. It seems the Nvidia driver takes too long to process the change of metadata and drops frames. On my AmLogic device, it does not appear. The file there also has a DTS-HD track ;)


The issue I'm referring to here is only trueHD/Atmos and seamless branching.

> plenty of tests have been done, including what you suggest about using the older MAT code in the current branch (IT HAS ALREADY BEEN DONE).

Ahhh - I should have looked more into the commit messages! Sorry for making you upset!


>https://github.com/xbmc/xbmc/pull/25312 | If you can compile CoreElec yourself, you can include this diff.

I will try, thanks! I have a VM that I use for CE compiles... so it should be done easily...



I will do some further tests on this topic. I'm also currently looking into the possibility that makemkv could have screwed up creating that file (although somewhat unlikely, but the file created by makemkv throws errors on the merging spot, whereas the same movie created by mkvtoolnix does not... need to test this on my HT system with passthrough.)

##Edit/Update:

Behavior is the same between the file created by makemkv and mkvtoolnix... I just reencoded the Atmos track and now everything works fine... Also, AC3 tracks experience dropouts at the merging spot... reencoded that track as well, and now it works too.
