### PR TITLE
[filesystem][CurlFile] Allow explicit use of HTTP Basic authentication

### LINKED ISSUE #22035: Webdav - Anonymous requests
### Describe the bug
Here is a clear and concise description of what the problem is:

When using Webdav source (Nextcloud in my case), Kodi executes two requests for each normal requests:
- One unauthenticated request
- One authenticated as expected

Here is an example of logs from Apache showing the issue. The user is "kodi" as you can see, each file request is composed of first an unauthenticated request, resulting in a 401 status code, and one authenticated request (resulting in a 404 which is normal here):

> 192.168.144.2 - - [15/Oct/2022:21:26:26 +0000] "HEAD /remote.php/dav/files/kodi/Documents/Folder.JPG HTTP/1.1" 401 591 "-" "Kodi/19.3 (Linux; Android 9.0; MIBOX4 Build/PI) Android/9.0.0 Sys_CPU/armv8l App_Bitness/32 Version/19.3-(19.3.0)-Git:20211024-49a04cd6a7"
192.168.144.2 - kodi [15/Oct/2022:21:26:26 +0000] "HEAD /remote.php/dav/files/kodi/Documents/Folder.JPG HTTP/1.1" 404 528 "-" "Kodi/19.3 (Linux; Android 9.0; MIBOX4 Build/PI) Android/9.0.0 Sys_CPU/armv8l App_Bitness/32 Version/19.3-(19.3.0)-Git:20211024-49a04cd6a7"
192.168.144.2 - - [15/Oct/2022:21:26:26 +0000] "HEAD /remote.php/dav/files/kodi/Documents/Folder.jpg HTTP/1.1" 401 591 "-" "Kodi/19.3 (Linux; Android 9.0; MIBOX4 Build/PI) Android/9.0.0 Sys_CPU/armv8l App_Bitness/32 Version/19.3-(19.3.0)-Git:20211024-49a04cd6a7"
192.168.144.2 - kodi [15/Oct/2022:21:26:26 +0000] "HEAD /remote.php/dav/files/kodi/Documents/Folder.jpg HTTP/1.1" 404 528 "-" "Kodi/19.3 (Linux; Android 9.0; MIBOX4 Build/PI) Android/9.0.0 Sys_CPU/armv8l App_Bitness/32 Version/19.3-(19.3.0)-Git:20211024-49a04cd6a7"
192.168.144.2 - - [15/Oct/2022:21:26:27 +0000] "HEAD /remote.php/dav/files/kodi/Documents/cover.jpg HTTP/1.1" 401 591 "-" "Kodi/19.3 (Linux; Android 9.0; MIBOX4 Build/PI) Android/9.0.0 Sys_CPU/armv8l App_Bitness/32 Version/19.3-(19.3.0)-Git:20211024-49a04cd6a7"
192.168.144.2 - kodi [15/Oct/2022:21:26:27 +0000] "HEAD /remote.php/dav/files/kodi/Documents/cover.jpg HTTP/1.1" 404 528 "-" "Kodi/19.3 (Linux; Android 9.0; MIBOX4 Build/PI) Android/9.0.0 Sys_CPU/armv8l App_Bitness/32 Version/19.3-(19.3.0)-Git:20211024-49a04cd6a7"
192.168.144.2 - - [15/Oct/2022:21:26:27 +0000] "HEAD /remote.php/dav/files/kodi/Documents/cover.JPG HTTP/1.1" 401 591 "-" "Kodi/19.3 (Linux; Android 9.0; MIBOX4 Build/PI) Android/9.0.0 Sys_CPU/armv8l App_Bitness/32 Version/19.3-(19.3.0)-Git:20211024-49a04cd6a7"
192.168.144.2 - kodi [15/Oct/2022:21:26:27 +0000] "HEAD /remote.php/dav/files/kodi/Documents/cover.JPG HTTP/1.1" 404 528 "-" "Kodi/19.3 (Linux; Android 9.0; MIBOX4 Build/PI) Android/9.0.0 Sys_CPU/armv8l App_Bitness/32 Version/19.3-(19.3.0)-Git:20211024-49a04cd6a7"

This problem causes fail2ban to jail my TV as it receives too many 401. It's disabled for the test above.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Normally, only authenticated requests should be sent if  user/password has been defined in the Webdav source

## Actual Behavior

Each Webdav request is doubled: One authenticated and one unauthenticated.

### To Reproduce

1. Connect to a webdav source which requires a user/password
2. Look at the logs from the server

### Debuglog

The debuglog can be found here:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9.0; MIBOX4 Build
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by Syquel**
## Description
Currently libcurl issues an unauthenticated request to the backend first to identify the available authentication mechanisms if no specifiy authentication mechanism has been specified. By allowing users to explicitly specify HTTP Basic authentication as the desired mechanism this extra roundtrip can be omitted.

## Motivation and context
Fix #22035  

If no specific authentication mechanism is specified in WebDAV URLs libcurl issues an anonymous HTTP request first to identify available authentication mechanisms before executing the desired authenticated request.  
In case of WebDav this results in a lot of "double" requests for each file in a directory and probing for additional meta files such as covers and thumbnails.  
Currently there is no way to specify HTTP Basic authentication as the desired authentication mechanism and therefore there is no way to avoid these extra unauthenticated requests for these files.

## How has this been tested?
1.  Compiled branch on Fedora Linux 42
2. Started Kodi
3. Added WebDAV video source with "|auth=basic" parameter in the URL (https://<my.webdav.host>:443/|auth=basic)
4. Browsed through WebDAV video source
5. Checked that there are only authenticated requests in the WebDAV HTTP server logs

## What is the effect on users?
Enable improved browsing performance of WebDAV sources with explicit HTTP Basic authentication

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/addons/kodi-dev-kit/include/kodi/c-api/filesystem.h [hunk 1]
```diff
@@ -126,7 +126,7 @@ extern "C"
     /// | <b>`accept-charset`</b>             | Set the "accept-charset" header
     /// | <b>`acceptencoding or encoding`</b> | Set the "accept-encoding" header
     /// | <b>`active-remote`</b>              | Set the "active-remote" header
-    /// | <b>`auth`</b>                       | Set the authentication method. Possible values: any, anysafe, digest, ntlm
+    /// | <b>`auth`</b>                       | Set the authentication method. Possible values: any, anysafe, digest, ntlm, basic
```
Comment (garbear) [inline xbmc/addons/kodi-dev-kit/include/kodi/c-api/filesystem.h:129]: Can you bump the filesystem API patch part by 1 in the same commit? Min stays the same.

**Comment by garbear** [comment]
Can you apply Jenkins formatting? Otherwise looks good, thanks for the fix.

**Comment by Syquel** [comment]
> Can you apply Jenkins formatting? Otherwise looks good, thanks for the fix.

If I apply Jenkins formatting there will be two different coding styles within the if-elseif-else construct. I kept the "legacy" coding style on purpose to keep it consistent.  

Should I still apply Jenkins formatting for my changes?

File: xbmc/addons/kodi-dev-kit/include/kodi/c-api/filesystem.h (hunk 1 above)
Comment (Syquel) [reply xbmc/addons/kodi-dev-kit/include/kodi/c-api/filesystem.h:129]: :+1:

**Comment by garbear** [comment]
> Should I still apply Jenkins formatting for my changes?

Yes, if we format everything in the future it'll save some history. History is more valuable than consistency IMO.

**Review by garbear — APPROVED** [review]

**Comment by Syquel** [comment]
I would like to backport this fix to 21.3.  
Do I just open another PR against the Omega branch with a cherry-pick of this commit?

**Comment by garbear** [comment]
Yes, just open a PR against omega with this commit. Cherry pick will have a conflict due to the version bump.
