### PR TITLE
[VIDEO] fix tv show episodes not probed for streamdetails when refres…

### LINKED ISSUE #24498: [Kodi 21 Beta3] Extract video information from files don't works from "KodiSetup-20240102-751e6c3b" with TV Shows
### Describe the bug
Here is a clear and concise description of what the problem is:

From Kodi (21.0-BETA2 (20.90.821) Git:20240102-751e6c3b55) when you add a new Tv Show or if you full refresh information for a existing Tv Show in library, all information from file (episode) are empty.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect to see all video information (codec, resolution, aspect...) for each episode.

## Actual Behavior

There is only the video duration

## Possible Fix

The latest Kodi version without issue is : 
21.0-BETA2 (20.90.821) Git:20240101-7413267da7

### To Reproduce

(All test are made from a clean Kodi install with all default settings)

Scenario 1 : add a new TV Show in library

1. use Kodi (21.0-BETA2 (20.90.821) Git:20240102-751e6c3b55) or newer 
2. add a new tvshow
3. then open this tvshow information
4. list the episode information

Scenario 2 : refresh a TV Show already in library with all video information correctly stored

1. use Kodi (21.0-BETA2 (20.90.821) Git:20240102-751e6c3b55) or newer 
2. open information for this tvshow
3. then refresh all information for all episode
4. list the episode information

### Debuglog
The debuglog can be found here:

After scrape a new TV Show
https://paste.kodi.tv/ijiwanutow.kodi

After refresh a tvshow already in library with all video information correctly stored
https://paste.kodi.tv/raloqocuvu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

The issue after a full refreh / a new TV Show added : 

What is expected : 

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Tested with the latest nightly Kodi version : 
 KodiSetup-20240112-5198ea50-master-x64

The issue is the same

### Your Environment
Used Operating system:

 - [X] Windows

 - Operating system version/name: Windows 11 Pro x64
 - Kodi version: KodiSetup-20240102-751e6c3b-master-x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by the-black-eagle**
…hed from scrapers

## Description
Test for more than just `item->HasStreamDetails()` as this is misleading in some cases.

## Motivation and context
The TV show scraper calls `SetVideoInfoTag()` directly but the only information it has to set is the duration of an episode.  With the old test, HasStreamDetails() would return true because at least one streamdetails item is set.  This means that when refreshing a TV show, if the user ignores any local nfo files and refreshes from the internet, the episode file is not probed for streamdetails and all that info disappears.

This doesn't occur with movies as the scraper uses a different method of setting the streamdetails so at this point in the code, they are not yet set.

Fixes https://github.com/xbmc/xbmc/issues/24498

## How has this been tested?
Tested by using local nfo files to set incorrect details in the db, then refreshing from the internet and checking the new details match the file details.  Tested against TV shows and movies.

## What is the effect on users?
Stream details will be obtained if they are either missing from an nfo file, or the show / movie is being refreshed from the internet.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by Hitcher** [comment]
Scanning new episodes result in all the details getting added and refreshing previously affected episodes also results in all details getting added.

**Comment by the-black-eagle** [comment]
@hitcher - works as expected then?  Refreshing movies still works as it should?

**Comment by Hitcher** [comment]
Yes, sorry I should have made it more obvious that I was confirming everything is now fixed. 
New movies still working as expected.

**Comment by MikeSiLVO** [comment]
I haven’t noticed any issues using this PR either. Fixes empty episode stream details and I have not seen any problems with movies.

**Comment by the-black-eagle** [comment]
Not reviews but two approvals, so if no one has any objections, I'll merge this later today.

File: xbmc/video/VideoInfoScanner.cpp [hunk 1]
```diff
@@ -1486,9 +1486,18 @@ namespace VIDEO
...
+     * get it from the video file */
+
+    CStreamDetails strmdetails{movieDetails.m_streamDetails};
+
+    bool probeFile = strmdetails.GetVideoCodec(1).empty() || strmdetails.GetVideoHeight(1) == 0 ||
+                     strmdetails.GetVideoWidth(1) == 0 || strmdetails.GetVideoDuration(1) == 0;
+
+    if (probeFile && CServiceBroker::GetSettingsComponent()->GetSettings()->GetBool(
+                         CSettings::SETTING_MYVIDEOS_EXTRACTFLAGS))
     {
```
Comment (ksooo) [inline xbmc/video/VideoInfoScanner.cpp:1501]: You never reach this block if the setting value is false. So there is no need to construct and check the `CStreamDetails` instance if the setting value is false.

I suggest to optimize this code a bit:

```c++
if (CServiceBroker::GetSettingsComponent()->GetSettings()->GetBool(CSettings::SETTING_MYVIDEOS_EXTRACTFLAGS))
{
    const CStreamDetails strmdetails{movieDetails.m_streamDetails};
    if (strmdetails.GetVideoCodec(1).empty() || strmdetails.GetVideoHeight(1) == 0 || strmdetails.GetVideoWidth(1) == 0 || strmdetails.GetVideoDuration(1) == 0)
    {
        ...
```

Comment (the-black-eagle) [reply xbmc/video/VideoInfoScanner.cpp:1501]: Yes.  The TV scraper creates a single videostream with just the duration set in it if/when it has scraped a value for an episode and it does this exactly once for each episode in turn.  If there is no duration and therefore no videostream then all of the calls will return either zero or an empty string and the data will be obtained from the file.

Thanks for the code optimisation :)

**Review by ksooo — APPROVED** [review]
I have not runtime-tested the change, but looks okay code-wise.

**Review by CrystalP — APPROVED** [review]
Looks and works fine for me.
