### PR TITLE
[Subtitles] Rework subtitle positions

### LINKED ISSUE #21555: Subtitle setting Bottom of Video
### Describe the bug

The subtitle position setting `Bottom of Video` is not actually the bottom of the video. 
Looks more like bottom of the screen.

## Expected Behavior

For the option `Bottom of Video` I expect the subtitle to be on the bottom of the video.
Now when the aspect ratio is not 16:9, the subtitle will appear half in the black bar or completely in black bar. 

## Possible Fix

Instead of taking the screen resolution, use the video resolution.
And make the bottom of the video option behave as it describes. 

### To Reproduce

1. Set subtitle position to bottom of video. 
2. Play movie/show with aspect ratio other 16:9, 21:9 for example
3. See how subtitle is not on the bottom of the video. 

### Your Environment
Used Operating system:

 - [x] Android Nvidia Shield Pro
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20 Alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #21699: Moving Slider control in the settings with the mouse/touchscreen does not respect the step value
### Describe the bug
Here is a clear and concise description of what the problem is:

When you move the white ball of Slider control with mouse/touchscreen cause unexpected values so not respect the xml step value
if instead you move the slider with keyboard the value is right so is incremented/decremented by following the step value

looks at vertical margin weird value:
immagine

this is the relative kodi xml setting
```
        <setting id="subtitles.marginvertical" type="number" label="39182" help="39183">
          <level>3</level>
          <default>7.75</default>
          <constraints>
            <minimum>0</minimum>
            <step>0.25</step>
            <maximum>50</maximum>
          </constraints>
          <dependencies>
            <dependency type="enable" on="property" operator="!is" name="isplaying" />
          </dependencies>
          <control type="slider" format="percentage"/>
        </setting>
```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Consistent % value

## Actual Behavior

Works but only with remote/keyboard not with mouse/touchscreen

## Possible Fix

i have not investigated

### To Reproduce

Keep clicked on the white ball of Slider control and move the mouse

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/fajaviwayu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Kodi 20 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

This PR rework subtitle positions and how works the manual position (e.g. by using key shortcuts) / Calibration window

After the big rework i changed the way in how the subtitle position/manual position works,
the `Bottom of Video` / `Top of Video` do not reflect the same behaviour as Kodi 19 for cropped videos,
so the text is not placed "inside the video" but act as standard Bottom / Top position, this because in the past i could not find a good solution

After the new request on #21555 i started to investigate again and i found a solution to restore the Kodi 19 behaviour of `Bottom of Video` / `Top of Video`.

Now `Bottom of Video` / `Top of Video` is same of Kodi 19
and `Below video` / `Above video` labels are renamed as `Bottom of screen` / `Top of screen` that IMO are more user friedly, but suggestions are welcome

Due to these changes, i had to revert some new changes i previously made on kodi 20, the changes are:
- Reverted the possibility to change subtitle position (e.g.key shortcuts) with all types of "subtitles positions", now you can change position only with `Bottom` and `Manual` (if i enable this for `Below video` could works but when the text go off the video margin will be cut out and disappear in the black bands, to avoid complaints from users this will not be enabled)
- The subtitle bar in Screen Calibration setting window, now works only with the `Manual` position settings, as Kodi 19
- I kept the possibility of moving the text with the `Bottom of screen` subtitle position, but will not be possible to save permanently the change with "save" parameter of `SubtitleShiftUp(save)` Player built-in.

however for those coming from Kodi 19 they dont see nothing changed

particular changes:
- CDVDSubtitlesLibass::RenderImage in DVDSubtitlesLibass.cpp:
~i added `opts.reconfigure` this to avoid call~ my oversight removed

- CDVDSubtitlesLibass::RenderImage in DVDSubtitlesLibass.cpp:
`ass_set_use_margins` was used to force place the text inside black bars and now i have set always disabled.
i see no difference between use standard `Bottom of screen` subtitle position, and enable this margin feature,
because if there are too many lines of text come out of the black bands anyway.
Therefore, we can avoiding an additional scaling and we do not need anymore also to set a specific margin `MARGIN_VERTICAL_BLACKBARS`.

- I have removed the FIXME in font size, and cleanup, this was not a problem to be fixed the values are based on a 720 window (i don't know the reason but the same conclusions came to the MPV devs)

- Some settings has been modified to accommodate these changes

- Removed todo `/! @todo Libass scale the margins values (style)` in OverlayRenderer.cpp, fixed the displacement in better way with the help of libass dev

## Motivation and context

Fix #21555
Fix #21699

## How has this been tested?

Use of screen calibration window, with "manual" align and other subtitle positions, while or not in playing
Try moving subtitles with shourtcut keys
Check if font size with ASS with overriding settings enabled is correct
Check if font size with adapted subtitiles (like SRT) is correct
Check if when you move the GUI subtitle bar in calibration window match the subtitle text, with/without overscan and kodi as windowed/fullscreen

## What is the effect on users?

Restored Kodi 19 behaviour of  `Bottom of Video` / `Top of Video`, for cropped videos

## Screenshots (if appropriate):
screenshot00001

screenshot00001

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
yes youre right, i think your suggest its appropriate

**Comment by lrusak** [comment]
jenkins build this please

**Comment by CastagnaIT** [comment]
jenkins build this please

**Comment by CastagnaIT** [comment]
@enen92 i have finally done the changes is possible now review

some remarks:
`Manual` position VS `Bottom of screen` position, is a bit different in how is managed the possibility to move the text (also in PlayerController.cpp i had to make a small change) this is due to "libass line displacement" problem (see comments in code), i "played" a lot and i think it is not possible to do better without use ugly hacks

With `Manual` we need to compensate the displacement to allow make GUI calibration working, this was already known,
and affects indirectly also the vertical margins, so despite the vertical margins set, if you try switch from `Manual` to `Bottom of screen` (or `Bottom of video`) you will see a different default subtitle position, this does not matter much since with `Manual` it is the user who has to manually move the subtitle position where prefers, but worth remembering

With `Bottom of screen` we avoid the compensation, to keep consistent the vertical margin as other positions (`Bottom of video`, `Top of screen`, ...)
in this case to be able to move the text, under, the vertical margin ofc we need to go offscreen,
this is the reason because the position value in the popup slider, i mean this:
immagine
exceeds the screen resolution (my 1080p), in this case is not perfect due to "libass displacement" problem the text can go slightly off-screen (Instead with `Manual` position is shown the real text line position without vertical margin)

it would be helpful if someone did a test also with 4k monitor/tv, to test Window calibration GUI subtitle bar, text size, vertical margins, if are ok, and to know if with `Bottom of screen` it is still possible reach the bottom edge of screen despite the vertical margin set

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h [hunk 1]
```diff
@@ -68,10 +68,20 @@ enum class OverrideStyles
   STYLES_POSITIONS
 };
 
+enum class MarginsMode
+{
+  // Use style margins only
+  DEFAULT = 0,
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:74]: = 0 probably not needed

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h [hunk 2]
```diff
@@ -103,14 +113,17 @@ struct subtitleOpts
 
 struct renderOpts
 {
+  // If true, it forces reconfiguration of the renderer
+  bool reconfigure = false;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:117]: I don't really like this, `reconfigure` is an action you do on a certain item not really some option you pass to define how to render elements. I don't have any better suggestion atm but I guess you understand my concern here and maybe can think of a possible alternative?
Maybe convey some member relater to position so that later on the render you can decide if you should reconfigure or not based on state change

**Review by enen92 — COMMENTED** [review]
I like the approach, have yet to runtime test. If you manage to get rid of that ugly "reconfigure" it'll be a +1 from my side

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:117]: my failure forgot to double-check, i see now libass source:
https://github.com/libass/libass/blob/1140b6b885c89d37eef13dc1f31f144e9a76a4d7/libass/ass_render_api.c#L131-L137
there is no problem if we set it at each frame, the method is noop if value is not changed
then i can remove this

**Comment by enen92** [comment]
jenkins build this please

**Review by enen92 — APPROVED** [review]
Runtime tested

**Comment by enen92** [comment]
Jenkins build and merge

**Comment by bokkoman** [comment]
Just a question regarding this and an idea maybe. 

It isn't possible to shift subtitle up when `Bottom of Video` is used with a certain percentage offset?
Since I've come across some movies where they leave the black bars, and I would love to be able to shift it up so it is inside the video again. Or be able to adjust the percentage temporary.

**Comment by CastagnaIT** [comment]
with `Bottom of Video` position is not possible shift subtitles, this due to difficulty to solve in good way some problems with the renderer, therefore you can use shortcutkey to change the position setting when necessary.
For other questions/requests please use forum sections not developings PR's.
