### PR TITLE
[contextmenu] fix queue/playnext items in music (root) addons

### LINKED ISSUE #16708: Context-Menu of Music-Addons contains wrong entries
### Describe the bug
Opening the context menu of a music addon shows entries like "Queue item", "Play next" or "Play" which in most cases lead to a neverending busy-dialog aca crash as you can't queue an addon etc. 

## Expected Behavior
Context menu should only contain "Information", "Disable", "Settings" and "Add to favourites". 

## Actual Behavior
neverending busy-dialog

### To Reproduce
1. Go to addons / music-addons
2. Select an addon 
3. Press 'c' 
4. Select one of the mentioned entries

### Debuglog
The debuglog can be found here:  not necessary

### Screenshots 
[https://i.imgur.com/QrRFIhY.jpg](https://i.imgur.com/QrRFIhY.jpg)

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 8.1 Pro
 - Kodi version:
18.4

### PR DESCRIPTION
**Pull request by enen92**
## Description
In the music base view we are presenting context menus which target audio files also for addon listings. This doesn't make sense and doesn't work (you can't queue, play, etc a plugin).
There is no pretty way to detect if the item is a root plugin path (e.g. plugin://plugin.audio.radio_de), the only way is to check if the addon properties are set on the item (Addon.Id, Addon.Name).

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/16708

## How has this been tested?
Manually, Linux.

## What is the effect on users?
Those incorrect music context menu items should not be shown anymore in music plugins

## Screenshots (if appropriate):

**Before:**
image
image

**Now:**
image
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

File: xbmc/music/windows/GUIWindowMusicBase.cpp [hunk 1]
```diff
@@ -572,7 +572,8 @@ void CGUIWindowMusicBase::GetContextButtons(int itemNumber, CContextButtons &but
 
     if (!item->IsParentFolder())
     {
-      if (item->CanQueue() && !item->IsAddonsPath() && !item->IsScript())
+      if (item->CanQueue() && !item->IsAddonsPath() && !item->IsScript() &&
```
Comment (howie-f) [inline xbmc/music/windows/GUIWindowMusicBase.cpp:575]: imho function `CanQueue()` of CFileItem needs to be fixed so it can be the only condition of this if statement?
sadly i‘ve no idea if this would open a can

Comment (enen92) [reply xbmc/music/windows/GUIWindowMusicBase.cpp:575]: That's a nice point - I also don't like the current implementation (there's even a comment to remove hacks based on those properties.
I think for now I'll fix the CanQueue condition for addon items and leave a todo to remove the other conditions later

**Review by howie-f — APPROVED** [review]
yes
