### PR TITLE
[GUI] Kill skin timers thread, move to ProcessSlow

### LINKED ISSUE #21791: Race condition in CGUIInfoManager causing an user-after-free
### Describe the bug
The problem is that `CGUIInfoManager::m_multiInfo` is modified from multiple threads causing a reallocation of the `std::vector`s internal buffer while a different thread has a reference to an object inside that buffer.

Here are the logs and Address Sanitizer output of two occasions:

#### Crash on startup

Debug log: https://gist.github.com/neo1973/1e72f91a0f5bd4d495e9088981cf0700
ASAN output: https://gist.github.com/neo1973/e2c546d82f0e87e870228c614491bf76

#### Crash while navigating through GUI:

Debug log: https://gist.github.com/neo1973/fd16b4f454fb3ac5a49c1408b7d80ae8
ASAN output: https://gist.github.com/neo1973/0960636f540c6c6f6860b3ee8fe40380

The issue is best reproduced when I launch Kodi with these ASAN options: `ASAN_OPTIONS=detect_stack_use_after_return=1:fast_unwind_on_malloc=0 ./kodi-wayland`
This makes the timings just right (on my machine) to trigger the bug within a couple of seconds, most of the time even before the GUI is up.

## Expected Behavior
No undefined behaviour that can cause crashes.

## Actual Behavior
Undefined behaviour and possible crashes.

## Possible Fix
Difficult. Simply protecting `CGUIInfoManager::m_multiInfo` with a `CCriticalSection` causes deadlocks. It doesn't matter if the `m_critInfo` one is reused or a separate `CCriticalSection` is added.

### To Reproduce

Happens immediately on startup or shortly after while browsing through the GUI. I don't think any particular steps are required to hit the problem.

### Debuglog

The debuglog can be found here: See above

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux, recently updated
 - Kodi version: Current master, commit 9c3a68f32e59dd25f0cacc35c47a88a5e5770990

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This fixes the race condition/use-after-free introduced with the skin timers addition by killing the separate thread while moving the processing logic to CApp ProcessSlow (same time interval as the original thread).
Completely untested, I have no way of checking this for the following days, just checking if it builds and maybe get a testbuild.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/21791

## How has this been tested?
Runtime tested on macOS

## What is the effect on users?
Fix use after free

### CODE REVIEW

File: xbmc/addons/gui/skin/SkinTimerManager.h [hunk 1]
```diff
@@ -21,23 +21,20 @@
  * \sa Skin_Timers
  * \sa CSkinTimer
  */
-class CSkinTimerManager : public CThread
```
Comment (ksooo) [inline xbmc/addons/gui/skin/SkinTimerManager.h:24]: Don't forget to remove `#include "threads/Thread.h"`, please.

File: xbmc/addons/gui/skin/SkinTimerManager.h [hunk 2]
```diff
@@ -66,12 +63,7 @@ class CSkinTimerManager : public CThread
   // CThread methods
 
   /*! \brief Start and run the main manager loop */
```
Comment (ksooo) [inline xbmc/addons/gui/skin/SkinTimerManager.h:65]: The comment does not fit anymore, right? It's not a loop anymore.

File: xbmc/addons/gui/skin/SkinTimerManager.cpp [hunk 3]
```diff
@@ -217,33 +202,25 @@ void CSkinTimerManager::Stop()
...
-  std::unique_lock<CCriticalSection> lock(m_timerCriticalSection);
-  m_bStop = true;
-  CThread::StopThread(bWait);
-}
-
 void CSkinTimerManager::Process()
 {
-  while (!m_bStop)
+  if (m_timers.empty())
+    return;
```
Comment (ksooo) [inline xbmc/addons/gui/skin/SkinTimerManager.cpp:208]: I think this is not needed. The for loop will check this as well and will do nothing if no timers are available.

File: xbmc/addons/gui/skin/SkinTimerManager.cpp [hunk 4]
```diff
@@ -20,19 +20,6 @@
 
 using namespace std::chrono_literals;
 
-CSkinTimerManager::CSkinTimerManager() : CThread("SkinTimers")
-{
-}
-
-void CSkinTimerManager::Start()
-{
-  std::unique_lock<CCriticalSection> lock(m_timerCriticalSection);
```
Comment (ksooo) [inline xbmc/addons/gui/skin/SkinTimerManager.cpp:29]: Not sure we still need `m_timerCriticalSection` as we are not calling `CSkinTimermanager`from other threads than the main thread.

Comment (enen92) [reply xbmc/addons/gui/skin/SkinTimerManager.cpp:29]: shouldn't be needed anymore, it's all called from the main thread now. Added a note to doxy docs warning about this.

File: xbmc/addons/gui/skin/SkinTimerManager.cpp (hunk 3 above)
Comment (enen92) [reply xbmc/addons/gui/skin/SkinTimerManager.cpp]: true, container is empty which is pretty much the same thing

**Review by ksooo — APPROVED** [review]
Code changes looking good. Did no runtime-test, though.

File: xbmc/addons/gui/skin/SkinTimerManager.cpp [hunk 5]
```diff
@@ -217,33 +196,22 @@ void CSkinTimerManager::Stop()
...
-  m_bStop = true;
-  CThread::StopThread(bWait);
-}
-
 void CSkinTimerManager::Process()
 {
-  while (!m_bStop)
+  for (auto const& [key, val] : m_timers)
```
[the remark this answers is not in the document]
Comment (ksooo) [reply xbmc/addons/gui/skin/SkinTimerManager.cpp:201]: good catch

**Comment by enen92** [comment]
Runtime tested on osx with the jenkins testbuild. All good.
Detected an unrelated issue with the debug overlay (it's duplicated if the player is running), will check if after https://github.com/xbmc/xbmc/pull/21795 the issue persists.

**Comment by ksooo** [comment]
@enen92  can you please squash down to a single commit?

**Comment by enen92** [comment]
I think it's fine as is, second commit has no relation with what's being done on the first one.

**Review by ksooo — APPROVED** [review]

**Comment by thexai** [comment]
> moving the processing logic to CApp ProcessSlow (same time interval as the original thread).

Time interval was 500 ms before but now is ~16 ms because has NOT moved to `ProcessSlow` but `CApplication::Process()` 

I mean that skin timers are evaluated every 16 ms and not seems necessary 🤔

**Comment by ksooo** [comment]
> NOT moved to ProcessSlow but CApplication::Process()

 Yikes. Good catch. Overlooked that in my review, sorry.

**Comment by enen92** [comment]
Agrf, thanks @thexai will try to push it in a while.
