### PR TITLE
change season/episode infolabels for specials

### LINKED ISSUE #17402: xbmc.getInfoLabel('VideoPlayer.Season') and xbmc.getInfoLabel('VideoPlayer.Episode') Not Integers for Specials
### Describe the bug
Here is a clear and concise description of what the problem is:

https://github.com/trakt/script.trakt/issues/490

As raised in the issue above. The kodi video player reports a special episode as ES1 instead of S0E1

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

xbmc.getInfoLabel('VideoPlayer.Episode') and xbmc.getInfoLabel('VideoPlayer.Season') should always return an int not a string as anyone who codes to grab these values expects ints to be returned.

## Actual Behavior

If the infolabels of an item in an plugin are set to {'season': 0, 'episode': 1} then Kodi returns the season as None and the episode as S1

## Possible Fix

Set xbmc.getInfoLabel('VideoPlayer.Season') to return 0 when the infolabel for the listitem is 0
and set xbmc.getInfoLabel('VideoPlayer.Episode') to return the int of the episode not add S to highlight the episode as a special.

### To Reproduce

1. Setup the trakt script from the Kodi repo and watch any file from a plugin where the season is set to 0 on its infolabel.

### Your Environment
Used Operating system:

 - [ Yes ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ]  OSX
 - [ ] Raspberry-Pi
 - [ Yes ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Martix 19 Any Nightly 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ronie**
the PR removes the odd season/episode numbering we use in infolabels for episodes that are specials.

before:
```
ListItem.Season:
ListItem.Episode: S1
```

after:
```
ListItem.Season: 0
ListItem.Episode: 1
```

(the same change applies to VideoPlayer.Season / VideoPlayer.Episode)

fixes https://github.com/xbmc/xbmc/issues/17402

for skinners / addon devs it's much easier to work with those infolabels this way.

### CODE REVIEW

File: xbmc/guilib/guiinfo/VideoGUIInfo.cpp [hunk 1]
```diff
@@ -221,23 +221,19 @@ bool CVideoGUIInfo::GetLabel(std::string& value, const CFileItem *item, int cont
         int iSeason = -1, iEpisode = -1;
```
Comment (Razzeee) [inline xbmc/guilib/guiinfo/VideoGUIInfo.cpp]: `iSeason` now is unused in this branch

```suggestion
        int iEpisode = -1;
```

Comment (ronie) [reply xbmc/guilib/guiinfo/VideoGUIInfo.cpp]: thx! updated.

**Comment by emveepee** [comment]
@Razzeee , @ronie , @ksooo This is impacting PVR recordings.  The documentation says S0+E0 is ok for invalid for PVR Recordings but they are now displayed as S0 because of the = test
https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/guiinfo/VideoGUIInfo.cpp#L236

**Comment by ronie** [comment]
i'm not really familiar with pvr, can you please point me to this documentation?

**Comment by emveepee** [comment]
> i'm not really familiar with pvr, can you please point me to this documentation?

https://codedocs.xyz/AlwinEsch/kodi/struct_p_v_r___r_e_c_o_r_d_i_n_g.html#afe2e4edaf0b7589e5a464a543b7f1cda

**Comment by ronie** [comment]
thanx!

i've only now found out that PVR uses their own code for season / episode infolabels:

https://github.com/xbmc/xbmc/blob/dfad22ee2edc7f5ba6708c2a4e38d002f7629987/xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp#L573-L583

https://github.com/xbmc/xbmc/blob/dfad22ee2edc7f5ba6708c2a4e38d002f7629987/xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp#L565-L572

since i haven't touched that part, i wonder how this PR could have an effect on PVR...

**Comment by emveepee** [comment]
It is cosmetic but looks odd on non-series PVR recordings.  I expect the problem is not as bad for addons that use legacy code and memset the API returns.

s0

I do have another concern about how this might look confusion when it is properly used on a special when there is no Episode name.

**Comment by ksooo** [comment]
PVR has own code part for EPG, but uses videoinfotag code path for recordings. Thus, charges in the video path affect recordings.

**Comment by ksooo** [comment]
> The documentation says S0+E0 is ok for invalid for PVR Recordings but they are now displayed as S0 because of the = test

I suggest to change PVR API to not allow 0/0 to signal "not available" any longer. This means, to update the API documentation and to adapt all PVR add-ons.

 As I'm not available for doing this during there next couple of months due to time constraints, somebody else would have to step up.

**Comment by emveepee** [comment]
> I suggest to change PVR API to not allow 0/0 to signal "not available" any longer. This means, to update the API documentation and to adapt all PVR add-ons.

> As I'm not available for doing this during the next couple of months due to time constraints, somebody else would have to step up.

@ksooo is that feasible without knowing what the backend is sending?  I checked pvr.hts and I see

      /* season/episode (tvh 4.3+) */
      rec.iSeriesNumber = recording.GetSeason();
      rec.iEpisodeNumber = recording.GetEpisode();

Rather than adding a condition to each PVR could we not just  modify how they are copied https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/recordings/PVRRecording.cpp#L78  to

    if (recording.iSeriesNumber!=0 && recording.iSeriesNumber!=0)
    {
        m_strShowTitle = recording.strEpisodeName;
        m_iSeason = recording.iSeriesNumber;
    }

Also is memset required on any of the PVR types functions at this time?  If not I could flag issues on the official addons that still use them (like mine) to remove it.

**Comment by ksooo** [comment]
>  is that feasible without knowing what the backend is sending? I checked pvr.hts and I see

 It is feasible for the maintainer of the soon, yes. If there is no maintainer, the add-on will die, former or later.

> Rather than adding a condition to each PVR could we not just modify how they are copied

We should fix the route cause, which is bad API  design here, not hack around the actual problem, just because the later is less effort.

**Comment by emveepee** [comment]
> 
> > Rather than adding a condition to each PVR could we not just modify how they are copied
> 
> We should fix the route cause, which is bad API design here, not hack around the actual problem, just because the latter is less effort.

Sorry I misunderstand your first comment I thought you wanted someone other than the maintainer to make this change.  The recent update to pvr.hts shows how difficult that would be.

My comments about memset were more about how to factor this change in with PR1645 looming but now I see that likely won't be a Matrix issues anyway.  I think we can close this discussion here as I opened a PR for your recommendation.
