### PR TITLE
[filemanger] reset to root if directory is inaccessible

### LINKED ISSUE #18119: File manager failure when the folder is deleted
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello there is a problem that occurs in the kodi file manager, when you open a folder and then it is deleted the kodi gets lost and cannot identify it.
Let's say that I enter the kodi file manager in a folder, press esc to exit the screen, if otherwise that folder is deleted it is lost needing to close the application and open it again.

## Expected Behavior
In this case, the solution would be that if he tries to open a folder and it does not exist, he returns to the main folder.

## Actual Behavior

File manager interruption.

## Possible Fix

In this case, the solution would be that if he tries to open a folder and it does not exist, he returns to the main folder.

### To Reproduce

1.  Open a folder with the file manager;
2. Exit the file manager screen but without going back to the main folder;
3. Delete this same folder using samba, ssh, winscp and others.
4. Open the file manager again.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ronie**
the filemanger can get stuck in no man's land when it's trying to re-enter a folder that has been deleted in the meantime.
it should load the root folder when such a situation is encountered.

fixes #18119

### CODE REVIEW

File: xbmc/windows/GUIWindowFileManager.cpp [hunk 1]
```diff
@@ -1245,11 +1245,13 @@ void CGUIWindowFileManager::OnInitWindow()
   else if (!bResult0)
   {
     ShowShareErrorMessage(m_Directory[0]); //show the error message after window is loaded!
+    Update(0,""); // reset view to root
```
Comment (Rechi) [inline xbmc/windows/GUIWindowFileManager.cpp:1248]: > Commas have to be followed by one space.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

File: xbmc/windows/GUIWindowFileManager.cpp [hunk 2]
```diff
@@ -1245,11 +1245,13 @@ void CGUIWindowFileManager::OnInitWindow()
...
   }
 
   if (!bResult1)
   {
     ShowShareErrorMessage(m_Directory[1]); //show the error message after window is loaded!
+    Update(1,""); // reset view to root
```
Comment (Rechi) [inline xbmc/windows/GUIWindowFileManager.cpp:1254]: > Commas have to be followed by one space.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

**Review by Rechi — COMMENTED** [review]
Please follow the [current code guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).
