### PR TITLE
[Linux][Discs] Fix play dvd automatically setting

### LINKED ISSUE #19237: Play discs automatically setting leads to browse menu
### Describe the bug

Found while working on the DVD/discs functionality. If you enable "Play Discs automatically" in Settings->Player->Discs Kodi will open a browse menu whenever a disc is inserted instead of attempting direct playback.

This seems to be an issue affecting Kodi since...eden according to posts on the forum. Ref: https://forum.kodi.tv/showthread.php?tid=128057

I'll try to have a look at it whenever I find time, opening this issue just for tracking purposes.

## Expected Behavior
Kodi should attempt to playback the dvd instead of showing a browser option.

## Actual Behavior
Kodi shows browse menu

## Possible Fix
Since the setting is not working for a long time I'd consider to change it to an option-based setting:
Behaviour on disc insertion:
- Do nothing
- Browse
- Play

### To Reproduce

Enable the setting. Insert dvd.

### Debuglog
Don't have one at the moment. Verified on linux but should be reproducible in other platforms too.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix RC1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This fixes the "play dvd automatically" setting that was broken since Eden on linux. Due to the way Kodi handles discs they can only be played after they've been mounted. However, when this event happens, the autorun was already executed. This makes sure that if the mounted drive is optical and the setting is enabled we attempt the autorun before defering to the media browse menu.

Includes also a cleanup for dead code/unused branches in the `ExecuteAutorun` method.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/19237

## How has this been tested?
Runtime tested

## What is the effect on users?
Should restore the setting functionality on linux

## Screenshots (if appropriate):

playdiscsautomatically

**Master:**
before

**PR:**
dvdmenu

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by DaVukovic** [comment]
Awesome. Thanks much.  I will have a look tomorrow :+1:

**Comment by DaVukovic** [comment]
Also this works as expected. 

So a :+1: from my side and the approval in regard of the functionality

**Review by DaVukovic — APPROVED** [review]

File: xbmc/Autorun.cpp [hunk 1]
```diff
@@ -60,25 +60,17 @@ CAutorun::CAutorun()
...
 
   if (CServiceBroker::GetGUI()->GetWindowManager().GetActiveWindow() == WINDOW_LOGIN_SCREEN)
-    return;
+    return success;
 
   CCdInfo* pInfo = CServiceBroker::GetMediaManager().GetCdInfo(path);
 
   if ( pInfo == NULL )
-    return ;
+    return success;
```
Comment (howie-f) [inline xbmc/Autorun.cpp:73]: `return false;`

File: xbmc/Autorun.cpp [hunk 2]
```diff
@@ -491,7 +484,8 @@ void CAutorun::HandleAutorun()
 
   if (mediadetect.m_evAutorun.Wait(0ms))
   {
-    ExecuteAutorun();
+    if (!ExecuteAutorun(""))
+      CLog::Log(LOGDEBUG, "{}: Could not execute autorun", __FUNCTION__);
```
Comment (howie-f) [inline xbmc/Autorun.cpp:488]: `__FUNCTION__` should be `__func__` in general

File: xbmc/platform/linux/storage/UDevProvider.cpp [hunk 3]
```diff
@@ -245,7 +245,7 @@ bool CUDevProvider::PumpDriveChangeEvents(IStorageEventsCallback *callback)
       {
         CLog::Log(LOGINFO, "UDev: Added {}", mountpoint);
         if (callback)
-          callback->OnStorageAdded(label, mountpoint);
+          callback->OnStorageAdded(label, mountpoint, false);
```
Comment (howie-f) [inline xbmc/platform/linux/storage/UDevProvider.cpp:248]: maybe add a comment, what `false` means here

File: xbmc/platform/linux/storage/UDevProvider.cpp [hunk 4]
```diff
@@ -263,7 +263,7 @@ bool CUDevProvider::PumpDriveChangeEvents(IStorageEventsCallback *callback)
         {
           CLog::Log(LOGINFO, "UDev: Changed / Added {}", mountpoint);
           if (callback)
-            callback->OnStorageAdded(label, mountpoint);
+            callback->OnStorageAdded(label, mountpoint, false);
```
Comment (howie-f) [inline xbmc/platform/linux/storage/UDevProvider.cpp:266]: same

File: xbmc/storage/IStorageProvider.h [hunk 5]
```diff
@@ -21,7 +21,12 @@ class IStorageEventsCallback
 public:
   virtual ~IStorageEventsCallback() = default;
 
-  virtual void OnStorageAdded(const std::string &label, const std::string &path) = 0;
+  /*! \brief Callback executed when a new storage device is added
+    * @param label the storage label
+    * @param path the storage path
+    * @param optical if this is an optical device
+    */
+  virtual void OnStorageAdded(const std::string& label, const std::string& path, bool optical) = 0;
```
Comment (howie-f) [inline xbmc/storage/IStorageProvider.h:29]: or even better go with `enum class Optical { YES, NO }` instead of a new bool argument

File: xbmc/storage/MediaManager.cpp [hunk 6]
```diff
@@ -689,17 +689,34 @@ std::vector<std::string> CMediaManager::GetDiskUsage()
   return m_platformStorage->GetDiskUsage();
 }
 
-void CMediaManager::OnStorageAdded(const std::string &label, const std::string &path)
+void CMediaManager::OnStorageAdded(const std::string& label, const std::string& path, bool optical)
```
Comment (howie-f) [inline xbmc/storage/MediaManager.cpp:692]: enum class?

**Review by howie-f — COMMENTED** [review]
few suggestions only, nothing serious

**Review by howie-f — APPROVED** [review]
👍

**Review by howie-f — APPROVED** [review]
i can't see anything wrong with this, but it would be really nice if @DaVukovic could give this another round of runtime-testing. i have no optical device available to do it myself

**Comment by DaVukovic** [comment]
Works like a charm ;)

**Review by DaVukovic — APPROVED** [review]

**Comment by mkreisl** [comment]
Hopefully someone still reads this
This commit produces a segfault when I do the following:

```
1) mount loop device: sudo mount /dev/mapper/loop0p2  /tmp/m (Kodi still fine after that)
2) sudo umount /tmp/m --> BANG (Kodi crashing with segfault, and that always)
```

last log message is `info <general>: UDisks2: Removed /dev/mapper/loop0p2`

Segfault happens here: https://github.com/xbmc/xbmc/blob/master/xbmc/platform/linux/storage/UDisks2Provider.cpp#L45

Reverting this commit everything back to normal

**Comment by enen92** [comment]
Thanks for reporting, will take a look next week. I highly doubt the crash was introduced with the changes done here, most likely it just exposed some bug that was always there

**Comment by mkreisl** [comment]
I'm pretty sure I included this PR in my build right from the start.
But I have not really noticed that because this mounting of the loop device only takes place in the context of weekly backups.

**Comment by enen92** [comment]
Can you provide a stacktrace btw? Would help narrow this down

**Comment by mkreisl** [comment]
I can post the output of the gdb stacktrace tomorrow, hth

**Comment by enen92** [comment]
I'll be away for the weekend but you can try this patch if you are in a rush:
https://github.com/xbmc/xbmc/blob/2df9040e55a01468031078995a009ed5a7056eca/xbmc/platform/linux/storage/UDisks2Provider.cpp#L97

Try to replace by:

`return m_block != nullptr && m_block->m_drive->IsOptical();`

**Comment by mkreisl** [comment]
I'll test it tomorrow, I'm not in a hurry now that I know where the problem lies.

But I don't think that is the reason, the crash happens in the IsOptical() function, which I had already tested and pointed out.
If I change it like this, there is no crash.
```
bool CUDisks2Provider::Drive::IsOptical() const
{
  return false;
  //return std::any_of(m_mediaCompatibility.begin(), m_mediaCompatibility.end(),
                     [](const std::string& kind) { return kind.compare(0, 7, "optical") == 0; });
}
```

**Comment by enen92** [comment]
According to the stacktrace crash happens in Filesystem::IsOptical() (not in drive::IsOptical()) either because m_block is null or m_drive in m_block is null, before it even gets to drive::IsOptical.

Either way, a proper fix will take a bit more of work than only checking for null. Since we can't get that kind of info from unmounted drives it makes no sense to have an IsOptical member on the callbacks. We will need to have a different abstraction (something like type::unknown, type::optical) in StorageDevice. Either way, I'll get that fixed next week.
Thanks for bringing the issue

**Comment by mkreisl** [comment]
However, there is no hurry. Better do it right

Should only not take 8 8odi versions again until the fix is fixed :smiley:
