### PR TITLE
[FIX][Video][Music] Use dynpath when checking for dvd/bluray image files etc

### LINKED ISSUE #15257: Music Videos don't play if  launched from Shift/Infowall/Widelist/Wall
### Describe the bug
Here is a clear and concise description of what the problem is:

Music Videos don't play if  launched from Shift/Infowall/Widelist/Wall while play if lunched from "Recently added music videos"

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. Add some Music Video. In my cased I added some ISO files Bluray Concerts 
2. Select a video from Shift/Infowall/Widelist/Wall and  launch
3. The play does not start
4. Select a video from "Recently added music videos"  and  launch
5.  The play starts

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/laneveyofa     - PLAY OK form "Recently added music videos"
https://paste.kodi.tv/axaxaqacow  - PLAY NOK from "Shift"

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

In positive case VideoPlayer opens the rigth file. Eg:

NOTICE: VideoPlayer::OpenFile: nfs://192.168.1.2/BLURAY-CONCERTS/Aerosmith - Rocks Donington-2014/Aerosmith-Rocks Donington-2014.iso

In negative case VideoPlayer tries to open a wrong file: eg:
NOTICE: VideoPlayer::OpenFile: videodb://musicvideos/titles/2

This leads to the error:

ERROR: Open - error probing input format,

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  Leia 18.0 RC5

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #15414: Bluray and DVD ISO playback from library not working
### Describe the bug
Here is a clear and concise description of what the problem is:

[bluray-kodi.log](https://github.com/xbmc/xbmc/files/2825900/bluray-kodi.log)
[dvd-kodi.log](https://github.com/xbmc/xbmc/files/2825901/dvd-kodi.log)
On Kodi 18 playback of DVD & Bluray ISO files from the library dont play correctly.  Blurays fail to start playing or show the menu.  DVDs start but dont allow you to access the DVD menu or allow you to navigate the DVD menu.  If you load the ISO from the file manager it plays correctly for both Blurays and DVDs.  Also if you goto the library and bring up the contextual menu and play it from there it plays correctly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Would expect the bluray menu to start.  Would allow you to use DVD menu.

## Actual Behavior

Bluray ISOs fail to play from library only.  DVD ISOs start but menus dont work when played from library. Both work fine from the file manager and playing from the contextual menu.

## Possible Fix

Duplicate behavior of playing from the contextual menu or file manager in the library.

### To Reproduce

1.  Scan Bluray and DVD ISOs to the library.
2. Try to playback the Bluray or DVD ISO from the library using the enter key.

### Debuglog

The debuglog can be found here:
Bluray playback debug log: https://paste.kodi.tv/hojenekite.kodi
DVD Playback debug log: https://paste.kodi.tv/pulojirame.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.0
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #18250: Starting an ISO from the library twice doesnt load dvd/bluray menu the 2nd time
### Describe the bug
Here is a clear and concise description of what the problem is:

If you play an ISO DVD or Bluray the menu will load fine the first time but on the second playback attempt the dvd/bluray menu will not work.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Would expect playing the ISO a second time would produce the same results as the first time playing it and show the menu.

## Actual Behavior

DVD/Bluray menu fails to load when playing the ISO a second time.

## Possible Fix

Have the ISO load the second time the same way as the first time.

### To Reproduce

1. Scan dvd or bluray ISO's to library
2. Play DVD or Bluray ISO
3. Stop playing the ISO
4. Start the ISO again.  DVD or Bluray menu will not work.

### Debuglog

The debuglog can be found here:
https://pastebin.com/LGxjUQA6

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

In the debug log on line 673 you can see the ISO playback matches the rule dvdimage, this is on the first playback attempt.  In the debug log on line 1187 you can see the second playback attempt of the ISO shows GetPlayers: matched 0 rules with players.

### Your Environment
Used Operating system:

 - [X ] Android
 - [ ] iOS
 - [ X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.8 & 19 Alpha

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by the-black-eagle**
## Description
Fixes opening DVD/Bluray images (either iso files or a directory containing the files) so that the item plays and any navigation menus work correctly.
Fixes https://github.com/xbmc/xbmc/issues/15414 
Fixes https://github.com/xbmc/xbmc/issues/15257
Should also fix https://github.com/xbmc/xbmc/issues/18250 (logfile shows same issue of incorrect path being used)

## Motivation and Context
When opening a dvd .iso file from eg music videos/titles the dvd menu appears but is not navigable.  Directories containing a dvd/bluray structure are not playable at all and simply show an error message.  Navigating by title/genre/etc should instead work correctly and the files should be played.

The reason these don't work is that the current code tests `strPath`  to try and determine what is to be played. But in these instances it contains a path such as `videodb://musicvideos/titles/3` rather than the actual path to the item.  This causes the tests to fail and renders the item either unplayable or, in the case of a dvd iso, not recognized as a dvd so the iso is launched but users are unable to navigate any menus.  Altering the tests to use `DynPath` instead fixes the issues.  As routines such as `CPlayerCoreFactory::GetPlayers()` always use DynPath for matching players I don't think this should cause any regressions.

## How Has This Been Tested?

I have tested this by playing various music concert dvd's both in iso format and with the video_ts.ifo etc files in a directory.  In all cases the files were opened properly.  I also tested a BD directory structure which failed to play before these changes but I do not have any BD.iso's to test against.

## User related:
Fixes an issue with the music video library where in some cases dvd iso files or directories containing dvd/Bluray files either failed to play at all or played without any navigation.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by the-black-eagle** [comment]
@DaVukovic any chance you can test this?

**Comment by MediaBrasil** [comment]
@the-black-eagle 

Compiled windows 64 version, work fine now, play ok the items, but appear 2 issues, broken access to videoinfo dialog (i), and in the library after movie titles, the values are replaced all with 0.

**Comment by the-black-eagle** [comment]
@MediaBrasil Thanks for testing!  Both those issues should be fixed now.

**Comment by MediaBrasil** [comment]
@the-black-eagle 

Yes, all fine now, thanks

Wanilton

File: xbmc/FileItem.cpp [hunk 1]
```diff
@@ -1093,7 +1093,10 @@ bool CFileItem::IsNFO() const
 
 bool CFileItem::IsDiscImage() const
 {
-  return URIUtils::HasExtension(m_strPath, ".img|.iso|.nrg|.udf");
+  if (URIUtils::HasExtension(m_strPath))
```
Comment (enen92) [inline xbmc/FileItem.cpp:1096]: dynpath should always take precedence over strPath (as you can see in all other implementations). When you call `GetDynPath` on `CFileItem` it will return the dynpath if not empty and then fall back to path. If you write this the other way around, does it still work?

Comment (enen92) [reply xbmc/FileItem.cpp:1096]: I'd say to use just:

`return URIUtils::HasExtension(GetDynPath(), ".img|.iso|.nrg|.udf");`

Comment (the-black-eagle) [reply xbmc/FileItem.cpp:1096]: Makes sense.  I kept as close to the original code as possible because for some routes, `m_strPath` worked correctly and I was wary of introducing any regression.

**Review by enen92 — APPROVED** [review]

**Review by phunkyfish — APPROVED** [review]
LGTM
