### PR TITLE
[video] fix selected item after removing version/extra

### LINKED ISSUE #24485: [video] Issue with extras removal
### Describe the bug

There is a problem in the "Manage Extras" dialog after removing an extra (maybe after other actions too, and maybe the same happens for versions). After following a specific sequence (see reproduction), the remove button doesn't work.

## Expected Behavior

Remove always works on the selected item (it's possible for extras. Versions have to worry about default version for the enabled status of Remove button)

### To Reproduce

With a movie that has at least 2 extras
1. Open Info > Manage Extras
2. Go down to the second extra
3. Go to the Remove button, activate it, confirm that you want to remove the extra.
4. The list refreshes, the highlight / selection is back on the first item of the list
5. Press right > focus should be again in Remove button. Activate it, confirm the removal.
6. The extra is still in the list. Closing / reopening the dialog doesn't help, the extra is really still there, it's not a missing list refresh.

As a workaround, the Remove button works as expected after pressing enter/selecting the first item explicitly between step 4 and 5.

### Debuglog

The debuglog can be found here, though likely not relevant: https://paste.kodi.tv/ogelehigux.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

The selected item member was not updated after removing a version or extra

This PR selects the first item of the list when the previously selected item doesn't exist in the list anymore after Refresh() - for example after removal of an item.

The first checks are overkill for the current needs in the context of the Remove button but make the function bulletproof for the future.

## Motivation and context

Fix #24485, which affects both versions and extras.

After removal of a version or extra, the top item of the list is highlighted and appears selected, but going to the remove button again attempts to remove again the already removed item, instead of removing the new selection.

## How has this been tested?

Versions/Extras Manager still opens with correct default item selected (default version or 1st extra of the list)
Back to back removals work as expected on the new selected item (top of the list).

## What is the effect on users?

Remove version/extra works as expected without side effects.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/video/dialogs/GUIDialogVideoManager.h [hunk 1]
```diff
@@ -28,6 +28,7 @@ class CGUIDialogVideoManager : public CGUIDialog
   virtual void SetVideoAsset(const std::shared_ptr<CFileItem>& item);
   virtual void SetSelectedVideoAsset(const std::shared_ptr<CFileItem>& asset);
   virtual bool HasUpdatedItems() const { return m_hasUpdatedItems; }
+  virtual void RefreshSelectedVideoAsset();
```
Comment (ksooo) [inline xbmc/video/dialogs/GUIDialogVideoManager.h:31]: Why is this `virtual`? I would make it only virtual if there is actual a reason. Virtual calls are more expensive than normal function calls (vtable lookup).

Comment (CrystalP) [reply xbmc/video/dialogs/GUIDialogVideoManager.h]: Not really useful today, it can easily be changed later if we need a different behavior for versions and extras.
It doesn't have to be public either. I pushed an updated.

Comment (CrystalP) [reply xbmc/video/dialogs/GUIDialogVideoManager.h]: unrelated: shouldn't the destructor be virtual though?

Comment (ksooo) [reply xbmc/video/dialogs/GUIDialogVideoManager.h]: > unrelated: shouldn't the destructor be virtual though?

It is. => https://github.com/xbmc/xbmc/blob/master/xbmc/video/dialogs/GUIDialogVideoManager.h#L26C3-L26C48

**Review by ksooo — APPROVED** [review]
LGTM
