### PR TITLE
[Windows] DXVA: check if HDR10 color spaces are supported by video processor

### LINKED ISSUE #23357: [Windows] HDR10 passthrough using limited range is broken on NVIDIA cards in master branch
### Describe the bug
Here is a clear and concise description of what the problem is:

HDR10 passthrough using limited color range is broken on NVIDIA cards in master branch.

Previously was (and still) working fine with RTX 2060 on v20/Nexus

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback fine using HDR10 passthrough with limited color range output.

## Actual Behavior
Kodi halts in `IsFormatConversionSupported`:

https://github.com/xbmc/xbmc/blob/d6b9189f5ca69886c4195e7695632197e27dd9f6/xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererDXVA.cpp#L119

Done several extensive tests:

- This only affects NVIDIA (probably also AMD) but is working fine on Intel (NUC8i3BEK).
- In NVIDIA behavior varies depending on hardware used.
- Tested various NVIDIA drivers (535.98, 528,49, 517.48) and no differences found.

| Model        |  Driver version   | IsFormatConversionSupported | black level  |
|    :---:         |         :---:             |                   :----:                        |        :---:      |
| RTX 2060   |    535.98             |            failed                              |    correct    |
| RTX 4070   |    535.98             |            failed                              |    wrong     |

The main reason of behavior change in v21 is that color conversions are strictly validated with `IsFormatConversionSupported` also this is even more broken using newer RTX 40x because black level is wrong if bypass `IsFormatConversionSupported`

In summary: 

- In master branch is broken for all NVIDIA graphics cards.
- In Nexus seems only broken in new RTX 40x, this is probably the reason of no complaints so far.
- It seems that NVIDIA is going in the direction of not supporting HDR10 limited range output and we could say that with older RTX 20x, 30x and GTX 10x, 16x graphics, it is working fine by chance because IsFormatConversionSupported fails anyway.

## Possible Fix

`IsFormatConversionSupported` seems well implemented and no issues found. Is not possible bypass / remove because in newer graphics black level obtained is wrong. Tested alternative TOPLEFT color space `DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020` and the result is the same.

I have some idea that I have tried and it works but I need to think about how to implement it correctly since it could cause other side effects, basically is always use full range in the video driver and move range conversion to swap chain. This is move this functionality  from video driver to Win32 API then it is very unlikely that there will be behavior variations due different hardware.

### To Reproduce

1. Configure limited color range in settings 
2. Play HDR10 video in a setup that supports HDR passthrough

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/edawolasid.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Windows 11 22H2
 - Kodi version: v21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description

 - In similar way that https://github.com/xbmc/xbmc/pull/23109 implements a static method to check if HDR10 color spaces are supported by video processor before initialize it. Then fallback to Pixel Shaders when DXVA not supports color conversion.
- Added support for use the two existent DXGI HDR10 color spaces with different chroma sitting: `DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_LEFT_P2020` and `DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020`.
- When the two YCBCR HDR10 color spaces are supported is used TOPLEFT because according Microsoft documentation this is the right one for UHD Blu-Ray https://learn.microsoft.com/en-us/windows/win32/api/dxgicommon/ne-dxgicommon-dxgi_color_space_type#siting
- Removes the workaround for HDR10 in limited range implemented in https://github.com/xbmc/xbmc/pull/19826 because in RTX 4070 is not valid anymore (wrong black level) and even on RTX 20x, 30x is not usable now because  `CheckVideoProcessorFormatConversion` returns is not valid conversion.

## Motivation and context
Found that in NVIDIA RTX 4070 things goes wrong with HDR10 limited range.... The use of only "native" color spaces for HDR10 simplifies things and with more strictly checks and fallback to Pixel Shaders more robust and predictable behavior should result.

Closes https://github.com/xbmc/xbmc/issues/23357

Also should fix other sporadic issues seen in forums as: 
https://forum.kodi.tv/showthread.php?tid=372606&pid=3146966#pid3146966

## How has this been tested?
Runtime tested Intel NUC8i3BEK and NVIDIA RTX 4070. 
On NUC continues working as before supporting DXVA HDR10 passthrough in full and limited range.
On RTX 4070 DXVA HDR10 works only in full range and now is used Pixel Shaders in limited range.

Note that current behavior for RTX 4070 limited range in Nexus is wrong black level and in master execution halts in:
https://github.com/xbmc/xbmc/blob/f84cf8bcff3c22e249d91e676c7a0229547190c1/xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererDXVA.cpp#L137

## What is the effect on users?
Avoids failures or wrong picture/black screen when DXVA HDR10 color conversion is not full supported and improves compatibility in some scenarios.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by afedchin — APPROVED** [review]

**Comment by CrystalP** [comment]
UHD Blu-ray is not the only source of HDR so unsure about always using topleft (it's most likely the most common though).
Phones, cameras, streaming, transcoding, ... I don't know the details for those.

Looks like a solid change, will have to run-time test it to go through some of the combinations.

File: xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererDXVA.cpp [hunk 1]
```diff
@@ -32,8 +32,20 @@ void CRendererDXVA::GetWeight(std::map<RenderMethod, int>& weights, const VideoP
   unsigned weight = 0;
   const AVPixelFormat av_pixel_format = picture.videoBuffer->GetFormat();
 
+  const bool streamIsHDR = (picture.color_primaries == AVCOL_PRI_BT2020) &&
+                           (picture.color_transfer == AVCOL_TRC_SMPTE2084 ||
+                            picture.color_transfer == AVCOL_TRC_ARIB_STD_B67);
+  const auto settings = CServiceBroker::GetSettingsComponent()->GetSettings();
+  const auto setting = DX::Windowing()->SETTING_WINSYSTEM_IS_HDR_DISPLAY;
+  const bool systemUsesHDR =
+      settings ? settings->GetBool(setting) && DX::Windowing()->IsHDRDisplay() : false;
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererDXVA.cpp:41]: HDR logic in Windows is quite complicated and this not covers all use cases: setting in Kodi can be off but HDR enabled permanently in Windows display settings or user can toggle HDR on manually with F11 key before start movie...

Then is need:
` (settings->GetBool(setting) && DX::Windowing()->IsHDRDisplay()) || DX::Windowing()->IsHDROutput()`

**Comment by thexai** [comment]
> UHD Blu-ray is not the only source of HDR so unsure about always preferring topleft (it's most likely the most common though). Phones, cameras, streaming, transcoding, ... I don't know the details for those.

4K Remuxes, even 1080p HDR versions probably comes all from UHD Blu Ray anyway. In any case the difference (if any) sure is minimal: probably chroma plane half pixel shifted vertically. This in 4K resolution I'm not sure if can be noticed.

**Review by CrystalP — COMMENTED** [review]
forgot to push the button earlier, sorry.

**Comment by CrystalP** [comment]
> > UHD Blu-ray is not the only source of HDR so unsure about always preferring topleft (it's most likely the most common though). Phones, cameras, streaming, transcoding, ... I don't know the details for those.
> 
> 4K Remuxes, even 1080p HDR versions probably comes all from UHD Blu Ray anyway. In any case the difference (if any) sure is minimal: probably chroma plane half pixel shifted vertically. This in 4K resolution I'm not sure if can be noticed.

We can go with topleft preferred, but please add a comment that flags are ignored on purpose.
I found an example of HDR reencode with missing flagging, but am unable to tell if chroma was moved during reencode or is still topleft.

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp [hunk 2]
```diff
@@ -324,16 +318,37 @@ bool CProcessorHD::InitProcessor()
...
+        &supported);
+    const bool HDRtopLeft = SUCCEEDED(hr) && static_cast<bool>(supported);
+
     m_BT2020TopLeft = !left && topLeft;
     CLog::LogF(LOGDEBUG,
                "BT.2020 input color spaces supported: YCBCR_STUDIO_G22_LEFT_P2020: {}, "
                "YCBCR_STUDIO_G22_TOPLEFT_P2020: {}",
                left ? "yes" : "no", topLeft ? "yes" : "no");
+
+    m_HDR10Left = !HDRtopLeft && HDRleft;
```
[the remark this answers is not in the document]
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:342]: This is matter for another PR. I take a look another time.

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp [hunk 3]
```diff
@@ -1025,7 +1097,7 @@ DXGI_COLOR_SPACE_TYPE CProcessorHD::AvToDxgiColorSpace(const DXGIColorSpaceArgs&
   {
     if (csArgs.color_transfer == AVCOL_TRC_SMPTEST2084)
       // Full range DXGI_COLOR_SPACE_YCBCR_FULL_G2084_LEFT_P2020 does not exist at this time
-      return DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_LEFT_P2020;
+      return DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020;
```
[the remark this answers is not in the document]
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:1100]: This in another PR too

**Comment by CrystalP** [comment]
Is it stable for runtime testing?

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp [hunk 4]
```diff
@@ -324,16 +318,39 @@ bool CProcessorHD::InitProcessor()
...
+        DXGI_FORMAT_P010, DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_LEFT_P2020, format, outputCS,
+        &supported);
+    const bool HDRleft = SUCCEEDED(hr) && static_cast<bool>(supported);
+
+    hr = m_pEnumerator1->CheckVideoProcessorFormatConversion(
+        DXGI_FORMAT_P010, DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020, format, outputCS,
+        &supported);
+    const bool HDRtopLeft = SUCCEEDED(hr) && static_cast<bool>(supported);
+
     m_BT2020TopLeft = !left && topLeft;
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:336]: Should prefer topleft as well, this mode is used for HDR source, most likely a topleft uhd bd.
AMD supports topleft and left equally.
Please also log which one will be used when both are available,

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp [hunk 5]
```diff
@@ -324,16 +318,39 @@ bool CProcessorHD::InitProcessor()
...
+
+    m_HDR10Left = !HDRtopLeft && HDRleft;
+    CLog::LogF(LOGDEBUG,
+               "HDR10 input color spaces supported with {} range output: "
+               "YCBCR_STUDIO_G2084_LEFT_P2020: {}, "
+               "YCBCR_STUDIO_G2084_TOPLEFT_P2020: {}. {} will be used.",
+               DX::Windowing()->UseLimitedColor() ? "limited" : "full", HDRleft ? "yes" : "no",
+               HDRtopLeft ? "yes" : "no",
+               m_HDR10Left ? "Fallback chroma siting left"
+                           : "Preferred UHD Blu-Ray chroma siting top left");
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:350]: Respectively "Fallback left chroma si**tt**ing" and "Preferred UDH Blu-Ray top left chroma si**tt**ing" please. (spelling +order of words in english)

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (CrystalP) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:342]: nevermind I'm OK with topleft for everything. We'll see later if it's a problem.

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp [hunk 6]
```diff
@@ -848,6 +855,73 @@ bool CProcessorHD::IsBT2020Supported()
...
+  }
+
+  if (FAILED(pEnumerator.As(&pEnumerator1)))
+  {
+    CLog::LogF(LOGWARNING,
+               "ID3D11VideoProcessorEnumerator1 is not available. DXVA will not be used.");
+    return false;
+  }
+
+  const DXGI_FORMAT destFormat = DX::Windowing()->GetBackBuffer().GetFormat();
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:890]: Problematic with screen SDR/HDR switch by Kodi and AMD "Use 10 bit for SDR" Auto or off.
Back buffer is still 8 bits when this function executes.

The AMD dxva processor doesn't support PQ in B8G8R8A8_UNORM, as a result there is fallback to Pixel Shaders.
The processor has no issue with topleft and left both available in R10G10B10A2 that will be switched to a little later.

Always using R10G10B10A2 format here should be OK, no? There are guards in GetWeight() before getting here.

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp [hunk 7]
```diff
@@ -848,6 +855,73 @@ bool CProcessorHD::IsBT2020Supported()
...
+  const DXGI_COLOR_SPACE_TYPE destColor = DX::Windowing()->UseLimitedColor()
+                                              ? DXGI_COLOR_SPACE_RGB_STUDIO_G2084_NONE_P2020
+                                              : DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020;
+  BOOL supported = 0;
+
+  // Check if HDR10 (TOP LEFT) input color space is supported by video driver
+  HRESULT hr = pEnumerator1->CheckVideoProcessorFormatConversion(
+      DXGI_FORMAT_P010, DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020, destFormat, destColor,
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:898]: Assuming P010 will work 99% of the time but I have a sample with 8 bit PQ+BT.2020
AMD doesn't support NV12 + PQ and BT.2020 as input, but Intel Gen 8 does and outputs correctly.
Pass the format NV12/P010 from GetWeight?

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp [hunk 8]
```diff
@@ -324,16 +318,39 @@ bool CProcessorHD::InitProcessor()
...
+    hr = m_pEnumerator1->CheckVideoProcessorFormatConversion(
+        DXGI_FORMAT_P010, DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_LEFT_P2020, format, outputCS,
+        &supported);
+    const bool HDRleft = SUCCEEDED(hr) && static_cast<bool>(supported);
+
+    hr = m_pEnumerator1->CheckVideoProcessorFormatConversion(
+        DXGI_FORMAT_P010, DXGI_COLOR_SPACE_YCBCR_STUDIO_G2084_TOPLEFT_P2020, format, outputCS,
+        &supported);
+    const bool HDRtopLeft = SUCCEEDED(hr) && static_cast<bool>(supported);
+
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:335]: This function is called after switching screen SDR to HDR so assuming output format = back buffer = rgb10 works but doesn't feel very strong.
The log looks odd in SDR for AMD and 8 bit backbuffer ("Use 10 bit for SDR" Auto or off value) because the processor has no support for PQ in B8G8R8A8_UNORM. Odd but not blocking.
Same note as IsHDR10PassthroughSupported(), assuming the input format is always P010.

**Comment by CrystalP** [comment]
Tested completed on AMD, Intel Gen 4 and Gen 8. See the previous notes. The problem of destination format in IsHDR10PassthroughSupported() is blocking.

The limited output is rejected for AMD and accepted by Intel, as expected.

AMD also doesn't output limited range for SDR, do you think the new function can be generalized or would it take a separate one? (no questions of top left vs left in SDR)

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp (hunk 4 above)
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp]: Done, only is logged when both are available.

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp (hunk 5 above)
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp]: I changed order of words but spelling is correct siting  (one t) see:
https://learn.microsoft.com/en-us/windows/win32/api/dxgicommon/ne-dxgicommon-dxgi_color_space_type#siting

> The following examples show different combination of chroma siting in a 4x4 image.
https://www.kernel.org/doc/html/next/userspace-api/media/v4l/yuv-formats.html

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp (hunk 6 above)
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp]: Done

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp (hunk 7 above)
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp]: I'm not sure of this: is supposed HDR10 is always P010

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp (hunk 5 above)
Comment (CrystalP) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp]: yes my bad, I assumed it was derived from sit, not site

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp (hunk 8 above)
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:335]: This code is only to determine use Left or TopLeft and if `dxgi_format` is not supported is detected early in `IsHDR10PassthroughSupported()` and this code is not reached anyway.

**Comment by thexai** [comment]
I think all points are resolved and is ready for final test/review.

**Comment by thexai** [comment]
> AMD also doesn't output limited range for SDR, do you think the new function can be generalized or would it take a separate one?

Maybe a new separated method like `IsSDRLimitedOutputSupported()` as HDR limited is already covered and SDR full is not need to check as is the default.

**Comment by atrugiel69** [comment]
Sorry for the ignorant question but... I have tried installing the build from today. I saw from Jenkins, up here, that it failed building for TVOS and Linux GLES but it built for other platforms, Windows included.

Does this mean that build 20230607-babe32cf-master-x64 should include this? If it does... it doesn't appear to solve the problem with HDR material. If it doesn't, please ignore (or maybe explain why, so that I won't repeat the mistake in the future).

**Comment by afedchin** [comment]
current nightly doesn't include these changes till this will be merged

**Comment by atrugiel69** [comment]
> current nightly doesn't include these changes till this will be merged

Ok, thanks for confirming. So testing PRs before merge is something that only devs can do (unless one builds by him/herself)?

**Comment by atrugiel69** [comment]
> There is a build here: https://mirrors.kodi.tv/test-builds/windows/win64/
> 
> KodiSetup-20230607-bb6f0be3-dxva-hdr10-x64.exe

For me, RTX 3070, this solves the HDR playback problem. Thanks for sharing the build.

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp [hunk 9]
```diff
@@ -848,6 +866,72 @@ bool CProcessorHD::IsBT2020Supported()
   return false;
 }
 
+bool CProcessorHD::IsHDR10PassthroughSupported(const DXGI_FORMAT dxgi_format)
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/DXVAHD.cpp:869]: Do you mind renaming to IsPQ010PassthroughSupported? PQ010 is HDR10 without metadata, which don't matter here

File: xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererDXVA.cpp [hunk 10]
```diff
@@ -31,9 +31,25 @@ void CRendererDXVA::GetWeight(std::map<RenderMethod, int>& weights, const VideoP
...
+  const auto settings = CServiceBroker::GetSettingsComponent()->GetSettings();
+  const auto setting = DX::Windowing()->SETTING_WINSYSTEM_IS_HDR_DISPLAY;
+  const bool systemUsesHDR =
+      (settings ? settings->GetBool(setting) && DX::Windowing()->IsHDRDisplay() : false) ||
+      DX::Windowing()->IsHDROutput();
 
   if (av_pixel_format == AV_PIX_FMT_D3D11VA_VLD)
   {
+    // Check if HDR10 passthrough is supported by DXVA video processor
+    if (streamIsHDR && systemUsesHDR &&
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererDXVA.cpp:49]: Please add comment that the check is relevant also for HLG because the renderer has a workaround to use PQ passthrough when the processor doesn't support HLG input.

**Review by CrystalP — APPROVED** [review]
Looks good, ran well. No need for a retest after the couple cosmetic comments, it's approved for me.

**Comment by CrystalP** [comment]
You can merge whenever.

**Comment by thexai** [comment]
TVOS build failure is unrelated.
