### PR TITLE
[Windows] Fix: incorrect colors in some AMD graphics when used 10bit in SDR

### LINKED ISSUE #21081: Colors too saturated with Kodi versions > 19.1
### Describe the bug

I don't update Kodi often, and I was running 19.1 for a while. Recently I updated to 19.3, and I noticed the colors in every video were way too saturated. Everything is way too red, and unwatchable. It's not visible in screenshots. It looks like Kodi forces my TV to make everything saturated. If I play the same video files in MPC BE it looks fine.

Every version > 19.1 has this problem. If I install 19.1 everything is fine. If I install 19.2/3/4 everything looks too saturated and dark. I don't change any settings, just install a different version, and I immediately see the difference. I use standard settings in Kodi, with DXVA2 and HDR enabled. I tried changing these, but that doesn't make a difference.

My Kodi PC runs Windows 10, and has an Intel G4600 CPU and an AMD RX550 GPU. I have tried several AMD graphic driver versions, but that doesn't seem to make a difference. And as I said earlier, if I play a video with MPC BE it looks fine, but with Kodi > 19.1 it's too saturated.

My Kodi PC is connected to a LG OLED, which is HDR capable. If I play HDR movies with Kodi my TV switches to HDR mode. This issue seems to be only with SDR content though. The AMD graphic drivers are set to "10-Bit Pixel Format", and to RGB 4:4:4 Full RGB.  

## Expected Behavior
Video looks normal.

## Actual Behavior

When upgrading to a Kodi version past 19.1, everything looks too saturated. Every video is too red/dark.

## Possible Fix

I looked at the 19.2 changelog, and I saw several changes to HDR and other color related things. I narrowed it down to a few PR's, and started compiling my own versions of Kodi 19.4 with several files reverted to 19.1. In the end, I narrowed it down to PR #19775.

When I compile my own version of Kodi 19.4, everything looks dark/red/saturated. If I then manually revert the changes from PR #19775, everything looks as it should.

This pull request seems to change some HDR and color related stuff, but in my case this makes Kodi unusable, everything looks like crap. I can't find anything else about this, so apparently I am the only one with this problem. As far as I can tell, this isn't a setting or something, but an actual change in Kodi behavior right?

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 21H2
 - Kodi version: 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Fix: incorrect colors in some AMD graphics when used 10bit in SDR

Fixes https://github.com/xbmc/xbmc/issues/21081

## Motivation and context
Some AMD graphics has issues when is used 10bit swapchain. Seems all processing inside Kodi is right but when video outputs graphics card are flagged as BT.2020 by AMD video driver.

See: https://github.com/xbmc/xbmc/issues/21081 and https://forum.kodi.tv/showthread.php?tid=365817

Screenshots are with correct colors and if in TV settings are forced BT.709 color space, correct colors are also obtained. Is not related to DXVA2 video decoding.

This incompatibility only has been reported by AMD users. In master branch this is not critical because already exist a GUI setting to enable or not 10 bit for SDR in https://github.com/xbmc/xbmc/pull/20014 but in Matrix currently cannot be disabled. 

This PR only limits the cases in which it is activated by default, although users who are not affected by this may continue to activate it the same in GUI settings. 

Also with backport to Matrix users may continue enable 10bit using advanced setting "try10bitoutput".

## How has this been tested?
Two users has confirmed issue is fixed by this: https://github.com/xbmc/xbmc/issues/21081#issuecomment-1114031692 and https://github.com/xbmc/xbmc/issues/21081#issuecomment-1114309543

## What is the effect on users?
Fixed: Wrong/too saturated colors with some AMD graphics when playing SDR video using 10bit on an HDR compatible display (with Windows HDR off).

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/rendering/dx/DeviceResources.cpp [hunk 1]
```diff
@@ -607,7 +607,11 @@ void DX::DeviceResources::ResizeBuffers()
   {
     HDR_STATUS hdrStatus = CWIN32Util::GetWindowsHDRStatus();
     const bool isHdrEnabled = (hdrStatus == HDR_STATUS::HDR_ON);
-    bool use10bit = (hdrStatus != HDR_STATUS::HDR_UNSUPPORTED);
+
+    DXGI_ADAPTER_DESC ad = {};
+    GetAdapterDesc(&ad);
+    bool use10bit = hdrStatus != HDR_STATUS::HDR_UNSUPPORTED &&
```
Comment (afedchin) [inline xbmc/rendering/dx/DeviceResources.cpp:613]: as I understand the sentence it disables 10bit output completely for AMD cards even if HDR is supported. I'm not sure what HDR will work correctly with 8bit output.

Comment (thexai) [reply xbmc/rendering/dx/DeviceResources.cpp:613]: No, `use10bit` only determines if is used 10 bit for SDR.

For HDR is used `isHdrEnabled`:
https://github.com/xbmc/xbmc/blob/768d7fceac2328fda6e57739e8d598c173f9e503/xbmc/rendering/dx/DeviceResources.cpp#L609

And finally combined condition here:
https://github.com/xbmc/xbmc/blob/768d7fceac2328fda6e57739e8d598c173f9e503/xbmc/rendering/dx/DeviceResources.cpp#L646-L650

Comment (afedchin) [reply xbmc/rendering/dx/DeviceResources.cpp:613]: ok. but what for there is condition with FL >= 12.1? 10bit can be used on FL >= 11

Comment (thexai) [reply xbmc/rendering/dx/DeviceResources.cpp:613]: Those are just the conditions that trigger it ON by default. They can be overridden by GUI settings in any case. 

The idea is to activate it by default only when used the latest drivers (12.1) from Intel or Nvidia  and when the system also supports HDR (even if it is not activated), this also implies that is in Windows 10/11 only. Systems that do not meet all these conditions may have issues and must be expressly activated by the user (once confirmed that it works).

Instead FL >= 11 is the condition that allows it to be activated. If it fails despite the user forcing it in GUI settings or "try10bitoutput" (Matrix) it will not be enabled.

**Review by afedchin — APPROVED** [review]

**Review by garbear — APPROVED** [review]
The logic is a bit crammed on that line. I would keep the previous removed line (preserves git history) and then do something like:

```c++
bool use10bit = (hdrStatus != HDR_STATUS::HDR_UNSUPPORTED);

// Add comment here about why this stanza is needed
DXGI_ADAPTER_DESC ad = {};
GetAdapterDesc(&ad);
if (m_d3dFeatureLevel >= D3D_FEATURE_LEVEL_12_1 && ad.VendorId != PCIV_AMD)
  use10bit = false;
```

IMO looks more readable than

```c++
     bool use10bit = hdrStatus != HDR_STATUS::HDR_UNSUPPORTED &&
                     m_d3dFeatureLevel >= D3D_FEATURE_LEVEL_12_1 && ad.VendorId != PCIV_AMD;
```

**Comment by thexai** [comment]
Ok but your example code is wrong (doesn't do what we want):

 if ad.VendorId != PCIV_AMD want 10 bit enabled 

enable condition if !A **and** !B    is the same that disable condition if A **or** B

want 10bit enabled if `FL >= 12.1` and `VendorId != PCIV_AMD`  

so

want 10bit disabled if `FL < 12.1`  OR `VendorId == PCIV_AMD`

**Review by garbear — APPROVED** [review]
You're right, my logic doesn't pass muster. Nevertheless do you see how you can split if-statements in some situations to make the code more understandable? To that end, it's a style question, and I entirely defer to you how you want it done.
