### PR TITLE
DVDFileInfo: Consult av_image_get_buffer_size before allocating

### LINKED ISSUE #18935: CDVDFileInfo::ExtractThumb
### Describe the bug
Here is a clear and concise description of what the problem is:

kodi (git/master) is crashing when loading icon from my movie collection.

Backtrace is

```
(gdb) bt
#0  0x00007ffff4f127bb in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff4efd535 in __GI_abort () at abort.c:79
#2  0x00007ffff4f54508 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff505f28d "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff4f5ac1a in malloc_printerr (str=str@entry=0x7ffff505d393 "corrupted double-linked list") at malloc.c:5341
#4  0x00007ffff4f5c56c in _int_free (av=0x7fff68000020, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4325
#5  0x0000555558fe0071 in sws_freeContext (c=0x7fff68a8c740) at src/libswscale/utils.c:2339
#6  0x0000555558fe0071 in sws_freeContext (c=0x7fff68a8c740) at src/libswscale/utils.c:2319
#7  0x00005555572daa5e in CDVDFileInfo::ExtractThumb(CFileItem const&, CTextureDetails&, CStreamDetails*, long) (fileItem=..., details=..., pStreamDetails=0x7fff6c124140, pos=-1)
    at /home/mathieu/Perso/xbmc/xbmc/cores/VideoPlayer/DVDFileInfo.cpp:269
#8  0x00005555574ac0d5 in CThumbExtractor::DoWork() (this=0x7fff6c11e7b0) at /home/mathieu/Perso/xbmc/xbmc/video/VideoThumbLoader.cpp:113
#9  0x0000555557575f6e in CJobWorker::Process() (this=0x55555bf2a960) at /home/mathieu/Perso/xbmc/xbmc/utils/JobManager.cpp:55
#10 0x0000555557636ef5 in CThread::Action() (this=0x55555bf2a960) at /home/mathieu/Perso/xbmc/xbmc/threads/Thread.cpp:282
#11 0x00005555576365ed in CThread::<lambda(CThread*, std::promise<bool>)>::operator()(CThread *, std::promise<bool>) const (__closure=0x55555c40dca8, pThread=0x55555bf2a960, promise=...)
    at /home/mathieu/Perso/xbmc/xbmc/threads/Thread.cpp:140
#12 0x00005555576374cd in std::__invoke_impl<void, CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> >(std::__invoke_other, CThread::<lambda(CThread*, std::promise<bool>)> &&, CThread *&&, std::promise<bool> &&) (__f=..., __args#0=@0x55555c40dcc0: 0x55555bf2a960, __args#1=...) at /usr/include/c++/8/bits/invoke.h:60
#13 0x00005555576371bb in std::__invoke<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> >(CThread::<lambda(CThread*, std::promise<bool>)> &&, CThread *&&, std::promise<bool> &&) (__fn=..., __args#0=@0x55555c40dcc0: 0x55555bf2a960, __args#1=...) at /usr/include/c++/8/bits/invoke.h:95
#14 0x0000555557637879 in std::thread::_Invoker<std::tuple<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > >::_M_invoke<0, 1, 2>(std::_Index_tuple<0, 1, 2>)
    (this=0x55555c40dca8) at /usr/include/c++/8/thread:244
#15 0x0000555557637818 in std::thread::_Invoker<std::tuple<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > >::operator()(void) (this=0x55555c40dca8)
    at /usr/include/c++/8/thread:253
#16 0x00005555576377fc in std::thread::_State_impl<std::thread::_Invoker<std::tuple<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > > >::_M_run(void)
    (this=0x55555c40dca0) at /usr/include/c++/8/thread:196
#17 0x00007ffff409eb2f in  () at /lib/x86_64-linux-gnu/libstdc++.so.6
#18 0x00007ffff7f6dfa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#19 0x00007ffff4fd44cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

```

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fritsch**
As we have intrinsics in use and sws_scale needs proper alignment and
proper dimensions, we not only shall continue to use av_malloc but
also properly align the buffer size to not write out of the picture.

Fixes: #18935

### CODE REVIEW

**Comment by fritsch** [comment]
@malaterre This should be the proper way of doing it.

**Comment by fuzzard** [comment]
Jenkins build this please

File: xbmc/cores/VideoPlayer/DVDFileInfo.cpp [hunk 1]
```diff
@@ -250,7 +251,8 @@ bool CDVDFileInfo::ExtractThumb(const CFileItem& fileItem,
               aspect = hint.aspect;
             unsigned int nHeight = (unsigned int)((double)nWidth / aspect);
 
-            uint8_t *pOutBuf = (uint8_t*)av_malloc(nWidth * nHeight * 4);
+            int sizeNeeded = av_image_get_buffer_size(AV_PIX_FMT_BGRA, nWidth, nHeight, 64);
```
Comment (lrusak) [inline xbmc/cores/VideoPlayer/DVDFileInfo.cpp:254]: `64` alignment for what? :wink:

Comment (fritsch) [reply xbmc/cores/VideoPlayer/DVDFileInfo.cpp:254]: It's not for the alignment, it's for the additional padding. sws_scale needs 16 bit alignment and sizes need to be 16 bit aligned as well. Shall I reduce it to 16? Just wanted to make sure that any possible intrinsic we get is safe to use.

Comment (fritsch) [reply xbmc/cores/VideoPlayer/DVDFileInfo.cpp:254]: If I set it to 16 instead, it crashes again right away.

Comment (fritsch) [reply xbmc/cores/VideoPlayer/DVDFileInfo.cpp]: Okay revisited it. In my testing the , 64 works by chance - what really matters for me seems that the width needs to be dividable by 16.

**Review by lrusak — APPROVED** [review]

**Comment by fritsch** [comment]
Thanks much!
