### PR TITLE
[upnp] Prefer movie posters to thumbs when serving the library items …

### LINKED ISSUE #17587: UPnP / DLNA regression: albumArtURI is pointing to the video rather than the poster image
### Describe the bug
Thumbnails for videos no longer work over UPnP / DLNA. This is a regression, since it works in 18.6.

## Expected Behavior
When viewing the Kodi library on a DLNA client, in my case an LG webOS TV, Kodi is normally using the poster images as the thumbnails.

## Actual Behavior
With Kodi 19 as the DLNA server the thumbnails are missing on the client.

## Possible Fix

I used wireshark to compare the metadata Kodi sends, and for whatever reason Kodi 19 is using the video URI rather than the poster image URI. This was not the case in Kodi 18.

**Kodi 18.6:**
`<upnp:albumArtURI dlna:profileID="JPEG_TN">http://192.168.2.116:1998/%25/4b003382b6490bc3a9682f223e60e683/Fight.Club.1999.1080p.BluRay.X264-poster.jpg</upnp:albumArtURI>`

**Kodi 19:**
`<upnp:albumArtURI dlna:profileID="JPEG_TN">http://192.168.2.116:1889/%25/bc1efdd9cfe15fda86ef87e57f5ed2e4/Fight.Club.1999.1080p.BluRay.X264.mkv</upnp:albumArtURI>`

### To Reproduce
1. Browse the Kodi video library on a DLNA client.
2. Observe the missing thumbnails.

The debuglog can be found here: https://paste.kodi.tv/hadiyutudi.kodi

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64 (10.0.18363.752)
 - Kodi version: 19 (KodiSetup-20200329-e7878130-master-x64)

### PR DESCRIPTION
**Pull request by enen92**
…over upnp

In https://github.com/xbmc/xbmc/pull/17127 we removed the old fallback for the default filling of movie thumbs with poster images. Reason was that thumb itself is a legit art type and it was up to the client (skins, apps, webinterfaces, etc) to choose which art types to display (provided the whole art map). However, this caused a regression in library sharing over upnp where it now uses thumb as the `albumArtURI` for movies.
This PR thus make it prefer posters for that property instead of thumbs for movies only.

@Montellese and @rmrector for review

## Motivation and Context
Fixes https://github.com/xbmc/xbmc/issues/17587

## How Has This Been Tested?
Compile and tested using vlc as a client in android.

## Screenshots (if appropriate):

**Before:**

alt text

**After:**

alt text

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
jenkins build this please

File: xbmc/network/upnp/UPnPInternal.cpp [hunk 1]
```diff
@@ -580,7 +580,13 @@ BuildObject(CFileItem&                    item,
             thumb_loader->LoadItem(&item);
 
         // finally apply the found artwork
-        thumb = item.GetArt("thumb");
+        // note: movies should use poster as the preferred "thumb" image
+        if (item.HasVideoInfoTag() && item.GetVideoInfoTag()->m_type == MediaTypeMovie &&
```
Comment (Montellese) [inline xbmc/network/upnp/UPnPInternal.cpp:584]: Is `"thumb"` the correct default for tvshows and seasons?

**Review by Montellese — APPROVED** [review]
Changes look good but I don't know what the proper default artwork for each video type is.

**Comment by rmrector** [comment]
Makes sense. Can you add TV shows and seasons (but not episodes) to the check as well? They also use "poster" as the primary image and were likely affected the same as movies here.

**Comment by enen92** [comment]
VLC doesn't use it unless it is a video file, so I don't have any way to test it. Any tips?

**Comment by sialivi** [comment]
Sorry to butt in, I'm the one who reported the issue.

Does the fact that you're seeing thumbnails in VLC in your before-screenshot mean VLC is generating the thumb client side from the video URI? That can't be the right behavior. It's supposed to be a JPEG, not a video.

Also, according to the spec, the albumArtURI is a multi-value field, but Kodi only returns the JPEG_TN. Why not also supply JPEG_SM, JPEG_MED and JPEG_LRG for clients that support, or even rely, on those?

**Comment by enen92** [comment]
@sialivi means kodi thumbloader is generating a thumbnail from the video since the "thumb" entry in the art map is empty. As for the second part of your comment, it's a feature request and my only goal here to restore the previous behaviour since I was the one to break it.

Can you check what the behaviour was before for tvshows and seasons before vs the current one with your smart tv? VLC doesn't show any image for those items (just a generic folder item) so I am unsure if my PR also broke it for those media types.

**Comment by sialivi** [comment]
> @sialivi means kodi thumbloader is generating a thumbnail from the video since the "thumb" entry in the art map is empty.

That's not the behavior I was seeing on my TV though, since the wireshark log showed that Kodi was supplying the URI of the video instead of the image.

> Can you check what the behaviour was before for tvshows and seasons vs the current one with your smart tv? VLC doesn't show any image for those items (just a generic folder icon) so I am unsure if my PR also broke it for those media types.

Kodi v19:
- Movies: Blank
- TV Shows: Blank
- TV Show Seasons: Blank
- TV Show Episodes: Working thumbnails
- Music Videos: Working thumbnails

Kodi v18:
- Movies: Working posters
- TV Shows: Blank
- TV Show Seasons: Blank
- TV Show Episodes: Working thumbnails
- Music Videos: Working thumbails

**Comment by enen92** [comment]
You're right, so probably it's vlc generating the thumb and not kodi thumbloader. But kodi does the same in similar situations (when thumb is empty).

Since it is not clear if shows and seasons should follow the same behaviour (they are in fact directories and not video files) - and since episodes (the actual video files) have the correct thumb - I suggest to merge this one as is and see if anyone complains about shows and seasons later.

And thank you for bringing the issue to our attention

**Comment by Montellese** [comment]
I just noticed that in the Chorus2 webinterface it also shows video thumbnails instead of posters for movies.

**Comment by enen92** [comment]
@Montellese I fixed the chorus2 issue here: https://github.com/xbmc/chorus2/pull/392

I plan to go over to open PRs and see which ones make sense in a new version and then update the chorus2 version we ship. Unfortunately the project is not maintained anymore.
Let's hope gsoc somehow fixes the situation
