### PR TITLE
[upnp] fix regressions for folder definitions

### LINKED ISSUE #22665: Musiccast streaming music playlist fails after upgrade to 20.0, works on 19.3
## Bug report
Since upgrading to v20, cant stream any music to music cast devices. Downgrading to 19.3 and it works again.

### Describe the bug
Unable to stream music to Musiccast devices (tried HTR amp, and Musiccast 50, both fail), since upgraded to v20.
When downgraded to v19.3 it works again.

## Expected Behavior
Playlists are listed, can select a song, and it starts playing.

## Actual Behavior
Playlists are listed, but cant open up the playlist and select a song. An error is given in the app 'afspelen is niet mogelijk', which is Dutch for ' playback is not possible' .
It fails upon selecting the playlist, and it not even listing songs.

## Possible Fix
Downgrade to v19.3

### To Reproduce

Open up the Musiccast android app, choose KODI -> Music -> Playlist and start one of the playlists
It now says 'afspelen is niet mogelijk' which is Dutch for 'playback is not possible'
It seems to try and hit every song, so the app going kinda haywire.

### Debuglog
Playlists are located in 
C:\Users\$USERNAME\AppData\Roaming\Kodi\userdata\playlists\music

### Your Environment
Used Operating system:
Client is Android 12
Server is Windows 10, tried on Kodi v20 (kodi-20.0-Nexus-x64.exe, fails) and 19.3 (kodi-19.3-Matrix-x64.exe) (success)
Tried to set Kodi to extensive logging, but no relevant logs are saved (at leasts, non of the attempt to read the playlist).

How can I provide debug logging to help you guys?

### PR DESCRIPTION
**Pull request by enen92**
## Description

This fixes regressions introduced in v20 development regarding folder definitions. Those fallbacks/definitions that in the past used to work miraculously have been removed from other parts of the codebase breaking upnp on some clients (items reported instead of containers).
Better to set them on the source while creating the items.

Note that clang-format will for sure complain and suggest a huge diff. Since those folders are completely broken in terms of style I think it is better not to do it now (keeping the history clean) and maybe consider to do it in bulk later. 

Fixes https://github.com/xbmc/xbmc/issues/22665
Fixes partially https://github.com/xbmc/xbmc/issues/22828 (requires more changes)

### CODE REVIEW

File: xbmc/network/upnp/UPnPServer.cpp [hunk 1]
```diff
@@ -272,8 +272,9 @@ PLT_MediaObject* CUPnPServer::Build(const std::shared_ptr<CFileItem>& item,
 
     m_logger->debug("Preparing upnp object for item '{}'", (const char*)path);
 
-    if (path == "virtualpath://upnproot") {
+    if (path.StartsWith("virtualpath://upnproot")) {
         path.TrimRight("/");
+        item->m_bIsFolder =  true;
         if (path.StartsWith("virtualpath://")) {
```
Comment (enen92) [inline xbmc/network/upnp/UPnPServer.cpp:278]: this condition here doesn't make much sense as it's guarded already by `virtualpath://upnproot` probably some old leftover

Comment (smf007) [reply xbmc/network/upnp/UPnPServer.cpp:278]: Looking at the rest of the code, was this functionally backwards previously?  In which case should this if should be testing for requesting the root, in which case this should be the
`if (path == "virtualpath://upnproot") {`

Comment (enen92) [reply xbmc/network/upnp/UPnPServer.cpp:278]: Yes it is only testing root (and the whole codeblock below proves it). I think the first condition should be checking for virtualpath:// generically (not sure what other virtualpaths:// exist besides upnproot)

Comment (smf007) [reply xbmc/network/upnp/UPnPServer.cpp:278]: I found this list in one of Montellese's posts:

    virtualpath://upnproot/
    musicdb://
    videodb://
    library://video
    sources://video
    special://musicplaylists
    special://profile/playlists
    special://videoplaylists
    addons://sources
    upnp://
    plugin://

In which case virtualpath://upnproot/ would be the root. So perhaps the intent is that the first IF finds the directory and sets it as such. The second IF should be testing IF it is in fact the root and not some subdirectory, and set it as such. So perhaps the intent was:

        if (path.StartsWith("virtualpath://upnproot")) {
            path.TrimRight("/");
            item->m_bIsFolder =  true;
            if (path == "virtualpath://upnproot")) {

In the case of virtualpath://upnproot/sub1/item.txt it would hit the first IF, the path would be found as virtualpath://upnproot/sub1 and get flagged as a folder. The second IF would be false as it is not the root.

In the case of virtualpath://upnproot both IF blocks would be true and it would be set appropriately.

Comment (smf007) [reply xbmc/network/upnp/UPnPServer.cpp:278]: Further down there is also something wrong.

    if (object) {
        // remap Root virtualpath://upnproot/ to id "0"
        if (object->m_ObjectID == "virtualpath://upnproot/")
            object->m_ObjectID = "0";
        // remap Parent Root virtualpath://upnproot/ to id "0"
        if (object->m_ParentID == "virtualpath://upnproot/")
            object->m_ParentID = "0";
    }

Comment (enen92) [reply xbmc/network/upnp/UPnPServer.cpp:278]: Not really, this last block checks Object_ID and Parent_ID, they refer to different properties. If any of them is `"virtualpath://upnproot/"` kodi needs to remap it to "0". The first request any client does is usually request Object Id "0":

image

If we would answer this with `<container id="virtualpath://upnproot/"` instead of `<container id="0"` that would be invalid from the client perspective.

Comment (enen92) [reply xbmc/network/upnp/UPnPServer.cpp:278]: > virtualpath://

None of the items you point out is a virtualpath:// apart from the first one. We have some old references in the code though:
image

This might be completely broken by now...I doubt we can return any valid data. So I think we're mostly on the same line of though here. First if checks for "virtualpath://" generically (not upnproot) and sets the isFolder property. The nested if checks explicitly for `virtualpath://upnproot`.
But I guess only @Montellese might know for sure, if he still remembers ofc :)

Comment (smf007) [reply xbmc/network/upnp/UPnPServer.cpp:278]: > Not really, this last block checks Object_ID and Parent_ID, they refer to different properties. If any of them is `"virtualpath://upnproot/"` kodi needs to remap it to "0". The first request any client does is usually request Object Id "0":
> 
> image
> 
> If we would answer this with `<container id="virtualpath://upnproot/" parentID=...` instead of `<container id="0" parentID=...` that would be invalid from the client perspective.

Ah, sorry, completely missed noticing it being Object vs Parent.

**Comment by enen92** [comment]
Note: Merging by the end of the week unless someone objects

File: xbmc/network/upnp/UPnPServer.cpp (hunk 1 above)
Comment (Montellese) [reply xbmc/network/upnp/UPnPServer.cpp:278]: TBH I don't remember. IIRC the `ObjectID`s are used by UPnP clients which provide fixed root elements like "Video", "Music", "Pictures" etc. IIRC we used to map these onto special paths like `virtualpath://upnpvieo` or something like that. But I don't remember if this was removed.

I also checked the UPnP ContentDirectory specification and it only mentions that `ObjectID == 0` is reserved for root.

Comment (Montellese) [reply xbmc/network/upnp/UPnPServer.cpp:278]: OK I tracked the changes to 370df02d29596b90b57ebba30112353cc363c7f7 and that was one or two years before my time so no wonder I don't remember ;-)

Comment (enen92) [reply xbmc/network/upnp/UPnPServer.cpp:278]: nice one, goes in line with my thoughts. I'll fix the if condition later as those virtual paths no longer apply, will take that opportunity to apply the clang-format changes too since the methods are wrongly indented (and result on a huge diff).
Thanks!
