### PR TITLE
changed: Have filecache retry instead of abort with fatal errors

### LINKED ISSUE #19175: Hang up when playing movies with google drive
Good afternoon, I'm having problems with the matrix rc 19.0 RC1 version. When playing a video file from the google drive addon the movie gets to play but stops in the first second. In the previous version, (leia) works without problems but it is not compatible with hdr10 and the colors are dull and the tone very dark. I am sending you the log files and screenshots. Please, I would appreciate some solution to solve this failure.

Log kodi Matrix -----https://1drv.ms/u/s!AkEEvAcFQvuln5dAivFQMtLwDHl7Zg?e=bHuQVG
Screenshoot movie 4k-hdr10 kodi Leia ----- https://1drv.ms/u/s!AkEEvAcFQvuln5dC84yt0_VuBmstyA?e=0wSgWQ

Log Kodi Leai ------https://1drv.ms/u/s!AkEEvAcFQvuln5dDjup-pJiaflatJQ?e=flHIJF

### LINKED ISSUE #19429: Kodi on Android TV aborts playback from NAS
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi on Android TV aborts playback from a Qnap NAS.

 I have tried both SMB and NFS(currently running NFS). It goes back to the normal screen as if I had hit "Stop". On some occasions, it freezes video while continuing audio for 10+ seconds, and then fast forwards video to catch up with audio, but that's rarer, and the log I'm attaching is from a clean start up to a playback abort and aplication manual exit(so doesn't include the latter described symptom).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Normal playback until the end of the video.

## Actual Behavior

Unexpected playback abort

### To Reproduce

1. Start payback of video from NFS or SMB network share on NAS
2. Video playback aborts wihtout quitting Kodi(back to the normal playbakc stopped view)
3.

### Debuglog

The debuglog can be found here:

https://pastebin.com/tca4zJdj

The culprit seems to be at line 368, but I cannot find relevant info.

---
**UPDATE**
<details>
  <summary>I've switched to back to SMB, and now I'm getting this:</summary>

```
2021-03-25 14:12:29.558 T:5167     INFO <general>: Loading skin file: VideoFullScreen.xml, load type: KEEP_IN_MEMORY
2021-03-25 14:12:59.443 T:5240     INFO <general>: VideoInfoScanner: Finished scan. Scanning for video info took 00:40
2021-03-25 14:20:32.106 T:5263    ERROR <general>: Read - Error( -1, 110, Connection timed out )
2021-03-25 14:22:37.324 T:5256     INFO <general>: Process - eof reading from demuxer
2021-03-25 14:22:37.324 T:5256     INFO <general>: CVideoPlayer::OnExit()
2021-03-25 14:22:37.324 T:5256     INFO <general>: VideoPlayer: eof, waiting for queues to empty
2021-03-25 14:22:37.325 T:5256     INFO <general>: Closing stream player 1
2021-03-25 14:22:37.325 T:5256     INFO <general>: CDVDMessageQueue(audio)::WaitUntilEmpty
2021-03-25 14:22:37.325 T:5256     INFO <general>: Waiting for audio thread to exit
2021-03-25 14:22:37.325 T:5286    ERROR <general>: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2021-03-25 14:22:37.325 T:5286     INFO <general>: thread end: CVideoPlayerAudio::OnExit()
2021-03-25 14:22:37.326 T:5256     INFO <general>: Closing audio device
2021-03-25 14:22:37.426 T:5256     INFO <general>: Deleting audio codec
2021-03-25 14:22:37.426 T:5256     INFO <general>: Closing stream player 2
2021-03-25 14:22:37.426 T:5256     INFO <general>: CDVDMessageQueue(video)::WaitUntilEmpty
2021-03-25 14:22:37.479 T:5256     INFO <general>: waiting for video thread to exit
2021-03-25 14:22:37.479 T:5283    ERROR <general>: Got MSGQ_ABORT or MSGO_IS_ERROR return true
2021-03-25 14:22:37.479 T:5283     INFO <general>: thread end: video_thread
2021-03-25 14:22:37.480 T:5256     INFO <general>: deleting video codec
2021-03-25 14:22:37.592 T:5256     INFO <general>: Closing stream player 3
```
</details>

I'm guessing that `ERROR <general>: Read - Error( -1, 110, Connection timed out )` for SMB is analogous to `ERROR <general>: Read - Error( -4, read call failed with "Command was cancelled" )` I was getting for NFS.

---

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Running Kodi 19.0 Matrix on Sony Andoid TV v9, but this had been occurring on Kodi 18 as well. The log is from the TV beeing connected through LAN, but I have also tried WiFi, and that seems to go more towards the freezing video behaviour(which is far harder to replicate, ergo no log file). I also have two Android 9 based Xiaomi Mi Box S devices, which both exibit no problems whatsoever connected by WiFI to the same network.

Also worth mentionig that this happens irrespective of the video codec, container, bitrate etc.

### Your Environment
Used Operating system:

 - [x ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi 19.0 Matrix on Sony Andoid TV v9, but this had been occurring on Kodi 18 as well.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by arnova**
The retry logic in filecache currently only retries with no data is returned from fs but some fs (eg NFS) seem to return a fatal error (-1) when it's unable to read data. This PR also enables retry for such errors. Fixes #19429

### CODE REVIEW

File: xbmc/filesystem/FileCache.cpp [hunk 1]
```diff
@@ -369,19 +369,17 @@ void CFileCache::Process()
...
     else if (iRead < 0) // Fatal error
     {
-      CLog::Log(LOGDEBUG, "{} - <{}> source read returned a fatal error! Will wait for buffer to empty", __FUNCTION__, m_sourcePath);
+      CLog::Log(LOGDEBUG, "{} - <{}> source read returned a fatal error! Will retry", __FUNCTION__, m_sourcePath);
 
-      m_pCache->EndOfInput();
-
-      while (m_pCache->WaitForData(0, 0) > 0)
+      // Wait a bit:
+      if (m_seekEvent.WaitMSec(5000))
```
Comment (bugwelle) [inline xbmc/filesystem/FileCache.cpp:375]: Hi, out of curiosity: Why 5 seconds? Did it still fail with a lower value? :-)

Comment (arnova) [reply xbmc/filesystem/FileCache.cpp:375]: Dunno, I just c&p-ed it from the part above. It's a long time ago I implemented that part so I can't recall why I chose 5s.

**Comment by wsnipex** [comment]
Yes, NFS does return negative values in same cases, so this PR looks sensible.

In the Read case, it is supposed to return the number of bytes read:

```
numberOfBytesRead = nfs_read(m_pNfsContext, m_pFileHandle, uiBufSize, (char *)lpBuf);
if (numberOfBytesRead < 0)
    CLog::Log(LOGERROR, "%s - Error( %" PRId64", %s )", __FUNCTION__, (int64_t)numberOfBytesRead, nfs_get_error(m_pNfsContext));

  return numberOfBytesRead;

```
Very curious how this becomes a negative number...

btw, libnfs supports retry, which we could use:`
EXTERN void nfs_set_autoreconnect(struct nfs_context *nfs, int num_retries);`

**Comment by arnova** [comment]
> btw, libnfs supports retry, which we could use:` EXTERN void nfs_set_autoreconnect(struct nfs_context *nfs, int num_retries);`

Oh great, then we can also make it work like we already do with smb.

File: xbmc/filesystem/FileCache.cpp (hunk 1 above)
Comment (arnova) [reply xbmc/filesystem/FileCache.cpp:375]: I think I chose 5s to prevent "hammering" the underlying filesystem, but now that I think of it, this may be a little long for some scenarios. @wsnipex : What's your idea about this? Perhaps lowering it to 1 or 2 seconds?

Comment (wsnipex) [reply xbmc/filesystem/FileCache.cpp:375]: 1 sec sounds good to me

Comment (arnova) [reply xbmc/filesystem/FileCache.cpp]: I opted for the comprise after all: 2 seconds....

**Review by wsnipex — APPROVED** [review]

**Comment by arnova** [comment]
@wsnipex : Could you please review it again? I've merged/cleaned up the retry code.

**Comment by wsnipex** [comment]
lgtm

**Comment by arnova** [comment]
Build error unrelated
