### PR TITLE
GLES: enable HQ scalers (8/10/16-bit) for feature parity with GL renderer

### LINKED ISSUE #25801: Kodi crashes when both tone mapping and optimized scaling shaders are used simultaneously.
### Describe the bug
When playing back a HDR video, if the optimized versions of either Spline36 or Lanczos3 are selected and any of the HDR tone mapping curves is selected too, Kodi crashes immediately.

## Expected Behavior
Kodi should play the video with the defined settings, without crashing.

## Actual Behavior
Kodi crashes immediately.

## Possible Fix
This is likely related to #24611.

### To Reproduce
1. Make sure your screen doesn't support HDR, or that HDR is disabled.
2. Select either Spline36 or Lanczos3 optimized.
3. Select one of the tone mapping curves.
4. Play a HDR video.

### Debuglog
https://paste.kodi.tv/gaqatekoxo.kodi (Pentium N4200-based machine)

### Screenshots
N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 13 daily build from the [11th October](https://test.libreelec.tv/13.0/Generic/Generic/LibreELEC-Generic.x86_64-13.0-nightly-20241011-f5bd1a2.img.gz).
 - Kodi version: Kodi master ed8f18b779b28ee62e5e1154e839479680612700.

This has been verified on both Apollo Lake (Pentium N4200, gen. 9 graphics) and Alder Lake (Core N100, Xe-LP gen. 12.2 graphics) systems.

### PR DESCRIPTION
**Pull request by reardonia**
## Description
(UPDATED)

Add configurable FBO intermediate precision (8/10/16-bit) for GLES HQ scalers. Fix crash when FAST scalers are combined with HDR tone mapping (#25801). Fix several bugs in both GL and GLES renderers.

NOTE: GLES has had working HQ scalers (multi-pass FBO with ConvolutionFilterShader) since #12474 (2017). This PR does NOT enable HQ scalers from scratch -- it adds higher-precision FBO intermediates for parity with GL, fixes bugs, and improves "FAST" (aka "Optimized") scaler routing.

Bug fixes (critical)

- Fix #25801 -- FAST scaler + tone mapping crash: YUV2RGBFilterShader (from #24611) included GL-only shader files (gl_tonemap.glsl, gl_output.glsl) instead of GLES equivalent (gles_tonemap.frag). When tone mapping was active, the shader failed to compile (inversePQ() and hable() undefined), causing a null dereference crash.
- Fix LoadShaders double initialization: Filter shader was created regardless of RQ_SINGLEPASS. In multi-pass mode (FAST on < GLES 3.1), the wrong shader type was used for the YUV pass. Also added fallback to YUV2RGBProgressiveShader on compile failure.

Bug fixes (other)

- Configure() not initializing m_scalingMethod -- stale value persists across videos (both GL and GLES)
- GL Update() resetting m_scalingMethodGui to -1 on every call, causing needless shader/FBO recreation on window resize, pause/resume
- Viewport 0x0 guard in UpdateVideoFilter -- ValidateRenderTarget calls it before display resolution is established
- DefaultFilterShader fallback for GLES -- prevents null m_pVideoFilterShader after scaler initialization failure

Features

- Configurable FBO intermediate precision (8/10/16-bit) via hqscalerprecision setting, now exposed on GLES builds (was GL-only). GL_RGB10_A2 for 10-bit, GL_RGBA16F for 16-bit, with fallback to GL_RGBA
- AUTO scaling method on GLES (resolves to Lanczos3 Fast for SD upscaling, otherwise Linear)
- FAST scalers available on all GLES versions: single-pass with textureGather on GLES 3.1+, multi-pass FBO fallback on lower versions

Type correctness / cosmetic
- m_reloadShaders int->bool across both renderers
- Typo fix in GL error log ("defauilt" -> "default")

Changes settings.xml to allow hqscalerprecision on HAS_GLES builds.

NOTE: this applies to 4:2:0 video only.  4:2:2 will come in future PR.

NOTE: DRMPRIMEGLES support will come in future PR.

## Motivation and context
Feature parity for GLES renderers. Users on GBM/GLES platforms (RPi, RK3588, x86 with GLES) had no access to HQ scalers (8/10/16-bit) that GL users have had for years. This is part of a broader effort to reach GL/GLES feature parity.

## How has this been tested?
Tested on Intel NUC (i3-8109U) with mesa iris GLES 3.1:
- All HQ scaler methods verified working (Lanczos2/3, Spline36, cubics)
- FAST variants use single-pass on GLES 3.1+, multi-pass FBO on lower versions
- FBO precision 8/10/16-bit verified
- Fallback to GL_RGBA when higher precision not available
- No regressions on YUV420P or NV12 software decode

## What is the effect on users?
Brings high-quality scaling to GLES platforms; better scaled video.  Potentially allows Libreelec move to GLES everywhere not just ARM SoC.

## Screenshots (if appropriate):
n/a

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by reardonia** [comment]
cc @lrusak @chewitt @smp79

**Comment by reardonia** [comment]
> ### Impact
> [MAJOR] xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp (718): Missing GL_UNSIGNED_BYTE parameter causes FBO creation to use wrong signature The fallback CreateAndBindToTexture call at line 718 omits the type parameter, which means it will call a different overload than intended. The first attempt at line 711 passes `m_intermediateFormat, m_intermediateType, GL_NEAREST` (5 params), but the fallback at line 718 only passes `GL_RGBA` (4 params). This causes the call to use a different function signature, potentially with undefined behavior or incorrect texture format.
> 
> [MAJOR] xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp (819): UpdateVideoFilter called recursively from LoadShaders creates potential infinite loop At line 819, when the YUV2RGBFilterShader successfully compiles in LoadShaders(), the code calls UpdateVideoFilter(). However, UpdateVideoFilter() is what originally called LoadShaders() via the m_reloadShaders flag. This creates a call chain: UpdateVideoFilter() → sets m_reloadShaders → LoadShaders() → UpdateVideoFilter(). While m_reloadShaders is set to false at line 782, this recursive call pattern is fragile and could cause issues if UpdateVideoFilter() sets m_reloadShaders again based on viewport or scaling method changes.
> 
> [MAJOR] xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp (736, 771): Memory leak when shader initialization fails When ConvolutionFilterShader creation fails at line 737, the code breaks out of the switch at line 740, falling through to the cleanup section at line 767-775. However, m_pVideoFilterShader was already allocated at line 736 with `new ConvolutionFilterShader()`. The cleanup section only deletes m_pVideoFilterShader if it exists (line 769), but if CompileAndLink() fails, the shader object is already allocated but not cleaned up before the DefaultFilterShader is created at line 771, causing a memory leak.
> 
> ## Suggestions
> * Optional: Consider adding debug logging for the FBO format fallback path to help diagnose precision issues on different GLES implementations
> * Future consideration: The TODO comments mention porting non-linear stretch and CMS to GLES - tracking these as follow-up work would help maintain feature parity goals
> 
> ## Verdict
> 🔴 **Address before merging** -- 3 blocking issue(s) found
> 

All three issues are false positives:

  1. CreateAndBindToTexture has default parameter type=GL_UNSIGNED_BYTE -- 4-param call is correct. The fallback call at line 720-721 uses the default -- which is what we want for GL_RGBA fallback
  2. m_reloadShaders is cleared at line 785 before UpdateVideoFilter is called -- no recursion possible. Same pattern as
HQ Scaler in GL.
  3. Failed ConvolutionFilterShader is deleted at line 764-767 before DefaultFilterShader is created -- no leak

**Comment by reardonia** [comment]
Anyone: is there a reason that scalingmethod is not a visible GUI setting globally?  I converted this to draft because this confuses me. There is no way to actually set a global "High Quality" scaling method other than via xml settings. Yet there is `hqscalers` which thresholds and should unlock such a scaler.

**Review by neo1973 — APPROVED** [review]
I can confirm that the crash has been fixed.

I don't know much about GL(ES), but the description and code make sense to a novice like me so I'm OK with it 🙂

File: xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGL.cpp [hunk 1]
```diff
@@ -772,18 +774,27 @@ void CLinuxRendererGL::UpdateVideoFilter()
...
-  else
-    m_reloadShaders = 1;
+
+  // Viewport-only change doesn't need shader reload -- only method/stretch/CMS changes do
+  if (m_scalingMethod != m_videoSettings.m_ScalingMethod || nonLinStretchChanged || cmsChanged)
+    m_reloadShaders = true;
 
   // recompile YUV shader when non-linear stretch is turned on/off
   // or when it's on and the scaling method changed
   if (m_nonLinStretch || nonLinStretchChanged)
```
Comment (popcornmix) [inline xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGL.cpp]: The `nonLinStretchChanged` check looks redundant as the preceding conditional would have set `m_reloadShaders` if it were true. (Combining the two conditionals is an also an option).

Comment (reardonia) [reply xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGL.cpp]: good catch, thanks

9df7389
