### PR TITLE
Pipewire: Catch exceptions in CPipewire::Create()

### LINKED ISSUE #23225: Kodi dies due to strict pipewire requirements
### Describe the bug
Here is a clear and concise description of what the problem is:

Without the full blown pipewire package, kodi cannot start ending in a core dump.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should start without pipewire

## Actual Behavior

kodi cannot start ending in a core dump.

### To Reproduce

1. Build [kodi-git](https://aur.archlinux.org/packages/kodi-git)
2. Start `kodi-gbm.service` from [kodi-standalone-service](https://aur.archlinux.org/packages/kodi-standalone-service)

### Debuglog

The debug log generated is empty since kodi coredumps before it can initialize and generate one.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I did open a ticket against Arch's libpipewire and pipewire packages calling out that some shared objects as well as a config file are needed.  See [here](https://bugs.archlinux.org/task/78337).  One of the packagers/developers feels that kodi should be made more tolerant of pipewire failing to initialize which is the driving force behind me opening this ticket.

Journalctl output without pipewire installed:
```
kodi-standalone[4025]: [D] pw.context [pipewire.c:229 load_spa_handle()] load lib:'support/libspa-support' factory-name:'support.log'
kodi-standalone[4025]: [D] pw.context [pipewire.c:113 open_plugin()] can't load /usr/lib/spa-0.2/support/libspa-support.so: /usr/lib/spa-0.2/support/libspa-support.so: cannot open shared object file: No such file or directory
kodi-standalone[4025]: [D] pw.context [pipewire.c:229 load_spa_handle()] load lib:'support/libspa-journal' factory-name:'support.log'
kodi-standalone[4025]: [D] pw.context [pipewire.c:113 open_plugin()] can't load /usr/lib/spa-0.2/support/libspa-journal.so: /usr/lib/spa-0.2/support/libspa-journal.so: cannot open shared object file: No such file or directory
kodi-standalone[4025]: [D] pw.context [pipewire.c:229 load_spa_handle()] load lib:'support/libspa-support' factory-name:'support.cpu'
kodi-standalone[4025]: [D] pw.context [pipewire.c:113 open_plugin()] can't load /usr/lib/spa-0.2/support/libspa-support.so: /usr/lib/spa-0.2/support/libspa-support.so: cannot open shared object file: No such file or directory
kodi-standalone[4025]: [I] pw.context [pipewire.c:647 pw_init()] version 0.3.70
kodi-standalone[4025]: [D] pw.thread-loop [thread-loop.c:145 loop_new()] 0x55874c5fc690: new name:pipewire
kodi-standalone[4025]: [D] pw.context [pipewire.c:229 load_spa_handle()] load lib:'support/libspa-support' factory-name:'support.system'
kodi-standalone[4025]: [D] pw.context [pipewire.c:113 open_plugin()] can't load /usr/lib/spa-0.2/support/libspa-support.so: /usr/lib/spa-0.2/support/libspa-support.so: cannot open shared object file: No such file or directory
kodi-standalone[4025]: [E] pw.loop [loop.c:67 pw_loop_new()] 0x55874c5e7980: can't make support.system handle: No such file or directory
kodi-standalone[4025]: terminate called after throwing an instance of 'std::runtime_error'
kodi-standalone[4025]: what(): CPipewireThreadLoop: failed to create main loop
systemd[1]: Started Process Core Dump (PID 4029/UID 0).
systemd-coredump[4030]: [🡕] Process 4025 (kodi.bin) of user 981 dumped core.

Stack trace of thread 4025:
#0 0x00007faafb2618ec n/a (libc.so.6 + 0x878ec)
#1 0x00007faafb212ea8 raise (libc.so.6 + 0x38ea8)
#2 0x00007faafb1fc53d abort (libc.so.6 + 0x2253d)
#3 0x00007faafac9a833 _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9a833)
#4 0x00007faafaca6d0c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xa6d0c)
#5 0x00007faafaca6d79 _ZSt9terminatev (libstdc++.so.6 + 0xa6d79)
#6 0x00007faafaca6fdd __cxa_throw (libstdc++.so.6 + 0xa6fdd)
#7 0x0000558748bfdd6b n/a (kodi.bin + 0x98fd6b)
#8 0x000055874a1994c1 _ZN4KODI8PIPEWIRE9CPipewire5StartEv (kodi.bin + 0x1f2b4c1)
#9 0x000055874a199b28 _ZN4KODI8PIPEWIRE9CPipewire6CreateEv (kodi.bin + 0x1f2bb28)
#10 0x000055874a192dab _ZN2AE4SINK15CAESinkPipewire8RegisterEv (kodi.bin + 0x1f24dab)
#11 0x0000558748fcdfb6 _ZN14CPlatformLinux12InitStageOneEv (kodi.bin + 0xd5ffb6)
#12 0x000055874998ab82 _ZN15CServiceManager12InitStageOneEv (kodi.bin + 0x171cb82)
#13 0x0000558749728cfd _ZN12CApplication6CreateEv (kodi.bin + 0x14bacfd)
#14 0x00005587494dcdf8 XBMC_Run (kodi.bin + 0x126edf8)
#15 0x0000558748ca41d7 main (kodi.bin + 0xa361d7)
#16 0x00007faafb1fd790 n/a (libc.so.6 + 0x23790)
#17 0x00007faafb1fd84a __libc_start_main (libc.so.6 + 0x2384a)
#18 0x0000558748d16f35 _start (kodi.bin + 0xaa8f35)

Stack trace of thread 4028:
#0 0x00007faafb25c766 n/a (libc.so.6 + 0x82766)
#1 0x00007faafb25ef90 pthread_cond_wait (libc.so.6 + 0x84f90)
#2 0x00007faafaccfe51 __gthread_cond_wait (libstdc++.so.6 + 0xcfe51)
#3 0x0000558749fa1251 _ZN12ANNOUNCEMENT20CAnnouncementManager7ProcessEv (kodi.bin + 0x1d33251)
#4 0x000055874948b6e5 _ZN7CThread6ActionEv (kodi.bin + 0x121d6e5)
#5 0x000055874948c4b0 n/a (kodi.bin + 0x121e4b0)
#6 0x00007faafacd72c3 execute_native_thread_routine (libstdc++.so.6 + 0xd72c3)
#7 0x00007faafb25fbb5 n/a (libc.so.6 + 0x85bb5)
#8 0x00007faafb2e1d90 n/a (libc.so.6 + 0x107d90)
ELF object binary architecture: AMD x86-64
systemd[1]: [systemd-coredump@3-4029-0.servi](mailto:systemd-coredump@3-4029-0.servi)ce: Deactivated successfully.
kodi-standalone[4020]: /usr/bin/kodi: line 181: 4025 Aborted (core dumped) ${KODI_BINARY} $SAVED_ARGS
kodi-standalone[4020]: Crash report available at /var/lib/kodi/kodi_crashlog-20230430_070427.log
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux (up-to-date)
 - Kodi version: Latest git

### PR DESCRIPTION
**Pull request by neo1973**
## Description
`CPlatformLinux::InitStageOne()` doesn't expect `OPTIONALS::*Register()` methods to throw so exceptions aren't handled, they bubble up the stack and crash the application.

## Motivation and context
An exception from `CAESinkPipewire::Register()` crashed Kodi in #23225 which isn't good behaviour even if the host system is setup in an expected way.

## How has this been tested?
Artificially create an exception in `CAESinkPipewire::Register()`. Kodi doesn't crash and instead initializes the pulseaudio interface.

## What is the effect on users?
Kodi doesn't crash maybe there even is sound.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp [hunk 1]
```diff
@@ -254,18 +254,25 @@ std::unique_ptr<PIPEWIRE::CPipewire> pipewire;
...
+    entry.enumerateFunc = CAESinkPipewire::EnumerateDevicesEx;
+    entry.cleanupFunc = CAESinkPipewire::Destroy;
+    AE::CAESinkFactory::RegisterSink(entry);
 
-  return true;
+    return true;
+  }
+  catch (const std::exception&)
+  {
+    return false;
```
Comment (enen92) [inline xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:274]: wouldn't it make sense to log the actual exception?

File: xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp [hunk 2]
```diff
@@ -254,18 +254,25 @@ std::unique_ptr<PIPEWIRE::CPipewire> pipewire;
 
 bool CAESinkPipewire::Register()
 {
-  pipewire = PIPEWIRE::CPipewire::Create();
-  if (!pipewire)
-    return false;
+  try
+  {
+    pipewire = PIPEWIRE::CPipewire::Create();
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:259]: We already have try/catch blocks in `PIPEWIRE::CPipewire::Create` It would be nice if we could just catch the exception in there.

**Review by lrusak — COMMENTED** [review]
I'm actually fine throwing if we hit undefined/unexpected behaviour. Many distros may only build Kodi with one audio sink anyways so no matter what they may have broken audio if the pipewire sink cannot initialize.

File: xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp (hunk 1 above)
Comment (neo1973) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp]: I added logging, but unfortunately it doesn't show up in the log because the logger is not yet initialized. But it helps when logging directly to the console :slightly_smiling_face:

File: xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp (hunk 2 above)
Comment (neo1973) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp]: Moved the exception handling to `CPipewire::Create`.
