### PR TITLE
[PVR] Fix 'any channel' timer rules children not displayed.

### LINKED ISSUE #15710: PVR Radio timer rules for any channel appear in TV Timer Rules
### Describe the bug
Here is a clear and concise description of what the problem is:

PVR Radio timer rules created for any channel appear in TV Timer Rules instead of Radio.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

PVR Radio timer rules created for any channel appear in Radio Timer Rules.

## Actual Behavior

PVR Radio timer rules created for any channel appear in TV Timer Rules instead of Radio.

## Possible Fix

I assume this is because timers require a similar channel type field to recordings. This could even be defaulted to the correct type in the add timer dialog.

### To Reproduce

1. Create a radio epg auto timer for any channel using Enigma2 addon 
2. Go to timer rules in Radio and it will not be displayed 
3. Go to timer rules in TV and it will be displayed

### Debuglog

The debuglog can be found here:

I don’t believe a debug log is required here. Happy to provide if it is.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ x] OSX
 - [ ] Raspberry-Pi
 - [ x] Windows
 - [ ] Windows UWP

 - Operating system version/name: OSX, Librelec x86, Windows
 - Kodi version: 18.2RC

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #15710 

@Jalle19 Got some time for a short review? Using Window Manager to determine the context for the status string is not the nicest solution, but without new GUI labels the only way (I found).

@phunkyfish could you runtime-test? I did and it seems to work well.

### CODE REVIEW

File: xbmc/pvr/timers/PVRTimerInfoTag.cpp [hunk 1]
```diff
@@ -189,10 +189,14 @@ bool CPVRTimerInfoTag::operator ==(const CPVRTimerInfoTag& right) const
...
-          m_bHasChildRecording  == right.m_bHasChildRecording &&
-          m_bHasChildErrors     == right.m_bHasChildErrors);
+          m_iActiveTVChildTimers == right.m_iActiveTVChildTimers &&
+          m_iActiveRadioChildTimers  == right.m_iActiveRadioChildTimers &&
+          m_bHasTVChildConflictNOK== right.m_bHasTVChildConflictNOK &&
+          m_bHasRadioChildConflictNOK== right.m_bHasRadioChildConflictNOK &&
+          m_bHasTVChildRecording  == right.m_bHasTVChildRecording &&
+          m_bHasRadioChildRecording  == right.m_bHasRadioChildRecording &&
+          m_bHasTVChildErrors     == right.m_bHasTVChildErrors &&
+          m_bHasRadioChildErrors     == right.m_bHasRadioChildErrors);
```
Comment (MartijnKaijser) [inline xbmc/pvr/timers/PVRTimerInfoTag.cpp]: might as well remove the extra spaces?

**Comment by phunkyfish** [comment]
Ya, will runtime time

File: xbmc/pvr/timers/PVRTimerInfoTag.cpp (hunk 1 above)
Comment (ksooo) [reply xbmc/pvr/timers/PVRTimerInfoTag.cpp]: sure

**Comment by phunkyfish** [comment]
Works as expected!

**Comment by phunkyfish** [comment]
I have not been able to see the timers under the timer rule. This is most likely my addon code, need a bit more time to figure out what’s happening.

**Comment by ksooo** [comment]
Works with pvr.hts.

**Comment by phunkyfish** [comment]
So not my code, or yours ;)

Happened upon an obscue Enigma2 bug.

Everything works as expected on pvr.vuplus

**Comment by ksooo** [comment]
So, good to go in?

**Comment by phunkyfish** [comment]
Correct, thanks for the quick turnaround.
