### PR TITLE
[UPnP] Use base64 encoded values for objectIds

### LINKED ISSUE #22828: Samsung Smart TV (from 2017) can see kodi-20.3-nexus DLNA, but wont see any content.
## Bug report or rather regression?
Samsung Smart TV sees DLNA on kodi-20.3 but can not retrieve any lists (content).
### Describe the bug
Here is a clear and concise description of what the problem is:
While other devices can see and stream from kodis DLNA, the Samsung TV does not retrieve any content lists (latest Firmware is from 2022).
The same Samsung TV however can see and stream content from a miniDLNA server, as well as from kodi-19.5. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The TV should receive DLNA media and in return be able to stream them.

## Actual Behavior

The TV sees the DLNA-server but wont get any media entries (content)

## Possible Fix
It seems legacy folders have been dropped.
So the solution would seem to reenable legacy folders.

The problems seems to affect other OSes too. See: 
[on reddit](https://www.reddit.com/r/kodi/comments/113qeki/updated_to_kodi_20_and_now_my_samsung_tv_shows_no/)

Somewhere between kodi-19.5 and kodi-20.3 has been changes made to the DLNA server, which in turn made streaming impossible.

### Debuglog
at:
http://sprunge.us/HexijV

with upnp component and libcurl enabled..
```

### Your Environment
Used Operating system:
Kodi-20.3 runs on self built LibreELEC devel-20230206105220-6783302 (RPi4.arm).
Samsung Smart TV from 2017 (probably Tizen)
Kodi-19.5 runs on a Gentoo machine, same for minidlna-1.3.2-r1

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

### PR DESCRIPTION
**Pull request by enen92**
## Description
Currently Kodi uses vfs paths as object ids in UPnP. This is convenient from Kodi side (easier to read and to interpret) but causes all sort of issues for external clients when trying to list childrens or browse the metadata associated to those virtual paths. We have all sorts of virtual uris, some containing query arguments, repetition of query arguments on the same string, sort methods (which are then interpreted as json), etc. This is not compatible with DIDL (Digital Item Declaration Language) leading to most of the UPnP directories to show empty and/or without metadata in external clients.
Hence, for retaining the ease of use from our side, this PR suggests that we move from plain vfs urls to the resulting base64 encoded strings for the vfs uris which is safe to use. Easy to convert when debugging and are also logged to the kodi log along with the encoded string:

```
2023-02-26 10:47:12.157 T:2429179   debug <CUPnPServer[Kodi (MacBook-Air.local)]>: Returning UPnP response with 2 items out of 2 total matches
2023-02-26 10:47:12.654 T:2429183    info <CUPnPServer[Kodi (MacBook-Air.local)]>: Received UPnP Browse Metadata request for encoded object 'dmlkZW9kYjovL3R2c2hvd3MvdGl0bGVzLzEvMS8xP3NlYXNvbj0xJnR2c2hvd2lkPTEmeHNwPSU3YiUyMm9yZGVyJTIyJTNhJTdiJTIyZGlyZWN0aW9uJTIyJTNhJTIyYXNjZW5kaW5nJTIyJTJjJTIyaWdub3JlZm9sZGVycyUyMiUzYTAlMmMlMjJtZXRob2QlMjIlM2ElMjJzb3J0dGl0bGUlMjIlN2QlMmMlMjJ0eXBlJTIyJTNhJTIydHZzaG93cyUyMiU3ZA==' (plain value: 'videodb://tvshows/titles/1/1/1?season=1&tvshowid=1&xsp=%7b%22order%22%3a%7b%22direction%22%3a%22ascending%22%2c%22ignorefolders%22%3a0%2c%22method%22%3a%22sorttitle%22%7d%2c%22type%22%3a%22tvshows%22%7d')
2023-02-26 10:47:12.654 T:2429183   debug <CUPnPServer[Kodi (MacBook-Air.local)]>: Translated id to 'videodb://tvshows/titles/1/1/1?season=1&tvshowid=1&xsp=%7b%22order%22%3a%7b%22direction%22%3a%22ascending%22%2c%22ignorefolders%22%3a0%2c%22method%22%3a%22sorttitle%22%7d%2c%22type%22%3a%22tvshows%22%7d'
```

Depends (ideally) on https://github.com/xbmc/xbmc/pull/22858.

~~Plan to backport after it has been in master for a bit of time (maybe 20.2).~~ (will not be backported)
I wont be adjusting clang-format for now, those files are totally broken. Plan to do it in bulk after the two PRs are in.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/22828

## How has this been tested?
Tested with the official client of my philips tv and kodi/server on mac. Original issue reporter (@misanthropos) reported similar results on the official Tizen client for Samsung TV and librelec. See the issue thread for additional details.

## What is the effect on users?
Make UPnP more widely compatible with external clients

## Screenshots (if appropriate):

**Before:**
IMG20230226103119
IMG20230226103200

**After:**

IMG20230226102852

IMG20230226102941

### CODE REVIEW

**Comment by Tolriq** [comment]
That will have side effects on some clients that may require the id to match things and possibly break upnp search.

Yatse use UPnP action browse with ObjectID set to the file provided by JSON API, this will most probably not work anymore and prevent mapping media from JSON to UPnP (Necessary to stream for example to device that do not support basic auth and Kodi webserver requiring authentification unlike UPnP).

**Comment by enen92** [comment]
> That will have side effects on some clients that may require the id to match things and possibly break upnp search.
> 
> Yatse use UPnP action browse with ObjectID set to the file provided by JSON API, this will most probably not work anymore and prevent mapping media from JSON to UPnP (Necessary to stream for example to device that do not support basic auth and Kodi webserver requiring authentification unlike UPnP).

I'd be interested into looking into possible upnp search regressions. Any idea how I'd be able to test that?

Regarding your second point that's literally a hack were you/yatse expect to use information that is internal to the inner workings of the application. In that case I guess you can continue to do the same as long as you decode/encode the path before sending to the upnp target...

**Comment by Tolriq** [comment]
The ids being well known, stable and used as they are is done since for ever, so maybe it's an hack, but after many discussions over the years it was the only way. And it's used by many not just Yatse.

Wonder what happens too for Kodi that are UPnP servers for others Kodi, with a change in the Ids, that will also probably have impacts, @Montellese will know.

For searches, no idea I don't use, but there's many UPnP test tools.

And since UPnP is not versioned this is not that simple to encode, since there's no way to properly know when it's needed or not, it's not like JSON that have proper API version to know what to do when.

So this is a major breaking change, that will have impacts on quite a few externals things. this is not something that should be backported just like it's nothing. Changing this for 21 is something, changing this on an future .X release is really something else.

**Comment by enen92** [comment]
> The ids being well known, stable and used as they are is done since for ever, so maybe it's an hack, but after many discussions over the years it was the only way. And it's used by many not just Yatse.

Not maybe, it's an hack. If the id's we're using would be stable we'd not for sure be here :)
This is the root cause of more than one application not showing upnp directory contents. minidlna server, for example, does something similar with object ids (just some random ascii string mapped internally to the actual path).

> 
> Wonder what happens too for Kodi that are UPnP servers for others Kodi, with a change in the Ids, that will also probably have impacts, @Montellese will know.
> 

Nothing, Kodi as a client uses whatever the server gives it, being plain vfs paths or encoded paths.
Tested using this as a server and plain nexus as client; or this as a server and this as a client.

> For searches, no idea I don't use, but there's many UPnP test tools.
> 

I think this indeed got broken. Marking as don't merge for now until I test (and fix it) - my tv doesn't send the actual content of the search string so I need to figure out some other way to validate this end-to-end.


> And since UPnP is not versioned this is not that simple to encode, since there's no way to properly know when it's needed or not, it's not like JSON that have proper API version to know what to do when.
> 
> So this is a major breaking change, that will have impacts on quite a few externals things. this is not something that should be backported just like it's nothing. Changing this for 21 is something, changing this on an future .X release is really something else.

I was unsure about backporting this in the first place - I am sensible to the argument that it might impact users that use applications that rely on those kind of heuristics like yatse. Doing this in some point release is likely not a good idea.

Note however that you won't be blocking/spamming this (just like my old playlist id PR) with hidden use-cases that take advantage on principles that are clearly wrong leaving official applications broken on the other hand.

**Comment by Tolriq** [comment]
> Not maybe, it's an hack. If the ids we're using would be stable we'd not for sure be here :)

The IDs are stable, fact. The fact that they may break UPnP standard is independent of that fact.
Since it's not officially advertised as stable you are free to change the fact, but it's still a fact until this change happens.

> Nothing, Kodi as a client uses whatever the server gives it, being plain vfs paths or encoded paths.

Not talking about client usage but about the sync system Montellese has built over UPnP .... But not sure this was actually finished and merged.


For the rest I'm not in the power of blocking anything, I expose facts what Kodi team does with them is no more my business since a long time, I've lost energy to fight on the users's behalf.

With that said I appreciate the consideration about the backport impacts.

**Comment by enen92** [comment]
> > Nothing, Kodi as a client uses whatever the server gives it, being plain vfs paths or encoded paths.
> 
> Not talking about client usage but about the sync system Montellese has built over UPnP .... But not sure this was actually finished and merged.
> 

That's not merged into master (nor even PRd) atm. Can for sure be fixed if somehow it breaks.

-------------

@misanthropos can you somehow test if upnp search works on some directory of your server when browsing using the TV? Even if it does (or does not) work, a pcap would be nice

**Comment by enen92** [comment]
Note: Merging by the end of the **month** unless someone objects

**Comment by misanthropos** [comment]
> Note: Merging by the end of the **month** unless someone objects

@enen92 sorry for not reporting back sooner. I believe there is no search function built in the Samsung TVs I own. At least I could not find such an entry.
However I found out, why e.g. Top 100 Albums would not display a single item (unrelated to UPnP). I had to upgrade mariadb (mysql) with mysql_upgrade.... after that, even these entries will appear in kodis DLNA. It is so much nicer to use kodis DLNA instead of e.g. minidlna just because of that.
So you have my full support merging this into master :-)

Cheers

**Comment by Montellese** [comment]
I'll try to take a look at this next week. Last time I invested a lot of effort in UPnP (which was quite a few years ago) there wasn't really any client which provided / used UPnP search. I've implemented a very basic version of it in my UPnP media import work but only to filter / search by media type.

**Comment by enen92** [comment]
Looking at the search method body this seems to have been implemented for Sonos and similar clients. My tv has a search function but seems not to be implemented it properly (it just requests a search with an empty payload on the root (0) object id).
Anyway I doubt it will cause regressions now (it'd on the first revision of the patch set). The client just provides a search expression targeting a specific object id (the one you're browsing) so as long as we can decode it from base64 the implementation is exactly the same as before since it was kodi serving the object id in the first place.

File: xbmc/network/upnp/UPnPInternal.cpp [hunk 1]
```diff
@@ -597,7 +598,7 @@ BuildObject(CFileItem&                    item,
 
         /* Get the number of children for this container */
         if (with_count && upnp_server) {
-            if (object->m_ObjectID.StartsWith("virtualpath://")) {
+            if (StringUtils::StartsWithNoCase(DecodeObjectId(object->m_ObjectID.GetChars()), "virtualpath://")) {
```
Comment (Montellese) [inline xbmc/network/upnp/UPnPInternal.cpp:601]: Can we introduce a temporary variable for the decoded objectID? It is difficult to read the way it is now.

File: xbmc/network/upnp/UPnPInternal.cpp [hunk 2]
```diff
@@ -1218,5 +1219,44 @@ std::shared_ptr<CFileItem> GetFileItem(const NPT_String& uri, const NPT_String&
...
+NPT_String DecodeObjectId(const std::string& id)
+{
+  if (id.empty())
+  {
+    CLog::LogF(LOGWARNING, "Failed to decode object id, provided object id is empty");
+    return {};
+  }
+  // we use integers in some special cases like virtualpath://upnproot or whenever clients with
+  // quirks expect to receive integer ids for some parent containers
+  if (StringUtils::IsInteger(id))
```
Comment (Montellese) [inline xbmc/network/upnp/UPnPInternal.cpp:1248]: Is it possible that the base64 encoded string is an integer? That might lead to misinterpretations here.

File: xbmc/network/upnp/UPnPInternal.cpp [hunk 3]
```diff
@@ -1218,5 +1219,44 @@ std::shared_ptr<CFileItem> GetFileItem(const NPT_String& uri, const NPT_String&
...
+  {
+    return id.c_str();
+  }
+  std::string decodedObjectId = Base64::Decode(id);
```
Comment (Montellese) [inline xbmc/network/upnp/UPnPInternal.cpp:1252]:
```suggestion
  const auto decodedObjectId = Base64::Decode(id);
```

File: xbmc/network/upnp/UPnPServer.cpp [hunk 4]
```diff
@@ -405,18 +405,18 @@ PLT_MediaObject* CUPnPServer::Build(const std::shared_ptr<CFileItem>& item,
...
-            object->m_ParentID = parent_id;
+            object->m_ParentID = EncodeObjectId(parent_id);
         }
     }
 
     if (object) {
         // remap Root virtualpath://upnproot/ to id "0"
-        if (object->m_ObjectID == "virtualpath://upnproot/")
-            object->m_ObjectID = "0";
+        if (StringUtils::EqualsNoCase(object->m_ObjectID, EncodeObjectId("virtualpath://upnproot/")))
```
Comment (Montellese) [inline xbmc/network/upnp/UPnPServer.cpp:414]: See comment above about readability.

File: xbmc/network/upnp/UPnPServer.cpp [hunk 5]
```diff
@@ -659,10 +660,10 @@ CUPnPServer::OnBrowseDirectChildren(PLT_ActionReference&          action,
                                     const PLT_HttpRequestContext& context)
 {
     CFileItemList items;
-    NPT_String parent_id = TranslateWMPObjectId(object_id, m_logger);
+    m_logger->info("Received Browse DirectChildren request for encoded object '{}' (plain value: '{}'), with sort criteria {}",
+                   object_id, DecodeObjectId(object_id).GetChars(), sort_criteria);
```
Comment (Montellese) [inline xbmc/network/upnp/UPnPServer.cpp:664]: You're decoding `object_id` twice. Please use a local variable for the decoded `object_id`.

File: xbmc/network/upnp/UPnPServer.cpp [hunk 6]
```diff
@@ -872,10 +873,10 @@ CUPnPServer::OnSearchContainer(PLT_ActionReference&          action,
                                const char*                   sort_criteria,
                                const PLT_HttpRequestContext& context)
 {
-  m_logger->debug("Received Search request for object '{}' with search '{}'", object_id,
-                  search_criteria);
+  m_logger->debug("Received Search request for encoded object '{}' (plain value: '{}') with search '{}'",
+                  object_id, DecodeObjectId(object_id).GetChars(), search_criteria);
```
Comment (Montellese) [inline xbmc/network/upnp/UPnPServer.cpp:877]: You're decoding `object_id` twice. Please use a local variable for the decoded `object_id`.

**Review by Montellese — CHANGES_REQUESTED** [review]
Looks good apart from the comments and the question concerning the pure integers.

What happens if we pass in a VFS path into `Base64::Decode()`? Does it return an empty string or the same string that was inserted? To alleviate @Tolriq's concerns we could try to extend `DecodeObjectId()` to support both raw VFS paths and base64 encoded VFS paths. It should be pretty simple to detect if the objectID contains `://` (which are not valid in a base64 encoded string) and assume it's a raw VFS path which doesn't need decoding from base64.

File: xbmc/network/upnp/UPnPInternal.cpp (hunk 2 above)
Comment (enen92) [reply xbmc/network/upnp/UPnPInternal.cpp:1248]: Nice point. I guess it is possible but highly unlikely due to the way base64 works (multiple conversions involved) and also what we "expect" to have as decoded values. 
Maybe this can be made safer by defining some whitelist of allowed values.

**Review by Montellese — APPROVED** [review]

**Comment by Tolriq** [comment]
I know me and my users are non existing thanks for the reminder ;)

For the record since Kodi 19 the need and usage have increased (And it's good, because by enforcing users to add a password to Kodi security is improved). Let me explain again a tons of previous discussions.

Some (many) users want to cast from Kodi to other devices, devices that may not be supported by Kodi natively.
Those devices may (do) not support basic auth (the only thing Kodi support). (Chromecast, UPnP, ...).

The API to list everything and control Kodi and get the media is JSON.
JSON only allows to generate urls for the web server that by design will require the basic auth since there's no token or api key support.
Those urls do not work for that usage. The only other solution is to use the Kodi UPnP server for that.
There's no API to link UPnP and JSON. There's no way to properly search in UPnP for quite a few cases.

So call that an hack, an heresy or whatever you want this is a need that exist for some (many) users and a working solution was found. (And is used by many non existing people, including from other applications completely not related to me) (Using the VFS path to search and enable UPnP access for the specific files) [Hack used way before you started to contribute to Kodi, and that I ensured still worked 10 years ago https://github.com/xbmc/xbmc/pull/2764)

A proper API to fit that need would be more than welcome, but Montellese stopped being active on the JSON/UPnP part before anything could be done.

**Comment by enen92** [comment]
jenkins build this please

**Comment by enen92** [comment]
@Tolriq I said that for me **the issue** is non-existent, not your users.

But anyway, went ahead and gave it a spin:
- installed yatse
1) first test
- configured yatse to connect via json-rpc to kodi on my desktop and selected the chromecast on my living room as renderer. Tried to play music --> works; tried to play a movie --> failed
- removed the commit I am adding here; tried to play a movie --> failed (looks broken to me)

2) second test
- Yatse using my kodi laptop as client, kodi on the living room (v20) as upnp renderer configured in yatse. Tried to play audio --> works; trying to play video --> works

My conclusion: the issue is non-existent. The only issue I faced was there even before this commit.

**Comment by Tolriq** [comment]
Is your Kodi password protected? That's the whole story. If not then it use the http server as normal since there's no issue with that.
If it's protect then Yatse spin the UPnP locator to find the media on the UPnP server.

For the movie, your issue is incompatible codecs not much to be done as the transcoding thing was never done.

About your edit, your last changes does fix the issue for the Yatse use case, thanks to @Montellese for requesting it and you for implementing it.

**Comment by enen92** [comment]
> About your edit, your last changes does fix the issue for the Yatse use case, thanks to @Montellese for requesting it and you for implementing it.

Montellese suggested (**not requested**) a compatibility-fallback which is well scoped/bounded and doesn't really get into the way of the new implementation. Since everyone here is trying to make Kodi better (I guess) and the suggestion doesn't harm...I included it. He didn't exactly come here moaning about the fact some id was being changed.

You're the one being paranoid. Afaik martijn is absent for years, I couldn't care less about politics.
I suggest you take some time to review your attitude, it's not my fault if you have problems with someone else.

**Comment by Tolriq** [comment]
Can you please show me a single word in this PR that show that I'm paranoid or that have attitude problem?

This is a genuine question, because I tried my best to avoid every possible susceptibility thing here.


> Which makes me wonder what your intentions here really are... 

I report the issue, explain why, explain the history explain everything calmly, and you keep telling me that there's no issue without reading the explanation and then ask about my motivations?

Let's ignore the attitude on the other side.
