### PR TITLE
SysfsPath: Have CSysfsPath::Get() return a std::optional because reads can fail

### LINKED ISSUE #21747: Kodi crashes if current freq of CPU 0 is not available
### Describe the bug

Kodi crashes upon opening the CPU info page in Settings if it can't read from _/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq_ on Linux.

In short, there are systems with multiple CPUs where disabling some of the CPUs is favorable. On older kernels reading from the _/sys/devices/system/cpu/cpuX/cpufreq/scaling_cur_freq_ of the disabled CPU was returning simply zero or last known value. Currently it returns _read error_ and that causes Kodi to crash. 

Please read more information here:
https://github.com/LibreELEC/LibreELEC.tv/issues/6758

## Expected Behavior

Kodi doesn't crash.

## Actual Behavior

Kodi crashes.

## Possible Fix

Don't expect the CPU 0 to be the main CPU and to be always online. Before trying to read from _/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq_ we should check whether the CPU 0 is actually online by reading _/sys/devices/system/cpu/cpu0/online_. If it is not online, then try CPU 1, 2, 3 etc. until we find CPU which is online and then read all the CPU info from it.

### To Reproduce

1. run "_echo '0' > /sys/devices/system/cpu/cpu0/online_"
2. open "Settings" -> "System information" -> "CPU"
3. Kodi crashes on affected platforms (depends on the Linux kernel)

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 11 (RK3399)
 - Kodi version: 20.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by neo1973**
## Description
Reading from sysfs can fail with errors, this causes `CSysfsPath::Get()` to throw an exception. This exception wasn't handled in `CCPUInfoLinux::GetCPUFrequency()` causing Kodi to crash. This PR handles exceptions inside `CSysfsPath::Get()` and returns a `std::nullopt` in case the read failed.

## Motivation and context
Should fix #21747.

## How has this been tested?
In `CCPUInfoLinux::CCPUInfoLinux()` changed the path from `/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq` to `/sys/devices/system/cpu/power/autosuspend_delay_ms` which causes an input/output error on my machine:
```
$ cat /sys/devices/system/cpu/power/autosuspend_delay_ms
cat: /sys/devices/system/cpu/power/autosuspend_delay_ms: Input/output error
```
Without this PR Kodi crashes, with this PR it's fine.

## What is the effect on users?
Fixes crash in some circumstances (see #21747)

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/platform/linux/CPUInfoLinux.cpp [hunk 1]
```diff
@@ -359,8 +360,15 @@ float CCPUInfoLinux::GetCPUFrequency()
   if (m_freqPath.empty())
     return 0;
 
-  CSysfsPath path{m_freqPath};
-  return path.Get<float>() / 1000.0f;
+  try
+  {
+    CSysfsPath path{m_freqPath};
```
Comment (lrusak) [inline xbmc/platform/linux/CPUInfoLinux.cpp:365]: We check `m_freqPath` above in the constructor. I think it would be better to do a similar check there so that it's not even used if it throws an error.

File: xbmc/platform/linux/CPUInfoLinux.cpp [hunk 2]
```diff
@@ -371,11 +379,18 @@ bool CCPUInfoLinux::GetTemperature(CTemperature& temperature)
   if (m_tempPath.empty())
     return false;
 
-  CSysfsPath path{m_tempPath};
-  double value = path.Get<double>() / 1000.0;
+  try
+  {
+    CSysfsPath path{m_tempPath};
+    double value = path.Get<double>() / 1000.0;
```
Comment (lrusak) [inline xbmc/platform/linux/CPUInfoLinux.cpp:385]: Does this throw or are you just being defensive? Maybe it would be better to build the safety into `CSysfsPath`?

File: xbmc/platform/linux/CPUInfoLinux.cpp (hunk 1 above)
Comment (neo1973) [reply xbmc/platform/linux/CPUInfoLinux.cpp:365]: Hmm, not sure about that. It sounds to me like CPUs can switch between online and offline at any time so doing a check during construction probably isn't beneficial.

Ideally we would search for a new online CPU every time a read fails but at the moment I'm not motivated to implement that ^^

File: xbmc/platform/linux/CPUInfoLinux.cpp (hunk 2 above)
Comment (neo1973) [reply xbmc/platform/linux/CPUInfoLinux.cpp:385]: I'm just being defensive here.

Moving this safety to `CSysfsPath` sounds like a good idea. Are you thinking about catching exceptions in `CSysfsPath::Get<>()` and changing the return value of that method to a `std::optional` to distinguish failure/success?

File: xbmc/platform/linux/CPUInfoLinux.cpp (hunk 1 above)
Comment (lrusak) [reply xbmc/platform/linux/CPUInfoLinux.cpp:365]: yea that might be overkill really for something that is purely for visual sugar.

File: xbmc/platform/linux/CPUInfoLinux.cpp (hunk 2 above)
Comment (lrusak) [reply xbmc/platform/linux/CPUInfoLinux.cpp:385]: Yea that would be ok with me.

File: xbmc/platform/linux/SysfsPath.cpp [hunk 3]
```diff
@@ -19,19 +21,27 @@ bool CSysfsPath::Exists()
...
+    std::ifstream file(m_path);
 
-  std::string value;
+    std::string value;
 
-  std::getline(file, value);
+    std::getline(file, value);
 
-  if (file.bad())
+    if (file.bad())
```
Comment (lrusak) [inline xbmc/platform/linux/SysfsPath.cpp:34]: Is this if block even relevant anymore?

File: xbmc/platform/linux/SysfsPath.h [hunk 4]
```diff
@@ -23,26 +25,34 @@ class CSysfsPath
...
+    {
+      std::ifstream file(m_path);
+
+      T value;
 
-    T value;
+      file >> value;
 
-    file >> value;
+      if (file.bad())
```
Comment (lrusak) [inline xbmc/platform/linux/SysfsPath.h:38]: Same here.

**Review by lrusak — APPROVED** [review]
Looks nice. A great improvement.

File: xbmc/platform/linux/SysfsPath.cpp (hunk 3 above)
Comment (neo1973) [reply xbmc/platform/linux/SysfsPath.cpp:34]: I think it is, `std::ifstream::operator>>` doesn't throw if it can't convert the input if I understand correctly.
