### PR TITLE
NFSv3 and NFSv4 fixes and improvements

### LINKED ISSUE #22862: Playback stops due to unreliable NFSv4 mount
### Describe the bug
Here is a clear and concise description of what the problem is:

Video playback stops due to unreliable NFSv4 mount

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Video playback show not prematurely end

## Actual Behavior

Video playback stops seemingly due to read access to file changing while playback is occurring due to NFSv4 mount

### To Reproduce

1. Build from Nexus branch and apply https://github.com/xbmc/xbmc/pull/22714
2. Start kodi and try playing back some video file that is 2-3 hours long

### Debuglog

The debuglog can be found here:

**When this bug hit, I did not have debug logging enabled.  I will repeat the playback and attach a full debug log when I reproduced the bug.**

```
2023-02-24 19:03:34.464 T:5982     info <general>: VideoPlayer::OpenFile: nfs://10.9.8.112/homemovies/dogs_at_park.mp4
2023-02-24 19:03:34.465 T:28935    info <general>: Creating InputStream
2023-02-24 19:03:34.469 T:28935    info <general>: Creating Demuxer
2023-02-24 19:03:34.578 T:28935    info <general>: Opening stream: 0 source: 256
2023-02-24 19:03:34.578 T:28935    info <general>: Creating video codec with codec id: 27
2023-02-24 19:03:34.578 T:28935    info <general>: CDVDVideoCodecFFmpeg::Open() Using codec: H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
2023-02-24 19:03:34.578 T:28935    info <general>: Creating video thread
2023-02-24 19:03:34.578 T:28939    info <general>: running thread: video_thread
2023-02-24 19:03:34.578 T:28935    info <general>: Opening stream: 1 source: 256
2023-02-24 19:03:34.578 T:28935    info <general>: Finding audio codec for: 86018
2023-02-24 19:03:34.579 T:28935    info <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder aac
2023-02-24 19:03:34.579 T:28935    info <general>: OpenStream: Allowing max Out-Of-Sync Value of 10 ms
2023-02-24 19:03:34.579 T:28935    info <general>: Creating audio thread
2023-02-24 19:03:34.579 T:28940    info <general>: running thread: CVideoPlayerAudio::Process()
2023-02-24 19:03:34.579 T:28935    info <general>: Opening stream: 0 source: 1024
2023-02-24 19:03:34.580 T:28935    info <general>: CDVDSubtitlesLibass: Using libass version 1700000
2023-02-24 19:03:34.580 T:28935    info <general>: CDVDSubtitlesLibass: Creating ASS library structure
2023-02-24 19:03:34.580 T:28935    info <general>: CDVDSubtitlesLibass: Initializing ASS Renderer
2023-02-24 19:03:34.580 T:28935    info <general>: CDVDSubtitlesLibass: Initializing ASS library font settings
2023-02-24 19:03:34.580 T:28935   error <general>: GetDirectory - Error getting /var/lib/kodi/.kodi/temp/fonts/
2023-02-24 19:03:34.580 T:28935   error <general>: GetDirectory - Error getting special://temp/fonts/
2023-02-24 19:03:34.590 T:28935    info <general>: CDVDSubtitlesLibass: Creating new ASS track
2023-02-24 19:03:34.629 T:28940    info <general>: Creating audio stream (codec id: 86018, channels: 6, sample rate: 48000, no pass-through)
2023-02-24 19:03:34.635 T:28944    info <general>: COutput::OnStartup: Output Thread created
2023-02-24 19:03:34.635 T:28944    info <general>: VAAPI::SupportsFilter vaDeriveImage not supported by driver - ffmpeg postprocessing and CPU-copy rendering will not be available
2023-02-24 19:03:34.651 T:6016     info <general>: CActiveAESink::OpenSink - initialize sink
2023-02-24 19:03:34.699 T:5982     info <general>: GL: Selecting YUV 2 RGB shader
2023-02-24 19:03:34.699 T:5982     info <general>: GL: Using GL_ARB_pixel_buffer_object
2023-02-24 19:03:34.699 T:5982     info <general>: Using GL_TEXTURE_2D
2023-02-24 19:03:34.850 T:6016     info <general>: CAESinkALSA::Initialize - Attempting to open device "iec958:CARD=PCH,DEV=0"
2023-02-24 19:03:34.852 T:6016     info <general>: CAESinkALSA::Initialize - Opened device "iec958:CARD=PCH,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x02"
2023-02-24 19:03:34.852 T:6016     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-02-24 19:03:34.852 T:6016     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
2023-02-24 19:03:35.260 T:28939    info <general>: CDVDVideoCodecFFmpeg::CDropControl: calculated diff time: 41708
2023-02-24 19:47:01.585 T:5982     info <general>: NFS: sending keep alive after 180 s.
2023-02-24 19:47:10.061 T:6016     info <general>: CActiveAESink::OpenSink - initialize sink
2023-02-24 19:47:10.061 T:6016     info <general>: CAESinkALSA::Initialize - Attempting to open device "iec958:CARD=PCH,DEV=0"
2023-02-24 19:47:10.242 T:6016     info <general>: CAESinkALSA::Initialize - Opened device "iec958:CARD=PCH,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x02"
2023-02-24 19:47:10.242 T:6016     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-02-24 19:47:10.242 T:6016     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
2023-02-24 19:47:10.394 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:10.394 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:12.394 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:12.394 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:14.395 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:14.395 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:16.395 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:16.395 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:18.395 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:18.395 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:20.396 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:20.396 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:22.396 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:22.396 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:24.396 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:24.396 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:26.397 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:26.397 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:28.397 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:28.397 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:30.397 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:30.397 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:32.398 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:32.398 T:28938 warning <general>: CFileCache::Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read returned -34! Will retry
2023-02-24 19:47:34.398 T:28938   error <general>: Read - Error( -34, read call failed with "NFS4: READ (path (null)) failed with NFS4ERR_EXPIRED(-11)" )
2023-02-24 19:47:34.398 T:28938   error <general>: Process - <nfs://10.9.8.112/homemovies/dogs_at_park.mp4> source read failed with -34!
2023-02-24 19:47:41.199 T:28940    info <general>: CVideoPlayerAudio::Process - stream stalled
2023-02-24 19:47:41.352 T:28935    info <general>: CVideoPlayer::OnExit()
2023-02-24 19:47:41.352 T:28935    info <general>: VideoPlayer: eof, waiting for queues to empty
2023-02-24 19:47:41.352 T:28935    info <general>: Closing stream player 1
2023-02-24 19:47:41.352 T:28935    info <general>: CDVDMessageQueue(audio)::WaitUntilEmpty
2023-02-24 19:47:41.352 T:28935    info <general>: Waiting for audio thread to exit
2023-02-24 19:47:41.352 T:28940    info <general>: thread end: CVideoPlayerAudio::OnExit()
2023-02-24 19:47:41.352 T:28935    info <general>: Closing audio device
2023-02-24 19:47:41.352 T:28935    info <general>: Deleting audio codec
2023-02-24 19:47:41.352 T:28935    info <general>: Closing stream player 2
2023-02-24 19:47:41.352 T:28935    info <general>: CDVDMessageQueue(video)::WaitUntilEmpty
2023-02-24 19:47:41.503 T:28935    info <general>: waiting for video thread to exit
2023-02-24 19:47:41.503 T:28939    info <general>: thread end: video_thread
2023-02-24 19:47:41.503 T:28935    info <general>: deleting video codec
2023-02-24 19:47:41.504 T:28935    info <general>: Closing stream player 3
2023-02-24 19:47:41.505 T:28935   error <general>: Failed to close(homemovies/dogs_at_park.mp4) - close call failed with "NFS4: CLOSE (path (null)) failed with NFS4ERR_EXPIRED(-11)"
2023-02-24 19:47:41.519 T:5982     info <general>: CVideoPlayer::CloseFile()
2023-02-24 19:47:41.524 T:5982     info <general>: VAAPI::Close
2023-02-24 19:47:41.524 T:28944    info <general>: COutput::OnExit: Output Thread terminated
2023-02-24 19:47:41.524 T:5982     info <general>: VAAPI::Close - closing decoder context
2023-02-24 19:47:41.525 T:5982     info <general>: VideoPlayer: waiting for threads to exit
2023-02-24 19:47:41.525 T:5982     info <general>: VideoPlayer: finished waiting
2023-02-24 19:47:41.525 T:5982     info <general>: CVideoPlayer::CloseFile()
2023-02-24 19:47:41.525 T:5982     info <general>: VideoPlayer: waiting for threads to exit
2023-02-24 19:47:41.525 T:5982     info <general>: VideoPlayer: finished waiting
2023-02-24 19:47:41.536 T:29066    info <general>: WEATHER: Downloading weather
2023-02-24 19:47:41.650 T:6016     info <general>: CActiveAESink::OpenSink - initialize sink
2023-02-24 19:47:41.851 T:6016     info <general>: CAESinkALSA::Initialize - Attempting to open device "iec958:CARD=PCH,DEV=0"
2023-02-24 19:47:41.852 T:6016     info <general>: CAESinkALSA::Initialize - Opened device "iec958:CARD=PCH,DEV=0,AES0=0x04,AES1=0x82,AES2=0x00,AES3=0x00"
2023-02-24 19:47:41.852 T:6016     info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-02-24 19:47:41.852 T:6016     info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S32NE
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have not seen this bug hit on shorter video clips of <1 hour, yet it only took about 45 minutes to hit on a 2+ hour clip.  It happened a total of 3 times.

Here is `/etc/exports`:
```
/srv/nfs         10.9.8.0/24(ro,fsid=root,no_subtree_check,insecure,async,all_squash,pnfs,anonuid=99,anongid=99)
/srv/nfs/misc    10.9.8.0/24(ro,no_subtree_check,insecure,async,all_squash,pnfs,anonuid=99,anongid=99)
/srv/nfs/homemovies    10.9.8.0/24(ro,no_subtree_check,insecure,async,all_squash,pnfs,anonuid=99,anongid=99)
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux (up-to-date)
 - Kodi version: Kodi built from https://github.com/xbmc/xbmc/commit/246fd7f19fce0e841f7edef6a44df9357deca08f

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
NFSv3 and NFSv4 fixes and improvements:

- Fixes session expiration due insufficient keep alive interval (NFSv4 only).
- Fixes attempt to reuse cached but expired NFS contexts (NFSv4 only).
- Fixes crash when read Blu-Ray BDMV structures and some optional files not exist (NFSv3 & NFSv4).
- Use 128K read/write chunk size in NFSv4  (NFSv4 servers do not enforce or limit to any specific value).
- Fixes https://github.com/xbmc/xbmc/issues/22862
- Fixes https://github.com/xbmc/xbmc/pull/22714#issuecomment-1439719284

## Motivation and context
Due to the big differences between NFSv3 and NFSv4, certain changes are necessary, especially everything related to time outs and keep alive:

> NFSv3 is stateless. That effectively means that the NFS server (ONTAP) doesn't keep track of which filesystems are mounted, by whom, or which locks are truly in place. Tracking NFS client state is not part of the NFSv3 standard.
> 
> In contrast, NFSv4 is stateful. The NFSv4 server tracks which clients are using which filesystems, which files exist, which files and/or regions of files are locked, etc. This means there needs to be regular communication between an NFSv4 server to keep the state data current.

https://community.netapp.com/t5/Tech-ONTAP-Blogs/NFSv3-and-NFSv4-What-s-the-difference/ba-p/441316

> The client queries the server's "lease_time" attribute. (Default 90s on Linux.)
> Normal filesystem activity starts. The client ensures that it sends one rpc (may be some sort of no-op) at least every lease_time, to reassure the server that it's still active.

> NFSv3 also has the notion of grace periods and reclaim flags on lock requests. The main differences are:
> there's no lease time, and clients aren't required to poll the server regularly.

https://linux-nfs.org/wiki/index.php/NFS_lock_recovery_notes

## How has this been tested?
Runtime Windows x64 and Android (Shield). 
As NFSv4 server used Synology NAS (DSM 7.1.1) Indeed, it has been proven that it has 90s "lease_time".
Tested NFSv3 and NFSv4, tested and reproduced all issues mentioned.

## What is the effect on users?
- Fixes random `NFS4ERR_EXPIRED` errors at open files any time.
- Fixes video playback stalls and closes after pause due insufficient keep alive of NFSv4 session.
- Fixes crash opening Blu-Ray folders (BDMV) if some optional files not present (very common).
- Fixes slow NFSv4 read when not using file cache due very small read chunk size.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by graysky2** [comment]
I build the latest commit form Nexus branch with this PR and found that all NFS paths are broken.  Can you confirm?

EDIT: my system is using a shared mysqld data base if that matters.  I am finding lines in the log like this:
```
2023-03-03 15:01:21.611 T:718      info <general>: Running database version Addons33
2023-03-03 15:01:21.611 T:718      info <general>: Running database version ViewModes6
2023-03-03 15:01:21.612 T:718      info <general>: Running database version Textures13
2023-03-03 15:01:21.615 T:718     error <general>: Unable to open database: MyMusic82 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.615 T:718     error <general>: Unable to open database: MyMusic81 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.615 T:718     error <general>: Unable to open database: MyMusic80 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.615 T:718     error <general>: Unable to open database: MyMusic79 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.615 T:718     error <general>: Unable to open database: MyMusic78 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.615 T:718     error <general>: Unable to open database: MyMusic77 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.615 T:718     error <general>: Unable to open database: MyMusic76 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic75 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic74 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic73 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic72 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic71 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic70 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic69 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic68 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic67 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic66 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic65 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.616 T:718     error <general>: Unable to open database: MyMusic64 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic63 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic62 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic61 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic60 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic59 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic58 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic57 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic56 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic55 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic54 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.617 T:718     error <general>: Unable to open database: MyMusic53 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic52 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic51 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic50 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic49 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic48 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic47 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic46 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic45 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic44 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.618 T:718     error <general>: Unable to open database: MyMusic43 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic42 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic41 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic40 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic39 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic38 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic37 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic36 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic35 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic34 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic33 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.619 T:718     error <general>: Unable to open database: MyMusic32 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.620 T:718     error <general>: Unable to open database: MyMusic82 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.620 T:718     error <general>: Unable to create new database
2023-03-03 15:01:21.621 T:718     error <general>: Unable to open database: MyVideos121 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.621 T:718     error <general>: Unable to open database: MyVideos120 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.621 T:718     error <general>: Unable to open database: MyVideos119 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.621 T:718     error <general>: Unable to open database: MyVideos118 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.621 T:718     error <general>: Unable to open database: MyVideos117 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.621 T:718     error <general>: Unable to open database: MyVideos116 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos115 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos114 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos113 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos112 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos111 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos110 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos109 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos108 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos107 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos106 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos105 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.622 T:718     error <general>: Unable to open database: MyVideos104 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos103 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos102 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos101 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos100 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos99 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos98 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos97 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos96 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos95 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos94 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.623 T:718     error <general>: Unable to open database: MyVideos93 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos92 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos91 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos90 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos89 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos88 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos87 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos86 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos85 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos84 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos83 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos82 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.624 T:718     error <general>: Unable to open database: MyVideos81 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.625 T:718     error <general>: Unable to open database: MyVideos80 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.625 T:718     error <general>: Unable to open database: MyVideos79 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.625 T:718     error <general>: Unable to open database: MyVideos78 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.625 T:718     error <general>: Unable to open database: MyVideos77 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.625 T:718     error <general>: Unable to open database: MyVideos76 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.625 T:718     error <general>: Unable to open database: MyVideos75 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.625 T:718     error <general>: Unable to open database: MyVideos121 [2002](Can't connect to server on '10.9.8.112' (101))
2023-03-03 15:01:21.625 T:718     error <general>: Unable to create new database
```

**Comment by fritsch** [comment]
Sorry - this error has absolutely nothing to do with your mysql connection issue.

**Comment by thexai** [comment]
`2023-03-03 15:01:21.625 T:718     error <general>: Unable to open database:`

This is totally unrelated: database/Mysql not uses NFS at all...

**Comment by graysky2** [comment]
Very odd/I applied the latest version of this PR to the latest commit from Nexus and it is behaving as expected.  Not sure what triggered the errors I posted above.

**Comment by thexai** [comment]
Note that last commit (128K chunks) is critical. 

Without it when FileCache is not used, and with some file types (as playing BDMV folders) never is used (even if buffermode is set to 1). VideoPlayer stalls with buffering all the time as 4K read chunks is not enougth for high bitrate streaming....

File: xbmc/filesystem/NFSFile.cpp [hunk 1]
```diff
@@ -432,11 +444,13 @@ void CNfsConnection::keepAlive(const std::string& _exportPath, struct nfsfh* _pF
...
-  CLog::Log(LOGINFO, "NFS: sending keep alive after {} s.",
-            std::chrono::duration_cast<std::chrono::seconds>(KEEP_ALIVE_TIMEOUT).count());
+  CLog::LogF(LOGDEBUG, "sending keep alive after {}s.",
+             std::chrono::duration_cast<std::chrono::seconds>(KEEP_ALIVE_TIMEOUT).count());
   std::unique_lock<CCriticalSection> lock(*this);
   nfs_lseek(pContext, _pFileHandle, 0, SEEK_CUR, &offset);
-  nfs_read(pContext, _pFileHandle, 32, buffer);
+  int bytes = nfs_read(pContext, _pFileHandle, 32, buffer);
+  if (bytes < 0)
+    CLog::LogF(LOGERROR, "nfs_read - Error ({}, {})", bytes, nfs_get_error(pContext));
```
Comment (arnova) [inline xbmc/filesystem/NFSFile.cpp:453]: Shouldn't we early return here to skip the SEEK_SET below?

File: xbmc/filesystem/NFSFile.cpp [hunk 2]
```diff
@@ -585,34 +599,34 @@ bool CNFSFile::Open(const CURL& url)
...
-    m_exportPath = gNfsConnection.GetContextMapId();
+  m_pNfsContext = gNfsConnection.GetNfsContext();
+  m_exportPath = gNfsConnection.GetContextMapId();
 
-    return nfs_open(m_pNfsContext, filename.c_str(), O_RDONLY, &m_pFileHandle) == 0;
-  };
+  int ret = nfs_open(m_pNfsContext, filename.c_str(), O_RDONLY, &m_pFileHandle);
 
-  if (!NfsOpen(url, filename))
+  if (ret == -11) // NFS4ERR_EXPIRED
```
Comment (arnova) [inline xbmc/filesystem/NFSFile.cpp:610]: Perhaps use a #define ?

**Review by arnova — COMMENTED** [review]
Some minors but overall looking good.

File: xbmc/filesystem/NFSFile.cpp [hunk 3]
```diff
@@ -45,16 +45,16 @@ using namespace std::chrono_literals;
 
 namespace
 {
+// Default "lease_time" on most Linux NFSv4 servers are 90s.
```
Comment (lrusak) [inline xbmc/filesystem/NFSFile.cpp:48]: Because this value can be changed is why I avoided adjusting the timeouts in the first place.

File: xbmc/filesystem/NFSFile.cpp [hunk 4]
```diff
@@ -45,16 +45,16 @@ using namespace std::chrono_literals;
...
+// See: https://linux-nfs.org/wiki/index.php/NFS_lock_recovery_notes
+// Keep alive interval should be always less than lease_time to avoid client session expires
 
-constexpr auto CONTEXT_TIMEOUT = 6min;
-
-constexpr auto KEEP_ALIVE_TIMEOUT = 3min;
-
-constexpr auto IDLE_TIMEOUT = 3min;
+constexpr auto CONTEXT_TIMEOUT = 60s; // 2/3 parts of lease_time
```
Comment (lrusak) [inline xbmc/filesystem/NFSFile.cpp:52]: Why do these other values need to be adjusted?

File: xbmc/filesystem/NFSFile.cpp [hunk 5]
```diff
@@ -432,11 +444,13 @@ void CNfsConnection::keepAlive(const std::string& _exportPath, struct nfsfh* _pF
   if (!pContext)// this should normally never happen - paranoia
     pContext = m_pNfsContext;
 
-  CLog::Log(LOGINFO, "NFS: sending keep alive after {} s.",
-            std::chrono::duration_cast<std::chrono::seconds>(KEEP_ALIVE_TIMEOUT).count());
+  CLog::LogF(LOGDEBUG, "sending keep alive after {}s.",
```
Comment (lrusak) [inline xbmc/filesystem/NFSFile.cpp:447]: I imagine you changed this to debug because it's a bit spammy with the faster keep alive.

File: xbmc/filesystem/NFSFile.cpp [hunk 6]
```diff
@@ -585,34 +599,34 @@ bool CNFSFile::Open(const CURL& url)
...
+    m_pNfsContext = gNfsConnection.GetNfsContext();
+    m_exportPath = gNfsConnection.GetContextMapId();
+    ret = nfs_open(m_pNfsContext, filename.c_str(), O_RDONLY, &m_pFileHandle);
+  }
 
-    if (!NfsOpen(url, filename))
-    {
-      CLog::Log(LOGERROR, "CNFSFile::Open: Unable to open file: '{}' error: '{}'",
-                url.GetFileName(), nfs_get_error(m_pNfsContext));
+  if (ret != 0)
```
Comment (lrusak) [inline xbmc/filesystem/NFSFile.cpp:622]: Are positive error codes allowed?

File: xbmc/filesystem/NFSFile.cpp [hunk 7]
```diff
@@ -45,16 +45,16 @@ using namespace std::chrono_literals;
...
-
-constexpr auto IDLE_TIMEOUT = 3min;
+constexpr auto CONTEXT_TIMEOUT = 60s; // 2/3 parts of lease_time
+constexpr auto KEEP_ALIVE_TIMEOUT = 45s; // half of lease_time
+constexpr auto IDLE_TIMEOUT = 30s; // close fast unused contexts when no active connections
 
 constexpr auto SETTING_NFS_VERSION = "nfs.version";
-
-} // namespace
+} // unnamed namespace
```
Comment (lrusak) [inline xbmc/filesystem/NFSFile.cpp:57]: I'm surprised clang-format doesn't trip up on this.

File: xbmc/filesystem/NFSFile.cpp (hunk 4 above)
Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:52]: Because context "expires" when time of inactivity is greater than server's "lease_time"

File: xbmc/filesystem/NFSFile.cpp (hunk 5 above)
Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:449]: True

File: xbmc/filesystem/NFSFile.cpp (hunk 7 above)
Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:59]: ?

Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:59]: https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#6-scoping

File: xbmc/filesystem/NFSFile.cpp (hunk 6 above)
Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:631]: only `ret == 0` is open successfully, then `ret != 0` is open FAILED which is precisely what we want to detect here

File: xbmc/filesystem/NFSFile.cpp (hunk 3 above)
Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:48]: But Linux default (nfs-kernel-server) is 90s. This is so....

6 minutes does NOT work. If you want to use 6 minutes because "avoid change here" then you need submit patch to Linux kernel

File: xbmc/filesystem/NFSFile.cpp (hunk 5 above)
Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:449]: I want to prevent someone from opening a new issue "log spamming when video is paused"  and you assigning it to me. :)

File: xbmc/filesystem/NFSFile.cpp (hunk 3 above)
Comment (enen92) [reply xbmc/filesystem/NFSFile.cpp:48]: Wouldn't an advanced setting for this purpose be better (while keeping the sane defaults)?
I assume there's no easy way to get those values from the server

File: xbmc/filesystem/NFSFile.cpp (hunk 4 above)
Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:52]: Current solution is:

CONTEXT_TIMEOUT = 6 minutes
But expires in 90s then when someone opens a file after 90s nfs_open fails with NFS4ERR_EXPIRED but is retry with https://github.com/xbmc/xbmc/commit/9dc30e83c830d379c063eaf3a4a64a9fb57ca782


New solution is:

Discard expired contexts so `nfs_open` should never fail and should never retry...

File: xbmc/filesystem/NFSFile.cpp (hunk 3 above)
Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:48]: > I assume there's no easy way to get those values from the server

In fact, the spec says that clients should get the lease_time from the server:

> The client queries the server's "lease_time" attribute. (Default 90s on Linux.)

https://linux-nfs.org/wiki/index.php/NFS_lock_recovery_notes

But we are limited to what `libnfs` offers and I haven't found a way to get this (note that this is "new" in NFSv4 and v4 support in libnfs is very limited and NFSv4.1 is unsupported).

Anyway 45s keep alive should work in all cases because common values are 90s (default), 120s or 60s.

30s or less is discouraged.

Comment (lrusak) [reply xbmc/filesystem/NFSFile.cpp:48]: Maybe @sahlberg know more about the leasing period. It would be nice if we could just query it.

Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:48]: I also think that it is necessary to clarify here that the keep alive that we have implemented (it was already in NFSv3) are not to keep the NFS server's session active (this concept simply did not exist in NFSv3) but rather to prevent the hard disk from stopping spin up and go into hibernation when the video is paused for several minutes.

It is true that now with NFSv4 the same keep alive works for both.

The keep alive for NFS session does not need to read data from the hard drive, it just sends a RENEW command. On the other hand, to keep the hard drive spinning, it is necessary to read something...

File: xbmc/filesystem/NFSFile.cpp [hunk 8]
```diff
@@ -327,10 +329,22 @@ bool CNfsConnection::Connect(const CURL& url, std::string &relativePath)
...
-    //read chunksize only works after mount
+
+    // read chunksize only works after mount
     m_readChunkSize = nfs_get_readmax(m_pNfsContext);
     m_writeChunkSize = nfs_get_writemax(m_pNfsContext);
 
+    if (m_readChunkSize == 0)
+    {
+      CLog::Log(LOGDEBUG, "NFS Server did not return max read chunksize - Using 128K default");
+      m_readChunkSize = 128 * 1024; // 128K
```
Comment (wsnipex) [inline xbmc/filesystem/NFSFile.cpp:340]: I wonder if it's worth making this an advanced setting.

**Review by wsnipex — APPROVED** [review]
looks good to me, but left a question for your consideration

File: xbmc/filesystem/NFSFile.cpp (hunk 8 above)
Comment (fritsch) [reply xbmc/filesystem/NFSFile.cpp:340]: There is already chunksize as advancedsetting, that this works though you need to return 1 here,then FileCache will set it to 64K or to chunksize else. Sucks. Smb returns 128K always.

Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:340]: @wsnipex 
It seems like a good idea to me but I will do in a follow up PR to keep this simple for backport.

128K has been chosen (and should be fine for all) because 128K is already used in NFSv3 and also when FileCahe is used with NFSv4.

This code force to use default 128K chunk size when source reports 0:

https://github.com/xbmc/xbmc/blob/56b88b2bf5d82fd2b2feb4df4b35f81e70ca1b89/xbmc/filesystem/FileCache.cpp#L138-L144

Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:340]: File chunk size is a bit chaotic because is hardcoded in many places:

https://github.com/xbmc/xbmc/blob/56b88b2bf5d82fd2b2feb4df4b35f81e70ca1b89/xbmc/filesystem/File.cpp#L119

Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp:340]: > There is already chunksize as advancedsetting

This is chunk size for FileCahe only

We can create a new setting for NFS only (when is not used in combination with FileCache)

Comment (wsnipex) [reply xbmc/filesystem/NFSFile.cpp:340]: yes, it's cache only, so won't work when caching is disabled.

adding this in a followup PR is fine for me.

**Comment by lrusak** [comment]
Why was this rushed to be merged? There was still outstanding comments and no approvals 😞

**Comment by thexai** [comment]
> and no approvals 

approval
