### PR TITLE
[WEBSERVER] Handle HEAD requests in exactly the same way as GET requests

### LINKED ISSUE #20759: Duplicate Content-Length HTTP Header in JSON-RPC responses
### Describe the bug
Here is a clear and concise description of what the problem is:

Responses from the JSON-RPC include a duplicate `Content-Length` HTTP header that is causing some useragents to throw exceptions:

Screen Shot 2021-12-31 at 19 14 58

I am running Kodi 19.3-2 on both my Linux desktop (5.15.10) and Mac OS (20.6.0).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The JSON-RPC server should only include one `Content-Length` header in responses, like tested on Mac OS:

Screen Shot 2021-12-31 at 19 43 14

## Actual Behavior

There are two `Content-Length` headers in the HTTP response. This breaks some useragents from using the JSON-RPC data, such as Home Assistant's Kodi integration (will see if I can grab you a traceback for that too):

Screen Shot 2021-12-31 at 19 14 58

## Possible Fix

Between these two functions, do we have a double-up of `Content-Length` Header logic?:

1. https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/xbmc/utils/HttpResponse.cpp#L89
2. https://github.com/xbmc/xbmc/blob/7478f983b67dc1e3b09e061acf2eaa675b0f0170/xbmc/network/WebServer.cpp#L445

### To Reproduce

1. Running Kodi 19.3-2 on Linux (reinstalled multiple times + with empty `.kodi` directory, works fine on Mac OS)

### Debuglog

In this debug log, I accessed the webserver and confirmed it was spitting out a duplicate `Content-Length` header.

[kodi.log](https://github.com/xbmc/xbmc/files/7797418/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

```
Traceback (most recent call last):
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/client_proto.py", line 213, in data_received
    messages, upgraded, tail = self._parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 551, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadHttpMessage: 400, message='Duplicate Content-Length'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/jsonrpc_async/jsonrpc.py", line 33, in send_message
    response = await self._request(data=message.serialize())
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 900, in start
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Duplicate Content-Length', url=URL('http://192.168.0.100:8080/jsonrpc')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/pykodi/kodi.py", line 164, in ping
    response = await self._server.JSONRPC.Ping()
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/jsonrpc_async/jsonrpc.py", line 35, in send_message
    raise TransportError('Transport Error', message, exc)
jsonrpc_base.jsonrpc.TransportError: ("Error calling method 'JSONRPC.Ping': Transport Error", ClientResponseError(RequestInfo(url=URL('http://192.168.0.100:8080/jsonrpc'), method='POST', headers=<CIMultiDictProxy('Host': '192.168.0.100:8080', 'Content-Type': 'application/json', 'Accept': 'application/json-rpc', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'Python/3.9 aiohttp/3.8.1', 'Authorization': 'Basic ******', 'Content-Length': '104')>, real_url=URL('http://192.168.0.100:8080/jsonrpc')), (), status=400, message='Duplicate Content-Length'))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/robertkingston/Documents/pykodi-testing/test.py", line 19, in <module>
    asyncio.run(test())
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/robertkingston/Documents/pykodi-testing/test.py", line 11, in test
    await kodi.ping()
  File "/Users/robertkingston/Documents/pykodi-testing/venv/lib/python3.9/site-packages/pykodi/kodi.py", line 170, in ping
    raise CannotConnectError from error
pykodi.kodi.CannotConnectError
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux 5.15.10 / Arch
 - Kodi version: 19.3-2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by Karlson2k**
I started this PR as a fix for https://github.com/xbmc/xbmc/issues/20759

While fixing duplicated `Content-Length:` headers, I discovered that Kodi uses libmicrohttpd (MHD) API incorrectly. Responses for `HEAD` requests are formed as responses with zero-length body. This is incorrect.
MHD API uses the same responses for `GET` and `HEAD` requests. When response is used to answer `GET` request, it is completely sent, including body. When the same response is used to answer `HEAD` request, response body is not sent (even if body has non-zero length).

According to HTTP RFCs, reply to `HEAD` requests should be exactly the same as reply for the `GET` requests, but reply body must not be sent.

In this PR I fixed improper use of MHD API.

This PR is fixing several things:
* Response for `HEAD` requests are handled in exactly the same way as responses for `GET` requests (as per RFC), now response headers for `HEAD` request are **exactly** the same as in response for similar `GET` request.
* Fixed wrong `Content-Length: 0` header always present in replies for `HEAD` request. This may fix a number of problems in clients that use Kodi HTTP interface.
* Fixed duplicated `Content-Length:` headers in all responses.
* Unrelated small optimisation suggested by @lrusak 
* Fixed run-time warning in log at startup.
* Fixed order of initialization parameters to avoid run-time warning at startup.

### CODE REVIEW

**Comment by lrusak** [comment]
When reviewing it's helpful to disable whitespace changes in some cases. In the case of this PR it reduces the amount of lines changes quite a lot. You can see it here https://github.com/xbmc/xbmc/pull/21019/files?w=1

|whitespace|additions|deletions|
|---|---|---|
|with|+92|−126|
|witout|+4|−38|

File: xbmc/network/WebServer.cpp [hunk 1]
```diff
@@ -1425,12 +1403,9 @@ MHD_RESULT CWebServer::AddHeader(struct MHD_Response* response,
   if (CServiceBroker::GetLogging().CanLogComponent(LOGWEBSERVER))
     m_logger->debug("[OUT] {}: {}", name, value);
 
-#if MHD_VERSION >= 0x00096800
   if (name == MHD_HTTP_HEADER_CONTENT_LENGTH)
-  {
-    MHD_set_response_options(response, MHD_RF_INSANITY_HEADER_CONTENT_LENGTH, MHD_RO_END);
-  }
-#endif
+    m_logger->warn("Attempt to override MHD automatic \"Content-Length\" header");
```
Comment (lrusak) [inline xbmc/network/WebServer.cpp:1407]: Would be nice if this change was split into a separate commit as it seems to change the behaviour (logical commits, etc). I'm not really that worried about it though.

File: xbmc/network/WebServer.cpp [hunk 2]
```diff
@@ -827,112 +822,98 @@ MHD_RESULT CWebServer::CreateFileDownloadResponse(
...
-    if (handler->IsRequestRanged())
-    {
-      if (!request.ranges.IsEmpty())
-        context->ranges = request.ranges;
-      else
-        HTTPRequestHandlerUtils::GetRequestedRanges(request.connection, fileLength,
-                                                    context->ranges);
-    }
+  uint64_t totalLength = 0;
+  std::unique_ptr<HttpFileDownloadContext> context(new HttpFileDownloadContext());
```
Comment (lrusak) [inline xbmc/network/WebServer.cpp:826]: would be nice to update this to use make_unique but not required.
```suggestion
  std::unique_ptr<HttpFileDownloadContext> context = std::make_unique<HttpFileDownloadContext>();
```

**Review by lrusak — COMMENTED** [review]
Seems like the right thing to do. The only thing I'll add is that should our tests be amended to support the new behaviour of HEAD requests?

**Comment by Karlson2k** [comment]
@lrusak Applied all of your suggestions. Also updated PR description to make it clearer.

File: xbmc/network/WebServer.cpp (hunk 2 above)
Comment (Karlson2k) [reply xbmc/network/WebServer.cpp]: Applied.

File: xbmc/network/WebServer.cpp (hunk 1 above)
Comment (Karlson2k) [reply xbmc/network/WebServer.cpp:1405]: Makes sense. Separated changes.

**Comment by Karlson2k** [comment]
> Seems like the right thing to do. The only thing I'll add is that should our tests be amended to support the new behaviour of HEAD requests?

Current set of tests passed just fine with this changes. Do you think it's needed to add some additional tests?

**Comment by Karlson2k** [comment]
I'm working on additional checks in the tests.

**Comment by Karlson2k** [comment]
Added checks in tests.
Checked that not more than one `Content-Length` header is present or exactly one Content-Length` header is present (in some tests).
So it is not an "adaptation" of the tests, it is more check that bug from https://github.com/xbmc/xbmc/issues/20759 is fixed.

**Review by garbear — APPROVED** [review]
Welcome back!!! No problems that I can see, so +1

**Review by lrusak — APPROVED** [review]
Thank you for providing additional tests and going the extra mile to make some other improvements. 👍
