### PR TITLE
[FFmpegExtraData] Cleanups + fix a crash

### LINKED ISSUE #23285: Segfault in ffmpeg demux in m2ts testfile
### Describe the bug
Here is a clear and concise description of what the problem is:

Dolby Helicopter demo crashes ([Link](https://drive.google.com/file/d/0BwxFVkl63-lENElIcC1xTnF2Yk0/view?usp=sharing&resourcekey=0-1_ByUhiruAwxfSNqW4ryAQ)) on stop. Could potentially be a regression introduced with the ffmpeg 6 upgrade. Stacktrace shows ffmpeg demux related stuff. Crashes at least on Android and webOS nightlies

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No segfault

## Actual Behavior

Segfault

### To Reproduce

1. Download [Helicopter Demo]( https://drive.google.com/file/d/0BwxFVkl63-lENElIcC1xTnF2Yk0/view?usp=sharing&resourcekey=0-1_ByUhiruAwxfSNqW4ryAQ)
2. Play the file
3. Stop playback
4. Crash

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/uluzerical.kodi

Stacktrace:
```
#0  __libc_do_syscall () at libc-do-syscall.S:49
#1  0xf7a9f456 in __libc_signal_restore_set (set=0xd98fa280) at ../sysdeps/unix/sysv/linux/internal-signals.h:86
#2  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:48
#3  0xf7a90962 in __GI_abort () at abort.c:79
#4  0xf7ac6874 in __libc_message (action=action@entry=do_abort, fmt=<optimized out>)
    at ../sysdeps/posix/libc_fatal.c:155
#5  0xf7acb646 in malloc_printerr (str=<optimized out>) at malloc.c:5346
#6  0xf7accc30 in _int_free (av=0xf7b6b59c <main_arena>, p=0xd6491ce8, have_lock=<optimized out>) at malloc.c:4314
#7  0x01ddcd34 in avcodec_parameters_free ()
#8  0x02822458 in ff_free_stream ()
#9  0x02822604 in avformat_free_context ()
#10 0x0282bb24 in avformat_close_input ()
#11 0x009df998 in CDVDDemuxFFmpeg::Dispose() ()
#12 0x009dfa30 in CDVDDemuxFFmpeg::~CDVDDemuxFFmpeg() ()
#13 0x009dfa70 in CDVDDemuxFFmpeg::~CDVDDemuxFFmpeg() ()
#14 0x00a1b450 in CVideoPlayer::OnExit() ()
#15 0x00b87df4 in CThread::Action() ()
#16 0x00b88a6c in std::thread::_State_impl<std::thread::_Invoker<std::tuple<CThread::Create(bool)::{lambda(CThread*, std::promise<bool>)#1}, CThread*, std::promise<bool> > > >::_M_run() ()
#17 0x02d76a44 in execute_native_thread_routine ()
#18 0xf7ec5898 in start_thread (arg=0xf2986682) at pthread_create.c:477
#19 0xf7b110ec in ?? () at ../sysdeps/unix/sysv/linux/arm/clone.S:73 from /lib/libc.so.6
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [X] webOS

 - Operating system version/name: Android / webOS
 - Kodi version: 21 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by neo1973**
## Description
Fixes some oversights from the initial implementation and a crash caused by a heap-use-after-free.

## Motivation and context
Fix #23285.

## How has this been tested?
File from #23285 is played and address sanitizer is happy.

## What is the effect on users?
No crashes when playing videos.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/FFmpeg.cpp [hunk 1]
```diff
@@ -140,11 +140,14 @@ FFmpegExtraData::FFmpegExtraData(size_t size)
 {
   if (!m_data)
     throw std::bad_alloc();
+  // E.g. AVCodecParameters expects the padding to be zeroed
+  std::memset(m_data + m_size, 0, AV_INPUT_BUFFER_PADDING_SIZE);
```
Comment (lrusak) [inline xbmc/cores/FFmpeg.cpp:144]: `av_mallocz` instead?

**Comment by sundermann** [comment]
Can confirm this fixes the issue

File: xbmc/cores/FFmpeg.cpp (hunk 1 above)
Comment (neo1973) [reply xbmc/cores/FFmpeg.cpp]: Yeah, probably isn't more expensive to have the full buffer initialized :+1:

**Comment by lrusak** [comment]
jenkins build this please

**Comment by neo1973** [comment]
Jenkins build this please.
