### PR TITLE
[msvcrt] Fix buffer overflow due to fixed "var" size

### LINKED ISSUE #25868: Kodi crashes on startup before it can write any logs
### Describe the bug
Here is a clear and concise description of what the problem is:

On my machine, Kodi (current + since at least v19, nightlies, dev builds) is crashing (i.e. silently exiting the process) before writing anything in the logs or showing anything on the screen. basically starting kodi looks like nothing happens, since the process exists so fast.

I tried all the debugging tutorials, but they all rely on the logfile, which in my case, is created but has 0 bytes in it.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi starts

## Actual Behavior

Kodi does not start. Clean install, no plugins, no profile. Nothing matters.

## Possible Fix

Debugging is needed.

### To Reproduce

1. Start Kodi
2. Observe that nothing is happening at all, Kodi exits immediately and silently
3. PROFIT!

### Debuglog

The debuglog can be found here:
None created

Is there any "debug" build which I can use to somehow diagnose further whats happening there? It's been 20 years since I debugged C++, not sure what to do.

### Screenshots 
Here are some links or screenshots to help explain the problem:

None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win10 + Win11
 - Kodi version: 19-current, incl. dev and nightly

Happened with Win10, which I upgraded to Win11 and the problem persists.
I have HyperV with a bunch ov VMs on the machine with some "non-standard" config.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

"var" has fixed size of 64 but the string length can be more bigger

## Motivation and context

fix #25868
## How has this been tested?

only debug, ~i wait confirm from user~ user confirmed to works https://github.com/xbmc/xbmc/issues/25868#issuecomment-2436234249
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by thexai — APPROVED** [review]
Tested and reproduced the crash and confirmed the fix.

It's rare to have a 64 character env variable name but it's definitely possible.

env

File: xbmc/cores/DllLoader/exports/emu_msvcrt.cpp [hunk 1]
```diff
@@ -1819,16 +1819,18 @@ extern "C"
 
       if (value_start != NULL)
       {
-        char var[64];
+        const size_t varSize = value_start - envstring;
+        char* var = static_cast<char*>(std::malloc(varSize + 1));
+
```
Comment (neo1973) [inline xbmc/cores/DllLoader/exports/emu_msvcrt.cpp:1824]: I would prefer to see the check if ` malloc` succeeded directly after the allocation. The way it is currently it would leak memory if only one `malloc` failed. Not really a big issue in practice but something static analyzers will complain about. 
```suggestion
        const size_t varSize = value_start - envstring;
        char* var = static_cast<char*>(std::malloc(varSize + 1));

        if (!var)
          return -1;
```

**Review by neo1973 — APPROVED** [review]
