### PR TITLE
[Subtitles] Removed legacy GUI text rendering in flavor of LibAss rendering

### LINKED ISSUE #15902: Subtitles are rendered outside of videowindow control
### Describe the bug
Here is a clear and concise description of what the problem is:

When a videowindow control is used with dimensions smaller than full screen, subtitles (tested, external srt sub) are rendered outside of the videowindow and are not scaled to videowindow dimensions.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The displayed subtitle is rendered using the subtitle settings and scaled/positioned within the dimensions of the videowindow control as can be observed in Kodi 17.

## Actual Behavior

The subtitle is rendered full-size (at the display resolution/aspect).  It appears to be positioned horizontally correctly, but vertically it is at the bottom of the screen, not within the videowindow control.

### To Reproduce

1.   Add video with external subtitle (Tested: episode of tv show tested: srt format)
2.  Start playback of video with subtitle enabled
3.  View playing video in a skin window with a videowindow control (tested:  Custom window in estuary:
https://pastebin.com/6Zsdc2cH

When settings/player/language subtitle position is set to "fixed", the subtitle is rendered in the proper x-position but at the bottom of the screen, not the bottom of the videowindow control as experienced in Kodi 17.  In addition, the subtitles are not scaled to the videowindow control dimensions.

If the language settings are changed to subtitle position "bottom of video", the subtitles are rendered within the videowindow control, but are not scaled.

Tested in both full screen window and true full screen with DXVA/pixel shaders/software rendering.  All other system display settings are default.

### Debuglog

The debuglog can be found here:
https://pastebin.com/pKjDPUm6

### Screenshots 
Here are some links or screenshots to help explain the problem:

Sub position fixed:
<a href="https://imgur.com/DpPdnIS"></a>

Sub position bottom of video:
<a href="https://imgur.com/LuoweUm"></a>

Kodi 17 Sub position fixed comparison:
<a href="https://imgur.com/28lcMVv"></a>

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Win 7 SP1 x64
 - Kodi version:  18.2 RC1 190410

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Removed legacy GUI text rendering in flavor of LibAss rendering to fix problems that are difficult to solve and provide more features.

## Motivation and context

The current rendering of text-type subtitles has several problems that are difficult to solve, mainly:
- Wrong subtitles positioning in videowindow (#15902)
- Wrong subtitles positions in kodi windowed mode or too lower/higher resolutions (#19698)
- Difficult to implement any kind of support for dynamic positioning of subtitles with tags position (like `{\a4}`) often used

From https://github.com/xbmc/xbmc/issues/15902#issuecomment-485227401 comment:
>text subtitles do not follow the schema of the other types and violate the design of rendering of video player. They delegate rendering to some gui component which expects this kind of transformation matrix. For gui this is done at the beginning of gui rendering but here we see an ugly hack that lacks any sense of a reasonable design.

Reading the comments of the Issue, devs agree to drop legacy GUI subtitles text rendering in flavor of LibAss rendering and semplify all rendering code, thus having a more complete support for many subtitles features that are now unsupported and making it easier to manage.

There are many changes, I have tried to split the changes into several commits as best I could, not always easy.

**New features:**
- Introduced LibASS rendering on all text type subtitles streaming codecs and parsers
- Add support to underline style
- Add support to subtitle dynamic positioning by using subtitles tags (e.g. `{\a4}`)
- Add new subtitle setting `Override ASS / SSA subtitles styles` this can be used to override the embedded ASS/SSA styles with the kodi subtitle settings (like font styles, positions, border, colors...)

**Changes:**
- Removed `assfixedworks` from advanced setting xml now not more needed
- Changes to the `Subtitle position on screen` settings:
  o `Fixed` entry is renamed to `Manual` -> **behaviour is similar** but now is used only in conjuction with video calibration settings, to set the position on screen manually
  o All others entries is same as before
  o The default value is now `Bottom of video`
- Changed the default font size from 28 to 42, will result the same font size of regular kodi release, this is due because the wrong proportion between font size points and pixels size has been fixed

**Fixed problems:**
- Fixed wrong text position issue #19698
- Fix possible style problem #19911
- ~SRT subtitles: fix wrong order of subtitles when multiple subtitles entry have same timestamp/duration (from forum: https://forum.kodi.tv/showthread.php?tid=359359)~ user file malformed
- VPlayer subtitles: fix not displaying multiple lines
- SAMI subtitles: fixed multilanguage support, was completely broken (also if you specify the language in filename)
- Fixed text position off screen after window resize of OSD video info debug (alt+o)
- "Fixed" or better is alternative way (maybe to investigate in future) on SSA/LibAss flickering with parsers (streams codecs not affected), when subtitles entries have close start/stop timestamp between them, see CreateOverlay method in SubtitlesAdapter.cpp
- Fixed #15902
- Fixed wrong text size on screen, the proportion between points/pixels was wrong
- All subtitle settings can be now changed when in playback without side effects

**TODO:**

- [x] ~Test dynamic positioning of subtitles with InputStream Adaptive (currently only for WebVTT)~
- [x] ~Rework and add new setting to override ASS/SSA subtitles styles and position (usually for embedded style with file/stream)~
- [ ] I am not sure about this code https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp#L189-L201 the offset affects the overlays start/stop but not the actual LibAss rendering based on Events(knot to fixed start/stop pts), this code should not work, i havent found a good way to test it. Reference PR #4049 - Need to be investigated and maybe changed behaviour in other PR (i suspect has never worked with previous Libass implementation and of course nothing changed with this PR)
- [x] ~To fix SRT overlapping/lines order cases **UPDATE**: Used `Tester for overlapped subtitles` in https://ale5000.altervista.org/subtitles.htm Are partially fixed but randomly are displayed with wrong order, not found the cause yet~ there is no error in the code, the problem is that **libass rendering that is not consistent when you seek forward/backward the video** this is known to the developers and not documented, the current libass rendering does not take into account the whole sequence of events when you seek and this cause subtitles mixing when overlapped

There are a lot of meat here, be patient if it is not all perfect i am learning C++.

## How has this been tested?

Tests are done on Windows 10 only:
- tests with external subtitles formats (also converted and manually edited)
- tests with subtitles by using InputStream Adaptive and a video streaming with WebVTT (Kodi will fallback always to Overlay Codec Text because currently ISA convert always to SRT format)
- tests with videos with embedded subtitles ass/srt/ffmpeg
- tests with some SRT files from https://ale5000.altervista.org mostly compatible
- test with videos with CC subtitles (from https://github.com/xbmc/xbmc/pull/20010#issuecomment-894673804, https://github.com/xbmc/xbmc/pull/20010#issuecomment-894760930 and others)
- test TX3G video with text styles
- test ASS subtitles cases, with and without set styles override settings cases
- test ASS subtitles cases, with font override set
- test persistence of subtitles after video video seek forwards or backwards
- test changing all subtitles settings, during playback
- compared the size of subtitles displayed on screen from the old legacy GUI rendering to the Libass rendering, through overlapping screenshots
- check the subtitles text size on screen, after window resizing
- check if enabling the ASS style override on Kodi settings, the subtitles text size on screen is correct (the ASS style override affect the scale, need to be calculated differently or cause wrong text size)
- tested WebVTT dynamic text positions by using InputStreamAdaptive, see experimental implementation from https://github.com/CastagnaIT/inputstream.adaptive/tree/webvtt_positions

## Screenshots (if appropriate):
Some basic screenshots, **all with font style Normal** (usually kodi default to Bold) to see bold style difference
Before:
Screenshot01orig
After:
immagine

### With background box color:
Before:
Screenshot02orig
After:
immagine

### Changes to the subtitle settings:
overr1
overr2

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
if there are changes to suggest please comment,
after that i will apply jenkins format changes and i go on

**Comment by Essam3152** [comment]
@CastagnaIT Is it possible to add an option for changing the subtitles' border style for the outline and shadow in this PR? These posts explain the problem.

https://forum.kodi.tv/showthread.php?tid=337741
https://forum.kodi.tv/showthread.php?tid=344515
https://forum.kodi.tv/showthread.php?tid=344515&pid=2878169#pid2878169

**Comment by CastagnaIT** [comment]
hi @Essam3152 time ago I had tried playing with the border size
but apparently from the specifications there is not much range to modify the edges
I will try again, I will let you know

**Comment by Essam3152** [comment]
@CastagnaIT Thank you, from the screenshots for before and after with background box color this problem seems to be much less.

**Comment by bossanova808** [comment]
Is it possible to make the underlining continuous, rather than separate for each character?  Visually a continuous line would be a lot nicer...

**Comment by fuzzard** [comment]
Can i suggest the bikeshedding and feature requests be handled outside of this PR.

Keep this to what it is, a replacement of existing functionality. Extend the features after this goes in so review and testing can be handled appropriately.

**Comment by bossanova808** [comment]
With all due respect, it's a WIP PR, and with a specific comment of:

> ` i created the PR for feedbacks`

...but if a forum thread is created, happy to discuss there.

**Comment by fuzzard** [comment]
And if something extra keeps being added/requested all the time, it'll just end up as another WIP PR that never gets merged.

Its difficult to keep having to review a PR when the goal posts are constantly moved. Why would someone review, if they then just have to re-review multiple times to check again and again.

As i said, Keep the PR to something managable, or it just wont ever get anywhere

**Comment by CastagnaIT** [comment]
>Keep this to what it is, a replacement of existing functionality. Extend the features after this goes in so review and testing can be handled appropriately.
> And if something extra keeps being added/requested all the time, it'll just end up as another WIP PR that never gets merged.
> As i said, Keep the PR to something managable, or it just wont ever get anywhere

yes agreed, i am aware of the current size,
i will do different PR's, however currently is in Draft not ready yet

@bossanova808 In everything I'm modifying, I'm trying to keep all the pre-existing behaviour of the old GUI rendering and adding a few things that are closely related to the new LibAss rendering,
the mentioned comment is to evaluate the implementation of the PR code, not to request new features

**Comment by CastagnaIT** [comment]
@fuzzard if the PR is currently too big i can delete the last commit:

`Implemented ASS style override and improved position settings`

this commit is required to fix position settings (which is related to the ASS styles)
that are not working well
please le me know if you prefeer i do another PR for this and lighten this

**Comment by fuzzard** [comment]
No its fine, just trying to recommend not getting pulled into too much scope creep. Do what you have done is fine by me, deal with the changes/feature requests after the base change is done.

I know @enen92 was dabbling in this area a little while ago essentially looking to do the same thing. Im sure he'll chime in with any info when he has some time

**Comment by CastagnaIT** [comment]
yes i talk with him on slack about some problems where suggested me some changes
currently i am reworking all commits to make jenkins happy
because its last notification is crashed?!? up^^^

**Comment by Essam3152** [comment]
@CastagnaIT If you need any tests on Windows I could try to help If you could compile a Windows 64bit version, Kodi should remember the subtitles position after you change it from Video calibration and restart Kodi, this was a very important fix done by @peak3d long time ago.

**Comment by CastagnaIT** [comment]
@Essam3152 donwload here portable version: https://www.dropbox.com/s/pqyz9zaevq96x2o/Kodi20_Portable_build1.zip?dl=1

**Comment by Essam3152** [comment]
@CastagnaIT Thank you, this is @peak3d PR for fixing the problem of not remembering the subtitle position after a restart.

https://github.com/xbmc/xbmc/pull/15516

**Comment by CastagnaIT** [comment]
i have found now `SRT capibility file tester` here: https://ale5000.altervista.org/subtitles.htm
i found problems with colors and positions

for the positions problem i suspect that the solution that proposed to me @enen92 to merge all entries with same timestamps (and create a single Event) could be a solution to solve the problem of reversed order lines (https://forum.kodi.tv/showthread.php?tid=359359)

but cause other side effects, if more entries have same timestamp but different alignment tag,
LibAss read only the first alignment tag and ignore all others, the all entries text are wrongly merged

however i think solve all SRT capibility tester file cases is difficult

**Comment by CastagnaIT** [comment]
> but still happens when I use the the Netflix add-on it looks like this (Vikings season 1 episode 1)

thanks for point it out a example movie,
the problem is that Netfx has WebVTT then use InputStreamAdaptive subtitle parser, that transfer the parsed chunks to the kodi subtitle parser, these multiple steps probably makes a mess with lines, for now we hava to ensure that embedded subtitles in videos and external files works good, with regard to ISA will have to be studied what changes/adaptions is needed later after this PR

> Automatic being the default in Kodi for the position of the subtitles might be confusing for the users who do not know about this option, it might be better to make Manual as default. 

I wish to keep Manual for Video calibration purpose only, because is more clear also in the source code how works

I was thinking some time ago about changing the functionality again, something like this:

Bottom - Will be the _default setting_
Manual - for Video calibration only
Below/Top/Above - as name say

^^ in this case possible alignment/position tags can force move the text on screen
i think this is more clear

**Comment by CastagnaIT** [comment]
@Essam3152 i have done the changes, if you can give a look
New build [Win64]: https://www.dropbox.com/s/xbyug25afqbezo9/Kodi20_Portable_build2.zip?dl=1
If you can test ASS subtitles (embedded on videos or external files) with the new ASS style override settings combinations

NOTE: i have not done yet the fix for overlapped SRT lines, i try wait an answer from libass dev

**Comment by Essam3152** [comment]
@CastagnaIT I removed the tags from this webvtt file then converted it to ASS format using the latest Subtitle Edit 3.6.1.

[The.Witcher.S01E01.en[cc].zip](https://github.com/xbmc/xbmc/files/6941125/The.Witcher.S01E01.en.cc.zip)

https://github.com/SubtitleEdit/subtitleedit/releases

**Comment by CastagnaIT** [comment]
The problem with converters are that not always can automatically add the metadata
then you have to add manually, subtitleedit has the appropriate menus to edit ASS metadata
however is another case that need to be solved because the lack of this data causes problems mentioned
and surely other users do not bother to add metadata...

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 1]
```diff
@@ -38,12 +39,67 @@ class CDVDSubtitlesLibass
...
+  /*!
+  * \brief Add an ASS event to show a subtitle on a specified time
+  * \param startTime The PTS start time of the Event
+  * \param stopTime The PTS stop time of the Event
+  * \return Return the Event added, otherwise NULL if fails
+  */
+  ASS_Event* AddEvent(std::string text, double startTime, double stopTime);
+
+  /*!
+  * \brief Append text to the specified event (\\n will be add before the text)
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:64]: grammar: `added` instead of `add`.

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 2]
```diff
@@ -38,12 +39,67 @@ class CDVDSubtitlesLibass
...
   bool DecodeDemuxPkt(const char* data, int size, double start, double duration);
+
+  /*!
+  * \brief Create a new ASS track with a default ASS style (used on ASS events)
+  * \param useDebugStyle Use style text/color/position for debug info purpose
+  * \return True if has success
+  */
+  bool CreateTrack(bool useDebugStyle = false);
+  /*!
+  * \brief Create a new ASS track based on a SSA buffer
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:50]: grammar: `an SSA` instead of `a SSA`, because the leading sound ("*es*") governs whether you use "a" or "an", not the actual letter of the first word.

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 3]
```diff
@@ -38,12 +39,67 @@ class CDVDSubtitlesLibass
 
   bool DecodeHeader(char* data, int size);
   bool DecodeDemuxPkt(const char* data, int size, double start, double duration);
+
+  /*!
+  * \brief Create a new ASS track with a default ASS style (used on ASS events)
+  * \param useDebugStyle Use style text/color/position for debug info purpose
+  * \return True if has success
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:46]: grammar: maybe `True if success, false if error`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 4]
```diff
@@ -141,32 +168,232 @@ bool CDVDSubtitlesLibass::DecodeDemuxPkt(const char* data, int size, double star
...
+  if (!m_track)
+  {
+    CLog::Log(LOGINFO, "CDVDSubtitlesLibass: Creating new ASS track");
+    m_track = ass_new_track(m_library);
+    m_track->Timer = 100.;
+    // Set fixed values to PlayRes to allow the use of style override code for positioning
+    m_track->PlayResX = 1280;
+    m_track->PlayResY = 720;
+    m_track->Kerning = true; // Font kerning improves the letterspacing
+    m_track->WrapStyle = 1; // The line feed \n not breaks but wrap (instead \N breaks)
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:186]: grammar: `The line feed \n doesn't break but wraps (instead \N breaks)`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 5]
```diff
@@ -141,32 +168,232 @@ bool CDVDSubtitlesLibass::DecodeDemuxPkt(const char* data, int size, double star
...
+  if (subalign == SUBTITLE_ALIGN_TOP_INSIDE || subalign == SUBTITLE_ALIGN_TOP_OUTSIDE)
+    style->Alignment = 6;
+  else
+    style->Alignment = 2;
+
+  // Margins (in pixels)
+  style->MarginL = 20 * scale;
+  style->MarginR = style->MarginL;
+  style->MarginV = 20 * scale; // Vertical (direction depends from alignment)
+  //style->Blur = 2; // Blur edges
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:331]: Commented code?

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 6]
```diff
@@ -141,32 +168,232 @@ bool CDVDSubtitlesLibass::DecodeDemuxPkt(const char* data, int size, double star
...
+  int subalign = settings->GetInt(CSettings::SETTING_SUBTITLES_ALIGN);
+  if (subalign == SUBTITLE_ALIGN_TOP_INSIDE || subalign == SUBTITLE_ALIGN_TOP_OUTSIDE)
+    style->Alignment = 6;
+  else
+    style->Alignment = 2;
+
+  // Margins (in pixels)
+  style->MarginL = 20 * scale;
+  style->MarginR = style->MarginL;
+  style->MarginV = 20 * scale; // Vertical (direction depends from alignment)
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:330]: grammar: `depends on alignment`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 7]
```diff
@@ -200,3 +427,86 @@ int CDVDSubtitlesLibass::GetNrOfEvents() const
...
+  int eventId = ass_alloc_event(m_track);
+  if (eventId >= 0)
+  {
+    ASS_Event* event = m_track->events + eventId;
+    event->Start = DVD_TIME_TO_MSEC(startTime);
+    event->Duration = DVD_TIME_TO_MSEC(stopTime - startTime);
+    event->Style = m_track->default_style;
+    event->ReadOrder = eventId;
+    // Many subtitle formats use \r\n as line break,
+    // we have to remove all \r because it cause to display empty box "tofu"
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:457]: grammar: `because it causes the line to display empty box "tofu"`

Comment (garbear) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:457]: and below

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserVplayer.cpp [hunk 8]
```diff
@@ -27,59 +32,72 @@ bool CDVDSubtitleParserVplayer::Open(CDVDStreamInfo &hints)
...
+
+        if (PTSDuration < defaultDuration)
+          lastEvent->Duration = DVD_TIME_TO_MSEC(PTSDuration);
       }
-      pPrevOverlay = pOverlay;
-      for (int i = 0; i < 3 && !lines[i].empty(); i++)
-          pOverlay->AddElement(new CDVDOverlayText::CElementText(lines[i].c_str()));
 
-      m_collection.Add(pOverlay);
+      // A single line can contains multiple lines splitted by |
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserVplayer.cpp:78]: grammar: `A single line can contain multiple lines split by |`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSami.cpp [hunk 9]
```diff
@@ -32,67 +34,131 @@ bool CDVDSubtitleParserSami::Open(CDVDStreamInfo &hints)
...
+            m_libass->AddEvent(convText, lastPTSStartTime, lastPTSStartTime + defaultDuration);
+      }
     }
-    if(pOverlay)
-      TagConv.ConvertLine(pOverlay, text, strlen(text), lang);
   }
-  m_collection.Sort();
+
+  // Create a single overlay to avoid subtitles flickering when events have close timing,
+  // this seem due to a delay in the turn on/off of the graphic renderer,
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSami.cpp:147]: grammar: `seem` -> `seems`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSami.cpp [hunk 10]
```diff
@@ -32,67 +34,131 @@ bool CDVDSubtitleParserSami::Open(CDVDStreamInfo &hints)
...
-    lang = strClassID.c_str();
+  {
+    StringUtils::ToLower(strClassID);
+    langClassID = strClassID.c_str();
+  }
+
+  ASS_Event* lastEvent = NULL;
+  double lastPTSStartTime = 0;
+  std::string lastLangClassID;
+  // SAMI synchronization provide only the start time value,
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSami.cpp:89]: grammar: `provide` -> `provides`

below:

`take` -> `takes`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSami.cpp [hunk 11]
```diff
@@ -32,67 +34,131 @@ bool CDVDSubtitleParserSami::Open(CDVDStreamInfo &hints)
...
+      std::string langName = TagConv.m_Langclass[i].Name;
+      StringUtils::ToLower(langName);
+      if (strFileName.find(langName) != std::string::npos)
       {
         strClassID = TagConv.m_Langclass[i].ID;
-        StringUtils::ToLower(strClassID);
         break;
       }
     }
+    // No language specified or found try select the first class ID
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSami.cpp:72]: grammar: `No language specified or found, try to select the first class ID`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSami.cpp [hunk 12]
```diff
@@ -32,67 +34,131 @@ bool CDVDSubtitleParserSami::Open(CDVDStreamInfo &hints)
...
   std::string strClassID;
-  strFileName = URIUtils::GetFileName(m_filename);
+  strFileName = StringUtils::ToLower(URIUtils::GetFileName(m_filename));
 
   CDVDSubtitleTagSami TagConv;
   if (!TagConv.Init())
     return false;
   TagConv.LoadHead(m_pStream.get());
+  // If there are more languages contained in a file,
+  // try get the language class ID that match to the language name
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserSami.cpp:58]: grammar: `try getting the language class ID that matches the language name`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h [hunk 13]
```diff
@@ -53,14 +54,20 @@ class CDVDSubtitleParserText
...
+                         const std::string& filename,
+                         const char* name)
+    : CDVDSubtitleParserCollection(filename), m_pStream(std::move(stream)), parserName(name)
   {
   }
 
   ~CDVDSubtitleParserText() override = default;
 
+  /*
+   * return parser name
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:67]: Could be improved to `\brief Returns parser name`

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayText.h [hunk 14]
```diff
@@ -8,150 +8,23 @@
 
 #pragma once
 
+#include "../../DVDSubtitles/DVDSubtitlesLibass.h"
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayText.h:11]: Relative include intended?

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h [hunk 15]
```diff
@@ -8,8 +8,11 @@
 
 #pragma once
 
+#include "../../DVDSubtitles/DVDSubtitlesLibass.h"
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h:11]: Relative import intended?

File: addons/resource.language.en_gb/resources/strings.po [hunk 16]
```diff
@@ -22541,3 +22541,33 @@ msgstr ""
 msgctxt "#39153"
 msgid "Windowing system:"
 msgstr ""
+
+#. Description of setting with label #39156 "Override ASS / SSA subtitles styles"
```
Comment (garbear) [inline addons/resource.language.en_gb/resources/strings.po:22545]: Great description! Could the strings below use descriptions too?

**Comment by garbear** [comment]
Sorry to drop so many grammar errors! The native speaker in me finds it easier to read comments without mental breaks when a grammar rule is broken

**Comment by CastagnaIT** [comment]
> 
> 
> Sorry to drop so many grammar errors! The native speaker in me finds it easier to read comments without mental breaks when a grammar rule is broken

no fear i am aware that my english is bad, i was expecting corrections

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayText.h (hunk 14 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayText.h:11]: not really i have copied from existing code, not knowing the reason of this relative case i have kept as is
i will change

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h (hunk 15 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h:11]: same reply before

File: addons/resource.language.en_gb/resources/strings.po (hunk 16 above)
Comment (CastagnaIT) [reply addons/resource.language.en_gb/resources/strings.po:22545]: if you mean this, i can add helper string for translators on all enum values below

**Comment by FernetMenta** [comment]
I suggest to test this with closed captions too. Note that CC are not static. Dialogs are often expanded by words. This might be difficult to handle with conversion to ASS.

**Comment by CastagnaIT** [comment]
Updated test build [Win64]: https://www.dropbox.com/s/0jm8m3vt7szopgm/Kodi20_Portable_build3.zip?dl=1

@FernetMenta have you some idea where i can find these particular CC subtitles to download/test?

**Comment by Essam3152** [comment]
@CastagnaIT Everything is working great now with the ASS subtitles I got from converting the webvtt subtitles using Subtitle Edit.

**Comment by FernetMenta** [comment]
> Updated test build [Win64]: https://www.dropbox.com/s/0jm8m3vt7szopgm/Kodi20_Portable_build3.zip?dl=1
> 
> @FernetMenta have you some idea where i can find these particular CC subtitles to download/test?

@CastagnaIT here is a video I got when I implemented CC https://www.dropbox.com/s/xinhkng7i7ukivf/1023_20141209080000.mpg?dl=0
The text expands by letters or words and lines are shifted up when a new line starts. Select subtitle 2/2 when you play this video.

**Comment by FernetMenta** [comment]
Closed captions are muxed into the video stream. Hence you may get updates on the subs on every video frame. There shouldn't be any heavy weight conversions at decoding stage.

**Comment by FernetMenta** [comment]
@CastagnaIT the other samples I had for testing are still available: https://forum.kodi.tv/showthread.php?tid=144517&pid=1870871#pid1870871

**Comment by enen92** [comment]
Sorry for the delay, I've been with little to no time lately. I agree with Fernet, closed captions may be hard to implement and should be checked. Furthermore some times they have the so called "karaoke effect" that probably can be mimic with ASS \k tag (see https://aegi.vmoe.info/docs/3.1/ASS_Tags/).

I'd suggest you to try out the sample from https://github.com/xbmc/xbmc/issues/18845 to make sure you can replicate the same behaviour with ASS.

I'll look into the actual code at some point this week

**Comment by CastagnaIT** [comment]
thanks for the examples helped me understand how works
maybe ASS \k tag in some way could works
but there is the problem is that the decoder return every time also the previous text, e.g.:
(each line is a decode call)
```
HI
HITC
HITCHC
HITCHCOC
HITCHCOCK:
```

**Comment by CastagnaIT** [comment]
I think i have found a possible solution:
- add the first ass event with a default duration of 20 secs
- on each next decoder calls (that respect duration of 50ms):
will be replaced the duration of the last added event with the current start time
and then added a new event with the current text and default duration of 20 secs
- each events are blocks of 50ms

i have done a test and seem imitate the regular kodi version
I will do more tests

**Comment by enen92** [comment]
Thanks a lot to the pull request. I've looked briefly into the code (it will take a while), having looked myself into a similar approach, my first request is to avoid calling into libass from the parsers. Ideally things should be decoupled and abstracted, so consider following an adapter design pattern for them (https://refactoring.guru/design-patterns/adapter). The adapter should hold the reference to the libass class and translate the interface methods to the libass specific implementation.

It's a bit of common sense, if you look for instance to your Subrip parser implementation (https://github.com/xbmc/xbmc/pull/20010/files#diff-dc4386e17b46e331a62a0dbb9afe03c330d2005b374c53540ba2b200c1bb0781R34) the parser shouldn't need to know what an ASS_Track, ASS_Event, etc is (unless it's an ASS/SSA parser). Parsers should initialize an SubtitleAdapter which have CDVDSubtitlesLibass/libass as a member and provide a well defined interface that gets translated into libass calls

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleTagMicroDVD.cpp [hunk 17]
```diff
@@ -11,13 +11,14 @@
 #include "DVDCodecs/Overlay/DVDOverlayText.h"
 #include "utils/StringUtils.h"
 
-void CDVDSubtitleTagMicroDVD::ConvertLine(CDVDOverlayText* pOverlay, const char* line, int len)
+std::string CDVDSubtitleTagMicroDVD::ConvertLine(const char* line, int len)
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleTagMicroDVD.cpp:14]: I am pretty sure you can avoid the multiple copies of the string to the callee (specially because those strings can be quite big), unsure how to do it though. Maybe since the `std::string` is created in `ConvertLine` you can use `std::move` to move it to a string argument passed from the callee. @lrusak or @phunkyfish can probably advise better

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 18]
```diff
@@ -200,3 +450,128 @@ int CDVDSubtitlesLibass::GetNrOfEvents() const
...
+
+  int eventId = ass_alloc_event(m_track);
+  if (eventId >= 0)
+  {
+    ASS_Event* event = m_track->events + eventId;
+    event->Start = DVD_TIME_TO_MSEC(startTime);
+    event->Duration = DVD_TIME_TO_MSEC(stopTime - startTime);
+    event->Style = m_track->default_style;
+    event->ReadOrder = eventId;
+    // Many subtitle formats use \r\n as line break,
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:479]: At this point you shouldn't touch the string anymore, that's a job for the parser or tagger, the string should be const

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 19]
```diff
@@ -200,3 +450,128 @@ int CDVDSubtitlesLibass::GetNrOfEvents() const
     return 0;
   return m_track->n_events;
 }
+
+int CDVDSubtitlesLibass::AddEvent(std::string text, double startTime, double stopTime)
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:454]:
```suggestion
int CDVDSubtitlesLibass::AddEvent(std::string& text, double startTime, double stopTime)
```

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:454]: Please check if you really need to pass a `std:string` here as you'll endup feeding libass with a c_str

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 20]
```diff
@@ -38,12 +50,74 @@ class CDVDSubtitlesLibass
 
   bool DecodeHeader(char* data, int size);
   bool DecodeDemuxPkt(const char* data, int size, double start, double duration);
+
+  /*!
+  * \brief Create a new ASS track with a default ASS style (used on ASS events)
+  * \param useDebugStyle Use style text/color/position for debug info purpose
+  * \return True if success, false if error
+  */
+  bool CreateTrack(bool useDebugStyle = false);
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: this seems hackish. The libasshandler (this class) shouldn't need to know what a debug style is. You want to abstract the style into some kodi class or struct and feed it to the libasshandler instead. The handler should then be able to do the necessary mapping or conversion to something libass understands

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 21]
```diff
@@ -26,8 +29,17 @@ class CDVDSubtitlesLibass
   */
   void Configure();
 
-  ASS_Image* RenderImage(int frameWidth, int frameHeight, int videoWidth, int videoHeight, int sourceWidth, int sourceHeight,
-                         double pts, int useMargin = 0, double position = 0.0, int* changes = NULL);
+  ASS_Image* RenderImage(int frameWidth,
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:32]: the method has 11 arguments it's usually a sign something is not good. Maybe combine some of the arguments into some "options" struct and pass it instead

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 22]
```diff
@@ -38,12 +50,74 @@ class CDVDSubtitlesLibass
...
+  * \param startTime The PTS start time of the Event
+  * \param stopTime The PTS stop time of the Event
+  * \return Return the Event ID, otherwise ASSEVENT_NO_ID if fails
+  */
+  int AddEvent(std::string text, double startTime, double stopTime);
+
+  /*!
+  * \brief Append text to the specified event (\\n will be added before the text)
+  */
+  void AppendTextToEvent(int eventId, std::string text);
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:77]: any methods that are not consumed by any ASS/SSA class (ass parser and ass codec) shouldn't be publicly exposed to anyone else. Maybe your `KodiSubtitleAdapter` (my first comment) can be a friend class of this one

File: xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp [hunk 23]
```diff
@@ -823,6 +824,8 @@ void CVideoPlayerVideo::ProcessOverlays(const VideoPicture* pSource, double pts)
     for(it = overlays.begin(); it != overlays.end(); ++it)
     {
       double pts2 = (*it)->bForced ? pts : pts - m_iSubtitleDelay;
+      CLog::Log(LOGINFO, "CHIAMATA m_renderManager qui: m_iSubtitleDelay {}", m_iSubtitleDelay);
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp:827]: Italian comment :)
Can you explain why `subtitleOffset` was added here? Also please name all member functions as `m_*`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 20 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: this is used only from DebugRenderer only, we don't need to change libass style properties never,
i don't think it's worth spending a lot of time redefining more than 15 libass properties just to create a debug style used only by developers

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 24]
```diff
@@ -10,11 +10,14 @@
 
 #include "ServiceBroker.h"
 #include "cores/VideoPlayer/Interface/TimingConstants.h"
+#include "cores/VideoPlayer/VideoRenderers/OverlayRenderer.h"
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:13]: All the new includes are a bad sign. The Renderer calls the libass handler you shouldn't include the renderer here.

Settings are global for subtitles/text and define the user configured subtitle style, they are not specific to libass. I think this component should be self-contained: styles, resolution, etc should be propagated to this component not created by itself

File: xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp (hunk 23 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp:827]: whoops :D oversight
several Kodi developers have told me in the past to remove prefixes in new variables
here is different thing? only to understand

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 25]
```diff
@@ -141,32 +168,251 @@ bool CDVDSubtitlesLibass::DecodeDemuxPkt(const char* data, int size, double star
...
+    style->Outline = 1 * scale;
+    style->Shadow = 0;
+  }
+  else
+  {
+    // Compute the color to be used for the background (depending on the opacity)
+    UTILS::Color bgColor = bgColors[settings->GetInt(CSettings::SETTING_SUBTITLES_BGCOLOR)];
+    bgColor = ColorUtils::ChangeOpacity(bgColor, (100 - bgOpacity) / 100.0f);
+
+    style->BorderStyle = 4; // Opaque box + outline
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:323]: Please avoid magic numbers, define const values for them

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 20 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: It's pretty much irrelevant since the style should be computed by the `OverlayRenderer` (or `DebugRenderer`) and passed to the libass handler instead. So you'll need to abstract the style anyway, either for the regular subs or for the debug overlay (which will be always a fixed style).

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: I would rather create a new different method

File: xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp (hunk 23 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp:827]: I guess you might be confusing it with the hungarian notation (e.g. `m_ievents` to specify an integer) and not exactly the member identifier. But I can be wrong as well :)

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 20 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: this will make the code huge and heavy to understand...

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: i need to create a new style struct to pass all variables

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: theorising about doing this thing, i can not move it in the `OverlayRenderer` because i need create the ASS style before add the ASS events, then when the parser is just "Open"

File: xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp (hunk 23 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp:827]: oh O_O i don't remember
no problem

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 20 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: Nobody said this would be easy or quick, it won't. A lot of effort has been placed into refactoring Kodi and making sure new additions do not deteriorate the architecture.

This class is an handler for libass, means it calls libass specific methods. It shouldn't be aware of styles, settings (except libass specific), resolutions, state, etc. I think creating a style struct or class is the best way to go, it allows to abstract all the available Kodi sub style options and to easily map them to the ass_style equivalent. It will also be easier to extend in the future with new style options.

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: Note the style depends on the user configured settings, the user wants to change a setting and the style should follow, even during the playback. It can't be static and configured once. Libass handles styles just like events as far as I remember. You need to allocate a style and you get an id returned, you then set the required ASS_style members. You are then free to change those members during runtime if needed.
Afaics the only way to do this is to pass the style before calling into RenderImage. The component controlling all this workflow is the OverlayRenderer

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: This means generating styles for each frame, with spending resources for no reason
or you have a system to intercept changes in Kodi settings (also in a generic way) and update styles only at that particular time

Comment (fuzzard) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: The concept of settings change callbacks already exist, so thats not a concern just fyi

https://github.com/xbmc/xbmc/blob/master/xbmc/settings/lib/ISettingCallback.h

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: I will take a look thanks

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:59]: Yeap, no need to feed a new style on each frame, Kodi is able to handle settings callback. Out of curiosity, when working on this I was precisely on this point, trying to group all subtitle settings into a single place just like other components (e.g. games - https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/xbmc/settings/GameSettings.h) do.

Having something similar would allow any component to register as an observer (https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/xbmc/utils/Observer.cpp#L32) and be notified of changes (https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/xbmc/games/GameSettings.cpp#L98). The problem is that subtitle settings are pretty much everywhere and you can easily go into the rabbit hole. Either way, it's the right way to do it even though it needs a far bit of work

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleTagMicroDVD.cpp (hunk 17 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleTagMicroDVD.cpp]: changed in another way

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 18 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp]: done

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 19 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp]: done

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 20 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h]: done all

File: xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp (hunk 23 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp]: > Can you explain why subtitleOffset was added here? 

I had only found this way to be able to modify the PTS of the libass renderer 
the current implementation IMO suspect has never worked with libass
before the overlay contained the data to be rendered (like text) now the rendering it is independent from the overlay
libass renderer is based on the current PTS and not on the start / stop values of the overlay
this should in theory only cause problems with libass rendering

however i have removed all "offset" change,
i do not know how to test if really works,
maybe you could take a look on this, to be fix in another PR,
since this my suspected problem was already present in the official kodi anyway

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 24 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp]: done

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 25 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp]: done

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 21 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h]: done

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 22 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h]: done

File: xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp (hunk 23 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp]: This is exactly one of my concerns with your new implementation - I recognize some merits on the old overlay implementation. By removing the overlay and using ass events directly you'll loose the ability of having a container for your events that can carry not only the event but additional data. This can cause limitations in the future. Suppose that you want to have a vtt parser where each overlay can have a different position on the screen (just like Netflix does). Personally I feel the overlay would be the best place to carry and propagate that data in a format independent way. Forcing it in the ass event may be possible but I think it will always be too static. I mean, suppose that because of some sort of requirement, the positional data for the overlay must be recalculated because of a settings change. This is probably hard to do with events only as you'd have to iterate through all the events in the track and recalculate them

**Review by enen92 — COMMENTED** [review]
This will still require several iterations until we get it right. Thanks a lot for continue the development, greatly appreciated

File: xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp (hunk 23 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp]: IMO kodi overlay is only a surplus for libass case, libass already takes care of everything

> Suppose that you want to have a vtt parser where each overlay can have a different position on the screen (just like Netflix does)...

yes, but you are talking about converted subtitles formats that are special cases, with special settings

the position text values have to be fully managed by libass, attach these values to the overlays is not needed and IMO greatly increases the current code complexity and the amount of data to be processed at every frame
i also believe that the current problem of delay could increase

if the text change position for every Event you are assuming that we should create an Style for each Event in order to set the position, and i do not think this is a correct way to do this, because the styles should be used for more events not linked to one event, and this increase all complexity IMO unnecessarily.

theorizing of VTT case, we have text position values for each text entry, font color or other
we theorize to let to the user some special settings:
"Ignore VTT text positions" ON/OFF
"Ignore VTT font styles" ON/OFF

being a format type conversion, IMO the best way is set the text positions by using the forced ass tag positions
(is the reason because there is a fixed PlayRes values for "adapted" subtitles types:
https://github.com/CastagnaIT/xbmc/blob/subtitles_libass/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp#L174-L175)

then, if the user change a special VTT settings,
we should find a way to re-parse again the file by respecting the new settings,
or otherwise you can disable these special VTT settings when the player is in playing, which is not a great loss

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp]: > if the text change position for every Event you are assuming that we should create an Style for each Event in order to set the position, and i do not think this is a correct way to do this,

if you are thinking to create a single Style and changes his values every frame, suggest to do not do this
libass developers warn to not alter styles, or do it as little as possible

Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp]: I am not saying the previous implementation is the way to go, I am just trying to ensure we can have the same functionality as before (now with libass) but without compromising the requirements of future features. Basically that we manage to have the foundations for extensibility right.

IMHO it's the overlayrenderer responsibility (which basically is a manager) to dictate how, where and with which style the libass handler should render an ass image.

 In the particular case of vtt I don't think creating a setting per format is the way to go as you suggest. We likely want a setting that applies to all sub formats that can render overlays at arbitrary positions (such as vtt or even ass). That  setting would behave similarly to the old "assfixedworks" advanced setting. If on will respect the fixed position defined in the calibration settings, otherwise it will respect the position dictated by the parser. 
Either way, we need to figure out a way of passing this data in a format and resolution independent way. Can be (and should be) done later in the scope of another PR, as long as we don't identify any limitation now.

File: system/settings/settings.xml [hunk 26]
```diff
@@ -536,7 +536,7 @@
         </setting>
         <setting id="subtitles.style" type="integer" parent="subtitles.font" label="736" help="36187">
           <level>3</level>
-          <default>1</default> <!-- FONT_STYLE_BOLD -->
+          <default>0</default> <!-- FONT_STYLE_NORMAL -->
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply system/settings/settings.xml:539]: I've tried it, at most I'll remove this change, if require more changes could be done in a different PR

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayASS.h [hunk 27]
```diff
@@ -0,0 +1,38 @@
...
+
+  ~CDVDOverlayASS() override = default;
+
+  CDVDOverlayASS* Clone() override { return new CDVDOverlayASS(*this); }
+
+  /*!
+  \brief Getter for the subtitle adapter
+  \return The subtitle adapter.
+  */
+  std::shared_ptr<CSubtitlesAdapter> GetSubtitlesAdapter() const { return m_adapter; }
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayASS.h:34]: is just a class name not referring to the native/adapted type
which name do you prefer?

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp [hunk 28]
```diff
@@ -9,31 +9,47 @@
...
+    supportedCodec = true;
+  if (!supportedCodec)
+    return false;
 
-  return false;
+  m_bIsSSA = (hints.codec == AV_CODEC_ID_SSA);
+
+  Dispose();
+
+  return m_adapter->CreateSubtitlesTrack();
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp:52]: I think it is more intuitive this way
or else try propose another name,
when you use m_adapter on "native types" you do not have to "initialize" m_adapter and may cause confusion on other devs

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp [hunk 29]
```diff
@@ -113,7 +111,7 @@ int CDVDOverlayCodecSSA::Decode(DemuxPacket *pPacket)
     }
   }
   else
-    m_libass->DecodeDemuxPkt((char*)data, size, pts, duration);
+    m_adapter->DecodeASSDemuxPkt((char*)data, size, pts, duration);
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp:114]: more details, how do you handle it if it doesn't have them?
you have clearly expressed that you do not access Libass methods..

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.h [hunk 30]
```diff
@@ -9,8 +9,9 @@
 #pragma once
 
 #include "DVDOverlayCodec.h"
+#include "DVDSubtitles/SubtitlesAdapter.h"
 
-class CDVDOverlayText;
+class CDVDOverlayASS;
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.h:14]: CDVDOverlayText and CDVDOverlayASS is exactly the same code without differences in any point
why duplicate it?

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayASS.h (hunk 27 above)
[the remark this answers is not in the document]
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayASS.h:34]: Here, none. It should use CDVDLibass directly not the adapter.

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp (hunk 28 above)
[the remark this answers is not in the document]
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp:52]: Native should use libass directly, hence uses libass terminology. On the other hand the adapter hides libass from the user so it should use generic names. Initialize seems ok to me. They are 2 different code paths.

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp (hunk 29 above)
[the remark this answers is not in the document]
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp:114]: On adapted subs, not on native. Native should continue to use the handler directly.

File: xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp (hunk 23 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp]: the screen resolution is not a problem, all text positions coordinates depends on the PlayResX/PlayResY values,
that has no relation with the actual screen resolution, even if it changes, because the scale of subtitles images are done after libass rendering

> We likely want a setting that applies to all sub formats that can render overlays at arbitrary positions (such as vtt or even ass)

yes agree my was only an simple example to try avoid misunderstoods

however, as the libass devs themselves have told me, the "overrides" for ass positions/styles like implemented in kodi are a kind of hack, is an extra feature that may not work in some particular cases,
in the same way override the original text positions of others formats (like VTT) means doing another type of hack

in any case, all the basic functionalities are all there, also if you cannot doing the overrides hacks (positions/styles) always in easy way

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayASS.h (hunk 27 above)
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayASS.h:34]: I thought it was good practice not to use the Libass class itself also here

[the remark this answers is not in the document]
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayASS.h:34]: You only need the adapter for subtitle types that need to be adapted to ass. The reason being that if for some reason we need a different backend to process them in the future, you only need to change the adapter logic.

For ass based subs (parser and codec) you'll only ever have to change the code if you rely on another lib rather than libass.

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 31]
```diff
@@ -130,64 +145,265 @@ bool CDVDSubtitlesLibass::DecodeHeader(char* data, int size)
...
+  else if (subStyle.alignment == FontAlignment::MIDDLE_RIGHT)
+    style->Alignment = VALIGN_CENTER | HALIGN_RIGHT;
+  else if (subStyle.alignment == FontAlignment::SUB_LEFT)
+    style->Alignment = VALIGN_SUB | HALIGN_LEFT;
+  else if (subStyle.alignment == FontAlignment::SUB_CENTER)
+    style->Alignment = VALIGN_SUB | HALIGN_CENTER;
+  else if (subStyle.alignment == FontAlignment::SUB_RIGHT)
+    style->Alignment = VALIGN_SUB | HALIGN_RIGHT;
+
+  if (subtitleType == NATIVE)
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:357]: Duplicated code

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 32]
```diff
@@ -130,64 +145,265 @@ bool CDVDSubtitlesLibass::DecodeHeader(char* data, int size)
...
+    {
+      stylesFlags = ASS_OVERRIDE_BIT_ALIGNMENT;
+    }
+    ass_set_selective_style_override(m_renderer, style);
+  }
+  ass_set_selective_style_override_enabled(m_renderer, stylesFlags);
+}
+
+void CDVDSubtitlesLibass::ConfigureFont(bool overrideFont, std::string fontName)
+{
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:391]: A ternary operator would make this block of code more concise

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 31 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:357]: you mean for "ConfigureAssOverride" ?

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 33]
```diff
@@ -196,7 +412,129 @@ ASS_Event* CDVDSubtitlesLibass::GetEvents()
...
   CSingleLock lock(m_section);
-  if(!m_track)
+  if (!m_track)
     return 0;
   return m_track->n_events;
 }
+
+int CDVDSubtitlesLibass::AddEvent(const char* text, double startTime, double stopTime)
+{
+  if (!*text)
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:422]: I think this is unsafe as you are blindingly dereferencing the pointer. To check if the "string" is empty I think you need to check if the pointer is null and then check if the first char is the string delimiter ('\0')

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 34]
```diff
@@ -196,7 +412,129 @@ ASS_Event* CDVDSubtitlesLibass::GetEvents()
...
+    return;
+  if (!m_track)
+  {
+    CLog::Log(LOGERROR, "{} -  Missing ASS structs (m_track)", __FUNCTION__);
+    return;
+  }
+
+  ASS_Event* assEvents = m_track->events;
+  if (!assEvents)
+    return;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:494]: Missing log

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 33 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:422]: can go well as `if (text == NULL || text[0] == '\0')` ?

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 31 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:357]: Yes, it seems this is already called on the begining of the method

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 33 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:422]: Yeah I think that's the correct way

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp [hunk 35]
```diff
@@ -9,31 +9,47 @@
...
-  if(m_pOverlay)
-    SAFE_RELEASE(m_pOverlay);
+  Dispose();
 }
 
 bool CDVDOverlayCodecText::Open(CDVDStreamInfo &hints, CDVDCodecOptions &options)
 {
-  if (hints.codec == AV_CODEC_ID_TEXT || hints.codec == AV_CODEC_ID_SUBRIP)
-    return true;
+  bool supportedCodec = false;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp:40]: You can just return early (false) if the codecs don't match the expected ones (if !x && !y) return false.

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp [hunk 36]
```diff
@@ -9,31 +9,47 @@
...
+  if (hints.codec == AV_CODEC_ID_TEXT || hints.codec == AV_CODEC_ID_SSA)
+    supportedCodec = true;
+  if (hints.codec == AV_CODEC_ID_SUBRIP)
+    supportedCodec = true;
+  if (!supportedCodec)
+    return false;
 
-  return false;
+  m_bIsSSA = (hints.codec == AV_CODEC_ID_SSA);
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp:48]: Please check if you really need to store the state. You can simply do a comparison against the AV_CODEC_ID_SSA where needed, which to me looks like a single place

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h [hunk 37]
```diff
@@ -53,14 +54,20 @@ class CDVDSubtitleParserText
...
+    : CDVDSubtitleParserCollection(filename), m_pStream(std::move(stream)), parserName(name)
   {
   }
 
   ~CDVDSubtitleParserText() override = default;
 
+  /*
+   * \brief Returns parser name
+   */
+  const char* GetName() override { return parserName.c_str(); };
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:69]: I think this is better as a std::string, you even store it internally with this type. Afaics you only added this for logging purposes, the clog accepts std::string just fine

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:69]: Also no need to move it on construction this is always const, can be declared and initialized on the header file

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp [hunk 38]
```diff
@@ -0,0 +1,158 @@
...
+
+  // We delete some old Events to avoid allocating too much,
+  // this can easily happen with karaoke text or live videos
+  int lastId = m_adapter->DeleteSubtitles(50, 200);
+  if (prevSubId != NO_SUBTITLE_ID)
+  {
+    if (lastId == NO_SUBTITLE_ID)
+    {
+      prevPTSStart = 0.0;
+      prevText = "";
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp:80]: string.clear() anytime you need to reset a string to an empty string

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.cpp [hunk 39]
```diff
@@ -254,31 +253,33 @@ int CDVDOverlayCodecTX3G::Decode(DemuxPacket *pPacket)
...
-  if (m_pOverlay)
-    SAFE_RELEASE(m_pOverlay);
+  m_adapter->Flush();
+  m_output = false;
 }
 
 CDVDOverlay* CDVDOverlayCodecTX3G::GetOverlay()
 {
-  if (m_pOverlay)
+  if (m_output)
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.cpp:279]: Can you explain why you need this here to control the state? Is it to avoid concurrency? Wouldn't a mutex::try_lock be better?

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.cpp:279]: i have replicated the current implementation of ass (already present in DVDOverlayCodecSSA) also in the other codecs that now use ass, so i have kept it as
i do not know if change it with a mutex could cause some type of stalls to videoplayersubtitle

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h (hunk 37 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:69]: > Also no need to move it on construction this is always const, can be declared and initialized on the header file

is done in the same way of all `DVDOverlayCodecXY` already implemented on original kodi sources
why you want change it all again?
seems functional to me

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:69]: i think i have not userstand exaclty
can you provide a example?

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:69]: You can keep this as is, it doesn't matter much anyway.

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp (hunk 36 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp:48]: Ok, then I think that storing the codec and doing a further comparison is better than having a member Boolean completely tied to a single codec type

File: system/settings/settings.xml (hunk 26 above)
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply system/settings/settings.xml]: reverted, would be a nice thing to do

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp [hunk 40]
```diff
@@ -0,0 +1,158 @@
...
+}
+
+CDVDOverlay* CDVDOverlayCodecCCText::GetOverlay()
+{
+  if (m_output)
+  {
+    m_output = false;
+    return m_pOverlay->Acquire();
+  }
+  return NULL;
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp:156]: kept as is, as we discussed the problem will have to be investigated on other PR

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.h [hunk 41]
```diff
@@ -0,0 +1,37 @@
...
+  int Decode(DemuxPacket* pPacket) override;
+  void Reset() override;
+  void Flush() override;
+  CDVDOverlay* GetOverlay() override;
+
+private:
+  std::shared_ptr<CSubtitlesAdapter> m_adapter;
+  CDVDOverlayASS* m_pOverlay;
+  bool m_output;
+  int prevSubId;
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.h]: done

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayASS.h (hunk 27 above)
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayASS.h]: done

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp (hunk 28 above)
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp]: done

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp (hunk 29 above)
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp]: done

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.h (hunk 30 above)
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.h]: restored the two types

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 31 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp]: done

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 32 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:419]: done

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 33 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp]: done

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp (hunk 36 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp]: done

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.cpp (hunk 39 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.cpp:278]: as discussed need to be investigated and maybe changed in separated PR

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 34 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:521]: i have lost it, i will add after

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 42]
```diff
@@ -8,12 +8,23 @@
...
+#include "utils/ColorUtils.h"
 
 #include <ass/ass.h>
+#include <ass/ass_types.h>
 
 /** Wrapper for Libass **/
 
+static constexpr int ASS_NO_ID = -1;
+
+enum ASSSubType
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:22]: Still needed? With different code paths and different overlay types (text/adapted) and ass (native) does the handler still need to know the context of the call?

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp [hunk 43]
```diff
@@ -6,178 +6,187 @@
...
+      CDVDOverlayLibass* ovAss = static_cast<CDVDOverlayLibass*>(it->overlay_dvd);
+      if (!ovAss || !ovAss->GetLibassHandler())
+        continue;
 
-    COverlayText *text = dynamic_cast<COverlayText*>(o);
-    if (text)
-      text->PrepareRender("arial.ttf", 1, 100, 15, 0, m_font, m_fontBorder, UTILS::COLOR::NONE,
-                          m_rv);
+      KODI::SUBTITLES::subtitlesStyle subStyle;
+      bool updateStyle = !ovAss->GetLibassHandler()->IsStyleInitialized();
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: I am not a big fan of this. Whenever you need to ask a component about its internal state it's usually a sign the design logic can be improved. Can you figure out a way of writing this so that the managers (overlayrenderer and debugrenderer) are responsible for tracking the state instead? Probably you can initialize the style right on the adapter->initialize() and store it on the manager as a member. Then, on settingschanged observed callback you update the member style in the manager and flag the convert() method the style needs to be updated on the handler side

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp [hunk 44]
```diff
@@ -6,178 +6,187 @@
...
+    m_adapter->AddSubtitle(m_strDebug[0].c_str(), 0., 5000000.);
   }
   if (video.metaPrim != m_strDebug[1])
   {
     m_strDebug[1] = video.metaPrim;
-    if (m_overlay[1])
-      m_overlay[1]->Release();
-    m_overlay[1] = new CDVDOverlayText();
-    m_overlay[1]->AddElement(new CDVDOverlayText::CElementText(m_strDebug[1]));
+    m_adapter->AddSubtitle(m_strDebug[1].c_str(), 0., 5000000.);
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:108]: You have a few magic numbers here. What happens when the end time is reached? The ass "spec" does not preclude "always visible" overlays, so we need to ensure the overlay time is extended, or am I understanding the current logic wrong?

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 42 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:22]: if you remove it you need to add a compare to check each overlay, has no sense,
IMO is better kept as is to be set just after libass Configure method
this can be useful also for possible changes in future libass versions.
if you do not want an enum i could change it with a bool like:
`bool m_isNativeAssType;` and related set method
but to me seem more clean as is

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp (hunk 43 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: the adapter here has nothing to do with it,
but i will try to seeto remove IsStyleInitialized and manage it directly internally libass class
so we will no longer have this to do here (and also in overlayrenderer)

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp (hunk 44 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:108]: This is what I tried to explain to you on slack,
here you don't have to rely on start/duration times, but only to the actual PTS  passed to the libass renderer
from this line we pass "1000000." so we have always the current pts to 1sec
https://github.com/CastagnaIT/xbmc/blob/subtitles_libass/xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp#L84
in this way we have "always visible" events because the libass renderer elaborate every time the images for the PTS position of 1 sec

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp (hunk 43 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: I remember now,
no this need to be handled as is, to avoid an CPU overload in creating styles unnecessarily at every frame

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: because you create the style inside the debugrenderer/overlayrenderer class

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: ah you mean to move this variable in the debugrenderer/overlayrenderer class?

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp (hunk 44 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:108]: now that i see seem create too much overlays over the time, i am not sure, i will recheck

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp (hunk 43 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: I mean the manager should not ask the state of a component it is in charge of. I am pretty sure we can figure out a way of refactoring this without asking the state and still have the same performance levels

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: I have to try see, because when i have done this, i encountered many problems when you switch subtitles with another subtitle track _while in playback_, but i don't remember exactly now

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.cpp [hunk 45]
```diff
@@ -10,7 +10,35 @@
...
+  if (pkt->duration != DVD_NOPTS_VALUE)
+    duration = pkt->duration;
+
+  if (pkt->pts != DVD_NOPTS_VALUE)
+    pts = pkt->pts;
+  else if (pkt->dts != DVD_NOPTS_VALUE)
+    pts = pkt->dts;
+
+  starttime = pts;
+  if (duration)
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.cpp:34]: Implicit conversion to bool, please use:

`if (duration > 0)`

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.cpp [hunk 46]
```diff
@@ -21,18 +49,18 @@ void CDVDOverlayCodec::GetAbsoluteTimes(double &starttime, double &stoptime, Dem
...
-  if     (pkt->pts != DVD_NOPTS_VALUE)
+  if (pkt->pts != DVD_NOPTS_VALUE)
     pts = pkt->pts;
-  else if(pkt->dts != DVD_NOPTS_VALUE)
+  else if (pkt->dts != DVD_NOPTS_VALUE)
     pts = pkt->dts;
 
   starttime = pts + offset;
-  if(duration)
+  if (duration)
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.cpp:63]: Same

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.h [hunk 47]
```diff
@@ -0,0 +1,35 @@
...
+
+class CDVDOverlay;
+
+class CDVDOverlayCodecCCText : public CDVDOverlayCodec, public CSubtitlesAdapter
+{
+public:
+  CDVDOverlayCodecCCText();
+  ~CDVDOverlayCodecCCText() override;
+  bool Open(CDVDStreamInfo& hints, CDVDCodecOptions& options) override;
+  void Dispose() override;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.h:23]: This Dispose method always seem to be used internally, please confirm. If so, please make it protected or private

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h [hunk 48]
```diff
@@ -26,6 +26,7 @@ class CDVDSubtitleParser
   virtual void Dispose() = 0;
   virtual void Reset() = 0;
   virtual CDVDOverlay* Parse(double iPts) = 0;
+  virtual std::string GetName() = 0;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:29]:
```suggestion
  virtual std::string GetName() const = 0;
```

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp (hunk 43 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: Tried check again, on debugrenderer we can think to remove it,
but in the overlayrenderer is needed, or will cause a big mess when you choose another subtitles tracks (eg. external file etc..) while playing,
because when you are in playback, the overlayrenderer in always the same class instance, the overlay's (that now is one single, replied to each frame) are async and you have no chance to know when you are switching to another libass instance that require the style to be set

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: so without knowing the status of the libass component, IMO you can't solve it because is a libass internal state,
if you know another possible way, try push in your github the changes, I don't see any other solution

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h (hunk 48 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:29]: suggested change not compile, always say that cannot create all parsers classes without specify the reason
instead use `virtual const std::string GetName() = 0;`
works

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.h (hunk 47 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.h:23]: yes can be moved to private to all dvdoverlaycodec's

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h (hunk 48 above)
Comment (howie-f) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:29]: please return `const std::string&` as reference, also for the overridden function. never return plain const (one rule that sunk into me)

**Comment by CastagnaIT** [comment]
@garbear can you review english language again? thanks

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h (hunk 48 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:29]: Tried i have changed line 29 and 69 as:
`virtual const std::string& GetName() = 0;`
`std::string& const GetName() { return parserName; };`

but compiler complain
```
D:\GIT\kodi\xbmc\cores\VideoPlayer\DVDSubtitles\DVDSubtitleParser.h(69,29): warning C4227: anachronism used: qualifiers
 on reference are ignored (compiling source file D:\GIT\kodi\xbmc\cores\VideoPlayer\DVDSubtitles\DVDSubtitleParserSSA.c
pp) [D:\kodi-build\libkodi.vcxproj]
```

Comment (howie-f) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:29]: i think on your 2nd line the & is misplaced, it should look like `std::string const& GetName() override { return parserName; };`

or even better
```c
const std::string& GetName() override { return parserName; };
```

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:29]: thanks now it's ok

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMPL2.cpp [hunk 49]
```diff
@@ -48,20 +51,24 @@ bool CDVDSubtitleParserMPL2::Open(CDVDStreamInfo &hints)
     int pos = reg.RegFind(line);
     if (pos > -1)
     {
-      const char* text = line + pos + reg.GetFindLen();
+      std::string text(line + pos + reg.GetFindLen());
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMPL2.cpp:54]: not needed afaics, you pass the text to AddSubtitle as a c str

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMicroDVD.cpp [hunk 50]
```diff
@@ -55,20 +58,24 @@ bool CDVDSubtitleParserMicroDVD::Open(CDVDStreamInfo &hints)
     int pos = reg.RegFind(line);
     if (pos > -1)
     {
-      const char* text = line + pos + reg.GetFindLen();
+      std::string text(line + pos + reg.GetFindLen());
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMicroDVD.cpp:61]: Same?

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 51]
```diff
@@ -26,8 +37,29 @@ class CDVDSubtitlesLibass
...
+  * \brief Translate and apply Kodi subtitles style to LibAss style
+  */
+  void ApplyStyle(KODI::SUBTITLES::subtitlesStyle subStyle);
+
+  /*!
+  * \brief Specify whether the subtitles are
+  * native (loaded from ASS/SSA file or stream)
+  * or adapted (converted from other types e.g. SubRip)
+  */
+  void SetSubtitleType(ASSSubType type) { m_subtitleType = type; };
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:61]: Doesn't need to be public afaics. I thing you don't even need the getter as this is restricted to the class instance

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h [hunk 52]
```diff
@@ -0,0 +1,93 @@
...
+
+const UTILS::Color colors[9] = {
+    UTILS::COLOR::YELLOW,      UTILS::COLOR::WHITE,       UTILS::COLOR::BLUE,
+    UTILS::COLOR::BRIGHTGREEN, UTILS::COLOR::YELLOWGREEN, UTILS::COLOR::CYAN,
+    UTILS::COLOR::LIGHTGREY,   UTILS::COLOR::GREY,        UTILS::COLOR::DARKGREY};
+
+const UTILS::Color bgColors[5] = {UTILS::COLOR::BLACK, UTILS::COLOR::YELLOW, UTILS::COLOR::WHITE,
+                                   UTILS::COLOR::LIGHTGREY, UTILS::COLOR::GREY};
+
+struct LibassRenderOpts
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:80]: Rename to subtitleRenderOpts please, this is supposed to be independent from the backend/libass

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMPL2.cpp (hunk 49 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMPL2.cpp:54]: ConvertLine need a string

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 51 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:61]: this is used by subtitlesAdapter

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp (hunk 43 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:170]: I'll try to take a look in ~ 1 week when I am back near a computer

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 51 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:61]: i could add in the libass Configure() method an argument to be used from subtitlesAdapter to set it instead of SetSubtitleType

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:61]: You're right. Leave it as is as it's easier to understand. We will need to revisit this before approval anyway. I still think that all the methods that are called from the adapter should be private or protected in libass so that we know no other components are supposed to call them. This can be done either by making the "adapter" extend the libass handler or setting the adapter as a friend class of the handler (See https://www.google.com/amp/s/www.geeksforgeeks.org/friend-class-function-cpp/amp/). I'll look into it later

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:61]: i have already think this before you, if you extend the subtitlesAdapter class to libass class, then you cannot do libass as std::make_shared this means having to handle different points of the overlayRenderer and overlays and parsers in more complex way,
and also you have to redo all the PR code from the beginning
i think that has no sense
the current implementation is the most user-friendly approach, also for understanding the functionality from external users

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:61]: if you want do this i stop develop the PR now because it is a lost of time without sense

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:61]: if the problem is only this SetSubtitleType i move it to the Configure method as argument
it is not a problem, but redoing everything from scratch makes no sense and I'm not willing to do that

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp (hunk 43 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp]: your provided example works well thank you
this is also done

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h (hunk 51 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h]: I clearly misinterpreted the use of "friend class", please try look at last pushed commit

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h]: Yeah I  didn't understand your reaction as the suggested change was quite small, literally setting a class as a friend and move stuff to private or protected :) I thought you could understand what I meant from the shared link.

It might depend a bit on the interpretation though. Abusing friend classes is a bad practice, in this case I think it is better to hide the methods that shouldn't be publicly used by anything rather than our "adapter"/proxy than simply having all of them public.

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.h [hunk 53]
```diff
@@ -0,0 +1,35 @@
...
+
+#pragma once
+
+#include "DVDOverlayCodec.h"
+#include "DVDStreamInfo.h"
+#include "DVDSubtitles/SubtitlesAdapter.h"
+
+class CDVDOverlay;
+
+class CDVDOverlayCodecCCText : public CDVDOverlayCodec, public CSubtitlesAdapter
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.h:17]:
```suggestion
class CDVDOverlayCodecCCText : public CDVDOverlayCodec, private CSubtitlesAdapter
```

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.h [hunk 54]
```diff
@@ -9,22 +9,23 @@
 #pragma once
 
 #include "DVDOverlayCodec.h"
+#include "DVDSubtitles/SubtitlesAdapter.h"
 
-class CDVDOverlayText;
+class CDVDOverlay;
 
-class CDVDOverlayCodecTX3G : public CDVDOverlayCodec
+class CDVDOverlayCodecTX3G : public CDVDOverlayCodec, public CSubtitlesAdapter
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.h:16]:
```suggestion
class CDVDOverlayCodecTX3G : public CDVDOverlayCodec, private CSubtitlesAdapter
```

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.h [hunk 55]
```diff
@@ -9,21 +9,30 @@
...
-class CDVDOverlayText;
+extern "C"
+{
+#include <libavcodec/avcodec.h>
+}
+
+class CDVDOverlay;
 
-class CDVDOverlayCodecText : public CDVDOverlayCodec
+class CDVDOverlayCodecText : public CDVDOverlayCodec, public CSubtitlesAdapter
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.h:22]:
```suggestion
class CDVDOverlayCodecText : public CDVDOverlayCodec, private CSubtitlesAdapter
```

File: xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp [hunk 56]
```diff
@@ -41,24 +39,11 @@ void CDVDOverlayContainer::ProcessAndAddOverlayIfValid(CDVDOverlay* pOverlay)
...
-      break;
-    }
-
     else if (m_overlays[i]->iPTSStartTime != pOverlay->iPTSStartTime)
       m_overlays[i]->iPTSStopTime = pOverlay->iPTSStartTime;
   }
 
-  if (addToOverlays)
-    m_overlays.push_back(pOverlay);
+  m_overlays.push_back(pOverlay);
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp:46]:
```suggestion
  m_overlays.emplace_back(pOverlay);
```

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h [hunk 57]
```diff
@@ -26,6 +26,7 @@ class CDVDSubtitleParser
   virtual void Dispose() = 0;
   virtual void Reset() = 0;
   virtual CDVDOverlay* Parse(double iPts) = 0;
+  virtual const std::string& GetName() = 0;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:29]:
```suggestion
  virtual const std::string& GetName() const = 0;
```

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h [hunk 58]
```diff
@@ -53,14 +54,20 @@ class CDVDSubtitleParserText
...
+    : CDVDSubtitleParserCollection(filename), m_pStream(std::move(stream)), parserName(name)
   {
   }
 
   ~CDVDSubtitleParserText() override = default;
 
+  /*
+   * \brief Returns parser name
+   */
+  const std::string& GetName() override { return parserName; };
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:69]:
```suggestion
  const std::string& GetName() const override { return m_parserName; };
```

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h [hunk 59]
```diff
@@ -77,4 +84,5 @@ class CDVDSubtitleParserText
   }
 
   std::unique_ptr<CDVDSubtitleStream> m_pStream;
+  std::string parserName;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:87]:
```suggestion
  std::string m_parserName;
```

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMPL2.h [hunk 60]
```diff
@@ -9,16 +9,19 @@
 #pragma once
 
 #include "DVDSubtitleParser.h"
+#include "SubtitlesAdapter.h"
 
 #include <memory>
 
-class CDVDSubtitleParserMPL2 : public CDVDSubtitleParserText
+class CDVDSubtitleParserMPL2 : public CDVDSubtitleParserText, public CSubtitlesAdapter
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMPL2.h:16]:
```suggestion
class CDVDSubtitleParserMPL2 : public CDVDSubtitleParserText, private CSubtitlesAdapter
```

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMicroDVD.h [hunk 61]
```diff
@@ -9,16 +9,20 @@
 #pragma once
 
 #include "DVDSubtitleParser.h"
+#include "SubtitlesAdapter.h"
 
 #include <memory>
 
-class CDVDSubtitleParserMicroDVD : public CDVDSubtitleParserText
+class CDVDSubtitleParserMicroDVD : public CDVDSubtitleParserText, public CSubtitlesAdapter
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserMicroDVD.h:16]:
```suggestion
class CDVDSubtitleParserMicroDVD : public CDVDSubtitleParserText, private CSubtitlesAdapter
```

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserVplayer.h [hunk 62]
```diff
@@ -9,16 +9,20 @@
 #pragma once
 
 #include "DVDSubtitleParser.h"
+#include "SubtitlesAdapter.h"
 
 #include <memory>
 
-class CDVDSubtitleParserVplayer : public CDVDSubtitleParserText
+class CDVDSubtitleParserVplayer : public CDVDSubtitleParserText, public CSubtitlesAdapter
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParserVplayer.h:16]:
```suggestion
class CDVDSubtitleParserVplayer : public CDVDSubtitleParserText, private CSubtitlesAdapter
```

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 63]
```diff
@@ -36,14 +53,87 @@ class CDVDSubtitlesLibass
...
+  * \brief Decode ASS/SSA demux packet (depends from DecodeHeader)
+  * \return True if success, false if error
+  */
   bool DecodeDemuxPkt(const char* data, int size, double start, double duration);
+
+  /*!
+  * \brief Create a new empty ASS track
+  * \return True if success, false if error
+  */
+  bool CreateTrack();
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:73]: Isn't this used only by the adapter? If so move it near the other private methods. If not please ignore

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesAdapter.cpp [hunk 64]
```diff
@@ -0,0 +1,87 @@
...
+
+void CSubtitlesAdapter::FlushSubtitles()
+{
+  // Flush events to avoid display duplicates events e.g. on video seek
+  m_libass->FlushEvents();
+}
+
+CDVDOverlay* CSubtitlesAdapter::CreateOverlay()
+{
+  // Warning with Libass the overlay not contains image or text then is not tied to Libass Events
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesAdapter.cpp:71]: does not contain instead of "not contains"

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h [hunk 65]
```diff
@@ -0,0 +1,97 @@
...
+
+enum class AssOverrideStyles
+{
+  DISABLED = 0,
+  POSITIONS,
+  STYLES,
+  STYLES_POSITIONS
+};
+
+struct subtitlesStyle
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:58]: This is just a personal preference but maybe you can change the struct name just to style? The namespaces already identifies it as kodi::subtitles::style, makes it at least a bit more concise

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.h [hunk 66]
```diff
@@ -10,31 +10,39 @@
...
+    std::shared_ptr<struct KODI::SUBTITLES::subtitlesStyle> m_debugOverlayStyle;
   };
 
   std::string m_strDebug[6];
-  CDVDOverlayText* m_overlay[6];
   CRenderer m_overlayRenderer;
+
+private:
+  CSubtitlesAdapter* m_adapter{nullptr};
+  bool m_isInitialized{false};
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.h:47]: I am not sure if a simple bool is enough here as it will be consumed without any sort of locking by different threads. Maybe a `std::atomic_bool ` would make more sense?

**Review by enen92 — COMMENTED** [review]
I am pretty happy with this now, a few last comments to improve the code and for discussion. After that you'll have my approval. I have runtime tested this and haven't found any regressions so far. I am making sure my main system has your work so that I can daily stress it.

This will need another review from someone from the team, at least to make sure best practices are being followed. I see you use a lot of c-style casts but according to the guidelines cpp style casts are preferred. I am however, unsure how to do convert them all or even if they should be converted. I'll try to ping someone else to review this as well.

Thanks in advance for your work and patience dealing with my review comments

**Comment by enen92** [comment]
Ofc when this is finished the commits need to be squashed/bisectable, but please wait for other reviews before wasting time on it.

**Review by enen92 — APPROVED** [review]
+1 from my side. Please do not forget to fix clang-format

**Comment by CastagnaIT** [comment]
Hi @Essam3152 can you help me to test right-to-left languages such as hebrew?
i need to know if with a SRT subtitle with RTL language the characters are correctly displayed

Here there are two builds (Windows 64):
Build with encoding set: https://www.dropbox.com/s/41yce0hldp231vm/Kodi20Libass_build6_EncodingSet.zip?dl=1
Build regular: https://www.dropbox.com/s/eirax2idss0v4kq/Kodi20Libass_build6_Regular.zip?dl=1

Please test both versions, and let me know the results

**Comment by thexai** [comment]
I tested portable build "Kodi20Libass_build6_Regular.zip" and I have found some issues related to debug OSD:

Debug Info OSD (Ctrl+Shift+O) seems not working (nothing appears).
Debug Info video OSD (Alt+O) is working but every time some text changes adds new line instead of updating the text on the same line:

debugOSD

Can be reproduced in Windowed mode resizing window and resolution text changes or with HDR content changing tone mapping method (Alt+F11) while is playing.

**Comment by CastagnaIT** [comment]
yes "Ctrl+Shift+O" shortcut in my case interferes with amd drivers then i have manually changed the default shortcut key to make it works
debug video info "alt+o" i thought it was correct evidently i am wrong.. but easy to fix

**Comment by thexai** [comment]
I've already seen it Alt+P

debugOSD2

Is working fine

**Comment by thexai** [comment]
Caught another little issue: CPU consumption is very good, we can hardly see the difference when debug OSD is activated or not but there is a memory leak:

Captura de pantalla 2021-09-06 200851

While it is activated there is an infinite increase in memory usage (ramp), when deactivated all memory is freed and returns to the starting point.

**Comment by CastagnaIT** [comment]
nice catch, i will check

**Comment by lrusak** [comment]
jenkins build this please

**Comment by Essam3152** [comment]
@CastagnaIT Everything is fine with the RTL languages in both of the two builds, tested with Arabic and Hebrew subtitles.

**Comment by CastagnaIT** [comment]
Thank you @Essam3152

@thexai please try this build: https://www.dropbox.com/s/zas17w1vc77h3r1/Kodi20Libass_build7.zip?dl=1
to me the mem leak seem now fixed but let me know as confirmation

**Review by fuzzard — COMMENTED** [review]
Just some short comments so far

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.cpp [hunk 67]
```diff
@@ -10,7 +10,35 @@
...
+{
+  if (!pkt)
+    return;
+
+  double duration = 0.0;
+  double pts = 0.0;
+
+  // we assume pts from packet is better than what
+  // decoder gives us, only take duration
+  // from decoder if available
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.cpp:24]: to me the comment seem right
i could add the missing

```
  if (stoptime > starttime)
    duration = stoptime - starttime;
```

just for consistency with the other method, let me know

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.cpp [hunk 68]
```diff
@@ -21,18 +49,18 @@ void CDVDOverlayCodec::GetAbsoluteTimes(double &starttime, double &stoptime, Dem
...
+  if (pkt->pts != DVD_NOPTS_VALUE)
     pts = pkt->pts;
-  else if(pkt->dts != DVD_NOPTS_VALUE)
+  else if (pkt->dts != DVD_NOPTS_VALUE)
     pts = pkt->dts;
 
   starttime = pts + offset;
-  if(duration)
+  if (duration > 0)
   {
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.cpp:64]: i try to see

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp [hunk 69]
```diff
@@ -15,113 +15,98 @@
...
 {
-  if(m_pOverlay)
-  {
-    CDVDOverlay* overlay = m_pOverlay;
-    m_pOverlay = NULL;
-    return overlay;
-  }
-  return NULL;
+  if (m_pOverlay)
+    return nullptr;
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp:109]: yes it is right, because this method is called in a non-ending loop,
and we have to exit from the loop after the first call

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlaySSA.h [hunk 70]
```diff
@@ -8,38 +8,21 @@
 
 #pragma once
 
-#include "../../DVDSubtitles/DVDSubtitlesLibass.h"
-#include "DVDOverlay.h"
+#include "DVDOverlayLibass.h"
+#include "cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h"
 
-class CDVDOverlaySSA : public CDVDOverlay
+#include <memory>
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlaySSA.h:14]: it is used on line 19 or is not mandatory?

> explicit CDVDOverlaySSA(std::shared_ptr<CDVDSubtitlesLibass> libass)

[the remark this answers is not in the document]
Comment (fuzzard) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlaySSA.h:14]: All good then, missed it

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.h [hunk 71]
```diff
@@ -73,12 +75,18 @@ class CDVDOverlayCodec
...
-  static void GetAbsoluteTimes(double &starttime, double &stoptime, DemuxPacket *pkt, bool &replace, double offset = 0.0);
+  static void GetAbsoluteTimes(double& starttime, double& stoptime, DemuxPacket* pkt);
+  /*
+   * \brief Adapts startTime, stopTIme from the subtitle stream (which is relative to stream pts)
+   * so that it returns the absolute start and stop timestamps.
+   * \param replace Will be set to true if the overlay should replace the former overlay
+   * \param offset Optional - Offset will be added to start and stoptime
+   */
+  static void GetAbsoluteTimes(
+      double& starttime, double& stoptime, DemuxPacket* pkt, bool& replace, double offset = 0.0);
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.h:89]: i try to see a way to rework the GetAbsoluteTimes method

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h [hunk 72]
```diff
@@ -10,6 +10,7 @@
 
 #include <assert.h>
 #include <atomic>
+#include <memory>
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h]: done

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp [hunk 73]
```diff
@@ -15,6 +15,7 @@
 #include "cores/VideoPlayer/Interface/DemuxPacket.h"
 #include "cores/VideoPlayer/Interface/TimingConstants.h"
 #include "utils/StringUtils.h"
+#include "utils/log.h"
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp]: forgot removed

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.h (hunk 71 above)
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodec.h]: i have reworked GetAbsoluteTimes method now there is one method only
and i have moved offset case within ffmpeg ov codec

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp (hunk 69 above)
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp:109]: see: https://github.com/xbmc/xbmc/pull/20010/files#diff-dcd446081d8b39cb8f3e81e58e815a0a3cceab7269a31c28348b26a5c01f025d
VideoPlayerSubtitle.cpp line 58

**Comment by thexai** [comment]
Main mem leak is fixed now. Still a small mem leak when debug info is enabled/disabled many times, however is not critical and can be investigated/fixed in a following PR.

Debug OSD font size is changed now from 16 to 24 in the commit https://github.com/xbmc/xbmc/pull/20010/commits/3a1c0ec204473e07c39ee05fde6c148ad5de5609.  I think 16 is better but it's a personal preference, I don't know what others will think.

**Comment by CastagnaIT** [comment]
I hadn't noticed, I'll try to check it
i have changed OSD font size to match the regular kodi font size, i had forgot to correct it when i have fixed the point/pixel proportion

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp [hunk 74]
```diff
@@ -0,0 +1,150 @@
...
+bool CDVDOverlayCodecCCText::Open(CDVDStreamInfo& hints, CDVDCodecOptions& options)
+{
+  Dispose();
+
+  return Initialize();
+}
+
+void CDVDOverlayCodecCCText::Dispose()
+{
+  if (m_pOverlay)
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp:53]: `SAFE_RELEASE` macro already checks for object not NULL so `if (m_pOverlay)` condition can be removed

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp [hunk 75]
```diff
@@ -0,0 +1,150 @@
...
+
+void CDVDOverlayCodecCCText::Reset()
+{
+  Dispose();
+  Flush();
+}
+
+void CDVDOverlayCodecCCText::Flush()
+{
+  if (m_pOverlay)
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp:133]: Same here

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp [hunk 76]
```diff
@@ -48,96 +45,65 @@ bool CDVDOverlayCodecSSA::Open(CDVDStreamInfo &hints, CDVDCodecOptions &options)
 
 void CDVDOverlayCodecSSA::Dispose()
 {
-  if(m_pOverlay)
+  if (m_pOverlay)
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp:48]: Same

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp [hunk 77]
```diff
@@ -146,16 +112,18 @@ void CDVDOverlayCodecSSA::Reset()
 
 void CDVDOverlayCodecSSA::Flush()
 {
+  if (m_pOverlay)
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecSSA.cpp:115]: same

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.cpp [hunk 78]
```diff
@@ -250,35 +265,43 @@ int CDVDOverlayCodecTX3G::Decode(DemuxPacket *pPacket)
...
 {
-  if (m_pOverlay)
-    SAFE_RELEASE(m_pOverlay);
+  Dispose();
+  Flush();
 }
 
 void CDVDOverlayCodecTX3G::Flush()
 {
   if (m_pOverlay)
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecTX3G.cpp:295]: same

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp [hunk 79]
```diff
@@ -15,113 +15,98 @@
...
-  return false;
+  Dispose();
+
+  return Initialize();
 }
 
 void CDVDOverlayCodecText::Dispose()
 {
-  if(m_pOverlay)
+  if (m_pOverlay)
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp:47]: same

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp [hunk 80]
```diff
@@ -15,113 +15,98 @@
...
-  if(m_pOverlay)
-    SAFE_RELEASE(m_pOverlay);
+  Dispose();
+  Flush();
 }
 
 void CDVDOverlayCodecText::Flush()
 {
-  if(m_pOverlay)
+  if (m_pOverlay)
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecText.cpp:100]: same

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesAdapter.h [hunk 81]
```diff
@@ -0,0 +1,68 @@
...
+  /*!
+  * \brief Append text to the specified subtitle ID
+  * \param subtitleId The subtitle ID
+  * \param text The text to append
+  */
+  void AppendToSubtitle(int subtitleId, const char* text);
+
+  /*!
+  * \brief Delete old subtitles only if the total number of subtitles added reaches the threshold
+  * \param nEvents The number of subtitles to delete
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesAdapter.h:49]: Typo: param name `nEvents` not match with current name `nSubtitles`

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h [hunk 82]
```diff
@@ -53,14 +54,20 @@ class CDVDSubtitleParserText
...
+    : CDVDSubtitleParserCollection(filename), m_pStream(std::move(stream)), m_parserName(name)
   {
   }
 
   ~CDVDSubtitleParserText() override = default;
 
+  /*
+   * \brief Returns parser name
+   */
+  const std::string& GetName() const override { return m_parserName; };
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitleParser.h:69]:
```suggestion
  const std::string& GetName() const override { return m_parserName; }
```

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h [hunk 83]
```diff
@@ -36,14 +53,86 @@ class CDVDSubtitlesLibass
...
+
+  /*!
+  * \brief Specify whether the subtitles are
+  * native (loaded from ASS/SSA file or stream)
+  * or adapted (converted from other types e.g. SubRip)
+  */
+  void SetSubtitleType(ASSSubType type) { m_subtitleType = type; };
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.h:92]:
```suggestion
  void SetSubtitleType(ASSSubType type) { m_subtitleType = type; }
```

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp (hunk 74 above)
Comment (lrusak) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp:53]: Please don't use `SAFE_RELEASE` macro, I've been trying to get rid of it for a while now.

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp:53]: can go well if replace all SAFE_RELEASE with:
```
  if (m_pOverlay)
  {
    m_pOverlay->Release();
    m_pOverlay = nullptr;
  }
```
?

Comment (thexai) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp:53]: Then:

```c++
  if (m_pOverlay)
  {
    m_pOverlay->Release();
    m_pOverlay = nullptr;
  } 
```

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlayCodecCCText.cpp:51]: done

**Comment by CastagnaIT** [comment]
@thexai i have found also the last mem leak and fixed
i have restored to 16pt, i do not think it is a big problem...

**Comment by thexai** [comment]
I wanted to test this PR and I have compiled your branch as it is now but crash here: 

xbmc\cores\VideoPlayer\DVDSubtitles\DVDSubtitlesLibass.cpp L527

Captura de pantalla 2021-09-13 102421

I missed something? Is needed to update some dependence or use patched libass?

Instead your test build (Kodi20Libass_build7.zip) in portable mode works fine.

**Comment by CastagnaIT** [comment]
@thexai can you specify the steps to reproduce?
i need to know also:
if external subtitle or video embedded
the subtitle file type

**Comment by thexai** [comment]
Crash is enabling debug info OSD (Ctrl+Shift+O   or  Alt+O)
I want to create my build to use at daily basis and test SRT and PGS subs, etc.

**Comment by CastagnaIT** [comment]
@thexai i have just cleaned my sources, redownloaded kodi deps and rebuilded from scratch (as release build)
but this crash do not occours

**Comment by phunkyfish** [comment]
Maybe create a windows build from Jenkins for testing purposes.

**Comment by thexai** [comment]
In release mode not crash.... seems only crash in debug mode. I will continue with this tomorrow.

**Comment by CastagnaIT** [comment]
i have done some tests
- Kodi builded as release -> ok
- Kodi builded as debug -> crash
- Kodi builded as debug + replaced libass.dll with self builded library as debug -> ok

if you take look at libass.dll on Kodi builded as debug and Kodi builded as release the file has the same size,
this is a bit weird where debug dll should have bigger size than release dll

In kodi debug and release builds the dll has about 2.157kb
my self compiled dll as release has 1.710kb only

**Comment by CastagnaIT** [comment]
i think that kodi not compile the dll library itself but download it from a mirror already compiled
then this is the cause of the mentioned crash on debug and it makes sense

**Comment by jjd-uk** [comment]
Yes Windows builds use pre-complied dependacies from https://mirrors.kodi.tv/build-deps/win32/

**Comment by CastagnaIT** [comment]
> Changes can be included in this PR before merge.

I will not to include these changes in this PR
as first i have no idea how works all dependencies things
as seconds i have a PR of more 2000 lines to rework before merge

**Comment by thexai** [comment]
Sorry, I just meant to replace

`libass-0.15.1-x64-v142-20210620.7z` with `libass-0.15.x-x64-v142-2021xxxx.7z`

inside `0_package.target-xxxx.list`

This can be done in a separate PR of course.

**Comment by CastagnaIT** [comment]
sidenote the libass library must be updated anyway
because have a critical bug in font loading (on Windows only)
i have already opened a PR with the fix to @Paxxi GH when he has free time to check
so he can shoot two birds with one stone

**Comment by Paxxi** [comment]
@thexai I don't include debug builds of dlls in the packages, only statically linked libraries contain both debug and release builds as they break the build otherwise. The included pdb file should provide fairly good support for debugging provided you have sources checked out somewhere and can point vs to them

**Comment by thexai** [comment]
Tested for a few days and I found a issue with an MKV with forced PGS subtitles:

Captura de pantalla 2021-09-18 213616

New subs gets overlapped with previous. Previous overlays only are cleared when seeking.

I don't think this file has nothing special and with current master branch works fine.

```
Text
ID                                       : 3
Format                                   : PGS
Codec ID                                 : S_HDMV/PGS
Codec ID/Info                            : Picture based subtitle format used on BDs/HD-DVDs
Duration                                 : 2 h 5 min
Bit rate                                 : 30.7 kb/s
Count of elements                        : 2858
Stream size                              : 27.4 MiB (0%)
Title                                    : Spanish Forced
Language                                 : Spanish
Default                                  : Yes
Forced                                   : Yes
```

**Comment by CastagnaIT** [comment]
Can you provide a link with a sample file?

**Comment by thexai** [comment]
https://www.mediafire.com/file/92wzqddpargzn3x/Le_Pass%25C3%25A9-005.mkv/file

**Comment by CastagnaIT** [comment]
@thexai PGS subtitles regression fixed

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp [hunk 84]
```diff
@@ -6,178 +6,150 @@
...
   }
-
   ReleaseUnused();
 }
+
+void CDebugRenderer::CRenderer::CreateSubtitlesStyle()
+{
+  m_debugOverlayStyle = std::make_shared<KODI::SUBTITLES::style>();
+  m_debugOverlayStyle->fontName = "arial.ttf";
+  m_debugOverlayStyle->fontSize = 16.0;
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:154]:
```suggestion
  m_debugOverlayStyle->fontSize = 20.0;
```
After tested with 4K screen I agree with you that 16 is too small. At this time I think 20 is a good size 😃

**Review by thexai — APPROVED** [review]
Runtime tested and everything seems fine to me now. As a whole, it is a big improvement.

File: xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp (hunk 84 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/DebugRenderer.cpp:154]: hahaha ok will do

File: system/settings/settings.xml [hunk 85]
```diff
@@ -523,7 +523,7 @@
         </setting>
         <setting id="subtitles.height" type="integer" parent="subtitles.font" label="289" help="36186">
           <level>3</level>
-          <default>28</default>
+          <default>42</default>
```
Comment (enen92) [inline system/settings/settings.xml:526]: Yesterday when testing your branch on top of a previous installation I was presented with really small fontsizes. This happens because I had the default value of 28 in my guisettings.xml file. I think we should change the setting id (e.g. to subtitle.fontsize) to avoid similar issues. I have no strong opinions about the default value change for the alignment setting but I think the same applies, if the default value changes we should stop using the same Id for the setting.

Comment (enen92) [reply system/settings/settings.xml:526]: Actually the alignment one should be fine. You didn't change the order. The fontsize one is important though, the value interpretation now seems to be different

Comment (CastagnaIT) [reply system/settings/settings.xml:526]: yes the now it is different because the font is rendered with the right proportion between points/pixels
i will rename as suggested to `subtitle.fontsize`

**Comment by enen92** [comment]
Looks like we don't have any feedback at all from the forum 🤷‍♂️ 
Since this now has two approvals I think it's time to consider merging as it will just delay further improvements if it stays for too long in the queue. Thus, please adjust the last 2 comments above. Please also rebase/restructure your commits to allow them to be bissectable (you've loads of fixup commits). When done, it's time for it to go in.
Thanks again for the massive work @CastagnaIT

**Comment by jjd-uk** [comment]
It seems both yourself @enen92 and @thexai have well tested this, so I'd agree lets get this merged. We are still early in the v20 release cycle so any potential breakage would not be a big deal, and finding any issues early gives more time to resolve.

**Comment by ksooo** [comment]
I know I'm late to the party, but next time if you introduce no strings to translate, provide conextual information in the po file (those line beginning with `#.`and `#:`). Translators really need these contextual information to be able to procide high quality translations.

TBH, I would prefer if @CastagnaIT would provide a follow-up PR to add those pieces of information.

**Comment by wsnipex** [comment]
this broke subtitles on linux(ubuntu PPA).
Looks like the subtitle renderer is initialized normally, no errors, but no subs are shown. Tested with libass 0.14 and 0.15.2, makes no difference.

I've tried to bisect, but since most commits here are not compiling, the list of possible culprits is long:

> There are only 'skip'ped commits left to test.
The first bad commit could be any of:
c70eb9b1c0a7d6cc77737da3f8cf1938c929ea9e
0b7c6acccbf3318dd000d051c42df3d53f50beb2
661ed672ca8cf743672fabacf44d8d6aedd43250
613ceea5f418bb25f55da1848cf3b9c8a4c44434
ada5b198089b54a8c85fa431793e5b39a5f8f667
9a72f0d1808a3569d1a14a8912b7d79e3dc73a67
ab467e31c30ab296d67a2208c42bd058bebe962d
afdd1428283c800a134cc09f1ec4c7cfb13d8ecf
fca93c8ae595513ef68bcfe4ea04f54cee128ad4
5e100729f81c1538c601e8b708c8f960c933ed9a
7757cd17038b69ca43fd96dc2a3472286dd429df
728162be9eb22b226c25f46fc2cf34e459ad96f1
e08d299d35cf1f262543c1da87e5ef23770c0c3a
a2445e17020341de2ad22fda7a2a4d6ffb8b770b
c2cf8736bd0005a6f84d594d0fedcf18fa403507
2fada9640fbc1cb8e736b702bbc8f7ef7b283557
75aed8876e31da18ff4d4c2ab05f8380d2f5c7c2
054ee81f903ba4ce44e8e3d8ac73a04650fc2c62
792806800e48ca7c6c1f1cba06b66fd7ad9230b2
12b047a2997579c1f05fac69ff3b2008e5de7749
We cannot bisect more!

**Comment by CastagnaIT** [comment]
i have tried on virtualbox on old lubuntu
no need bisect code just read the kodi log
at least with my test happen this, I don't know if it's the same with you

https://paste.kodi.tv/izozobutej.kodi

there are a lot of

> CDVDSubtitlesLibass: [ass] No style found

this is an error output by libass library itself because prefixed by `[ass]`,
for some reason apparently seem that libass still read the old "m_track" values instead get the updated one when ApplyStyle (DVDSubtitlesLibass.cpp) create the style.

I would have expected that using ASS/SSA with override font and styles should have worked properly, 
in this case it does not generate errors but subs are not displayed, this is another strange situation
as if the set style for the override did not exist but at the same time there was...

somewhat bizarre situation as it works correctly with other systems

**Comment by phunkyfish** [comment]
@lrusak is that a Jenkins check that can be added to check that all commits in a PR compile? Most of the gnarly bugs I have fixed would have been impossible to fix without bisecting.

**Comment by CastagnaIT** [comment]
due to the large work it was impossible to ensure that every single commit would be compiled
otherwise I would have done a single commit with all changes merged otherwise it was a nightmare to do this..

**Comment by wsnipex** [comment]
here is a log from master with libass 0.15.2: https://paste.kodi.tv/osunuhover.kodi

**Comment by CastagnaIT** [comment]
your log is also different from my, so no errors
buf you have the last libass version, and on my kodi installed to lubuntu is specified an old libass version
I have little knowledge of how things work on linux, libass needs to be updated manually in some way?

**Comment by wsnipex** [comment]
I initially suspected the old libass version in ubuntu as the culprit, so I compiled 0.15.2 myself. Then I noticed that it doesn't make a difference.
In case 0.15.2 is _required_ I'll update the package for our PPA.

**Comment by CastagnaIT** [comment]
the current libass lubuntu version 0.14 is a very old version i don't know if could cause problems
but as far as i can see, subtitle "style" is not applied in my case
in yours there is no such error but still something wrong happens

could you try to do these tests, with last libass version?
1) play a video with an ASS/SSA subtitle (all ASS overrides in subtitle settings have to be Disabled)

2)
- Go to kodi subtitle settings set:
override ass font to OFF
override ass style to "Style"
- play a video with an ASS/SSA subtitle

**Comment by wsnipex** [comment]
I'll try to, once I find something with ASS subs, I don't usually use subs and don't seem to have something to test with.

In the meantime, I've put updated libass 0.15.2 packages in this PPA: https://launchpad.net/~wsnipex/+archive/ubuntu/test

**Comment by CastagnaIT** [comment]
thanks for the ppa, I was able to update libass to lubuntu
i have done the tests mentioned, and now i can have your same results
if you need ASS file to do other tests: [TestASS.zip](https://github.com/xbmc/xbmc/files/7267219/TestASS.zip)

**Comment by CastagnaIT** [comment]
i have tried Kodi 19 release on last ubuntu (virtualbox) and also here the ASS subtitles are not displayed
is possible that the problem have something related to #20196 ?

**Comment by enen92** [comment]
I tested this on ubuntu 18.04 with the latest nightly from nightly PPA and ASS subtitles work, however srt subtitles (adapted to ass) are not displayed on screen. The log doesn't show anything of relevance though

**Comment by enen92** [comment]
@CastagnaIT stepping through the debugger shows that ASS_Events created on the adapter have an hardcoded style ID of 1:

https://github.com/xbmc/xbmc/blob/b9ef15302bfd6e9d8d1c82952e9d882e4e9457eb/xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp#L464

However when we allocate the default kodi style, as there is no other available the ID is 0. Hardcoding the id=0 in the above line makes the subtitles being displayed. We have to populate the style ID with the result of `ass_alloc_style` not assume it's always a fixed value.

**Comment by CastagnaIT** [comment]
> . Hardcoding the id=0 in the above line makes the subtitles being displayed (but it's not a proper fix).

this because the style with ID 0 already exists by default (created by libass by default)
we ensure that we always have ID 1 because we always restore the counter with the previous numbering
but if the problem is that the style pre-allocation is missing, should be easy to solve if it works...
please try build kodi for ubuntu with this patch [fixtest.diff.txt](https://github.com/xbmc/xbmc/files/7269493/fixtest.diff.txt)

**Comment by enen92** [comment]
@CastagnaIT I don't like the proposed solution. Using hardcoded ids is always a bad idea as it strongly depends on the library internal implementation.
I've submited https://github.com/xbmc/xbmc/pull/20217 as a possible alternative. Would you be kind to provide some feedback?
