### PR TITLE
[guilib][EditControl] Improved rendering of label texts

### LINKED ISSUE #21184: When French labels are too long in settings, we can't see the selected values next to the label
### Describe the bug
Here is a clear and concise description of what the problem is:

When French labels are too long in settings, we can't see the selected values next to the label

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

labels not too long, be able to see the selected values in settings

## Actual Behavior

French labels too long in settings, unable to see the selected values

## Possible Fix

Scrolling label shorter on the left, show selected value every time.

### To Reproduce

1. change regional language to French in Kodi
2. go to inputstream adaptive settings
3. cry because you cannot see the settings values

### Debuglog

The debuglog can be found here:
**not applicable**

### Screenshots
Here are some links or screenshots to help explain the problem:

image
image

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

- [ ] Android
- [ ] iOS
- [ ] tvOS
- [x] Linux
- [ ] OSX
- [x] Windows
- [ ] Windows UWP

- Operating system version/name:
- Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

This PR fix labels on the edit control and since was related implement truncate for right-aligned text by removing some GUI label hacks

**Truncate for right-aligned text**
the previous implementation did not contemplate truncate for right-aligned text
so was not possible add ellipses ("...") to the left nor truncate to the left the text,
so some hacks were made to the GUI to limit some use cases (like force x offset to shift the rendering and so hidden the text that exceeds the available space, force remove align attribute...),
so here i implemented truncate for right-aligned text, imo a good find for edit control and in general to let the user know that the text is truncated to the left

**Edit control, labels improvements**
If on the edit control you set the text on the left and on the right labels (like on settings panel),
and the left label text is so long that exceeds the control width, will result that overlap and erase the text on the right label and so remove the editable field, as you can see on the first screenshot below (and on https://github.com/xbmc/xbmc/issues/21184#issuecomment-1094801495)

This PR improve the situation by limiting the maximum width for the left lable text,
then when not focused it can take max 70% of space, when focused max to 50% to allow have more space when editing the value

Previous broken implementation, the right label start to be erased
immagine

Now, on preview, the left label width limited to max 70%, the left label and right label when the text exceeds the available space ellipses ("...") will be add to the appropriate position, and the text is truncated on the left for right-aligned text
immagine

Now, with focus, so while editing, the left label width is limited to max 50% of space and the text auto-scroll
immagine

Another example, with short text on left label:
immagine
in this case the right label can take all space available to display in full the preview value

**Edit control, related alignment bugfix**
This bug can be shown easily with keyboard window, so when you edit a text,
initially the text is shown at center of the gray text box,
but if you write a long text that exceeds the limits of the gray text box width,
and after you delete all the text, will lost the text alignment and "fallback" as left-aligned text
as following screenshot
immagine
the fix take care to preserve the alignment

Changes to GUIFontTTF.cpp are required because our rendering works as left-to-right.

## Motivation and context

fix #21184

## How has this been tested?

a couple of editing control with text, numeric, IP field and keyboard window

for GUI label i tested truncate for right-aligned text with a python addon on a custom XML window
by using
```xml
<control type="label" id="55000">
...
  <scroll>false</scroll> <!-- false to apply truncate-->
  <align>right</align>
...
```

verified CGUITextBox for possible regressions on right-aligned text
```xml
<control type="textbox" id="55001">
...
  <autoscroll>false</autoscroll>
  <align>right</align>
...
```

## What is the effect on users?

for GUI label support truncate for right-aligned text
in general better user experience

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
marked WIP, i have found kind of problem, i need to investigate better

**Comment by CastagnaIT** [comment]
marked again WIP,
i found a side effect on textbox control i need to investigate what happens

File: xbmc/guilib/GUIEditControl.cpp [hunk 1]
```diff
@@ -24,38 +24,58 @@
...
+                                           "jkl5JKL",
+                                           "mno6MNO",
+                                           "pqrs7PQRS",
+                                           "tuv8TUV",
+                                           "wxyz9WXYZ"};
+
+constexpr float smsDelay = 1000;
+
+// Additional space between left label text and left label text
+constexpr float TEXT_SPACE = 20.0f;
```
Comment (garbear) [inline xbmc/guilib/GUIEditControl.cpp:53]: What are the units here? Does this assume a 1920x1080 skin?

Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp:53]: the use of "space" variables along most gui controls has been done more than 10y old
and the only ancient refactor do not explains nothing,
for sure are pixels, i too have theorised for 1920x1080 i believe no documentation exists

Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp:53]: for example in a 1080p display, if you put kodi windowed, by debugging all control rendering variables
you still have values for full 1080p, seem all them are scaled to another place

Comment (garbear) [reply xbmc/guilib/GUIEditControl.cpp:53]: I think I understand that. You mean a skin that defines a 1080p folder, right? if you put Kodi windows, all control dimensions are scaled to 1080p. But what about a 720p skin like Confluence? Will that still scale by 720 or will it scale by 1080?

Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp:53]: these GUI thing has always confused me because are not so clear,
what i can say is that properties like gui control width/height has px based on the xml skin resolution
but other values like x/y are referred to current display resolution widowed or full
but by debugging ProcessText/RenderText i remember that if i am in windowed mode i have to take in account that calculated coordinates values are based full screen, i cannot tell you specifically how the kodi GUI works because it would take days to try investigate
but in any case these are pixel unit

Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp:53]: but whats your request on this variable?

Comment (garbear) [reply xbmc/guilib/GUIEditControl.cpp:53]: Chose one of two requests:

* Spend days, if not years, figuring out what the heck is going on
* Do what works, if this variable works for you, do it

I'd choose the second :wink:

Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp:53]: yeah i also choose the second one😐
this variable had a different name before just renamed and increased value other gui controls do the same so good as is

Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp:53]: rebased and add "in pixels" in the description

**Comment by CastagnaIT** [comment]
@CrystalP do you have a chance to review?

**Comment by CrystalP** [comment]
@CastagnaIT sure I could take a look next chance I get - should be this week.

File: xbmc/guilib/GUIEditControl.cpp [hunk 2]
```diff
@@ -379,25 +399,22 @@ void CGUIEditControl::SetInputType(CGUIEditControl::INPUT_TYPE type, const CVari
...
-  if (leftTextWidth > 0)
-    maxTextWidth -= leftTextWidth + spaceWidth;
+  const std::wstring text = GetDisplayedText();
+  const float textWidth = m_label2.CalcTextWidth(text + L'|');
+  const float beforeCursorWidth = m_label2.CalcTextWidth(text.substr(0, m_cursorPos));
+  const float afterCursorWidth = m_label2.CalcTextWidth(text.substr(0, m_cursorPos) + L'|');
+  const float leftTextWidth = std::min(m_label.GetTextWidth(), m_label.GetMaxWidth());
+  float maxTextWidth = m_width - 2 * m_label.GetLabelInfo().offsetX;
 
-  // if skinner forgot to set height :p
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp:396]: its not removed but moved some lines above
i will add a warning log

File: xbmc/guilib/GUIFontTTF.cpp [hunk 3]
```diff
@@ -428,6 +437,28 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
...
       startX -= w;
     }
+    else if (alignment & XBFONT_RIGHT && alignment & XBFONT_TRUNCATED)
+    {
+      // We need to determinate where the text will be truncated on the left
+      // by taking in account that we have also to add ellipses before the text
+      float textWidth = ellipsesWidth;
+      // We need to iterate from the end to the beginning
+      auto itRGliph = glyphs.rbegin();
+      for (; itRGliph != glyphs.rend(); itRGliph++)
```
Comment (enen92) [inline xbmc/guilib/GUIFontTTF.cpp:447]: Possible to combine on a single line?
```suggestion
      for (auto itRGliph = glyphs.rbegin(); itRGliph != glyphs.rend(); itRGliph++)
```

File: xbmc/guilib/GUIEditControl.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (enen92) [reply xbmc/guilib/GUIEditControl.cpp:396]: ah right

**Review by enen92 — APPROVED** [review]
Looks good to me. Only minor comments left.

File: xbmc/guilib/GUIFontTTF.cpp (hunk 3 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIFontTTF.cpp]: done

**Comment by CrystalP** [comment]
@CastagnaIT didn't have much time this week + was finishing a project, I'll start reviewing. But it looks like it got a pretty good look already.

File: xbmc/guilib/GUITextBox.cpp [hunk 4]
```diff
@@ -241,10 +241,22 @@ void CGUITextBox::Render()
...
+
+        if (lineString.m_text.size() && lineString.m_carriageReturn)
           align &= ~XBFONT_JUSTIFIED; // last line of a paragraph shouldn't be justified
-        m_font->DrawText(posX, posY, m_colors, m_label.shadowColor, m_lines[current].m_text, align, m_width);
+
+        if (align & XBFONT_RIGHT)
+        {
+          // We need to adjust the posX in similar way the CGUILabel recalculate the render rect
+          // see CGUILabel::UpdateRenderRect()
+          linePosX -= GetTextWidth(lineString.GetAsString());
```
Comment (CrystalP) [inline xbmc/guilib/GUITextBox.cpp:255]: That doesn't seem right for unicode? Seems that a CGUIString is a vector of uint32_t, so most likely meant to accept UTF32, to be confirmed though.
A new GetTextWidth that accepts a vecText would preserve unicode data & avoid a trip through string?

**Comment by CrystalP** [comment]
For that movie there is a regression when the textbox is made right-aligned (line 2 truncated, all lines do not end at the same place)
(add align tag to block line 127 in DialogVideoInfo.xml of Estuary)
Left aligned and justified are still fine (line 2 not truncated, all lines start/end at the same vertical position). Many other movies are fine,

master (OK):
image

PR (regression):
image

File: xbmc/guilib/GUIFontTTF.cpp [hunk 5]
```diff
@@ -443,20 +443,22 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
       // by taking in account that we have also to add ellipses before the text
       float textWidth = ellipsesWidth;
       // We need to iterate from the end to the beginning
-      auto itRGliph = glyphs.rbegin();
-      for (; itRGliph != glyphs.rend(); itRGliph++)
+      for (auto itRGliph = glyphs.rbegin(); itRGliph != glyphs.rend(); itRGliph++)
```
Comment (CrystalP) [inline xbmc/guilib/GUIFontTTF.cpp:446]: isn't ++itRGliph preferred?

Comment (CastagnaIT) [reply xbmc/guilib/GUIFontTTF.cpp:446]: hmm depends on the compiler, if compiler optimizations are disabled using prefix on "for each" is more fast, otherwise there is same performances with both prefix/postfix
however i will change with prefix just to be sure

File: xbmc/guilib/GUIEditControl.cpp [hunk 6]
```diff
@@ -424,45 +447,55 @@ void CGUIEditControl::ProcessText(unsigned int currentTime)
...
-      { // align by whatever the skinner requests
-        align |= (m_label2.GetLabelInfo().align & 3);
-      }
+    if (leftTextWidth > 0)
+    { // right align as we have 2 labels
+      align |= XBFONT_RIGHT;
+    }
+    else
+    { // align by whatever the skinner requests
+      align |= (m_label2.GetLabelInfo().align & 3);
```
Comment (CrystalP) [inline xbmc/guilib/GUIEditControl.cpp:496]: (XBFONT_RIGHT | XBFONT_CENTER_X) instead of 3?
horizontal alignment XBFONT_JUSTIFIED is ignored, on purpose?

File: xbmc/guilib/GUIFontTTF.cpp [hunk 7]
```diff
@@ -504,36 +550,58 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
...
+              cursorX += period->m_advance;
+            }
+          }
+          if (maxPixelWidth > 0 && cursorX > maxPixelWidth)
+            break; // exceeded max allowed width - stop rendering
+        }
+        else
+        {
+          // Check if we will be exceeded the max allowed width
+          if (cursorX + ch->m_advance + 3 * m_ellipsesWidth > maxPixelWidth)
```
Comment (CrystalP) [inline xbmc/guilib/GUIFontTTF.cpp:577]: ellipsesWidth instead of 3 * m_ellipsesWidth

File: xbmc/guilib/GUIFontTTF.cpp (hunk 5 above)
Comment (CrystalP) [reply xbmc/guilib/GUIFontTTF.cpp:446]: crbegin / crend? no difference on Windows but maybe for other platforms

File: xbmc/guilib/GUIFontTTF.cpp (hunk 3 above)
Comment (CrystalP) [reply xbmc/guilib/GUIFontTTF.cpp]: itRGlyph please

File: xbmc/guilib/GUIEditControl.cpp (hunk 6 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp:496]: no idea this is not my code then i have no investigated
i have just changed space indentation
cleanups on existing code can be done with separate prs

**Comment by CastagnaIT** [comment]
@CrystalP i tried replicate your Plot info in screenshot by assuming that all text is one single line without any return characters
but to me is shown as follow (at least with current updated PR) at least on Windows OS:
immagine
tried switch fullscreen and widowed but always same results, can you recheck and if needed provide more details to replicate?

**Comment by CrystalP** [comment]
> can you recheck and if needed provide more details to replicate?
It's fixed after your updates.

File: xbmc/guilib/GUIFontTTF.cpp [hunk 8]
```diff
@@ -428,6 +437,30 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
...
+            GetCharacter(text[itRGlyph->m_glyphInfo.cluster], itRGlyph->m_glyphInfo.codepoint);
+        if (!ch)
+          continue;
+
+        textWidth += ch->m_advance;
+
+        if (textWidth > maxPixelWidth)
+        {
+          // Start rendering from left truncation position
+          startPosGliph = std::distance(itRGlyph, glyphs.crend());
```
Comment (CrystalP) [inline xbmc/guilib/GUIFontTTF.cpp:458]: startPosGl**y**ph instead of startPosGliph please

File: xbmc/guilib/GUIFontTTF.cpp [hunk 9]
```diff
@@ -428,6 +437,30 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
       // Offset this line's starting position
       startX -= w;
     }
+    else if (alignment & XBFONT_RIGHT && alignment & XBFONT_TRUNCATED)
```
Comment (CrystalP) [inline xbmc/guilib/GUIFontTTF.cpp:440]: I think there is a problem with right alignment and no truncated flag.
If alignment parameter is initially RIGHT | TRUNCATED, then TRUNCATED is removed @line 407 when the text fits > this block is skipped, OK
If alignment parameter is RIGHT | TRUNCATED, and the text doesn't fit > handled by this block, OK
If alignment parameter is RIGHT without TRUNCATED and the text doesn't fit > not handled, or I missed it

Without TRUNCATED I'm not sure if you should stop at the last character that will not be clipped at all, or the next one that will be partially clipped. Should be the same as what is done by current code for left alignment and no TRUNCATED.

File: xbmc/guilib/GUIEditControl.cpp (hunk 6 above)
Comment (CrystalP) [reply xbmc/guilib/GUIEditControl.cpp:496]: I suppose justified wouldn't be very useful in an edit control.
Replacing the magic number would still be nice, did you have other things in mind for a cleanup PR?

Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp]: i have no plan to make a cleanup pr soon...
i have add a separate commit to replace magic n

**Review by CrystalP — APPROVED** [review]
Looks ok, runs fine when forcing everything to right-aligned and navigating through Estuary. The remaining display problems are not regressions and are due to skin and/or other types of controls not in scope of this change.
Well done!
