### PR TITLE
[video] Fix playback of multi-version movies. Do not prompt for versi…

### LINKED ISSUE #24322: [Video Versions] When default select is "Show info" user is prompted to select version before information dialog is displayed.
### Describe the bug
Here is a clear and concise description of what the problem is:

When default select action is "Show information", selecting a movie with versions asks user to select a version both before displaying the info dialog and after selecting play in the dialog.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The user should only be asked to select a version once (when attempting playback).

As the info dialog is not specific to the version, the user should not be asked to select a version before displaying the info dialog.

## Actual Behavior

User is asked to select a version before the info dialog is displayed.

### To Reproduce

1. Set default select action to "Show information" and disable playing defaulting version.
2. Click a movie in library with versions
3. Prompt to select a version is displayed.
4. Select a version and info is displayed.
5. Click "Play" in info dialog and asked to select a version again.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/13770058/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Omega v21 nightlies

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
…on to play, as we already know it from the context of the info dialog.

Fixes #24322 

In the context of the info dialog, we always display information for a certain version. No need to ask which one to play.

@jurialmunkey fyi

Runtime-tested on macOS, latest Kodi master.

@enen92 should be simple to review. We have an item property to control whether version chooser will be used.

### CODE REVIEW

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp [hunk 1]
```diff
@@ -793,6 +793,9 @@ void CGUIDialogVideoInfo::Play(bool resume)
   // close our dialog
   Close(true);
 
+  // play the current video version, even if multiple versions are available
+  m_movieItem->SetProperty("prohibit_choose_video_version", true);
```
Comment (enen92) [inline xbmc/video/dialogs/GUIDialogVideoInfo.cpp:797]: Although this is just an arbitrary string I'd change it to the actual cause that will then block the action and not the action itself. You're augmenting the item with a new property which should be independent from the respective action. E.g. if for some reason you kill the choose dialog it does not make sense anymore.
Make it like has_resolved_version or something similar

Comment (ksooo) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp:797]: I agree in general , but this property is just a temporary construct and was not introduced by this PR. I don’t want to put too much effort into this interim stuff.

Comment (ksooo) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp:797]: Okay, what you say makes sense. I will change the property name in a separate commit. Thanks.

Comment (ksooo) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp]: done.

**Review by enen92 — APPROVED** [review]
Thanks much

**Comment by CrystalP** [comment]
Does what it says but maybe a bit premature, as versions are not independent movies (yet).

> In the context of the info dialog, we always display information for a certain version. No need to ask which one to play.

Not in my tests. The information displayed is that of the "root" movie that versions were added to.
Versions can only have individual artwork at this point, but it is not used in the info dialog (tested by changing the poster from default on all versions of a movie).

**Comment by ksooo** [comment]
> Does what it says but maybe a bit premature, as versions are not independent movies (yet).

Step by step, in small chunks, okay? Otherwise we end up with monster PRs. The fix is needed as of now. Everything else can be fixed separately. *Logically* the info dialog displays for a certain version already. There are bugs (e.g. artwork) and due to the broken data model no real metadata per version. But this is where we are heading to.

**Comment by ksooo** [comment]
> Versions can only have individual artwork at this point, but it is not used in the info dialog (tested by changing the poster from default on all versions of a movie).

Please open an issue for the artwork problem.

**Comment by jurialmunkey** [comment]
I appreciate the quick fix. Behaviour is much improved. 

I'm assuming a subsequent PR will change where select appears to make it consistent with how `Action(Info)` behaves? i.e.
_Click movie > Opens default version info > Click play > Select version_

Can see how this change sets up future possibilities for toggling whether info asks to select or shows default, so I'm not much fussed about the order itself, only the inconsistency between an info key press and select as info key press.

Very much low priority, but thought it worth mentioning. Can open a new issue for this if you'd like?

**Comment by ksooo** [comment]
Write an issue, please. So we don’t forget.
