### PR TITLE
[Subtitles] Improvements vertical margin and manual position

### LINKED ISSUE #21298: Vertical subtitle position incorrectly written to / read from guisettings.xml
### Describe the bug
Here is a clear and concise description of what the problem is:

Since the 20220421 nightly (or maybe a bit sooner), the vertical subtitle position is incorrectly being written to / read from guisettings.xml.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Before the bug, I had the subtitle position for all my refresh rates set to 1008. When going back to the Video Calibration screen after configuring, this value was correctly shown again. And during playback, the subtitles were in the desired position.

## Actual Behavior

While playing some media, I noticed my subtitles were suddenly being displayed a lot higher vertically.
When I checked the Video Calibration screen, the value showed there as "933" even though it was previously set at 1008.
Even more strangely, when I set the value back to 1008 and then looked in guisettings.xml, the value stored there was 1083.
Also, when clearing out all resolutions from guisettings.xml and having Kodi write them fresh, the subtitle positions now defaults to the same value as the vertical resolution (i.e. 480 for all 720x480 resolutions, 720 for all 1280x720 resolutions and 1080 for all 1920x1080 resolutions; exception: 1080 is also set for all 3840x2160 resolutions).

### To Reproduce

1. Go to System -> Video -> Video Calibration
2. Configure your desired subtitle position (I used 1008)
3. Exit the calibration screen
4. Exit Kodi
5. Check guisettings.xml. Value there shows as 1083
6. Restart Kodi and go to the calibration screen again. The subtitle position now shows 1005.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/rinapiluxo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11 on Nvidia Shield Experience 9.0.2
 - Kodi version: kodi-20220421-3f3a3c94-master-22457-arm64-v8a

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

in PR's where i have reworked subtitles renderer/features, i have introduced vertical margin support
(until now temporary can only be overwritten through advanced settings xml)
i have noticed that vertical margin can confuse some users (see #21298)

the reason is that the calibration window displays the value of the displayed text position
therefore implicitly exclude vertical margins (because the value is from top),
so the value saved in xml is the one with vertical margins.

to make it clearer the situation i have shown both values in Video calibration GUI:
immagine

and i have add a new GUI setting "vertical margin" (and removed the one in advanced settings):
immagine
in this way the user is aware of the vertical margin, and can read in the description that will influence also the Video calibration.

The value is in percentage instead of pixels, this to fit the screen resolution in use,
otherwise the value will results always wrong at the resolution change ("Adjust refresh rate" setting enabled case)

## Motivation and context

An user #21298 think to a bug because did not understand the reason for the different value between xml file / GUI Calibration window

fix #21298 little bug in saving/loading position value
fix https://github.com/xbmc/xbmc/pull/21026#issuecomment-1104531231 to save value permanently position value changed via e.g. shortcut (kept after kodi restart)

## What is the effect on users?

better understand vertical margin functionality and its influence
allows to change vertical margin from GUI
can save permanently subtitle position changed e.g. via keyboard (by using e.g. `SubtitleShiftUp(save)`)

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
Applied dont merge because i found just now a problem
while change vertical margin if you do video backward weird thing happens

**Comment by CastagnaIT** [comment]
seem that libass cache margin somewhere
for now disabled the vertical margin settings during the playback

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.h [hunk 1]
```diff
@@ -136,17 +142,17 @@ namespace OVERLAY {
     void SetSubtitleVerticalPosition(const int value, bool save);
 
     /*!
-     * \brief Reset the subtitle position to default value
+     * \brief Get the subtitle vertical margin in percentage
+     * \return The percentage value
      */
-    void ResetSubtitlePosition();
+    static double GetSubtitleVerticalMarginPerc();
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.h:148]: Any reason for a double instead of float? I don't think we need that level of precision here (also double is 64bit)

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp [hunk 2]
```diff
@@ -580,25 +602,21 @@ void CRenderer::LoadSettings()
...
 
-  // Try get the vertical margin customized by user
-  int overrideMerginVertical =
-      CServiceBroker::GetSettingsComponent()->GetAdvancedSettings()->m_videoSubtitleVerticalMargin;
-
-  if (overrideMerginVertical >= 0)
-    return overrideMerginVertical;
-
-  return KODI::SUBTITLES::MARGIN_VERTICAL;
+  return settings->GetNumber(CSettings::SETTING_SUBTITLES_MARGINVERTICAL);
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:621]: Would be nice to wrap this as a getter in SubtitlesSettings to avoid spreading raw setting access everywhere (better encapsulation)

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp [hunk 3]
```diff
@@ -580,25 +602,21 @@ void CRenderer::LoadSettings()
...
 }
 
-int CRenderer::GetSubtitleVerticalMargin()
+double CRenderer::GetSubtitleVerticalMarginPerc()
 {
-  int subAlign = CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(
-      CSettings::SETTING_SUBTITLES_ALIGN);
+  // We return the vertical margin as percentage
+  // to fit the current screen resolution
+  const std::shared_ptr<CSettings> settings{CServiceBroker::GetSettingsComponent()->GetSettings()};
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:612]: Same for this one: Would be nice to wrap this as a getter in SubtitlesSettings to avoid spreading raw setting access everywhere (better encapsulation)

Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:612]: Same for this one: Would be nice to wrap this as a getter in SubtitlesSettings to avoid spreading raw setting access everywhere (better encapsulation)

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp [hunk 4]
```diff
@@ -580,25 +602,21 @@ void CRenderer::LoadSettings()
   m_subtitleHorizontalAlign = static_cast<SubtitleHorizontalAlign>(
       CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(
           CSettings::SETTING_SUBTITLES_CAPTIONSALIGN));
+  ResetSubtitlePosition();
 }
 
-int CRenderer::GetSubtitleVerticalMargin()
+double CRenderer::GetSubtitleVerticalMarginPerc()
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:608]: float?

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp [hunk 5]
```diff
@@ -373,7 +390,11 @@ void CRenderer::CreateSubtitlesStyle()
   else
     m_overlayStyle->assOverrideStyles = KODI::SUBTITLES::OverrideStyles::DISABLED;
 
-  m_overlayStyle->marginVertical = GetSubtitleVerticalMargin();
+  // Changing vertical margin while in playback causes side effects when you
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:393]: Not against this but probably requires deeper investigation? Probably some issue in libass itself?

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h [hunk 6]
```diff
@@ -22,7 +22,7 @@ constexpr double VIEWPORT_WIDTH = 1920.0;
 constexpr int MARGIN_VERTICAL = 75;
 // Vertical margin used when is selected the alignment
 // to keep the text inside the black bars
-constexpr int MARGIN_VERTICAL_BLACKBARS = 30;
+constexpr double MARGIN_VERTICAL_BLACKBARS = 2.75; // in %
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:25]: float?

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.h (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.h:148]: because i kept same type of `GetNumber` return type
ofc i can change it and add a type cast

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp [hunk 7]
```diff
@@ -57,11 +57,13 @@ unsigned int CRenderer::m_textureid = 1;
 CRenderer::CRenderer()
 {
   KODI::SUBTITLES::CSubtitlesSettings::GetInstance().RegisterObserver(this);
+  CServiceBroker::GetWinSystem()->GetGfxContext().RegisterObserver(this);
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:60]: This couples the overlay renderer with the graphic context/GUI. I am not sure this is something we would want

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp (hunk 5 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:393]: i tried check libass code but i found nothing i could understand
i can try to report it but we already know how it will end...

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp (hunk 7 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:60]: there is currently no usable callbacks, the only one implemented is for GUI purpose
if there is a alternative way to get the callback welcome suggestions

Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:60]: I wonder, isn't setVideoRect called when the resize happens? Couldn't this be used instead of going the observer route?

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:60]: i will check

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.h (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.h]: done

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp]: add method try look

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp [hunk 8]
```diff
@@ -277,6 +289,12 @@ bool CRenderer::HasOverlay(int idx)
 
 void CRenderer::SetVideoRect(CRect &source, CRect &dest, CRect &view)
 {
+  if (m_rv != view)
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:292]: Glad to see this worked. Without wanting to be a pain in the ass do you mind turning this into a some sort of "callback" function call? Something on the lines of:

```
if (m_rv != view)
  OnViewChanged()
```

Also I am not sure if you shouldn't simply give up if the lock is locked - depends on who calls `SetVideoRect`. I am assuming it is the render thread. If that the case locking is something that you should try to avoid (or employ some sort of lazy approach: try lock -> change, islocked -> give up. The event (`m_isSettingsChanged`) will be recorded anyway

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp [hunk 9]
```diff
@@ -577,28 +601,24 @@ void CRenderer::Notify(const Observable& obs, const ObservableMessage msg)
 
 void CRenderer::LoadSettings()
 {
-  m_subtitleHorizontalAlign = static_cast<SubtitleHorizontalAlign>(
-      CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(
+  m_subtitleHorizontalAlign =
+      static_cast<SubtitleHorizontalAlign>(SUBTITLES::CSubtitlesSettings::GetSettings()->GetInt(
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:605]: Hum my suggestion was to extend the `CSubtitleSettings` class with your access methods:

```cpp
SubtitleHorizontalAlign CSubtitlesSettings::GetHorizontalAlignment () 
{
   return static_cast<SubtitleHorizontalAlign>(m_settings->GetInt(CSettings::SETTING_SUBTITLES_CAPTIONSALIGN));
}
```

Same for other access methods. At the moment the class is a singleton (but only used by OverlayRenderer) but maybe at some point (depending on who can access it) it can be even made a simple member var)

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp (hunk 8 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:292]: I'd have to actually tested. I've done something similar recently (didn't went in but the implementation might be similar):

https://github.com/xbmc/xbmc/pull/21111/files#diff-204721060df48a53f6d011516f7680586a061ebe67336ceeecc1cce296c2a08aR439-R447

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp (hunk 9 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp]: done, moved all settings in CSubtitlesSettings

**Review by enen92 — APPROVED** [review]
LGTM, thanks for taking my comments into consideration.

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.h [hunk 10]
```diff
@@ -192,9 +175,11 @@ namespace OVERLAY {
...
     int m_subtitleVerticalMargin{0};
-    SubtitleHorizontalAlign m_subtitleHorizontalAlign{SubtitleHorizontalAlign::CENTER};
+    bool m_saveSubtitlePosition{false}; // To save subtitle position permanently
+    KODI::SUBTITLES::HorizontalAlign m_subtitleHorizontalAlign{
+        KODI::SUBTITLES::HorizontalAlign::CENTER};
 
-    std::shared_ptr<struct KODI::SUBTITLES::style> m_overlayStyle;
-    bool m_isSettingsChanged{false};
+    std::shared_ptr<struct KODI::SUBTITLES::STYLE::style> m_overlayStyle;
+    std::atomic<bool> m_isSettingsChanged{false};
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.h:184]: done
