### PR TITLE
[guilib] let oninfo propagate from the item to the container if the c…

### LINKED ISSUE #23838: <oninfo> Does not work for static content in list controls
### Describe the bug
Here is a clear and concise description of what the problem is:

`<oninfo>` tags in a skin do not work for list controls when static `<content><item>` items are defined.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The `<oninfo>` action should be performed when pressing info on a list control with static content just like it does when using dynamic plugin content.

## Actual Behavior

Nothing happens when pressing info despite `<oninfo>` tags being defined in the list control.

### To Reproduce

In Estuary Home.xml add an `<oninfo>ActivateWindow(settings)</oninfo>` tag to the list control with id="9000" (Home side menu).

Pressing info on the side menu *should* now open settings when pressing info but nothing occurs.

I have also tested with placing `<oninfo>` inside the `<item>` tags, which also does nothing.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/ugodujifop.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Omega Alpha 3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
…ontainer cannot handle the item info

## Description
This is precisely the case of `CStaticListProvider`(s) (see https://github.com/xbmc/xbmc/blob/489f1bcf686c5a62b5ef41b4be5a6060559cc3d3/xbmc/listproviders/StaticProvider.h#L29) which cannot pass the info evaluation into the item. The current code returns true regardless avoiding the evaluation of the info that could be bound to the parent control. 

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/23838

## How has this been tested?
Runtime tested with the procedure of the bug report

## What is the effect on users?
Info should be executed if defined on `<oninfo>` of static list containers.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

File: xbmc/guilib/GUIBaseContainer.cpp [hunk 1]
```diff
@@ -404,14 +404,14 @@ bool CGUIBaseContainer::OnAction(const CAction &action)
...
     if (m_listProvider)
     {
-      int selected = GetSelectedItem();
+      const int selected = GetSelectedItem();
       if (selected >= 0 && selected < static_cast<int>(m_items.size()))
       {
-        m_listProvider->OnInfo(m_items[selected]);
-        return true;
+          if (m_listProvider->OnInfo(m_items[selected]))
+            return true;
```
Comment (ksooo) [inline xbmc/guilib/GUIBaseContainer.cpp:411]: Indentation looks wrong.

Comment (enen92) [reply xbmc/guilib/GUIBaseContainer.cpp:411]: well it was done by `clang-format` :shrug:

Comment (ksooo) [reply xbmc/guilib/GUIBaseContainer.cpp:411]: > well it was done by clang-format 🤷

I had such cases as well, were clang-format obviously did it wrong. I guess it happens if the file contains many style errors then clang-format gets "confused". In your case the if now is indented 3 spaces, which is obviously wrong.

**Comment by enen92** [comment]
@ksooo good to go? This is pretty much a no brainer. Clang format was addressed already.

**Review by ksooo — APPROVED** [review]
LGTM.
