### PR TITLE
VideoTagInfoLoaderFFmpeg: Resolve stack before trying to process

### LINKED ISSUE #15638: Changing the artwork of multipart video files crashes Kodi
### Describe the bug
Kodi crashes when changing the artwork of multipart video files.

## Expected Behavior
No crash

## Actual Behavior
Crash

### To Reproduce
1. Use a multipart video, for example:
"Video part01.mp4"
"Video part02.mp4"
"Video part03.mp4"

2. Changing the poster or fanart leads to an immediate crash.

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 8.0 & Windows 10

 - Kodi version: Kodi 18 Final, Kodi 18.1 Final, Kodi 18.2 Nightly

### PR DESCRIPTION
**Pull request by a1rwulf**
## Description
Resolve a fileitems stack and use the first stackitem to initialize ffmpeg.

## Motivation and Context
Fixes: https://github.com/xbmc/xbmc/issues/15638

## How Has This Been Tested?
Tested to set art for normal movies and multifile movies on linux.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/video/tags/VideoTagLoaderFFmpeg.cpp [hunk 1]
```diff
@@ -15,6 +15,7 @@
 #include "filesystem/File.h"
 #include "utils/StringUtils.h"
 #include "video/VideoInfoTag.h"
+#include "xbmc/filesystem/StackDirectory.h"
```
Comment (Rechi) [inline xbmc/video/tags/VideoTagLoaderFFmpeg.cpp]: no need for `xbmc/`

Comment (a1rwulf) [reply xbmc/video/tags/VideoTagLoaderFFmpeg.cpp]: fixed

**Comment by a1rwulf** [comment]
jenkins build this please

**Review by notspiff — APPROVED** [review]

**Comment by a1rwulf** [comment]
uwp64 fail due to python3.

**Comment by ksooo** [comment]
backport needed?

**Comment by a1rwulf** [comment]
Can't hurt I guess.

File: xbmc/video/tags/VideoTagLoaderFFmpeg.cpp [hunk 2]
```diff
@@ -39,8 +40,12 @@ CVideoTagLoaderFFmpeg::CVideoTagLoaderFFmpeg(const CFileItem& item,
   : IVideoInfoTagLoader(item, info, lookInFolder)
   , m_info(info)
 {
+  std::string filename =
+      item.IsStack() ? CStackDirectory::GetFirstStackedFile(item.GetPath()) : item.GetPath();
```
Comment (garbear) [inline xbmc/video/tags/VideoTagLoaderFFmpeg.cpp]: A little late, but slightly more readable might be

```c++
std::string filename = item.GetPath();
if (item.IsStack())
  filename = CStackDirectory::GetFirstStackedFile(filename);
```

Comment (a1rwulf) [reply xbmc/video/tags/VideoTagLoaderFFmpeg.cpp]: I had an if in my first draft, but I preferred the direct assignment as it's pretty obvious imho.
