### PR TITLE
AEStreamInfo: Support EAC3 independent + EAC3 (dependent) streams

### LINKED ISSUE #19182: Garbled sound with DD+/EAC3 passthrough and official Dolby DD+ 7.1 sample
### Describe the bug
When playing the Dolby Digital Plus 7.1 sample file [MP4_HPL40_30fps_channel_id_71.mp4](http://media.developer.dolby.com/DDP/MP4_HPL40_30fps_channel_id_71.mp4) from the [Dolby website](https://developer.dolby.com/tools-media/sample-media/video-streams/hd-video-streams/) audio output is garbled - it sounds like sound on/off in quick succession or stuttering - and kodi logs tons of "large audio sync error"s.

## Expected Behavior
Kodi is able to pass through official Dolby samples.

### Debuglog
The debuglog can be found here: http://ix.io/2OvU

## Additional context or screenshots (if appropriate)
The 5.1 DD+ sample [MP4_HPL40_30fps_channel_id_51.mp4](http://media.developer.dolby.com/DDP/MP4_HPL40_30fps_channel_id_51.mp4) from the webpage plays fine with passthrough enabled.

When disabling DD+/EAC3 passthrough the 7.1 sample plays fine with software decode (tested with downmix to 2.0)

### Your Environment
Used Operating system:
 - [X] Linux
 - Operating system version/name: LibreELEC master, RPi4
 - Kodi version: master, githash 1e6f7347ec56233923d176825f0ccdc6a60d76d3

### PR DESCRIPTION
**Pull request by popcornmix**
## Description
Fix for EAC3 passthrough with files that contain EAC3 independent + EAC3 (dependent) streams

## Motivation and context
Fixes: https://github.com/xbmc/xbmc/issues/19182

## How has this been tested?
Tested with the file is linked bug report. It now plays fine. 

## What is the effect on users?
More EAC3 files will play correctly

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by popcornmix** [comment]
Thanks to @jc-kynesim for the patch.

Report from original bug reporter (@HiassofT)

> thanks a lot, your EAC3 patch worked fine here! :+1:
The Dolby sample worked here, too, and the 3 Hobbit files with EAC3 audio tracks I fount in my archive worked fine, too (all of them "stuttered" before)

File: xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp [hunk 1]
```diff
@@ -446,6 +446,25 @@ bool CAEStreamParser::TrySyncAC3(uint8_t *data, unsigned int size, bool resyncin
     m_fsize = framesize << 1;
     m_info.m_repeat = MAX_EAC3_BLOCKS / blocks;
 
+    /* EAC3 can have a dependent stream too */
+    if (!wantEAC3dependent)
+    {
+      unsigned int fsizeMain = m_fsize;
```
Comment (lrusak) [inline xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp:452]: f as in frame? Maybe `frameSizeMain`?

**Review by lrusak — COMMENTED** [review]
Please update comments to use the correct style. https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#91-general

Also please apply the clang-format output.

File: xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp (hunk 1 above)
Comment (fritsch) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp:452]: Rest of file uses f instead of frame, too.

Comment (popcornmix) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp:452]: This code is pretty much a copy of the code above just in the EAC3 path, rather than AC3 path.

**Review by fritsch — APPROVED** [review]
For me the change is fine. I don't want to overrule any variable naming suggestions. Though I think changing it to "frame" will only confuse everyone else, cause of the "f" in other positions.

**Review by thexai — APPROVED** [review]

File: xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp (hunk 1 above)
Comment (lrusak) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp:452]: So is that reason enough not to update new code to the current guidelines? Just because it's copy paste?

Comment (HiassofT) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp:452]: just my 2c: I'd say before you enforce new coding styles just bulk-apply that style to your existing code so it meets that criteria, then copy&paste isn't a problem.

If you don't do it a single file will contain a mixture of all coding styles you had over time and will be really unpleasant to read.

Comment (lrusak) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp:452]: > just my 2c: I'd say before you enforce new coding styles just bulk-apply that style to your existing code so it meets that criteria, then copy&paste isn't a problem.
> 
> 
> 
> If you don't do it a single file will contain a mixture of all coding styles you had over time and will be really unpleasant to read.

We decided a few years ago that this wasn't the route that we wanted to take. I don't remember all the details at the moment.

**Comment by da-anda** [comment]
have been testing this change the other day and it fixed the issue for me. A big thanks to everybody involved.

File: xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp (hunk 1 above)
Comment (fritsch) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp:452]: > So is that reason enough not to update new code to the current guidelines? Just because it's copy paste?

No. It makes zero sense though to make the semantic, with half the file using f less intuitive by enforcing regulatoric enhancements. This drives the whole idea behind that guidelines nuts and decreases the semantic understanding. Let the change in and make a refactor afterwards for entire file to rename f to frame. This allows backports and really helps towards the well meant guidelines.

Comment (lrusak) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp:452]: > > So is that reason enough not to update new code to the current guidelines? Just because it's copy paste?
> 
> 
> 
> No. It makes zero sense though to make the semantic, with half the file using f less intuitive by enforcing regulatoric enhancements. This drives the whole idea behind that guidelines nuts and decreases the semantic understanding. Let the change in and make a refactor afterwards for entire file to rename f to frame. This allows backports and really helps towards the well meant guidelines.

Sure, leave the variable name. The rest should be updated to follow the guidelines and clang-format though.

Promise of refactoring later never works.

Comment (fritsch) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp:452]: Yes - I agree. Thanks much.

File: xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp [hunk 2]
```diff
@@ -446,6 +446,25 @@ bool CAEStreamParser::TrySyncAC3(uint8_t *data, unsigned int size, bool resyncin
     m_fsize = framesize << 1;
     m_info.m_repeat = MAX_EAC3_BLOCKS / blocks;
 
+    /* EAC3 can have a dependent stream too */
```
Comment (jc-kynesim) [inline xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp]: Whilst I really, really hate to pick nits here - you've just carefully converted every other comment in this file to //

Comment (popcornmix) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp]: I'm not following. This commit follows the formatting of the original code (as it's basically a copy and paste).
The next two commits apply the code formatting guidelines to the whole file.

Comment (jc-kynesim) [reply xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp]: Oh - mea culpa - I misread the commit order

**Comment by thexai** [comment]
I think there have been several misunderstandings here: what lrusak wanted is clang-format of new code lines only:

e.g:

```c++
    // EAC3 can have a dependent stream too
    if (!wantEAC3dependent)
    {
      unsigned int fsizeMain = m_fsize;
      unsigned int reqBytes = fsizeMain + 8;
      if (size < reqBytes)
      {
        // not enough data to check for E-AC3 dependent frame, request more
        m_needBytes = reqBytes;
        m_fsize = 0;
        // no need to resync => return true
        return true;
      }
      if (TrySyncAC3(data + fsizeMain, size - fsizeMain, resyncing, /*wantEAC3dependent*/ true))
      {
        // concatenate the main and dependent frames
        m_fsize += fsizeMain;
        return true;
      }
    }
```

Note that Jenkins checks formatting of each commit separately so a commit with wrong format + patch to fix format on a separated commit does not fix all Jenkins complains. Also for backport is need cherry pick same commit (if possible) so is much more easy one commit only.

@popcornmix, please update the PR with a single commit of the new code (without touching the rest of the existing code).

**Comment by popcornmix** [comment]
I think that would be a worse solution.
The code added is basically very similar to the code in the other branch of the if.
Keeping it similar makes it easier to spot this.
Having a mixture of two coding styles in one function is going to be worse.
The final result of this PR fixes the bug and fixes the coding style of the whole file.

**Comment by jc-kynesim** [comment]
@thexai Would it but OK by you if the patch sequence went - update entire file to new coding style and then apply patch in the new coding style (rather then the other way round which is how it is at the moment)? I have to agree with @popcornmix that mixing styles within a function is truly horrid.

**Comment by lrusak** [comment]
> @thexai Would it but OK by you if the patch sequence went - update entire file to new coding style and then apply patch in the new coding style (rather then the other way round which is how it is at the moment)? I have to agree with @popcornmix that mixing styles within a function is truly horrid.

Yes it's generally considered ok to run clang-format on an entire section (or file) and commit that prior to making the actual changes/commits. This is typically done to help clarify the code changes that are contained in a commit to avoid bloating it with formatting changes.

This does typically make it harder to backport but it's not impossible either.

In this case the code change is easy to read so I don't really think that formatting the entire file is needed. I'm not opposed to it though if it is causing others grief to mix styles in a single file.

**Comment by thexai** [comment]
> Would it but OK by you if the patch sequence went - update entire file to new coding style and then apply patch in the new coding style (rather then the other way round which is how it is at the moment)?

Yes, that would be correct. Then the new code added would already be with the new style and the Jenkins message will disappear.

Although it is not necessary to change the entire file, just the new code added.

**Comment by sundermann** [comment]
I've noticed on webOS these streams are unfortunately still broken. It seems that some `m_info` variables would also need to be updated with the information of the dependent stream. Right now `m_channels` and `m_ac3FrameSize` is only parsed from the main stream thus giving only 4 channels on a 7.1 stream.

**Comment by jc-kynesim** [comment]
Ah! very believable - I did worry about that - but as I don't know that code well and what I did seemed to work on the test cases and platform I had so I left it as was. If you've got a test case & platform that shows the problem then patch away.  Or is you can make it fail on arm/linux then I'll happily build a new patch.

**Comment by sundermann** [comment]
I guess it's not relevant on all other platforms except for webOS as they don't need correct information on the channel count for passthrough.

**Comment by jc-kynesim** [comment]
If you want I can make a best guess at a patch but without a test case it will just be a guess.

**Comment by sundermann** [comment]
This seems to be working at a first glance but I haven't done any extensive testing yet. The error should also be visible on any platform from the logs reporting only the channels of the dependent stream:

```
2023-05-14 11:13:10.891 T:5113     info <general>: CAEStreamParser::TrySyncAC3 - E-AC3 stream detected (4 channels, 48000Hz)
```

```diff
diff --git a/xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp b/xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp
index c98a306827..4b7c17208c 100644
--- a/xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp
+++ b/xbmc/cores/AudioEngine/Utils/AEStreamInfo.cpp
@@ -369,6 +369,9 @@ bool CAEStreamParser::TrySyncAC3(uint8_t* data,
       // no need to resync => return true
       return true;
     }
+
+    m_info.m_ac3FrameSize = fsizeMain;
+    m_info.m_channels = AC3Channels[acmod] + lfeon;
     if (TrySyncAC3(data + fsizeMain, size - fsizeMain, resyncing, true))
     {
       // concatenate the main and dependent frames
@@ -389,10 +392,10 @@ bool CAEStreamParser::TrySyncAC3(uint8_t* data,
 
     // if we get here, we can sync
     m_hasSync = true;
-    m_info.m_channels = AC3Channels[acmod] + lfeon;
+    m_info.m_channels += AC3Channels[acmod] + lfeon;
     m_syncFunc = &CAEStreamParser::SyncAC3;
     m_info.m_type = CAEStreamInfo::STREAM_TYPE_AC3;
-    m_info.m_ac3FrameSize = m_fsize;
+    m_info.m_ac3FrameSize += m_fsize;
     m_info.m_repeat = 1;
 
     CLog::Log(LOGINFO, "CAEStreamParser::TrySyncAC3 - AC3 stream detected ({} channels, {}Hz)",
@@ -451,6 +454,9 @@ bool CAEStreamParser::TrySyncAC3(uint8_t* data,
         // no need to resync => return true
         return true;
       }
+
+      m_info.m_ac3FrameSize = fsizeMain;
+      m_info.m_channels = AC3Channels[acmod] + lfeon;
       if (TrySyncAC3(data + fsizeMain, size - fsizeMain, resyncing, true))
       {
         // concatenate the main and dependent frames
@@ -464,10 +470,10 @@ bool CAEStreamParser::TrySyncAC3(uint8_t* data,
 
     // if we get here, we can sync
     m_hasSync = true;
-    m_info.m_channels = AC3Channels[acmod] + lfeon;
+    m_info.m_channels += AC3Channels[acmod] + lfeon;
     m_syncFunc = &CAEStreamParser::SyncAC3;
     m_info.m_type = CAEStreamInfo::STREAM_TYPE_EAC3;
-    m_info.m_ac3FrameSize = m_fsize;
+    m_info.m_ac3FrameSize += m_fsize;
 
     CLog::Log(LOGINFO, "CAEStreamParser::TrySyncAC3 - E-AC3 stream detected ({} channels, {}Hz)",
               m_info.m_channels, m_info.m_sampleRate);
```
