### PR TITLE
[GUI] Don't touch plugin:// urls

### LINKED ISSUE #16516: ActivateWindow() behaves inconsistently wrt. trailing slashes
### Describe the bug
Here is a clear and concise description of what the problem is:
We discovered that when using `ActivateWindow()` using a URL without a trailing slash causes the wrong URL to be taken into account in some cases.

It appears that if the last path fragment is an number (e.g. 2016) it is chopped off the URL, unless it is followed by a trailing slash.

|URL used                         |Ends up in                |
|----------------------------|------------------------|
|plugin://plugin.video.vrt.nu/programs/pano/2016|**/programs/pano/**|
|plugin://plugin.video.vrt.nu/programs/pano/2016/|/programs/pano/2016/|
|plugin://plugin.video.vrt.nu/programs/pano/allseasons|/programs/pano/allseasons|
|plugin://plugin.video.vrt.nu/programs/pano/allseasons/|/programs/pano/allseasons/|

More information when we discovered this: https://github.com/pietje666/plugin.video.vrt.nu/pull/425#discussion_r315485160

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

`ActivateWindow()` should go to the exact URL that is requested.

## Actual Behavior
`ActivateWindow()` chops off numbers at the end of a URL.

### To Reproduce
1. Run `ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016`
2. Check the path that is requested
3. See it is chopped off

### Debuglog

The debuglog can be found here:
Here is an overview of commands I ran:
```shell
kodi01:~ # kodi-send -a 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016)'
Sending: {'content': 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016)', 'type': 'action'}
kodi01:~ # kodi-send -a 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016/)'
Sending: {'content': 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/2016/)', 'type': 'action'}
kodi01:~ # kodi-send -a 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/allseasons)'
Sending: {'content': 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/allseasons)', 'type': 'action'}
kodi01:~ # kodi-send -a 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/allseasons/)'
Sending: {'content': 'ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/pano/allseasons/)', 'type': 'action'}
```
And this is the resulting log:
```
2019-08-20 05:07:26.444 T:1222632304  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/pano/
2019-08-20 05:07:26.458 T:1222632304  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/pano/&si
ze=300
2019-08-20 05:07:30.636 T:1222632304  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/pano/2016/
2019-08-20 05:07:30.653 T:1222632304  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[seasonTitle]=2016&facets[programUrl]=//www.
vrt.be/vrtnu/a-z/pano/&size=300
2019-08-20 05:07:50.770 T:1222632304  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/pano/allseasons
2019-08-20 05:07:50.785 T:1222632304  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/pano/&si
ze=300
2019-08-20 05:07:55.188 T:1222632304  NOTICE: [plugin.video.vrt.nu] Access: plugin://plugin.video.vrt.nu/programs/pano/allseasons/
2019-08-20 05:07:55.202 T:1222632304  NOTICE: [plugin.video.vrt.nu] URL get: https://vrtnu-api.vrt.be/search?i=video&facets[programUrl]=//www.vrt.be/vrtnu/a-z/pano/&si
ze=300
```

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 9.0.2
 - Kodi version: v18.2

### PR DESCRIPTION
**Pull request by mediaminister**
## Description

Kodi should pass untouched `plugin://` urls when getting the start folder of a GUIMediaWindow with `GetStartFolder`.
Changes to the dir parameter of `ActivateWindow()` should be done in `GetStartFolder`. (in this case a hack for the Android leanback  screen)

## Motivation and Context

Plugins can independently create their own `plugin://` urls and Kodi shouldn't change these urls when a plugin calls a builtin function like `ActivateWindow()`. This solves an issue where Kodi removes numbers from `plugin://` urls.
For instance, when a plugin needs to list Season 25 of a TV show "Thuis" using  `ActivateWindow()`, the plugin calls `plugin://plugin.video.vrt.nu/programs/thuis/25` but Kodi removes the number `25` and wrongly navigates to `plugin://plugin.video.vrt.nu/programs/thuis/`

This fixes https://github.com/xbmc/xbmc/issues/16516

## How Has This Been Tested?

I tested this with **autoexec.py**:
```
import xbmc
xbmc.executebuiltin('ActivateWindow(videos, plugin://plugin.video.vrt.nu/programs/thuis/25)')
```

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
Seems reasonable and doesn't introduce any changes compared to the previous behaviour that are likely to cause regressions (apart from a plugin exception which this tries to solve). 

Personally I'd say it is not the GUIWindow responsibility to change any paths provided to the window just to bypass some platform specific hack/functionality. I am not familiar with it but I guess the leanback workaround probably belongs somewhere else (a new vfs entry maybe?).

**Review by enen92 — APPROVED** [review]

**Comment by phunkyfish** [comment]
@enen92 ok to merge this?

**Comment by enen92** [comment]
I approved it but would be better to have someone else to look at it

File: xbmc/windows/GUIMediaWindow.cpp [hunk 1]
```diff
@@ -2165,6 +2160,17 @@ std::string CGUIMediaWindow::GetStartFolder(const std::string &dir)
       StringUtils::EqualsNoCase(dir, "root"))
     return "";
 
+  // Let plugins handle their own urls themselves
+  if (StringUtils::StartsWith(dir, "plugin://"))
+    return dir;
+
+  // Hack for Android items (numbered id's) on the leanback screen
+  std::string path, fileName;
```
Comment (phunkyfish) [inline xbmc/windows/GUIMediaWindow.cpp:2168]: One variable declaration per line please.

File: xbmc/windows/GUIMediaWindow.cpp [hunk 2]
```diff
@@ -2165,6 +2160,17 @@ std::string CGUIMediaWindow::GetStartFolder(const std::string &dir)
       StringUtils::EqualsNoCase(dir, "root"))
     return "";
 
+  // Let plugins handle their own urls themselves
+  if (StringUtils::StartsWith(dir, "plugin://"))
+    return dir;
+
+  // Hack for Android items (numbered id's) on the leanback screen
```
Comment (phunkyfish) [inline xbmc/windows/GUIMediaWindow.cpp:2167]: I don't know if it's correct to have Android specific code here but if it is required it should be at least `#if defined(TARGET_ANDROID)` to make it clear it is only for one platform.

**Review by phunkyfish — CHANGES_REQUESTED** [review]

File: xbmc/windows/GUIMediaWindow.cpp (hunk 1 above)
Comment (mediaminister) [reply xbmc/windows/GUIMediaWindow.cpp]: Done.

File: xbmc/windows/GUIMediaWindow.cpp (hunk 2 above)
Comment (mediaminister) [reply xbmc/windows/GUIMediaWindow.cpp:2178]: Originally this was a totally undocumented hack by @koying https://github.com/xbmc/xbmc/commit/01dbdf956f47e1df3c96261d154848b673fe996a#diff-05be91542194f697ea542d6c9db7d391R477

After investigating it turned out this was intended for the Android leanback screen. I'm not familiar with this functionality for Android. So, I kept the changes as small as possible to avoid breaking stuff.

**Comment by mediaminister** [comment]
> Personally I'd say it is not the GUIWindow responsibility to change any paths provided to the window just to bypass some platform specific hack/functionality. I am not familiar with it but I guess the leanback workaround probably belongs somewhere else (a new vfs entry maybe?).

I'm not familiar with this functionality on Android so I kept the changes to a minimum to avoid breaking things.

**Comment by phunkyfish** [comment]
I’m not sure who the right person to ask about this is 😐

@spiff @alwinus any ideas?

**Comment by enen92** [comment]
Maybe @peak3d can also take a look as this is android specific and he has looked into the leanback/channels in the past

**Comment by peak3d** [comment]
I agree to @enen92 that GUIWindow should not modify the path.
-> I'm fine with this change, and I'll keep it in memory if I see regression.

**Comment by enen92** [comment]
one last request @mediaminister. Can you add a doxygen `@todo` near the ifdef block so that we know that that block of code should be moved somewhere else in the future?

**Review by phunkyfish — APPROVED** [review]
LGTM
