### PR TITLE
[Video] Adjust getting movie names from archives.

### LINKED ISSUE #27850: zip/rar Files Library Import Issues
### Describe the bug
Here is a clear and concise description of what the problem is:

Issues with the addition to the library of video files contained in a zip/rar archive since PR #27580.

Some files inside the archives are not recognized, and those that are have the wrong movie name.

My test zip file 1 has multiple properly named movies at the top level of the zip. Like so:
movies-top-level.zip
  Big Buck Bunny.mp4
  Elephant Dreams.avi
  Sintel.mkv
  Tears of Steel.mov
result: none visible in the library (db and GUI)

My test zip file 2 has the same video files but with their original file name and placed inside top level folders named after the movie:
movies-in-dir.zip
  Big Buck Bunny
      bbb_sunflower_1080p_60fps_normal.mp4
      bbb_sunflower_1080p_60fps_normal extended.mp4
      bbb_sunflower_1080p_60fps_normal super duper.mp4
  Elephant Dreams
    ed.avi
  Sintel
    Sintel.2010.1080p.mkv
  Tears of Steel
    tears_of_steel_1080p.mov
etc...
result: imported but all with another incorrect movie name.

The scraper options were "content: movies, scraper: tmdb python, movies in separate folders: no, scan recursively: yes"

The code before #27580 imports both .zip as best as is possible (all movies from movies-top-level.zip, Sintel and Tears of Steel from movies-in-dir.zip since they're only ones with the movie name present in the file name).

### Debuglog

The debuglog can be found here: https://paste.kodi.tv/isiqaleroh.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: 22-master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

@CrystalP pointed out some cases where movies in archives weren't scanned correctly.

There were two cases:
1) An archive file containing files in root of the archive:
```
movies-top-level.zip
  Big Buck Bunny.mp4
  Elephant Dreams.avi
  Sintel.mkv
  Tears of Steel.mov
```

This is fixed.

2) An archive file containing movie folders - this didn't work previously but I can't see a reason why it shouldn't do:
```
movies-in-dir.zip
  Big Buck Bunny
      bbb_sunflower_1080p_60fps_normal.mp4
      bbb_sunflower_1080p_60fps_normal extended.mp4
      bbb_sunflower_1080p_60fps_normal super duper.mp4
  Elephant Dreams
    ed.avi
  Sintel
    Sintel.2010.1080p.mkv
  Tears of Steel
    tears_of_steel_1080p.mov
```

This now works as well (with movies in folders selected for source).

## Motivation and context

Fix #27850.

## How has this been tested?

Locally.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by 78andyp** [comment]
@kodiai - I've made the two amendments you suggested

**Comment by CrystalP** [comment]
Seems this has to be tested at the same time as #27849 since for a given video, the migrated old path+filename should be identical to the new scanned path and filename (which wasn't available for comparison before this PR)

File: xbmc/test/TestFileItem.cpp [hunk 1]
```diff
@@ -386,19 +400,32 @@ const TestNameData BaseNames[] = {
...
+    {"zip://%2fsomepath%2fmovies%2ffilm.zip/movie/film.avi", true, "movie"},
+    {"zip://%2fsomepath%2fmovies%2fmovies.zip/movie/BDMV/index.bdmv", true, "movie"},
     {"zip://%2fsomepath%2fmovie%2fmovie%2fdisc%201%2ffilm.zip/BDMV/index.bdmv", true, "movie"},
-    {"rar://%2fsomepath%2fmovie.rar/film.avi", false, "movie"},
-    {"rar://%2fsomepath%2fmovie%2ffilm.rar/BDMV/index.bdmv", true, "movie"},
+    //
+    {"rar://%2fsomepath%2fmovies.rar/movie.avi", false, "movie"},
+    {"rar://%2fsomepath%2fmovies%2fmovie.rar/BDMV/index.bdmv", false, "movie"},
+    {"rar://%2fsomepath%2fmovie%2ffilm.rar/film.avi", true, "movie"},
+    {"rar://%2fsomepath%2fmovies%2ffilm.rar/movie/film.avi", true, "movie"},
```
Comment (CrystalP) [inline xbmc/test/TestFileItem.cpp:679]: where is the matching use_folder=false case? it's relevant to the PR.
there seem to be a few others missing, as well as some use_folder=true
Defining them all (and the combinations...) is a pain, I wonder if some part can be generated dynamically.

File: xbmc/test/TestUtil.cpp [hunk 2]
```diff
@@ -547,18 +547,18 @@ const TestBaseData Paths[] = {
...
      "smb://somepath/movie/disc 1/", "movie"},
-    {"zip://smb%3a%2f%2fsomepath%2fmovie%2fmovie.zip/BDMV/PLAYLIST/00800.mpls",
-     "smb://somepath/movie/", "movie"},
+    {"zip://smb%3a%2f%2fsomepath%2fmovie%2fmovie.zip/BDMV/index.BDMV", "smb://somepath/movie/",
+     "movie"},
     {"zip://smb%3a%2f%2fsomepath%2fmovie%2fdisc%201%2fmovie.zip/file.mkv",
-     "smb://somepath/movie/disc 1/", "movie"},
-    {"rar://smb%3a%2f%2fsomepath%2fmovie%2fmovie.rar/BDMV/PLAYLIST/00800.mpls",
-     "smb://somepath/movie/", "movie"},
+     "smb://somepath/movie/disc 1/", "file"},
```
Comment (CrystalP) [inline xbmc/test/TestUtil.cpp:553]: that gets complicated. I don't know that it makes any sense to acknowledge potentially multiple files in the zip here, it's already supposed to be disc 1, which decides path and movie already, no?.
what would/should happen in the same situation without the .zip?
ex filesystem with smb:://somepath/movie/disc 1/file,mkv

File: xbmc/test/TestFileItem.cpp (hunk 1 above)
Comment (78andyp) [reply xbmc/test/TestFileItem.cpp:679]: Done.

File: xbmc/test/TestUtil.cpp (hunk 2 above)
Comment (78andyp) [reply xbmc/test/TestUtil.cpp:553]: Agree - but it's logical - if someone chooses to not tick the movies in folders option for the scraper and then puts movies in folders - the result is always going to be odd (even if it follows logic).

File: xbmc/test/TestUtil.cpp [hunk 3]
```diff
@@ -789,11 +786,11 @@ constexpr TestMatchingSourceData SourcesToMatch[] = {
...
     {"\\\\Server\\TV Shows\\A Perfect Planet (2021)\\", 10},
     {"\\\\Server\\Other\\Something Else\\", -1},
-    {"zip://%5c%5cServer%5cMovies%5cmovie.zip/BDMV/PLAYLIST/00800.mpls", 9},
+    {"zip://%5c%5cServer%5cMovies%5cmovie.zip/BDMV/index.BDMV", 9},
     {"zip://%5c%5cServer%5cTV%20Shows%5cdisc%201%5cshow.rar/file.mkv", 10},
-    {"rar://%5c%5cServer%5cMovies%5cmovie.rar/BDMV/PLAYLIST/00800.mpls", 9},
+    {"rar://%5c%5cServer%5cMovies%5cmovie.rar/BDMV/index.BDMV", 9},
     {"rar://%5c%5cServer%5cTV%20Shows%5cdisc%201%5cshow.rar/file.mkv", 10},
-    {"archive://%5c%5cServer%5cMovies%5cmovie.tar.gz/BDMV/PLAYLIST/00800.mpls", 9},
+    {"archive://%5c%5cServer%5cMovies%5cmovie.tar.gz/BDMV/index.BDMV", 9},
```
Comment (CrystalP) [inline xbmc/test/TestUtil.cpp:793]: For this and the similar changes: what's the reason for the change from PLAYLIST/00800.mpls to index.BDMV?

File: xbmc/test/TestUtil.cpp (hunk 2 above)
Comment (CrystalP) [reply xbmc/test/TestUtil.cpp:553]: After more reading my comment was probably off, it doesn't look like stacking is supposed to happen at that level, or is it? Wherever it's located would be the place to that needs to be able to deal with this situation. Does that make sense?

**Comment by CrystalP** [comment]
what changed in that force push? The test cases are already hard to read because the same commit changes existing cases but also adds a bunch more for bluray.

File: xbmc/test/TestUtil.cpp (hunk 3 above)
Comment (78andyp) [reply xbmc/test/TestUtil.cpp:793]: Because PLAYLIST/008000.mps can actually never happen - they would automatically be bluray://. But BDMV/index.bdmv can happen at scan time.

**Comment by 78andyp** [comment]
> what changed in that force push? The test cases are already hard to read because the same commit changes existing cases but also adds a bunch more for bluray.

Nothing in the end - it was my bad - I thought your language PR had bumped the database up to 142 and I needed to change this to 143 - but I was wrong - so in the end the only change was a rebase against origin/master.

**Comment by 78andyp** [comment]
> After more reading my comment was probably off, it doesn't look like stacking is supposed to happen at that level, or is it? > Wherever it's located would be the place to that needs to be able to deal with this situation. Does that make sense?

Not sure what you mean - do you mean stacking as in stack:// ??

File: xbmc/test/TestUtil.cpp (hunk 2 above)
Comment (CrystalP) [reply xbmc/test/TestUtil.cpp:553]: By stacking I mean automatically combining disc 1/2 etc. Is it called something else?

**Comment by CrystalP** [comment]
> Nothing in the end - it was my bad - I thought your language PR had bumped the database up to 142 and I needed to change this to 143 - but I was wrong - so in the end the only change was a rebase against origin/master.

This PR doesn't interact with the database or did I miss something?

File: xbmc/test/TestUtil.cpp (hunk 2 above)
Comment (78andyp) [reply xbmc/test/TestUtil.cpp:553]: No - that's stacking. That happens in CFileItems::Stack - but directories which are named just `Disc 1` etc.. aren't stacked. It is much more common for Blurays to have disc 1 - UHD, disc 2 - Bluray, Disc 3 - extras than it is the film spread over multiple discs. The LOTR/Hobbit are the exception - but then the directory name would need to be `movie (year) disc 1` - off the top of my head.

**Comment by 78andyp** [comment]
Sorry wrong PR - I think the force push was fixing the cases you identified with folders within the archives themselves.

File: xbmc/test/TestFileItem.cpp [hunk 4]
```diff
@@ -364,14 +412,47 @@ const TestNameData BaseNames[] = {
     {"bluray://smb%3a%2f%2fsomepath%2fmovie%2f/BDMV/PLAYLIST/00800.mpls", false, "movie"},
     {"bluray://smb%3a%2f%2fsomepath%2fmovie%2f/BDMV/PLAYLIST/00800.mpls", true, "movie"},
     {"bluray://smb%3a%2f%2fsomepath%2fmovie%2fDisc%201%2f/BDMV/PLAYLIST/00800.mpls", true, "movie"},
-    {"zip://smb%3a%2f%2fsomepath%2fmovie.zip/film.avi", false, "movie"},
+    //
+    {"zip://smb%3a%2f%2fsomepath%2fmovies.zip/movie.avi", false, "movie"},
+    {"zip://smb%3a%2f%2fsomepath%2fmovies.zip/movie.avi", true, ""},
+    {"zip://smb%3a%2f%2fsomepath%2fmovies%2fmovie.zip/BDMV/index.bdmv", false, "movie"},
+    {"zip://smb%3a%2f%2fsomepath%2fmovies%2fmovie.zip/BDMV/index.bdmv", true, "movies"},
+    {"zip://smb%3a%2f%2fsomepath%2fmovie%2ffilm.zip/film.avi", false, "film"},
```
Comment (CrystalP) [inline xbmc/test/TestFileItem.cpp]: naming both the .zip and the contained video film makes the test confusing - does film come from the zip name or the file inside the zip?
same comment for the identical case in rar and archive and later with linux/etc paths

**Comment by CrystalP** [comment]
Speaking of folders within the archives, I see a test case for GetMovieName (lines 422/423) but not for GetVideoBasePathAndFileName (TestUtil.cpp)

**Comment by CrystalP** [comment]
Can you for now add another commit which will make spotting the differences and the review easier, to be squashed later.

**Comment by CrystalP** [comment]
Runtime testing is ok (back to pre-27850 behavior). I'll approve after the test adjustments.

**Comment by 78andyp** [comment]
> Runtime testing is ok (back to pre-27850 behavior). I'll approve after the test adjustments.

Additional tests added and tests moved to separate commit.

Are you happy with #27849 as well - I'd like that in for alpha 3 if possible alongside this one.

**Comment by CrystalP** [comment]
argh I didn't want a force push, to be able to easily see the changes... will have to go test by test. again.

File: xbmc/test/TestFileItem.cpp [hunk 5]
```diff
@@ -162,77 +162,244 @@ const TestFileData BaseMovies[] = {
...
+     "smb://somepath/movies/"},
+    {"rar://smb%3a%2f%2fsomepath%2fmovie%2fmovie.rar/film.avi", false,
+     "rar://smb%3a%2f%2fsomepath%2fmovie%2fmovie.rar/film.avi"},
+    {"rar://smb%3a%2f%2fsomepath%2fmovie%2ffilm.rar/film.avi", true, "smb://somepath/movie/"},
+    {"rar://smb%3a%2f%2fsomepath%2fmovies%2fmovie.rar/movie/film.avi", false,
+     "rar://smb%3a%2f%2fsomepath%2fmovies%2fmovie.rar/movie/film.avi"},
+    {"rar://smb%3a%2f%2fsomepath%2fmovies%2ffilm.rar/movie/film.avi", true,
+     "rar://smb%3a%2f%2fsomepath%2fmovies%2ffilm.rar/movie/"},
+    {"rar://smb%3a%2f%2fsomepath%2fmovies%2fmovies.rar/movie/BDMV/index.bdmv", false,
+     "smb://somepath/movies/movies.rar"},
```
Comment (CrystalP) [inline xbmc/test/TestFileItem.cpp]: that doesn't seem right? result rar://smb%3a%2f%2fsomepath%2fmovies%2fmovies.rar/movie/ instead?

Comment (78andyp) [reply xbmc/test/TestFileItem.cpp]: It depends. We are effectively in undocumented territory here - as supporting folders within archives can be considered a new feature.

Logically - the useFolder flag is false - so the first filename that can be used is that of the archive itself.
But I also agree that probably what the user wants is the 'movie' instead of 'movies' - although it comes from a folder.

I am more than happy to change it - as far as I can see there is nothing in the wiki about naming of contents within archives for scraping, although that could also be a discussion for another PR. The important thing with this one is we have fixed the regressions (which I think we have).

There will also need to be some testing to see if external subs/audio, nfos/art etc.. are now properly found/written for import/export of folders within archives - but again, that can be another PR (post alpha 3) if adjustments are needed as it's part of implimenting a new feature that we haven't formally announced yet - @garbear would you agree??

I'll add an additional commit making the change above for now. I'll also hold off jenkins until we are happy.

Comment (78andyp) [reply xbmc/test/TestFileItem.cpp]: New commit is the above.

Comment (CrystalP) [reply xbmc/test/TestFileItem.cpp]: Thanks. It looked like an odd exception. But in the code appears to add another exception instead of removing one!
The implementation can be finetuned later, there may be a better design.

External files are challenging but as long as the simple case of artwork and nfo for a single file in archive works, it's good enough for alpha3 (I haven't tested - did you?) and addresses spiff's concerns.
The main use case (maybe the only one in practice!) is probably usenet rar archives. I haven't seen one in a very long time and forgot what they look like and their contents.

I had a little problem during testing because of a zip created by Windows Explorer with the proprietary deflate64 method not supported by Kodi or much open source. After recreating the zip, playing the videos worked fine.

Actually a lot more combinations scan successfully now with usefolder=true than before 27850, I wonder if that's from the zip/rar changes or something else.

**Comment by CrystalP** [comment]
After more testing, I didn't find differences in the library scanning outside of archives (went back to 21.3, alpha1, alpha2 for comparison)
Inside archives can be resolved later.

**Review by CrystalP — APPROVED** [review]
Runtime tested OK, the PR restores scanning of archives and doesn't impact files outside of archives.
Please squash and make sure clang-format and builds are green before merge.
