### PR TITLE
[Subtitles] Add support to font collection (.ttc)

### LINKED ISSUE #23300: A font that doesn't work in 20.1 but works in 19.5 (Android)
### Describe the bug
Here is a clear and concise description of what the problem is:  

In Android Kodi 19, I was able to use this ttf font and override the embedded sub's font. However, in Android Kodi 20.1 (Fresh install) it doesn't work at all and it uses the default font instead. I tried restarting many times but it still doens't work, and then I tried going back to Kodi 19.5 and the font started working again.  
**Kindly note that this issue is not present in Windows Kodi 20.1. The font works perfectly there**

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

  
The ttf font should work in Android Kodi 20.1 like it used to work in Android Kodi 19 and the Windows version of Kodi 20.1.  
The following screenshot is from Windows version which works fine:  
Screenshot (1143)

## Actual Behavior

  
Unlike Android Kodi 19 and Windows Kodi 20.1, the font doesn't work in Android Kodi 20.1.  
The following screenshot is from Android Kodi 20.1:  
image

### To Reproduce

1. (Android ) Put font file .ttf inside /.kodi/media/Fonts
2. Choose the font from subtitle settings
3. Enable override ASS/SSA subtitles fonts
4. Change the size settings and position settings
5. Play any mkv file with embedded ASS subs
6. You'll notice that the size settings and position settings have been applied, but not the fonts settings.

### Debuglog

The debuglog can be found here:  
https://paste.kodi.tv/qepedipazo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

  
This is the ttf font file in question:  
[Bahij Jalal-Regular Edit.zip](https://github.com/xbmc/xbmc/files/11510454/Bahij.Jalal-Regular.Edit.zip)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11 and Android 12 ( Galaxy S10e and Shield TV)
 - Kodi version:  
 - 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #23402: font not working properly
got a font that doesn't seem to work properly on kodi 20.1
it embedded in a mkv file
and kodi is installed on windows 10  (22h2...or whatever the newest one is)
[DFMrg9.zip](https://github.com/xbmc/xbmc/files/11742221/DFMrg9.zip)
works properly on MPC-HC 2.0.xx beta and other windows players

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

This PR add support to use font collection (.ttc) to subtitles
since .ttc contains more fonts, we need to inspect the file to get family name of each font

this format is already supported in to libass renderer but we have not allowed his use
that lead to the problem with mkv's where user opened issue

this code change
- fix the problem that mkv was not extracting .ttc files
- allow load .ttc from the "fonts" folder to allow show each font contained, in the subtitles fonts list setting menu

the results in the fontcache.xml will be as follow:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<fonts>
    <font>
        <filename>DFMrg9.ttc</filename>
        <familyname>DFGMaruGothic-SB</familyname>
        <familyname>DFMaruGothic-SB</familyname>
        <familyname>DFPMaruGothic-SB</familyname>
    </font>
    <font>
        <filename>Helvetica.ttc</filename>
        <familyname>.Helvetica Light</familyname>
        <familyname>Helvetica</familyname>
    </font>
    <font>
        <filename>wqy-microhei.ttc</filename>
        <familyname>WenQuanYi Micro Hei</familyname>
        <familyname>WenQuanYi Micro Hei Mono</familyname>
    </font>
</fonts>
```

NOTE 1: the DFMrg9.ttc file on zip below contains multiple font familynames for different architectures on each font,
but for some reason to me unknown with this particular fonts kodi is not able to convert the familyname enoceded "macintosh" to uft8, i tried use fontforge to check fonts, but i have not found problems and i have no idea where is the problem (could be also on freetype library). So for now i prioritized the family name set for MS/APPLE platforms then use MAC as fallback, in this way we can workaround it.

NOTE 2: i add fontfamily name selection from "english" field that should be always filled, this for two reasons, prevent possible problems of "tofu" chars appears in the GUI font list, kodi dont support multilanguage GUI, and avoid add a encoding mapping to decode each language with iconv, if there will be problems on particular use cases it will be addressed when reported

## Motivation and context

fix #23402
## How has this been tested?

tested mkv provided in the issue that embed an ass subtitle + fonts
tested .ttc fonts with srt subtitles by using fonts on zip [Fonts.zip](https://github.com/xbmc/xbmc/files/11833493/Fonts.zip)

## What is the effect on users?

Allow users to use .ttc files and display font correctly
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by scott967** [comment]
From what I can find in specs there isn't a difference in tables between .ttc and .otc font collections.  Any reason not to include .otc?

**Comment by CastagnaIT** [comment]
for me no problem add it, but are you able to find at least one .otc file to make test?

File: xbmc/guilib/GUIFontManager.cpp [hunk 1]
```diff
@@ -49,6 +49,8 @@ using namespace ADDON;
 namespace
 {
 constexpr const char* XML_FONTCACHE_FILENAME = "fontcache.xml";
+constexpr int XML_FONTCACHE_VER_0 = 0; // Initial version
```
Comment (enen92) [inline xbmc/guilib/GUIFontManager.cpp:52]: Mind clarifying why and when the font cache should be rebuilt? This is probably something that should be forced on startup on new releases (first run)? Maybe it should be the application in charge of triggering the rebuild and not this component.

Comment (CastagnaIT) [reply xbmc/guilib/GUIFontManager.cpp:52]: thanks for point this out i think this is a full oversight i got confused things last days
now rereading the code i realized that since we add new extension the operation is done automatically anyway
this is therefore superfluous i will remove it

**Review by enen92 — APPROVED** [review]
Codewise I can't figure out anything to nitpick now, the versioning was my only concern.

File: xbmc/guilib/GUIFontManager.cpp [hunk 2]
```diff
@@ -597,10 +597,16 @@ void GUIFontManager::LoadUserFonts()
...
-        std::string familyName;
         XMLUtils::GetString(fontNode, "filename", filename);
-        XMLUtils::GetString(fontNode, "familyname", familyName);
-        m_userFontsCache.emplace_back(filename, familyName);
+
+        std::set<std::string> familyNames;
+        for (const TiXmlElement* fnChildNode = fontNode->FirstChildElement("familyname");
+             fnChildNode; fnChildNode = fnChildNode->NextSiblingElement("familyname"))
+        {
+          familyNames.insert(fnChildNode->GetText());
```
Comment (neo1973) [inline xbmc/guilib/GUIFontManager.cpp:606]:
```suggestion
          familyNames.emplace(fnChildNode->GetText());
```

File: xbmc/utils/FontUtils.h [hunk 3]
```diff
@@ -40,14 +41,34 @@ std::string GetSystemFontPath(const std::string& filename);
...
 
 /*!
- *  \brief Get the font family name from a font file
+ *  \brief Get the font family name from a font file,
+ *         in case of font collection (.ttc) will take the family name of all fonts
+ *  \param buffer The font data
+ *  \param familyNames The font family names
+ *  \return True if success, otherwise false when an error occurs
+ */
+bool GetFontFamilyNames(std::vector<uint8_t>& buffer, std::set<std::string>& familyNames);
```
Comment (neo1973) [inline xbmc/utils/FontUtils.h:50]:
```suggestion
bool GetFontFamilyNames(const std::vector<uint8_t>& buffer, std::set<std::string>& familyNames);
```

**Review by neo1973 — CHANGES_REQUESTED** [review]
Looks good, just some minor suggestions.

**Review by neo1973 — APPROVED** [review]

**Comment by scott967** [comment]
I did some hunting for ".otc" collections, and it seems like using the ".ttc" extension appears to be the convention.  Per Adobe, the tables in the collection need to be checked to determine if the fonts are ttf or otf (ttf will have 'glyf' tables).  So I don't think it is worth the effort to worry about otc.  I did build a couple of otf font collections using Adobe Font Development Kit for OpenType following the 2 examples provided, but not sure it's worth looking at them.  If you are interested anyway here are the files:

https://mega.nz/file/PapUxRRL#Y_Fv9nIUldgPJ43XOHvbfbjp7sESg6SQDfrS2x5sJpA
https://mega.nz/file/yXQghaxI#c6atA700EKcJlO5Oh6mXwFENuK-MkfI37tdNaLYTS94

**Comment by CastagnaIT** [comment]
out of curiosity i tried both .otc attached but fontforge and also libass are not able to load glyphs

**Comment by CastagnaIT** [comment]
please wait to merge this
i want try investigate better also for #23300 that if needed i will improve some code

**Comment by CastagnaIT** [comment]
all ok ready to merge
