### PR TITLE
[EPG] change season/episode infolabels for specials

### LINKED ISSUE #17402: xbmc.getInfoLabel('VideoPlayer.Season') and xbmc.getInfoLabel('VideoPlayer.Episode') Not Integers for Specials
### Describe the bug
Here is a clear and concise description of what the problem is:

https://github.com/trakt/script.trakt/issues/490

As raised in the issue above. The kodi video player reports a special episode as ES1 instead of S0E1

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

xbmc.getInfoLabel('VideoPlayer.Episode') and xbmc.getInfoLabel('VideoPlayer.Season') should always return an int not a string as anyone who codes to grab these values expects ints to be returned.

## Actual Behavior

If the infolabels of an item in an plugin are set to {'season': 0, 'episode': 1} then Kodi returns the season as None and the episode as S1

## Possible Fix

Set xbmc.getInfoLabel('VideoPlayer.Season') to return 0 when the infolabel for the listitem is 0
and set xbmc.getInfoLabel('VideoPlayer.Episode') to return the int of the episode not add S to highlight the episode as a special.

### To Reproduce

1. Setup the trakt script from the Kodi repo and watch any file from a plugin where the season is set to 0 on its infolabel.

### Your Environment
Used Operating system:

 - [ Yes ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ]  OSX
 - [ ] Raspberry-Pi
 - [ Yes ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Martix 19 Any Nightly 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ronie**
this is follow-up to https://github.com/xbmc/xbmc/pull/17408

i missed the fact that PVR uses their own code for the season and episode infolabels,
this PR now corrects that code as well.

before:
```
ListItem.Season:
ListItem.Episode: S1
```

after:
```
ListItem.Season: 0
ListItem.Episode: 1
```

(the same change applies to VideoPlayer.Season / VideoPlayer.Episode)

fixes https://github.com/xbmc/xbmc/issues/17402

for skinners / addon devs it's much easier to work with those infolabels this way.

### CODE REVIEW

File: xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp [hunk 1]
```diff
@@ -574,10 +574,7 @@ bool CPVRGUIInfo::GetListItemAndPlayerLabel(const CFileItem* item, const CGUIInf
       case LISTITEM_EPISODE:
         if (epgTag->EpisodeNumber() > 0)
```
Comment (phunkyfish) [inline xbmc/pvr/guilib/guiinfo/PVRGUIInfo.cpp]: `>= 0`

This makes it consistent with how it works for VideoInfoTag

**Review by phunkyfish — COMMENTED** [review]
And in xbmc/pvr/epg/EpgInfoTag.h we also need to change the defaults I think.

    int m_iSeriesNumber = -1; /*!< series number */
    int m_iEpisodeNumber = -1; /*!< episode number */
    int m_iEpisodePart = -1; /*!< episode part number */

**Comment by phunkyfish** [comment]
IF we are happy with this the code changes can happen here and doc changes in the other PR or do we want it all in one PR?

**Comment by ronie** [comment]
two PR's are fine, the can be merged at the same time.

> int m_iEpisodePart = -1; /*!< episode part number */

not sure about this one.. does it have any relation to the code i'm altering?

**Comment by phunkyfish** [comment]
We should be consistent in the API. If -1 means invalid it should mean that for all season episode info.

**Comment by emveepee** [comment]
>
>And in xbmc/pvr/epg/EpgInfoTag.h we also need to change the defaults I think.

     int m_iSeriesNumber = -1; /*!< series number */
     int m_iEpisodeNumber = -1; /*!< episode number */
     int m_iEpisodePart = -1; /*!< episode part number */

That is only if you want to document invalid as the default.  As I was trying to point out in another post PVR addons will typically use memset() or = {} and they will all be zero anyway.  I was thinking for the future C++ port a common way of getting defaults would be better

**Comment by phunkyfish** [comment]
The API should be correct and consistent regardless of whether this is a recording or an epg tag.

We can fix the addons after that.

**Comment by phunkyfish** [comment]
I assume there are no plans to backport this change. If so we have time to fix the matrix versions of the addons.

**Comment by phunkyfish** [comment]
@ronie these should also be updated to `>= 0`: https://github.com/xbmc/xbmc/blob/40b26aa29f047939494e7ac7c0584e440b775035/xbmc/pvr/epg/EpgInfoTag.cpp#L646

**Comment by ronie** [comment]
addressed all comments made by @phunkyfish

**Review by phunkyfish — APPROVED** [review]
Looks good, will put this on hold as I need to make the PVR addons changes and have them ready before this can go in.

**Comment by phunkyfish** [comment]
Hope to merge this shortly as the first of 3 PRs all that have a PVR API change.

This one first, then https://github.com/xbmc/xbmc/pull/17153 and finally https://github.com/xbmc/xbmc/pull/17192.

**Comment by emveepee** [comment]
> 
> 
> Hope to merge this shortly as the first of 3 PRs all that have a PVR API change.
> 
> This one first, then #17153 and finally #17192.

You probably should be changing these PR's to use the defines rather the >=0 or >0    Also with your arguments that some cultures might start shows with episode 0 and episodepart 0 should,  you not follow the same logic for series and come up with a define for  specials?

**Comment by phunkyfish** [comment]
> > Hope to merge this shortly as the first of 3 PRs all that have a PVR API change.
> > This one first, then #17153 and finally #17192.
> 
> You probably should be changing these PR's to use the defines rather the >=0 or >0 Also with your arguments that some cultures might start shows with episode 0 and episodepart 0 should, you not follow the same logic for series and come up with a define for specials?

Hmmm. On this one I'm not sure. I think reading the code it's clear that if any of those functions have a value of 0 or greater then it's valid as a series. If `function > INVALID`, not so much. The defines are largely for the benefit of PVR Addon devs.

What were you thinking of for the definition of specials? I wonder since the use cases for specials vary so much, maybe we shouldn't be defining anything and leave the addon decide the definition of a series itself.

**Comment by emveepee** [comment]
> 
> 
> > > Hope to merge this shortly as the first of 3 PRs all that have a PVR API change.
> > > This one first, then #17153 and finally #17192.
> > 
> > 
> > You probably should be changing these PR's to use the defines rather the >=0 or >0 Also with your arguments that some cultures might start shows with episode 0 and episodepart 0 should, you not follow the same logic for series and come up with a define for specials?
> 
> Hmmm. On this one I'm not sure. I think reading the code it's clear that if any of those functions have a value of 0 or greater then it's valid as a series. If `function > INVALID`, not so much. The defines are largely for the benefit of PVR Addon devs.
> 

I find invalid looks just odd in the PVR code too thought it might be better to be consistent.

> What were you thinking of for the definition of specials? I wonder since the use cases for specials vary so much, maybe we shouldn't be defining anything and leave the addon decide the definition of a series itself.

I never liked S0 for special since it looks really hacky in the guide out of context.  I think EPG specials are more like the flags I discussed on the RFC thread  the @djp952 opened.  If you check the link I made for that thread showing some other guides https://imgur.com/a/wxeXMvR check how they deal with the live, premier, new indicators.  To me special fits more in that category where you might want to quickly pick it out.

TMS (Schedules Direct and HDHR) data,  specials are considered a genre but there is no DVB standard map for that so NextPVR doesn't pass it to the guide for Kodi.  It does pass genre text for recordings though and the text "Special" looks much clearer then S0

**Comment by phunkyfish** [comment]
I do like having the new as a flag, adding live and premier would be easy after these PRs (even specials if we get to that), some of those flags could make sense on recordings too. On the specials side I would like to hear @ronie's thoughts though as the experience would want to be consistent across PVR and Videos. The EPG UI is very full already so not sure what scope there would be to display it differently.

**Comment by emveepee** [comment]
> 
> 
> I do like having the new as a flag, adding live and premier would be easy after these PRs (even specials if we get to that), some of those flags could make sense on recordings too. On the specials side I would like to hear @ronie's thoughts though as the experience would want to be consistent across PVR and Videos. The EPG UI is very full already so not sure what scope there would be to display it differently.

This discussion is better in the RFC for follow up but for the EPG display flag I think the flag is mutually exclusive coded by the addon to save space  For example I would code Special, Premier or Finale (when New), and Live.     If there was a live, special, series on covid19 premiering tonight a dev would need to think which to flag.  Currently it would be new and you'd have to navigate to it to see S0.

**Comment by phunkyfish** [comment]
WIN32 failure unrelated

**Comment by emveepee** [comment]
For completeness the hard-coded S in the code which is not really season plus S and E in the skin should probably be internationalized in a future release.
