### PR TITLE
[VideoPlayer] Fix and improve subtitle stream selection

### LINKED ISSUE #15672: Forced subtitles not working when audio and subtitle language is different
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing a video with forced subtitles it doesn't automatically turn on if the subtitle language is different from the audio language.

For example I have an anime episode with JPN video, JPN audio and ENG forced subtitles, this doesn't work as subtitles are not enabled by default even with "Forced only" enabled in settings.

If I take the same file and change it in MKVToolNix to ENG video, ENG audio and ENG forced sub without actually changing the files it works and forced subtitles are enabled by default like they should.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Matching language for audio and subtitles should be irrelevant as forced should mean forced no matter what language is set on the file as long as the subtitle is flagged as forced.

## Actual Behavior

Only enables forced subtitles by default if audio and subtitle language matches.

### To Reproduce

1. Take a file and change audio and subtitles language to different languages in MKVToolNix as well as flagging it as forced.
2. Take the same file but this time make another one with audio and subtitle language set to the same language.
3. Play both files in Kodi and the first file will have subtitles disabled even with "Forced only" enabled while the 2nd file will play just fine.

### Debuglog

The debuglog can be found here: 
[kodi.log](https://github.com/xbmc/xbmc/files/2929114/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 8.0.0
 - Kodi version: Kodi 18.1 20190228

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #24777: [Kodi 21]: Automatically disable the subtitle setting without asking the user at adaptive streaming
## Bug report
Kodi automatically deactivates subtitles after a certain period of time. After manual reactivation in the Kodi OSD, the subtitles will be displayed again for a certain time until they are automatically deactivated again. I was able to understand the problem, especially with the PrimeVideo addon for adaptive streaming.
### Describe the bug
Here is a clear and concise description of what the problem is:
The matter has already been mentioned in connection with the inputstream.adaptive addon and is shown here: https://github.com/xbmc/inputstream.adaptive/issues/1461#issuecomment-1966194360

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Once activated, subtitles are displayed throughout the entire duration of the stream.

## Actual Behavior
Kodi automatically deactivates subtitles after a certain period of time.

## Possible Fix
see: https://github.com/xbmc/inputstream.adaptive/issues/1461#issuecomment-1966194360

### To Reproduce

1. Start Amazon VOD (plugin.video.amazon-test) Addon in Kodi (german Version)
2. Start Stream (Live Streaming recommended)
3. Enabling subtitles in Kodi OSD
4. After a certain time the display stops (manual reactivation of the subtitles required)

### Debuglog

The debuglog can be found here:
[kodi.sub.log](https://github.com/xbmc/xbmc/files/14458478/kodi.sub.log)
[kodi_sub_debug1.log](https://github.com/xbmc/xbmc/files/14458659/kodi_sub_debug1.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 -   Hardware: Raspberry Pi 400
 -   OS version: LineAgeOS 20 (Android 13)
 -   Kodi version number: Omega (21.0-Beta3)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #25617: Subtitle precedence messed up if "Preferred subtitle language" = "Original language"
### Describe the bug

Here is a clear and concise description of what the problem is:

The subtitle precedence seems messed up if _Preferred subtitle language_ is set to `Original language`.

Additionally, _Prefer subtitles for the hearing impaired_ is completely ignored if _Preferred subtitle language_ is set to `Original language`.

## Expected Behavior

Here is a clear and concise description of what was expected to happen:

If _Preferred subtitle language_ is set to `Original language` and a video has one or more subtitle tracks flagged as _original_, the precedence for those matching tracks should be exactly the same as if the tracks were matched by a specificied language, e.g matching English tracks if _Preferred subtitle language_ were set to `English`.

So, if _Preferred subtitle language_ is set to `Original language` and _Prefer subtitles for the hearing impaired_ is `disabled`, the precedence should be like this:

1. The first track with _original_ flag + any other flags
2. None (or maybe the _default_ track)

and if _Preferred subtitle language_ is set to `Original language` and _Prefer subtitles for the hearing impaired_ is `enabled`, the precedence should be like this:

1. The first track with _original_ and _hearing impaired_ flag + any other flags
2. The first track with _original_ flag + any other flags
3. None (or maybe the _default_ track)

## Actual Behavior

If _Preferred subtitle language_ is set to `Original language`, the precendence seems to be like this:

1. The first track with _original_ and _forced_ flag + any other flags
2. The first track with _default_ flag + any other flags, no matter the _original_ flag
3. The first track with _original_ flag + any other flags

Enabling _Prefer subtitles for the hearing impaired_ also has no effect.

## Possible Fix

On playback start, get all subtitle tracks with the _original_ flag, then apply the same precedence as if those tracks were matched by using a specifc language setting, e.g. _Preferred subtitle language_ = `English`.

BTW: currently, if _Preferred subtitle language_ is set to a specific language and _Prefer subtitles for the hearing impaired_ is `disabled`, the first track with the matching language is selected, purely based on the track order. But in my opinion no matter the setting of _Prefer subtitles for the hearing impaired_, _forced_ tracks matching the selected language should have the lowest precedence among the matching tracks, because if the user only wanted to play _forced_ tracks, they always have the option to set _Preferred subtitle language_ to `Forced only`. Of course this should also be true if _Preferred subtitle language_ is set to `Original language` and not to a specific language.

### To Reproduce

1. Create a video file with multiple subtitle tracks
   1. Track with _original_ flag
   2. Track with _original_ and _hearing impaired_ flag
   3. Track with _original_ and _forced_ flag or alternatively a track with only the _default_ flag
2. Set _Preferred subtitle language_ to `Original language`
3. Play the video file
4. Observe track 3 getting selected even if the correct one should be track 1, or track 2 (if _Prefer subtitles for the hearing impaired_ is `enabled`)

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/hirediwipa

### Screenshots

Here are some links or screenshots to help explain the problem:

The beginning of the video shows the correct behaviour if _Preferred subtitle language_ is set to `English`, and then the incorrect behavior seen on 3 files after setting _Preferred subtitle language_ to `Original language`.

All 3 files have their English tracks flagged as _original_ (Kodi sadly doesn't show the _original_ flag in the subtitle list):

- Batman has the most tracks
- Iron Man lacks the English _original_, _forced_ track compared to Batman
- Avengers lacks the Spanish _default_ track compared to Iron man

I created 3 files with different tracks to show the currently used precedence.

https://github.com/user-attachments/assets/0d1528d0-ea25-47f1-9d53-a2cc9be6860b

## Additional context or screenshots (if appropriate)

Here is some additional context or explanation that might help:

### Your Environment

Used Operating system:

- [ ] Android
- [ ] iOS
- [ ] tvOS
- [ ] Linux
- [ ] macOS
- [x] Windows
- [ ] Windows UWP

- Operating system version/name: Windows 11
- Kodi version: 21.0

_note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved._

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

i started rework this part, starting from impaired problems and then i improved also other use cases

**problems fixed:**
1) if you set "original", kodi select and show the "forced" track based on audio language (ref. issue #25617)
2) "hearing impaired" setting dont works combined with "original"
3) "hearing impaired" setting apparently do nothing with "forced", now if both are enabled "forced" is internally disabled
4) if you set a sub language, and the video played dont have it, kodi still show a language based on audio language, that usually its different (does not comply with the chosen language), now if a sub language dont exists subtitles become disabled
5) "default" flag on all use cases was not so well handled, i handled some more distinctions on code
6) Changes to videos with embedded CC subtitles (read section below)
7) Wrong subs language selection can happens when: _audio language setting is set to a language not provided by the video played, and subtitle language setting is set to a language not provided by the video played or "forced"_. This will lead to a wrong subs language at playback startup. Caused by the fact that the code only considered the audio language coming from the audio track to be played without considering the audio language settings (ref. issue #15672)

### About subtitles "default" flag
from what i understood on the subtitles the "default" flag is not so important since it is used only
to give more priority to a stream, for the case when there are two streams with same properties (lang and flags, but maybe different author version or codec)
On kodi there is no “Media default” setting for subs in the GUI, such as happens on audio language setting, and there is no intention to implement it

### Note for the case 4
this problem was mentioned also on 
https://github.com/xbmc/xbmc/blob/ed8f18b779b28ee62e5e1154e839479680612700/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L103
this behaviour make no sense to me, a user set a subtitle language because should want to display only that language, but kodi fallback to the audio language when missing, this does not match the GUI setting, this bug(?) or weird feature is not documented anywhere, so now has been changed, if the language is missing dont show nothing

### Changes to videos with embedded CC subtitles
The current behaviour of Kodi was:
on CC stream mark it as "hearing impaired", but on stream selection full ignore the "impaired" flag and treat it as regular subtitle

I find this behaviour inconsistent, that also make the subtitle selection code more hard to understand,
when a subtitle is defined/marked as “impaired” it should be treated as such, not force it with a different behavior

as also explained on wiki https://en.wikipedia.org/wiki/Closed_captioning CC subtitles are generally regular subtitles,
in some cases there may be countries that treat them for hearing impaired, but its not a rule.

what changes i have done: i removed the "impaired" flag previously set by default to CC streams. CC streams can be identified now by the "CC" name on description

immagine

the behavior remains the same as before,
plus i added a new setting that allows you to reassign the "impaired" flag to CC streams
immagine
this allows you to change the stream auto-selection behaviour of subtitles and can also prevent them from being automatically selected if not desired

the `language = "cc"` on `CDVDDemuxCC` demuxer has been removed
https://github.com/xbmc/xbmc/blob/9f5b450620cc4fb284ea654ea4d71b3982af2b28/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxCC.cpp#L405
"cc" language code was sort of hack and an invalid lang code,
the only uses of "cc" lang was on the stream selection code that i have also removed since not needed anymore.
Instead of "cc" on CC will be set "und" thats an expected language code internally allowed for "undetermined" language case

### sidenotes
i removed the `subson` variable that was changing behaviour of the sort order (the order of priority) for unclear reasons to me,
if subtitles are disabled i dont see why there should be a different sort order
if some one has some reminescence of this say so, i found apparently no possible problems in its removal

I add missing Dhivehi to ISO 639-2, this lack wasted my time in testing, because caused different behavior in subtitle selection due to incorrect coversion of the language code, anyway the root of problem has been fixed by #26011

## Motivation and context

fix #25617
fix #24777
fix #15672

## How has this been tested?

- basic things with self modified mkv that contains more subs
- mkv with more external subtitles (subs with same mkv filename but with appended "-eng-forced.srt", "-eng-impaired.srt", etc...),
- videos with embedded CC
- PVR iptv m3u with embedded CC

DVD is not affected by this PR change

## What is the effect on users?

appropriate subtitle selected on playback start
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by scott967** [comment]
As I understand it "forced" was created to mark certain portions of a sub for the original or primary audio track language.  Expanded to allow for an entire text codec sub to be treated as "forced", again for the original audio language and then expanded again for audio tracks in other languages as a separate "forced" text sub.   I guess the default is to show the "forced" sub if it exists for the current selected audio track language, irrespective of a global "enable sub" or "sub language" setting (unless player language subtitle set to "None").  But that probably cause problem where "forced" sub is separate from "narrative" or "hearing impaired" sub in the same language.  Not sure there is a correct answer.

**Comment by CastagnaIT** [comment]
forced are a type of subtitle tracks different from regular one, which show only a little info on the screen
not to be mixed with other tracks (avoid auto-selecting other types if “forced” is set)

>  I guess the default is to show the "forced" sub if it exists for the current selected audio track language, irrespective of a global "enable sub" or "sub language" setting (unless player language subtitle set to "None")

currently is not so...
is as i explained above, if there are duplicate subtitles with the exact same characteristics/properties those are selected
i think because there is no “Media default” setting for subs in the GUI, such as on audio language setting,
should be added the “Media default” setting to subs setting to do what you mean correctly,
I don't know the reason why there is no such setting for subtitles, perhaps because it would not be used much

**Comment by CastagnaIT** [comment]
@enen92 if one day you can review, also take a look in the description: "note for the case 6 fix" maybe you can give some info about this

**Comment by CastagnaIT** [comment]
PR can be reviewed,
i have some problems in testings due to kodi crashes not related to this (amd problem #25985) that prevent me to make some tests e.g. DVD 

i tag here someone that recently helped on subs things
@jjd-uk, @scott967 for general testing?
@ksooo you could provide a feedback for PVR CC subs, if you have a channel that have it
@CrystalP for dvd test? and/or in general

what to test, play video to see if subtitles are correctly auto-selected at playback startup, based on choosen settings, e.g.:
- set sub setting to a language or "forced", with or without "hear impaired" setting enabled
- uses of external subs for local video files
- with PVR having CC embedded to video, should be shown/enabled as before, with the exception when the new setting `Set CC subtitles only for the hearing impaired` is enabled
- DVD, im expecting no problems, but i cant test it

I have done a variety of tests, and seem no regressions,
but as there are many use cases it could be that some specific use case i missed

**Comment by jjd-uk** [comment]
@enen92 did some work with Closed Captions so it could be worth him having a look at that aspect of this if he has the time.

I'll try and find the time to do some general testing at the weekend.

**Comment by scott967** [comment]
Testing an mkv file with 2 video Eng default no /  Jpn default yes
2 audio Jpn default yes / Eng default no
3 subs Eng default yes / Heb default no / Jpn default no forced yes hearing impaired yes

Interface lang Eng
language  preferred audio lang media default
language preferred subtitle lang  forced only
language prefer subtitles for hearing impaired yes
play movie / check stream select dialog -- all streams reported correctly 

on playing the English sub (default) is selected?
screenshot00004

**Comment by CastagnaIT** [comment]
i created a mkv with same languages/flags
i used your settings
immagine
despite its weird that your mkv have forced and captions combined toghether
to me the japanese track is selected correctly
immagine
maybe you have by mistake changed track manually that have invalidated the auto-selection?

try rename the mkv file name with another name to avoid saved preferences, or delete kodi video database to force reset stored preferences

**Comment by CastagnaIT** [comment]
some test builds for the review
http://mirrors.kodi.tv/test-builds/android/arm/kodi-20241127-5c7cda41-fix_sub_selection-armeabi-v7a.apk
http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20241127-5c7cda41-fix_sub_selection-arm64-v8a.apk
http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20241127-5c7cda41-fix_sub_selection-x64.exe
http://mirrors.kodi.tv/test-builds/osx/x86_64/kodi-20241128-5c7cda41-fix_sub_selection-36419-x86_64.dmg
http://mirrors.kodi.tv/test-builds/osx/arm64/kodi-20241128-5c7cda41-fix_sub_selection-6676-arm64.dmg

**Comment by CastagnaIT** [comment]
@garbear are you able to review this one?
i would like to merge within this month to get possible user feedbacks

File: xbmc/utils/LangCodeExpander.cpp [hunk 1]
```diff
@@ -921,6 +921,7 @@ const std::array<struct LCENTRY, 540> g_iso639_2 = {{
     {MAKECODE('\0', 'd', 'e', 'l'), "Delaware"},
     {MAKECODE('\0', 'd', 'i', 'n'), "Dinka"},
     {MAKECODE('\0', 'd', 'i', 'v'), "Divehi"},
+    {MAKECODE('\0', 'd', 'i', 'v'), "Dhivehi"},
```
Comment (garbear) [inline xbmc/utils/LangCodeExpander.cpp:924]: This code is identical to the line above? Are dictionary entries not supposed to be unique in this map?

Comment (CastagnaIT) [reply xbmc/utils/LangCodeExpander.cpp:924]: some english names in the ISO 639-2 can have name variations with same code, another example is "Haitian" that have 2 names variants
it is possible that others multiple names are missing (i have not check its out of scope of this PR) i found this one by chance,
despite this anyway the root of problem (mentioned on PR "sidenote") will be fixed by #26011

**Comment by jjd-uk** [comment]
Sorry had as much time as I hope to test due to family member being in hospital. I've done some brief testing and not noticed any regressions,

> 1. if you set "original", kodi select and show the "forced" track based on audio language

Can you explain this fix?

Is it in the case of Audio set to Original and Subtitles set to English, then if I play something with with both Forced and Full English subtitle tracks then it will prefer the Forced track over the full track?

**Comment by CastagnaIT** [comment]
> 1. if you set "original", kodi select and show the "forced" track based on audio language

> Can you explain this fix?

yes, you can set the desired audio language dosnt matter, but we assume "original" is set to subs kodi language,
then fwik 2 bugged use cases:
- play video without original sub track >> results kodi wrongly select forced subs, instead to fallback to regular subtitle, if any, imo forced should not be shown
- play video without original sub track, but impaired track available, and pref. impaired sub setting is enabled >>> results kodi wrongly select forced subs, and wrongly ignore impaired track

**Comment by CrystalP** [comment]
> i removed the subson variable that was changing behaviour of the sort order (the order of priority) for unclear reasons to me,
if subtitles are disabled i dont see why there should be a different sort order

Could be for the selection of forced/normal subs? Subs off by default > prioritize forced subs. Subs on > prioritize non-forced subs. Non-forced subs normally include the content of the forced subs.

Some of the current code oddities could have been ways to deal with empty/und sub language? Those would be lower priority than subs with some attributes + language match, but are still candidates.

**Comment by CastagnaIT** [comment]
> Could be for the selection of forced/normal subs? Subs off by default > prioritize forced subs. Subs on > prioritize non-forced subs. Non-forced subs normally include the content of the forced subs.

it is not clear to me what you mean exactly with "Subs off by default", please explain better

if the forced track in the preferred lang is missing, the "regular" one is preselected, as per:
https://github.com/xbmc/xbmc/blob/5c7cda41cf8c2914350304f5a41e5e1291f0f6c7/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L378-L379

> Some of the current code oddities could have been ways to deal with empty/und sub language? Those would be lower priority than subs with some attributes + language match, but are still candidates.

i will improve the fallback

---
i have found just now another bug in the original kodi subtitle selection code, that i will need to investigate,
steps to reproduce:
1) set audio language setting to a language not provided by the video played
2) set subtitle language setting to a language not provided by the video played or "forced"

Will results that kodi selected a wrong subs language that dont match the settings, but match the language of the currently played audio track (that may change depends from the video)
therefore there is a clear inconsistency, and user settings are ignored, IMO this is clearly wrong
when the track language is missing should disable subs instead to show a different language

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 2]
```diff
@@ -86,68 +86,105 @@ using namespace std::chrono_literals;
...
 
-    if (ss.language == "cc" && ss.flags & StreamFlags::FLAG_HEARING_IMPAIRED)
-      return false;
+      return true;
+    }
 
-    if(!original)
+    if (m_isPrefOriginal)
+    {
+      if ((ss.flags & FLAG_ORIGINAL))
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:169]: maybe if (ss.flags & (FLAG_ORIGINAL | FLAG_DEFAULT)) ?
is it ok not to match the language?
no else on purpose?

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 3]
```diff
@@ -86,68 +86,105 @@ using namespace std::chrono_literals;
...
         return false;
+      else
+        return true;
     }
-    else if (ss.flags & StreamFlags::FLAG_DEFAULT)
+
+    // can fall here only when "forced" and "impaired" are disabled,
+    // it always enable subs if language is unknown for external and CC
+    if ((isSameSubLang ||
+         ((isExternal || isCC) && (ss.language.empty() || ss.language == "und"))) &&
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:183]: external + no language already covered L141

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 4]
```diff
@@ -86,68 +86,105 @@ using namespace std::chrono_literals;
...
+        (ss.flags & FLAG_FORCED) == 0 && (ss.flags & FLAG_HEARING_IMPAIRED) == 0)
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:184]: maybe a ss.flags & FLAG_DEFAULT somewhere in that expression?

why (ss.flags & (FLAG_FORCED | FLAG_HEARING_IMPAIRED) == 0)? even with one of those flags, it's still a good sub if it was ranked the best available? maybe it's the only sub.

**Comment by CrystalP** [comment]
> > Could be for the selection of forced/normal subs? Subs off by default > prioritize forced subs. Subs on > prioritize non-forced subs. Non-forced subs normally include the content of the forced subs.
> 
> it is not clear to me what you mean exactly with "Subs off by default", please explain better

I meant the subtitles on/off setting stored in video settings or the default value saved in guisettings.xml after using "set as default for all media" in the OSD.

It gets tricky when OpenDefaultStreams overrides the setting because of "relevant()" and forced_flag testing. I just noticed a problem with that actually and will submit a PR.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:169]: there is no need to check for FLAG_DEFAULT on PredicateSubtitleFilter it is not a flag to be considered for enabling and disabling subtitles

> no else on purpose?

it must be able to go further to the next condition

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 4 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:184]: this code is for enable/disable subs only, not used for track selection,
so FLAG_DEFAULT has no importance here,
you cant mix impaired and forced or you will cause a wrong behaviour on subtitle visibility/enabling

**Comment by CastagnaIT** [comment]
changes done,
also implemented changes to fix last bug found above https://github.com/xbmc/xbmc/pull/25813#issuecomment-2530779646

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 5]
```diff
@@ -216,91 +253,148 @@ class PredicateAudioFilter
...
-    filter(lang, stream),
-    subStream(stream)
+  explicit PredicateSubtitlePriority(const std::string& lang, int stream)
+    : m_playedAudioLang(lang), m_filter(lang, stream), m_subStream(stream)
   {
+    auto settings = CServiceBroker::GetSettingsComponent()->GetSettings();
+    const std::string subLangSetting =
+        settings->GetString(CSettings::SETTING_LOCALE_SUBTITLELANGUAGE);
+
+    const bool isSubNone = StringUtils::EqualsNoCase(subLangSetting, "none");
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:285]: Unused variable:

```
/home/jenkins/jenkins-root/workspace/android-arm64-docker@4/xbmc/cores/VideoPlayer/VideoPlayer.cpp:285:16: warning: unused variable 'isSubNone' [-Wunused-variable]
  285 |     const bool isSubNone = StringUtils::EqualsNoCase(subLangSetting, "none");
      |                ^~~~~~~~~
1 warning generated.
```

File: addons/resource.language.en_gb/resources/strings.po [hunk 6]
```diff
@@ -24230,6 +24230,18 @@ msgctxt "#39203"
...
+msgid "Set CC subtitles only for the hearing impaired"
+msgstr ""
+
+#. Help text for setting of label #39204
+#: system/settings/settings.xml
+msgctxt "#39205"
+msgid "By enabling it, CC subtitles will be labeled for the hearing impaired; this will affect the automatic selection of subtitles, which unless otherwise specified will not be displayed by default."
+msgstr ""
+
 #empty strings from id 39204 to 39999
```
Comment (thexai) [inline addons/resource.language.en_gb/resources/strings.po:24245]:
```suggestion
#empty strings from id 39206 to 39999
```

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 5 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp]: thanks

**Review by thexai — APPROVED** [review]
Tested few days in my habitual usage and no issues found.

**Comment by ksooo** [comment]
@CastagnaIT sorry, a bit late to the party, but stumbled about the following while translating the new strings: 

image

That "CC" displayed in the dialog definitely should be a localizable string. "CC" will say nothing to most of our end users, I'm afraid.

**Comment by jjd-uk** [comment]
> That "CC" displayed in the dialog definitely should be a localizable string. "CC" will say nothing to most of our end users, I'm afraid.

In my experience fromthe UK then CC for closed captions is always used in EPG's, however as there's the space here then I'd agree that perhaps the long form should be used.

**Comment by ksooo** [comment]
> however as there's the space here then I'd agree that perhaps the long form should be used.

My main point is not space/abbreviation, but translation into other languages. For example, in German even the abbreviation would be something other than "CC".

**Comment by jjd-uk** [comment]
> > however as there's the space here then I'd agree that perhaps the long form should be used.
> 
> My main point is not space/abbreviation, but translation into other languages. For example, in German even the abbreviation would be something other than "CC".

OK, I hadn't realised it wasn't a universal abbreviation.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 7]
```diff
@@ -971,8 +1062,8 @@ void CVideoPlayer::OpenDefaultStreams(bool reset)
       valid = true;
       if(!psp.relevant(stream))
         visible = false;
-      else if(stream.flags & StreamFlags::FLAG_FORCED)
-        visible = true;
+      //else if(stream.flags & StreamFlags::FLAG_FORCED)
+      //  visible = true;
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:1066]: Hello @CastagnaIT, what was the idea behind this removal? It made sense to force forced subs on when user has subs off by default. Those lines were not responsible for the issue #26050.

Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:1066]: > what was the idea behind this removal?

I think removal is OK because this condition now is included inside "relevant" filter.

> It made sense to force forced subs on when user has subs off by default.

No, because then the setting options "None" and "Forced only" behaves the same.

If user has subs language = "None" and continues displaying forced subs then is the same than "Forced only".

As it is now is fine.

> Those lines were not responsible for the issue https://github.com/xbmc/xbmc/issues/26050.

Agree. This issue still present in current master.

Comment (mkreisl) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:1066]: > About subtitles "default" flag

> from what i understood on the subtitles the "default" flag is not so important since it is used only
> to give more priority to a stream, for the case when there are two streams with same properties (lang > and flags, but maybe different author version or codec)
> On kodi there is no “Media default” setting for subs in the GUI, such as happens on audio language > > setting, and there is no intention to implement it

With this PR you have ruined a decades-long behavior, namely that subtitles containing the default flag are automatically displayed

Congratulations on this insane change

**Comment by mkreisl** [comment]
> About subtitles "default" flag

> from what i understood on the subtitles the "default" flag is not so important since it is used only
> to give more priority to a stream, for the case when there are two streams with same properties (lang > and flags, but maybe different author version or codec)
> On kodi there is no “Media default” setting for subs in the GUI, such as happens on audio language > > > setting, and there is no intention to implement it

With this PR you have ruined decades of behavior, namely that subtitles containing the default flag are automatically displayed

I have thousands of mkv files that rely on default flagged subtitles being displayed and from now on will not be displayed without intervention

Players such as SMPlayer, on the other hand, still do it correctly, I wonder how you can suddenly come up with the idea of not doing it that way anymore

Congratulations on this insane change

**Comment by CastagnaIT** [comment]
you completely misunderstood the description mentioned

kodi has, never, implemented support for “default” flags in subtitles
this PR has no influence in that, and it is not the intention of this PR to implement support for "default" flag for subtitles

**Comment by CastagnaIT** [comment]
if you have a particular use case that now seems not to be working, open an issue so that we can understand better the situation and investigate appropriately.

if you want to make a request ask implementing default flag (“Media default” setting) support for subtitles, use the appropriate “feature request” section of the forum

I invite you to don't use development PR's for complaints without clear basis...

**Comment by crawfish3141** [comment]
Appreciate all this good work, and I concur that the Default flag does NOT means the subtitles should be displayed by default. That's a bit of misinformation I see repeated on a regular basis, and Kodi doesn't work like that anyway.

I'm wondering, have you considered altering the effect of the Toggle Subtitles command to switch between Main(1) and Forced subtitles when the latter are present? That's the sensible behavior I've implemented in Autohotkey and JSON for my own use. Kodi currently just turns Forced subtitles on and off, which is not useful. Main subtitles should contain all the Forced ones, and the idea behind toggling is to switch between the complete subtitles and the Baseline(1) ones. The only downside is that you can run into the "10 second delay when switching subtitles". I talked about both these things in this post, but mainly the delay, which came to my attention when I implemented my new Toggle command:

https://github.com/xbmc/xbmc/issues/21086

(1) "Main" subtitles are the highest ranked ones outside of the subset of Forced ones, e.g. they're in the default user language, and out of those, the one marked "Default", if any. For purposes of my Toggle command, I define "Baseline" subtitles as the highest ranked Forced one or no subtitles at all if there are no Forced ones. Thus, toggling switches between Baseline and Main subtitles.

**Comment by crawfish3141** [comment]
In v22 Alpha 3, the default settings cause non-forced external .srt subs lacking a language identifier in the filename to be shown. Adding .en to the end of the filename suppresses them. They shouldn't be shown without the ID. By default settings, I mean this excerpt from guisettings.xml, which includes settings available from the main Settings menu system and settings available only from the OSD during playback:

```
<settings>
    <setting id="locale.subtitlelanguage">forced_only</setting>
    <defaultvideosettings>
            <showsubtitles>true</showsubtitles>
    </defaultvideosettings>
</settings>
```

In v21 and at least a version or two earlier, values (default, false) for the above worked right for everything, including this case, and in general, showing forced subs when present, even when there was only one sub in the file, and not showing unforced subs by default. Kodi v22 does not update these values when installed over v21, and it does not treat this combination the same. It was a bit of a struggle to figure out how to get the desired behavior back. I arrived at the v22 defaults by trial and error, and I then verified them against a new installation in a VM. Still, it fails on the external .srt subs lacking language ID as described above.

ETA: v22 Alpha 3 is not showing forced subs by default when they are the only subs present, even with the default v22 settings. Again, this worked fine in v21. This affects internal subs having language ID, so it's a separate issue from the external subs lacking language ID in their filenames
