### PR TITLE
[guilib] Ensure ListItems release the layout before it is destroyed

### LINKED ISSUE #15226: Kodi 18 crash using script.extendedinfo
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 18 crashes when extendedinfoscript dialog window YoutubeList.xml is closed.  Current viewmode for the media window is changed without user action.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

dialog window YoutubeList.xml closes and Kodi returns to the existing media window with the existing viewtype mode.

## Actual Behavior

When the dialog is closed by keyboard action "back" the dialog closes and gui shows the media window.  Within a couple of seconds Windows 7 error popup launches that Kodi has stopped working debug/close 

## Possible Fix

After extensive testing of available Windows nightly builds, nightly 170517 is the last one that does not crash, and 170629 is the first one that does crash.  I don't have any builds between those dates for further testing.

What I found is that script.extendedinfo loads modules from script.module.kodi65
kodi65 has a file dialogbaselist.py that handles setting up YoutubeList.xml as an XMLdialog and populating the container with listitems (links to youtube videos).

Dialogbaselist.py implements Class DialogBaseList(object) and a method in that class is def OnInit(self):

OnInit contains the following:

        viewtype = addon.setting("viewtype_selection")
        if viewtype:
           xbmc.executebuiltin("Container.SetViewMode(%s)" % viewtype)

In a default install "viewtype_selection" is set to -1.  I tried manually changing it to 500 (the id of the container in YoutubeList.xml) but that didn't change the crash.  I then commented out the
xbmc.executebuiltin("container.SetViewMode(%s)" % viewtype)

That fixed the problem of the media window changing its viewmode (but still crashed).

I then located the method def update_ui(self):

In update_ui is 

```
for item in self.listitems:
    item.set_label2(self.LABEL2[self.sort](item))
    items.append(item.get_listitem())
    self.addItems(items)
```

which I changed last line to

    self.getControl(500).addItems(items)

After which I no longer get the crash (limited testing tho)

However, this seems like a work-around, AFAIK, the Python API allows scripts to use XMLwindow containers with view modes (and other Dialogs in this addon do have multiple views).  So I consider the problem to be in the Python API xbmc.gui, not the addon itself (which is just the trigger).

### To Reproduce

1. Install Kodi 18 RC4 Winx64
2. Install Kodi addon ExtendedInfoScript from Kodi repo
3. Add a music source and scan to populate the library
4. Open music library artists node.  Select any artist.
5. Open the musicinfo dialog (Estuary) for the selected artist.  In the dialog select/click "search youtube" button.
6.  YoutubeList.xml dialog opens
7.  Exit the youtubeList dialog (keyboard "back")
8.  Dialog closes / Kodi crashes

### Debuglog

The debuglog can be found here:  https://pastebin.com/8vTkjjwZ

No crash files or stack traces are produced.

I did try to run VS2015 debugger and it seemed to indicate a problem in de-allocating a pointer. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

None needed

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

There's also a problem in script.module.kodi65 where it attempts to open a busy dialog.  That can be fixed for Kodi 18 and it doesn't change the crash behavior at all.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 7 x64 sp1
 - Kodi version:  Kodi (18.0-RC4 Git:20181228-14086a7bd3). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This PR makes sure listitems in a grouplist release the reference to the container/layout before it is destroyed. Right now this occurs too late, making the container pointer invalid when the pointed object is deleted (as a child of a group).
Credits for the proper solution goes to @peak3d. Thanks also to @fritsch and @pkerling for the patience :)

## Motivation and Context
Fix https://github.com/xbmc/xbmc/issues/15226 and make we still have extended.info support in Estuary for v18 (invalidating https://github.com/xbmc/xbmc/pull/15258).

## How Has This Been Tested?
Compiled and tested on osx

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by ronie** [comment]
tested and it works ok on my end. thx!

File: xbmc/guilib/GUIBaseContainer.cpp [hunk 1]
```diff
@@ -58,6 +58,10 @@ CGUIBaseContainer::CGUIBaseContainer(const CGUIBaseContainer &) = default;
 
 CGUIBaseContainer::~CGUIBaseContainer(void)
 {
+  // release the container from items
+  for (auto item :m_items)
```
Comment (pkerling) [inline xbmc/guilib/GUIBaseContainer.cpp]:
```suggestion
  for (auto item : m_items)
```

**Review by yol — COMMENTED** [review]
Looks innocent, but it's *really* hard to say if this will break anything else or not

**Comment by peak3d** [comment]
@pkerling FreeMemory simply removes the Layouts which are used for presenting the listItem.
There is no real risk, because layouts are not a shared resource over GUI control parents

**Comment by MartijnKaijser** [comment]
Shall we merge and see for couple of days?

**Comment by enen92** [comment]
@MartijnKaijser have been using this for a few days and haven't found any regression yet. Peak3d did a lot of rework on GUI for v18 and this fix is proposed by him anyways (as the bug was introduced in his rework PR). I'd say this is safe enough to be merged. We can always revert if justified.
