### PR TITLE
Inputstream fixes

### LINKED ISSUE #27: INPUTSTREAM_INFO::m_flags
There is a new m_flags fiels in INPUTSTREAM_INFO to specify infos for selectionStream.
You may want to initialize it to FLAG_NONE?

https://github.com/xbmc/xbmc/pull/12690

### PR DESCRIPTION
**Pull request by svenfoo**
## Description
The Inputstream class should make sure that the structs it defines are initialized with reasonable default values by their default constructor. Before this change the code relied on users to do the initialization, and not all users actually did this, leading to undefined behavior.
 
## Motivation and Context
This fixes https://github.com/xbmc/inputstream.rtmp/issues/27
**Update:** It doesn't fix it any longer, but it's still a minor cleanup.

## How Has This Been Tested?
I have only compiled this change, not actually tested it.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [] All new and existing tests passed

### CODE REVIEW

File: xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h [hunk 1]
```diff
@@ -67,7 +67,7 @@ extern "C"
     };
 
     /// set of supported capabilities
-    uint32_t m_mask;
+    uint32_t m_mask = 0;
```
Comment (AlwinEsch) [inline xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h]: Here and on other places not match a "C" style for there.
They are thought to use also (in future) as pure "C".

Also some other parts (already before, not from you) are not "C" conform and need improved.

Is already set to 0 here: https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp#L58

Better to extend this be make a `m_caps = {{0}};` to make sure it stays 0 if another part becomes added

File: xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h [hunk 2]
```diff
@@ -240,7 +240,7 @@ extern "C"
       COLORTRC_MAX
     };
 
-    uint32_t m_flags;
+    uint32_t m_flags = STREAM_FLAGS::FLAG_NONE;
```
Comment (AlwinEsch) [inline xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h]: Make for all them here on struct a:
```
INPUTSTREAM props = {{0}};
```
by https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp#L123

**Review by AlwinEsch — CHANGES_REQUESTED** [review]
Thanks a lot to fix the bug. Makes completly sense to make sure to have it 0. Only the hard thing is to hold the "C" by parts where work between Kodi and addon (and to allow pure "C" in future).

Also some other things (not related to this request), like
```
    struct INPUTSTREAM_IDS(__cdecl* get_stream_ids)(const AddonInstance_InputStream* instance);
    struct INPUTSTREAM_INFO(__cdecl* get_stream)(const AddonInstance_InputStream* instance,
                                                 int streamid);
```
are C++ in a C interface and need to be changed in future.

One another way where this problem on addon can be prevented and from my side good to have are the "C" <-> "C++" translator by https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h#L339 (as Note, need inside *=* a fix and currently not work by `=`), currently used on PVR remake request.

File: xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h [hunk 3]
```diff
@@ -138,13 +138,13 @@ extern "C"
       TYPE_AUDIO,
```
Comment (AlwinEsch) [inline xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h]: Set the to `TYPE_NONE = 0,` to confirm is really always 0, also on addon side.

**Comment by svenfoo** [comment]
> Thanks a lot to fix the bug. Makes completly sense to make sure to have it 0. Only the hard thing is to hold the "C" by parts where work between Kodi and addon (and to allow pure "C" in future).

Ah, I didn't realize that, thanks for pointing it out. Then it can not be fixed this way.

**Comment by svenfoo** [comment]
With these changes your comments should be addressed. However xbmc/inputstream.rtmp#27 is not fixed then as the code in the inputstream.rtmp plugin initialises the structs using their default constructors:
```
INPUTSTREAM_IDS CInputStreamRTMP::GetStreamIds()
{
  return INPUTSTREAM_IDS();
}

INPUTSTREAM_INFO CInputStreamRTMP::GetStream(int streamid)
{
  return INPUTSTREAM_INFO();
}
```
I'll make another change in the add-on then.

File: xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h (hunk 2 above)
Comment (svenfoo) [reply xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h]: Sounds good, and I changed it that way. However even though it compiles on my machine (gcc 9.2) the Jenkins build fails on some platforms now, see for example https://jenkins.kodi.tv/job/LINUX-RBPI/15289/console

File: xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h (hunk 3 above)
Comment (svenfoo) [reply xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h]: Done

File: xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h (hunk 2 above)
Comment (svenfoo) [reply xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h]: This is now fixed, all builds are green.

File: xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h (hunk 1 above)
Comment (svenfoo) [reply xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h]: Ok, done as you suggested.

**Comment by svenfoo** [comment]
@AlwinEsch, are there any other changes needed? As far as I can see all your comments have been addressed and this pull request is ready for merge.

**Comment by AlwinEsch** [comment]
Looks good, Thanks a lot!

**Review by AlwinEsch — APPROVED** [review]
