### PR TITLE
[PVR] Fix group manager crash when adding a new group. Closes #16079.

### LINKED ISSUE #16079: Kodi 18.2 crashes when creating new group in PVR iptv simple client
### Describe the bug
Here is a clear and concise description of what the problem is:

 In PVR iptv simple client after the update to Kodi 18.2 in xbox one, android and windows 10 after creating a new group in Group Manager, and adding the first channel Kodi crashes

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After creating the new group before the Kodi 18.2 update i could add as many channels as i needed in pvr simple client.

## Actual Behavior

Now in KOdi 18.2 in android, xbox one and windows 10 as soon as i cick to a channel to be added in a group in pvr simple client Kodi crashes.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
android log : https://pastebin.com/00Vz5Cgh
Windows 10 log: https://pastebin.com/QF2vqnAb

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [x] Windows UWP

 - Operating system version/name:
 - Kodi version:
18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #16079, fallout from #15707.

@Jalle19 good to go. Reason for the crash was `CChannelGroup::m_allChannelsGroup` null deref, because wrong `CChannelGroup` ctor was used in `CPVRChannelGroups::AddGroup`.

### CODE REVIEW

**Review by Jalle19 — APPROVED** [review]

**Comment by ksooo** [comment]
Fixed linker error...

File: xbmc/pvr/channels/PVRChannelGroups.cpp [hunk 1]
```diff
@@ -500,9 +500,8 @@ bool CPVRChannelGroups::AddGroup(const std::string &strName)
     if (!group)
     {
       // create a new group
-      group = CPVRChannelGroupPtr(new CPVRChannelGroup());
-      group->SetRadio(m_bRadio);
-      group->SetGroupName(strName);
+      group.reset(new CPVRChannelGroup(m_bRadio, CPVRChannelGroup::INVALID_GROUP_ID, strName, GetGroupAll()));
```
Comment (thebrid) [inline xbmc/pvr/channels/PVRChannelGroups.cpp]: Consider replacing this with `std::make_shared`:

```c++
group = std::make_shared<CPVRChannelGroup>(m_bRadio, CPVRChannelGroup::INVALID_GROUP_ID, strName, GetGroupAll());
```

https://clang.llvm.org/extra/clang-tidy/checks/modernize-make-shared.html

Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroups.cpp]: Had that, resulted in linker error foe `CPVRChannelGroup::INVALID_GROUP_ID` on some platforms.

If you tell me how to solve the linker error I will be happy to change back to `std::make_shared`.

Comment (thebrid) [reply xbmc/pvr/channels/PVRChannelGroups.cpp]: That's a weird one! I'm happy to follow up after merging.

Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroups.cpp]: Error details: https://jenkins.kodi.tv/view/Automation/job/BuildMulti-PR/12067/
