### PR TITLE
[Video] Fix episode thumbs not found if using local art.

### LINKED ISSUE #27130: [Bug] Local NFO and assets are ignored when adding a new series
**Description:**
I just added a new TV series with WITHOUT AN INTERNET CONNECTION, which was already complete with NFO, poster and thumbnails, etc. (via export from another external Windows Kodi app)

Nevertheless, Kodi tried to load all assets from the internet and then did not display the thumbnails for the episodes, even though they are also available locally, as are the NFO and all other assets.

**Expectation:**
If all the necessary assets and the NFO file for a series and all episodes are available locally on the NAS by exporting them from another Kodi app, then it should be possible to add them even without an Internet connection, or at least all local assets should be preferred, loaded and displayed.

**Information:**
Kodi used: KodiSetup-20250801-1e952fc2-master-x64.exe
OS: Windows 11

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Only look for episode specific -SxxEyy art if multi-episode media file.

## Motivation and context

When importing episode art looked for -SxxEyy on art filename even if not a multi-episode file.

Fix #27130.

## How has this been tested?

In bug report and on slack.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by 78andyp** [comment]
@KarellenX - as requested.

File: xbmc/video/VideoInfoScanner.cpp [hunk 1]
```diff
@@ -2161,8 +2161,11 @@ CVideoInfoScanner::~CVideoInfoScanner()
 
         std::string path;
         if (content == ContentType::TVSHOWS)
-          path = ART::GetLocalArtBaseFilename(*pItem, useFolder,
-                                              ART::AdditionalIdentifiers::SEASON_AND_EPISODE);
+          path =
+              ART::GetLocalArtBaseFilename(*pItem, useFolder,
+                                           pItem->GetProperty("multiple_episodes").asBoolean(false)
```
Comment (garbear) [inline xbmc/video/VideoInfoScanner.cpp]: Can the magic string be dealt with better? No big issue if that's not for this fix.

Comment (78andyp) [reply xbmc/video/VideoInfoScanner.cpp]: Not easily I don't think. Either adding another parameter to AddVideo() and GetArtwork() or adding another module level variable into FileItem - unless you can think of another way. I quite like the ability to add custom properties - it seems tidier than function parameters for niche cases - what is preferred??

Comment (garbear) [reply xbmc/video/VideoInfoScanner.cpp]: Ideally, the less magic strings, the better and safer. But that can be out of scope of this PR.

Comment (78andyp) [reply xbmc/video/VideoInfoScanner.cpp]: Is it better to have more function parameters then??

File: xbmc/video/VideoInfoScanner.cpp [hunk 2]
```diff
@@ -2337,6 +2340,11 @@ CVideoInfoScanner::~CVideoInfoScanner()
         {
           item.GetVideoInfoTag()->m_iEpisode = file->iEpisode;
           item.GetVideoInfoTag()->m_iSeason = file->iSeason;
+
+          // Add flag if multi-episode file
+          if (std::ranges::count_if(files, [&file](const EPISODE& e)
+                                    { return e.strPath == file->strPath; }) > 1)
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/video/VideoInfoScanner.cpp]: Done

**Comment by 78andyp** [comment]
Force push for Copilot suggestion.

File: xbmc/video/VideoInfoScanner.cpp (hunk 1 above)
Comment (garbear) [reply xbmc/video/VideoInfoScanner.cpp]: How do you mean? The parameter count should stay the same, it's only the strings that would be defined centrally and replaced with constants.

Comment (78andyp) [reply xbmc/video/VideoInfoScanner.cpp]: Apologies - i thought you meant not use SetProperty at all. You mean define `"multiple_episodes"` as a const. Will do.

Comment (78andyp) [reply xbmc/video/VideoInfoScanner.cpp]: Done

**Comment by 78andyp** [comment]
Unless there are any objections I will merge this. Has been confirmed working x2.
