### PR TITLE
[PVR] Reminders: Show reminder dialogs only when GUI is fully initialized / user has logged in

### LINKED ISSUE #18006: [PVR] Reminder feature: Stuck at startup.xml
## Bug report
If a PVR reminder has been set and you startup Kodi at the time when it kicks in,  Kodi will be stucked at `startup.xml` and won't switch to the defined `System.StartupWindow`

### Describe the bug
This is caused by the reminder dialog. 
The very first active window in Kodi is always `startup.xml` and usually there is only a `ReplaceWindow($INFO[System.StartupWindow])`in there. But since the reminder dialog pops in, any `ReplaceWindow()` or `ActivateWindow()` is blocked because of the modal dialog. 
If you press `Cancel` on the reminder, Kodi will be stucked on `startup.xml`. 

Here's a video:
https://www.youtube.com/watch?v=fUFoxtIqNmA

## Expected Behavior
Don't show a reminder dialog during the Kodi startup or login process.

## Actual Behavior
Reminder is kicking in as soon as the PVR stuff is loaded, which is going to happen right at the Kodi startup.

## Possible Fix
Don't show the reminder dialog while `startup.xml` and `loginscreen.xml` is active.
Plus:
Since a lot of skins are using own skin setup or startup routines with custom windows I suggest to delay the reminder dialog if the Kodi uptime is below 30s. This should be enough to bypass any other unexpected skin behaviours or skinshortcuts menu generations to win the race condition.

### To Reproduce
- Set a reminder for a EPG item that is going to start in a few minutes
- Close Kodi an wait until the selected show is live
- Start Kodi

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/abixeveyow.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: matrix master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #18006 

[PVR] Show reminder dialogs only when GUI is fully initialized / user has logged in.

Runtime-tested by me on latest master, on Android and macOS.
Fix confirmed working by issue submitter @sualfred 

@phunkyfish do you have some time for a code review?

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
Looks good

File: xbmc/ServiceManager.cpp [hunk 1]
```diff
@@ -177,7 +177,10 @@ bool CServiceManager::InitStageThree(const std::shared_ptr<CProfileManager>& pro
     *profileManager));
 
   m_contextMenuManager->Init();
-  m_PVRManager->Init();
+
+  // Init PVR manager after login, not already on login screen
+  if (!profileManager->UsingLoginScreen())
```
Comment (garbear) [inline xbmc/ServiceManager.cpp:182]: Does this cause `m_PVRManager->Init();` to never be called if login screen is in use?

Comment (ksooo) [reply xbmc/ServiceManager.cpp:182]: In this case it will be called from `CProfileManager::FinalizeLoadProfile()`
