### PR TITLE
DNSNameCache: Add a Time To Live for cached names

### LINKED ISSUE #26487: Accessing a .local hostname via SMB results in Kodi trying to access an old (cached?) IP address
### Describe the bug
Here is a clear and concise description of what the problem is:

My smb server is at `raspberrypi.local` which resolves to `192.168.0.1` for other programs on the system (e.g. `ping`) and with `avahi-resolve-host-name`. Kodi resolves it to its old address 192.168.0.5 when accessing the path `smb://raspberrypi.local`, and throws a "no route to host" message on the screen. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect Kodi to actually look up the host names that I use, every time I use them. Instead it appears to cache them, which makes the .local indirection pointless. My impression at least is that .local addresses are used in private networks to help locate devices who get assigned addresses dynamically, and whose addresses therefore shouldn't be assumed to stay static. 

## Actual Behavior

No route to host, since it's trying to access a non-existent ip address. 

## Possible Fix

Don't cache host name lookups — look them up when accessed. 

### To Reproduce

I don't know, since it happens mainly when a host has changed its ip address and I haven't yet had time to test it, but I imagine something like this:

1. Set up smb server with some ip address and a .local mDNS host name. 
2. Access it using its mDNS host name in Kodi on separate machine. 
3. Change server's ip address. 
4. Repeat # 2 and get an error. 
5. Confirm other programs on the Kodi machine can resolve the address correctly. `ping` and `avahi-resolve-host-name` should suffice (they use different mechanisms apparently). 

### Debuglog

The debuglog can be found here:

Will have to be uploaded in a later edit. 

This problem has only happened spontaneously and I only have a standard log until the time I can reproduce it with debug logging active. This standard log will simply confirm that Kodi is trying to access `smb://USERNAME:PASSWORD@192.168.0.5/` when I ask for `smb://raspberrypi.local/`. 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

This problem can always be worked around by restarting Kodi to presumably reset its erroneous caching of host name lookups. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Debian testing (13/Trixie) 32 bit

 - Kodi version:
21.2 from Debian

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by neo1973**
## Description

So far the IP of the first successful lookup has been used indefinitely. This PR adds a TTL of 60 seconds for dynamically looked up hostnames and an infinity TTL for static names from the advancedsettings.xml. 60 seconds has been choosen as Firefox uses the same value for its DNS cache.

## Motivation and context

Fixes #26487.

## How has this been tested?

Verified the behavior with a debugger for dynamic and permanent cache entries.

## What is the effect on users?

Kodi uses the correct IPs if the IP for a host changes.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

File: xbmc/network/DNSNameCache.h [hunk 1]
```diff
@@ -8,27 +8,65 @@
...
   static bool Lookup(const std::string& strHostName, std::string& strIpAddress);
 
-protected:
-  static CCriticalSection m_critical;
-  std::vector<CDNSName> m_vecDNSNames;
+private:
+  CDNSNameCache() = default;
+
+  static constexpr std::chrono::seconds TTL{60};
+  static CDNSNameCache _instance;
```
Comment (ksooo) [inline xbmc/network/DNSNameCache.h:60]: https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#member-variables

`_instance`-> `ms_instance`

File: xbmc/network/DNSNameCache.h [hunk 2]
```diff
@@ -8,27 +8,65 @@
...
   static bool Lookup(const std::string& strHostName, std::string& strIpAddress);
 
-protected:
-  static CCriticalSection m_critical;
-  std::vector<CDNSName> m_vecDNSNames;
+private:
+  CDNSNameCache() = default;
+
+  static constexpr std::chrono::seconds TTL{60};
+  static CDNSNameCache ms_instance;
```
Comment (ksooo) [inline xbmc/network/DNSNameCache.h:60]: Shouldn't this rather be a `CServiceBroker` component, to be able to control instance's live time? I thought we agreed not to introduce new globals...

File: xbmc/network/DNSNameCache.h [hunk 3]
```diff
@@ -40,7 +40,7 @@ class CDNSNameCache final
    *
    * \return true if the IP is cached
    */
-  static bool GetCached(const std::string& strHostName, std::string& strIpAddress);
+  bool GetCached(const std::string& strHostName, std::string& strIpAddress);
```
Comment (ksooo) [inline xbmc/network/DNSNameCache.h:43]: Could this member function be `const`now?

File: xbmc/network/DNSNameCache.h [hunk 4]
```diff
@@ -51,13 +51,10 @@ class CDNSNameCache final
    *
    * \return true if the IP is cached or the DNS query was successful
    */
-  static bool Lookup(const std::string& strHostName, std::string& strIpAddress);
+  bool Lookup(const std::string& strHostName, std::string& strIpAddress);
```
Comment (ksooo) [inline xbmc/network/DNSNameCache.h:54]: Could this member function be `const`now?

File: xbmc/network/DNSNameCache.h (hunk 3 above)
Comment (neo1973) [reply xbmc/network/DNSNameCache.h:43]: Only if I make `m_hostToIp` `mutable`.

File: xbmc/network/DNSNameCache.h (hunk 4 above)
Comment (neo1973) [reply xbmc/network/DNSNameCache.h:54]: Only if I make `m_hostToIp` `mutable`. And even then it's questionable as this function changes the state of the object:
```
cache.GetCached("example.com", ...); // fails
cache.Lookup("example.com", ...); // succeeds
cache.GetCached("example.com", ...); // now succeeds despite only calling `const` functions
```

Comment (neo1973) [reply xbmc/network/DNSNameCache.h:54]: Correct, but this isn't logical const. The contract for const is that if I only call const functions, then they should behave identical no matter how often or in which order they are called. This isn't the case here. But for `GetCached` it would be OK.

(At least that's my understanding :slightly_smiling_face:)

Comment (ksooo) [reply xbmc/network/DNSNameCache.h:54]: https://stackoverflow.com/questions/3830367/difference-between-logical-and-physical-const-ness

There is exactly the cache lookup case mentioned for good use of a mutable class member: "A mutable class member can be modified even if the class object itself (or the reference or pointer used to access it) is const. Examples of good uses of this are a mutex that must be locked during a read operation, and a cache to store the result of an expensive read operation. In both cases, the operation itself should be a const function (since it doesn't affect the visible state of the object)..."

But no hard feelings, as this can for sure be seen from different perspectives.

**Comment by neo1973** [comment]
Merged after quick chat with @ksooo @ devcon.
