### PR TITLE
[FileSystem][POSIX] Fix SMB passwordless access (POSIX client - Windows server)

### LINKED ISSUE #18832: Does not connect to passwordless Windows 10 SMB share
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi v19 beta 1 for Android does not connect to unpassworded Windows 10 share that Kodi v18.9 for Android connected to just fine. Kodi v19 beta 1 for Windows, on the other hand, connects to the same unpassworded Windows 10 SMB share just fine. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I expect Kodi v19 beta 1 for Android to connect to a share that I was able to connect to with Kodi v18.9 for Android. 

## Actual Behavior

Kodi v19 beta 1 for Android does not connect to that SMB share (not permitted), while Kodi v19 beta 1 for Windows does. 

## Possible Fix

No clue how to fix. 

### To Reproduce

1. Set up unpassworded Windows 10 SMB share according to this guide: https://forum.kodi.tv/showthread.php?tid=353532
2. Try to connect to it with Kodi v18.9 for Android and see that it connects just fine. 
3. Try to connect to it with Kodi v19 beta 1 for Android and see you cannot connect (not permitted error)
4. Kodi v19 beta 1 for Windows can connect to unpassworded Windows 10 shares but the Android port cannot. 

### Debuglog

From a Samsung Android 10 tablet: http://paste.kodi.tv/onijicewaj

### Screenshots 
Here are some links or screenshots to help explain the problem:

None

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

None

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: compared v18.9 to v19b1
 - Used with Android 9, Android 10, and a Windows 10 unpassworded SMB share.
 - Tested on Moto G7, Samsung Android 10 tablet, FireTV 4K, and 2 Windows 10 PCs.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Fix passwordless access (POSIX client - Windows server)

Fix https://github.com/xbmc/xbmc/issues/18832

## Motivation and context
SMB passwordless still (semi-broken) in some cases:

|  Client (Kodi) | Server   |  current state
|---|---|:---:|
|  Windows  | Windows  |  works |  
| Windows  |  Linux based |  works |
|  Android  |  Linux based |  works  |
|  Android  |  Windows |  semi-broken  |

* semi-broken = access is possible but user needs enter guest/1234

This PR fixes Android/Windows case.

NOTE: this PR is similar to https://github.com/xbmc/xbmc/pull/19599 which fixed the same thing for Windows only.
 
## How has this been tested?
- Tested in Shield with Windows 11 24H2 as SMB server.
- Tested also on Windows 10 22H2 based server.
- Tested on Synology NAS server to test no regressions in other cases.

Before --> prompts for user/password
After --> direct access without prompt and no needed store passwords in `passwords.xml`

## What is the effect on users?
Allow access to SMB share without prompt for user/password (only if Windows server is properly configured).

This works on Windows 11 **24H2** using SMBv3.

Is need turn Off "Password protected sharing" in Advanced network settings > Advanced sharing settings > All networks:

Screenshot 2025-01-18 091442

And in a shared folders Add "guest" or "everyone" user permissions.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/platform/posix/filesystem/SMBDirectory.cpp [hunk 1]
```diff
@@ -259,11 +259,22 @@ int CSMBDirectory::Open(const CURL &url)
...
+  bool guest = false;
 
   /* make a writeable copy */
   CURL urlIn = CSMB::GetResolvedUrl(url);
 
   CPasswordManager::GetInstance().AuthenticateURL(urlIn);
+
+  // set the username to "guest" when not provided user/pass
+  // which is required for passwordless or everyone access
+  if (urlIn.GetUserName().empty() && urlIn.GetPassWord().empty())
```
Comment (arnova) [inline xbmc/platform/posix/filesystem/SMBDirectory.cpp:271]: Perhaps only check for empty username?

**Review by arnova — COMMENTED** [review]
I'm ok with the rest, which is fairly straightforward.

**Review by arnova — APPROVED** [review]

**Comment by dbyoung720** [comment]
kodi-22.0-Piers_beta2-armeabi-v7a
Under Windows Network (SMB), the computer name can indeed be seen, but it cannot be clicked to access.
I manually added the SMB network, but it prompted that the network could not be connected.
Windows SMB is completely useless.
I had to revert back to version 21.3. Although it does have a login box.
