### PR TITLE
[Android] Fix AFR not working after standby/wake cycle

### LINKED ISSUE #26393: [Android TV/Kodi 21.2] Adjust display refresh rate stops working after turning off the TV or putting android box to sleep and turning it on again
### Describe the bug
Here is a clear and concise description of what the problem is:

After turning the TV off or putting the device to sleep and then waking up again, adjust display refresh rate doesn't work anymore.  It works fine up to that point. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Adjust display refresh rate should switch refresh rate automatically even after device goes to standby/then wakes up or doing the same by turning off the tv and turning back on (hdmi cec). 

## Actual Behavior

It doesn't switch refresh rate automatically anymore

## Possible Fix

Killing kodi and restarting it fixes the problem 

### To Reproduce

1.  Start kodi
2.  Put android box to standby or turn off the tv (hdmi cec  puts the system to standby)
3.  Wake the system or turn on the tv, go to kodi again and play something, auto refresh rate doesn't work anymore

### Debuglog

The debuglog can be found here:  

[kodi.log](https://github.com/user-attachments/files/18708558/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:  Android TV 14, Android TV 12, Android TV 11
 - Kodi version:     21.2, 21.1, 21.0 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fritsch**
See: #27892 

I was asked to carry the fix over.

### CODE REVIEW

File: xbmc/windowing/android/WinSystemAndroid.cpp [hunk 1]
```diff
@@ -127,6 +127,13 @@ bool CWinSystemAndroid::CreateNewWindow(const std::string& name,
     return false;
   }
 
+  if (m_dispModesUpdatePending)
+  {
+    CLog::Log(LOGDEBUG, "CWinSystemAndroid::CreateNewWindow: display modes update was pending, refreshing resolutions");
```
Comment (thexai) [inline xbmc/windowing/android/WinSystemAndroid.cpp]:
```suggestion
    CLog::LogF(LOGDEBUG, "display modes update was pending, refreshing resolutions");
```

**Review by thexai — APPROVED** [review]
I don't have an Android 14 device to test it on, but the fix is simple and already confirmed is working in https://github.com/xbmc/xbmc/pull/27892#issuecomment-3939188001
