### PR TITLE
[macOS] Only disable GUI rendering if the window is not visible

### LINKED ISSUE #27435: macOS ARM64 — Video freezes when Kodi loses focus (audio continues) since build 10687; last working = 10461
Platform: macOS Tahoe (ARM64, Apple Silicon)
Kodi versions tested:
 - kodi-20250929-c1dea33a-master-10461-arm64 ✅ works (video continues)
 - kodi-master-10687-arm64 ❌ video freezes when window loses focus
Steps to reproduce:
 1. Play any local or streaming video.
 2. Switch focus to another macOS app (e.g. Safari).
 3. Audio continues, video stops updating until focus returns.
Settings tested:
 - Windowed / windowed fullscreen
 - Hardware acceleration (VideoToolbox) ON/OFF
 - advancedsettings.xml <backgroundpause>false</backgroundpause>
Same behavior in all cases.
Logs show no decoding errors, but render loop halts on focus loss.

### PR DESCRIPTION
**Pull request by enen92**
## Description
https://github.com/xbmc/xbmc/pull/27273 disabled GUI rendering whenever the window resigns its key window state (gets unfocused). However, it doesn't make sense since the application/window may still be visible and actually playing video content - it's just not the key window. Instead, disable GUI rendering when the window actually gets completely occluded and enable GUI rendering when it's partially visible.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/27435 

## How has this been tested?
Runtime tested by checking the CPU load in xcode while playing a video (window occluded, window partially visible, etc).

## What is the effect on users?
They should now be able to have Kodi rendering if the window is visible. CPU load reduced if the window is not visible.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by enen92** [comment]
@claude please review the last revision

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm [hunk 1]
```diff
@@ -116,7 +116,7 @@ - (void)windowDidBecomeKey:(NSNotification*)aNotification
   g_application.m_AppFocused = true;
   CServiceBroker::GetAnnouncementManager()->Announce(ANNOUNCEMENT::GUI, "WindowFocused");
 
-  EnableRenderGUI(true);
+  EnableRenderGUI(self.window.occlusionState & NSWindowOcclusionStateVisible);
```
Comment (kambala-decapitator) [inline xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: extracting this bool expression to a method would be better I think

**Review by kambala-decapitator — APPROVED** [review]
can't comment on the occlusion thing, but I also noticed this bug

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm (hunk 1 above)
Comment (enen92) [reply xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: you're right. Done on the last revision. Can you take a look whenever possible?

**Review by kambala-decapitator — APPROVED** [review]

**Comment by enen92** [comment]
Jenkins build and merge
