### PR TITLE
[GUIWindowVideoBase] Fix wrong item data pointer

### LINKED ISSUE #23502: STRM Playlist regression(!?) on current master branch, playback dont start
### Describe the bug
Here is a clear and concise description of what the problem is:

This is a fake STRM just for test purpose
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
https://www.dropbox.com/s/p0dq75hf05s2szc/segtimeline_live_ast.mpd?dl=1
```
usually i play it in this way
1) add the strm to a folder
2) add the folder to favourites
3) go to kodi main menu Favourites, open the folder, play the STRM

this now dont works anymore and print
`PLAYLIST::CPlayListPlayer::Play: ListItem type must be audio or video type. The type can be specified by using ListItem::getVideoInfoTag or ListItem::getMusicInfoTag, in the case of playlist entries by adding #KODIPROP mimetype value.`

where old nightlies run ISAdaptive (without play content because its fake)

this use case seem broken starting from PR #23460

## Possible Fix

i have seen something weird around here
i havent test i do not know if this is intentional
https://github.com/ksooo/xbmc/blob/master/xbmc/video/windows/GUIWindowVideoBase.cpp#L1083-L1096
there is a CFileItem copy but GetPlaylistPlayer().Play use the Ptr one that should have properties unchanged

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/dufafepiwe.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: master branch 1c65bbbe61e3dfb4b832d3baa431001551bf7520

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

PR #23474 has omitted the copy of `CFileItem` and then all change made to properties are lost, that breaks STRM playback

## Motivation and context

fix #23502
## How has this been tested?

play STRM from favourites menu directly and within a folder
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/video/windows/GUIWindowVideoBase.cpp [hunk 1]
```diff
@@ -1080,20 +1080,21 @@ bool CGUIWindowVideoBase::OnPlayMedia(int iItem, const std::string &player)
   CServiceBroker::GetPlaylistPlayer().Reset();
   CServiceBroker::GetPlaylistPlayer().SetCurrentPlaylist(PLAYLIST::TYPE_NONE);
 
-  CFileItem item(*pItem);
+  CFileItemPtr pItemCopy = std::make_shared<CFileItem>(*pItem);
```
Comment (lrusak) [inline xbmc/video/windows/GUIWindowVideoBase.cpp:1083]: I think there is a `Clone()` method available.

Also, no `p` prefixes.

File: xbmc/video/windows/GUIWindowVideoBase.cpp [hunk 2]
```diff
@@ -1080,20 +1080,21 @@ bool CGUIWindowVideoBase::OnPlayMedia(int iItem, const std::string &player)
...
+  CLog::Log(LOGDEBUG, "{} {}", __FUNCTION__, CURL::GetRedacted(pItemCopy->GetPath()));
 
-  item.SetProperty("playlist_type_hint", m_guiState->GetPlaylist());
+  pItemCopy->SetProperty("playlist_type_hint", m_guiState->GetPlaylist());
 
   if (m_thumbLoader.IsLoading())
     m_thumbLoader.StopAsync();
 
-  CServiceBroker::GetPlaylistPlayer().Play(pItem, player);
+  CServiceBroker::GetPlaylistPlayer().Play(pItemCopy, player);
```
Comment (ksooo) [inline xbmc/video/windows/GUIWindowVideoBase.cpp:1097]: Although your fix is correct, I think the fix can look a bit simpler. The only line that needs to be changed to fix the issue is this one. Replace ‚pItem‘ with ‚std::make_shared<CFileItem>(&item)‘.

Comment (ksooo) [reply xbmc/video/windows/GUIWindowVideoBase.cpp:1097]: On second thought, your approach is better than what I suggested, because my suggestion would introduce a second copy.

File: xbmc/video/windows/GUIWindowVideoBase.cpp (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/video/windows/GUIWindowVideoBase.cpp]: yes there is but is not needed on make_shared CFileItem constructor that want the CFileItem reference

File: xbmc/video/windows/GUIWindowVideoBase.cpp [hunk 3]
```diff
@@ -1080,20 +1080,21 @@ bool CGUIWindowVideoBase::OnPlayMedia(int iItem, const std::string &player)
   CServiceBroker::GetPlaylistPlayer().Reset();
   CServiceBroker::GetPlaylistPlayer().SetCurrentPlaylist(PLAYLIST::TYPE_NONE);
 
-  CFileItem item(*pItem);
+  CFileItemPtr itemCopy = std::make_shared<CFileItem>(*pItem);
```
Comment (ksooo) [inline xbmc/video/windows/GUIWindowVideoBase.cpp:1083]: This could be a `const CFileItemPtr`, right?

File: xbmc/video/windows/GUIWindowVideoBase.cpp [hunk 4]
```diff
@@ -1080,20 +1080,21 @@ bool CGUIWindowVideoBase::OnPlayMedia(int iItem, const std::string &player)
   CServiceBroker::GetPlaylistPlayer().Reset();
   CServiceBroker::GetPlaylistPlayer().SetCurrentPlaylist(PLAYLIST::TYPE_NONE);
 
-  CFileItem item(*pItem);
+  const CFileItemPtr itemCopy = std::make_shared<CFileItem>(*pItem);
```
Comment (enen92) [inline xbmc/video/windows/GUIWindowVideoBase.cpp:1083]: Iirc there was a desire to kill cfileitemptr. Can you please use auto here since it is implicit from the constructor?
In other places you'd write the actual type instead of the typedef but here it's one of those places where auto would suffice.

**Review by enen92 — APPROVED** [review]

**Review by ksooo — APPROVED** [review]

**Comment by CastagnaIT** [comment]
jenkins build and merge this please
