### PR TITLE
[pvr] always add new members to group at end in group manager

### LINKED ISSUE #17324: PVR: regression: Wrong channel numbers in groups
### Describe the bug

Channels have the same numbers in all groups. There is no way to set them for any group (other than `All Channels`).

## Expected Behavior

There should be a way to set channel numbers for groups independently.
That behavior was in Krypton.
In Group Manager, channel were added to the end of the group and take sequential numbers, starting from 1. That way user could manage channel numbers in groups. 

## Actual Behavior

Wherever channel is added to the group in Group Manager, it keeps it's number and position from `All Channels` group and there is no way to change it. 

## Possible Fix

Restore previous behavior. At least, make it optional.

### To Reproduce

1. Install any PVR addon, e.g PVR Demo.
2. in [Settings/TV/General](https://kodi.wiki/view/Settings/TV/General), TURN OFF both options below:
- [Use channel order from backend(s)]( https://kodi.wiki/view/Settings/TV/General#Use_channel_order_from_the_backend.28s.29)
- [Use channels number from backend](https://kodi.wiki/view/Settings/TV/General#Use_channels_number_from_backend)
3. Go to [Group manager](https://kodi.wiki/view/Settings/TV/General#Group_manager), add some random channels to any group.
4. The channels get added with the same numbers and order they had in "All Channels" group (effectively, when they were ungrouped). There is no way to change that. (see screenshots)

### Debuglog

The debuglog can be found here:
http://sprunge.us/yqaXZw

### Screenshots 

Leia, wrong numbering in Group #3
screenshot000
Krypton, right numbering
image

## Additional context or screenshots (if appropriate)

If group's channel numbers are changed in the database directly (from external program), they are overwritten by Kodi with those fake numbers. So the user's data from e.g previous Kodi version are just lost.

#16593

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Leia

@ksooo @phunkyfish @Leatherface75

### PR DESCRIPTION
**Pull request by phunkyfish**
## Description

Always add new channels to groups at the end in group manager.

## Motivation and Context

Then adding support for group specific channel numbering and numbering from 1  (https://github.com/xbmc/xbmc/pull/16593) logic was missed in the group manager GUI. 

Fixes: https://github.com/xbmc/xbmc/issues/17324

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by phunkyfish** [comment]
@ksooo are you ok with the logic being in this class or would you prefer the max channel number is returned from the groups class?

**Comment by ksooo** [comment]
> would you prefer the max channel number is returned from the groups class?

 yes. :-)

**Comment by ksooo** [comment]
Add a new method? => `CPVRChannelGroup::AppendToGroup(…)`

**Comment by ksooo** [comment]
Looking at the documentation of `CPVRChannelGroup::AddToGroup` it seems, that this method's implementation needs to be fixed.

https://github.com/xbmc/xbmc/blob/master/xbmc/pvr/channels/PVRChannelGroup.h#L153

=> `@param channelNumber The channel number of the channel to add. Use empty channel number to add it at the end.`

File: xbmc/pvr/channels/PVRChannelGroup.cpp [hunk 1]
```diff
@@ -714,6 +714,20 @@ bool CPVRChannelGroup::AddToGroup(const std::shared_ptr<CPVRChannel>& channel, c
   return bReturn;
 }
 
+bool CPVRChannelGroup::AppendToGroup(const std::shared_ptr<CPVRChannel>& channel)
+{
+  CSingleLock lock(m_critSection);
+
+  unsigned int channelNumberMax = 0;
+  for (const auto member : GetMembers())
```
Comment (ksooo) [inline xbmc/pvr/channels/PVRChannelGroup.cpp]: `GetMembers()` creates a copy of `m_sortedMembers`.

I would go for `for (const auto& memberPair : m_members)` to avoid the copy. Or, if you actually need `m_sortedMembers`, access it directly.

Comment (phunkyfish) [reply xbmc/pvr/channels/PVRChannelGroup.cpp]: My bad, should have seen that.

File: xbmc/pvr/channels/PVRChannelGroup.cpp [hunk 2]
```diff
@@ -714,6 +714,20 @@ bool CPVRChannelGroup::AddToGroup(const std::shared_ptr<CPVRChannel>& channel, c
   return bReturn;
 }
 
+bool CPVRChannelGroup::AppendToGroup(const std::shared_ptr<CPVRChannel>& channel)
+{
+  CSingleLock lock(m_critSection);
+
+  unsigned int channelNumberMax = 0;
+  for (const auto member : m_sortedMembers)
```
Comment (ksooo) [inline xbmc/pvr/channels/PVRChannelGroup.cpp]: why not `const auto&`?

Comment (phunkyfish) [reply xbmc/pvr/channels/PVRChannelGroup.cpp]: I think I'm regressing ;)

**Review by ksooo — APPROVED** [review]

**Comment by bam80** [comment]
Thanks guys. Can we just merge it if it works for you, and I'll check when it builds itself tomorrow? Will it work?

**Comment by bam80** [comment]
Still can't check it, the latest nightly is git20200117

**Comment by bam80** [comment]
> Those nightlies are not created by team

Still see it's headed '“Kodi” team' on the Launchpad:
https://launchpad.net/~team-xbmc/+archive/ubuntu/xbmc-nightly?field.series_filter=eoan

>  Kodi Nightly Builds
PPA description
Official Team Kodi nightly builds.
