### PR TITLE
[application] Fix a race condition on CApplicationPlayerCallback::m_itemCurrentFile

### LINKED ISSUE #23247: Heap-use-after-free in CFileItem::UpdateInfo due to race condition on CApplicationPlayerCallback::m_itemCurrentFile
### Describe the bug
There's a race condition on `CApplicationPlayerCallback::m_itemCurrentFile` between two threads. The first thread is the main Kodi thread (where `CApplication::OnMessage` is called), and the second thread is the video player thread (where `CApplicationPlayerCallback::OnPlayBackStarted` is called).

I've confirmed that `m_itemCurrentFile` is accessed from two different contexts by adding following logs:
https://github.com/dobo90/xbmc/commit/d0e4dcf50b1c579443ae86b4242e9542ba5e0201

The crash happens when `GUI_MSG_UPDATE_ITEM` is being handled. `CApplicationPlayerCallback::m_itemCurrentFile` can be accessed concurrently by the main thread in `CApplication::OnMessage` and `CApplicationPlayerCallback::OnPlayBackStarted` in video thread. Sometimes `CApplicationPlayerCallback::OnPlayBackStarted` is called first, resets the `m_itemCurrentFile` (and deallocates the object) and later `CApplication::OnMessage`  tries to access it - this is where crash happens. It's shown in [address sanitizer report](https://paste.kodi.tv/gexokutajo.kodi).

## Expected Behavior
Kodi doesn't crash.

## Actual Behavior
Kodi randomly crashes after switching the live TV channel. On my Raspberry Pi 4 it crashes few times a month (it's a rare crash).

## Possible Fix
A possible fix is implemented inside [that branch](https://github.com/dobo90/xbmc/commits/20.1-Nexus_cfileitem_heap_after_free_fix). I've introduced `GUI_MSG_PLAYBACK_PAUSED`, `GUI_MSG_PLAYBACK_RESUMED`, `GUI_MSG_PLAYBACK_SEEKED` and `GUI_MSG_PLAYBACK_SPEED_CHANGED` messages to make sure that `CApplicationPlayerCallback::m_itemCurrentFile` is accessed only from one context. To be honest I'm not sure whether it's the best solution that's why I'm creating a problem report instead of a pull request.

If the fix is accepted I can open a PR to master branch, split it into the several commits (as it needed to change type from int to int64_t in `CGUIMessage::{Param1,Param2}`. 

### To Reproduce
1. Compile Kodi with address sanitizer enabled (additional options pased to cmake: -DCMAKE_BUILD_TYPE=Debug -DECM_ENABLE_SANITIZERS=address -DENABLE_DEBUGFISSION=FALSE).
2. Prepare some list of TV channels separated into groups (on my side I use IPTV Simple PVR plugin).
3. Run [that script](https://paste.kodi.tv/kagohepema) which randomly switches the TV channels. I've reproduced it twice on my side: for the first time I needed 15 minutes, for the second time about half an hour.

### Debuglog
The debuglog can be found here (it's the address sanitizer report - Kodi debug logs are too big to paste):
https://paste.kodi.tv/gexokutajo.kodi

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Arch Linux (and Arch Linux ARM on Raspberry Pi 4)
 - Kodi version: 20.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by dobo90**
## Description
There's a possibility of a race codition on CApplicationPlayerCallback::m_itemCurrentFile leading to heap-use-after-free reported by the address sanitizer [1].
    
The crash happens when GUI_MSG_UPDATE_ITEM is being handled. CApplicationPlayerCallback::m_itemCurrentFile can be accessed concurrently by the main thread in CApplication::OnMessage and CApplicationPlayerCallback::OnPlayBackStarted in the video thread.

Sometimes CApplicationPlayerCallback::OnPlayBackStarted is called first, resets the m_itemCurrentFile (and deallocates the object). Then CApplication::OnMessage tries to read it - this is where heap-use-after-free occurs.
    
In order to mitigate the issue introduce additional messages GUI_MSG_PLAYBACK_PAUSED, GUI_MSG_PLAYBACK_RESUMED, GUI_MSG_PLAYBACK_PAUSED and GUI_MSG_PLAYBACK_SPEED_CHANGED. Those messages are sent from the GUI thread to the main thread. That way the access to CApplicationPlayerCallback::m_itemCurrentFile is serialized (it will be accessed only from the main thread).

## Motivation and context
It fixes https://github.com/xbmc/xbmc/issues/23247.

## How has this been tested?
Mainly it has been tested on Arch Linux ARM on 20.1. Since 4 months Kodi haven't crashed. Previously it was crashing couple of times a month.

## What is the effect on users?
Kodi shouldn't crash while switching the items.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/application/ApplicationPlayerCallback.cpp [hunk 1]
```diff
@@ -244,17 +221,8 @@ void CApplicationPlayerCallback::OnPlayBackSeek(int64_t iTime, int64_t seekOffse
...
-  JSONRPC::CJSONUtils::MillisecondsToTimeObject(seekOffset, param["player"]["seekoffset"]);
-  param["player"]["playerid"] = CServiceBroker::GetPlaylistPlayer().GetCurrentPlaylist();
-  const auto& components = CServiceBroker::GetAppComponents();
-  const auto appPlayer = components.GetComponent<CApplicationPlayer>();
-  param["player"]["speed"] = static_cast<int>(appPlayer->GetPlaySpeed());
-  CServiceBroker::GetAnnouncementManager()->Announce(ANNOUNCEMENT::Player, "OnSeek",
-                                                     m_itemCurrentFile, param);
-
-  CDataCacheCore::GetInstance().SeekFinished(static_cast<int>(seekOffset));
+  CGUIMessage msg(GUI_MSG_PLAYBACK_SEEKED, 0, 0, iTime, seekOffset);
```
Comment (lrusak) [inline xbmc/application/ApplicationPlayerCallback.cpp:224]: I doubt this needs to be an int64_t, would a uint32_t be enough?

File: xbmc/application/Application.cpp [hunk 2]
```diff
@@ -228,7 +229,9 @@ CApplication::CApplication(void)
     m_Autorun(new CAutorun()),
 #endif
     m_pInertialScrollingHandler(new CInertialScrollingHandler()),
-    m_WaitingExternalCalls(0)
+    m_WaitingExternalCalls(0),
+    m_itemCurrentFile(new CFileItem),
```
Comment (lrusak) [inline xbmc/application/Application.cpp:233]:
```suggestion
    m_itemCurrentFile(std::make_shared<CFileItem>()),
```

File: xbmc/application/Application.cpp [hunk 3]
```diff
@@ -2728,6 +2731,9 @@ bool CApplication::OnMessage(CGUIMessage& message)
       // @TODO move this away to platform code
       CDarwinUtils::SetScheduling(GetComponent<CApplicationPlayer>()->IsPlayingVideo());
 #endif
+      m_itemCurrentFile.reset(new CFileItem(*std::static_pointer_cast<CFileItem>(message.GetItem())));
```
Comment (lrusak) [inline xbmc/application/Application.cpp:2734]:
```suggestion
      m_itemCurrentFile = std::make_shared<CFileItem>(*std::static_pointer_cast<CFileItem>(message.GetItem())));
```

File: xbmc/application/ApplicationPlayerCallback.cpp [hunk 4]
```diff
@@ -77,9 +69,9 @@ void CApplicationPlayerCallback::OnPlayBackStarted(const CFileItem& file)
   auto& components = CServiceBroker::GetAppComponents();
   const auto stackHelper = components.GetComponent<CApplicationStackHelper>();
   if (stackHelper->IsPlayingISOStack() || stackHelper->IsPlayingRegularStack())
-    m_itemCurrentFile.reset(new CFileItem(*stackHelper->GetRegisteredStack(file)));
+    itemCurrentFile.reset(new CFileItem(*stackHelper->GetRegisteredStack(file)));
```
Comment (lrusak) [inline xbmc/application/ApplicationPlayerCallback.cpp:72]:
```suggestion
    itemCurrentFile = std::make_shared<CFileItem>(*stackHelper->GetRegisteredStack(file)));
```

File: xbmc/application/ApplicationPlayerCallback.cpp [hunk 5]
```diff
@@ -77,9 +69,9 @@ void CApplicationPlayerCallback::OnPlayBackStarted(const CFileItem& file)
...
   else
-    m_itemCurrentFile.reset(new CFileItem(file));
+    itemCurrentFile.reset(new CFileItem(file));
```
Comment (lrusak) [inline xbmc/application/ApplicationPlayerCallback.cpp:74]:
```suggestion
    itemCurrentFile = std::make_shared<CFileItem>(file));
```

**Review by lrusak — COMMENTED** [review]
Typically moving code into CApplication isn't the best solution. It's not immediately obvious why you need to do that?

File: xbmc/GUIUserMessages.h [hunk 6]
```diff
@@ -143,3 +143,8 @@ constexpr const int GUI_MSG_PLAYBACK_AVSTARTED      = GUI_MSG_USER + 44;
 // Sent to notify system sleep/wake
 constexpr const int GUI_MSG_SYSTEM_SLEEP  			= GUI_MSG_USER + 45;
 constexpr const int GUI_MSG_SYSTEM_WAKE 			= GUI_MSG_USER + 46;
+
+constexpr const int GUI_MSG_PLAYBACK_PAUSED 		= GUI_MSG_USER + 47;
+constexpr const int GUI_MSG_PLAYBACK_RESUMED 		= GUI_MSG_USER + 48;
+constexpr const int GUI_MSG_PLAYBACK_SEEKED 		= GUI_MSG_USER + 49;
+constexpr const int GUI_MSG_PLAYBACK_SPEED_CHANGED 	= GUI_MSG_USER + 50;
```
Comment (enen92) [inline xbmc/GUIUserMessages.h:150]: Please add an empty line at the end of the file

File: xbmc/application/ApplicationPlayerCallback.cpp [hunk 7]
```diff
@@ -36,28 +35,21 @@
...
-                                                     m_itemCurrentFile, data);
-
   CGUIMessage msg(GUI_MSG_PLAYBACK_ENDED, 0, 0);
   CServiceBroker::GetGUI()->GetWindowManager().SendThreadMessage(msg);
 }
 
 void CApplicationPlayerCallback::OnPlayBackStarted(const CFileItem& file)
 {
   CLog::LogF(LOGDEBUG, "CApplication::OnPlayBackStarted");
+  CFileItemPtr itemCurrentFile;
```
Comment (enen92) [inline xbmc/application/ApplicationPlayerCallback.cpp:52]: Please avoid using the typedef (killing cfileitemptr is on our roadmap)

File: xbmc/application/ApplicationPlayerCallback.cpp (hunk 1 above)
Comment (dobo90) [reply xbmc/application/ApplicationPlayerCallback.cpp:224]: Video player uses uin64_t for both values:
https://github.com/xbmc/xbmc/blob/d3f1d4b10afcff29d4cf49a8f44a49cb24710071/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L3192C2-L3192C2
https://github.com/xbmc/xbmc/blob/d3f1d4b10afcff29d4cf49a8f44a49cb24710071/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L3217C1-L3217C1

**Comment by dobo90** [comment]
> Typically moving code into CApplication isn't the best solution. It's not immediately obvious why you need to do that?

As described in the commit message it's needed because of the race condition on `m_itemCurrentFile`. Sending the messages makes it race free as m_itemCurrentFile is accessed only in the main thread. Another option would be to add locking around `m_itemCurrentFile`.

**Comment by CastagnaIT** [comment]
i tend to agree with current PR changes,
`m_itemCurrentFile` is declared by `CApplicationPlayerCallback` but instead it is used in a lot of methods of `CApplication`,
since `CApplicationPlayerCallback` is called from outside may cause side effects on any of `CApplication` methods
so i think the better place at least for now is move it out from `CApplicationPlayerCallback`

**Comment by dobo90** [comment]
Format changes made by Jenkins are deleted. Running clang-format locally produced a huge diff for me. I've rebased to the current master and I'll wait for the Jenkins to reformat one more time.

File: xbmc/application/ApplicationPlayerCallback.cpp (hunk 1 above)
Comment (garbear) [reply xbmc/application/ApplicationPlayerCallback.cpp:226]: I'm all for changing to int64_t, but this will cause a *lot* of warnings anywhere GetParamX() is currently used in a calculation and assigned to an int. A change to int64_t should probably come with the brush of a fine-toothed comb.

Comment (dobo90) [reply xbmc/application/ApplicationPlayerCallback.cpp:226]: @garbear I understand your concerns. Although casting each value returned from GetParamX() seems to be an excessive task to implement. m_param1 contains values from constant expressions like GUI_MSG_UPDATE_ITEM, ACTION_SELECT_ITEM. Changing their type to int64_t would introduce inconsistency across other message constants.

I've got two proposals. Please let me know if one of them is acceptable to you (to be honest I'm not a huge fan of them but I didn't come up with anything else).

1. 
```
int CGUIMessage::GetParam1() const
{
  return static_cast<int>(m_param1);
}

int64_t CGUIMessage::GetParam1i64() const
{
  return m_param1;
}

int CGUIMessage::GetParam2() const
{
  return static_cast<int>(m_param2);
}

int64_t CGUIMessage::GetParam2i64() const
{
  return m_param2;
}
```

Narrowing conversion happens in getters - there are no code changes needed from the caller perspective.

3. Leave int in m_paramX and use CGUIMessage::SetPointer/GetPointer to send POD like
```
struct
{
  const int64_t iTime;
  const int64_t seekOffset;
};
```

Comment (garbear) [reply xbmc/application/ApplicationPlayerCallback.cpp:226]: Approach 1 looks better (though I would call it `GetParam1AsI64()`).

Approach 2 is certainly creative but let's not extend the use of raw pointers.

Overall the "param1/param2" think is a bit hacky. We could add "param3" and "param4" for 64bit ints but that just makes the problem worse.

I'm fine with Approach 1 but I'm open to other ideas that are less hacky.

**Comment by CrystalP** [comment]
I stumbled on what looks like a rare race in the opposite end of playback: CApplicationPlayerCallback::OnPlayBackEnded(), also in copy of m_itemCurrentFile so the subject of the issue and PR caught my eye.
Haven't read in detail or dug in the race yet though, so maybe not related.

Repro: play a very short video (a few sec) on repeat (playlist->repeat:all). On one computer I get either a crash or screen frozen after 15 minutes or so. Another one takes much longer,

File: xbmc/application/ApplicationPlayerCallback.cpp (hunk 1 above)
Comment (dobo90) [reply xbmc/application/ApplicationPlayerCallback.cpp:226]: I've updated the PR. Now it implements Approach 1.

**Comment by dobo90** [comment]
@CrystalP I believe it's the same issue. Originally I was encountering it on RPi4 while changing TV channels. Then I managed to reproduce it on x64 machine with address sanitizer enabled by invoking a script which randomly swtiches channels.
I've rebased the PR, you can try to check whether it fixes the issue for you.

**Comment by CrystalP** [comment]
Thanks for making the change. I was still concerned about playback stop/end but after looking up some information and some testing it's fine.

**Comment by CrystalP** [comment]
jenkins build this please

File: xbmc/application/ApplicationPlayerCallback.cpp [hunk 8]
```diff
@@ -92,12 +84,10 @@ void CApplicationPlayerCallback::OnPlayBackStarted(const CFileItem& file)
     CServiceBroker::GetJobManager()->PauseJobs();
   }
 
-  CServiceBroker::GetPVRManager().OnPlaybackStarted(*m_itemCurrentFile);
+  CServiceBroker::GetPVRManager().OnPlaybackStarted(*itemCurrentFile);
```
Comment (CrystalP) [inline xbmc/application/ApplicationPlayerCallback.cpp:87]: Maybe move to CApplication like the other calls to GetPVRManager for consistency, but don't know if exact timing of following line ```stackHelper->OnPlayBackStarted(file)``` is important for PVR.

File: xbmc/guilib/GUIMessage.h [hunk 9]
```diff
@@ -365,9 +365,15 @@ class CFileItemList;
...
-  CGUIMessage(int msg, int senderID, int controlID, int param1, int param2, CFileItemList* item);
-  CGUIMessage(int msg, int senderID, int controlID, int param1, int param2, const CGUIListItemPtr &item);
+  CGUIMessage(int dwMsg, int senderID, int controlID, int64_t param1 = 0, int64_t param2 = 0);
+  CGUIMessage(
+      int msg, int senderID, int controlID, int64_t param1, int64_t param2, CFileItemList* item);
+  CGUIMessage(int msg,
+              int senderID,
+              int controlID,
+              int64_t param1,
+              int64_t param2,
```
Comment (garbear) [inline xbmc/guilib/GUIMessage.h:375]: Please add stdint.h inclusion to the header

Comment (CastagnaIT) [reply xbmc/guilib/GUIMessage.h:375]: use c++ header <cstdint>

File: xbmc/application/ApplicationPlayerCallback.cpp (hunk 8 above)
Comment (ksooo) [reply xbmc/application/ApplicationPlayerCallback.cpp:87]: For me it is logically correct to have this call here. We are in ApplicationPlayCallBack and inform the otehr components from here about playback state changes.

Comment (CrystalP) [reply xbmc/application/ApplicationPlayerCallback.cpp:87]: Your call. I was only pointing out the inconsistency with the other PVR calls moved to CApplication.

**Comment by CrystalP** [comment]
Moving m_itemCurrentFile to application may not be the best when considering multiple simultaneous players / streams in the future (for PiP for example). I'll defer to other team members whether it's appropriate, what's on the roadmap, ...

**Comment by CastagnaIT** [comment]
PiP is only a future therory for now,
from what i remember from old discussions to be implemented it needs more kodi core refactors
imo should not block this fix to avoid kodi crashes on playback

**Comment by CrystalP** [comment]
You can merge if you want, my comment wasn't meant to hold this back.

File: xbmc/application/ApplicationPlayerCallback.cpp (hunk 8 above)
Comment (ksooo) [reply xbmc/application/ApplicationPlayerCallback.cpp:87]: @dobo90 i agree to @CrystalP if the other pvr manager calls were moved to `CApplication`, then this one here also should be moved, for consistency.

@CastagnaIT this should be changed before we merge this PR.

Comment (ksooo) [reply xbmc/application/ApplicationPlayerCallback.cpp:87]: What about the call stackHelper->OnPlayBackStarted(file)? I'm missing a bit the consistency here as well? Which callbacks are now done in CApplication and why not all of them? @dobo90 how did you decide what needs to stay here and what has to be moved?

**Comment by ksooo** [comment]
> You can merge if you want, my comment wasn't meant to hold this back.

Before doing this, please read my recent questions/comments in this PR.

File: xbmc/application/ApplicationPlayerCallback.cpp (hunk 8 above)
Comment (dobo90) [reply xbmc/application/ApplicationPlayerCallback.cpp]: @ksooo
It moved also `CServiceBroker::GetPVRManager().OnPlaybackStarted`.

Regarding stackHelper: personally I don't like how it's designed but I believe it shouldn't crash the application if it's accessed from different threads. It relies on the fact that CApplicationStackHelper::m_currentStack (CFileItemList) is thread safe which is assured by CFileItemList::m_lock. CApplicationStackHelper also uses separate critical section in CApplicationStackHelper::OnPlayBackStart - probably it should be extended to other methods of that class. But I don't think it should be done as a scope of this PR. This PR makes sure that members of CApplicationPlayerCallback are race free (because they were moved to CApplication).

Regarding what needs to be moved from CApplicationPlayerCallback to CApplication. CVideoPlayer invokes methods from CVideoPlayer::m_callback in different contexts, for example:
```
      IPlayerCallback *cb = &m_callback;
      m_outboundEvents->Submit([=]() {
        cb->OnAVChange();
      });
```
Every method of CApplicationPlayerCallback should be thread safe. The rule of thumb is to get rid of all members of CApplicationPlayerCallback and access them in CApplication. This makes CApplicationPlayerCallback transfer control flow to the main thread.

**Comment by CastagnaIT** [comment]
@ksooo changes done, if you have a chance take another look

jenkins build this please

**Review by CastagnaIT — APPROVED** [review]
jenkins build this please

**Comment by CastagnaIT** [comment]
jenkins build this please
