### PR TITLE
[Subtitles] Always use frame margins with native ass

### LINKED ISSUE #21860: [Kodi20] The position of ASS\SSA subtitle cannot be set to the bottom of video
### Describe the bug
Here is a clear and concise description of what the problem is:

After I upgrade to Kodi20, the position of ASS\SSA subtitle cannot be set to the bottom of video, it seems that `Position of screen` option is not working, it will always be the bottom of screen. Kodi19 is working fine.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The position of ASS\SSA subtitle can be set to the bottom of video or the bottom of screen.

## Actual Behavior

The position of ASS\SSA subtitle can only display at the bottom of screen.

## Possible Fix

The subtitle position can be overwritten, and we can adjust it manually, but this will cause some bilingual subtitles to work abnormally.

### To Reproduce

1. Prepare a movie with ASS subtitles and will be black edges.
2. Play it.

### Debuglog

The debuglog can be found here:
[Log of ASS subtitles](https://github.com/xbmc/xbmc/files/9567849/kodi.old.log)
[Log of bilingual subtitles](https://github.com/xbmc/xbmc/files/9567978/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

#### Kodi 20, `Position of screen` is set to `bottom of video`:
sub1
sub2
#### Correct position from VLC (Kodi19 is same):
sub3
sub4
#### Overwritten the position will cause some bilingual subtitles to work abnormally:
incorrect bilingual subtitles
#### Correct bilingual subtitles:
correct bilingual subtitles

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I use Kodi on Windows and Android. Both of them have this problem. I think that the Kodi20 of all platforms may be the same.
Test file: [ASS Test Video.zip](https://github.com/xbmc/xbmc/files/9574318/ASSTestVideo.zip)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows11, Android11
 - Kodi version: Kodi20 Alpha3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

A recent regression there are so much use cases to consider

This change make by default framemargins enabled when native ass/ssa subtitle are used without override settings enabled,
instead when override settings are enabled the framemargins will be enabled only with subtitle position "bottom/top of video"

to test with cropped video

~i will provide a test build to the user to have a confirmation~
confirmed

## Motivation and context

Fix #21860

## How has this been tested?

User have provided sample video/subtitle on #21860

## What is the effect on users?

Right subtitle position

## Screenshots (if appropriate):
Before
immagine

After
immagine

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 1]
```diff
@@ -292,7 +292,8 @@ ASS_Image* CDVDSubtitlesLibass::RenderImage(double pts,
   {
     ass_set_storage_size(m_renderer, static_cast<int>(opts.sourceWidth),
                          static_cast<int>(opts.sourceHeight));
-    useFrameMargins = opts.marginsMode != MarginsMode::DISABLED;
+    useFrameMargins =
+        opts.marginsMode == MarginsMode::DISABLED || opts.marginsMode == MarginsMode::INSIDE_VIDEO;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:296]: Is the change intentional? Before you had != Marginsmode::disabled and now you have ==

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:296]: yes since variables on OverlayRender are changed we have
DISABLED only when overrides are disabled
INSIDE_VIDEO when overrides are enabled with position inside video

so in this case we need to enable it when set as disabled
otherwise as alternative, maybe better, we need to rename `MarginsMode::DISABLED` to something like `MarginsMode::NATIVE`

**Review by enen92 — APPROVED** [review]
