### PR TITLE
[Android] Allow setting the VideoLayout view to transparent color

### LINKED ISSUE #25166: Gray Bars on Sony AF8 after being updated to version 21.
## Bug report
Gray Bars on Sony TV after v21
### Describe the bug
Here is a clear and concise description of what the problem is:
Playing videos shows Gray Bars and Washed out UI instead of Black Bars. Enabling Dolby fixes it but video lags hard.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Movie to have black bars.

## Actual Behavior
Movie has Gray Bars.

## Possible Fix
Apparently this was already fixed long time ago but for some reason reverted to fix some issues other people had. The thing is you can't just remove something that has been working for 5 Years. You just made the reverse now, we are having issues and this "other" people don't have them. How about a middle ground. Don't push fixes until both groups are satisfied or an option is introduced to enable the fix. 

image

https://forum.kodi.tv/showthread.php?tid=376806&pid=3189708

https://forum.kodi.tv/showthread.php?tid=371557&pid=3189636#pid3189636

https://github.com/xbmc/xbmc/pull/22561

### To Reproduce
1. Play a HDR/Dolby Movie
2. Look at Gray Bars

### Debuglog

The debuglog can be found here:
Not doing that sorry, Issue is well known.

### Screenshots 
Here are some links or screenshots to help explain the problem:
Gray vs Black

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
https://forum.kodi.tv/showthread.php?tid=376806&pid=3189708

https://forum.kodi.tv/showthread.php?tid=371557&pid=3189636#pid3189636

### Your Environment
Used Operating system:

 - [X ] Android

 - Operating system version/name:
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by quietvoid**
## Description
Add advanced setting to set the `VideoLayout` view background color on launch, for Android devices only.
Replaces PR https://github.com/xbmc/xbmc/pull/25171

Usage:
```
<advancedsettings version="1.0">
  <gui>
   <transparentvideolayout>true</transparentvideolayout>
 </gui>
</advancedsettings>
```

## Motivation and context
Sony TVs have a long standing firmware bug. Allow a user to configure the video layout background color to workaround this.
Fixes #25166 

## How has this been tested?
Runtime tested on FireTV Stick 4K Max which has the same issue but with transparent background color instead of black.
Needs testing by Sony TV users.

## What is the effect on users?
None by default. Requires advanced setting.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/application/Application.cpp [hunk 1]
```diff
@@ -668,6 +668,13 @@ bool CApplication::Initialize()
       }
     }
 
+#if defined(TARGET_ANDROID)
+    if (CServiceBroker::GetSettingsComponent()->GetAdvancedSettings()->m_guiVideoLayoutTransparent)
+    {
+      CLog::Log(LOGINFO, "XBMCApp: VideoLayout view was set to transparent.");
+      CXBMCApp::Get().SetVideoLayoutBackgroundColor(0);
+    }
+#endif
```
Comment (fuzzard) [inline xbmc/application/Application.cpp:677]: is there a reason this cant be placed in one of the platform specific init stages, or in windowing?

Comment (quietvoid) [reply xbmc/application/Application.cpp:677]: I'm not sure of the best place. I just reused fritsch's code.

Comment (quietvoid) [reply xbmc/application/Application.cpp:677]: If anyone can clarify where the Android init stuff is, I can try it out.
Or other suggestions.

Comment (thexai) [reply xbmc/application/Application.cpp:677]: Maybe move here:

```diff
diff --git a/xbmc/platform/android/activity/XBMCApp.cpp b/xbmc/platform/android/activity/XBMCApp.cpp
index 437c7371d9..64f4dff6ca 100644
--- a/xbmc/platform/android/activity/XBMCApp.cpp
+++ b/xbmc/platform/android/activity/XBMCApp.cpp
@@ -265,6 +265,12 @@ void CXBMCApp::onStart()
         std::make_unique<CJNIActivityManager>(getSystemService(CJNIContext::ACTIVITY_SERVICE));
     m_inputHandler.setDPI(GetDPI());
     runNativeOnUiThread(RegisterDisplayListenerCallback, nullptr);
+
+    if (CServiceBroker::GetSettingsComponent()->GetAdvancedSettings()->m_guiVideoLayoutTransparent)
+    {
+      CLog::Log(LOGINFO, "XBMCApp: VideoLayout view was set to transparent.");
+      SetVideoLayoutBackgroundColor(0);
+    }
   }
 }
```
 
not tested although

Comment (quietvoid) [reply xbmc/application/Application.cpp:677]: I've tried moving it but `CServiceBroker::GetSettingsComponent()` ends up being a nullptr at that stage.

Comment (CastagnaIT) [reply xbmc/application/Application.cpp:677]: you can try move it on `CPlatformAndroid` (PlatformAndroid.cpp)
by add a new override to use `InitStageThree` method

Comment (quietvoid) [reply xbmc/application/Application.cpp:677]: Thanks. That works. :+1:

**Review by thexai — APPROVED** [review]
Changes looks good to me.

**Comment by thexai** [comment]
Jenkins build this please

**Comment by thexai** [comment]
Jenkins build this please

**Comment by thexai** [comment]
jenkins build this please

**Comment by quietvoid** [comment]
Does this still need to be backported to Nexus?

**Comment by thexai** [comment]
Yes, I think it is necessary. Thanks.
