### PR TITLE
[LanguageCodes] Fix code lookup with language addons and lang codes user defined

### LINKED ISSUE #15308: Kodi not reading some languages codes right
### Describe the bug
Kodi reads some languages codes wrong if they are in this way "pt-BR" (Brazilian Portuguese) and "es-ES" (European Spanish), it reads "pt-BR" as "Portuguese - Breton" and reads "es-ES" as "Spanish - Spanish", it reads the abbreviation "BR" as the language "Breton" when it should read it as the country "Brazil" and reads "ES" as "Spanish" instead of the country "Spain", and this leads to choosing the wrong language for the audio and subtitles (usually chooses the default language), it should read the codes the same way it does in "ar-EG", Kodi reads it as Arabic, "EG" is the abbreviation of the country Egypt.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

## Possible Fix

I noticed that this problem happens only when there are a country and a language have the same abbreviation like "br" for "Brazil" and "br" for "Breton", and "es" for "Spain" and "es" for "Spanish", in this case Kodi chooses the language instead of the country, the fix for this problem might be by making Kodi considers any abbreviation after "-" is a country code.

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

Here is the debug log for "Spanish" "es-ES" after downloading the language from 'Download" then "Look and Feel", then "languages", then "Spanish", and choosing "Spanish" for the preferred audio and subtitle, then running the first episode from the TV show "Elite".

It downloads

C:\Users\Essam\AppData\Roaming\Kodi\addons\resource.language.es_es

https://pastebin.com/b5bNZgbG

and here are "manifest.json" and "manifest.mpd" for this episode

[manifest.es-ES.zip](https://github.com/xbmc/xbmc/files/2784689/manifest.es-ES.zip)

Here is the debug log for "Portuguese (Brazil)" "pt-BR" after downloading the language from 'Download" then "Look and Feel", then "languages", then " Portuguese (Brazil)", and choosing "Portuguese (Brazil)" for the preferred audio and subtitle, then running the first episode from the TV show "3%".

It downloads

C:\Users\Essam\AppData\Roaming\Kodi\addons\resource.language.pt_br

https://pastebin.com/RMJVNNyj

and here are "manifest.json" and "manifest.mpd" for this episode

[manifest.pt-BR.zip](https://github.com/xbmc/xbmc/files/2784691/manifest.pt-BR.zip)

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://i.ibb.co/cDxKGxW/1.jpg

https://i.ibb.co/RQXXyTY/2.jpg

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

This problem is with Kodi 18 Leia RC, Windows 10, and this Netflix plugin (using paid subscription in the official Netflix site).

https://github.com/asciidisco/plugin.video.netflix

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #21533: Language packs installed not fully implemented for subtitles with addons
### Describe the bug
Here is a clear and concise description of what the problem is:

This is the use case:
An user wants use Kodi with a language not provided by default, then install the language packet from Skin regional settings
this will allow to select the new language also for the subtitles, but at least for python/binary addons when you select
for subtitles a language that come from a installed packet not works,
So Kodi not select the language for the played video, and also the language name in the OSD subtitle settings (while in playback) is displayed in wrong way, and the user is forced to have each time open the OSD to select manually to select the correct language for each video played

moreover also in the `xbmc.convertLanguage` python module have a similar problem, is not able to read installed packages to convert the language format by returning an emtpy string,
at least looking at the source code, only the reading of language codes set in xml advanced settings is implemented, this is an awkward implementation for the normal user and also for addons dev where we have to find ugly workarounds

this has been reported to me in [#1348](https://github.com/CastagnaIT/plugin.video.netflix/issues/1348)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have language installed working also for python/binary addons
that concern also the python module

## Actual Behavior

Each time a video is played an user have to select manually via OSD the correct language

## Possible Fix

Implementing the missing part of code to get the language code from the language packets installed separately

### To Reproduce

To allow make tests i have prepared a custom STRM file
with 3 fake subtitles languages
so the video stream contains 3 subtitles tracks:
English / Chinese (Simple) / Chinese (Traditional)
where for chinese languages is needed to install the kodi language packets,
with following steps:

1) copy this to a `.strm` file:
```
#KODIPROP:inputstream=inputstream.adaptive
#KODIPROP:inputstream.adaptive.manifest_type=mpd
#KODIPROP:inputstream.adaptive.license_type=com.widevine.alpha
https://www.dropbox.com/s/z6i7p9daovxkt1d/DASH_manifest_adaptive_webvtt_test_langcode.mpd?dl=1
```
2) Open Kodi 20 (also Kodi 19 go well)
3) Install InputStream Adaptive addon
4) Goto Kodi Skin settings, and install for example the Chinese (Simple):
immagine
5) Goto Kodi Player settings and select  Chinese (Simple) for subtitles:
immagine
6) Play the strm file
7) Open OSD subtitle settings window, you can see that the subtitles language is not selected correctly, and the names are wrongs:
immagine
so `Chinese - cn` should appears as `Chinese (Simple)`, as the language packet is installed and set

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/wakanudehe.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have talk about subtitles, but is possible that this problem affect also audio track languages
(but not tested)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 20 from master branch and Kodi 19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

There are some ancien bugs in Kodi that prevent to correcly handle language codes,
follow use cases:

### An user has installed a language pack addon e.g. `Chinese (simple)`
**Case 1:**
When you play a streaming video we expects to see the correct language description in the subtilte/audio language list as defined in language pack addon
instead is shown a wrong name, especially if language code have the country code, for example:
`pt-br` is shown as `Portuguese - Breton` (instead of Portuguese-Brazil)
`nl-be` is shown as `Dutch - Belarusian` (instead of Dutch-Belgium)
this is wrong

so now we let to the users three possibilities:
- Install and use the addon language pack language code descriptions (if available)
- Define his language code's in xml advanced setting
- Do nothing, and the description will be as follow:
`pt-br` now will be shown as `Portuguese - br`
`nl-be` now will be shown as `Dutch - be`
which is preferable instead to show incorrect descriptions,
this can be improved in future maybe by implementing IETF BCP 47

**Case 2:**
When you play a streaming video with `Chinese (simple)`, Kodi is not able to select the subtitle (or audio) track automatically (set as `Chinese (simple)`), this because is missing the lookup in language addons, and the user has to manually select every time the correct language from the GUI audio/video language list

**Case 3:**
Similar to case 2, but for inpraticable use of advanced setting xml to define language codes with country code,
kodi do not taken in account of user defined language codes with country code, causing language selection to fail when playback,
see following point.

### Define language code with country code in advanced setting xml
You can define for example "zh-tw" (as the example below) this will be shown in the kodi setting subtitle/audio language list with right description, but if you try to play a video with that language code, not works, with all side effects mentioned before.
This because `CLangCodeExpander::Lookup` was not prioritizing the user map as happens in `CLangCodeExpander::ConvertToISO6392B`

### Playing an MKV video with tracks defined with language and country codes
If you play a mkv with tracks defined with language and country codes for example subs with
"zh-cn", "zh-tw", "zh-hans"
currenlty all tracks are identified and displayed as `Chinese` without distinction. This lead to a broken kodi track language selection when playback starts, and impossibility to the user to identify the type of language from the GUI.
MKV support IETF BCP 47 to set language codes with regions (country) but our ffmpeg demuxer not, and fallback always to the first language tag ("zh").
The only workaround possible is add the possibility to parse the language code with country code from the "title" field, to override the wrong language code.
So i have add a regex to parse following formats e.g. `zh-tw` or `(zh-hans)` (with or without round brackets)
this will require users to edit the video file, IMO it is an acceptable workaround until there is a definitive solution from ffmpeg

i am not sure about a backport to Kodi19 because to partially fix these problems many addons has implemented rather cumbersome cheats workarounds

## Motivation and context

Fix #21533

This also partially fix issues:
#15333
#15308
for a complete solution to display/manage right language names imo will be needed in future implement IETF BCP 47

## How has this been tested?

See example provided in the Issue #21533

A MKV with more subtitles with language code + country code

I will provide a test build to user that report to me the problem, to have a confirmation:
user confirmed that works: https://github.com/CastagnaIT/plugin.video.netflix/issues/1348#issuecomment-1229165210

## What is the effect on users?

Can have an automatic subtitle (also audio) language selection working with user custom defined language codes or installed language addons, where before subtitles track was not selected when play a video

Can display the correct language name in the subtitle (and audio) language list as defined with user custom defined language codes or installed language addons

Can define their custom locale codes also with country code in the advanced setting xml, eg.
```xml
<advancedsettings>
<languagecodes>
  <code>
    <short>zh-tw</short>
    <long>MyCustomDesc(zh-tw)</long>
  </code>
</languagecodes>
</advancedsettings>
```

Can have an automatic subtitle (also audio) language selection working with MKV videos that use in tracks language+country code, and right language names, as long as the workaround on the "title" track is used

## Screenshots (if appropriate):
Follow situation is, Chinese (simple) language addon installed, and `zh-tw` language code defined in the xml advanced setting
BEFORE:
immagine
AFTER:
immagine

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by matthuisman** [comment]
Great! Currently I need to proxy and then convert language codes in manifests so Kodi correctly picks them so this would remove need for such a workaround

**Comment by CastagnaIT** [comment]
yes much better that before
the user who did the test pointed out to me that with mkv files this does not work
i have no idea which path the code takes with regular video files, i will try to see if i am able to solve also with video files

File: xbmc/LangInfo.cpp [hunk 1]
```diff
@@ -667,6 +667,21 @@ LanguageResourcePtr CLangInfo::GetLanguageAddon(const std::string& locale /* = "
   return NULL;
 }
 
+std::string CLangInfo::ConvertEnglishNameToLocale(const std::string& langName) const
+{
+  ADDON::VECADDONS addons;
+  CServiceBroker::GetAddonMgr().GetAddons(addons, ADDON::ADDON_RESOURCE_LANGUAGE);
+  for (auto& addon : addons)
```
Comment (ksooo) [inline xbmc/LangInfo.cpp:674]: const auto& ?

File: xbmc/LangInfo.cpp [hunk 2]
```diff
@@ -667,6 +667,21 @@ LanguageResourcePtr CLangInfo::GetLanguageAddon(const std::string& locale /* = "
...
+  {
+    if (addon->Name() == langName)
```
Comment (ksooo) [inline xbmc/LangInfo.cpp:676]: Are langcodes case sensitive?

File: xbmc/LangInfo.cpp [hunk 3]
```diff
@@ -667,6 +667,21 @@ LanguageResourcePtr CLangInfo::GetLanguageAddon(const std::string& locale /* = "
...
+    {
+      LanguageResourcePtr langAddon = std::dynamic_pointer_cast<ADDON::CLanguageResource>(addon);
```
Comment (ksooo) [inline xbmc/LangInfo.cpp:678]: const Language…

File: xbmc/LangInfo.h [hunk 4]
```diff
@@ -74,9 +74,16 @@ class CLangInfo : public ISettingCallback, public ISettingsHandler
   const std::string& GetLanguageCode() const { return m_languageCodeGeneral; }
 
   /*!
-   \brief Returns the given language's name in English
+   * \brief Convert an english language name to locale,
+   *        by searching in the installed language addons.
+   * \param langName [OPT] The english language name
+   */
+  std::string ConvertEnglishNameToLocale(const std::string& langName) const;
```
Comment (ksooo) [inline xbmc/LangInfo.h:81]: As far as I see, this does not need to be a member function. So, make it ‘static’, remove ‘const’.

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp [hunk 5]
```diff
@@ -1835,7 +1836,29 @@ CDemuxStream* CDVDDemuxFFmpeg::AddStream(int streamIdx)
...
+      //! that have the priority over the Language element, but this is not currently
+      //! implemented in to ffmpeg library. Since ffmpeg read only the Language element
+      //! all tracks will be identified with same language (of Language element).
+      //! As workaround to allow set the right language code we provide the possibility
+      //! to set the language code in the title field in the following format:
+      //! "(zh-tw)" or "(zh_hans)"
+      //! this allow to kodi to recognize the right language and select the
+      //! right track to be played at playback starts.
+      AVDictionaryEntry* title = av_dict_get(pStream->metadata, "title", NULL, 0);
+      if (title && title->value != nullptr)
```
Comment (ksooo) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:1851]: Either ‘title != nullptr && title->value != nullptr’ or ‘ title && title->value’

File: xbmc/utils/LangCodeExpander.cpp [hunk 6]
```diff
@@ -410,6 +413,24 @@ bool CLangCodeExpander::LookupInUserMap(const std::string& code, std::string& de
...
 }
 
+bool CLangCodeExpander::LookupInLangAddons(const std::string& code, std::string& desc)
+{
+  if (code.empty())
+    return false;
+
+  std::string sCode(code);
+  StringUtils::ToLower(sCode);
+  StringUtils::Trim(sCode);
```
Comment (ksooo) [inline xbmc/utils/LangCodeExpander.cpp:423]: Nitpicking, but trim should be done first. There are chances that tolower has to deal with less characters. :-)

File: xbmc/utils/LangCodeExpander.cpp [hunk 7]
```diff
@@ -410,6 +413,24 @@ bool CLangCodeExpander::LookupInUserMap(const std::string& code, std::string& de
...
+  StringUtils::Replace(sCode, '-', '_');
+  std::string langDesc = g_langInfo.GetEnglishLanguageName(sCode);
```
Comment (ksooo) [inline xbmc/utils/LangCodeExpander.cpp:425]: const std::string

Comment (ksooo) [reply xbmc/utils/LangCodeExpander.cpp:425]: And the whole block until end of function can be simplified to
‘’’
desc = g_lang…;
return !desc.empty();
‘’’

File: xbmc/utils/LangCodeExpander.h [hunk 8]
```diff
@@ -118,6 +118,16 @@ class CLangCodeExpander
...
   static bool LookupInISO639Tables(const std::string& code, std::string& desc);
+
+  /*
+   * \brief Looks up the language description for given language code
+   *        in to the installed language addons.
+   * \param[in] code The language code for which description is looked for.
+   * \param[out] desc The english language name.
+   * \return true if the language description was found, false otherwise.
+   */
+  bool LookupInLangAddons(const std::string& code, std::string& desc);
```
Comment (ksooo) [inline xbmc/utils/LangCodeExpander.h:129]: Can be static.

File: xbmc/LangInfo.cpp (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/LangInfo.cpp]: done

File: xbmc/LangInfo.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/LangInfo.cpp]: yes maybe better case insensitive

File: xbmc/LangInfo.cpp (hunk 3 above)
Comment (CastagnaIT) [reply xbmc/LangInfo.cpp]: done

File: xbmc/LangInfo.h (hunk 4 above)
Comment (CastagnaIT) [reply xbmc/LangInfo.h]: done

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp (hunk 5 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp]: done

File: xbmc/utils/LangCodeExpander.cpp (hunk 6 above)
Comment (CastagnaIT) [reply xbmc/utils/LangCodeExpander.cpp:422]: nice right

File: xbmc/utils/LangCodeExpander.cpp (hunk 7 above)
Comment (CastagnaIT) [reply xbmc/utils/LangCodeExpander.cpp]: done

File: xbmc/utils/LangCodeExpander.h (hunk 8 above)
Comment (CastagnaIT) [reply xbmc/utils/LangCodeExpander.h]: done

**Comment by CastagnaIT** [comment]
@enen92 have you an idea to the page to use for the wiki?

**Comment by enen92** [comment]
Maybe add a known issues/quirks subsection in https://kodi.wiki/view/Subtitles
Or ping @KarellenX as he's our wiki guy nowadays

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp [hunk 9]
```diff
@@ -1835,7 +1836,29 @@ CDemuxStream* CDVDDemuxFFmpeg::AddStream(int streamIdx)
...
+      //! all tracks will be identified with same language (of Language element).
+      //! As workaround to allow set the right language code we provide the possibility
+      //! to set the language code in the title field in the following format:
+      //! "(zh-tw)" or "(zh_hans)"
+      //! this allow to kodi to recognize the right language and select the
+      //! right track to be played at playback starts.
+      AVDictionaryEntry* title = av_dict_get(pStream->metadata, "title", NULL, 0);
+      if (title && title->value)
+      {
+        CRegExp regLangCode;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:1853]: I'd say this logic here shouldn't be part of the demuxer cop file but rather as some static method in utils (maybe language code expander). The simple fact you include low level stuff like regex is a clear sign of this

File: xbmc/utils/LangCodeExpander.cpp [hunk 10]
```diff
@@ -8,6 +8,10 @@
 
 #include "LangCodeExpander.h"
 
+#include "LangInfo.h"
+#include "ServiceBroker.h"
```
Comment (enen92) [inline xbmc/utils/LangCodeExpander.cpp:12]: This also needs further thinking. Including references to service broker and add-on manager in an utils class doesn't look right. I.e. this is not some isolated component but rather something that can be called from any component

Comment (CastagnaIT) [reply xbmc/utils/LangCodeExpander.cpp:12]: I will find an alternative way both classes are intrinsic

Comment (enen92) [reply xbmc/utils/LangCodeExpander.cpp:12]: Yeah I'll also try to think a bit about it, including such headers here creates unwanted dependencies between components.
I think this calls more and more to a resources component that can be the owner of all static resources (fonts, language, colours, etc). This is too much work thought so if you can find a way to self contain this in the meanwhile it'd be great already.

Comment (CastagnaIT) [reply xbmc/utils/LangCodeExpander.cpp]: i removed the other includes but `LangInfo.h` i think cannot be removed without a large refactor

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp (hunk 9 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp]: done

File: xbmc/utils/LangCodeExpander.cpp (hunk 10 above)
Comment (enen92) [reply xbmc/utils/LangCodeExpander.cpp]: I think it's totally fine for now, both Langinfo and languagecodeexpander are some sort of components (although accessed as globals) which clearly urges for a refactoring (and inherently to my comment above regarding resources).
Unfortunately it's quite a huge amount of work.
Nevertheless, thanks much for your patch

File: xbmc/LangInfo.cpp [hunk 11]
```diff
@@ -667,6 +681,24 @@ LanguageResourcePtr CLangInfo::GetLanguageAddon(const std::string& locale /* = "
   return NULL;
 }
 
+bool CLangInfo::ConvertEnglishNameToAddonLocale(const std::string& langName, std::string& locale)
```
Comment (enen92) [inline xbmc/LangInfo.cpp:684]: Why not return the converted locale if found else empty string instead of this book return code approach + string refs? Would make the API a bit more sane. The cost of returning a copy is not significant in my opinion.

File: xbmc/utils/LangCodeExpander.cpp [hunk 12]
```diff
@@ -410,6 +419,20 @@ bool CLangCodeExpander::LookupInUserMap(const std::string& code, std::string& de
   return false;
 }
 
+bool CLangCodeExpander::LookupInLangAddons(const std::string& code, std::string& desc)
```
Comment (enen92) [inline xbmc/utils/LangCodeExpander.cpp:422]: Same here I'd say

File: xbmc/utils/LangCodeExpander.cpp [hunk 13]
```diff
@@ -547,6 +588,19 @@ std::string CLangCodeExpander::ConvertToISO6392T(const std::string& lang)
   return lang;
 }
 
+bool CLangCodeExpander::FindLanguageCodeWithSubtag(const std::string& str, std::string& langCode)
```
Comment (enen92) [inline xbmc/utils/LangCodeExpander.cpp:591]: Same here I'd say

File: xbmc/utils/LangCodeExpander.h [hunk 14]
```diff
@@ -102,22 +102,53 @@ class CLangCodeExpander
...
-  std::vector<std::string> GetLanguageNames(LANGFORMATS format = ISO_639_1, bool customNames = false);
-protected:
+  /*
+   * \brief Get the list of language names.
+   * \param format [OPT] The format type.
+   * \param addAddonLanguages [OPT] True to add languages of addons languages.
+   * \param addUserDefined [OPT] True to add user-defined languages (can override existings).
+   * \return The languages
+   */
+  std::vector<std::string> GetLanguageNames(LANGFORMATS format = ISO_639_1,
```
Comment (enen92) [inline xbmc/utils/LangCodeExpander.h:128]: Can you change both bools to an enum class? Would make the calling code easier to read (rather than having true,true,false,false, etc)

**Review by enen92 — COMMENTED** [review]
Some comments, mostly personal preference

File: xbmc/LangInfo.cpp (hunk 11 above)
Comment (CastagnaIT) [reply xbmc/LangInfo.cpp:684]: so i can do it for public methods, instead for private/protected i keep ref way
existing methods use ref way and this result in a more clean code, otherwise all code become more verbose due to have to check empty string after every single method call

Comment (enen92) [reply xbmc/LangInfo.cpp:684]: yeah, fine doing it for public methods only.

Comment (CastagnaIT) [reply xbmc/LangInfo.cpp]: done

File: xbmc/utils/LangCodeExpander.h (hunk 14 above)
Comment (CastagnaIT) [reply xbmc/utils/LangCodeExpander.h:140]: done, but LANGFORMATS enum seem cannot be changed to class enum without doing a breaking change on python interface so i kept it as is

**Review by enen92 — APPROVED** [review]
Can find anything else to bike-shed :)
Thanks a lot for the adjustments

**Comment by CastagnaIT** [comment]
Wiki added to:
https://kodi.wiki/view/Advancedsettings.xml#languagecodes
https://kodi.wiki/view/Settings/Player/Language#Language_code_support_on_MKV_files
feel free to improve it if needed

**Comment by scott967** [comment]
> Wiki added to: https://kodi.wiki/view/Advancedsettings.xml#languagecodes 
Typo on the wiki 
Portughese =>> Portuguese
