### PR TITLE
[Subtitles][ASS] Support both user defined fonts and extracted fonts

### LINKED ISSUE #16209: External ASS subtitles with custom fonts always display with default font
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi doesn't recognize the fonts the external ass subtitle indicates and always loads the default font.

Fonts are already copied to media/Fonts and can be seen in settings. I also copied the fonts to /system/fonts.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi should load and use the fonts indicated in the ass file from media/Fonts or /system/fonts or any other specific place, except that the fonts are embedded in the mkv or ass file.

## Actual Behavior

Kodi always loads the default font. All the fonts in the ass file are ignored. I can see the fonts put in media/Fonts, and changing the default font in the setting works.

## Possible Fix

libass cannot find any fontconfig configue file, so that it only loads fonts from temp/fonts. However, as neither mkv files nor ass files embedded fonts, it is empty inside temp/fonts. So libass can only use the default font.

A possible fix is to configure fontconfig to make sure libass reads the configure file, so that extra font path can be added into the configure file. Or make libass also loads fonts from a specific path so that users can put fonts inside it.

### To Reproduce

1. Use a mkv without embedded fonts.
2. Use an ass file without embedded fonts  which indicated a font other than the default one.
3. Play the mkv and you can see the subtitle in the default font.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/3232209/kodi.log)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: NVidia Shield TV 2017, version 6.4.0
 - Kodi version: 18.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This PR improves font handling for ASS subtitles. In kodi we allow users to add new fonts for subtitles (see 5.1 in https://kodi.wiki/view/Subtitles) by placing them into .kodi/media/Fonts. When using external subtitles that require the use of external fonts, the user should be able to place the fonts there for kodi/libass to find and use.

The main issue here is that libass only supports a single folder for storing additional fonts (see `ass_set_fonts_dir`) and we currently use the temp folder (.kodi/temp/Fonts) - the demuxer is configured to extract fonts to this directory (for muxed subs).

Due to the limitation, this PR changes the implementation and makes the demuxer extract subtitles to the user font directory by appending a known prefix to the files "tmp.font.*. This prefix is later used to cleanup temporary files, just like today (`ClearTempFonts`). This way we can support external fonts for subtitles and muxed fonts with libass.

## Motivation and Context
Improve font handling for ASS subtitles. Feature pairity between ASS and other subtitle formats (so that we can work towards a future conversion).
Fixes https://github.com/xbmc/xbmc/issues/16209

## How Has This Been Tested?
This was runtime tested on Linux, Android (TV), Windows and OSX with the samples available on the team ftp server. Furthermore, external subtitles (with missing fonts) were tested using the sample provided in https://forum.kodi.tv/showthread.php?tid=361545&pid=3024983#pid3024983

## Screenshots (if appropriate):

**Before (segoeprb.ttf in media/Fonts):**
alt text

**After (segoeprb.ttf in media/Fonts)**
alt text

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
Jenkins build this please

**Comment by phunkyfish** [comment]
jenkins build this please

File: xbmc/Util.cpp [hunk 1]
```diff
@@ -679,7 +679,7 @@ void CUtil::ClearSubtitles()
 
 void CUtil::ClearTempFonts()
 {
-  std::string searchPath = "special://temp/fonts/";
+  std::string searchPath = "special://home/media/Fonts/";
```
Comment (phunkyfish) [inline xbmc/Util.cpp:682]: `const` std::string

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 2]
```diff
@@ -49,8 +49,9 @@ static void libass_log(int level, const char *fmt, va_list args, void *data)
 
 CDVDSubtitlesLibass::CDVDSubtitlesLibass()
 {
-  //Setting the font directory to the temp dir(where mkv fonts are extracted to)
-  std::string strPath = "special://temp/fonts/";
+  // Setting the font directory to the user font dir. This is the directory
+  // where user defined fonts are located (and where mkv fonts are extracted to)
+  std::string strPath = "special://home/media/Fonts/";
```
Comment (phunkyfish) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:54]: `const` std::string

**Review by phunkyfish — CHANGES_REQUESTED** [review]
Just some minors.

**Review by phunkyfish — APPROVED** [review]
LGTM

**Comment by enen92** [comment]
Jenkins build and merge
