### PR TITLE
Fix watched items in plugins after updating Kodi

### LINKED ISSUE #487: LE 17.6 (8.2.5) to LE 9.0 (Milhouse Builds) "Watched History Gone"
Hello,

As the title says to I upgraded to LE 9.0, my whole Watched History only for YouTube is gone.all the items I have seen doesn't show the Tick Sign.

I have a lot of Playlists of TV Shows and I can't seem to remember till which episode I have seen each Show lol.

I have this on the Milhouse Forum Thread as well. Kindly help me out.

### PR DESCRIPTION
**Pull request by AkariDN**
Closes jdf76/plugin.video.youtube#487
 
## Description
Old Kodi versions incorrectly save path for plugin items in video database (CVideoDatabase::SplitPath() and URIUtils::GetParentPath() behavior mismatch for plugin URLs). This is fixed in 18a2, but when updating video database we have to set new pathes for old plugin items to save watched/progress history in plugins with complex URLs.

## How Has This Been Tested?
* Install Kodi 17 and YouTube plugin
* Mark some youtube videos as watched, save resume points
* Update to Kodi 18 with this PR
* Check status of watched youtube videos

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/video/VideoDatabase.cpp [hunk 1]
```diff
@@ -5379,11 +5379,37 @@ void CVideoDatabase::UpdateTables(int iVersion)
...
+      m_pDS2->next();
+    }
+    m_pDS2->close();
+  }
 }
 
 int CVideoDatabase::GetSchemaVersion() const
 {
-  return 112;
+  return 114;
```
Comment (Rechi) [inline xbmc/video/VideoDatabase.cpp]: Why skip 113?

Comment (AkariDN) [reply xbmc/video/VideoDatabase.cpp]: I don't like 13

File: xbmc/video/VideoDatabase.cpp [hunk 2]
```diff
@@ -5379,11 +5379,37 @@ void CVideoDatabase::UpdateTables(int iVersion)
...
+  if (iVersion < 114)
+  {
+    m_pDS2->query("SELECT files.idFile, files.strFilename, path.strPath FROM files LEFT JOIN path ON files.idPath = path.idPath WHERE files.strFilename LIKE 'plugin://%'");
+    while (!m_pDS2->eof())
+    {
+      std::string path, fn;
+      SplitPath(m_pDS2->fv(1).get_asString(), path, fn);
+      if (path != m_pDS2->fv(2).get_asString())
+      {
+        int pathid = AddPath(path);
```
Comment (pkerling) [inline xbmc/video/VideoDatabase.cpp]: It is not safe to call most other functions of this class that act upon the DB from the update code - this might break in the future because e.g. `AddPath` already expects the DB to be fully updated. Can you do it some other way? Moderate amounts of code duplicate are permissible and probably unavoidable in this case.

Also, as you probably noticed, `AddPath` uses `m_pDS` (which is why your code wouldn't work when you swap `m_pDS2` and `m_pDS` which would be more natural).

**Review by yol — CHANGES_REQUESTED** [review]
Thanks for looking into this. Unfortunately, I don't think we can merge this as-is (see comment).

**Comment by AkariDN** [comment]
@pkerling done

**Comment by pkerling** [comment]
Looking good now, thanks!

Two minors, then I think we are good to go (@MartijnKaijser should probably go into v18):
* Change the version to `113`
* Add a comment to the code explaining what this update does and why it is necessary.

**Comment by AkariDN** [comment]
Done. Please merge this PR before v18 release otherwise we can get more "watch history gone..." tickets.

**Comment by AkariDN** [comment]
jenkins build this please

**Review by yol — APPROVED** [review]

**Comment by pkerling** [comment]
I took the liberty of editing the comment to save some back-and-forth and so you can see what I would expect. Very briefly, the comment should provide enough context to understand *why* the update is necessary (most other migrations just add columns, it's obvious in that case). Merging this now, thanks for taking care. It will for sure save us some bug reports :-)
