### PR TITLE
[Android] Ignore obsolete DOVI profiles from codec selection

### LINKED ISSUE #24171: Problem playing Dolby Vision movies and series via streaming services
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello Kodi Team @fritsch or @ksooo,

Hadrware:
Nvidia Shield TV Pro 2019
LG OLED55B7D

Via streaming services (Netflix Addon, Amazon Prime Addon, Disney+ Addon) from kodi-20231124-940fe21f-master-arm64-v8a.apk and newer build = not OK = problems with 4K no Dolby Vision start icon on TV and when playing movies/series - black picture but sound is running.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Via streaming services (Netflix Addon, Amazon Prime Addon, Disney+ Addon)  with kodi-20231122-8f075c53-master-arm64-v8a.apk and builds before that = OK = No problems even if you return from a newer build.

## Actual Behavior

Via streaming services (Netflix Addon, Amazon Prime Addon, Disney+ Addon) Problems with 4K no Dolby Vision start icon on TV and when playing movies/series - black picture but sound is running.

kodi-20231124-940fe21f-master-arm64-v8a.apk = Not OK
kodi-20231127-b4ae12fe-master-arm64-v8a.apk = Not OK
kodi-20231128-4a41a5e4-master-arm64-v8a.apk = Not OK
kodi-20231130-12d991a5-master-arm64-v8a.apk = Not OK

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:  https://paste.kodi.tv/irinahiyaf.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android TV 11
 - Kodi version: Nightlies Kodi 21 Omega Beta1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by quietvoid**
## Description
When the `AVDOVIDecoderConfigurationRecord` is not valid, the fields are zeroed and profile is set to 1, which is incorrect. It should default to profile 0.

Fixes #24171.

## Motivation and context
Fixes Dolby Vision playback when file hints are not provided by FFmpeg demuxer.
In Dolby's specifications it also says `Profiles 0–3 and 6 are not supported for new applications.`

## How has this been tested?
Not tested.

## What is the effect on users?
Corrects playback of videos through streaming addons.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp [hunk 1]
```diff
@@ -539,27 +539,12 @@ bool CDVDVideoCodecAndroidMediaCodec::Open(CDVDStreamInfo &hints, CDVDCodecOptio
           {
             switch (m_hints.dovi.dv_profile)
             {
-              case 0:
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:542]: Maybe group the cases and break adding a comment to explain why they are not considered? Just saves someone from incorrectly adding them again

Comment (quietvoid) [reply xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:542]: Good idea.

**Review by thexai — APPROVED** [review]

**Comment by thexai** [comment]
jenkins build this please
