### PR TITLE
[video] Fix year infoLabel in CVideoInfoTag

### LINKED ISSUE #16486: ListItem "year" infoLabel is not used in Information pane
### Describe the bug
Here is a clear and concise description of what the problem is:

When we set the `year` infoLabel on a ListItem, it is not being used in the Information pane when selecting **Information** in the context menu of that item. Instead it is using the year of the `aired` or `premiered` infoLabel.

Since our add-ons are listing TV streaming content, the `aired` infoLabel actually is when it was broadcasted on the TV channel (usually the same or previous year), not when it first was broadcasted. That is why we set the `year` infoLabel for the movie explicitly.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The Information pane should be showing the `year` infoLabel if that is explicitly set, rather than use the `aired` date's year value. It could still use that if the `year` infoLabel wasn't set.

## Actual Behavior
The Information pane is ignoring the `year` infoLabel, but is using the year from the `aired` infoLabel.

## Possible Fix
Use the `year` infoLabel if it was set, otherwise fall back to the `premiered` infoLabel, or `aired` infoLabel.

### To Reproduce
1. Create a ListItem with a `year` and `aired` infoLabel using a different year
2. Open the Information pane
3. Conclude that Kodi is using the year from the `aired` infoLabel

### Debuglog
The debuglog is of no help in this issue.

### Screenshots 
The below screenshot shows the movie year as **2019** whereas the `year` infoLabel was correctly set to `2013`.
screenshot010
*The VOD metadata shows season-metadata as year, and episode-metadata as 1, that is why you also see 2013x1 below the movie title.*

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC v9.0.2
 - Kodi version: 18.2

### PR DESCRIPTION
**Pull request by mediaminister**
## Description

Preferably use `year` infolabel in `CVideoInfoTag` if set and extract the year from `premiered` or `aired` infolabel as a fallback.

## Motivation and Context

When a plugin sets the `year` infolabel on a ListItem using `ListItem.SetInfo()`, it is not being used in `ListItem.Year` infolabel and this causes `DialogVideoInfo.xml` (Information pane) to show no or wrong information. Instead it is always using the year extracted from the `aired` or `premiered` infolabel.

Since some plugins are listing content of tv catchup services, the `aired` infoLabel actually contains the most recent (re)broadcast date on a TV channel and not the production year.

This fixes https://github.com/xbmc/xbmc/issues/16486

## How Has This Been Tested?

Tested on Linux x64 with Kodi 19 with a "minimal" video plugin containing a ListItem with all "date" related infoLabels set. Also compared the wrong behaviour in Kodi 18 and this fix in Kodi 19 with VRT NU add-on (see screenshots)
## Screenshots (if appropriate):
Wrong behaviour in Kodi 18 (Big Eyes https://www.imdb.com/title/tt1126590/)
Screenshot at 2020-01-18 23-03-02

Correct behaviour with this fix in Kodi 19 (Big Eyes https://www.imdb.com/title/tt1126590/)
Screenshot at 2020-01-18 23-01-39

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by enen92 — APPROVED** [review]
I agree with the implementation, if the year is specifically set (e.g. from python) that value should take precedence over premiered. Only comment is to avoid using the Hungarian notation for the new member variable.

**Comment by dagwieers** [comment]
I was told another release (Leia?) was coming soon, could this be added/backported, please?

**Comment by DaveTBlake** [comment]
> 
> 
> I was told another release (Leia?) was coming soon, could this be added/backported, please?

Sorry, no backport. Another Leia release was only being considered because of the HTTP2 workarounded needed following widely impacting thrid-party changes. Cloudflare seem to have reverted their changes that caused the problem just as a v18.9 release was ready to go, so even doing that is being reconsidered. 

Fixes for v19 are very welcome, but consider v18 to be completed.

**Comment by ksooo** [comment]
@phunkyfish you might want to check that this does not introduce any regressions for PVR recordings...

**Comment by mediaminister** [comment]
> Only comment is to avoid using the Hungarian notation for the new member variable.

Okay, I removed the Hungarian notation.

**Comment by phunkyfish** [comment]
@emveepee could you check this change in light of your recent PVRRecordings Year change? https://github.com/xbmc/xbmc/pull/18430

It looks like it won't have an impact as we override GetYear and HasYear methods but worth checking. If you don't have time let me know and I can look next weekend.

@mediaminister if a PR like this gets stuck, please ping me on slack and I can see if we can get it moving again.

**Comment by emveepee** [comment]
> 
> @emveepee could you check this change in light of your recent PVRRecordings Year change? #18430

I shouldn't impact PVR but I don't understand the new variable m_year since that should be the same as m_premiered.GetYear()  m_premiered will be a movie or tv_show premier date (versus the m_firstAired being the date for tv or an episode date for a series).    The problem all along is populating  first aired as year.

From a display perspective the question is whether the year is shown or not and in that case m_year makes some sense but if that is case HasYear() should only check m_year.   It depends if you want to show  Coronation Street (1960) or just Coronation Year, I prefer the later.  This also depends on if m_premiered is available as a separate tag from the year since seeing 1960-12-09 might be interesting.  For one-off videos like specials and sporting events having the year should be optional.

**Comment by mediaminister** [comment]
> I don't understand the new variable m_year since that should be the same as m_premiered.GetYear()

This is needed because you can define a separate `year` and `premiered` infoLabel on a ListItem: https://romanvm.github.io/Kodistubs/_autosummary/xbmcgui.html?highlight=setinfo#xbmcgui.ListItem.setInfo

The `year` infoLabel can indicate the production year and the `premiered` date may differ depending on the streaming provider or broadcaster.

**Comment by emveepee** [comment]
> 
> The `year` infoLabel can indicate the production year and the `premiered` date may differ depending on the content provider or broadcaster.

True my view is limited because PVR doesn't allow the flexibility for tags that python and full scrappers might have.  I do feel
the main title should be defined to be consistent across providers.  What do you consider the "year" for "The Man with the Golden Gun"?  https://www.imdb.com/title/tt2382320/  https://www.themoviedb.org/movie/370172-no-time-to-die

**Comment by mediaminister** [comment]
I consider it 2021.

> I do feel the main title should be defined to be consistent across providers.

Indeed, it makes sense to define and use the `year` infoLabel because some scrapers/add-ons don't have access to the necessary information to define a full datestring in the `premiered` or` aired` infoLabel.

And this approach won't interfere with implementations that just use the `premiered` or `aired` infoLabel.

**Comment by emveepee** [comment]
I agree but with the change there is flexibility to show 2020  or 2021 I would like the same flexibility with SetYear(0) to define showing just "Coronation Street" or "The Big Bang Theory" or "Premier League Football" without having to remove premier/air date year metadata.

**Comment by phunkyfish** [comment]
@emveepee do you specifically want that for PVR? Or in general?

As PVR overrides these for recordings a change in this PR would have no effect.

**Comment by emveepee** [comment]
> 
> 
> @emveepee do you specifically want that for PVR? Or in general?
> 
> As PVR overrides these for recordings a change in this PR would have no effect.

I think it is a general issue.  Taking my "Coronation Street" example a with a new variable you can't flag that  you don't want to show a  year  so you only have the choice of "Coronation Street (1960)"  or you could still end up with the first aired date "Coronation Street (1982)" , "Coronation Street (2020)".   If forcing the year is what is preferred that is fine, typically it is optional for original series and single episode shows.

In PVR there is a further restriction because there currently is no SetPremiered() functionality but that's a different PR.

**Comment by DaveTBlake** [comment]
Sorry this has lurked so long @mediaminister, obviously ideally it wants to be merged and get into alpha 3. However 

a) I'm not clear that the debate over the impact (or not) on PVR was resolved
b) have doubts that the serialiszed "year" value can be changed from premired/aired to some set value without being a JSON API change (at very least an internal one so patch bump)
c) what is the effect on sorting _any_ video library item by year going to be? That uses m_year directly (which will be -1 unless something sets it?)  and not GetYear which has fallback.

With c) it seems to me this small change could have much wider impact than expected. Can someone confirm? I know this is the kind of comment that would have been better made 11 months ago, apologies. I sincerely hope these matters can be clarified quickly.

**Comment by phunkyfish** [comment]
Sorry I didn’t get back to this and hit approve. There is no impact to PVR as noted by @emveepee.

**Review by phunkyfish — APPROVED** [review]
👍

**Review by DaveTBlake — CHANGES_REQUESTED** [review]
Finally made some time for testing this and sadly there is a problem, just not the one I expected.

My original concern c) was that setting sortable[FieldYear] = m_year in `ToSortable()` would interfere with sorting video library items. That isn't the case because `ByYear` in SortUtils.cpp uses FieldAirDate before FieldYear, a sort field value that falls back to premiered date when first aired is invalid.

The problem with this change is the impact on JSON requests for video library items. So not only yes the patch bump you have added is necessary, but calls to GetMovies, GetMovieDetails, GetTVShows and GetTVShowDetails for normal video library items now return -1 for "year" property whereas previously it  returned a year value determined from premiered date.

**Comment by mediaminister** [comment]
I guess calling GetYear() instead of m_year fixes this issue.

File: xbmc/video/VideoInfoTag.cpp [hunk 1]
```diff
@@ -592,7 +593,7 @@ void CVideoInfoTag::Serialize(CVariant& value) const
   value["playcount"] = GetPlayCount();
   value["lastplayed"] = m_lastPlayed.IsValid() ? m_lastPlayed.GetAsDBDateTime() : StringUtils::Empty;
   value["top250"] = m_iTop250;
-  value["year"] = m_premiered.GetYear();
+  value["year"] = GetYear();
```
Comment (DaveTBlake) [inline xbmc/video/VideoInfoTag.cpp:596]: I suggest 
```
if (m_year > 0)
    value["year"] = m_year;
  else if (m_premiered.IsValid())
    value["year"] = m_premiered.GetYear();
  else
    value["year"] = 0;
```

Comment (mediaminister) [reply xbmc/video/VideoInfoTag.cpp:596]: This is GetYear() and this does the almost the same as your suggestion:
```
int CVideoInfoTag::GetYear() const
{
  if (m_year > 0)
    return m_year;
  if (m_firstAired.IsValid())
    return GetFirstAired().GetYear();
  if (m_premiered.IsValid())
    return GetPremiered().GetYear();
  return 0;
}
```

Comment (DaveTBlake) [reply xbmc/video/VideoInfoTag.cpp:596]: Ha, cross posted!
I didn't suggest GetYear because that potentially involves first aired date, and previous JSON results have been only from premiered date. However looking closer only episodes have a valid first aired date, and only movies and TV shows return "year" and "premiered" properties. So GetYear will work.

Note this also solves a previous issue with invalid premiered dates returning odd "year" values because validity was not checked.

**Review by DaveTBlake — APPROVED** [review]

**Comment by emveepee** [comment]
@DaveTBlake  @phunkyfish  after a first compile this seems to break PVR but I don't have time to confirm why.

Nightly

image

Today

image

**Comment by phunkyfish** [comment]
So it’s that the year is missing now?

**Comment by DaveTBlake** [comment]
Hang on, that second screenshot you posted has changed @emveepee 
Initially it was showing 0B on the list part, now that is fine and it is just the title + year in the details panel that has year missing.

Can you PVR guys clarify what is or isn't working now.

**Comment by emveepee** [comment]
Yes I changed the screen shot to make them use the same sort order.  The first post shot using size order (which I used for testing the sort order PR) so it showed 0B To avoid confusion I changed the sort order. Good catch though.

**Comment by emveepee** [comment]
I just went for a jog and it is about 0 right now and typing with frozen fingers is t I don't see it making it to a break point here.  The problem is here

SetYear() removed the following

  if (m_bHasPremiered)
    m_premiered.SetDate(year, m_premiered.GetMonth(), m_premiered.GetDay());
  else
    m_premiered = CDateTime(year, 1, 1, 0, 0, 0);

and just sets  m_year = year;

PVR uses m_premiered to get the year

It would need access to m_year I don't' think  GetYear will work because we still end up with the first aired data in the year.  I'll try and see

**Comment by phunkyfish** [comment]
We just need to implement SetYear in PVRRecording

**Comment by emveepee** [comment]
Yes I am testting that  override now

**Comment by phunkyfish** [comment]
Works, here is the PR: https://github.com/xbmc/xbmc/pull/18681

**Comment by emveepee** [comment]
Here is my diff https://paste.kodi.tv/vivevesesi works too.

Martin
