### PR TITLE
RetroPlayer: Fix black screen for RGB emulators on some GLES platforms

### LINKED ISSUE #5: LE: Black screen after starting Emulator
I got a black screen after starting the emulator. Even there is no sound.
http://ix.io/QSS
I reported another issue with MrBoom, where I got sound. Don't know the bugs have the same reason or it is just LE :~

PS: I started the ROMs with IARL, but this shouldn't be a problem

### PR DESCRIPTION
**Pull request by garbear**
## Description
This PR fixes the black screen shown in emulators across some GLES platforms.

The problem is visible during gameplay, when the screen is black. However, when the game is paused and the menu appears, the video is correctly shown under the dialog.

The fix adds a new GLES shader that sets the alpha bits to 0xff, removing transparency issues.

## Motivation and Context
Fixes https://github.com/kodi-game/game.libretro.stella/issues/5 and others.

Addresses the bug mentioned in https://github.com/xbmc/xbmc/pull/15771

## How Has This Been Tested?
Tested using Stella emulator on RPi 3 running LibreELEC.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

File: xbmc/cores/RetroPlayer/rendering/RenderContext.cpp [hunk 1]
```diff
@@ -74,6 +74,7 @@ static ESHADERMETHOD TranslateShaderMethod(GL_SHADER_METHOD method)
   case GL_SHADER_METHOD::TEXTURE: return SM_TEXTURE;
 #if defined(HAS_GLES)
   case GL_SHADER_METHOD::TEXTURE_RGBA_OES: return SM_TEXTURE_RGBA_OES;
+  case GL_SHADER_METHOD::TEXTURE_NOALPHA: return SM_TEXTURE_NOALPHA;
```
Comment (Rechi) [inline xbmc/cores/RetroPlayer/rendering/RenderContext.cpp]:
```suggestion
  case GL_SHADER_METHOD::TEXTURE_NOALPHA:
    return SM_TEXTURE_NOALPHA;
```

File: system/shaders/GLES/2.0/gles_shader_texture_noalpha.frag [hunk 2]
```diff
@@ -0,0 +1,27 @@
...
+
+#version 100
+
+precision mediump float;
+uniform sampler2D m_samp0;
+varying vec4 m_cord0;
+
+void main ()
+{
+  vec4 rgb;
```
Comment (VelocityRa) [inline system/shaders/GLES/2.0/gles_shader_texture_noalpha.frag]: Suggestion for all of `main`. Simplify the code and not read the 4th component of the texture since it's not used:
```glsl
void main ()
{
  vec3 rgb;
   rgb = texture2D(m_samp0, m_cord0.xy).rgb;

 #if defined(KODI_LIMITED_RANGE)
  rgb *= (235.0 - 16.0) / 255.0;
  rgb += 16.0 / 255.0;
#endif

   gl_FragColor = vec4(rgb, 1.0);
}
```

Comment (garbear) [reply system/shaders/GLES/2.0/gles_shader_texture_noalpha.frag]: I just tried this and games work, but now GUI textures are having the invisible problem

Comment (VelocityRa) [reply system/shaders/GLES/2.0/gles_shader_texture_noalpha.frag]: Hm weird, it should be functionally the same.

Comment (garbear) [reply system/shaders/GLES/2.0/gles_shader_texture_noalpha.frag]: Must have been stale build files, because I retried your suggestion and found a typo. With the typo fixed, everything works. I'm adding your suggestion to the PR.

**Comment by garbear** [comment]
Created a test image for RPi 2: https://github.com/kodi-game/LibreELEC.tv/releases/tag/v9.1-20190901

File: system/shaders/GLES/2.0/gles_shader_texture_noalpha.frag (hunk 2 above)
Comment (StormTrooper) [reply system/shaders/GLES/2.0/gles_shader_texture_noalpha.frag]: > I just tried this and games work, but now GUI textures are having the invisible problem

I'm seeing a similar issue with OSMC builds.  Invisible  logos under MyOSMC.  Tested using the latest commit as well.

**Comment by garbear** [comment]
Uploaded a new image (had a report the last one got corrupted): https://github.com/kodi-game/LibreELEC.tv/releases

**Comment by garbear** [comment]
Received a report that the new image also fixes black screen. @VelocityRa @gusandrianos look good?

**Comment by gusandrianos** [comment]
@garbear Not sure what you're talking about... I have yet to add GLES and so far, I haven't noticed any black screen issues, neither on Nvidia nor on Intel GPUs

**Review by VelocityRa — APPROVED** [review]
@gusandrianos was about another issue, not w/ your shaders
lgtm

**Review by gusandrianos — APPROVED** [review]
@VelocityRa Yeah, my mistake.
Also lgtm

File: xbmc/cores/RetroPlayer/rendering/RenderContext.cpp (hunk 1 above)
Comment (Rechi) [reply xbmc/cores/RetroPlayer/rendering/RenderContext.cpp]: > Do not put multiple statements on a single line. Always use a new line for a new statement.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#41-multiple-statements

**Review by dagwieers — APPROVED** [review]

**Comment by dagwieers** [comment]
Could this be merged and backported to Leia, please?
This bug is causing most games to fail on Raspberry Pi.

**Comment by garbear** [comment]
Updated for Rechi's style comment. Will merge the PR when jenkins is happy.

**Comment by garbear** [comment]
Sorry, I missed the 18.5 cutoff. If there's talk of 18.6 I'll do a backport.

**Comment by Rechi** [comment]
@garbear please always set milestone before or right after merging a PR.

**Comment by dagwieers** [comment]
I know triage isn't fun, but it would be nice if important bugs (like this one) would be labeled or added to a milestone so it wouldn't be forgotten like this.

Especially the milestones functionality of GitHub would make it easy to ensure nothing important gets left behind. Or at least postponing it becomes a deliberate decision, and not an oversight.

*The problem with milestones here is that you can't have two milestones set (i.e. one for Leia and one for Matrix)*

**Comment by DaveTBlake** [comment]
>Sorry, I missed the 18.5 cutoff. If there's talk of 18.6 I'll do a backport.

@garbear do the backport, and providing there are some fixes to release I will do a 18.6 release

**Comment by garbear** [comment]
Backport PR is open with test build based on 9.2: https://github.com/xbmc/xbmc/pull/16969
