### PR TITLE
[discs] Improve Linux dvd playback without mounting

### LINKED ISSUE #20048: Kodi 19.1 won't play DVD
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi is unable to play DVDs kodi is detecting them as an incorrect image format
Detecting DVD-ROM media filesystem...
2021-08-16 17:00:55.662 T:28       INFO <general>: CD Analysis Report
2021-08-16 17:00:55.663 T:28       INFO <general>: __________________________________
                                                   
2021-08-16 17:00:55.664 T:28       INFO <general>: CD-ROM with ISO 9660 filesystem
2021-08-16 17:00:55.664 T:28       INFO <general>: ISO 9660: 0 blocks, label 
2021-08-16 17:00:55.664 T:28       INFO <general>: Tracks overall:1; Audio tracks:0; Data tracks:1
2021-08-16 17:00:55.664 T:28       INFO <general>: Using protocol iso9660://
2021-08-16 17:00:55.664 T:28       INFO <general>: Disc label: 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

 Kodi shold be able to play a DVD.

## Actual Behavior
Does does nothing when clicking on disc in menu.

### To Reproduce

1. Start Kodi
2. Put DVD in drive
3. Click the disc icon in kodi's menu

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/6993844/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [✔ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This is an ~alternative~ (follow up) to https://github.com/xbmc/xbmc/pull/23488 and attempts to fix optical DVD playback on Linux where mounting is not supported (e.g. udisks2 not installed). It brings several other improvements that hopefully makes Kodi a bit more future proof instead of just hacking stuff around:

- Introduces a `Resolve` method on `IDirectory` implementations which vfs implementations are free to use to resolve urls before playback (this will allow us to extend PluginDirectory and UPNPDirectory in the future instead of having VP to resolve the paths)
- Moves directory resolution to application player (resolving directories should not be dependent on player implementations, Kodi should provide the entries already resolved to the players/inputstreams)
- Implements DVDDirectory to abstract raw `dvd://` paths. For instance, it did not work if set from strm files (or playlists).
- Doesn't bind the `iso9660://` vfs paths to a specific drive. Kodi only supports one at the moment but we should be able to support more than one drive in the future. The implementation accounts for this and exploits the hostname of the vfs entry to propagate the actual drive directory (thanks @rmrector).

Closes https://github.com/xbmc/xbmc/issues/20048

## Motivation and context
Restore Leia behaviour concerning DVDs while improving the architecture

## How has this been tested?
- Tested on arch linux by removing udisks2 package
- Tested on windows to make sure no regressions are introduced
- Tested `dvd://` from strm files

## What is the effect on users?
Kodi on linux should now be able to play optical dvds without requiring the discs to be mounted.
Code is also a bit more clean since directory resolution for playback is centralised and implementation dependent.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [x] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/filesystem/DVDDirectory.h [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+{
+
+/*!
+ \brief Abstracts a DVD virtual directory (dvd://) which in turn points to the actual physical drive
+ */
+class CDVDDirectory : public IFileDirectory
+{
+public:
+  CDVDDirectory() = default;
+  ~CDVDDirectory() = default;
```
Comment (ksooo) [inline xbmc/filesystem/DVDDirectory.h:23]: IFileDirectory does not have a virtual ctor? Or did you forget to add override here?

File: xbmc/filesystem/DVDDirectory.cpp [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+#include "FileItem.h"
+#include "ServiceBroker.h"
+#include "URL.h"
+#include "storage/MediaManager.h"
+
+using namespace XFILE;
+
+bool CDVDDirectory::Resolve(CFileItem& item) const
+{
+  CURL url{item.GetDynPath()};
```
Comment (ksooo) [inline xbmc/filesystem/DVDDirectory.cpp:20]: const CURL

File: xbmc/application/Application.cpp [hunk 3]
```diff
@@ -2376,11 +2377,20 @@ bool CApplication::PlayFile(CFileItem item, const std::string& player, bool bRes
   if (item.IsPlayList())
     return false;
 
+  // Translate/Resolve the url if needed
+  std::unique_ptr<IDirectory> dir{CDirectoryFactory::Create(item)};
```
Comment (ksooo) [inline xbmc/application/Application.cpp:2381]: const std::unique_ptr

File: xbmc/filesystem/ISO9660Directory.cpp [hunk 4]
```diff
@@ -79,3 +79,19 @@ bool CISO9660Directory::Exists(const CURL& url)
   CFileItemList items;
   return GetDirectory(url, items);
 }
+
+bool CISO9660Directory::Resolve(CFileItem& item) const
+{
+  CURL url{item.GetDynPath()};
```
Comment (ksooo) [inline xbmc/filesystem/ISO9660Directory.cpp:85]: const CURL

**Review by ksooo — COMMENTED** [review]
Nice. Just some nitpicking from my end.

File: xbmc/filesystem/DVDDirectory.h (hunk 1 above)
Comment (howie-f) [inline xbmc/filesystem/DVDDirectory.h:23]: should the dtor be marked override?
```suggestion
  ~CDVDDirectory() override = default;
```

Comment (howie-f) [reply xbmc/filesystem/DVDDirectory.h:23]: oh, see comment below :)

**Comment by howie-f** [comment]
this is awesome, tried my super scratchy old dvd-disc as always.  vlc wont play, smplayer wont, dragon plays crap... only kodi with a shared /dev/sr0 does it's job now

grafik

File: xbmc/filesystem/DVDDirectory.h (hunk 1 above)
Comment (enen92) [reply xbmc/filesystem/DVDDirectory.h:23]: It doesn't have a virtual ctor. Defining one breaks multiple parts of the code where we call IFileDirectory constructor directly.
Should I keep it as is or should I remove it?

Comment (howie-f) [reply xbmc/filesystem/DVDDirectory.h]: afaik constructors can never be virtual, maybe ksooo meant the destructor?

**Comment by dmahurin** [comment]
It is good that this will be finally fixed. After all, that was the purpose of #23488.

Though may I suggest that this change is split into two parts.  One single commit that fixes the old bug, and other commits that adds the refactoring and improvement changes.   Currently it seems that the bug fix is mixed in with other desired improvements.

Since this is an old bug, having the bug fix separate (commit) from the other improvements will make it easily applied to the previous broken versions.   Since this bug had not yet been fixed in Kodi 19 or 20, the fix should work there.

@enen92, the changes you previously proposed, look fine for such a simple fix.
https://github.com/enen92/xbmc/commit/fb9684b1a13b64c6c773e64104f87313a00b59e6

Then you improvement/refactoring changes (12 files changed), could build from the changes in the fix.

Separating bug fixes from improvements is good practice.

**Comment by enen92** [comment]
We can try to push that minimal version (maybe backportable if there's another nexus release) and then rebase this one on top of that. Can you please submit the PR? The fix is yours afterall :)

**Comment by howie-f** [comment]
> It is good that this will be finally fixed.

i totally agree

**Comment by dmahurin** [comment]
@enen92, Ok.  We can use #23488 for the minimal fix.  I will rework that over the next couple days.

**Review by howie-f — APPROVED** [review]
nice
