### PR TITLE
[GUI] Fix some regressions regarding skin strings

### LINKED ISSUE #27753: [LocalizeStrings][Skin] label format nnnnn no longer renders since 260122 nightly
### Describe the bug
Here is a clear and concise description of what the problem is:

Skin xml code that formats label text as
`<label>31620</label>`
has in the past been interpreted as localizing a string 31620 from skin language strings.po.  Now that no longer works and alt format
`<label>$LOCALIZE[31620]</label>`
is required.  Is this intended?  I assume PR https://github.com/xbmc/xbmc/pull/27728 did this?  Nightly from 260122 still works.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The previous format works

## Actual Behavior

The string is not rendered

### To Reproduce

1. Include any skin control with the label set to use the failing format
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/elinivadas.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Will have to do a regex find and replace on entire skin if this is now a requirement to use $LOCALIZE[] format

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win x64 11 25H2
 - Kodi version: 22 A2 260126 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This fixes a few regressions caused by https://github.com/xbmc/xbmc/pull/27712 since there are other places where skin strings might be also used.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/27753 

## How has this been tested?
Runtime tested

## What is the effect on users?
Some skins strings should now be restored

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

File: xbmc/addons/Skin.cpp [hunk 1]
```diff
@@ -531,7 +532,7 @@ void GetFontsetsFromFile(const std::string& fontsetFilePath,
         if (idAttr)
         {
           if (idLocAttr)
-            list.emplace_back(g_localizeStrings.Get(atoi(idLocAttr)), idAttr);
```
Comment (garbear) [inline xbmc/addons/Skin.cpp:534]: Did this not cause a compiler error? I thought `g_localizeStrings` was removed in the last PR?

Comment (enen92) [reply xbmc/addons/Skin.cpp:534]: It's not yet merged

Comment (garbear) [reply xbmc/addons/Skin.cpp:534]: Well that would explain it 🙂

**Comment by garbear** [comment]
@claude please review

**Comment by enen92** [comment]
Unsure what's going on with Claude, seems broken for a couple of days again

**Comment by enen92** [comment]
@claude review

**Comment by scott967** [comment]
My build system is VS 2022 on a Win 10 machine, and a debug build of this PR did display integer label string format that didn't render in the 0126 nightly and also fixed the Container.ViewType infolabel rendering both in my skin and Estuary.  I assume it would also work in Win 11 (verified issue also in Win 10 installed Kodi).  Should note that all my Win systems updated their VC++ runtimes during install of 20260125 nightly installer but don't think that's involved.

**Review by scott967 — COMMENTED** [review]
As noted in previous comment a quick check of labels that didn't render now do render.

**Comment by enen92** [comment]
Thanks for reporting the issue, let me know if you find some other regression
