### PR TITLE
[video][gui] Fix remove option in context menu for tags

### LINKED ISSUE #18470: Tags- Remove From Library (broken)
### Describe the bug
The function **Remove from library** for video library tags has been broken since v17.

Please look at the three images in section 4 on this wiki page to understand which feature this is...
https://kodi.wiki/view/Video_library_tags#Managing_tags

## Expected Behavior
When a user wants to delete a tag, the user would select the Context Menu on the appropriate tag, select Manage... then select Remove from library. This should remove all movies from that tag, then delete the tag from the database.

## Actual Behavior
Nothing happens.

## Possible Fix
Unknown

### To Reproduce
1. Ensure you have tags in your library.
2. Attempt to delete a tag by following the images shown in section 4... https://kodi.wiki/view/Video_library_tags#Managing_tags

### Debuglog
Nil debuglog. Nothing is shown

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://kodi.wiki/view/Video_library_tags#Managing_tags

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by the-black-eagle**
## Description
Fix the remove tag from library in the tags context menu. Minor change to the confirmation dialog which previously read 'Remove movie from library'.

## Motivation and Context
Tags can't currently be removed from Kodi. All the required code is present, there is just no current method to call it.
Fixes https://github.com/xbmc/xbmc/issues/18470

## How Has This Been Tested?
Tested by adding several tags to movies and then removing them again.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
@the-black-eagle you seem to have nuked the "Manage.." context menu item for tags that then shows a submenu that gives user  facilities to add movies to a tag etc. as well as delete the tag. I think it is that delete action that needs fixing for tags, rather than add a new context menu.

**Comment by the-black-eagle** [comment]
@DaveTBlake Yeah, didn't mean to actually nuke that!  Fixed so that 'remove tag from library' via the context menu now works correctly.

File: xbmc/video/windows/GUIWindowVideoNav.cpp [hunk 1]
```diff
@@ -845,8 +845,9 @@ void CGUIWindowVideoNav::OnDeleteItem(CFileItemPtr pItem)
   else if (m_vecItems->GetContent() == "tags" && pItem->m_bIsFolder)
   {
     CGUIDialogYesNo* pDialog = CServiceBroker::GetGUI()->GetWindowManager().GetWindow<CGUIDialogYesNo>(WINDOW_DIALOG_YES_NO);
-    pDialog->SetHeading(CVariant{432});
-    pDialog->SetLine(1, CVariant{ StringUtils::Format(g_localizeStrings.Get(433).c_str(), pItem->GetLabel().c_str()) });
+    pDialog->SetHeading(CVariant{10058});
+    pDialog->SetLine(1, CVariant{StringUtils::Format(g_localizeStrings.Get(10059).c_str(),
+                                                     pItem->GetLabel().c_str())});
     pDialog->SetLine(2, CVariant{""});
```
Comment (DaveTBlake) [inline xbmc/video/windows/GUIWindowVideoNav.cpp:851]: By handling "tag" removeal in CGUIDialogVideoInfo::DeleteVideoItemFromDatabase, this entire `else if` can be removed and the final `else` in calling CGUIDialogVideoInfo::DeleteVideoItem will do the delete.
Better to have `<delete>` and CONTEXT_BUTTON_DELETE actions use common processing.

File: addons/resource.language.en_gb/resources/strings.po [hunk 2]
```diff
@@ -5022,7 +5022,17 @@ msgctxt "#10057"
...
+#: xbmc/video/dialogs/CGUIDialogVideoInfo.cpp
+msgctxt "#10058"
+msgid "Remove tag from library"
+msgstr ""
+
+#. xbmc/video/windows/CGUIWindowVideoNav.cpp
+msgctxt "#10059"
+msgid "Would you really like to remove tag '{0:s}' from the library ?"
+
+#empty strings from id 10060 to 10098
```
Comment (DaveTBlake) [inline addons/resource.language.en_gb/resources/strings.po:5035]: With suggested changes to `CGUIWindowVideoNav::OnDeleteItem` these become unnecessary

**Review by DaveTBlake — CHANGES_REQUESTED** [review]
Sorry for delay in checking this. I think it can be simplified, have delete key and menu action processing done in one place, so easier to keep consistent.

File: xbmc/video/windows/GUIWindowVideoNav.cpp (hunk 1 above)
Comment (the-black-eagle) [reply xbmc/video/windows/GUIWindowVideoNav.cpp]: Done.

File: addons/resource.language.en_gb/resources/strings.po (hunk 2 above)
Comment (the-black-eagle) [reply addons/resource.language.en_gb/resources/strings.po]: Done.

File: addons/resource.language.en_gb/resources/strings.po [hunk 3]
```diff
@@ -5022,7 +5022,13 @@ msgctxt "#10057"
 msgid "Edit file source"
 msgstr ""
 
-#empty strings from id 10058 to 10098
+#: xbmc/video/windows/CGUIWindowVideoNav.cpp
```
Comment (DaveTBlake) [inline addons/resource.language.en_gb/resources/strings.po:5025]: No it doesn't use 10058 :)

Comment (the-black-eagle) [reply addons/resource.language.en_gb/resources/strings.po]: Comment removed :)

**Review by DaveTBlake — APPROVED** [review]
