### PR TITLE
[GUI] Fix ActivateWindow if 'return' is defined

### LINKED ISSUE #16492: Using ActivateWindow() with return from context menu fails
### Describe the bug
Here is a clear and concise description of what the problem is:

When `ActivateWindow(window,dir,return)` is run from a context menu, going back will just end up in the top level Video menu, not the listing it started from.

This has been a bug since Krypton, but still exists in Kodi Leia.

*This was already reported on the forums: https://forum.kodi.tv/showthread.php?tid=336929*

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should go back to the original listing it was called from.

## Actual Behavior
It goes to the Videos window (presumably the &lt;window&gt; used in the call.

### To Reproduce
1. Call ActivateWindow(window,dir,return) from a context menu
2. Go back
3. Notice you end up in the generic Videos menu, not the listing you called it from.

### Debuglog
Log file is of no use here.

### Screenshots 
Screenshots won't show the issue.

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [x] Raspberry-Pi
 - [x] Windows
 - [] Windows UWP

 - Operating system version/name: LibreELEC 9.0.2
 - Kodi version: 18.2

### PR DESCRIPTION
**Pull request by enen92**
## Description
This pull request fixes the usage of `ActivateWindow(window, dir, return)` if the action is executed from context menu items (which according to the bug report is there since krypton).

This is mainly the case in python addons where listitems are created (for example) with the `ActivateWindow(xxxx, plugin://plugin.video.foo/bar, return)` as context menu actions. Other examples are any other `dir` paths to MusicLibrary and VideoLibrary.

According to the documentation, it is expected that Kodi moves back to the plugin directory from which the action was executed. However this doesn't work because:

- Kodi always computes the history for the provided path even if we specify the return parameter (e.g. we provide "plugin://plugin.video.foo/bar" as `dir`, Kodi will create the respective history: `plugin://plugin.video.foo/bar` ../ `plugin://plugin.video.foo`)

- Kodi always defines the provided `dir` as the root folder. This works well if we are activating a different window than the one that is already active. If they are the same, the root folder of `dir` should be set to the `path` that was on the media window before activating this new one otherwise we won't be able to move back to where we were.

@mediaminister @dagwieers since you were the ones reporting the issue, it'd be nice if you guys could test it.

I am unsure who I should ping for review, this seems no-man's code by now.

## Motivation and Context
Fixes https://github.com/xbmc/xbmc/issues/16492

## How Has This Been Tested?
Context menu item created in a plugin that pointed to another plugin:
```python
    myitem = xbmcgui.ListItem("TEST")
    myitem.addContextMenuItems([("move to programs", "ActivateWindow(Videos,plugin://plugin.video.vrt.nu/programs/emma/allseasons, return)")])
    xbmcplugin.addDirectoryItem(handle=plugin.handle, listitem=myitem, isFolder=True, url=plugin.url_for(live))
```
Confirmed the `onBack` action moved back to where I was before. Also tested library navigation (movies and tvshows) in estuary and confirmed the behaviour is still the same.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by DaveTBlake** [comment]
Take care you don't break other behaviour with this @enen92 , or ways in which skinners have become used to using this and Kodi behaving. I am unable to test immediately, and @the-black-eagle may be interested

**Comment by enen92** [comment]
@DaveTBlake I was about to ping you. Unfortunately we never know if regressions are introduced. This needs extensive testing and won't be merged unless it's proven okay. I'll ask in #skinning and maybe #testing

**Comment by DaveTBlake** [comment]
Sure @enen92 I wasn't saying don't, just aware from looking at other parts of the window/history/navigation behavour that it can bite back.

**Comment by mediaminister** [comment]
Because of this bug the VRT NU add-on moved to using `Container.Update(plugin_url)` which also works.
To test this I changed it back to `ActivateWindow(Videos,plugin_url,return)` and I can confirm this works now as it should be.

Thanks a lot for fixing this bug.

**Comment by enen92** [comment]
One "regression" found by @sualfred (or to be more precise something that didn't correspond to his expected behaviour - although still better than we have now):

Test case:
HOME -> TvShows -> Select a TVShow -> Select a random season -> JSON RPC: `{ "jsonrpc": "2.0", "method":"GUI.Activatewindow","params":{"window":"videos","parameters":["videodb://movies","return"]},"id":"1"}` -> (moves to movies as expected)

Navigating back:

*PR* (old implementation): Back -> episode view -> back -> home
*Master*: Back -> HOME
*Expected Behaviour*: Back -> episode view -> (back) seasons -> back (shows) -> back (HOME)

I adjusted the code to comply to the expected behaviour.

Would still be nice to have some feedback on the music section.

**Comment by DaveTBlake** [comment]
>Would still be nice to have some feedback on the music section

Understood @enen92 but been a bit busy with release and sunny summer weather. :) 
Will take a look soonest.

**Comment by the-black-eagle** [comment]
Tested in the music section by opening various nodes with both `musicdb://` and `library://music/` type paths.  Didn't see any regressions and with `return` defined always returned to the nav window that the node was activated from.  Without `return` defined, some nodes return to the root node list when navigating <BACK> before returning to the window they were called from.
LGTM but @DaveTBlake may spot something I missed :)

**Comment by DaveTBlake** [comment]
Did you check the recently adjusted version @the-black-eagle ?

**Comment by enen92** [comment]
Thanks @the-black-eagle (hopefully you cherry-picked today since I changed the implementation last night). @DaveTBlake no rush at all, was just a reminder I didn't test the MusicLibrary :).

This needs yet to be validated with `ReplaceWindow` yet as it shares the same implementation as `ActivateWindow` and I'm pretty sure the behaviour will not be 100% identical after my changes.

File: xbmc/windows/GUIMediaWindow.cpp [hunk 1]
```diff
@@ -553,12 +553,23 @@ bool CGUIMediaWindow::OnMessage(CGUIMessage& message)
...
-      { // first time to this window - make sure we set the root path
-        m_startDirectory = returning ? dir : GetRootPath();
+      {
+        // if this is the first time to this window - make sure we set the root path
+        // if "return" is defined make sure we set the startDirectory to the directory we are
+        // moving to (so that we can move back to where we were onBack). If we are activating
+        // the same window but with a different path, do nothing - we are simply adding to the
+        // window history.
+        if (message.GetParam1() != message.GetParam2())
+          m_startDirectory = returning ? dir: GetRootPath();
```
Comment (Rechi) [inline xbmc/windows/GUIMediaWindow.cpp:571]: > Conventional operators have to be surrounded by one space on each side.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

**Review by Rechi — COMMENTED** [review]
Please follow the [current code guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

**Comment by enen92** [comment]
Tested with `ReplaceWindow()` and it behaves correctly too:

Test case1:
Home -> RunAddon -> `"ReplaceWindow(videos,videodb://movies/titles, return)"` on the addon entrypoint -> moves to movie titles

Test case2:
Home -> RunAddon -> `"ReplaceWindow(videos,videodb://movies/titles)"` on the addon entrypoint -> moves to movie titles

OnBack navigation for test case 1:
Back -> home

OnBack navigation for test case 2:
Back -> videodb://movies -> Back -> videos -> Back -> Home

Weather in estuary (where replace window is used) also behaves identical.

**Comment by enen92** [comment]
jenkins build this please

**Review by DaveTBlake — APPROVED** [review]
Sorry for the weeks of delay @enen92, tested out the music library navigation and all looks fine to me

**Comment by enen92** [comment]
Thanks a lot @davetblake for testing and no worries about the time taken!

**Comment by Nanomani** [comment]
No Backport ?

**Comment by dagwieers** [comment]
@enen92 Can we backport this to Leia?

**Comment by enen92** [comment]
Although I didn't spot any regressions I'd prefer not to. It's better be prepared to find any regression in v19 development cycle than to introduce regressions on a version that is supposed to (TM) be the last one (leia). But you are always welcome to bring it as a pull request and see what others have to say about it. Personally I think it's time to move on an focus 100% on matrix

**Comment by dagwieers** [comment]
I understand, but we add-on developers will have to work with Leia for a few years, and it helps if we can reduce the number of workarounds in our code.
