### PR TITLE
PipeWire: stop log spam from RequestProcess events

### LINKED ISSUE #26122: Omega spams pipewire 1.2.4 logs with 2x10 "spa.audioadapter: 0x55679102b8: can't send command 10: Operation not supported" per second
### Describe the bug
Here is a clear and concise description of what the problem is:

**AudioEngine calls pw_stream_trigger_process in an incompatible way**

When using Kodi21 below RaspberryPi-OS to play Audio from GUI sounds or DVB-T2 it keeps spamming the pipewire processes logs with messages like:
`pipewire[767] spa.audioadapter: 0x55679102b8: can't send command 10: Operation not supported`
The log entry seems to occur 20 times per second.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi uses Pipewire in a way that doesn't lead to log spam.

## Actual Behavior

while audio just seems to play just fine it looks like

https://github.com/xbmc/xbmc/blob/Omega/xbmc/cores/AudioEngine/Sinks/pipewire/PipewireStream.cpp#L78 seems to call
the method `pw_stream_trigger_process`
from https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/1.2.4/src/pipewire/stream.c#L2537

https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/1.2.4/spa/plugins/audioconvert/audioadapter.c#L987 shows that the invalid [command 10](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/8f7acb717cda83f78fc128112e30d9b68337b2bd/spa/include/spa/node/type-info.h#L47) maybe unsupported by either the triggerer device would cause the same log message to be produced.

## Possible Fix

Pipewire seems to have two modes of using streams, (self)"driving" or by being triggered.

Kodi should use this method (existing since pw 0.3.4 and thus [allowed](https://github.com/xbmc/xbmc/blob/Omega/CMakeLists.txt#L243) by kodi) `pw_stream_is_driving` to check weather the stream is "driving" and should be triggered explicitly.
https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/1.2.4/src/pipewire/stream.h#L566

It could still be that this is just a bug in pw, since I could have messed up my understanding of driving and triggered pw usage.

### To Reproduce

1. install kodi21 on a recent raspberryPi OS with pipewire 1.2.4
2. play audio e.g. by navigating menues or watching a video
3. watch `journalctl -b -0 -f` for some seconds

### Debuglog

The debuglog can be found here:
debug log https://paste.kodi.tv/ciqaveyuca.kodi
journalctl pw debug log https://paste.kodi.tv/feniwijade created with `PIPEWIRE_DEBUG=E,spa.audioadapter:D`

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Screenshots
Here are some links or screenshots to help explain the problem:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
/etc/rpi-issue 
Raspberry Pi reference 2024-11-19
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 891df1e21ed2b6099a2e6a13e26c91dea44b34d4, stage4
/etc/debian_version
12.8
 - Kodi version:
   Kodi Media Center 21.1 (21.1.0) Git:20241025-f41df4d7da / package 3:21.1-5~bookworm

- pipewire 1.2.4-1~bpo12+1+rpt1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by stephan49**
## Description

This PR fixes an issue where PipeWire error logs are continuously created whenever there is audio playing or if the "keep audio device alive" setting is enabled.

This issue has appeared ever since PipeWire [v1.2.4](https://gitlab.freedesktop.org/pipewire/pipewire/-/compare/1.2.3...1.2.4) introduced a [change](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/c6ae68b9326f235aa6ee11b62b8e6a9126bb2e22) that forwards RequestProcess events.

These events are emitted whenever [`pw_stream_trigger_process()`](https://github.com/xbmc/xbmc/blob/b794e3660961ad23246035ddd78eabd607581615/xbmc/cores/AudioEngine/Sinks/pipewire/PipewireStream.cpp#L78) is called, which then tries to send RequestProcess commands (`command 10`) to a driver that fails with the error.

Since the stream is a driver, as set by [`PW_STREAM_FLAG_DRIVER`](https://github.com/xbmc/xbmc/blob/b794e3660961ad23246035ddd78eabd607581615/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp#L463), we should only call `pw_stream_trigger_process()` when the stream is driving by checking [`pw_stream_is_driving()`](https://docs.pipewire.org/group__pw__stream.html#ga3ddd332c45aa95250d3d1d26cf01452a). This allows [`do_trigger_driver()`](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/e4ff13a75d7acf170f6094db148dc77f380d505a/src/pipewire/stream.c#L2598) to be called while not allowing RequestProcess events to be emitted when the stream is not driving.

The [`(impl->trigger)` condition](https://gitlab.freedesktop.org/pipewire/pipewire/-/blob/e4ff13a75d7acf170f6094db148dc77f380d505a/src/pipewire/stream.c#L2594) only applies when the stream has `PW_STREAM_FLAG_TRIGGER` set, which is not the case [here](https://github.com/xbmc/xbmc/blob/b794e3660961ad23246035ddd78eabd607581615/xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp#L461).

## Motivation and context

This PR fixes #26122.

Other users have also reported the same [issue](https://forum.endeavouros.com/t/thousands-of-pipewire-errors/61069/8).

## How has this been tested?

I have tested this fix to be working on Arch (PipeWire v1.2.7) and Ubuntu 24.10 (PipeWire v1.2.4).

## What is the effect on users?

This change will stop logging errors continuously whenever there is audio playback.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp [hunk 1]
```diff
@@ -607,7 +607,8 @@ unsigned int CAESinkPipewire::AddPackets(uint8_t** data, unsigned int frames, un
 
   } while (true);
 
-  m_stream->TriggerProcess();
+  if (m_stream->IsDriving())
```
Comment (fritsch) [inline xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: Due to the design - the two commands are "non atomic". Means you could be scheduled away and condition when you call TriggerProcess might be the other way round already and your log comes back. As those two belong together, they need to be protected with a critical section.

Key question is: Is it worth it?

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: Also from the PW docu:
Streams that are not drivers according to [pw_stream_is_driving()](https://docs.pipewire.org/group__pw__stream.html#ga3ddd332c45aa95250d3d1d26cf01452a) can also call this method. The result is that a RequestProcess event is sent to the driver. If the graph is lazy scheduling according to [pw_stream_is_lazy()](https://docs.pipewire.org/group__pw__stream.html#gac987fb3ab601efd721dbd912e21b9136), this might result in a graph cycle by the driver. If the graph is not lazy scheduling and the stream is not a driver, this method will have no effect.

We are very well allowed to call it - even if we are not driving ...

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: That is an interesting find. When keep audio alive packages are queued only, they would have no effect.

One reason why Kodi wants to be a driver is the delay management. We want to know and feel at all times that audio was consumed under the hood. Also by design audio engine in Kodi has a driving loop itself. The Kodi audio sink thread is only blocked by the PW sink implementation. So it is clear why driver design was chosen.

Need to check again where the bug is. The stream noise case rings my alarm bells in a sense of that stream trigger is anyways not fully working as we thought it works.

Thanks for looking into this!

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: It might be that PW does an idle detection and unloads us as a driver when AE stops adding samples when being in its idle state without being alive. That way you should only get it when pressing a button.

It might be that we have to reset the driving state. E.g. when it removed our driver state, we have to ask it again?  If (!driving) make it drive() followed by process?

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: There is no direct possibility (e.g. set_driving) available. There is the stream properties that could update it - but honestly - I think something is wrong here. Do you see that PW reports idle and unloads the sink?

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: Okay. That basically means, we properly have to issue timeouts in pipewire itself when the sink is not being used.

For the menu sounds: Yes, that is the reason we implemented keep audio alive in first place as HDMI receivers and others would simply shutdown.

Comment (ford-prefect) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: I believe the lazy mechanism is more about screensharing, where frames might only be provided by the stream when something changes rather than on a clock.

This patch seems correct -- for audio, the expectation would be that the driver is generating process callbacks on its clock, and the rest of the graph nodes run their `process()` callback as a result -- so `pw_stream_trigger_process()` _must_ be called when the stream is driving, and _only_ when the stream is driving (there are some exceptions like in the loopback module where the playback stream opts out of process callbacks, and is triggered by the capture stream using the same API).

While I see why you might want to choose Kodi's clock as the driver, I assume that adapts to current delay? PipeWire will do rate matching on the ALSA node if it's following, but I can imagine this would get tricky with passthrough.

Comment (ford-prefect) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: I could not track how the "keep device alive in idle" functionality works. There is a `PW_KEY_PAUSE_ON_IDLE` and `PW_KEY_SUSPEND_ON_IDLE`, but pause/suspend would only happen if your stream is unlinked or not providing data, so I would not expect that to happen if you're feeding in silence when nothing else is playing.

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: Thanks @ford-prefect - btw. when did you switch to PW from pulse? Had hoped we would finished pulseaudio dts-hd / truehd at a point? I still have the WIP somewhere.

Then let's get this code merged.

@stephan49  Could you please rebase and mark for backport as well?

Comment (ford-prefect) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: Hey @fritsch! Unfortunately, the [reconfiguration work](https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/merge_requests/24) we needed for HBR formats got caught up in a review cycle that didn't close before people lost interest.

Most of the effort these days is on the PipeWire side anyway, so I'm not sure we'll ever complete that. The PulseAudio client libraries are still a fully supported (and in some cases recommended) API to talk to PipeWire, so maybe your branch + libpulse + pipewire-pulse will actually just work (and if not, I can take a look)

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/pipewire/AESinkPipewire.cpp:610]: Thanks for the feedback. Actually I don't want to break kodi's long lasting pulsesink, but just keep it as is - pipewire seems to be the road forward, so therefore let's focus on that one.

**Review by fritsch — APPROVED** [review]
Thanks!

**Comment by fritsch** [comment]
Thanks very much again. Will merge it once CI is done.
