### PR TITLE
[infoscanner] ensure we're only checking for .nomedia in folders (fixes #17651)

### LINKED ISSUE #17651: Kodi 18.6 segfaults playing mpeg2 video content on Ubuntu
### Describe the bug
Here is a clear and concise description of what the problem is:

Using 2:18.6+git20200301.1506-final-0eoan (Ubuntu 19.10 Eoan Ermine backport).

Kodi crashes/segfaults whenever I try to play mpeg2-encoding video content, regardless of whether the container is m2ts, mkv, or vob.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Select video content with mpeg2 encoding. It should play.

## Actual Behavior

Kodi segfaults and crashes out instead of playing the content.

## Possible Fix

Unknown

### To Reproduce

1. Launch kodi 
2. Select content with mpeg2-encoded video content

### Debuglog

The debuglog can be found here:
[kodi-crash-log-mpeg2-m2ts-content.txt](https://github.com/xbmc/xbmc/files/4462990/kodi-crash-log-mpeg2-m2ts-content.txt)
[kodi-crash-log-mpeg2-vob-content.txt](https://github.com/xbmc/xbmc/files/4462991/kodi-crash-log-mpeg2-vob-content.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screenshots illustrate problem, since it just crashes.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

No additional screenshots.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 19.10 Eoan Ermine
 - Kodi version: 18.6

### PR DESCRIPTION
**Pull request by mkortstiege**
Ensure we're not doing pointless .nomedia checks on files. Regression was introduced with https://github.com/xbmc/xbmc/pull/12772

## Motivation and Context

https://trac.kodi.tv/ticket/17651

## How Has This Been Tested?

Briefly tested on Linux.

## Types of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves existing functionality)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the [Code guidelines](https://codedocs.xyz/xbmc/xbmc/code_guidelines.html) of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the [CONTRIBUTING](https://github.com/xbmc/xbmc/blob/master/CONTRIBUTING.md) document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/music/infoscanner/MusicInfoScanner.cpp [hunk 1]
```diff
@@ -504,7 +504,7 @@ bool CMusicInfoScanner::DoScan(const std::string& strDirectory)
   // Discard all excluded files defined by m_musicExcludeRegExps
   const std::vector<std::string> &regexps = g_advancedSettings.m_audioExcludeFromScanRegExps;
 
-  if (IsExcluded(strDirectory, regexps))
+  if (CUtil::ExcludeFileOrFolder(strDirectory, regexps))
```
Comment (notspiff) [inline xbmc/music/infoscanner/MusicInfoScanner.cpp]: this removes the nomedia check for music info scanner. is this intentional?

File: xbmc/video/VideoInfoScanner.cpp [hunk 2]
```diff
@@ -429,8 +429,12 @@ namespace VIDEO
       if (!info2) // skip
         continue;
 
+      // Discard all .nomedia folders
+      if (pItem->m_bIsFolder && HasNoMedia(pItem->GetPath()))
```
Comment (notspiff) [inline xbmc/video/VideoInfoScanner.cpp]: this changes the behaviour of .nomedia with respect to recursions. ie before you could have .nomedia in the stop strDirectory and we would stop scanning, now it looks for .nomedia in each of the subfolders.

**Review by notspiff — COMMENTED** [review]
i'm not entirely sure what the issue is so i just pointed out the changed behavior implied.

**Comment by mkortstiege** [comment]
added the missing ``HasNoMedia()`` checks.

**Comment by samdurnxn** [comment]
Any update on this issue ? 
I try in the last Nightly Build of Kodi 18 (5th January) and the issue is not fix.

**Comment by afedchin** [comment]
@mkortstiege any progress on this?

**Comment by jcea** [comment]
Testing 18.0-alpha 2. This issue is still alive and killing my webdav server. Library update takes hours instead of 5 minutes in Kodi 17.4. What is missing to integrate this fix?

Thanks.

File: xbmc/InfoScanner.h [hunk 3]
```diff
@@ -48,10 +48,9 @@ class CInfoScanner
 
   /*! \brief Check if the folder is excluded from scanning process
    \param strDirectory Directory to scan
-   \param regexps Regular expression to exclude from the scan
    \return true if there is a .nomedia file or one of the regexps is a match
```
Comment (Razzeee) [inline xbmc/InfoScanner.h]: Comment is wrong if we change it like this

**Comment by jcea** [comment]
Just tested today repository. The problem is still present :-(

Please, merge this in, if correct or provide some kind of feedback if it is wrong.

Thanks.

**Review by notspiff — APPROVED** [review]
looks fine now
