### PR TITLE
[guilib] Decouple left/right text truncate from alignment

### LINKED ISSUE #24725: Error <align>right</align> at line break [CR]
### Describe the bug
Here is a clear and concise description of what the problem is:

When using a line break, the entire text is no longer aligned to the right.
The longer text is aligned to the right.
The shorter text is aligned to the left, to the beginning of the longer text.

Nexus alignment correct:
screenshot00019

Nexus alignment not correct:
screenshot00017

Nexus alignment not correct:
screenshot00015

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

All text is aligned to the right.

## Actual Behavior

Only the longest text is aligned to the right.

## Possible Fix

Possible cause of this error: 
https://github.com/xbmc/xbmc/pull/24624

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows10
 - Kodi version: Kodi 21 Omega beta3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

This PR introduce the left text truncate setting.

The problem is started with the GUI control improvements PR #22691 where in the past i tried to introduce the left truncate, but has caused some issues with the right text alignment. After that i had tried to fix with PR #24624, but was not so perfect solution (this PR also revert that changes).

The right solution is decouple left/right truncate so that can be configured without strictly depends from alignment.

`XBFONT_TRUNCATED_LEFT` was inevitably added and should extend the "alignment" settings for python addons without particular impact

Having improved the code, I took the opportunity to include an additional fix for the use case having `<align>center</align>` and `OVER_FLOW` to TRUNCATE, was already broken from oldest kodi versions (screenshots for center case below)

These changes keep same behaviours for GUI settings improvements as shown on screenshots of PR #22691

In case of rebranch the backport to Kodi 21 is mandatory for the final release.

**Note 1 for `<align>justify</align>` / `XBFONT_JUSTIFIED`:**
This alignment was already broken, and will not be addressed with this PR

Note 2: the new left truncate can have an additional use for RTL text but requires other improvements

## Motivation and context

fix #24725

## How has this been tested?

user confirmed no regressions:
https://github.com/xbmc/xbmc/issues/24725#issuecomment-1985410259
https://github.com/xbmc/xbmc/issues/24610#issuecomment-1985000375

Used custom python addon with a xml window and with:
- label control `<control type="label" id="10000">` 
- fadelabel `<control type="fadelabel" id="10000">` (note this control perform truncate without ellipses)
- textbox `<control type="textbox" id="10000">`

**CURRENT MASTER BRANCH (BEFORE):**
_Here i show only broken use cases_

Multilines both lines are short, dont exceed the container width, and then text **"truncate" is not applied**
`<align>right</align>`
immagine

Multilines both lines are too long, exceed the container width, and text **"truncate to RIGHT" is applied**
`<align>center</align>` (broken already before Kodi 20)
309718003-62be8951-adca-44ee-a235-d09478f3e74b
`<align>right</align>`
309718003-62be8951-adca-44ee-a235-d09478f3e74b

**WITH PR (NOW):**

Multilines both lines are short, dont exceed the container width, and then text **"truncate" is not applied**
`<align>left</align>`
immagine
`<align>center</align>`
immagine
`<align>right</align>`
immagine

Multilines both lines are too long, exceed the container width, and text **"truncate to RIGHT" is applied**
`<align>left</align>`
immagine
`<align>center</align>`
immagine
`<align>right</align>`
immagine

Only for sake of completness, example of truncate from LEFT, on right aligned text:
immagine

## What is the effect on users?

Various type of GUI controls used on skins should display text as expected
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/interfaces/legacy/Control.h [hunk 1]
```diff
@@ -744,8 +744,9 @@ namespace XBMCAddon
     /// | XBFONT_RIGHT      | 0x00000001 | Align X right
     /// | XBFONT_CENTER_X   | 0x00000002 | Align X center
     /// | XBFONT_CENTER_Y   | 0x00000004 | Align Y center
-    /// | XBFONT_TRUNCATED  | 0x00000008 | Truncated text
-    /// | XBFONT_JUSTIFIED  | 0x00000010 | Justify text
+    /// | XBFONT_TRUNCATED  | 0x00000008 | Truncated text from right
+    /// | XBFONT_JUSTIFIED  | 0x00000016 | Justify text
+    /// | XBFONT_TRUNCATED_LEFT | 0x00000032 | Truncated text from left
```
Comment (CrystalP) [inline xbmc/interfaces/legacy/Control.h:749]: 0xXXXXX means a hex constant, but the values are decimal here.
0x10 was correct for justified and truncated left should be 0x20
Same for the other similar changes of the file.

Comment (CastagnaIT) [reply xbmc/interfaces/legacy/Control.h]: done, thanks i didnt realized

File: xbmc/guilib/GUIFontTTF.cpp [hunk 2]
```diff
@@ -455,16 +442,51 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
...
           // Start rendering from the glyph that does not exceed the maximum width
           startPosGlyph = std::distance(itRGlyph, glyphs.crend());
           break;
         }
+        textWidth = nextWidth;
       }
     }
+    else
+    {
+      // Determines the maximum width the text can have within the maximum width
```
Comment (CrystalP) [inline xbmc/guilib/GUIFontTTF.cpp:458]: not very clear, defines the max width with the max width?

File: xbmc/guilib/GUIFontTTF.cpp [hunk 3]
```diff
@@ -455,16 +442,51 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
...
+      if (alignment & XBFONT_TRUNCATED)
+        textWidth = ellipsesWidth;
+
+      for (const Glyph& glyph : glyphs)
+      {
+        Character* ch = GetCharacter(text[glyph.m_glyphInfo.cluster], glyph.m_glyphInfo.codepoint);
+        if (!ch)
```
Comment (CrystalP) [inline xbmc/guilib/GUIFontTTF.cpp:465]: The \t character has a special case in rendering, shouldn't it be the same here? (that would be a defect of the original c/p code)

File: xbmc/guilib/GUIFontTTF.cpp [hunk 4]
```diff
@@ -455,16 +442,51 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
...
+
+    if (alignment & XBFONT_RIGHT)
+    {
+      // Moves the x pos with the purpose of having the text effect aligned to the right
+      startX += maxPixelWidth - textWidth;
+    }
+
+    if (alignment & XBFONT_CENTER_X && !(alignment & XBFONT_RIGHT) && !(alignment & XBFONT_LEFT))
+    {
+      if (alignment & XBFONT_CENTER_X)
```
Comment (CrystalP) [inline xbmc/guilib/GUIFontTTF.cpp:485]: Which case is the first if() meant to filter? There is overlap with the second if()

A validation that alignment doesn't contain conflicting flags could be good but would belong to the beginning of the function (or its caller), would have some error logging and would override the flags to go back to a normal situation for the rest of the code.

File: xbmc/guilib/GUIFontTTF.cpp [hunk 5]
```diff
@@ -516,10 +538,10 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
       {
         float nextCursorX = cursorX;
 
-        if (alignment & XBFONT_TRUNCATED)
+        if (alignment & XBFONT_TRUNCATED || alignment & XBFONT_TRUNCATED_LEFT)
```
Comment (CrystalP) [inline xbmc/guilib/GUIFontTTF.cpp:541]: Is this addition necessary? cursorX is initialized with ellipsesWidth in case of left truncation and the iterator of the loop begins at the first character that fits with left truncation

Alternatively mirror the Render loop more closely, which does require this condition and an exception treatment for the first char.

File: xbmc/guilib/GUIFontTTF.cpp [hunk 6]
```diff
@@ -554,13 +576,13 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
         continue;
       }
 
-      if (alignment & XBFONT_TRUNCATED)
+      if (alignment & XBFONT_TRUNCATED || alignment & XBFONT_TRUNCATED_LEFT)
       {
```
Comment (CrystalP) [inline xbmc/guilib/GUIFontTTF.cpp:580]: since the XBFONT_TRUNCATED and the XBFONT_TRUNCATED_LEFT case don't share anything, might be clearer to do
```
if ((alignment & XBFONT_TRUNCATED)
{ existing code }
else if (alignment & XBFONT_TRUNCATED_LEFT && itGlyph == glypghBegin)
{ new code - except the final }
```

File: xbmc/guilib/GUIEditControl.cpp [hunk 7]
```diff
@@ -538,7 +537,7 @@ void CGUIEditControl::ProcessText(unsigned int currentTime)
     if (HasFocus() || leftTextWidth == 0)
       changed |= m_label2.SetOverflow(CGUILabel::OVER_FLOW_CLIP);
     else
-      changed |= m_label2.SetOverflow(CGUILabel::OVER_FLOW_TRUNCATE);
+      changed |= m_label2.SetOverflow(CGUILabel::OVER_FLOW_TRUNCATE_LEFT);
```
Comment (CrystalP) [inline xbmc/guilib/GUIEditControl.cpp:540]: Doesn't left or right truncation depend on the offset of the first character displayed?
Worst case there could be both left and right truncation. probably best left for another PR though, this one does not mean to change the behavior.

**Comment by CrystalP** [comment]
I don't have much skinning skills, my limited runtime testing didn't find issues in Estuary but a skinner's feedback would be preferable.
For completeness, in the before/after screenshots, could you add "Multilines both lines are too long, exceed the container width, and text "truncate to LEFT" is applied" with both left and center alignment.

File: xbmc/guilib/GUIFontTTF.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIFontTTF.cpp:458]: "Calculates the maximum width based on the characters that can be contained within the maximum width"
better?

File: xbmc/guilib/GUIEditControl.cpp (hunk 7 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIEditControl.cpp:540]: no not good, better as is otherwise break the overflow behaviour

File: xbmc/guilib/GUIFontTTF.cpp (hunk 4 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIFontTTF.cpp:485]: i made an attempt and as i was thinking it print on log millions lines of validating errors

so i will add a kid of validation check in to `CGUIFontTTF::DrawTextInternal` inside the `if (dirtyCache)`,
so that when cached dont print anymore tons of log lines
maybe not perfect but at least users/devs can know if has set an invalid alignment that can produce wrong rendering

File: xbmc/guilib/GUIFontTTF.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIFontTTF.cpp]: replaced

File: xbmc/guilib/GUIFontTTF.cpp (hunk 3 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIFontTTF.cpp]: thanks oversight!

File: xbmc/guilib/GUIFontTTF.cpp (hunk 4 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIFontTTF.cpp]: added validation as said on my previous comment, please try give a look

File: xbmc/guilib/GUIFontTTF.cpp (hunk 5 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIFontTTF.cpp]: removed

File: xbmc/guilib/GUIFontTTF.cpp (hunk 6 above)
Comment (CastagnaIT) [reply xbmc/guilib/GUIFontTTF.cpp:618]: done

**Comment by CastagnaIT** [comment]
> could you add "Multilines both lines are too long, exceed the container width, and text "truncate to LEFT" is applied" with both left and center alignment.

before this PR you cannot use truncate from LEFT with left/center alignment, because truncate to LEFT was linked to right alignment only, so no screenshots

**Review by Hitcher — APPROVED** [review]
Found some time to test this today and everything is working as expected.

Thanks.

**Comment by CastagnaIT** [comment]
jenkins build this please
