### PR TITLE
[info] Fix division by 0

### LINKED ISSUE #21619: Adding an empty tvshow to the library causes crash.
### Describe the bug
Here is a clear and concise description of what the problem is:

If an empty tvshow folder is scanned to the library, Kodi will crash when opening a library node with that item.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should be possible to have an empty tvshow in the library without Kodi crashing. Empty tvshows are useful to act as placeholders for upcoming tvshows.

## Actual Behavior

Kodi crashes as soon as any library node with the empty tvshow is accessed.

### To Reproduce

1. Add the folder in this [Ahsoka.zip](https://github.com/xbmc/xbmc/files/9009187/Ahsoka.zip) for the upcoming show Ahsoka to your tvshow source folder. The folder only contains a poster and an .nfo file with the corresponding themoviedb.org url
2. Scan the show to the library using the default tvshow scraper settings
3. Open tvshows node of library and Kodi crashes

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/9009201/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Nexus Nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
Introduced in https://github.com/xbmc/xbmc/issues/21619 Kodi is crashing for empty tvshows. Make sure we don't reach a division by 0 situation

FIxes https://github.com/xbmc/xbmc/issues/21619

### CODE REVIEW

File: xbmc/video/windows/VideoFileItemListModifier.cpp [hunk 1]
```diff
@@ -81,7 +81,8 @@ void CVideoFileItemListModifier::AddQueuingFolder(CFileItemList& items)
     pItem->SetProperty("numepisodes", watched + unwatched); // will be changed later to reflect watchmode setting
     pItem->SetProperty("watchedepisodes", watched);
     pItem->SetProperty("unwatchedepisodes", unwatched);
-    pItem->SetProperty("watchedepisodepercent", watched * 100 / (watched + unwatched));
+    pItem->SetProperty("watchedepisodepercent",
```
Comment (howie-f) [inline xbmc/video/windows/VideoFileItemListModifier.cpp:84]: i‘d calculate `const int totalEpisodes = watched + unwatched` right before the whole „SetProperty“ block.

**Review by howie-f — APPROVED** [review]
