### PR TITLE
fixed: division by zero in addon installation

### LINKED ISSUE #14989: Kodi crashes/closes when trying to install add-on from zip-file
### Describe the bug

After adding a source to the file manager and trying to install an add-on from a zip-file, Kodi is forced to close without any warning and doesn't install the add-on.

## Expected Behavior

Kodi installs the add-on from the zip-file.

## Actual Behavior

Kodi closes immediately without installing the add-on.

### To Reproduce

1.  Download the zip-file from [kodinerds](https://github.com/kodinerds/repo/raw/master/repository.kodinerds.zip) and save it onto your disc. 
2. In Kodi, go to file-manager and add the directory you saved the zip-file to as new source.
3. In Kodi, go to add-ons and choose "Install from zip-file".
4. Navigate to your newly added source and select the zip-file ("repository.kodinerds.zip").
After a short while Kodi closes.

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/ililemesup.kodi](https://paste.kodi.tv/ililemesup.kodi)

## Additional context
Since there's almost nothing in the debuglog, I added the kodi_crashlog.dmp. Maybe it helps.
[kodi_crashlog-18.0-RC2 Git_20181202-812855d84e-20181204-151448.dmp.zip](https://github.com/xbmc/xbmc/files/2644556/kodi_crashlog-18.0-RC2.Git_20181202-812855d84e-20181204-151448.dmp.zip)

### Your Environment

Operating system version/name: Windows 10 Pro (1803), 64bit
Kodi version: Kodi Leia 18 RC2, 64bit

### PR DESCRIPTION
**Pull request by notspiff**
let totalsteps equal deps + 1 since we are also installing
the add-on itself.

fixes #14989

@Rechi @AlwinEsch

### CODE REVIEW

File: xbmc/addons/AddonInstaller.cpp [hunk 1]
```diff
@@ -714,7 +714,7 @@ bool CAddonInstallJob::Install(const std::string &installFrom, const RepositoryP
   SetText(g_localizeStrings.Get(24079));
   auto deps = m_addon->GetDependencies();
 
-  unsigned int totalSteps = static_cast<unsigned int>(deps.size());
+  unsigned int totalSteps = static_cast<unsigned int>(deps.size())+1;
```
Comment (Rechi) [inline xbmc/addons/AddonInstaller.cpp]: can you fix the formatting?
```suggestion
  unsigned int totalSteps = static_cast<unsigned int>(deps.size()) + 1;
```

File: xbmc/addons/AddonInstaller.cpp [hunk 2]
```diff
@@ -786,7 +786,7 @@ bool CAddonInstallJob::Install(const std::string &installFrom, const RepositoryP
   }
 
   SetText(g_localizeStrings.Get(24086));
-  SetProgress(0);
+  SetProgress(static_cast<unsigned int>(100.0*(totalSteps-1.0)/totalSteps));
```
Comment (Rechi) [inline xbmc/addons/AddonInstaller.cpp]:
```suggestion
  SetProgress(static_cast<unsigned int>(100.0 * (totalSteps - 1.0) / totalSteps));
```

**Review by Rechi — APPROVED** [review]

File: xbmc/addons/AddonInstaller.cpp (hunk 1 above)
Comment (notspiff) [reply xbmc/addons/AddonInstaller.cpp]: sure. each space will costs you €1 ;p
