### PR TITLE
[addons][codec] Set correct video format from picture

### LINKED ISSUE #22879: InputStream no support newer video formats, GetFrameBuffer hardcoded format, cause faulty images
### Describe the bug
Here is a clear and concise description of what the problem is:

Time ago i have implemented to InputStream interface AV1 support (PR #21390)
this can works correctly when we dont use our internal DRM decoder

but as you can see to relative implementation PR for InputStream Adaptive https://github.com/xbmc/inputstream.adaptive/pull/972
there still be present a problem when we use our DRM video decoder with the results having wrong images
immagine

After investigating another time, i found that:
1) from addon inputstream interface is missing all video formats used by new generations codecs
https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-dev-kit/include/kodi/c-api/addon-instance/video_codec.h#L48-L63
only YV12 / I420 is supported
2) from addon inputstream interface `GetFrameBuffer`:
https://github.com/xbmc/xbmc/blob/master/xbmc/addons/kodi-dev-kit/include/kodi/addon-instance/VideoCodec.h#L367-L370
that make a callback to `CAddonVideoCodec::GetFrameBuffer`
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp#L351-L353
has hardcoded the video format to `AV_PIX_FMT_YUV420P` that make impossible for an binary addon playback correctly a stream that require a different video format

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Having our DRM decoder working with all common video formats

## Actual Behavior

We cannot playback streams that use video formats differents from `AV_PIX_FMT_YUV420P`

## Possible Fix

1) add to input stream interface the minimal video formats required by Widevine DRM, you can see the full list here:
https://github.com/xbmc/inputstream.adaptive/blob/Omega/wvdecrypter/cdm/media/cdm/api/content_decryption_module.h#L273-L291
2) find a way to avoid `GetFrameBuffer` hardcode the video format, seems we cannot know the video format before call `GetFrameBuffer` from the DRM, the info is in the decoded picture, so we should have a way to set it when we call `CAddonVideoCodec::GetPicture` https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp#L226-L272 since the property is already present in the `picture.videoFormat`

### To Reproduce

Unfurnately the only provider that i know have DRM AV1 is n€tflix
i dont know if there are DRM test streams AV1 or VP9 Profile 2 did not find any

1. install n€tflix addon
2. on addon expert settings enable AV1 and disable all other codecs
3. configure ISA to ask video quality, in order to make sure to play an AV1 stream
4. play a video recently added to the catalogue (the old movies/tvshow can not have AV1), at today "Dune" film is AV1 (but may change in future)

### Debuglog

The debuglog can be found here:
[kodi_AV1.log](https://github.com/xbmc/xbmc/files/10841775/kodi_AV1.log)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

if i replace the video format hardcoded here
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp#L351-L353
with the correct format required for the DRM stream, so `AV_PIX_FMT_YUV420P10`
the image is rendered correctly on screen, as follow:
immagine

i opened related Issue to the InputStream Adaptive repository:
https://github.com/xbmc/inputstream.adaptive/issues/1174

Tested on Windows, but affect all operative systems

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Kodi 21 master branch (ofc Kodi 20 also affected)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Currently binary addons that have an internal video decoder are forced to use `AV_PIX_FMT_YUV420P` video format:
https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp#L351-L353

this implementation allow to change the video format by the one provided by picture data

## Motivation and context

attempt to fix #22879

## How has this been tested?

to test its required ISAdaptive PR: https://github.com/xbmc/inputstream.adaptive/pull/1177
and follow instructions on Issue #22879

## What is the effect on users?

allow to playback video streams that have video formats differents from `AV_PIX_FMT_YUV420P`,
like AV1 / VP9 Profile 2

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/addons/kodi-dev-kit/include/kodi/versions.h [hunk 1]
```diff
@@ -174,7 +174,7 @@
 #define ADDON_INSTANCE_VERSION_VISUALIZATION_DEPENDS  "addon-instance/Visualization.h" \
                                                       "c-api/addon-instance/visualization.h"
 
-#define ADDON_INSTANCE_VERSION_VIDEOCODEC             "2.0.3"
+#define ADDON_INSTANCE_VERSION_VIDEOCODEC             "2.0.4"
 #define ADDON_INSTANCE_VERSION_VIDEOCODEC_MIN         "2.0.1"
```
Comment (ksooo) [inline xbmc/addons/kodi-dev-kit/include/kodi/versions.h:178]: As you are *inserting* new enum values, numeric value of VIDEOCODEC_FORMAT_MAXFORMATS will be changed, thus breaking every add-on that uses this value. 

ADDON_INSTANCE_VERSION_VIDEOCODEC_MIN need to be increased and all Videocodec add-ons need to be recompiled / version-bumped / re-released. ADDON_INSTANCE_VERSION_VIDEOCODEC_MIN

**Review by ksooo — CHANGES_REQUESTED** [review]

File: xbmc/addons/kodi-dev-kit/include/kodi/versions.h (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/addons/kodi-dev-kit/include/kodi/versions.h]: thanks i had forgot about max value

Comment (CastagnaIT) [reply xbmc/addons/kodi-dev-kit/include/kodi/versions.h]: i have not found other video binary addons that integrate a video decoder that use these includes
do you know someone?

Comment (ksooo) [reply xbmc/addons/kodi-dev-kit/include/kodi/versions.h]: I only know about inputstream.adpative,  but I might be wrong on this.

Comment (CastagnaIT) [reply xbmc/addons/kodi-dev-kit/include/kodi/versions.h]: i tried search also on pvr not found uses,
sice its limited use i can also backport to nexus?

Comment (ksooo) [reply xbmc/addons/kodi-dev-kit/include/kodi/versions.h]: > sice its limited use i can also backport to nexus?

Usually we do not backport breaking API changes. Not sure who can judge on this as @AlwinEsch, our binary add-on system maintainer, is currently not active.

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp [hunk 2]
```diff
@@ -16,6 +16,71 @@
...
+      return AV_PIX_FMT_YUV422P12;
+    case VIDEOCODEC_FORMAT_YUV444P9:
+      return AV_PIX_FMT_YUV444P9;
+    case VIDEOCODEC_FORMAT_YUV444P10:
+      return AV_PIX_FMT_YUV444P10;
+    case VIDEOCODEC_FORMAT_YUV444P12:
+      return AV_PIX_FMT_YUV444P12;
+    default:
+      CLog::LogF(LOGWARNING,
+                 "CInputStreamAddon: Video pixel format '{}' not valid, fallback to YUV420P.",
```
Comment (ksooo) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp:49]: "CInputStreamAddon" - this looks wrong. This is a free function, thus not bound to a class. Maybe use `CAddonVideoCodec`?

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp [hunk 3]
```diff
@@ -16,6 +16,71 @@
...
+    case VIDEOCODEC_FORMAT_YUV422P10:
+    case VIDEOCODEC_FORMAT_YUV444P10:
+      return 10;
+    case VIDEOCODEC_FORMAT_YUV420P12:
+    case VIDEOCODEC_FORMAT_YUV422P12:
+    case VIDEOCODEC_FORMAT_YUV444P12:
+      return 12;
+    default:
+      CLog::LogF(LOGWARNING,
+                 "CInputStreamAddon: Video pixel format '{}' not valid, fallback to 8 bit.",
```
Comment (ksooo) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp:76]: "CInputStreamAddon" - this looks wrong. This is a free function, thus not bound to a class. Maybe use `CAddonVideoCodec`?

**Review by ksooo — APPROVED** [review]

**Review by ksooo — COMMENTED** [review]
log message content should be fixed.

File: xbmc/addons/kodi-dev-kit/include/kodi/versions.h (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/addons/kodi-dev-kit/include/kodi/versions.h]: i know, since there will also be a braking change for the skins i thought maybe this could also be accepted
better to ask than nothing

Comment (phunkyfish) [reply xbmc/addons/kodi-dev-kit/include/kodi/versions.h]: We just never backport API changes. The number of users it can impact is immense. Not worth the risk.

Comment (CastagnaIT) [reply xbmc/addons/kodi-dev-kit/include/kodi/versions.h]: fine, i will coordinate with glennguy for merge this and make new release of ISAdaptive

**Comment by lrusak** [comment]
Note to self: I'll have to update CVideoBufferDMA to support the different pixel formats defined here.
