### PR TITLE
Fix CVideoInfoScanner strHash mismatch between linux and win32 platform

### LINKED ISSUE #26909: CVideoInfoScanner PathHash md5 mismatch between Windows and Linux platform using samba share
### Describe the bug
Here is a clear and concise description of what the problem is:

I've noticed a md5 calculation missmatch in the CVideoInfoScanner::GetPathHash() method (strHash value in "path" SQL table) between Windows and Linux.

I have a MySQL database shared between two machines: one Windows and one Linux. I noticed that every time I switched platforms, a “long” lib update would start.

I've checked if every datas given to Update() method of the CDigest class for difference.
Path string is same, items count is same, file/dir size is same... But, lowDateTime member of KODI::TIME::FileTime isn't the same!

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The md5 hash of CVideoInfoScanner::GetPathHash() should be the same between the platform.

## Actual Behavior

Md5 missmatch between Linux and Windows platform (and probably others too but not tested).

## Possible Fix

May I suggest to replace the binary format by a string one for the md5 digest update in GetPathHash() method?
https://github.com/xbmc/xbmc/blob/d0aaeea4d7062269801ad083e5ec30572db5c17b/xbmc/video/VideoInfoScanner.cpp#L2204
Something like that for exemple: `digest.Update(pItem->m_dateTime.GetAsLocalizedDateTime());`
EDIT:
GetAsLocalizedDateTime() return different output between Windows and Unix too...
Use the same formatter as IsPlugin() check instead:
`digest.Update(StringUtils::Format("{:02}.{:02}.{:04} {:02}:{:02}:{:02}", pItem->m_dateTime.GetDay(), pItem->m_dateTime.GetMonth(), ...));` 

To be compatible with the last master branch change on this part:
```
        const CDateTime& dateTime{pItem->GetDateTime()};
        if (dateTime.IsValid())
          digest.Update(StringUtils::Format("{:02}.{:02}.{:04}", dateTime.GetDay(),
                                            dateTime.GetMonth(), dateTime.GetYear()));
      }
      else
      {
        const int64_t size{pItem->GetSize()};
        digest.Update(&size, sizeof(size));
        KODI::TIME::FileTime time{};
        ---pItem->GetDateTime().GetAsTimeStamp(time);
        ---digest.Update(&time, sizeof(time));
        +++digest.Update(StringUtils::Format("{:02}.{:02}.{:04} {:02}:{:02}:{:02}", pItem->m_dateTime.GetDay(), pItem->m_dateTime.GetMonth(), pItem->m_dateTime.GetYear(), pItem->m_dateTime.GetHour(), pItem->m_dateTime.GetMinute(), pItem->m_dateTime.GetSecond()));

      }
      if (IsVideo(*pItem) && !PLAYLIST::IsPlayList(*pItem) && !pItem->IsNFO())
        count++;
```

### To Reproduce

1. Have a shared MySQL database or copy/paste a sqlite from a Windows system to a Linux one configured to use a samba share.
2. Start the Windows system and keep a backup of the database.
3. Start the Linux system.
4. Compare the database with backup, the strHash in the "path" table should be different (recomputed).

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/user-attachments/files/20931192/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Image

Image

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2 & Debian GNU/Linux 12
 - Kodi version: Omega 21.2

 - MySQL database

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by JackCarterSmith**
## Description

This PR will add consistency in datas used to compute the CVideoInfoScanner md5 strHash used to detect if folder need to be rescanned or not.

Technically, just force the DateTime into a common format instead of relying only on the OS FileTime conversion returned format, and force folder items list sorting (because the hash digest is serialized following the order of this list).

## Motivation and context

This PR is related to the opened issue #26909 

When sharing the same DB between multiples platform (like windows and linux) using a samba share for sources folders, the strHash value set in the "path" table of the MyVideo, Kodi rescan the unmodified source directory each time we switch of platform.
This behavior result in a relative slowdown of the library update (and at start of Kodi if auto-scan is enabled).

This bug was found in Omega 21.2 version of Kodi and seem partially fixed in the latest commit in master branch.
(FindFirstFileExW fixed only)
Other platforms than linux and windows can have this kind of hash missmatching between them.

## How has this been tested?

I've used my own actual usage case setup, in the following state:
- one windows 10 22H2 system,
- one linux debian 12 system,

both of them have used the [fc1ba27](https://github.com/xbmc/xbmc/commit/fc1ba2754b6201f6d532651917a446b5612ab430) last commit in date of this PR.
The same movies/tvshows database have been used in both case, with variants in the sub-folders structures in order to test many corners as possible.
I'm using mysql database for convenient use but sqlite file also works.

1. Running the kodi windows system first, update the library if not auto, that fill the database with its own computed hash.
2. Stopping the windows system (just stop the kodi program do the job too).
3. Dumping/clone the database as reference.
4. Repeat the step 1 to 2 with linux system this time.
5. Dump and compare the last database with the reference, the strHash will be identical for each entries.

## What is the effect on users?

This fix will trigger the directories rescan just one time for all existing setups (recompute the new uniform hash).

No others datas in the DB will be modified after that.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by garbear** [comment]
The fix looks correct. I'll get some artificial eyes on the code, and hopefully some squishy eyes come by too.

File: xbmc/video/VideoInfoScanner.cpp [hunk 1]
```diff
@@ -1035,6 +1035,9 @@ CVideoInfoScanner::~CVideoInfoScanner()
         // fast hash failed - compute slow one
         if (hash.empty())
         {
+          // force sorting consistency to avoid hash mismatch between platforms
+          // sort by filename as always present for any files, but keep case sensitiveness
+          items.Sort(SortByFile, SortOrderAscending, SortAttributeNone);
```
Comment (garbear) [inline xbmc/video/VideoInfoScanner.cpp:1321]: How does forcing sorting consistency avoid hash mismatches between platforms? Just seeking some more clarity. Also better is "case sensitivity".

File: xbmc/video/VideoInfoScanner.cpp [hunk 2]
```diff
@@ -2285,9 +2288,14 @@ CVideoInfoScanner::~CVideoInfoScanner()
       {
         const int64_t size{pItem->GetSize()};
         digest.Update(&size, sizeof(size));
-        KODI::TIME::FileTime time{};
-        pItem->GetDateTime().GetAsTimeStamp(time);
-        digest.Update(&time, sizeof(time));
+        // linux and windows platform don't follow the same output format (linux return a zero value for milliseconds member)
```
Comment (garbear) [inline xbmc/video/VideoInfoScanner.cpp]: Can you wrap comments at 80 chars for readers with small screens or large fonts?

File: xbmc/video/VideoInfoScanner.cpp [hunk 3]
```diff
@@ -2285,9 +2288,14 @@ CVideoInfoScanner::~CVideoInfoScanner()
...
+        // for consistency, use string format instead and discard milliseconds field.
+        // unless a modification occur during the 1 second window when kodi hash and update this particular file, we are safe.
+        const CDateTime& dateTime{pItem->GetDateTime()};
+        if (dateTime.IsValid())
+          digest.Update(StringUtils::Format("{:02}.{:02}.{:04} {:02}:{:02}:{:02}",
+                                            dateTime.GetDay(), dateTime.GetMonth(), dateTime.GetYear(),
+                                            dateTime.GetHour(), dateTime.GetMinute(), dateTime.GetSecond()));
```
Comment (garbear) [inline xbmc/video/VideoInfoScanner.cpp]: Small style nitpick, but if you surround the indented line with {}, it becomes easier to read when two blocks end at once below.

File: xbmc/video/VideoInfoScanner.cpp (hunk 1 above)
Comment (JackCarterSmith) [reply xbmc/video/VideoInfoScanner.cpp:1321]: While investigating why, despite the patch on DateTime, the hash was still different for directories, I found that Windows and Linux returned a different file list from CDirectory::EnumerateDirectory(). However, the hash depends on this order.

To ensure that the hash is not influenced (false positive in this case) by this difference specific to each platform. By forcing the order, we avoid detecting these false positives without compromising normal detection (making the whole process more robust).

File: xbmc/video/VideoInfoScanner.cpp (hunk 3 above)
Comment (JackCarterSmith) [reply xbmc/video/VideoInfoScanner.cpp]: I wasn't sure about the right structure to use, so when in doubt, I used the same one as above.

Comment (garbear) [reply xbmc/video/VideoInfoScanner.cpp]: The team decided to modernize and improve code when touched, instead of conforming to something probably written decades ago. Good job adding the `{}` above too.

File: xbmc/video/VideoInfoScanner.cpp [hunk 4]
```diff
@@ -2278,16 +2281,27 @@ CVideoInfoScanner::~CVideoInfoScanner()
...
+        // (linux return a zero value for milliseconds member).
+        // for consistency, use string format instead and discard milliseconds 
+        // field. Unless a modification occur during the 1 second window when 
+        // kodi hash and update this particular file, we are safe.
+        const CDateTime& dateTime{pItem->GetDateTime()};
+        if (dateTime.IsValid())
+        {
+          digest.Update(StringUtils::Format("{:02}.{:02}.{:04} {:02}:{:02}:{:02}", 
+                                            dateTime.GetDay(), dateTime.GetMonth(), dateTime.GetYear(), 
+                                            dateTime.GetHour(), dateTime.GetMinute(), dateTime.GetSecond()));
```
Comment (CrystalP) [inline xbmc/video/VideoInfoScanner.cpp]: Looking at the details of CDateTime, more efficient for similar and equally valid result:
```suggestion
          digest.Update(dateTime.GetAsDBDateTime());
```
However most likely even more efficient, convert the CDateTime to a time_t, which has a resolution of the second, which should align linux and Windows behavior, without the relatively more costly conversion to text.
```
        time_t tt{};
        pItem->GetDateTime().GetAsTime(tt);
        digest.Update(&tt, sizeof(tt));
```

... with a nice explanation comment, similar to what you added.

**Comment by CrystalP** [comment]
Thanks for investigating.
I wonder how common this is and why it didn't come up in the testing of #23631, also about hash differences between Windows and Android (uses the same samba client as linux as far as I know)

A few comments/questions:
- are movies not impacted? the change only takes care of the tv shows path.
- does the fasthash work correctly? it should since the digest is built with the addition of the files times (commutative) and the time is retrieved differently, avoiding both reported sources of differences.

- missing milliseconds in linux: I'm not a linux dev but it looks like Kodi hasn't been updated to use the more capable struct timespec instead of time_t. But there isn't much need for that accuracy in Kodi so doing the opposite and decreasing the precision of Windows is probably more practical.
See suggestion comment for the implementation. Benchmarking (ideally with a resource-constrained box) would be handy to confirm the best way forward.

- items sort is not light, did you compare performance before/after? no need for a fancy sort operator, a simple binary comparison would do but not sure how much performance difference we're talking about and whether it'd be worth the effort.

File: xbmc/video/VideoInfoScanner.cpp (hunk 4 above)
Comment (JackCarterSmith) [reply xbmc/video/VideoInfoScanner.cpp]: Ah indeed, I've missed GetAsDBDateTime when looking for a similar method... Nice look!
I'll give it a try yo the second option...

**Comment by JackCarterSmith** [comment]
I missed this one too... I didn't used the good key-words (only hash and parser/scanner).
But yes, look similar to this issue (android is a linux after all, I had my suspicions about this platform as well.)

For the questions:
- I've got issues on both Movies and TVShows, you mean the "sort" affect only the TVShows path? I'll give a look. The GetPathHash seem to be universal between Movies and TVShows.
- At the beginning of my debugging, I tested both Fast and "normal" hash. Fast seem to work (as the hash are good for some entries). I've added log to see when it use fast or normal, and got mismatch on elements who can't be "fasthashed" (fallback to normal). So I focused my effort on the GetPathHash to handle the "worst" case.
- I didn't push too far the linux time conversion, it's a long pitfall... Getting running the milliseconds on linux seemed overkill, and I choose to reduce the precision instead (as only milliseconds field is zero-ed on linux platform).
- The linux machine is an 10th gen i3 with 8 GB of RAM, not slow but not fast too. I didn't notice a "huge" charge during sorting (~450 entries in the path table).
I can test it on limited VM with only 2 cores and 1 GB of RAM (to match the kodi recommanded settings) in order to have a more precise way than my "feeling" on screen. :)
As the linux machine doesn't recompute the hash everytime now, I skip ~5 minutes of rehash.

EDIT:
I've measured the impact of sorting on the VM case, and I've got nothing above 19 ms.

> 	Ligne  706: 2025-07-08 15:03:45.806 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne  707: 2025-07-08 15:03:45.806 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1264: 2025-07-08 15:03:46.220 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne 1265: 2025-07-08 15:03:46.220 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1287: 2025-07-08 15:03:46.270 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne 1288: 2025-07-08 15:03:46.270 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1311: 2025-07-08 15:03:46.318 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne 1312: 2025-07-08 15:03:46.318 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1340: 2025-07-08 15:03:46.390 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne 1341: 2025-07-08 15:03:46.390 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1359: 2025-07-08 15:03:46.425 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne 1360: 2025-07-08 15:03:46.425 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1382: 2025-07-08 15:03:46.533 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne 1383: 2025-07-08 15:03:46.534 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1486: 2025-07-08 15:03:46.741 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne 1487: 2025-07-08 15:03:46.741 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1547: 2025-07-08 15:03:46.867 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne 1548: 2025-07-08 15:03:46.867 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1559: 2025-07-08 15:03:46.881 T:1184    debug <general>: VideoInfoScanner: before movies sort call
> 	Ligne 1560: 2025-07-08 15:03:46.881 T:1184    debug <general>: VideoInfoScanner: after movies sort call
> 	Ligne 1568: 2025-07-08 15:03:47.145 T:1184    debug <general>: VideoInfoScanner: before tvshows sort call
> 	Ligne 1569: 2025-07-08 15:03:47.145 T:1184    debug <general>: VideoInfoScanner: after tvshows sort call

I've added the sorting to the movies path too (something got wrong with my cleanup). Let's be more specific...
Using fasthash (the default option) only movies and tvshows is sorted, BUT the fasthash sorting work between platform. I didn't see mismatch during my final test when pushing on github.
When the fasthash is forced disable, the "EnumerateSeriesFolder" sorting is used instead to compute hash (where I got hash difference between platform).

Note that locale time settings impact the time conversion too. If the platforms do not have the same local time settings, the time difference will occur again!

File: xbmc/video/VideoInfoScanner.cpp (hunk 4 above)
Comment (JackCarterSmith) [reply xbmc/video/VideoInfoScanner.cpp]: The 2nd option is confirmed working!

**Comment by garbear** [comment]
@JackCarterSmith Can you squash everything into a single commit and force-push? I'll also generate a new Jenkins patch.

Jenkins build this please.

**Comment by JackCarterSmith** [comment]
@garbear It's good, I've added the typo from jenkins too.

**Comment by garbear** [comment]
Thanks for the fix! This'll go out in v22 Alpha 1 in a few days.
