### PR TITLE
[python] Fix xmbc.getRegion("time")

### LINKED ISSUE #23974: [Python] xbmc.getRegion('time') returns wrong scheme if language is set to German
### Describe the bug
xbmc.getRegion('time') returns '%H:mm:ss' instead of the correct scheme '%H:%M:%S' when language settings is set to "German". 

From an addon that calculate some time expression, the xbmc.getRegion('time') is processed and logged. For a german language setting xbmc.getRegion('time') returns '%H:mm:ss' instead of '%H:%M:%S'. As a result time calculations with `<dateobject>.strftime()` will fail. If region is set to english, all is ok (returns '%I:%M:%S %p').

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Until Nexus the time scheme calculation is ok. Please revert or correct this.

## Actual Behavior

xbmc.getRegion('time') returns wrong scheme if german language is selected.

### To Reproduce

1. set Kodi to german language
2. create an addon or script that logged xbmc.getRegion('time')

### Debuglog

The debuglog can be found here: There's no complete debug.log as the following snippet describes the problem:
```
2023-10-21 16:24:11.804 T:4153     info <general>: [script.knftv.announcer 3.1.6+matrix] Local time format of client: %d.%m.%Y %H:mm:ss
2023-10-21 16:24:11.830 T:4153    error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'ValueError'>
                                                   Error Contents: time data '21.10.2023 20:15' does not match format '%d.%m.%Y %H:mm:ss'
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: tested on CoreElec, Ubuntu 20.04
 - Kodi version: 21 alpha2, still remains on beta1 (reported on kodinerds forum: https://www.kodinerds.net/thread/68354-filmtipps-im-freien-tv-anstehende-sendetermine/?postID=731770#post731770)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by mglae**
## Description

-  Always convert minutes and seconds, fix after #22982
- Complete time formatting codes from https://kodi.wiki/view/Language_support#langinfo.xml

## Motivation and context

Fixes #23974

## How has this been tested?

Local Linux build, locale set to German.

## What is the effect on users?

Regression fix.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
@mglae while at it do u mind adding a new commit to document the missing arguments from doxygen? https://github.com/xbmc/xbmc/blob/5a6255c2d7062befe8d02dcdd90a27b7c6728167/xbmc/interfaces/legacy/ModuleXbmc.h#L652

**Comment by mglae** [comment]
@enen92 Done.

Please review if you can confirm the return parameter clarification.

File: xbmc/interfaces/legacy/ModuleXbmc.h [hunk 1]
```diff
@@ -649,9 +649,12 @@ namespace XBMCAddon
     /// @param id                    string - id of setting to return
     /// @return                      Region setting
     ///
-    /// @note choices are (dateshort, datelong, time, meridiem, tempunit, speedunit)
-    ///        You can use the above as keywords for arguments.
+    /// @note choices are (dateshort, datelong, time, meridiem, tempunit, speedunit,
+    ///       datelongraw, dateshortraw, timeraw)
+    ///       You can use the above as keywords for arguments.
     ///
+    ///       If returning an empty string id is not supported (e.g. older Kodi
```
Comment (enen92) [inline xbmc/interfaces/legacy/ModuleXbmc.h:656]: Maybe make this a warning and improve the wording since it reads confusing to me (also drop the Kodi version reference):
`/// @warning an empty string is returned if the provided Id is not supported`

After this I think it is good to go

Comment (mglae) [reply xbmc/interfaces/legacy/ModuleXbmc.h]: Is changed.

**Review by enen92 — APPROVED** [review]
Thanks
