### PR TITLE
[webOS] Add new webOS videoplayer

### LINKED ISSUE #24193: WebOS - Audio is out of sync
### Describe the bug
Live Stream Video or MKV files with audio AAC codecs is out of sync. 

Change : last build from 05/12/20023: mkv with aac codec from local storage (nfs) plays in sync

Stream Video, live stream from TVHeadend [ maybe other clients also ] or MKV (H264,H265) files with audio AAC codecs is out of sync., 
but :
Stream Video , live stream from TVHeadend or MKV Files (H264,H265) with AC3, eAC3, DTS codec plays in sync

It is not possible to move the audio to get AV in sync. 
TV : LG OLEG65C, webOS 7
Audio Paththroug : ON 
AC3 transcoding : ON

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/gahukeyogo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [ x ] WebOS

 - Operating system version/name:
 - Kodi version:
WebOS7, Latest KODI build

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #25065: webos: No sound when using Starfish passthrough
### Describe the bug
When using the Starfish passthrough audio device I hear no sound when playing media files. My TV is a LG OLED C9 running webos version 05.30.40 with Kodi 21. The TV is connected via eARC to a Denon AVR. When using internal apps like Netflix the audio is passed to the AVR without problems.
But when using Kodi the AVR show that there is no audio signal coming from TV. If I switch the audio device in Kodi to ALSA default. I get sound, so it seems using Starfish passthrough is the problem.

## Expected Behavior
From what I read in the wiki and the forum passthrough should work ob webos.

## Actual Behavior
Starfish passthrough audio is not working with LG OLED C9 running webos 05.30.40 with Kodi 21

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
https://pastebin.com/0GBC9TF2

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] webos

 - Operating system version/name:
 - Kodi version: 21
 - webos: 05.30.40

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #25101: WebOS: Video stutters every few seconds with Live HD content
### Describe the bug
Here is a clear and concise description of what the problem is:

ARD/ZDF/ONE/KikaHD stutters in HD quality every ~3 seconds. The sound plays countinously. All other non-HD sources like SAT1/RTL are streaming fine.

TVHeadend client is used.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No stuttering video.

## Actual Behavior

HD video stutters every 3-4 seconds.

### To Reproduce

1. watch german HD tv like ARD/ZDF or any other channel in HD quality
2.
3.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

tried sound passthrough without success.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [X] WebOS

 - Operating system version/name: 8.3.0
 - Kodi version: 21.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #25231: Screensaver activates during playback (LG C9)
### Describe the bug
Here is a clear and concise description of what the problem is:
The TVs internal screensaver activates even during playback

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The screensaver activates only in the menu or when playback is paused

## Actual Behavior

The screensaver always activates after 2 minutes

## Possible Fix

I have found documentation on how to prevent this potentially:
https://webostv.developer.lge.com/develop/guides/screensaver
https://webostv.developer.lge.com/faq/2024-04-09-how-can-i-set-my-app-to-play-video-in-full-screen

### To Reproduce

1.  Play any video
2.  Wait for 2 minutes

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/egusexodom.kod

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] webOS

 - Operating system version/name:  5.20.35
 - Kodi version: 22 ALPHA1 21.90.700
 - Git: 20240516-94b12dd1a8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #25589: LG Evo G4 WebOS  24 version 03.11.05 AV1/H264/H265 audio delay
### Describe the bug
Here is a clear and concise description of what the problem is:

On the LG Evo G4 running WebOS 24 version 03.11.05 all video formats types I have tested from a NAS.

- AV1
- H264
- H265

With the following audio formats

-  DTS
-  DTS uncompressed
- AC3
- ATMOS

I have added a 250ms delay and added passthrough via the menu. This fixes the initial audio delay I see in application.

The issue I see is as I advance from one episode or movie to the next, my audio delay becomes over 1 second and the delay added in menu no longer gives the delay seen. 

Stopping the video and starting again fixes the issue every time.

## Expected Behavior

No audio delay on start of application and on changing content

## Actual Behavior
Audio delay on all files worsening with change in content

## Possible Fix
Stop payback
Start Playback

### To Reproduce
1. Start video content (there will a noticable delay)
2. Add 250ms delay and save as default
3. Change episode. Delay returns

### Debuglog
Not consistent enough to generate debug log on demand. Seems to get worse the longer I watch content. OSD for debug makes that difficult to do with debug enabled.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] WebOS

 - Operating system version/name: WebOS 24 03.11.05
 - Kodi version: 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by sundermann**
## Description

Adds a new videoplayer for webOS in favor of the old separate video codec and audio sink. Video codec and audio sink code are mostly merged into one pipeline and the code is roughly similar.

## Motivation and context

With the current videoplayer where audio and video are handled separately, sync has always been an issue. This is because the public APIs we can use are very limited in that regard. Efforts to access the underlying gstreamer elements to get more advanced acess into synchronization were only partly successful.

That's why this PR introduces a new video player. It implements `IDVDStreamPlayerVideo` and `IDVDStreamPlayerAudio` feeding into a common pipeline. Synchronization is then handled by the webOS video APIs. It is still possible to set audio delay, subtitle delay etc.

There are a couple of commits improving the encoder and resampler. Those have been split into separate commits and should not affect platforms other than webOS.

## How has this been tested?

webOS 9
Users in the forum and on discord reported that sync issues are fixed and functionality on webOS 4 was restored.

## What is the effect on users?

Fixes #24193
Fixes #25589
Fixes #25065
Potentially fixes #25101
Potentially fixes #25231

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [x] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 1]
```diff
@@ -0,0 +1,1268 @@
...
+{
+  return m_audioInfo;
+}
+
+std::string CMediaPipelineWebOS::GetVideoInfo() const
+{
+  return m_videoInfo;
+}
+
+bool CMediaPipelineWebOS::Supports(const AVCodecID codec)
```
[the remark this answers is not in the document]
Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp:270]: Function is static.

File: xbmc/cores/VideoPlayer/VideoPlayerWebOS.cpp [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+  else if (m_mediaPipelineWebOS || (!m_VideoPlayerVideo && !m_VideoPlayerAudio))
+  {
+    delete m_VideoPlayerVideo;
+    delete m_VideoPlayerAudio;
+    m_mediaPipelineWebOS = nullptr;
+    m_VideoPlayerVideo =
+        new CVideoPlayerVideo(&m_clock, &m_overlayContainer, m_messenger, m_renderManager,
+                              *m_processInfo, m_messageQueueTimeSize);
+    m_VideoPlayerAudio =
+        new CVideoPlayerAudio(&m_clock, m_messenger, *m_processInfo, m_messageQueueTimeSize);
```
[the remark this answers is not in the document]
Comment (sundermann) [reply xbmc/cores/VideoPlayer/VideoPlayerWebOS.cpp]: Existing code. `Videoplayer` generally could make use of smart pointers but I don't want to make this PR bigger than it already is.

File: xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp [hunk 3]
```diff
@@ -114,8 +115,28 @@ bool CAEEncoderFFmpeg::Initialize(AEAudioFormat &format, bool allow_planar_input
 
   m_CodecCtx->bit_rate = m_BitRate;
   m_CodecCtx->sample_rate = format.m_sampleRate;
+
```
[the remark this answers is not in the document]
Comment (sundermann) [reply xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp:116]: Just leaving the old behavior as is.

**Comment by sundermann** [comment]
Test build here: https://mirrors.kodi.tv/test-builds/webos/org.xbmc.kodi_20250719-483c5eff-webos-videoplayer_arm.ipk

File: xbmc/cores/VideoPlayer/CMakeLists.txt [hunk 4]
```diff
@@ -43,4 +43,9 @@ set(HEADERS AudioSinkAE.h
             Interface/InputStreamConstants.h
             Interface/TimingConstants.h)
 
+if("webos" IN_LIST CORE_PLATFORM_NAME_LC)
+    list(APPEND SOURCES MediaPipelineWebOS.cpp VideoPlayerWebOS.cpp)
+    list(APPEND HEADERS MediaPipelineWebOS.h VideoPlayerWebOS.h)
+endif()
```
Comment (neo1973) [inline xbmc/cores/VideoPlayer/CMakeLists.txt]:
```suggestion
if("webos" IN_LIST CORE_PLATFORM_NAME_LC)
    list(APPEND SOURCES MediaPipelineWebOS.cpp
                        VideoPlayerWebOS.cpp)
    list(APPEND HEADERS MediaPipelineWebOS.h
                        VideoPlayerWebOS.h)
endif()
```

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 5]
```diff
@@ -0,0 +1,1278 @@
...
+  std::ostringstream s;
+  s << "aq:" << std::setw(2) << std::min(99, m_messageQueueAudio.GetLevel());
+  s << "% " << std::fixed << std::setprecision(3) << m_messageQueueAudio.GetTimeSize();
+  s << "s, Kb/s:" << std::fixed << std::setprecision(2) << m_audioStats.GetBitrate() / 1024.0;
+  if (m_audioEncoder)
+  {
+    s << ", transcoded ac3";
+  }
+
+  m_audioInfo = s.str();
```
Comment (neo1973) [inline xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]:
```suggestion
  m_audioInfo = std::move(s).str();
```

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 6]
```diff
@@ -0,0 +1,1278 @@
...
+  std::ostringstream s;
+  s << "vq:" << std::setw(2) << std::min(99, m_processInfo.GetLevelVQ());
+  s << "% " << std::fixed << std::setprecision(3) << m_messageQueueVideo.GetTimeSize();
+  s << "s, Mb/s:" << std::fixed << std::setprecision(2)
+    << static_cast<double>(GetVideoBitrate()) / (1024.0 * 1024.0);
+  s << ", fr:" << std::fixed << std::setprecision(3)
+    << static_cast<double>(m_videoHint.fpsrate) / static_cast<double>(m_videoHint.fpsscale);
+  s << ", drop:" << m_droppedFrames;
+
+  m_videoInfo = s.str();
```
Comment (neo1973) [inline xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]:
```suggestion
  m_videoInfo = std::move(s).str();
```

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 7]
```diff
@@ -0,0 +1,1278 @@
...
+    default:
+      break;
+  }
+
+  using namespace KODI::WINDOWING::WAYLAND;
+  const auto winSystem = dynamic_cast<CWinSystemWaylandWebOS*>(CServiceBroker::GetWinSystem());
+  if (winSystem->SupportsExportedWindow())
+  {
+    std::string exportedWindowName = winSystem->GetExportedWindowName();
+    p["option"]["windowId"] = exportedWindowName;
```
Comment (neo1973) [inline xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]: To ensure the string is moved into the variant:
```suggestion
    p["option"]["windowId"] = winSystem->GetExportedWindowName();
```

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 8]
```diff
@@ -0,0 +1,1278 @@
...
+void CMediaPipelineWebOS::SetHDR(const CDVDStreamInfo& hint) const
+{
+  if (hint.hdrType == StreamHdrType::HDR_TYPE_NONE)
+    return;
+
+  CVariant hdrData;
+  CVariant sei;
+
+  if (ms_hdrInfoMap.contains(hint.colorTransferCharacteristic))
+    hdrData["hdrType"] = ms_hdrInfoMap.at(hint.colorTransferCharacteristic).data();
```
Comment (neo1973) [inline xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]:
```suggestion
    hdrData["hdrType"] = std::string(ms_hdrInfoMap.at(hint.colorTransferCharacteristic));
```

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 9]
```diff
@@ -0,0 +1,1278 @@
...
+      auto player = static_cast<mediapipeline::CustomPlayer*>(m_mediaAPIs->player.get());
+      auto pipeline = static_cast<mediapipeline::CustomPipeline*>(player->getPipeline().get());
+      MEDIA_CUSTOM_CONTENT_INFO_T contentInfo;
+      pipeline->loadSpi_getInfo(&contentInfo);
+      contentInfo.ptsToDecode = pts.count();
+      pipeline->setContentInfo(MEDIA_CUSTOM_SRC_TYPE_ES, &contentInfo);
+    }
+
+    auto player = static_cast<mediapipeline::CustomPlayer*>(m_mediaAPIs->player.get());
+    auto pipeline = static_cast<mediapipeline::CustomPipeline*>(player->getPipeline().get());
```
Comment (neo1973) [inline xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]:
```suggestion
    auto player = static_cast<mediapipeline::CustomPlayer*>(m_mediaAPIs->player.get());
    auto pipeline = static_cast<mediapipeline::CustomPipeline*>(player->getPipeline().get());
    
    if (!m_mediaAPIs->setTimeToDecode(payload.c_str()))
    {
      CLog::LogF(LOGERROR, "setTimeToDecode failed");
      MEDIA_CUSTOM_CONTENT_INFO_T contentInfo;
      pipeline->loadSpi_getInfo(&contentInfo);
      contentInfo.ptsToDecode = pts.count();
      pipeline->setContentInfo(MEDIA_CUSTOM_SRC_TYPE_ES, &contentInfo);
    }
```

File: xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp [hunk 10]
```diff
@@ -36,9 +36,10 @@ CAEEncoderFFmpeg::CAEEncoderFFmpeg() : m_CodecCtx(NULL), m_SwrCtx(NULL)
 CAEEncoderFFmpeg::~CAEEncoderFFmpeg()
 {
   Reset();
-  swr_free(&m_SwrCtx);
-  av_channel_layout_uninit(&m_CodecCtx->ch_layout);
-  avcodec_free_context(&m_CodecCtx);
+  if (m_SwrCtx)
+    swr_free(&m_SwrCtx);
+  if (m_CodecCtx)
+    avcodec_free_context(&m_CodecCtx);
```
Comment (neo1973) [inline xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp]: `swr_free` and `avcodec_free_context` check themself if they are already null.

https://github.com/FFmpeg/FFmpeg/blob/722a2170e83231283fc74bede495b3b4ee9591ac/libswresample/swresample.c#L121

https://github.com/FFmpeg/FFmpeg/blob/722a2170e83231283fc74bede495b3b4ee9591ac/libavcodec/options.c#L164

**Review by neo1973 — COMMENTED** [review]
Sounds very exciting! Unfortunately I don't have the hardware to test, but browsing through the code I spotted a couple of places that may need attention.

File: xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp (hunk 10 above)
Comment (sundermann) [reply xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp]: Interesting, I've removed the checks. `av_channel_layout_uninit` was causing the issue as the access to the member variable is unsafe as `m_CodecCtx` can be null. I've changed the commit. The whole encoder class could use an overhaul. Half of the code is completely unused (like m_SwrCtx which is set but never used).

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp (hunk 5 above)
Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]: Does moving the `std::ostringstream` do anything?

Comment (neo1973) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]: It causes the rvalue overload of [`std::ostringstream::str()`](https://en.cppreference.com/w/cpp/io/basic_ostringstream/str.html) to be called which moves the underlying `std::string` out of the stream instead of copying it.

Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]: I think `std::ostringstream` doesn't have a move-optimized version. This code is mostly copied from the original `VideoPlayer*` classes and maybe using `std::format` could be a better fit here?

Comment (neo1973) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]: > I think `std::ostringstream` doesn't have a move-optimized version.

Overload (3) from the link?

Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]: Thanks for the explaining! I didn't knew there was a new overload in C++20. Commited the change

Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]: I actually refactored these functions to use `std::format` which is a lot more readable (and faster?) than the `stringstream` approach.

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.h [hunk 11]
```diff
@@ -0,0 +1,440 @@
...
+
+private:
+  CMediaPipelineWebOS& m_mediaPipeline;
+};
+
+/**
+ * @class CVideoPlayerAudioWebOS
+ * @brief Audio stream player adapter forwarding to CMediaPipelineWebOS.
+ */
+class CVideoPlayerAudioWebOS final : public IDVDStreamPlayerAudio
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: Can separate classes be split into separate files? I got a little scared when I saw a 440 line header, not realizing it was multiple classes.

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 12]
```diff
@@ -0,0 +1,1275 @@
+/*
+*  Copyright (C) 2005-2025 Team Kodi
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]: Oopsie

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.h (hunk 11 above)
Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: Sure but those two classes mostly just forward into the pipeline class.

Comment (garbear) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: OK.

Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: They live in their own header files now. Do you think that's alright or should I also split the definitions into their own cpp files?

Comment (garbear) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: I'd split. Files are cheap, and long headers should be avoided. IMO it also helps to see the architecture at a FS level before diving into the code.

**Review by garbear — APPROVED** [review]
I didn't scan MediaPipelineWebOS.cpp in depth, but at a level above that this looks good. I like the documentation in CMediaPipelineWebOS.

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.h (hunk 11 above)
Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: Done, CLions split function definition is great

**Review by neo1973 — APPROVED** [review]

**Comment by sundermann** [comment]
Can someone put [webos-userland 0.0.13](https://github.com/webosbrew/webos-userland/releases/tag/0.0.13) on the mirrors?

File: xbmc/cores/VideoPlayer/VideoPlayerWebOS.cpp [hunk 13]
```diff
@@ -0,0 +1,76 @@
...
+        *m_processInfo, m_renderManager, m_clock, m_messenger, m_overlayContainer, hasAudio);
+    m_VideoPlayerVideo = new CVideoPlayerVideoWebOS(*m_mediaPipelineWebOS, *m_processInfo);
+    m_VideoPlayerAudio = new CVideoPlayerAudioWebOS(*m_mediaPipelineWebOS, *m_processInfo);
+
+    const CVideoSettings settings = m_processInfo->GetVideoSettings();
+    m_VideoPlayerVideo->EnableSubtitle(settings.m_SubtitleOn);
+    m_VideoPlayerVideo->SetSubtitleDelay(
+        static_cast<int>(-settings.m_SubtitleDelay * DVD_TIME_BASE));
+  }
+  else if (m_mediaPipelineWebOS || (!m_VideoPlayerVideo && !m_VideoPlayerAudio))
```
[the remark this answers is not in the document]
Comment (sundermann) [reply xbmc/cores/VideoPlayer/VideoPlayerWebOS.cpp:56]: No, the function is called twice. We only setup once streams are known

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 14]
```diff
@@ -0,0 +1,1413 @@
...
+      CLog::LogF(LOGERROR, "Pipeline STR_ERROR numValue: {}, strValue: {}", numValue, logStr);
+      break;
+    default:
+      break;
+  }
+
+  m_eventCondition.notify_all();
+}
+
+void CMediaPipelineWebOS::PlayerCallback(const int32_t type,
```
[the remark this answers is not in the document]
Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp:1458]: Variables are atomic and it doesn't really matter if they are properly synchronized as most of it is just for reporting stuff

File: xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererStarfish.cpp [hunk 15]
```diff
@@ -108,26 +109,29 @@ void CRendererStarfish::ManageRenderArea()
...
     {
-      AcbAPI_setCustomDisplayWindow(m_acbId, m_sourceRect.x1, m_sourceRect.y1, m_sourceRect.Width(),
-                                    m_sourceRect.Height(), m_destRect.x1, m_destRect.y1,
-                                    m_destRect.Width(), m_destRect.Height(), false, nullptr);
+      AcbAPI_setCustomDisplayWindow(
+          m_videoBuffer->m_acbId, static_cast<long>(m_sourceRect.x1),
+          static_cast<long>(m_sourceRect.y1), static_cast<long>(m_sourceRect.Width()),
+          static_cast<long>(m_sourceRect.Height()), static_cast<long>(m_destRect.x1),
+          static_cast<long>(m_destRect.y1), static_cast<long>(m_destRect.Width()),
+          static_cast<long>(m_destRect.Height()), false, &m_videoBuffer->m_taskId);
```
[the remark this answers is not in the document]
Comment (sundermann) [reply xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererStarfish.cpp]: It can't be null

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 16]
```diff
@@ -0,0 +1,1413 @@
...
+  {
+    m_audioStats.AddSampleBytes(packet->iSize);
+    UpdateAudioInfo();
+    return;
+  }
+
+  if (result.find("BufferFull") != std::string::npos)
+  {
+    m_messageQueueAudio.PutBack(msg);
+    std::this_thread::sleep_for(100ms);
```
[the remark this answers is not in the document]
Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp:969]: Intentional

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp [hunk 17]
```diff
@@ -0,0 +1,1413 @@
...
+
+  HContext requestContext;
+  requestContext.pub = true;
+  requestContext.multiple = false;
+  requestContext.callback = [](LSHandle* sh, LSMessage* msg, void* ctx)
+  {
+    CVariant config;
+    CJSONVariantParser::Parse(HLunaServiceMessage(msg), config);
+    if (config["configs"]["tv.model.edidType"].asString().find("dts") != std::string::npos)
+      ms_codecMap.emplace(AV_CODEC_ID_DTS, "DTS");
```
[the remark this answers is not in the document]
Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.cpp]: Fixed, though I guess in practice this shouldn't had mattered

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.h [hunk 18]
```diff
@@ -0,0 +1,385 @@
...
+
+/**
+  * @class CMediaPipelineWebOS
+  * @brief WebOS media pipeline for audio/video playback.
+  */
+class CMediaPipelineWebOS final : public CThread
+{
+public:
+  /**
+  * @brief Construct the WebOS media pipeline.
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: Still bad indentation in this file.

File: xbmc/cores/VideoPlayer/MediaPipelineWebOS.h [hunk 19]
```diff
@@ -37,9 +37,9 @@ class CDVDAudioCodec;
 class StarfishMediaAPIs;
 
 /**
-  * @class CMediaPipelineWebOS
-  * @brief WebOS media pipeline for audio/video playback.
-  */
+* @class CMediaPipelineWebOS
```
Comment (garbear) [inline xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: Your IDE just does not like you.

Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: Looks alright to me? I don't know what the exact formatting rules on doxygen comments are. I looked at a couple of files for reference but it's all over the place and clang-format generally doesn't format these at all

Comment (sundermann) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: I just found `ReflowComments: IndentOnly` which does allow clang-format to properly work. Should be alright now. Maybe we should set that clang-format option by default though.

Comment (garbear) [reply xbmc/cores/VideoPlayer/MediaPipelineWebOS.h]: Yeah, if the clang-format option helps, maybe add it.

**Comment by sundermann** [comment]
Squashed the commits as I think all?/most of the issues from the initial PR that came up from testing on the forums are adressed now. I would consider this mostly feature complete.

**Comment by rcorex** [comment]
tested build org.xbmc.kodi_20250731-e453465f-webos-videoplayer_arm.ipk on an LG C9 - the LG 'fireworks' screensaver turns on while video is playing with this build. this does not happen with the nightly build org.xbmc.kodi_20250804-805b5f0e-master_arm.ipk.

**Comment by sundermann** [comment]
@rcorex We've had people on the forums with a C9 and they've not reported that the screensaver wasn't working. Weird stuff. Unfortunately, webOS 4 is vastly different from webOS 5+ and I do not own one myself.

I want to move forward with this PR though and hope to figure out why that's happening (sometimes?) on webOS 4 and address it in a followup PR.

**Comment by jeanmoulart** [comment]
@sundermann I was about to get a shield pro because of the audio sync issue I couldn't fix with any of the suggested workarounds. This commit solved all audio issues I had encountered.

Thanks a **lot**!
