### PR TITLE
[linux] TestSysfsPath: Use unique file name for every test

### LINKED ISSUE #18000: Test failures building Debian package using pbuilder / sbuild
### Describe the bug

Here I will drop test failures and fixes for tests breaking Debian build similar to issue created by @candrews 

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian GNU/Linux 10 buster
 - Kodi version: 19.0 trunk

### PR DESCRIPTION
**Pull request by basilgello**
## Description

Fixes #18000 

## Motivation and Context

The hard-coded file name in TestSysfsPath introdices random test failures
on data race.

## How Has This Been Tested?

Build Debian package using pbuilder 

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/platform/linux/test/TestSysfsPath.cpp [hunk 1]
```diff
@@ -8,24 +8,38 @@
...
+  std::string GetTestFilePath()
+  {
+    using namespace std::chrono;
 
-  std::ofstream m_output{"/tmp/kodi-test"};
+    std::stringstream ss;
+    unsigned long long timestamp = duration_cast< nanoseconds >(
+      system_clock::now().time_since_epoch()).count();
+
+    ss << "/tmp/kodi-test" << timestamp;
```
Comment (garbear) [inline xbmc/platform/linux/test/TestSysfsPath.cpp:28]: Resulting path might be more readable if you add a dash between `test` and the timestamp:

```
"/tmp/kodi-test-" << timestamp
```

**Review by wsnipex — COMMENTED** [review]
it would be better not to hardcode /tmp as path and use $TMPDIR env var

File: xbmc/platform/linux/test/TestSysfsPath.cpp (hunk 1 above)
Comment (basilgello) [reply xbmc/platform/linux/test/TestSysfsPath.cpp]: Done! As well as Wolfgang's point.

File: xbmc/platform/linux/test/TestSysfsPath.cpp [hunk 2]
```diff
@@ -8,24 +8,44 @@
...
 {
-  ~TestSysfsPath() { std::remove("/tmp/kodi-test"); }
+  std::string GetTestFilePath()
+  {
+    using namespace std::chrono;
 
-  std::ofstream m_output{"/tmp/kodi-test"};
+    const char *test_tmpdir = getenv("TMPDIR");
+    if (!test_tmpdir || test_tmpdir[0] == '\0') {
+      return "";
```
Comment (wsnipex) [inline xbmc/platform/linux/test/TestSysfsPath.cpp:26]: we need a fallback when TMPDIR is not set, which will often be the case:
```suggestion
      test_tmpdir = "/tmp/kodi-test";
```

**Comment by basilgello** [comment]
@wsnipex the empty string is used here to fatal-assert the test indicating problems with chroot.
However I can change it to:

```c++
std::string tmpdir = "/tmp";
const char * test_tmpdir = getenv("TMPDIR");

if (test_tmpdir && test_tmpdir[0] != '\0') {
  tmpdir = test_tmpdir;
}

ss << tmpdir << "/kodi-test-" << nanoseconds << std::endl;
```

and remove ASSERT_CMPNEs from both test declarations.

**Review by wsnipex — APPROVED** [review]

**Comment by basilgello** [comment]
Since it has been approved, can we have this change merged please?

**Comment by phunkyfish** [comment]
Sure, will merge shortly.

**Comment by basilgello** [comment]
Thanks Ross! :)
