### PR TITLE
[JPGDecoder] Prevent wrong buffer size through integer overflow

### LINKED ISSUE #24956: Buffer Overflow in JPGDecoder::LoadFile
### Describe the bug
Here is a clear and concise description of what the problem is:

The vulnerable JPGDecoder::LoadFile function in file JPGDecoder.cpp (https://github.com/xbmc/xbmc/blob/master/tools/depends/native/TexturePacker/src/decoder/JPGDecoder.cpp) is used to decompress jpegs and create a raw bitmap version of the image.

In JPGDecoder::LoadFile, the values for cinfo.image_width and cinfo.image_height are retrieved directly from a jpeg file's header.

cinfo.image_width and cinfo.image_height can be manipulated by editing the header of the jpeg file being processed. They are two bytes each in the image's header so their values can range from 0x0000 to 0xFFFF. These variables are multiplied by 4.

When these three values are multiplied together they can exceed the limit of a 32-bit unsigned integer, leading to an integer overflow vulnerability. This product is used to set the size of pixels vector, which will store the decompressed jpeg (https://github.com/xbmc/xbmc/blob/master/tools/depends/native/TexturePacker/src/decoder/JPGDecoder.cpp#L97). When the sizing arguments overflow, the vector becomes too small to store the decompressed data.

The program writes the decompressed image to the array using the jpeg_read_scanlines function. The function ends up writing to out-of-bounds memory due to the vector’s small size (https://github.com/xbmc/xbmc/blob/master/tools/depends/native/TexturePacker/src/decoder/JPGDecoder.cpp#L107). This causes data in memory adjacent to the vector to be overwritten.

An attacker is in control of the image's height, width, and contents. This allows an attacker to craft an exploit to overwrite data in memory with data they control.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by neo1973**
## Description
Fixes #24956. Not sure if this could be exploited but certainly it doesn't hurt to make the calculation correct in every case.

## Motivation and context
Fixes #24956.

## How has this been tested?
Hasn't been tested.

## What is the effect on users?
None.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Review by fuzzard — APPROVED** [review]

File: tools/depends/native/TexturePacker/src/decoder/JPGDecoder.cpp [hunk 1]
```diff
@@ -80,21 +82,25 @@ bool JPGDecoder::LoadFile(const std::string &filename, DecodedFrames &frames)
...
   jpeg_create_decompress(&cinfo);
 
   jpeg_stdio_src(&cinfo, arq.getFP());
   jpeg_read_header(&cinfo, TRUE);
   jpeg_start_decompress(&cinfo);
 
-  // Image Size is calculated as (width * height * bytes per pixel = 4
-  ImageSize = cinfo.image_width * cinfo.image_height * 4;
+  // Image Size is calculated as width * height * bytes per pixel = 4
+  // Since image_width and image_height can be at most 0xFFFF, this is save from overflows
```
Comment (garbear) [inline tools/depends/native/TexturePacker/src/decoder/JPGDecoder.cpp:93]: "safe" not save

Comment (neo1973) [reply tools/depends/native/TexturePacker/src/decoder/JPGDecoder.cpp]: Whops, thanks :slightly_smiling_face:

**Review by garbear — APPROVED** [review]
LGTM
