### PR TITLE
[Windows] Fix SMB read chunk size when is not used FileCache

### LINKED ISSUE #18031: Libbluray full menu's and seamless branched UHD and Blurays cause glitches/audio drops and frame skips
### Describe the bug
Here is a clear and concise description of what the problem is:

Hi there
i have found that when using the full menu system for bluray and UHD's if the movie is what i believe to be called seamless branched or multi-angle, when these changes happen varying results happen, with my nvidia set up i get frame skips and audio drop outs until the file change has settled usually a few seconds, with an intel setup i get horrid pixel coruption and audio drop outs, so far i have the in UHD format the the Phantom Menace, Attack of the Clones do this when ever a scene requires the subtitles to be displayed for alien speak, X-men Dark Pheonix also does this, and for standard blu-ray X-men Days of Future Past the rogue cut does it as you can play theatrical version or the rogue cut

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

the film should play flawless without interuption

## Actual Behavior

the film does not play seamless and interupts the enjoyment

## Possible Fix

i so wish i was smart enough

### To Reproduce

1. the only steps i have found so far is to play a full blu ray rip using menu's and the movie use the seamless branching method or multi angle will try and update the movie list as and when i find more
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/zorocexezu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

forum topic i opened for this https://forum.kodi.tv/showthread.php?tid=354431

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

i have tested all the affected movies using VLC as this was the only other player i knew that used Libbluray, there latest version was using libbluray 1.2.0 and all films played back flawless, i tried moving those files to kodi and renaming to version 1.1.2 although the movie played it would only get to the language selection screen and i couldn't use the keyboard to progress, i then hunted down a version of VLC that used the same libbluray as kodi this was version 3.08 and again the movies played flawless with no skips or audio drop outs so it looks like a problem with Kodi and not libbluray

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: windows 10 2004
 - Kodi version: v19 nightly, v19 HDR branch and V18 coreelec branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Fix SMB read chunk size when is not used FileCache

Fixes https://github.com/xbmc/xbmc/issues/18031

## Motivation and context
After https://github.com/xbmc/xbmc/pull/22897 found that SMB also has issues related to file chunk size.

In Android when not used FileCache chunk size is 64K instead of 128K when FileCache is used.

In Windows things are much worse and chunk size defaults to only 6144 bytes causing severe performance issues. This is reproducible playing Blu-Ray folders (BDMV) as by default are not used FileCache.

chunk-size

## How has this been tested?
Runtime tested Windows x64

## What is the effect on users?
Fixes severe issues at playback Blu-Ray's (BDMV) over SMB with default settings.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/platform/win32/filesystem/Win32File.cpp [hunk 1]
```diff
@@ -761,3 +761,11 @@ int CWin32File::Stat(struct __stat64* statData)
 
   return 0;
 }
+
+int CWin32File::GetChunkSize()
+{
+  if (m_smbFile)
+    return 128 * 1024;
```
Comment (thexai) [inline xbmc/platform/win32/filesystem/Win32File.cpp:768]: In Windows `CWin32File` is common for SMB and regular local files calls as is used built-in OS SMB API.

`m_smbFile` flag differentiates if is SMB file or local file. Only returns 128K size for SMB and zero for local files as before.

File: xbmc/platform/posix/filesystem/SMBFile.h [hunk 2]
```diff
@@ -79,7 +79,7 @@ class CSMBFile : public IFile
   bool OpenForWrite(const CURL& url, bool bOverWrite = false) override;
   bool Delete(const CURL& url) override;
   bool Rename(const CURL& url, const CURL& urlnew) override;
-  int GetChunkSize() override { return 64*1024; }
+  int GetChunkSize() override { return 128 * 1024; }
```
Comment (arnova) [inline xbmc/platform/posix/filesystem/SMBFile.h:82]: Are 100% sure 128K chunks won't cause any regressions? 64K has been around for ages and known to work....

**Comment by arnova** [comment]
When this is in, we should perhaps also consider removing the hack for zero-chunksize from CFileCache and just create a default implementation in IFile for GetChunkSize (of 64/128K)...

File: xbmc/platform/posix/filesystem/SMBFile.h (hunk 2 above)
Comment (arnova) [reply xbmc/platform/posix/filesystem/SMBFile.h:82]: > Nothing is certain but my reasoning is that 128K was already used with NFSv3 and the file types are the same. 128K is also used on Windows with FileCache: i.e. when size is zero or < 1 FileCache forces to use 128K chunk size (default in advanced settings).
> 
> Maybe we can merge it but not backport to 20.1 but wait until 20.2. Or backport only Windows commit as it fixes a major bug.
> 

Sounds good.

**Comment by arnova** [comment]
> > When this is in, we should perhaps also consider removing the hack for zero-chunksize from CFileCache and just create a default implementation in IFile for GetChunkSize (of 64/128K)...
> 
> There is one last piece of the puzzle to optimize: local files (USB files, external hard drives, etc). Shield has performance issues over USB but I don't know to what extent it's all due to Shield or something can be improved within Kodi.
> 
> The chunk size for local files is also important but I will do that in a separate PR so as not to mix concepts. I haven't done tests yet and I don't know to what extent there is something to improve or not.
> 
> I think the problem is not in the IFile but in the demuxers. That is to say, IFile is fine returning zero chunk size because it does not have any requirements and it does not even know if it is an audio/video file or a configuration text file.
> 
> When file is SMB/NFS forces chunk size of 64/128K this part is already fine.
> 
> But what happens now when file is not SMB/NFS and IFile returns 0 chunk size?
> 
> Maybe the demuxer should set a reasonable minimum when IFile and FileCache don't have any special requirements. That probably already exists (or not) but maybe it's not updated for the types of files that are handled today.
> 
> The demuxer has an advantage because it knows in advance if the file is a Blu-Ray etc... and can set a suitable chunk size.

Well my idea is that IFile should just always return a sane chunksize (instead of 0). So each implementation should either return a non-zero value and/or the override in IFile defaults to 128K....

**Comment by thexai** [comment]
I've decided to leave Android as it is for now and use 64K on Windows as well. The reason is that 64K is the default value that is used in `CFileStreamBuffer` and I want to use this value also for local files and in general use `CFileStreamBuffer` whenever FileCache is not used.

**Comment by thexai** [comment]
> Well my idea is that IFile should just always return a sane chunksize (instead of 0). So each implementation should either return a non-zero value and/or the override in IFile defaults to 128K....

There is a downside to this and that is that IFile is used in general for everything, i.e.: read xml configuration files, read true type fonts, skin/GUI resources, etc. Actually we only want to change things for the audio/video files.

I'm going to open another PR to fix this in the local files (USB files, etc.).

**Comment by thexai** [comment]
> I don't understand: what's the exact downside then? When reading stuff like xml, it's NOT read chunked, right? So in those cases it also doesn't matter which chunksize is returned by the implementation, correct?

Maybe I'm wrong in this then but it's not something we should solve in this PR since it only deals with chunk size in SMB (Windows). If the changes in this PR are correct, I would appreciate your approval in order to move forward.

**Review by arnova — APPROVED** [review]
