### PR TITLE
[ColorUtils] Add sort by alpha to color compare

### LINKED ISSUE #28010: Color sorting order in DialogColorPicker.xml
### Describe the bug
In its current form, the internal color picker does not support transparency. I am trying to work around this by creating ten levels of opacity descending from 100% to 10%, for each color in an existing color palette. Unfortunately, this only works to a limited extent because the colors are sorted incorrectly in the color picker. 
(It also depends on the color palette; the one shown here behaves very well. Other color palettes are considerably messier.)
Perhaps because function `comparePairColorInfo` in file [https://github.com/xbmc/xbmc/blob/master/xbmc/utils/ColorUtils.cpp](https://github.com/xbmc/xbmc/blob/master/xbmc/utils/ColorUtils.cpp) doesn't sort by transparency?

Kodi 21.3 / Windows

Image

[colors.xml](https://github.com/user-attachments/files/26000016/colors.xml)

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Colors are now correctly sorted also by transparency

## Motivation and context

fix #28010

## How has this been tested?

tested by replacing system/dialogcolors.xml with user [colors.xml](https://github.com/user-attachments/files/26644690/colors.xml) that contains gradient colors with transparency

BEFORE:
immagine

AFTER:
immagine

## What is the effect on users?

See better sorted colors when custom colors with transparency are used

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/utils/ColorUtils.cpp [hunk 1]
```diff
@@ -127,7 +127,17 @@ bool comparePairColorInfo(const std::pair<std::string, ColorInfo>& a,
   if (a.second.hue == b.second.hue)
   {
     if (a.second.saturation == b.second.saturation)
-      return (a.second.lightness < b.second.lightness);
+    {
+      if (a.second.lightness == b.second.lightness)
+      {
+        // Ascending transparency
+        const unsigned alphaA = (a.second.colorARGB >> 24) & 0x000000FF;
+        const unsigned alphaB = (b.second.colorARGB >> 24) & 0x000000FF;
```
Comment (CrystalP) [inline xbmc/utils/ColorUtils.cpp]: it works but isn't masking with a constexpr unsigned alphaMask = 0xFF000000 enough?

**Review by CrystalP — COMMENTED** [review]
nice usability improvement, just a minor style note.

File: xbmc/utils/ColorUtils.cpp (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/utils/ColorUtils.cpp]: change done if it is what you mean

File: xbmc/utils/ColorUtils.cpp [hunk 2]
```diff
@@ -127,7 +127,18 @@ bool comparePairColorInfo(const std::pair<std::string, ColorInfo>& a,
...
     if (a.second.saturation == b.second.saturation)
-      return (a.second.lightness < b.second.lightness);
+    {
+      if (a.second.lightness == b.second.lightness)
+      {
+        // Ascending transparency
+        constexpr unsigned alphaMask = 0xFF000000u;
+        const unsigned alphaA = (a.second.colorARGB & alphaMask) >> 24;
+        const unsigned alphaB = (b.second.colorARGB & alphaMask) >> 24;
+        return alphaA > alphaB;
```
Comment (CrystalP) [inline xbmc/utils/ColorUtils.cpp]: Including the type in the literal is a good idea. This is what I had in mind because the shift is not needed for a valid comparison unless I'm missing something
(parenthesis for clarity of operator priority)

```suggestion
        constexpr auto alphaMask = 0xFF000000u;
        return (a.second.colorARGB & alphaMask) > (b.second.colorARGB & alphaMask);
```

Comment (CastagnaIT) [reply xbmc/utils/ColorUtils.cpp]: yeah same result

**Review by CrystalP — APPROVED** [review]
