### PR TITLE
ExifParser: Fix several out of bounds accesses while parsing exif information

### LINKED ISSUE #22377: kodi image exif parse bug
### Describe the bug

After inserting the wrong/malformed image file into the USB storage device and mounting it, run kodi to run the Picture application. Exifparse crashes while scanning (reading) the wrong image files included in the USB storage device, leading to the termination of the process

## Expected Behavior
If you include an invalid image file, the kodi process crashes, you can check the memory address through the internal crash log.

## Possible Fix
1. Please check the attached crash report information. It is reporting which functions are crashing. I guess is that it has to do with CExifparse function.

### To Reproduce
1. Save the attached image file to a USB storage device.
2. After recognizing the USB storage device in an environment that can operate kodi, such as Raspberry Pi, run the Picture application inside kodi.
3. After a while the process crashes.
4. If you need a crash log dump, you can enable the log dump option in preferences within kodi.

[image.zip](https://github.com/xbmc/xbmc/files/10334869/image.zip)

### Debuglog

[kodi_crashlog-20230103_053835.log](https://github.com/xbmc/xbmc/files/10334863/kodi_crashlog-20230103_053835.log)
[kodi_crashlog-20230103_071817.log](https://github.com/xbmc/xbmc/files/10334864/kodi_crashlog-20230103_071817.log)
[kodi_crashlog-20230103_071903.log](https://github.com/xbmc/xbmc/files/10334865/kodi_crashlog-20230103_071903.log)

### Screenshots 
스크린샷 2023-01-03 오후 4 30 51

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

스크린샷 2023-01-03 오후 4 32 28

### Your Environment
Used Operating system:

 - [O] Android
 - [ ] iOS
 - [ ] tvOS
 - [0] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Raspberrypi 4
 - Kodi version: Latest Version.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fritsch**
Several drafted images could crash kodi. This was tested with memory, address sanitizers enabled.
cmake -DENABLE_VAAPI=1 -DCORE_PLATFORM_NAME=wayland -DCMAKE_BUILD_TYPE=Debug -DAPP_RENDER_SYSTEM=gl -DECM_ENABLE_SANITIZERS=address,memory

Example Output:
SUMMARY: AddressSanitizer: heap-buffer-overflow (/home/fritsch/Desktop/xbmc-fritsch/xbmc/build/kodi-wayland+0x3dca321) in CExifParse::Get32(void const*, bool)
Shadow bytes around the buggy address:
  0x0c3c8004e070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c8004e080: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c8004e090: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c8004e0a0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c3c8004e0b0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x0c3c8004e0c0: 00 00 00 00 00[04]fa fa fa fa fa fa fa fa fa fa
  0x0c3c8004e0d0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c8004e0e0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c8004e0f0: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c8004e100: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
  0x0c3c8004e110: fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==824657==ABORTING

via: https://paste.kodi.tv/kagukejefa.kodi

The issues were long fixed upstream: https://android.googlesource.com/platform/external/jhead/+/2a4c12f5e5808e309b9ba04fe8b1539debf466d1

Kodi should remove the copied libexif code and use jhead directly.

This fixes: #22377

### CODE REVIEW

File: xbmc/pictures/ExifParse.cpp [hunk 1]
```diff
@@ -376,7 +377,7 @@ void CExifParse::ProcessDir(const unsigned char* const DirStart,
       unsigned OffsetVal;
       OffsetVal = (unsigned)Get32(DirEntry+8, m_MotorolaOrder);
       // If its bigger than 4 bytes, the dir entry contains an offset.
-      if (OffsetVal+ByteCount > ExifLength)
+      if (OffsetVal > UINT32_MAX - ByteCount || OffsetVal + ByteCount > ExifLength)
```
Comment (lrusak) [inline xbmc/pictures/ExifParse.cpp:380]:
```suggestion
      if (OffsetVal > std::numeric_limits<uint32_t>::max() - ByteCount || OffsetVal + ByteCount > ExifLength)
```

**Review by lrusak — APPROVED** [review]
Looks fine if it fixes the issues.

I agree that we need to move to using upstream libexif instead.

File: xbmc/pictures/ExifParse.cpp (hunk 1 above)
Comment (fritsch) [reply xbmc/pictures/ExifParse.cpp:380]: As long as we have an "upstream" copy - I would suggest to stay as near to it as possible to ease future cherry-pick / fixes.

Please merge ahead if you agree, seeing that you already acked.
