### PR TITLE
[Subtitles] Fix text aspect ratio and size with video effects

### LINKED ISSUE #21718: Subtitle Size in KODI Alpha widely vary in size and format efffected by video file format.
### Describe the bug
Here is a clear and concise description of what the problem is:

- Subtitles take size of the video format being played at the time. Subtitle size should conform to the KODI's (Versions Alpha 1 & 2) setup selected.
- Subtiles, whether sources internally, from the video file, OR external subtitles, vary in size effect directly by the video's format being played. In previous versions of KODI, the subtitles were set or fixed in size based on manual setup selected by the user.
- This is a bug because subtitles vary in size from extremely large to extrememly small. OTHER PROBLEM: In most cases, each line of the subtitle text does not recogize double or triple line setting and display the line a a single line displayed from the extreme left to the right edge of the screen; better said, subtitles generally display 2 or 3 lines at a time but now only as a single line.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
 

The subtitles should conform to the selected setting in Kodi Setup > settings > Player > Subtitles > Size.. 

## Actual Behavior

Rather, the size of the subtitles conform to the video format played at the time. The size of subtitles may vary/change from one video format to another, large or small size.

## Possible Fix

Disassociate video format effects on subtitle format.

### To Reproduce

1. Play 2160p or 1080p video after setting subtitles size to (e.g) 30.
2. Play, with subtitles, one format then the other format. If all is well, the subtitles should remain similar; otherwise different sizes.
3. Playing two similary formats (both 1080p for example) will also differ subtitle size view because rarely do video formats maintain similar standards. 

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I suffer viewing generally extrememly large texted subtitles.

### Your Environment
Used Operating system:

 - [x] Android Version 20 ARM64-v8a.apk
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows Windows 11, all upgrades
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi Alpha 1 and 2, effected.  Version 20 ARM64-v8a.apk
- Android Media Player: Nvidea Shield (latest firmware upgraded)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Fix text aspect ratio and size when video effects are used like zoom or `View mode` settings

Example of 4/3 view mode BEFORE:
Forced43Before
Example of 4/3 view mode AFTER:
Forced43After

Example of Zoom effect used on a cropped video (position used `Bottom of video`):
ZoomEffect
You can see that not only the text size is consistent to settings, but also follow the black bars size

For native subtitles (ASS) and subtitles that make use of margins like WebVTT, the text will be fixed aligned to screen to prevent problems with positions defined by authors or possible side effects like text offscreen. Users can always enable subtilte position override settings to force change text position as preferred

~Require PR #21680~

## Motivation and context

When you use video effects like zoom or `View mode` forced to 4/3 etc...
the subtitles are wrongly rendered with wrong aspect ratio and size

## How has this been tested?

Using video settings and playing a video with SRT

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
jenkins build this please

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h [hunk 1]
```diff
@@ -115,15 +115,21 @@ struct renderOpts
 {
   float frameWidth;
   float frameHeight;
+  // Video size width, may be influenced by video settings (e.g. zoom)
   float videoWidth;
+  // Video size height, may be influenced by video settings (e.g. zoom)
   float videoHeight;
+  float videoScaledWidth; // Video size width, scaled to frame
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:122]: Do we really need all these new members? Afaics you compute a ratio based on the already existing members just to compute the scaled sizes based on the found ratio. If you could somehow do this on the flight without storing the values it would greatly simplify the code. Also we seem to passthrough always the same set of values (video rect, source rect, etc) everywhere

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:122]: yes i can move it within libass RenderImage to avoid add these members
i had done it this way to avoid the calculation at each frame

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:122]: i was thinking now, this is used to calculate sar/dar
but now with videoScaled* vars will results that have same ratio of source size
therefore now sar/dar will have always the same value
and `dar / sar` in `ass_set_pixel_aspect(m_renderer, dar / sar);` if i am not wrong should now results always as 1.0,
then we could set `ass_set_pixel_aspect(m_renderer, 1.0);` fixed value or else change as:
```
double sar = static_cast<double>(opts.sourceWidth) / static_cast<double>(opts.sourceHeight);
double dar = static_cast<double>(opts.sourceWidth) / static_cast<double>(opts.sourceHeight);
```

Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:122]: Calibration window applies to GUI as a whole, in the past subtitles were rendered by OverlayRendererGUI which was effectively a GUI component. However setups with old 4:3 CRTs are still common nowadays. I wonder if this PR breaks them again (Ronie provided a way to simulate that in estuary a while ago but I don't remember the instructions by heart).
Maybe we could have another option in the calibration window to account for this.

Personally I feel the subtitle line in the calibration screen a bit confusing for someone new to kodi - you affect positioning while the effect on other properties like scale are a bit obscure. A rectangle positioned at the center of the line which you could move up/down to affect position and right/left to affect scale would capture all this much better and allow to force the overlays to be rendered inside the rendered rect if you want so...although at the cost of quite a bit of work. 

Displaying actual placeholder text would even be better (but even harder to implement).

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp [hunk 2]
```diff
@@ -276,49 +277,51 @@ ASS_Image* CDVDSubtitlesLibass::RenderImage(double pts,
     ApplyStyle(subStyle, opts);
   }
 
-  double sar = static_cast<double>(opts.sourceWidth) / static_cast<double>(opts.sourceHeight);
-  double dar = static_cast<double>(opts.videoWidth) / static_cast<double>(opts.videoHeight);
-  ass_set_pixel_aspect(m_renderer, dar / sar);
+  float par = (opts.m_par - 2.0f) * -1;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:280]: Comment explaining this rather obscure calculation would be great :)

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp [hunk 3]
```diff
@@ -549,13 +552,12 @@ COverlay* CRenderer::ConvertLibass(
...
 #endif
 
-  // scale to video dimensions
   if (overlay)
   {
-    overlay->m_width = rOpts.frameWidth / rOpts.videoWidth;
-    overlay->m_height = rOpts.frameHeight / rOpts.videoHeight;
-    overlay->m_x = (rOpts.videoWidth - rOpts.frameWidth) / 2 / rOpts.videoWidth;
-    overlay->m_y = (rOpts.videoHeight - rOpts.frameHeight) / 2 / rOpts.videoHeight;
+    overlay->m_width = 1.0;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp:557]: Are these sane defaults? If so I think they could be moved to the constructor of the overlay, both are only used in this class

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h [hunk 4]
```diff
@@ -115,15 +115,20 @@ struct renderOpts
...
   float sourceWidth;
   float sourceHeight;
+  float m_par; // Set the pixel aspect ratio
   MarginsMode marginsMode = MarginsMode::DEFAULT;
   // Vertical line position of subtitles in percentage
   // only for bottom alignment, 0 = bottom (no change), 100 = on top
   double position = 0;
   HorizontalAlign horizontalAlignment = HorizontalAlign::DISABLED;
+  // Make font size relative to the window instead of the video
+  bool m_fontScaleWithWindow = false;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:131]: Is this one really needed? Maybe checking marginsmode against `SUBTITLES::STYLE::MarginsMode::INSIDE_VIDEO` could be enough?

File: xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/DVDSubtitlesLibass.cpp:280]: yes i will ask to lord darth vader

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h (hunk 4 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h:131]: yes atm can be an alternative, but i think that linking font scaling to marginmode is not so good idea

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h]: par is now implemented by taking value from "calibration window", remains to do some more tests

> Maybe we could have another option

would you like to provide a setting to set a customised aspect ratio for subtitles only separately? (maybe better xml advanced setting)
or did you think of other type of settings?

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h (hunk 4 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h]: Sure, my point/request here was to prefer avoiding random bools for every single option in favor of something that can be either derived from other properties or grouped into some enum class or so.

**Review by enen92 — APPROVED** [review]
Looks good to me, I can't runtime test this for a couple of days but I guess you stressed it enough
Thanks for the continued work on this, it's turning out pretty great

File: xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h (hunk 1 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDSubtitles/SubtitlesStyle.h]: Let's wait for user feedback and come back to this later :)
