### PR TITLE
[video][dialogs] Video versions: Fix delay before "Convert to version" video select dialog opens

### LINKED ISSUE #24293: Delay before "Convert movie version" opens / Very long list of movies
### Describe the bug

* As reported in the forum, with a large library  (>1000) and desktop computer it takes 10 seconds to open the Manage > Convert movie version screen.
This will be much worse on Android boxes or Pi.

The time is spent mostly in thumbs loading, but even when it is removed, takes a second or two just to add all items to the list.

* From a usability point of view, the screen presents a list of all movies in the library. Most are not relevant and it can be long to find the right one, which will likely have the same imdb/tmdb or name/year as the movie being converted to a version.

## Expected Behavior

Screens opens within a second on low power device.

## Possible Fix

Async loading of thumbs / items.

No thumbs.

Alternatively, first show only the similar movies (matching imdb/tmdb or same name+year), with a More... button if the user wants to link less strongly related movies (ex. Justice League (2017) - Zack Snyder's Justice League (2021) used somewhere in the forum)

Although movie sets may be more appropriate for movies that are not directly related (Justice League, remakes of movies?)

### To Reproduce

Prerequisite: large-ish library (>1000)

1. Navigate to movie library and a movie that doesn't have versions
2. Open context menu, go to Manage > Convert movie version
3. Screen opens after a delay

### Debuglog

There is nothing relevant, but here: https://paste.kodi.tv/iyocugivig.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: master post v21 beta2.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #24293 

@CrystalP fyi

Idea for the fix is to enhance `CGUIDialogSelect`with the capability to asynchronously load thumbnails of the items to display and to use that from the video manage dialogs implementation for the version conversion. => Commit 1.

While working on this I stumbled over a reproducable crash on Kodi exit triggered by this change. If not stopped before the async load is done, a `CBackgroundInfoLoader` will hold the list of items containing the smart pointers to the items originally handed over to the dialog until Kodi exits or the loader is reused and stopped prematurely then). On exit, when the dialog instance gets destroyed, other kodi parts are already deallocated (GUI control structures referenced by the items for example). Fix for this is also to clear the item list of `CGUIDialogSelect` when the async load completed. I checked that the list is not accessed by any derived classes after it gets cleared now. => Commit 2

Commit 3 is removing of some duplicate code.

Runtime-tested on macOS, latest Kodi master

@enen92 something different this time.

### CODE REVIEW

**Comment by CrystalP** [comment]
The dialog appears much faster, the jury is still out on the usability of the dialog.
It still takes a full second to open on medium-range desktop (don't know how that translates for a low power Android box), and picking a movie from a large library can take many page scrolls.
I have some ideas and can take a shot at it after this PR is merged if you'd rather take care of other things.

**Comment by ksooo** [comment]
Yes, this dialog is unusable for larger libraries for the teaspoons you pointed out. I will not invest time in improvements and I suggest for now the same for you. 

I’m questioning the whole „convert to version“ menu item as to my understanding what it does can be achieved using the manage versions dialog already(needs to be checked). If this is correct, I would just remove this redundant menu item and its implementation. 

Result of convert to version to my understanding is the same as for add version in the manage dialog. For both paths you end with a video added as a new version to a movie.

**Comment by ksooo** [comment]
The original author of the feature imo had a „wrong“ thinking about all this in general. They was thinking „some things you have in the library are versions, some other things are movies“ instead of „everything you see in the library is a movie which has (not is!) is a version“. This general imo problematic thinking has driven the implementation (database schema and everything) and even is visible at the user interface.

**Comment by thexai** [comment]
Why not use same logic than in scanning: filter only movies with same uniqueId or same title/years. 

Scanning detects same movies when added new movies. 
This feature allows detect same movies of existent movies in library.

**Comment by ksooo** [comment]
> Why not use same logic than in scanning: filter only movies with same uniqueId or same title/years.

@thexai not sure this logic will work here, as we can assign arbitrary movies contained in the library to any other movie during the "convert". There is no filter criteria (other than prevent self-assigning). Something that can be considered in the future PR that will deal with ux improvements for the video selection dialog.

File: xbmc/BackgroundInfoLoader.cpp [hunk 1]
```diff
@@ -90,6 +90,9 @@ void CBackgroundInfoLoader::Run()
     m_bIsLoading = false;
     CLog::Log(LOGERROR, "{} - Unhandled exception", __FUNCTION__);
   }
+
+  m_pVecItems = nullptr;
```
Comment (enen92) [inline xbmc/BackgroundInfoLoader.cpp:94]: Probably create a reset method you can reuse to set all the members to default?
Same seems to be done in stop thread.

File: xbmc/dialogs/GUIDialogSelect.h [hunk 2]
```diff
@@ -9,6 +9,7 @@
 #pragma once
 
 #include "GUIDialogBoxBase.h"
+#include "video/VideoThumbLoader.h"
```
Comment (enen92) [inline xbmc/dialogs/GUIDialogSelect.h:12]: This doesn't look good :/
Who is the consumer of this? Some window for versions that extend dialog select or just a raw dialog select?
I guess this should be moved elsewhere

**Review by enen92 — CHANGES_REQUESTED** [review]
I don't like the dependency of standard dialogselect on thumbloader and/or video. That dialog is the base for select actions, should be agnostic to types.

**Comment by ksooo** [comment]
> I don't like the dependency of standard dialogselect on thumbloader and/or video. That dialog is the base for select actions, should be agnostic to types.

I agree, but then we need a completely different fix approach. In the first place I tried to trigger async loading of thumbs from the versions manage dialog, before opening the select dialog. This does not work, as the select dialog is taking a copy (!) of the items, thus the "outside" loader is working not on the right items. It does not fill the items that are used by the select dialog, thus loaded thumbs not usable by the dialog.

No idea why the select dialog takes copies of the items, maybe this simply can be changed to work with the original items, but so far I was thinking that this might introduce strange/bad side effects.

**Comment by ksooo** [comment]
@enen92 should be MUCH cleaner now. :-)

**Review by enen92 — APPROVED** [review]
Yeap, great cleanup all together. Thanks for adjusting

**Comment by ksooo** [comment]
Need to trick Jenkins.

**Comment by CrystalP** [comment]
> No idea why the select dialog takes copies of the items, maybe this simply can be changed to work with the original items, but so far I was thinking that this might introduce strange/bad side effects.

You could leave a todo for the v22 cycle.

> I’m questioning the whole „convert to version“ menu item as to my understanding what it does can be achieved using the manage versions dialog already(needs to be checked)

It's a complex decision, an explanation of your vision of the UX for version creation / management would help understand what you're going for in v21 and what will be left for v22.

Yes technically the action can be achieved through manage versions and I can understand that mindset though to me it's more intuitive as a context menu action on the duplicate movie I see in the library view (also a few less clicks)

The word "convert" may be wrong at the user level, maybe rename the context menu item "Add as version to..."

> Why not use same logic than in scanning: filter only movies with same uniqueId or same title/year.

That's what I had in mind, as I think the most common case by far is to pick an identical movie. The screen would open very quickly. I would also add a "More..." item or button to access the complete library, for when the user really wants it, with the accompanying speed penalty and difficulty to pick from thousands of movies.

The same thing could be applied to the Add version of the Manage screen, currently unusable as far as I am concerned (shows a file picker of all sources).

**Comment by ksooo** [comment]
> You could leave a todo for the v22 cycle.

Not needed, as the latest force-push already removed the copy. I'm pretty sure meanwhile that there are no bad side effects. The copy is just a leftover from 2012 where we worked with raw pointers all over the place. 

> The word "convert" may be wrong at the user level, maybe rename the context menu item "Add as version to..."

Definitely better to understand. Feel free to change that. ;-)

**Comment by thexai** [comment]
> That's what I had in mind, as I think the most common case by far is to pick an identical movie. The screen would open very quickly. I would also add a "More..." item or button to access the complete library, for when the user really wants it, with the accompanying speed penalty and difficulty to pick from thousands of movies.

Maybe button "More..." is not necessary: is sufficient with display movies with same uniqueId / same title (if any) at top on the list.

**Comment by ksooo** [comment]
We are drifting off a bit from the scope of this PR. Maybe we continue this discussion in Slack? This PR is for fixing the long delay before the select dialog opens, not for UX improvements or even roadmap discussions. ;-)

**Comment by ksooo** [comment]
Jenkins build this please
