### PR TITLE
LinuxRendererGLES: enable HDR passthrough for HDR videos with incomplete(?) metadata info

### LINKED ISSUE #8322: [BUG] Intel NUC 13 Pro doesn't switch to HDR with my Sony A95L[BUG]
### Describe the bug
Hi I have an Intel NUC 13 Pro with Core i7 1360P connected to the Sony A95L.
on LibreELEC-Generic.x86_64-12.0-nightly-20231108

When trying to run any HDR Video the display dose not switch to HDR mode. Debug log attached for more information.

I hope if you can tell me where the issue is.

### How to reproduce
Run any HDR File with Intel NUC 13

### Information
 - LibreELEC Version: [Generic.x86_64-12.0-nightly-20231108]
 - Hardware Platform: [Intel NUC 13]

### Log file
https://paste.kodi.tv/tefayidini

### PR DESCRIPTION
**Pull request by smp79**
## Description

This fixes [#8322](https://github.com/LibreELEC/LibreELEC.tv/issues/8322). This also fixed HDR passthrough for all of my HDR videos that didn't switch my TV into HDR mode. Even the HLG sample now switches the TV to HLG HDR mode.

## How has this been tested?

Tested on Intel TGL + Samsung 4K TV.

## Types of change

- [X ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp [hunk 1]
```diff
@@ -132,7 +132,6 @@ bool CLinuxRendererGLES::Configure(const VideoPicture &picture, float fps, unsig
   // setup the background colour
   m_clearColour = CServiceBroker::GetWinSystem()->UseLimitedColor() ? (16.0f / 0xff) : 0.0f;
 
-  if (picture.hasDisplayMetadata && picture.hasLightMetadata)
```
Comment (lrusak) [inline xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp:135]: I don't think this "fixes" the problem. Allowing incomplete metadata may result in a worse image as the MaxFALL and MaxCLL provide info about the HDR content.

This means that if the encoding contains a valid HDR10 (pq) or HLG flag in the `color_transfer` then it can switch HDR mode on without any other metadata.

Simply seeing the HDR logo light up on the tv doesn't mean the picture is correct.

Ref:

```
Static metadata: SMPTE ST 2086 (mastering display color volume), MaxFALL (maximum frame-average light level), and MaxCLL (maximum content light level)
```
https://en.wikipedia.org/wiki/HDR10

And
```
MaxFALL/MaxCLL is static metadata required for HDR10 content. 
```

https://professionalsupport.dolby.com/s/article/Calculation-of-MaxFALL-and-MaxCLL-metadata?language=en_US

**Review by lrusak — COMMENTED** [review]
I

File: xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp (hunk 1 above)
Comment (smp79) [reply xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp:135]: It can't look worse than any of the tone mapping methods. IMO we'd still want to switch the TV to HDR/BT.2020.

Comment (smp79) [reply xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp:135]: Not to mention that DRM PRIME platforms, eg. RPI4 allow switching to HDR mode with those "incomplete metadata" videos. Why this should be different for Intel?

Comment (smp79) [reply xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp:135]: Even the TV's internal player would switch the TV to HDR mode with those videos. But on Intel PC they are tone mapped to SDR and look horrible.

Comment (smp79) [reply xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp:135]: [This video](https://www.dropbox.com/scl/fi/t086p6sn4dajhv6bpdhgt/Life-Untouched-4K-Demo.mp4?rlkey=dk5gdhhee30fr9sntlgtczq1d&dl=1), for example, doesn't even trigger the tone mapping and it is absolutely unwatchable. With this PR it would switch the TV to HDR mode and looks perfectly fine, same as with TV's internal player.

Comment (lrusak) [reply xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp:135]: > Not to mention that DRM PRIME platforms, eg. RPI4 allow switching to HDR mode with those "incomplete metadata" videos. Why this should be different for Intel?

If the behaviour is inconsistent across platforms we should check how other platforms and applications handle it.

If it's expected to be able to just ignore any metadata then so be it but we should investigate more about what the correct behaviour should be.

Comment (smp79) [reply xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp:135]: I also removed metadata checks for tonemapping. HLG streams and HDR10 videos with missing MaxFALL/MaxCLL didn't trigger tonemapping for SDR TVs.

Comment (CrystalP) [reply xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp:135]: I was going to suggest removing the check altogether if you hadn't done it already. For Windows, HDR mode is triggered by color_transfer + primaries only. Metadata, when present, is forwarded as is to the TV, it hasn't caused issues that I know of. But it's possible that Windows is interfering in the process.

HLG streams typically don't come with metadata and that's valid. Windows has special handling though because of missing HLG passthrough support, Instead it's converted to PQ with shader and metadata is made up with 1000nits max, value found in many places of HLG spec.

**Comment by quietvoid** [comment]
It's very strange to me that the changes remove HDR10 metadata passthrough altogether.
Is it not possible to only set it conditionally?

**Comment by smp79** [comment]
> It's very strange to me that the changes remove HDR10 metadata passthrough altogether.

The changes only remove unneeded checks and the leftover code that was used only for those checks.

**Comment by ilikenwf** [comment]
I know it is a stretch but could this have anything to do with my issue, in which youtube HDR videos refuse to play until I disable HDR?

**Comment by smp79** [comment]
> I know it is a stretch but could this have anything to do with my issue

All I can say is that with this PR VP9 HDR videos that I downloaded from youtube (like [this one](https://www.dropbox.com/scl/fi/v1z2qtglylts1y9dhnvh0/videoplayback.mkv?rlkey=y21b4fg6ar182rwyu0k21e3m3&dl=1))  would switch the TV to HDR mode. Without this PR they are tonemapped to SDR. Whether or not it has anything to do with your issue I have no idea.

**Comment by ilikenwf** [comment]
My current struggle seems more to potentially be either with buliding and running Kodi on Arch, or with my intel arc...

I ran Libreelec live and managed to get it to switch to HDR, for one video but then no others...lol not sure how to handle that especially since my goal is avoiding the use of the privacy unfriendly google tv install that my new bravia has.

**Comment by ilikenwf** [comment]
So youtube HDR playback is still fully broken for me (though I wonder if it's not broken for everyone and everyone just watches youtube on Kodi in SDR), but I found arch is packaging kodi with the gl instead of gles backend...it appears that some if not all vp9 videos, at least when in mkv containers, refuse to playback in HDR mode for me, as well...

**Comment by ilikenwf** [comment]
@smp79 you think this will ever get merged? I've been building with it locally for a while now, as it fixes all of my trouble with HDR save for issues with youtube and my Arc card...so for vp9 i have VAAPI disabled right now.

**Comment by ilikenwf** [comment]
Any thoughts on merging this?

**Comment by smp79** [comment]
> @smp79 you think this will ever get merged?

No idea. 
IMO this is a proper fix. We should not disable HDR passthrough if the video does not have MaxFALL/MaxCLL present. This is especially relevant for HLG DVB streams since HLG does not use MaxFALL/MaxCLL by design.

**Comment by harment** [comment]
can add this patch for kodi20 ?

**Comment by ilikenwf** [comment]
So things were great until recent builds, now webm's are no longer working for HDR support.

**Comment by ilikenwf** [comment]
Ah, I thought it was merged.

**Comment by smp79** [comment]
I'm running this patch for over a year with no issues. Hope this gets some attention. In current master we have a broken HLG, VP9 HDR on x86 Linux.  
ping @thexai - I understand that Linux is not your thing but maybe you have an opinion on this PR?

**Review by neo1973 — APPROVED** [review]
I agree that if every other player allows HDR, we should probably allow it as well. If we find cases where this causes problems, we can revisit this approach.

**Comment by ilikenwf** [comment]
> I'm running this patch for over a year with no issues. Hope this gets some attention. In current master we have a broken HLG, VP9 HDR on x86 Linux. ping @thexai - I understand that Linux is not your thing but maybe you have an opinion on this PR?

Same here.

**Review by thexai — APPROVED** [review]

**Comment by smp79** [comment]
PR updated as per @thexai's suggestion.

**Comment by neo1973** [comment]
@smp79: As the code change is minimal, can you please do a backport for Omega?
