### PR TITLE
[wayland][input] Add xkb compose and dead-keys support

### LINKED ISSUE #23828: cannot input a caret or circumflex above a character with `dead key` via a physical keyboard
### Describe the bug
I cannot input a caret or circumflex above a character with `dead key` via a physical keyboard (the virtual keyboard already has characters with the circumflex above). I believe it is the same with other dead keys (`"` for one).

Reproduced in Debian with kodi 20.1 and LibreElec 12.
Plugging a keyboard, keymap set as French.

I noticed the issue because I use a random password generator for one of my account. Typing the password in Kodi did not help with getting the extension to connect. Turned out in the hidden password characters, the caret was not produced.

## Expected Behavior
When I press the circumflex dead key twice on a Linux base, I should get a caret (not that the English keyboard Shift+6 is already a plain caret so it does not behave as a dead key). When I pressed it followed by `e` I should get `ê`.

## Actual Behavior
Nothing appear when I press the circumflex dead key twice or followed by another character.

## Possible Fix
I believe this is a missing capability of the toolkit used by Kodi, which as far as I know is internal to the Kodi project.

### To Reproduce

1.  Enter the extension search with a French keyboard layout
2. Type the circumflex french keyboard mapping dead key - which on the English keyboard mapping is the `[` key - twice.
3. Nothing is inputted.

### Debuglog
The end of the log was with debug logging (the part where I press the same circumflex dead key a few times in a row)
The debug log can be found here:
https://paste.kodi.tv/iqofeyocil.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
I was trying to input an account password that had a caret in it (which is only available on the French keyboard via pressing twice the circumflex dead key).

### Your Environment
Used Operating system:

!--- Include as many relevant details about the environment you experienced the bug in -->

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ X ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian trixie and LibreElex 12
 - Kodi version: 20.1 on Debian and 21.0 on LibreElec

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This pull request adds support for compose keys (those created from pressing key combinations using dead keys) to xkbcommon - wayland implementation (read more about this [here](https://xkbcommon.org/doc/current/group__compose.html)).
This has bugged me for a while, using an attached keyboard you can't input the deadkey unicode symbol (usually used in passwords like `~`,`´`, `^`, etc) nor the key composed combinations (e.g. `~`+`a` = `ã`).

Along with support for the key composer in xkbcommon, this PR also modifies the GUIEditControl to allow for user feedback while composing keys - similar to what happens when you use regular applications like the terminal or a text input in the browser:
- If the control is flushed and waiting for input it has a blinking cursor (`|`)
- If the control is composing a key it shows the current dead key unicode codepoint sequence as the cursor value without blinking
- After composing a key, the cursor buffer is flushed to the actual input while the cursor is reset to normal state (blinking `|`).

See more about this in the video screencast below.

All this is guaranteed by a new set of events (`XBMC_KEYCOMPOSING_COMPOSING`, `XBMC_KEYCOMPOSING_FINISHED`, `XBMC_KEYCOMPOSING_CANCELLED`) that then map to actions that end up consumed by the GUI layer.

Unfortunately this ended up being a bit involved and is also platform dependent. Regardless, it sets the blueprint for other platforms to implement something similar. I may have a crack at other platforms (namely other linux implementations and android) later if this one goes in.

Most of the complexity comes from the fact that to mimic the composed-key sequence cancellation behaviour we all are used to (replaying the sequence plus the key/unicode that lead to the cancellation) requires that state is stored outside of the composer. I am using the control cursor to track the "state": when the composing cancellation event occurs, the control flushes the cursor buffer (the key sequence until then) to the actual control input (to which is later appended the cancellation key).

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/23828

## How has this been tested?
Runtime tested on Linux, wayland qwerty keyboard with a portuguese layout.

## What is the effect on users?
Dead key / Composed keys should now be supported when using keyboards just like other applications

## Screenshots (if appropriate):

https://www.youtube.com/watch?v=1y147A87hAc

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/windowing/wayland/XkbcommonKeymap.cpp [hunk 1]
```diff
@@ -221,10 +283,21 @@ std::unique_ptr<CXkbcommonKeymap> CXkbcommonContext::KeymapFromString(std::strin
...
 
-  return std::make_unique<CXkbcommonKeymap>(std::move(xkbKeymap));
+  std::unique_ptr<xkb_compose_table, CXkbcommonKeymap::XkbComposeTableDeleter> xbkComposeTable{
+      xkb_compose_table_new_from_locale(m_context.get(), locale.c_str(),
+                                        XKB_COMPOSE_COMPILE_NO_FLAGS),
+      CXkbcommonKeymap::XkbComposeTableDeleter()};
+
+  if (!xbkComposeTable)
+  {
+    throw std::runtime_error("Failed to compile localized compose table");
```
Comment (sundermann) [inline xbmc/windowing/wayland/XkbcommonKeymap.cpp:293]: I am hitting this on webOS probably because `/usr/share/X11/locale`does not exist breaking keyboard input completely due to missing keymap. Can we not error out here early and return `nullptr` for the compose map instead?

File: xbmc/windowing/wayland/XkbcommonKeymap.cpp [hunk 2]
```diff
@@ -221,10 +283,21 @@ std::unique_ptr<CXkbcommonKeymap> CXkbcommonContext::KeymapFromString(std::strin
...
+  }
+  return std::unique_ptr<CXkbcommonKeymap>{
+      new CXkbcommonKeymap(std::move(xkbKeymap), std::move(xbkComposeTable))};
```
Comment (sundermann) [inline xbmc/windowing/wayland/XkbcommonKeymap.cpp:296]: typo here `**xbk**ComposeTable`

**Review by sundermann — CHANGES_REQUESTED** [review]
Can't say much on the GUI stuff. The wayland stuff seems fine, except for that this feature should be optional as the compose map is not available on webOS. For the same reason, I couldn't test it unfortunately. I'll look if there's something about the webOS side to fix this because dead keys appararently work on the webbrowser

File: xbmc/windowing/wayland/XkbcommonKeymap.cpp (hunk 1 above)
Comment (enen92) [reply xbmc/windowing/wayland/XkbcommonKeymap.cpp:293]: Yeah that's why I asked for the review,  I'll try to make this optional :)
Added logger configuration on a new commit, I guess you're right in your assumption:

```
2023-10-16 21:40:23.658 T:21155   debug <general>: xkbLogger: Compiling xkb_keycodes "(unnamed)"
2023-10-16 21:40:23.658 T:21155   debug <general>: xkbLogger: Compiling xkb_types "(unnamed)"
2023-10-16 21:40:23.658 T:21155   debug <general>: xkbLogger: Compiling xkb_compatibility "(unnamed)"
2023-10-16 21:40:23.658 T:21155   debug <general>: xkbLogger: Compiling xkb_symbols "(unnamed)"
2023-10-16 21:40:23.660 T:21155   debug <general>: xkbLogger: created compose table from locale C with path /usr/share/X11/locale/en_US.UTF-8/Compose
```

Comment (enen92) [reply xbmc/windowing/wayland/XkbcommonKeymap.cpp]: @sundermann https://github.com/xbmc/xbmc/pull/23943/commits/59f8bdce0768beb64480454d653bd91931890197 makes this optional so it should no longer crash on webOS.
Still it'd be nice if you could look it up. I guess the compose files must exist somewhere in webOS (and we also can use libxkbcommon to load the table from a given file).

Comment (sundermann) [reply xbmc/windowing/wayland/XkbcommonKeymap.cpp]: Can confirm keyboard / remote support is working again. I tried mounting `/usr/share/X11/locale` from `libX11-data` from debian but for some reason it would still not read from these files. I also tried reading directly from the compose file using `xkb_compose_table_new_from_file` which worked but dead keys were still not working. I wouldn't worry too much about it though, probably not implemented properly in LG's wayland compositor

File: xbmc/windowing/wayland/XkbcommonKeymap.cpp [hunk 3]
```diff
@@ -212,19 +300,36 @@ void CXkbcommonContext::XkbContextDeleter::operator()(xkb_context* ctx) const
   xkb_context_unref(ctx);
 }
 
-std::unique_ptr<CXkbcommonKeymap> CXkbcommonContext::KeymapFromString(std::string const& keymap)
+std::unique_ptr<CXkbcommonKeymap> CXkbcommonContext::LocalizedKeymapFromString(
+    const std::string& keymap, const std::string& locale)
 {
+  // install logger
+  xkb_context_set_log_level(m_context.get(), XKB_LOG_LEVEL_DEBUG);
```
[the remark this answers is not in the document]
Comment (enen92) [reply xbmc/windowing/wayland/XkbcommonKeymap.cpp:307]: yeah we can move this to the `CXkbcommonContext` creation :+1:

**Review by sundermann — APPROVED** [review]

**Review by neo1973 — APPROVED** [review]
