### PR TITLE
[database][mysql] Change MySQL/MariaDB charset/collation to utf8mb4/utf8mb4_general_ci

### LINKED ISSUE #16328: Use utf8mb4_general_ci instead of utf8_general_ci in MySql/MariaDB
### Describe the bug
Some UTF characters are not stored in the MySQL database, e.g. if file names contains some special characters like emoticons. utf8_ charsets can contain only 3-byte-characters (design flaw in MySQL).

## Possible Fix
Use utf8mb4_general_ci as default collation and charset for MySQL.

### LINKED ISSUE #23312: Kodi will not add video with Unicode > 0x10000 in filename to mysql/mariadb library
### Describe the bug
Here is a clear and concise description of what the problem is:

Video files with emoji characters in the filename are not added to the video library when scanned if using mysql or mariadb databases.  The files are added when default sqlite db is used.

Note:  musicdb not tested but probably has similar issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Files should be scanned and local info / scraped into mysql / mariadb databases

## Actual Behavior

When scanning, Kodi logs an error
```
error <general>: SQL: [MyVideos121] Undefined MySQL error: Code (1366)
Query: INSERT INTO files (idFile, idPath, strFileName, playCount, lastPlayed, dateAdded) VALUES(NULL, 5817, '🏝댄스 커버🏝 WJSN - Boogie Up │우주소녀 - 부기업 COVER DANCE 안무 영상(1).mp4', NULL, NULL, '2020-03-30 08:08:13')
                                                   
error <general>: CVideoDatabase::AddFile unable to addfile ()
```

## Possible Fix

Discovered while moving from sqlite to mariadb.  Investigating this issue I found a likely candidate issue https://github.com/xbmc/xbmc/issues/16328 that seems to be inactive but is likely the root cause.  Namely, mysql/mariadb need to created with utf8mb4_general_ci collation, not utf8_general_ci (aka utf8mb3).  The inability to handle 4 byte utf-8 character data is the reason that the data can't be inserted into the tables.  Note that 4-byte utf-8 characters cover more area than just emojis -- everything outside the unicode BMP.

I tried a naive fix by just changing
```
        snprintf(sqlcmd, sizeof(sqlcmd),
                 "CREATE DATABASE `%s` CHARACTER SET utf8 COLLATE utf8mb4_general_ci", db.c_str());`\
```

in dbwrapers/mysqldataset.cpp connect function, but that failed with error 1250 returned.

See also [MySQL Ref Man 8.0](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8.html) concerning deprecating utf8/utf8mb3
### To Reproduce

1. Scan a video file into library (exact here musicvideo with local nfo) having filename with characters outside of unicode BMP (in this case: U+1F3DD) `🏝댄스 커버🏝 WJSN - Boogie Up │우주소녀 - 부기업 COVER DANCE 안무 영상(1).mp4`
2. 
3.
4.

### Debuglog

The debuglog can be found here:

[log](https://paste.kodi.tv/isenicutuv.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10 x64 22H2
 - Kodi version: 20.1.0 x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Set the MySQL/MariaDB character set to utf8mb4 and the collation to utf8mb4_general_ci
They are 4-byte extensions of the currently used utf8 (aliased to utf8mb3 / utf8mb3_general_ci), with support for all unicode characters (including emojis). No change for the characters that were already suppported.

Bump the databases that can be configured as external per advancedsettings (VideoDB MusicDB EPG TV) to recreate the DBs with the new charset and collation.

Increase the minimum MySQL and MariaDB server requirements to versions that enable a large index prefix size by default. utf8mb4 needs larger index pages for varchar(255) and the server supports that with the ROW_FORMAT=DYNAMIC + innodb_large_prefix=TRUE settings.
MySQL: version 5.7.9 from release notes
MariaDB: sometime between 10.2.2 and 13.0. The release notes don't have the detail. An internet post identifies 10.2.5 as the first suitable version (https://docs.bestpractical.com/rt/5.0.0/README.MariaDB.html)
Both are unsupported (released 10 years ago) and users should upgrade to the latest LTS version anyway.
Kodi stops on version check failure.

Removed some unnecessary code: default charset, setting charset and collation in individual CREATE TABLE statements. The database and connection have the correct settings, inherited by the tables and their columns.

Added a validation of the table names and free connection resources earlier when connect() fails.

Wiki: find a place to write the server version requirements

## Motivation and context

Feature parity with Sqlite databases, handle all unicode characters.

Work started in #23346, which closes #23312 and #16328
It needed the DB bumps, server requirement bump, charset/collation conversion when upgrading a DB.

## How has this been tested?

With mariadb 11.8, tested a new database and a database upgrade from utf8m3.
Verified the charset and collation of the database, table and column attributes afterwards with db admin tool.
Quick runtime test of Kodi is OK.

## What is the effect on users?

Feature parity with Sqlite local databases.
All Japanese/Chinese characters, emojis! Requires compatible fonts for the display, not included here.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
Connection leak: addressed
Unnecessary temp string allocation: doesn't seem valid, please show the C++ specification that guarantees that string_view literals are null-terminated.
Table name validation: added

@kodiai please review again

**Comment by CrystalP** [comment]
Build failed due to missing support of many platforms for the C++20 std::format
Reworked as fmt::format

**Comment by scott967** [comment]
Thanks for taking this over.  I stopped work on https://github.com/xbmc/xbmc/pull/23346 as I was concerned that Kodi allows MySQL 5.6 which I'm not sure is compatible.  I would suggest making ver 5.7 a minimum, but we might consider ver 8.0.  My understanding is general_ci collation was "dumbed down" for performance reasons and is not preferred on ver 8.0+ . Also MariaDB 10.6 although I don't recall seeing a check for min MariaDB ver in the code.

**Comment by CrystalP** [comment]
- Versions:

It took some time to figure out the minimum server versions and MariaDB is still approximate - the release notes are not as detailed and I don't have the time to dig in the commit history.

5.7.9 and  10.2.5 are the first versions that set global options as needed by default. Some earlier versions can be tuned manually but I don't expect Kodi users to have the skills. Later versions removed the options, acknowledging that they were good required defaults.

It may have been possible to make Kodi set the options but it's very version dependent and I don't have the means to test (the versions are very old, unsupported and there are no docker images available). Also, from a responsibility pov it's a dba task that client applications should not be performing.

Versions are checked in the code. With the PR, Kodi stops if a server is too old. I am unable to test but gathered from related support posts on the internet that index creation fails without the mentioned correct global options. Allowing db migration to complete would produce a database crippled with missing indexes at best.

Should the version check be optional instead? or require a command line parameter to bypass?

- Collation:

True, the db servers offer better collations. than general. I kept general_ci to lower the risk of this change and alleviate the concerns expressed by @DaveTBlake in #23346. The purpose of the PR is not to improve or modify collation.

My reading of the code back when I commented on your PR showed that the music db uses a custom collation (alphanum) for sorting => db default collation is ignored
The other databases (video/epg/tv) collate/sort in Kodi code after retrieving the data from the db from what I can tell so even if MySQL/MariaDB provide a better default collation than Sqlite (binary!), Kodi collates again afterwards => the PR has no effect

However collation is also used by db engines in the WHERE part of the queries and I suspect there are differences between Sqlite and MySQL/MariaDB there, even for the music db
For ex. WHERE title like 'Cafe%' matches Cafe and Café with MySQL/MariaDB generic_ci, but Sqlite BINARY collation will only match Cafe.
The current situation is not changed by the PR for good and bad.

File: xbmc/dbwrappers/mysqldataset.cpp [hunk 1]
```diff
@@ -24,6 +24,8 @@
 #include <string_view>
 #include <vector>
 
+#include <fmt/base.h>
```
Comment (thexai) [inline xbmc/dbwrappers/mysqldataset.cpp]: I agree that for new code is better use fmt for format and avoid include that big class `StringUtils` but since in this file `StringUtils` is already included and used for more than format, in this case seems preferable use `StringUtils::Format` and avoid include <fmt/base.h> only for one call.

Comment (CrystalP) [reply xbmc/dbwrappers/mysqldataset.cpp]: I used format() but what was really needed was a constexpr string_view defined as the concatenation of other constexpr string_views. C++ doesn't allow it without a lot of additional code, which wasn't worth it.

To simplify I changed to a couple good old defines, which allows all strings to be compile-time constants and there is no runtime format.
Other way was to duplicate the text, defeating the point...

**Comment by CrystalP** [comment]
Changed the SQL string formatting per comment, and uppercased the constexpr variable names per guidelines.

**Review by thexai — APPROVED** [review]
Tested database migration on large video library on NAS (Server version: 10.11.11-MariaDB) and no issues found.

**Comment by CrystalP** [comment]
Thanks for testing.

Waiting for the builds to succeed after fixing the clang-format issue.

If users complain about the new database server version requirements, it would be possible to use either utf8mb3 or utf8mb4 after testing the server version.
utf8mb3 will be missing some characters and won't be future-proof, the same as today, but it's not necessary to completely kill it right away.

**Comment by thexai** [comment]
> If users complain about the new database server version requirements, it would be possible to use either utf8mb3 or utf8mb4 after testing the server version.

I don't think this is necessary and would add extra complexity and a logic that might not be intuitive: if the user (or the device automatically, NAS firmware, etc.) updates the MariaDB version to one that supports utf8mb4, then should Kodi migrate the database even if nothing else changes (without updating Kodi) or postpone it until the next kodi database bump? There are many possibilities, but if done incorrectly, unexpected and unwanted behaviors could appear, etc.

**Comment by CrystalP** [comment]
I'm not changing anything at this time, we'll see! The increased requirements should be posted in the release notes.

**Comment by scott967** [comment]
Just built this as debug and using sqlite databases from a few days ago had a failure updating MyMusic83.db:
` info <general>: Attempting to update the database MyMusic84 from version 83 to 84
error <general>: SQL: [MyMusic84.db] SQLite error SQLITE_ERROR (no such table: songview)
                            Query: select count(idSong) as NumSongs from songview 
error <general>: CMusicDatabase::GetSongsCount: () failed`

Looking at the songview table in MyMusic83.db I don't see anything wrong with it.   I restarted Kodi and I don't see any obvious problems in MyMusic84.db.   Songview looks OK.  Maybe spurious?
Log:  https://paste.kodi.tv/xaquvasiro.kodi

**Comment by CrystalP** [comment]
it's harmless - code triggered when a transaction is committed relies on songview, but a transaction is committed during the migration, before all db objects are created.
the problem is older than the linux port...

**Comment by DoughMucker** [comment]
Got a failure when upgrading MyVideos141 to MyVideos142. It's a mysql database running in a container on unraid.

2026-03-08 17:01:41.797 T:9065    error <general>: SQL: Can't copy schema for table 'sets' (1064)
2026-03-08 17:01:41.798 T:9065    error <general>: Unable to copy old database MyVideos141 to new version MyVideos142

Other databases upgrade fine, but Kodi then terminaes.

kodi.log:
https://pastebin.com/iTaGbxxD

**Comment by CrystalP** [comment]
Yes there is an issue but it's not related to this PR, see #27901
