### PR TITLE
Get rid of CFDEventMonitor static global instance.

### LINKED ISSUE #21240: Linux master builds segfault on exit
### Describe the bug
Here is a clear and concise description of what the problem is:

Since #21174 Linux master builds segfault on exit in thread FDEventMonitor.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No crash.

## Actual Behavior

Crash because Log() is used after logging was uninitialized.

### To Reproduce

1. Build current master
2. Exit kodi

### Debuglog

The debuglog can be found here:

Debug log ends with `INFO <general>: Exiting the application...`. Backtrace is:
```
Thread 6 "FDEventMonitor" received signal SIGSEGV, Segmentation fault.

#0  CLog::FormatAndLogInternal<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (format=..., 
    level=spdlog::level::debug, this=0x0) at /usr/include/c++/8/bits/shared_ptr_base.h:996
        message = "Thread FDEventMonitor 140736800478976 terminating"
        message = <optimized out>
#1  CLog::Log<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (format=..., level=spdlog::level::debug)
    at /home/mg/build/kodi/kodi-git/xbmc/utils/log.h:101
No locals.
#2  CLog::Log<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&> (format=..., level=0)
    at /home/mg/build/kodi/kodi-git/xbmc/utils/log.h:81
No locals.
#3  CThread::<lambda(CThread*, std::promise<bool>)>::operator()(CThread *, std::promise<bool>) (
    pThread=<optimized out>, promise=..., __closure=<optimized out>)
    at /home/mg/build/kodi/kodi-git/xbmc/threads/Thread.cpp:147
        name = "FDEventMonitor"
        autodelete = <optimized out>
        ss = <incomplete type>
        id = "140736800478976"
        __FUNCTION__ = <optimized out>
#4  0x000000000109e136 in std::__invoke_impl<void, CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > (__f=...) at /usr/include/c++/8/bits/invoke.h:60
No locals.
#5  std::__invoke<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > (
    __fn=...) at /usr/include/c++/8/bits/invoke.h:95
No locals.
#6  std::thread::_Invoker<std::tuple<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > >::_M_invoke<0, 1, 2> (this=<optimized out>) at /usr/include/c++/8/thread:244
No locals.
#7  std::thread::_Invoker<std::tuple<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > >::operator() (this=<optimized out>) at /usr/include/c++/8/thread:253
No locals.
#8  std::thread::_State_impl<std::thread::_Invoker<std::tuple<CThread::Create(bool)::<lambda(CThread*, std::promise<bool>)>, CThread*, std::promise<bool> > > >::_M_run(void) (this=<optimized out>)
    at /usr/include/c++/8/thread:196
No locals.
#9  0x00007fffed5b3c74 in ?? () from /usr/lib64/libstdc++.so.6
No symbol table info available.
#10 0x00007fffed0ac539 in start_thread (arg=0x7fffd6ffd700) at pthread_create.c:465
        pd = 0x7fffd6ffd700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140736800478976, 8021298964176438805, 140736817258206, 
                140736817258207, 140736615943776, 140736817258208, -8021248386058287595, -8021268289186298347}, 
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, 
              canceltype = 0}}}
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
        frame = <optimized out>
#11 0x00007fffefe43e0f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

First noticed in https://github.com/LibreELEC/LibreELEC.tv/pull/6353. Reproduced on desktop with symbols.

Reverting #21174 let the crash disappear.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #21240

@lrusak Do you think the way I solved the new case of a platform dependent service by extending `CPlatform` is okay?
@mglae by any chance, could you do a runtime-test and report back here?

### CODE REVIEW

**Comment by lrusak** [comment]
> @lrusak Do you think the way I solved the new case of a platform dependent service by extending `CPlatform` is okay?

I think you've done a fine job finding a solution to the problem and your solution is quite nice.

I am however concerned about our ongoing path of strict ordering when it comes to "service" init/deinit. I'm conflicted about the choice to make everything really structured to define proper init/deinit sequence and possibly constantly chasing that dream. I think I'm more inclined to make the init/deinit more error proof with the possibility of retrying.

When I imagine an init system I think of systems and the way it handles dependencies. You can declare specific dependencies for a service which also may have implicit dependencies. You can also define a service to retry if it failed and set the amount of retries.

I'm honestly not sure what is the best fit for our service management and would be willing to bounce some ideas around.

As for your code here I'm generally fine with it. If we decide to do something different later that's ok. I just hope we don't have to continually extend the cplatform and service broker init whenever we need to make a change.

File: xbmc/platform/Platform.h [hunk 1]
```diff
@@ -65,4 +95,65 @@ class CPlatform
...
+                                    {
+                                      const auto& sRef = *s.get();
+                                      return (typeid(sRef) == typeInfo);
+                                    }),
+                     m_services.end());
+  }
+
+private:
+  CCriticalSection m_critSection;
+  std::vector<std::shared_ptr<IPlatformService>> m_services; //!< Registered services
```
Comment (OBorce) [inline xbmc/platform/Platform.h:158]: This can be `std::unordered_map<std::type_index, std::shared_ptr<IPlatformService>>`
you get O(1) insert, add, delete and you know it is always only one per type, so you can't register 2 of the same type.

Comment (ksooo) [reply xbmc/platform/Platform.h:158]: Thanks for this very valuable feedback. Will change the code accordingly.

File: xbmc/platform/Platform.h [hunk 2]
```diff
@@ -65,4 +94,45 @@ class CPlatform
...
+    std::unique_lock<CCriticalSection> lock(m_critSection);
+    m_services.insert({std::type_index(typeid(serviceRef)), service});
+  }
+
+  /**\brief Deregister a platform service instance.
+   */
+  void DeregisterService(const std::type_info& typeInfo)
+  {
+    std::unique_lock<CCriticalSection> lock(m_critSection);
+    const auto it = m_services.find(std::type_index(typeInfo));
```
Comment (OBorce) [inline xbmc/platform/Platform.h:130]: you can call directly `m_services.erase(typeInfo);` no need to find it first.

**Comment by howie-f** [comment]
no more crashing on exit (debian bullseye). :+1:

**Comment by mglae** [comment]
Can confirm clean exit. Order is:

```
2022-04-21 22:58:11.997 T:8372    DEBUG <general>: FreeVisualisation() done
2022-04-21 22:58:12.000 T:8372     INFO <general>: Skipped 1 duplicate messages..
2022-04-21 22:58:12.000 T:8372    DEBUG <general>: CloseBundle - Closed bundle
2022-04-21 22:58:12.001 T:8372     INFO <general>: Unloaded skin
2022-04-21 22:58:12.003 T:8372     INFO <general>: unload sections
2022-04-21 22:58:12.003 T:8372     INFO <general>: CWSDiscoveryListenerUDP::Stop - Stopped
2022-04-21 22:58:12.003 T:8372    DEBUG <general>: LogindUPowerSyscall - delay lock sleep released
2022-04-21 22:58:12.003 T:8372    DEBUG <general>: ~CPVRManager: PVR Manager instance destroyed
2022-04-21 22:58:12.004 T:8452    DEBUG <general>: Thread Timer 140734614726400 terminating
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 0 --> 0 instances
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 1 --> 0 instances
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 2 --> 0 instances
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 3 --> 0 instances
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 4 --> 0 instances
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 5 --> 0 instances
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 6 --> 0 instances
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 7 --> 0 instances
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 8 --> 0 instances
2022-04-21 22:58:12.004 T:8372    DEBUG <general>: object 9 --> 0 instances
2022-04-21 22:58:12.010 T:8385    DEBUG <general>: Thread FDEventMonitor 140736800478976 terminating
2022-04-21 22:58:12.010 T:8382    DEBUG <general>: Thread Lirc 140736900187904 terminating
2022-04-21 22:58:12.010 T:8381    DEBUG <general>: Thread Announce 140736908580608 terminating
2022-04-21 22:58:12.010 T:8372     INFO <general>: Exiting the application...
```

File: xbmc/platform/Platform.h [hunk 3]
```diff
@@ -65,4 +94,43 @@ class CPlatform
...
+
+    return nullptr;
+  }
+
+protected:
+  /**\brief Register a new platform service instance.
+   */
+  void RegisterService(const std::shared_ptr<IPlatformService>& service)
+  {
+    if (!service.get())
```
Comment (garbear) [inline xbmc/platform/Platform.h:116]: shared_ptr has an operator(bool) that doesn't require exposing pointers: `if (!service)`

File: xbmc/platform/Platform.h [hunk 4]
```diff
@@ -65,4 +94,43 @@ class CPlatform
...
+      return;
+
+    const auto& serviceRef = *service.get();
```
Comment (garbear) [inline xbmc/platform/Platform.h:119]: Similarly,

```c++
const auto& serviceRef = *service;
```

File: xbmc/platform/Platform.h (hunk 3 above)
Comment (ksooo) [reply xbmc/platform/Platform.h:116]: Thanks.

File: xbmc/platform/Platform.h (hunk 4 above)
Comment (ksooo) [reply xbmc/platform/Platform.h:119]: Yep.
