### PR TITLE
[addons] fix crash when updating addon with private repo in manifest

### LINKED ISSUE #18715: [Addons] Crash when updating addon with private repo in manifest
### Describe the bug
Here is a clear and concise description of what the problem is:

When manually updating an addon that has a private repository in its manifest, Kodi will crash.  The source of the problem appears to be with changes made between Matrix Alpha 1 and Alpha 2:

https://github.com/xbmc/xbmc/blob/f60adf0651984f8f5227b6fbdb57478d932d6cb2/xbmc/addons/AddonInstaller.cpp#L678-L684

The call to CheckForUpdates is casting an object that is not a CRepository into one, which bypasses construction, but more specifically the CRepository::m_dirs member variable isn't really a vector<>, causing the crash when m_dirs is attempted to be iterated here:

https://github.com/xbmc/xbmc/blob/36962a8b9a3591dc245d442423c0bef94820ca31/xbmc/addons/Repository.cpp#L234-L237

The vector<> iterators are garbage, so it enters the loop and blows up calling dir.checksum.empty().

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Expected to not crash, I suppose?

## Actual Behavior
Please see description above.

## Possible Fix
Construct a new instance of CRepository and use that instead? That doesn't appear to be trivial with the information on-hand in that function and might need multiple changes to support it, so I didn't bother trying a PR for this one, leaving it to the pros.

### To Reproduce
1. Install an addon that has a private repository in its manifest
2. Attempt to update that addon manually via an external .zip file
3. After the addon is installed, Kodi will crash

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/resavetori.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:
N/A

## Additional context or screenshots (if appropriate)
N/A

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: (19.0-ALPHA3 (18.9.730) Git:20201031-bb0699db41). Platform: Windows NT x86 64-bit

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by howie-f**
## Description
fixes crash by correcting call to `IAddon->HasType()`

## Motivation and Context
closes #18715 

## How Has This Been Tested?
by issue reporter. thanks @djp952 

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

File: xbmc/addons/Addon.h [hunk 1]
```diff
@@ -59,7 +59,10 @@ class CAddon : public IAddon
    * @param[in] type The to checked type identifier
    * @return true in case the wanted type is supported, false if not
    */
-  bool HasType(TYPE type) const override { return m_addonInfo->HasType(type); }
+  bool HasType(TYPE type, bool mainOnly) const override
```
Comment (ksooo) [inline xbmc/addons/Addon.h:62]: May I suggest to not add another (unreadable bool) parameter here, but to:

a) Rename `HasType`to `ProvidesType`with semantics of current `HasType(false)`
b) Introduce `GetMainType`with the semantics of current `HasType(true)`

IMO, this makes the calling code far more readable/understandable.

File: xbmc/addons/AddonInstaller.cpp [hunk 2]
```diff
@@ -675,7 +675,7 @@ bool CAddonInstallJob::DoWork()
   {
     origin = ORIGIN_SYSTEM; // keep system add-on origin as ORIGIN_SYSTEM
   }
-  else if (m_addon->HasType(ADDON_REPOSITORY))
+  else if (m_addon->HasType(ADDON_REPOSITORY, true))
```
Comment (ksooo) [inline xbmc/addons/AddonInstaller.cpp:678]: The dilemma with bool params. What does 'true' mean here?

File: xbmc/addons/IAddon.h [hunk 3]
```diff
@@ -35,7 +35,7 @@ namespace ADDON
     virtual ~IAddon() = default;
     virtual TYPE MainType() const = 0;
     virtual TYPE Type() const =0;
-    virtual bool HasType(TYPE type) const = 0;
+    virtual bool HasType(TYPE type, bool mainOnly) const = 0;
```
Comment (ksooo) [inline xbmc/addons/IAddon.h:38]: Please, additional bool param. See my other comment.

File: xbmc/addons/Addon.h (hunk 1 above)
Comment (howie-f) [reply xbmc/addons/Addon.h:62]: yes, the bool params.. i intended to quickly get this fix in and later change the bool param to a `CheckMainOnly::YES/NO`-enum. but i'm also fine with options a) and b)... what would you like more?

File: xbmc/addons/IAddon.h [hunk 4]
```diff
@@ -15,6 +15,12 @@
 
 class TiXmlElement;
 
+enum class ADDON::MainOnly
```
Comment (garbear) [inline xbmc/addons/IAddon.h:18]: Can you add a quick doxy string for what this means?

**Comment by garbear** [comment]
I probably would have added a second method, like

```c++
virtual bool IsMainType(TYPE type) const = 0;
virtual bool HasType(TYPE type) const = 0;
```

or something but this is fine.

**Comment by basilgello** [comment]
Maybe a bit unrelated question but: are disabled add-ons excluded from add-on local search results? Raised here: https://github.com/basilgello/kodi-nightly-debian-repo/issues/2 and I never used add-on search to browse locally-installed add-ons.

**Comment by howie-f** [comment]
> Maybe a bit unrelated question

@basilgello from a very quick glance i think these are filtered on search: (you find the list in `addoninfo/AddonType.h`)
https://github.com/xbmc/xbmc/blob/5d48b1958f62cb9e81720a997aa37616387b0491/xbmc/addons/AddonDatabase.cpp#L1052

**Comment by howie-f** [comment]
> I probably would have added a second method

yes, i think this is the cleanest approach

**Comment by howie-f** [comment]
jenkins build this please

**Comment by howie-f** [comment]
jenkins build this please

File: xbmc/addons/addoninfo/AddonInfo.h [hunk 5]
```diff
@@ -138,7 +138,9 @@ class CAddonInfo
    * @param[in] mainOnly to check only in first defined main addon inside addon.xml
    * @return true in case the wanted type is supported, false if not
    */
-  bool HasType(TYPE type, bool mainOnly = false) const;
+  bool HasType(TYPE type, bool mainOnly) const;
+
+  bool HasType(TYPE type) const { return HasType(type, false); }
```
Comment (AlwinEsch) [inline xbmc/addons/addoninfo/AddonInfo.h:143]: Think to use only as one function, like there is the same in code write on other places as with `bool mainOnly = false` before. Only then another call from process work inside (where to new stack works).

To have, think to have more clean can it be then as:
```cpp
enum class TYPE_ASK_WAY
{
  Complete = 0,
  MainOnly = 1,
};

bool HasType(TYPE type, TYPE_ASK_WAY way) const;
```

So that callers must set this and there visible what wanted.

**Comment by ksooo** [comment]
> I probably would have added a second method, like
>
>virtual bool IsMainType(TYPE type) const = 0;
>virtual bool HasType(TYPE type) const = 0;
>
>or something but this is fine.

Exactly, what I suggested. :-)

**Comment by howie-f** [comment]
> Exactly, what I suggested. :-)

first i have to win the fight against `gtest` :)

**Comment by howie-f** [comment]
jenkins build this please

File: xbmc/addons/addoninfo/AddonInfo.h [hunk 6]
```diff
@@ -140,6 +140,14 @@ class CAddonInfo
    */
   bool HasType(TYPE type, bool mainOnly = false) const;
 
+  /**
+   * @brief To check an addon's main type
+   *
+   * @param[in] type Type identifier to be checked
+   * @return true in case the wanted type is supported, false if not
+   */
+  bool IsMainType(TYPE type) const;
```
Comment (ksooo) [inline xbmc/addons/addoninfo/AddonInfo.h:149]: "Is" reads strange. Why not "Has"? And addon **has** a type, but it **is** not a type, right?

Comment (ksooo) [reply xbmc/addons/addoninfo/AddonInfo.h:149]: And the doc speaks about "supported", yet another verb, btw. ;-)

Comment (howie-f) [reply xbmc/addons/addoninfo/AddonInfo.h:149]: yes, that's both correct :) .. but beside the naming of that function i'm sorry to say i've no idea why this test keeps failing

File: xbmc/addons/test/TestAddonInfoBuilder.cpp [hunk 7]
```diff
@@ -156,6 +156,8 @@ TEST_F(TestAddonInfoBuilder, TestGenerate_DBEntry)
   EXPECT_TRUE(addon->HasType(ADDON_AUDIO));
   EXPECT_FALSE(addon->HasType(ADDON_GAME));
 
+  EXPECT_FALSE(addon->IsMainType(ADDON_AUDIO));
```
Comment (howie-f) [inline xbmc/addons/test/TestAddonInfoBuilder.cpp:159]: why is this test failing? i just don't get it

File: xbmc/addons/AddonInstaller.cpp [hunk 8]
```diff
@@ -675,7 +675,7 @@ bool CAddonInstallJob::DoWork()
   {
     origin = ORIGIN_SYSTEM; // keep system add-on origin as ORIGIN_SYSTEM
   }
-  else if (m_addon->HasType(ADDON_REPOSITORY))
+  else if (m_addon->IsMainType(ADDON_REPOSITORY))
```
Comment (howie-f) [inline xbmc/addons/AddonInstaller.cpp:678]: and i am wondering if the fix for this crash is a simple
`else if (m_addon->MainType() == ADDON_REPOSITORY)`
but this isn't tested

File: xbmc/addons/addoninfo/AddonInfo.h (hunk 6 above)
Comment (howie-f) [reply xbmc/addons/addoninfo/AddonInfo.h:149]: @ksooo let's just call it `HasMainType()` - only the test is still a mystery to me. can't be right to just kick it out. what do you think?

File: xbmc/addons/AddonInstaller.cpp (hunk 8 above)
Comment (AlwinEsch) [reply xbmc/addons/AddonInstaller.cpp:678]: For there becomes only the first entry in addon.xml with `<extension point="...">` (xbmc.addon.repository) used.

All other parts and later "extension point"'s becomes ignored.
The `HasType` looks also about subparts:
```xml
    <extension point="xbmc.python.pluginsource" library="resources/lib/default.py">
        <provides>video</provides>
    </extension>
```
On this should `ADDON_PLUGIN` and `ADDON_VIDEO` true.
And all other `extension point` parts becomes checked about type.

Comment (AlwinEsch) [reply xbmc/addons/AddonInstaller.cpp:678]: As a result, the difference between CAddon and CAddonInfo has to be taken into account.

- CAddonInfo gives the complete addon with all its parts
- CAddon brings the respective part to use in it

As a result, a CAddonInfo can e.g. belong to 5 different CAddon classes.

File: xbmc/addons/test/TestAddonInfoBuilder.cpp (hunk 7 above)
Comment (AlwinEsch) [reply xbmc/addons/test/TestAddonInfoBuilder.cpp:159]: There becomes `addonType.Insert("provides", "video audio");` added, where marks it as `ADDON_VIDEO` and  `ADDON_AUDIO`.

File: xbmc/addons/addoninfo/AddonInfo.h (hunk 6 above)
Comment (ksooo) [reply xbmc/addons/addoninfo/AddonInfo.h:149]: HasMainType would be fine for me

**Comment by howie-f** [comment]
then this all boils down a lot ;)
jenkins build this please

File: xbmc/addons/Addon.h [hunk 9]
```diff
@@ -61,6 +61,14 @@ class CAddon : public IAddon
    */
   bool HasType(TYPE type) const override { return m_addonInfo->HasType(type); }
 
+  /**
+   * @brief To check complete addon (not only this) has a specific main type
```
Comment (garbear) [inline xbmc/addons/Addon.h:65]: Can you clarify what a "main" type is here? I think it's the first extension point in addon.xml, right?

Comment (howie-f) [reply xbmc/addons/Addon.h:65]: yes, wasn't quite simple. main type means the first extension point including provided subcontent (like `ADDON_VIDEO` for instance). hope that is explained correctly and understandable. i would add it to the doxy

**Comment by howie-f** [comment]
jenkins build this please

**Review by ksooo — APPROVED** [review]
