### PR TITLE
[IFile][CFile] Rework `ReadString` into `ReadLine`

### LINKED ISSUE #25980: Library scan with hidden files and MacOsx files “._” leads to a crash
### Describe the bug

Library scan with hidden files and MacOsx files “._” leads to a crash.

### To Reproduce

1. Enable "Show hidden files and directories"
2. Add your library some MacOsx files something like "._tvshow.nfo"
3. Select directory contains "TV shows"  and information provider "Local information only" 
4. press scan library

### Debuglog

The debuglog can be found here:
[https://pastebin.com/raw/1Nznx1X8](https://pastebin.com/raw/1Nznx1X8)

MacOsx for Library
[TestScanFiles.zip](https://github.com/user-attachments/files/17776322/TestScanFiles.zip)

Logcat
```Build fingerprint: 'NVIDIA/mdarcy/mdarcy:11/RQ1A.210105.003/7825230_3167.5736:user/release-keys'
Revision: '0'
ABI: 'arm64'
Timestamp: 2024-11-15 15:07:38+0100
pid: 10590, tid: 12439, name: Thread-3  >>> org.xbmc.kodi <<<
uid: 10082
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: 'exiting due to SIG_DFL handler for signal 11'
    x0  0000000000000000  x1  0000000000003097  x2  0000000000000006  x3  00000030f75ecc60
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000028
    x8  00000000000000f0  x9  937f3b4096a70b84  x10 0000000000000000  x11 ffffffc0fffffbdf
    x12 0000000000000001  x13 00000000673755aa  x14 0034a17d8a402800  x15 000016c095bfdab9
    x16 0000002e5c617c80  x17 0000002e5c5f9870  x18 000000316fa4c000  x19 000000000000295e
    x20 0000000000003097  x21 00000000ffffffff  x22 00000030f75ece48  x23 0000005cd5a1f9a0
    x24 0000000000000040  x25 0000003167ff7000  x26 000000000000000b  x27 0000005cd5a1f5c0
    x28 0000000000000000  x29 00000030f75ecce0
    lr  0000002e5c5ad2a0  sp  00000030f75ecc40  pc  0000002e5c5ad2cc  pst 0000000000000000
backtrace:
      #00 pc 000000000004e2cc  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: 45994aaacbd3639b43f2bde9e3052edc)
      #01 pc 000000000000506c  /system/bin/app_process64 (art::SignalChain::Handler(int, siginfo*, void*)+1112) (BuildId: bdcc463a75a1be87eb0f7478ec16547d)
      #02 pc 0000000000000690  [vdso] (__kernel_rt_sigreturn)
      #03 pc 0000000002b4a424  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (XFILE::CFile::ReadString(std::__ndk1::vector<char, std::__ndk1::allocator<char> >&)+436)
      #04 pc 00000000024b33bc  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (KODI::PLAYLIST::CPlayListM3U::Load(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)+392)
      #05 pc 0000000002b5d078  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (XFILE::CPlaylistFileDirectory::GetDirectory(CURL const&, CFileItemList&)+88)
      #06 pc 0000000002b4c770  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (XFILE::CFileDirectoryFactory::Create(CURL const&, CFileItem*, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)+1900)
      #07 pc 0000000002b3f490  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (XFILE::CDirectory::FilterFileDirectories(CFileItemList&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, bool)+172)
      #08 pc 0000000002b3ed58  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (XFILE::CDirectory::GetDirectory(CURL const&, std::__ndk1::shared_ptr<XFILE::IDirectory> const&, CFileItemList&, XFILE::CDirectory::CHints const&)+2252)
      #09 pc 0000000002b3e2a4  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (XFILE::CDirectory::GetDirectory(CURL const&, CFileItemList&, XFILE::CDirectory::CHints const&)+96)
      #10 pc 0000000002b3e1a0  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (XFILE::CDirectory::GetDirectory(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, CFileItemList&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, int)+144)
      #11 pc 0000000002b3f5e8  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (XFILE::CDirectory::EnumerateDirectory(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, std::__ndk1::function<void (std::__ndk1::shared_ptr<CFileItem> const&)> const&, std::__ndk1::function<bool (std::__ndk1::shared_ptr<CFileItem> const&)> const&, bool, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, int)+92)
      #12 pc 000000000239b734  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (KODI::VIDEO::CVideoInfoScanner::EnumerateSeriesFolder(CFileItem*, std::__ndk1::vector<KODI::VIDEO::EPISODE, std::__ndk1::allocator<KODI::VIDEO::EPISODE> >&)+980)
      #13 pc 00000000023997a8  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForEpisodes(CFileItem*, long, std::__ndk1::shared_ptr<ADDON::CScraper> const&, bool, CGUIDialogProgress*)+80)
      #14 pc 0000000002397d94  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (KODI::VIDEO::CVideoInfoScanner::RetrieveInfoForTvShow(CFileItem*, bool, std::__ndk1::shared_ptr<ADDON::CScraper>&, bool, CScraperUrl*, bool, CGUIDialogProgress*)+656)
      #15 pc 0000000002396e3c  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (KODI::VIDEO::CVideoInfoScanner::RetrieveVideoInfo(CFileItemList&, bool, CONTENT_TYPE, bool, CScraperUrl*, bool, CGUIDialogProgress*)+804)
      #16 pc 0000000002395d54  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (KODI::VIDEO::CVideoInfoScanner::DoScan(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&)+2676)
      #17 pc 0000000002394c1c  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (KODI::VIDEO::CVideoInfoScanner::Process()+556)
      #18 pc 0000000002395220  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (KODI::VIDEO::CVideoInfoScanner::Start(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char> > const&, bool)+544)
      #19 pc 00000000022e4a00  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (CVideoLibraryScanningJob::Work(CVideoDatabase&)+32)
      #20 pc 00000000022e1b34  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (CVideoLibraryJob::DoWork()+68)
      #21 pc 0000000002430df8  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (CJobWorker::Process()+96)
      #22 pc 00000000024a256c  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so (CThread::Action()+40)
      #23 pc 00000000024a2778  /data/app/~~stLjdlQHcUq7v6KLZWON3g==/org.xbmc.kodi-3DI22zDbBCGVt1qx6A04dg==/lib/arm64/libkodi.so
      #24 pc 00000000000afd4c  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+64) (BuildId: 45994aaacbd3639b43f2bde9e3052edc)
      #25 pc 0000000000050288  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 45994aaacbd3639b43f2bde9e3052edc)
```

### Your Environment
Used Operating system:

 - [X] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by neo1973**
## Description

The function signature of `IFile::ReadString` and `CFile::ReadString` has a major shortcoming: There is no way to detect if a full line or only what fits into the buffer has been read. Also the name doesn't make it clear that it's reading lines.

This PR renames `ReadString` into `ReadLine` and gives it rich error handling capabilities. In addition it returns the number of read bytes which allows proper processing of lines containing `'\0'` bytes and saves some `strlen` calls.

Lastly the better error handling is used to correct the implementation of the `CFile::ReadLine` overload that's reading an arbitrary long line . This fixes #25980. Also the function signature has been changed to work on a `std::string` instead of a `std::vector<char>` as this is was callers want anyway.

**If this approach is welcome I will add unit tests before merging.**

## Motivation and context

This fixes #25980. Also the old interface was too vague which caused confusion in the past, see e.g. #22222.

## How has this been tested?

Unit tests are passing and the example from #25980 doesn't crash.

## What is the effect on users?

None.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

File: xbmc/playlists/PlayListPLS.cpp [hunk 1]
```diff
@@ -79,19 +79,18 @@ bool CPlayListPLS::Load(const std::string &strFile)
     return false;
   }
 
-  char szLine[4096];
   std::string strLine;
+  strLine.reserve(4096);
```
Comment (CastagnaIT) [inline xbmc/playlists/PlayListPLS.cpp:83]: imo all these "reserve" (also on other cases shown here) are not really needed
anyway keep a value of 4096 for most of time is too high, can be lowered to 1024

**Review by CastagnaIT — APPROVED** [review]
tested a bouch of strm seem to works as before,
also for the problematic strm with long text that i fixed time ago its ok

just commented for "reserve" cases, imo can be removed or lowered higher value cases

**Comment by neo1973** [comment]
Sigh... While writing the unit tests I realized that `ReadLine` of `IFile` and `CFile` are behaving differently. `IFile` preserves the line end character (kind of, `\r\n\` becomes `\r`, `\n\r` becomes `\n`) while `CFile` removes it when `m_pBuffer` exists and does the `IFile` behavior if `m_pBuffer` doesn't exist.

Something to cleanup in a followup PR.

**Comment by neo1973** [comment]
Jenkins build this please

**Comment by neo1973** [comment]
Jenkins build this please
