### PR TITLE
[listproviders][video][PVR][utils][builtins] Fix and Refactor Video Select Actions

### LINKED ISSUE #23722: Setting to Choose action when item is selected not honoured for home screen widgets
## Bug report
Movie or music video plays or present resume dialog but no option to show information.
Works as expected for episodes.
### Describe the bug
If the Settings>Media>Videos>Default Select Action is set to "Choose". When a music video or movie if selected from a widget, it does not offer the option to show information. It either play immediately or if there is a resume point, offers the resume dialog but without the option to show information.
As a comparison, episodes gives either Play/Show Info or Resume/Beginning/Show info when selected
Here is a clear and concise description of what the problem is:

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Present dialog to either Play/Show Info or Resume/Beginning/Show info when selected

### To Reproduce

1. Settings>Media>Videos>Default Select Action is set to "Choose"
2. Click on a music video widget or movie widget
3. Compare behaviour with tv show widget

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x ] Linux (LibreELEC)
 - [ ] macOS
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
 Master as at Sep 3, 2023

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #23722

Well, I only wanted to quickly fix a bug and it ended with a larger refactoring of the video select action handling code across the code base. I think the code is now in a much better maintainable shape than it was before.

Runtime-tested on macOS and Android, latest Kodi master.

@enen92 maybe you could have a look at the code changes? I tried to split stuff into logical chunks, so best to review commit by commit.

### CODE REVIEW

File: xbmc/video/VideoSelectActionProcessor.cpp [hunk 1]
```diff
@@ -0,0 +1,152 @@
...
+ *  SPDX-License-Identifier: GPL-2.0-or-later
+ *  See LICENSES/README.md for more information.
+ */
+
+#include "VideoSelectActionProcessor.h"
+
+#include "FileItem.h"
+#include "ServiceBroker.h"
+#include "dialogs/GUIDialogContextMenu.h"
+#include "dialogs/GUIDialogSelect.h"
```
Comment (enen92) [inline xbmc/video/VideoSelectActionProcessor.cpp:14]: It would be great if somehow this could be further decoupled. I mean isn't it possible to only have methods in this class which return a list of items and their respective action?
Opening the dialog select would fit better in the previous base class since it is in the scope of gui/guilib. A quick search on the phone seems to indicate all these gui includes are just required to open the dialog select. All the remaining code is pretty much gui free

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp [hunk 2]
```diff
@@ -518,7 +518,7 @@ int PlayOrQueueMedia(const std::vector<std::string>& params, bool forcePlay)
     item.SetProperty("check_resume", false);
   }
 
-  if (item.m_bIsFolder || item.IsPlayList())
+  if (item.m_bIsFolder || item.IsPlayList() || !forcePlay)
```
Comment (enen92) [inline xbmc/interfaces/builtins/PlayerBuiltins.cpp]: Maybe place the forceplay check before the isplaylist check? I mean, the playlist check should be a bit more intensive so in the cases force play is not set it should save a few CPU cycles.

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp [hunk 3]
```diff
@@ -812,16 +822,17 @@ static int SubtitleShiftDown(const std::vector<std::string>& params)
 ///     <b>`QueueMedia(media[\,isdir][\,1][\,playnext]\,[playoffset=xx])`</b>
 ///     \anchor Builtin_QueueMedia,
 ///     Queues the given media. This can be a playlist\, music\, or video file\, directory\,
-///     plugin or an Url. The optional parameter "\,isdir" can be used for playing
-///     a directory. "\,1" will start the media without switching to fullscreen.
-///     If media is a playlist\, you can use playoffset=xx where xx is
-///     the position to start playback from.
+///     plugin\, disc image stack\, video file stack or an URL. The optional parameter "\,isdir" can
```
Comment (enen92) [inline xbmc/interfaces/builtins/PlayerBuiltins.cpp:825]: Can you use markdown inline code statements (using `) instead of the double quotes (") around isdir?

File: xbmc/FileItem.cpp [hunk 4]
```diff
@@ -3741,14 +3741,14 @@ bool CFileItem::LoadDetails()
     return true;
   }
 
-  if (m_bIsFolder && URIUtils::IsPVRRecordingFileOrFolder(GetPath()))
+  if (URIUtils::IsPVRRecordingFileOrFolder(GetPath()))
```
Comment (enen92) [inline xbmc/FileItem.cpp:3744]: I think this is likely a getdynpath here. I.e. a plugin:// item could resolve to a Pvr recording right? In such cases behaviour would differ if playing the plugin item or the Pvr recording directory.

**Review by enen92 — COMMENTED** [review]
This looks great. Thanks a lot!
Added a few comments in places I think it can be improved.

File: xbmc/video/VideoSelectActionProcessor.cpp (hunk 1 above)
Comment (ksooo) [reply xbmc/video/VideoSelectActionProcessor.cpp:14]: This class is intended to be a GUI helper. If every calling code would need to implement the dialog logic itself (in exactly the same way - as a code copy, as you want no helper ;-), this would contradict the idea of the refactoring a bit.

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp (hunk 2 above)
Comment (ksooo) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp]: I need to rethink the naming of the variable `forcePlay` - actually it should be named 'queueItem' and checks adapted to the inverse semantics.

File: xbmc/video/VideoSelectActionProcessor.cpp (hunk 1 above)
Comment (enen92) [reply xbmc/video/VideoSelectActionProcessor.cpp:14]: Then can you please move the file itself to a guilib folder? e.g. video/guilib/XXX.cpp?
Would make the intention clear

Comment (enen92) [reply xbmc/video/VideoSelectActionProcessor.cpp:14]: Or guilib/video/XXX.cpp?
It will be easy to find the "offending" consumers

Comment (ksooo) [reply xbmc/video/VideoSelectActionProcessor.cpp:14]: Okay, video/guilib/ it will be. I use this schema in pvr already...

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp (hunk 3 above)
Comment (ksooo) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:825]: Not introduced by me in this PR, but yes I can change this.

File: xbmc/FileItem.cpp (hunk 4 above)
Comment (ksooo) [reply xbmc/FileItem.cpp:3744]: Nope. I need to check the pvr-URL, which is the unchangable identity of the item.

> plugin:// item could resolve to a Pvr recording right

Those cases currently will not work as by design. Dyn path is just a single de-reference, what you are referring to would need a chain of path: plugin -> pvr -> file

**Comment by ksooo** [comment]
@enen92 requested changes are incorporated now. Good to go in?

**Review by enen92 — APPROVED** [review]

File: xbmc/video/windows/GUIWindowVideoBase.h [hunk 5]
```diff
@@ -11,22 +11,18 @@
...
-  SELECT_ACTION_PLAY,
-  SELECT_ACTION_PLAYPART,
-  SELECT_ACTION_QUEUE
-};
+class CVideoSelectActionProcessor;
+} // unnamed namespace
 
 class CGUIWindowVideoBase : public CGUIMediaWindow, public IBackgroundLoaderObserver
 {
+  friend class CVideoSelectActionProcessor;
```
Comment (sundermann) [inline xbmc/video/windows/GUIWindowVideoBase.h:24]:
```suggestion
  friend class ::CVideoSelectActionProcessor;
```
Fixes build failures on Linux

**Comment by ksooo** [comment]
Side note: Video default select action handling for Favorites (Home screen Favorites widget, Favorites window, (deprecated Favorites dialog) is still pending. This will be a bit more work and might come with a follow-up PR.

**Comment by xpeiro** [comment]
Hi, thanks for the great work first of all!
On omega beta 3 (and 2) on android (fire cube) the default select action does not seem to work for TV shows. For movies it works fine, but for tv shows if set to "show information" or "choose" it just goes into the "seasons" view directly as if "play" were the default action. If I open the context menu with the c key, with the cursor on the tv show and select "information", only then it does show the information screen. This happens on both library tv shows and addon tv shows. Am I misunderstanding something? Thanks again!

**Comment by ksooo** [comment]
> but for tv shows if set to "show information" or "choose" it just goes into the "seasons" view directly

Works as designed and imo has never behaved different. default select action setting applies only to media (movies, episodes), not folders (tv shows, seasons. movie sets).

**Comment by xpeiro** [comment]
Yes, sorry you are right, I just reverted to a clean nexus install and it works like you say. In my previous nexus setup I somehow had it so that when clicking on a tv show (mostly in an addon home screen widget), it showed the information screen and only after clicking again did it go to seasons view. I have no idea how to replicate this functionality now on either omega or a clean nexus install, so maybe it was a bug or something, but I liked it... Anyway, sorry for the confusion.
