### PR TITLE
[database] Fix 'endless' waiting on splash screen when connect to remote database(s) fails.

### LINKED ISSUE #25262: app stays on the splash screen indefinitely when DB is inaccessible
### Describe the bug
Here is a clear and concise description of what the problem is:

I have DB on an external PC on the home LAN. Trying to launch Kodi in the office doesn't get me past splash screen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Main menu is shown, Kodi is usable

## Actual Behavior

Kodi stays on splash screen

### To Reproduce

1. Configure external DB pointing to a LAN address via advanced settings
2. Launch Kodi in another LAN
3. Observe splash screen never disappearing

### Debuglog

The debuglog can be found here: [log.txt](https://github.com/xbmc/xbmc/files/15452797/log.txt)

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

In the office I'm behind a corporate proxy and my LAN address is 10.x.y.z (DB address is in a different IP address space).

The issue looks similar to #25157

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: macOS 13.6.7
 - Kodi version: master nightly from today (latest)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #25262

Changed: Instead of trying again and again to connect to a non accessible database, now, whenever during Kodi startup connect to a remote database fails, Kodi startup will immediately stopped, an error message will be displayed on splash screen for 10 secs, then Kodi exits.

Screenshot 2025-04-18 at 13 14 38
Screenshot 2025-04-18 at 13 07 35

Runtime-tested on macOS and Android.

@enen92 if you are around, could you have alook?

### CODE REVIEW

**Comment by ksooo** [comment]
@samnazarko ping

File: xbmc/dbwrappers/dataset.h [hunk 1]
```diff
@@ -31,7 +31,7 @@ class Dataset; // forward declaration of class Dataset
 
 #define DB_CONNECTION_NONE 0
 #define DB_CONNECTION_OK 1
-#define DB_CONNECTION_BAD 2
+#define DB_CONNECTION_DATABASE_NOT_FOUND 2
```
Comment (enen92) [inline xbmc/dbwrappers/dataset.h:34]: Constexpr int? I think we're moving away from defines

**Review by enen92 — COMMENTED** [review]
Globally ok, left a few comments

File: xbmc/application/Application.cpp [hunk 2]
```diff
@@ -597,6 +602,24 @@ bool CApplication::Initialize()
...
   CServiceBroker::GetRenderSystem()->ShowSplash("");
 
+  if (!allDatabasesInitialized)
+  {
+    // Bail out if any of the databases failed to initialize properly.
+    CLog::Log(LOGFATAL, "Failed to initialize databases");
+
+    const std::string dbInitFailedExiting{g_localizeStrings.Get(24187)};
+
+    unsigned int secondsLeftUntilExit{10};
```
[the remark this answers is not in the document]
Comment (ksooo) [reply xbmc/application/Application.cpp:612]: > Please make this a constexpr.

No, this is a variable, not a constant. Value will be decreased until zero in the while loop.

> but might external DBs be used with wol hosts? If so, 10 secs could be too small. 

 Yes, but you misread the code. The 10 secs are not a timeout for db connects. The 10 is the start value for a count down, which will be started after (!) db connect errors, to keep the error message visible to the user before kodi exits. Connect timeout is different.

File: xbmc/dbwrappers/dataset.h (hunk 1 above)
Comment (ksooo) [reply xbmc/dbwrappers/dataset.h:34]: Okay, will change.

File: xbmc/application/Application.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (enen92) [reply xbmc/application/Application.cpp:612]: The constexpr was for the 10 value not for the "timer" itself (just to avoid the magic number). But it's fine as it is assuming this is only for presentation.

So I assume nothing happens during these 10 secs right? Just a timeout for exit.
Fine to me, although in that case 10 secs might be too high just for presentation purposes.

[the remark this answers is not in the document]
Comment (ksooo) [reply xbmc/application/Application.cpp:612]: > So I assume nothing happens during these 10 secs right?

Correct.

> although in that case 10 secs might be too high just for presentation purposes.

We can change that in case users complain. But this message will never be shown to 99% of our users, so ...

File: xbmc/dbwrappers/Database.h [hunk 3]
```diff
@@ -255,7 +255,13 @@ class CDatabase
                         CDbUrl& dbUrl,
                         SortDescription& sorting);
 
-  bool Connect(const std::string& dbName, const DatabaseSettings& db, bool create);
+  enum class ConnectionState
+  {
+    STATE_ERROR,
+    STATE_DATABASE_NOT_FOUND,
+    STATE_CONNECTED,
+  };
```
Comment (CrystalP) [inline xbmc/dbwrappers/Database.h:263]: newline to separate from next line please

**Review by CrystalP — COMMENTED** [review]
A couple style comments.

File: xbmc/DatabaseManager.cpp [hunk 4]
```diff
@@ -60,6 +61,9 @@ void CDatabaseManager::Initialize()
   CLog::Log(LOGDEBUG, "{}, updating databases... DONE", __FUNCTION__);
 
   m_bIsUpgrading = false;
+
+  return std::none_of(m_dbStatus.cbegin(), m_dbStatus.cend(),
+                      [](const auto& db) { return db.second != DBStatus::READY; });
```
[the remark this answers is not in the document]
Comment (ksooo) [reply xbmc/DatabaseManager.cpp:67]: Sure. Good idea.

File: xbmc/dbwrappers/Database.h (hunk 3 above)
Comment (ksooo) [reply xbmc/dbwrappers/Database.h:263]: Will change that.

**Review by enen92 — APPROVED** [review]

File: xbmc/application/Application.cpp [hunk 5]
```diff
@@ -577,18 +577,23 @@ bool CApplication::Initialize()
...
+      {
+        allDatabasesInitialized = databaseManager.Initialize();
+        event.Set();
+      });
 
-  std::string localizedStr = g_localizeStrings.Get(24150);
+  const std::string connecting{g_localizeStrings.Get(24186)};
+  const std::string updating{g_localizeStrings.Get(24150)};
   int iDots = 1;
   while (!event.Wait(1000ms))
```
Comment (howie-f) [inline xbmc/application/Application.cpp:592]: @ksooo can this be read like
 "if the submitted event takes longer than 1000ms then display the text message on the splash"?

i'm asking because i'm testing LE13 on a slow raspberry pi and i _always_ see the message "Database migration in progress... please wait" ..... even though there is no database migration executed.
nothing in the loig about a database migration, and my shared mariadb is already migrated.

in that case the amount of time should be increased a little, maybe 2500ms?

on my living room htpc - which is way faster - i do not get the message on the splash.

File: xbmc/application/Application.cpp [hunk 6]
```diff
@@ -577,18 +577,23 @@ bool CApplication::Initialize()
...
   {
-    if (databaseManager.IsUpgrading())
```
Comment (howie-f) [inline xbmc/application/Application.cpp:590]: or is it maybe this `if` that needs to be restored. just guessing
