### PR TITLE
[Fix] Update fileitem stream details from the currently playing stream

### LINKED ISSUE #18702: StreamDetails broken for DVD, Bluray and ISO
### Describe the bug

Sometime early 2019 a change to v18 caused a break in populating the **streamdetails** table. 

A few attempts were made to fix the issue, ultimately resulting in a change to the way streamdetails were read and saved.

This new method will only read and save streamdetails in the following instances:

1. First scan of the movie \ episode (not subsequent delete from library and rescan)
2. Refresh of the movie \ episode

It no longer saves streamdetails from playback.

This caused a flood of complaints, and we still receive complaints about missing streamdetails and missing flags

Some relevant PR's here...
https://github.com/xbmc/xbmc/pull/12651
https://github.com/xbmc/xbmc/pull/15589
https://github.com/xbmc/xbmc/issues/15896
https://github.com/xbmc/xbmc/issues/15929
https://github.com/xbmc/xbmc/pull/16342

## Expected Behavior

Streamdetails for every type of video file/folder handled by Kodi should populate the streamdetails table.

## Actual Behavior
The current implemented method in v18 and v19 does not work for the following:

Movies or episodes saved with Bluray folder structure
Movies or episodes saved with DVD folder structure
Movies or episodes saved as an ISO file

Which means this works in a single instance only - when using single video files.

This does not work as expected for TV Shows even when using standard single video files like mkv. Refreshing the TV Show and then answering Yes to refresh the episodes does not refresh streamdetails.

Each episode needs to be refreshed individually for this to work. If there are 50 episodes in the show, that is a lot of work to refresh each episode.

Refreshing is not the way to go. It kills any personal edits the user has made for that movie/episode.

Could this entire approach be redesigned. It really is making a mess of peoples libraries.

### To Reproduce
1.  Scan a bluray structure movie into the library.
2.  Note the missing codecs / flags.
3.

### Debuglog
The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Flags / codecs displayed for single file videos (mkv, avi, etc)
singlefile

Bluray structure displays no flags / codecs
bluray

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: All
 - Kodi version: v18 and v19

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by the-black-eagle**
## Description
Fixes the issue where playing Iso's or DVD/Bluray structured directories no longer updates the fileitem details.

## Motivation and Context
Fixes https://github.com/xbmc/xbmc/issues/18702

## How Has This Been Tested?
Tested against iso images and dvd structure directories.  Before playing the test files the GUI only showed the length of the item.  After playing, all flags were shown correctly.

## Screenshots (if appropriate):
Before playing.
<a href="https://ibb.co/CzmNd9R">screenshot00040</a>

After playing
<a href="https://ibb.co/F3Dgszg">screenshot00041</a>
## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by arnova — CHANGES_REQUESTED** [review]

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 1]
```diff
@@ -4970,6 +4985,8 @@ void CVideoPlayer::GetVideoStreamInfo(int streamId, VideoStreamInfo &info)
   info.DestRect = s.DestRect;
   info.VideoRect = s.VideoRect;
   info.codecName = s.codec;
+  if (m_pInputStream->IsStreamType(DVDSTREAM_TYPE_DVD))
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:4988]: Can this somehow be avoided by setting it on the struct (independently of the stream type) instead of the conditions when getting the info?

File: xbmc/Application.cpp [hunk 2]
```diff
@@ -3173,8 +3173,7 @@ void CApplication::OnPlayBackStarted(const CFileItem &file)
   CLog::LogF(LOGDEBUG,"CApplication::OnPlayBackStarted");
 
   // check if VideoPlayer should set file item stream details from its current streams
-  if (file.GetProperty("get_stream_details_from_player").asBoolean())
-    m_appPlayer.SetUpdateStreamDetails();
+  m_appPlayer.SetUpdateStreamDetails();
```
[the remark this answers is not in the document]
Comment (arnova) [reply xbmc/Application.cpp:3176]: An alternative could be to only update (or store) details when we don't have any yet.

[the remark this answers is not in the document]
Comment (the-black-eagle) [reply xbmc/Application.cpp:3176]: Sure. Is ```if (file.GetProperty("get_stream_details_from_player").asBoolean() || file.IsDiscImage() ||
      file.IsDVDFile() || file.IsBDFile())``` enough or does it need some more ?

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 1 above)
Comment (the-black-eagle) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:4988]: I could use `m_CurrentStream.hint.dvd` but that particular test is used several times already in the code so I presumed it was the correct way to do it.

File: xbmc/Application.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (arnova) [reply xbmc/Application.cpp:3176]: I think it also requires IsDVD/IsOnDVD/IsBluray, not sure though.

[the remark this answers is not in the document]
Comment (the-black-eagle) [reply xbmc/Application.cpp:3176]: I'd go with only updating or storing details when we don't have any but this would mean that for dvds with multiple audio tracks, eg 2.0 & 5.1 that the details would be set on first play.  If I played it in stereo first then it would always show as that, even if I later played it in surround. Personally I'd prefer it to update to what it is currently but I'm fine with not doing so if that's what the team wants.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 1 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:4988]: my question was if we could set the conditions on the setter (wherever that is) and not on the getter. The getter should return whatever is on the struct without the need for checking any conditions

File: xbmc/Application.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (arnova) [reply xbmc/Application.cpp:3176]: Good point, I'm with you then.

Please also have a look at the comments in https://github.com/xbmc/xbmc/pull/15589 as to why ALWAYS updating (Without a condition) stream details was causing problems.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 1 above)
Comment (the-black-eagle) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:4988]: Ah, right I see what you mean. If you omit the check, it will return `h262` instead of `mpeg-2`.  Maybe there is somewhere else in the code where h262 can be translated to mpeg2 but currently the GUI will not show a flag when fed with h262.  I don't know if that is purely a skin thing or somewhere in the GUI core code.  I do agree that if it could be handled elsewhere it would be better to do so.

Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:4988]: Ah if that is just a skin thing it should be fixed elsewhere. @jjd-uk might be able to help as he did similar things in the past

File: xbmc/Application.cpp (hunk 2 above)
[the remark this answers is not in the document]
Comment (the-black-eagle) [reply xbmc/Application.cpp]: OK, done.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 1 above)
Comment (arnova) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:4988]: IMO it's fine if it happens somewhere else as long as it's NOT in the skin itself....

**Comment by lrusak** [comment]
jenkins build this please

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 1 above)
Comment (jjd-uk) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:4988]: I only know about doing flagging in the skin, I'm mostly clueless when comes to core C++ stuff. However the only reference I see to h262 is https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp#L1605 so is that where it comes from? if so could that be change to mpeg2???

Comment (the-black-eagle) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:4988]: Umm, the problem here is that no audio codec at all is returned without that check. I'll test to see if its possible to always use the hint value.  If so then the checks can be dropped.  Its not straightforward because there is no audio codec returned for a dvd stream without that check.

Comment (FernetMenta) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:4988]: that's all wrong here. Neither m_CurrentVideo/Audio nor m_pInputStream must be accessed from outside.

**Comment by FernetMenta** [comment]
The best approach to fix this is to purge out this IsBetterStream crap. Should be fairly easy for Bluray because it doesn't use the NAV source in selections streams anymore.

**Comment by the-black-eagle** [comment]
I've looked at the audio codec stuff in more detail and the reason it is missing is that `CDVDInputStreamNavigator` doesn't return any audio codec info to store in the selectionstream.  Current behaviour therefore is to not show any codec flags for dvd audio streams, just the number of channels. I'd prefer in that case to use the codecID from the hint to correctly show the flags.  This would require an additional audiocodec PCM flag adding to skins, named `pcm_dvd.png`. Other formats (DD etc) will already display correctly.
@jjd-uk is correct in that `CDVDInputStreamNavigator` could be altered to return `mpeg2` rather than `h262` which means no skin modifications would be necessary for the video codec.
Instead of the if statement, audio codec info can be obtained with 
`info.codecName = !s.codec.empty()? s.codec : avcodec_get_name(m_CurrentAudio.hint.codec);`  This keeps original behaviour as far as possible but returns `pcm_dvd` for lpcm dvd audio.
@arnova @enen92 Is that acceptable to you guys?  If so I'll go ahead and make the changes.

**Comment by arnova** [comment]
> I've looked at the audio codec stuff in more detail and the reason it is missing is that `CDVDInputStreamNavigator` doesn't return any audio codec info to store in the selectionstream. Current behaviour therefore is to not show any codec flags for dvd audio streams, just the number of channels. I'd prefer in that case to use the codecID from the hint to correctly show the flags. This would require an additional audiocodec PCM flag adding to skins, named `pcm_dvd.png`. Other formats (DD etc) will already display correctly.
> @jjd-uk is correct in that `CDVDInputStreamNavigator` could be altered to return `mpeg2` rather than `h262` which means no skin modifications would be necessary for the video codec.
> Instead of the if statement, audio codec info can be obtained with
> `info.codecName = !s.codec.empty()? s.codec : avcodec_get_name(m_CurrentAudio.hint.codec);` This keeps original behaviour as far as possible but returns `pcm_dvd` for lpcm dvd audio.
> @arnova @enen92 Is that acceptable to you guys? If so I'll go ahead and make the changes.

Sounds good to me. IMO mpeg2 as far more common/known than h262. I also don't understand the comment saying the absolute opposite about h262. Are we sure changing it doesn't cause any other problems?

File: xbmc/Application.cpp [hunk 3]
```diff
@@ -3173,7 +3173,8 @@ void CApplication::OnPlayBackStarted(const CFileItem &file)
   CLog::LogF(LOGDEBUG,"CApplication::OnPlayBackStarted");
 
   // check if VideoPlayer should set file item stream details from its current streams
-  if (file.GetProperty("get_stream_details_from_player").asBoolean())
+  if (file.GetProperty("get_stream_details_from_player").asBoolean() || file.IsDiscImage() ||
+      file.IsDVDFile() || file.IsBDFile() || file.IsBluray() || file.IsDVD() || file.IsOnDVD())
```
Comment (arnova) [inline xbmc/Application.cpp:3177]: Perhaps add: "|| !file.HasVideoInfoTag() || !file.GetVideoInfoTag()->HasStreamDetails() ?

Comment (ksooo) [reply xbmc/Application.cpp:3177]: OMG. Looks horrible.

Comment (arnova) [reply xbmc/Application.cpp:3177]: Well, perhaps the complete if statement can simply be replaced with "if (!file.HasVideoInfoTag() || !file.GetVideoInfoTag()->HasStreamDetails()) ?

File: xbmc/Application.cpp [hunk 4]
```diff
@@ -3173,7 +3173,15 @@ void CApplication::OnPlayBackStarted(const CFileItem &file)
...
-  if (file.GetProperty("get_stream_details_from_player").asBoolean())
+  if (file.GetProperty("get_stream_details_from_player").asBoolean()
+      || file.IsDiscImage()
+      || file.IsDVDFile()
+      || file.IsBDFile()
+      || file.IsBluray()
+      || file.IsDVD()
+      || file.IsOnDVD()
+      || !file.HasVideoInfoTag()
+      || !file.GetVideoInfoTag()->HasStreamDetails())
```
Comment (arnova) [inline xbmc/Application.cpp:3184]: After some more thought I *think* the 2 checks above need to go. This conflicts with the thumb/details extractor in the thumbloader. Now the details could be extracted here before the thumbloader does, which, as I recall, could give problems with eg. wrong AR (see #15934) . Not sure though if this is still the case.

Comment (the-black-eagle) [reply xbmc/Application.cpp:3184]: OK.  That still won't prevent overwriting details from nfo files associated with iso's or dvd/bluray directories though, as mentioned in that issue.

Comment (arnova) [reply xbmc/Application.cpp:3184]: Ok, than I think the safe approach would be (the other way around):
if (file.GetProperty("get_stream_details_from_player").asBoolean()
      || ((!file.HasVideoInfoTag() || !file.GetVideoInfoTag()->HasStreamDetails())
      && (file.IsDiscImage()
      ||  file.IsDVDFile()
      ||  file.IsBDFile()
      ||  file.IsBluray()
      ||  file.IsDVD()
      ||  file.IsOnDVD()))

Comment (the-black-eagle) [reply xbmc/Application.cpp]: @arnova LGTM.  If a user has gone to the trouble of adding the streamdetails to an nfo, we should not over-write that.  The only (small) issue I can foresee now is if a user happens to play the wrong audio track (eg 2 channel vs 5.1).  That will now stay set but can be worked around by removing and re-adding the iso and in any case it will probably only be a tiny minority that need to do that.

**Comment by arnova** [comment]
Thanks for updating it, lgtm now. Did you happen to check whether we get a proper ar for video and channel count for audio with this?

**Comment by the-black-eagle** [comment]
For DVD yes.  For bluray the AR is reported by the player while it's playing but is not in the streamdetails although everything else is.  Means it doesn't get stored in the db.  Don't yet know why that info is missing, there is a lot of code to try and understand.

**Comment by the-black-eagle** [comment]
Ha, aspect ratio wasn't being added to the selectionstream so it always defaulted to zero. Now corrected.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 5]
```diff
@@ -524,6 +525,7 @@ void CSelectionStreams::Update(const std::shared_ptr<CDVDInputStream>& input,
         CDemuxStreamVideo* vstream = static_cast<CDemuxStreamVideo*>(stream);
         s.width = vstream->iWidth;
         s.height = vstream->iHeight;
+        s.aspect_ratio = vstream->fAspect;
```
Comment (arnova) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:528]: I also once created a PR with the exact same fix but it was never merged because of comments by @FernetMenta . Please see https://github.com/xbmc/xbmc/pull/16239

Comment (the-black-eagle) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:528]: It already should be by the if statement in `CApplication.cpp`.  We're only updating stuff using vp that doesn't already have any details and even then, only if it's from DVD or Bluray. Everything else is updated by the background loader isn't it ? I've tested this by removing everything from the streamdetails table in the db then playing something not dvd related that the background loader hasn't got to yet and the details were not updated from vp.

Comment (arnova) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:528]: Ok, then I guess we should be ok.

**Comment by lrusak** [comment]
jenkins build this please

**Comment by the-black-eagle** [comment]
@arnova Is this OK to go in?  It has been tested by several forum members, none of which reported any issues.

**Comment by arnova** [comment]
LGTM :-)

**Comment by smp79** [comment]
This PR crashes Kodi when trying to play .ts files. 
https://paste.kodi.tv/ugekadazil.kodi

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 6]
```diff
@@ -4932,12 +4947,26 @@ void CVideoPlayer::UpdateContent()
...
+
   m_content.m_videoIndex = m_SelectionStreams.TypeIndexOf(STREAM_VIDEO, m_CurrentVideo.source,
                                                       m_CurrentVideo.demuxerId, m_CurrentVideo.id);
   m_content.m_audioIndex = m_SelectionStreams.TypeIndexOf(STREAM_AUDIO, m_CurrentAudio.source,
                                                       m_CurrentAudio.demuxerId, m_CurrentAudio.id);
   m_content.m_subtitleIndex = m_SelectionStreams.TypeIndexOf(STREAM_SUBTITLE, m_CurrentSubtitle.source,
                                                          m_CurrentSubtitle.demuxerId, m_CurrentSubtitle.id);
+
+  if (m_content.m_videoIndex == -1 && m_content.m_audioIndex == -1)
+  {
```
Comment (arnova) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:4959]: This is missing the condition "&& m_pInputStream->IsStreamType(DVDSTREAM_TYPE_DVD)". Probably causing the reported crash.

Comment (arnova) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:4959]: PR here https://github.com/xbmc/xbmc/pull/19645

**Comment by matthuisman** [comment]
@the-black-eagle

this PR makes it call IsBluray()
IsBluray() calls GetOpticalMediaPath()
which then tries to get the 6x files (VIDEO_TS.IFO, etc etc)
https://github.com/xbmc/xbmc/blob/master/xbmc/FileItem.cpp#L1865

Issue is, its calling this for internet streams causing 6x http requests

You can test by creating a file called test.strm with below url in it:
http://cdn.theoplayer.com/video/elephants-dream/playlist-single-audio.m3u8
then open via kodi file manager.

So maybe you just need to check not internet stream before IsBluray() ??
Could you also backport the fix to Matrix :)
