### PR TITLE
[Video][Directory] Allow get the custom named season with GetLocalizedName

### LINKED ISSUE #21735: Custom season name not appearing
### Describe the bug
Here is a clear and concise description of what the problem is:

if I edit a season title (for example the season 1 title of a tv show), in the episodes view it won't show the custom season title in the top left corner but "Season 1".

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The custom/edited season name should appear at the top left corner in the episodes view

## Actual Behavior

The default season name (which is Season [number]) is still displayed after editing of the season name

## Possible Fix

I don’t know 

### To Reproduce

1. Go to Tv Shows  
2. Choose a tv show to show the seasons listing
3. Edit the name of a season by clicking (long press) on enter on windows or « ok » on android tv to display the context menu and click on « edit title » to change the name.
4. Click on the season to display the episodes of the season and see at the top left corner, the edited season name  is not displayed  

### Debuglog

I can’t provide one at the time but everyone can reproduce the issue

### Screenshots 

Can’t provide screenshots

## Additional context or screenshots (if appropriate)
None

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Kodi Matrix 19.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Old PR #6041 has introduced the feature to rename a season with a custom title on Kodi video library
but if you try rename it and you browse the episodes you cannot display the custom title,
this add the missing piece of code

the other commit instead fix the empty dialog when you rename the season title (that should be pre-populated with the original title)

## Motivation and context

Fix #21735

## How has this been tested?

1) Add to kodi video library a tvshow with more seasons
2) open context menu on a Season -> select "Manage..." -> then change with a custom title
3) Browse the season, and look to the wrong title above the screen

## What is the effect on users?

Allow display the custom season title instead the default one

## Screenshots (if appropriate):
immagine

BEFORE:
immagine

AFTER:
immagine

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [x] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp [hunk 1]
```diff
@@ -1422,7 +1422,10 @@ bool CGUIDialogVideoInfo::UpdateVideoItemTitle(const std::shared_ptr<CFileItem>&
   else if (mediaType == MediaTypeSeason)
   {
     database.GetSeasonInfo(iDbId, detail);
-    title = detail.m_strSortTitle;
+    if (detail.m_strSortTitle.empty())
```
Comment (enen92) [inline xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1425]: ternary operator would make this more concise

File: xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeSeasons.cpp [hunk 2]
```diff
@@ -31,21 +31,33 @@ std::string CDirectoryNodeSeasons::GetLocalizedName() const
...
+    case -2:
+    {
+      CDirectoryNode* pParent = GetParent();
+      if (pParent)
+        return pParent->GetLocalizedName();
+      return "";
+    }
+    default:
+    {
+      std::string season;
```
Comment (enen92) [inline xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeSeasons.cpp:47]: maybe wrap this into a new private method to avoid spreading db code on common logic

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp]: done

File: xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeSeasons.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/filesystem/VideoDatabaseDirectory/DirectoryNodeSeasons.cpp]: changed not sure that is what you mean

**Review by enen92 — APPROVED** [review]

**Review by garbear — APPROVED** [review]
Fix looks correct
