### PR TITLE
VAAPI: fix 10-bit surface format for HEVC/VP9/AV1 via inputstream addons

### LINKED ISSUE #25383: Disney+ Addon not playing properly the stream when VAAPI is enabled
### Describe the bug
Here is a clear and concise description of what the problem is:

Disney+ Addon creator and Inputstream.Adaptive maintainers think that it can be Kodi core problem.

This was tested with Omega, when playing the content as Disney stream this is happening:

- for one of Disney movies, when playing with VAAPI enabled, it doesn't refresh video and Kodi log shows errors: `ffmpeg[0x1c3b8a30]: [hevc] hardware accelerator failed to decode picture`
- with VAAPI disabled everything works fine
- if that Disney stream will be downloaded as local mp4 file then Kodi plays it fine, with and without VAAPI enabled
- other movies plays well with or without VAAPI support enabled, this would imply this particular stream is somehow different?

Full log file is [here](https://x0.at/IkO2.txt).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
- play the mentioned contents with VAAPI enabled

## Actual Behavior
- Kodi doesn't play video, just some sound. The log file shows multiple errors: `ffmpeg[0x1c3b8a30]: [hevc] hardware accelerator failed to decode picture`.

### To Reproduce
1. Enable VAAPI support in the Player options
2. Use Disney+ Addon to play Movies/Documentary/'Machine Gun Kelly’s Life in Pink'

### Debuglog
The debuglog can be found here:
https://x0.at/IkO2.txt

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshot from the played stream:
nuc10-stream

Screenshot from the played file:
nuc10-file

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
<details>
<summary>See these stream details (click it)</summary>

```
General
Complete name                            : Machine Gun Kelly’s Life in Pink.mp4
Format                                   : MPEG-4
Format profile                           : Base Media
Codec ID                                 : isom (isom/dby1/iso2/mp41)
File size                                : 2.29 GiB
Duration                                 : 1 h 41 min
Overall bit rate mode                    : Variable
Overall bit rate                         : 3 219 kb/s
Frame rate                               : 23.976 FPS
Movie name                               : Machine Gun Kelly’s Life in Pink
Description                              : 'Machine Gun Kelly’s Life in Pink'
Recorded date                            : 2022
Writing application                      : Lavf60.3.100
Cover                                    : Yes

Video
ID                                       : 1
Format                                   : HEVC
Format/Info                              : High Efficiency Video Coding
Format profile                           : Main 10@L3.1@Main
Codec ID                                 : hvc1
Codec ID/Info                            : High Efficiency Video Coding
Duration                                 : 1 h 41 min
Bit rate                                 : 2 958 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Bits/(Pixel*Frame)                       : 0.134
Stream size                              : 2.10 GiB (92%)
Title                                    : BAMTech video
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
Codec configuration box                  : hvcC

Audio
ID                                       : 3
Format                                   : E-AC-3
Format/Info                              : Enhanced AC-3
Commercial name                          : Dolby Digital Plus
Codec ID                                 : ec-3
Duration                                 : 1 h 41 min
Bit rate mode                            : Constant
Bit rate                                 : 256 kb/s
Channel(s)                               : 6 channels
Channel layout                           : L R C LFE Ls Rs
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Stream size                              : 186 MiB (8%)
Title                                    : BAMTech audio / English
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Alternate group                          : 1
Dialog Normalization                     : -29 dB
compr                                    : -0.28 dB
mixlevel                                 : 105 dB
roomtyp                                  : Small
dialnorm_Average                         : -29 dB
dialnorm_Minimum                         : -29 dB
dialnorm_Maximum                         : -29 dB
```
</details>

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: `LibreELEC Linux x86 64-bit version 6.9.5`
 - Kodi version: `Kodi (21.0 (21.0.0) Git:21.0-Omega`

### PR DESCRIPTION
**Pull request by reardonia**
## Description

Fixes #25383 

VAAPI creates NV12 (8-bit) surfaces instead of P010 (10-bit) for HEVC Main10 content played via inputstream addons, because ffmpeg's HEVC, VP9, and AV1 decoders do not set `avctx->bits_per_raw_sample`. Derive bit depth from `avctx->pix_fmt` as a fallback.

NOTE: The current inputstream API does not allow setting bitDepth.  

NOTE: it would be nice it ffmpeg set `bits_per_raw_sample` for all codecs, but it only does so for H.264.  But this PR solves the problem today for the other major codecs that are supported by VAAPI.

## Motivation and context

Fixes #25383 -- HEVC 10-bit content (e.g. Disney+ via inputstream.adaptive) fails with `vaEndPicture error 18 (invalid parameter)` on every frame. File-based playback is unaffected because `CDVDDemuxFFmpeg` sets `bitDepth` independently.

## How has this been tested?

  - Disney+ HEVC Main10 720p via inputstream.adaptive on Intel Gen12 (iHD driver)
  - Verified P010 surfaces created instead of NV12
  - Verified playback succeeds with VAAPI where it previously failed on every frame
  - Software decode confirmed working before and after the change

## What is the effect on users?
fixes #25383

## Screenshots (if appropriate):
n/a

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by keithah** [comment]
@kodiai review

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp [hunk 1]
```diff
@@ -589,6 +590,16 @@ bool CDecoder::Open(AVCodecContext* avctx, AVCodecContext* mainctx, const enum A
   m_vaapiConfig.surfaceHeight = avctx->coded_height;
   m_vaapiConfig.aspect = avctx->sample_aspect_ratio;
   m_vaapiConfig.bitDepth = avctx->bits_per_raw_sample;
+  // ffmpeg's HEVC, VP9, and AV1 decoders do not set bits_per_raw_sample,
+  // but they do set pix_fmt correctly (e.g. yuv420p10le for 10-bit).
+  // Derive bit depth from the pixel format when bits_per_raw_sample is 0,
+  // otherwise ConfigVAAPI creates NV12 surfaces for 10-bit content.
+  if (m_vaapiConfig.bitDepth == 0)
+  {
+    const AVPixFmtDescriptor* desc = av_pix_fmt_desc_get(avctx->pix_fmt);
```
Comment (fritsch) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp:599]: maybe call get_bit_depth instead with the pix_fmt as parameter. That way you do not rely ofn the inner workings of desc->comp[0] and so on?

Via: https://www.ffmpeg.org/doxygen/3.2/vpcc_8c_source.html#l00092

Comment (reardonia) [reply xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp:599]: > maybe call get_bit_depth instead with the pix_fmt as parameter. That way you do not rely ofn the inner workings of desc->comp[0] and so on?
> 
> Via: https://www.ffmpeg.org/doxygen/3.2/vpcc_8c_source.html#l00092

@fritsch 
I couldn't find a public function for this... you'd think there would be one.  I can raise issue there (ffmpeg) but assume we want a Kodi-side fix asap.  I don't love using the struct directly but don't see any other option. Note that AVComponentDescriptor.depth is the publicly documented struct,; it's not opaque in the public API.

Comment (fritsch) [reply xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp:599]: Yes. In that case, you are right.

**Review by jernejsk — APPROVED** [review]
nice catch!

**Comment by reardonia** [comment]
@fritsch anything further for me to address here?

**Comment by fritsch** [comment]
All good all fine. Your button!

**Comment by fritsch** [comment]
Ah. Now I got it. You cannot press the button, even though all acked. Sorry.
