### PR TITLE
[Pictures] Fix exif parsing regression from v19

### LINKED ISSUE #22900: Pictures - Date of a picture is not using EXIF "DateTimeOriginal"
### Describe the bug
Here is a clear and concise description of what the problem is:

In Pictures when viewing the picture's Date it is not using EXIF's "DateTimeOriginal" .  It is using "ModifyDate".  
This is a change in behaviour from previous versions, 19.X at least, of Kodi.   
This means that the sort of pictures by "Date taken" is using "ModifyDate" as well.   

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When viewing pictures the "Date" of the picture should use EXIF's "DateTimeOriginal" as in previous versions of Kodi.  
Sorting by "Date Taken" should also use EXIF "DateTimeOriginal".   
Summary:  EXIF "DateTimeOriginal" should be used for "Date" in Kodi.

## Actual Behavior
The Date of a picture is EXIF "ModifyDate" and sorting by "Date taken" is also using "ModifyDate" instead of using "DateTimeOriginal".

## Possible Fix
As in previous 19.X, at least, version of Kodi used "DateTimeOriginal" for the "Date" being displayed in Kodi.  If this field is use for Date I suspect the sorting by "Date taken" in Kodi will also be corrected.

### To Reproduce

1. Go to Pictures.
2. Select one picture and look at the date information of a picture in a tool like ExifTool or ExifToolGui.
3. Note "ModifyDate" "DateTimeOriginal" "CreateDate"
4. Modify the "DateTimeOriginal" field.   
5. Notice this change in date isn't displayed in Kodi.
6. *Note the field "ModifyDate" is not the field you see in Windows Explorer "Date modified".

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I have made modifications  to "TimeDateCreated" to pictures in a folder that has pictures from multiple cameras.   The cameras, unfortunately, did not have their time's synchronized.   Now I can't sort by this field. 

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Windows 10 21H2/Kodi 20.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #23360: JSON API does not share EXIF data for pictures in slideshow (GetInfoLabels)
### Describe the bug
Here is a clear and concise description of what the problem is:

The JSON API of Kodi 21.0 ALPHA does not provide the expected response for picture EXIF data when requesting it via the following command:

```
{
    "jsonrpc": "2.0",
    "method": "XBMC.GetInfoLabels",
    "params": {"labels": ["Slideshow.Resolution",
                          "Slideshow.Process",
                          "Slideshow.Filename",
                          "Slideshow.CameraModel",
                          "Slideshow.CameraMake",
                          "Slideshow.EXIFTime",
                          "Slideshow.Aperture",
                          "Slideshow.ISOEquivalence",
                          "Slideshow.ExposureTime",
                          "Slideshow.Exposure",
                          "Slideshow.ExposureBias",
                          "Slideshow.MeteringMode",
                          "Slideshow.FocalLength"]
    },
    "id": 1
}
```

With 19.5 it works with the same image files.

Also, as per iOS Remote App use it does not work with Kodi 20.1, but with Kodi 17.6 (see https://forum.kodi.tv/showthread.php?tid=359717&pid=3155095#pid3155095).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The response provides results for all requested items, if present.

## Actual Behavior

The response has empty strings as results for most of the fields. Only for camera make, camera model, filename, resolution and time there is a proper response.

## Possible Fix

I cannot tell.

### To Reproduce

1.  Add images with EXIF data to playlist and start playing them.
2.  Send JSON command as described above.
3.  Review response.

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Linux Mint 21.1
 - Kodi version: 21.0 ALPHA

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This fixes EXIF parsing which has been broken since v19. This is a regression from: https://github.com/xbmc/xbmc/commit/f894813ad1dbc38be36388b8facbd6d6e1487bc2

Fixes https://github.com/xbmc/xbmc/issues/23360
Fixes https://github.com/xbmc/xbmc/issues/22900

## Motivation and context
The code will be nuked for v22 but lets have something actually working for v21.

## How has this been tested?
Runtime tested on macOS

## What is the effect on users?
Exif parsing should now be working.

## Screenshots (if appropriate):
**Prev:**
image

**Now:**
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by enen92** [comment]
Jenkins build this please

**Review by thexai — APPROVED** [review]
Seems logic 😊

File: xbmc/pictures/ExifParse.cpp [hunk 1]
```diff
@@ -105,19 +105,21 @@ static void ErrNonfatal(const char* const msg, int a1, int a2);
...
+constexpr auto FMT_SBYTE = 6;
+[[maybe_unused]] constexpr auto FMT_UNDEFINED = 7;
+constexpr auto FMT_SSHORT = 8;
+constexpr auto FMT_SLONG = 9;
+constexpr auto FMT_SRATIONAL = 10;
+constexpr auto FMT_SINGLE = 11;
+constexpr auto FMT_DOUBLE = 12;
 // NOTE: Remember to change NUM_FORMATS if you define a new format
-constexpr auto NUM_FORMATS = 10;
+constexpr auto NUM_FORMATS = 12;
```
Comment (lrusak) [inline xbmc/pictures/ExifParse.cpp:120]: Does this go away eventually? An enum seems better here otherwise.

Comment (enen92) [reply xbmc/pictures/ExifParse.cpp:120]: Yes, it will be removed in v22 altogether (waiting for a new exiv2 tag). So I really don't want to waste much time with this.
