### PR TITLE
Adjust punctuation in RTL Subtitles

### LINKED ISSUE #18648: Reversed punctuation in RTL subtitles in Kodi 19
### Describe the bug
Here is a clear and concise description of what the problem is:

Punctuation is reversed when using Hebrew subtitles in Kodi 19. This is a common issue with RTL (right to left) languages but it used to work properly in Kodi 18.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Punctuation should be placed at the end of the sentence, see attached screenshot for reference.

## Actual Behavior

Punctuation is placed in the beginning of the sentence.

### To Reproduce

1. Change language in Player settings to Hebrew, character set to Hebrew (Windows).
2. Place attached subtitle file "Hebrew_subs.srt" in same dir of a video named accordingly (e.g. "Hebrew_subs.mp4").
3. Play the video in Kodi

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/aqunebojuw.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Reference screenshot:

screenshot

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Sample subtitle file:

[Hebrew_subs.zip](https://github.com/xbmc/xbmc/files/5440000/Hebrew_subs.zip)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64, Android
 - Kodi version: Kodi 19.0 "Matrix" - Release

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by AhmedAdelAbouzeid**
## Description
Use "forceLTRReadingOrder" in call to "utf32logicalToVisualBiDi" inside "BidiFlip" function
Fixes #18648

## Motivation and Context
This modification fixes the misplaced punctuation marks in RTL subtitles.

## How Has This Been Tested?
This change was tested on windows 10 (64-bit) with Kodi 19.0 (compiled from master)

## Screenshots (if appropriate):
See issue #18648

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by enen92 — APPROVED** [review]
This seems correct to me as it restores the same behaviour that was previously in https://github.com/xbmc/xbmc/pull/17790 and also due to https://github.com/xbmc/xbmc/issues/18648#issuecomment-795111365

Someone else should look into it too. I'm requesting @phunkyfish and @AlwinEsch as both were on the previous PR.

Thanks much for the fix

File: xbmc/guilib/GUITextLayout.cpp [hunk 1]
```diff
@@ -315,7 +315,8 @@ std::wstring CGUITextLayout::BidiFlip(const std::wstring& text,
 
   // Convert to utf32, call bidi then convert the result back to utf16
   g_charsetConverter.wToUtf32(text, utf32logical);
-  g_charsetConverter.utf32logicalToVisualBiDi(utf32logical, utf32visual, false, false,
+  g_charsetConverter.utf32logicalToVisualBiDi(utf32logical, utf32visual, forceLTRReadingOrder,
+                                              false,
```
Comment (AlwinEsch) [inline xbmc/guilib/GUITextLayout.cpp:319]: I'm not really a specialist of this part, but seems makes sense, the `forceLTRReadingOrder` was unused before and on the `utf32logicalToVisualBiDi` call is this the third value.

So with this change the needed value becomes given to needed place :+1:

**Review by phunkyfish — APPROVED** [review]
Makes sense.

**Comment by enen92** [comment]
@AhmedAdelAbouzeid thanks for the fix. Do you mind issuing a backport PR against the Matrix branch?

**Comment by AhmedAdelAbouzeid** [comment]
Happy to help!
Please check PR #19391 against Matrix branch.
