### PR TITLE
fixed: Instead of determining if something is remote, we should determine if it's a network filesystem (should fix AirPlay issue #19795)

### LINKED ISSUE #19795: AirPlay broken with CACHE_BUFFER_MODE_REMOTE
### Describe the bug

AirPlay no longer works on 19.1.  It worked on 19.0.

## Expected Behavior

- Apple Music (on a Mac) can stream audio through Kodi
- Kodi produces sound and visually indicates that it is playing

## Actual Behavior

No audio or visual feedback from Kodi.  Apple Music indicates that it is playing.

### To Reproduce

<-- Put your text below this line -->
0. Install Kodi 19.1 and verify that audio work by playing some local music
1. Enable Airplay in Kodi preferences
2. Select Kodi as the audio destination in Apple Music
3. Play music and enjoy the silence
4. Downgrade to 19.0 and enjoy the music

### Debuglog

The debuglog can be found here:

Log from Kodi 19.1
```
021-05-24 10:03:34.398 T:17467    INFO <general>: AIRTUNES: Accepted IPv4 client on socket 15
2021-05-24 10:03:34.399 T:17467    INFO <general>: AIRTUNES: Local: 192.168.1.171
2021-05-24 10:03:34.399 T:17467    INFO <general>: AIRTUNES: Remote: 192.168.1.153
2021-05-24 10:03:34.445 T:17467    INFO <general>: AIRTUNES: Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002
2021-05-24 10:03:34.446 T:17467    INFO <general>: AIRTUNES: Responding with RTP/AVP/UDP;unicast;mode=record;timing_port=50126;events;control_port=44827;server_port=55350
2021-05-24 10:03:34.456 T:17467    INFO <general>: AIRTUNES: Got metadata of 1290 bytes
2021-05-24 10:03:34.463 T:17467    INFO <general>: AIRTUNES: Got image data of 260469 bytes
2021-05-24 10:03:34.574 T:17497   ERROR <general>: Init: Error creating demuxer
2021-05-24 10:03:34.575 T:17497   ERROR <general>: CAudioDecoder: Unable to Init Codec while loading file pipe://1/
2021-05-24 10:03:34.575 T:17497 WARNING <general>: PAPlayer::QueueNextFileEx - Failed to create the decoder
2021-05-24 10:03:34.582 T:17497   ERROR <general>: InputStream: Error opening, /home/jim/Videos/Penguins_of_Madagascar.m4v
2021-05-24 10:03:34.583 T:17497   ERROR <general>: InputStream: Error opening, /home/jim/Videos/Monster_High_Boo_York_Boo_York.m4v
2021-05-24 10:03:34.722 T:17496    INFO <general>: Skipped 1 duplicate messages..
2021-05-24 10:03:34.722 T:17496   ERROR <general>: InputStream: Error opening, /home/jim/Videos/Penguins_of_Madagascar.m4v
2021-05-24 10:03:34.836 T:17500   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/4/4a7c31a0.jpg
2021-05-24 10:03:34.836 T:17496   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/4/46e34668.jpg
2021-05-24 10:03:34.836 T:17497   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/0026be5b.jpg
2021-05-24 10:03:34.837 T:17501   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/0bcb57f1.jpg
2021-05-24 10:03:34.837 T:17501   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/2/26b34079.jpg
2021-05-24 10:03:34.837 T:17501   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/5/506a8b3b.jpg
2021-05-24 10:03:34.838 T:17501   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/1/1bcc5060.jpg
2021-05-24 10:03:47.521 T:17467    INFO <general>: AIRTUNES: Flush with RTP-Info: seq=3019;rtptime=1313862431
2021-05-24 10:03:59.043 T:17493    INFO <general>: AIRTUNES: Exiting UDP RAOP thread
2021-05-24 10:04:01.689 T:17467    INFO <general>: AIRTUNES: Connection closed for socket 15
```

Log from Kodi 19.0
```
2021-05-24 09:57:20.203 T:14494    INFO <general>: AIRTUNES: Accepted IPv4 client on socket 30
2021-05-24 09:57:20.203 T:14494    INFO <general>: AIRTUNES: Local: 192.168.1.171
2021-05-24 09:57:20.203 T:14494    INFO <general>: AIRTUNES: Remote: 192.168.1.153
2021-05-24 09:57:20.252 T:14494    INFO <general>: AIRTUNES: Transport: RTP/AVP/UDP;unicast;interleaved=0-1;mode=record;control_port=6001;timing_port=6002
2021-05-24 09:57:20.252 T:14494    INFO <general>: AIRTUNES: Responding with RTP/AVP/UDP;unicast;mode=record;timing_port=42793;events;control_port=33673;server_port=38791
2021-05-24 09:57:20.262 T:14494    INFO <general>: AIRTUNES: Got metadata of 1290 bytes
2021-05-24 09:57:20.267 T:14494    INFO <general>: AIRTUNES: Got image data of 260469 bytes
2021-05-24 09:57:20.330 T:14520    INFO <general>: CDVDAudioCodecFFmpeg::Open() Successful opened audio decoder pcm_s16le
2021-05-24 09:57:20.330 T:14520    INFO <general>: CDVDAudioCodecFFmpeg::GetChannelMap - FFmpeg reported 2 channels, but the layout contains 0 ignoring
2021-05-24 09:57:20.530 T:14523   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/4/4a7c31a0.jpg
2021-05-24 09:57:20.531 T:14519   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/4/46e34668.jpg
2021-05-24 09:57:20.547 T:14522   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/0026be5b.jpg
2021-05-24 09:57:20.581 T:14523   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/0bcb57f1.jpg
2021-05-24 09:57:20.582 T:14519   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/2/26b34079.jpg
2021-05-24 09:57:20.582 T:14523   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/5/506a8b3b.jpg
2021-05-24 09:57:20.582 T:14519   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/1/1bcc5060.jpg
2021-05-24 09:57:20.582 T:14523   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/7/7d129cb3.jpg
2021-05-24 09:57:20.583 T:14523   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/f/fcf99199.jpg
2021-05-24 09:57:20.583 T:14523   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/3/38986531.jpg
2021-05-24 09:57:22.051 T:14520    INFO <general>: AudioDecoder: File is queued
2021-05-24 09:57:22.108 T:14520    INFO <general>: PAPlayer::PrepareStream - Ready
2021-05-24 09:57:22.459 T:14412    INFO <general>: Loading skin file: MusicVisualisation.xml, load type: KEEP_IN_MEMORY
2021-05-24 09:57:39.167 T:14494    INFO <general>: AIRTUNES: Flush with RTP-Info: seq=23764;rtptime=1207690070
2021-05-24 09:57:50.689 T:14516    INFO <general>: AIRTUNES: Exiting UDP RAOP thread
2021-05-24 09:57:50.810 T:14526   ERROR <general>: CUPnPDirectory::GetResource - unable to find object folder.jpg
2021-05-24 09:57:50.991 T:14520   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/4/4a7c31a0.jpg
2021-05-24 09:57:50.991 T:14527   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/4/46e34668.jpg
2021-05-24 09:57:50.992 T:14529   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/0026be5b.jpg
2021-05-24 09:57:50.994 T:14526   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/0/0bcb57f1.jpg
2021-05-24 09:57:50.994 T:14526   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/2/26b34079.jpg
2021-05-24 09:57:50.995 T:14526   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/5/506a8b3b.jpg
2021-05-24 09:57:50.995 T:14526   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/3/38986531.jpg
2021-05-24 09:57:50.995 T:14526   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/7/7d129cb3.jpg
2021-05-24 09:57:50.995 T:14526   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/e/e7d19ce1.jpg
2021-05-24 09:57:50.996 T:14526   ERROR <general>: DoWork - Direct texture file loading failed for special://masterprofile/Thumbnails/1/1bcc5060.jpg
2021-05-24 09:57:53.300 T:14494    INFO <general>: AIRTUNES: Connection closed for socket 30
```

## Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Others seem to have the same problem:
`https://forum.kodi.tv/showthread.php?tid=362685`
`https://archlinuxarm.org/forum/viewtopic.php?t=15349&p=66614`

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 34
 - Kodi version: 19.1 kodi-19.1-1.fc34.x86_64 from RPM Fusion
   + works with kodi-19.0-3.fc34.x86_64, same settings

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by arnova**

### CODE REVIEW

**Comment by arnova** [comment]
Backport will be provided once proven this fixes the AirPlay issue.

File: xbmc/filesystem/File.cpp [hunk 1]
```diff
@@ -293,23 +293,26 @@ bool CFile::Open(const CURL& file, const unsigned int flags)
              URIUtils::IsInternetStream(pathToUrl, true)) ||
             (iCacheBufferMode == CACHE_BUFFER_MODE_TRUE_INTERNET &&
              URIUtils::IsInternetStream(pathToUrl, false)) ||
-            (iCacheBufferMode == CACHE_BUFFER_MODE_REMOTE && URIUtils::IsRemote(pathToUrl)) ||
-            (iCacheBufferMode == CACHE_BUFFER_MODE_ALL))
+            (iCacheBufferMode == CACHE_BUFFER_MODE_REMOTE &&
```
Comment (wsnipex) [inline xbmc/filesystem/File.cpp:296]: shouldn't this be CACHE_BUFFER_MODE_NETWORK?

Comment (arnova) [reply xbmc/filesystem/File.cpp]: Yup, thanks for the headsup. Fixed :)

**Comment by arnova** [comment]
jenkins build this please

File: xbmc/filesystem/File.cpp [hunk 2]
```diff
@@ -293,23 +293,26 @@ bool CFile::Open(const CURL& file, const unsigned int flags)
              URIUtils::IsInternetStream(pathToUrl, true)) ||
             (iCacheBufferMode == CACHE_BUFFER_MODE_TRUE_INTERNET &&
              URIUtils::IsInternetStream(pathToUrl, false)) ||
-            (iCacheBufferMode == CACHE_BUFFER_MODE_REMOTE && URIUtils::IsRemote(pathToUrl)) ||
-            (iCacheBufferMode == CACHE_BUFFER_MODE_ALL))
+            (iCacheBufferMode == CACHE_BUFFER_MODE_NETWORK &&
+             URIUtils::IsNetWorkFilesystem(pathToUrl)) ||
```
Comment (wsnipex) [inline xbmc/filesystem/File.cpp:297]:
```suggestion
             URIUtils::IsNetworkFilesystem(pathToUrl)) ||
```

File: xbmc/filesystem/File.cpp [hunk 3]
```diff
@@ -293,23 +293,26 @@ bool CFile::Open(const CURL& file, const unsigned int flags)
...
+            (iCacheBufferMode == CACHE_BUFFER_MODE_ALL &&
+             (URIUtils::IsNetWorkFilesystem(pathToUrl) || URIUtils::IsHD(pathToUrl))))
```
Comment (wsnipex) [inline xbmc/filesystem/File.cpp:299]:
```suggestion
             (URIUtils::IsNetworkFilesystem(pathToUrl) || URIUtils::IsHD(pathToUrl))))
```

**Review by wsnipex — COMMENTED** [review]
suggestions should fix the build issue

File: xbmc/filesystem/File.cpp (hunk 2 above)
Comment (arnova) [reply xbmc/filesystem/File.cpp]: Thanks again: Fixed. Forgot to compile test that on my end....

**Comment by wsnipex** [comment]
jenkins build this please

**Comment by wsnipex** [comment]
closing and reopening to check jenkins to update git

**Comment by wsnipex** [comment]
win64 error is unrelated

**Review by wsnipex — APPROVED** [review]

**Comment by arnova** [comment]
Thanks @wsnipex for review.

**Comment by lrusak** [comment]
jenkins build this please

**Comment by arnova** [comment]
@wsnipex: You ok with this as is? IMO the formatting changes are silly.

**Comment by ksooo** [comment]
> IMO the formatting changes are silly.

The formatting changes are what we as a team agreed to use.

**Comment by wsnipex** [comment]
No hard feeling about the formatting, but
I'd simply apply them and be done with it.

**Comment by enen92** [comment]
Can the commits be squashed for merging? It's important to get this in as a backport for 19.2

**Comment by arnova** [comment]
> Can the commits be squashed for merging? It's important to get this in as a backport for 19.2

Yes, will do as soon as it's finished. I'm still tweaking it a bit. Will be ready in a few days.

File: xbmc/FileItem.cpp [hunk 4]
```diff
@@ -1044,6 +1044,14 @@ bool CFileItem::IsInternetStream(const bool bStrictCheck /* = false */) const
   return URIUtils::IsInternetStream(m_strPath, bStrictCheck);
 }
 
+bool CFileItem::IsStreamedFileSystem() const
+{
+  if (!m_strDynPath.empty())
+    return URIUtils::IsStreamedFilesystem(m_strDynPath);
+
+  return URIUtils::IsStreamedFilesystem(m_strPath);
```
Comment (ksooo) [inline xbmc/FileItem.cpp:1052]: CFileItem::GetDynPath imo checks whether m_strDynPath is empty and in case it returns m_strPath. So, this could be simplified to read `return URIUtils::IsStreamedFileSystem(GetDynPath());`

File: xbmc/utils/URIUtils.cpp [hunk 5]
```diff
@@ -924,7 +924,7 @@ bool URIUtils::IsFTP(const std::string& strFile)
          IsProtocol(strFile, "ftps");
 }
 
-bool URIUtils::IsHTTP(const std::string& strFile)
+bool URIUtils::IsHTTP(const std::string& strFile, const bool& bTranslate /* = false */)
```
Comment (ksooo) [inline xbmc/utils/URIUtils.cpp:927]: It does not make much sense to specify simple types as **const** ref param. Just use `bool`by val here.

File: xbmc/utils/URIUtils.cpp [hunk 6]
```diff
@@ -936,8 +936,10 @@ bool URIUtils::IsHTTP(const std::string& strFile)
   if (HasParentInHostname(url))
     return IsHTTP(url.GetHostName());
 
-  return IsProtocol(strFile, "http") ||
-         IsProtocol(strFile, "https");
+  std::string strProtocol = (bTranslate ? url.GetTranslatedProtocol() : url.GetProtocol());
```
Comment (ksooo) [inline xbmc/utils/URIUtils.cpp:939]: const std::string

File: xbmc/utils/URIUtils.h [hunk 7]
```diff
@@ -124,14 +124,16 @@ class URIUtils
   static bool IsDOSPath(const std::string &path);
   static bool IsDVD(const std::string& strFile);
   static bool IsFTP(const std::string& strFile);
-  static bool IsHTTP(const std::string& strFile);
+  static bool IsHTTP(const std::string& strFile, bTranslate = false);
```
Comment (ksooo) [inline xbmc/utils/URIUtils.h:127]: Type of the param is missing! And please see my other comment. Use `bool`, not `const bool&`

**Review by ksooo — CHANGES_REQUESTED** [review]

File: xbmc/utils/URIUtils.cpp [hunk 8]
```diff
@@ -936,8 +936,10 @@ bool URIUtils::IsHTTP(const std::string& strFile)
...
+
+  return (strProtocol == "http" ||
+         strProtocol ==  "https";
```
Comment (thexai) [inline xbmc/utils/URIUtils.cpp:942]:
```suggestion
         strProtocol ==  "https");
```
missing close previously opened parentheses 😃

Comment (ksooo) [reply xbmc/utils/URIUtils.cpp:942]: Well, seeing code suggested for merge that does not even compile makes me a bit worried about how this got tested.

Comment (arnova) [reply xbmc/utils/URIUtils.cpp:942]: Well I said I wasn't ready yet, that's why ;-) Obviously I will test it once again, when done.

File: xbmc/FileItem.cpp (hunk 4 above)
Comment (arnova) [reply xbmc/FileItem.cpp:1052]: Yes, but all the other methods around it use the way I cp-ed so I'd rather keep it all the same....

Comment (ksooo) [reply xbmc/FileItem.cpp:1052]: > I'd rather keep it all the same....

No hard feelings, but why? Not saying you should fix all the other methods, though.

File: xbmc/utils/URIUtils.cpp (hunk 8 above)
Comment (ksooo) [reply xbmc/utils/URIUtils.cpp]: > Well I said I wasn't ready yet, that's why ;-)

In this case, please add the [WIP] label to this PR. So, nobody will waiste time with reviewing in-progress stuff.

File: xbmc/FileItem.cpp (hunk 4 above)
Comment (arnova) [reply xbmc/FileItem.cpp:1052]: I like consistency (and less chance of fallout/regression in the future) ;-) But no problem changing it anyway.

File: xbmc/utils/URIUtils.cpp (hunk 8 above)
Comment (arnova) [reply xbmc/utils/URIUtils.cpp]: Yes, obviously this wasn't my initial intention. This started as a simple fix and later on I decided to cleanup/refactor some related stuff....

Please note I just committed  the final changes so it's ready for its last review.

File: xbmc/utils/URIUtils.cpp [hunk 9]
```diff
@@ -1019,12 +1020,9 @@ bool URIUtils::IsInternetStream(const CURL& url, bool bStrictCheck /* = false */
...
 
-  // Special case these
-  //! @todo sftp special case has to be handled by vfs addon
-  if (url.IsProtocol("ftp") || url.IsProtocol("ftps")  ||
-      url.IsProtocol("dav") || url.IsProtocol("davs")  ||
-      url.IsProtocol("sftp"))
-    return bStrictCheck;
+  // Only consider "streamed" filesystems internet streams when being strict
+  if (bStrictCheck && IsStreamedFileSystem(url.Get())
+    return true;
```
Comment (wsnipex) [inline xbmc/utils/URIUtils.cpp:1025]: shouldn't this be:
```suggestion
    if (bStrictCheck)
      return IsStreamedFileSystem(url.Get());
```
?

Comment (arnova) [reply xbmc/utils/URIUtils.cpp:1025]: No, because in that case if you would pass something with http:// it would return false

Comment (wsnipex) [reply xbmc/utils/URIUtils.cpp:1025]: In that case I don't understand what strictCheck is for

Comment (arnova) [reply xbmc/utils/URIUtils.cpp:1025]: strictCheck means: "Do we consider quasi filesystems like webdav, ftp, sftp and ftps also streams?". Normally we don't.

**Comment by arnova** [comment]
jenkins build this please

**Comment by arnova** [comment]
> Can the commits be squashed for merging? It's important to get this in as a backport for 19.2

I think I'll leave it as is. For backport only the first commit should be cherry-picked...

File: xbmc/utils/URIUtils.cpp (hunk 9 above)
Comment (wsnipex) [reply xbmc/utils/URIUtils.cpp:1025]: Ok, thanks.
The new code will always return true for http, on purpose or did you want to test for Dav in IsStreamedFilesystem?

Comment (arnova) [reply xbmc/utils/URIUtils.cpp:1025]: The old code also always returns true for http. This is also one of the reasons I refactored it a bit: to make it (hopefully) more obvious what the idea is...

**Review by wsnipex — APPROVED** [review]

**Review by ksooo — APPROVED** [review]

**Comment by arnova** [comment]
build error unrelated
