### PR TITLE
[macos-nativeWindow] main thread exit waits for xbmc thread [ resolves #22788 ]

### LINKED ISSUE #22788: Kodi macOS native window build crashes on system quit
### Kodi macOS native window build crashes on macOS system quit message
**Note**: this bug applies to a macOS build of Kodi configured with `--with-windowsystem=native` and cmake with `APP_WINDOW_SYSTEM=native`.  Builds with this configuration are not publicly released, as far as I know.

Kodi always crashes when receiving macOS quit messages from e.g.:
-  logout or shutdown
- the dock menu Quit
- the app menubar Quit
- applescripts and shortcuts

Choosing Exit from Kodi's UI menu will not cause a crash.
## Expected Behavior
Closing the Kodi app by any means available on the Mac should exit without crashes.
## Actual Behavior
Closing the Kodi app in any manner described above will crash in random code locations, but always somewhere in the XBMC main loop thread, which is a separate thread from the application main loop.
## Suggested Fix
When the Kodi application main thread receives `applicationShouldTerminate:`, it should first signal the XBMC main loop thread (via a `XBMC_QUIT` message or similar) and then wait for it to exit before continuing the exit on the main thread.

[Pull request is here](https://github.com/xbmc/xbmc/pull/22789).
 
### To Reproduce
1. Build Kodi with configuration `--with-windowsystem=native` and cmake with `APP_WINDOW_SYSTEM=native`
2. Launch Kodi
3. If the display is in full-screen, enter 1 or more CMD-TABs to bring the Finder front.
4. Right-click on the Kodi dock icon and choose Quit from the dock menu.

### Debuglog
The debuglog is not relevant, but the crash log shows the main thread (thread 0) calling `exit()`, while the XBMC main loop thread (thread 1) has crashed:
https://paste.kodi.tv/ayafureqem.kodi

### Screenshots 
KodiCrashedDialog

## Additional context
When the main thread calls `exit()`, destructors of statically-defined c++ objects are called.  With the XBMC main loop thread still running, methods which access these static objects (e.g. `CGUIFontTTF` via `MathUtils` or `FreeType`, for example) will crash.

### Your Environment
Used Operating system:
 - [x] macOS

Operating system version/name:
- Kodi version: 21.0.alpha1 (20230215-71c28c78e7)

### PR DESCRIPTION
**Pull request by stevehartwell**
## Description
**Note**: the issue that this PR applies to is for a macOS build of Kodi configured with `--with-windowsystem=native` and cmake with `APP_WINDOW_SYSTEM=native`. Builds with this configuration are not publicly released, as far as I know.

Implement the `NSApplicationDelegate` to wait for the XBMC main loop thread to exit, after which it is safe to call destructors to global static objects.

- `-[NSApplicationDelegate applicationWillFinishLaunching:]`
   - create XBMC main thread
   - create thread exit observer
   - start XBMC main thread
- `-[NSApplicationDelegate applicationShouldTerminate:]`
   - if `GetAppPort()` is `nullptr`, tell `NSApplication` to exit immediately
   - else post `XBMC_QUIT` and tell `NSApplication` to enter a modal runLoop
- on thread exit observer block:
   - tell `NSApplication` to exit modal runLoop
   - proceed with `-[NSApplication terminate:]`
- use blocks (closures) instead of method selectors
- call `NSApplicationMain()` as prescribed by Apple for all objective-C applications.
- remove dead code, unused includes
- add `const`s as required by `NSApplicationMain()`

## Motivation and context

This resolves https://github.com/xbmc/xbmc/issues/22788

## How has this been tested?

foreach method in [quit via dock menu, quit via menubar Quit, logout, shutdown]
1. launch Kodi in debugger
2. quit via {method}

Note: Jenkins builds Kodi.app with the `APP_WINDOW_SYSTEM=sdl` configuration, which does not have this issue.

## What is the effect on users?
Avoids crashes on application exit via system shutdown, logout, dock menu, menubar menu, applescripts, and shortcuts.

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/platform/darwin/osx/XBMCApplication.mm [hunk 1]
```diff
@@ -268,7 +231,7 @@ - (BOOL)application:(NSApplication*)theApplication openFile:(NSString*)filename
   if (arg == nullptr)
     return FALSE;
 
-  newargv = (char**)realloc(gArgv, sizeof(char*) * (gArgc + 2));
+  newargv = (const char**)realloc(gArgv, sizeof(char*) * (gArgc + 2));
```
Comment (enen92) [inline xbmc/platform/darwin/osx/XBMCApplication.mm:234]: Possible to avoid c style casts and use c++ casts instead? Seems to be possible according to other objective c files we have

File: xbmc/platform/darwin/osx/XBMCApplication.mm [hunk 2]
```diff
@@ -346,42 +301,40 @@ - (NSMenu*)applicationDockMenu:(NSApplication*)sender
 
 @end
 
-int main(int argc, char* argv[])
+int main(int argc, const char* argv[])
 {
+#if defined(DEBUG) && 0 // SHH enable as needed
```
Comment (enen92) [inline xbmc/platform/darwin/osx/XBMCApplication.mm:306]: Any reason for disabling by default? Seems to be enabled on the old code if debug is set

File: xbmc/platform/darwin/osx/XBMCApplication.mm [hunk 3]
```diff
@@ -346,42 +301,40 @@ - (NSMenu*)applicationDockMenu:(NSApplication*)sender
...
+#endif
+
   @autoreleasepool
   {
     /* Copy the arguments into a global variable */
     /* This is passed if we are launched by double-clicking */
     if (argc >= 2 && strncmp(argv[1], "-psn", 4) == 0)
     {
-      gArgv = (char**)malloc(sizeof(char*) * 2);
+      gArgv = (const char**)malloc(sizeof(char*) * 2);
```
Comment (enen92) [inline xbmc/platform/darwin/osx/XBMCApplication.mm:319]: C style cast, usually we use these opportunities to change them (if possible)

File: xbmc/platform/darwin/osx/XBMCApplication.mm [hunk 4]
```diff
@@ -346,42 +301,40 @@ - (NSMenu*)applicationDockMenu:(NSApplication*)sender
...
       gArgv[0] = argv[0];
       gArgv[1] = nullptr;
       gArgc = 1;
     }
     else
     {
       gArgc = argc;
-      gArgv = (char**)malloc(sizeof(char*) * (argc + 1));
+      gArgv = (const char**)malloc(sizeof(char*) * (argc + 1));
```
Comment (enen92) [inline xbmc/platform/darwin/osx/XBMCApplication.mm:327]: Same

**Review by enen92 — COMMENTED** [review]
Thanks for the contribution and for fixing the issue (I've never noticed myself and been using macos+nativewindowing for a while). Hopefully it gets closer and closer for prime time and eventually lead to sdl removal.

Left a few comments but preferably someone more familiar with objective c should review.

**Comment by stevehartwell** [comment]
Thanks for your review!  I'm agreeable to making all of the changes you suggest.

As you know, I'm still learning about what matters to Kodi reviewers, so I've asked some questions about your review points.  Please reply when convenient.

Second question, should I apply these changes to a separate commit, or amend this commit to include them?
Either is fine with me.

File: xbmc/platform/darwin/osx/XBMCApplication.mm [hunk 5]
```diff
@@ -204,13 +139,41 @@ - (void)applicationDidFinishLaunching:(NSNotification*)note
 
   //window.acceptsMouseMovedEvents = TRUE;
   [NSApp activateIgnoringOtherApps:YES];
-  // kick our mainloop into an extra thread
-  [NSThread detachNewThreadSelector:@selector(mainLoopThread:) toTarget:self withObject:nil];
+
+  // kick our mainloop into a separate thread
+  //
```
[the remark this answers is not in the document]
Comment (stevehartwell) [reply xbmc/platform/darwin/osx/XBMCApplication.mm:144]: Ok.  As far as I can tell the code guidelines don't address this.
I use the blank line to make the comment above it to read like a paragraph title on a group of statements, rather than a comment applying only to the immediately following statement.
I suppose I can just put a blank line there without the comment marker.
Would that work, or can you suggest a better way to do this?

File: xbmc/platform/darwin/osx/XBMCApplication.mm (hunk 1 above)
Comment (stevehartwell) [reply xbmc/platform/darwin/osx/XBMCApplication.mm:234]: I agree that blind casts (c-style) should be avoided, but I was only addressing the const virality and didn't want to add distracting changes.

I have another topic branch which replaces this code with _NSGetArgv() so I'd be inclined not to make extra changes here.

File: xbmc/platform/darwin/osx/XBMCApplication.mm (hunk 2 above)
Comment (stevehartwell) [reply xbmc/platform/darwin/osx/XBMCApplication.mm:306]: I don't think every debug build should enable this.  Do you know what it's for?

File: xbmc/platform/darwin/osx/XBMCApplication.mm (hunk 3 above)
Comment (stevehartwell) [reply xbmc/platform/darwin/osx/XBMCApplication.mm:319]: well, all right then :-)

File: xbmc/platform/darwin/osx/XBMCApplication.mm (hunk 5 above)
[the remark this answers is not in the document]
Comment (enen92) [reply xbmc/platform/darwin/osx/XBMCApplication.mm:144]: Yeah a single empty line is fine imho. Personally I feel keeping the comment mark looks like a leftover

File: xbmc/platform/darwin/osx/XBMCApplication.mm (hunk 1 above)
Comment (enen92) [reply xbmc/platform/darwin/osx/XBMCApplication.mm:234]: Well it's not mandatory, just a suggestion. We usually take those opportunities to partially modernize the codebase (rename stuff according to code guidelines, update casts, remove NULL in favor of nullptr, etc). But it's perfectly fine if you don't want to bother with that stuff.

File: xbmc/platform/darwin/osx/XBMCApplication.mm (hunk 2 above)
Comment (enen92) [reply xbmc/platform/darwin/osx/XBMCApplication.mm:306]: No idea, but having different behaviour for release/debug is not great.

This seems to have been done by @Memphiz in https://github.com/xbmc/xbmc/commit/d6e57d210fbaa71243b0a375b71def6b0ccd45fe. Not sure if he's still around.

**Comment by enen92** [comment]
Since they are minor requests I'd probably wait for kambala's review before changing stuff. Usually it's better (and is requested) to squash those changes into the actual commits to keep the history clean when merged

**Review by kambala-decapitator — APPROVED** [review]
Looks good, thanks!

Just please change c-style casts to static cast (running clang-format should do it automatically I believe)

**Comment by enen92** [comment]
@stevehartwell `git clang-format HEAD~1` will fix clang for you automatically. You can then commit the changes and squash on top of your old commit

**Comment by enen92** [comment]
@stevehartwell after this change it looks like xcode doesn't launch a detachable application/executable. The window is left below xcode and doesn't show neither in the dock or the list of running applications (cmd+shift):

image

It gets listed as a process on activity monitor though

**Comment by stevehartwell** [comment]
Yes, the solution is to build the 'bundle' target in Xcode and first time set the executable in the scheme to where the built "Kodi.app" is.  Then 'Run without building' to save time.
Untitled

This used to work before because the previous code set some flag which conflicts with running NSApplicationMain(). Mac UI apps are designed to run inside an .app bundle, with Info.plist and libraries on `@rpath`, Resources, and so on.

Any other run mode is not really supported and may fail in unexpected ways.

**Comment by enen92** [comment]
It never had an icon (just a generic one). Your solution works fine (not sure if it might be somehow automated).
One small issue though, it looks like `-NSDocumentRevisionsDebugMode YES` is interpreted as a playlist :)

image

So you're pretty much pretty much presented with an "Item failed to play" right away

**Comment by stevehartwell** [comment]
Uncheck that debug option in the Run scheme.  And any others.

**Comment by fuzzard** [comment]
Might need to update the cmake to set some of these arguments to what is required (where available in cmaken of course)

Eg. https://cmake.org/cmake/help/latest/variable/CMAKE_XCODE_SCHEME_DEBUG_DOCUMENT_VERSIONING.html
