### PR TITLE
[Xbox] Add support for HDR10 passthrough

### LINKED ISSUE #24070: HDR not supported on Xbox UWP
### Describe the bug
It was previously not possible to enable HDR on Xbox UWP and it was removed in https://github.com/xbmc/xbmc/pull/19879 

@worleydl discovered how to enable it on an Xbox
https://github.com/worleydl/dolphin-color/commits/hdr-xbox
https://github.com/worleydl/pcsx2/commits/hdr

## Expected Behavior
HDR video should play in HDR if the display supports HDR

## Actual Behavior
HDR video is tone mapped to SDR

### To Reproduce

1. Play any HDR video

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [x] Windows UWP

 - Operating system version/name: Xbox Series X
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
[Xbox] Add support for HDR10 passthrough.

Closes https://github.com/xbmc/xbmc/issues/24070

## Motivation and context
As commented in https://github.com/xbmc/xbmc/issues/24070 Microsoft has recently changed something in UWP API (at least for Xbox) and now HDR toggle works using `HdmiDisplayInformation` API.

Almost same code removed in https://github.com/xbmc/xbmc/pull/19879 (due not working) now works. Main difference is that now is used `HdmiDisplayHdrOption::Eotf2084` for GUI because from https://github.com/xbmc/xbmc/pull/23509 GUI is always rendered in BT.2020 and PQ transfer when HDR is ON. This is same in Windows x64.

Toggle code switches HDR state while keep same refresh rate and resolution.

Changes in `CWinSystemWin10::ChangeResolution` are necessary to change video mode (resolution/refresh) while keeps same HDR state: e.g. HDR is alredy on with 59Hz (GUI) and starts playback of 23.976 fps HDR movie.

Logic is quite complex (same as x64) but tested and all seems working as should:

**Auto Mode - "Use HDR display capabilities"  = ON (default)**

- GUI is rendered in SDR mode. HDR only is switched on at playback HDR contents. None is tone mapped.

**Auto Mode but GUI in HDR - "Use HDR display capabilities"  = ON (default)**

- User opens Kodi in SDR but press F11 key (manual HDR toggle). GUI is now in HDR PQ.
- Playing HDR contents HDR not toggles because is already in HDR.
- Playing SDR contents HDR toggles OFF and is played in SDR (no tone mapped).
- When playback stops GUI returns to initial state (HDR PQ ON).

**Manual Mode - "Use HDR display capabilities" = OFF**
- HDR videos are played in SDR mode (tone mapped Renhard/Hable/ACES) unless F11 key is pressed to toggle HDR ON.
- SDR videos are played in SDR and optionally (if HDR is manually ON / F11) are tone mapped to HDR10 by Windows.

All combinations works as expected with correct picture:
- GUI looks fine both SDR and HDR PQ (tone mapped Kodi shaders).
- SDR videos has correct picture when output is HDR PQ (handled by Windows).
- HDR videos has correct picture when output is SDR (tone mapped Kodi).

This after all seems low-risk change because Windows x64 HDR code is not touched and in Xbox feature not working at all previously and in case of some unexpected error users may switch "Use HDR display capabilities" OFF and all works as before (in the worst case scenario).
 

## How has this been tested?
Runtime Xbox Series S

## What is the effect on users?
Enables HDR10 passthrough on Xbox Series S/X

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
Some more tests done:

- 4K HDR 59.94 fps / Hz (Gemini Man) working smooth.
- HLG to PQ working same as x64 desktop.
- "Use system HDR/SDG brightness balance" setting for adjust of SDR subtitles on HDR contents all good.
- "GUI peak luminance in HDR PQ mode" setting also working.

Currently I can't think of any limitation regarding audio/video compared to Windows x64 🙂

**Comment by enen92** [comment]
Can't review (nor even use) but want to say thanks for the feature and for your continued work on the codebase. Definetly will make a lot of users happy.

**Review by afedchin — APPROVED** [review]

File: xbmc/platform/win32/WIN32Util.cpp [hunk 1]
```diff
@@ -1196,7 +1196,38 @@ HDR_STATUS CWIN32Util::ToggleWindowsHDR(DXGI_MODE_DESC& modeDesc)
...
+    if ((!needHDR || (needHDR && mode.ColorSpace() == HdmiDisplayColorSpace::BT2020)) &&
+        mode.ResolutionHeightInRawPixels() == current.ResolutionHeightInRawPixels() &&
+        mode.ResolutionWidthInRawPixels() == current.ResolutionWidthInRawPixels() &&
+        mode.StereoEnabled() == false &&
+        fabs(mode.RefreshRate() - current.RefreshRate()) <= 0.00001)
+    {
+      if (current.ColorSpace() == HdmiDisplayColorSpace::BT2020) // HDR is ON
+      {
+        CLog::LogF(LOGINFO, "Toggle Windows HDR Off (ON => OFF).");
+        if (Wait(hdmi.RequestSetCurrentDisplayModeAsync(mode, HdmiDisplayHdrOption::None)))
```
Comment (CrystalP) [inline xbmc/platform/win32/WIN32Util.cpp:1219]: Does this test the bool return result of RequestSetCurrentDisplayModeAsync()?
Or Wait() own success code?

File: xbmc/windowing/win10/WinSystemWin10.cpp [hunk 2]
```diff
@@ -316,11 +316,14 @@ bool CWinSystemWin10::ChangeResolution(const RESOLUTION_INFO& res, bool forceCha
...
     if (hdmiInfo != nullptr)
     {
       // default mode not in list of supported display modes
-      if (res.iScreenWidth == details->ScreenWidth && res.iScreenHeight == details->ScreenHeight
-        && fabs(res.fRefreshRate - details->RefreshRate) <= 0.00001)
+      if (!needHDR && res.iScreenWidth == details->ScreenWidth &&
+          res.iScreenHeight == details->ScreenHeight &&
+          fabs(res.fRefreshRate - details->RefreshRate) <= 0.00001)
       {
         Wait(hdmiInfo.SetDefaultDisplayModeAsync());
```
Comment (CrystalP) [inline xbmc/windowing/win10/WinSystemWin10.cpp:328]: Is the default mode always SDR?

File: xbmc/windowing/win10/WinSystemWin10.cpp [hunk 3]
```diff
@@ -333,8 +336,10 @@ bool CWinSystemWin10::ChangeResolution(const RESOLUTION_INFO& res, bool forceCha
...
         for (const auto& mode : hdmiModes)
         {
-          if (res.iScreenWidth == mode.ResolutionWidthInRawPixels() && res.iScreenHeight == mode.ResolutionHeightInRawPixels()
-            && fabs(res.fRefreshRate - mode.RefreshRate()) <= 0.00001)
+          if ((!needHDR || (needHDR && mode.ColorSpace() == HdmiDisplayColorSpace::BT2020)) &&
+              res.iScreenWidth == mode.ResolutionWidthInRawPixels() &&
+              res.iScreenHeight == mode.ResolutionHeightInRawPixels() &&
+              fabs(res.fRefreshRate - mode.RefreshRate()) <= 0.00001)
           {
             selected = mode;
```
Comment (CrystalP) [inline xbmc/windowing/win10/WinSystemWin10.cpp:344]: No need to test the mode SDR/HDR attribute to match needHDR, like the HDR toggle?

File: xbmc/rendering/dx/DeviceResources.cpp [hunk 4]
```diff
@@ -1370,13 +1374,28 @@ HDR_STATUS DX::DeviceResources::ToggleHDR()
...
-  if (hdrStatus != HDR_STATUS::HDR_TOGGLE_FAILED)
+  if (!isXbox && hdrStatus != HDR_STATUS::HDR_TOGGLE_FAILED)
   {
     CreateWindowSizeDependentResources();
 
     DX::Windowing()->NotifyAppFocusChange(true);
   }
 
+  // On Xbox set new color space in same swapchain
+  if (isXbox && hdrStatus != HDR_STATUS::HDR_TOGGLE_FAILED)
```
Comment (CrystalP) [inline xbmc/rendering/dx/DeviceResources.cpp:1385]: Isn't CRendererBase::ProcessHDR supposed to take care of setting the swap chain color space? (it also sets the HDR10 metadata, which should also work on xbox now)

File: xbmc/rendering/dx/DeviceResources.cpp [hunk 5]
```diff
@@ -1354,14 +1354,18 @@ HDR_STATUS DX::DeviceResources::ToggleHDR()
   DXGI_MODE_DESC md = {};
   GetDisplayMode(&md);
 
+  // Xbox does not like re-create swapchain but since full screen
+  // exclusive mode is not used, it's not necessary to do so.
+  const bool isXbox = (CSysInfo::GetWindowsDeviceFamily() == CSysInfo::Xbox);
+
```
Comment (CrystalP) [inline xbmc/rendering/dx/DeviceResources.cpp:1360]: What does it mean "does not like"? same black screen + slowness you mentioned in my PR with ClearState()?

File: xbmc/platform/win32/WIN32Util.cpp (hunk 1 above)
Comment (thexai) [reply xbmc/platform/win32/WIN32Util.cpp:1219]: See definition of Wait here:
https://github.com/xbmc/xbmc/blob/031dca9bd69d4e4fa2826690e23eea884b7e3a05/xbmc/platform/win10/AsyncHelpers.h#L63-L79

`Wait` returns result of `winrt::IAsyncOperation<TResult>` that in case of `RequestSetCurrentDisplayModeAsync` is

`winrt::IAsyncOperation<bool>`  then is returned bool.

File: xbmc/windowing/win10/WinSystemWin10.cpp (hunk 2 above)
Comment (thexai) [reply xbmc/windowing/win10/WinSystemWin10.cpp:328]: Yes, default mode is 4K / 59,94 Hz / SDR anyway SetDefaultDisplayModeAsync not supports HDR extensions then can not be used to set any HDR mode. 

Then if `needHDR` is true this is not used and is used the other call (RequestSetCurrentDisplayModeAsync) even if mode was the default (which it is not).

File: xbmc/windowing/win10/WinSystemWin10.cpp (hunk 3 above)
Comment (thexai) [reply xbmc/windowing/win10/WinSystemWin10.cpp:344]: Initially the code was:

```c++
const auto newColoSp = (needHDR) ? HdmiDisplayColorSpace::BT2020 : HdmiDisplayColorSpace::BT709;

if (mode.ColorSpace() == newColorSp && ...)
```

But this broken SDR 23,976 Hz refresh rate (introduces a regression even for users that not use HDR). Probably is because some video modes not has any color space defined `::None`. Then only is compared color space for HDR (BT.2020) but not for SDR. This is same as before.... 

`(!needHDR || (needHDR && mode.ColorSpace() == HdmiDisplayColorSpace::BT2020))`

This condition is always true when is not needHDR. In other words is not possible cause regressions because code used to switch SDR modes not changes.

File: xbmc/rendering/dx/DeviceResources.cpp (hunk 4 above)
Comment (thexai) [reply xbmc/rendering/dx/DeviceResources.cpp:1385]: `CRendererBase::ProcessHDR` only is used for video playback but HDR also needs activated from Kodi GUI (F11 key) because GUI is rendered with color space BT.2020 / tranfer PQ when HDR is On.

This code does the same in Windows x64:

https://github.com/xbmc/xbmc/blob/031dca9bd69d4e4fa2826690e23eea884b7e3a05/xbmc/rendering/dx/DeviceResources.cpp#L755-L756

The only difference is BT.709 color space is not need to specify because is the default when swap chain is created but could be replaced by:

```c++
if (m_IsHDROutput) 
   SetHdrColorSpace(DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020); 
else
   SetHdrColorSpace(DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709); 
```

on Xbox since is not recreated is need a call also for transition HDR --> SDR

File: xbmc/rendering/dx/DeviceResources.cpp (hunk 5 above)
Comment (thexai) [reply xbmc/rendering/dx/DeviceResources.cpp:1360]: No, in this case 4K resolution is lost on GUI. The video output is 4K but GUI is blur like 1080p upscaled to 4K.

The effect is very similar that when Windows limits memory usage or app not has 
<rescap:Capability Name="hevcPlayback" /> in the manifest and limits memory and graphics resources usage.

See: https://github.com/xbmc/xbmc/pull/19659#issuecomment-869806412

Comment (thexai) [reply xbmc/rendering/dx/DeviceResources.cpp:1360]: Off topic here: probably for your PR one path is apply 10 bit setting without kill / recreate swap chain at least for Xbox. Probably current PR code changes are fine for x64.

File: xbmc/platform/win32/WIN32Util.cpp (hunk 1 above)
Comment (CrystalP) [reply xbmc/platform/win32/WIN32Util.cpp:1219]: ok

File: xbmc/windowing/win10/WinSystemWin10.cpp (hunk 2 above)
Comment (CrystalP) [reply xbmc/windowing/win10/WinSystemWin10.cpp:328]: ok

File: xbmc/rendering/dx/DeviceResources.cpp (hunk 5 above)
Comment (CrystalP) [reply xbmc/rendering/dx/DeviceResources.cpp:1360]: That's weird. So the screen resolution is 4k, the resolution of video played is 4k but GUI on top is like 1080p?
Could you write that explanation in the comment instead of "does not like".
What is the connection with FSE? Switching between FSE and windowed doesn't recreate the swap chain.

Is xbox always using 10 bit format for SDR? Otherwise the backbuffer needs to change from 8 to 10bit for HDR playback using m_swapchain->ResizeBuffers() but the current code makes it difficult to do that without a swap chain recreation.

off topic, for v22: even for x64 I think the swap chain is sometimes recreated needlessly, and m_swapchain->ResizeBuffer() would be enough most of the time, but risky to change now.

File: xbmc/rendering/dx/DeviceResources.cpp (hunk 4 above)
Comment (CrystalP) [reply xbmc/rendering/dx/DeviceResources.cpp:1385]: ok

File: xbmc/platform/win32/WIN32Util.cpp [hunk 6]
```diff
@@ -1196,7 +1196,38 @@ HDR_STATUS CWIN32Util::ToggleWindowsHDR(DXGI_MODE_DESC& modeDesc)
...
+  if (!hdmi)
+    return status;
+
+  const auto current = hdmi.GetCurrentDisplayMode();
+
+  const bool needHDR = (current.ColorSpace() != HdmiDisplayColorSpace::BT2020);
+
+  for (const auto& mode : hdmi.GetSupportedDisplayModes())
+  {
+    if ((!needHDR || (needHDR && mode.ColorSpace() == HdmiDisplayColorSpace::BT2020)) &&
```
Comment (CrystalP) [inline xbmc/platform/win32/WIN32Util.cpp:1210]: Not sure mode.ColorSpace() is the best check, the values don't match the values of HdmiDisplayHdrOption passed to RequestSetCurrentDisplayModeAsync

mode also has attributes "IsSdrLuminanceSupported" "IsSmpte2084Supported" "IsDolbyVisionLowLatencySupported", which match the values of HdmiDisplayHdrOption exactly.
But MS doc is not really clear...

File: xbmc/windowing/win10/WinSystemWin10.cpp (hunk 3 above)
Comment (CrystalP) [reply xbmc/windowing/win10/WinSystemWin10.cpp:344]: See my other comment about checking other attributes of mode instead of ColorSpace(), maybe it helps.

With needHDR = false, the test allows modes with any colorspace and good results seem depend SDR modes being enumerated first, which is not very robust, Kodi doesn't control the enumeration.

If no attribute can be used then please add a comment that SDR modes are assumed to be enumerated first, otherwise the wrong mode may be selected. The toggle code has the same weakness.

File: xbmc/windowing/win10/WinSystemWin10.cpp [hunk 7]
```diff
@@ -344,7 +349,8 @@ bool CWinSystemWin10::ChangeResolution(const RESOLUTION_INFO& res, bool forceCha
 
         if (selected != nullptr)
         {
-          changed = Wait(hdmiInfo.RequestSetCurrentDisplayModeAsync(selected));
+          changed = Wait(hdmiInfo.RequestSetCurrentDisplayModeAsync(
+              selected, needHDR ? HdmiDisplayHdrOption::Eotf2084 : HdmiDisplayHdrOption::None));
```
Comment (CrystalP) [inline xbmc/windowing/win10/WinSystemWin10.cpp:353]: Debug log the attributes of the mode + hdr option? Same for toggle. Up to you, xbox is your turf.

**Comment by CrystalP** [comment]
Are there version numbers to test for the availability of this function or was it a matter of MS adding a few additional HdmiDisplayHdrOption values in the SDK?

File: xbmc/windowing/win10/WinSystemWin10.cpp (hunk 3 above)
Comment (thexai) [reply xbmc/windowing/win10/WinSystemWin10.cpp:344]: These are all modes supported in Xbox Series S:

```
2023-11-13 16:55:28.931 T:788      info <general>: 1920x1080, 23.98 Hz, colorSpace: 0, Smpte2084: no, 2086Metadata: no, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.933 T:788      info <general>: 1280x720,  50.00 Hz, colorSpace: 0, Smpte2084: no, 2086Metadata: no, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.935 T:788      info <general>: 3840x2160, 59.94 Hz, colorSpace: 0, Smpte2084: no, 2086Metadata: no, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.937 T:788      info <general>: 1920x1080, 50.00 Hz, colorSpace: 0, Smpte2084: no, 2086Metadata: no, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.938 T:788      info <general>: 3840x2160, 23.98 Hz, colorSpace: 0, Smpte2084: no, 2086Metadata: no, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.940 T:788      info <general>: 3840x2160, 50.00 Hz, colorSpace: 0, Smpte2084: no, 2086Metadata: no, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.942 T:788      info <general>: 3840x2160, 59.94 Hz, colorSpace: 3, Smpte2084: no, 2086Metadata: yes, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.943 T:788      info <general>: 3840x2160, 59.94 Hz, colorSpace: 2, Smpte2084: yes, 2086Metadata: yes, DolbyVision: yes, Stereo: no
2023-11-13 16:55:28.944 T:788      info <general>: 3840x2160, 23.98 Hz, colorSpace: 2, Smpte2084: yes, 2086Metadata: yes, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.946 T:788      info <general>: 3840x2160, 23.98 Hz, colorSpace: 3, Smpte2084: no, 2086Metadata: yes, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.947 T:788      info <general>: 3840x2160, 50.00 Hz, colorSpace: 3, Smpte2084: no, 2086Metadata: yes, DolbyVision: no, Stereo: no
2023-11-13 16:55:28.949 T:788      info <general>: 3840x2160, 50.00 Hz, colorSpace: 2, Smpte2084: yes, 2086Metadata: yes, DolbyVision: yes, Stereo: no
```

2 = BT.2020
3 = BT.709
0 = RgbLimited

Some resolutions only exits in RGBLimited then not all "SDR modes" uses BT.709 
All HDR modes uses BT.2020 and is equivalent to check for Smpte2084 supported

Then I replaced this in HDR toggle code as seems safe.

BUT same replacement in ChangeResolution() cause side effects e.g. 59.94 Hz when HDR is already on and start playback of 23.974 fps movie.

Currently I do not understand the cause and unfortunately do not have time to investigate and doing multiple required tests. To change this I would have to delay it for another week and I think it is now more important to ensure that this is included in Beta2 and RC1 to have feedback and have time to fix possible critical errors before final version.

File: xbmc/rendering/dx/DeviceResources.cpp (hunk 5 above)
Comment (thexai) [reply xbmc/rendering/dx/DeviceResources.cpp:1360]: > Is xbox always using 10 bit format for SDR

Yes, is the default when HDR display is detected: 10 bits is used for both HDR and SDR

File: xbmc/platform/win32/WIN32Util.cpp (hunk 6 above)
Comment (thexai) [reply xbmc/platform/win32/WIN32Util.cpp]: Changed to use `IsSmpte2084Supported()` in toggle code

File: xbmc/windowing/win10/WinSystemWin10.cpp (hunk 3 above)
Comment (CrystalP) [reply xbmc/windowing/win10/WinSystemWin10.cpp:344]: OK so the RGB limited modes are srgb instead of BT709. The gamma curve difference can be compensated.

Fine to push as is with a comment explaining that block is still a work in progress.

**Review by CrystalP — APPROVED** [review]
Cannot runtime test but looks ok, the common scenarios are taken care of.
Will make Xbox owners very happy! And now just wait for the dovi questions to come in...
Please add a WIP / TODO comment in ChangeResolution as its still a bit rough.

**Comment by thexai** [comment]
Jenkins build this please

**Comment by craigcarnell** [comment]
@thexai Do you think DV is possible as well? Fantastic work on the xbox port. I've was hoping HDR would be supported eventually again.

**Comment by danprice142** [comment]
@csdougliss I foundthis on Discord about Dolby Vison if it helps 

The main 3 things are:
Adding the hevcPlayback rescap to the package manifest
Calling out to RequestSetCurrentDisplayModeAsync(mode, HdmiDisplayHdrOption::Eotf2084) from App.cpp layer
Calling swap_chain4->SetColorSpace1(DXGI_COLOR_SPACE_RGB_FULL_G2084_NONE_P2020); when the swap chain is setup.  I think you may set P709 here for DolbyVision, it should probably be optional
