### PR TITLE
[VideoPlayer] Close PGS/VobSub subtitles when audio language dont match

### LINKED ISSUE #26050: Cannot Disable Forced PGS or VOBSUB Subtitles
### Describe the bug
When the Forced flag embedded in PGS or VOBSUB subtitles stream is set to true, it is not possible to disable them during playback in Kodi. Trying to set the forced flag in the container to false (mkv for example), has no effect as the embedded flags in the stream seem to override the container flags.

This issue has been reported on the forum here... https://forum.kodi.tv/showthread.php?tid=379599
It is accepted that the streams in the sample file are incorrectly flagged as forced, but Kodi should still allow a user to enable/disable them.

## Expected Behavior
Allow forced subtitles to be toggled on or off.

## Actual Behavior
Forced subtitles cannot be disabled.

## Possible Fix
--

### To Reproduce
1. From the forum thread, download the sample file in post#16 (if the links have expired, let me know as I will hold onto the sample for a few weeks.)
2. Play file and try to disable subtitles.
3.

### Debuglog
Nil

### Screenshots 
Nil

## Additional context or screenshots (if appropriate)
Nil

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v21, v22

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

Stream selection always try to select the "best" track based on settings also when subtitles are disabled, and internally the stream is kept opened

This means that even though subtitles are disabled, they are still parsed.
Parsing PGS/VobSub subtitles that support “forced” mode on individual images will override the subtitle settings,
with the result that "forced" images are always displayed on screen, even if subtitles settings are set to disabled.

This can also lead to the display of an unwanted language,
the behaviour is:
`-> kodi select "best" language -> open the stream -> if dont match the settings, it set the subs visibility to false, but still kept the stream opened`

so it is necessary to close the stream at least when it does not match the audio language,
in order to avoid parsing (and show on screen) unwanted languages

this is based on closed PR #26087 after further verification i think this is currently the best approach
except that i added an additional check for the subtitle type so as not to affect other subtitle types with this behavior

## Motivation and context

fix #26050
## How has this been tested?

user test stream:
[Bud_VOBSUB_Forced.zip](https://github.com/user-attachments/files/23499113/Bud_VOBSUB_Forced.zip)

1) set kodi audio and subtitles language settings to english
2) play the video
3) BEFORE: kodi show unwanted language (forced overlays)
AFTER: kodi internally close the stream because dont match audio language (forced overlays are not parsed/shown)

## What is the effect on users?

avoid show unwanted language
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 1]
```diff
@@ -1063,9 +1063,21 @@ void CVideoPlayer::OpenDefaultStreams(bool reset)
       valid = true;
       if(!psp.relevant(stream))
         visible = false;
+
+      // Image type subtitles (e.g. VOBSUB) can support "forced" flag on overlays (images)
+      // so you need to keep the stream open to parse "forced" flag on each image
+      // since we leave the stream open by default, it is necessary to close it
+      // if the language does not match the preferences.
+      if (!visible && StreamUtils::IsCodecSupportForcedOverlay(stream.codecId) &&
+          !g_LangCodeExpander.CompareISO639Codes(stream.language, as.language))
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:1072]: in case of invalid values `m_SelectionStreams.Get()` return an empty object
then IsCodecSupportForcedOverlay and CompareISO639Codes will fails in any case

**Review by thexai — APPROVED** [review]
👍

**Comment by garbear** [comment]
@claude please review

**Comment by CastagnaIT** [comment]
jenkins build this please

**Comment by CrystalP** [comment]
I haven't had the chance to retest, but unless something changed in the player I have to repeat my previous comment on the previous PR
https://github.com/xbmc/xbmc/pull/26087#issuecomment-2658259690
I don't think it's the correct place for a fix.

Also does it allow turning off forced subs that match the current audio language (situation where they normally would be displayed, but the user wants them off)?

**Comment by CastagnaIT** [comment]
i will take a look

**Comment by thexai** [comment]
This PR corrects a situation where subtitles should NOT be displayed under any circumstances (it doesn't depend on the settings or user preferences). For me the fix is correct.

If the user doesn't want any subtitles at all, that's a separate issue that probably requires a new setting, but it doesn't make much sense to me if the user has also selected "only forced" as a preference. (only forced for me is "I want forced subs enabled").

Furthermore, forced PGS subtitles cannot be disabled by definition.

**Comment by CastagnaIT** [comment]
i done some more tests (always by deleting MyVideos*.db database between tests to avoid have settings stored that invalidate tests)
1) (sub lang set to english) -> play sample -> subs are disabled -> OSD enable subs -> subs are displayed correctly
2) (sub lang set to english) -> play sample -> subs are disabled -> OSD enable and disable subs -> subs are not displayed correctly
3) (sub lang set to english) -> play sample -> subs are disabled -> OSD enable and disable and re-enable subs -> subs are displayed correctly

this change seem dont cause side effects, or please specify better the use case, maybe i didn't understand...

However, if you are considering to fully disabling “forced” overlays, this is not covered by this PR
f.e. VLC dont support "forced overlays" just it's just a simple enable/disable subs (at least it seems that way)

as @thexai said PGS/Vobsub should always have the "forced" subs displayed regardless of the settings (this is by subtitles type specs)
if instead we want provide a way to disable "forced" overlay support, i agree that another setting is required

otherwise remove this support, but i don't know if everyone would appreciate that, as usual, these are small features that you either like or dislike

(forced push just rebased branch)

**Comment by CastagnaIT** [comment]
@CrystalP let me know if you have specific tests to do

**Comment by CrystalP** [comment]
I dug up the sample of the user who started the issue (subs encoded with forced flag on every picture even though they're regular subs, and could not be turned off).
Also starting from an empty database.
Play > initially subs are turned off and no subs are rendered > fine
Attempt to turn subs on (key T or toggle OSD Enable Subtitles on/off,  > the toast message appears with the subs language (swe because that sub is the first sub track) but the subs don't actually show.

It's what I commented on earlier, VP expects the current sub to be loaded (even if subs are disabled).
A side effect (or was it the goal in the design many years ago?) of that assumption is that when subs are turned on at some point T, they display instantly for timestamp T because already demuxed and queued instead of showing later at T+8 seconds due to demuxer read-ahead.

**Comment by CastagnaIT** [comment]
> they display instantly for timestamp T because already demuxed and queued instead of showing later at T+8 seconds due to demuxer read-ahead.

yes this is an existing bug i dont see how this is related with this PR,
however about this there is an Issue opened #21086 where Fernet has given a kind of fix hint but i don't understand about how it should be done

infact if you reenable subs, subs are correctly shown on screen just do video seek, otherwise you need a video that have more subs cues, the attached sample video is too short...

**Comment by CrystalP** [comment]
> > they display instantly for timestamp T because already demuxed and queued instead of showing later at T+8 seconds due to demuxer read-ahead.
> 
> yes this is an existing bug i dont see how this is related with this PR, however about this there is an Issue opened #21086 where Fernet has given a kind of fix hint but i don't understand about how it should be done
> 
> infact if you reenable subs, subs are correctly shown on screen just do video seek, otherwise you need a video that have more subs cues, the attached sample video is too short...

I shouldn't have mentioned it, it plays no role here. I tried seeking and the sub still didn't appear > issue not related to the caching. The only way to make subs appear is to switch to a different sub (because that action loads a new track).

**Comment by CastagnaIT** [comment]
i will try test again, but as mentioned on my previous comment i was not able to replicate your problem

**Comment by CastagnaIT** [comment]
so i started again from scratch database removed,
settings are:
immagine
at playback start, no subtitles as expected,
then i enabled here:
immagine
i seeked back the video and subtitles are shown correctly,
maybe you have different settings?

**Comment by CrystalP** [comment]
Yes the settings are a bit different, I tested with default settings. With a new portable directory, they are:

image

image

Play the sample: subs not displayed.
Toggle subs on / press T (and seek back for the short sample): toast popup with "Subtitles Swedish", but no subs rendered.
After selecting a different subs track (and seeking back), they appear (even the Swedish that were initially not displayed)

The default preferred sub language was changed recently; reverting to "none" gives the same result.

**Comment by CrystalP** [comment]
Tried other settings just in case (even the same as you) but I still observe the same:

image

image

**Comment by CrystalP** [comment]
I think that after following the code what I see makes sense. The track is initially unloaded, so the demuxer filters out the sub packets. Switching subs on allows the rendering of subs but there are no demuxed packets to render on screen. Seeking cannot help.
Switching sub tracks opens that stream and the sub packets are not discarded anymore. They're then rendered per the "usual" behavior (rendered when "enable subs" is on, or unconditionnally when pgs/vobsubs have the picture forced flag).

File: xbmc/utils/StreamUtils.cpp [hunk 2]
```diff
@@ -150,3 +150,9 @@ std::string StreamUtils::GetLayout(unsigned int channels)
 
   return layout;
 }
+
+bool StreamUtils::IsCodecSupportForcedOverlay(int codecId)
+{
+  return codecId == AV_CODEC_ID_DVD_SUBTITLE || codecId == AV_CODEC_ID_HDMV_PGS_SUBTITLE ||
+         codecId == AV_CODEC_ID_DVB_SUBTITLE;
```
Comment (garbear) [inline xbmc/utils/StreamUtils.cpp:157]: `AV_CODEC_ID_DVB_SUBTITLE` is listed twice?

**Comment by garbear** [comment]
@claude checking in, where are we at?

**Comment by CastagnaIT** [comment]
> Yes the settings are a bit different, I tested with default settings. With a new portable directory, they are:
> image image
> 
> Play the sample: subs not displayed. Toggle subs on / press T (and seek back for the short sample): toast popup with "Subtitles Swedish", but no subs rendered. After selecting a different subs track (and seeking back), they appear (even the Swedish that were initially not displayed)
> 
> The default preferred sub language was changed recently; reverting to "none" gives the same result.

ok i reproduced it
so by using GUI subtitles are shown correctly
but if you use keyboard (with T) subtitles are NOT shown correctly
as soon as i have time, i will try to see if i can understand it better this difference

File: xbmc/utils/StreamUtils.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/utils/StreamUtils.cpp:157]: look at DVD vs DVB

Comment (garbear) [reply xbmc/utils/StreamUtils.cpp:157]: You're right. I even tried comparing pixels and missed the difference. Not sure if code can be made more clear but it's correct as is.

**Comment by CastagnaIT** [comment]
@CrystalP problem fixed now should work correctly

**Comment by CrystalP** [comment]
yes ok, thanks.
