### PR TITLE
[addons] store number of available updates to member for performant use

### LINKED ISSUE #18588: Kodi high CPU usage on addons menu
### Describe the bug
Here is a clear and concise description of what the problem is:
When you navigate from main screen to addons menu (where on top is the number of addons to be updated) the cpu usage become higher. Also if video is played on background it get slow playback. The issue happens after https://github.com/xbmc/xbmc/pull/18546. Seems addons are checked even if not installed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
CPU usage should be the same as before and playback on background should be normal.

## Actual Behavior
CPU usage is higher and video playback is not smooth.

## Possible Fix
Not known.

### To Reproduce
1. went back to main kodi screen
2. went to addons menu
3. check cpu usage before and after

### Debuglog
The debuglog can be found here: https://pastebin.com/J9zsL04j

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://ibb.co/SP2zVm3
https://ibb.co/xs9sMdp

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Ubuntu 18.04.5 LTS, kernel: Linux x86 64-bit version 5.4.0-51-generic
 - Kodi version: Kodi (19.0-ALPHA2 (18.9.702) Git:20201016-f68475a8d5). Platform: Linux x86 64-bit

### PR DESCRIPTION
**Pull request by howie-f**
## Description
stores the number of available addon-updates to a private member for use with infolabel `AddonUpdateCount`.
prevents the expensive call to `GetAvailableUpdates()` in a tight loop.

## Motivation and Context
closes #18588 

## How Has This Been Tested?
debian buster local

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Improvement** (non-breaking change which improves existing functionality)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

File: xbmc/addons/AddonManager.cpp [hunk 1]
```diff
@@ -211,7 +211,11 @@ bool CAddonMgr::ReloadSettings(const std::string &id)
 
 std::vector<std::shared_ptr<IAddon>> CAddonMgr::GetAvailableUpdates() const
 {
-  return GetAvailableUpdatesOrOutdatedAddons(false);
+  std::vector<std::shared_ptr<IAddon>> availableUpdates =
+      GetAvailableUpdatesOrOutdatedAddons(false);
+  m_lastAvailableUpdatesCount = availableUpdates.size();
```
Comment (ksooo) [inline xbmc/addons/AddonManager.cpp:216]: CAddonMgr::GetAvailableUpdates() writing the new member and GetLastAvailableUpdatesCount() reading it are accessed from different threads. Thus access to the new member must be mutex protected i both the writing and reading method.

File: xbmc/addons/AddonManager.h [hunk 2]
```diff
@@ -486,6 +486,14 @@ namespace ADDON
     bool GetCompatibleVersions(const std::string& addonId,
                                std::vector<std::shared_ptr<IAddon>>& compatibleVersions) const;
 
+    /*!
+     * \brief Return number of available updates collected by GetAvailableUpdates()
+     *        this can be used as a lightweight method of retrieving the number of updates
+     *        rather than using the expensive GetAvailableUpdates call
+     * \return number of available updates
+     */
+    unsigned int GetLastAvailableUpdatesCount() const { return m_lastAvailableUpdatesCount; };
```
Comment (ksooo) [inline xbmc/addons/AddonManager.h:495]: As member access needs mutex protection, I would not inline define this method.

File: xbmc/addons/AddonManager.h [hunk 3]
```diff
@@ -486,6 +486,14 @@ namespace ADDON
     bool GetCompatibleVersions(const std::string& addonId,
                                std::vector<std::shared_ptr<IAddon>>& compatibleVersions) const;
 
+    /*!
+     * \brief Return number of available updates collected by GetAvailableUpdates()
```
Comment (ksooo) [inline xbmc/addons/AddonManager.h:490]: i would never describe any implementation details in interface documentation, only the functionality.

File: xbmc/guilib/guiinfo/SystemGUIInfo.cpp [hunk 4]
```diff
@@ -307,7 +307,7 @@ bool CSystemGUIInfo::GetLabel(std::string& value, const CFileItem *item, int con
       return true;
     case SYSTEM_ADDON_UPDATE_COUNT:
       value =
-          StringUtils::Format("{0}", CServiceBroker::GetAddonMgr().GetAvailableUpdates().size());
+          StringUtils::Format("{0}", CServiceBroker::GetAddonMgr().GetLastAvailableUpdatesCount());
```
Comment (ksooo) [inline xbmc/guilib/guiinfo/SystemGUIInfo.cpp:310]: If the new method is made exactly for this use case, i would let it do the string conversion, which makes it even cheaper. Means, change the new member to be a string.

**Review by ksooo — CHANGES_REQUESTED** [review]

File: xbmc/addons/AddonManager.cpp (hunk 1 above)
Comment (howie-f) [reply xbmc/addons/AddonManager.cpp:216]: ok, regarding the mutex i've searched the webs and come up now with this https://github.com/howie-f/xbmc/commit/1ff3de915f9ed334a19377a29c4784cc6503b835 is this what we need in our case? (for some reason i don't know that guy didn't lock the read in the getter)

Comment (ksooo) [reply xbmc/addons/AddonManager.cpp:216]: It's okay as you did. It's a widely spread mistake not to protect the getters. But it's necessary, because the writing thread might be somewhere in the middle of changing data while the unprotected getter reads that half-changed data.

Comment (ksooo) [reply xbmc/addons/AddonManager.cpp:216]: BTW: Thre is no reason for stroing a copy of the vector here! Just do

std::string ...::Get....() const
{
  std::string count = std::to_string(GetAvailableUpdatesOrOutdatedAddons(false).size());
  ...mutex lock
  m_lastAva... = count;
  return m_last...
}

Note that m_aval is a string now!

Comment (howie-f) [reply xbmc/addons/AddonManager.cpp:216]: yeah, assuming that is `GetLastAvailableUpdateCount()` this would bring our 1700% cpu usage back ;)

File: xbmc/addons/AddonManager.cpp [hunk 5]
```diff
@@ -211,9 +211,21 @@ bool CAddonMgr::ReloadSettings(const std::string &id)
 
 std::vector<std::shared_ptr<IAddon>> CAddonMgr::GetAvailableUpdates() const
 {
-  return GetAvailableUpdatesOrOutdatedAddons(false);
+  std::vector<std::shared_ptr<IAddon>> availableUpdates =
+      GetAvailableUpdatesOrOutdatedAddons(false);
+
+  std::lock_guard<std::mutex> lk(m_lastAvailableUpdatesMutex);
+  m_lastAvailableUpdatesCountAsString = StringUtils::Format("{0}", availableUpdates.size());
```
Comment (ksooo) [inline xbmc/addons/AddonManager.cpp:218]: std::to_string should also work and is more simple than StringUtils::Format

File: xbmc/addons/AddonManager.cpp [hunk 6]
```diff
@@ -211,9 +211,21 @@ bool CAddonMgr::ReloadSettings(const std::string &id)
 
 std::vector<std::shared_ptr<IAddon>> CAddonMgr::GetAvailableUpdates() const
 {
-  return GetAvailableUpdatesOrOutdatedAddons(false);
+  std::vector<std::shared_ptr<IAddon>> availableUpdates =
+      GetAvailableUpdatesOrOutdatedAddons(false);
+
+  std::lock_guard<std::mutex> lk(m_lastAvailableUpdatesMutex);
```
Comment (ksooo) [inline xbmc/addons/AddonManager.cpp:217]: We usually use 'lock' as name for locks.

File: xbmc/addons/AddonManager.h [hunk 7]
```diff
@@ -561,6 +569,12 @@ namespace ADDON
 
     // Temporary path given to add-ons, whose content is deleted when Kodi is stopped
     const std::string m_tempAddonBasePath = "special://temp/addons";
+
+    /*!
+     * latest count of available updates
+     */
+    mutable std::string m_lastAvailableUpdatesCountAsString;
+    mutable std::mutex m_lastAvailableUpdatesMutex;
```
Comment (ksooo) [inline xbmc/addons/AddonManager.h:577]: I would name the  mutex `m_lastAvailableUpdatesCountMutex` as this is what the mutex protects.

File: xbmc/addons/AddonManager.h [hunk 8]
```diff
@@ -486,6 +486,14 @@ namespace ADDON
     bool GetCompatibleVersions(const std::string& addonId,
                                std::vector<std::shared_ptr<IAddon>>& compatibleVersions) const;
 
+    /*!
+     * \brief Return number of available updates formatted as string for infolabel use
```
Comment (ksooo) [inline xbmc/addons/AddonManager.h:490]: Don't want to be too nitpicking, but how could you know that this string is only used for GUI info labels? So, say this is an example use or (better) just leave this kind of usage assumptions.

BTW: It's "GUI info labels"

File: xbmc/addons/AddonManager.cpp [hunk 9]
```diff
@@ -211,9 +211,21 @@ bool CAddonMgr::ReloadSettings(const std::string &id)
...
+  m_lastAvailableUpdatesCountAsString = StringUtils::Format("{0}", availableUpdates.size());
+
+  return availableUpdates;
 }
 
+const std::string& CAddonMgr::GetLastAvailableUpdatesCountAsString() const
+{
+  std::lock_guard<std::mutex> lk(m_lastAvailableUpdatesMutex);
```
Comment (ksooo) [inline xbmc/addons/AddonManager.cpp:225]: `lock`, not `lk`

File: xbmc/addons/AddonManager.h (hunk 8 above)
Comment (phunkyfish) [reply xbmc/addons/AddonManager.h:490]: What else would you use a string surrounded by `{}` for?

Comment (phunkyfish) [reply xbmc/addons/AddonManager.h:490]: Ignore me. Having a face palm moment.

Comment (howie-f) [reply xbmc/addons/AddonManager.h:490]: this was just an example, i'd simply cut `for infolabel use` off. agree this is the official doc and would imply it is only for gui infolabel usage which is not true... let's do it perfect :)

**Review by ksooo — APPROVED** [review]
Awesome. Thank you.

**Review by phunkyfish — APPROVED** [review]

**Comment by howie-f** [comment]
thanks guys for polishing it up and thanks @vpeter4 for reporting the issue.
didn‘t notice this during testing

**Comment by howie-f** [comment]
so strictly speaking, and with @lrusak ‘s work in https://github.com/xbmc/xbmc/pull/20980, the `std::mutex` introduced here should have been one of our custom locks in the first place?

**Comment by phunkyfish** [comment]
Not necessarily. I asked the question about that on that PR. Let’s see what the response is.
