### PR TITLE
[video] Video versions: Fix certain default select action handling scenarios

### LINKED ISSUE #24448: Selected Version will not play
### Describe the bug
I have installed... KodiSetup-20240107-caa9d53c-master-x64

When the option... **Default select action** is set to...
**Play**- selecting a movie version to play, the selected version is played
**Information**- selecting a movie version to play, the parent movie plays.

## Expected Behavior
When selecting a version to play, the selected version should play

## Actual Behavior
The parent movie plays instead of the selected version

### To Reproduce

1. 
2.
3.

### Debuglog
https://paste.kodi.tv/puhagufoqi.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #24448 

When 'default select action' is `choose` or `info` and 'select default version' is `off` and 'show videos with multiple versions as folder' is `off`, then the action would be executed upon the default video version, not the version selected by the user, e.g. video info dialog with wrong version opened, leading to button 'Play' playing (ofc) the wrong version, from users point of view, though technically working correct. The dialog plays exactly the version it was initialised with. But root cause is to initialise it with the wrong version. ;-)

Runtime-tested on macOS, latest Kodi version.

@enen92 something for you to review, please. Problem with previous implementation was that the version selected is not always in the list of items the window displays. The index passed on points to the default version of the video. We must not pass the index, but the real item to the window.

### CODE REVIEW

**Review by enen92 — APPROVED** [review]
+1. Can't say I like much the special case for versions there though

**Comment by ksooo** [comment]
> Can't say I like much the special case for versions there though

Same here. But we can only do one small step after the other and it is still a long way to go to clean up all the mess - err special casing needed - caused by the original design.

File: xbmc/video/windows/GUIWindowVideoBase.cpp [hunk 1]
```diff
@@ -821,16 +826,13 @@ void CGUIWindowVideoBase::GetContextButtons(int itemNumber, CContextButtons &but
   CGUIMediaWindow::GetContextButtons(itemNumber, buttons);
 }
 
-bool CGUIWindowVideoBase::OnPlayStackPart(int itemIndex, unsigned int partNumber)
+bool CGUIWindowVideoBase::OnPlayStackPart(const std::shared_ptr<CFileItem>& item,
```
Comment (garbear) [inline xbmc/video/windows/GUIWindowVideoBase.cpp:829]: When I built an early dialog, it looked like this, with `const std::shared_ptr<CFileItem>& item` copied from an even earlier dialog and passed around everywhere. I refactored it to pass around `const CFileItem& item` and the result was more concise code without an extra shared_ptr dependency everywhere.
