### PR TITLE
[python][window] Delete pcontrol after SendGUIMessage

### LINKED ISSUE #22674: Crash when you use self.removeControl on xbmcgui.WindowXMLDialog
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a custom window by using `xbmcgui.WindowXMLDialog`
on `onInit()` method i placed the code to remove some added XML button controls

look at sample addon on file: `resources/lib/kodi/ui/xmldialog_ratingthumb.py`
relative window xml: `resources/skins/default/1080i/plugin-video-netflix-RatingThumb.xml`

so the window is opened correctly but when it execute `self.removeControl` kodi crashes

~_seem a problem of current master branch_~
~on Kodi 19 or 20 i dont have crashes, maybe by luck?~

if you use Windows nightly release, the crash never happens
if you self build kodi for Windows, as debug mode, the crash always happens
on android its weird, usually can happens the first time, on next kodi run seem dont crash anymore

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Have the window opened with the controls removed

## Actual Behavior

The window is opened but kodi crashes

## Possible Fix

I tried investigate and i see something weird on control pointers
on: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/legacy/Window.cpp#L553-L566

when the `while` is executed the control is erased from vecControls vector
after that `pControl` become with weird content at least my debugger show weird values
and when is executed the SendGUIMessage, callback fall here:
https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIWindow.cpp#L698
on mentioned line the dereference make kodi to crash

no idea for a good fix

### To Reproduce

1. Build kodi as debug mode for Windows
2. Install: [plugin.video.netflix_1.20.5+matrix.1_TEST.zip](https://github.com/xbmc/xbmc/files/10569485/plugin.video.netflix_1.20.5%2Bmatrix.1_TEST.zip) its a modded fake addon, just to open the custom window dialog
3. Run the addon
4. A small window dialog with thumb up / down should be shown without Kodi crash

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/meyezagoyu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 / SHield 
 - Kodi version: builded from master branch and android master branch nightlies

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

The fix was simple, window controls pointers are stored to `vecControls`
when a python addon execute `self.removeControl` in a XML window
the `Window::doRemoveControl` is executed
but the while loop to `vecControls` delete the specified control pointer
the pointer data is so lost and the `SendGUIMessage` that is executed after that send a dead pointer that make kodi crash
so solution is just reverse the code order

Now I don't know why this works with some release build, perhaps the code execution it is so fast in the that the pointer data has not yet been completely wiped from memory, however this on debug builds always make kodi crashes
differently on android also the release build make kodi crash

## Motivation and context

fix #22674
## How has this been tested?

Used python test addon in the Issue
the test addon is a bit confusing but the relevant file is in the file:
resources/lib/kodi/ui/xmldialog_ratingthumb.py
on `onInit` method the first `self.removeControl`  call cause kodi crash

tested on windows debug build and android release build (on android debug and release was crashing)

## What is the effect on users?

Python addons that use custom XML windows and `self.removeControl` dont make crash kodi anymore

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/interfaces/legacy/Window.cpp [hunk 1]
```diff
@@ -550,21 +550,23 @@ namespace XBMCAddon
...
+      std::vector<AddonClass::Ref<Control>>::iterator it = vecControls.begin();
       while (it != vecControls.end())
       {
         AddonClass::Ref<Control> control = (*it);
         if (control->iControlId == pControl->iControlId)
         {
           it = vecControls.erase(it);
-        } else ++it;
+        }
+        else
```
Comment (enen92) [inline xbmc/interfaces/legacy/Window.cpp:566]: can you add the braces to this branch as well? Not a big deal (and not mandatory) but I think it reads better due to the above if being also wrapped (and multi-line)

**Review by enen92 — APPROVED** [review]
Thanks!
