### PR TITLE
Fix rendering for EGL_KHR_partial_update enabled platforms

### LINKED ISSUE #26305: [webOS d4d99546] Blank/Flickering screen on start up
### Describe the bug
Here is a clear and concise description of what the problem is:

After a fresh install, when opening the Kodi app on webOS the Kodi logo shows, then the screen goes completely blank. The TV is not frozen, just the app shows nothing. I have replicated this on:

-  251a25f0
- e7e6ee63
- 8a0d510b
- d761f075
- 4aa140e3
- d4d99546

I have reinstalled about ten times using these different builds, and the issue is the same.

After writing this bug report, I restarted my TV and tried again. This time the screen flickered when Kodi was opened. See Log #2

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The app's menu should have shown.

## Actual Behavior

After the Kodi logo appears and disappears, the screen turns black (Kodi displays nothing)

Log #1: I wish to note that when presented with a black screen I proceeded to click the 'main' (or 'click?' button) and 'back' button on my remote multiple times, with no change to the screen.

### To Reproduce

1. Install Kodi on webOS
2. Open Kodi
3. Stare into the void of nothingness

### Debuglog

The debuglog can be found here:

Log #1: https://paste.kodi.tv/pigiyuputi.kodi

Log #2: https://paste.kodi.tv/ohewinahaj.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Video (expires in 2 days) of the screen flickering (Log #2) https://streamable.com/gug0z9

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I just want Kodi to work without A/V sync issues, which is present on the stable build :(

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [x] webOS

 - Operating system version/name: webOS24 9.2.2-1805
 - Kodi version: d4d99546-master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by sarbes**
## Description
Final touches for platforms with EGL_KHR_partial_update support. The main issue is that `eglQuerySurface(m_eglDisplay, m_eglSurface, EGL_HEIGHT, &height)` returns just 1 on current Mesa for some reason :(. 

## Motivation and context
Fixes rendering on EGL_KHR_partial_update enabled platforms.

## How has this been tested?
Runs fine with every algorithmdirtyregions type on my Odroid C2 on Libreelec 13.

## What is the effect on users?
Display the UI properly on Panfrost/Lima systems.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/utils/EGLUtils.cpp [hunk 1]
```diff
@@ -667,13 +667,16 @@ void CEGLContextUtils::SetDamagedRegions(const CDirtyRegionList& dirtyRegions)
   }
   else
   {
-    EGLint height = eglQuerySurface(m_eglDisplay, m_eglSurface, EGL_HEIGHT, &height);
+    EGLint height;
```
Comment (fritsch) [inline xbmc/utils/EGLUtils.cpp:670]: Please initialize to 0, so when the below call fails, we still have a valid value.

Comment (sarbes) [reply xbmc/utils/EGLUtils.cpp]: Yeah, sorry about that. I've defaulted to a height of 1080, if that's all right.

File: xbmc/utils/EGLUtils.cpp [hunk 2]
```diff
@@ -667,13 +667,16 @@ void CEGLContextUtils::SetDamagedRegions(const CDirtyRegionList& dirtyRegions)
   }
   else
   {
-    EGLint height = eglQuerySurface(m_eglDisplay, m_eglSurface, EGL_HEIGHT, &height);
+    EGLint height = 1080;
+    eglQuerySurface(m_eglDisplay, m_eglSurface, EGL_HEIGHT, &height);
```
Comment (fritsch) [inline xbmc/utils/EGLUtils.cpp:671]: What would practically happen if the call fails and region.y2 is larger than 1080?

Comment (sarbes) [reply xbmc/utils/EGLUtils.cpp:671]: The UI would be unusable.

Comment (fritsch) [reply xbmc/utils/EGLUtils.cpp:671]: Yeah. That was my hint ;-). So should we go with height of 1080 or should we rather make sure that the rect's height we set below is positiv?

Comment (sarbes) [reply xbmc/utils/EGLUtils.cpp:671]: You really don't trust the EGL implementations out there, do you 🙂?

If the driver fails us here, we would need to return a bool that it did and subsequently draw the UI at full resolution, not just the subset which was suitable for the regions. In this case, we would essentially fall back to the default `<algorithmdirtyregions>3</algorithmdirtyregions>`. 

I don't think that adding such workarounds for broken embedded drivers is really worth it, since it also adds to the main application code. Because this code is gated behind an advanced setting (which has driver warnings in the wiki), the impact of a malfunctioning driver is not critical.

Or do you see a way this could fail in normal operation?

Comment (fritsch) [reply xbmc/utils/EGLUtils.cpp:671]: In fact since I started with Kodi there was always a broken driver ;-). One broken differently than the other. Let's go with what we have now here. Reality will tell.

What you could do to help us track that issue: if it returns false log a debug

**Review by fritsch — APPROVED** [review]
Thanks very much!

**Review by neo1973 — APPROVED** [review]

File: xbmc/utils/EGLUtils.cpp [hunk 3]
```diff
@@ -669,6 +669,12 @@ void CEGLContextUtils::SetDamagedRegions(const CDirtyRegionList& dirtyRegions)
   {
     EGLint height = 1080;
     eglQuerySurface(m_eglDisplay, m_eglSurface, EGL_HEIGHT, &height);
```
Comment (kszaq) [inline xbmc/utils/EGLUtils.cpp:671]: Is it possible to use
```
if (eglQuerySurface(m_eglDisplay, m_eglSurface, EGL_HEIGHT, &height) != EGL_TRUE)
```
or
```
if (!eglQuerySurface(m_eglDisplay, m_eglSurface, EGL_HEIGHT, &height))
```
to prevent calling `eglGetError()`?

**Comment by neo1973** [comment]
Jenkins build this please.

**Comment by Portisch** [comment]
Is that intentional that now `SetDirtyRegions` is only called when not `DIRTYREGION_SOLVER_FILL_VIEWPORT_ALWAYS` or `DIRTYREGION_SOLVER_FILL_VIEWPORT_ON_CHANGE` is used?

https://kodi.wiki/view/Advancedsettings.xml#algorithmdirtyregions
