### PR TITLE
[VideoPlayerAudio] Flush audiosink when dropping audio packets (edl m…

### LINKED ISSUE #17328: [REGRESSION] Kodi v18.8 (EDL) muting de-syncs audio 8/12/20
## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Back in Kodi Version 17.0 it will mute starting at the indicated time and unmute at the end time (as it is marked precisely in the EDL file).

Here is a comparison video of the last stable build 17.1-RC1 (GIT:2017-02-22-964306f)
https://drive.google.com/file/d/1G6YFIc4Owpdt2y3hj7W3mZQrA7NZyDhc/view?usp=sharing

## Actual Behavior

The problem is that instead of giving us silence at the start of the mute time it plays the next available sound (which would be the sound, possibly in the buffer, that comes immediately after the marked end mute time)
So, it will play a seemingly random length of audio from the future which won't line up with the lips at all. And it will then silence the audio until it reaches the end of the stolen audio buffer.   <<<    Instead of unmuting at the marked end time.

Here is a simple video demonstration. Watch their lips
https://drive.google.com/file/d/1Njj79fA5fpLJuu7obMJ5F1LM68D1qBJz/view?usp=sharing

## Possible Fix

Remove the patch that came in and messed with the EDL code in V17.1
https://github.com/xbmc/xbmc/pull/11714
^^^ here

### To Reproduce

1. Download
https://drive.google.com/open?id=1YBoUXXO3CcjUNgl-eg_Otsu_vwjhwtxm
!!!Ignore log file which was on Windows 7 originally with Kodi v18.5
18.8 log on windows 10 is below >>>

~~~~~~~~~~~~~~~~~~~~
WATCH Jimmy Stewart's LIPS.
You will see him grunting repeatedly then on his last grunt you will suddenly see him talking from the future audio.
~~~~~~~~~~~~~~~~~~~~~

2...Watch it with and without the edl file in the same folder to get a feel for the dialogue. Note audio should be set to Stereo PCM through DirectSound possibly

3. Play my clip or try it on lots of other videos too that you're more familiar with and watch their lips to see when the audio is getting played ahead of time.
...Sometimes it won't play sound from the future (but I think honestly those times it was just silent in the movie where it stole the sound from)
I notice that 90% of every video does this. And it happens on 4 of my computers Windows 7 Windows 8 and Windows 10 included. I have further tested on 2 more machines with ubuntu 16.04 through 20.04
It happens on full 1080p blurays and 480p dvds and everything in between from my experience. Audio formats don't matter either.

### Debuglog

The debuglog can be found here:

[kodi.log](https://drive.google.com/file/d/1KQXuCq7K4G_8tWxTfIhE29bLXbEuGUip)
^^^Kodi V18.8 on windows 10
!!!The log in the original download is for 18.5 which can be ignored

As requested
Kodi Nightly Log 8/13/20
https://pastebin.com/CzNeTfML

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

The other person who initially brought up the most recent EDL (commercials don't skip because of comments) bug over on the forums mentioned this lingering issue (once the comments bug was fixed)
His name is "Astrocyte74" and you can see what he said here
https://forum.kodi.tv/showthread.php?tid=349685
"There is still the annoying audio sync issue for a few seconds before and after every '1' (mute) where as with kodi 17.0 (and earlier builds) the mute worked perfectly.  Should I report this somewhere?"
I have also found that v16.1 did not have this issue

EDIT:
Here is another description of his issue which sounds like mine too
"With 18.4, .edl files worked.  Though, since v17 .edl files have caused a temporary audio sync issue but it always re-adjusts / catches up.  Here is a log for 18.4 running the same movie / edl file:"
^^^But there's his log too...actually that has the previous bug in it which seems to have been fixed.
I'll ask him for a new log only showing this bug which remains which we both seem to have.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.8

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
…ute)

## Description
Follow up to https://github.com/xbmc/xbmc/pull/20293 - in the proximity of edl mute ranges it seems VPA tries to keep up with the dropped packets and audio sort of accelerates or jumps forward. The behaviour was described here: https://github.com/xbmc/xbmc/pull/20293#issuecomment-971239711
This happens because the sink still has a small buffer of packets, hence make sure the sink is flushed when audio packets are intentionally dropped (as the case of EDL mute). It was confirmed fixed by the issue reporter.

@FernetMenta, again, it seems the only way for this to go forward is with your help/review. Can you please take a look if possible? Is the change acceptable or do you foresee any regressions for other use cases?

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/17328

## How has this been tested?
With the sample provided by @lilgandhi1199 on https://github.com/xbmc/xbmc/issues/17328

## What is the effect on users?
EDL mute sections should be fixed in addition to 

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by FernetMenta** [comment]
Even for the sledgehammer method this change is quite hard because if flushes on every single packet. If flushing were the right solution, it should only flush when it changes state.
I don't think flushing AE is a good solution because it throws aways up to 2 seconds of audio. It should play all the audio packets already buffered.
From the description on the other PR is is not clear to me what's the observed behaviour vs the desired behaviour. No log file either (how could that happen :) ) Shooting from the hip I would think that AE's sync error gets too big when packets are dropped and this large error causes trouble when VPA moved on in STARTING state. But that is just guessing. 
Is the test file available somewhere?

**Comment by enen92** [comment]
The test file is on the original issue report: https://drive.google.com/open?id=1YBoUXXO3CcjUNgl-eg_Otsu_vwjhwtxm

**Comment by lilgandhi1199** [comment]
@FernetMenta I've edited my original thread to be clear. And there is a video you can watch of it in action.

**Comment by enen92** [comment]
@FernetMenta this looks harder than I originally though. Regarding the sample above, and taking into account just the first mute region, the correct behaviour is:

- Should start muting ~ 23.897 seconds of playback. This means the last phrase you hear from the lady is "came back 3 days ago". Should start muting right when she starts speaking again. It should unmute on 27.500secs - you hear "hope you find the (something) George.

On current master, around 24secs you still hear something after "came back 3 days ago", which is wrong according to the EDL file.

Looking at the log of current master the following happens on the first mute scene:

```
2021-11-21 18:17:52.747 T:35160   DEBUG <general>: OnAVChange: CApplication::OnAVChange
2021-11-21 18:17:52.747 T:35162   DEBUG <general>: CVideoPlayerAudio - CDVDMsg::GENERAL_RESYNC(23140608.656565), level: 49, cache: 795715.344763
2021-11-21 18:17:52.747 T:35162   DEBUG <general>: CDVDAudio::Resume - resume audio stream
2021-11-21 18:17:52.810 T:34911   DEBUG <general>: ActiveAE - start sync of audio stream
2021-11-21 18:17:52.968 T:34911   DEBUG <general>: ActiveAE::SyncStream - average error of -3.350474, start adjusting
2021-11-21 18:17:52.968 T:34911   DEBUG <general>: ActiveAE::SyncStream - average error -0.017141 below threshold of 30.000000
2021-11-21 18:17:53.094 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.983846
2021-11-21 18:17:53.158 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.982396
2021-11-21 18:17:53.221 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.980529
2021-11-21 18:17:53.253 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.979231
2021-11-21 18:17:53.316 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.975734
2021-11-21 18:17:53.379 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.973758
2021-11-21 18:17:53.443 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.969781
2021-11-21 18:17:53.506 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.965694
2021-11-21 18:17:53.569 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.961188
2021-11-21 18:17:53.601 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.960619
2021-11-21 18:17:53.664 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.957133
2021-11-21 18:17:53.696 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.955565
2021-11-21 18:17:53.759 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.952398
2021-11-21 18:17:53.791 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.950710
2021-11-21 18:17:53.854 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.949373
2021-11-21 18:17:53.917 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.947736
2021-11-21 18:17:53.949 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.947398
2021-11-21 18:17:54.012 T:34911 WARNING <general>: ActiveAE - large audio sync error: 3615.947942
2021-11-21 18:17:54.012 T:34911   DEBUG <general>: ActiveAE::SyncStream - average error 857.140572 above threshold of 100.000000
2021-11-21 18:17:54.797 T:34911   DEBUG <general>: ActiveAE::SyncStream - average error 7.140572, last average error: 857.140572
2021-11-21 18:17:54.956 T:34911   DEBUG <general>: ActiveAE::SyncStream - average error of 2765.934045, start adjusting
```
It seems `CActiveAE` is still calculating sync errors (as you pointed out in your guess) despite the player is not in sync (different states on both objects). Furthermore, I am not sure reusing `IDVDStreamPlayer::SYNC_STARTING` is the current state to put VPA on when dropping packets. If you check the logs you see VPA triggers a `PLAYER_STARTED` message which puts VPA again in `SYNC_INSYNC`, this happens here:

https://github.com/xbmc/xbmc/blob/8ab611f6b244b6f7a14fb6e14c62bac1da04578a/xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp#L534-L554

The patch on this PR doesn't solve this `GENERAL_RESYNC` issue but avoids the sync error on ActiveAE because, as the sync is empty, it returns early:

https://github.com/xbmc/xbmc/blob/719f55a5a8178430e999479f44a0693e10dd97a5/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp#L1964

Maybe we can consider something more conservative that makes sure that's only executed once in the edl mute range:

```
diff --git a/xbmc/cores/VideoPlayer/DVDMessage.h b/xbmc/cores/VideoPlayer/DVDMessage.h
index 60b248f5cb..d6207de5e4 100644
--- a/xbmc/cores/VideoPlayer/DVDMessage.h
+++ b/xbmc/cores/VideoPlayer/DVDMessage.h
@@ -54,6 +54,7 @@ public:
     PLAYER_REPORT_STATE,
     PLAYER_FRAME_ADVANCE,
     PLAYER_DISPLAY_RESET,           // report display reset event
+    PLAYER_FLUSH,
 
     // demuxer related messages
     DEMUXER_PACKET,                 // data packet
diff --git a/xbmc/cores/VideoPlayer/VideoPlayer.cpp b/xbmc/cores/VideoPlayer/VideoPlayer.cpp
index 91979aa95b..25a9aacc84 100644
--- a/xbmc/cores/VideoPlayer/VideoPlayer.cpp
+++ b/xbmc/cores/VideoPlayer/VideoPlayer.cpp
@@ -1644,6 +1644,13 @@ void CVideoPlayer::ProcessAudioData(CDemuxStream* pStream, DemuxPacket* pPacket)
     drop = true;
   else if (m_Edl.InCut(DVD_TIME_TO_MSEC(m_CurrentAudio.dts + m_offset_pts), &cut) && cut.action == EDL::Action::MUTE)
   {
+    if (m_CurrentAudio.syncState == IDVDStreamPlayer::SYNC_INSYNC)
+    {
+      m_VideoPlayerAudio->SendMessage(
+          std::make_shared<CDVDMsg>(CDVDMsg::PLAYER_FLUSH));
+    }
+
+    m_CurrentAudio.syncState = IDVDStreamPlayer::SYNC_STARTING;
     drop = true;
   }
 
diff --git a/xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp b/xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp
index c700036aa1..6cbf105cdd 100644
--- a/xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp
+++ b/xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp
@@ -380,6 +380,11 @@ void CVideoPlayerAudio::Process()
       m_messageParent.Put(
           std::make_shared<CDVDMsgType<SStateMsg>>(CDVDMsg::PLAYER_REPORT_STATE, msg));
     }
+    else if (pMsg->IsType(CDVDMsg::PLAYER_FLUSH))
+    {
+      m_audioSink.Flush();
+      CLog::Log(LOGDEBUG, "CVideoPlayerAudio - CDVDMsg::PLAYER_FLUSH");
+    }
     else if (pMsg->IsType(CDVDMsg::DEMUXER_PACKET))
     {
       DemuxPacket* pPacket = std::static_pointer_cast<CDVDMsgDemuxerPacket>(pMsg)->GetPacket();
(END)

```

However, a proper fix would be far better. Let me know if you have any ideas

**Comment by lilgandhi1199** [comment]
@enen92 "Nice girl that marry"
and it pulls back >>> "the kind that will help you find the answers george"

then on 2nd mute

"Oh stop that grunting" then it immediately pulls back the dialogue from later when she questions him "give me 1 good reason you shouldn't call on marry" and he says "Sure! Sam Wayright he's crazy about marry"

File: xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp [hunk 1]
```diff
@@ -388,6 +388,7 @@ void CVideoPlayerAudio::Process()
       if (bPacketDrop)
       {
         m_syncState = IDVDStreamPlayer::SYNC_STARTING;
+        m_audioSink.Flush();
```
Comment (FernetMenta) [inline xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp:391]: This should work. I recommend to test accurate seeks for regression.

```
      if (bPacketDrop)
      {
        pMsg->Release();
        if (m_syncState != IDVDStreamPlayer::SYNC_STARTING)
        {
          m_audioSink.Drain();
          m_audioSink.Flush();
          audioframe.nb_frames = 0;
        }
        m_syncState = IDVDStreamPlayer::SYNC_STARTING;
        continue;
      }
```

Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp]: Thanks @FernetMenta I've adjusted based on your patch. This works similar to the original code - mutes are correctly applied. Tested accurate seeks and they work as expected.

Looking at the log and playing the sample I still get the `GENERAL_RESYNC` triggered a few ms after the EDL mute started. This happens because of the `PLAYER_STARTED` being triggered in VPA (snippet of my last comment). Furthermore while playing in the second mute zone I also still get the "large audio sync error" messages.

Is the result of `DEMUXER_PACKET` reception and the actual packet output supposed to be somehow in sync? I ask this because the packet that causes the `PLAYER_STARTED` message to be sent (the first packet with a dts > than the mute zone) comes right after the mute (the playback I mean) has actually started. Likely this is the way this is supposed to work and the log messages are harmless but still, you'd be better to confirm with you before considering merging this. Wouldn't this indicate some issue with the audio clock?

Snippet of the log here: https://pastebin.com/DBTxVvEM

**Comment by FernetMenta** [comment]
> Looking at the log and playing the sample I still get the GENERAL_RESYNC triggered a few ms after the EDL mute started

That's expected behaviour because the muted section is smaller than the buffer of the demux queue. When VPA gets first dropped packet the next unmuted packet is already in the queue. VPA pulls out all dropped packet and signals resync request to VP. You could try to increase the muted section to > 10 seconds. Then I would expect some time between first drop and PLAYER_STARTED message.

**Review by a1rwulf — APPROVED** [review]
Looks good now - thx @FernetMenta for your help!
