### PR TITLE
[video] Refresh library list after changes in Info > Manage versions

### LINKED ISSUE #24378: [Video versions] Library list not updated after managing versions
### Describe the bug
Here is a clear and concise description of what the problem is:

Separate movie versions still persist in the library view after they have been managed in the versions dialog.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After managing separate versions of a movie the library view should only display a single version.

## Actual Behavior

After managing separate versions of a movie the library view they're still displayed as separate versions unless you exit the view and re-enter it.

## Possible Fix

A container refresh after closing the manage dialog might fix the issue.

### To Reproduce

1. Manage a version via the context menu or info dialog
2. Add another version
3. Exit manage dialog
4. Separate versions are still listed
5. Exit library view
6. Enter library view
7. Only one version is listed

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

2 versions of Alien:
screenshot00006
Manage versions:
screenshot00007
Both versions still displayed:
screenshot00008
Exiting and re-entering single version displayed:
screenshot00009

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CrystalP**
## Description

Added the plumbing to propagate the success status of "Add version" to the Info dialog and the library list, so that movies turned into versions are removed from the library list without having to leave/return to the library.

Refresh only when an addition was completed to avoid the unnecessary delay of a large library list refresh if the user cancels the action half-way through.

Propagation applied only to the Add version button of Manage versions because the other ones don't have impacts that could impact the library list (yet!).

## Motivation and context

Fix #24378

Version creation through the context menu didn't have the problem because the manage context menu systematically refreshes the library list.

## How has this been tested?

local and remote db, similar movie, different movie from library, movie picked with file browser.

## What is the effect on users?

Improved user experience.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CrystalP** [comment]
While this works and is straightforward, I'll revisit with an approach of sending a GUI_MSG_UPDATE_ITEM message to directly update an item, rather than reload the library list. That would be more efficient but may not be possible when removing items, we'll see.

**Comment by CrystalP** [comment]
I'm removing the "Don't merge". It cannot be done with a GUI_MSG_UPDATE_ITEM because the addition of a version removes a line from the library list. Sending a GUI_MSG_UPDATE_ITEM for an item that is not backed by the db and shouldn't be in the list anymore doesn't work.
It seems that a new message GUI_MSG_DELETE_ITEM would have to be implemented across the app first.

However the previous PR #24176 that this one builds on could be rewritten more efficiently with a GUI_MSG_UPDATE_ITEM and avoid the library refresh.

File: xbmc/video/dialogs/GUIDialogVideoInfo.h [hunk 1]
```diff
@@ -90,7 +91,7 @@ class CGUIDialogVideoInfo :
    * \param pItem Search result item
    */
   void OnSearchItemFound(const CFileItem* pItem);
-  void OnManageVideoVersions();
+  bool OnManageVideoVersions();
   void OnManageVideoExtras();
```
Comment (ksooo) [inline xbmc/video/dialogs/GUIDialogVideoInfo.h:95]: Should this be changed in the same way we changed `OnManageVideoVersions` in this PR, adding a return value and using it to refresh properly?

**Review by ksooo — APPROVED** [review]
LGTM, maybe for consistency we also should adapt refresh after extras management?

File: xbmc/video/dialogs/GUIDialogVideoInfo.h (hunk 1 above)
Comment (CrystalP) [reply xbmc/video/dialogs/GUIDialogVideoInfo.h:95]: I don't think that's needed now, with extras not exposed in the library, the refresh would never be useful.

The only situation I can think of where it would make a difference is the addition of a library item (a movie) as an extra of another movie (possible through file browser). A lack of refresh would be a minor inconvenience compared with the db corruption that would happen... I'll add a validation to avoid if there isn't one already.

If extras were displayed in a library subfolder of movies in the future, then it would make sense to add, but likely only for specific navigation and different requirements than versions.

Comment (ksooo) [reply xbmc/video/dialogs/GUIDialogVideoInfo.h:95]: Alright, understood. Then there is no need to add add this now.
