### PR TITLE
Forward Setting Changes to ApplicationVolumeHandling class

### LINKED ISSUE #21915: Replaygain settings not applied until Kodi restart
### Describe the bug
Here is a clear and concise description of what the problem is:

When user changes replaygain settings on Settings -> Player -> Music -> Volume Adjustments (advanced)
guisettings.xml is updated with proper rpg type (0/1/2) (None/Album/Track) however, the updated setting is not used when playing a song.  Restarting Kodi does use the updated setting.  This appears to be a regression from PR #21449 @notspiff

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Changing the Replaygain settings should take effect with the next playing song.  Confirmed in 20220522 nightly (prior to 21449)

## Actual Behavior

Stale replaygain settings continue to be used.

## Possible Fix

revert commit 43323255b9f130f2fe811f8dc2608430191d7adc
In testing I see that replaygain is set in CAudioDecoder GetReplayGain
That in turn calls g_application.GetReplayGainSettings()
which access some variable "quick" in GlobalHandlings.h
That variable has CApplicationVolumeHandling member m_replayGainSettings which appears to not be updated after changing settings.  That in turn gets returned to GetReplayGain resulting in wrong rpg values being calculated and used.

### To Reproduce

1. Create a song with replaygain track/track peak/album/album peak values in tags
2. Scan the track into the library 
3. Play song (default setting is to use album replaygain 1)
4. Enter settings and change player/music/ volume adjustment to use track replaygain 2
5. Play song again
6. Observe rpg data in kodi.log -- both plays use the album rpg data
7. Exit Kodi and restart
8. Play song again
9. Observe rpg data in kodi.log -- play now uses the track rpg data

### Debuglog

The debuglog can be found here:
[https://paste.kodi.tv/cufivoyahe.kodi](https://paste.kodi.tv/cufivoyahe.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Testing PR#21881

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10x64 21h1
 - Kodi version: Kodi (20.0-ALPHA3 (19.90.710) Git:20220914-7c8397512c). Platform: Windows NT x86 64-bit built in VS 2022 on Win 10 x64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by complexlogic**
## Description
The OnSettingChanged callback needs to be forwarded to the volume handling class.

## Motivation and context
Fixes #21915

## How has this been tested?
1. Play a song that is tagged with both track gain and album gain
2. Change the ReplayGain mode
3. Play the same song again
4. Verify in the ReplayGain log statement that the setting change in step 2 took effect

## What is the effect on users?
Bug fix

## Screenshots (if appropriate):
N/A

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/application/ApplicationSettingsHandling.cpp [hunk 1]
```diff
@@ -120,6 +120,9 @@ void CApplicationSettingsHandling::OnSettingChanged(const std::shared_ptr<const
   if (m_powerHandling.OnSettingChanged(*setting))
     return;
 
+  if (m_volumeHandling.OnSettingChanged(*setting))
```
Comment (notspiff) [inline xbmc/application/ApplicationSettingsHandling.cpp:123]: if you see the lines above you can identify the c&p error somebody (probably me) made a while ago. please fix that while we are at it.

Comment (complexlogic) [reply xbmc/application/ApplicationSettingsHandling.cpp:120]: Done.

**Review by garbear — APPROVED** [review]
This looks like the correct fix for the c/p error
