### PR TITLE
[Android] Check if dovi profile is supported by the codec

### LINKED ISSUE #24078: Dolby Vision doesn't work on Sony A95L
### Describe the bug
DV videos are rendered incorrectly, some with balck screen, some with funny colors.
I tried samples from demolandia.net without HDR fallback.
mediainfo: https://paste.kodi.tv/uxupadidil.
This might affect other Sony or Android TVs.

**Looks like it's because Kodi chose the wrong codec -  "c2.mtk.dvav.se.decoder" instead of "c2.mtk.dvhe.stn.decoder".**

## Expected Behavior
Video must be played in Dolby Vision mode.

## Actual Behavior
Video is not rendered properly.

## Possible Fix
Improve logic for selecting the right Android codec.

### To Reproduce
1.  Download DV video
2. Play it with Kodi
3. See the result

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/mudebiwugo.kodi

## Additional context or screenshots (if appropriate)
Initial discussion: https://forum.kodi.tv/showthread.php?tid=374979

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: BRAVIA_AE1_EU-user 12 STT2.230327.001 604070 (Android TV 12)
 - Kodi version: kodi-20231105-76e06459-master

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Similar to identifying video profiles and checking that they are supported by the device's codec capabilities.

When a video is dovi we should assign to the `profile` variable the value of the constant corresponding to the video profile of the `MediaCodecInfoCodec.ProfileLevel` class.

This variable does not affect the decoder, it's only used to check if the video profile is supported by the codec of the device.

## How has this been tested?
As my TV doesn't support dovi I can't do the tests I would like to do, any feedback is welcome.

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by quietvoid** [comment]
I've runtime tested this on my FireTV Stick 4K Max and it breaks hardware decoding for profile 7 files.
Log snippet: [kodi-snip.log](https://github.com/xbmc/xbmc/files/12234735/kodi-snip.log)

I had tried this before and gave up on it: https://github.com/xbmc/libandroidjni/pull/27#issuecomment-1005769441

**Comment by joseluismarti** [comment]
Looking at the log, profile 7 (128) is not included in the result of querying the dovi codec capabilities of this device.

If this device plays the video normally, I understand that it selects a dovi codec but does not use it and internally fallback to the hevc codec. If it works like this, we cannot discard dovi codecs when not support a profile.

**Comment by quietvoid** [comment]
> If this device plays the video normally, I understand that it selects a dovi codec but does not use it and internally fallback to the hevc codec. If it works like this, we cannot discard dovi codecs when not support a profile.

Without the profile check, the device plays profile 7 in Dolby Vision correctly.
The problem is that there's no fallback to the HEVC HW codec if all of the tested ones aren't supported, so it uses FFmpeg.

The other issue is that some users want profile 7 playback in Dolby Vision, so checking the profile won't work for them.
Other apps like Plex implemented this checking and it forces HDR10 for devices that don't support profile 7 (most of them), and as expected some users complained.

**Comment by joseluismarti** [comment]
I close this PR as the profile check has more repercussions than expected, maybe it can be used later on.

**Comment by quietvoid** [comment]
The one case where profile is necessary for Dolby Vision would be with AV1 codec.
Simply setting `m_mime` to `video/dolby-vision` ends up selecting the HEVC decoder by default, which doesn't work.

**Comment by joseluismarti** [comment]
@quietvoid now that the compatibility mode is used to play profile 7, perhaps we should incorporate the profile check to see if it solves the [issues](https://github.com/xbmc/xbmc/issues/24078) that have arisen when selecting the codec. I can't do the test on my tv, I leave it up to you.

**Comment by quietvoid** [comment]
We can't specify the profile for profile 7 unless it's conditional on the compatibility mode being enabled.
And having compatibility mode would override to profile 8 (not current behaviour).

There's still a need for a fallback to `profile = 0` to avoid ending up with software decoding.

**Comment by joseluismarti** [comment]
What do you think if we keep the profile `case` and for values 7 and 8 return `profile = 0`?

**Comment by quietvoid** [comment]
It's a good alternative.

**Comment by dbarkar** [comment]
> There's still a need for a fallback to `profile = 0` to avoid ending up with software decoding.

As a fallback, I suggest sorting codecs list so hardware codecs come first. 
That will solve the issue for Sony A95L.
It might break some other devices, so you can do it only for Dolby Vision and only if profile is not set.

**Comment by joseluismarti** [comment]
After testing, it seems to be a good idea to activate also the case for profile 8, I will modify it.

**Comment by joseluismarti** [comment]
This PR fixes the issue described in #24078 for profiles 5 and 8.

Ensures that the selected codec is compatible with the profile of the video to be played.

**Comment by thexai** [comment]
Tested on Shield, no regressions found. Tested various DV profiles and containers:

- P4 mkv
- P5 mkv, mp4
- P7 mkv
- P8 mkv, mp4

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp [hunk 1]
```diff
@@ -548,6 +548,50 @@ bool CDVDVideoCodecAndroidMediaCodec::Open(CDVDStreamInfo &hints, CDVDCodecOptio
...
+                profile = CJNIBase::GetSDKVersion() >= 27
+                              ? CJNIMediaCodecInfoCodecProfileLevel::DolbyVisionProfileDvheSt
+                              : 0;
+                break;
+              case 9:
+                profile = CJNIBase::GetSDKVersion() >= 27
+                              ? CJNIMediaCodecInfoCodecProfileLevel::DolbyVisionProfileDvavSe
+                              : 0;
+                break;
+              default:
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:590]: default case seems redundant as profile is initially set to 0 and all for all cases NOT handled remains 0 anyway

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp [hunk 2]
```diff
@@ -548,6 +548,50 @@ bool CDVDVideoCodecAndroidMediaCodec::Open(CDVDStreamInfo &hints, CDVDCodecOptio
...
+                profile = CJNIMediaCodecInfoCodecProfileLevel::DolbyVisionProfileDvheStn;
+                break;
+              case 6:
+                profile = CJNIMediaCodecInfoCodecProfileLevel::DolbyVisionProfileDvheDth;
+                break;
+              case 7:
+                profile = 0; // DolbyVisionProfileDvheDtb
+                break;
+              case 8:
+                profile = CJNIBase::GetSDKVersion() >= 27
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:581]: Maybe:

```c++
if (CJNIBase::GetSDKVersion() >= 27)
  profile = CJNIMediaCodecInfoCodecProfileLevel::DolbyVisionProfileDvheSt;
```

Seems more clear and 0 is not necessary set because is the "default".

Comment (joseluismarti) [reply xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:581]: Right, I make the changes

**Review by thexai — APPROVED** [review]

**Comment by thexai** [comment]
Jenkins build this please

**Comment by thexai** [comment]
TVOS build error is unrelated
