### PR TITLE
[addons] CGUIDialogAddonInfo: Fix add-on status not updated when enab…

### LINKED ISSUE #25696: [GUI] Addon Status not updated on info screen when enabled/disabled
### Describe the bug
Here is a clear and concise description of what the problem is:

Go to the info screen of an addon, and try enable/disable it, the list info "Status" is not updated

Addon is disabled
immagine
then switched to enabled, still show as disabled on the info list "Status"
immagine

affected both Kodi 21 and 22

### To Reproduce

1. open addon info
2. switch enable/disable button
3. see the info list text dont change

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/igotusirux.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Last Kodi 22 nightly, and Kodi 21 release

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
…ling/disabling the add-on.

## Description

When enabling or disabling an add-on using the respective add-on info dialog button, the add-on status info displayed in the dialog is not updated. The PR fixes this bug. 

## Motivation and context

Provide correct add-on status in the info dialog at any time.

## How has this been tested?

By looking at the screen after applying the patch. :-)

## What is the effect on users?

Correct add-on status in the info dialog at any time.

## Screenshots (if appropriate):
Screenshot 2025-09-19 at 00 09 36

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Review by neo1973 — APPROVED** [review]

File: xbmc/addons/gui/GUIDialogAddonInfo.cpp [hunk 1]
```diff
@@ -610,15 +610,17 @@ void CGUIDialogAddonInfo::OnEnableDisable()
...
   else
   {
     // Check user want to enable if lifecycle not normal
     if (!ADDON::GUI::CHelpers::DialogAddonLifecycleUseAsk(m_localAddon))
       return;
 
-    CServiceBroker::GetAddonMgr().EnableAddon(m_localAddon->ID());
+    if (CServiceBroker::GetAddonMgr().EnableAddon(m_localAddon->ID()))
+      m_item->SetProperty("Addon.Status", g_localizeStrings.Get(305)); // Enabled
   }
```
Comment (garbear) [inline xbmc/addons/gui/GUIDialogAddonInfo.cpp:624]: What about instead, after the if statement, having a single statement:

```c++
bool enabled = CServiceBroker::GetAddonMgr().IsEnabled(m_localAddon->ID());
m_item->SetProperty("Addon.Status", enabled ?
    g_localizeStrings.Get(305) : // Enabled
    g_localizeStrings.Get(24023)); // Disabled
```

Because whatever the result of the block, we want the add-on status to be correct. Similar to the approach of "verify the invariant".

Comment (ksooo) [reply xbmc/addons/gui/GUIDialogAddonInfo.cpp:624]: Not really. Theoretically,  the current addon-on status can be something different from enabled/disabled, if I understand the code setting the property elsewhere correctly. So, my idea was to touch the status only if the operation supposed to change the status was successful, otherwise keep the previous status whatever it was.

Comment (garbear) [reply xbmc/addons/gui/GUIDialogAddonInfo.cpp:624]: Then good as is.

**Review by garbear — APPROVED** [review]
