### PR TITLE
DVDDemuxFFmpeg: Fix issues after st->cur_pts replacement part 3

### LINKED ISSUE #23712: [Windows] Seeking broken on certain files
### Describe the bug
Here is a clear and concise description of what the problem is:
Seeking seems to be broken for me on Windows since last week (only on some files). I build myself with latest PRs every few days. At first I thought it was just MP4 files but in testing I've found that some MP4 files work just fine so I'm not sure if it's the codec being used or what. This morning I did a test with some files that are basically the same video just different containers/formats. The MP4 files were working fine and the MKV container was causing the videoplayer to essentially crash on seeking with log message "CDVDMsgGeneralSynchronize - global timeout". Not sure if it's related but I noticed Kodi is not extracting thumbs on the files where seeking is also broken.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
I have a build from Aug 20, 2023 that is working fine. Issue seems to have started since the PR relating to ifdef #23634  but of course I don't want to blame this PR specifically.

## Actual Behavior
On certain files, seeking forward/backward will cause indefinite "Buffering..." and/or videplayer crash back to Kodi menu.

## Possible Fix
I'm sorry I'm not that smart

### To Reproduce
1.  Sample files I used here https://filesamples.com/formats/mkv and https://filesamples.com/formats/avi
2.  Find some files where thumbnails won't load and try step forward/back during playback.
3.  HDR Autoswitch enabled, VSR enabled, HPP enabled

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/nebumoyisa.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:
Not able to screenshot while videoplayer is crashing due to screen reset event

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11 Pro Version 10.0.22631 Build 22631
 - Kodi version: 21.0-ALPHA2 (20.90.201) Git:20230901-bf184b9184
 - Intel i7, RTX 3080 Ti, 32GB RAM
 - Samsung 8k OLED TV

### PR DESCRIPTION
**Pull request by popcornmix**
## Description

Avoid stalls after seeking introduced by https://github.com/xbmc/xbmc/pull/23629

## Motivation and context
See: https://github.com/xbmc/xbmc/issues/23673

## How has this been tested?

Tested on Pi 4 in a LibreELEC build using video provided in linked issue

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
@thexai can you test your use case

**Comment by thexai** [comment]
Yes, tested several h264 and h265 files and seek issues are resolved in all cases until now. 

Seems a good fix 🙂

**Comment by fuzzard** [comment]
@enen92 if you find a minute, just want to confirm your pvr stuff is all good as well still

**Comment by enen92** [comment]
I'll only be able to provide feedback later today (worst case scenario tomorrow morning)

**Comment by enen92** [comment]
Yes, still works fine for my use case (hdhomerun)

**Comment by fritsch** [comment]
Looks good for me - idea wise, definitely. I know that fernet does not like (default) bool parameters too much, as they are the start of a parameter driven design that no one understands anymore after a certain point was reached. Here in this case a potential refactoring towards a Read vs. Peak vs. WhateverACamelCanThinkOffMethod ... can be done any time, if needed at all.

**Comment by fritsch** [comment]
For the PTS change, here I don't have yet a full opinion, reason is - I am wondering where the PTS should come from when the DTS is not yet known / valid, also wondering how that would come in that combination from a demuxer.

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp [hunk 1]
```diff
@@ -1177,13 +1177,19 @@ DemuxPacket* CDVDDemuxFFmpeg::Read()
           if (pPacket->dts != DVD_NOPTS_VALUE &&
               (pPacket->dts > m_currentPts || m_currentPts == DVD_NOPTS_VALUE))
             m_currentPts = pPacket->dts;
+          else if (pPacket->pts != DVD_NOPTS_VALUE &&
+              (pPacket->pts > m_currentPts || m_currentPts == DVD_NOPTS_VALUE))
+            m_currentPts = pPacket->pts;
```
Comment (FernetMenta) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:1182]: That should be dts. Pts is not monotonic at this stage

**Comment by stumpalump** [comment]
I can confirm this fixes both issues I listed in #23712 with thumbnail extraction and seeking.

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp (hunk 1 above)
Comment (popcornmix) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:1182]: Without this we discard video I frames, which causes large stalls.
How about we only update from pts when `m_currentPts == DVD_NOPTS_VALUE`?

```
          else if (pPacket->pts != DVD_NOPTS_VALUE && m_currentPts == DVD_NOPTS_VALUE))
            m_currentPts = pPacket->pts;
```

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp [hunk 2]
```diff
@@ -1243,6 +1249,11 @@ DemuxPacket* CDVDDemuxFFmpeg::Read()
   return pPacket;
 }
 
+DemuxPacket* CDVDDemuxFFmpeg::Read()
+{
+  return ReadInternal(false);
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:1254]: What about keeping a boolean state member variable to specify if the packet should be kept or not instead of adding the bool to the argument? Should only be a matter of setting it to true before calling read I guess

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp (hunk 1 above)
Comment (FernetMenta) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:1182]: Sorry, only had a a smartphone yesterday. You added pts as fallback if dts is not set. This is perfectly fine. Sorry for the noise.

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp (hunk 2 above)
Comment (fritsch) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:1254]: I would not do that: Reason, you will always need two function calls. From API usage this complicates things. I would keep it as is.

If stuff should be really obvious. Adding and additional Peek() method would be my choice, so it is clear that Read does Pop while Peek does peek or something.

Also I think, can easily be a follow up.

**Comment by fuzzard** [comment]
Cheers again @popcornmix i'll merge this for now, and fingers crossed we dont need a part 4 :)
