### PR TITLE
Games: Fix playing m3u files for multi-disc games

### LINKED ISSUE #24068: Kodi crashes when opening m3u file in Games section
### Describe the bug
Here is a clear and concise description of what the problem is:

When I try to open any m3u file from the Games window Kodi crashes immediately.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi plays the game (in case of a multi-disc game playlist) or throws an error (in case of music or video playlist). I'm aware that the libretro multi-disc support is not implemented yet, but it can at least open the first item from the playlist or throw an error instead of crashing.

## Actual Behavior

Kodi crashes.

## Possible Fix

Even without the full multi-disc support in place Kodi could pass the whole playlist to the libretro as the Retroarch is doing it. The first disc is loaded and the savestates are named after the playlist file instead of the disc image file. This way the savestates are not specific for every disc, but shared across them. The disc changing function can be added later.

### To Reproduce

1. Go to Games -> Files -> find any m3u file.
2. Open the m3u file.
3. Kodi crashes.

### Debuglog

The debuglog can be found here:
The log ends by the pressing of the Select button:
```
2023-11-07 19:22:39.838 T:7597    debug <general>: PushCecKeypress - received key a7 duration 106
2023-11-07 19:22:40.059 T:7597    debug <general>: PushCecKeypress - received key a7 duration 0
2023-11-07 19:22:40.062 T:7562    debug <general>: HandleKey: 167 (0xa7, obc88) pressed, window 10821, action is Down
2023-11-07 19:22:40.167 T:7597    debug <general>: PushCecKeypress - received key a7 duration 107
2023-11-07 19:22:40.442 T:7597    debug <general>: PushCecKeypress - received key a7 duration 0
2023-11-07 19:22:40.445 T:7562    debug <general>: HandleKey: 167 (0xa7, obc88) pressed, window 10821, action is Down
2023-11-07 19:22:40.550 T:7597    debug <general>: PushCecKeypress - received key a7 duration 108
2023-11-07 19:22:40.830 T:7597    debug <general>: PushCecKeypress - received key a7 duration 0
2023-11-07 19:22:40.845 T:7562    debug <general>: HandleKey: 167 (0xa7, obc88) pressed, window 10821, action is Down
2023-11-07 19:22:40.936 T:7597    debug <general>: PushCecKeypress - received key a7 duration 107
2023-11-07 19:22:43.134 T:7597    debug <general>: PushCecKeypress - received key  b duration 0
2023-11-07 19:22:43.886 T:7597    debug <general>: PushCecKeypress - received key  b duration 108
2023-11-07 19:22:43.895 T:7562    debug <general>: HandleKey: 11 (0xb, obc244) pressed, window 10821, action is Select
2023-11-07 19:22:43.895 T:7685    debug <general>: Thread GUIDialogCache start, auto delete: true
2023-11-07 19:22:43.895 T:7686    debug <general>: Thread waiting start, auto delete: false

############### END LOG FILE ################

############ END kodi CRASH LOG #############

```

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I've tested this on Windows and LibreELEC (both x86 and ARM) and even on the Omega beta1. Also it seems to NOT depend on the content of the m3u file at all.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [X] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 11
 - Kodi version: 20 and 21

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by garbear**
## Description

Currently Kodi crashes when playing m3u files (multi-disk game lists) from the My Games window. This PR fixes the crash, and allows m3u files to be played. Along with the Disc Manager in https://github.com/xbmc/xbmc/pull/27984, m3u files can be disc-swapped as well.

It also fixes the directory-existence check for directories that end in ".m3u". These folders are created for savestates, named after the game's filename.

Note that this PR just bypasses the segfault. The correct fix for the segfault is in https://github.com/xbmc/xbmc/pull/27990.

Also note, there are a myriad of ways to play files, some of which lose "gameness" context. I hacked the code for the worst-case scenario of no context beyond the path, and Kodi falls back to playing the first file in the m3u. In this case, the remaining files can be added manually in the Disc Manager. But note this is worst-case playback scenario

## Motivation and context

Fixes https://github.com/xbmc/xbmc/issues/24068

## How has this been tested?

To be included in upcoming test builds.

Tested with the following `Metal Gear Solid (Europe).m3u` file:

```
Metal Gear Solid (Europe) (Disc 1)/Metal Gear Solid (Europe) (Disc 1).cue
Metal Gear Solid (Europe) (Disc 2)/Metal Gear Solid (Europe) (Disc 2).cue
```

Before:

Kodi go boom

After:

Kodi correctly plays the m3u as a game:

Screenshot 2026-03-12 at 1 00 58 PM

Savestates are associated with the m3u file:

Screenshot 2026-03-12 at 12 45 51 PM

With the Disc Manager, the disc list is correctly populated from the core, after it loads the m3u directly:

Screenshot 2026-03-12 at 12 46 16 PM

## What is the effect on users?

* Fixed playing m3u files from the My Games window

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by garbear** [comment]
@kodiai please review after the consistency improvement

**Comment by garbear** [comment]
@kodiai classify risk of adding a bunch of "isgame"s and also the hit when creating a directory thing

**Comment by garbear** [comment]
It looks like the extra directory check in the file loading path isn't very expensive.

**Comment by garbear** [comment]
Been playing from m3u the last week, this should be good to go.

Screenshot 2026-03-18 at 10 40 30 AM

File: xbmc/filesystem/DirectoryFactory.cpp [hunk 1]
```diff
@@ -121,7 +126,21 @@ IDirectory* CDirectoryFactory::Create(const CURL& url)
...
+  struct __stat64 st = {};
+  if (CFile::Stat(URIUtils::SubstitutePath(url), &st) == 0)
+  {
+    item.SetFolder(S_ISDIR(st.st_mode));
+    canBeFileDirectory = !item.IsFolder();
+  }
+
+  IFileDirectory* pDir = nullptr;
+  if (canBeFileDirectory)
+    pDir = CFileDirectoryFactory::Create(url, &item);
```
Comment (ksooo) [inline xbmc/filesystem/DirectoryFactory.cpp:143]: @garbear This change creates serious log spam during startup of Kodi and later:

```log
...
2026-04-15 11:14:37.184 T:2839  warning <general>: CreateLoader - unsupported protocol(addons) in addons://
2026-04-15 11:14:37.244 T:2868  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/video/
2026-04-15 11:14:37.250 T:2868  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/audio/
2026-04-15 11:14:37.258 T:2868  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/game/
2026-04-15 11:14:37.259 T:2868  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/executable/
2026-04-15 11:14:37.270 T:2847  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/image/
2026-04-15 11:14:37.316 T:2847  warning <general>: CreateLoader - unsupported protocol(sources) in sources://video/
2026-04-15 11:14:37.345 T:2847  warning <general>: CreateLoader - unsupported protocol(favourites) in favourites://
2026-04-15 11:14:37.519 T:2847  warning <general>: CreateLoader - unsupported protocol(sources) in sources://pictures/
...
2026-04-15 11:14:48.379 T:2839  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/video/
2026-04-15 11:14:48.404 T:2839  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/audio/
2026-04-15 11:14:48.406 T:2839  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/game/
2026-04-15 11:14:48.407 T:2839  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/executable/
2026-04-15 11:14:48.411 T:2839  warning <general>: CreateLoader - unsupported protocol(addons) in addons://sources/image/
2026-04-15 11:14:48.411 T:2839  warning <general>: CreateLoader - unsupported protocol(addons) in addons://
...
```
 
Image

File: xbmc/filesystem/DirectoryFactory.cpp [hunk 2]
```diff
@@ -121,7 +126,21 @@ IDirectory* CDirectoryFactory::Create(const CURL& url)
...
 
   CFileItem item(url.Get(), true);
-  IFileDirectory* pDir = CFileDirectoryFactory::Create(url, &item);
+
+  // Load directory flag from the VFS. If the url is truly a directory, don't
+  // attempt to use a file-directory loader.
+  bool canBeFileDirectory = true;
+
+  struct __stat64 st = {};
+  if (CFile::Stat(URIUtils::SubstitutePath(url), &st) == 0)
```
Comment (78andyp) [inline xbmc/filesystem/DirectoryFactory.cpp:135]: This block also breaks UPNP browsing. See #28159.

Comment (garbear) [reply xbmc/filesystem/DirectoryFactory.cpp:135]: OK, We'll likely need an opt-in for protocols for hard stats. I can't look into this until I've set up my dev laptop again, currently on macOS 13 which can't build latest Kodi.

Comment (78andyp) [reply xbmc/filesystem/DirectoryFactory.cpp:135]: If I change it to:
```
  if (!URIUtils::IsUPnP(item.GetPath()) && CFile::Stat(URIUtils::SubstitutePath(url), &st) == 0)
  {
    item.SetFolder(S_ISDIR(st.st_mode));
    canBeFileDirectory = !item.IsFolder();
  }
```
it works fine - but not sure that's the correct fix.

Comment (garbear) [reply xbmc/filesystem/DirectoryFactory.cpp:135]: This looks like the right approach. Condition the execution of a stat depending on the protocol, either opt-in or opt-out. Your UPnP change would be opt-out, for example.

Comment (78andyp) [reply xbmc/filesystem/DirectoryFactory.cpp:135]: Do you want me to do a PR??

Comment (garbear) [reply xbmc/filesystem/DirectoryFactory.cpp:135]: Yeah, as I won't be able to until I get my dev laptop setup again. Maybe we can put some thought into the allow/block protocol lists to fix https://github.com/xbmc/xbmc/pull/27989#discussion_r3085455728 too.
