### PR TITLE
[INFO] Add ListItem.Property(WatchedEpisodePercent) for tvshows

### LINKED ISSUE #21543: Skins cannot retrieve percentage of tvshow watched
### Describe the bug
Skins are unable to display a progress control to provide a visual indication of the percentage of episodes watched in a tvshow or season as there is no appropriate infolabel for this data.

Currently, skins can only display the _number_ of unwatched or watched episodes. As a result, the user must read two different points of data and then do math to figure out how much of an in-progress tvshow that they have watched.

Visual indications would improve the user experience by allowing the user to see this progress information at a glance.

## Expected Behavior
Skins are able to display a visual indication of watched progress for tvshows and seasons via an infolabel.

## Actual Behavior
There is no 0-100 infolabel for this data.

## Possible Fix
A new 0-100 progress infolabel which contains `int(watchedepisodes / totalepisodes * 100)`

### Additional context
See the below screenshot where I have mocked up this behaviour using Arctic Horizon 2 and TMDb Helper. I am outputting this data to a property `ListItem.Property(WatchedProgress)` and then reading it in the skin. 

You should be able to see from this live mock-up how useful this progress indicator is. I have 11 episodes left to watch for both Fresh Off the Boat and Dark. Because FotB has 116 episodes but Dark has only 26, you can see the significantly different progress despite both having 11 episodes left. I'm only a little over half way through my re-watch of Dark but I've almost finished FotB.

screenshot00112

### PR DESCRIPTION
**Pull request by enen92**
## Description
Sounded quite easy to implement and was requested by one of our team skinners - this adds `ListItem.Property(WatchedEpisodePercent)` for tvshows so the skin can display the percentage of watched episodes/show.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/21543

## How has this been tested?
In estuary:
```
diff --git a/addons/skin.estuary/xml/Variables.xml b/addons/skin.estuary/xml/Variables.xml
index d875941d08..46f49557d6 100644
--- a/addons/skin.estuary/xml/Variables.xml
+++ b/addons/skin.estuary/xml/Variables.xml
@@ -79,7 +79,7 @@
                <value>$INFO[ListItem.Label]</value>
        </variable>
        <variable name="ListLabel2Var">
-               <value condition="String.IsEmpty(Container.PluginName) + Container.Content(tvshows) + Container.SortMethod(29)">$INFO[ListItem.Property(WatchedEpisodes)]$INFO[ListItem.Property(TotalEpisodes), / ,]</value>
+               <value condition="String.IsEmpty(Container.PluginName) + Container.Content(tvshows) + Container.SortMethod(29)">$INFO[ListItem.Property(watchedepisodepercent)]%</value>
                <value condition="Container.SortMethod(7) | Container.SortMethod(29)">$INFO[ListItem.Year]</value>
                <value condition="!String.isempty(ListItem.Appearances)">$LOCALIZE[38026]: $INFO[ListItem.Appearances]</value>
                <value condition="Window.IsActive(musicplaylist) | Window.IsActive(videoplaylist)">$INFO[ListItem.Duration]</value>
```
Screenshot from 2022-06-26 16-20-26

Screenshot from 2022-06-26 16-20-40

## What is the effect on users?
If the skin takes advantage of it, a percentage mark can be shown in the skin for the several tvshows.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [x] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by enen92** [comment]
@jurialmunkey testbuild here: https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220626-5c3cf9c6-watched_episode_percent-x64.exe

File: xbmc/video/VideoDatabase.cpp [hunk 1]
```diff
@@ -4132,6 +4132,7 @@ CVideoInfoTag CVideoDatabase::GetDetailsForTvShow(const dbiplus::sql_record* con
     item->SetProperty("numepisodes", details.m_iEpisode); // will be changed later to reflect watchmode setting
     item->SetProperty("watchedepisodes", details.GetPlayCount());
     item->SetProperty("unwatchedepisodes", details.m_iEpisode - details.GetPlayCount());
+    item->SetProperty("watchedepisodepercent", (details.GetPlayCount() * 100 / details.m_iEpisode));
```
Comment (howie-f) [inline xbmc/video/VideoDatabase.cpp:4135]: should this be generally casted to int, since CVariant can take floats and doubles? just for safety, rounding issues etc.

Comment (howie-f) [reply xbmc/video/VideoDatabase.cpp:4135]: disregard, shouldn‘t matter as only int‘s involved

Comment (enen92) [reply xbmc/video/VideoDatabase.cpp:4135]: the division is inverted (multiplication by 100) to avoid precisely that otherwise we'd get a 0% if you watched 1 episode out of 3 since only ints are involved

Comment (garbear) [reply xbmc/video/VideoDatabase.cpp:4135]: One thing to consider is that we use floor division here. If there are 1000 episodes, and the user watches 9, it'll say 0%, even though it's closer to 1%. However, I think this is OK, becuase we actually *want* this behavior at the other end - the user doesnt want to see 100% if they've watched 999/1000, they want to see 99% to show that there's still one left. So I think flooring is OK for this property.

**Review by howie-f — APPROVED** [review]
nice feature

**Comment by jurialmunkey** [comment]
Appears to be working as expected. I tested the two main approaches to displaying a GUI progress indicator and both worked well: (1) a `progress` control; and (2) a folder of textures ranging from 0.png to 100.png
```
<control type="progress">
<info>ListItem.Property(watchedepisodepercent)</info>
</control>
```

```
<control type="image">
<texture>$INFO[ListItem.Property(watchedepisodepercent),indicator/progress/,.png]</texture>
</control>
```

Here's circle indicator in action:
Honeyview_screenshot00134


BTW, not sure if it is related, but `.strm` files in the library appear to crash this build of Nexus. Normally I would use `.strm` to create a fake library for testing purposes but in this case I couldn't and had to make a library containing *only* real video files. As soon as I scanned even a single `.strm`, loading the library window would cause Kodi to crash.

**Comment by enen92** [comment]
@jurialmunkey can you open a new issue for the storm file crash and append a crashlog?
Certainly unrelated to this change

**Comment by jurialmunkey** [comment]
> @jurialmunkey can you open a new issue for the storm file crash and append a crashlog? Certainly unrelated to this change

@enen92 - Here you go https://github.com/xbmc/xbmc/issues/21619

I thought it was specifically shows with `.strm`  files but after a bit more testing I'm fairly certain I've isolated the issue to empty shows with no episodes used as placeholders for upcoming shows -  i.e. a folder with only poster and .nfo but no actual episodes.

Might be related to this after all e.g. divide by zero error?

**Comment by realcopacetic** [comment]
hi @enen92 - in the code it states "currently selected tvshow or season\,"

This is working great for tvshows, but for season containers I get an empty string using ListItem.Property(WatchedEpisodePercent) using the latest nightly - https://mirrors.kodi.tv/nightlies/windows/win64/master/KodiSetup-20220629-30fb576e-master-x64.exe

**Comment by enen92** [comment]
Yeap this is only available at tvshow scope, not seasons. Can be added though.

**Comment by realcopacetic** [comment]
@enen92 I would really appreciate having this at season level as well. 

My skin Copacetic is currently reliant on the emburary skin helper to do the calculation, but that means it needs to be triggered with a hidden button, and there's a calculation delay, so it gets quite messy. It would be great to remove all that code with a native ListItem property that works for seasons as well as tv shows.

**Comment by realcopacetic** [comment]
thanks!

**Comment by HitcherUK** [comment]
@enen92 can this also be made available in the video information dialog please?

**Comment by enen92** [comment]
isn't it available already?

**Comment by HitcherUK** [comment]
Sorry, my mistake I had a visible condition hiding it when testing with a progress bar.
