### PR TITLE
[PlayListPlayer] Fixed wrong player playlist with playlist files

### LINKED ISSUE #17915: Json RPC "Player.GetProperties" missing data - strange behaviour
### Describe the bug
Here is a clear and concise description of what the problem is:

I have Netflix add-on installed on latest Kodi 19 nightly
i have exported some tvshows and enabled kodi scraper to the exported folder
(all exported files are STRM that point to add-on to play a video with inputstreamadaptive)

now i trying to play the episodes from Tv Show menu but from "Recentry added episodes" section:
image

but the RPC Json `Player.GetProperties` return partial data
and happen only if you try to play a video from Recentry added episodes screen

i use these properties: (player id is taken in realtime so it is exactly)
```python
            player_state = common.json_rpc('Player.GetProperties', {
                'playerid': self.active_player_id or player_id,
                'properties': [
                    'audiostreams',
                    'currentaudiostream',
                    'currentvideostream',
                    'subtitles',
                    'currentsubtitle',
                    'subtitleenabled',
                    'percentage',
                    'time']
            })
```

In my tests json rpc call return always this,
so many data are missing: `currentsubtitle`, `currentvideostream`, `subtitles`
<pre>
{
    'audiostreams': [{
            'bitrate': 131072,
            'channels': 2,
            'codec': 'aac',
            'index': 0,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'ger',
            'name': 'AAC ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 1,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'ger',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'eac3',
            'index': 2,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': True,
            'language': 'eng',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 3,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': True,
            'language': 'eng',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'aac',
            'index': 4,
            'isdefault': False,
            'isimpaired': True,
            'isoriginal': False,
            'language': 'eng',
            'name': 'AAC ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 5,
            'isdefault': False,
            'isimpaired': True,
            'isoriginal': False,
            'language': 'eng',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'eac3',
            'index': 6,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'fre',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 7,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'fre',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 8,
            'isdefault': True,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'ita',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'aac',
            'index': 9,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'ita',
            'name': 'AAC ',
            'samplerate': 0
        }, {
            'bitrate': 131072,
            'channels': 2,
            'codec': 'eac3',
            'index': 10,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'rum',
            'name': 'DD+ ',
            'samplerate': 0
        }, {
            'bitrate': 655360,
            'channels': 6,
            'codec': 'eac3',
            'index': 11,
            'isdefault': False,
            'isimpaired': False,
            'isoriginal': False,
            'language': 'rum',
            'name': 'DD+ ',
            'samplerate': 0
        }
    ],
    'currentaudiostream': {
        'bitrate': 655360,
        'channels': 6,
        'codec': 'eac3',
        'index': 8,
        'isdefault': True,
        'isimpaired': False,
        'isoriginal': False,
        'language': 'ita',
        'name': 'DD+ ',
        'samplerate': 0
    },
    'currentsubtitle': None,
    'currentvideostream': None,
    'percentage': 0.021548116579651833,
    'subtitleenabled': False,
    'subtitles': [],
    'time': {
        'hours': 0,
        'milliseconds': 309,
        'minutes': 0,
        'seconds': 0
    },
    'elapsed_seconds': 0
}
</pre>

if i try to play by browsing folders data are right
if try to play by  browsing add-on folders data are right

UPDATE:
the problem happen also when you not set a video screaper to folder
and try to play a video

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

return all video data of played video

## Actual Behavior

missing: `currentsubtitle`, `currentvideostream`, `subtitles`

### To Reproduce

1. Install netflix 
2. export a season
3. play from Kodi menu page Tv shows , "Recentry added episodes" section

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/nozawicatu.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 19, 20 nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

The old PR https://github.com/xbmc/xbmc/pull/11747
has changed the way in how the playlist type is set
by moving all code in one method: `CPlayListPlayer::Play` where now the type is detected by using `IsAudio`/`IsVideo `methods
but this change however, led to a regression with playlist files like STRM, M3U, ...

the strm is an extension set in both audio and video extensions lists,
therefore when you test for `IsAudio`/`IsVideo `this will return true on both methods:
https://github.com/xbmc/xbmc/blob/master/xbmc/PlayListPlayer.cpp#L260-L273
since both methods return true, only the first one is taken in account `IsAudio`
therefore set a wrong playlist, with further repercussions
on the JSON-RPC calls by returning missing/wrong data due to wrong playlist set
such as:
`Player.GetProperties`
`Player.GetActivePlayers`
becoming unusable for addons from first version of Kodi 19 (not sure about Kodi 18)

Then this PR restore the old hint value for playlist type that has been removed,
and that will be used as fallback only when `IsAudio`/`IsVideo` both return true as happens with strm

**A secondary use case fix**
is when you use `Play from here` context menu when you have opened a STRM file that contains more than one links

in this case the video is played from `CGUIMediaWindow::OnPlayAndQueueMedia`
but the playlist set/returned from here https://github.com/xbmc/xbmc/blob/master/xbmc/windows/GUIMediaWindow.cpp#L1512 is wrong. Use `Play from here` from a multiple links STRM is not so popular, therefore is possible that no one complained over the time, this code has never changed in more than 10 years, this is the reason of my changes in `xbmc/view/GUIViewState.cpp`

If possible need to be backported

## Motivation and context

Fix #17915

## How has this been tested?

call JSON RPC `Player.GetActivePlayers`  and see the player id when you play a strm video must be "1"
call JSON RPC `Player.GetProperties` and check if `currentsubtitle`, `currentvideostream`, `subtitles` data fields exists
more info in the Issue

## What is the effect on users?

Have a working JSON RPC response when you play videos with STRM/M3U files

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by enen92 — COMMENTED** [review]
Thinking a bit about this, instead of reintroducing the argument (which is pretty ugly if you ask me) why not use a listitem property on the item itself (if not already defined) and use that for decision later? Or even keeping everything as is he current and use the property to override the behaviour...
I believe this mostly affects plugin content right? Or playlists resolving to plugin:// VFS paths.

**Comment by CastagnaIT** [comment]
take in consideration that this problem will happens for each file extension that has been added (or will be added) on both extensions lists (audio / video) https://github.com/xbmc/xbmc/blob/master/xbmc/settings/AdvancedSettings.cpp#L438-L439

so another example is `.pls` extension, is set on both lists, and will have same problem

then if we add a new listitem property, there are some critical points:

- The file type must have the possibility to add the new property e.g. `#KODIPROP:PlaylistType=video` as text inside the file itself, for STRM/M3U case its ok, but other file format types may not be so (.pls ?).
- I have the suspect that the loading of STRM/M3U file content happens after all this stage, need to be checked, if so it cannot be done so easily
- Many users have huge catalogues of STRM files (tvshows + each episode of each seasons ...etc, hundreds of files and more) therefore each addon-dev have to apply a change to all the hundreds of files of each kodi user, which is not acceptable, each addon will have to create a script to modify all the STRM/M3U of each user to add this new property, so this could be ok if we want to make a transition for Kodi 20 (but this lead to last point)
- This will be a kind of new feature to workaround a regression, but for kodi 20, a backport will be not allowed and Kodi 19 and still be broken, i would like a common solution that can be improved

IMO i would be inclined to still include this regression fix that reitroduce the old behaviour,
this will give the possibility to fix Kodi 19,
then for Kodi 20 we can think to add a new property that allow override the playlist, if it is possible to do so...

**Comment by enen92** [comment]
Sure but still...the item is propagated throughout the chain, you could well define a property on the playlist fileitem to provide the hint without having to overload existing method implementations.

**Comment by CastagnaIT** [comment]
i digged more, so manage a "public" override listitem proprerty (#KODIPROP) is not so easy, need to be reworked a lot of things to make playlist created in a different way

however i have removed the overload as suggested, and also i found another bug for a similar use case with context menu, i updated the PR description so you can be read above

File: xbmc/video/windows/GUIWindowVideoBase.cpp [hunk 1]
```diff
@@ -1184,11 +1184,13 @@ bool CGUIWindowVideoBase::OnPlayAndQueueMedia(const CFileItemPtr& item, const st
   return CGUIMediaWindow::OnPlayAndQueueMedia(movieItem, player);
 }
 
-void CGUIWindowVideoBase::PlayMovie(const CFileItem *item, const std::string &player)
```
Comment (enen92) [inline xbmc/video/windows/GUIWindowVideoBase.cpp:1187]: this is a bad sign. Play should play and keep the item as is (so const). Please check where this is called and set the property there

Comment (CastagnaIT) [reply xbmc/video/windows/GUIWindowVideoBase.cpp:1187]: done

File: xbmc/PlayListPlayer.cpp [hunk 2]
```diff
@@ -258,13 +258,23 @@ bool CPlayListPlayer::PlaySongId(int songId)
...
 {
   int playlist;
-  if (pItem->IsAudio())
+  bool isVideo{pItem->IsVideo()};
+  bool isAudio{pItem->IsAudio()};
+  if (isVideo && isAudio && pItem->HasProperty("playlist_type_hint"))
+  {
+    // If an extension is set in both audio / video lists (e.g. playlist .strm),
+    // is not possible detect the type of playlist then we rely on the hint
+    playlist = pItem->GetProperty("playlist_type_hint").asInteger32();
```
Comment (enen92) [inline xbmc/PlayListPlayer.cpp:267]: probably this needs to be validated before calling `.asInteger32()`? I.e. plugin authors may set that property to some random string. What happens in that case?
I've not checked the implementation of the `.asInteger32()` though so it might be fine already. Please double check if possible.

File: xbmc/view/GUIViewState.cpp [hunk 3]
```diff
@@ -101,7 +101,15 @@ CGUIViewState* CGUIViewState::GetViewState(int windowId, const CFileItemList& it
     return new CGUIViewStateLibrary(items);
 
   if (items.IsPlayList())
-    return new CGUIViewStateMusicPlaylist(items);
+  {
+    // Playlists (like .strm) can be music or video type
+    // we set the playlist type based on the current
+    // GUI NAV window, otherwise fallback to general
+    if (windowId == WINDOW_VIDEO_NAV)
```
Comment (enen92) [inline xbmc/view/GUIViewState.cpp:108]: maybe we need a sane default here? What if the window ID is different from both?

Comment (CastagnaIT) [reply xbmc/view/GUIViewState.cpp:108]: add the "else" case

File: xbmc/PlayListPlayer.cpp (hunk 2 above)
Comment (CastagnaIT) [reply xbmc/PlayListPlayer.cpp]: i checked and yes its safe, so if the property is set with data other than integer, then the method fallback to default value,
so i have add the default value to PLAYLIST_NONE

Comment (enen92) [reply xbmc/PlayListPlayer.cpp]: I'd say that if a plugin resolves its url to a local or remote playlist (e.g. strm) yes, the property will still be set from python although the dynpath changed

File: xbmc/view/GUIViewState.cpp [hunk 4]
```diff
@@ -101,7 +101,17 @@ CGUIViewState* CGUIViewState::GetViewState(int windowId, const CFileItemList& it
...
+      return new CGUIViewStateVideoPlaylist(items);
+    else if (windowId == WINDOW_MUSIC_NAV)
+      return new CGUIViewStateMusicPlaylist(items);
+    else
+      return new CGUIViewStateGeneral(items);
```
Comment (enen92) [inline xbmc/view/GUIViewState.cpp:113]: why general? shouldn't it be `return new CGUIViewStateMusicPlaylist(items);` just like before?

Comment (CastagnaIT) [reply xbmc/view/GUIViewState.cpp]: yes changed

**Review by enen92 — APPROVED** [review]
Looks good to me and shouldn't cause regressions on jsonrpc like my previous attempt. Nice job

**Comment by enen92** [comment]
jenkins build please

**Comment by enen92** [comment]
jenkins build this please

**Comment by matthuisman** [comment]
Just curious, would if make more sense to check for video before audio? I think it's more likely someone playing video vs audio? 

Ie. If we didn't have the hint and it was a playlist, it would check isvideo before isaudio and use video playlist.

**Comment by lrusak** [comment]
jenkins build this please

**Comment by CastagnaIT** [comment]
the hint prop is always set when needed, have you found a code path where is not set?
