### PR TITLE
[Art] Fix #25601 - Refresh art after update in information dialog

### LINKED ISSUE #25601: TV Show/Movie poster not refreshing after manually changing via Info->Choose art, but refreshed after Kodi restart
### Describe the bug
When clicking on Info->Choose art to change the Poster image for a Movie or TV Show on the main page, the newly selected Poster does not display after the selection is made. See video attached. If Kodi is quit and restarted, the newly selected image is now properly displayed. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I think the right behaviour would be to refresh the image on the page immediately after the new Poster is selected and confirmed.

## Actual Behavior

The poster is not refreshed right away, but if Kodi is quit and restarted, the newly selected poster image shows correctly.

## Possible Fix

Maybe there is a call missing to refresh the poster(s) art/thumbnail on the main page after a new one is selected in Info->Choose art

### To Reproduce

1. Click Info->Choose Art on a Movie/TV Show item on the main page
2. Select a new art (remote art) and click ok
3. Back out to home screen, the old Poster is still shown.
4. Exit out of Kodi and restart, the newly selected image is now displayed.

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/user-attachments/files/16577680/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

https://github.com/user-attachments/assets/7048b8d0-1f66-4620-a84b-aeb25eadff9e

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 latest
 - Kodi version: 20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Fix #25601

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by thexai — APPROVED** [review]
Tested and works!

File: xbmc/video/windows/GUIWindowVideoBase.cpp [hunk 1]
```diff
@@ -514,6 +514,11 @@ bool CGUIWindowVideoBase::ShowInfoAndRefresh(const CFileItemPtr& item, const Scr
     m_viewControl.SetSelectedItem(itemNumber);
   }
 
+  CVariant data;
+  data["id"] = item->GetVideoInfoTag()->m_iDbId;
+  data["type"] = item->GetVideoInfoTag()->m_type;
+  CServiceBroker::GetAnnouncementManager()->Announce(ANNOUNCEMENT::VideoLibrary, "OnUpdate", data);
```
Comment (enen92) [inline xbmc/video/windows/GUIWindowVideoBase.cpp:520]: I don't doubt this fixes the issue but the announce for videolibrary update is being done by a GUI window when it should be done by the actual library component...
Any change you can find out a proper place for the announce?
Thanks for tackling some of our open issues! It's greatly appreciated

Comment (ksooo) [reply xbmc/video/windows/GUIWindowVideoBase.cpp:520]: I do not know how to fix this properly, but the taken approach seems not the best, like @enen92 pointed out here.

@CrystalP If I remember correctly you already dealt with similar problems. Do you have an idea for a more suitable fix. Using window's `Refresh()` method or something like this maybe?

Comment (78andyp) [reply xbmc/video/windows/GUIWindowVideoBase.cpp:520]: I think that was one of my first PRs #24176 which @CrystalP guided me through.

Comment (ksooo) [reply xbmc/video/windows/GUIWindowVideoBase.cpp]: > Refresh() doesn't always get called. 

I meant maybe you could call Refresh() yourself to fix the issue.

File: xbmc/video/VideoDatabase.h [hunk 2]
```diff
@@ -979,7 +979,7 @@ class CVideoDatabase : public CDatabase
     }
   }
 
-  void SetArtForItem(int mediaId, const MediaType &mediaType, const std::string &artType, const std::string &url);
+  void SetArtForItem(int mediaId, const MediaType &mediaType, const std::string &artType, const std::string &url) const;
```
Comment (ksooo) [inline xbmc/video/VideoDatabase.h:982]: From the logical POV a setter methid being `const` looks somehow wrong.

Comment (78andyp) [reply xbmc/video/VideoDatabase.h:982]: Only changed as Visual Studio/Resharper said it could be const - I thought the preference was for a function to be const where it could be?? Will change back.

File: xbmc/video/windows/GUIWindowVideoBase.cpp (hunk 1 above)
Comment (78andyp) [reply xbmc/video/windows/GUIWindowVideoBase.cpp]: I could, but that's still in the GUI class - @enen92 preferred it out of there - are you happy with the current solution in VideoDatabase??

File: xbmc/video/VideoDatabase.h (hunk 2 above)
Comment (ksooo) [reply xbmc/video/VideoDatabase.h:982]: > I thought the preference was for a function to be const where it could be??

Yes, this is correct. I'm only irritated why a member function that does not change member's state can be const. This is from the logical perspective, not technical. Nothing you have introduced with your PR, and unrelated to your change, so I suggest to leave it as it is and to remove `const`.

Comment (78andyp) [reply xbmc/video/VideoDatabase.h]: Removed.

**Review by enen92 — APPROVED** [review]
LGTM, thanks!
Please apply clang-format

**Comment by 78andyp** [comment]
> LGTM, thanks! Please apply clang-format

Done. Thanks and thanks for the advice.
