### PR TITLE
[JSON-RPC] Fix plugin:// url support for Files.GetFileDetails

### LINKED ISSUE #15897: JSON-RPC API v10 Files.GetFileDetails not supporting plugin:// (plugin source)
### Describe the bug
Sending JSONRPC request for file that was added with plugin source failed with `Invalid params`.
Files added with source plugin results in adding as:
`MyVideos<id>.db -> files.strFilename = plugin://plugin.video.nakamori/tvshows/98939/play, idPath = 2`
`MyVideos<id>.db -> path.idPath = 2, strPath = plugin://plugin.video.nakamori/`

Sending JSONRPC for file = strPath + strFilename, or file=strFilename both failes.

It looks like the function for this don't support anything that starts with `plugin://` (that what I assume) 
https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/FileOperations.cpp#L164

## Expected Behavior
Sending JSONRPC like this:
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/tvshows/98939/play","media":"video","properties":["title"]},"id":1}`
should return valid response or invalid parms when the `file` is wrong

## Actual Behavior
Sending JSONRPC like on of those:
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/tvshows/98939/play","properties":["title"]},"id":1}`
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/tvshows/98939/play","media":"video","properties":["title"]},"id":1}`
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/plugin://plugin.video.nakamori/tvshows/98939/play","properties":["title"]},"id":1}`
`{"jsonrpc":"2.0","method":"Files.GetFileDetails","params":{"file":"plugin://plugin.video.nakamori/plugin://plugin.video.nakamori/tvshows/98939/play","media":"video","properties":["title"]},"id":1}`

Results with
```
XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.nakamori/tvshows/98939/play
2019-04-11 06:58:45.132 T:7068  NOTICE: {"error":{"code":-32602,"message":"Invalid params."},"id":1,"jsonrpc":"2.0"}
```

## Possible Fix
I have no idea about c++ but the fix would be add code to function to support this: https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/FileOperations.cpp#L164

### To Reproduce
1. use supported video plugin as library source
2. scan as local info (media scraper)
3. send jsonrpc with filepath take out of myvideo.db

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: KodiSetup-20190406-39c78c00-master-x64.exe (18.2 RC?)

### PR DESCRIPTION
**Pull request by mediaminister**
## Description

This fixes support for `plugin://` urls in `Files.GetFileDetails` and `Files.SetFileDetails`

## Motivation and Context

Video plugins should be able to synchronize their users' viewing activity between Kodi and corresponding API's of online streaming services (like Netflix or VRT NU). This change enables video plugins to update Kodi's resume position and playcount number using JSON-RPC `Files.GetFileDetails` and `Files.SetFileDetails`.

For instance:
```json

{"jsonrpc": "2.0", "method": "Files.GetFileDetails", "params": {"file": "plugin://plugin.video.vrt.nu/play/id/vid-6fec4cf9-ccc5-4c59-8066-c1090eff599b/pbs-pub-e6cd657c-8497-48d8-bd4d-33929ae43ac3", "media": "video", "properties": ["resume"]}, "id": "1"}

{"jsonrpc": "2.0", "method": "Files.SetFileDetails", "params": {"file": "plugin://plugin.video.vrt.nu/play/id/vid-6fec4cf9-ccc5-4c59-8066-c1090eff599b/pbs-pub-e6cd657c-8497-48d8-bd4d-33929ae43ac3", "media": "video", "resume": {"position":1094, "total": 2499}}, "id": "1"}

```
This enables continue watching online video content across different devices including Kodi ones.

This fixes https://github.com/xbmc/xbmc/issues/15897 and https://github.com/pietje666/plugin.video.vrt.nu/issues/568

## How Has This Been Tested?

Tested in Kodi 19 with [VRT NU Add-on](https://github.com/pietje666/plugin.video.vrt.nu)

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by mediaminister** [comment]
cc @bigretromike @AkariDN @rmrector @DaveTBlake @doko-desuka @dagwieers @michaelarnauts

**Comment by dagwieers** [comment]
cc @CastagnaIT This is also needed by the Netflix add-on for the upcoming Resumepoints/Watched implementation in order to synchronize online metadata with local metadata.

**Comment by dagwieers** [comment]
It would be nice to see this backported to Leia as well.

**Comment by bigretromike** [comment]
Glad to see it. Would love it in Leia. But then again awesome having it in Matrix, than not having it at all.

**Comment by CastagnaIT** [comment]
one step forward good
i will see in the near future
when the implementation on netflix will be mature

**Review by rmrector — APPROVED** [review]
Cheers, this looks good.

Have you given any thought to how the addition to `CFileFactory::CreateLoader` may affect other parts of the code? How are other calls to `CFileFactory::CreateLoader` affected when this returns a new file for a plugin path though it previously returned nothing?

Unlikely for a backport, the addition to `CFileFactory::CreateLoader` touches a lot of other functionality.

**Comment by mediaminister** [comment]
> Have you given any thought to how the addition to CFileFactory::CreateLoader may affect other parts of the code?

No, I didn't investigate this yet. I only tested this with JSON-RPC calls and I currently have no clue what other calls use `CFileFactory::CreateLoader`

File: xbmc/filesystem/PluginFile.cpp [hunk 1]
```diff
@@ -0,0 +1,28 @@
+/*
+ *  Copyright (C) 2005-2018 Team Kodi
+ *  This file is part of Kodi - https://kodi.tv
+ *
+ *  SPDX-License-Identifier: GPL-2.0-or-later
+ *  See LICENSES/README.md for more information.
+ */
+
+#include "PluginFile.h"
+#include "URL.h"
```
Comment (Rechi) [inline xbmc/filesystem/PluginFile.cpp]: > Included header files have to be sorted (case sensitive) alphabetically to prevent duplicates and allow better overview, **with an empty line clearly separating sections.**

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#7-headers

File: xbmc/filesystem/PluginFile.cpp [hunk 2]
```diff
@@ -0,0 +1,28 @@
...
+
+using namespace XFILE;
+
+CPluginFile::CPluginFile(void)
+  : COverrideFile(false)
```
Comment (Rechi) [inline xbmc/filesystem/PluginFile.cpp]: > For lines up to [line length](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#line-length) everything stays on one line, excluding the braces which must be on the following lines.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#116-constructor-initialzation-lists

File: xbmc/filesystem/PluginFile.h [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+{
+public:
+  CPluginFile(void);
+  ~CPluginFile(void) override;
+  bool Exists(const CURL& url) override;
+
+protected:
+  std::string TranslatePath(const CURL& url) override;
+};
+}
```
Comment (Rechi) [inline xbmc/filesystem/PluginFile.h]: `} // namespace XFILE`

File: xbmc/interfaces/json-rpc/FileOperations.cpp [hunk 4]
```diff
@@ -174,10 +174,15 @@ JSONRPC_STATUS CFileOperations::GetFileDetails(const std::string &method, ITrans
   std::string path = URIUtils::GetDirectory(file);
 
   CFileItemList items;
-  if (path.empty() || !CDirectory::GetDirectory(path, items, "", DIR_FLAG_DEFAULTS) || !items.Contains(file))
+  if (path.empty())
     return InvalidParams;
 
-  CFileItemPtr item = items.Get(file);
+  CFileItemPtr item;
+  if(CDirectory::GetDirectory(path, items, "", DIR_FLAG_DEFAULTS) && items.Contains(file))
```
Comment (Rechi) [inline xbmc/interfaces/json-rpc/FileOperations.cpp]: > Control statement keywords have to be separated from opening parentheses by one space.

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

**Review by Rechi — COMMENTED** [review]
Please follow the [current code guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

**Comment by rmrector** [comment]
@mediaminister Alright, one last change is needed before merging: update the version number for JSON-RPC. Edit the [xbmc/interfaces/json-rpc/schema/version.txt](https://github.com/xbmc/xbmc/blob/master/xbmc/interfaces/json-rpc/schema/version.txt) file and increase the last "patch" number by 1 - right now the change is from "11.1.0" to "11.1.1".

**Comment by dagwieers** [comment]
Could this be backported to Kodi v18.6? It would make our lives as add-on developers a lot easier.

**Comment by rmrector** [comment]
Nope, the addition to `CFileFactory::CreateLoader` touches a lot of other functionality and the fallout is unpredictable.
