### PR TITLE
[Android] Set codec profile 8 in DOVI compatibility mode

### LINKED ISSUE #24078: Dolby Vision doesn't work on Sony A95L
### Describe the bug
DV videos are rendered incorrectly, some with balck screen, some with funny colors.
I tried samples from demolandia.net without HDR fallback.
mediainfo: https://paste.kodi.tv/uxupadidil.
This might affect other Sony or Android TVs.

**Looks like it's because Kodi chose the wrong codec -  "c2.mtk.dvav.se.decoder" instead of "c2.mtk.dvhe.stn.decoder".**

## Expected Behavior
Video must be played in Dolby Vision mode.

## Actual Behavior
Video is not rendered properly.

## Possible Fix
Improve logic for selecting the right Android codec.

### To Reproduce
1.  Download DV video
2. Play it with Kodi
3. See the result

### Debuglog
The debuglog can be found here: https://paste.kodi.tv/mudebiwugo.kodi

## Additional context or screenshots (if appropriate)
Initial discussion: https://forum.kodi.tv/showthread.php?tid=374979

### Your Environment
Used Operating system:
 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: BRAVIA_AE1_EU-user 12 STT2.230327.001 604070 (Android TV 12)
 - Kodi version: kodi-20231105-76e06459-master

### PR DESCRIPTION
**Pull request by quietvoid**
## Description
Signals the real (final) profile when converting Dolby Vision profile 7 files, to allow choosing the correct codec.

## Motivation and context
Improves fix of #24078.

## How has this been tested?
Not tested but code change is simple.

## What is the effect on users?
Allows Kodi to pick the correct codec when playing back profile 7 videos with compatibility mode enabled.
No changes for playback without compatibility mode.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp [hunk 1]
```diff
@@ -498,6 +498,9 @@ bool CDVDVideoCodecAndroidMediaCodec::Open(CDVDStreamInfo &hints, CDVDCodecOptio
       m_mime = "video/hevc";
       m_formatname = "amc-hevc";
 
+      bool convertDovi = CServiceBroker::GetSettingsComponent()->GetSettings()->GetBool(
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:501]:
```suggestion
      const auto settings = CServiceBroker::GetSettingsComponent()->GetSettings();
      const bool convertDovi =
          (settings) ? settings->GetBool(CSettings::SETTING_VIDEOPLAYER_CONVERTDOVI) : false;
```

We can take the opportunity to use `const bool` and handle the rare case where settings may be null

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp [hunk 2]
```diff
@@ -557,6 +560,10 @@ bool CDVDVideoCodecAndroidMediaCodec::Open(CDVDStreamInfo &hints, CDVDCodecOptio
                 profile = CJNIMediaCodecInfoCodecProfileLevel::DolbyVisionProfileDvheDth;
                 break;
               case 7:
+                // set profile 8 when converting
+                if (convertDovi && CJNIBase::GetSDKVersion() >= 27)
+                  profile = CJNIMediaCodecInfoCodecProfileLevel::DolbyVisionProfileDvheSt;
+
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:566]: It would be good to add a code comment briefly explaining the reason why it is omitted set the profile 7 when is not converted.

**Review by thexai — COMMENTED** [review]
Many thanks for improve this

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp (hunk 1 above)
Comment (quietvoid) [reply xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp]: Done.

**Comment by fuyar** [comment]
Works perfectly on a A95L

**Review by thexai — APPROVED** [review]
Also tested on Shield
