### PR TITLE
Fix `ValidateField` to correctly detect invalid characters as per issue #26044.

### LINKED ISSUE #26044: Incorrect code in PLT_ProtocolInfo::ValidateField
### Describe the bug
Here is a clear and concise description of what the problem is:

The code in PLT_ProtocolInfo::ValidateField appears to be incorrect.

https://github.com/xbmc/xbmc/blob/3c88ff04edc95487569605b807ba59366ea4a35b/lib/libUPnP/Platinum/Source/Core/PltProtocolInfo.cpp?plain=1#L236C1-L237C1

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Presumably it should validate the chars in "val" are **only** what are in the string "valid_chars".

## Actual Behavior

As it stands, if there were no matching character, the inner while loop runs past the end of valid_chars until by chance it encounters a matching character elsewhere.

## Possible Fix

    while ( val )
    {
        const char c = *val++;
        if ( c == '\0' )
            return NPT_SUCCESS;

        // look for character in valid chars
        const char* p = valid_chars;
        while ( *p != c && *(++p) )
        {
        };

        // reached end of valid chars means we didn't find it
        if ( !*p )
            break;
    }

### To Reproduce

1.  Test the code as it stands - carefully!

### Debuglog

The debuglog can be found here:
N/A

### Screenshots
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

N/A

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: N/A
 - Kodi version: Latest master source code

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by Dave-Lowndes**
## Description
As the code was, if there were no matching character, the inner while loop runs past the end of valid_chars until by chance it encounters a matching character elsewhere.

## Motivation and context
Issue #26044 

## How has this been tested?
N/A

## What is the effect on users?
N/A

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

**Review by neo1973 — CHANGES_REQUESTED** [review]
The fix looks correct, thank you 🙂 

Because this is an external dependency please add a .patch file as well, see e.g. #25373 for reference.

**Comment by Dave-Lowndes** [comment]
I've added a .patch file, hope it's OK, its not something I've ever needed to do before!

**Comment by neo1973** [comment]
Please squash the commits and I'll give this an approval :slightly_smiling_face:

**Comment by Dave-Lowndes** [comment]
> Please squash the commits and I'll give this an approval 🙂

How do I do that?
Squash Merging is showing as enabled on my repo.

**Comment by neo1973** [comment]
You do this via an interactive rebase in your Git client. Then you force-push your branch.

**Comment by Dave-Lowndes** [comment]
> You do this via an interactive rebase in your Git client. Then you force-push your branch.

I've done *something*, but may have made it worse! There doesn't seem to be an "interactive rebase" in Visual Studio 2022.

**Comment by garbear** [comment]
@claude give instructions on how to fix the branch. Assume the user is using VS 2022 as their IDE and has access to standard windows tools and utilities. If VS doesn't have an interactive rebase, give accessible commands using Git for Windows.

**Comment by Dave-Lowndes** [comment]
@claude 
After performing the following command:
git rebase -i HEAD~7
The editor has 10 lines including ones prior to mine, should I leave these line intact, or delete them?

**Review by neo1973 — APPROVED** [review]
Thanks, looks good now 👍

File: lib/libUPnP/Platinum/Source/Core/PltProtocolInfo.cpp [hunk 1]
```diff
@@ -228,15 +228,15 @@ PLT_ProtocolInfo::ValidateField(const char*  val,
         return NPT_ERROR_INVALID_SYNTAX;
 
     while (val) {
-        char c = *val++;
+        const char c = *val++;
```
Comment (CrystalP) [inline lib/libUPnP/Platinum/Source/Core/PltProtocolInfo.cpp]: It works and Claude didn't mention it but SonarQube likely will, for clarity:
```suggestion
        const char c = *(val++);
```
like the other change a few lines down

or split on two lines for extra clarity. Storage is cheap ;-)

Comment (Dave-Lowndes) [reply lib/libUPnP/Platinum/Source/Core/PltProtocolInfo.cpp]: I agree that such statements are confusing and unnecessary, but I was only making minimal changes to fix the issue.
If there's consensus on generally making the code clearer (and still getting it passed), I can do that.

Comment (CrystalP) [reply lib/libUPnP/Platinum/Source/Core/PltProtocolInfo.cpp]: We try to bring the lines modified by a change up to the current coding standards so that much is enough for me. A rewrite as modern C++ would be beyond the scope of the PR (it'd be nice though as a second phase)

Comment (Dave-Lowndes) [reply lib/libUPnP/Platinum/Source/Core/PltProtocolInfo.cpp]: @CrystalP Without going the whole hog and rewriting it as modern C++, see if you think the latest version tidies it up a bit better.

Comment (CrystalP) [reply lib/libUPnP/Platinum/Source/Core/PltProtocolInfo.cpp]: Yes that's better. Though the curly braces { } are not needed for single line blocks and should be omitted as they don't improve readability here.

Comment (Dave-Lowndes) [reply lib/libUPnP/Platinum/Source/Core/PltProtocolInfo.cpp]: My preference is to always have the braces. Always putting them in can prevent sloppy mistakes creeping in.

**Comment by CrystalP** [comment]
Though it's not the standard of the project, the curly braces for a single statement after if() are not forbidden either.
I think this will be ready for merge after squashing the commits.

**Comment by thexai** [comment]
Patch file should be renamed to `0057-` because 0056 already exist currently (from the other PR).

**Comment by thexai** [comment]
@claude review

**Comment by garbear** [comment]
jenkins build this please

@claude sanity check?

**Review by thexai — APPROVED** [review]
