### PR TITLE
[Android] Mark window dirty on app resume

### LINKED ISSUE #25632: [Android TV, Kodi 21.1] When using minimize command (just by pressing home on remote or a key set by keymap editor), returning to app gives a black screen
### Describe the bug
Here is a clear and concise description of what the problem is: 

When you press a key to execute minimize command set by keymap editor, or press home button to go to home screen, clicking back on kodi app to bring it back results in black screen

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

It should bring up the app again since it is active

## Actual Behavior

You get the black screen

## Possible Fix

It is enough to press any button and black screen goes away. The bug wasn't present in previous stable version. 

### To Reproduce

1. Run kodi 
2. Press a key to execute minimize command or just press home on a remote. 
3. Click on Kodi again to bring it up and  you get the black screen 

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

Android TV 11 and 12

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
21.1 stable  and all development nightly versions 

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Mark the window as dirty to render it when resuming the app from android home screen.

Regression added in #25121 and #25164.

Now displays Kodi screen instantly when resuming from home screen.

## Motivation and context
Fix #25632

## How has this been tested?
Chromecast with Google TV

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/platform/android/activity/XBMCApp.cpp [hunk 1]
```diff
@@ -318,6 +318,9 @@ void CXBMCApp::onResume()
     appPower->ResetShutdownTimers();
   }
 
+  if (CServiceBroker::GetAppMessenger())
```
Comment (fritsch) [inline xbmc/platform/android/activity/XBMCApp.cpp:321]: This check makes only sense, when refcounting would be involved. Therefore assign the GetAppMessenger to a local variable and then use this for sending the message?

e.g. mymessenger = CServiceBroker::GetAppMessenger();
if (mymessenger)
{
}

Right?

**Comment by fritsch** [comment]
I had one minor comment for the code. Thank you very much for fixing that long standing issue -> should also be backported to stable version.

File: xbmc/platform/android/activity/XBMCApp.cpp (hunk 1 above)
Comment (joseluismarti) [reply xbmc/platform/android/activity/XBMCApp.cpp]: Good, use a variable

**Review by neo1973 — APPROVED** [review]
I don't have a device to test but code looks good :+1:

**Review by thexai — APPROVED** [review]
Tested on Shield and is working fine 👍

**Comment by neo1973** [comment]
Jenkins build this please.

**Comment by neo1973** [comment]
Backport please :slightly_smiling_face:

**Comment by Zizou3000** [comment]
A big thank you for fixing this.  Where can I see in which version has it been fixed?

**Comment by joseluismarti** [comment]
> A big thank you for fixing this. Where can I see in which version has it been fixed?

Will be included in the next release 21.2

**Comment by Zizou3000** [comment]
> > A big thank you for fixing this. Where can I see in which version has it been fixed?
> 
> Will be included in the next release 21.2

will it be in today's nightly? (I'm trying to figure out how this works, sorry)

**Comment by joseluismarti** [comment]
You can try this build while available:  [armeabi-v7a](https://jenkins.kodi.tv/job/android-arm-docker/9334/artifact/kodi-20250103-b0655ece-PR26226-armeabi-v7a.apk) or [arm64-v8a](https://jenkins.kodi.tv/job/android-arm64-docker/9117/artifact/kodi-20250103-b0655ece-PR26226-arm64-v8a.apk)
