### PR TITLE
[Windows] Fix: green screen on DX feature level 9.1 systems (old HW) playing 10-bit videos

### LINKED ISSUE #18902: Kodi 19 Beta 1 show green screen when play a .mkv file
[cut.zip](https://github.com/xbmc/xbmc/files/5696072/cut.zip)

### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi 19 Beta-1, When play one type of mkv file which codec is MPEG-H Part 2/HEVC (H.265), It will only a green screen, Audio is playing ok.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The same file is playing normally in Kodi v18.6 and VLC

## Actual Behavior

When play the video file, it show as green screen

## Possible Fix

Nil

### To Reproduce

1. Play the file
2.
3.

### Debuglog

The debuglog can be found here:
https://surbanajurong-my.sharepoint.com/:u:/g/personal/terence_ngan_bharchitects_com/EdouKUcd7DJMt6ud6ohHDE0BzkZEGlgoahn0EKX7GIgpGQ?e=rLVy72

### Screenshots 
Here are some links or screenshots to help explain the problem:

image
image

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: v19 Beta 1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Fix: green screen on DX feature level 9.1 systems (old HW) playing 10-bit videos.

Fixes https://github.com/xbmc/xbmc/issues/18902

## Motivation and Context
Some users have reported "green screens" issues playing 10-bit videos on old HW. 
See: https://forum.kodi.tv/showthread.php?tid=359422 and https://github.com/xbmc/xbmc/issues/18902

When DXVA2 is disabled or HW codec is not supported on that system, Pixel Shaders render method has preference over DXVA because has more weight:

https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererShaders.cpp#L49-L55

https://github.com/xbmc/xbmc/blob/a80d1293b0579bbed7dd7d20304ba34a20519f78/xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererDXVA.cpp#L61-L64

Then PS is used by default in these conditions. However is required texture formats `DXGI_FORMAT_R16_UNORM` and `DXGI_FORMAT_R16G16_UNORM` that is not supported on DX feature level 9.1

The fix consists on check textures format support early, before assign more weight to PS render method. In case of not supported then defaults to DXVA render method. DXVA use `DXGI_FORMAT_P010` and is supported on FL 9.1.

## How Has This Been Tested?
**Test conditions:**
- DXVA2 disabled
- Render Method = AUTO
- Simulate DX FL 9.1 condition on `DeviceResources.cpp` by removing all from featureLevel array except `D3D_FEATURE_LEVEL_9_1`
- Used test video provided by bug reporter (x264 10-bit)

Green screen is reproducible in these conditions. 

## Screenshots (if appropriate):
Before
screenshot00012

After
screenshot00013

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererShaders.cpp [hunk 1]
```diff
@@ -46,13 +46,33 @@ void CRendererShaders::GetWeight(std::map<RenderMethod, int>& weights, const Vid
...
+    if (!DX::Windowing()->IsFormatSupport(DXGI_FORMAT_R16_UNORM, D3D11_FORMAT_SUPPORT_TEXTURE2D))
+    {
+      CLog::LogF(LOGWARNING, "Texture format DXGI_FORMAT_R16_UNORM is not supported.");
+      return;
+    }
+    if (!DX::Windowing()->IsFormatSupport(DXGI_FORMAT_R16G16_UNORM, D3D11_FORMAT_SUPPORT_TEXTURE2D))
+    {
+      CLog::LogF(LOGWARNING, "Texture format DXGI_FORMAT_R16G16_UNORM is not supported.");
+      return;
+    }
```
Comment (afedchin) [inline xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererShaders.cpp:73]: switch case will be more readable. please change to switch/case.

**Review by afedchin — CHANGES_REQUESTED** [review]

File: xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererShaders.cpp (hunk 1 above)
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/windows/RendererShaders.cpp]: Done!

**Review by afedchin — APPROVED** [review]
