### PR TITLE
init stage 2/3 implementation

### LINKED ISSUE #19321: KODI Matrix - XMBChelper and Harmony keymap load issue
### Describe the bug
Here is a clear and concise description of what the problem is:

When starting KODI Matrix on OSX, the harmony keymap is not loaded, although its has been set to use the harmony remote under settings - input - apple remote

It does not matter if you use the standard customcontroller.Harmony.xml provided in the masterprofile, or if you use a custom keymap verson of customcontroller.Harmony.xml placed in the userdata/keymap folder.

If you set the remote to -disabled- then -standard- then -harmony- the keymap is loaded correctly but not reloaded when KODI is started at a later time.
Both masterprofile or userprofile version will load correctly if done manually.

The XBMChelper is NOT keeped alive, even if you have select the -allow KODI to be started with the remote- option.

It would appear that it is killed unless you do above load of the keymap manually.
If you dont, XBMChepler is closed on KODI exit.

It seems like the remote setting is not properly activated on load.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

KODI should load the correct keymap as set under settings-imput-apple remote
And XBMChelper should be kept alive on exit

## Actual Behavior

It does not load the correct keymap 
And XBMChelper is killed on exit.

## Possible Fix

Review the remote - settings loading process and fix the bug.

### To Reproduce
Steps to reproduce the behaviour:

1. install KODI MATRIX on OSX - with a fully fresh userdata / masterprofile 
2. setup the harmony remote to be used as a KODI remote. There are various guides for this.
3. select the harmony under settings-imput-apple remote

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/xahuraweka.kodi

2 lines are interesting

What is this error. 
Could especially the first error be related to a load of settings issue.

2021-02-22 17:36:10.807 T:203828 WARNING <general>: JSONRPC: Could not parse type "Setting.Details.SettingList"

2021-02-22 17:37:11.243 T:204039 WARNING <general>: DARWINOSX: underflow (0 vs 4096 bytes) 

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Matrix 19.0 Build 19.0.0

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by fuzzard**
## Description
Implement stagetwo and stagethree platform init.
Relocate tvos/macos service init to platform initstagetwo as required.

Application startup system logging has a platform override.

## Motivation and Context
Fix existing issues with components for tvos/osx builds. Provide ability for other platforms to do platform specific init at later stages than stage one

Stagetwo is done after settings have been init, so any non gui/windowing related services could/should be done here
Stagethree is done after window init. Any services/components that depend on gui/windowing can be done here. 

Should allow an easier definition of services for potential headless operation.

As part of this, streamline some other functions in Application, and move dvdmediadetect into Servicemanager

## How Has This Been Tested?
Runtime test OSX

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by sy6sy2 — APPROVED** [review]
Runtime tested on tvOS. Fix the issue pointed by https://github.com/xbmc/xbmc/pull/19460.

If merged, I guess we can close https://github.com/xbmc/xbmc/pull/19460 and https://github.com/xbmc/xbmc/pull/19522.

File: xbmc/ServiceManager.cpp [hunk 1]
```diff
@@ -148,6 +151,16 @@ bool CServiceManager::InitStageTwo(const CAppParamParser &params, const std::str
   m_mediaManager.reset(new CMediaManager());
   m_mediaManager->Initialize();
 
+#if !defined(TARGET_WINDOWS) && defined(HAS_DVD_DRIVE)
+  // Start Thread for DVD Mediatype detection
+  CLog::Log(LOGINFO, "start dvd mediatype detection");
+  m_DetectDVDType.reset(new MEDIA_DETECT::CDetectDVDMedia());
```
Comment (lrusak) [inline xbmc/ServiceManager.cpp:157]:
```suggestion
  m_DetectDVDType = std::make_unique<MEDIA_DETECT::CDetectDVDMedia>();
```

File: xbmc/ServiceManager.cpp [hunk 2]
```diff
@@ -148,6 +151,16 @@ bool CServiceManager::InitStageTwo(const CAppParamParser &params, const std::str
   m_mediaManager.reset(new CMediaManager());
   m_mediaManager->Initialize();
 
+#if !defined(TARGET_WINDOWS) && defined(HAS_DVD_DRIVE)
+  // Start Thread for DVD Mediatype detection
+  CLog::Log(LOGINFO, "start dvd mediatype detection");
```
Comment (lrusak) [inline xbmc/ServiceManager.cpp:156]: Can you improve this log message? (I know it's just copied from where it was)

File: xbmc/ServiceManager.cpp [hunk 3]
```diff
@@ -190,6 +206,12 @@ void CServiceManager::DeinitStageTwo()
 {
   init_level = 1;
 
+#if !defined(TARGET_WINDOWS) && defined(HAS_DVD_DRIVE)
+  CLog::Log(LOGINFO, "stop dvd detect media");
```
Comment (lrusak) [inline xbmc/ServiceManager.cpp:210]: same with this log message

File: xbmc/platform/Platform.h [hunk 4]
```diff
@@ -23,17 +23,33 @@ class CPlatform
...
 
   /**\brief Called at an early stage of application startup
    *
    * This method can be used to do platform specific environment preparation
    * or initialisation (like setting environment variables for example)
    */
-  virtual bool Init();
+  virtual bool Init() { return true; };
+
+  /**\brief Called at a middle stage of application startup
```
Comment (lrusak) [inline xbmc/platform/Platform.h:38]: Can you note that logging will be available here (it is available in stage one but may not actually log anything because `CLog::Initialize` isn't called till after stageone. Platforms that use special loggers (android, osx) may show the logging from initstageone but other platforms that only use the log file logging won't.

File: xbmc/platform/Platform.h [hunk 5]
```diff
@@ -23,17 +23,33 @@ class CPlatform
...
-  virtual ~CPlatform();
+  virtual ~CPlatform() = default;
 
   /**\brief Called at an early stage of application startup
    *
    * This method can be used to do platform specific environment preparation
    * or initialisation (like setting environment variables for example)
    */
-  virtual bool Init();
+  virtual bool Init() { return true; };
```
Comment (lrusak) [inline xbmc/platform/Platform.h:36]: might be worth it to update this to `InitStageOne`?

**Review by lrusak — COMMENTED** [review]
Generally looks ok. Greate work :100: 

I've left a few small comments. I don't like the ifdefs introduced into servicemanager but we should be able to add a instance wrapper for that at a later time.

File: xbmc/platform/Platform.h (hunk 5 above)
Comment (sy6sy2) [reply xbmc/platform/Platform.h:36]: I thought the same thing when I saw this line.  I vote for it.

File: xbmc/ServiceManager.cpp (hunk 1 above)
Comment (garbear) [reply xbmc/ServiceManager.cpp:157]: is the reason to hide `new` inside the unique ptr?

File: xbmc/ServiceManager.h [hunk 6]
```diff
@@ -168,4 +177,7 @@ class CServiceManager
   std::unique_ptr<CPlayerCoreFactory> m_playerCoreFactory;
   std::unique_ptr<CDatabaseManager> m_databaseManager;
   std::unique_ptr<CMediaManager> m_mediaManager;
+#if !defined(TARGET_WINDOWS) && defined(HAS_DVD_DRIVE)
+  std::unique_ptr<MEDIA_DETECT::CDetectDVDMedia> m_DetectDVDType;
```
Comment (garbear) [inline xbmc/ServiceManager.h:181]: From one dumping ground to another. It would be a good time to consider a new home for anything here, but not required for the PR.

Comment (fuzzard) [reply xbmc/ServiceManager.h:181]: From what I've gathered, servicebroker was just a stepping stone to greater things which just haven't materialised. I still think it helps to get everything here to give a clear picture of what to do with the DI stuff.
I've tried comprehending jimfcarrols DI stuff, but it hasn't sunk in how I could do it as yet. Maybe one day, haha

File: xbmc/platform/Platform.h (hunk 5 above)
Comment (fuzzard) [reply xbmc/platform/Platform.h:36]: I contemplated it, then I said stuff it. Haha. I'll go back and do it though

**Review by garbear — APPROVED** [review]
This PR contains some great refactoring! I like the documentation you added for the 2nd and 3rd stage.

File: xbmc/ServiceManager.h (hunk 6 above)
Comment (garbear) [reply xbmc/ServiceManager.h:181]: @jimfcarroll's DI stuff improves our tangle of dependencies by replacing imperative relationships with declarative relationships. What we truly need is a decoupling of dependencies. However, it's a shame that "how it all should be" got in the way of the tangible benefits of DI for the parts that don't need decoupling.

**Comment by fuzzard** [comment]
Ok, couple changes, fixed @lrusak 's comments. Init renamed to initstageone for consistency

Ive also pulled out the system startup log section from CApplication::Create. As part of that, ive provided a platform override for individual platforms to output their unique device info. Just removes ifdefs in application.cpp

Im VERY open to function naming opinions here. let me know if something else is better.

File: xbmc/platform/android/PlatformAndroid.cpp [hunk 7]
```diff
@@ -34,3 +37,17 @@ bool CPlatformAndroid::Init()
...
+      LOGINFO,
+      "Product: %s, Device: %s, Board: %s - Manufacturer: %s, Brand: %s, Model: %s, Hardware: %s",
+      CJNIBuild::PRODUCT.c_str(), CJNIBuild::DEVICE.c_str(), CJNIBuild::BOARD.c_str(),
+      CJNIBuild::MANUFACTURER.c_str(), CJNIBuild::BRAND.c_str(), CJNIBuild::MODEL.c_str(),
+      CJNIBuild::HARDWARE.c_str());
+  std::string extstorage;
+  bool extready = CXBMCApp::GetExternalStorage(extstorage);
+  CLog::Log(LOGINFO, "External storage path = %s; status = %s", extstorage.c_str(),
+            extready ? "ok" : "nok");
+}
```
Comment (lrusak) [inline xbmc/platform/android/PlatformAndroid.cpp:53]: new line at end of file

File: xbmc/platform/win32/WIN32Util.cpp [hunk 8]
```diff
@@ -1521,3 +1521,20 @@ HDR_STATUS CWIN32Util::GetWindowsHDRStatus()
...
+            (IsCurrentUserLocalAdministrator() == TRUE) ? "administrator"
+                                                        : "restricted");
+  CLog::Log(LOGINFO, "Aero is %s", (g_sysinfo.IsAeroDisabled() == true) ? "disabled" : "enabled");
+  HDR_STATUS hdrStatus = GetWindowsHDRStatus();
+  if (hdrStatus == HDR_STATUS::HDR_UNSUPPORTED)
+    CLog::Log(LOGINFO, "Display is not HDR capable or cannot be detected");
+  else
+    CLog::Log(LOGINFO, "Display HDR capable is detected and Windows HDR switch is %s",
+              (hdrStatus == HDR_STATUS::HDR_ON) ? "ON" : "OFF");
+}
```
Comment (lrusak) [inline xbmc/platform/win32/WIN32Util.cpp:1540]: new line at end of file

**Review by lrusak — COMMENTED** [review]
A couple more comments.

One thing I will say is that when getting others to review and they leave a review it's typically good to add extra commits (either using `--fixup` or not) after the reviewed section. That way when you request a review again the reviewer can see exactly what changed from your first review rather than having to dig through the entire PR again. Then when all the comments are addressed you can squash.

I would also be careful when increasing the scope like you have done. Sometimes it can delay the review even more. I know it doesn't seem like much but when already touching large parts of code it may be best to leave for a follow up PR. Just some food for thought :smiley:

**Comment by fuzzard** [comment]
yeah, the scope thing was a concern. I can split it out into another PR. doesnt really bother me too much if thats the preference.

I had them as fixups, but just rebased. i'll keep that in mind for the future

**Comment by fuzzard** [comment]
Jenkins build this please

File: xbmc/platform/win32/PlatformWin32.cpp [hunk 9]
```diff
@@ -35,3 +35,8 @@ bool CPlatformWin32::Init()
 
   return true;
 }
+
+void CPlatformWin10::PlatformSyslog()
```
Comment (howie-f) [inline xbmc/platform/win32/PlatformWin32.cpp:39]: `CPlatformWin32` ?

**Comment by fuzzard** [comment]
jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
any further comments, or good to go?

File: xbmc/platform/android/PlatformAndroid.cpp [hunk 10]
```diff
@@ -34,3 +37,17 @@ bool CPlatformAndroid::Init()
 
   return true;
 }
+
+void CPlatformAndroid::PlatformSyslog()
+{
+  CLog::Log(
+      LOGINFO,
+      "Product: %s, Device: %s, Board: %s - Manufacturer: %s, Brand: %s, Model: %s, Hardware: %s",
```
Comment (lrusak) [inline xbmc/platform/android/PlatformAndroid.cpp:45]: please update to current log standards using `{}`

File: xbmc/platform/win32/WIN32Util.cpp [hunk 11]
```diff
@@ -1521,3 +1521,20 @@ HDR_STATUS CWIN32Util::GetWindowsHDRStatus()
...
+
+void CWIN32Util::PlatformSyslog()
+{
+  CLog::Log(LOGINFO, "System has {:.1f} GB of RAM installed",
+            GetSystemMemorySize() / static_cast<double>(MB));
+  CLog::Log(LOGINFO, "%s", GetResInfoString().c_str());
+  CLog::Log(LOGINFO, "Running with %s rights",
+            (IsCurrentUserLocalAdministrator() == TRUE) ? "administrator"
+                                                        : "restricted");
+  CLog::Log(LOGINFO, "Aero is %s", (g_sysinfo.IsAeroDisabled() == true) ? "disabled" : "enabled");
```
Comment (lrusak) [inline xbmc/platform/win32/WIN32Util.cpp:1533]: please update to current log standards using `{}`

File: xbmc/Application.cpp [hunk 12]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+#elif defined(NDEBUG)
+  buildType = "Release";
+#else
+  buildType = "Unknown";
+#endif
+
+  CLog::Log(LOGINFO, "Using %s %s x%d", buildType.c_str(), CSysInfo::GetAppName().c_str(),
+            g_sysinfo.GetXbmcBitness());
+  CLog::Log(
+      LOGINFO, "%s compiled %s by %s for %s %s %d-bit %s (%s)", CSysInfo::GetAppName().c_str(),
```
Comment (lrusak) [inline xbmc/Application.cpp:4932]: please update to current log standards using `{}`

File: xbmc/Application.cpp [hunk 13]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+      CSysInfo::GetBuildDate(), g_sysinfo.GetUsedCompilerNameAndVer().c_str(),
+      g_sysinfo.GetBuildTargetPlatformName().c_str(), g_sysinfo.GetBuildTargetCpuFamily().c_str(),
+      g_sysinfo.GetXbmcBitness(), g_sysinfo.GetBuildTargetPlatformVersionDecoded().c_str(),
+      g_sysinfo.GetBuildTargetPlatformVersion().c_str());
+
+  std::string deviceModel(g_sysinfo.GetModelName());
+  if (!g_sysinfo.GetManufacturerName().empty())
+    deviceModel = g_sysinfo.GetManufacturerName() + " " + (deviceModel.empty() ? std::string("device") : deviceModel);
+  if (!deviceModel.empty())
+    CLog::Log(LOGINFO, "Running on %s with %s, kernel: %s %s %d-bit version %s",
```
Comment (lrusak) [inline xbmc/Application.cpp:4942]: please update to current log standards using `{}`

File: xbmc/Application.cpp [hunk 14]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+              deviceModel.c_str(), g_sysinfo.GetOsPrettyNameWithVersion().c_str(),
+              g_sysinfo.GetKernelName().c_str(), g_sysinfo.GetKernelCpuFamily().c_str(),
+              g_sysinfo.GetKernelBitness(), g_sysinfo.GetKernelVersionFull().c_str());
+  else
+    CLog::Log(LOGINFO, "Running on %s, kernel: %s %s %d-bit version %s",
```
Comment (lrusak) [inline xbmc/Application.cpp:4947]: please update to current log standards using `{}`

File: xbmc/Application.cpp [hunk 15]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+              g_sysinfo.GetOsPrettyNameWithVersion().c_str(), g_sysinfo.GetKernelName().c_str(),
+              g_sysinfo.GetKernelCpuFamily().c_str(), g_sysinfo.GetKernelBitness(),
+              g_sysinfo.GetKernelVersionFull().c_str());
+
+  CLog::Log(LOGINFO, "FFmpeg version/source: %s", av_version_info());
```
Comment (lrusak) [inline xbmc/Application.cpp:4952]: please update to current log standards using `{}`

File: xbmc/Application.cpp [hunk 16]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+
+  std::string cpuModel(CServiceBroker::GetCPUInfo()->GetCPUModel());
+  if (!cpuModel.empty())
+    CLog::Log(LOGINFO, "Host CPU: %s, %d core%s available", cpuModel.c_str(),
```
Comment (lrusak) [inline xbmc/Application.cpp:4956]: please update to current log standards using `{}`

File: xbmc/Application.cpp [hunk 17]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+              CServiceBroker::GetCPUInfo()->GetCPUCount(),
+              (CServiceBroker::GetCPUInfo()->GetCPUCount() == 1) ? "" : "s");
+  else
+    CLog::Log(LOGINFO, "%d CPU core%s available", CServiceBroker::GetCPUInfo()->GetCPUCount(),
```
Comment (lrusak) [inline xbmc/Application.cpp:4960]: please update to current log standards using `{}`

File: xbmc/Application.cpp [hunk 18]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+#if defined(__arm__) || defined(__aarch64__)
+  if (CServiceBroker::GetCPUInfo()->GetCPUFeatures() & CPU_FEATURE_NEON)
+    CLog::Log(LOGINFO, "ARM Features: Neon enabled");
+  else
+    CLog::Log(LOGINFO, "ARM Features: Neon disabled");
+#endif
+  CSpecialProtocol::LogPaths();
+
+  std::string executable = CUtil::ResolveExecutablePath();
+  CLog::Log(LOGINFO, "The executable running is: %s", executable.c_str());
```
Comment (lrusak) [inline xbmc/Application.cpp:4975]: please update to current log standards using `{}`

File: xbmc/Application.cpp [hunk 19]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+  std::string hostname("[unknown]");
+  m_ServiceManager->GetNetwork().GetHostName(hostname);
+  CLog::Log(LOGINFO, "Local hostname: %s", hostname.c_str());
```
Comment (lrusak) [inline xbmc/Application.cpp:4978]: please update to current log standards using `{}`

File: xbmc/Application.cpp [hunk 20]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+  std::string lowerAppName = CCompileInfo::GetAppName();
+  StringUtils::ToLower(lowerAppName);
+  CLog::Log(LOGINFO, "Log File is located: %s.log",
```
Comment (lrusak) [inline xbmc/Application.cpp:4981]: please update to current log standards using `{}`

**Review by lrusak — CHANGES_REQUESTED** [review]
I hate to do it but can you pretty please update the logging to current standards. This also involves dropping the `.c_str()` where applicable. Thanks!

File: xbmc/Application.cpp [hunk 21]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
   m_saveSkinOnUnloading = !switchingProfiles;
 }
 
+void CApplication::print_startup_log()
+{
+  CLog::Log(LOGINFO, "-----------------------------------------------------------------------");
+  CLog::Log(LOGINFO, "Starting %s (%s). Platform: %s %s %d-bit", CSysInfo::GetAppName().c_str(),
```
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4916]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp [hunk 22]
```diff
@@ -5052,6 +4910,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+  std::string buildType;
+#if defined(_DEBUG)
+  buildType = "Debug";
+#elif defined(NDEBUG)
+  buildType = "Release";
+#else
+  buildType = "Unknown";
+#endif
+
+  CLog::Log(LOGINFO, "Using %s %s x%d", buildType.c_str(), CSysInfo::GetAppName().c_str(),
```
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4929]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 13 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4942]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 14 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4947]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 15 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4952]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 16 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4956]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 17 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4960]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 18 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4975]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 19 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4978]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 20 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4981]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/android/PlatformAndroid.cpp [hunk 23]
```diff
@@ -34,3 +37,17 @@ bool CPlatformAndroid::Init()
...
+      CJNIBuild::PRODUCT.c_str(), CJNIBuild::DEVICE.c_str(), CJNIBuild::BOARD.c_str(),
+      CJNIBuild::MANUFACTURER.c_str(), CJNIBuild::BRAND.c_str(), CJNIBuild::MODEL.c_str(),
+      CJNIBuild::HARDWARE.c_str());
+  std::string extstorage;
+  bool extready = CXBMCApp::GetExternalStorage(extstorage);
+  CLog::Log(LOGINFO, "External storage path = %s; status = %s", extstorage.c_str(),
```
Comment (jenkins4kodi) [inline xbmc/platform/android/PlatformAndroid.cpp:51]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/win32/WIN32Util.cpp [hunk 24]
```diff
@@ -1521,3 +1521,20 @@ HDR_STATUS CWIN32Util::GetWindowsHDRStatus()
 
   return status;
 }
+
+void CWIN32Util::PlatformSyslog()
+{
+  CLog::Log(LOGINFO, "System has {:.1f} GB of RAM installed",
+            GetSystemMemorySize() / static_cast<double>(MB));
+  CLog::Log(LOGINFO, "%s", GetResInfoString().c_str());
```
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1529]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/win32/WIN32Util.cpp [hunk 25]
```diff
@@ -1521,3 +1521,20 @@ HDR_STATUS CWIN32Util::GetWindowsHDRStatus()
...
+  CLog::Log(LOGINFO, "Running with %s rights",
```
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1530]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/win32/WIN32Util.cpp (hunk 11 above)
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1533]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/win32/WIN32Util.cpp [hunk 26]
```diff
@@ -1521,3 +1521,20 @@ HDR_STATUS CWIN32Util::GetWindowsHDRStatus()
...
+            (IsCurrentUserLocalAdministrator() == TRUE) ? "administrator"
+                                                        : "restricted");
+  CLog::Log(LOGINFO, "Aero is %s", (g_sysinfo.IsAeroDisabled() == true) ? "disabled" : "enabled");
+  HDR_STATUS hdrStatus = GetWindowsHDRStatus();
+  if (hdrStatus == HDR_STATUS::HDR_UNSUPPORTED)
+    CLog::Log(LOGINFO, "Display is not HDR capable or cannot be detected");
+  else
+    CLog::Log(LOGINFO, "Display HDR capable is detected and Windows HDR switch is %s",
```
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1538]: Please update to the current log standards using `{}`
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 21 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4916]: Please update to the current log standards using `{}`

File: xbmc/Application.cpp (hunk 22 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4929]: Please update to the current log standards using `{}`

File: xbmc/Application.cpp (hunk 13 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4942]: Please update to the current log standards using `{}`

File: xbmc/Application.cpp (hunk 14 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4947]: Please update to the current log standards using `{}`

File: xbmc/Application.cpp (hunk 15 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4952]: Please update to the current log standards using `{}`

File: xbmc/Application.cpp (hunk 16 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4956]: Please update to the current log standards using `{}`

File: xbmc/Application.cpp (hunk 17 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4960]: Please update to the current log standards using `{}`

File: xbmc/Application.cpp (hunk 18 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4975]: Please update to the current log standards using `{}`

File: xbmc/Application.cpp (hunk 19 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4978]: Please update to the current log standards using `{}`

File: xbmc/Application.cpp (hunk 20 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4981]: Please update to the current log standards using `{}`

File: xbmc/platform/android/PlatformAndroid.cpp (hunk 23 above)
Comment (jenkins4kodi) [inline xbmc/platform/android/PlatformAndroid.cpp:51]: Please update to the current log standards using `{}`

File: xbmc/platform/win32/WIN32Util.cpp (hunk 24 above)
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1529]: Please update to the current log standards using `{}`

File: xbmc/platform/win32/WIN32Util.cpp (hunk 25 above)
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1530]: Please update to the current log standards using `{}`

File: xbmc/platform/win32/WIN32Util.cpp (hunk 11 above)
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1533]: Please update to the current log standards using `{}`

File: xbmc/platform/win32/WIN32Util.cpp (hunk 26 above)
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1538]: Please update to the current log standards using `{}`

**Review by jenkins4kodi — COMMENTED** [review]
For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

**Comment by lrusak** [comment]
jenkins build this please

File: xbmc/Application.cpp (hunk 21 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4916]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 22 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4929]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 13 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4942]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 14 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4947]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 15 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4952]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 16 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4956]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 17 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4960]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 18 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4975]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 19 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4978]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/Application.cpp (hunk 20 above)
Comment (jenkins4kodi) [inline xbmc/Application.cpp:4981]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/android/PlatformAndroid.cpp (hunk 23 above)
Comment (jenkins4kodi) [inline xbmc/platform/android/PlatformAndroid.cpp:51]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/win32/WIN32Util.cpp (hunk 24 above)
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1529]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/win32/WIN32Util.cpp (hunk 25 above)
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1530]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/win32/WIN32Util.cpp (hunk 11 above)
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1533]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

File: xbmc/platform/win32/WIN32Util.cpp (hunk 26 above)
Comment (jenkins4kodi) [inline xbmc/platform/win32/WIN32Util.cpp:1538]: Please update to the current log standards using `{}`.

For more information please see the [libfmt documentation](https://fmt.dev/latest/syntax.html)

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by lrusak** [comment]
jenkins build this please

**Comment by fuzzard** [comment]
jenkins build this please

**Comment by fuzzard** [comment]
This good to go now? Had some troubles getting Jenkins to greenlight everything, but all good now from that perspective

File: xbmc/Application.cpp [hunk 27]
```diff
@@ -4999,6 +4857,80 @@ void CApplication::SetLoggingIn(bool switchingProfiles)
...
+              (CServiceBroker::GetCPUInfo()->GetCPUCount() == 1) ? "" : "s");
+
+  // Any system info logging that is unique to a platform
+  m_ServiceManager->GetPlatform().PlatformSyslog();
+
+#if defined(__arm__) || defined(__aarch64__)
+  if (CServiceBroker::GetCPUInfo()->GetCPUFeatures() & CPU_FEATURE_NEON)
+    CLog::Log(LOGINFO, "ARM Features: Neon enabled");
+  else
+    CLog::Log(LOGINFO, "ARM Features: Neon disabled");
```
Comment (howie-f) [inline xbmc/Application.cpp:4917]:
```
CLog::Log(LOGINFO, "ARM Features: Neon {}",
  (CServiceBroker::GetCPUInfo()->GetCPUFeatures() & CPU_FEATURE_NEON) ? "enabled" : "disabled");
```

File: xbmc/platform/darwin/osx/PlatformDarwinOSX.cpp [hunk 28]
```diff
@@ -8,27 +8,42 @@
...
-  // Configure and possible manually start the helper.
-  XBMCHelper::GetInstance().Configure();
-
   CWinSystemOSXGL::Register();
 
   CCocoaPowerSyscall::Register();
 
+  std::string install_path;
+
+  install_path = CUtil::GetHomePath();
```
Comment (howie-f) [inline xbmc/platform/darwin/osx/PlatformDarwinOSX.cpp:35]: `std::string install_path(CUtil::GetHomePath());`

**Review by howie-f — APPROVED** [review]
no negative impact seen at linux runtime
