### PR TITLE
Override joystick controls per-keyname (fixes userdata config override)

### LINKED ISSUE #15316: Kodi ignores custom joystick.xml in special://home/userdata/keymaps/
### Describe the bug

I use a gamepad exclusively to control Kodi and hence it is important to configure it to suit my needs.

I create a custom file `special://home/userdata/keymaps/joystick.xml`, based on the default `joystick.xml` found in the system directory. Kodi totally ignores `joystick.xml` in the userdata directory, located in `/home/kodi/.kodi/userdata/keymaps/`. A workaround I found is to delete the default `joystick.xml` in the system directory (Kodi installation directory), however this file will be recreated any time Kodi is updated.

In the debug log, I can verify that Kodi loads both XML configuration files when both are present and Kodi ignores the custom configuration in the XML file in the userdata directory.

## Expected Behavior

The joystick XML file in the userdata directory must override the default XML file in the system directory.

## Actual Behavior

Kodi ignores the configuration in the userdata directory when a default configuration exists in the system directory.

## Possible Fix

N/A

### To Reproduce

* Install Kodi and use a gamepad to control it.

* Create a custom `joystick.xml` file in `/home/kodi/.kodi/userdata/keymaps/` directory to override the default `joystick.xml` in Kodi installation.

* Kodi totally ignores the custom configuration file `joystick.xml`.

### Debuglog

My custom [joystick.xml](https://paste.kodi.tv/xagikegitu.kodi) in `/home/kodi/.kodi/userdata/keymaps/joystick.xml`.

[Kodi debug log](https://paste.kodi.tv/tevekerofa.kodi) when default `joystick.xml` has been deleted and custom joystick configuration works.

[Kodi debug log](https://paste.kodi.tv/zasifiyeca.kodi) when default `joystick.xml` is present and custom `joystick.xml` is totally ignored.

### Screenshots 

N/A

### Your Environment

Linux Ubuntu Xenial, Kodi version from master commit `3aac935a7e712e7a303763c649351d1569241cae`.

### PR DESCRIPTION
**Pull request by arucard21**
## Description

This PR fixes a bug where the custom joystick configuration from the userdata folder was no longer being applied. This has been fixed by overriding the configuration per keyname. 

## Motivation and Context

This fixes a bug that no longer allowed user-provided joystick configuration. 

The custom configuration only needs to contain the modified controls and the default controls will still be used from the default configuration file. This might be slightly different from previous behavior but it seems like a reasonable solution. It was also the only solution that I could get to work correctly.

Fixes #15316.
Fixes PR #15347 (The change in that PR didn't work correctly. This PR is based on the code changes in that PR).

## How Has This Been Tested?

This has been tested manually using a PS4 controller and the `peripheral.joystick` binary addon (master branch).

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed (Test 490: `TestWebServer.CanHeadFile` already failed before this change)

### CODE REVIEW

File: xbmc/input/JoystickMapper.cpp [hunk 1]
```diff
@@ -38,6 +38,15 @@ void CJoystickMapper::MapActions(int windowID, const TiXmlNode *pDevice)
   if (controllerId.empty())
     return;
 
+  // Update Controller IDs
```
Comment (garbear) [inline xbmc/input/JoystickMapper.cpp]: Is this block of code still needed?

**Comment by garbear** [comment]
> This has been fixed by overriding the configuration per keyname.

Can you test to see if overriding a keyname with an empty action or `noop` deletes the system configuration for that keyname? If so, then this fix is perfect.

File: xbmc/input/JoystickMapper.cpp (hunk 1 above)
Comment (arucard21) [reply xbmc/input/JoystickMapper.cpp]: I think this block is the one that's actually needed. But I think the other code (in the if-statement) can be removed. I will do that.

**Comment by arucard21** [comment]
> Can you test to see if overriding a keyname with an empty action or noop deletes the system configuration for that keyname?

I'll try to test that soon (though I think it should work that way). Do you mean to test both with an empty XML tag as well as `noop` in the XML tag? Should an empty XML tag work the same as `noop`?

File: xbmc/input/JoystickMapper.cpp [hunk 2]
```diff
@@ -38,6 +38,15 @@ void CJoystickMapper::MapActions(int windowID, const TiXmlNode *pDevice)
...
+  if (std::find(m_controllerIds.begin(), m_controllerIds.end(), controllerId) == m_controllerIds.end())
+    m_controllerIds.emplace_back(controllerId);
+
+  // Create/overwrite keymap
+  auto &keymap = m_joystickKeymaps[controllerId];
```
Comment (Rechi) [inline xbmc/input/JoystickMapper.cpp]: left align `&`, https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#52-pointer-and-reference-types

File: xbmc/input/JoystickMapper.cpp [hunk 3]
```diff
@@ -38,6 +38,15 @@ void CJoystickMapper::MapActions(int windowID, const TiXmlNode *pDevice)
...
+  if(!keymap)
```
Comment (Rechi) [inline xbmc/input/JoystickMapper.cpp]: add a space between `if` and `(`, https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#34-whitespace

**Comment by Rechi** [comment]
@arucard21 please squash the commits.

**Comment by garbear** [comment]
> I'll try to test that soon (though I think it should work that way). Do you mean to test both with an empty XML tag as well as noop in the XML tag? Should an empty XML tag work the same as noop?

Correct, they should be the same, but it's worth testing to identify pre-existing issues to minimize surprises later

**Comment by arucard21** [comment]
@Rechi 
> @arucard21 please squash the commits.

I don't mind doing this but isn't it easier to squash the commits when merging the pull request? It should be an option when merging the pull request and the end result should be the same. I'm only mentioning this because I generally prefer not to force push commits. And it avoids having to squash multiple times, should another commit be needed. 

Of course, if you still want me to, just let me know. I still need to test this (as @garbear suggested) so I'll need a bit more time anyway.

**Comment by arucard21** [comment]
I've tested this now and it currently works like this:
* If you have `noop` defined in your custom xml, the default behavior is overridden and that button does nothing when pressed. 
* If you put an element in your custom xml but leave it empty, the default behavior is used
* If you leave out an element entirely from your custom XML, the default behavior is used. 

So the `noop` action works but the empty element does not imply `noop` and instead works as though the element was not provided at all. I actually think it's always worked like that because otherwise there'd be no need for the explicit `noop` action to exist. I also looked at the code changes again, and I don't think anything I did could have influenced this part of the behavior. So if this needs to be fixed, it might be better as a separate PR.

Let me know if I still need to squash the commits beforehand or if you can just do it while merging the PR.

**Comment by Rechi** [comment]
Yes, please squash the commits.

**Comment by arucard21** [comment]
It should be squashed now.

**Comment by Rechi** [comment]
jenkins build this please

**Comment by garbear** [comment]
Thanks for testing! I was wrong about the empty tag, but given the existence of `noop` we don't need duplicate behavior. no effect is a more appropriate result of an empty tag anyway.

**Review by garbear — APPROVED** [review]

**Comment by garbear** [comment]
Since joining my startup my free time just isn't what it was. I'm glad you took the initiative to open a PR. Kodi is better off for it. Big thumbs up 👍

**Comment by arucard21** [comment]
Is anything still needed to get this merged?

**Comment by Rechi** [comment]
@garbear  please always set the version label and milestone before or right after merging a PR.

**Comment by Wintermute0110** [comment]
Can this merged into Leia as well?

**Comment by arucard21** [comment]
@garbear 
@Rechi 
I'd also like to see this in Leia, assuming a v18.5 release is still forthcoming. Can I just add the label "Backport: Needed"? Or does something else need to be done?

**Comment by DaVukovic** [comment]
You have to create a similar PR against the Leia branch.

If there's enough PRs for a 18.5 release then nothing speaks against that. Not sure how many backports already exists after the 18.4 release. This PR sounds like somewhat reasonable to be backported. So I'll set the label.

**Comment by arucard21** [comment]
@DaVukovic Thanks for explaining it. I've created #16609 for this backport now. I assume someone else has to add those labels since I don't seem to be able to do that.
