### PR TITLE
[PVR] Fix crashes on Kodi startup caused by inconsistent TV database.…

### LINKED ISSUE #20145: PVR frequently segfault's on startup...
### Describe the bug
... when trying to set GroupName but obtaining an instance for client id 0 fails. i believe client id 0 is invalid.
it happens frequently on startup and can be fixed by removing `TV38.db` so this one gets recreated.
lasted 16 days functional until crashing and the crash is reproducable. i saved the database files.
```
-rw-r--r--  1 nexus nexus   131072 16. Sep 19:25 TV38.db        <--- this is created new and functional
-rw-r--r--  1 nexus nexus   143360 31. Aug 16:35 TV38.db.crash  <--- this is not corrupted, can be accessed via sqlite3
-rw-r--r--  1 nexus nexus   143360 16. Sep 09:07 TV38.db.crash2
```

### To Reproduce
this setup with kodi master, pvr.hts and the tvheadend server is restarted dialy.. after 16 days it crashes on startup but no idea why (ok, client id 0 invalid)

### Debuglog
https://paste.kodi.tv/gehujasove.kodi

```
2021-09-16 18:59:47.325 T:1694    DEBUG <general>: AddOnLog: pvr.hts: event id:10004823 channel:12784202 start:1631829900 stop:1631831100 title:Tagesschau vor 20 Jahren desc:
2021-09-16 18:59:47.324 T:1695    DEBUG <general>: AddOnLog: pvr.hts: receive message [eventAdd]
2021-09-16 18:59:47.326 T:1700    ERROR <general>: Skipped 73 duplicate messages..
2021-09-16 18:59:47.324 T:1700    ERROR <general>: SetGroupName: Unable to obtain instance for client id: 0
```

## Additional context
a `TV38.db.crash` database is no problem for Matrix. it doesnt crash here.
i suspect that https://github.com/xbmc/xbmc/pull/19831 introduced this.

trying a build before this merge commit (which is the merge of https://github.com/xbmc/xbmc/pull/19786) the crash doesn't happen, even though a 'disfunctional' `TV38.db` is already on the filesystem.
however updating to current master after that also works fine. not sure how long it will.

### Your Environment
Used Operating system:

 - [X] Linux

 - Operating system version/name: Debian Bullseye
 - Kodi version: current master

### PR DESCRIPTION
**Pull request by ksooo**
… Improve logging.

Fixes #20145 

@howie-f an me did extensive runtime-tests.

@phunkyfish mind taking a look at the code change?

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins errors are unrelated:

```log
16:08:30 Running testsuite...
16:08:30 [==========] Running 671 tests from 92 test suites.
16:08:30 [----------] Global test environment set-up.
16:08:30 Setup of basic environment failed.
16:08:35 Clean shutdown of TestGlobalPattern1
16:08:35 /xbmc/project/BuildDependencies/msys64/usr/bin/sed: can't read C:\Users\Kodi\Kodi\jenkins\builds\workspace\WIN-32\gtestresults.xml: No such file or directory
16:08:36 Could Not Find C:\Users\Kodi\Kodi\jenkins\builds\workspace\WIN-32\gtestresults.xml
16:08:36         1 file(s) moved.
16:08:36 Done running testsuite
```

File: xbmc/pvr/PVRDatabase.cpp [hunk 1]
```diff
@@ -449,9 +450,9 @@ bool CPVRDatabase::Delete(const CPVRChannelGroup& group)
   return RemoveChannelsFromGroup(group) && DeleteValues("channelgroups", filter);
 }
 
-bool CPVRDatabase::Get(CPVRChannelGroups& results)
+int CPVRDatabase::Get(CPVRChannelGroups& results)
 {
-  bool bReturn = false;
+  int iLoaded = false;
```
Comment (howie-f) [inline xbmc/pvr/PVRDatabase.cpp:455]: even though `false` implicitly coverts to `0` i'd still do `int iLoaded = 0;`

File: xbmc/pvr/channels/PVRChannelGroup.cpp [hunk 2]
```diff
@@ -469,11 +475,71 @@ int CPVRChannelGroup::LoadFromDb()
...
+  {
+    CSingleLock lock(m_critSection);
+    for (const auto& member : results)
+    {
+      // Consistency check.
+      if (member->ClientID() > 0 && member->ChannelUID() > 0 && member->IsRadio() == IsRadio())
+      {
+        m_sortedMembers.emplace_back(member);
+        m_members.insert(
+            std::make_pair(std::make_pair(member->ClientID(), member->ChannelUID()), member));
```
Comment (howie-f) [inline xbmc/pvr/channels/PVRChannelGroup.cpp:492]: this is safe to emplace
```suggestion
        m_members.emplace(std::make_pair(member->ClientID(), member->ChannelUID()), member);
```

**Review by howie-f — APPROVED** [review]
thanks, i didn't look too close for differences to the well tested version. this one does definitely cope with my inconsistent `TV38.db.crash` as is.

File: xbmc/pvr/PVRDatabase.cpp (hunk 1 above)
Comment (ksooo) [reply xbmc/pvr/PVRDatabase.cpp:455]: Ooops, will change that.

File: xbmc/pvr/channels/PVRChannelGroup.cpp (hunk 2 above)
Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroup.cpp:492]: Cool, thanks.

Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroup.cpp]: I changed all occurrences of `m_members.insert`

File: xbmc/pvr/channels/PVRChannelGroup.cpp [hunk 3]
```diff
@@ -469,11 +475,71 @@ int CPVRChannelGroup::LoadFromDb()
...
+  {
+    const std::shared_ptr<CPVRDatabase> database = CServiceBroker::GetPVRManager().GetTVDatabase();
+    if (!database)
+    {
+      CLog::LogF(LOGERROR, "No TV database");
+      return;
+    }
+
+    // Note: We must lock the db the whole time, otherwise races may occur.
+    database->Lock();
```
Comment (neo1973) [inline xbmc/pvr/channels/PVRChannelGroup.cpp:525]: Such naked Lock/Unlock always give me a shiver... What are the thoughts on renaming these member functions to lowercase `lock` and `unlock` so that a `std::lock_guard` can be used?

Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroup.cpp:525]: This is something for another day/PR.

File: xbmc/pvr/channels/PVRChannelGroups.cpp [hunk 4]
```diff
@@ -313,8 +313,8 @@ bool CPVRChannelGroups::LoadFromDb()
               m_bRadio ? "radio" : "TV");
 
   // load all groups from the database
-  database->Get(*this);
-  CLog::LogFC(LOGDEBUG, LOGPVR, "Fetched {} {} groups from the database", m_groups.size(),
+  const int iLoaded = database->Get(*this);
```
Comment (phunkyfish) [inline xbmc/pvr/channels/PVRChannelGroups.cpp:316]: `const` has no effect here? Do you mean to just infer there is no need to change it, which is fine BTW.

**Review by phunkyfish — APPROVED** [review]
Just a comment which can be ignored. Nice work.

File: xbmc/pvr/channels/PVRChannelGroups.cpp (hunk 4 above)
Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroups.cpp:316]: > infer there is no need to change it

This. As you know I'm a big fan of Item 21 in Scott Meyers' book Effective C++ ("Use const whenever possible").

File: xbmc/pvr/channels/PVRChannelGroup.cpp [hunk 5]
```diff
@@ -469,11 +475,71 @@ int CPVRChannelGroup::LoadFromDb()
...
+  {
+    CSingleLock lock(m_critSection);
+    for (const auto& member : results)
+    {
+      // Consistency check.
+      if (member->ClientID() > 0 && member->ChannelUID() > 0 && member->IsRadio() == IsRadio())
+      {
+        m_sortedMembers.emplace_back(member);
+        m_members.emplace(
+            std::make_pair(std::make_pair(member->ClientID(), member->ChannelUID()), member));
```
Comment (howie-f) [inline xbmc/pvr/channels/PVRChannelGroup.cpp:492]: superfluous `std::make_pair` here, we only need one :) emplace will make the std::pair by forwarding its arguments

`m_members.emplace(std::make_pair(member->ClientID(), member->ChannelUID()), member);`

File: xbmc/pvr/channels/PVRChannelGroup.cpp [hunk 6]
```diff
@@ -511,7 +577,7 @@ bool CPVRChannelGroup::UpdateFromClient(const std::shared_ptr<CPVRChannelGroupMe
       groupMember->SetGroupID(GroupID());
 
     m_sortedMembers.emplace_back(groupMember);
-    m_members.insert(std::make_pair(channel->StorageId(), groupMember));
+    m_members.emplace(std::make_pair(channel->StorageId(), groupMember));
```
Comment (howie-f) [inline xbmc/pvr/channels/PVRChannelGroup.cpp:580]:
```suggestion
    m_members.emplace(channel->StorageId(), groupMember);
```

File: xbmc/pvr/channels/PVRChannelGroup.cpp [hunk 7]
```diff
@@ -719,7 +758,7 @@ bool CPVRChannelGroup::AppendToGroup(const std::shared_ptr<CPVRChannel>& channel
       newMember->SetClientPriority(allGroupMember->ClientPriority());
 
       m_sortedMembers.emplace_back(newMember);
-      m_members.insert(std::make_pair(allGroupMember->Channel()->StorageId(), newMember));
+      m_members.emplace(std::make_pair(allGroupMember->Channel()->StorageId(), newMember));
```
Comment (howie-f) [inline xbmc/pvr/channels/PVRChannelGroup.cpp:761]: and here

**Review by howie-f — COMMENTED** [review]
nothing serious

File: xbmc/pvr/channels/PVRChannelGroup.cpp (hunk 5 above)
Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroup.cpp:492]: Nice. Did not know this. Will change.

File: xbmc/pvr/channels/PVRChannelGroup.cpp (hunk 6 above)
Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroup.cpp:580]: Will change.

File: xbmc/pvr/channels/PVRChannelGroup.cpp (hunk 7 above)
Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroup.cpp:761]: :+1:

File: xbmc/pvr/channels/PVRChannelGroup.cpp [hunk 8]
```diff
@@ -99,12 +99,18 @@ bool CPVRChannelGroup::Load(
...
 
   for (const auto& groupMember : m_members)
   {
     auto channel = channels.find(groupMember.first);
+    if (channel == channels.end())
+    {
+      CLog::Log(LOGERROR, "Cannot find group member '{},{}' in channels!", groupMember.first.first,
+                groupMember.first.second);
+      // No workaround here, please. We need to find and fix the root cause of this case!
+    }
```
Comment (AlwinEsch) [inline xbmc/pvr/channels/PVRChannelGroup.cpp:113]: With a note, I don't really understand here, is the following crash accepted and only the previous log entry as information from where?

The following `(*channel).second` would probably not work :thinking: .

Comment (AlwinEsch) [reply xbmc/pvr/channels/PVRChannelGroup.cpp:113]: Or has you forgot a `return false;`?

Comment (AlwinEsch) [reply xbmc/pvr/channels/PVRChannelGroup.cpp:113]: Maybe on the log, add also the amount of channels, think good to know:
```cpp
      CLog::Log(LOGERROR, "Cannot find group member '{},{}' in {} channels!", groupMember.first.first,
                groupMember.first.second, channels.size());
```

Comment (howie-f) [reply xbmc/pvr/channels/PVRChannelGroup.cpp:113]: inconsistency of the TV database occurred twice with a distance of about 2 weeks at my end. both times after a clean shutdown of kodi. we didn‘t really find the root cause, but this pr corrects the db then and throws out the warning…

doesnt mean it can never happen again but it can cope with it now

Comment (ksooo) [reply xbmc/pvr/channels/PVRChannelGroup.cpp:113]: The comment means that I want to crash (due to the following call to `(*channel).second`, yes. I also could assert() or throw. I forgot nothing and was hoping the comment makes the intention clear.

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
WIN-32 and WIN64 jenkins errors are unrelated.
