### PR TITLE
fixed: NFO/tag loading for http/https sources was broken (fixes #15481)

### LINKED ISSUE #15481: Kodi 18 can't load TV episode nfo files over http
### Describe the bug
Here is a clear and concise description of what the problem is:

I have a library set up using local nfo files only that are hosted over http. Adding a TV Show source over http results in shows being imported but no episodes being imported. Works properly over SMB. works properly over HTTP in Kodi 17.6. Based on the debug log it appears that the episode nfo files are not being read/seen.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
TV Show episodes should be imported over http.

## Actual Behavior
TV Show episodes are not imported into the library.

## Possible Fix
Change to smb protocol instead, or revert to Kodi 17.6.

### To Reproduce
1. Add video source using an https URL.
2. Set content of a subfolder to "TV Show" using local information only.
3. Scan for new content.

### Debuglog
The debuglog can be found here:
https://paste.kodi.tv/ufesetozed.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:
https://forum.kodi.tv/showthread.php?tid=340621&pid=2820560#pid2820560

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Files are hosted on a debian linux server over nginx. nfo files are hosted as text/plain with utf8 encoding. Normally used with a mariadb database, but the issue occurs regardless of whether a database is in use.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [X ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 64-bit
 - Kodi version: 18

### PR DESCRIPTION
**Pull request by arnova**
## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/video/tags/VideoInfoTagLoaderFactory.cpp [hunk 1]
```diff
@@ -22,10 +22,6 @@ IVideoInfoTagLoader* CVideoInfoTagLoaderFactory::CreateLoader(const CFileItem& i
                                                               bool lookInFolder,
                                                               bool forceRefresh)
 {
-  // don't try to read tags for streams
-  if (item.IsInternetStream())
-    return nullptr;
-
```
Comment (fritsch) [inline xbmc/video/tags/VideoInfoTagLoaderFactory.cpp]: @notspiff you directly programmed it like this. Removing it without discussion sounds not right.

Comment (arnova) [reply xbmc/video/tags/VideoInfoTagLoaderFactory.cpp]: Alternatively we could move the NFO-reading up so it's before the IsInternetStream()-check, although I don't see why any of the stuff below it could be a problem for http/https.

Comment (notspiff) [reply xbmc/video/tags/VideoInfoTagLoaderFactory.cpp]: in principle there is no problem loading for http(s). but some servers will not like the Exists() and some for some streaming protocols it makes little sense. so i added it to lessen chance of issues and log spam. i don't see a big issue removing it as such, but that was the logic.

Comment (arnova) [reply xbmc/video/tags/VideoInfoTagLoaderFactory.cpp]: Yes, I already suspected that. Since we've ran into this issue before I think we should see whether we can find another way to flag/distinguish between actual "streams" and "files" served from http/https but that's beyond the scope of this PR.

Comment (DaveTBlake) [reply xbmc/video/tags/VideoInfoTagLoaderFactory.cpp]: Also be aware of shoutcasts (internet radio). I don't know if they would get to this part of code, but I know that they are often over looked and we had issues with determining it was a shoutcast outside the player (the player knows but does not publish the fact)

Comment (notspiff) [reply xbmc/video/tags/VideoInfoTagLoaderFactory.cpp]: If somebody tries to scan a shoutcast station into their video library they deserve it all.

**Comment by arnova** [comment]
So ,this is good to go?

**Comment by notspiff** [comment]
Do it.

**Comment by Rechi** [comment]
jenkins build this please

**Comment by arnova** [comment]
build error unrelated
