### PR TITLE
[upnp] picture playback and thumb fixes

### LINKED ISSUE #21734: Kodi does not show images via dlna
### Describe the bug
I have a dlna server on my network and a couple of days ago I decided to add some photos to it.However, kodi, which can play stuff via dlna (already tested with audio and video files) does not show any of the image files.

## Expected Behavior
Kodi should show the image files from the dlna server.

## Actual Behavior
As seen in the screenshot below, kodi even fails to create the thumbnails for the images and it just goes black when it "plays" an image.

## Possible Fix
No idea.

### To Reproduce
1. Create a dlna server on the network and have it share some image files.
2. Enable kodi's upnp support in settings.
3. Add the dlna server as a source for image content
4. Browse to it and notice what I mention above.

### Debuglog
The debuglog can be found here:
http://ix.io/46Iv

### Screenshots 
Screenshot of kodi failing to even create thumbnails for the images.
screenshot00001

## Additional context or screenshots (if appropriate)
As I said above, kodi does play video and audio files from that same dlna server. 
However, the images do "play" on other apps that support dlna, e.g
- vlc on windows, linux and android
- bubbleupnp on android 
- the dlna player on a smart tv (panasonic viera)

The dlna server mentioned above is minidlna (v1.3.0), but gerbera (v1.11) was tested too, althought it had the same results. Moreover, there are no errors in minidlna's log for kodi's failure to "play" them.

Although the errors in the log are identical for all the kodi versions mentioned below, the log above is from the libreelec 11 nightly x64 installation that comes with kodi 20a2. This installation will soon (= by August 15th) be removed (possibly in favor of libreelec 10 nightly x64), so no other log will be available from that one. 
The same applies for the libreelec 11 nightly installation on the rpi, although it will probably be available until early to mid September. 
So, if any fixes for it do reach kodi 20, please backport them for kodi 19 as well.

Last but not least, I would like to use the word "render" instead of "play" for the images above, if everyone agrees. Sounds better and more technical.

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Tested on all these
Debian testing/unstable x64 with kodi 19.4
Libreelec stable 9.2.6 x64 with kodi 18.9
Libreelec stable 10.0.2 x64 with kodi 19.4
Libreelec nightly 11 x64 with kodi 20a2
Libreelec nightly 11 armv7l (rpi3b+) with kodi 20a2
Coreelec stable 9.2.8 aarch64 (amlogic s905 tvbox) with kodi 18.9

 - Kodi versions: 18.9, 19.4 and 20a2 as explained above

### PR DESCRIPTION
**Pull request by enen92**
## Description
This PR brings essentially two fixes:

- While testing UPNP picture playback I've found out kodi issues stat requests for all upnp object ids when browsing upnp directories in order to check the thumb hash of each item while we navigate. This not only doesn't work since all upnp items do not have thumbs (they should be provided when filling each item with the content provided by the upnp server), brings unnecessary requests to the server (e.g. we try to stat every object along with stuff like [objectid]/folder.jpg just like regular directories) and are also a common source of crashes (I got a few...). Also, it has the side effect of messing with upnp cache (and directory listings) since those requests ask for the metadata of the item. In those cases the response provided by libplatinum [is limited to 1 item](https://github.com/xbmc/xbmc/blob/master/lib/libUPnP/Platinum/Source/Devices/MediaServer/PltSyncMediaBrowser.cpp#L427). So, we rewrite the cache associated to already existing object ids (directories) for no reason - breaking the folder content (see screenshots). 

- Fixes "playback" (actually the slideshow) for upnp picture items. The image uri was never set on the item and the slideshow player doesn't really resolve vfs addresses like videoplayer does. Since we have the picture url when browsing the directory we can simply fill the dynpath and set the thumb at that point. There's no need for further resolving afterwards. This code dates way back from the dynpath addition....
This should bring minimal support for upnp picture viewing.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/21734
Can well fix a lot of other upnp issues/crashes...

## How has this been tested?
With minidlna installed on a raspberry pi, serving video, audio and picture content to kodi.

## What is the effect on users?
Less crashes related to upnp. Should be able to see pictures served via upnp/dlna as well as their thumbs. This does not affect/changes thumbs behaviour for regular video files.

## Screenshots (if appropriate):
**Before:**
(picture root folder broken)
image
(after fixing directory access with 6c3140ae6472a6ef379879ecbd4550a839c63929 - no thumbs and no playback)
image
image

**PR:**
image
image
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [x] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

File: xbmc/network/upnp/UPnPInternal.cpp [hunk 1]
```diff
@@ -1015,8 +1015,8 @@ CFileItemPtr BuildObject(PLT_MediaObject* entry,
         UPNP::PopulateTagFromObject(*pItem->GetMusicInfoTag(), *entry, res, upnp_service);
 
     } else if(image) {
-        //CPictureInfoTag* tag = pItem->GetPictureInfoTag();
-
+      //! @todo fill pictureinfotag?
```
Comment (garbear) [inline xbmc/network/upnp/UPnPInternal.cpp:1018]: Did you mean to include this feature in the PR?

**Review by garbear — APPROVED** [review]
Description is thorough, before pictures show problem, after pictures show fix. Easy approve.

File: xbmc/network/upnp/UPnPInternal.cpp (hunk 1 above)
Comment (enen92) [reply xbmc/network/upnp/UPnPInternal.cpp:1018]: no, I just noticed that for all other content kodi populates the infotag from the received `PLT_MediaObject` while for pictures we don't (and we have that line of code commented). Not sure if there is any info from the response that might be usable/important for upnp pictures since they are a bit different. Maybe some exif tags might be pre-populated, hence decided to keep a todo there. Doesn't necessarily mean I'll do it later though.

File: xbmc/pictures/GUIWindowSlideShow.cpp [hunk 2]
```diff
@@ -1326,7 +1326,7 @@ void CGUIWindowSlideShow::GetCheckedSize(float width, float height, int &maxWidt
 std::string CGUIWindowSlideShow::GetPicturePath(CFileItem *item)
 {
   bool isVideo = item->IsVideo();
-  std::string picturePath = item->GetPath();
+  std::string picturePath = item->GetDynPath();
```
Comment (Montellese) [inline xbmc/pictures/GUIWindowSlideShow.cpp:1329]: I'm not up-to-date with the whole path / dyn path design / approach. Did you make sure that non-UPnP slideshows still work as well?

**Review by Montellese — APPROVED** [review]
Looks good to me.

File: xbmc/pictures/GUIWindowSlideShow.cpp (hunk 2 above)
Comment (enen92) [reply xbmc/pictures/GUIWindowSlideShow.cpp:1329]: Yeap, tested all is working as before. GetDynPath fallsback to Path if the dynamic path is not defined. We don't really resolve urls for pictures so in all other cases the dynpath is empty.
Even python plugins just add listitems with the path to the final picture url.
