### PR TITLE
[profiles] honor lock state of media sources

### LINKED ISSUE #20687: Locked source state not honored in favorites
### Describe the bug
Usually, media from locked sources aren't even shown to the user unless the source is unlocked first. But if you favorite such media, they are displayed despite of the lock state and are freely accessible while the source is locked.

## Expected Behavior
A favorite from a locked source should not be visible unless the corresponding source was unlocked first (or master mode is enabled).

## Actual Behavior
Locked but favorited media is always visible and is played without having to unlock the source first.

## Possible Fix
Either don't show these favorites unless their source was unlocked or master-mode was enabled (preferred solution).
Or at least present the user with the appropriate unlock dialog before playing.

### To Reproduce
1. Favorite a movie
2. Lock the source of the movie
3. Access your favorites
4. See/Play the locked title

### Your Environment
Used Operating system:
 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreElec 10.0.1
 - Kodi version: 19.3

### PR DESCRIPTION
**Pull request by howie-f**
## Description
closes https://github.com/xbmc/xbmc/issues/20687

this is the continuation of patching profiles mediasource locks. ~~the lock will now be honored if media from a restricted source is added to favourites.~~

EDIT: changed the approach:
favourite items are hidden now if the matching mediasource is restricted+locked and master mode is not active.

## How has this been tested?
runtime test on linux

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

**Comment by howie-f** [comment]
maybe @fuzzard can review this? you were involved in my very first contribution that touched exactly this area

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp [hunk 1]
```diff
@@ -458,6 +492,18 @@ static int PlayMedia(const std::vector<std::string>& params)
   if (!item.m_bIsFolder && item.IsPlugin())
     item.SetProperty("IsPlayable", true);
 
+  bool restricted{false};
+  if (!item.m_bIsFolder && !item.IsPlayList())
+  {
+    if (item.IsAudio())
+      restricted = IsVideoOrAudioRestricted(item, "audio");
```
Comment (lrusak) [inline xbmc/interfaces/builtins/PlayerBuiltins.cpp:499]: You are already using the CFileItem as a param. You shouldn't need the "type".

Comment (lrusak) [inline xbmc/interfaces/builtins/PlayerBuiltins.cpp:499]: You can probably just shorten this whole block.

```suggestion
      if (IsVideoOrAudioRestricted(item))
        return false:
```

Comment (howie-f) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:499]: indeed, thanks ☺️

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp [hunk 2]
```diff
@@ -39,6 +41,34 @@
 #include "Autorun.h"
 #endif
 
+namespace
+{
+bool IsMediasourceRestricted(const CFileItem item)
```
Comment (howie-f) [inline xbmc/interfaces/builtins/PlayerBuiltins.cpp:46]: forgot to pass it by reference. in the next round

File: xbmc/GUIPassword.h [hunk 3]
```diff
@@ -66,6 +66,17 @@ class CGUIPassword : public ISettingCallback
   void RemoveSourceLocks();
   bool IsDatabasePathUnlocked(const std::string& strPath, VECSOURCES& vecSources);
 
+  /*! \brief Helper function to test if the user is allowed to access the path
+   by looking up the matching Mediasource. Used internally by CheckMenuLock.
```
Comment (fuzzard) [inline xbmc/GUIPassword.h:70]: This comment isnt exactly correct now if its now being used externally

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp [hunk 4]
```diff
@@ -39,6 +41,34 @@
...
+{
+  const std::shared_ptr<CProfileManager> profileManager =
+      CServiceBroker::GetSettingsComponent()->GetProfileManager();
```
Comment (fuzzard) [inline xbmc/interfaces/builtins/PlayerBuiltins.cpp:49]: GetSettingsComponent returns a pointer, so theres a possibility of it being a nullptr.
I know this style is used everywhere, but i think we should be more defensive in general (eg check getsettignscomponent, log nullptr/fail method). Just my thoughts.

Comment (howie-f) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:49]: ok, i'm thinking of
```c
if (!componentSettings)
{
 log(LOGERROR, "peng.. nullptr {}" , __func__);
 return false; // claim this mediasource is not locked, just catch it in thje log
}
something better you have in mind?
```

Comment (fuzzard) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:49]: Essentially, yeah that'd be fine

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp [hunk 5]
```diff
@@ -39,6 +41,45 @@
...
 #endif
 
+namespace
+{
+bool IsMediasourceRestricted(const CFileItem& item)
+{
+  const auto settingsComponent = CServiceBroker::GetSettingsComponent();
+  if (!settingsComponent)
+  {
+    CLog::LogF(LOGERROR, "GetSettingsComponent() returned nullptr.");
```
Comment (fuzzard) [inline xbmc/interfaces/builtins/PlayerBuiltins.cpp:51]: This is just an idle comment, no need for action.
However i wonder if we should "standardise" a log string. From memory @garbear knew all the ins and outs of __FUNCTION__ and its variants on different platforms.

Something like "CCLASS::FUNC - message". Just so its more obvious exactly where a log message is being generated.

**Review by fuzzard — APPROVED** [review]

File: xbmc/interfaces/builtins/PlayerBuiltins.cpp (hunk 5 above)
Comment (howie-f) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:51]: yes, coolest would be this https://en.cppreference.com/w/cpp/utility/source_location. bet until then we'll have to grep the codebase for interesting messages without __ func __ :/

Comment (garbear) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:51]: `source_location` looks nice but doesn't handle the class name. IIRC on windows `__FUNCTION__` includes the class name. Also IIRC not all compilers have a way to "detect" which class a function is in.

Comment (garbear) [reply xbmc/interfaces/builtins/PlayerBuiltins.cpp:51]: Here's my comment: https://github.com/xbmc/xbmc/pull/20254#discussion_r722728647

**Comment by howie-f** [comment]
i adjusted logs, but unfortunately i had to drop the original approach and move this functionality to `CFavouritesService`.
favourite items are hidden now if the matching mediasource is restricted+locked and master mode is not active. this behavior is in line with the movies/tvshows views of the home-screen. and it is at a lower risk since `PlayMedia` action is left in its original state.

thanks @phunkyfish for help with the last missing piece.

File: xbmc/favourites/FavouritesService.cpp [hunk 6]
```diff
@@ -227,5 +284,14 @@ void CFavouritesService::GetAll(CFileItemList& items) const
...
+  for (const auto& fav : m_favourites)
+  {
+    if (!IsMediasourceRestricted(fav))
+      items.Add(fav);
+  }
+}
+
+void CFavouritesService::RefreshFavourites()
+{
+  m_events.Publish(FavouritesUpdated{});
```
Comment (phunkyfish) [inline xbmc/favourites/FavouritesService.cpp:296]: You could check if anything has changed prior to sending the event. Then events would not be sent if not required. You have access to the current list of favourites, you would just need to reload them in order to check. Although now that I think about it this feels like more work than is really necessary!

Comment (howie-f) [reply xbmc/favourites/FavouritesService.cpp:296]: i believe the only not required call is here:
https://github.com/xbmc/xbmc/blob/1411dec80f5dbe2924dd09d7d11989f6f5819c1d/xbmc/interfaces/builtins/ProfileBuiltins.cpp#L72-L80

_user tries to enter master mode, but then they don't remember their code_
no big deal, i'll fix that

File: xbmc/dialogs/GUIDialogContextMenu.cpp [hunk 7]
```diff
@@ -493,6 +494,9 @@ bool CGUIDialogContextMenu::OnContextButton(const std::string &type, const CFile
       {
         // don't prompt user for mastercode when reactivating a lock
         g_passwordManager.LockSource(type, share->strName, true);
+
+        // refresh favourites due to possible visibility changes
```
Comment (phunkyfish) [inline xbmc/dialogs/GUIDialogContextMenu.cpp:498]: The comment should contain why this needs to be called here. Not a general reason but the specific reason.

File: xbmc/interfaces/builtins/ProfileBuiltins.cpp [hunk 8]
```diff
@@ -66,12 +67,20 @@ static int MasterMode(const std::vector<std::string>& params)
   {
     g_passwordManager.bMasterUser = false;
     g_passwordManager.LockSources(true);
+
+    // master mode turned off, refresh favourites due to possible visibility changes
```
Comment (phunkyfish) [inline xbmc/interfaces/builtins/ProfileBuiltins.cpp:71]: Here you give the specific reason. But in other cases you do not.

File: xbmc/interfaces/builtins/ProfileBuiltins.cpp [hunk 9]
```diff
@@ -66,12 +67,20 @@ static int MasterMode(const std::vector<std::string>& params)
...
+
     CGUIDialogKaiToast::QueueNotification(CGUIDialogKaiToast::Warning, g_localizeStrings.Get(20052),g_localizeStrings.Get(20053));
   }
   else if (g_passwordManager.IsMasterLockUnlocked(true))
   {
     g_passwordManager.LockSources(false);
     g_passwordManager.bMasterUser = true;
+
+    // successfully entered master mode, refresh favourites
+    CServiceBroker::GetFavouritesService().RefreshFavourites();
```
Comment (phunkyfish) [inline xbmc/interfaces/builtins/ProfileBuiltins.cpp:82]: The comment should contain why this needs to be called here. Not a general reason but the specific reason.

File: xbmc/profiles/dialogs/GUIDialogLockSettings.cpp [hunk 10]
```diff
@@ -75,6 +76,10 @@ bool CGUIDialogLockSettings::ShowAndGetLock(CProfile::CLock &locks, int buttonLa
     return false;
 
   locks = dialog->m_locks;
+
+  // refresh favourites due to possible visibility changes
```
Comment (phunkyfish) [inline xbmc/profiles/dialogs/GUIDialogLockSettings.cpp:80]: The comment should contain why this needs to be called here. Not a general reason but the specific reason.

File: xbmc/GUIPassword.cpp [hunk 11]
```diff
@@ -87,6 +90,9 @@ bool CGUIPassword::IsItemUnlocked(T pItem,
         CMediaSourceSettings::GetInstance().UpdateSource(strType, strLabel, "badpwdcount",
                                                          std::to_string(pItem->m_iBadPwdCount));
         CMediaSourceSettings::GetInstance().Save();
+
+        // refresh favourites due to possible visibility changes
```
Comment (phunkyfish) [inline xbmc/GUIPassword.cpp:94]: The comment should contain why this needs to be called here. Not a general reason but the specific reason.

**Review by phunkyfish — CHANGES_REQUESTED** [review]

File: xbmc/dialogs/GUIDialogContextMenu.cpp (hunk 7 above)
Comment (howie-f) [reply xbmc/dialogs/GUIDialogContextMenu.cpp]: yes, improved all comments and some blemish

**Comment by howie-f** [comment]
hrm, i had to adjust the template `CGUIPassword::IsItemUnlocked`. it should only refresh favourites if instantiated for a mediasource. now this should be really ready for review :)

**Review by phunkyfish — APPROVED** [review]

**Comment by howie-f** [comment]
squashed and rebased. i'm going to merge this tomorrow if there are no objections.

**Comment by howie-f** [comment]
jenkins build this please

**Comment by howie-f** [comment]
jenkins build this please

**Comment by howie-f** [comment]
jenkins build this please
