### PR TITLE
[webOS][Power management] Implement shutdown/reboot

### LINKED ISSUE #24240: WebOS - Power Menu does not turn off TV
### Describe the bug
Here is a clear and concise description of what the problem is:
When you select "Turn off the system" on the power menu,  the app simply quit leaving tv turned on instead of turn it off.

TV LG 55UP75006LF

### To Reproduce
1.  Open power menu
2.  Select "Turn off the system" according to your language

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [X] WebOS

 - Operating system version/name:
 - Kodi version: 21.0-Beta2 (20.90.821), 
 - GIT 20231210-979dbf5fe5 compiled 2023-12-09
 - WebOS TV 6.3.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by sundermann**
## Description

Implements calling the luna power management endpoints on shutdown / reboot

## Motivation and context

Fixes #24240

## How has this been tested?

webOS 7

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/platform/linux/powermanagement/LinuxPowerSyscall.cpp [hunk 1]
```diff
@@ -14,13 +14,21 @@
...
+
 #include <functional>
 #include <list>
 #include <memory>
 #include <utility>
 
 IPowerSyscall* CLinuxPowerSyscall::CreateInstance()
 {
+#if TARGET_WEBOS
+  return new CLunaPowerManagement();
```
Comment (lrusak) [inline xbmc/platform/linux/powermanagement/LinuxPowerSyscall.cpp:29]: Can you adjust the linuxpowersyscall registration instead in cplatformlinux?

It might even be nice to make a new cplatformwebos.

**Comment by sundermann** [comment]
Jenkins build this please

**Comment by sundermann** [comment]
Jenkins build this please

**Comment by sundermann** [comment]
Can you try [this](https://jenkins.kodi.tv/job/webos-docker/2865/) build which adds an additional delay before exiting the application

**Comment by sundermann** [comment]
Jenkins build this please

**Comment by sundermann** [comment]
@lrusak Can you review the changes?

**Review by fuzzard — APPROVED** [review]
Looks reasonable to me. If @lrusak finds some time to check it, otherwise I'll merge towards the end of the week to keep things moving
