### PR TITLE
[FileSystem] Add GUI settings for NFS and SMB chunk size

### LINKED ISSUE #24001: SMB speed is limited by small chunk size, video playback stutters on high bitrate files
### Describe the bug
Here is a clear and concise description of what the problem is:

When playing back high bitrate files from SMB the player stutters.
Kodi is running on Fire TV Stick 4K Max. SMB share is on Windows PC, SSD drive.
Increasing chunk size from current 64KB to 256KB fixed the issue completely for me.

https://github.com/xbmc/xbmc/blob/3e13d1a3557f66b73928cf1eeaa49c1b6e10d667/xbmc/platform/posix/filesystem/SMBFile.h#L82

### More details
Observed player information (ctrl+shift+o) during playback. The video bitrate fluctuated between 50 and 90 Mb/s. On certain scenes where bitrate was constantly high near 80 Mb/s the video buffer started to slowly decrease. After a minute or so the buffer was empty, the playback paused to fill the buffer.

Monitored network activity during playback. The network speed never exceeded 90 Mb/s.

Then I made another test. Using Kodi File Manager copied a large file from SMB share to local storage. The File Manager showed copying speed and it was about 10MB/s. Tried copying the same file using other app on the same device and the copying speed was 35MB/s.

Another test was to try FTP. Configured FTP server on the same Windows PC. Result: playback in Kodi without issues. Copy speed in Kodi: 20MB/s.

Then I tested Kodi on Mac and tried to copy the same file (using Kodi File Manager). The speed on Mac was 17MB/s. Tried to copy this same file using Finder - speed was 80MB/s.

It was clear that something limits SMB performance in Kodi.

Studied the Kodi code and found out that chunk size is set (hardcoded) to 64KB for SMB files. Tried to increase it and got immediate performance boost. Copy speed results using Kodi File Manager (reproducible):

|Chunk size -> | 64KB | 128KB | 256KB | 512KB | 1024KB |
| --- | --- | --- | --- | --- | --- |
|MacBook 2015, MB/s | 17 | 26 | 36 | 46 | 54 |
|Fire TV Stick 4K Max, MB/s | 10 | 15 | 23 | 27 | 30|

I'd like to point out that I don't really care about copy speed in File Manager. However File Manager is the easiest way to test SMB speed. The results of these tests correspond  very well to the smoothness of playback. Knowing copy speed is a good indicator of what to expect in player for certain bitrates.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Playback should not stutter if the network speed is sufficient and the performance isn't limited by hardware. Kodi should be able to read from SMB shares at speeds limited by network connection and not by a hardcoded buffer size.

## Actual Behavior

Video playback stutters on high bitrate files. Reading from SMB shares is three times slower than other apps can do; it is also two times slower than reading from FTP in Kodi.

## Possible Fix

I was able to fix the stuttering issue by increasing the chunk size from 64KB to 256KB.

I'm not sure if that simple change of the constant is a proper solution for all users. I've studied the issues related to SMB and also to chunk size (for other file sources). The following issues are related to chunk size: #22946, #22941, #22920.

From the comments I've learned that chunk size is a sensible area and should be chosen wisely. I understand the goal to have a default size which provides the best compatibility. On the other side we want to use Kodi on modern devices for playback of modern sources. I consider my setup as typical enough and not extravagant in any way: Fire TV Stick 4K Max with Kodi; Windows PC with network share (where SMB is a native share protocol); playing back Blu-ray 4K remuxes (mkv).

If there are objections to increasing of hardcoded chunk size, then maybe it's worth a setting? Either an advanced setting or even a setting in GUI.

Another consideration would be to change the behaviour of caching. Currently hardcoded chunk size overrides any change made to advanced setting for chunk size.

### To Reproduce

Using File Manager is the easiest way to reproduce the issue (and to test a possible fix)
1. Open File Manager in Kodi
2. Connect to network SMB share
3. Copy a large file (1GB) to local storage.
4. Observe copying speed in the progress window.
5. Compare with network connection speed.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/ujiyiqupiy.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

- [x] Android
- [ ] iOS
- [ ] tvOS
- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Windows UWP

- Operating system version/name: Fire OS 7.6.6.4.
- Kodi version: Omega Beta 1.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Add GUI settings for NFS and SMB chunk size

Closes https://github.com/xbmc/xbmc/issues/24001

## Motivation and context
Is well known that SMB is some less efficient (protocol overhead) that NFS, however this is more accentuated in Kodi due we using smaller 64 KB chunk size vs. 128 KB chunk size for NFS.

Several users have reported low speed issues playing UHD Blu-Ray Remux using SMB on Fire Stick 4K max and similar devices. On Shield seems less problematic (has 1 Gigabit Ethernet) but anyway in forums exists similar complains.

@hugbug has done some detailed measurements (see  https://github.com/xbmc/xbmc/issues/24001) that confirms the relation between chunk size and maximum effective throughput obtained (on Fire Stick 4K max):

|Chunk size -> | 64KB | 128KB | 256KB | 512KB | 1024KB |
| --- | --- | --- | --- | --- | --- |
|MacBook 2015, MB/s | 17 | 26 | 36 | 46 | 54 |
|Fire TV Stick 4K Max, MB/s | 10 | 15 | 23 | 27 | 30|

- Currently with 64K 10 MB/s (80 Mbit/s) is insufficient for all 4K remuxes.
- Only changing to 128K (same as NFS) improves to 15 MB/s (120 Mbit/s) that is enough for almost all UHD Blu-Ray’s.
- Using 256KB is obtained 23 MB/s (184 Mbit/s) that covers completely maximum UHD Blu-Ray spec of 144 Mbit/s.

This PR changes default SMB chunk size to 128 KB and adds new GUI settings to make this parameter user configurable for both SMB and NFS.

Then for most users the new SMB default value is enough and represent a big improvement even in case of not being aware of the existence of this setting. 

The reason of not choosing higher values by default is that for some content (especially BD ISO’s) may work better small values (faster load/seek times), then probably 128 KB is the most balanced value that works well for all.

## How has this been tested?
Runtime tested on Windows x64 and Shield.

On Shield I not have issues using previous 64 KB chunk in regular UHD Blu-Ray's but using extreme case of 400 Mbps jellyfish test file can also confirm that performance improves using big chunk sizes and in fact this file is only playable thought SMB with 256 chunk size (and 512 works even better).

So this would confirm that it is not a problem isolated to Fire Stick but rather that all devices would be affected but to a lesser degree and therefore the issue is not noticeable when 64 KB is sufficient for the content being played.

Also tested BD ISO's and the new 128 KB default not causes evident issues and not noticeable increasing in load times.

Relevant log lines when using 512 KB chunk size:

**SMB**
```
debug <general>: CFileCache::Open - <smb://DiskStation/NAS/TEST-MEDIA/H264/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv> opening
debug <general>: CSMBFile::Open - opened smb://USERNAME:PASSWORD@DiskStation/NAS/TEST-MEDIA/H264/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv, fd=10000
debug <general>: CFileCache::Open - <smb://DiskStation/NAS/TEST-MEDIA/H264/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv> source chunk size is 524288, setting cache chunk size to 524288
debug <general>: CFileCache::Open - <smb://DiskStation/NAS/TEST-MEDIA/H264/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv> using double memory cache each sized 67108864 bytes
```

**NFS**
```
debug <general>: NFS: version: 4
debug <general>: NFS: Connected to server 192.168.50.13 and export /
debug <general>: NFS Server did not return max read chunksize - Using setting value 524288
debug <general>: NFS Server did not return max write chunksize - Using setting value 524288
debug <general>: NFS: chunks: r/w 524288/524288
```

```
debug <general>: CFileCache::Open - <nfs://192.168.50.13/volume1/NAS/TEST-MEDIA/H264/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv> opening
debug <general>: CNFSFile::Open - opened volume1/NAS/TEST-MEDIA/H264/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv
debug <general>: CFileCache::Open - <nfs://192.168.50.13/volume1/NAS/TEST-MEDIA/H264/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv> source chunk size is 524288, setting cache chunk size to 524288
debug <general>: CFileCache::Open - <nfs://192.168.50.13/volume1/NAS/TEST-MEDIA/H264/jellyfish-400-mbps-4k-uhd-hevc-10bit.mkv> using double memory cache each sized 67108864 bytes
```

## What is the effect on users?
Enables the possibility to easy configure NFS and SMB chunk sizes according to device used and type of contents most frequently played.

The only functional change is 64 KB to 128 KB for SMB that according tests done seems "better" default, although in case of regressions, users can easily back to previous 64 KB chunk size.

## Screenshots (if appropriate):

SMB

NFS

chunksizes

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/filesystem/NFSFile.cpp [hunk 1]
```diff
@@ -336,13 +337,21 @@ bool CNfsConnection::Connect(const CURL& url, std::string &relativePath)
...
+
+      CLog::Log(LOGDEBUG, "NFS Server did not return max read chunksize - Using setting value {}",
+                chunkSize);
+      m_readChunkSize = chunkSize;
     }
     if (m_writeChunkSize == 0)
     {
-      CLog::Log(LOGDEBUG, "NFS Server did not return max write chunksize - Using 128K default");
-      m_writeChunkSize = 128 * 1024; // 128K
+      const auto settings = CServiceBroker::GetSettingsComponent()->GetSettings();
```
Comment (fritsch) [inline xbmc/filesystem/NFSFile.cpp:349]: I think this might be enough in practice. What we do not handle is: NFS server says 256KB and we wanted to use a lower value, cause the user only watches BD ISOs.

May be, but I leave that to you: Changing the positive log path, e.g. Server returned a max chunk value - ignoring user defined value?

**Review by fritsch — APPROVED** [review]
Code is fine, thanks very much. With our limited automatisms I don't see another choice here sadly. The default now that SMB is switched to 128 KB should work for 90% of the users. I left a small comment if we wanted to log that we ignore user's value cause server's value was used.

File: xbmc/filesystem/NFSFile.cpp (hunk 1 above)
Comment (thexai) [reply xbmc/filesystem/NFSFile.cpp]: Handled this case: value returned by server is bigger that client setting, then is used the smallest of two.

Comment (fritsch) [reply xbmc/filesystem/NFSFile.cpp]: Thanks!

**Comment by hugbug** [comment]
Thank you very much for implementing this.

Tested this PR on a Fire Stick 4K Max (1st gen.).
The setting for SMB chunk size works as expected. Tested specifically with small size (32KB) - as result not being able to playback high bitrate file. Changing the setting to a high value fixed the issue.

I couldn't test NFS (don't have NFS shares unfortunately).

**Review by wsnipex — APPROVED** [review]
looks good

**Comment by enen92** [comment]
How does this relate to the `chunksize` setting we have on advanced settings? Will it override what is defined there or does it get obsolete/ignored for this two specific protocols?

**Comment by thexai** [comment]
Recently have been found that advanced setting `chunksize` is ignored when is used a filesystem/protocol that returns chunk size > 1 (has a predefined value hardcoded as SMB or NFS). Then before was ignored and with this PR is also ignored but is now configurable in GUI settings.

Then the reason of this PR is to be able to change these values on NFS and SMB. Before it was just a placebo effect.

Advanced setting should still have effect for others filesystems/protocols that not has any predefined value (chunk size == 0): FTP, WebDAV, HTTPS… but it would be necessary to check all the cases because I am not sure when is used.

**Comment by enen92** [comment]
> Recently have been found that advanced setting `chunksize` is ignored when is used a filesystem/protocol that returns chunk size > 1 (has a predefined value hardcoded as SMB or NFS). Then before was ignored and with this PR is also ignored but is now configurable in GUI settings.
> 
> Then the reason of this PR is to be able to change these values on NFS and SMB. Before it was just a placebo effect. 😛
> 
> Advanced setting should still have effect for others filesystems/protocols that not has any predefined value (chunk size == 0): FTP, WebDAV, HTTPS… but it would be necessary to check all the cases because I am not sure when is used.

Thanks for explaining - maybe we should later improve the wiki with this info.
I've faced a lot of buffering issues recently with uhd Blu-ray's streamed from NFS maybe this will help. Any way we can check the bandwidth in the GUI or similar?

**Comment by thexai** [comment]
> I've faced a lot of buffering issues recently with uhd Blu-ray's streamed from NFS maybe this will help

Maybe but depends if is used WiFi or 1 Gbps Ethernet and if media is MKV or full ISO / BDMV folder. 
`FileCache` not used for ISOs / BDMV then some combinations are really bad (ISO + WiFi).

> Any way we can check the bandwidth in the GUI or similar?

Player debug Info (Ctrl + Shift + O) check cache memory is filled and "play time of cached bytes" > 8 s and if not used FileCache (0 MB) play time still has to be ~8.0 s and vq ~99%

**Comment by thexai** [comment]
Jenkins build this please

File: xbmc/settings/ServicesSettings.cpp [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+                                                       int& current,
+                                                       void* data)
+{
+  list.emplace_back("16 KB", 16);
+  list.emplace_back("32 KB", 32);
+  list.emplace_back("64 KB", 64);
+  list.emplace_back("128 KB", 128);
+  list.emplace_back("256 KB", 256);
+  list.emplace_back("512 KB", 512);
+  list.emplace_back("1 MB", 1024);
```
Comment (ksooo) [inline xbmc/settings/ServicesSettings.cpp:22]: @thexai  Late to the party, sorry. Are you sure that these values should not be translated? is it for countries in the world KB and MB?

Comment (ksooo) [reply xbmc/settings/ServicesSettings.cpp:22]: Do you plan to add translation support (strings.po) in a follow up PR? I think we should do this.

Comment (lrusak) [reply xbmc/settings/ServicesSettings.cpp:22]: I see a translation available for `MByte` but nothing else. It would be nice if we could reuse existing translations if available.

https://github.com/xbmc/xbmc/blob/master/addons/resource.language.en_gb/resources/strings.po#L9407

**Comment by jp12git** [comment]
Noticing that this is still an issue on Fire TV Cube 3 while playing a 100 Mbps Jellyfish HEVC file on a 200 Mbps+ connection using the build from here [https://jenkins.kodi.tv/job/android-arm-docker/4074/](https://jenkins.kodi.tv/job/android-arm-docker/4074/). I've set the NFS share chunk size to 1 MB. 

I've tried tweaking video cache as suggested here (https://kodi.wiki/view/HOW-TO:Modify_the_video_cache) to no luck. Any suggestions what else I can tweak?

**Comment by jp12git** [comment]
@thexai  @wsnipex  @ksooo  Noticing that this is still an issue on Fire TV Cube 3 while playing a 100 Mbps Jellyfish HEVC file on a 200 Mbps+ connection using the latest build from this PR (here https://jenkins.kodi.tv/job/android-arm-docker/4074/ ). I've set the NFS share chunk size to 1 MB.

I've tried tweaking video cache as suggested here (https://kodi.wiki/view/HOW-TO:Modify_the_video_cache) to no luck. Any suggestions what else I can tweak?

**Comment by fritsch** [comment]
Stop highjacking multiple PRs. As said this does not fix Firmware flaws with bad wifi implementations. Use an USB3 adapter instead. FireTV is not invented for such throughput, amazon does not sell that content.

File: xbmc/settings/ServicesSettings.cpp (hunk 2 above)
Comment (Danny3) [reply xbmc/settings/ServicesSettings.cpp:22]: > > is it for all countries in the world KB and MB?
> 
> Probably not, although probably in all countries understand what means 128 KB in English

In Romanian, we use octets (octeți) as the translation for bytes so pretty much every software that translates units properly will use that, so it KO, MO, GO and or KiO, MiO, GiO, depending how originally it was written in English.

In Qbittorrent for example, if the language is changed to Romanian, all units of size and time / date are properly translated.

The units in English might be understood by people, but it's most likely that they will be understood by people who already understand english, but the translations are not intended for those people.

And if somebody uses Windows and Qbittorent in Romanian and these display units as properly translated, then it would be nice if Kodi would use the proper units translations too.

Comment (thexai) [reply xbmc/settings/ServicesSettings.cpp:22]: Done in https://github.com/xbmc/xbmc/pull/24049

**Comment by raidboy** [comment]
The GUI comment under Settings->Services->Caching->Chunk Size says:

"The data chunk size to use when a filesystem or protocol does not force the value, e.g.: NFS will override this wits its own value."

With this PR included it seem the text should better say something like the following:

"The data chunk size to use when a filesystem or protocol does not force a value. Not used for filesystems with their own chunk size config option (currently NFS and SMB)."
