### PR TITLE
[videoplayer] don't spam the log when in pause state (fixes #18535)

### LINKED ISSUE #18535: Kodi 19 - Log spam on pausing video
### Describe the bug
Here is a clear and concise description of what the problem is:

While playing a Video from local drive  in Windows, if video is paused by pressing space, immediately the log starts filling with the following message at rate of 2 messages per second.
`WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer`
So if I pause the video for 5 minutes to go do something, the log gets 600 of these messages.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Pausing a Video should not cause LOG file to fillup

## Actual Behavior

```
2020-10-07 18:02:18.417 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:18.918 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:19.419 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:19.920 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:20.421 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
2020-10-07 18:02:20.922 T:11552 WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer
```

### To Reproduce

1. play any video from kodi library, files in local drive
2. pause the video for 30 seconds
3. log has 60 messages

### Debuglog

The debuglog can be found here:
[Debug Log](http://paste.kodi.tv/luqejuhaxu)

### Screenshots 
Here are some links or screenshots to help explain the problem:

Not Applicable

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Not Applicable

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
Windows 10 2004
 - Kodi version:
Nightly 19.0-ALPHA2 (18.9.702) Git:20201007-f1074bd420
(Tested from Alpha1 snapshot to 7 OCT 2020 nightly)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by wsnipex**
## Description

Currently the kodi log is spammed with the following message when a video is paused:
`WARNING <general>: CRenderManager::WaitForBuffer - timeout waiting for buffer`

## Motivation and Context

https://github.com/xbmc/xbmc/issues/18535

## Screenshots (if appropriate):

@FernetMenta is this the correct approach? Note that I tried to use m_paused, but that is always false at this point, which seems suspect to me.

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp [hunk 1]
```diff
@@ -1055,10 +1055,6 @@ int CRenderManager::WaitForBuffer(volatile std::atomic_bool&bStop, int timeout)
     m_presentevent.wait(lock, std::min(50, timeout));
     if (endtime.IsTimePast() || bStop)
     {
-      if (timeout != 0 && !bStop)
-      {
-        CLog::Log(LOGWARNING, "CRenderManager::WaitForBuffer - timeout waiting for buffer");
-      }
```
Comment (fritsch) [inline xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp:1061]: I wonder if this could be kept. Now when the other side (e.g. the player user) says OUTPUT_AGAIN, it should receive something or better present the last buffer once more. (Why keeping: if we are not paused, but really render is stuck, then we would not see it anymore. But I admit I don't have a better idea at hand.

Btw. do you still see a 100% CPU usage when this block is hit?

Comment (wsnipex) [reply xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp:1061]: If we keep that log here, it will keep spamming. I guess introducing a new parameter for this would be a hack?
As for cpu usage: I see no real difference between play and pause state. Both are ~50% CPU

Comment (fritsch) [reply xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp:1061]: The key thing here is that the RenderManager should have no idea about player's internal state. Changing the interface of rendermanager to introduce something like: Pause() though would work.

Never the less out of scope of this PR. We could make a it a LOGDEBUG, then at least if someone wants to debug these things they'd see it and normal users won't?

**Comment by FernetMenta** [comment]
Silencing a warning does not fix the issue. If you see this in the log, something goes wrong and should be fixed. Instead of hiding the symptom you should investigate the root cause.

**Comment by fritsch** [comment]
@FernetMenta  Do you have an idea of what goes wrong? From reading, the first WARNING (in player) infact was not correct as it did not have PAUSE state in mind where no new frames come from decoder. But here I don't get why it's triggered as the current frame should just be painted again, right?

**Comment by FernetMenta** [comment]
> @FernetMenta Do you have an idea of what goes wrong? From reading, the first WARNING (in player) infact was not correct as it did not have PAUSE state in mind where no new frames come from decoder. But here I don't get why it's triggered as the current frame should just be painted again, right?

Paused state is not relevant here. When paused VPV submits the same frame continuously to renderer and renderer should provide free buffers for it.

**Comment by fritsch** [comment]
Seems nothing is delivered. Which is why we timeout here and spam?

**Comment by fritsch** [comment]
```
  XbmcThreads::EndTime endtime(timeout);
  while(m_free.empty())
  { 
    m_presentevent.wait(lock, std::min(50, timeout));
    if (endtime.IsTimePast() || bStop)
    {
      if (timeout != 0 && !bStop)
      {
        CLog::Log(LOGWARNING, "CRenderManager::WaitForBuffer - timeout waiting for buffer");
      }
      return -1;
    }
```

Okay, the WaitForBuffer is polling it's m_free queue and it stays empty forever, which is odd as no new frame is delivered, means someone does not return its buffers or RenderManager looses track?

Could you please emphasize on this a bit more? Who is meant to return frames to RenderManager so that it has empty frames again? Also most of the time we configure decoder frames + 3 render frames, if they would be taken we could render something right?

**Comment by FernetMenta** [comment]
Sorry, I was wrong. Meanwhile RM has access to the clock and pause state does matter. I think this PR is ok as is.

**Comment by wsnipex** [comment]
oh great, thanks!

**Review by ksooo — APPROVED** [review]
@FernetMenta gave his okay.

**Comment by djp952** [comment]
Hello, I apologize for not seeing this in time to ask a question about it, but I was wondering if you think it would be beneficial to add to this to also suppress the message if the Video stream is in a stalled state:

```
    if (m_speed != DVD_PLAYSPEED_PAUSE && !m_stalled)
      CLog::Log(LOGWARNING, "{} - timeout waiting for buffer", __FUNCTION__);
```

A secondary concern with Issues [18389](https://github.com/xbmc/xbmc/issues/18389) and [17041](https://github.com/xbmc/xbmc/issues/17041) that was not resolved with PR [19048](https://github.com/xbmc/xbmc/pull/19048) is the "timeout waiting for buffer" logspam condition.  I made no attempt to address this since it wasn't related to the main playback issue.

> If the video stream is stalled, is it acceptable to suppress this message?

Commenting on a merged PR is absolutely bad form, and I apologize for that, but I didn't want to write up a PR for something that's conceptually incorrect (again).

**Comment by djp952** [comment]
Based on lack of feedback I intend to issue a PR to address this as time allows; I do not see any reason for this log message to exist if the underlying video stream is in a known "stalled" state.
