### PR TITLE
[Windows] fix DirectSound buffer underrun with some Bluetooth audio devices

### LINKED ISSUE #20567: Audio stutter on win11 due to broken Directsound
### Describe the bug
After moving from win10 to win11, I can no longer enjoy videos on kodi. Audio stutters all the way including UI sound. A workaround I found is switching the audio backend to WASAPI, where Directsound, the *default* choice, seems to be broken. **Both the UWP version from M$ store and the .exe installer suffer from the same problem.**

## Expected Behavior

Audio plays normally.

## Actual Behavior

Both UI sound and video sound stutter all the way. 

## Possible Fix

No idea.

### To Reproduce

1. Fresh install Kodi 19.3 on a win11 machine.
2. Play a random video or use arrow keys to browse the menus to trigger UI sound.

### Debuglog

The debuglog can be found here, which is full of:
```
WARNING <general>: CWin32DirectSound::GetSpace - buffer underrun - W:16248, P:4294965000, O:384.
```
Full log: https://fars.ee/nYT6.log (captured from a fresh UWP install)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [X] Windows UWP

 - Operating system version/name: Windows 11 Home 21H2 22000.348
 - Device: Surface Pro 7
 - Kodi version: 19.3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Fix DirectSound buffer underrun with some Bluetooth audio devices

Fixes https://github.com/xbmc/xbmc/issues/20567

## Motivation and context
Windows 11 has changed a bit the way DirectSound is handled and in combination with some Bluetooth audio devices / drivers causes buffer underruns. 

There was some confusion with this because at the beginning of Windows 11 there were widespread problems with BT audio devices. After some Microsoft patches the situation improved significantly but even today some devices still have problems apparently only with Kodi (even that these same devices works in Kodi with Windows 10).

In any case DirectSound buffers seems very small: only 15ms chunks and 180 ms sink buffer. On forum one of affected users has confirmed issue is fixed increasing buffer size in various combinations:

15 ms * 20 chunks = 300 ms OK
15 ms * 30 chunks = 450 ms OK
50 ms * 8 chunks = 400 ms  OK
50 ms * 5 chunks = 250 ms is not enough 

https://forum.kodi.tv/showthread.php?tid=376406&pid=3193663#pid3193663

15 ms seems have some issues because 44100 sample rate * 0.015  is not exact number, then no exact number of samples for chunk duration. Good candidates are 20 ms 30 ms or 50 ms but stressing thins --> scrolling very fast in a list of files with GUI sounds I have gotten occasional buffer underruns with 20 ms and even 30 ms and 10 chunks (300 ms buffer). Same is happens with current 15 ms and 12 chunks. Seems 15 ms chunk is too small regardless of buffer size.

50 ms seems best number to obtain stability and works fine in my system with 5 chunks but not enough on these BT devices. 

8 chunks seems totally stable and is one of options tested with success on affected BT devices.

NOTE: this problem only happens in DirectSound, WASAPI is not affected because works in other way and system/driver returns optimal buffer duration that is already bigger: 500 ms or 1s. 

## What is the effect on users?
Fixes DirectSound buffer underruns in Windows 11 in combination with some Bluetooth audio devices.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/AudioEngine/Sinks/AESinkDirectSound.cpp [hunk 1]
```diff
@@ -218,10 +218,10 @@ bool CAESinkDirectSound::Initialize(AEAudioFormat &format, std::string &device)
 
   m_AvgBytesPerSec = wfxex.Format.nAvgBytesPerSec;
 
-  unsigned int uiFrameCount = (int)(format.m_sampleRate * 0.015); //default to 15ms chunks
+  const unsigned int uiFrameCount = static_cast<int>(format.m_sampleRate * 0.050); // 50ms chunks
   m_dwFrameSize = wfxex.Format.nBlockAlign;
   m_dwChunkSize = m_dwFrameSize * uiFrameCount;
-  m_dwBufferLen = m_dwChunkSize * 12; //180ms total buffer
+  m_dwBufferLen = m_dwChunkSize * 8; // 400ms total buffer
```
Comment (fritsch) [inline xbmc/cores/AudioEngine/Sinks/AESinkDirectSound.cpp:224]: I have a similar issue in pulse and Linux. It might very well be that just the increased chunk size is enough.

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/AESinkDirectSound.cpp:224]: https://github.com/xbmc/xbmc/blob/5e6d5de2c6a151683b77ac34abce8fae8294b7b9/xbmc/cores/AudioEngine/Sinks/AESinkALSA.cpp#L733

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/AESinkDirectSound.cpp:224]: > https://github.com/xbmc/xbmc/blob/5e6d5de2c6a151683b77ac34abce8fae8294b7b9/xbmc/cores/AudioEngine/Sinks/AESinkALSA.cpp#L733

https://github.com/xbmc/xbmc/blob/5e6d5de2c6a151683b77ac34abce8fae8294b7b9/xbmc/cores/AudioEngine/Sinks/AESinkPULSE.cpp#L907

Comment (fritsch) [reply xbmc/cores/AudioEngine/Sinks/AESinkDirectSound.cpp:224]: Your change is fine. Let's assume Get delay works properly combined with Flush.

**Review by fritsch — APPROVED** [review]

**Comment by fritsch** [comment]
Especially Bluetooth headsets buffer a whole lot by themselves. You can hear that if you press the pause / stop button that they continue to play for "several time", some even in the seconds range. SBC and a potential bad reception in between can cause issues if payload chunks are too small. That was the case why I linked the pulseaudio sink. We had an exact similar issue there with audio stuttering.

While you definitely have a point with the Ringbuffer distance. If that could be used - even a dynamic would be possible.

In general for AE design: Large buffers do not harm, given that GetDelay and Flush / Drain are properly working.

**Comment by thexai** [comment]
> I understand that the PR helps, but is this the correct knob to turn?

I don't think there is any other way to solve this that doesn't include an increase in the buffer size.

We should look for the origin of the issue in an increase of latency and/or jitter due internal changes in Windows 11 at lest for Bluetooth audio. The underrun error in logs is only a consequence, not the cause. The main issue is audio glitch/corruption.

> Play cursor offset is close to the max DWORD value

These "big" numbers are in reality near to zero:

DWORD is an unsigned 32 bit type (same as uint32_t) and these numbers are easily generated by overflow to (non possible) negative numbers.

Example:

```c++
DWORD number = 0;
number = number - 5288;
```

> With the buffer size increase of the PR, do the underrun log lines actually go away?

Yes, this PR fixes the two things: audio corruption and log errors.

**Comment by thexai** [comment]
Jenkins build this please

**Comment by CrystalP** [comment]
> DWORD is an unsigned 32 bit type (same as uint32_t) and these numbers are easily generated by overflow to (non possible) negative numbers.

yes that is my guess as well, the Windows 11 DirectSound emulation may have some sort of bug.

It's probably unrelated but dsound has a constant DSBSIZE_FX_MIN for the minimum size of a buffer that is intended to have dsound effects applier (150ms). 


> > With the buffer size increase of the PR, do the underrun log lines actually go away?
> 
> Yes, this PR fixes the two things: audio corruption and log errors.

I only saw users saying that it plays. Not seen any debug logs of that.

**Comment by CrystalP** [comment]
and you merged already... what's the point of discussing...

**Comment by CrystalP** [comment]
I'm not OK with a backport until there is more testing. At least low and high sampling rates. It could cause issues on many systems that worked fine until now.

**Comment by thexai** [comment]
The backport was not my intention either, I have only created a branch to make a build for interested users (precisely because the change will take time to reach Omega)

**Comment by fritsch** [comment]
From this description (not a windows expert): https://learn.microsoft.com/en-us/previous-versions/windows/desktop/ee416820(v=vs.85)#remarks

it seems that they want to handle it internally. Means: Set it to zero and then use GetCaps to check how much buffer it wanted / needed.

```
dwBufferBytes
Size of the new buffer, in bytes. This value must be 0 when creating a buffer with the DSBCAPS_PRIMARYBUFFER flag. For secondary buffers, the minimum and maximum sizes allowed are specified by DSBSIZE_MIN and DSBSIZE_MAX, defined in Dsound.h.
```

**Comment by CrystalP** [comment]
Maybe we should phase out DirectSound in favor of XAudio2, already coded for xbox and comes pre-installed with a good enough version on Windows 8 and above.

**Comment by fritsch** [comment]
Back at the time, when first implemented, we had massive issues with getting proper delays. Also I found the API totally complicated ...

**Comment by thexai** [comment]
Created a draft PR to test it: https://github.com/xbmc/xbmc/pull/25068

It works!

works = it has sound
