### PR TITLE
[CRenderManager] Fix adjust display refresh rate start/stop setting behaviour

### LINKED ISSUE #21033: VFR content breaks display refresh rate switching
### Describe the bug
Here is a clear and concise description of what the problem is:

Display refresh rate switching is broken with VFR content. When the video file changes framerate mid playback it changes the display refresh rate even when set to start/stop.

This results is horrendous stuttering for all scenes afterword. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Setting it to Start/Stop should adjust the display refresh rate before playing video and should not change until closing video.

## Actual Behavior

Start/Stop adjusts display refresh rate fine at the start, but changes display refresh rate mid video when the video refresh rate changes. 

## Possible Fix

Make Start/Stop only change the display refresh rate before and after a video is closed and not allow it during.

### To Reproduce

1. Have Adjust display refresh rate = On start / stop
2. Open provided video (its all black frames with VFR timecodes muxed in) \ Or any VFR mkv you can find.
3. Wait for video frame rate to change (00:31) and see the display refresh rate change mid playback.

Non Copyright Material File: 
https://mega.nz/file/Mp0HUSra#FjGkng63Ui8PjYV7QAcpH1UiqIVCqQW0JyspIxq8H-8
^ Has timecodes muxed in already.
  
  
31 Seconds in is when the display refresh rate changes. 

Raw Timecode File: [timecodes.txt](https://github.com/xbmc/xbmc/files/8127213/timecodes.txt)

Is reproducible with any VFR mkv file not just the one provided.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/8127019/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10/11, Manjaro 21.2.2.2, Android TV 9, 8.2.3 Nvidia Shield
 - Kodi version:19.3, Master Branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

At playback start we trigger resolution change 2 times
- the first one based on stream hint info (CRenderManager not configured yet)
- the second one based on data (CRenderManager initializations/configuring)

after that, during playback we still check for video stream info changes
but videos like MKV with variable framerate pointed out that
the "adjust display refresh rate" start/stop settings is not respected by changing display refresh rate in any case

## Motivation and context

fix #21033

## How has this been tested?

user provided a sample file to test it in the Issue

## What is the effect on users?

Have a consistent "adjust display refresh rate" start/stop setting

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp [hunk 1]
```diff
@@ -131,6 +131,7 @@ bool CRenderManager::Configure(const VideoPicture& picture, float fps, unsigned
 
   {
     std::unique_lock<CCriticalSection> lock(m_statelock);
+    m_isRenderInitializing = m_renderState == STATE_UNCONFIGURED;
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp:134]: I don't see a need for this new member variable if all you do is compare `m_renderState == STATE_UNCONFIGURED`. Why not compare it directly below with `m_renderState != STATE_UNCONFIGURED`?

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp:134]: will result in always true
Configure() is called only if m_renderState == STATE_CONFIGURING
instead i need to know the first init call

**Comment by da-anda** [comment]
I would love to review, but I am utterly unqualified for this, sorry

**Comment by CastagnaIT** [comment]
since you asked i thought you wanted to do a test

**Comment by da-anda** [comment]
I merely tried to get some issues from our ever growing list of tickets fixed by poking some people ;)

**Comment by CastagnaIT** [comment]
jenkins build this please

File: xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp:134]: I do not understand in full your statement, please notice that method
`bool CRenderManager::Configure(const VideoPicture& picture, float fps, unsigned int orientation, int buffers)`
can be called more times during playback

instead method
`bool CRenderManager::Configure()`
is called only if `m_renderState == STATE_CONFIGURING`
you cannot replace  m_isRenderInitializing  here:
https://github.com/xbmc/xbmc/blob/961d5fdeb66681ac0e7de0eea10cb36074a54d30/xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp#L225
by using `m_renderState` value state because will have a fixed value to STATE_CONFIGURING

File: xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp [hunk 2]
```diff
@@ -892,13 +901,16 @@ void CRenderManager::UpdateLatencyTweak()
...
-  if (m_bTriggerUpdateResolution)
+  if (m_bTriggerUpdateResolution && m_fps > 0.0f)
   {
-    if (CServiceBroker::GetWinSystem()->GetGfxContext().IsFullScreenVideo() && CServiceBroker::GetWinSystem()->GetGfxContext().IsFullScreenRoot())
+    if (CServiceBroker::GetWinSystem()->GetGfxContext().IsFullScreenVideo() &&
+        CServiceBroker::GetWinSystem()->GetGfxContext().IsFullScreenRoot())
     {
-      if (CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(CSettings::SETTING_VIDEOPLAYER_ADJUSTREFRESHRATE) != ADJUST_REFRESHRATE_OFF && m_fps > 0.0f)
+      if (CServiceBroker::GetSettingsComponent()->GetSettings()->GetInt(
+              CSettings::SETTING_VIDEOPLAYER_ADJUSTREFRESHRATE) != ADJUST_REFRESHRATE_OFF)
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp:910]: its not my choice this is Clang code formatting you cannot change it,
only for some special cases you can disable Clang

File: xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp (hunk 1 above)
Comment (da-anda) [reply xbmc/cores/VideoPlayer/VideoRenderers/RenderManager.cpp]: thanks. Looks much better to me now. 👍

**Review by enen92 — APPROVED** [review]

**Comment by ksooo** [comment]
@CastagnaIT  Is this something we should backport (if even possible)?

**Comment by CastagnaIT** [comment]
if possible it would be appropriate since this change have a low impact

**Comment by ksooo** [comment]
> if possible it would be appropriate since this change have a low impact

 @CastagnaIT would you be so kind to open a backport PR?

**Comment by matthuisman** [comment]
Great stuff. I assume this will also fix the issue of streams with ads (x-discontinuity) from jumping frame rates at the adverts as per below
https://github.com/matthuisman/slyguy.addons/issues/46

**Comment by CastagnaIT** [comment]
good to hear
backport done

**Comment by FernetMenta** [comment]
> the "adjust display refresh rate" start/stop settings is not respected by changing display refresh rate in any case

This was by intent. The start/stop setting was implemented to prevent changes of resolution when users navigate to the menu while video is playing. 
You don't want to watch a 60fps video on a 24Hz screen. Hence it was allowed that variable framerate videos can switch to a higher framerate midstream. This has gone now with this change.

**Comment by CastagnaIT** [comment]
provide steps to reproduce the problem i have not found regressions,
if someone want the refresh rate change while in playback will set "adjust display refresh rate" to "always"
and if "adjust display refresh rate" is set to "OFF" the refresh must no changed while in playback

**Comment by CastagnaIT** [comment]
Pushed a followup pr #21455

**Comment by smf007** [comment]
> 

Sorry to jump in on this, but it appears there is some miscommunication here.  As an outsider who has looked over the coding, perhaps this would help.

- "ON_StartStop"  This will always revise the refresh rate based on the video.  The GUI will be run at the same refresh rate as the video, the GUI would not trigger a change of the refresh rate.  When the video is stopped, the GUI will be run at the defined GUI refresh rate.
- "ALWAYS"  This will always revise the refresh rate based on the video.  The GUI will be run at the defined GUI refresh rate, thus the GUI would trigger a change of the refresh rate.  When the video is stopped, the GUI will be run at the defined GUI refresh rate.
- "ON_START"  This will always revise the refresh rate based on the video.  The GUI will be run at the same refresh rate as the video, the GUI would not trigger a change of the refresh rate.  When the video is stopped, the GUI will remain at the refresh rate of the video.
- "OFF"  The video will be displayed at the defined GUI refresh rate, NO refresh rate changes would occur.

**Comment by thexai** [comment]
Confirmed breakage in master and Matrix see https://github.com/xbmc/xbmc/issues/21447#issuecomment-1139398457
