### PR TITLE
[Windows] Fix crash when audio device not has 'PKEY_Device_EnumeratorName' property

### LINKED ISSUE #25635: Kodi crashes during windows remote desktop sessions.
### Describe the bug
Here is a clear and concise description of what the problem is:

For the last few builds this month Kodi crashes during remote desktop sessions. Prior to this I could log onto my server using RDP without issue.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Connect to my server via RDP and configure Kodi as needed.

## Actual Behavior

Connect via RDP Kodi crashes instantly. 

### To Reproduce

1.  Run Kodi on a windows platform. 
2. Connect to that PC via RDP.
3.

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/yofolowijo.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
21.1 and its prior nightlies for the past two weeks?

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #25717: Kodi 21.1 in Windows Sandbox: error c0000005 at startup
I can't launch Kodi 21.1 in Window Sandbox: it exists right after the startup:

https://github.com/user-attachments/assets/a0747636-92bd-41be-b9f4-3508d1e4869e

Here's the error detail:

```xml
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
    <EventID>1000</EventID> 
    <Version>0</Version> 
    <Level>2</Level> 
    <Task>100</Task> 
    <Opcode>0</Opcode> 
    <Keywords>0x8000000000000000</Keywords> 
    <TimeCreated SystemTime="2024-09-09T16:03:25.5671875Z" /> 
    <EventRecordID>232</EventRecordID> 
    <Correlation /> 
    <Execution ProcessID="6212" ThreadID="2716" /> 
    <Channel>Application</Channel> 
    <Computer>68221410-d8b0-456a-8d7e-9cecdfe697e4</Computer> 
    <Security UserID="S-1-5-21-2047949552-857980807-821054962-504" /> 
  </System>
  <EventData>
    <Data Name="AppName">Kodi.exe</Data> 
    <Data Name="AppVersion">21.1.0.0</Data> 
    <Data Name="AppTimeStamp">66c05352</Data> 
    <Data Name="ModuleName">Kodi.exe</Data> 
    <Data Name="ModuleVersion">21.1.0.0</Data> 
    <Data Name="ModuleTimeStamp">66c05352</Data> 
    <Data Name="ExceptionCode">c0000005</Data> 
    <Data Name="FaultingOffset">0000000000202f64</Data> 
    <Data Name="ProcessId">0x1c80</Data> 
    <Data Name="ProcessCreationTime">0x1db02d1ccce9e2e</Data> 
    <Data Name="AppPath">C:\Program Files\Kodi\Kodi.exe</Data> 
    <Data Name="ModulePath">C:\Program Files\Kodi\Kodi.exe</Data> 
    <Data Name="IntegratorReportId">bed654e9-f36d-426b-802d-d70407882c9c</Data> 
    <Data Name="PackageFullName" /> 
    <Data Name="PackageRelativeAppId" /> 
  </EventData>
</Event>
```

### PR DESCRIPTION
**Pull request by thexai**
## Description
- Fix crash when audio device not has 'PKEY_Device_EnumeratorName' property
- Fix crash when computer is accessed with RDP.
- Fix https://github.com/xbmc/xbmc/issues/25635

## Motivation and context
Unfortunately the recent fix for Bluetooth audio devices (https://github.com/xbmc/xbmc/pull/25510) causes crash when computer is accessed with Microsoft Remote Desktop. As usual, changes are not tested massively until they reach the stable versions 😒

This is because special audio device is used to redirect audio with remote desktop and since is a virtual device not has `PKEY_Device_EnumeratorName` property despite `pProperty->GetValue` not returns error but S_OK.

The immediate fix is check also for `varName.pwszVal` not nullptr but since is also possible in others circunstancies  `pProperty->GetValue` return error, a better fix is make this optional as only is used to detect Bluetooth devices. I mean no worth abort enumeration of all audio devices with `goto failed` and instead continue when audio device not has "PKEY_Device_EnumeratorName".

Possible values of `PKEY_Device_EnumeratorName` are "USB",  "HDAUDIO", "BTHENUM" related to type of hardware used then is "logic" that virtual/software device not has any of these values. 

## How has this been tested?
Runtime Windows 11 23H2 accessed from other computer with RDP. Crash is reproducible before even from Visual Studio running Kodi in Debug mode and not reproducible after (this PR).

Original fix for Bluetooth audio devices continue working with regular audio devices. 

## What is the effect on users?
 Fix crash when computer is accessed with RDP and probably others issues with special/non-common audio devices types.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
jenkins build this please

File: xbmc/cores/AudioEngine/Sinks/windows/AESinkFactoryWin32.cpp [hunk 1]
```diff
@@ -130,14 +130,11 @@ std::vector<RendererDetail> CAESinkFactoryWin::GetRendererDetails()
     PropVariantClear(&varName);
 
     hr = pProperty->GetValue(PKEY_Device_EnumeratorName, &varName);
-    if (FAILED(hr))
+    if (SUCCEEDED(hr) && varName.pwszVal != nullptr)
     {
-      CLog::LogF(LOGERROR, "Retrieval of endpoint enumerator name failed.");
-      goto failed;
+      details.strDeviceEnumerator = KODI::PLATFORM::WINDOWS::FromW(varName.pwszVal);
+      StringUtils::ToUpper(details.strDeviceEnumerator);
```
Comment (CrystalP) [inline xbmc/cores/AudioEngine/Sinks/windows/AESinkFactoryWin32.cpp:136]: ok to make optional, but please keep logging errors of GetValue and null enumerator string.

**Comment by CrystalP** [comment]
AEWASAPIDeviceWin32::IsUSBDevice() seems vulnerable to the same issue, and could be simplified to use details.streviceEnumerator instead of opening the property bag again?

**Comment by thexai** [comment]
> AEWASAPIDeviceWin32::IsUSBDevice() seems vulnerable to the same issue, and could be simplified to use details.strDeviceEnumerator instead of opening the property bag again?

This is for another PR. I want do minimal changes here because is also a backport. `AEWASAPIDeviceWin32::IsUSBDevice()` not crash because by default always is used DirectSound with RDP. This is because all audio devices changes (system audio devices are temporally unavailable) and always fallback to default DirectSound device.

**Review by CrystalP — APPROVED** [review]
looks good.
