### PR TITLE
Fix Blu-Ray menus after PR20260 - CDVDOverlayImage: cleanup

### LINKED ISSUE #20544: CDVDOverlayImage: cleanup #20260 breaks JAVA menu's for blurays and UHD
## Bug report
since this PR has been merged JAVA menu's on bluray iso and folder rips are broken
Here is a clear and concise description of what the problem is:

when you start a bluray disk and the JAVA menu appears you often get an option to resume the movie or go to the menu's these options do not display and you are just left with the background of the menu and unable to watch the movie

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

when you launch the movie you should be greeted with menu options to select default language, resume or start over or go to main menu/play main title

## Actual Behavior

the background for the menu loads but no options appear to progress

## Possible Fix

remove the PR or rework it

### To Reproduce

1. install any version of Kodi V20 after or including KodiSetup-20211020-ac0d7632--x64
2.play a bluray title with full menu's
3.

### Debuglog

The debuglog can be found here: https://pastebin.com/R56nDdn2
debug log of a working build but with graphic corruption https://pastebin.com/pDApTNAh

### Screenshots 
Here are some links or screenshots to help explain the problem:

here is what it should look like https://ibb.co/6NQhGzY this is from kodi 19.3
this is what is does look like https://ibb.co/CKLBLJH

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

jjd-uk was helping me test this and supplied two builds, one worked and one didn't but the one that worked has graphical glitches that are not present in Kodi 19.3 so suspecting possibly another overlay PR would need looking at if one exists 

menu from Kodi 19.3 https://ibb.co/P6FjZGh no corruption

menu from KodiSetup-20211020-a497d89a--x64 https://ibb.co/QfpfjX9 graphical corruption

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 21h2
 - Kodi version: Nexus V20

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Fix Blu-Ray menus after PR20260 - CDVDOverlayImage: cleanup

Fixes https://github.com/xbmc/xbmc/issues/20544

## Motivation and context
Blu-Ray / Blu-Ray UHD menus are broken after https://github.com/xbmc/xbmc/pull/20260

This is not a revert of mentioned commit. This is an independent rework from a previous working version. Replaces alloc/calloc calls with vectors but avoids using additional vectors to move, copy, or transform data. That is, we try to optimize to the maximum without creating additional (unnecessary) copies of the data.

i.e. is much more efficient:

`uint32_t* rgba = reinterpret_cast<uint32_t*>(o->pixels.data());`

instead of:

`rgba = std::vector<uint32_t>(o->data.data(), o->data.data() + o->data.size());`

Also renames some variables to avoids confusing `data.data()`

Now is `overlay->pixels.data()`  and  `quads.texture.data()`

## How has this been tested?
Runtime tested Windows x64

## What is the effect on users?
Blu-Ray / Blu-Ray UHD menus are working again.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by thexai** [comment]
`OverlayRendererGL.cpp` code not tested at all as only tested on Windows x64

**Comment by lrusak** [comment]
You should split functional changes from formatting changes instead of lumping them all on one commit. That makes reviewing functional changes much easier.

**Comment by thexai** [comment]
> You should split functional changes from formatting changes

Too late 🙄

**Comment by thexai** [comment]
@lrusak 
If you are looking for an PR easy to review (only additions) you have https://github.com/xbmc/xbmc/pull/20645 waiting

**Review by enen92 — APPROVED** [review]
Gave this a whirl on Linux and couldn't find any regression. BR and DVD menus continue to work just like before. Tested also multiple subtitle formats (specially some obscure ASS animes) and all work well.
Great job, thanks much for fixing the regression!

**Comment by thexai** [comment]
@enen92  
Thank you for testing!

**Comment by fuzzard** [comment]
Just as a passing comment for potential reviewers, disable whitespace and it makes it more managable

https://github.com/xbmc/xbmc/pull/20873/files?w=1

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp [hunk 1]
```diff
@@ -43,32 +44,31 @@ static uint32_t build_rgba(int yuv[3], int alpha, bool mergealpha)
 }
 #undef clamp
 
-std::vector<uint32_t> convert_rgba(CDVDOverlayImage* o, bool mergealpha)
+void convert_rgba(CDVDOverlayImage* o, bool mergealpha, std::vector<uint32_t>& rgba)
```
Comment (lrusak) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp:47]: This seems odd. Is there a reason why you want to pass in an empty vector by reference rather than allocate the vector in the method and return it?

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp [hunk 2]
```diff
@@ -43,32 +44,31 @@ static uint32_t build_rgba(int yuv[3], int alpha, bool mergealpha)
...
-
-  return rgba;
+  for (int row = 0; row < o->height; row++)
+    for (int col = 0; col < o->width; col++)
+      rgba[row * o->width + col] = palette[o->pixels[row * o->linesize + col]];
 }
 
-std::vector<uint32_t> convert_rgba(
-    CDVDOverlaySpu* o, bool mergealpha, int& min_x, int& max_x, int& min_y, int& max_y)
+void convert_rgba(CDVDOverlaySpu* o,
```
Comment (lrusak) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp:62]: Same thing here.

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp [hunk 3]
```diff
@@ -159,21 +159,18 @@ std::vector<uint32_t> convert_rgba(
...
 {
   ASS_Image* img;
+  int count = 0;
 
   if (!images)
     return false;
 
   // first calculate how many glyph we have and the total x length
 
-  int count{0};
```
Comment (lrusak) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp:175]: Did you mean to move this? It seems irrelevant?

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.h [hunk 4]
```diff
@@ -17,28 +17,34 @@ class CDVDOverlaySpu;
...
-}
+namespace OVERLAY
+{
+
+struct SQuad
+{
+  int u, v;
+  unsigned char r, g, b, a;
+  int x, y;
+  int w, h;
```
Comment (lrusak) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.h:28]: one declaration per line please.

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererDX.cpp [hunk 5]
```diff
@@ -198,32 +199,21 @@ COverlayImageDX::~COverlayImageDX()
 
 COverlayImageDX::COverlayImageDX(CDVDOverlayImage* o)
 {
-  std::vector<uint32_t> rgba;
-  int stride;
-  if (!o->palette.empty())
+  if (o->palette.empty())
```
Comment (lrusak) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererDX.cpp:202]: Is there a reason you decided to invert this?

**Comment by lrusak** [comment]
> @lrusak If you are looking for an PR easy to review (only additions) you have #20645 waiting

???

**Review by lrusak — COMMENTED** [review]
I left some comments about some minors that I saw.

I do think there is some very valid optimizations in this PR and it is a solid improvement overtop #20260. Continued optimization and cleanup is greatly appreciated.

It would be nice if the formatting was separated into a separate commit (with or without the use of clang-format) as the formatting cleanups muddy the functional changes and it's not exactly clear what specifically fixed the issue you were seeing. Do you know what the actual problem turned out to be?

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp (hunk 1 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp:47]: Isn't this a best practice to avoid copying the vector later when it already has elements? We seem do to this everywhere

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.h (hunk 4 above)
Comment (garbear) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.h:28]: and initialize with the definition. The cost of `= 0` is far less than the cost of a bug

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp (hunk 1 above)
Comment (garbear) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp:47]: I haven't looked deeply, but RVO - return value optimization - might be a reason to allocate the vector in the method and return it

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp (hunk 3 above)
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp:175]: All changes from PR20260 should not be interpreted as fixups or things that were wrong. I have started from the functional code in Matrix without looking much at the code of the previous PR (so as not to be influenced and make the same mistakes). So the resulting code has been different, which on the other hand is what is expected and what I intended.

Once this has been effectively justified, the change is irrelevant and for this same reason it can also be left as it is.

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp (hunk 1 above)
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp:47]: Yes probably this is the reason. I want to be sure that a copy of the object is not produced. I know these are common optimizations in c++ but they are still compiler dependent and these RVO and NRVO optimizations are not always guaranteed to occur.

And from a cosmetic point of view seems not looks bad as is in line with other calls:

```c++
  convert_rgba(o, USE_PREMULTIPLIED_ALPHA, min_x, max_x, min_y, max_y, rgba);

  glGenTextures(1, &m_texture);
  glBindTexture(GL_TEXTURE_2D, m_texture);

  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
  glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);

  LoadTexture(GL_TEXTURE_2D, max_x - min_x, max_y - min_y, o->width * 4, &m_u, &m_v, false,
              rgba.data() + min_x + min_y * o->width);

  glBindTexture(GL_TEXTURE_2D, 0);
```

**Comment by thexai** [comment]
I am going to proceed to merge the PR since it has been tested on Windows x64 and Linux, it has an approval, and the clang format is correct since Jenkins is 100% happy. But mostly because this PR fixes an important functionality that is currently broken in master.

Possible minor code formatting issues, as well as possible new warnings that arise (static analysis) will be addressed, if necessary, in a follow-up PR in one or two weeks.

**Comment by lrusak** [comment]
So is this the precedent we are setting? As long as the PR can be merged it should be merged? Without addressing comments/concerns from others?

If you were really concerned about fixing the issue that is all you would have changed without making all the other unnecessary changes.

This behaviour concerns me.

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp (hunk 1 above)
Comment (garbear) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererUtil.cpp:47]: As time go on, some compiler-specific optimizations do become guaranteed actually. I'm pretty sure that RVO is one of those and is now guaranteed
