### PR TITLE
[moviesets] allow to add movie to set if there's only one member so far

### LINKED ISSUE #15814: Movie Sets with one member don't appear in "Select movie set" list
### Describe the bug

If a movie set contains one member, and the setting `Include sets containing a single movie` is disabled, then it is not possible to add a second member to the Movie Set as the Movie Set is not listed in the `Manage movie set` > `Select movie set` dialog.

## Expected Behavior

All Movie Sets with single or multiple movies should be listed in the `Select movie sets` dialog regardless of the `Include sets containing a single movie` setting.

## Actual Behavior

Movie Sets that contain a single movie are not listed in the `Select movie sets` dialog, making it (almost) impossible to add a second movie to an existing Movie Set that contains only a single movie.

## Possible Fix

Presumably a SQL query somewhere needs to ignore the single-movie filter when populating the "Select movie sets" dialog. Not sure if the same query is used for the "Select movie set" dialog as it is elsewhere, which would complicate the change.

### To Reproduce

1. Set `Include sets containing a single movie` to disabled
2. Enter the Movies listing
3. For any random movie (not already in a movie set), from the context menu select `Manage...` > `Manage Movie Set` then click on `Add movie to a new set` and create Movie Set `ABC`
4. For a second random movie (not already in a movie set), from the context menu select `Manage...` > `Manage Movie Set`
5. Attempt to add the second movie to the Movie Set `ABC` - the movie set `ABC` is not listed

Clicking `Add movie to a new set` and then entering the title of the existing Movie Set (ie. `ABC`) will allow the second movie to be added to the existing Movie Set, at which point the Movie Set `ABC` will start to appear in the `Select movie set` dialog list whenever adding additional movies.

Obviously this solution isn't practical unless the name of the Movie Set is trivially simple (as per the example).

### Debuglog

Not relevant.

### Screenshots 

This is the meta data for the Movie Set `Fantastic Beasts Collection` when attempting to add a second movie set member:
```
  {
    "art": {
      "fanart": "image://nfs://192.168.0.3/mnt/share/media/Video/MoviesHD/Fantastic Beasts Collection/fanart.jpg/",
      "poster": "image://nfs://192.168.0.3/mnt/share/media/Video/MoviesHD/Fantastic Beasts Collection/poster.jpg/"
    },
    "label": "Fantastic Beasts Collection",
    "setid": 79,
    "tc.members": [
      {
        "file": "nfs://192.168.0.3/mnt/share/media/Video/MoviesHD/Fantastic Beasts Collection/Fantastic Beasts - The Crimes of Grindelwald (2018)[BDRip].mkv",
        "movieid": 2771,
        "sorttitle": "FB02",
        "title": "Fantastic Beasts: The Crimes of Grindelwald"
      }
    ],
    "title": "Fantastic Beasts Collection"
  },
```
`Include sets containing a single movie` disabled:
s1
s2

`Include sets containing a single movie` enabled:
s3
s4

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 10.0 (test build)
 - Kodi version: 18.2 master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by howie-f**
## Description
This change allows us to add movies to a movieset if there's only one member so far and _"Include sets containing a single movie"_ is disabled.

## Motivation and Context
closes  #15814, #15984 and https://trac.kodi.tv/ticket/17880

## How Has This Been Tested?
local build of current master on debian

## Screenshots (if appropriate):

screenshot002

the duplicate entry in this dialog "ABC" is now removed!

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

maybe @MilhouseVH and/or @KarellenX would like to look into this?

### CODE REVIEW

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp [hunk 1]
```diff
@@ -1663,6 +1681,8 @@ bool CGUIDialogVideoInfo::GetSetForMovie(const CFileItem *movieItem, CFileItemPt
     CFileItemPtr keepItem(new CFileItem(strKeep));
     keepItem->GetVideoInfoTag()->m_iDbId = currentSetId;
     listItems.AddFront(keepItem, 1);
+
+    // we should remove the duplicate entry for the current set from listItems
```
Comment (howie-f) [inline xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1685]: if this is wanted i would appreciate some pointing out 🙂

**Comment by KarellenX** [comment]
Thanks @howie-f 

This fixes an old trac ticket I submitted 2 years ago...
https://trac.kodi.tv/ticket/17880

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp [hunk 2]
```diff
@@ -1636,10 +1636,22 @@ bool CGUIDialogVideoInfo::GetSetForMovie(const CFileItem *movieItem, CFileItemPt
...
+  // if "Include sets containing a single movie" is disabled in settings
+  // we need to temporary enable it while fetching the movieset list ...
+  if (!m_groupSingleItemSets)
+    settings->SetBool(CSettings::SETTING_VIDEOLIBRARY_GROUPSINGLEITEMSETS, true);
+
   CFileItemList listItems;
-  std::string baseDir = "videodb://movies/sets/";
-  if (!CDirectory::GetDirectory(baseDir, listItems, "", DIR_FLAG_DEFAULTS))
-    return false;
+  CDirectory::GetDirectory("videodb://movies/sets/", listItems, "", DIR_FLAG_DEFAULTS);
```
Comment (howie-f) [inline xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1649]: removing the exit-code check had no negative effects with an emptied „sets“-table

**Comment by howie-f** [comment]
hy @enen92 
are you in the mood for a review? i know this is probably the damn worst thing i ever pushed up, stumbled upon the nasty thing a few days ago. i just wonder if we can do something better, this is not a fix but an ugly workaround 😙

**Comment by phunkyfish** [comment]
If it's an ugly workaround then we shouldn't put it in IMO ;)

Is the issue that GetDirectory obeys this setting? Or are other parts a hack too?

**Comment by howie-f** [comment]
> Is the issue that GetDirectory obeys this setting?

that's exactly the point.

if i get it right we're somewhere here:
https://github.com/xbmc/xbmc/blob/d1887984dd5536ca5c28108f563b9da2d216fbec/xbmc/filesystem/Directory.cpp#L151-L156
and single-movie-collections aren't returned to fill the list.

this pr performs the advice in the wiki: https://kodi.wiki/view/Movie_sets
```
**3.2 Kodi Movie Set Editor**
Note: Ensure you have enabled the setting Include sets containing a single movie
otherwise sets with a single movie will not be listed in the Movie Set Editor shown
in Image 3 above. This setting can be enabled without enabling the parent setting
Show movie sets.
```

i'm fine with closing it anyway, no prob ;)

**Comment by phunkyfish** [comment]
I’m curious to find out the correct way to do this is all 😉

**Comment by howie-f** [comment]
> I’m curious to find out the correct way to do this is all 😉

me too..... 👻

**Comment by enen92** [comment]
@howie-f sorry I don't use moviesets nor am I familiar with them. I am thus unable to review this.

**Comment by jjd-uk** [comment]
If I recall correctly @Montellese did something with sets a long...long...long time ago.

**Comment by Montellese** [comment]
@jjd-uk Yeah I've basically implemented movie sets together with Jonathan a long time ago. And it was already a pain back then - mostly because basically every user wanted movie sets to behave differently than every other user...

@howie-f Concerning this change IMO the workaround is problematic because Kodi is multi-threaded so while the setting is temporarily disabled something else might also retrieve the item list for `videodb://movies/sets/` and would get an unexpected result.

I haven't looked into this part of the code in a long time but maybe the proper solution would be to add an option to the URL like `videodb://movies/sets/?includesetswithonemovie=true` and check for that option in `CVideoDatabase::GetSetsByWhere()` (or wherever it checks the setting). Then there would be four possibilities:
* the `includesetswithonemovie` option is not present and the setting is disabled --> don't include sets with a single movie
* the `includesetswithonemovie` option is not present and the setting is enabled --> include sets with a single movie
* the `includesetswithonemovie` option is present and is `false` --> don't include sets with a single movie
* the `includesetswithonemovie` option is present and is `true` --> include sets with a single movie

**Comment by howie-f** [comment]
thanks for the insights @Montellese 
yes i am convinced it's problematic, but your approach looks promising.
i'll just happily try to put it together then.

File: xbmc/video/VideoDatabase.cpp [hunk 3]
```diff
@@ -6304,7 +6304,21 @@ bool CVideoDatabase::GetSetsByWhere(const std::string& strBaseDir, const Filter
       return false;
 
     CFileItemList sets;
-    GroupAttribute groupingAttributes = ignoreSingleMovieSets ? GroupAttributeIgnoreSingleItems : GroupAttributeNone;
+    GroupAttribute groupingAttributes;
+    const CUrlOptions::UrlOptions& options = videoUrl.GetOptions();
+    auto option = options.find("includesetswithonemovie");
```
Comment (howie-f) [inline xbmc/video/VideoDatabase.cpp:6309]: should this new option `includesetswithonemovie` get documented (doxy/wiki/both) ? @AlwinEsch

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp [hunk 4]
```diff
@@ -1638,7 +1638,7 @@ bool CGUIDialogVideoInfo::GetSetForMovie(const CFileItem *movieItem, CFileItemPt
     return false;
 
   CFileItemList listItems;
-  std::string baseDir = "videodb://movies/sets/";
+  std::string baseDir = "videodb://movies/sets/?includesetswithonemovie=true";
```
Comment (enen92) [inline xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1641]: Shouldn't the baseDir, as the name states, be the base without including any further options? And the option be injected by the functionality that actually requires that option?

File: xbmc/video/VideoDatabase.cpp (hunk 3 above)
Comment (AlwinEsch) [reply xbmc/video/VideoDatabase.cpp:6309]: Would be good to have on both, as it relate to parts outside.

Not sure, think in doxygen the whole show of available variables like "videodb://movies/sets/?includesetswithonemovie=true" not descripted :thinking:.

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp (hunk 4 above)
Comment (howie-f) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1641]: > actually the only place where the options should be used..

yes, actually it's the only place. we have  calls to `videodb://movies/sets/` wide spread throughout the codebase. when that happens (without added option) the functionality doesn't change. we need this option when filling the movieset-editor, because it should always return "single-movie-sets", so they can be fed with more movies. would definitely add a comment at this point. renaming? hm, matter of taste i think, but no problem if forced ;)

File: xbmc/video/VideoDatabase.cpp (hunk 3 above)
Comment (Montellese) [reply xbmc/video/VideoDatabase.cpp:6309]: AFAIK none of these options are documented. Back when most of these were introduced we didn't even have doxygen properly setup / integrated.

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp (hunk 4 above)
Comment (Montellese) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1641]: I agree that the variable name `baseDir` is not ideal. Unforunately it's used throughout a lot of old code.

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp [hunk 5]
```diff
@@ -1664,6 +1664,15 @@ bool CGUIDialogVideoInfo::GetSetForMovie(const CFileItem *movieItem, CFileItemPt
     CFileItemPtr keepItem(new CFileItem(strKeep));
     keepItem->GetVideoInfoTag()->m_iDbId = currentSetId;
     listItems.AddFront(keepItem, 1);
+    // remove duplicate entry
```
Comment (Montellese) [inline xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1667]: If you would move this logic up to before the clear item and the current set are added the code could be cleaner without having to remember to start at `listIndex = 2`.

**Review by Montellese — APPROVED** [review]
Looks good in general apart from the minors I commented on.

**Review by enen92 — APPROVED** [review]

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp [hunk 6]
```diff
@@ -1638,7 +1638,13 @@ bool CGUIDialogVideoInfo::GetSetForMovie(const CFileItem *movieItem, CFileItemPt
     return false;
 
   CFileItemList listItems;
-  std::string baseDir = "videodb://movies/sets/";
+
+  // "includesetswithonemovie=true" as option in the url is needed here
+  // to override the gui-setting "Include sets containing a single movie"
+  // and retrieve all moviesets
+
+  std::string baseDir = "videodb://movies/sets/?includesetswithonemovie=true";
```
Comment (howie-f) [inline xbmc/video/dialogs/GUIDialogVideoInfo.cpp]: too bad. i missed that 🤗 next round

File: xbmc/video/dialogs/GUIDialogVideoInfo.cpp [hunk 7]
```diff
@@ -1582,9 +1582,10 @@ bool CGUIDialogVideoInfo::GetMoviesForSet(const CFileItem *setItem, CFileItemLis
   if (!videodb.Open())
     return false;
 
-  std::string baseDir = StringUtils::Format("videodb://movies/sets/%d", setItem->GetVideoInfoTag()->m_iDbId);
+  std::string dir =
```
Comment (DaveTBlake) [inline xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1585]: I know that a previous comment from @enen92 suggested you rename the variable to just dir, but the final implementation you have  makes the variable name change the only change in this unit. Hence why do it? For me it just makes it hard to see what you have done.

Comment (enen92) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1585]: He did it on a second commit, actual logic changes are in https://github.com/xbmc/xbmc/pull/17865/commits/7c738a9dc64d6e062669b7269426e6c2c8ff0f88

Comment (DaveTBlake) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1585]: Fair enough, but I wouldn't change a var name at all in this kind of work it really does not make anything less confusing. `basDir` is commonly used as a var name for similar purposes thoughout the older code, maybe I am just familiar with it.

Comment (howie-f) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1585]: as i said, a matter of taste. imo we can stay with `baseDir` i just wanted to take the opportunity due to the suggestion. as the whole thing is not yet 100%-ready (checking a 2nd dialog) we can decide what to do with the cleanup commit. to me it makes no big difference (apart from a confusing diff)

Comment (DaveTBlake) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp:1585]: Yes, sorry @howie-f that you are piggy-in-the-middle here over a var name discussion. Total madness :)

Comment (howie-f) [reply xbmc/video/dialogs/GUIDialogVideoInfo.cpp]: np, decided to cut off

**Comment by phunkyfish** [comment]
I will merge this tomorrow.

**Comment by howie-f** [comment]
yeah thanks. this was a last polishing

**Comment by howie-f** [comment]
who would usually update the wiki? unfortunately i cannot do this...

**Comment by KarellenX** [comment]
@howie-f 

Is it this page you need updated? https://kodi.wiki/view/Movie_sets

What do you need updated?

**Comment by howie-f** [comment]
@KarellenX yes, that‘s it. the note under 3.2. needs removal. i‘m just not sure because it‘s v19 right now and as it‘s a feature it won‘t be backported...

**Comment by KarellenX** [comment]
Modified the note. Can't remove just yet as v18 is still current.
