### PR TITLE
[video] VideoSelectActionProcessor: On ACTION_INFO, if the item has …

### LINKED ISSUE #25217: Setting "Media > Videos > Default select action" to "Show information" leads to issues when clicking on non-DB video video files (since Kodi 20)
### Describe the bug

Setting 
"Media > Videos > Default select action" to "Show information" 
leads to issues when clicking on non-DB video video files (since Kodi 20)

## Expected Behavior

With the described setting, non-DB video files should simply just play as they did with Kodi 19 instead of opening any dialogs

## Actual Behavior

On Kodi 20, clicking on such video files leads to a dialog telling the user "Show video information - No information available"

On Kodi 21-22, clicking on such files leads to opening an empty "DialogVideoInfo"-dialog for the non-DB video file.

## Possible Fix

not sure

### To Reproduce

see above

### Debuglog

.
### Screenshots 

.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10
 - Kodi version: Kodi 20-22

### PR DESCRIPTION
**Pull request by ksooo**
…no video db info data, fall back to resume/play.

Fixes #25217 and complaints on the Forum regarding changed behavior.

Runtime-tesed on macOS and Android, latest Kodi master.

@enen92 maybe you can have a look at the code change?

### CODE REVIEW

**Comment by Hitcher** [comment]
Hopefully you've made everyone happy now, thanks.

File: xbmc/video/guilib/VideoSelectActionProcessor.cpp [hunk 1]
```diff
@@ -70,7 +71,17 @@ bool CVideoSelectActionProcessorBase::Process(Action action)
       return OnQueueSelected();
 
     case ACTION_INFO:
+    {
+      if (GetDefaultAction() == ACTION_INFO && !KODI::VIDEO::IsVideoDb(*m_item) &&
+          !m_item->IsPlugin() && !m_item->IsScript() &&
+          !KODI::VIDEO::UTILS::HasItemVideoDbInformation(*m_item))
+      {
+        // for items without info fall back to resume/play
+        return OnResumeSelected();
```
Comment (neo1973) [inline xbmc/video/guilib/VideoSelectActionProcessor.cpp:80]: How about this instead, honoring the configured default play action?
```suggestion
        return Process( CVideoPlayActionProcessorBase::GetDefaultAction() );
```

Comment (ksooo) [reply xbmc/video/guilib/VideoSelectActionProcessor.cpp:80]: Yes, that's better. Will change.

**Comment by ksooo** [comment]
jenkins build this please

**Review by neo1973 — APPROVED** [review]

**Comment by ksooo** [comment]
jenkins build this please
