### PR TITLE
fixed: always update stream details from player (fixes #15584)

### LINKED ISSUE #15584: Audio info not updated when replacing a video file with same name but different audio!
### Describe the bug
Here is a clear and concise description of what the problem is:

In Kodi 18 if you have a Movie for example "Rocky" that has Dolby Digital audio and then you replace it with a newer "Rocky" that has DTS audio. The movie information will remain showing Dolby Digital instead of DTS.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Audio info should be updated when replacing a movie with the same name but different audio!

## Actual Behavior

Audio info is never updated when replacing a Movie or TV Show with the same name but different audio!

## Possible Fix

Only fix would be to go back to Kodi 17 and use Metropolis Skin as the audio info always got updated after starting a movie with the new audio. However even in Kodi 17 the default Estuary Skin would not show the updated audio info.

### To Reproduce

1. Add a Movie with Dolby Digital
2. Replace same movie with DTS version
3. Check audio info for same Movie and it will still say Dolby Digital when it should now say DTS!

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by arnova**
## Description
This fixes a regression introduced by v18. Basically we should always update the stream details from the player, no matter what.

## Motivation and Context
It fixes a regression bug ;-)

## How Has This Been Tested?
No brainer

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by arnova** [comment]
@FernetMenta : I assume you're also fine with this?

**Comment by DaveTBlake** [comment]
What about where some of the details are not in the stream itself but provided by say an addon that started the playback? I don't if know that happens, but I know that some item properties can be set via Python so is it possible?

The "get_stream_details_from_player" property may not have been implemented/updated correctly, but there must have been a reason for it, and are you sure that reason is no longer valid?

**Comment by arnova** [comment]
No I'm not sure about the original "reason" but I do know we always want to update stream details, like we always did in v17 (and older). An additional benefit of doing this is for (low powered) systems where auto stream detail extraction is disabled, and we still retrieve stream details this way.

**Comment by da-anda** [comment]
this is the PR that introduced the code that's changed here:
https://github.com/xbmc/xbmc/pull/13566

**Comment by DaveTBlake** [comment]
>I do know we always want to update stream details

Reading https://github.com/xbmc/xbmc/pull/13566 that seems not always to be the case. Maybe @AkariDN should be given the chance to explain, or suggest another solution to the issue

**Comment by FernetMenta** [comment]
if you want to break https://github.com/xbmc/xbmc/pull/13566, go ahead :)

**Comment by arnova** [comment]
@FernetMenta : From what I get the guy that did #13566 didn't realise that we previously always would update the db with player's stream details so this doesn't break #13566 but simply restores the old logic, still supporting #13566. The only thing is that setting the additional property is a nul-operation now.

**Comment by da-anda** [comment]
from what I recall some users didn't want that VP did overwrite whatever was scanned into the DB, because when you think about DVDs and BluRays the stream itself might be 16:9 but the actual movie might be 21:9 and be encoded with black bars. So VP would overwrite 21:9 with 16:9 again, wouldn't it?

**Comment by arnova** [comment]
@FernetMenta : Didn't the "update stream details by default" logic get lost with the whole player/app refactor that was done for v18? That may have confused @AkariDN

**Comment by arnova** [comment]
> from what I recall some users didn't want that VP did overwrite whatever was scanned into the DB, because when you think about DVDs and BluRays the stream itself might be 16:9 but the actual movie might be 21:9 and be encoded with black bars. So VP would overwrite 21:9 with 16:9 again, wouldn't it?

Could be, but than we need another mechanism than this since now the cure is worse than the disease. "The old behavior" where you always update the stream details is what you want in the majority of cases and only for a few corner cases you want the "new behavior".

**Comment by FernetMenta** [comment]
Updating stream details in general was dropped by @peak3d because the implementation was crap and resulted in segfaults: https://github.com/xbmc/xbmc/pull/12651
btw: even this old behavior had a condition. In other words stream details were not updated for all cases.

**Comment by arnova** [comment]
> Updating stream details in general was dropped by @peak3d because the implementation was crap and resulted in segfaults: #12651
> btw: even this old behavior had a condition. In other words stream details were not updated for all cases.

But the segfault can't occur now anymore, since it uses a callback from player now, right? So the only issue that remains then is the exclusion of some types (which we could c-p from the old code) and optionally force update those which the property is set (?)

**Comment by AkariDN** [comment]
> Maybe @AkariDN should be given the chance to explain, or suggest another solution to the issue

Stream details for internet streams were not updated in 18a2 so I implemented this logic to allow plugins to save stream details from VP by setting this property to fileitem.

**Comment by arnova** [comment]
> 
> 
> > Maybe @AkariDN should be given the chance to explain, or suggest another solution to the issue
> 
> Stream details for internet streams were not updated in 18a2 so I implemented this logic to allow plugins to save stream details from VP by setting this property to fileitem.

But what's the point of only setting the stream details when this property is set? Why not always do it?

**Comment by AkariDN** [comment]
> Why not always do it?

I didn't know exactly the reason why this old behavior was dropped and not re-implemented. I just wanted to make it work again for plugins without globally changing the current behavior and add more flexibility. It would be better to discuss it with FernetMenta and peak3d.

**Comment by arnova** [comment]
@peak3d / @FernetMenta : I've reinstated the old logic to determine whether we should update stream details. Please let me know what you think. I still believe the new property that was introduced for this can go, right?

**Comment by peak3d** [comment]
@arnova have you found the PR which removed the 17.x functionality ?

**Comment by arnova** [comment]
> @arnova have you found the PR which removed the 17.x functionality ?

@peak3d : Yes, as mentioned by @FernetMenta : #12651

File: xbmc/Application.cpp [hunk 1]
```diff
@@ -3047,9 +3047,12 @@ void CApplication::OnPlayBackStarted(const CFileItem &file)
 {
   CLog::LogF(LOGDEBUG,"CApplication::OnPlayBackStarted");
 
-  // check if VideoPlayer should set file item stream details from its current streams
-  if (file.GetProperty("get_stream_details_from_player").asBoolean())
+  /* Always update streamdetails, except for DVDs where we only update
+     streamdetails if total duration > 15m (Should yield more correct info) */
+  if (!(file.IsDiscImage() || file.IsDVDFile()) || m_appPlayer.GetTotalTime() > 15*60*1000)
```
Comment (FernetMenta) [inline xbmc/Application.cpp]: GetTotalTime is undefined / zero at OnPlayBackStarted

Comment (arnova) [reply xbmc/Application.cpp]: @FernetMenta : Good point. Any idea how to proceed with this? Perhaps only drop the GetTotalTime()-part and replace it with the GetProperty() call ?

Comment (FernetMenta) [reply xbmc/Application.cpp]: For what reason do you place the code into OnPlaybackStarted?

Comment (da-anda) [reply xbmc/Application.cpp]: would you suggest `OnAVStarted()`? There all the required info should be ready, right?

Comment (FernetMenta) [reply xbmc/Application.cpp]: To me the intent described by the comment does not make much sense. Maybe some workaround to skip intro tracks instead of properly detecting the main title. Orignally introduced by @notspiff https://github.com/xbmc/xbmc/commit/8877348f00f15f51ff1955d39acfd4f21fb6050d
If you are not able to determine the original intent, it is better to drop the condition and save stream details always.

Comment (arnova) [reply xbmc/Application.cpp]: Yes, makes sense. Changed it back to what I initially had.

**Comment by arnova** [comment]
So we merge this "as-is" or is there anything else we need to take care of?

**Comment by gate1975mlm** [comment]
Hello,
I was one of the original people who reported this issue and was just wondering if this will be fixed and a build will be available to try? Thanks :)

**Comment by arnova** [comment]
ping @FernetMenta / @notspiff

**Comment by FernetMenta** [comment]
@arnova I think for the majority of cases this is correct. If you start videos with intros and and stop while playing the into, you'll get the details form the into stored. Maybe it has always been like this and the exclusion was just for DVDs. Personally I don't care much about DVDs because this format is dead anyway.

**Comment by arnova** [comment]
@FernetMenta : Yes my idea exactly: dvd is a dead horse. And if "issues" do popup we'll solve those then.

**Comment by KarellenX** [comment]
Note to self for future reference... 
https://forum.kodi.tv/showthread.php?tid=342336&pid=2838656#pid2838656

It was impossible to save stream details for DVD and Bluray folder before this fix.

**Comment by KarellenX** [comment]
Hello @arnova 

Surprisingly this fix does not work for movies saved as DVD folders. Is there a chance you could look at it again? Bluray and ISO's seem to work though.

https://forum.kodi.tv/showthread.php?tid=342336&pid=2838734#pid2838734

Thanks

**Comment by arnova** [comment]
@KarellenX : I created https://github.com/arnova/xbmc/commit/0c4108fe1e28624d9f675414fa82609745773979 which should fix it, but somehow it's not picked up by the skin. I don't have the time at the moment to further look into it, but for others this may be a good starting point.

**Comment by MilhouseVH** [comment]
Since this PR merged, after playback ends the `aspect` ratio and several audio properties are overwritten with `0.0` or dropped entirely.

This affects 18.2, 18.3 and master.

Reproducible in LibreELEC and Ubuntu.

https://forum.kodi.tv/showthread.php?tid=343962
https://forum.kodi.tv/showthread.php?tid=343811

For example, the following JSON query:
```
{"jsonrpc": "2.0", "params": {"sort": {"order": "ascending", "method": "title"}, "filter": {"operator": "contains", "field": "title", "value": "Final Cut"}, "properties": ["title", "art", "file", "trailer", "streamdetails", "mpaa", "rating", "plot", "dateadded", "playcount", "runtime", "country", "lastplayed", "imdbnumber", "votes", "resume"], "limits": {"start": 0, "end": 400}}, "method": "VideoLibrary.GetMovies", "id": "libMovies"}
```

With this PR **BEFORE** playback:
```
[
  {
    "art": {
      "fanart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/Blade Runner - The Final Cut (2007)[BDRip]-fanart.jpg/",
      "poster": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/Blade Runner - The Final Cut (2007)[BDRip]-poster.jpg/",
      "set.fanart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/fanart.jpg/",
      "set.poster": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/poster.jpg/"
    },
    "country": [
      "USA",
      "Hong Kong"
    ],
    "dateadded": "2018-02-17 14:42:30",
    "file": "nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/Blade Runner - The Final Cut (2007)[BDRip].mkv",
    "imdbnumber": "tt0083658",
    "label": "Blade Runner - The Final Cut",
    "lastplayed": "2019-06-28 22:37:21",
    "movieid": 2777,
    "mpaa": "Rated R for violence and brief nudity (Definitive Cut)",
    "playcount": 66,
    "plot": "In a cyberpunk vision of the future, man has developed the technology to create replicants, human clones used to serve in the colonies outside Earth but with fixed lifespans. In Los Angeles, 2019, Deckard is a Blade Runner, a cop who specialises in terminating replicants. Originally in retirement, he is forced to re-enter the force when six replicants escape from an offworld colony to Earth.",
    "rating": 8.300000190734863,
    "resume": {
      "position": 3769.0,
      "total": 7056.0
    },
    "runtime": 7056,
    "streamdetails": {
      "audio": [
        {
          "channels": 6,
          "codec": "ac3",
          "language": "eng"
        },
        {
          "channels": 6,
          "codec": "truehd",
          "language": "eng"
        },
        {
          "channels": 2,
          "codec": "ac3",
          "language": "eng"
        },
        {
          "channels": 2,
          "codec": "ac3",
          "language": "eng"
        },
        {
          "channels": 2,
          "codec": "ac3",
          "language": "eng"
        }
      ],
      "subtitle": [],
      "video": [
        {
          "aspect": 1.777999997138977,
          "codec": "wvc1",
          "duration": 7056,
          "height": 1080,
          "language": "eng",
          "stereomode": "",
          "width": 1920
        }
      ]
    },
    "title": "Blade Runner - The Final Cut",
    "trailer": "",
    "votes": "254073"
  }
]
```

With this PR **AFTER** playback:
```
[
  {
    "art": {
      "fanart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/Blade Runner - The Final Cut (2007)[BDRip]-fanart.jpg/",
      "poster": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/Blade Runner - The Final Cut (2007)[BDRip]-poster.jpg/",
      "set.fanart": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/fanart.jpg/",
      "set.poster": "image://nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/poster.jpg/"
    },
    "country": [
      "USA",
      "Hong Kong"
    ],
    "dateadded": "2018-02-17 14:42:30",
    "file": "nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/Blade Runner - The Final Cut (2007)[BDRip].mkv",
    "imdbnumber": "tt0083658",
    "label": "Blade Runner - The Final Cut",
    "lastplayed": "2019-06-28 22:42:52",
    "movieid": 2777,
    "mpaa": "Rated R for violence and brief nudity (Definitive Cut)",
    "playcount": 66,
    "plot": "In a cyberpunk vision of the future, man has developed the technology to create replicants, human clones used to serve in the colonies outside Earth but with fixed lifespans. In Los Angeles, 2019, Deckard is a Blade Runner, a cop who specialises in terminating replicants. Originally in retirement, he is forced to re-enter the force when six replicants escape from an offworld colony to Earth.",
    "rating": 8.300000190734863,
    "resume": {
      "position": 3770.0,
      "total": 7056.0
    },
    "runtime": 7056,
    "streamdetails": {
      "audio": [
        {
          "channels": 6,
          "codec": "truehd",
          "language": "eng"
        }
      ],
      "subtitle": [],
      "video": [
        {
          "aspect": 0.0,
          "codec": "vc1",
          "duration": 7056,
          "height": 1080,
          "language": "eng",
          "stereomode": "",
          "width": 1920
        }
      ]
    },
    "title": "Blade Runner - The Final Cut",
    "trailer": "",
    "votes": "254073"
  }
]
```

Diff:
```
--- /tmp/before-playback        2019-06-28 22:42:43.875956298 +0100
+++ /tmp/after-playback 2019-06-28 22:42:56.672061876 +0100
@@ -14,14 +14,14 @@
     "file": "nfs://192.168.0.3/mnt/share/media/Video-Private/MoviesHD/Blade Runner/Blade Runner - The Final Cut (2007)[BDRip].mkv",
     "imdbnumber": "tt0083658",
     "label": "Blade Runner - The Final Cut",
-    "lastplayed": "2019-06-28 22:37:21",
+    "lastplayed": "2019-06-28 22:42:52",
     "movieid": 2777,
     "mpaa": "Rated R for violence and brief nudity (Definitive Cut)",
     "playcount": 66,
     "plot": "In a cyberpunk vision of the future, man has developed the technology to create replicants, human clones used to serve in the colonies outside Earth but with fixed lifespans. In Los Angeles, 2019, Deckard is a Blade Runner, a cop who specialises in terminating replicants. Originally in retirement, he is forced to re-enter the force when six replicants escape from an offworld colony to Earth.",
     "rating": 8.300000190734863,
     "resume": {
-      "position": 3769.0,
+      "position": 3770.0,
       "total": 7056.0
     },
     "runtime": 7056,
@@ -29,35 +29,15 @@
       "audio": [
         {
           "channels": 6,
-          "codec": "ac3",
-          "language": "eng"
-        },
-        {
-          "channels": 6,
           "codec": "truehd",
           "language": "eng"
-        },
-        {
-          "channels": 2,
-          "codec": "ac3",
-          "language": "eng"
-        },
-        {
-          "channels": 2,
-          "codec": "ac3",
-          "language": "eng"
-        },
-        {
-          "channels": 2,
-          "codec": "ac3",
-          "language": "eng"
         }
       ],
       "subtitle": [],
       "video": [
         {
-          "aspect": 1.777999997138977,
-          "codec": "wvc1",
+          "aspect": 0.0,
+          "codec": "vc1",
           "duration": 7056,
           "height": 1080,
           "language": "eng",
```

Complete NFO is here: http://ix.io/1Na3
