### PR TITLE
[addons] fix: don't check updated repos for updates during migration

### LINKED ISSUE #18723: Add-on migration stuck on Kodi update from Leia to Matrix
### Describe the bug
Here is a clear and concise description of what the problem is:

I was tested the new repository structure for automatic add-on updating from my repository at Kodi 19 update and ran into the problem of the Kodi freezing on message "Add-on migration in progress - please wait...".
I tested on alpha-3 build. Here is profile folder, which was used in tests: [kodi_data.zip](https://vlmaksime.github.io/repository.vlmaksime.test/files/kodi_data.zip)
According kodi.log, it's freezing after updating of my repository, here is full log: [kodi.log](https://vlmaksime.github.io/repository.vlmaksime.test/files/kodi_matrix.log)
I'm waited about 20 minutes, before stopping Kodi process. After Kodi restarts, it successfully completes add-on migration. 
Here is repository, that I'm using for tests: [vlmaksime.repository.test](https://vlmaksime.github.io/repository.vlmaksime.test/repo/)

I also noticed that add-ons disappear from the list if an error with a dependency occurred during their update.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After repository updating, Kodi should install updates for add-ons, presented at my Matrix repository. Then it should open user interface, but not stuck on loading screen.

## Actual Behavior

After successful update of my repository add-on, Kodi freezing on message "Add-on migration in progress - please wait...".
If I remove repository add-on before Kodi update, it's loads successful.

### To Reproduce

1. Unpack [kodi_data.zip](https://vlmaksime.github.io/repository.vlmaksime.test/files/kodi_data.zip) into Kodi 19 data folder
2. Launch Kodi

### Debuglog

The debuglog can be found here:
[kodi.log](https://vlmaksime.github.io/repository.vlmaksime.test/files/kodi_matrix.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 x64
 - Kodi version: 19.0-ALPHA3 (18.9.730)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by howie-f**
## Description
If third-party repositories are updated during a migration v18 -> v19 process and checked for content updates afterwards, kodi would stuck on the startup splash `Add-on migration in progress - please wait...`

the root issue may be competing `CheckForUpdates()` calls that submit update-jobs. this pr skips the content-update-check for repositories during addon-migration. as we are reaching beta this approach needs to be assessed at a later point

## Motivation and Context
closes #18723 
thanks to @vlmaksime for reporting and providing your repo for testing 

## How Has This Been Tested?
confirm passing addon migration with the provided home-directory
https://vlmaksime.github.io/repository.vlmaksime.test/files/kodi_data.zip
debian buster

@glennguy would be nice if you could test if this pr affects/harms the changes you introduced with #18417
@phunkyfish 

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document

### CODE REVIEW

File: xbmc/addons/AddonInstaller.h [hunk 1]
```diff
@@ -56,6 +56,12 @@ enum class InstallModalPrompt
   NO_PROMPT,
 };
 
+enum class MigrationJob
```
Comment (phunkyfish) [inline xbmc/addons/AddonInstaller.h:59]: This might be better called `MigrationActive` as it is is used not only in `DoInstall` which is job specific but also in `InstallAddonUpdates` and `InstallAddons`.

Comment (enen92) [reply xbmc/addons/AddonInstaller.h:59]: Or even be made more generic and not implementation specific. Migration is only a possible use of the add-on updates method, it should then be agnostic to what is calling it. Maybe CheckForUpdates:YES/NO?

Please also make sure doxygen stays in sync with the new parameters.

Comment (phunkyfish) [reply xbmc/addons/AddonInstaller.h:59]: Or even `AllowCheckForUpdates::YES/NO`.

**Comment by glennguy** [comment]
Works well here. Even with the changes there still seems to be a content check after migration has finished (scheduled update) so no loss in functionality.

File: xbmc/addons/AddonInstaller.h (hunk 1 above)
Comment (howie-f) [reply xbmc/addons/AddonInstaller.h]: ok, let's use `AllowCheckForUpdates`, also removed the default argument and doxy updated

**Comment by howie-f** [comment]
oh, great. thanks for testing @glennguy

File: xbmc/addons/AddonInstaller.h (hunk 1 above)
Comment (phunkyfish) [reply xbmc/addons/AddonInstaller.h]: I think you have this inverted @howie-f. You need to check the `YES`/`NO`'s

File: xbmc/addons/AddonInstaller.cpp [hunk 2]
```diff
@@ -678,9 +683,26 @@ bool CAddonInstallJob::DoWork()
...
+        CLog::Log(LOGDEBUG, "ADDONS: repository [{}] updated. now checking for content updates.",
+                  m_addon->ID());
+        CServiceBroker::GetRepositoryUpdater().CheckForUpdates(
+            std::static_pointer_cast<CRepository>(m_addon), false);
+      }
+    }
+    else
+    {
+      CLog::Log(LOGDEBUG,
+                "ADDONS: skipping CheckForUpdates() on [{}] due to add-on migration in progress",
```
Comment (phunkyfish) [inline xbmc/addons/AddonInstaller.cpp:703]: Log statement should be changed. It's not necessarily the migration that is the reason

File: xbmc/addons/AddonInstaller.cpp [hunk 3]
```diff
@@ -678,9 +683,26 @@ bool CAddonInstallJob::DoWork()
...
   {
     origin = m_addon->ID(); // use own id as origin if repository
-    if (m_isUpdate)
-      CServiceBroker::GetRepositoryUpdater().CheckForUpdates(
-          std::static_pointer_cast<CRepository>(m_addon), false);
+
+    // if a repository is updated during the add-on migration process, we need to skip
+    // calling CheckForUpdates() on the repo to prevent deadlock issues during migration
+
+    if (m_allowCheckForUpdates == AllowCheckForUpdates::NO)
```
Comment (phunkyfish) [inline xbmc/addons/AddonInstaller.cpp:690]: Should this not be `YES`?

File: xbmc/addons/AddonManager.cpp [hunk 4]
```diff
@@ -458,7 +458,7 @@ std::vector<AddonInfoPtr> CAddonMgr::MigrateAddons()
   CLog::Log(LOGINFO, "ADDON: waiting for add-ons to update...");
   VECADDONS updates;
   GetAddonUpdateCandidates(updates);
-  InstallAddonUpdates(updates, true);
+  InstallAddonUpdates(updates, true, AllowCheckForUpdates::YES);
```
Comment (phunkyfish) [inline xbmc/addons/AddonManager.cpp:461]: `::NO`

File: xbmc/addons/AddonManager.cpp [hunk 5]
```diff
@@ -497,7 +497,7 @@ void CAddonMgr::CheckAndInstallAddonUpdates(bool wait) const
   std::lock_guard<std::mutex> lock(m_installAddonsMutex);
   VECADDONS updates;
   GetAddonUpdateCandidates(updates);
-  InstallAddonUpdates(updates, wait);
+  InstallAddonUpdates(updates, wait, AllowCheckForUpdates::NO);
```
Comment (phunkyfish) [inline xbmc/addons/AddonManager.cpp:500]: `::YES`

**Review by phunkyfish — CHANGES_REQUESTED** [review]
I think the logic was inverted when moving from `MigrationJob` to `AllowCheckForUpdates`.

File: xbmc/addons/AddonManager.cpp (hunk 5 above)
Comment (howie-f) [reply xbmc/addons/AddonManager.cpp:500]: sure... those `sed` changes.....

**Review by phunkyfish — APPROVED** [review]
Nice
