### PR TITLE
[edl] Allow EDL files on private subnets for network shares rather than the one the Kodi host in on

### LINKED ISSUE #23651: EDL ignored for different subnet/lan
### Describe the bug
Here is a clear and concise description of what the problem is:

The EditDecisionList (edl) support seems to be restricted to the current subnet, regardless where the actual media is coming from.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Support edl files where subtitle files are supported or media is playable.

## Actual Behavior

edl files are only loaded if in the same subnet/lan as the interface reports

## Possible Fix

Same permissions as subtitles or allow in all private ip ranges?

The current check for the LAN seems to be done here:
https://github.com/xbmc/xbmc/blob/f5ab9fd5d2d6d3589470208a774bbfa757a63ee9/xbmc/cores/VideoPlayer/Edl.cpp#L55

### To Reproduce

1. Add new network source (smb or nfs) on the same subnet eg.: 192.168.1.1
2. Play video with edl file. 
3. edl markers are correctly used
4. Add new network source (smb or nfs) on a different subnet eg.: 192.168.2.1
5. Play video with edl file
6. edl markers are missing

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/exunezexaj.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20.2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
This seems like a low-hanging fruit and the request actually makes sense (since I also have a specific subnet for my lan share). Currently Kodi only processes the EDL files if the share is on the same subnet as the Kodi host. However you can simply have multiple routers in your network and the actual share can be behind one of those routers without implicitly meaning it's accessible via the internet. So we can simply consider the check as long as the share is within a private network range.

## Motivation and context
Closes https://github.com/xbmc/xbmc/issues/23651 

## How has this been tested?
On linux with mplayer edl

## What is the effect on users?
EDL should now be taken into account if the media is being played from a share belonging to a private network range

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

File: xbmc/utils/URIUtils.h [hunk 1]
```diff
@@ -146,7 +146,7 @@ class URIUtils
   static bool IsMusicDb(const std::string& strFile);
   static bool IsNfs(const std::string& strFile);
   static bool IsOnDVD(const std::string& strFile);
-  static bool IsOnLAN(const std::string& strFile);
+  static bool IsOnLAN(const std::string& strFile, bool offLineCheck = false);
```
Comment (ksooo) [inline xbmc/utils/URIUtils.h:149]: I would suggest to not introduce new bool (default) param here, but a param of type of a new enum class `OfflineCheck`. Makes calling code much more readable, without having to look up the method declaration telling me what that `true`actually means.

Comment (enen92) [reply xbmc/utils/URIUtils.h]: Yeah that's a good idea. Done in the last revision.
The diff is a bit bigger but it's well split by commits

**Review by ksooo — APPROVED** [review]
Nice.
