### PR TITLE
[Android] Change to MediaCodecList.getCodecInfos()

### LINKED ISSUE #20639: Black screen with video playback by using inputstream.adaptive with LineageOS (Kodi 19.3)
### Describe the bug
Here is a clear and concise description of what the problem is:

I'am using Kodi 19.3 (Matrix) with LineageOS running on Raspberry Pi 400 with Android 11.0.0 (API level 30). When I Start using Addons the widevine encryption the Inputstream Adaptive only plays the sound but no picture. 

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Addons which use widevine also output a picture in addition to the sound

## Actual Behavior

When I Start using Addons the widevine encryption the Inputstream Adaptive on Kodi 19.3 with LineageOS only plays the sound but no picture.

## Possible Fix

A possible theory of the cause is that getCodecCount not work anymore, because has been deprecated on API 21.

### To Reproduce

1. Start Kodi-Addon (DAZN, Tvnow, ...) for encrypted videos via inputstream adaptive plugin
2. Start playing stream

### Debuglog

The debuglog can be found here:
[kodi_debug.log](https://github.com/xbmc/xbmc/files/7660686/kodi_debug.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

unavailable

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

after log line:
CDVDVideoCodecAndroidMediaCodec::Open: Secure decoder requested: false (stream flags: 0)
is missing the codec testing, in your case should appears like:
CDVDVideoCodecAndroidMediaCodec::Open Testing codec: OMX.google.h264.decoder
and then fails with:
CDVDVideoCodecAndroidMediaCodec:: Failed to create Android MediaCodec

According to [CastagnaIT](https://github.com/CastagnaIT) feedback, this is where the problem lies in the code:(https://github.com/xbmc/xbmc/blob/master/xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp#L664-L750)

For further information also looking at (https://github.com/xbmc/inputstream.adaptive/issues/771#issue-961565492)

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LineageOS 18.1 based on Android for Raspberry Pi 400
 - Kodi version: 19.3 (Matrix)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.

Greetings Weri

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
MediaCodecList object uses two static methods to get available codecs, these two methods are deprecated in API level 21.

I propose to use the non-static ```getCodecInfos()``` method instead, it returns a list of MediaCodecInfo objects.

The constructor has a parameter with two possible values:

* ```ALL_CODECS```: Enumerate all codecs, even ones that are not suitable for regular (buffer-to-buffer) decoding or encoding, such as secure codecs (.secure).

* ```REGULAR_CODECS```: Enumerate only codecs that are suitable for regular (buffer-to-buffer) decoding or encoding. These are the same codecs that are returned by the deprecated methods.

This PR depends on (xbmc/libandroidjni#34).

## How has this been tested?
Runtime tested on AFTV (Android TV 9)

## Types of change
- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/platform/android/media/decoderfilter/MediaCodecDecoderFilterManager.cpp [hunk 1]
```diff
@@ -39,10 +39,11 @@ CMediaCodecDecoderFilterManager::CMediaCodecDecoderFilterManager()
     NULL
   };
 
-  int num_codecs = CJNIMediaCodecList::getCodecCount();
-  for (int i = 0; i < num_codecs; i++)
+  std::vector<CJNIMediaCodecInfo> codecInfos =
+      CJNIMediaCodecList(CJNIMediaCodecList::REGULAR_CODECS).getCodecInfos();
+
+  for (auto codec_info : codecInfos)
```
Comment (CastagnaIT) [inline xbmc/platform/android/media/decoderfilter/MediaCodecDecoderFilterManager.cpp:45]: if it is not an iterator, please specify the type instead use `auto`
and probably worth not making copies of each object so add `&`

File: xbmc/windowing/android/AndroidUtils.cpp [hunk 2]
```diff
@@ -429,10 +429,11 @@ CHDRCapabilities CAndroidUtils::GetDisplayHDRCapabilities()
 
 bool CAndroidUtils::SupportsMediaCodecMimeType(const std::string& mimeType)
 {
-  int num_codecs = CJNIMediaCodecList::getCodecCount();
-  for (int i = 0; i < num_codecs; i++)
+  std::vector<CJNIMediaCodecInfo> codecInfos =
+      CJNIMediaCodecList(CJNIMediaCodecList::REGULAR_CODECS).getCodecInfos();
+
+  for (auto codec_info : codecInfos)
```
Comment (CastagnaIT) [inline xbmc/windowing/android/AndroidUtils.cpp:435]: same as before

File: xbmc/platform/android/media/decoderfilter/MediaCodecDecoderFilterManager.cpp (hunk 1 above)
Comment (CastagnaIT) [reply xbmc/platform/android/media/decoderfilter/MediaCodecDecoderFilterManager.cpp:45]: and all others

**Comment by CastagnaIT** [comment]
are you able to attach a test build arm64?

**Comment by joseluismarti** [comment]
Two versions to test based on the constructor's parameters:
[kodiapp-arm64-v8a-PR21421_ALL_CODECS.apk](https://drive.google.com/file/d/1i364u6GTERvKkNfImy9fX8ZiF9wmHHBS/view?usp=sharing)
[kodiapp-arm64-v8a-PR21421_REGULAR_CODECS.apk](https://drive.google.com/file/d/1s_x3DCD0KqHGQlHIR4zQ8r3tzFG75fe1/view?usp=sharing)

**Comment by howie-f** [comment]
jenkins build this please

**Comment by CastagnaIT** [comment]
tested on my phone regular version works as before on android 8
more interesting would be a test on Android >= 11

**Comment by fuzzard** [comment]
I can test on android 12, whats the test cases you need looked at? hit me up on slack @CastagnaIT

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp [hunk 3]
```diff
@@ -367,7 +367,7 @@ std::atomic<bool> CDVDVideoCodecAndroidMediaCodec::m_InstanceGuard(false);
 
 bool CDVDVideoCodecAndroidMediaCodec::Open(CDVDStreamInfo &hints, CDVDCodecOptions &options)
 {
-  int num_codecs;
+  std::vector<CJNIMediaCodecInfo> codecInfos;
```
Comment (ksooo) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:370]: This is C++. Please declare and init the variable, where it first is needed.

File: xbmc/platform/android/media/decoderfilter/MediaCodecDecoderFilterManager.cpp [hunk 4]
```diff
@@ -39,10 +39,11 @@ CMediaCodecDecoderFilterManager::CMediaCodecDecoderFilterManager()
     NULL
   };
 
-  int num_codecs = CJNIMediaCodecList::getCodecCount();
-  for (int i = 0; i < num_codecs; i++)
+  std::vector<CJNIMediaCodecInfo> codecInfos =
```
Comment (ksooo) [inline xbmc/platform/android/media/decoderfilter/MediaCodecDecoderFilterManager.cpp:42]: `const std::vector<...`

File: xbmc/windowing/android/AndroidUtils.cpp [hunk 5]
```diff
@@ -429,10 +429,11 @@ CHDRCapabilities CAndroidUtils::GetDisplayHDRCapabilities()
 
 bool CAndroidUtils::SupportsMediaCodecMimeType(const std::string& mimeType)
 {
-  int num_codecs = CJNIMediaCodecList::getCodecCount();
-  for (int i = 0; i < num_codecs; i++)
+  std::vector<CJNIMediaCodecInfo> codecInfos =
```
Comment (ksooo) [inline xbmc/windowing/android/AndroidUtils.cpp:432]: `const std::vector<...`

File: xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.cpp [hunk 6]
```diff
@@ -200,12 +200,12 @@ bool CDVDAudioCodecAndroidMediaCodec::Open(CDVDStreamInfo &hints, CDVDCodecOptio
   {
     //StereoDownmixAllowed is true if the user has selected 2.0 Audio channels in settings
     bool stereoDownmixAllowed = CServiceBroker::GetActiveAE()->HasStereoAudioChannelCount();
-    int num_codecs = CJNIMediaCodecList::getCodecCount();
+    std::vector<CJNIMediaCodecInfo> codecInfos =
```
[the remark this answers is not in the document]
Comment (howie-f) [reply xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.cpp:203]: should at least be `const std::vector<...` but i'd go further and split it like this
```cpp
  CJNIMediaCodecList regularCodecList(CJNIMediaCodecList::REGULAR_CODECS);
  const std::vector<CJNIMediaCodecInfo> codecInfos = regularCodecList.getCodecInfos();
```
but this is up to you to decide

[the remark this answers is not in the document]
Comment (ksooo) [reply xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.cpp:203]: As `regularCodecList` is not directly needed, the temporary here imo is fine. But cannot harm to separate, yes. Up to you, @joseluismarti

[the remark this answers is not in the document]
Comment (joseluismarti) [reply xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.cpp:203]: I always forget the const :)

As we don't need the List later, I think it's fine to leave as is

File: xbmc/platform/android/media/decoderfilter/MediaCodecDecoderFilterManager.cpp (hunk 4 above)
Comment (joseluismarti) [reply xbmc/platform/android/media/decoderfilter/MediaCodecDecoderFilterManager.cpp:42]: Right

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp (hunk 3 above)
Comment (joseluismarti) [reply xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:370]: The rest of the variable declarations I've added are where they are initialised and make sense.

This case is special because the code has several ```GOTO statements```. If the definition is where it should be, the error "jump bypasses variable initialization" is generated.

For the moment and to make the minimum changes, I decided to declare the variable where one of the variables it replaces was already defined, although I didn't like it either.

Comment (howie-f) [reply xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:370]: ugh, `goto FAIL;` ?!?
can we (maybe in a follow up) define a new private member `bool DoCleanupAndFail() {...}` and just call `return DoCleanupAndFail();` instead?

Comment (joseluismarti) [reply xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp:370]: Better to manage it in a separate PR, do not mix these two issues.

**Comment by joseluismarti** [comment]
Fixes #20639

**Review by CastagnaIT — APPROVED** [review]

**Comment by howie-f** [comment]
well then let‘s go. thanks again @joseluismarti
