### PR TITLE
 Tone mapping: Extend default video settings to store tone map method

### LINKED ISSUE #16257: Tone mapping parameter reset to default setting after Kodi restart
### Describe the bug
Here is a clear and concise description of what the problem is:

Tone mapping parameter always reset to default "1.00" after Kodi is restarted.

### To Reproduce

Set it to anything other than 1.00, click "Set default for all media" and restart Kodi.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/tusaxibehu.kodi

### Your Environment
Used Operating system:

 - [x] Linux

 - Operating system version/name: LibreELEC
 - Kodi version: current master

### PR DESCRIPTION
**Pull request by thexai**
## Description
- Extend default video settings to store tone map method & param (user preference for all videos).
- Clean up of `CVideoSettings` class: move all initialization values to constructor, ~~delete unused element `m_SubtitleCached`~~
- ~~Round tone map param to 2 decimal places to avoid store inexact values e.g. 0.9988346789~~  (*)
- Fixes https://github.com/xbmc/xbmc/issues/16257

(*) Removed code that fix this because Team not wants merge (someone will doing it better).

## Motivation and Context
Users may want change default tone map method and use always one of the new methods (ACES or Hable). Without this PR the only way is enter on OSD video settings for every new video is playing. Setting is stored but only for current video.

"Set as default for all media" does not work. This PR fix this.

This change does not affect users that has video library items with custom tonemap settings. Only affects to new video library items added or items without tonemap settings.

## How Has This Been Tested?
Check that on userdata folder **guisettings.xml** stores user preference for `defaultvideosettings`

New `<tonemapmethod>1</tonemapmethod>`  and `<tonemapparam>1.000000</tonemapparam>` entry is created.

```
    <defaultvideosettings>
        <interlacemethod>1</interlacemethod>
        <scalingmethod>1</scalingmethod>
        <noisereduction>0.000000</noisereduction>
        <postprocess>true</postprocess>
        <sharpness>0.000000</sharpness>
        <viewmode>6</viewmode>
        <zoomamount>1.000000</zoomamount>
        <pixelratio>1.000000</pixelratio>
        <verticalshift>0.000000</verticalshift>
        <volumeamplification>0.000000</volumeamplification>
        <showsubtitles>true</showsubtitles>
        <brightness>50.000000</brightness>
        <contrast>50.000000</contrast>
        <gamma>20.000000</gamma>
        <audiodelay>0.000000</audiodelay>
        <subtitledelay>0.000000</subtitledelay>
        <nonlinstretch>false</nonlinstretch>
        <stereomode>0</stereomode>
        <centermixlevel>0</centermixlevel>
        <tonemapmethod>1</tonemapmethod>
        <tonemapparam>1.000000</tonemapparam>
    </defaultvideosettings>
```
And all videos on database that not has its own tonemap setting is using the default video settings.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [X] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Isn't this why we have the "Set as default for all media" option in the video OSD?

video-osd-set-as-default

**Comment by thexai** [comment]
> Isn't this why we have the "Set as default for all media" option in the video OSD?

Seems that this option is broken or not does what uses expect.
e.g. https://forum.kodi.tv/showthread.php?tid=358128&pid=2986915#pid2986915

I have looked at what the code does and it seems that it deletes all the settings saved in the database (for each item in the video library).

But then the "default settings" are still used, that is, a place is still needed where the user can choose which is the default setting to use in all the videos. Now these "defaults" seems are hard-codded.

**Comment by jjd-uk** [comment]
Sounds like something has become broken the purpose of  "Set as default for all media"  was to apply the OSD settings as the default settings to all video items. If it's now acting as reset all video items to default then someone has done a change and not understood it's purpose, or just missed this use case.

**Comment by lrusak** [comment]
could also be related to this https://github.com/xbmc/xbmc/issues/16257

**Comment by thexai** [comment]
`Isn't this why we have the "Set as default for all media" option in the video OSD?`

You are right. Now is fixed and can be used this setting as it should.

**Comment by thexai** [comment]
jenkins build this please

**Comment by fuzzard** [comment]
You seem to be changing defaults to a tonemap implementation that isnt on every platform. Intentional?

File: xbmc/video/VideoDatabase.cpp [hunk 1]
```diff
@@ -4470,10 +4470,10 @@ bool CVideoDatabase::GetVideoSettings(int idFile, CVideoSettings &settings)
       settings.m_CenterMixLevel = m_pDS->fv("CenterMixLevel").get_asInt();
       m_pDS->close();
 
-      if (settings.m_ToneMapParam == 0.0)
+      if (settings.m_ToneMapParam < 0.1f || settings.m_ToneMapParam > 5.0f)
       {
-        settings.m_ToneMapMethod = VS_TONEMAPMETHOD_REINHARD;
-        settings.m_ToneMapParam = 1.0;
+        settings.m_ToneMapMethod = VS_TONEMAPMETHOD_HABLE;
```
Comment (fuzzard) [inline xbmc/video/VideoDatabase.cpp:4475]: can you implicitly include cores/VideoSettings.h as a header please. theres a forward declaration in the header, but there should be an implicit inclusion in the implementation file.

File: xbmc/settings/MediaSettings.cpp [hunk 2]
```diff
@@ -220,6 +221,7 @@ bool CMediaSettings::Save(TiXmlNode *settings) const
   XMLUtils::SetBoolean(pNode, "nonlinstretch", m_defaultVideoSettings.m_CustomNonLinStretch);
   XMLUtils::SetInt(pNode, "stereomode", m_defaultVideoSettings.m_StereoMode);
   XMLUtils::SetInt(pNode, "centermixlevel", m_defaultVideoSettings.m_CenterMixLevel);
+  XMLUtils::SetInt(pNode, "tonemapmethod", m_defaultVideoSettings.m_ToneMapMethod);
```
Comment (lrusak) [inline xbmc/settings/MediaSettings.cpp:224]: what about saving the tonemap param as well?

File: xbmc/cores/VideoPlayer/VideoRenderers/VideoShaders/WinVideoFilter.h [hunk 3]
```diff
@@ -96,7 +96,7 @@ class COutputShader : public CWinShader
   unsigned m_sourceHeight = 0;
   int m_lutSize = 0;
   int m_ditherDepth = 0;
-  int m_toneMappingMethod = VS_TONEMAPMETHOD_REINHARD;
+  int m_toneMappingMethod = VS_TONEMAPMETHOD_HABLE;
```
Comment (fuzzard) [inline xbmc/cores/VideoPlayer/VideoRenderers/VideoShaders/WinVideoFilter.h:99]: Implicit inclusion of cores/VideoSettings.h again

**Comment by thexai** [comment]
> You seem to be changing defaults to a tonemap implementation that isnt on every platform. Intentional?

Due to the way it is codded, any value of tone map `method != VS_TONEMAPMETHOD_OFF` will make the tonemap activate even though the platform only supports Reinhard. Anyway, it is already being implemented on more platforms.

File: xbmc/settings/MediaSettings.cpp (hunk 2 above)
Comment (thexai) [reply xbmc/settings/MediaSettings.cpp:224]: It can be done but I don't think it's convenient. Normally only is need to ajust tonemap param for a specific video. While the tonemap method can be a personal preference for all media library items.

File: xbmc/cores/VideoPlayer/VideoRenderers/VideoShaders/WinVideoFilter.h (hunk 3 above)
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/VideoShaders/WinVideoFilter.h]: Replaced with:

`int m_toneMappingMethod = 0;`

Here is not need define default value because always tonemap is activated is passed current method and param.

`COutputShader::SetToneMapParam(int method, float param);`

File: xbmc/video/VideoDatabase.cpp (hunk 1 above)
Comment (thexai) [reply xbmc/video/VideoDatabase.cpp]: I'm not sure what this code is needed for. I think it can be removed.

In the tests that I have done adding and removing media library items it has never entered to this block.

It seems that it was a stopgap measure to migrate old database or initialize wrong values. Now if no saved data in DB, the default values from `m_defaultVideoSettings` are used.

**Comment by thexai** [comment]
jenkins build this please

**Comment by jjd-uk** [comment]
Have labelled this for v19 if anyone disagrees then feel free to remove label & milestone.

**Comment by jjd-uk** [comment]
> > You seem to be changing defaults to a tonemap implementation that isnt on every platform. Intentional?
> 
> Due to the way it is codded, any value of tone map `method != VS_TONEMAPMETHOD_OFF` will make the tonemap activate even though the platform only supports Reinhard. Anyway, it is already being implemented on more platforms #18751

A note to point out the other PR only adds implementations for GL on Linux, GLES is still missing although @sarbes is looking into GLES I think. So even after that I think Reinhard will still be only option for Android, RPi, iOS, & tvOS and possible OSX???

**Comment by thexai** [comment]
I have made several changes:

I have thought better of it and at the moment do not change to Hable by default (there will be time later :D )
Tonemap param is saved to guisettings.xml too
Clean up of `CVideoSettings` class and delete unused code
Round tonemap param to 2 decimal places

**Comment by thexai** [comment]
jenkins build this please

File: xbmc/cores/VideoSettings.h [hunk 4]
```diff
@@ -101,7 +101,6 @@ class CVideoSettings
   int m_SubtitleStream;
   float m_SubtitleDelay;
   bool m_SubtitleOn;
-  bool m_SubtitleCached; // not used -> remove from DB
```
Comment (lrusak) [inline xbmc/cores/VideoSettings.h:104]: This line doesn't seem relevant to this PR/commit. Can you move it to a new commit?

File: xbmc/settings/MediaSettings.cpp [hunk 5]
```diff
@@ -114,10 +114,10 @@ bool CMediaSettings::Load(const TiXmlNode *settings)
       m_defaultVideoSettings.m_StereoMode = 0;
     if (!XMLUtils::GetInt(pElement, "centermixlevel", m_defaultVideoSettings.m_CenterMixLevel))
       m_defaultVideoSettings.m_CenterMixLevel = 0;
-
-    m_defaultVideoSettings.m_ToneMapMethod = 1;
-    m_defaultVideoSettings.m_ToneMapParam = 1.0f;
-    m_defaultVideoSettings.m_SubtitleCached = false;
```
Comment (lrusak) [inline xbmc/settings/MediaSettings.cpp:120]: same with this line

File: xbmc/video/VideoDatabase.cpp [hunk 6]
```diff
@@ -4462,19 +4462,12 @@ bool CVideoDatabase::GetVideoSettings(int idFile, CVideoSettings &settings)
       settings.m_ScalingMethod = (ESCALINGMETHOD)m_pDS->fv("ScalingMethod").get_asInt();
       settings.m_StereoMode = m_pDS->fv("StereoMode").get_asInt();
       settings.m_StereoInvert = m_pDS->fv("StereoInvert").get_asBool();
-      settings.m_SubtitleCached = false;
```
Comment (lrusak) [inline xbmc/video/VideoDatabase.cpp:4465]: same with this line

File: xbmc/video/dialogs/GUIDialogVideoSettings.cpp [hunk 7]
```diff
@@ -178,7 +178,8 @@ void CGUIDialogVideoSettings::OnSettingChanged(const std::shared_ptr<const CSett
   else if (settingId == SETTING_VIDEO_TONEMAP_PARAM)
   {
     CVideoSettings vs = g_application.GetAppPlayer().GetVideoSettings();
-    vs.m_ToneMapParam = static_cast<float>(std::static_pointer_cast<const CSettingNumber>(setting)->GetValue());
+    float val = static_cast<float>(std::static_pointer_cast<const CSettingNumber>(setting)->GetValue());
+    vs.m_ToneMapParam = std::roundf(val * 100) / 100; // round to 2 decimal places
```
Comment (lrusak) [inline xbmc/video/dialogs/GUIDialogVideoSettings.cpp:182]: What's the reason for this? The slider should only allow 0.1 increments as defined here: https://github.com/xbmc/xbmc/blob/b5871f5c48df16f862930773bddbd36dc2e13dc5/xbmc/video/dialogs/GUIDialogVideoSettings.cpp#L420-L422

min = 0.1
step = 0.1
max = 5.0

**Review by lrusak — CHANGES_REQUESTED** [review]
Looks good! Much cleaner than the original PR! Just some small comments to address then should be good to go.

File: xbmc/video/dialogs/GUIDialogVideoSettings.cpp (hunk 7 above)
Comment (thexai) [reply xbmc/video/dialogs/GUIDialogVideoSettings.cpp:182]: Without this inexacte values like 0.9988346789 are stored on xml. 

In fact, it is no longer possible to save the default value of 1.00000 anymore when slider has moved.

`<tonemapparam>1.000000</tonemapparam>`

Comment (thexai) [reply xbmc/video/dialogs/GUIDialogVideoSettings.cpp:182]: Also on screen step is not 0.1 but 0.01

Captura de pantalla 2020-11-11 103424

File: xbmc/cores/VideoSettings.h (hunk 4 above)
Comment (thexai) [reply xbmc/cores/VideoSettings.h:104]: Moved to separate commit: https://github.com/xbmc/xbmc/pull/18749/commits/ed0f2aa83a3e6967630b5ea996b2c48a010856d2

**Comment by jjd-uk** [comment]
jenkins build this please

**Comment by jjd-uk** [comment]
I can confirm this now Fixes #16257 on Windows, the reported problem was first reproduced with todays Nightly (KodiSetup-20201110-b5871f5c-master-x64.exe) before testing a build with the contents of this PR. However original report was for LibreELEC however it appears the changes here should to agnostic to the OS.

File: xbmc/video/dialogs/GUIDialogVideoSettings.cpp (hunk 7 above)
Comment (jjd-uk) [reply xbmc/video/dialogs/GUIDialogVideoSettings.cpp:182]: Don't know how you managed that as it's 0.10 steps here https://youtu.be/s_1Mbeg836o

Comment (lrusak) [reply xbmc/video/dialogs/GUIDialogVideoSettings.cpp:182]: maybe you need to reset your settings?

File: xbmc/cores/VideoSettings.h (hunk 4 above)
Comment (lrusak) [reply xbmc/cores/VideoSettings.h:104]: Thanks!

**Comment by jjd-uk** [comment]
By the way just an observation, I assume the Tone Map settings will only ever apply to BT.2020 HDR video? as the settings seem to be always available even when playing SDR video. Would probably make sense to grey them out for SDR video if at all possible, but that can be done in a future PR if anyone has the inclination to look at it.

File: xbmc/video/dialogs/GUIDialogVideoSettings.cpp (hunk 7 above)
Comment (thexai) [reply xbmc/video/dialogs/GUIDialogVideoSettings.cpp:182]: Video is moving slider with keyboard... try with mouse... 
Anyway the problem is not number in screen (only 2 decimals is shown) the problem is internal value that is e.g. 1.002356456867  On guisettings.xml is stored with more decimals and you can see the problem. Also on BD or debugging the code.

Comment (thexai) [reply xbmc/video/dialogs/GUIDialogVideoSettings.cpp:182]: With round code the same number shown on screen is stored on xml.  

With NO round code the number saved on xml is not the same as shown on screen.

**Comment by lrusak** [comment]
> By the way just an observation, I assume the Tone Map settings will only ever apply to BT.2020 HDR video? as the settings seem to be always available even when playing SDR video. Would probably make sense to grey them out for SDR video if at all possible, but that can be done in a future PR if anyone has the inclination to look at it.

Yea best to do it in a future PR

**Comment by lrusak** [comment]
jenkins build this please

File: xbmc/video/dialogs/GUIDialogVideoSettings.cpp (hunk 7 above)
Comment (lrusak) [reply xbmc/video/dialogs/GUIDialogVideoSettings.cpp:182]: That may be a larger issue we need to solve then, but I don't want to hold this PR up anymore. I'd rather remove the rounding code and we can look at it later.

Comment (thexai) [reply xbmc/video/dialogs/GUIDialogVideoSettings.cpp]: Done

**Comment by thexai** [comment]
Jenkins build this

**Comment by thexai** [comment]
jenkins build this please

**Review by fuzzard — APPROVED** [review]

**Comment by jjd-uk** [comment]
@lrusak Please confirm whether this is now ok for you.

As it's now fixing broken behavior I assume we don't need @DaveTBlake ok for this one.

**Review by lrusak — APPROVED** [review]

**Comment by lrusak** [comment]
LGTM
