### PR TITLE
[PVR] Guide window: Fix timer icon issues. Fixes #16621

### LINKED ISSUE #16621: [REQUEST] play m3u8 content with "EXT-X-MEDIA-SEQUENCE"
### Describe the bug
Here is a clear and concise description of what the problem is:

The content m3u8 with these headers not play in Kodi 18.4
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-TARGETDURATION:10
#EXT-X-MEDIA-SEQUENCE:268998

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

To be able to play these type of contents
VLC can play this content

## Actual Behavior

Not playable

### To Reproduce

1. Use this file M3u file : [1501.zip](https://github.com/xbmc/xbmc/files/3612599/1501.zip)
2. Play in Kodi

### Debuglog

The debuglog can be found here:
Log : https://pastebin.com/0aLjaTs9
Full Log: [kodi.log](https://github.com/xbmc/xbmc/files/3612613/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

No screenshot to provide

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

No more context

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.4

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes issues with not appearing/disappearing timer state icons in PVR Guide window, like discussed here: https://github.com/xbmc/xbmc/pull/10024#issuecomment-228530671 ff. 

Fixes http://trac.kodi.tv/ticket/16621

Code changes are strait forward.

Reported to actually fix the problems by @bas-t and @seo

### CODE REVIEW

**Comment by ksooo** [comment]
jenkins build this please

**Comment by ksooo** [comment]
@MilhouseVH ping

**Comment by bas-t** [comment]
@ksooo thanks for your effort, this works like a charm for me.

Is marking the trac ticket as fixed (referencing this PR)  and closing it an automated process? It's not done yet and I don't know how to do it.

**Comment by ksooo** [comment]
> Is marking the trac ticket as fixed (referencing this PR) and closing it an automated process?

@bas-t  no, no automated process, but cannot login to trac currently. no idea what's broken. if trac is working again i will close the ticket.

**Comment by BigNoid** [comment]
If you add ```Fixes #1662``` to the PR title it should automatically close the ticket when merged.

**Comment by ksooo** [comment]
@BigNoid does this work for trac tickets? I thought this is only for github issues, no?

**Comment by BigNoid** [comment]
There's some trac integration afaik. Github Janitor will close the ticket.
See #4115 and http://trac.kodi.tv/ticket/14885 for an example.

**Comment by ksooo** [comment]
Cool. Thanks. Will change PR title, then.

**Comment by ksooo** [comment]
Will changing the PR title do the trick or do I have to change one if the commit messages?

**Comment by BigNoid** [comment]
I am not sure tbh. Let's see what happens :) 
We can always close it manually.

**Comment by ksooo** [comment]
@BigNoid changing PR title seems not to be enough. Ticket got not closed automatically on merge. One needs to put 'fixes #xxxxx' into one of the involved commit messages.

File: xbmc/pvr/windows/GUIWindowPVRGuide.cpp [hunk 1]
```diff
@@ -97,11 +97,19 @@ void CGUIWindowPVRGuide::StopRefreshTimelineItemsThread()
...
+  if (g_PVRTimers)
+    g_PVRTimers->RegisterObserver(this);
+  CGUIWindowPVRBase::RegisterObservers();
 }
 
 void CGUIWindowPVRGuide::UnregisterObservers(void)
 {
+  CSingleLock lock(m_critSection);
+  CGUIWindowPVRBase::UnregisterObservers();
+  if (g_PVRTimers)
```
Comment (FernetMenta) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: this will cause the system crash when PVRManager is restarted because i.e. another clients gets connects. There is no guarantee the the lifetime of Timers is longer than that of this window.

Comment (FernetMenta) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: IMO the entire observes should go away from GUIWindows. This pattern is not suited for this purpose. Why don't you use window messages?

Comment (ksooo) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: Just to confirm that we are on the same page: problem here is that g_PVRTimers (which is a CPVRTimers *) can get invalid between call to <code>if (g_PVR_Timers)</code> and <code>g_VRTimers->...</code>, right? OMG, we have this pattern all over the place...

> Why don't you use window messages?

 I'm not the original author of this code, but valid point.

 Would it be okay to use window messages inside the PVR core classes, like CPVRTimers? I think so.

Comment (FernetMenta) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: Your first statement is correct. If it does not access an invalid pointer, it may unregister at a different instance which is not correct either. I don't think we should switch to shared pointers as a solution, the problem is the observer pattern that is an anti pattern here.
I would use window messages, and maybe route them through a proxy object.

**Comment by ksooo** [comment]
ok. what would be the purpose of the proxy object?

File: xbmc/pvr/windows/GUIWindowPVRGuide.cpp (hunk 1 above)
Comment (ksooo) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: ok. what would be the purpose of the proxy object?

Comment (FernetMenta) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: Not having a dependency from every pvr child component to windowmanager. maybe pvrmanager can act as the proxy but not sure if this makes sense without looking into the details.
which is quite hard atm because Telekom killed my internet connection :(

**Comment by ksooo** [comment]
> Not having a dependency from every pvr child component to windowmanager

 Absolutely. That was also my take on you suggestion.

> pvrmanager can act as the proxy

 I thought about this too, but wasn't pvrmanager getting restarted part of the original story? Does 'restarted' mean a new pvrmanager instance gets created, then?

File: xbmc/pvr/windows/GUIWindowPVRGuide.cpp (hunk 1 above)
Comment (ksooo) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: > Not having a dependency from every pvr child component to windowmanager

 Absolutely. That was also my take on your suggestion.

> pvrmanager can act as the proxy

 I thought about this too, but wasn't pvrmanager getting restarted part of the original story? Does 'restarted' mean a new pvrmanager instance gets created, then?

Comment (FernetMenta) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: PVRManager instance is owned by ServiceManager which is owned by CApplication. A restart of PVRManager won't create a new instance.

Comment (ksooo) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: > PVRManager instance is owned by ServiceManager which is owned by CApplication. A restart of PVRManager won't create a new instance.

 yeah. looked this up myself meanwhile. good that you confirm. so, no lifecycle issues when using g_PVRManager as proxy for messaging.

using window messages as replacement for current observer approach relies on the fact that there can only be max one active window at a time, right? messaging is 1:1, observer is 1:n communication, right? So, what if currently there are non-window observers (have not checked this yet) the messaging approach wont work, no.

Comment (FernetMenta) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: > using window messages as replacement for current observer approach relies on the fact that there can only be max one active window at a time, right?

not correct. 

regarding non-window observers, I think we should treat this as a separate topic.

Comment (ksooo) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: never dealt with kodi window messaging before. How does broasdcasting messages work?

> regarding non-window observers, I think we should treat this as a separate topic.
 
ok

Comment (ksooo) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: what do you think about this approach, which does not need window messages:

pvr components will be no longer Observables, instead of calling NotifyObservers() directly like they do now, they will call g_PVRManager.NotifyObservers(), passing the same observable message like they do today. the pvr windows no longer observe different pvr components, but the pvr manager. problem solved.

Comment (FernetMenta) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: sounds reasonable :)

**Comment by ksooo** [comment]
Okay, I will see what I can make out of this.

File: xbmc/pvr/windows/GUIWindowPVRGuide.cpp (hunk 1 above)
Comment (ksooo) [inline xbmc/pvr/windows/GUIWindowPVRGuide.cpp]: Okay, I will see what I can make out of this.
