### PR TITLE
[Android] Avoid failure when getInterfaceName() method returns null

### LINKED ISSUE #25815: Kodi crashes on GoogleTV when the Tailscale is running
## Bug report
### Describe the bug

Kodi crashes when the Xiaomi 4K TvStick gen2 is connected to Tailscale network.
When disconnected and Kodi is force shutted down then I run Kodi and starts normally.
I see the exception in the log, clearly that's some edge case.


## Expected Behavior
Kodi should turn on instead crash



## Actual Behavior
Kodi crashes



## Possible Fix
Workaround : stop using Tailscale



### To Reproduce
<!--- Provide a link to a live example, or an unambiguous set of steps to -->
<!--- reproduce this bug. Include code to reproduce, if relevant -->
<!--- Put your text below this line -->
1.  Connect the Tailscale network
2. Start Kodi



### Debuglog
Attached full log started from clicking the Kodi icon (adb logcal) 
excerpt:
```
10-10 11:50:11.489  6183  6233 I TetheringManager: registerTetheringEventCallback:org.xbmc.kodi                                                                                                                                               
10-10 11:50:11.495  6183  6233 E Kodi    : 2024-10-10 11:50:11.495 T:6233    error <general>: CNetworkAndroid::RetrieveInterfaces Cannot get interface by name: wlan0                                                                         
10-10 11:50:11.500  6183  6233 E Kodi    : 2024-10-10 11:50:11.500 T:6233    error <general>: CNetworkAndroid::RetrieveInterfaces Cannot get interface by name: tun0                                                                          
10-10 11:50:11.502   556  1857 D ConnectivityService: requestNetwork for uid/pid:10076/6183 NetworkRequest [ TRACK_DEFAULT id=64, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10076 AdministratorUids: [] RequestorUid: 10076 Request
orPackageName: org.xbmc.kodi] ]                                                                                                                                                                                                               
10-10 11:50:11.503   556   634 D ConnectivityService: NetReassign [64 : null → 101]                                                                                                                                                           
10-10 11:50:11.503   556   663 I chatty  : uid=1000(system) EthernetService expire 1 line                                                                                                                                                     
10-10 11:50:11.505  6183  6240 D Kodi    : 2024-10-10 11:50:11.505 T:6240    debug <general>: CNetworkAndroid::onAvailable The default network is now: 101                                                                                    
10-10 11:50:11.507  6183  6233 E Kodi    : 2024-10-10 11:50:11.507 T:6233    error <general>: Rename - Error renaming file /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/temp/kodi.log                                           
10-10 11:50:11.509  6183  6233 I Kodi    : 2024-10-10 11:50:11.509 T:6233     info <general>: -----------------------------------------------------------------------                                                                         
10-10 11:50:11.509  6183  6233 I Kodi    : 2024-10-10 11:50:11.509 T:6233     info <general>: Starting Kodi (21.1 (21.1.0) Git:20240817-d00181569e). Platform: Android ARM 32-bit                                                             
10-10 11:50:11.509  6183  6233 I Kodi    : 2024-10-10 11:50:11.509 T:6233     info <general>: Using Release Kodi x32                                                                                                                          
10-10 11:50:11.509  6183  6233 I Kodi    : 2024-10-10 11:50:11.509 T:6233     info <general>: Kodi compiled 2024-08-17 by Clang 9.0.9 (https://android.googlesource.com/toolchain/llvm-project a2a1e703c0edb03ba29944e529ccbf457742737b) for A
ndroid ARM 32-bit API level 21 (API level 21)                                                                                                                                                                                                 
10-10 11:50:11.509  6183  6233 I Kodi    : 2024-10-10 11:50:11.509 T:6233     info <general>: Running on Xiaomi MiTV-AYFR0 with Android TV 11.0.0 API level 30, kernel: Linux ARM 32-bit version 5.4.233-android12-9-g399b53624b72-ab1469     
10-10 11:50:11.509  6183  6233 I Kodi    : 2024-10-10 11:50:11.509 T:6233     info <general>: FFmpeg version/source: 6.0.1-Kodi                                                                                                               
10-10 11:50:11.509  6183  6233 I Kodi    : 2024-10-10 11:50:11.509 T:6233     info <general>: Host CPU: ARMv8 Processor rev 0 (v8l), 4 cores available                                                                                        
10-10 11:50:11.509  6183  6233 I Kodi    : 2024-10-10 11:50:11.509 T:6233     info <general>: Product: soul, Device: soul, Board: soul - Manufacturer: Xiaomi, Brand: Xiaomi, Model: MiTV-AYFR0, Hardware: amlogic                            
10-10 11:50:11.510  6183  6240 E AndroidRuntime: FATAL EXCEPTION: ConnectivityThread                                                                                                                                                          
10-10 11:50:11.510  6183  6240 E AndroidRuntime: Process: org.xbmc.kodi, PID: 6183                                                                                                                                                            
10-10 11:50:11.510  6183  6240 E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.util.List java.net.NetworkInterface.childs' on a null object reference                                                      
10-10 11:50:11.510  6183  6240 E AndroidRuntime:        at java.net.NetworkInterface.getAll(NetworkInterface.java:498)                                                                                                                        
10-10 11:50:11.510  6183  6240 E AndroidRuntime:        at java.net.NetworkInterface.getByName(NetworkInterface.java:298)
10-10 11:50:11.510  6183  6240 E AndroidRuntime:        at org.xbmc.kodi.interfaces.XBMCConnectivityManagerNetworkCallback._onAvailable(Native Method)
10-10 11:50:11.510  6183  6240 E AndroidRuntime:        at org.xbmc.kodi.interfaces.XBMCConnectivityManagerNetworkCallback.onAvailable(XBMCConnectivityManagerNetworkCallback.java:13)
10-10 11:50:11.510  6183  6240 E AndroidRuntime:        at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3322)
10-10 11:50:11.510  6183  6240 E AndroidRuntime:        at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3607)
10-10 11:50:11.510  6183  6240 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-10 11:50:11.510  6183  6240 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
10-10 11:50:11.510  6183  6240 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
10-10 11:50:11.515   556  1166 W ActivityTaskManager:   Force finishing activity org.xbmc.kodi/.Main
```

[kodi-crash.log](https://github.com/user-attachments/files/17326272/kodi-crash.log)


### Screenshots 
Here are some links or screenshots to help explain the problem:
<!--- Put your text below this line -->



## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Xiaomi 4K Tv Stick gen2



### Your Environment
Used Operating system:
 - [X] Android


 - Operating system version/name:
 - Kodi version: 21.1

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
Check that the [getInterfaceName()](https://developer.android.com/reference/android/net/LinkProperties#getInterfaceName()) method may return `null` causing the app to crash.

Try to fix the issue https://github.com/xbmc/xbmc/issues/25815 when the interface name for the link is not set.

Log:
```
D Kodi    : debug <general>: CNetworkAndroid::onAvailable The default network is now: 101
...
E AndroidRuntime: FATAL EXCEPTION: ConnectivityThread
E AndroidRuntime: Process: org.xbmc.kodi, PID: 6716
E AndroidRuntime: java.lang.NullPointerException: Attempt to read from field 'java.util.List java.net.NetworkInterface.childs' on a null object reference
E AndroidRuntime:        at java.net.NetworkInterface.getAll(NetworkInterface.java:498)
E AndroidRuntime:        at java.net.NetworkInterface.getByName(NetworkInterface.java:298)
E AndroidRuntime:        at org.xbmc.kodi.interfaces.XBMCConnectivityManagerNetworkCallback._onAvailable(Native Method)
E AndroidRuntime:        at org.xbmc.kodi.interfaces.XBMCConnectivityManagerNetworkCallback.onAvailable(XBMCConnectivityManagerNetworkCallback.java:13)
E AndroidRuntime:        at android.net.ConnectivityManager$NetworkCallback.onAvailable(ConnectivityManager.java:3322)
E AndroidRuntime:        at android.net.ConnectivityManager$CallbackHandler.handleMessage(ConnectivityManager.java:3607)
E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
E AndroidRuntime:        at android.os.Looper.loop(Looper.java:223)
E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)
``` 

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by joseluismarti** [comment]
jenkins build this please

File: xbmc/platform/android/network/NetworkAndroid.cpp [hunk 1]
```diff
@@ -360,14 +360,21 @@ void CNetworkAndroid::RetrieveInterfaces()
...
   CJNILinkProperties lp = connman.getLinkProperties(n);
 
   if (lp)
   {
     CJNINetworkInterface intf = CJNINetworkInterface::getByName(lp.getInterfaceName());
+    if (xbmc_jnienv()->ExceptionCheck())
+    {
+      xbmc_jnienv()->ExceptionClear();
+      CLog::Log(LOGERROR, "CNetworkAndroid::onAvailable: Cannot get interface by name: {}",
+                lp.getInterfaceName());
```
Comment (fuzzard) [inline xbmc/platform/android/network/NetworkAndroid.cpp:375]: wont lp.getInterfaceName always be null in this situation? what value does logging it give?

Comment (joseluismarti) [reply xbmc/platform/android/network/NetworkAndroid.cpp:375]: This code captures the exceptions that can be thrown when invoking the `getByName()` method, one can be `NullPointerException` when receiving a parameter that is `null`, but they can be others such as `SocketException` and in this case it would have value.

**Comment by neo1973** [comment]
Probably worth to backport?

**Comment by joseluismarti** [comment]
Yes I backport it
