### PR TITLE
changed: Refactor & improve logging for FileCache

### LINKED ISSUE #19785: Lagging and keep buffering when play dolby vision with matrix on Shield TV Pro.
### Describe the bug
Here is a clear and concise description of what the problem is:

Lagging and keep buffering when play dolby vision with matrix on Shield TV Pro. And it will just happen on some files, not all Dolby Vision file.
It can play normal for the beginning, the color and audio are all right. But about 1 or 2 minutes later, the playback will be paused and the buffer loading circle keeps showing for a long time, maybe it can continue to play about 5 seconds more, but it will just keep loading more time after that.
And the network is not the cause of the issue, the box and Nas is connected with LAN, and I tried to play other remux files right after the issue is happening, 80gb HDR remux can be played without any issue.

I tried with Emby Server and direct FTP file, same issue there.

First time it happens when playing WandaVision S01E01&S01E02, but everything normal when playing S01E03 ~ S01E09. I changed the source file to another team's work, I can finally play.
And this time, it happens with Hamiton, the former HDR version plays perfectly, but the DV vision shows the buffer issue. I tried with my phone (galaxy note 10+) this time, Kodi 19 connect with Emby by WIFI, the file can play smoothly without the buffer issue, but the Dolby vision color is not right, shows green.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Play those Dolby Vision file without the buffer issue, if the network is all right.

## Actual Behavior

Play those Dolby Vision file with lagging and buffer issue, though the network is capable to play big HDR remux file.
And the log seems that it Kodi tried to cache the video and resume the video, but a seek position behavior by itself will just reset the cache completely. And the situation keeps coming over and over again, cache -> seek -> reset.
And the situation is can be seen if you are watching the progress bar, you can see the cached time will disappear suddenly, then come back, then disappear again, then come back. 

## Possible Fix

Seems like an issue when playback some specific dolby vision file, the file won't be cached right.

### To Reproduce

1. The files:
Hamilton.2020.2160p.WEB-DL.DDP5.1.DoVi.HEVC-LEWIS.mp4
WandaVision.S01E01.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.x265-MZABI
WandaVision.S01E02.2160p.DSNP.WEB-DL.DDP5.1.Atmos.DV.x265-MZABI

### Debuglog

The debuglog can be found here:
[kodi-issues.log](https://github.com/xbmc/xbmc/files/6529515/kodi-issues.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

A video to show the cache's disappearance in the progress bar, it happens at 14, 18, 22, 24, 26, 30, 33 and more seconds. 
https://user-images.githubusercontent.com/66369455/119293053-3cff4780-bc84-11eb-9ac9-33171e4a205d.mp4

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Open debug log mode, and open ffmpeg detail log at the same time would strangely fix the problem. The cached time will keep in the progress bar. 

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 9 / Shield 8.2.2
 - Kodi version: 19.0/19.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by arnova**
This PR refactors/cleans up some of the FileCache-related code. It furthermore improves logging.

### CODE REVIEW

File: xbmc/filesystem/FileCache.cpp [hunk 1]
```diff
@@ -268,23 +272,31 @@ void CFileCache::Process()
...
-          m_bFilling = true;
-          m_bLowSpeedDetected = false;
-        }
+      }
+
+      m_writePos = m_pCache->CachedDataEndPos();
+      assert(m_writePos == cacheMaxPos);
+      average.Reset(
+          m_writePos,
+          bCompleteReset); // Can only recalculate new average from scratch after a full reset (empty cache)
```
Comment (wsnipex) [inline xbmc/filesystem/FileCache.cpp:292]: the formatting would probably look better if you move the comment to it's own line

**Review by wsnipex — APPROVED** [review]

File: xbmc/filesystem/FileCache.cpp (hunk 1 above)
Comment (arnova) [reply xbmc/filesystem/FileCache.cpp]: Done

File: xbmc/filesystem/CacheStrategy.cpp [hunk 2]
```diff
@@ -327,32 +327,32 @@ int64_t CDoubleCache::Seek(int64_t iFilePosition)
...
-          || m_pCache->CachedDataEndPos() >= m_pCacheOld->CachedDataEndPos()))
+  if (clearAnyway || !m_pCache->IsCachedPosition(iSourcePosition))
   {
-    return m_pCache->Reset(iSourcePosition, clearAnyway);
-  }
-  if (!m_pCacheOld)
-  {
-    CCacheStrategy *pCacheNew = m_pCache->CreateNew();
-    if (pCacheNew->Open() != CACHE_RC_OK)
+    // Position not in active cache: swap caches
```
Comment (wsnipex) [inline xbmc/filesystem/CacheStrategy.cpp:334]: maybe add a log debug here?

File: xbmc/filesystem/CacheStrategy.cpp [hunk 3]
```diff
@@ -327,32 +327,32 @@ int64_t CDoubleCache::Seek(int64_t iFilePosition)
...
+    CCacheStrategy* pCacheTmp;
+    if (!m_pCacheOld)
+    {
+      pCacheTmp = m_pCache->CreateNew();
+      if (pCacheTmp->Open() != CACHE_RC_OK)
+      {
```
Comment (wsnipex) [inline xbmc/filesystem/CacheStrategy.cpp:340]: and here

File: xbmc/filesystem/CacheStrategy.cpp (hunk 2 above)
Comment (arnova) [reply xbmc/filesystem/CacheStrategy.cpp:334]: Yes, I was thinking about this as well. It would be especially helpful if the current begin/end positions of both caches are logged, agreed?

File: xbmc/filesystem/CacheStrategy.cpp (hunk 3 above)
Comment (arnova) [reply xbmc/filesystem/CacheStrategy.cpp:340]: Yes, I had the exact same idea until I checked the Open() implementations: It's already being done there.

File: xbmc/filesystem/CacheStrategy.cpp (hunk 2 above)
Comment (wsnipex) [reply xbmc/filesystem/CacheStrategy.cpp:334]: yes, sounds good

File: xbmc/filesystem/CacheStrategy.cpp [hunk 4]
```diff
@@ -329,31 +329,28 @@ int64_t CDoubleCache::Seek(int64_t iFilePosition)
 
 bool CDoubleCache::Reset(int64_t iSourcePosition, bool clearAnyway /* = false */)
 {
-  if (!clearAnyway && m_pCache->IsCachedPosition(iSourcePosition)
-      && (!m_pCacheOld || !m_pCacheOld->IsCachedPosition(iSourcePosition)
-          || m_pCache->CachedDataEndPos() >= m_pCacheOld->CachedDataEndPos()))
+  if (clearAnyway || !m_pCache->IsCachedPosition(iSourcePosition))
```
Comment (arnova) [inline xbmc/filesystem/CacheStrategy.cpp:345]: @wsnipex: What's your idea about the (old) logic here? It used to consider which cache had the "highest" end position but I think that logic is wrong/flawed but I also have doubts that just swapping in case of a seek may not be the best solution for all possible scenarios.

**Comment by arnova** [comment]
jenkins build this please

**Comment by fritsch** [comment]
Maybe, when looking at the history of the cache files in question, I see many, many, small commits, titles as workarounds, but it seems the logic is still flawed and each change for good breaks something else.

How about using the chance to drop one of the caches and just use the player and its cache for all playback related stuff?

**Comment by arnova** [comment]
> Maybe, when looking at the history of the cache files in question, I see many, many, small commits, titles as workarounds, but it seems the logic is still flawed and each change for good breaks something else.
> 
> How about using the chance to drop one of the caches and just use the player and its cache for all playback related stuff?

The problem is that some files/streams simply don't work without double caching: the seeks that some of them "trigger" are simply not fast enough on streamed filesystems (http etc.) for playback to work properly. That's why this was implemented in the first place.

Also note that the ticket in question probably concerns an issue with ffmpeg, and not with filecache at all but I just want to make sure filecache is NOT the problem.

**Comment by fritsch** [comment]
Is there an easy option to entirely disable the non-player cache? And let that other user test this?

**Comment by arnova** [comment]
> Is there an easy option to entirely disable the non-player cache? And let that other user test this?

yes, set as.xml/cache/buffermode to 3. I already asked him, but he didn't report back if he tried it (will ask again).

**Comment by arnova** [comment]
> Is there an easy option to entirely disable the non-player cache? And let that other user test this?

Well as it turns out (and expected): that didn't fix the issue. So the final conclusion is: the problem is in his files and/or our ffmpeg version. The only strange thing is: he says the problem is gone when he enables ffmpeg component logging.

**Comment by arnova** [comment]
@wsnipex : Updated it. Please note that the actual "bug-fix" was removed and all that remains is cleanup/refactoring/logging. Since the old logic turned out to work as intended, only lacked proper comment/explanation.

File: xbmc/filesystem/CacheStrategy.cpp [hunk 5]
```diff
@@ -198,21 +203,31 @@ int64_t CSimpleFileCache::Seek(int64_t iFilePosition)
...
-  if (nDiff > 500000 || (nDiff > 0 && WaitForData((unsigned int)(iTarget - m_nReadPosition), 5000) == CACHE_RC_TIMEOUT))
+  if (nDiff > 500000)
   {
-    CLog::Log(LOGDEBUG,"CSimpleFileCache::Seek - Attempt to seek past read data");
+    CLog::Log(LOGDEBUG, "CSimpleFileCache::{} - <{}> Requested position {} is beyond cached data ({})", __FUNCTION__,
+              m_filename, iFilePosition, m_nWritePosition);
+    return CACHE_RC_ERROR;
+  }
+
+  if (nDiff > 0 && WaitForData((unsigned int)(iTarget - m_nReadPosition), 5000) == CACHE_RC_TIMEOUT)
```
Comment (lrusak) [inline xbmc/filesystem/CacheStrategy.cpp:219]:
```suggestion
  if (nDiff > 0 && WaitForData(static_cast<unsigned int>(iTarget - m_nReadPosition), 5000) == CACHE_RC_TIMEOUT)
```

**Review by wsnipex — APPROVED** [review]
