### PR TITLE
Fix aborts with -D_GLIBCXX_ASSERTIONS -D_GLIBCXX_DEBUG

### LINKED ISSUE #15101: Kodi 18 RC2 Fedora 29 x64 SIGABRTs at random, can be repeated with on screen notifications
### Describe the bug
Here is a clear and concise description of what the problem is:

Kodi SIGABRTs at random but can be 'forced' to crash by sending on screen notifications (I have a mythtv backend)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Doesn't SIGABRT

## Actual Behavior

SIGABRTs at random, but can almost always be forced to crash by sending on screen notifications.

## Possible Fix

The last half dozen posts in this thread may point to a fix.

https://forum.kodi.tv/showthread.php?tid=331155

### To Reproduce

1. Start Kodi
2. Send on screen notifications
3. Watch Kodi crash

### Debuglog

The debuglog can be found here:

I will attach 6 crashlogs from two different machines to show it's not a single machine issue.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ X ] Linux
 - [ ] OSX
 - [ ] Raspberri-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Fedora 29 x64
 - Kodi version: 18 RC 2 from RPMFUSION repos

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by yol**
Fedora now seems to build with `-D_GLIBCXX_ASSERTIONS` on by default, leading to a (justified) abort when calling `DrawText` with an empty text value.

Another unrelated Wayland problem found with `-D_GLIBCXX_DEBUG` is also fixed here.

Should fix #15101

### CODE REVIEW

**Comment by pkerling** [comment]
Reference: https://retrace.fedoraproject.org/faf/reports/2402433/

**Comment by pkerling** [comment]
Reference to #15101 removed from commit message as it seems to be a different issue.

**Comment by pkerling** [comment]
@fritsch Would appreciate a quick look at this, should be a no-brainer essentially

**Comment by fritsch** [comment]
All fine. Let's spot what we overlooked after merging.

**Comment by pkerling** [comment]
Thanks! :-)

**Comment by pkerling** [comment]
jenkins build and merge

File: xbmc/guilib/GUIFontTTFGL.cpp [hunk 1]
```diff
@@ -280,6 +282,9 @@ void CGUIFontTTFGL::LastEnd()
 
 CVertexBuffer CGUIFontTTFGL::CreateVertexBuffer(const std::vector<SVertex> &vertices) const
 {
+  assert(!vertices.empty());
```
Comment (FernetMenta) [inline xbmc/guilib/GUIFontTTFGL.cpp]: kodi-x11: /home/xbmc/progs/src/kodi/xbmc/guilib/GUIFontTTFGL.cpp:285: virtual CVertexBuffer CGUIFontTTFGL::CreateVertexBuffer(const std::vector<SVertex>&) const: Assertion `!vertices.empty()' failed.
Aborted (core dumped)

reproducible here by changing a timer on the backend during tv playback

Comment (pkerling) [reply xbmc/guilib/GUIFontTTFGL.cpp]: @FernetMenta Thanks, I'll have a look. Now I'm glad I added the assert even though I thought everything should be fine...
