### PR TITLE
[VideoPlayer][FFmpegDemux] Don't add image attachments as video streams.

### LINKED ISSUE #26984: Image attachments from .mkv and .mp4 videos are shown as video streams in the Stream selection / Video streams OSD menu
### Describe the bug

.mkv and .mp4 that have attached images like this cover:

Image

show it as a video stream in the OSD:

Image

## Expected Behavior
Since it can't be played nor displayed, the image shouldn't appear in the OSD and much less in the video stream section.

## Actual Behavior

The image is showed in the OSD.

### To Reproduce

[Here](https://drive.google.com/file/d/1cV2URnhUExAYcW5AKkFcd9JAhiFSRTmN/view?usp=drive_link) is a small .mkv with an image attached.

Start the video, go to the Stream selection / Video streams OSD menu and confirm that the png is shown as a video stream.

### Debuglog

[kodi.log](https://github.com/user-attachments/files/21300315/kodi.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 22H2, kernel: Windows NT x86 64-bit version 10.0.19045.6093
 - Kodi version: 22.0-ALPHA1 (21.90.700) Git:20250716-7d349752a3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by Uukrull**
## Description

As discussed [here](https://github.com/xbmc/xbmc/issues/26984), FFmpeg adds image attachments as video streams so they should be discarded.

## Motivation and context

Fixes https://github.com/xbmc/xbmc/issues/26984

## How has this been tested?

With this [mkv](https://drive.google.com/file/d/1cV2URnhUExAYcW5AKkFcd9JAhiFSRTmN/view?usp=drive_link) that has a png attached.

## What is the effect on users?

Image attachments aren't shown as video streams in the OSD.

## Screenshots (if appropriate):
Before:
Image

After:
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp [hunk 1]
```diff
@@ -1545,6 +1545,14 @@ CDemuxStream* CDVDDemuxFFmpeg::AddStream(int streamIdx)
       return nullptr;
     }
 
+    // FFmpeg adds the image attachments as video streams
+    if ((pStream->disposition & AV_DISPOSITION_ATTACHED_PIC) != 0)
+    {
+      CLog::LogF(LOGDEBUG, "CDVDDemuxFFmpeg::AddStream - discarding image attachment");
```
Comment (sundermann) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp]:
```suggestion
      CLog::LogF(LOGDEBUG, "Discarding image attachment");
```
LogF already adds class and function name

**Review by sundermann — APPROVED** [review]
Just a minor thing. Else this should be the correct place to put this check. Tested on a local file and it does work.

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp (hunk 1 above)
Comment (Uukrull) [reply xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp]: Done.

**Review by neo1973 — APPROVED** [review]
Thanks :slightly_smiling_face:
