### PR TITLE
[VideoDatabase] Do not overwrite Set Overview if no field in NFO

### LINKED ISSUE #24481: Videodb   Old style movie nfo with <set>name</set> deletes set overview
### Describe the bug
Here is a clear and concise description of what the problem is:

When movies have a local movie.nfo file, an existing set overview in the video library is deleted when a movie.nfo file is parsed that contains the pre-Jarvis element
`<set>name</set>`
or Jarvis and follow without "overview" child element 
`<set>
<name>name<name>
</set>`

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Existing overview is retained unless `<overview></overview>` element is included

## Actual Behavior

The set overview is deleted from the videodb  sets table.

## Possible Fix

Modify VideoInfoTag ParseNative and SetSetOverview to provide a bool to provide a case where "overview" element is not present, instead of setting to null string.  Or provide a bool for VideoDatabase AddSet so the SQL does not update the overview in this case
`"UPDATE sets SET strOverview = '%s' WHERE idSet = %i", strOverview.c_str(), id`

### To Reproduce

1. Scan movies into database containing a full set description via movie nfo or scraper.  Verify existence of set and overview via the video info dialog for the set in the UI
2. Provide a movie nfo file for a movie with `<set>set name</set>` where set name matchs the existing set name in the appropriate source folder
3.  Refresh the movie (if existing) or scan the movie (if new)

### Debuglog

The debuglog can be found here:

https://paste.kodi.tv/qadumavawa.kodi

Note: in this log existing movie "Back to the Future" / set name "Back to the Future Collection" was refreshed with nfo file
https://paste.kodi.tv/uqinomujac

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Some 3rd party tools create nfo files using the `<set></set>` element.  When new movies from the set are scanned, the nfo files remove existing overview.  My workaround is to export the contents of the sets table (SELECT * FROM sets) and edit nfo files to add the name and overview using data from the export.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Win 10 x64 22H2
 - Kodi version:  Kodi (21.0-BETA2 (20.90.821) Git:20240107-a5019a8d40

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Fix #24481.

## Motivation and context

If a move with an NFO is added to an existing set, the set overview is overwritten irrespective of whether there is an <overview> field in the NFO (ie. if no field it's blanked).

## How has this been tested?

Locally

## What is the effect on users?

Prevent overview being overwritten.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by KarellenX** [comment]
How does this work?

Are the set tags read for the first creation of the set, then ignored for all other movies added to the set, or is it that if the overview tag is missing then the overview in the DB is left alone, but the set name tag is still overwritten and future movies added will still always overwrite the existing data in the DB?

File: xbmc/video/VideoDatabase.h [hunk 1]
```diff
@@ -1000,7 +1000,9 @@ class CVideoDatabase : public CDatabase
   \return The dbId of the season.
   */
   int AddSeason(int showID, int season, const std::string& name = "");
-  int AddSet(const std::string& strSet, const std::string& strOverview = "");
+  int AddSet(const std::string& strSet,
+             const std::string& strOverview = "",
+             const bool& updateOverview = true);
```
Comment (ksooo) [inline xbmc/video/VideoDatabase.h:1005]: It does not make much sense to pass simple data types by reference. Please change the type to a simple `bool`, passed by value.

**Comment by 78andyp** [comment]
> How does this work?
> 
> Are the set tags read for the first creation of the set, then ignored for all other movies added to the set, or is it that if the overview tag is missing then the overview in the DB is left alone, but the set name tag is still overwritten and future movies added will still always overwrite the existing data in the DB?

If a movie is added and there is no NFO - the set details will be updated from the scraper, including the overview
If a movie is added and there is an NFO but it contains no <overview> - the set overview is left alone
If a movie is added and there is an NFO with <overview> (even if it is blank) - the NFO overrides

File: xbmc/video/VideoDatabase.h (hunk 1 above)
Comment (78andyp) [reply xbmc/video/VideoDatabase.h]: Done

**Comment by KarellenX** [comment]
Thanks @78andyp 

I'll update the wiki when I have a moment.

**Comment by 78andyp** [comment]
> Thanks @78andyp
> 
> I'll update the wiki when I have a moment.

Thanks. I'm going to add a refresh button to the set information dialog as well (as suggested by @CrystalP in #24131) - then this PR, #24131 and the refresh button PR will complement each other nicely.

**Comment by scott967** [comment]
Thanks for taking this on.  Didn't review closely, but seems to achieve what I thought necessary.

Use case is many videos that do not scrape, so require full nfo files.  Files have locally defined sets (name, art, and overview).  Problem is adding new files to library that are part of existing set; since overview is custom (user created) existing overview must be retrieved and added to nfo along with set name when generating nfo.

**Comment by KarellenX** [comment]
>Thanks. I'm going to add a refresh button to the set information dialog as well (as suggested by @CrystalP in https://github.com/xbmc/xbmc/pull/24131) - then this PR, https://github.com/xbmc/xbmc/pull/24131 and the refresh button PR will complement each other nicely.

Yep, I've been watching that one also.

Once they are merged and closer to final release for v21, I'll start with the wiki updates.

If any of the logic changes, please make note in the thread, so I don't add the wrong info to the wiki. Thanks :)

File: xbmc/video/VideoInfoTag.h [hunk 2]
```diff
@@ -330,6 +330,13 @@ class CVideoInfoTag : public IArchivable, public ISerializable, public ISortable
    */
   void SetIsDefaultVideoVersion(bool isDefaultVideoVersion);
 
+  /*!
+  * @brief Get whether the Set Overview should be updated. If an NFO contains a <name> but no <overview> then
+  * this allows the current Ovewview to be kept. Otherwise it is overwritten. Default is true - so if updated
```
Comment (fuzzard) [inline xbmc/video/VideoInfoTag.h:335]: Typo in Ovewview

**Comment by fuzzard** [comment]
Thanks for the contribution @78andyp
