### PR TITLE
[guilib] Fix Font style bits were not being applied in SetStyledText

### LINKED ISSUE #17977: Long text in input dialog does not scroll correctly
### Describe the bug
Here is a clear and concise description of what the problem is:

If an input dialog is opened (e.g. using `xbmcgui.Dialog().input()`) and the text is too long (either from the default value or from what the user enters), and the cursor is moved to the far right, it is not visible anymore.

The text does scroll, but not enough.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The text should have scrolled far enough to see the cursor.

## Actual Behavior

The text does scroll, but not far enough.

## Possible Fix

I think the problem has something to do with how the needed width for the text is calculated. This is done through `CGUILabel::CalcTextWidth()` method. Here is how I came to this conclusion:

I added some logging code to `CGUIEditControl::RecalcLabelPosition()`. Then I inserted some long text, scrolled all the way to the left and then moved the cursor to the right edge. This showed me that the width reported from `CGUILabel::GetMaxWidth()` did not quite match the text width reported from `CGUILabel::CalcTextWidth()` for the part of the text up to the cursor.

My first thought was that the width reported from `CGUILabel::GetMaxWidth()` was wrong (some padding issue or the like). What made me change my mind was a weird behaviour when scrolling to the far right, then left again. The cursor is not on the far left of the text box as soon as it starts scrolling: There is a certain distance between the left edge and the cursor. This distance slowly gets smaller if I continue scrolling left, until it finally hits the edge when arriving at the beginning of the text.

However, the code of `CGUIEditControl::RecalcLabelPosition` does not even use the reported max width from `CGUILabel::GetMaxWidth()`. Also, the gradual movement to the left indicates that the error is proportional to the width of the text, which is perfectly explained by a wrong font size or similar issues.

### To Reproduce

1. Open an input dialog, for example from the library via the context menu -> Manage ... -> Change name
2. Enter a very long text, so it exceeds the available width
3. The cursor is not visible; it has moved out to the right.

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/4707741/kodi.2.log)

It was created including my additional logging code. I edited xbmc/guilib/GUIEditControl.cpp as seen [here](https://github.com/w4kodi/xbmc/commit/cf77095673eb4a99194bf5196e2c03c3a70b9388#diff-f49f0f1b67f54dd376c4f89392c64c1d). The last time this logging code is executed (line 2522 in the log file) the cursor was already invisible, so afterCursorWidth should be greater than maxTextWidth. The opposite is true.

### Screenshots 
Here are some links or screenshots to help explain the problem:

Screenshot 1: Cursor is visible, at the right edge

Now, I move the cursor one to the right:

Screenshot 2: Cursor is no longer visible

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [X] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:

       $ uname -srvmpio
       Linux 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

 - Kodi version: Leia 18.6, Matrix (master: 139b2af53d1856cb62c8207d66202a3d436b5b2b)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by amacchietto**
## Description
Fix for #17977 'Long text in input dialog does not scroll correctly'
Font style bits were not being applied in SetStyledText
leading to incorrect width being returned by CGUITextLayout::GetTextWidth(const std::wstring&).

Description of problem described here: https://github.com/xbmc/xbmc/issues/17977

## Motivation and context
Fixes a usability issue with entering long text into a dialog box.

## How has this been tested?
Locally tested on Matrix and Master branch. Confirmed the issue is resolved with no side effects.

## What is the effect on users?
Will allow users to see all end of their text in the dialog box regardless of selected font.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/guilib/GUIEditControl.cpp [hunk 1]
```diff
@@ -553,9 +553,16 @@ bool CGUIEditControl::SetStyledText(const std::wstring &text)
   unsigned int startSelection = m_cursorPos + m_editOffset;
   unsigned int endSelection   = m_cursorPos + m_editOffset + m_editLength;
 
+  unsigned int style = 0;
+  CGUIFont* font = m_label2.GetLabelInfo().font;
+  if (font)
+  {
+    style = font->GetStyle() << 24;
```
Comment (CastagnaIT) [inline xbmc/guilib/GUIEditControl.cpp:560]: can you explain me what means the shift to 24?

Comment (amacchietto) [reply xbmc/guilib/GUIEditControl.cpp:560]: The font style bits are stored in the upper byte in vecText. 

```
float CGUITextLayout::GetTextWidth(const std::wstring &text) const
{
  // NOTE: Assumes a single line of text
  if (!m_font) return 0;
  vecText utf32;
  AppendToUTF32(text, (m_font->GetStyle() & FONT_STYLE_MASK) << 24, utf32);
  return m_font->GetTextWidth(utf32);
}
```

Another side effect of this change is that the text entered into the edit box should now match the font style of the theme (which I believe was the original intent).

**Comment by lrusak** [comment]
jenkins build this please

**Review by CastagnaIT — COMMENTED** [review]
I tried to make my own review although i am not so expert in the GUI section,
following the logic seems correct and in my test it works,

IMO i think it is appropriate also inlcude in this PR the fix for GUILabelControl, that have the same bug on similar code (used for highlighted text range such as NumericPad input)
Code here: https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUILabelControl.cpp#L85-L96
This last one can be easly tested by open "IP Address" button on virtual keyboard
immagine
and look the difference in numbers text style that should appears slightly different
immagine

Last thing, the commits need to be squashed all in one, the description of the commit must have the prefix [guilib] with a short description of the fix without add the ID of the issue

**Review by CastagnaIT — APPROVED** [review]
for me its ok already tested
if @lrusak would like to have a second look before the merge

**Comment by CastagnaIT** [comment]
@amacchietto since this fix has a low impact i think you can create a PR to backport it to matrix (will be released shortly new release)

**Review by enen92 — APPROVED** [review]

**Comment by amacchietto** [comment]
> [CastagnaIT](/CastagnaIT)

[Created PR to backport to Matrix](https://github.com/xbmc/xbmc/pull/20995)
