### PR TITLE
[contextmenus] Add missing context menu items from properties/plugins

### LINKED ISSUE #21843: ListItem.addContextMenuItems() not added on plugin:// widgets
### Describe the bug
Here is a clear and concise description of what the problem is:

Context menu items added to listitems using the addContextMenuItems() method only display in the media windows. These context menu items are not added when the plugin is used as widget in a `<content>plugin://path</content>` container.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The context menu items should be added when used as a widget just as in the media windows.

## Actual Behavior

Context menu items are not added.

### To Reproduce

1. Install any plugin that uses addContextMenuItems()
2. Add it to the home screen in a dynamic content container
3. Context menu does not work

I've created a simple test case plugin here to reduce possibility of other issues
https://github.com/jurialmunkey/plugin.video.testlang

Add this to Estuary Home.xml by editing one of the widgets and reloading the skin 
(I've changed in-progress TV widget to point to this plugin)

```xml
<include content="WidgetListPoster" condition="True">
	<param name="content_path" value="plugin://plugin.video.testlang/"/>
	<param name="widget_header" value="Testing"/>
	<param name="widget_target" value="videos"/>
	<param name="list_id" value="6100"/>
</include>
```

### Debuglog

The debuglog can be found here:
[kodi.log](https://github.com/xbmc/xbmc/files/9539427/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

First screenshot shows contextmenu items correctly displayed in IsMedia window. Second screenshot shows contextmenu not working correctly on Home.xml

Context added in IsMedia windows (working as expected)

Honeyview_screenshot00168

Context not added on Home.xml (not working)

Honeyview_screenshot00167

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: Nexus Alpha 2

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
## Description
Context menu items might be set on fileItem properties (the case of plugins). This is done with property pairs `contextmenulabel` and `contextmenuaction`. However these menu items are only parsed on media windows - where the contextmenu dialog is invoked with a vector of items for displaying. The generic implementation in the contextmenu manager (when showing context menu items for a given fileitem) does not include them. For this reason, on content widgets, plugin listitem's context menus are not being shown.

## Motivation and context
Fix https://github.com/xbmc/xbmc/issues/21843

## How has this been tested?
With the procedure outlined on the bug report, in linux.

## What is the effect on users?
Plugin context menu items are now displayed in content widgets with plugin:// paths. Other cases might be fixed as well.

## Screenshots (if appropriate):
**Before:**
image

**Now:**
image

Just a note this doesn't affect the context menu items on plugin browsing:
image

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

### CODE REVIEW

**Comment by matthuisman** [comment]
Nice 👍

File: xbmc/ContextMenuManager.cpp [hunk 1]
```diff
@@ -230,21 +231,43 @@ bool CONTEXTMENU::ShowFor(const CFileItemPtr& fileItem, const CContextMenuItem&
...
+  {
+    int i = 0;
+    while (fileItem->HasProperty(StringUtils::Format("contextmenulabel({})", i)))
+    {
+      buttons.emplace_back(
+          ~buttons.size(),
+          fileItem->GetProperty(StringUtils::Format("contextmenulabel({})", i)).asString());
+      ++i;
+    }
+  }
```
Comment (howie-f) [inline xbmc/ContextMenuManager.cpp:245]: maybe this can be a private helper `CContextButtons GetPropertyMenuButtons(const CFileItem& item) const` or something.

**Review by howie-f — APPROVED** [review]
looks good

File: xbmc/ContextMenuManager.cpp (hunk 1 above)
Comment (enen92) [reply xbmc/ContextMenuManager.cpp:245]: It's not easy because the context action is not part of the button, they're rather a simple label. As a result this is hard to encapsulate as later on you'll have to use the index to send the built-in message. I think it's better to try to reuse this method in media windows instead of duplicating the logic there
