### PR TITLE
[Video] Fix for #25097 and requested updates from #24720

### LINKED ISSUE #25097: Starting file playback with keyboard Enter button is broken in master
### Describe the bug
Here is a clear and concise description of what the problem is:

Starting playback in file mode with Enter button seems broken.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Keyboard Enter button should start the playback of any video file in the folder.

### To Reproduce

1.  Go to a folder with multiple video files
2.  Select any file and press Enter
3.  Playback would start but **it would start from the first file in the folder, regardless of which file is actually selected.**

### Debuglog

The debuglog can be found here:
[debug log](https://gist.githubusercontent.com/smp79/9b43a01742cb54af8a72246e17a92776/raw/a8d342e971b3ce049df4bdd77b199879a526b8b7/gistfile1.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC
 - Kodi version: current master

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

This PR is twofold:

1) It fixes the issue reported in #25097.

When play from here or automatically play next item are selected then a playlsit is generated.
If this was done through Video -> Files, on items that weren't yet scanned into the database then there was no `VideoInfoTag` and therefore `p->GetVideoInfoTag()->m_basePath` was actually empty.

This corrects that.

2) Requested updates from devs

As detailed in https://github.com/xbmc/xbmc/commit/54a63d02f1e63ebad0cd99dc06ca070c91ceb93c

## How has this been tested?

Part 1 by @smp79 who kindly reported the original issue.

## What is the effect on users?

Fix and code optimisation/clarity.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/dialogs/GUIDialogSimpleMenu.cpp [hunk 1]
```diff
@@ -135,11 +132,14 @@ bool CGUIDialogSimpleMenu::ShowPlaySelection(CFileItem& item, const std::string&
 
     if (item_new->m_bIsFolder == false)
     {
-      if (m_savePath.empty()) // If not set above (choose playlist selected)
-        m_savePath = item.GetDynPath();
+      std::string path{};
```
Comment (ksooo) [inline xbmc/dialogs/GUIDialogSimpleMenu.cpp:135]: Remove `{}` not needed. Default ctor will be called automatically.

File: xbmc/windows/GUIMediaWindow.cpp [hunk 2]
```diff
@@ -1532,27 +1532,49 @@ bool CGUIMediaWindow::OnPlayAndQueueMedia(const CFileItemPtr& item, const std::s
     // Remove ZIP, RAR files and folders
     CFileItemList playlist;
     playlist.Copy(*m_vecItems, true);
+
+    CLog::LogF(LOGDEBUG,
+               "m_vecItems (in playlist) before removal of folders/RAR/ZIP and duplicates");
+    for (const auto& p : playlist)
+      CLog::LogF(LOGDEBUG, "Path {}, DynPath {}", p->GetPath(), p->GetDynPath());
+
```
Comment (ksooo) [inline xbmc/windows/GUIMediaWindow.cpp:1540]: Please remove this. While this was useful during implementation, once the filtering of the list works, chances are almost zero that it breaks. So, no point in polluting the log with (potentially) many lines.

File: xbmc/windows/GUIMediaWindow.cpp [hunk 3]
```diff
@@ -1532,27 +1532,49 @@ bool CGUIMediaWindow::OnPlayAndQueueMedia(const CFileItemPtr& item, const std::s
...
-                      return i->GetVideoInfoTag()->m_basePath == j->GetVideoInfoTag()->m_basePath;
-                    }),
+                    [](const std::shared_ptr<CFileItem>& i, const std::shared_ptr<CFileItem>& j)
+                    { return i->GetDynPath() == j->GetDynPath(); }),
         playlist.end());
 
+    CLog::LogF(LOGDEBUG, "Playlist after remove duplicates");
+    for (const auto& p : playlist)
+      CLog::LogF(LOGDEBUG, "Path {}, DynPath {}", p->GetPath(), p->GetDynPath());
+
```
Comment (ksooo) [inline xbmc/windows/GUIMediaWindow.cpp:1566]: Please remove this. While this was useful during implementation, once the filtering of the list works, chances are almost zero that it breaks. So, no point in polluting the log with (potentially) many lines.

File: xbmc/windows/GUIMediaWindow.cpp [hunk 4]
```diff
@@ -1532,27 +1532,49 @@ bool CGUIMediaWindow::OnPlayAndQueueMedia(const CFileItemPtr& item, const std::s
...
                    playlist.end());
 
-    // Remove duplicates (eg. ISO/VIDEO_TS)
+    // Remove duplicates (eg. ISO/VIDEO_TS) in two stages
+    // Firstly with the same DynPath as our desired item
+    // Keeping our desired item instead of the first item with the same DynPath
+    playlist.erase(std::remove_if(playlist.begin(), playlist.end(),
+                                  [&item](const std::shared_ptr<CFileItem>& i) {
+                                    return i->GetDynPath() == item->GetDynPath() &&
+                                           i->GetPath() != item->GetPath();
```
Comment (ksooo) [inline xbmc/windows/GUIMediaWindow.cpp:1552]: No need to compare the dynpaths, paths is enough. Path is the identity of an item, there must not be two items having the same path and different dynpaths.

File: xbmc/windows/GUIMediaWindow.cpp [hunk 5]
```diff
@@ -1532,27 +1532,49 @@ bool CGUIMediaWindow::OnPlayAndQueueMedia(const CFileItemPtr& item, const std::s
...
+                   playlist.end());
+
+    // Now remove all other duplicates
     playlist.erase(
         std::unique(playlist.begin(), playlist.end(),
-                    [](const std::shared_ptr<CFileItem>& i, const std::shared_ptr<CFileItem>& j) {
-                      return i->GetVideoInfoTag()->m_basePath == j->GetVideoInfoTag()->m_basePath;
-                    }),
+                    [](const std::shared_ptr<CFileItem>& i, const std::shared_ptr<CFileItem>& j)
+                    { return i->GetDynPath() == j->GetDynPath(); }),
```
Comment (ksooo) [inline xbmc/windows/GUIMediaWindow.cpp:1560]: Why dynpath? Should by path. path == identity.

File: xbmc/windows/GUIMediaWindow.cpp [hunk 6]
```diff
@@ -1532,27 +1532,49 @@ bool CGUIMediaWindow::OnPlayAndQueueMedia(const CFileItemPtr& item, const std::s
...
+    for (const auto& p : playlist)
+      CLog::LogF(LOGDEBUG, "Path {}, DynPath {}", p->GetPath(), p->GetDynPath());
+
     // Chosen item
     int mediaToPlay =
         std::distance(playlist.begin(), std::find_if(playlist.begin(), playlist.end(),
                                                      [&item](const std::shared_ptr<CFileItem>& i) {
-                                                       return i->GetVideoInfoTag()->m_basePath ==
-                                                              item->GetVideoInfoTag()->m_basePath;
+                                                       return i->GetDynPath() == item->GetDynPath();
```
Comment (ksooo) [inline xbmc/windows/GUIMediaWindow.cpp:1571]: Why dynpath? Should by path. path == identity.

File: addons/resource.language.en_gb/resources/strings.po [hunk 7]
```diff
@@ -7289,6 +7289,9 @@ msgctxt "#13423"
 msgid "Remember for this path"
 msgstr ""
 
+#. Shown on context menu when a bluray:// or dvd:// playlist has already been saved
+#. Giving the user a change to select a new one via the simple menu dialog
```
Comment (ksooo) [inline addons/resource.language.en_gb/resources/strings.po:7293]: typo? change -> chance

File: xbmc/dialogs/GUIDialogSimpleMenu.cpp (hunk 1 above)
Comment (78andyp) [reply xbmc/dialogs/GUIDialogSimpleMenu.cpp:135]: Done

File: xbmc/windows/GUIMediaWindow.cpp (hunk 2 above)
Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1540]: Done

File: xbmc/windows/GUIMediaWindow.cpp (hunk 3 above)
Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1566]: Done

File: xbmc/windows/GUIMediaWindow.cpp (hunk 4 above)
Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1552]: I think this is right.
Lets say you have 10 episodes in a season over 2 discs.
You will have 10 FileItems. All will have Path = a VideoDB that is specific for the episode.
The first 5 will have a DynPath of the first disc (.ISO/VIDEO_TS.IFO/INDEX.BDMV) and the last 5 a DynPath of the second disc.

What this code does currently is select the correct (selected) item (ie Path) from the first disc and then the first entry from the second disc.

The rationale for this - without this PR, for a DVD you would play the disc 5 times - whereas it's probably reasonable to assume that you would watch the first 5 episodes from the menu, exit, and then want hte second disc to be played for the next 5 episodes.

Thinking about it, if it's a bluray and simple menu is selected then each entry should remain as you will be presented with the title selection each time - I'll test this further now.

This will be refined further in my next PR.

File: xbmc/windows/GUIMediaWindow.cpp (hunk 5 above)
Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1560]: Dynpath for reasons as above

File: xbmc/windows/GUIMediaWindow.cpp (hunk 6 above)
Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1571]: I agree. Done.

File: addons/resource.language.en_gb/resources/strings.po (hunk 7 above)
Comment (78andyp) [reply addons/resource.language.en_gb/resources/strings.po:7293]: Apologies, fixed.

File: xbmc/windows/GUIMediaWindow.cpp (hunk 4 above)
Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp:1552]: I think we are facing a conceptional flaw here. 

It seems not correct, that if you have a list with ten episodes (== 10 items), to reduce this to only two items, namely "select the correct (selected) item (ie Path) from the first disc and then the first entry from the second disc." This seems like a hack, just to make it somehow work. Video playlist will for example only show two items, one for episode 1, one for episode 6. That's clearly a bug, because user is not able to select episode 2-5 and 7-10 from the video playlist.

The actual problem imo is that the dynpath does not point to the actual episode to play, but to a "container" file representing 5 episodes in your example. This is not how dynpath is supposed to be used. And that's why you need all this filter hackery here. 

Correct implementation imo would be to extend the dynpath with some information which episode is ment (like .ISO/VIDEO_TS.IFO/INDEX.BDMV?track=42). Don't you already have the "track" info? I guess somewhere (outside the video playlist window) I can select the tracks for the episodes on the disc.

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1552]: And that's what I've been working on!! The original PR was the start - extending the use of bluray:// as that then points directly to the playlist rather than the ISO/folder. With this PR, once a episode is played the dynpath WILL be unique (as there will be an individual entry in the file table).

In #24997 I extend this to introduce dvd:// VFS support as well as more comprehensive episode selection.

The final part would be to generate dvd:// or bluray:// paths for each episode/movie version on disc at library addition - but that requires more work and needs this PR with #24997 tested in the alpha phase so we can see how robust my algoritms for assigning episodes are.

Ultimately then we wouldn't have this problem.

I've been working on these for months - it's helped me learn kodi but it's ended up being more complex than I first thought.

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1552]: I want to get folder stakcs playing nicely with this and then I'll tidy up #24997 and if we can get that in as well, we are well on the way to making DynPath unique for everything - as it should be.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp:1552]: Not sure I get all this. I only can say from what I understood that this PR seems to break the video playlist, because it removes video items from the file item list. For your example video play list should contain 10 items, one for every episode, not only entries for episode 1 and 6.

Video playlist == this window:
image

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1552]: That was a bug in the original PR - but as outlined above there are SOME circumstances when removing duplicates is appropriate - until bluray:// and dvd:// is fully implimented.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp:1552]: Can you please confirm that my understanding regarding video playlist breakage introduced by this PR is correct?

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp]: I wouldn't say breaks, but yes - if you had 5 episodes on a DVD ISO/folder then the playlist would be resolved to one entry so you could play all 5 episodes from the DVD menu and then when you stop playback and return to Kodi the DVD won't be played again.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp]: How is the „resolved“ item labeled? If it refers to something like„disc x“ i would be fine with that. If it is labelled „episode 1“ but referring to multiple episodes, this is a bug.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp]: I'm asking for the label of the item (the text displayed along with the item in GUI, movies window), not path or dynpath.

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp]: I don't change anything to do with the GUI.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp]: And that’s the problem. You should!

 I bet in the video playlist window i will see something like „Episode 1“ and „Episode 6“ (to stick with your 2 disc example), which is wrong because actually the items refer to something „multi episode“ (a disc). Not sure i get my message across…

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp]: Let me try and demonstrate:

Season 3 of Dad's Army is on 2 DVDs

In the GUI i see:
image

Currrently there is no simple menu for DVDs - so the disc it just played (ie menu and then selection from menu within player). I think most people would play all the episodes they want from the menu without exiting to kodi and the disc loading again - therefore only one entry for the disc is needed in the playlist rather than 7/8.

Similarly when the next disc is loaded for the second half of the series one would play all the episodes they want from the menu and then exit to kodi when finished.

Therefore only 2 entries are needed for this season - one for each disc.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp]: > Therefore only 2 entries are needed for this season - one for each disc.

Understood. My question still is, after removing the "duplicate" episodes, how will the screen look like?

There will only be two items left, one labelled "3x01. The ..." the other  "3x06. Room ..." - you see what I mean? The title of the items is wrong as they imply only episode 1 and 6 are present ... and what happens if you open the context menu of such an item and select "information"? What you do is a hack or workaround at best. Simply removing the items with same dynath is just the wrong approach.

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp]: There is no screen after removal - you go straight into the player.
Yes it is a hack - because there is currently no way to address DVD titles directly - the VFS doesn't exist yet (I've added it in the #24997 PR). To be honest, I'm not sure it's worth debating this any more, I'm happy to remove the code that removes duplicates and just leave it as it is. We need to get something in to fix the original problem.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp]: I'm afraid I'm not getting across what i wnat to say (language barrier as my first language is not English).

Do you know the video playlist window? If yes, what does it contain while you are playing the "filtered" item list?

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp]: Video playlist window?? Not sure i'm familiar with that.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp]: `CGUIMediaWindow::OnPlayAndQueueMedia` compiles a list of items which is handed over to the player. Only what you hand over will show up in the video playlist window. If you have 10 episodes in the movies window, and play next video automatically is enabled, and you select the first episode, 10 episodes will show up in the playlist window. With your change, only two items will show up in the playlist window, "episode 1" (for disc 1) and "episode 6" (for disc 2).

I agree that this is no major issue, but want to make sure that you understand the problem.

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp]: How do I get the video playlist window??
I may have a solution - I did something similar in #24304 - look at pictures 3 and 4 - the latter shows the user that a disc can contain multiple episodes.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp]: screenshot00003
screenshot00004

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp]: Ahh.. I never knew that. You are right, it is broken.
Sorry - my misunderstanding.

image

OK - my suggestion is that I remove the code that removes duplicates for now - so we can ge the fix in and I'll pick it up in #24997 which will introduce the dvd:// VFS and the ability to address titles directly and will mitigate this to a large extent anyway. I'll also extend the code I use in the Video -> Files display to show a disc has multiple episodes to the video playlist view as well so it would show two entries but Episodes 1-7 and Episodes 8-15.

Is that OK??

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp]: That is fine for me, yes.

Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp]: All done. Thanks for your guidance, sorry I didn't understand initially.

Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp]: Thanks for your patience. :-)

File: xbmc/windows/GUIMediaWindow.cpp [hunk 8]
```diff
@@ -1532,26 +1528,21 @@ bool CGUIMediaWindow::OnPlayAndQueueMedia(const CFileItemPtr& item, const std::s
...
-
     // Chosen item
     int mediaToPlay =
         std::distance(playlist.begin(), std::find_if(playlist.begin(), playlist.end(),
-                                                     [&item](const std::shared_ptr<CFileItem>& i) {
-                                                       return i->GetVideoInfoTag()->m_basePath ==
-                                                              item->GetVideoInfoTag()->m_basePath;
-                                                     }));
+                                                     [&item](const std::shared_ptr<CFileItem>& i)
+                                                     { return i->GetPath() == item->GetPath(); }));
```
Comment (ksooo) [inline xbmc/windows/GUIMediaWindow.cpp:1541]: Are you sure the change to not compare `m_basepath` but `Path()`is still needed?

File: xbmc/windows/GUIMediaWindow.cpp [hunk 9]
```diff
@@ -1532,26 +1528,21 @@ bool CGUIMediaWindow::OnPlayAndQueueMedia(const CFileItemPtr& item, const std::s
     // Remove ZIP, RAR files and folders
     CFileItemList playlist;
     playlist.Copy(*m_vecItems, true);
+
```
Comment (ksooo) [inline xbmc/windows/GUIMediaWindow.cpp:1531]: Nitpick, but this is not needed. ;-)

File: xbmc/windows/GUIMediaWindow.cpp [hunk 10]
```diff
@@ -1532,26 +1528,21 @@ bool CGUIMediaWindow::OnPlayAndQueueMedia(const CFileItemPtr& item, const std::s
...
-                                                     [&item](const std::shared_ptr<CFileItem>& i) {
-                                                       return i->GetVideoInfoTag()->m_basePath ==
-                                                              item->GetVideoInfoTag()->m_basePath;
-                                                     }));
+                                                     [&item](const std::shared_ptr<CFileItem>& i)
+                                                     { return i->GetPath() == item->GetPath(); }));
+
+    CLog::LogF(LOGDEBUG, "Item desired - Path {}, DynPath {}", item->GetPath(), item->GetPath());
+    CLog::LogF(LOGDEBUG, "Item resolved - Path {}, DynPath {}", playlist[mediaToPlay]->GetPath(),
+               playlist[mediaToPlay]->GetPath());
```
Comment (ksooo) [inline xbmc/windows/GUIMediaWindow.cpp:1545]: As there is no more new "resolution" done here, these log lines seem not needed anymore.

File: xbmc/windows/GUIMediaWindow.cpp (hunk 8 above)
Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1541]: Yes. That was part of the problem - if you select an item from Video -> Files that isn't in the library then the VideoInfoTag and hence m_basePath were empty.

File: xbmc/windows/GUIMediaWindow.cpp (hunk 9 above)
Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1531]: If you're sure that changing m_vecItems doesn't matter. The original code just looped through m_vecItems and added to PlayListPlayer one at a time. I was erring on the side of caution by making a copy.

File: xbmc/windows/GUIMediaWindow.cpp (hunk 10 above)
Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1545]: Agreed.

File: xbmc/windows/GUIMediaWindow.cpp (hunk 9 above)
Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp:1531]: I was requesting that you remove the blank line you have introduced here, no code change.

File: xbmc/windows/GUIMediaWindow.cpp (hunk 8 above)
Comment (ksooo) [reply xbmc/windows/GUIMediaWindow.cpp:1541]: Okay.

File: xbmc/windows/GUIMediaWindow.cpp (hunk 9 above)
Comment (78andyp) [reply xbmc/windows/GUIMediaWindow.cpp:1531]: Done

**Review by ksooo — APPROVED** [review]
As far as I can tell, this looks good.

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by ksooo** [comment]
jenkins build this please

**Review by enen92 — APPROVED** [review]
