### PR TITLE
Port Kodi to FFmpeg 5.0

### LINKED ISSUE #21625: ASS Subtitles embedded in MKV files not being rendered correctly
### Describe the bug
Here is a clear and concise description of what the problem is:

I have long had an issue with Kodi not properly playing mkv files that have .ass subtitles muxed into the file.
My two problems with subtitles are as follows:
Problem 1: When playing an episode of a series (it can be any episode) the dialogue font is displayed 2-3 times larger than it is supposed to be, and can sometimes cause the text to cover half the screen or more, depending on the length of the line.
The problem does not occur when I play the same file in mpv or any other player that uses mpv as the renderer.

Problem 2: With a certain episode of a different series, the video plays and the subtitles render in the size they are expected to be. However, none of the lines of the subtitles disappear when they're supposed to and will stay on the screen the entire episode, causing the screen to become more and more crowded with text the longer the episode plays.
However, the bug only seems to occur when the episode is first launched from the Kodi library. If I launch the episode and just let it play, the subtitles will not vanish when they are supposed to. But if I launch the episode, then use the 10 or 30 second skip back to the beginning of the episode, the subtitles will then appear and disappear when they are supposed to.
As with the previous problem, this issue does not occur when playing the same episode in mpv or and other mpv-based player.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

For the episode of the first series I described, the subtitles for the dialogue should be rendered and displayed in the proper size, just as they are when the episode is played in mpv here: First Series Played in mpv

For the episode of the second series I described, the lines of the subtitles should vanish when the line ends and not continue to remain on the screen for the entire episode. Example of how it is supposed to look from when I played it in mpv: Second Series Played in mpv

## Actual Behavior

For the episode of the first series, it displays the dialogue font in an incorrect size, to the point where the single line can often cover up half the screen.  Example of how it looks when played in Kodi: First Series Played in Kodi

For the episode of the second series, none of the subtitle lines disappear when they are supposed to, and subtitle lines that are commented off in the .ass file are also displayed when they should not be. Example of how it looks when played in Kodi: Second Series Played in Kodi

## Possible Fix

I once had to report a similar bug to another project called smplayer (the bug report from which is located here https://github.com/smplayer-dev/smplayer/issues/234 )
The issue ended up being a Windows-specific problem with the version of mpv the author was using having the subtitle bug, while a newer version of mpv did not have that bug. The problem was solved by the author updating the program to be based on the newer version of mpv.

### To Reproduce

Play this file in Kodi for the first problem: [File with Example of Problem 1](https://www.mediafire.com/file/ttkqpc8kcm7h6v5/0976_%255BSubsPlease%255D_%25281%2529_%25281%2529-002.mkv/file)

And play this file in Kodi for the second problem: [File with Example of Problem 2](https://www.mediafire.com/file/d6itonjk5z21j0r/1047_%255BErai-raws%255D_%25281%2529-001.mkv/file)

### Debuglog

The debuglog can be found here:
[debuglog](https://paste.kodi.tv/lopusalihe.kodi)

### Screenshots 
Here are some links or screenshots to help explain the problem:

I posted screenshots in the above example of the issue.

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 10 Version 21H1 (Build 19043.1706)
 - Kodi version: I had the problem in the latest stable version of Kodi 19.4. 
 I then tried using the v19 20220629-b3f37f1592 nightly development build in hopes that the problem would be fixed, but it still occurs in that nightly build as well. 
I also tried the videos in v20 Alpha 1, and while the reworking of the subtitle system seems to have massively improved the rendering of the subtitles (and completely fixed my first problem), the second problem still remains - but to a lesser extent that I describe in a reply below.

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### LINKED ISSUE #21766: master fails to build with FFmpeg >=5.0
### Describe the bug

Building against FFmpeg 5.1 fails because some deprecated APIs have been removed and some gained `const` specifiers:
```
[...]
/var/tmp/paludis/build/media-kodi-scm/work/kodi-scm/xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp:281:13: error: 'avcodec_encode_a
udio2' was not declared in this scope; did you mean 'avcodec_encode_subtitle'?
  281 |   int ret = avcodec_encode_audio2(m_CodecCtx, pkt, frame, &got_output);
      |             ^~~~~~~~~~~~~~~~~~~~~
      |             avcodec_encode_subtitle
/var/tmp/paludis/build/media-kodi-scm/work/kodi-scm/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp: In member function 'virtual IA
E::SoundPtr ActiveAE::CActiveAE::MakeSound(const std::string&)':
/var/tmp/paludis/build/media-kodi-scm/work/kodi-scm/xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp:3051:33: error: invalid conversion from 'AVInputFormat**' to 'const AVInputFormat**' [-fpermissive]
 3051 |   av_probe_input_buffer(io_ctx, &io_fmt, file.c_str(), nullptr, 0, 0);
      |                                 ^~~~~~~
      |                                 |
      |                                 AVInputFormat**
[...]
```

## Expected Behavior

The build should succeed

## Actual Behavior

The build errors out

## Possible Fix

Port to FFmpeg 5, examples:
- https://github.com/acoustid/chromaprint/pull/116
- https://github.com/gkv311/sview/commit/a255e0d402c6e576b4d0569a6a0fd206816d7954

### To Reproduce

1. Install FFmpeg >= 5.0
2. Configure kodi build using FFmpeg >= 5.0 
3. Start build

### Debuglog

The debuglog can be found here: 
[kodi-scm.log](https://github.com/xbmc/xbmc/files/9381902/kodi-scm.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Exherbo Linux
 - Kodi version: master branch @ 8a85a4c4d9b8ee8cbe10d8f073fcbe985b915ebb

### PR DESCRIPTION
**Pull request by basilgello**
## Description

This PR is a first attempt to prepare Kodi for upcoming Debian transition to FFmpeg 5.0

## Motivation and context

There is a bug report filed by @sramacher about Kodi and inputstream.ffmpegdirect failing to build against FFmpeg 5,0 in Debian experimental.

## How has this been tested?

Tested on Debian sid/bookworm locally and by Debian users.

## What is the effect on users?

Debian and other Linux users will be able to continue using Kodi on newer systems.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed
- [ ] 

Linked issues:
closes https://github.com/xbmc/xbmc/issues/21625
closes https://github.com/xbmc/xbmc/issues/21766

### CODE REVIEW

**Comment by lrusak** [comment]
You should discuss this stuff in slack first as there is at least 3 people working on this already.

**Comment by lrusak** [comment]
Also, FYI https://github.com/xbmc/xbmc/pull/16185

**Comment by basilgello** [comment]
> You should discuss this stuff in slack first as there is at least 3 people working on this already.

I did this when everyone was at DevCon :) And I expected it was an easy move!

**Comment by basilgello** [comment]
@AlwinEsch this fixes playback of TS files including the one you gave me in Slack (sky...)
@phunkyfish You asked about the draft PR

**Comment by wsnipex** [comment]
please note that in it's current state, jenkins is using ffmpeg 4.4 for building this PR

**Comment by phunkyfish** [comment]
@basilgello we’ll need to get a kodi branch for ffmpeg 5 created from our clone. @lrusak can you help with this?

Once that is there we need to update this file in your PR: https://github.com/xbmc/xbmc/blob/master/tools/depends/target/ffmpeg/FFMPEG-VERSION

Did you require any patches for the ffmpeg5 build?

**Comment by basilgello** [comment]
> Did you require any patches for ffmpeg5 build?

If I understood your question correctly, I do not need any modifications to ffmpeg5 source tree to run this.
I linked against ffmpeg packaged in Debian, and it has no patches Kodi adds to ffmpeg git tree.

**Comment by phunkyfish** [comment]
> > Did you require any patches for ffmpeg5 build?
> 
> If I understood your question correctly, I do not need any modifications to ffmpeg5 source tree to run this. I linked against ffmpeg packaged in Debian, and it has no patches Kodi adds to ffmpeg git tree.

Ok, great. Then it should be easy to create and ffmpeg 5 branch.

**Comment by basilgello** [comment]
Yes, 5.1.2 is better because I made all the tests with it.

**Comment by phunkyfish** [comment]
A general comment on this PR. There are quite a few `#if` macros added based on particular versions of ffmpeg components. 

I’m wondering if it’s possible to also add the ffmpeg release (maybe as a comment) so I’m the future it’s easier to tell when a macro could be removed.

Is there value in adding this or is everyone fine with just the component version checks?

**Comment by basilgello** [comment]
In theory there is `ff_const59` but it is only in libavformat and it is marked as volatile.

**Comment by a1rwulf** [comment]
Afaik we ever only supported one version of ffmpeg at the same time.
Why do we need those `#ifdefs` at all?

**Comment by phunkyfish** [comment]
Because Linux users may not have ffmpeg 5, they may only have 4. And as we don’t build ffmpeg for Linux we can force it.

**Comment by lrusak** [comment]
> Because Linux users may not have ffmpeg 5, they may only have 4. And as we don’t build ffmpeg for Linux we can’t force it.
> 
> (I think)

This isn't quite right, we detect the version we want, if not found we build the internal version. You can force building an external ffmpeg but we still require it to be compatible (think LibreELEC, etc).

**Comment by lrusak** [comment]
@basilgello You can use the new tag version here -> https://github.com/xbmc/FFmpeg/releases/tag/5.1.2-Nexus-Alpha3

**Comment by phunkyfish** [comment]
Oh, so we don’t really need the ifdefs at all. Just update the cmake script used on Linux?

**Comment by phunkyfish** [comment]
> 

Weird, this is empty on your reply

**Comment by lrusak** [comment]
> Oh, so we don’t really need the ifdefs at all. Just update the cmake script used on Linux?

Well, the depends build of ffmpeg uses the CMakeLists.txt found here -> https://github.com/xbmc/xbmc/blob/master/tools/depends/target/ffmpeg/CMakeLists.txt

This CMakeLists.txt is also used with using the cmake option `-DENABLE_INTERNAL_FFMPEG=ON`

There is a build script here https://github.com/xbmc/xbmc/blob/master/tools/depends/target/ffmpeg/autobuild.sh
I'm not sure if it's needed anymore though, I think it was to just configure an ffmpeg build manually (though it could be used for ppa builds, I'm not 100% sure).

**Comment by wsnipex** [comment]
autobuild.sh is used for PPA packaging: https://github.com/xbmc/xbmc/blob/master/tools/Linux/packaging/package-kodi-launchpad.sh#L43 but it's only downloading the tarball.

**Comment by basilgello** [comment]
I can try keeping ifdeffery in `cores/FFmpeg.{cpp,h}` and interface out the helper functions.

We also can go ffmpeg 5 fully for v20, and it is fine for me as Kodi from Debian maintainer. Any minimally tech-savvy Linux user intending to build Kodi 20 against FFmpeg 4 can revert a couple of patches or add the ifdeffery from intermediate versions of this PR.

Should I bother with helper functions approach now?

**Comment by wsnipex** [comment]
traditionally, we only ever supported 1 ffmpeg major version, so going to 5.x for Nexus would be preferred if doable.
@fuzzard ?

**Comment by basilgello** [comment]
OK, then I drop the ifdeffery with a separate commit and when it is merged and someone asks "How do I build Kodi 20 with ffmpeg 4", we will point to that specific commit.

File: xbmc/cdrip/EncoderFFmpeg.cpp [hunk 1]
```diff
@@ -327,19 +313,19 @@ bool CEncoderFFmpeg::WriteFrame()
...
-        throw EncoderException("Failed to write the frame data (error '{}')", __func__,
-                               FFmpegErrorToString(err));
+        throw FFMpegException("Failed to write the frame data (error '{}')", __func__,
+                              FFMpegErrorToString(err));
 
       av_packet_unref(pkt);
     }
   }
-  catch (EncoderException& caught)
+  catch (FFMpegException& caught)
```
Comment (a1rwulf) [inline xbmc/cdrip/EncoderFFmpeg.cpp:328]: Can this be `const FFMpegException& caught`?

File: xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp [hunk 2]
```diff
@@ -242,63 +248,78 @@ unsigned int CAEEncoderFFmpeg::GetFrames()
...
-                    in, in_size, 0);
+      av_packet_unref(pkt);
+    }
 
-  /* initialize the output packet */
-  AVPacket* pkt = av_packet_alloc();
-  if (!pkt)
+    size = pkt->size;
+  }
+  catch (FFMpegException& caught)
```
Comment (a1rwulf) [inline xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp:308]: Can this be const FFMpegException& caught?

File: xbmc/cores/AudioEngine/Interfaces/AEStream.h [hunk 3]
```diff
@@ -13,6 +13,7 @@
 
 extern "C" {
 #include <libavcodec/avcodec.h>
+#include <libavutil/channel_layout.h>
```
Comment (a1rwulf) [inline xbmc/cores/AudioEngine/Interfaces/AEStream.h:16]: Is there any particular reason why you added it to the header?
Is it sufficient to put it in the cpp file where it's needed?

File: xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodec.h [hunk 4]
```diff
@@ -16,6 +16,7 @@
 
 extern "C" {
 #include <libavcodec/avcodec.h>
+#include <libavutil/channel_layout.h>
```
Comment (a1rwulf) [inline xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodec.h:19]: Is this really needed in this header?

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp [hunk 5]
```diff
@@ -647,7 +638,10 @@ bool CDVDDemuxFFmpeg::Open(const std::shared_ptr<CDVDInputStream>& pInput, bool
           {
             int idx = m_pFormatContext->programs[i]->stream_index[j];
             AVStream* st = m_pFormatContext->streams[idx];
-            if ((st->codecpar->codec_type == AVMEDIA_TYPE_VIDEO && st->codec_info_nb_frames > 0) ||
+            // Related to https://patchwork.ffmpeg.org/project/ffmpeg/patch/20210429143825.53040-1-jamrial@gmail.com/
+            // was becomed replaced with AVSTREAM_EVENT_FLAG_NEW_PACKETS.
```
Comment (a1rwulf) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:642]: `was becomed` => `has been` maybe?

**Review by a1rwulf — COMMENTED** [review]
I can't really say how correct the ffmpeg code is, so maybe someone else can have a look too.
Commented on some minors.
Thanks for working on this!

**Comment by basilgello** [comment]
@a1rwulf Addressed the comments and fixed the remnants of cleanup breaking POSIX builds!

**Comment by phunkyfish** [comment]
jenkins build this please

**Comment by HiassofT** [comment]
I did a quick test with this PR on LibreELEC/RPi4 and while all files so far played fine I noticed that trying to play live TV with pvr.hts just gives a "waiting circle". Playing back recordings through pvr.hts worked fine though.

Current kodi master works fine here, I tested with this PR and LE/RPi ffmpeg both with software and hardware decoding and finally dropped all RPi and LE ffmpeg patches so I only used ffmpeg 5.1.2 plus the 5.1.2-Nexus-Alpha3 patches - still it hung with software decoding.

Here's a log file with ffmpeg component logging enabled, trying to play a SD H264 stream: http://ix.io/4dMh - note the repeating `debug <general>: ffmpeg[0x3613e90]: [h264] ct_type:0 pic_struct:3` messages

And here's a log trying to play a HD H265 stream: http://ix.io/4dMg

**Comment by basilgello** [comment]
Thanks @HiassofT for the testing! May I also ask you to test audio encoding and audio channel remapping? In the next force push I will add another big commit  switching to channel layout APIs. And of course I will check the log you provided!

**Comment by HiassofT** [comment]
I probably won't be able to help much with channel mapping/layout testing.

I don't have any of the modern multi-channel rubbish here, analog stereo NAD amplifier and 2.0 speakers FTW :-)

**Comment by HiassofT** [comment]
I did a quick test on my laptop running Debian Bullseye and pvr.hts live TV playback hangs there, too, http://ix.io/4dPU

**Comment by basilgello** [comment]
@HiassofT All your logs show `unsupported stream` error that shoukd have been fixed with extradata commit. However, debug log shows no traces of extradata being called at all. I recall TVHeadEnd streams use RTSP ? That might explain why extradata step is omitted.

**Comment by HiassofT** [comment]
tvheadend uses it's own tcp based HTSP protocol https://tvheadend.org/projects/tvheadend/wiki/Htsp - but don't ask me any specifics about it, kodi pvr addon maintainers might help you more there

The "unsupported stream" warning occurs with ffmpeg 4.4, too.

For reference I uploaded logs with ffmpeg logging and pvr.hts tracing enabled, once with latest version of this ffmpeg 5.1.2 PR and once with 4.4.1

5.1.2: https://www.horus.com/~hias/tmp/libreelec/kodi-5.1.2.log
4.4.1: https://www.horus.com/~hias/tmp/libreelec/kodi-4.4.1.log

pvr.hts seems to relay the stream packets fine to kodi, but it looks like no H264 packet parsing is happening with 5.1.2

**Comment by basilgello** [comment]
@lrusak can you please add a Kodi patch to ffmpeg changing iOS from 11 to 13 here https://github.com/xbmc/FFmpeg/blob/release/5.1-kodi/libavfilter/metal/utils.m#L34 and update the tarball ? This should fix iOS builds and make Jenkins evergreen :)

**Comment by basilgello** [comment]
@HiassofT Good catch! The logs show that parsing takes place but without extradata split.

**Comment by basilgello** [comment]
@HiassofT Please test the latest PR :)

**Comment by HiassofT** [comment]
Thanks, this is better, live TV playback is working now - tested both with software decoding and drmprime / v4l2 HW decoding on LibreELEC/RPi4

**Comment by HiassofT** [comment]
While extract_extradata seems to have helped getting live TV playback working kodi log is now spammed with ffmpeg errors during playback
```
2022-10-27 12:19:26.554 T:1743    error <general>: ffmpeg[0x29eea70]: [extract_extradata] Codec 'eac3' (86056) is not supported by the bitstream filter 'extract_extradata'. Supported codecs are: av1 (226) avs2 (192) avs3 (194) cavs (87) h264 (27) hevc (173) mpeg1video (1) mpeg2video (2) mpeg4 (12) vc1 (70) 
2022-10-27 12:19:29.395 T:1750     info <general>: Skipped 93 duplicate messages..
```
Full log is here: http://ix.io/4eeR

**Comment by enen92** [comment]
In case someone needs a testbuild I asked jenkins to build one with the py3 patch + the ffmpeg update for android (arm32) for personal use:
https://mirrors.kodi.tv/test-builds/android/arm/kodi-20221027-e62535fe-ffmpeg+py311-27074-armeabi-v7a.apk

Haven't find any regression/non-playable video yet.

**Comment by basilgello** [comment]
@enen92 @HiassofT please test with this revision! It should fix spamminess in the log

**Comment by lrusak** [comment]
> @lrusak can you please add a Kodi patch to ffmpeg changing iOS from 11 to 13 here https://github.com/xbmc/FFmpeg/blob/release/5.1-kodi/libavfilter/metal/utils.m#L34 and update the tarball ? This should fix iOS builds and make Jenkins evergreen :)

Do we actually need that? Can't we just disable the filter with `--disable-filter=yadif_videotoolbox`?

File: xbmc/cores/FFmpeg.cpp [hunk 6]
```diff
@@ -117,3 +135,132 @@ void ff_avutil_log(void* ptr, int level, const char* format, va_list va)
   buffer.erase(0, start);
 }
 
+#define FF_MAX_EXTRADATA_SIZE ((1 << 28) - AV_INPUT_BUFFER_PADDING_SIZE)
```
Comment (lrusak) [inline xbmc/cores/FFmpeg.cpp:138]: constexpr in anonymous namespace

File: xbmc/cores/FFmpeg.cpp [hunk 7]
```diff
@@ -117,3 +135,132 @@ void ff_avutil_log(void* ptr, int level, const char* format, va_list va)
...
+                       uint8_t** p_extradata)
+{
+  int extradata_size = 0;
+
+  if (!pkt || !p_extradata)
+    return 0;
+
+  *p_extradata = nullptr;
+
+  AVBSFContext* bsf = nullptr;
```
Comment (lrusak) [inline xbmc/cores/FFmpeg.cpp:152]: Please declare variables where they are used.

File: xbmc/cores/FFmpeg.cpp [hunk 8]
```diff
@@ -117,3 +135,132 @@ void ff_avutil_log(void* ptr, int level, const char* format, va_list va)
...
+    }
+
+    ret_extradata =
+        av_packet_get_side_data(pkt_ref, AV_PKT_DATA_NEW_EXTRADATA, &ret_extradata_size);
+    if (ret_extradata && ret_extradata_size > 0 && ret_extradata_size < FF_MAX_EXTRADATA_SIZE)
+    {
+      *p_extradata = (uint8_t*)av_malloc(ret_extradata_size + AV_INPUT_BUFFER_PADDING_SIZE);
+      if (!*p_extradata)
+      {
+        CLog::Log(LOGERROR, "{} - failed to allocate {} bytes for extradata", __FUNCTION__,
```
Comment (lrusak) [inline xbmc/cores/FFmpeg.cpp:239]: `CLog::LogF`

File: xbmc/cores/FFmpeg.cpp [hunk 9]
```diff
@@ -117,3 +135,132 @@ void ff_avutil_log(void* ptr, int level, const char* format, va_list va)
...
+                  ret_extradata_size);
+
+        av_packet_unref(pkt_ref);
+        av_bsf_free(&bsf);
+        av_packet_free(&dst_pkt);
+        return 0;
+      }
+
+      CLog::Log(LOGDEBUG, "{} - fetching extradata, extradata_size({})", __FUNCTION__,
```
Comment (lrusak) [inline xbmc/cores/FFmpeg.cpp:248]: `CLog::LogF`

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxClient.cpp [hunk 10]
```diff
@@ -149,41 +148,44 @@ bool CDVDDemuxClient::ParsePacket(DemuxPacket* pkt)
...
-    int len = stream->m_parser->parser->split(stream->m_context, pkt->pData, pkt->iSize);
-    if (len > 0 && len < FF_MAX_EXTRADATA_SIZE)
+    uint8_t* old_extradata = st->ExtraData;
+
+    AVPacket* avpkt = av_packet_alloc();
+    if (!avpkt)
     {
-      if (st->ExtraData)
-        delete[] st->ExtraData;
+      CLog::Log(LOGERROR, "CDVDDemuxClient::{} - av_packet_alloc failed: {}", __FUNCTION__,
```
Comment (lrusak) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxClient.cpp:158]: `CLog::LogF`

File: xbmc/cores/FFmpeg.h [hunk 11]
```diff
@@ -21,6 +22,28 @@ extern "C" {
 #include <libpostproc/postprocess.h>
 }
 
+// https://github.com/FFmpeg/FFmpeg/blob/56450a0ee4/doc/APIchanges#L18-L26
+#define FFMPEG_FMT_CONST const
```
Comment (lrusak) [inline xbmc/cores/FFmpeg.h:26]: Can we get rid of this define and just use `const`?

File: xbmc/cores/FFmpeg.h [hunk 12]
```diff
@@ -51,3 +74,7 @@ class CFFmpegLog
   int level;
 };
 
+int GetPacketExtradata(const AVPacket* pkt,
```
Comment (lrusak) [inline xbmc/cores/FFmpeg.h:77]: You could return `uint8_t*` (which is the allocated extradata), That way you can avoid the double pointer. You can use the address for the size `int& extraDataSize` or just return a `std::tuple<uint8_t*, int>`.

**Review by lrusak — COMMENTED** [review]
Just some minors and formatting issues.

Please be aware of the code guidelines for variable names -> https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#87-variables

**Comment by basilgello** [comment]
@lrusak I adderessed the issues you spotted, thanks! Also, disabling the filter you mentioned made ios-arm64 target green :)

@enen92 @HiassofT please re-test the latest rev.

Tomorrow I will drop of the net for one week (maybe even more) so if there are no serious issues with the review, let's merge it!

File: xbmc/cores/FFmpeg.cpp [hunk 13]
```diff
@@ -117,3 +135,130 @@ void ff_avutil_log(void* ptr, int level, const char* format, va_list va)
...
+  if (ret < 0)
+  {
+    av_bsf_free(&bsf);
+    return std::make_tuple(nullptr, 0);
+  }
+
+  AVPacket* dstPkt = av_packet_alloc();
+  if (!dstPkt)
+  {
+    CLog::LogF(LOGERROR, "{} - failed to allocate packet", __FUNCTION__);
```
Comment (CastagnaIT) [inline xbmc/cores/FFmpeg.cpp:193]: when you use `CLog::LogF` the `__FUNCTION__` is not needed because already implicit
so become as
```suggestion
    CLog::LogF(LOGERROR, "Failed to allocate packet");
```
you need to fix also all others

Comment (basilgello) [reply xbmc/cores/FFmpeg.cpp]: Done, thanks!

**Comment by thexai** [comment]
Runtime tested on Windows x64 and no (evident) issues found. I will continue using it for the next few days.

Windows patches in `tools/buildsteps/windows/patches` need to be updated to apply clean.

@basilgello, please add these patches changes: https://github.com/thexai/xbmc/commit/7aac790b13769fbed01b85b476aa73bcfc411bcd

**Comment by basilgello** [comment]
@thexai Done, thanks!

**Comment by HiassofT** [comment]
I finally got some time to do more extensive tests on LibreELEC/RPi4 and everything seems to be working fine here :+1:

**Comment by phunkyfish** [comment]
Jenkins build this please

**Comment by mriedel87** [comment]
I also can confirm that these patches are working fine. 
Tested on Debian (Sid; arch x64) with VNSI as PVR client plugin.
Thank you all :)

**Comment by thexai** [comment]
Tested also on Nvidia Shield 2019 with quietvoid's DoVi MKV patch (https://github.com/thexai/xbmc/commits/shield)

Tested some 4K MKV's that before to only play in HDR10 now play in DV without changing any Shield settings. All seems right 😀

**Comment by KLudwig-V** [comment]
@fuzzard 

FFMPEG 5 was released January 2022... (5.1 in July). If this gets moved to v21 that means (statistically) one year from now, when the release is already 2 years old...

What is the risk of adding this before the first Beta? It seems it has been tested and works OK...

**Comment by jjd-uk** [comment]
Yes it's tested, but only by a handful of people. With it being such a key Kodi component the felling was that we'd need to do at least another couple of alpha's to make sure the multitude of platforms Kodi runs on are adequately tested, and this could potentially severely delay v20. Once we get Beta done, then we can branch v20 from Master, then Master becomes v21 development so this could then be merged into Master and available in Nightlies.

**Comment by jjd-uk** [comment]
However it's also recognised there's a big push from some quarters to get ffmpeg 5 in, so rather than delaying v20, the current thinking is to do a quick v21 before end of 2023. Not something we typically do, but there's nothing to stop us doing v21 only a few months after v20.

**Comment by DecalicatanDecalicatan** [comment]
> However it's also recognised there's a big push from some quarters to get ffmpeg 5 in, so rather than delaying v20, the current thinking is to do a quick v21 before end of 2023. Not something we typically do, but there's nothing to stop us doing v21 only a few months after v20.

I guess you meant " to do a quick v21 before end of _**2022**_" ?

File: xbmc/cores/FFmpeg.cpp [hunk 14]
```diff
@@ -21,6 +21,19 @@
...
 
+namespace FFMPEG_HELP_TOOLS
+{
+
+std::string FFMpegErrorToString(int err)
+{
+  std::string text;
+  text.reserve(AV_ERROR_MAX_STRING_SIZE);
+  av_strerror(err, text.data(), AV_ERROR_MAX_STRING_SIZE);
+  return text;
```
Comment (neo1973) [inline xbmc/cores/FFmpeg.cpp:37]: I know this code already existed before but anyway it doesn't work because the `std::string` length is still zero: https://godbolt.org/z/P3eKTfWGz
I think the only way to fix this is to allocate a `char[AV_ERROR_MAX_STRING_SIZE]` on the stack and assign the `std::string` from there.

Comment (lrusak) [reply xbmc/cores/FFmpeg.cpp:37]: I think the solution is to use `resize` rather than `reserve`.

https://en.cppreference.com/w/cpp/string/basic_string/resize

File: xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp [hunk 15]
```diff
@@ -242,63 +261,80 @@ unsigned int CAEEncoderFFmpeg::GetFrames()
...
+    avcodec_fill_audio_frame(frame, channelNum, m_CodecCtx->sample_fmt, in, in_size, 0);
+
+    pkt->size = out_size;
+    pkt->data = out;
+
+    /* encode it */
+    err = avcodec_send_frame(m_CodecCtx, frame);
+    if (err < 0)
+      throw FFMpegException("Error sending a frame for encoding (error '{}')", __func__,
+                            FFMpegErrorToString(err));
```
Comment (neo1973) [inline xbmc/cores/AudioEngine/Encoders/AEEncoderFFmpeg.cpp:300]: The number of arguments doesn't match the format string. I think the `__func__` is a copy past mistake. Same a couple of lines below.

File: xbmc/cores/FFmpeg.cpp (hunk 14 above)
Comment (thexai) [reply xbmc/cores/FFmpeg.cpp:37]: `AV_ERROR_MAX_STRING_SIZE` is only 64 so I think it's ok:

```c++
  text.resize(AV_ERROR_MAX_STRING_SIZE);
  av_strerror(err, text.data(), text.size());
```

If it were a much larger number (1000, 2000) then it would be better to do what neo1973 says to avoid always returning a string of maximum length.

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxClient.cpp [hunk 16]
```diff
@@ -149,41 +149,44 @@ bool CDVDDemuxClient::ParsePacket(DemuxPacket* pkt)
...
+  if (stream->m_parser_split && stream->m_parser && stream->m_parser->parser)
   {
-    int len = stream->m_parser->parser->split(stream->m_context, pkt->pData, pkt->iSize);
-    if (len > 0 && len < FF_MAX_EXTRADATA_SIZE)
+    uint8_t* oldExtraData = st->ExtraData;
+
+    AVPacket* avpkt = av_packet_alloc();
+    if (!avpkt)
+    {
+      CLog::LogF(LOGERROR, "CDVDDemuxClient::{} - av_packet_alloc failed: {}", __FUNCTION__,
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxClient.cpp:159]:
```suggestion
      CLog::LogF(LOGERROR, "av_packet_alloc failed: {}", strerror(errno));
```

The` __FUNCTION__` parameter is not needed since `LogF` is used

**Comment by HiassofT** [comment]
@basilgello a small request: could you please drop the "@" mention to me in the "ffmpeg5: Get extradata with extract_extradata BSF" commit message? Changing it to HiassofT, without the "@" or to my real name, Matthias Reichl, would be fine - in general I appreciate acknowledgements.

I'm getting rather annoying  (email) notifications whenever that commit is added to a branch on some github repo our when you rebase and force-push your PR branch and I haven't yet managed to configure github to stop doing that and it's filling my inbox...

**Comment by basilgello** [comment]
@HiassofT Will do! Sorry!!! I thought fame would not be so annoying :)

**Comment by phunkyfish** [comment]
Jenkins build this please

**Comment by phunkyfish** [comment]
Jenkins build this please

**Comment by phunkyfish** [comment]
Jenkins build this please

**Comment by basilgello** [comment]
@garbear you reviewed #22309 which fixed a leak in extradata. I had to rebase this PR to handle it. Can you please have a look at the extradata commit, especially `std::unique_ptr<uint8_t[]>(retExtraData)`?

I made a reproducer and built it with `-fsanitize=leak` and no leaks were spotted, but I am not sure if this is valid approach re dangling pointers.

**Comment by garbear** [comment]
Can you switch to `std::make_unique`? I don't see any problems in the meantime.

File: xbmc/cores/FFmpeg.cpp [hunk 17]
```diff
@@ -117,3 +135,128 @@ void ff_avutil_log(void* ptr, int level, const char* format, va_list va)
...
+
+      continue;
+    }
+
+    size_t retExtraDataSize = 0;
+    uint8_t* retExtraData =
+        av_packet_get_side_data(pktRef, AV_PKT_DATA_NEW_EXTRADATA, &retExtraDataSize);
+    if (retExtraData && retExtraDataSize > 0 && retExtraDataSize < FF_MAX_EXTRADATA_SIZE)
+    {
+      extraData = (uint8_t*)av_malloc(retExtraDataSize + AV_INPUT_BUFFER_PADDING_SIZE);
```
Comment (CastagnaIT) [inline xbmc/cores/FFmpeg.cpp:234]: use C++ cast

Comment (basilgello) [reply xbmc/cores/FFmpeg.cpp:234]: Thanks, I am testing the variant with `std::make_unique<uint8_t[]>` in this function!

Comment (CastagnaIT) [reply xbmc/cores/FFmpeg.cpp:234]: ah ok then nvm

Comment (basilgello) [reply xbmc/cores/FFmpeg.cpp:234]: The variant I tested mixes `operator new` and `av_freep` and thus crashes. At least I tested the assumption that ffmpeg itself does not free anything :)

File: xbmc/cores/FFmpeg.h [hunk 18]
```diff
@@ -21,6 +22,27 @@ extern "C" {
...
+struct FFMpegException : public std::exception
+{
+  std::string s;
+  template<typename... Args>
+  FFMpegException(const std::string& fmt, Args&&... args)
+    : s(StringUtils::Format(fmt, std::forward<Args>(args)...))
+  {
+  }
+  ~FFMpegException() throw() {} // Updated
+  const char* what() const throw() { return s.c_str(); }
```
Comment (neo1973) [inline xbmc/cores/FFmpeg.h:39]: `throw()` is deprecated/removed from C++, instead this should be:
```suggestion
  const char* what() const noexcept override { return s.c_str(); }
```

Comment (basilgello) [reply xbmc/cores/FFmpeg.h:39]: Fixed!

File: xbmc/cores/FFmpeg.cpp (hunk 17 above)
Comment (basilgello) [reply xbmc/cores/FFmpeg.cpp:234]: nvm found an offending `av_freep` :)

**Comment by basilgello** [comment]
Should be ready for review and merge! Let's go?

**Review by garbear — APPROVED** [review]
Looks good from my end!

**Review by enen92 — APPROVED** [review]
I've been using this for quite a while so +1 from me
