### PR TITLE
[CGUIPassword] Media served through plugins is not shown when there is a master lock.

### LINKED ISSUE #24358: Using master lock will remove all sources on all users for servers like Jellyfin, Emby, Plex, ... + workaround
### Describe the bug
Here is a clear and concise description of what the problem is:

Hello, I am a programming noob and have no experience on github, so excuses me in advance if I put something wrong here,
I experience this problem with both the Kodi in Libreelec and coreelec, but problem seems to be in kodi itself, I dit NOT have this problem with Kodi 19 (but that might have been a fluke), problem started when I upgraded and clean installed to Kodi 20,
I have multiple users on Kodi that access movie and TV series shares on a Jellyfin (Emby Fork) server, everything works fine, UNTIL I enable the master lock because I want to lock ONE user with a pin code, if I do that ALL shares disapear on ALL users, if I than go to movies or TV series, and click "enable master lock" than my shares work again. Thanks to a friendly user on the KODI forum I have gotten a workaround to fix this. (more about this below)
This also seems to be a problem that has been in Kodi a LONG time with shares from Emby, JellyFin, Plex, ....
[Plex](https://github.com/croneter/PlexKodiConnect/issues/779)
[Emby](https://emby.media/community/index.php?/topic/23065-how-i-solved-the-emby-and-kodi-master-lock-issue/)
[Jellyfin1](https://github.com/jellyfin/jellyfin-kodi/issues/169)
[Jellyfin2](https://github.com/jellyfin/jellyfin-kodi/issues/619)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

After enabeling master lock and giving one user a PIN code I should still be able to access ALL my shares on ALL my users they have access to .

## Actual Behavior

The moment I enable master lock , ALL shares disapear on all the users (also shares they should have access to without a pin) and you have to manualy enable them and put the MASTER pin in to access them.

## Possible Fix

Thanks to a very very friendly member on the KODI forum "izprtxqkft" I got it working again.
[profile izprtxqkft](https://forum.kodi.tv/member.php?action=profile&uid=477027)
here you will find our conversation and how he fixed it ;
[kodi forum](https://forum.kodi.tv/showthread.php?tid=372240)

In short , this is the workaround ;
- Install Kodi (libreelec or Coreelec)
- Set Master Lock Code
- Install Jellyfin addon (NO NEED TO CONNECT TO ANY SERVER, OR ADD ANY SOURCES)
- Add new user (you HAVE to select "COPY SOURCES" at creation or it will NOT work)
- Add Jellyfin server and select sources (NOTHING SHOWS UP)
- Add Sources.xml file containing this (this is a specific fix for my Jellyfin, so for Emby or Plex another sources.xml file will be needed)
````
<?xml version="1.0" encoding="utf-8"?>
<sources>
  <video>
    <default pathversion="1"/>
    <source>
      <name>Videos</name>
      <path pathversion="1">/storage/videos/</path>
      <allowsharing>true</allowsharing>
    </source>
    <source>
      <name>TV Shows</name>
      <path pathversion="1">/storage/tvshows/</path>
      <allowsharing>true</allowsharing>
    </source>
    <source>
            <name>jf</name>
            <path pathversion="1">plugin://plugin.video.jellyfin/</path>
            <allowsharing>true</allowsharing>
    </source>
  </video>
  <music>
    <default pathversion="1"/>
    <source>
      <name>Music</name>
      <path pathversion="1">/storage/music/</path>
      <allowsharing>true</allowsharing>
    </source>
  </music>
  <pictures>
    <default pathversion="1"/>
    <source>
      <name>Pictures</name>
      <path pathversion="1">/storage/pictures/</path>
      <allowsharing>true</allowsharing>
    </source>
  </pictures>
</sources>
````

- Reboot

WORKS , instantly have all my movies and series on all the users with or without PIN to access, no need to unlock with master code.

### To Reproduce

1. add extra user
2. set master lock
3. see your sources locked at every login needing to unlock them

### What I think needs to be done,
I think (and I am in NO way a programmer) that Kodi should get a dedicated \sources folder somewhere, and Kodi should read all the files put in there, 
than addons for like Jellyfin, Emby, Plex, .... servers/shares should put there own xml file in that folder at install (like Jellyfin.xml)
at startup Kodi should than read those files and add whatever is in there to its own sources.xml (this way if you have multiple servers they wont overwrite each other settings.
Than probably something will also need to be changed so that you DONT have to make sure that you have to "copy sources" whenever you create a extra user.

I realy hope this can be fixed by someone in the next Kodi versions.

### Debuglog

The debuglog can be found here:  [log](http://ix.io/4pDB)

### Your Environment
Used Operating system:

 - Operating system version/name: Libreelec (but also tryed on box with coreelec)
 - Kodi version: 20
 - running on RaPi4B (but also tried on Amlogic S905x box)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

One way to fix #24358 - which it looks like has been an issue in various guises for a number of years.

The issue occurs because, when there is a master lock, each media item's lock status is checked in `CGUIPassword::IsDatabasePathUnlocked`. The latter part of this routine tries to find the media's source and checks to see if the source is locked.

Jellyfin (and I assume the other plugins) don't have an entry in `sources.xml` so the source is not found and the routine exits false indicating the media is locked and hence it is not shown.

The workaround has been to create a dummy Jellyfin entry in sources that is 'found' by `CUtil::GetMatchingSource`.

As far as I can see there are 3 possible ways to fix this:

1) As per this PR - check to see if the media source is a plugin, and if so, instead of looking for a non-existant source it simply goes on whether videos are locked generally and if the video selection screen is displayed (as by definition if you're on the latter you've entered the master password).

2) You could just change the `return false` at the end of the `CGUIPassword::IsDatabasePathUnlocked` routine to `return true` - which is similar to the other lock checking routines - ie. assume it's unlocked if all else fails - but this way you'd never be able to lock the plugin video sources.

3) The plugin would need to be modified to add itself to the `sources.xml`. The two obvious issues are 1) it requires the plugin creators to do it and 2) they would need then to manage what can be seen through the source - ie. if you add the dummy entry above you can access all the videos/music/settings of the plugin through the souces entry.

## Motivation and context

As above.

## How has this been tested?

Windows 11 x64 with Jellyfin server.

EDIT: Confirmed working by the OP in https://github.com/xbmc/xbmc/issues/24358#issuecomment-1919616509

## What is the effect on users?

As above.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [X] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Jenkins build this please

File: xbmc/GUIPassword.cpp [hunk 1]
```diff
@@ -544,6 +545,14 @@ bool CGUIPassword::IsDatabasePathUnlocked(const std::string& strPath, VECSOURCES
   if (g_passwordManager.bMasterUser || profileManager->GetMasterProfile().getLockMode() == LOCK_MODE_EVERYONE)
     return true;
 
+  // Don't check plugin paths as they don't have an entry in sources.xml
+  // Base locked status on videos being locked and being in the video
+  // navigation screen (must have passed lock by then)
+  CURL url{strPath};
+  if (url.IsProtocol("plugin"))
+    return !(profileManager->GetCurrentProfile().videoLocked() &&
+             CServiceBroker::GetGUI()->GetWindowManager().GetActiveWindow() != WINDOW_VIDEO_NAV);
```
Comment (fuzzard) [inline xbmc/GUIPassword.cpp:554]: Is there any particular reason this is only "video"? I would assume users may want to use locking for audio (or pictures, or whatever other plugin types we have) as well possibly?

This looks to be at a level where it shouldnt explicitly handle one specific media type

Comment (78andyp) [reply xbmc/GUIPassword.cpp:554]: > Is there any particular reason this is only "video"? I would assume users may want to use locking for audio (or pictures, or whatever other plugin types we have) as well possibly?
> 
> This looks to be at a level where it shouldnt explicitly handle one specific media type

Interestingly there is no lock on TV shows.
I've added a commit for music.
Jellyfin doesn't serve anything else I don't think.
I think the other plugins make content available through the addon itself and not the default kodi menu.

Comment (78andyp) [reply xbmc/GUIPassword.cpp]: Ignore the above. I've done more testing today.
Music doesn't go through `CGUIPassword::IsDatabasePathUnlocked` and works as it should do already.
TV shows and videos are part of `videodb` so there doesn't need to be a seperate lock for TV shows.
I think the only code that's needed is the original code.
