### PR TITLE
Bluray: Fix linux support

### LINKED ISSUE #26407: Cannot play Bluray on latest release on debian 12
[debug_20.5.0.log](https://github.com/user-attachments/files/18751075/debug_20.5.0.log)

### Describe the bug
Using an external Bluray drive, valid bluray that plays using VLC do not play using xbmc

## Expected Behavior
Insert disc in drive, go to "Drive" menu and then start playing the disc

## Actual Behavior
The disc doesn't play.
Even its title is not displayed

## Possible Fix
Using debug log, is appears that xbmc tries to open /dev/cdrom/<path> instead of using disc mount point.

### To Reproduce
1. Start kodi
2. Insert disc 
3. Go to disc menu 

### Debuglog
2025-02-13 12:59:49.562 T:42236 debug : CBlurayCallback::Logger - bluray.c:1463: libbluray version 1.3.4
2025-02-13 12:59:49.562 T:42236 debug : CBlurayCallback::Logger - bluray.c:1488: BLURAY initialized!
2025-02-13 12:59:49.562 T:42236 debug : CBlurayCallback::Logger - register.c:420: bd_psr_write(): PSR18 (MENU_LANG) 0xffffff -> 0x656e67
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback::Logger - disc.c:333: failed opening UDF image (null)
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback - Error opening file! (/dev/cdrom/AACS/Unit_Key_RO.inf)
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback::Logger - aacs.c:83: AACS/Unit_Key_RO.inf not found. No AACS protection.
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback - Error opening file! (/dev/cdrom/BDMV/index.bdmv)
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback - Error opening file! (/dev/cdrom/BDMV/INDEX.BDM)
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback::Logger - disc.c:437: error opening file BDMV/index.bdmv
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback - Error opening file! (/dev/cdrom/BDMV/BACKUP/index.bdmv)
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback::Logger - disc.c:437: error opening file BDMV/BACKUP/index.bdmv
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback - Opening dir /dev/cdrom/BDMV/PLAYLIST
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback - Error opening dir! (/dev/cdrom/BDMV/PLAYLIST)
2025-02-13 12:59:49.563 T:42236 error : CBlurayDirectory::InitializeBluray - failed to open /dev/cdrom
2025-02-13 12:59:49.563 T:42236 debug : CBlurayCallback::Logger - bluray.c:1610: BLURAY destroyed!

[debug.log](https://github.com/user-attachments/files/18783439/debug.log)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: sgo@pi5:~ $ raspbian 12.9
 - Linux pi5 6.6.62+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.62-1+rpt1 (2024-11-25) aarch64 GNU/Linux
 - Kodi version: Kodi Media Center 22.0-ALPHA1 (21.90.700) Git:20250210-0bf4dd5f0c

*n*ote: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.

### PR DESCRIPTION
**Pull request by sgonauer**
## Description
This pull-request fixes bluray playback on Linux.

## Motivation and context
This fixes https://github.com/xbmc/xbmc/issues/26407

## How has this been tested?
The change has been tested on raspbian with an external Bluray drive.
The same test has been done on Windows build.

Both build were able to play Bluray.

## What is the effect on users?
Allow playing blurays on Debian 12 and most likely on any Linux distributiion
## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/filesystem/BlurayDirectory.cpp [hunk 1]
```diff
@@ -28,6 +28,9 @@
 #include <memory>
 #include <stdlib.h>
 #include <string>
+#ifdef HAVE_GETMNTENT_R
+#include <mntent.h>
```
Comment (fuzzard) [inline xbmc/filesystem/BlurayDirectory.cpp:32]: Can you keep this include alphabetical

File: xbmc/filesystem/BlurayDirectory.cpp [hunk 2]
```diff
@@ -212,6 +215,44 @@ void CBlurayDirectory::GetRoot(CFileItemList &items)
...
+    if (mtab)
+    {
+      struct mntent *m, mbuf;
+      char buf[8192];
+
+      while ((m = getmntent_r(mtab, &mbuf, buf, sizeof(buf))) != NULL)
+      {
+        if (!strcmp(m->mnt_fsname, bd_device))
+        {
+          CLog::Log(LOGERROR, "{}: found mount point = {}", __func__, m->mnt_dir);
```
Comment (fuzzard) [inline xbmc/filesystem/BlurayDirectory.cpp:243]: Better to use CLog:LogF, and then the ``__func__`` is unneccessary

**Review by fuzzard — DISMISSED** [review]
Cant talk for actual functionality, i'll leave that to the linux folk

File: xbmc/filesystem/BlurayDirectory.cpp (hunk 1 above)
Comment (sgonauer) [reply xbmc/filesystem/BlurayDirectory.cpp:30]: change applied

File: xbmc/filesystem/BlurayDirectory.cpp (hunk 2 above)
Comment (sgonauer) [reply xbmc/filesystem/BlurayDirectory.cpp]: I removed this trace that was used for debug and anyway had the wrong log level

File: xbmc/filesystem/BlurayDirectory.cpp [hunk 3]
```diff
@@ -212,6 +215,42 @@ void CBlurayDirectory::GetRoot(CFileItemList &items)
     items.Add(item);
 }
 
+void CBlurayDirectory::FindMountPoint(std::string* file)
```
Comment (enen92) [inline xbmc/filesystem/BlurayDirectory.cpp:218]: This is specific to Linux. Wouldn't it be possible to move to the base directory and somehow implement it only on Linux? Other implementations would return file

**Comment by vpeter4** [comment]
With this PR I'm getting one line in kodi.log which starts with garbage on LE master playing ISO from NFS.
It happens on all my few samples.
Maybe because real_path is now not const and it changes somewhere later?

`GetDirectory - Error getting @4'?#4'2f.........`

```
2025-03-08 18:27:21.292 T:1788    error <general>: GetDirectory - Error getting udf://nfs%3a%2f%2f192.168.0.5%2fThe%20Stanford%20Prison%20Experiment.iso/BDMV/META/TN
2025-03-08 18:27:21.396 T:1788    error <general>: GetDirectory - Error getting @4'?#4'2f192.168.0.5%2fThe%20Stanford%20Prison%20Experiment.iso/BDMV/PLAYLIST
2025-03-08 18:27:22.766 T:1646     info <general>: VideoPlayer::OpenFile: nfs://192.168.0.5/The Stanford Prison Experiment.iso
2025-03-08 18:27:22.766 T:1791     info <general>: Creating InputStream
2025-03-08 18:27:22.989 T:1791     info <general>: VideoPlayer: playing a file with menu's
```
Without PR
```
2025-03-08 18:32:08.218 T:1581    error <general>: GetDirectory - Error getting udf://nfs%3a%2f%2f192.168.0.5%2fThe%20Stanford%20Prison%20Experiment.iso/BDMV/META/TN
2025-03-08 18:32:11.787 T:952      info <general>: VideoPlayer::OpenFile: nfs://192.168.0.5/The Stanford Prison Experiment.iso
2025-03-08 18:32:11.787 T:1584     info <general>: Creating InputStream
2025-03-08 18:32:11.905 T:1584     info <general>: VideoPlayer: playing a file with menu's
```

**Review by neo1973 — CHANGES_REQUESTED** [review]
As @vpeter4 noted the problem with the garbage in the log is caused by the `real_path` string being deleted  when leaving `InitializeBluray()` but it's still in use by the callbacks.

So please add a private `std::string m_realPath` member which will survive at least as long as the `m_bd` handle.

Also, I couldn't test my proposed changes as I don't have a bluray drive!

**Comment by sgonauer** [comment]
@neo1973 : thank you for the comments. I will rewrite the patch in that direction. I am more a C than C++ guy and was not sure how to handle std::string.
I hope to send an update later this week.

File: xbmc/filesystem/BlurayDirectory.cpp [hunk 4]
```diff
@@ -284,7 +326,8 @@ bool CBlurayDirectory::InitializeBluray(const std::string &root)
   g_LangCodeExpander.ConvertToISO6392T(g_langInfo.GetDVDMenuLanguage(), langCode);
   bd_set_player_setting_str(m_bd, BLURAY_PLAYER_SETTING_MENU_LANG, langCode.c_str());
 
-  if (!bd_open_files(m_bd, const_cast<std::string*>(&root), CBlurayCallback::dir_open, CBlurayCallback::file_open))
+  if (!bd_open_files(m_bd, const_cast<std::string*>(&real_path), CBlurayCallback::dir_open,
+                     CBlurayCallback::file_open))
```
[the remark this answers is not in the document]
Comment (sgonauer) [reply xbmc/filesystem/BlurayDirectory.cpp]: applied

File: xbmc/filesystem/BlurayDirectory.h [hunk 5]
```diff
@@ -30,6 +30,7 @@ class CBlurayDirectory : public IDirectory
   bool GetDirectory(const CURL& url, CFileItemList &items) override;
 
   bool InitializeBluray(const std::string &root);
+  void FindMountPoint(std::string* file);
```
[the remark this answers is not in the document]
Comment (sgonauer) [reply xbmc/filesystem/BlurayDirectory.h]: Applied

**Comment by sgonauer** [comment]
I applied the requested changes and tested again.

**Comment by neo1973** [comment]
Thank you @sgonauer :slightly_smiling_face: 

@vpeter4: Can you please test if this fixes the garbage log for you?

**Comment by vpeter4** [comment]
Kodi log is now without garbage lines.

**Review by neo1973 — APPROVED** [review]
(not runtime tested at all by myself...)

**Comment by sgonauer** [comment]
@neo1973 what will happen now ? Will this be merged ?

**Comment by neo1973** [comment]
I'll keep the PR open for a couple of days so others have the chance to review and test it as well. If there is no push back it will be merged afterwards.

**Review by enen92 — COMMENTED** [review]
Sorry for the delay, pretty busy at the moment.
Regarding my previous comment, I am not really a big fan of having platform specific stuff in platform agnostic code (in this case bluray vfs). Can you check if something like this works:

```
From 3f64ae44d0dd14437305ff8b3bbe7f72516ea2fd Mon Sep 17 00:00:00 2001
From: Miguel Borges de Freitas <92enen@gmail.com>
Date: Fri, 14 Mar 2025 19:43:48 +0000
Subject: [PATCH] Test resolve mount

---
 xbmc/filesystem/BlurayDirectory.cpp               | 10 ++++++++--
 xbmc/filesystem/IDirectory.h                      |  7 +++++++
 xbmc/platform/posix/filesystem/PosixDirectory.cpp |  6 ++++++
 xbmc/platform/posix/filesystem/PosixDirectory.h   |  1 +
 4 files changed, 22 insertions(+), 2 deletions(-)

diff --git a/xbmc/filesystem/BlurayDirectory.cpp b/xbmc/filesystem/BlurayDirectory.cpp
index 1e0ec83d79..2b35addf20 100644
--- a/xbmc/filesystem/BlurayDirectory.cpp
+++ b/xbmc/filesystem/BlurayDirectory.cpp
@@ -14,6 +14,7 @@
 #include "URL.h"
 #include "filesystem/BlurayCallback.h"
 #include "filesystem/Directory.h"
+#include "filesystem/DirectoryFactory.h"
 #include "guilib/LocalizeStrings.h"
 #include "utils/LangCodeExpander.h"
 #include "utils/RegExp.h"
@@ -267,7 +268,7 @@ CURL CBlurayDirectory::GetUnderlyingCURL(const CURL& url)
   return CURL(host.append(filename));
 }

-bool CBlurayDirectory::InitializeBluray(const std::string &root)
+bool CBlurayDirectory::InitializeBluray(const std::string& root)
 {
   bd_set_debug_handler(CBlurayCallback::bluray_logger);
   bd_set_debug_mask(DBG_CRIT | DBG_BLURAY | DBG_NAV);
@@ -284,7 +285,12 @@ bool CBlurayDirectory::InitializeBluray(const std::string &root)
   g_LangCodeExpander.ConvertToISO6392T(g_langInfo.GetDVDMenuLanguage(), langCode);
   bd_set_player_setting_str(m_bd, BLURAY_PLAYER_SETTING_MENU_LANG, langCode.c_str());

-  if (!bd_open_files(m_bd, const_cast<std::string*>(&root), CBlurayCallback::dir_open, CBlurayCallback::file_open))
+  std::string realPath = root;
+  auto fileHandler = CDirectoryFactory::Create(CURL{root});
+  if (fileHandler)
+      realPath = fileHandler->ResolveMountPoint(root);
+
+  if (!bd_open_files(m_bd, const_cast<std::string*>(&realPath), CBlurayCallback::dir_open, CBlurayCallback::file_open))
   {
     CLog::Log(LOGERROR, "CBlurayDirectory::InitializeBluray - failed to open {}",
               CURL::GetRedacted(root));
diff --git a/xbmc/filesystem/IDirectory.h b/xbmc/filesystem/IDirectory.h
index 69def3f5b5..f0f054103e 100644
--- a/xbmc/filesystem/IDirectory.h
+++ b/xbmc/filesystem/IDirectory.h
@@ -102,6 +102,13 @@ public:
   \return Returns \e false if not successful
   */
   virtual bool Remove(const CURL& url) { return false; }
+
+  /*!
+  \brief Provided a path, attempts to resolve to a mount point
+  \param path Path to resolve
+  \return Returns the mountpoint if found, else the provided path
+  */
+  virtual const std::string& ResolveMountPoint(const std::string& path) { return path; }

   /*!
   \brief Recursively removes the directory
diff --git a/xbmc/platform/posix/filesystem/PosixDirectory.cpp b/xbmc/platform/posix/filesystem/PosixDirectory.cpp
index 761b8d53b4..903bcbdf5e 100644
--- a/xbmc/platform/posix/filesystem/PosixDirectory.cpp
+++ b/xbmc/platform/posix/filesystem/PosixDirectory.cpp
@@ -206,3 +206,9 @@ bool CPosixDirectory::Exists(const CURL& url)
     return false;
   return S_ISDIR(buffer.st_mode) ? true : false;
 }
+
+const std::string& CPosixDirectory::ResolveMountPoint(const std::string& path)
+{
+    // Do your stuff here
+    return path;
+}
diff --git a/xbmc/platform/posix/filesystem/PosixDirectory.h b/xbmc/platform/posix/filesystem/PosixDirectory.h
index eb323b68e9..6e9ed2d9a5 100644
--- a/xbmc/platform/posix/filesystem/PosixDirectory.h
+++ b/xbmc/platform/posix/filesystem/PosixDirectory.h
@@ -23,6 +23,7 @@ public:
   bool Exists(const CURL& url) override;
   bool Remove(const CURL& url) override;
   bool RemoveRecursive(const CURL& url) override;
+  const std::string& ResolveMountPoint(const std::string& path) override;
 private:
   bool Create(const std::string& path);
 };
--
2.39.5 (Apple Git-154)
```

That would place the getmntent stuff/ifdefs on platform code (although it's not really posix compliant but better there than in the bluray implementation).

**Comment by sgonauer** [comment]
@enen92 I have updated the patches with your suggestion which I combined with @neo1973 earlier proposition.
I tested on both Linux and Windows and everything is fine.

File: xbmc/filesystem/IDirectory.h [hunk 6]
```diff
@@ -103,6 +103,13 @@ class IDirectory
   */
   virtual bool Remove(const CURL& url) { return false; }
 
+  /*!
+  \brief Provided a path, attempts to resolve to a mount point
+  \param path Path to resolve
+  \return Returns the mountpoint if found, else the provided path
+  */
+  virtual std::string ResolveMountPoint(const std::string& path) { return path; }
```
Comment (enen92) [inline xbmc/filesystem/IDirectory.h:111]:
```suggestion
  virtual std::string ResolveMountPoint(const std::string& path) const { return path; }
```

File: xbmc/platform/posix/filesystem/PosixDirectory.cpp [hunk 7]
```diff
@@ -206,3 +210,51 @@ bool CPosixDirectory::Exists(const CURL& url)
     return false;
   return S_ISDIR(buffer.st_mode) ? true : false;
 }
+
+std::string CPosixDirectory::ResolveMountPoint(const std::string& file)
```
Comment (enen92) [inline xbmc/platform/posix/filesystem/PosixDirectory.cpp:214]:
```suggestion
std::string CPosixDirectory::ResolveMountPoint(const std::string& file) const
```

File: xbmc/platform/posix/filesystem/PosixDirectory.h [hunk 8]
```diff
@@ -23,6 +23,8 @@ class CPosixDirectory : public IDirectory
   bool Exists(const CURL& url) override;
   bool Remove(const CURL& url) override;
   bool RemoveRecursive(const CURL& url) override;
+  std::string ResolveMountPoint(const std::string& file) override;
```
Comment (enen92) [inline xbmc/platform/posix/filesystem/PosixDirectory.h:26]:
```suggestion
  std::string ResolveMountPoint(const std::string& file) const override;
```

**Review by enen92 — CHANGES_REQUESTED** [review]
Just a small request (const modifier)

File: xbmc/platform/posix/filesystem/PosixDirectory.cpp [hunk 9]
```diff
@@ -206,3 +210,51 @@ bool CPosixDirectory::Exists(const CURL& url)
...
+        if (bdDeviceSv == m->mnt_fsname)
+        {
+          return m->mnt_dir;
+        }
+      }
+
+      CLog::LogF(LOGERROR, "No mount point for device '{}' found", bdDeviceSv);
+    }
+    else
+      CLog::LogF(LOGERROR, "Failed to open mount table");
```
Comment (enen92) [inline xbmc/platform/posix/filesystem/PosixDirectory.cpp:256]: and this probably a WARNING?

Comment (sgonauer) [reply xbmc/platform/posix/filesystem/PosixDirectory.cpp:256]: first one shpuld be a warning the second is more serious I believe

**Comment by sgonauer** [comment]
@enen92 : changes applied

**Review by enen92 — CHANGES_REQUESTED** [review]
Leftover and it's good to go

**Comment by sgonauer** [comment]
@enen92 Sorry I missed this leftover. This is now removed. Thanks a lot for the help here.

**Review by enen92 — APPROVED** [review]

**Comment by enen92** [comment]
@sgonauer thanks for your work on this.
Do you want to handle a backport to omega branch?

**Comment by sgonauer** [comment]
> @sgonauer thanks for your work on this. Do you want to handle a backport to omega branch?

Sure, it will take me around a week to get something.  Do I need to link this PR in the backport PR ? If yes how ?

**Comment by enen92** [comment]
Nah just cherry pick the commits on top of current omega branch (maybe they even apply cleanly). Then just link this pr on the future pr.
