### PR TITLE
[CC] Fix basic american and special american charsets for EIA-608 CC …

### LINKED ISSUE #18845: Not decoding some EIA-608 closed caption characters
### Describe the bug
Here is a clear and concise description of what the problem is:

EIA-608 closed caption decoding skips some characters due to an invalid condition check.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Standard characters such as latin e acute "é" should be present in decoded closed captions

## Actual Behavior

Some valid characters such as e acute are not decoded

## Possible Fix

https://github.com/xbmc/xbmc/blob/eb161cdb7c4c97e9f054192c9ea9e8d00839c305/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c

Line 492 of the cc_decode_EIA608 function should be reviewed to match the comment of line 493

I.e.  the condition "if (c1 & 0x60)" is invalid as the range "0x20 <= c1 <= 0x7f" does not always correspond to bits 0b0110000.

Consequently, the function cc_decode_standard_char should be reviewed as it implies the same erroneous condition check.

More details on EIA-608 closed caption encoding can be found at 
http://www.theneitherworld.com/mcpoodle/SCC_TOOLS/DOCS/CC_CHARS.HTML

### To Reproduce

1. Play PVR video (live or recording) that has EIA-608 closed captions

### Debuglog

The debuglog can be found here:
No debug log corresponding to that issue

### Screenshots
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by enen92**
…decoder

## Description
This PR fixes the closed caption EIA-608 decoder that was incorrectly mapping exceptions in the Basic North American character set and Special North American character set. Those characters are usually mapped to unicode, thus taking more than 1 byte (`sizeof(char)`).
The map was taken from the ffmpeg decoder (c.f. https://github.com/FFmpeg/FFmpeg/blob/ce297b44d3b107150c07017993c267a4b9bb41b0/libavcodec/ccaption_dec.c#L69-L170), for more information on those overrides please check https://en.wikipedia.org/wiki/EIA-608#Characters.

This also allows to further extend the supported overrides to also cover the Extended Western European character set (spanish, french, portuguese, german, danish) in the future.

Please carefully review, I'm not sure I'm not leaking somewhere.

@hudokkow can you check if the license should in fact change?

## Motivation and Context
Fixes https://github.com/xbmc/xbmc/issues/18845

## How Has This Been Tested?
With the sample provided in the issue report. Also tested other samples containing the same closed captions.

## Screenshots (if appropriate):

**master**
master

**pr**
pr

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c [hunk 1]
```diff
@@ -87,26 +78,52 @@ static int good_parity(uint16_t data)
...
+            [0x37] = "\u266a",
+            [0x38] = "\u00e0",
+            [0x39] = "\u00A0",
+            [0x3a] = "\u00e8",
+            [0x3b] = "\u00e2",
+            [0x3c] = "\u00ea",
+            [0x3d] = "\u00ee",
+            [0x3e] = "\u00f4",
+            [0x3f] = "\u00fb",
+        },
```
Comment (fuzzard) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c:123]: Did clang-format do something funky with this block, or the one above?

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c [hunk 2]
```diff
@@ -87,26 +78,52 @@ static int good_parity(uint16_t data)
...
+         [0x2a] = "\u00e1",
+         [0x5c] = "\u00e9",
+         [0x5e] = "\u00ed",
+         [0x5f] = "\u00f3",
+         [0x60] = "\u00fa",
+         [0x7b] = "\u00e7",
+         [0x7c] = "\u00f7",
+         [0x7d] = "\u00d1",
+         [0x7e] = "\u00f1",
+         [0x7f] = "\u2588"},
```
Comment (fuzzard) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c:104]: is there a missing } somewhere in this block?

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c (hunk 1 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c:123]: I tried to adjust it manually, but clang-format changed it again to this style

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c (hunk 2 above)
Comment (enen92) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c:104]: Nop, the closing } is at the end of this line

Comment (fuzzard) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c:104]: Ah yeah, maybe that's what's causing clang to do weird things, maybe bump the }, to the next line maybe

**Comment by enen92** [comment]
jenkins build this please

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c [hunk 3]
```diff
@@ -250,7 +268,21 @@ void ccmem_tobuf(cc_decoder_t *dec)
         if (buf->rows[i].cells[l].c != ' ')
           break;
       for (j = f; j <= l; j++)
-        dec->text[dec->textlen++] = buf->rows[i].cells[j].c;
+      {
+        const char* override =
+            charset_overrides[(int)buf->rows[i].cells[j].charset][(int)buf->rows[i].cells[j].c];
```
Comment (phunkyfish) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c:273]: Is it guaranteed that all other array locations will return NULL/nullptr? I'm not sure it is.

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c [hunk 4]
```diff
@@ -87,26 +78,52 @@ static int good_parity(uint16_t data)
...
- chartbl[0x60] = 0xAA;
- chartbl[0x7b] = 0xA7;
- chartbl[0x7c] = 0xb7;
- chartbl[0x7d] = 0x91;
- chartbl[0x7e] = 0xB1;
- chartbl[0x7f] = 0xA4;    /* FIXME: this should be a solid block */
-}
-
-static void ccbuf_add_char(cc_buffer_t *buf, uint8_t c)
+  CCSET_BASIC_AMERICAN,
```
Comment (phunkyfish) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c:85]: `CCSET_BASIC_AMERICAN = 0,`

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c [hunk 5]
```diff
@@ -87,26 +78,52 @@ static int good_parity(uint16_t data)
...
+  CCSET_SPECIAL_AMERICAN,
+};
+
+// from ffmpeg EIA-608 decoder
+// see https://en.wikipedia.org/wiki/EIA-608#Characters for reference
+static const char* charset_overrides[2][128] = {
+    [CCSET_BASIC_AMERICAN] =
```
Comment (phunkyfish) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c:92]: `[static_cast<int>(CCSET_BASIC_AMERICAN) =`

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c [hunk 6]
```diff
@@ -87,26 +78,52 @@ static int good_parity(uint16_t data)
...
+         [0x5c] = "\u00e9",
+         [0x5e] = "\u00ed",
+         [0x5f] = "\u00f3",
+         [0x60] = "\u00fa",
+         [0x7b] = "\u00e7",
+         [0x7c] = "\u00f7",
+         [0x7d] = "\u00d1",
+         [0x7e] = "\u00f1",
+         [0x7f] = "\u2588"},
+    [CCSET_SPECIAL_AMERICAN] =
```
Comment (phunkyfish) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/contrib/cc_decoder.c:105]: `[static_cast<int>(CCSET_SPECIAL_AMERICAN) =`

**Review by phunkyfish — CHANGES_REQUESTED** [review]

**Review by phunkyfish — APPROVED** [review]
Looks good, nice work. I think this is better than the original implementation ;)

**Comment by enen92** [comment]
Thanks phunkyfish for the help with the noobie questions :)
Force pushed to fix a comment (don't need another review). I'll merge once jenkins is happy.
