### PR TITLE
CAddonSettings: Prevent reference cycle with CAddon

### LINKED ISSUE #23786: xbmcaddon.Addon python binding memory leak after 21.0alpha2
### Describe the bug
Here is a clear and concise description of what the problem is:

A basic monitor addon fetching settings from xbmcaddon.Addon instance appears to leak memory, this was noticed on LE12 nightly using the Youtube Addon.  It's roughly ~500 bytes every 60 seconds, which the monitor loop in Youtube fires a self-check to it's HTTP service if MPEG-DASH is enabled.

https://github.com/anxdpanic/plugin.video.youtube/issues/520
https://forum.libreelec.tv/thread/27544-kodi-21-alpha-3-memory-leak/#post183963

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

No memory leak

## Actual Behavior

Below you can see PSS/Dirty bytes increasing out of pmap, eventually left alone this will result in an OOM kill of kodi.bin.

time,kbytes,pss,dirty,player status
2023-09-19 07:00:39,2824716,379729,297096,0,null
2023-09-19 07:00:49,2824716,381397,298764,0,null
2023-09-19 07:00:59,2824716,383069,300436,0,null
2023-09-19 07:01:10,2824680,384777,302144,0,null
2023-09-19 07:01:20,2824680,386449,303816,0,null
2023-09-19 07:01:30,2824608,388121,305488,0,null
2023-09-19 07:01:40,2824608,389961,307328,0,null
2023-09-19 07:01:50,2824608,391633,309000,0,null
2023-09-19 07:02:00,2824608,393305,310672,0,null

### To Reproduce

1. Running 21.0alpha3 (LE12 nightly)
2. Youtube addon is enabled, with MPEG-DASH enabled (or use basic monitor addon that is probing settings through Python binding)
3. Memory leak should be observable

### Debuglog

The debuglog can be found here:

### Screenshots 
Here are some links or screenshots to help explain the problem:

Not much here, other than me toggling enable/disable of this addon for getting the minimal reproducer:
http://ix.io/4GNy

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: LibreELEC 12 nightly
 - Kodi version: 21.0alpha3

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by neo1973**
## Description

#23558 added a reference cycle that causes memory leaks as reported in #23786.

The problem is that `CAddon::m_settings` contains `CSettingsData` objects which contains `CAddonSettings` obejcts. The shared_ptr `CAddonSettings::m_addon` creates a cycle that prevents the addon from getting freed.

This PR breaks the cycle by using a `std::weak_ptr` in `CSettingsData`. To prevent constant locking of the weak_ptr the commit e02c6f09b904d90749b3a7bf7453b5d456f99616 is reverted.

Fixes #23786.

## Motivation and context
See above.

## How has this been tested?
Checked with heaptrack that the leak is gone and with ASAN that there are no general memory problems

## What is the effect on users?
Kodi's memory usage doesn't increase indefinitely.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [X] All new and existing tests passed

### CODE REVIEW

File: xbmc/addons/settings/AddonSettings.cpp [hunk 1]
```diff
@@ -436,8 +436,12 @@ bool CAddonSettings::HasSettings() const
 
 bool CAddonSettings::Save()
 {
-  assert(m_addon);
-  return m_addon->SaveSettings();
+  auto addon = m_addon.lock();
+  assert(addon);
```
Comment (enen92) [inline xbmc/addons/settings/AddonSettings.cpp:440]: Shouldn't this be assert(m_addon)?

Comment (enen92) [reply xbmc/addons/settings/AddonSettings.cpp:440]: nevermind

**Review by enen92 — APPROVED** [review]
Thanks for looking into this

File: xbmc/addons/settings/AddonSettings.cpp [hunk 2]
```diff
@@ -438,8 +436,12 @@ bool CAddonSettings::HasSettings() const
 
 bool CAddonSettings::Save()
 {
-  assert(m_addon);
-  return m_addon->SaveSettings();
+  auto addon = m_addon.lock();
```
Comment (enen92) [inline xbmc/addons/settings/AddonSettings.cpp:439]: Do you think the usage of auto here is preferred over the shared_ptr usage? It might be trivial for someone experienced with c++ but in my case I had to look into the documentation.
Up to you.

Comment (neo1973) [reply xbmc/addons/settings/AddonSettings.cpp]: I agree. I normally try to use `auto` only if the the type is already stated somewhere else in the expression (e.g. a static_cast) which isn't the case here. Looks like I was feeling lazy today :smile:

**Comment by neo1973** [comment]
Jenkins build this please

**Comment by wagnerch** [comment]
Built this on top of LE12 nightly, and it looks good.  I was seeing a 500 byte leak every 10 seconds with YT add-on, and now it is steady overnight:
Time,Kbytes,PSS,Dirty,Swap (from pmap)
2023-10-04 04:00:59,2724080,225657,140964,0
... 2 hours later
2023-10-04 05:59:59,2724080,225664,140972,0

**Comment by neo1973** [comment]
Thank you @wagnerch for giving it a try 🙂
