### PR TITLE
Correct on-screen keyboard behaviour for Arabic characters

### LINKED ISSUE #16040: Arabic letters not connected when using virtual keyboard
### Describe the bug
Here is a clear and concise description of what the problem is:

There is an issue in the virtual keyboard in kodi when writing in Arabic, Arabic is a compound form language(the letters are connected rather than separated like in Latin), the problem is that the virtual keyboard doesn't connect the letters and instead they are written as isolated letters, the problem doesn't appear when writing using the physical keyboard.
This issue is very old and has been around since Kodi 16 I think  and still no fix
link to old thread that mentions the bug with screenshots:https://forum.kodi.tv/showthread.php?tid=246853
link to trac ticket: https://trac.kodi.tv/ticket/17703

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The letters should be written connected to each other

## Actual Behavior

Arabic letters are isolated

## Possible Fix

This quote from the forum thread linked above may help to find a fix:
> I think the problem here, is that the Arabic keyboard is using the wrong Arabic Unicode block. Instead of using [Arabic Presentation Forms-B](https://en.wikipedia.org/wiki/Arabic_Presentation_Forms-B), it should use the [standard Arabic block](https://en.wikipedia.org/wiki/Arabic_(Unicode_block)).

### To Reproduce

1. open kodi and go to the interface settings and add the Arabic QWERTY keyboard layout
2. go back to the home kodi page and click on the search icon and choose any type of search
3. change the layout to Arabic in the virtual keyboard and try writing an arabic word like "اللغه العربيه"

### Debuglog

The debuglog can be found here:
not applicable since the problem doesn't produce any debug log entries

### Screenshots 
Here are some links or screenshots to help explain the problem:

- This is what it looks like when writing "اللغه العربيه" using virtual keyboard (signifies the problem):
https://i.imgur.com/xUJxlgLl.png
- This is what it looks when writing the same words using the physical keyboard(this is the correct form): 
https://i.imgur.com/XzIDAell.png

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 18.1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by AhmedAdelAbouzeid**
### Description of changes and context
1- Prevent Arabic characters from being dis-joined when using the on-screen keyboard
2- Prevent the flipping of existing Arabic text when editing (ex. renaming something) using the on-screen keyboard

Both the above points are cleared by turning off character flipping in calls to utf8ToW charset conversion function for ACTION_INPUT_TEXT and GUI_MSG_SET_TEXT (SetLabel2 function)

This fixes #16040

### How Has This Been Tested?
The changes were tested using Kodi on Windows 10 x64 (1909)
The on-screen keyboard was tested using a RTL language (Arabic) and a LTR language (English) and behave correctly for both languages after the changes. Kodi's interface language was alternated between Arabic and English during the test and didn't affect the results.

### Screenshots
kodi_KB_AR_Issue

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Review by phunkyfish — CHANGES_REQUESTED** [review]
@AhmedAdelAbouzeid can you please prefix the commit message with what the change does. I.e. a speaking description.

Other than that it looks good to me, will also ask one of the skin guys.

**Comment by phunkyfish** [comment]
@ronie this looks reasonable.

**Comment by ronie** [comment]
screenshots look nice, but i have no idea what the code changes do.
this is far out of my league :-)

**Comment by phunkyfish** [comment]
> screenshots look nice, but i have no idea what the code changes do.
> this is far out of my league :-)

No worries, thanks for taking a look.

**Comment by phunkyfish** [comment]
@MilhouseVH can we put this in a testbuild and see if any side effects are reported?

**Comment by MilhouseVH** [comment]
Will do, should be in tonight's `#0419` build.

**Comment by AhmedAdelAbouzeid** [comment]
Thanks for reviewing. I changed the commit message's title.

The code changes are limited to the edit control and only affect RTL languages. The changes ultimately bypass calls to FriBiDi which doesn't do anything to LTR languages anyway unless they are mixed with RTL languages in the same line.

I will test these cases (mixed RTL/LTR) and text including numerical values and signs later today.

**Comment by phunkyfish** [comment]
Thanks @AhmedAdelAbouzeid

**Comment by AhmedAdelAbouzeid** [comment]
I tested the keyboard with mixed RTL/LTR languages, numbers and signs and found no issues with characters getting separated nor reversed.

While testing I noticed that if the cursor is placed in the middle of an Arabic word, the characters to the left of the cursor are moved to the start of the word while the cursor is in its hidden state and then the characters return to their correct position again when the cursor is visible. This is easily fixed by modifying the character used to indicate the hidden cursor state to a simple space or null character.

Is it OK to add a commit for this to the pull request ?
Kodi_KB_AR_CR

**Comment by phunkyfish** [comment]
Yes of course. Please add the commit.

**Comment by AhmedAdelAbouzeid** [comment]
I will work on adjusting the arrow buttons as the cursor movement inside RTL text is reversed (clicking the left arrow moves the cursor right and vice versa). The code for the buttons' actions currently manipulate the cursor index without checking the text direction first.
The Arabic keyboard is fairly usable now though, I hope other changes can be done in a new PR.

**Comment by phunkyfish** [comment]
Yes, i think other changes in a new PR is fine.

Let's just check with @MilhouseVH if there is any feedback on this PR. Otherwise we can push it in.

File: xbmc/guilib/GUIEditControl.cpp [hunk 1]
```diff
@@ -565,7 +565,7 @@ bool CGUIEditControl::SetStyledText(const std::wstring &text)
   // show the cursor
   unsigned int ch = L'|';
   if ((++m_cursorBlink % 64) > 32)
-    ch |= (3 << 16);
+    ch = L' ';
```
Comment (phunkyfish) [inline xbmc/guilib/GUIEditControl.cpp:568]: Can you explain this change?

**Comment by MilhouseVH** [comment]
No feedback so far (none good, none bad). All I can say with any certainty is that it doesn't appear to have broken anything!

**Comment by phunkyfish** [comment]
That will do, thanks!

File: xbmc/guilib/GUIEditControl.cpp (hunk 1 above)
Comment (AhmedAdelAbouzeid) [reply xbmc/guilib/GUIEditControl.cpp:568]: For the blinking effect, the cursor will alternate between '|' and ' ' (simple space - 0x20) instead of between '|' and '𰁼' (It does look like a space in some fonts - 0x3007C)

The '𰁼' while looking like a space (or a double space), seem to reverse Arabic words around it even in word processors (If the paragraph direction is LTR).

Space VS 0x3007C

Comment (phunkyfish) [reply xbmc/guilib/GUIEditControl.cpp:568]: Great, thanks. Your explanation makes sense.

Although I’m not sure I understand why that was chosen for the original code! A mystery.

**Review by phunkyfish — APPROVED** [review]
LGTM

**Comment by phunkyfish** [comment]
Thanks @AhmedAdelAbouzeid for the contribution!

**Comment by phunkyfish** [comment]
@AhmedAdelAbouzeid 

I think I found out why that special character was used for a space. Without it if you change a text setting the text will move left/right on each blink.

Is it possible to only use a real space for arabic and similar languages and use the old character otherwise?

**Comment by AhmedAdelAbouzeid** [comment]
This is because the character width for ' ' and '|' may be different depending on the used font; for Arial they have the same width but this is not the case for the default font.
Using a figure space (U+2007) instead of basic space eliminates text movement for the default font but causes movement when using Arial.

I will work at solving this hopefully without going for language-specific nor font-specific solutions.

**Comment by phunkyfish** [comment]
Amazing, thanks!

**Comment by AhmedAdelAbouzeid** [comment]
PR #17790 solves the above issue, please check it. Thanks!
