### PR TITLE
Fix skin element "toggle button"

### LINKED ISSUE #25279: ToggleButton usealttexture not rendering control
### Describe the bug
Here is a clear and concise description of what the problem is:

On latest master nightlies, togglebutton controls with `<usealttexture>True</usealttexture>` are not rendering.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The usealttexture should toggle the togglebutton between rendering its main texture state and its alttexture states.

## Actual Behavior

In the alttexture state the togglebutton simply is not rendered

### To Reproduce

Create a togglebutton in Estuary at the end of the Home.xml like so

```
<control type="togglebutton">
	<visible>True</visible>
	<label>TOGGLEBUTTON Main Label</label>
	<altlabel>TOGGLEBUTTON Alt Label</altlabel>
	<align>center</align>
	<aligny>center</aligny>
	<usealttexture>False</usealttexture>
	<height>300</height>
	<width>700</width>
	<centerleft>50%</centerleft>
</control>
```

See that it renders correctly with usealttexture set to `False`. 

Switch usealttexture to `True` and reload skin to note that the togglebutton does not render at all (no font or texture). However, it is still clickable and will leave an appropriate space in a grouplist.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/upegevibad.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

Toggle button in False state (use main textures) - displays correctly:

screenshot00574

Toggle button in True state (use alt textures) - doesn't display (it should display like above but with the alt label instead).

screenshot00575

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Initially reported in this issue thread for my skin: https://github.com/jurialmunkey/skin.arctic.fuse/issues/926

However, as demonstrated above, can also be reproduced easily in Estuary, so it is not skin specific.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: 22.0-ALPHA1 (21.90.700) Git:20240529-c0a22c9e22

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by sarbes**
## Description
The PR (hopefully) fixes issue https://github.com/xbmc/xbmc/issues/25279 where alt label/textures of toggle buttons would not render.

## Motivation and context
The scissor cull PR (https://github.com/xbmc/xbmc/pull/23022) seems to uncover some hidden bugs. I'm pretty sure we have had issues with dirty region rendering for this element, which now crops up as them not rendering at all. There might be more.

## How has this been tested?
Barely. I do have a makeshift debug skin where I can kinda reproduce the issue and the fix.

## What is the effect on users?
Correct rendering of toggle buttons.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

File: xbmc/guilib/GUIToggleButtonControl.cpp [hunk 1]
```diff
@@ -11,6 +11,7 @@
 #include "GUIDialog.h"
 #include "GUIInfoManager.h"
 #include "GUIWindowManager.h"
+#include "guilib/GUIControl.h"
```
Comment (ksooo) [inline xbmc/guilib/GUIToggleButtonControl.cpp:14]: Is this include really needed?

Comment (garbear) [reply xbmc/guilib/GUIToggleButtonControl.cpp:14]: I would say no, as this class derives from CGUIControl which must include GUIControl.h in the header. (https://github.com/xbmc/xbmc/blob/b9e4a3438cfb8b07c9c80d0c5f8c80c4f48dabf7/xbmc/guilib/GUIButtonControl.h#L17)

Comment (sarbes) [reply xbmc/guilib/GUIToggleButtonControl.cpp:14]: Man, you guys are quick. VS inserted that for me (:

**Review by howie-f — DISMISSED** [review]
runtime tested (removed the include) and it fixes the issue.
:+1: thanks

File: xbmc/guilib/GUIToggleButtonControl.cpp [hunk 2]
```diff
@@ -38,6 +39,7 @@ void CGUIToggleButtonControl::Process(unsigned int currentTime, CDirtyRegionList
     m_selectButton.SetPulseOnSelect(m_pulseOnSelect);
     ProcessToggle(currentTime);
     m_selectButton.DoProcess(currentTime, dirtyregions);
+    CGUIControl::Process(currentTime, dirtyregions);
```
Comment (howie-f) [inline xbmc/guilib/GUIToggleButtonControl.cpp:42]: no clue about `guilib` :) but is `CGUIControl::Process()` the correct call?
i have tested this one

```suggestion
    CGUIButtonControl::Process(currentTime, dirtyregions);
```

which also seems to fix the issue at a first glance.
it would also allow to simply remove the `else` then??

**Comment by sarbes** [comment]
@howie-f I've redone some parts, to make it cleaner (so it seems to me). 

Previously, the "base" button did the state tracking, with the secondary button polling info each frame.

Now, both get state changes via the setters. Only the active one needs to be processed. Actions are still managed by the "base" button. This should also be faster.

I don't have no means to test it thoroughly, maybe @jurialmunkey can chime in.

**Comment by jurialmunkey** [comment]
Using the testbuild I now appear to have the opposite issue. When `<usealttexture>True</usealttexture>` the toggle button is *always* rendered even if `<visible>False</visible>`.

Also, it appears that `<width>auto</width>` is no longer respected.

I'm using togglebutton here in a grouplist:.

You can see that it is visible when it shouldn't be (it only has visible on focus of a hidden list). Also the previous label (which should now be hidden) is still visible behind it. In the second screenshot you can see that when it is visible, the autowidth is not calculated correctly.

I'll try to make up a test case for Estuary for you.

screenshot00581


screenshot00577

**Comment by jurialmunkey** [comment]
Here's a gist with test window for Estuary `ActivateWindow(1111)`

https://gist.github.com/jurialmunkey/44c7c86219ecd65c7e64b34dc0d46f68#file-custom_1111_testcase-xml

It has a grouplist with autowidth togglebutton and three labels autowidth. You can also see issues with autowidth labels using textoffsetx values not being calculated correctly either.

The four buttons switch whether ToggleButton is visible=true|false and usealttexture=true|false

If toggle button is hidden, a label is shown instead.

Visible+Main = Magenta togglebutton label
Visible+Alt = Cyan togglebutton label
Hidden = LimeGreen standard label control

**Comment by OfficerKD637** [comment]
@sarbes Please see this https://github.com/xbmc/xbmc/issues/25279#issuecomment-2181703827 
It seems this works but with swapped textures and reversed condition?

**Comment by sarbes** [comment]
@jurialmunkey could you test the PR in this state? I've reduced the changes to a minimum.

**Comment by jurialmunkey** [comment]
> @jurialmunkey could you test the PR in this state? I've reduced the changes to a minimum.

@sarbes - Seems to be working well now as far as I can tell. I couldn't see any unusual/unexpected behaviour using the test dialog or my own skin.

FYI for anyone else wanting to test - Windows 64bit testbuild is here:
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20240816-fedc8c49-toggle-fix-x64.exe

**Comment by sarbes** [comment]
jenkins build this please
