### PR TITLE
[VideoPlayer] Fixed: Infinite video halt when cache is full & valid

### LINKED ISSUE #23752: Kodi halts auto-playback after cache fills 100%
### Describe the bug

I will be describing two issues in this post which are likely related to each other.

When an internet media stream can not to be played by Kodi in real-time it pauses the video and starts filling up the cache. Once the cache has been filled to 100% the notification is shown to the user, "Rate too slow for continuous playback" and playback starts normally again.

Now, the two issues:
1. When the playback starts again, for some videos, the cache doesn't like to fill up at the same time while it's being read from.
2. When the playback stops again due to cache exhaustion, the cache starts filling up only after ~5 secs and even after the cache has been completely filled to a 100%, Kodi won't resume playback of the video as it should, rather the user has to hit pause and play again to continue watching the stream, but that isn't enough, because for the whole rest of the stream, Kodi won't autoplay the video after all the times that the cache keeps getting exhausted and refilled back to 100%.

## Why this is not an internet bandwidth issue:
- Avatar 2 UHD remux which is a 100GB+ mkv file plays just fine, and only pauses once to fill-up the cache.
- Dungeons & Dragons UHD remux which 80GB+ mkv file plays fine, and only pauses once to fill-up the cache.
- The Batman (2022) UHD remux which is ~90GB mkv file plays fine, and only pauses once to fill-up the cache.

In all the above cases, the cache keeps getting replenished as it is being read from and the whole movie plays without stutters.

However, for this one particular video Kodi doesn't replenish the cache at the same time as it is being read from.
- Dead Heat (1988) UHD remux - 56GB

#### For issue 1:
An unusual remedy suggested in https://github.com/xbmc/xbmc/issues/19785 by @MrNo00 i.e., to enable debug logging for FFMPEG component, fixes cache not filling up issue for most of the problematic streams (but not for all).
#### For issue 2:
None

#### For issue #1:
1. Throttle your internet speed between 15-20MB/s
2. On a clean install of Kodi modify advanced cache settings to accommodate:
    - buffermode = 1
    - 100MB ≥ memorysize≤ 300MB
    - 1 ≥ readfactor ≤ 99 
3. Play Dead Heat (1988) UHD remux via http streaming

#### For issue #2:
1. Throttle internet speed to lower than the actual video bitrate (if video requires 15MB/s, then you should limit Kodi to use 5-10MB/s)
2. On a clean install of Kodi modify advanced cache settings to accommodate:
    - buffermode = 1
    - 100MB ≥ memorysize≤ 300MB
3. Try playing any high-bitrate video via http streaming
4. Press `Ctrl`+`Shift`+`O` to check cache-fill info
5. Wait for kodi to show, "Rate too slow for continuous playback" message
6. Kodi will only autoplay the video the first time cache has been fully filled and will completely give up on autoplaying the video nomatter the cache fill percentage.

### Platforms thoroughly tested where this issue incontrovertibly exists:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Windows 10 - Kodi version: 20.2.0
Ubuntu 20.04 - Kodi Version: 20.2.0
Android 9 - Kodi version: 20.2.0

image

### PR DESCRIPTION
**Pull request by honest-mule**
\+ added SCacheStatus parameters to GetGeneralInfo()

## Description

- The function `HandlePlaySpeed()` in `CVideoPlayer` class has been added with a multi-conditional clause to account for resuming playback when cache is at it's appropriate level.
If the user the has set `cache->memorysize` in their `advancedsettings.xml` then it will be used for basic gauging purposes.
- The function `GetGeneralInfo()` has been modified to keep track of `SCacheStatus` parameters for debug purposes.

## Motivation and context

In the quest to enhance Kodi's performance and reliability, I've identified and addressed a specific bug that affects users with low-speed network connections. This issue is quite intricate and impacts the initial caching process during video playback.

Here's the crux of the problem: When the cache initially reaches its full capacity and Kodi notifies the user that the `rate is too slow for continuous playback`, the video stutters momentarily but then plays back normally utilizing the cache as it should. Once the cache gets depleted, it unexpectedly results in video playback stalling, even after the cache returns to its 100% capacity, the VideoPlayer fails to resume the video.

The motivation behind this pull request is to highlight Kodi's commitment to providing a seamless streaming experience for all Kodi users, irrespective of their network speed. By resolving this bug, I aim to ensure that video playback remains uninterrupted as long as cache reserve is at its appropriate level, offering a smoother and more enjoyable viewing experience, even under challenging network conditions.

I look forward to your feedback and collaboration.

## How has this been tested?

The fix has been tested in emulated & real-time environment.
Low-speed internet connection doesn't lead to an infinite halt of video playback anymore.

## What is the effect on users?

Cache-oriented smooth playback as per either user's cache memory settings or Kodi's default settings. 

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 1]
```diff
@@ -1854,10 +1854,19 @@ CacheInfo CVideoPlayer::GetCachingTimes()
 
 void CVideoPlayer::HandlePlaySpeed()
 {
+  auto cacheIdealSize = CServiceBroker::GetSettingsComponent()->GetAdvancedSettings()->m_cacheMemSize;
```
Comment (ksooo) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:1857]: I would not use `auto` for a trivial type, but this is juts personal taste.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 2]
```diff
@@ -1854,10 +1854,19 @@ CacheInfo CVideoPlayer::GetCachingTimes()
...
+  bool cacheToMemory = !!cacheIdealSize;
```
Comment (ksooo) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:1858]: 1. `const bool` to make clear to the reader that you will not change the value anymore after first assignment.
2. I know very well the meaning of `!!`to convert a numeric value to a bool, but don't consider it good style. Looks cute, but many people out there do not understand this and I have even seen people treating this a typo suggesting to remove one of the exclamation marks. This "confusion" can easily avoided by not using such "tricks".

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 3]
```diff
@@ -1854,10 +1854,19 @@ CacheInfo CVideoPlayer::GetCachingTimes()
...
   const bool isInMenu = IsInMenuInternal();
   const bool tolerateStall =
       isInMenu || (m_CurrentVideo.hint.flags & StreamFlags::FLAG_STILL_IMAGES);
 
+  // if our cache has filled to almost full it's play time
+  if (!tolerateStall && (m_VideoPlayerAudio->IsStalled() || m_VideoPlayerVideo->IsStalled()) &&
+    cacheToMemory && m_State.cache_bytes > cacheIdealSize * 0.65 && m_syncTimer.IsTimePast())
```
Comment (ksooo) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:1865]: You may want to consider to evaluate terms from cheap to expensive, please. 

```c++
if (!tolarateStall && cacheToMemory && ...
```

**Review by ksooo — COMMENTED** [review]
Cannot say anything about functional correctness of the change. Just some stylistic comments from my end.

**Comment by honest-mule** [comment]
All suggestions have been duly noted and respective changes made to the code. Thanks! @ksooo

**Comment by ksooo** [comment]
@FernetMenta do you have any thoughts on this fix?

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 4]
```diff
@@ -3299,6 +3309,15 @@ void CVideoPlayer::GetGeneralInfo(std::string& strGeneralInfo)
         strBuf += StringUtils::Format(" {} msec", DVD_TIME_TO_MSEC(m_State.cache_delay));
     }
 
+    XFILE::SCacheStatus status;
+    if (m_pInputStream->GetCacheStatus(&status))
+    {
+      strBuf +=
+          StringUtils::Format("\nCurrent rate: {}/s", StringUtils::SizeToString(status.currate));
+      strBuf += StringUtils::Format(", low: {}/s", StringUtils::SizeToString(status.lowrate));
+      strBuf += StringUtils::Format(", max: {}/s", StringUtils::SizeToString(status.maxrate));
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:3318]: `StringUtils::SizeToString` is for size units (MB megabytes) and bitrate units are probably Mbit/s

For it to make sense, the sum of the video bitrate + audio bitrate should be similar to the cache bitrate (or file reading rate if FileCache is not used).

Note that video and audio bitrates are displayed in the the first lines of debug OSD (aq, vq) and are expressed in Mb/s and Kb/s (Mbits/s and Kbits/s).

**Review by thexai — COMMENTED** [review]
I'm not saying that the fix is not necessary but I see several things that are wrong:

**Comment by FernetMenta** [comment]
> @FernetMenta do you have any thoughts on this fix?

I never liked the dependency of VP to FileCache. So far this was only for displaying some cache related info for what reason ever. I would not make behaviour of VP dependent on FileCache.

**Comment by honest-mule** [comment]
@thexai @FernetMenta thanks for your very informational input, guys!

I will be further working on this to improve the relationship between VideoPlayer & Caching modules. Hopefully, good things will come out of this!

Humbly request to whomever is responsible to not close this as such.

**Comment by honest-mule** [comment]
@thexai @FernetMenta I believe the latest commit should be it.

The actual fault was in `FileCache.cpp` file where `m_bFilling` bool flag wasn't being reset after `m_writeRateLowSpeed` was being reset - and since they go hand-in-hand, it was leading to the infinite video halt.

Fixing the above meant the user being shown `rate too low for continuous playback` notification every single time the cache gets filled to 100% & the video resumes.

Thus, the line `#1873` in `VideoPlayer.cpp` had to be commented out for now:
```cpp
CGUIDialogKaiToast::QueueNotification(g_localizeStrings.Get(21454), g_localizeStrings.Get(21455));
```
The ideal situation for this toast to be appropriate would be when `VideoPlayer` only shows it the first time to the user when lowrate is encountered, with only exceptions being further manual seek events.
Since people might unknowingly activate the notification again in the future, a todo info comment has also been added just above the line to ensure intent.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 5]
```diff
@@ -1854,10 +1854,20 @@ CacheInfo CVideoPlayer::GetCachingTimes()
 
 void CVideoPlayer::HandlePlaySpeed()
 {
+  auto cacheIdealSize =
+      CServiceBroker::GetSettingsComponent()->GetAdvancedSettings()->m_cacheMemSize;
```
[the remark this answers is not in the document]
Comment (honest-mule) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp]: Commit reverted so this is not of cause anymore.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 6]
```diff
@@ -3299,6 +3309,15 @@ void CVideoPlayer::GetGeneralInfo(std::string& strGeneralInfo)
         strBuf += StringUtils::Format(" {} msec", DVD_TIME_TO_MSEC(m_State.cache_delay));
     }
 
+    XFILE::SCacheStatus status;
+    if (m_pInputStream->GetCacheStatus(&status))
+    {
+      strBuf +=
+          StringUtils::Format("\nCurrent rate: {}/s", StringUtils::SizeToString(status.currate));
```
[the remark this answers is not in the document]
Comment (honest-mule) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp]: Will have to do this in another pull-request, given that this was supposed to be a quick fix.

The concerning code has been removed.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 4 above)
Comment (honest-mule) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp]: Concerning code has been removed.

File: xbmc/filesystem/FileCache.cpp [hunk 7]
```diff
@@ -598,6 +598,7 @@ int CFileCache::IoControl(EIoControl request, void* param)
     status->currate = m_writeRateActual;
     status->lowrate = m_writeRateLowSpeed;
     m_writeRateLowSpeed = 0; // Reset low speed condition
+    m_bFilling = true;
```
Comment (arnova) [inline xbmc/filesystem/FileCache.cpp:601]: IMO this is the wrong fix. m_bFilling is to determine whether we started filling up from 0% to allow proper detection of low-speed conditions inside(!) CFileCache. Reading cache-status doesn't eg. reset cache so we shouldn't reset m_bFilling here either.

Like @FernetMenta says: probably the dependency from CVideoPlayer on CFileCache needs to go (if possible?). It has been there for ages and they never played nice. I tried fixing the "low-speed-logic" several times but to be honest I never completely understood the depending logic in CVideoPlayer...

please note the comment I once added in CFileCache:
   /* NOTE: We can only reliably test for low speed condition, when the cache is *really*
    * filling. This is because as soon as it's full the average-
    * rate will become approximately the current-rate which can flag false
    * low read-rate conditions.
    */

Comment (honest-mule) [reply xbmc/filesystem/FileCache.cpp:601]: I sincerely hope you are not suggesting users with low-speed internet should live with the video playback halting indefinitely until a "proper" fix is implemented.

In my humble opinion, this commit (nomatter it being the "wrong" fix) immediately relieves the user of ever having to face a stuck video situation which should be of a greater priority than leaving the users waiting for an extended period of time for an overhaul to the cache-videoplayer relationship.

I also hope you do not take me in the wrong way here, your explanation has been immensely helpful in making me understand why the code is the way it is, which only means my brain will keep hunting for the right answers! Haha

But as reasonable people here we ought to accept fixes for broken things while we keep doing what's best to make things better in the background without making end-users notice such obvious breakage.

Comment (arnova) [reply xbmc/filesystem/FileCache.cpp:601]: > I sincerely hope you are not suggesting users with low-speed internet should live with the video playback halting indefinitely until a "proper" fix is implemented.
> 
> In my humble opinion, this commit (nomatter it being the "wrong" fix) immediately relieves the user of ever having to face a stuck video situation which should be of a greater priority than leaving the users waiting for an extended period of time for an overhaul to the cache-videoplayer relationship.
> 
> I also hope you do not take me in the wrong way here, your explanation has been immensely helpful in making me understand why the code is the way it is, which only means my brain will keep hunting for the right answers! Haha
> 
> But as reasonable people here we ought to accept fixes for broken things while we keep doing what's best to make things better in the background without making end-users notice such obvious breakage.

I understand your frustrating but the proposed changes are simply not acceptable as it will break existing correct logic. So it *may* fix your issue but it may introduce new regressions we're not aware of. If you want to introduce a workaround/hack it must probably be done in VP, not CFileCache.

**Comment by arnova** [comment]
I think the actual problem that's triggering your issue is the fact that the level is set to -1 in GetCachingTimes() when low-speed conditions are hit. Perhaps introduce an additional bool in CacheInfo to allow passing proper level, even with low-speed conditions (and use the bool where appropriate)? @FernetMenta probably has a better understanding of the logic low-speed logic and how it should "work"?

**Comment by honest-mule** [comment]
@arnova As per your suggestions, the fix has been re-introduced by adding relevant bool flags in some of the video/file cache-status structs.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 8]
```diff
@@ -1840,14 +1840,16 @@ CacheInfo CVideoPlayer::GetCachingTimes()
   info.delay = cache_left - play_left;
   info.time = cache_time;
 
-  if (lowrate > 0)
+  if (lowrate > 0 || cacheIsFull)
```
Comment (arnova) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp:1843]: I pretty sure this is wrong. This means that every time the cache is full, which is a normal/valid condition, the block below is triggered. Mind explaining your reasoning?

**Comment by FernetMenta** [comment]
@honest-mule have you tried just to remove the existing logic that depends on FileCache from VP? I don't think the state of FileCache should have any impact on bahaviour of VideoPlayer.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp (hunk 8 above)
Comment (honest-mule) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp:1843]: Just below this line, there's a comment:
```cpp
1847  // buffer is full & our read rate is too low
1848  CLog::Log(LOGDEBUG, "Readrate {} was too low with {} required", lowrate, maxrate);
```
Going by this comment's sentiment, `lowrate` actually means that we're not reading from it fast enough, which will be true all the times that the cache gets to full. If I remove this then the video will halt from the second time onwards when the cache gets to full and the problem remains as it is.

**Comment by honest-mule** [comment]
@FernetMenta Might as well, soon as I get some free time in my hands. Would be a nice & fun experiment, tbh!

**Comment by thexai** [comment]
Cache level calculation is wrong and in some cases is 0 when cache level is 100%. This is similar to https://github.com/xbmc/xbmc/pull/22881 (the root cause is the same, but I don't understand how this level is calculated) 

As now exist `cache.time` variable can be used as replacement. 8s is queue time, then >8 means queue is at 100% and cache start filling. This should fix related issue (infinite halt).

@honest-mule test this change:

```diff
diff --git a/xbmc/cores/VideoPlayer/VideoPlayer.cpp b/xbmc/cores/VideoPlayer/VideoPlayer.cpp
index 72419823d8..64fea25605 100644
--- a/xbmc/cores/VideoPlayer/VideoPlayer.cpp
+++ b/xbmc/cores/VideoPlayer/VideoPlayer.cpp
@@ -1871,7 +1871,7 @@ void CVideoPlayer::HandlePlaySpeed()
         CGUIDialogKaiToast::QueueNotification(g_localizeStrings.Get(21454), g_localizeStrings.Get(21455));
         SetCaching(CACHESTATE_INIT);
       }
-      if (cache.level >= 1.0)
+      if (cache.time > 8.0)
         SetCaching(CACHESTATE_INIT);
     }
     else

```

**Comment by honest-mule** [comment]
@thexai I agree wholeheartedly.

image

In my opinion the cache level should always be between `0-100%`. This way all player-related elements can work intelligently & predictably knowing the obvious min-max levels of cache. For ex: the video buffer gauging meter, which as of now, does not help predict when the video playback will resume, if at all...

Thus, the calculation in line 1850 this is wrong:
```c++
1850  info.level = (cached + queued) / (cache_need + queued);
```

--

The change you suggested, of course, gets rid of video halting issue but introduces another predicament where the cache is never allowed to fill to a 100%. Meaning, the video playback stops every 8 seconds and then waits until the next 8 seconds of playback is available.

**Comment by thexai** [comment]
>  but introduces another predicament where the cache is never allowed to fill to a 100%. Meaning, the video playback stops every 8 seconds and then waits until the next 8 seconds of playback is available.

This is not true: I tested proposed change and cache still used same as before:

osd

As commented VideoPlayer queue allows 8 seconds of playback and the rest from 8 to 14s is due FileCache.

In the capture cache has 7.44 MB that is the default without advanced settings, then is used 100% (same as before).

You a confused with "cache level required to start playback after cache dry" That doesn't have to be 100% and in fact it usually isn't. The logical strategy is to fill the cache to 100% only when start playback, but if due to an (unusual) event it is accidentally emptied during playback, you want to resume playback as soon as possible and therefore not wait to fill the cache to 100%. A usual percentage could be 20 or 30%. Since VideoPlayer queue already has 8s of data is fine even start playback with 0% of cache. 

It is assumed that the bandwidth of the connection on average is higher than the bit rate of the stream and therefore the cache will recover slowly (and there is also 8 seconds of margin for it to do so).

If the bandwidth of the connection is less than the bit rate of the stream it will never work well, neither with cache nor without cache. The cache only covers very temporary events and high latency issues.

Current trigger condition is `cache.level >= 1.0` and the equivalent is `cache.time > 8.0` 

If the condition was cache at 100% then it would be `cache.level >= 100`.

Conclusion: proposed change fixes the issue without changing the current operating mode.

**Comment by thexai** [comment]
Also reproduced and confirmed original issue limiting NAS bandwidth to ~80 Mbit/s and playing high bitrate 4K video files

nas

Confirmed two things:

1. Issue reproduced --> https://github.com/xbmc/xbmc/issues/23752
2. Confirmed that change `cache.time > 8.0` fixes the issue.

**Comment by honest-mule** [comment]
@thexai Your explanation makes it transparent that indeed, VideoPlayer should have to wait only 8 seconds before it starts playing from cache again and I concur my logic was flawed thinking the cache isn't filling up to a 100%.

Most likely this should be the fix. I just have apprehensions if the logic is calculating the seconds of footage in cache correctly. Did you ran any tests for that?

https://github.com/xbmc/xbmc/assets/143326476/e87076af-24ca-4e7a-b77e-04e021da5e1d

**Comment by thexai** [comment]
> VideoPlayer should have to wait only 8 seconds before it starts playing from cache again

No. You still not understand this :)

VideoPlayer should have to wait queue filled 100% and this allows 8 seconds of play. But is not need necessarily 8 s. to fill queue: this time depends on bandwidth of connection. 

But you are run in extreme case in which bandwidth is extremely limited and then read rate is only 1x or even 0.9x stream bit rate then in this special case (only) YES, you need 8 s. to read data of 8 s. of playback.

**Comment by honest-mule** [comment]
> VideoPlayer should have to wait only 8 seconds before it starts playing from cache again

Yes, forgive me for the poor phrasing. What I meant was VideoPlayer should only have to wait for 8 seconds of footage in cache before it starts playing from cache again.

I suppose we can close this and I believe you'll be pushing the fix from your endpoint! Cheers 🍻

**Comment by thexai** [comment]
> I suppose we can close this and I believe you'll be pushing the fix from your endpoint!

You can do it in this PR, simply remove all other changes and left only:

```diff
diff --git a/xbmc/cores/VideoPlayer/VideoPlayer.cpp b/xbmc/cores/VideoPlayer/VideoPlayer.cpp
index 72419823d8..64fea25605 100644
--- a/xbmc/cores/VideoPlayer/VideoPlayer.cpp
+++ b/xbmc/cores/VideoPlayer/VideoPlayer.cpp
@@ -1871,7 +1871,7 @@ void CVideoPlayer::HandlePlaySpeed()
         CGUIDialogKaiToast::QueueNotification(g_localizeStrings.Get(21454), g_localizeStrings.Get(21455));
         SetCaching(CACHESTATE_INIT);
       }
-      if (cache.level >= 1.0)
+      if (cache.time > 8.0)
         SetCaching(CACHESTATE_INIT);
     }
     else
```

**Comment by honest-mule** [comment]
@thexai Done!

**Comment by fritsch** [comment]
Please rebase and squash: https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec <- like presented here as a howto.

What I can already tell you is, that there is a behaviour change. For people using very large caches, that want to wait for playback start until this is full, it will now start after VideoPlayer has 8 seconds and first byte landed into the additional cache. Just saying - from my local tests -  with wifi, this change works great and is most likely better than the original implementation that - as documented in this thread - no one understands anymore.

**Comment by thexai** [comment]
For commit name is fine use some like PR name:

`[VideoPlayer] Fixed: Infinite video halt when cache is full & valid`

and please add a comment in second line like:

The reason is 'cache.level' variable some times is 0 when cache is full due the way is calculated. Replaced with 'cache.time' that not has these problems.

**Comment by honest-mule** [comment]
@fritsch I've done it, hope it's correct.

Looks like this at my end:
image

**Comment by fritsch** [comment]
Sadly not. As long as you see more than one commit in this web view, 66 now for your PR, it did not work.

**Comment by honest-mule** [comment]
What do you suggest, another rebase attempt or a new PR?

**Comment by thexai** [comment]
From your source folder:

`git reset --hard 1f4ee051090a27f0f37348e8229bdce271ba7036`

To start from scratch

**Comment by fritsch** [comment]
Here is a small howto:
Needs to be one once:
git remote add xbmc-upstream https://github.com/xbmc/xbmc.git
git remote add myself https://github.com/honest-mule/xbmc.git

Doing every time, when rebasing, being on the branch, you want to rebase:
git fetch xbmc-upstream
git rebase -i xbmc-upstream/master

Here now select all the commits, you want to "put" on top. In your case, it's exactly one.

Now - force push to yourself:
git push -f myself The_Name_Of_My_Branch

Good luck with that. But it's important to learn it now, as some changes will follow, e.g. 8.0 being a constant falling from heaving, which we make constexpr later on.

**Comment by honest-mule** [comment]
@fritsch Is this correct?

**Comment by fritsch** [comment]
Yes - you did it correctly.

**Comment by arnova** [comment]
I think it would also still be an improved if we would add an additional (bool) member to CacheInfo to flag low-speed conditions instead of setting level to -1.0. That way CVideoPlayer::GetCachingTimes() can always return proper level AND flag low-speed conditions at the same time. This has always felt a bit akward.

**Comment by thexai** [comment]
Current issue is when level is not -1 precisely. The level calculation bug is for positive values so changing this would not solve this problem.

Anyway, is supposed that when is produced "low speed condition" cache is not filled because connection bandwidth is less than required stream bitrate, then level is ~0 and is not need calculate (seems fine use -1 to signal this condition).

**Comment by honest-mule** [comment]
@fritsch made a great point which no one has picked on yet:
>What I can already tell you is, that there is a behaviour change. For people using very large caches, that want to wait for playback start until this is full, it will now start after VideoPlayer has 8 seconds and first byte landed into the additional cache.

This can only be resolved by adding new user-flags to `advancedsettings.xml` which when set should make the player only playback the video when either the cache is 100% full or there's no more file left to read from.

**Comment by fritsch** [comment]
Maybe or based if user has a cache related advanced setting or not. My point is: the usecase to load 200 or 300 MB into a cache so that consequent Playback of the 600M file would work with an ISDN 56kbit/s Connection is most likely a usecase from the past anyways. If not, it should not break ordinary Joe's playback cause we have forgotten how to properly calculate level internally ;-)

From my pov: cache handling needs huge overhaul in general, the change here makes it at least understandable by using time based judgement. Curious though if it breaks other things that worked by luck. We will find out.

**Review by thexai — APPROVED** [review]
As this fixes a real issue let's merge it and leave others changes/improvements for future

**Comment by arnova** [comment]
> Current issue is when level is not -1 precisely. The level calculation bug is for positive values so changing this would not solve this problem.
> 
> Anyway, is supposed that when is produced "low speed condition" cache is not filled because connection bandwidth is less than required stream bitrate, then level is ~0 and is not need calculate (seems fine use -1 to signal this condition).

Ah thanks for explaining that. I finally understand that piece of the puzzle (=why the level gets set to -1 with low-speed conditions).

**Comment by pannal** [comment]
Hey, I'm currently developing [PlexMod4Kodi](https://github.com/pannal/plex-for-kodi) and have added a "Slow connection" feature recently. It pauses the video and waits for `Player.ProgressCache` to reach a reasonable size compared to `Player.Progress`. Since the latest master this functionality doesn't work anymore.

I'm currently using an unreasonable cache size of 2000 MB and a readfactor of 20. After this PR, it seems like the buffer doesn't fill anymore (when the video is paused) - which it did before. Right now Kodi only buffers a certain percentage even while playing back, even though the buffer is huge and the readfactor is 20.

This is unexpected, as it was possible before to fill up the buffer as much as possible (even loading the full file into the buffer, then resuming, worked flawlessly).

**Comment by thexai** [comment]
> I'm currently using an unreasonable cache size of 2000 MB and a readfactor of 20.

20 readfactor also is unreasonable. Reason:

120 Mbps BluRay file * 20 = 2400 Mbps   this means saturate 1000 Mbps (1 Gbps Ethernet) unnecessarily and creating CPU spikes to fill the cache.

`Player.ProgressCache` and `Player.Progress` probably reports wrong numbers due the same reason "cache level" was wrong calculated and fixed here:

https://github.com/xbmc/xbmc/pull/22881

Then correct way is fix this internally while use 2000 MB cache size, 20 read factor and hack advancersettings is the wrong way.
