### PR TITLE
Show media stubs even if there is no optical drive

### LINKED ISSUE #17934: Media Stubs Cannot Display Messages without Optical Drive Present
### Describe the bug

If you create media stub files (either with custom messages or no messages at all), the stub message is never displayed because Kodi instead shows a message that there is no optical drive present.  If you connect an optical drive then the stub messages are displayed.

I believe this is bug because user preferenced messages should show instead of generic messages that have no effect on functionality (the fact that there is no optical drive doesn't mean Kodi will crash or malfunction if the media stub message is display).

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

When I create a media stub, I would expect either the default media stub message or the custom one written into the media stub to be displayed.
## Actual Behavior

I get a message that no optical drive is present.

## Possible Fix

Kodi should not check for the presence of an optical drive before displaying media stub messages.

Please see #11655 for information on a fix that was almost implemented 2 years ago.

### To Reproduce

1. Create a media stub as per https://kodi.wiki/view/Media_stubs
2. Scan into library.
3. Select the library item generated by the media stub without an optical drive attached.

### Debuglog

The debuglog can be found here:
N/A

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

I am trying to use the media stubs to catalog items from outside services in my Kodi library that will give me a message indicating on what service the item is.  For instance, Netflix or Disney+.  While I know there are addons for many of these services and ways to have items from those addons into the library, the addons are most often limited to 720p. By using media stubs, I can have the item remind me what service/device to use (like the Disney+ app on my TV).

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [] Linux
 - [x] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP
 - [x] OSMC

 - Operating system version/name: any
 - Kodi version: 18.7 (has occurred on any version since media stubs became available)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by dev77-07**
## Description
Allows media stubs to be shown if there is no optical drive

## Motivation and Context
Fixes https://github.com/xbmc/xbmc/issues/17934

## How Has This Been Tested?
Tested on Windows x64. With an optical drive in the system it displays the stub and gives the Play and Eject buttons. With no optical drive it displays the stub and gives just an OK button

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [ ] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by yeahme49** [comment]
Do I need to do anything after I rebased my PR? I'm also not sure why jenkins failed to build, it says the build was aborted but I don't see a reason.

**Comment by howie-f** [comment]
you need to rebase your branch to get rid of the merge-commit, then force push to trigger jenkins once again. before pushing you should also squash down to a single commit

File: xbmc/storage/MediaManager.h [hunk 1]
```diff
@@ -87,6 +87,9 @@ class CMediaManager : public IStorageEventsCallback, public IJobCallback
   void OnStorageUnsafelyRemoved(const std::string &label) override;
 
   void OnJobComplete(unsigned int jobID, bool success, CJob *job) override { }
+  
+  bool playStubFile(const CFileItem& item);
```
Comment (howie-f) [inline xbmc/storage/MediaManager.h:91]: looks like `#include "xbmc/FileItem.h"` is missing for building on all platforms

**Review by howie-f — CHANGES_REQUESTED** [review]

File: xbmc/storage/MediaManager.h (hunk 1 above)
Comment (yeahme49) [reply xbmc/storage/MediaManager.h:92]: Thanks, fixed that. Not sure why it compiles fine without that include on Windows but fails on everything else.

File: xbmc/storage/MediaManager.cpp [hunk 2]
```diff
@@ -760,3 +764,42 @@ void CMediaManager::RemoveDiscInfo(const std::string& devicePath)
   if (it != m_mapDiscInfo.end())
     m_mapDiscInfo.erase(it);
 }
+
+bool CMediaManager::playStubFile(const CFileItem& item)
+{
+  // Make sure we're actually dealing with a Disc Stub
+  if (!item.IsDiscStub())
+    return false;
+
```
Comment (howie-f) [inline xbmc/storage/MediaManager.cpp:773]: can be ommited because you already check when calling

**Review by howie-f — COMMENTED** [review]
looks ok to me, one minor. i suspect you force-pushed during build, what unfortunately knocks out jenkins for this pr. could someone please kick off?

File: xbmc/storage/MediaManager.cpp (hunk 2 above)
Comment (yeahme49) [reply xbmc/storage/MediaManager.cpp]: Removed this check

File: xbmc/storage/MediaManager.cpp [hunk 3]
```diff
@@ -760,3 +764,38 @@ void CMediaManager::RemoveDiscInfo(const std::string& devicePath)
...
+    }
+  }
+
+  // Use the label for Line 1 if not defined
+  if (strLine1.empty())
+    strLine1 = item.GetLabel();
+
+  if (HasOpticalDrive())
+  {
+#ifdef HAS_DVD_DRIVE
```
Comment (fuzzard) [inline xbmc/storage/MediaManager.cpp:791]: Im guessing this ifdef isnt needed either?

Has optical drive does that check already.

https://github.com/xbmc/xbmc/blob/65c06a2d361b7dab414ae1af39204ccd20e84d19/xbmc/storage/MediaManager.cpp#L391-L398

File: xbmc/storage/MediaManager.cpp [hunk 4]
```diff
@@ -59,6 +61,8 @@ using namespace XFILE;
 using namespace MEDIA_DETECT;
 #endif
 
+using namespace KODI::MESSAGING;
```
Comment (fuzzard) [inline xbmc/storage/MediaManager.cpp:64]: Im not sure its worth adding a using namespace for a single line.

Just my opinion though, if anyone else has a preference, im easy

File: xbmc/storage/MediaManager.cpp [hunk 5]
```diff
@@ -760,3 +764,38 @@ void CMediaManager::RemoveDiscInfo(const std::string& devicePath)
...
+  if (HasOpticalDrive())
+  {
+#ifdef HAS_DVD_DRIVE
+    if(CGUIDialogPlayEject::ShowAndGetInput(strLine1, strLine2))
+      return MEDIA_DETECT::CAutorun::PlayDiscAskResume();
+#endif
+  }
+  else
+  {
+    HELPERS::ShowOKDialogText(strLine1, strLine2);
```
Comment (fuzzard) [inline xbmc/storage/MediaManager.cpp:798]: KODI::MESSAGING::HELPERS::ShowOKDialogText(strLine1, strLine2);

and remove the using namespace KODI::MESSAGING.

let someone else chime in in case they have a strong preference i guess though

File: xbmc/storage/MediaManager.cpp (hunk 3 above)
Comment (howie-f) [reply xbmc/storage/MediaManager.cpp:791]: iirc dropping this ifdef failed android-builds

Comment (yeahme49) [reply xbmc/storage/MediaManager.cpp:791]: Yeah when I didn't have the ifdef the android builds failed so that's why I added it

File: xbmc/storage/MediaManager.cpp (hunk 4 above)
Comment (yeahme49) [reply xbmc/storage/MediaManager.cpp]: i'm fine changing this

File: xbmc/storage/MediaManager.cpp (hunk 5 above)
Comment (yeahme49) [reply xbmc/storage/MediaManager.cpp]: updated to this, i think it's a bit cleaner this way

**Comment by howie-f** [comment]
jenkins build this please

**Comment by phunkyfish** [comment]
Jenkins build this please

**Comment by yeahme49** [comment]
Looks like it still fails because it doesn't match the checked out revision so can't tell if it actually builds properly or not.

**Comment by howie-f** [comment]
if you like you can meanwhile squash down to one commit again and then force push once. if the build fails then we‘ll have to wait ;) but the code looks good, actually nothing you can do

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by lrusak** [comment]
This PR generates a new warning https://jenkins.kodi.tv/job/Android-ARM/lastFailedBuild/clang/new/source.e20b925d-b01a-4b5d-832a-318dfc033511/#799

**Comment by howie-f** [comment]
well i‘m sorry 😳 never encountered this before. may i give my suggestion? @yeahme49

**Comment by fuzzard** [comment]
It'll just be because if the mix of brackets and not, optimising itself to the wrong sets. I'd just add brackets to anything that you have brackets in one branch but not the other, ie if has no bracket, but else does.

**Comment by howie-f** [comment]
mine's a bit different.
the `else` (line 794) and its brackets `{}` should be dropped so that
```
KODI::MESSAGING::HELPERS::ShowOKDialogText(strLine1, strLine2);
return true;
```
are the last statements in that func.
i might be wrong...
let's confuse the author :)

**Comment by yeahme49** [comment]
Removing the else won't work. If you have an optical drive and it displays the stub message with the options to play or eject and you press escape, it will then display the stub message again but with just the OK button this time. I've changed it though so that it will always have some return value.

**Comment by yeahme49** [comment]
Am I doing something wrong pushing my new commits that causes jenkins to fail with the same "___ doesn't match currently checked out revision" or is some sort of jenkins bug?

**Comment by howie-f** [comment]
this is because there was a force-push during a running build.. yes will have to wait til the next manual trigger

**Comment by fuzzard** [comment]
jenkins build this please

**Comment by howie-f** [comment]
this looks much better.
finally please apply the diff from the jenkins job
(see https://jenkins.kodi.tv/job/BuildMulti-PR/16225/artifact/PR17940.diff) for your changes to follow the https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md

**Comment by fuzzard** [comment]
Before I kick over a last build, can you squash the commits. With that done I think it'll be ready for merge after the final build

**Review by howie-f — APPROVED** [review]
lgtm. a quick test yesterday on debian succeeded 👍🏻

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by howie-f** [comment]
someone build this please

**Comment by fuzzard** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Jenkins build this please

File: xbmc/dialogs/GUIDialogPlayEject.cpp [hunk 6]
```diff
@@ -75,38 +75,17 @@ void CGUIDialogPlayEject::OnInitWindow()
...
-  CXBMCTinyXML discStubXML;
-  if (discStubXML.LoadFile(item.GetPath()))
-  {
-    TiXmlElement * pRootElement = discStubXML.RootElement();
-    if (!pRootElement || StringUtils::CompareNoCase(pRootElement->Value(), "discstub") != 0)
-      CLog::Log(LOGERROR, "Error loading %s, no <discstub> node", item.GetPath().c_str());
-    else
-    {
-      XMLUtils::GetString(pRootElement, "title", strLine1);
-      XMLUtils::GetString(pRootElement, "message", strLine2);
```
Comment (fuzzard) [inline xbmc/dialogs/GUIDialogPlayEject.cpp:102]: Again, with the removal of this, doesn't appear to be any further use of xmlutils. Can we remove the include

https://github.com/xbmc/xbmc/blob/a288c97e191a45ff3c5c3bb54c6ec0bebff854cb/xbmc/dialogs/GUIDialogPlayEject.cpp#L16

File: xbmc/dialogs/GUIDialogPlayEject.cpp [hunk 7]
```diff
@@ -75,38 +75,17 @@ void CGUIDialogPlayEject::OnInitWindow()
...
     return false;
 
-  // Figure out Lines 1 and 2 of the dialog
-  std::string strLine1, strLine2;
-  CXBMCTinyXML discStubXML;
-  if (discStubXML.LoadFile(item.GetPath()))
-  {
-    TiXmlElement * pRootElement = discStubXML.RootElement();
-    if (!pRootElement || StringUtils::CompareNoCase(pRootElement->Value(), "discstub") != 0)
-      CLog::Log(LOGERROR, "Error loading %s, no <discstub> node", item.GetPath().c_str());
```
Comment (fuzzard) [inline xbmc/dialogs/GUIDialogPlayEject.cpp:98]: Header removal again. Doesn't appear to be any further clog usage

https://github.com/xbmc/xbmc/blob/a288c97e191a45ff3c5c3bb54c6ec0bebff854cb/xbmc/dialogs/GUIDialogPlayEject.cpp#L17

File: xbmc/storage/MediaManager.h [hunk 8]
```diff
@@ -8,6 +8,7 @@
 
 #pragma once
 
+#include "FileItem.h"
```
Comment (fuzzard) [inline xbmc/storage/MediaManager.h:11]: Regarding this, I think it may be better to forward declare the CFileItem in the header, and do the include in MediaManager.cpp.

Probably explains why it worked for windows, FileItem.h has been included in some other header that's behind a windows ifdef

Comment (howie-f) [reply xbmc/storage/MediaManager.h:11]: that should all work ok.
would by interesting to see if it still builds on windows with leaving the forward declaration behind.

Comment (fuzzard) [reply xbmc/storage/MediaManager.h:11]: Still best practice to have the include in the implementation file imo. Don't rely on an unknown include from somewhere else, as if that other header is changed you get a random breakage. CFileItem is absolutely used in the implementation, so declare it.
I believe that very scenario has affected some Devs recently when trying to do some minor change that snowballed all because of the luck of an include being done in some other include file.

Comment (howie-f) [reply xbmc/storage/MediaManager.h:11]: yeah, that's for sure. no need to check the win-build without forward-decl. unless @yeahme49 wants to ;) just confirm that all suggested include-removals do work

File: xbmc/Application.cpp [hunk 9]
```diff
@@ -2802,20 +2802,7 @@ bool CApplication::PlayFile(CFileItem item, const std::string& player, bool bRes
...
-        // PlayDiscAskResume takes path to disc. No parameter means default DVD drive.
-        // Can't do better as CGUIDialogPlayEject calls CMediaManager::IsDiscInDrive, which assumes default DVD drive anyway
-        return MEDIA_DETECT::CAutorun::PlayDiscAskResume();
-    }
-    else
-#endif
-      HELPERS::ShowOKDialogText(CVariant{435}, CVariant{436});
-
-    return true;
+    return CServiceBroker::GetMediaManager().playStubFile(item);
```
[the remark this answers is not in the document]
Comment (yeahme49) [reply xbmc/Application.cpp:2804]: removed this include

File: xbmc/dialogs/GUIDialogPlayEject.cpp (hunk 6 above)
Comment (yeahme49) [reply xbmc/dialogs/GUIDialogPlayEject.cpp:102]: removed this include

File: xbmc/dialogs/GUIDialogPlayEject.cpp (hunk 7 above)
Comment (yeahme49) [reply xbmc/dialogs/GUIDialogPlayEject.cpp:98]: removed this include

File: xbmc/storage/MediaManager.h (hunk 8 above)
Comment (yeahme49) [reply xbmc/storage/MediaManager.h]: moved the include and forward declared CFileItem in the header

**Comment by yeahme49** [comment]
Jenkins build this please

**Comment by fuzzard** [comment]
Thanks for your contribution @yeahme49. Appreciated.

**Comment by yeahme49** [comment]
Thanks everyone for the input on the PR and thank you for merging it.
