### PR TITLE
[GUI] GetNumPages crash on small textbox with large font sizes

### LINKED ISSUE #22136: Container.NumPages crash on small textbox with large font sizes
### Describe the bug
Here is a clear and concise description of what the problem is:

When using a short textbox control with large font sizes , Kodi will crash when the skin references Container(ID).NumPages for the textbox.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Kodi does not crash.

## Actual Behavior

Kodi crashes when referencing the Container.NumPages infolabel for a textbox control when the textbox is too short to accomodate a full line of text at the font height.

## Possible Fix

My guess is a divide by zero error.

My assumption is that somewhere the visible line count per page is being calculated as an integer. Since the textbox is not tall enough to accomodate a full line, the calculation will be 0 and NumPages will be infinite.

### To Reproduce

In Estuary xml

Add to default fontset in **Font.xml** 

```xml
<font>
    <name>fonttest</name>
    <filename>NotoSans-Regular.ttf</filename>
    <size>150</size>
</font>
```

Then in **Home.xml** add a textbox control and a label referencing Container.NumPages

```xml
<control type="textbox" id="99991">
    <aligny>top</aligny>
    <height>160</height>
    <label>$INFO[Container.ListItem.Label]</label>
    <font>fonttest</font>
    <textcolor>ffdedede</textcolor>
</control>
<control type="label">
    <top>160</top>
    <aligny>top</aligny>
    <height>40</height>
    <label>$INFO[Container(99991).NumPages]</label>
    <font>fonttest</font>
    <textcolor>ffdedede</textcolor>
</control>
```

### Debuglog

The debuglog can be found here:

[kodi.log](https://github.com/xbmc/xbmc/files/9998696/kodi.log)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Nexus Nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by joseluismarti**
## Description
When using a short textbox control with large font sizes, Kodi crashs when the skin references `Container(ID).NumPages` as described in #22136.

This textbox is not tall enough to accommodate the height of the label, thus the value of the `m_itemsPerPage` variable is 0.

A divide by zero error occurs in the `GetNumPages()` function.

## How has this been tested?
The error no longer occurs tested using the example code proposed in the issue.

## Types of change
- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:
- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/guilib/GUITextBox.cpp [hunk 1]
```diff
@@ -394,7 +394,10 @@ unsigned int CGUITextBox::GetRows() const
 
 int CGUITextBox::GetNumPages() const
 {
-  return (GetRows() + m_itemsPerPage - 1) / m_itemsPerPage;
+  if (m_itemsPerPage == 0)
```
Comment (enen92) [inline xbmc/guilib/GUITextBox.cpp:397]: You can make this a bit more concise using a ternary operator:

```
int CGUITextBox::GetNumPages() const
{
  return m_itemsPerPage > 0 ? (GetRows() + m_itemsPerPage - 1) / m_itemsPerPage : 0;
}
```

Comment (joseluismarti) [reply xbmc/guilib/GUITextBox.cpp:397]: Cool, more concise

**Review by enen92 — APPROVED** [review]
