### PR TITLE
[OSX] Reduce CPU usage by suspending rendering when app is inactive

### LINKED ISSUE #25436: High CPU usage when Kodi is not in focus on MacOS Apple Silicon (MBA)
### Describe the bug

When Kodi is playing a video or paused and it is not in focus the CPU usage gets very high about 90% and i can feel the MacBook getting really hot if Kodi is in focus CPU is about 15-20% while playing or paused. 
I have tried versions 19/20/21/ might builds x86 and apple silicon, Different Skins, some possible solutions found in forum for version 17 which had same issue nothing worked. 
MacOS version Sonoma 14.5
Hardware: Mackbook Air M1
Since this is my first Bug Report i would like to take this opportunity to thank the Developers for such an awesome software. You Guys Rock!!! 

## Expected Behavior

CPU usage should remain about the same when changing desktops or is in background

## Actual Behavior

When Kodi is playing a video or paused and it is not in focus the CPU usage gets very high about 90% and i can feel the MacBook getting really hot.

### To Reproduce

1. While playing or paused a video change desktop or move to Background.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/mifucudibi.kodi

### Screenshots 
Here are some links or screenshots to help explain the problem:

In focus
Screeshot in focus

https://paste.pics/ae15594fa9535cdbd3cb8f65e4e73120

in different desktop rendering frame actually is over 1200 and CPU 85% 
screenshot out of fucus

https://paste.pics/72cab595eb3bb09a7aff5367facea6f4

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [x] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: MacOS 14.5/Sonoma
 - Kodi version: 21 arm64

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by rfarina51**
## Description
Fixed https://github.com/xbmc/xbmc/issues/25436

Fix high CPU usage on macOS when Kodi window is not in focus by disabling GUI rendering during window focus/visibility changes.

## Motivation and context
This change addresses issue #25436 where Kodi on macOS Apple Silicon consumes 60-120% CPU when the application window is not in focus or is miniaturized. The root cause is that Kodi continues to aggressively render the GUI even when the window is not visible to the user, causing unnecessary CPU usage.

The fix implements proper window lifecycle management by:
- Disabling GUI rendering when the window loses focus (`windowDidResignKey`)
- Disabling GUI rendering when the window is miniaturized (`windowDidMiniaturize`) 
- Re-enabling GUI rendering when the window regains focus (`windowDidBecomeKey`)
- Re-enabling GUI rendering when the window is deminiaturized (`windowDidDeminiaturize`)
- Re-enabling GUI rendering when the window is exposed (`windowDidExpose`)

## How has this been tested?
Testing was performed on macOS Apple Silicon (M3 Max) with the following methodology:

1. **Build Environment**: Built Kodi with Python enabled using CMake with Unix Makefiles generator
2. **CPU Monitoring**: Used `ps aux | grep -i kodi` to monitor CPU usage in real-time
3. **Test Scenarios**:
   - **Focused window**: CPU usage ~0.3% (baseline)
   - **Unfocused window**: CPU usage drops from 60-77% to ~0.3% 
   - **Miniaturized window**: CPU usage drops to ~0.3%
   - **Window focus changes**: Proper transitions between focused/unfocused states

4. **Regression Testing**: Confirmed that GUI rendering resumes properly when window regains focus, ensuring no visual artifacts or functionality loss.

## What is the effect on users?
**Significant positive impact on macOS users:**

- **Reduced CPU usage**: CPU consumption drops from 60-77% to ~0.3% when Kodi is not in focus, preventing overheating and fan noise

This fix brings macOS behavior in line with other platforms and follows macOS application lifecycle best practices.

## Screenshots (if appropriate):
N/A - This is a performance optimization with no visual changes.

## Types of change
- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:
- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by rfarina51** [comment]
> I've made some formatting changes to meet the current code style. The diffs are available in the following links:
> 
>     * [PR27273-0001-bb8fb7bfd1-fix-high-cpu-issue-by-disabling-gu.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/35574/artifact/PR27273-0001-bb8fb7bfd1-fix-high-cpu-issue-by-disabling-gu.diff)
> 
>     * [PR27273.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/35574/artifact/PR27273.diff)
> 
> 
> For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

Applied

**Comment by ksooo** [comment]
> Applied

Almost. Jenkins is (ofc) still moaning about the first commit. Could you please squash down changes to a single commit.

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm [hunk 1]
```diff
@@ -99,18 +99,39 @@ - (void)windowDidEndLiveResize:(NSNotification*)notification
 - (void)windowDidMiniaturize:(NSNotification*)aNotification
 {
   g_application.m_AppFocused = false;
+
+  // Disable GUI rendering when window is miniaturized to reduce CPU usage
+  std::shared_ptr<CAppInboundProtocol> appPort = CServiceBroker::GetAppPort();
+  if (appPort)
+  {
+    appPort->SetRenderGUI(false);
+  }
```
Comment (ksooo) [inline xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: This code is (almost) duplicated 5 times. Could you please create a small helper function like `void SetRenderGUI(bool enable)` in an unnamed namespace in this cpp file. This would reduce number of changed code lines and improve overall readability and maintainability of the code.

In addition, I think the comments are not actually adding value, as a call to a function with a speaking name should be self-explaining.

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm [hunk 2]
```diff
@@ -99,18 +99,39 @@ - (void)windowDidEndLiveResize:(NSNotification*)notification
...
 }
 
 - (void)windowDidDeminiaturize:(NSNotification*)aNotification
 {
   g_application.m_AppFocused = true;
+
+  // Re-enable GUI rendering when window is deminiaturized
+  std::shared_ptr<CAppInboundProtocol> appPort = CServiceBroker::GetAppPort();
```
Comment (ksooo) [inline xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: This should be changed to `const std:.shared_ptr<...`

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm [hunk 3]
```diff
@@ -99,18 +99,39 @@ - (void)windowDidEndLiveResize:(NSNotification*)notification
...
+  if (appPort)
+  {
+    appPort->SetRenderGUI(true);
+  }
```
Comment (ksooo) [inline xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: I would remove the curly braces. The just make the cpp file bigger adding no real value for readability or whatever.

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm [hunk 4]
```diff
@@ -53,6 +53,13 @@ - (nullable instancetype)initWithTitle:(NSString*)title defaultSize:(NSSize)size
   return self;
 }
 
+- (void)setGUIRenderingForPerformance:(BOOL)enabled
```
Comment (ksooo) [inline xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: Nitpick: i would remove “ForPerformance” from the function name. A method name should reflect what the method does, not why it is called.

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm [hunk 5]
```diff
@@ -53,6 +53,13 @@ - (nullable instancetype)initWithTitle:(NSString*)title defaultSize:(NSSize)size
...
+{
+  const std::shared_ptr<CAppInboundProtocol> appPort = CServiceBroker::GetAppPort();
```
[the remark this answers is not in the document]
Comment (garbear) [reply xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: Disregard, `const` is intended.

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm (hunk 4 above)
Comment (ksooo) [reply xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: @rfarina51 what is your thought on this? Do you want to change that?

**Comment by ksooo** [comment]
@kambala-decapitator @enen92 any thoughts? I'm not a macOS expert. So no idea whether the approach for the fix taken here is okay. All I can say is that I runtime-tested the patch and it seems to work as designed without side effects.

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm [hunk 6]
```diff
@@ -53,6 +53,13 @@ - (nullable instancetype)initWithTitle:(NSString*)title defaultSize:(NSSize)size
...
+  if (appPort)
+    appPort->SetRenderGUI(enabled);
```
Comment (kambala-decapitator) [inline xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: Since it's a C++ call, `enabled` should be of type `bool`, not objc `BOOL`. And use true/false instead of YES/NO respectively.

**Review by kambala-decapitator — COMMENTED** [review]
the chosen approach looks good

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm (hunk 6 above)
Comment (ksooo) [reply xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: @kambala-decapitator I think the whole function should be c++ in an unnamed namespace. What do you think?

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm (hunk 4 above)
Comment (rfarina51) [reply xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: I think `setGUIRendering` with a comment explaining why we are doing this is the best approach

**Comment by rfarina51** [comment]
> the chosen approach looks good

thanks I also do not work on macOS, just a frustrated and determined user :)

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm (hunk 4 above)
Comment (ksooo) [reply xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: I don’t think we need comments. For me it is pretty obvious why we’re doing this even without further explanation. And, there will be the commit message which should explain the reasons.

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm (hunk 6 above)
Comment (kambala-decapitator) [reply xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: > @kambala-decapitator I think the whole function should be c++ in an unnamed namespace. What do you think?

yes, also good idea

**Comment by ksooo** [comment]
@rfarina51 from my perspective, if you apply the following patch, then squash down to a single commit, we should be ready to merge this PR:

```diff
diff --git a/xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm b/xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm
index 3f60d72dc5..7fbaf4dc92 100644
--- a/xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm
+++ b/xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm
@@ -20,6 +20,16 @@
 #include "windowing/osx/WinEventsOSX.h"
 #import "windowing/osx/WinSystemOSX.h"
 
+namespace
+{
+void EnableRenderGUI(bool enable)
+{
+  const std::shared_ptr<CAppInboundProtocol> appPort(CServiceBroker::GetAppPort());
+  if (appPort)
+    appPort->SetRenderGUI(enable);
+}
+} // unnamed namespace
+
 @implementation XBMCWindowControllerMacOS
 
 - (nullable instancetype)initWithTitle:(NSString*)title defaultSize:(NSSize)size
@@ -53,13 +63,6 @@ - (nullable instancetype)initWithTitle:(NSString*)title defaultSize:(NSSize)size
   return self;
 }
 
-- (void)setGUIRenderingForPerformance:(BOOL)enabled
-{
-  const std::shared_ptr<CAppInboundProtocol> appPort = CServiceBroker::GetAppPort();
-  if (appPort)
-    appPort->SetRenderGUI(enabled);
-}
-
 - (void)windowDidResize:(NSNotification*)aNotification
 {
   if ((self.window.styleMask & NSWindowStyleMaskFullScreen) != NSWindowStyleMaskFullScreen)
@@ -87,26 +90,24 @@ - (void)windowDidResize:(NSNotification*)aNotification
 
 - (void)windowWillStartLiveResize:(NSNotification*)notification
 {
-  [self setGUIRenderingForPerformance:NO];
+  EnableRenderGUI(false);
 }
 
 - (void)windowDidEndLiveResize:(NSNotification*)notification
 {
-  [self setGUIRenderingForPerformance:YES];
+  EnableRenderGUI(true);
 }
 
 - (void)windowDidMiniaturize:(NSNotification*)aNotification
 {
   g_application.m_AppFocused = false;
-
-  [self setGUIRenderingForPerformance:NO];
+  EnableRenderGUI(false);
 }
 
 - (void)windowDidDeminiaturize:(NSNotification*)aNotification
 {
   g_application.m_AppFocused = true;
-
-  [self setGUIRenderingForPerformance:YES];
+  EnableRenderGUI(true);
 }
 
 - (void)windowDidBecomeKey:(NSNotification*)aNotification
@@ -114,7 +115,7 @@ - (void)windowDidBecomeKey:(NSNotification*)aNotification
   g_application.m_AppFocused = true;
   CServiceBroker::GetAnnouncementManager()->Announce(ANNOUNCEMENT::GUI, "WindowFocused");
 
-  [self setGUIRenderingForPerformance:YES];
+  EnableRenderGUI(true);
 
   auto winSystem = dynamic_cast<CWinSystemOSX*>(CServiceBroker::GetWinSystem());
   if (winSystem)
@@ -128,7 +129,7 @@ - (void)windowDidResignKey:(NSNotification*)aNotification
   g_application.m_AppFocused = false;
   CServiceBroker::GetAnnouncementManager()->Announce(ANNOUNCEMENT::GUI, "WindowUnfocused");
 
-  [self setGUIRenderingForPerformance:NO];
+  EnableRenderGUI(false);
 
   auto winSystem = dynamic_cast<CWinSystemOSX*>(CServiceBroker::GetWinSystem());
   if (winSystem)
@@ -148,8 +149,7 @@ - (BOOL)windowShouldClose:(id)sender
 - (void)windowDidExpose:(NSNotification*)aNotification
 {
   g_application.m_AppFocused = true;
-
-  [self setGUIRenderingForPerformance:YES];
+  EnableRenderGUI(true);
 }
 
 - (void)windowDidMove:(NSNotification*)aNotification
 ```

File: xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm (hunk 4 above)
Comment (rfarina51) [reply xbmc/windowing/osx/OpenGL/WindowControllerMacOS.mm]: sg, not my repo so if it works for you then I'm all for it

**Review by ksooo — APPROVED** [review]
Thanks for your contribution.

**Comment by ksooo** [comment]
Because also @kambala-decapitator verbally approved the fix I’m going to merge this now.
