### PR TITLE
GUIFontTTF: fix last character corruption on AMD RX 6000 series

### LINKED ISSUE #20008: Corrupted font / characters using AMD 6800 GPU
### Describe the bug
Here is a clear and concise description of what the problem is:
The last character of every word in the Kodi GUI appears corrupted using Windows 10 (or 11) paired with an AMD 6800 GPU (or similar, see forum links below, other similar models show the same issue).  See the following images:
TA2i6A8
Kodi-1
Kodi-2

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Text is not corrupted when using the GPU(s) noted.

## Actual Behavior
Text is corrupted, every last character of every word, when using the GPU(s) noted.

## Possible Fix
Unknown if this is a GPU driver issue or Kodi fixable issue.  A moderator in the Kodi forum suggested this was a driver issue, but I'm not sure how that conclusion was made.

### To Reproduce

1.  Install Kodi on a Windows 10 or newer PC paired with an AMD 6800 GPU or similar
2.  Start Kodi, note corrupted fonts

Understand that this may be difficult to troubleshoot without the appropriate hardware, so I'm willing to help if necessary with additional troubleshooting or information.

### Debuglog

Below is a debug log showing my system build.  There is no other notable information in debug logs.  I will note I installed the latest nightly v20 Alpha, and the latest v19 stable, hoping the Harfbuzz library would potentially fix the problem, but the problem persists with any version of Kodi newer than 18.9:
```
2020-12-12 21:19:18.311 T:7836  NOTICE: -----------------------------------------------------------------------
2020-12-12 21:19:18.311 T:7836  NOTICE: Starting Kodi (18.9 (18.9.0) Git:20201023-0655c2c718). Platform: Windows NT x86 64-bit
2020-12-12 21:19:18.311 T:7836  NOTICE: Using Release Kodi x64 build
2020-12-12 21:19:18.311 T:7836  NOTICE: Kodi compiled 2020-10-23 by MSVC 191627035 for Windows NT x86 64-bit version 10.0 (0x0A000007)
2020-12-12 21:19:18.311 T:7836  NOTICE: Running on Windows 10, kernel: Windows NT x86 64-bit version 10.0.19042
2020-12-12 21:19:18.311 T:7836  NOTICE: FFmpeg version/source: 4.0.4-Kodi
2020-12-12 21:19:18.311 T:7836  NOTICE: Host CPU: AMD Ryzen 5 5600X 6-Core Processor, 12 cores available
2020-12-12 21:19:18.311 T:7836  NOTICE: Desktop Resolution: 1280x800 32Bit at 32Hz
...
2020-12-12 21:19:18.400 T:7836   DEBUG: DX:eviceResources::HandleOutputChange: selected AMD Radeon RX 6800 adapter.
2020-12-12 21:19:18.400 T:7836   DEBUG: CWinSystemWin32DX::InitHooks: Hooking into UserModeDriver on device .
2020-12-12 21:19:18.400 T:7836   DEBUG: CWinSystemWin32DX::InitHooks: error open registry key with error 2.
2020-12-12 21:19:18.402 T:7836   DEBUG: DX:eviceResources::CreateDeviceResources: creating DirectX 11 device.
2020-12-12 21:19:18.422 T:7836   DEBUG: DX:eviceResources::CreateDeviceResources: device is created on adapter 'AMD Radeon RX 6800' with feature level b100.
```

### Screenshots 
Here are some links or screenshots to help explain the problem:
I also compiled Freetype / freetype demo (ftview) from source to see if I could find a common issue with Freetype and the AMD GPU itself.  Below is a screenshot of ftview showing the Kodi's arial.ttf font, with no noted corrupt characters:
Screen Shot 2021-07-30 at 1 13 57 PM

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:
Links to the issue in Kodi Forums:
https://forum.kodi.tv/showthread.php?tid=359715
https://forum.kodi.tv/showthread.php?tid=359105

Links to the issue on the AMD forums:
https://community.amd.com/t5/graphics/radeon-rx-6900-xt-and-kodi-compatibility/td-p/436372

Additional notes are that using the DXVK Transitional Layer (Vulkan) fixes the issue (not sure if this points to the driver or not) .  However, this breaks video player capability in Kodi, so it's not a viable workaround.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [X] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:  v18.9 or newer (up to v20 Alpha as of 07/30/21).

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
GUIFontTTF: fix last character corruption on AMD RX 6000 series

Fixes: https://github.com/xbmc/xbmc/issues/20008

## Motivation and context
See https://forum.kodi.tv/showthread.php?tid=335005 and https://forum.kodi.tv/showthread.php?tid=359715 and https://forum.kodi.tv/showthread.php?tid=332826

Also https://github.com/xbmc/xbmc/issues/20008

This is very long-standing bug present at least in Kodi v16, v17, v18, v19....

Finally seems that true root cause is missing/corrupted vertex data due misaligned  `SVertex` structure. DirectX 11 needs 16 ~bit~ byte aligned data. ~as data type is `DXGI_FORMAT_R16_UINT`.~

`stride` is 36 before and 48 after here:
https://github.com/xbmc/xbmc/blob/d89c10711a535e572db1f093dbed9da0eed9fb6a/xbmc/guilib/GUIFontTTFDX.cpp#L91

Current Intel and Nvidia drivers seems are able to get around this ignoring missing/incorrect vertex data but RenderDoc displays that one vertex data is missing anyway (Nvidia).

## How has this been tested?
Runtime tested on AMD RX 6500 XT, Nvidia RTX 2060 and Intel NUC8i3BEK

Test build here: 
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220417-ab616756-fix-font-AMD-x64.exe

Updated build with vertex struct size = 44 bytes and all other changes:
https://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220418-c88e3449-fix-font-AMD-x64.exe

## What is the effect on users?
Fixes last character corruption on AMD RX 6000 series.

## Screenshots (if appropriate):
Before:
Captura de pantalla-before

After:
Captura de pantalla-after

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/guilib/GUIFontTTF.cpp [hunk 1]
```diff
@@ -469,7 +469,11 @@ void CGUIFontTTF::DrawTextInternal(CGraphicContext& context,
         break;
       cursorX += ch->m_advance;
     }
+
+    // Reserve vertices space in vector: 4 * num glyphs
+    tempVertices->reserve(glyphs.size() * 4);
```
Comment (thexai) [inline xbmc/guilib/GUIFontTTF.cpp:474]: This is not essential. It's just to reduce number of memory re-allocations in large texts.

Comment (lrusak) [inline xbmc/guilib/GUIFontTTF.cpp:474]: What does the `4` indicate?

Comment (thexai) [reply xbmc/guilib/GUIFontTTF.cpp:474]: Better?
`// Reserve vector space: 4 vertices for each glyph`

**Comment by afedchin** [comment]
I didn't get the idea of the fix.  16 **bits** alignment doesn't mean 16 **bytes** alignment. Your thoughts are wrong. 

**The vertexes buffer doesn't have a type** but indexies buffer can be `DXGI_FORMAT_R16_UINT` or  `DXGI_FORMAT_R32_UINT` type only (see [ms doc](https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-iasetindexbuffer)). **They are different buffers.** Type of the indexies buffer can't have any effect on verteies buffer.

It looks like there is an issue with optimized `memcpy` (or GPU's memcpy in AMD drivers) which operates with aligned blocks only that's why it doesn't copy vertexies completelly.

File: xbmc/guilib/GUIFontTTF.cpp (hunk 1 above)
Comment (afedchin) [reply xbmc/guilib/GUIFontTTF.cpp:474]: **4** vertixies for each glyph

**Comment by afedchin** [comment]
@thexai to verify my thought about memcpy you can try to allign the whole buffer here
https://github.com/xbmc/xbmc/blob/d89c10711a535e572db1f093dbed9da0eed9fb6a/xbmc/guilib/GUIFontTTFDX.cpp#L297

**Comment by thexai** [comment]
Sorry, my comment in description was wrong: I meant bytes.

`SVertex` struct needs to be aligned in 16 byte boundary.

Then `unsigned width = sizeof(SVertex) * vertex_count;`  becomes multiple of 16 always.

**Comment by thexai** [comment]
>  (or GPU's memcpy in AMD drivers)

Is not AMD specific issue. Also has been reported on Intel and Nvidia (less frequent).

i.e:
Intel ---> https://forum.kodi.tv/showthread.php?tid=332826&pid=2743542#pid2743542
Nvidia --> https://github.com/xbmc/xbmc/issues/20008#issuecomment-1013379095

File: xbmc/guilib/GUIFontTTF.cpp (hunk 1 above)
Comment (lrusak) [reply xbmc/guilib/GUIFontTTF.cpp:474]: I'm a big fan of constexpr human readable definitions.

Comment (thexai) [reply xbmc/guilib/GUIFontTTF.cpp:474]: It looks good to me but I add it in separate commits since the improvements are probably not necessary backport to Matrix.

**Comment by thexai** [comment]
I have found that method `CGUIFontTTFDX::UpdateDynamicVertexBuffer` are not used at all in current modern systems because supports hardware clipping:

https://github.com/xbmc/xbmc/blob/8e0f6f958ce4c4e2d68c12fa9234ed081262c8c3/xbmc/guilib/GUIFontTTF.cpp#L368

So this code path is not used and then memcpy here is also not used:

https://github.com/xbmc/xbmc/blob/8e0f6f958ce4c4e2d68c12fa9234ed081262c8c3/xbmc/guilib/GUIFontTTFDX.cpp#L323

However I forced `CRenderSystemDX::ScissorsCanEffectClipping()`  to return false and the issue is also reproducible in AMD 6000 drivers but it not happens in all texts. Last letter corruption is only in some (apparently) random texts and not all the time...

Also tested with fix (16 byte aligned vertex struct) + hardware clipping disabled and corruption is gone too.

So conclusions are:

Corruption happens here (software clipping):
https://github.com/xbmc/xbmc/blob/8e0f6f958ce4c4e2d68c12fa9234ed081262c8c3/xbmc/guilib/GUIFontTTFDX.cpp#L110

and here (hardware clipping)
https://github.com/xbmc/xbmc/blob/8e0f6f958ce4c4e2d68c12fa9234ed081262c8c3/xbmc/guilib/GUIFontTTFDX.cpp#L162

The data is correct until is "uploaded" to GPU by `ID3D11DeviceContext::IASetVertexBuffers`  https://docs.microsoft.com/en-us/windows/win32/api/d3d11/nf-d3d11-id3d11devicecontext-iasetvertexbuffers
Corruption not occurs if (same) data is 16 byte aligned.

For me 16 byte aligned data means:

`| vertex_1 |  padding until next 16 byte boundary | vertex_2 |  padding until next 16 byte boundary | ...`

currently vertex_n size is 36 bytes so padding is 12 bytes and sizeof(vertex_n+padding) is 36 +12 = 48 bytes

**Comment by afedchin** [comment]
the one thing gets me no sleep: why the issue occurs only for fonts? `SVertex` and similar structs are used not only for fonts.
https://github.com/xbmc/xbmc/blob/master/xbmc/guilib/GUIShaderDX.h#L19 is one of. `struct Vertex` has 44 bytes size which is also not aligned to 16 bytes. this vertex is used for all (!!!) graphics. Why it isn't corrupted then?

> Corruption happens here (software clipping):
you are wrong. the `IASetVertexBuffers` doesn't change or create a buffer, it just links it to GPU pipeline. The same for hardware clipping. they are corrupted while creating:

For software clipping here:
https://github.com/xbmc/xbmc/blob/8e0f6f958ce4c4e2d68c12fa9234ed081262c8c3/xbmc/guilib/GUIFontTTFDX.cpp#L306
and here (in case when buffere is created already):
https://github.com/xbmc/xbmc/blob/8e0f6f958ce4c4e2d68c12fa9234ed081262c8c3/xbmc/guilib/GUIFontTTFDX.cpp#L323

For hardware clipping here:
https://github.com/xbmc/xbmc/blob/a15445fe44b7c89296fcb7ee736ac813f2410254/xbmc/guilib/D3DResource.cpp#L953

`CreateBuffer` does:
1. copy a buffer into another area of memory (if initial data is defined)
2. puts a command into GPU command queue

all the magic occurs at the end of a frame. So there are two possible places where it corrupted:

1. While initial copying of buffer by directx (or driver)
2. while copying it into GPU's memory (driver)

as I know there only one requirement for data: all datas has to be 4 bytes aligned because hardware requires this.

**Comment by afedchin** [comment]
hm. it looks like there is mismatching between `SVertex` declaration here:
https://github.com/xbmc/xbmc/blob/8e0f6f958ce4c4e2d68c12fa9234ed081262c8c3/xbmc/guilib/GUIFontTTF.h#L55
and what exactly shader expects.

@thexai can you please change `SVertex` to the following declaration:
```cpp
#ifdef HAS_DX
struct SVertex
{
  float x, y, z;
  XMFLOAT4 col;
  float u, v;
  float u2, v2;
};
#else
....
```

**Comment by thexai** [comment]
Fantastic!  😀

This change has same positive effect that align to 16 bytes.

As u2, v2 members are not used, introduces zeros at end similar to padding although `sizeof` is 44 instead 48. 
Also in RenderDoc vertex data is exact same values that using align to 16 bytes.

**Review by afedchin — APPROVED** [review]
