### PR TITLE
[Video] Fix repetitive calls to UpdateFileItemStreamDetails().

### LINKED ISSUE #27533: PR #27176 introduced excessive calls to UpdateFileItemStreamDetails
### Describe the bug
Here is a clear and concise description of what the problem is:

I dont think its a real bug, it could be simply be a  poor implementation

each time you play a video the log is spammed by tons of
```
2025-11-29 13:34:28.669 T:3480    debug <general>: CVideoPlayer: updating file item stream details with available streams
2025-11-29 13:34:32.198 T:2232     info <general>: Skipped 17 duplicate messages..
```

this is caused by the new code 
https://github.com/xbmc/xbmc/blob/82844bb463e80d7c0337709e2013082978138474/xbmc/cores/VideoPlayer/VideoPlayer.cpp#L5193-L5197
introduced by PR #27176

The code says that it is specific to Blu-rays/DVDs, so i wonder why not limit this execution to those cases?
or whether to eliminate the log, or else find a better optimization for these calls

### To Reproduce

1.  play a video
2.
3.

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/uzasikarof.kodi

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: Kodi 22 master branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Inform VideoPlayer whenever a title/playlist is changed so that the streamdetails can be saved (for discs played through disc menu - eg. all DVDs currently and by choice for blurays). 

Once streamdetails are saved then stop calling UpdateFileItemStreamDetails().

## Motivation and context

Fix #27533.

## How has this been tested?

Locally playing a bluray and DVD through the disc menu and confirming correct main title playlist and associated streamdetails are saved.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@CastagnaIT FYI.

**Comment by CrystalP** [comment]
Event-based is much better. The solution feels adhoc though.
Could the same result be accomplished with a new message type sent by videoplayer to itself in order to safely send the signal to update stream details across threads? The trigger points you identified in DVDInputStream* seem appropriate.
That would take the code completely out of the per-frame path for the non-Bluray non-DVD cases.

**Comment by 78andyp** [comment]
> Event-based is much better. The solution feels adhoc though. Could the same result be accomplished with a new message type sent by videoplayer to itself in order to safely send the signal to update stream details across threads? The trigger points you identified in DVDInputStream* seem appropriate. That would take the code completely out of the per-frame path for the non-Bluray non-DVD cases.

I did look at the event system - the only reason I didn't use it was the events that exist currently seem to be derived from the dvd/bluray libraries and (for no particular reason) I didn't want introduce 'other' events - although I certainly can and that would mean less changes (and not needing the SetSaveStreamDetails() function and override).

It would still need to exist in the per frame path as when testing I found a few occasions when then very first few times stream details were saved they weren't fully populated - hence the introduction here of the complete flag.

I'll change it to use the current event system.

**Comment by CrystalP** [comment]
> I did look at the event system - the only reason I didn't use it was the events that exist currently seem to be derived from the dvd/bluray libraries and (for no particular reason) I didn't want introduce 'other' events - although I certainly can and that would mean less changes (and not needing the SetSaveStreamDetails() function and override).

It would seem appropriate to me to push a BD_EVENT_PLAYLIST into OnDiscNavResult for example.

Stream details not populated: odd, do you understand how that's supposed to work and why it occasionally fails?

**Comment by 78andyp** [comment]
Thanks. Will do.

Not fully - I know that when the title/playlist change is triggered in the input streams, the stream details will not yet have been set in videoplayer.

I don't fully understand the inter-relationship between the input streams, demuxers, players (VP and VPV) and ffpmeg and which does what when and how they are threaded, and then there are the callbacks in applicationplayercallback (they make sense) and application as well. It's all rather complicated!!

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
> I've made some formatting changes to meet the current code style. The diffs are available in the following links:
> 
> * [PR27543-0001-ba4cf908a4-Video-Fix-repetitive-calls-to-Upda.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/36278/artifact/PR27543-0001-ba4cf908a4-Video-Fix-repetitive-calls-to-Upda.diff)
> * [PR27543.diff](https://jenkins.kodi.tv/job/BuildMulti-PR/36278/artifact/PR27543.diff)
> 
> For more information please see our [current code style guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md).

This would actually break current formatting.

**Comment by 78andyp** [comment]
Force push - Added a commit first that Jenkins formats the OnDiscNavResult() function so that when it's changed in the functional commit there are no formatting errors (that would otherwise not be in keeping with the given layout of the function).

**Comment by CrystalP** [comment]
That's not what I had in mind, which was actually passing BD_EVENT_PLAYLIST and its DVD equivalent to OnDiscNavResult, just like how it's done for other events.
But regardless of name, it doesn't help with the rest of the change.
Why is it needed to catch the data while playing, instead of waiting for playback to stop?

@claude please analyze why, as reported by @78andyp, sometimes the stream detail information is not populated when the Bluray playlist changes, and suggest corrections.

**Comment by CastagnaIT** [comment]
its possible that this code
https://github.com/xbmc/xbmc/blob/bc1ce9725ad6aa73f0d7fdc65636725cb927941f/xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp#L1473-L1476
dont return the resolution width/height, and that are parsed from the stream when playback start?

**Comment by 78andyp** [comment]
@CrystalP 
The reason that this cannot just be done at the end (like it was before #27176) is that, in a single instance of videoplayer, multiple titles/playlists can be played.

Using Sympathy for the Devil (2023) DVD and playing through the menu the following titles are all played:
image
If we only saved the details of the last one (the menu) then the information displayed in the library would be wrong.

There is a logo, 2 trailers, the menu, the main movie and then back to the menu.

I think rewriting everything so that a single instance of videoplayer is used for each title/playlist would be an overkill and I have no idea what the resource implications would be.

**Comment by 78andyp** [comment]
> its possible that this code
> 
> https://github.com/xbmc/xbmc/blob/bc1ce9725ad6aa73f0d7fdc65636725cb927941f/xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStreamNavigator.cpp#L1473-L1476
> 
> 
> dont return the resolution width/height, and that are parsed from the stream when playback start?

It's not just the video stream it's all streams we want - so correct details are shown in the library.

**Comment by 78andyp** [comment]
Will merge in a few days unless objections.

File: xbmc/cores/VideoPlayer/VideoPlayer.cpp [hunk 1]
```diff
@@ -748,7 +748,8 @@ CVideoPlayer::CVideoPlayer(IPlayerCallback& callback)
   m_caching = CACHESTATE_DONE;
   m_HasVideo = false;
   m_HasAudio = false;
-  m_UpdateStreamDetails = false;
+  m_updateStreamDetails = false;
+  m_saveStreamDetails = false;
```
Comment (ksooo) [inline xbmc/cores/VideoPlayer/VideoPlayer.cpp]: No need to initialize the two members here because you have defined a default member initializer with exact the value you assign here.

Comment (78andyp) [reply xbmc/cores/VideoPlayer/VideoPlayer.cpp]: OK. Updated.

**Comment by CrystalP** [comment]
Regarding Claude's answer that stream info is not always available because the demuxer hasn't processed new packets yet...

That would mean that the streams creation by the demuxer should be the event that triggers the stream details update (through a semaphore read later by vp). Maybe checking the existing CDVDDemux::GetNrOfStreams() > 0 is good enough?

Is it necessary to react only to playlist changes or should all demuxer + stream additions be caught and evaluated? (for a more generic solution that could be helpful not only for Bluray at some point)

I believe UpdatePlayState is the wrong place for processing and that the stream details update should be moved up into Process() because UpdatePlayState's task is to update m_State (struct SPlayState).

**Comment by 78andyp** [comment]
Thanks @CrystalP 
I've made a function separate to UpdatePlayState for the stream details.

I'm not sure that the demuxer is the right place. Looking at the code:
- The demuxer is created by VideoPlayer, but there is (currently) no callback mechanism that I can see. The demuxer is aware of the inputstream but not videoplayer.
- There could (in theory) be more than one demuxer (although currently it's just ffmpeg).
- Within the demuxer streams are added dynamically as they are encountered (in ReadInternal()) so the same decision about stream completeness will still need to be made.

Given the state is maintained in videoplayer anway and it's the final common part of the pathway it seems better to keep it there.

It could be extended to other input streams - they would just need to:
1) use the callback mechanism to signal a stream change
2) handle SaveCurrentState() and UpdateItemFromSavedStates() from the virtual parent inputstream class.

**Comment by 78andyp** [comment]
@claude - looking at the current code and considering @CrystalP's comments and my responses, can you suggest a better place to put the demuxing classes rather than in the videoplayer class??

**Comment by 78andyp** [comment]
Final call for comments.

**Comment by CrystalP** [comment]
Claude misunderstood many things and regurgitated what was said before without much new analysis...

One interesting point it brought - what happens to the demuxer on playlist change? Keeps going as is, recreated, reset, ...?
The demuxer is typically ahead of the play position by a few seconds (cache)

Running tests to the end, the stream details of the movie/episode are replaced by those of the last played main playlist.
I asked in the PR how stream details imported from nfo would NOT be overwritten, the answer was "see the description". Well, I didn't get it from the description and the mechanism is failing on the tests I just ran.
It's a standard Bluray as far I can tell, with the main playlist started from the simple menu played for a few minutes then stopped.

**Comment by 78andyp** [comment]
> Claude misunderstood many things and regurgitated what was said before without much new analysis...
> 
> One interesting point it brought - what happens to the demuxer on playlist change? Keeps going as is, recreated, reset, ...? The demuxer is typically ahead of the play position by a few seconds (cache)
> 
> Running tests to the end, the stream details of the movie/episode are replaced by those of the last played main playlist. I asked in the PR how stream details imported from nfo would NOT be overwritten, the answer was "see the description". Well, I didn't get it from the description and the mechanism is failing on the tests I just ran. It's a standard Bluray as far I can tell, with the main playlist started from the simple menu played for a few minutes then stopped.

The PR didn't have anything to do with simple menus. It was about playing through the disc menu - and i've just checked - streamdetails from nfo are preserved.

I'll have a look at the interaction between simple menu and pre-existing nfo stream details and raise another PR if needed.

Regarding the demuxer - VideoPlayer calls OpenDemuxStreams() for each new playlist:
image
and the old streams are disposed of when the new streams are created.

Whilst claude has just restated what was said, it's still correct. I don't think adding a callback mechanism to demuxers is a simpler solution that this. Do feel free to amend this PR though.

**Comment by CrystalP** [comment]
From that call stack, the demuxer (and the streams) is recreated on playlist change. At the end of Open() the streams will have been created and a new boolean could be set to indicate that, and could be queried instead of an adhoc condition about video width and height?
GetNrStreams > 0 would also provide that info but there is a small window during stream creation where GetNrOfStreams > 0 but some streams haven't been created yet.

I didn't find the place in the code for the menu playback case but from the other PR, the logic is to persist stream details only if not present in the db yet, correct?
That provides a clean way to gate the feature to the specific scenario of "no stream details in videodb yet" and Bluray to avoid any processing on playlist change or every frame when it is know in advance that the result will be thrown away.

**Comment by 78andyp** [comment]
@CrystalP - the demuxer now maintains a flag, updated whenever a stream is added. This is checked prior to saving/updating the streamdetails. Is this what you had in mind??

**Comment by 78andyp** [comment]
@claude review please.

**Comment by 78andyp** [comment]
@claude review.

**Comment by 78andyp** [comment]
Unless there are any further comments I will merge soon.

**Comment by CrystalP** [comment]
let me take a look

**Comment by CrystalP** [comment]
That's a different concept, catch all stream changes. Why not, it simplifies some things.
The implementation looks race-y though. Also how do we know that m_SelectionStreams has been updated with the latest streams info and UpdateContent() ran? (important since UpdateFileItemStreamDetails() will grab info from m_content.m_selectionStreams)

The other point is that this still executes for all videos rather than only Bluray/DVD that require it, or did I miss something?

**Comment by 78andyp** [comment]
@claude evaluate the latest changes in light of @CrystalP's recent comments

**Comment by 78andyp** [comment]
@claude - if you look at ShouldUpdateStreamDetails() you will see it is only true if the streamdetails are not already derived (ie. for dvd and bluray). Other media has stream details set when it is added into the video database in CVideoInfoScanner when CDVDFileInfo::GetFileStreamDetails() is called. Revise concern 3 with this information.

**Comment by 78andyp** [comment]
Jenkins build this please

File: xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h [hunk 2]
```diff
@@ -318,6 +318,16 @@ class CDVDDemux
...
 
+  /*!
+   * \brief return true if streams have been updated, false otherwise
+   */
+  virtual bool GetStreamsUpdated() { return false; }
+
+  /*!
+   * \brief reset stream update flag
+   */
+  virtual void SetStreamsUpdated() {}
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h]: I think ResetStreamsUpdated() would be clearer

File: xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStream.h [hunk 3]
```diff
@@ -234,15 +227,54 @@ class CDVDInputStream
...
+  \param closed sets closed to indicate if the stream was closed (=true) (ie. playback stopped before end) or finished (=false)
+  \returns an UpdateState flag indicating if no main title was played (=NOT_PLAYED), the main title was played completely (=FINISHED) 
+  \        or no update needs to be made to the VideoPlayer state (=NONE)
+  */
+  virtual UpdateState UpdateItemFromSavedStates(CFileItem& item, double time, bool& closed)
+  {
+    return UpdateState::NONE;
+  }
+
+  virtual void UpdateStack(CFileItem& item) {}
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/DVDInputStreams/DVDInputStream.h]: Thanks for adding the documentation. This would be clearer if the functions hadn't moved down a bit under the definition of struct PlayListInformation.

**Review by CrystalP — COMMENTED** [review]
A few cosmetic comments.

**Comment by CrystalP** [comment]
I read through the code and tried to map the parts involved...
OK for the way that the logic is not invoked for non-Bluray (with caveats, see test results further down). The code executed per frame is light enough.

I'm wondering if the additions to the demuxer are necessary given that there is m_contentUpdated set in videoplayer. It reacts to stream creation already, a little bit after the demuxer's m_streamsUpdated is set? I wasn't really aware of the UpdateContent() flow earlier.
That would be immune to the timing issues I was worrying about earlier.
It doesn't catch stream changes mid-stream without a stream reopen, but that's not a requirement for Bluray, or is it?

That means SaveCurrentState() would check only m_contentUpdated and not GetStreamsUpdated().

Pushing that idea further, there is no need for the per-frame code, it's enough to call UpdateFileItemStreamDetails from OpenDemuxStream after UpdateContent? That worked fine in my testing, but I'm a sample of 1.

That aside, I tested playing a Bluray from menu - m_updateStreamDetails is set to false and remains false when playback of a playlist starts > the code is never triggered, stream details are not captured.
The item "menu" does not pass the conditions of ShouldUpdateStreamDetails().

Related: Claude's comment about internet streams is correct, they're not supposed to trigger the per frame checks and there is no need to capture intermediate stream details. The original behavior from a few PR back was to save stream details when playback ends (CVideoPlayer::OnExit()) for internet streams and it should be brought back.

**Comment by 78andyp** [comment]
The internet stream logic hasn't changed. It was only put in a function in #27176.
It used to be:
```
 // check if VideoPlayer should set file item stream details from its current streams
  const bool isBlu_dvd_image_or_stream = VIDEO::IsBDFile(file) || VIDEO::IsDVDFile(file) ||
                                         file.IsDiscImage() || NETWORK::IsInternetStream(file);

  const bool hasNoStreamDetails =
      (!file.HasVideoInfoTag() || !file.GetVideoInfoTag()->HasStreamDetails());

  // Always update streamdetails for bluray:// paths as existing details may be been taken from BLURAY_TITLE_INFO
  if (file.GetProperty("get_stream_details_from_player").asBoolean() ||
      (hasNoStreamDetails && isBlu_dvd_image_or_stream) ||
      URIUtils::IsBlurayPath(file.GetDynPath()))
  {
    auto& components = CServiceBroker::GetAppComponents();
    const auto appPlayer = components.GetComponent<CApplicationPlayer>();
        CServiceBroker::GetMediaManager().ResetBlurayPlaylistStatus();
#endif
      }
```

The inputstream code only exists for the dvd and bluray inputstreams - so:
```      m_pInputStream->SaveCurrentState(item.GetVideoInfoTag()->m_streamDetails);```
and
```  const CDVDInputStream::UpdateState updateState{m_pInputStream->UpdateItemFromSavedStates(fileItem, m_State.time, m_bCloseRequest)};```
Won't do anything for internet streams.

I've made the other changes as suggested. I did find one disc where one of the non-main playlists did update twice in the old code - but it's only the main playlist that needs accurate video/audio details so we can leave it like this for now and if we get reports/find an example of where it returns inaccurate info then revert to the previous iteration.

**Comment by 78andyp** [comment]
The disc that didn't work - was it a tv show disc by any chance - if so try with #27606 as well.

**Comment by 78andyp** [comment]
@claude review

**Comment by CrystalP** [comment]
Thanks for updating, I'll review.

Internet streams: slight misunderstanding. Yes they were already a part of what became ShouldUpdateStreamDetails(), but at the time it triggered only the update at the end of playback.
In the current code, it triggers the per-frame code as well, and that shouldn't have been happening (even though in the end as you wrote SaveCurrentState() does something only for Bluray)

The failing disc (any disc would do I think though!) is Alita. Select the menu as start playlist then m_updateStreamDetails is set to false and is not reevaluated when playing the main feature from main menu.

**Comment by CrystalP** [comment]
Code looks good to me now, a vast improvement. It would be better split in two because most of the diff is now cosmetic name changes, which distract from the fix.

My testing is not so successful, but for reason unrelated to the fix: I thought the use case for the feature was play from the BD menu, which can automate multiple playlists, in addition to the user having the ability to start multiple playlist from the menu. However as mentioned earlier, nothing happens for me in the use case.

I now tried with both BD as folders and BD in .iso file > same thing happens after picking "Menu" from the simple menu, m_updateStreamDetails is set to false.

* in both cases no stream details in the db yet
* for the .iso case, the dynpath is bluray://udf[long encoded path]Alita.iso%2f/menu, the regular path is identical minus the ending %2f/menu
* for the BD as folder, the dynpath is bluray://[long encoded path]Alita%20Battle%20Angel%20(2019)%5c/menu and the path is D:\BD\Alita Battle Angel (2019)\BDMV\index.bdmv

ShouldUpdateStreamDetails uses VIDEO::IsBDFile, which looks for a dynpath ending in index.bdmv or movieobject.bdmv, which is not true for any of the dynpaths in my tests.

DVD don't work for a different reason - the dynpath is identified and IsDVDFile or IsDiscImage return true, but stream details have already been populated, either by scraper/probe or by nfo.

I'll accept the fix after the minor style adjustment, but I think there are other issues with the feature to fix in another PR so that stream details capture happens as expected when using the BD menu or DVD.

**Comment by 78andyp** [comment]
@claude review

**Comment by 78andyp** [comment]
@claude - bluray menu path bug is fixed in #27676. Confine your analysis to this issue.

**Review by CrystalP — APPROVED** [review]
This is a good fix! Runtime tests successful (menu from simple menu issue handled in 27676)
Approved conditional to the typo fixes before merge.

**Comment by CrystalP** [comment]
Design-wise, the use of item properties is suspicious by default. "update_stream_details" for example, set and used within videoplayer. A CFileItem is not meant to carry temporary state within a "module". It's similar to the use of global variables, discouraged.
A side-effect is that it forces the use of CFileItem as parameter of UpdateFileItemStreamDetails() instead of the smaller more appropriate CVideoInfoTag.

Other comment about CDVDInputStream::SavePlaylistDetails(): when updating the same playlist (ex. menu loop), only lastPlaylist.watchedTime should be updated.
For the same playlist, duration and details cannot be different - or something is very wrong! I think two asserts (for peace of mind) would be preferable to unnecessary assignments
```
assert(lastPlaylist.duration == currentPlaylistInformation.duration);
assert(lastPlaylist.details == currentPlaylistInformation.details);
```

**Comment by 78andyp** [comment]
@claude - can you confirm that lines 227 and 261 do say movie and not move as you suggest.

**Comment by 78andyp** [comment]
> Design-wise, the use of item properties is suspicious by default. "update_stream_details" for example, set and used within videoplayer. A CFileItem is not meant to carry temporary state within a "module". It's similar to the use of global variables, discouraged. A side-effect is that it forces the use of CFileItem as parameter of UpdateFileItemStreamDetails() instead of the smaller more appropriate CVideoInfoTag.
> 
> Other comment about CDVDInputStream::SavePlaylistDetails(): when updating the same playlist (ex. menu loop), only lastPlaylist.watchedTime should be updated. For the same playlist, duration and details cannot be different - or something is very wrong! I think two asserts (for peace of mind) would be preferable to unnecessary assignments
> 
> ```
> assert(lastPlaylist.duration == currentPlaylistInformation.duration);
> assert(lastPlaylist.details == currentPlaylistInformation.details);
> ```

I'll see if I can do it differently in another PR.

The update was there in case the audio or subtitles 'late' to be included - I did find one example where this happened ?? something to do with the muxing. But agree duration shouldn't chage so will add that assert.
