### PR TITLE
Fix potential SQL constraint integrity violation in the PVR database

### LINKED ISSUE #172: CPVRChannelGroup - Persist: SQL constraint violation
Loading the hts plugin will frequently on reboot and the screen gets stuck in 'Starting PVR manager'.
I'm using TVHeadend with two satellite networks (Astra + Hotbird) so there are plenty of services and channels mapped. It seems the issue occurs when a video PID is missing and a channel that was classified 'tv' is changed to 'radio' or vice versa. This happens every few hours so I have to clear the TV DB on every reboot.

In this such a case the logs would give me an error like this:
```
22:13:46 T:139793007634176   ERROR: SQL: Abort due to constraint violation
        Query: INSERT INTO channels (iUniqueId, bIsRadio, bIsHidden, bIsUserSetIcon,
        bIsUserSetName, bIsLocked, sIconPath, sChannelName, bIsVirtual, bEPGEnabled, 
        sEPGScraper, iLastWatched, iClientId, idEpg) VALUES (1800902271, 1, 0, 0, 0, 0,
        'http://192.168.10.2:9981/imagecache/1577', 'Bahai Radio', 0, 1, 'client', 0, 1600, -1)
22:13:46 T:139793007634176   ERROR: CommitInsertQueries - failed to execute queries
```

At the same time TV29.db already contains the following entry in table channels:
```
sqlite> select * from channels where iUniqueId=1800902271;
1711|1800902271|0|0|0|0|0|http://192.168.10.2:9981/imagecache/1577|Bahai Radio|0|1|client|0|1600|1711
```

The records only differ in bIsRadio (insert statement wants to set it 1, exists as 0) and idEpg (insert: -1, exists: 1711). The error gets thrown because the records would share the same values for iUniqueId and iClientId (unique index).

Environment:
ArchLinux 4.3.3-2 x86_64
Kodi 15.2
kodi-addon-pvr-hts 2.1.18-1 (built from Isengard branch)

Note: I'm not sure if it's a bug in the addon or rather in the Kodi PVR manager but I understand that existing channels should have the m_iChannelId field populated in order to have the PVR manager call 'REPLACE INTO' rather than 'INSERT INTO'.

### PR DESCRIPTION
**Pull request by Jalle19**
Supersedes https://github.com/xbmc/xbmc/pull/8953
Fixes trac #16031
Closes kodi-pvr/pvr.hts#172

This fixes the problem without bumping the database version so it should be more possibly to get it merged for V17.

Basically the code that persists channels has been made smarter. Instead of just blindly looking at the primary key stored in the object we query the database to check if a channel with the unique ID and client ID already exists. If it does, we update that channel, if not we create a new channel. There is more background information in the referenced PRs.

This fix also has the added side-effect that it increases database performance. While a new SELECT statement has been added, we now do an UPDATE instead of a REPLACE INTO which prevents indexes from having to be re-calculated (REPLACE INTO basically does a DELETE followed by an INSERT). This also means we don't need to worry about the channel ID changing after the channel has been updated (which was a side effect of using REPLACE INTO).

@ksooo now's a good time to test that new review feature, @Glenn-1990 can you runtime test this? I tested with your reproducible test case (change a channel's service from TV to radio while Kodi is off) and it seems to fix the issue.

### CODE REVIEW

File: xbmc/pvr/PVRDatabase.cpp [hunk 1]
```diff
@@ -625,31 +624,25 @@ bool CPVRDatabase::Persist(CPVRChannel &channel)
...
+        "iUniqueId = %i, bIsRadio = %i, bIsHidden = %i, bIsUserSetIcon = %i, bIsUserSetName = %i, bIsLocked = %i, "
+        "sIconPath= %s, sChannelName = %s, bIsVirtual = %i, bEPGEnabled = %i, sEPGScraper = %s, iLastWatched = %u, "
+        "iClientId = %i, idChannel = %i, idEpg = %i "
+        "WHERE iUniqueId = %i AND iClientId = %i",
         channel.UniqueID(), (channel.IsRadio() ? 1 :0), (channel.IsHidden() ? 1 : 0), (channel.IsUserSetIcon() ? 1 : 0), (channel.IsUserSetName() ? 1 : 0), (channel.IsLocked() ? 1 : 0),
         channel.IconPath().c_str(), channel.ChannelName().c_str(), 0, (channel.EPGEnabled() ? 1 : 0), channel.EPGScraper().c_str(), channel.LastWatched(), channel.ClientID(),
-        channel.ChannelID(),
-        channel.EpgID());
-  }
+        channel.ChannelID(), channel.EpgID(), channel.UniqueID(), channel.ClientID());
```
Comment (xhaggi) [inline xbmc/pvr/PVRDatabase.cpp]: no need to update iUniqueId and iClientId as they are part of the where condition.

**Review by xhaggi — CHANGES_REQUESTED** [review]

**Comment by bkuhls** [comment]
@Jalle19: You referenced pull request 8963 but I think you mean PR 8953, right?

**Comment by Jalle19** [comment]
@bkuhls you're right, I meant https://github.com/xbmc/xbmc/pull/8953

File: xbmc/pvr/PVRDatabase.cpp (hunk 1 above)
Comment (Jalle19) [inline xbmc/pvr/PVRDatabase.cpp]: You're right, that's a left over from when it used REPLACE INTO

**Comment by Glenn-1990** [comment]
@Jalle19 thanks for this, now I can remove the "delete pvr database" script from my clients. I will test this tomorrow. :-)

File: xbmc/pvr/PVRDatabase.cpp (hunk 1 above)
Comment (Jalle19) [inline xbmc/pvr/PVRDatabase.cpp]: Fixed in the latest fixup commit

**Review by xhaggi — APPROVED** [review]
thx

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by Memphiz** [comment]
@Jalle19 i am currently working on new jenkins slave and need the server for some more time. I have canceled your build request and will mail around once i am done.

File: xbmc/pvr/PVRDatabase.h [hunk 2]
```diff
@@ -185,6 +185,14 @@ namespace PVR
...
 
     bool RemoveChannelsFromGroup(const CPVRChannelGroup &group);
+
+    /*!
+     * Checks whether the specified unique combination for a channel exists in the database
+     * @param iClientId
+     * @param iUniqueId
+     * @return
+     */
+    bool ChannelExists(int iClientId, int iUniqueId);
```
Comment (ksooo) [inline xbmc/pvr/PVRDatabase.h]: shouldn't this member function be 'const'?

File: xbmc/pvr/PVRDatabase.cpp [hunk 3]
```diff
@@ -667,3 +659,14 @@ bool CPVRDatabase::UpdateLastWatched(const CPVRChannelGroup &group)
 
   return ExecuteQuery(strQuery);
 }
+
+bool CPVRDatabase::ChannelExists(int iClientId, int iUniqueId)
+{
+  std::string strQuery = PrepareSQL("SELECT idChannel FROM channels WHERE iClientId = %d AND iUniqueId = %d",
```
Comment (ksooo) [inline xbmc/pvr/PVRDatabase.cpp]: const std::string strQuery(Prepare... ?

**Review by ksooo — APPROVED** [review]
despite from const nitpicking this is looking good to me, though i have not runtime tested it.

File: xbmc/pvr/PVRDatabase.h (hunk 2 above)
Comment (Jalle19) [inline xbmc/pvr/PVRDatabase.h]: I would like that too, but all database access methods are non-const only.

File: xbmc/pvr/PVRDatabase.cpp (hunk 3 above)
Comment (Jalle19) [inline xbmc/pvr/PVRDatabase.cpp]: Sure

**Comment by Jalle19** [comment]
@Memphiz okay, no problem.

**Comment by Glenn-1990** [comment]
@Jalle19 run time tested: reproduced the issue and restarted kodi several times, PVR manager was not starting up, then applied your commits and it came back to life ;-)

**Comment by Glenn-1990** [comment]
Btw, do we need the same for channel groups?

**Comment by Jalle19** [comment]
I need to check, I've never thought about that scenario.

File: xbmc/pvr/PVRDatabase.h (hunk 2 above)
Comment (ksooo) [inline xbmc/pvr/PVRDatabase.h]: yikes. So, leave it like it is, i'd say.

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
jenkins build this please

**Comment by Jalle19** [comment]
@ksooo good to go?

**Comment by ksooo** [comment]
> Btw, do we need the same for channel groups?

 what about this? supposed to be handled in another PR?

**Comment by Jalle19** [comment]
Yeah I'd say so, I'm not even sure if there's an issue in that regard yet.

**Comment by Jalle19** [comment]
@ksooo the code for persisting channel groups is very similar to what we had here. I would still prefer to get this merged so I have time to think of a proper solution for the groups part, if that's okay with you?

**Comment by Jalle19** [comment]
Actually the persisting of groups cannot have this exact same issue because there's no `UNIQUE INDEX` that could trigger an integrity violation. It still uses `REPLACE INTO` though which is not nice, but the performance impact is much lesser since one can assume that `num(channels) > num(groups)`.

**Comment by ksooo** [comment]
> Actually the persisting of groups cannot have this exact same issue

 thanks for the update on this.
