### PR TITLE
[subtitles] Align to screen image based subtitles when video source is cropped

### LINKED ISSUE #21141: Image based subtitles in Nexus
### Describe the bug
Here is a clear and concise description of what the problem is:

Image based subtitles stretch in 2.40ar video files, compress in 4:3 videos
Kodi matrix used to scale them to display resolution (most of displays being 16:9 AND on ultrawide monitors you could scale to a 16:9 resolution but it doesn't work anymore in the latest kodi nexus nightly) but the latest kodi nexus nightly scales the subtitles to video resolution which distorts them

## Expected Behavior

subtitles should be scaled to display resolution

## Actual Behavior

subtitles are scaled to video resolution which compresses them

### To Reproduce

1. video file https://drive.google.com/file/d/1Pgl7ZoYyCsROz4yABWSAnwMaQlhkS2bf/view?usp=drivesdk
2. I have included 3 subtitles in this mkv which can cycled through in kodi to see the behaviour

### Debuglog

The debuglog can be found here:

### Screenshots
Here are some links or screenshots to help explain the problem:

Kodi 19 overscan
immagine
Kodi 20 overscan
immagine
Kodi 20
immagine

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

this is most certainly a down grade compared to Matrix

### Your Environment
Used Operating system:

 - [ ✓] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] OSX
 - [ ✓] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version: 20 Nexus 20220315

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by CastagnaIT**
## Description

This introduce a different behaviour for scaling/stretching for image based subtitles, that concern cropped video cases only.

Now if a video has been cropped and the subtitles have been created for non-cropped video,
subtitles will be aligned to the screen by keeping the aspect-ratio, instead of align to video that cause to show subtitles distorted/squashed.

## Motivation and context

Time ago merged PR #20204 (with some revert with #20794) to fix issue #14866,
mainly i have changed the alignment from `ALIGN_SCREEN` to `ALIGN_VIDEO`.
This change allow to show the PGS/Vobsub correctly as happens on VLC/MPV players, respecting the correct positioning and appearance (even when the window is resized).

But (as happens on all other players) this cause a side effect with the videos that has been remuxed and cropped (removed black bars).

When a video is cropped have less height than the original source, if the subtitle images are scaled to the cropped video source (ALIGN_VIDEO) the subtitles will be displayed distorted/squashed, as i example in this issue #21141.

Then instead add another setting i have add a check to compare the subtitle size param to the video source, in this way we can understand if the video has been cropped, and align the subtitles to screen by keeping the aspect ratio `ALIGN_SCREEN_AR`.

This fix #21141 i have tested with the provided video and all my PGS/Vobsub/SUP with success

This partially re-add the code of #20204 to keep aspect ratio, but should not affect bluray menu, because use full resolution for menu. I have tested with a my bluray sample but it do not have a java menu and kodi do not handle it in good way, in any case i do not see regression for this case.

@thexai please can you try with your "Viuda negra" bluray that have java menu?

i will prepare an artifact to allow testing

## How has this been tested?

From our FTP folder: samples_new/subtitles/PGS/

**La.dolce.vita.1960.1080p.Criterion.Bluray.DTS.x264.mkv** (cropped video with cropped subtitles resolution, subtitles must be shown inside video not in the black bars and _aligned to the video_)

**PGS_StretchingTest.mkv** (4/3 video and same thing for subtitles, subtitles must be shown with right aspect ratio and _aligned to the video_)

**A Global Journey_cropped.mkv** (this is a cropped video with full 1080p subtitle. With the first sub track : original english, subtitles must be appears with right aspect ratio, _aligned to the screen_)

**Bohemian.Rhapsody.2018.4K.PGS.at.1080.mkv** (this is a full 4K video resolution with full 1080p subtitle, subtitles must be appears _aligned with the video_)

## What is the effect on users?

Have a better aspect ratio of subtitles when used with cropped videos,
and so allow to see subtitles with right aspect ratio on ultrawide monitor's

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by CastagnaIT** [comment]
test builds:
Android armv8: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20220322-c598214c-subtitleimage-24796-armeabi-v7a.apk
Android arm64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20220322-c598214c-subtitleimage-22115-arm64-v8a.apk
Windows 64bit: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220321-c598214c-subtitleimage-x64.exe

**Comment by enen92** [comment]
I've runtime tested this and seems to work just fine. I like the approach to avoid yet another setting. Bluray menus work fine too.

**Using vobsub subs (while toggling different zoom modes):**

Screenshot from 2022-03-22 09-42-51

Screenshot from 2022-03-22 09-43-12

Screenshot from 2022-03-22 09-43-30

Subtitles scale correctly depending on the "crop" percentage.

I am wondering if we could have the same for text based subtitles though. Adding an external subtitle to the same DVD and the behavior is different:

image

Screenshot from 2022-03-22 09-40-00

Screenshot from 2022-03-22 09-40-46

**Review by enen92 — APPROVED** [review]
Nice improvement! As long as the BR menus don't break (and @thexai reports a +1) I am fine with this.
Wondering if we couldn't have similar behavior for text subs.

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererGL.cpp [hunk 1]
```diff
@@ -185,17 +185,42 @@ COverlayTextureGL::COverlayTextureGL(CDVDOverlayImage* o)
...
+      m_align = ALIGN_SCREEN_AR;
+
+      m_width = static_cast<float>(o->width);
+      m_height = static_cast<float>(o->height);
+      m_source_width = static_cast<float>(o->source_width);
+      m_source_height = static_cast<float>(o->source_height);
+    }
+    else
+    {
+      // Should never happens, in case stretch to screen resolution
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererGL.cpp:218]:
```suggestion
      // Should never happen, in case stretch to screen resolution
```

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererGL.h [hunk 2]
```diff
@@ -24,8 +24,12 @@ namespace OVERLAY {
   class COverlayTextureGL : public COverlay
   {
   public:
-     explicit COverlayTextureGL(CDVDOverlayImage* o);
-     explicit COverlayTextureGL(CDVDOverlaySpu* o);
+    /*! \brief Create the overlay for the rendering
```
Comment (enen92) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererGL.h:27]:
```suggestion
    /*! \brief Create the overlay for rendering
```

**Comment by thexai** [comment]
Sorry to disagree but this PR changes everything again and introduces a lot of side effects on original 4K sources (not cropped):

current master:
ma-Captura de pantalla 2022-03-22 110346

ma-Captura de pantalla 2022-03-22 105654

PR:
Captura de pantalla 2022-03-22 110836

Captura de pantalla 2022-03-22 111644

PR stretch all subtitles and UHD overlays on 4K sources (not cropped)

**Review by thexai — CHANGES_REQUESTED** [review]
> This introduce a different behaviour for scaling/stretching for image based subtitles, that concern **cropped video cases only**.

I don't approve of it because it doesn't do what it's supposed to do.
That is, with original video sources (not cropped) it should not change anything.

Probably the only solution is a new setting to enable this optionally (default disabled). I'm not asking for it, for me the master branch is fine as it is now.

**Comment by thexai** [comment]
> Now if a video has been cropped and the subtitles have been created for non-cropped video,

This is a "bad source"

**Comment by CastagnaIT** [comment]
it is not a bad source, often black bars are cropped from video dvd/bd rip
i will try to see a way to exclude bluray from this behaviour

**Comment by thexai** [comment]
> i will try to see a way to exclude bluray from this behaviour

It's not about "excluding" DVD / Blu-Ray / UHD Blu-Ray / MKV untouched remuxes...

It is about adding a "special corner case" cropped video + not cropped PGS subs without break all other things.

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererDX.cpp [hunk 3]
```diff
@@ -213,17 +213,42 @@ COverlayImageDX::COverlayImageDX(CDVDOverlayImage* o)
...
+      m_align = ALIGN_SCREEN_AR;
+
+      m_width = static_cast<float>(o->width);
+      m_height = static_cast<float>(o->height);
+      m_source_width = static_cast<float>(o->source_width);
+      m_source_height = static_cast<float>(o->source_height);
+    }
+    else
+    {
+      // Should never happens, in case stretch to screen resolution
```
[the remark this answers is not in the document]
Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererDX.cpp:246]: no reference to display resolution here, but subtitle res vs video (file) source res

i have now tested some mkv 4k (cropped and not cropped) and i have found PGS resolution is always set as 1080p
that is now rendered stretched, then i have to change again these conditions

use a kind of exclusion is more safe, but to try understand to avoid add it,
i need to know what values have these variables when the BD menu appear:
`o->source_height`
`rSource.Height`
can you provide these values?

for example with my sample BD i have:
`o->source_height` 1080
`rSource.Height` 1080

[the remark this answers is not in the document]
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererDX.cpp]: Right now i can't test but i remember 3840, 2160 in `rSource` with Viuda Negra UHD BD. I'll confirm tomorrow.

[the remark this answers is not in the document]
Comment (thexai) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererDX.cpp]: Now looks better

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererGL.cpp [hunk 4]
```diff
@@ -185,17 +185,35 @@ COverlayTextureGL::COverlayTextureGL(CDVDOverlayImage* o)
...
+      // We check also for multiple of source_height because for
+      // example 1080P subtitles can be used on 4K videos
+      m_align = ALIGN_VIDEO;
+      m_width = static_cast<float>(o->width) / o->source_width;
+      m_height = static_cast<float>(o->height) / o->source_height;
+    }
+    else
+    {
+      // If the source_height is higher than the video source height (rSource)
+      // means that the video has been remuxed/cropped (removed black bars).
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererGL.cpp:207]:
```suggestion
      // means that the video has been recoded/cropped (removed black bars).
```
Remux only does not remove black bars

**Comment by CastagnaIT** [comment]
New artifacts builds:
Win64bit: http://mirrors.kodi.tv/test-builds/windows/win64/KodiSetup-20220323-495403da-subtitleimage-x64.exe
Android armv7: http://mirrors.kodi.tv/test-builds/android/arm/kodi-20220323-495403da-subtitleimage-24817-armeabi-v7a.apk
Android arm64: http://mirrors.kodi.tv/test-builds/android/arm64-v8a/kodi-20220323-495403da-subtitleimage-22136-arm64-v8a.apk

**Review by thexai — APPROVED** [review]
Tested and confirmed that now is working fine with 1080p and 4K untouched (AR = 16/9) video sources.

**Comment by CastagnaIT** [comment]
please wait to merge, i want test a bit more

**Comment by CastagnaIT** [comment]
ok i have done,
i have add a condition check also for the width, no change behaviour,
but this fix cases with 4/3 video resolution + 1080p subtitles

also done a couple of test with DVB subtitles samples all ok

File: xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererDX.cpp [hunk 5]
```diff
@@ -213,17 +213,35 @@ COverlayImageDX::COverlayImageDX(CDVDOverlayImage* o)
...
-    m_width = static_cast<float>(o->width) / o->source_width;
-    m_height = static_cast<float>(o->height) / o->source_height;
+
+    m_x = (0.5f * o->width + o->x) / o->source_width;
+    m_y = (0.5f * o->height + o->y) / o->source_height;
+
+    if ((o->source_height == static_cast<int>(rSource.Height()) ||
+         (static_cast<int>(rSource.Height()) % o->source_height == 0)) &&
+        (o->source_width == static_cast<int>(rSource.Width()) ||
+         (static_cast<int>(rSource.Width()) % o->source_width == 0)))
```
Comment (thexai) [inline xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererDX.cpp:226]: This code is hard to understand what do due excess of parentheses 😓

Can you please change to something like:

```c++
    int sh = static_cast<int>(rSource.Height());
    int sw = static_cast<int>(rSource.Width());

    if ((o->source_height == sh || sh % o->source_height == 0) &&
        (o->source_width == sw || sw % o->source_width == 0))
    {
```

Comment (CastagnaIT) [reply xbmc/cores/VideoPlayer/VideoRenderers/OverlayRendererDX.cpp]: yes done

**Review by thexai — APPROVED** [review]

**Comment by MediaBrasil** [comment]
@thexai 

Using screen 4K, I notice 2 issues after this commit, the external subtitle was moved to screen top, and the broken bd-java menu, don´t load more. I will test a little more.

**Comment by sugatam** [comment]
For cropped video where verticalshift is introduced, PGS subtitles don't honor the shift. I routinely shift cropped 1080p videos by -0.75 in my projector setup that has bottom masking only, but this causes the subtitles to drop down into the black bars.

**Comment by sugatam** [comment]
Sorry about that Stefano. TBC, when I'm shifting the video via supported methods, I expect overlays to shift with it, so I consider this a bug (it does the right thing when shifting uncropped video). But sorry about posting on this PR, I'll use the right channel (or try submitting a PR myself).
