### PR TITLE
Enforce minimum interval between add-on repository updates

### LINKED ISSUE #24829: Repeated `addons.xml.gz` download when unable to write to `~/.kodi/userdata/Database/AddonsXX.db`
## Bug report

Disk or file system corruption causes xbmc to repeatedly download the `addons.xml.gz` file.
As this seems to be happen quite a lot with consumer hardware (worn out flash drives/cards?), this effectively causes a distributed denial of service (DDoS) attack against mirror servers (like mine) providing this data.

### Describe the bug
If xbmc is unable to write to the SQLite database at `~/.kodi/userdata/Database/AddonsXX.db` as part of the `database.SetRepoUpdateData` invocation in `RepositoryUpdater.cpp`, the `nextcheck` column remains unchanged instead of configuring another attempt in (at least) one hour.

I simulated a re-download with a disk failure as follows:

 - configure manual updates in kodi
 - create LVM volume and mount it at `~/.kodi/userdata/Database`, copy over old DB information, adapt permissions
 - unset "checksum" column in "repo" table
 - start kodi
 - `umount -l ~/.kodi/userdata/Database`
 - trigger update

As a result of this, mirrors see repeated downloads. I tweaked `/usr/share/kodi/addons/repository.xbmc.org/addon.xml` to always use my mirror `ftp.halifax.rwth-aachen.de`. On the server I see this (limited to my own IP address):

```
1709997208.710 1247300 0.088 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997209.512 1247300 0.113 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997210.230 1247300 0.148 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997210.953 1247300 0.123 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997211.766 1247300 0.136 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997212.627 1247300 0.134 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997213.398 1247300 0.148 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997214.288 1247300 0.157 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997215.011 1247300 0.136 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997215.946 1247300 0.176 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
1709997216.930 1247300 0.239 GET /xbmc/addons/nexus/addons.xml.gz HTTP/2.0
```

The debug logs show (limited to "grep decompressing", as this happens once per download):
```
2024-03-09 16:14:32.113 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:32.904 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:33.615 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:34.409 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:35.201 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:36.047 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:36.852 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:37.711 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:38.490 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:39.449 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
2024-03-09 16:14:40.400 T:2002858   debug <general>: CRepository 'https://ftp.halifax.rwth-aachen.de/xbmc/addons/nexus/addons.xml.gz' is gzip. decompressing
```

Note the short delay of around a second between each download.

## Expected Behavior
Kodi waits before it issues another download request.

## Actual Behavior
The `addons.xml.gz` file is downloaded roughly once a second, possibly only limited by network/mirror/device speed.

## Possible Fix
 In-memory "persistence" might be necessary for this, but possibly it's better to crash/exit in case of DB (write) issues.

### To Reproduce
See above.

### Debuglog
[kodi.log](https://github.com/xbmc/xbmc/files/14546789/kodi.log)

### Your Environment
Tested with Debian, version 2:20.1+dfsg-1. On the mirror I see this with various versions of kodi/xbmc/osmc, though.

### PR DESCRIPTION
**Pull request by yol**
## Description
Repository update can fail in a way that would lead to an immediate reschedule of the update. A common reason would be a failure to update the `nextcheck` column of the `repo` table. This leads to mirror and repository servers getting constantly hammered.

Since there is no reason to have a smaller update interval than an hour anyway, we just enforce this as the minimum in all regular updates. This should catch all possible errors leading to a continuous series of requests.

## Motivation and context
#24829 

## How has this been tested?
Manual test stepping through common cases with the debugger on my machine.

## What is the effect on users?
Their broken RPi will not saturate their internet connection any more...

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

File: xbmc/addons/RepositoryUpdater.cpp [hunk 1]
```diff
@@ -332,6 +332,18 @@ void CRepositoryUpdater::ScheduleUpdate()
               nextCheck.GetAsLocalizedDateTime(), delta / 1000);
   }
 
+  if (scheduleType == UpdateScheduleType::Regular) {
+    // Enforce minimum hold-off time of 1 hour between regular updates - this is especially 
+    // important to handle all sorts of failure cases (e.g., failure to update the add-on database)
+    // that would otherwise lead to an immediate new update attempt and continuous hammering of the servers.
+    delta = std::max(1 * 60 * 60 * 1'000, delta);
```
Comment (lrusak) [inline xbmc/addons/RepositoryUpdater.cpp:339]: Can we just use std::chrono types?

File: xbmc/addons/RepositoryUpdater.h [hunk 2]
```diff
@@ -54,12 +54,20 @@ class CRepositoryUpdater : private ITimerCallback, private IJobCallback, public
    */
   void Await();
 
+  enum class UpdateScheduleType
+  {
+    /// Update should be scheduled as the first update after application start or setting change
```
Comment (lrusak) [inline xbmc/addons/RepositoryUpdater.h:59]: Are these doxygen comments? https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#92-doxygen

**Comment by ksooo** [comment]
@yol Your PR is for master, thus v22. For Omega, you need to open backport PR heading for Omega branch.

File: xbmc/addons/RepositoryUpdater.cpp (hunk 1 above)
Comment (yol) [reply xbmc/addons/RepositoryUpdater.cpp:339]: no

Comment (yol) [reply xbmc/addons/RepositoryUpdater.cpp:339]: I'll do another PR for changing the whole file to chrono later, but for omega I want to have it as nonintrusive as possible

**Review by neo1973 — APPROVED** [review]
Lgtm. Tested triggering updates manually and they happen immediately, didn't check for actual waiting for the regular update interval.

File: xbmc/addons/RepositoryUpdater.cpp (hunk 1 above)
Comment (lrusak) [reply xbmc/addons/RepositoryUpdater.cpp:340]: Boooo 😛

**Review by lrusak — APPROVED** [review]
