### PR TITLE
[Windows] Implements WS-Discovery daemon and enables browse SMB shares

### LINKED ISSUE #18840: legacy smb implementation still at the gui
### Describe the bug
Here is a clear and concise description of what the problem is:

When adding a smb networks share at Kodi it still shows the the "Windows Network Share" option that is not working with an recent system. So as user you need to know that this option is not working and they need to add it with "add network Location".
image

The out of the box experience should just work and should not depend at highly insecure and outdated stuff that is not existing anymore at any recent system.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

If you select the windows network you should be able to add windows network shares.

## Actual Behavior

If you select the windows network you can't add windows network shares.

## Possible Fix

- Rename that option to make clear that is just for the legacy SMB1 protocol nobody should use today.
- Remove that option completely
- maybe other ideas ?

### To Reproduce

1. add a network share
2. select windows network

### Debuglog

The debuglog can be found here:
no debuglog needed

### Screenshots 
Here are some links or screenshots to help explain the problem:

screenshot above

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

-

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows/LE10
 - Kodi version: 19.0 Beta1

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Implements WS-Discovery daemon and enables browse SMB shares

Continues from https://github.com/xbmc/xbmc/pull/19499 due Jenkins failures unrelated to code build.

Also implements improvements in the interface (v2):

- Aux. function to create `CClientNotificationSink` class is now inside class as static method.
- Is not longer need obtain sink pointer to get Servers IPs list.

All is handled from `CWSDiscoverySupport` class:

```c++
auto wsd = CWSDiscoverySupport::Get();

wsd->IsInitialized();

wsd->ThereAreServers();

wsd->GetServersIPs();
```

Fixes https://github.com/xbmc/xbmc/issues/18840 (on Windows only)

## Motivation and Context
Since Windows 10 no longer supports SMBv1 (deprecated) it is not possible browse SMB shares from the file explorer or when adding media sources.

This PR enables this functionality again (Windows desktop only) using the WS-Discovery protocol.

WS-Discovery is enabled by default on all Windows 10 installations and is well supported from Windows 7:
https://en.wikipedia.org/wiki/WS-Discovery

## How Has This Been Tested?
Runtime tested with various devices in LAN.
Are detected all computers running Windows 10 as well network storage devices (NAS).
Is possible to open SMB shared folders and navigate directory tree.

Users in forum (Team members) have reported satisfactory results with Synology and QNAP:
https://forum.kodi.tv/showthread.php?tid=361870&pid=3028922#pid3028922
https://forum.kodi.tv/showthread.php?tid=361870&pid=3028980#pid3028980

## Screenshots (if appropriate):
screenshot00000

screenshot00001

On NAS and similar devices it may be necessary to enable this option:
Captura de pantalla 2021-04-02 132155

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [X] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by lrusak** [comment]
Please don't just create a new PR because the build is failing....

**Comment by thexai** [comment]
> Jenkins failures unrelated to code build.

**Comment by lrusak** [comment]
> > Jenkins failures unrelated to code build.

You have slack access, Please ping someone so we can actually fix a problem.

When you open an new PR you remove the previous discussions from the context. You also may lose reviewers if people that commented on the last PR aren't pinged on the new one. Please just keep that in mind :smiley:

**Comment by jjd-uk** [comment]
Just to confirm here that I've tested this and it works with Kodi on Win10 to SMB3 shares configured on Win10, Synology and QNAP devices.

File: xbmc/platform/win32/network/WSDiscoveryWin32.cpp [hunk 1]
```diff
@@ -0,0 +1,287 @@
...
+
+  LPCWSTR address = nullptr;
+  service->GetRemoteTransportAddress(&address);
+
+  if (list && address)
+  {
+    std::wstring type(list->Next->Element->LocalName);
+    std::wstring addr(address);
+
+    CLog::Log(LOGINFO,
```
Comment (fuzzard) [inline xbmc/platform/win32/network/WSDiscoveryWin32.cpp:66]: Does this need to be loginfo? Better to have this as logdebug?

File: xbmc/platform/win32/network/WSDiscoveryWin32.cpp [hunk 2]
```diff
@@ -0,0 +1,287 @@
...
+      std::wstring addr(address);
+      const std::wstring ip = addr.substr(0, addr.find(L":", 0));
+
+      auto it = std::find(m_serversIPs.begin(), m_serversIPs.end(), ip);
+
+      // inserts server IP if not exist in list
+      if (it == m_serversIPs.end())
+      {
+        m_serversIPs.push_back(ip);
+        CLog::Log(LOGINFO, "[WS-Discovery]: IP '{}' has been inserted into the server list.",
```
Comment (fuzzard) [inline xbmc/platform/win32/network/WSDiscoveryWin32.cpp:82]: Same again, any real reason to keep as info and not debug?

File: xbmc/platform/win32/network/WSDiscoveryWin32.cpp [hunk 3]
```diff
@@ -0,0 +1,287 @@
...
+    m_provider->SetAddressFamily(WSDAPI_ADDRESSFAMILY_IPV4);
+
+    if (S_OK == CClientNotificationSink::Create(&m_sink))
+    {
+      if (S_OK == m_provider->Attach(m_sink))
+      {
+        if (S_OK == m_provider->SearchByType(nullptr, nullptr, nullptr, nullptr))
+        {
+          m_initialized = true;
+          CLog::Log(LOGINFO, "[WS-Discovery]: Daemon initialized successfully. Now are listening "
```
Comment (fuzzard) [inline xbmc/platform/win32/network/WSDiscoveryWin32.cpp:217]: Any need for the verbosity here? Keep it simple, daemon started. The hello/bye stuff can just be a code comment if needed imo

**Comment by fuzzard** [comment]
In general, loginfo for start/stop, everything else should be logdebug

File: xbmc/platform/win32/network/WSDiscoveryWin32.cpp (hunk 3 above)
Comment (thexai) [reply xbmc/platform/win32/network/WSDiscoveryWin32.cpp]: Done!

**Comment by thexai** [comment]
> In general, loginfo for start/stop, everything else should be logdebug

Done!

File: xbmc/platform/win32/network/WSDiscoveryWin32.cpp [hunk 4]
```diff
@@ -0,0 +1,291 @@
...
+    delete this;
+
+  return newRefCount;
+}
+
+//==================================================================================
+
+std::shared_ptr<CWSDiscoverySupport> CWSDiscoverySupport::Get()
+{
+  static std::shared_ptr<CWSDiscoverySupport> sWSD(new CWSDiscoverySupport);
```
Comment (lrusak) [inline xbmc/platform/win32/network/WSDiscoveryWin32.cpp:188]:
```suggestion
  static std::shared_ptr<CWSDiscoverySupport> sWSD = std::make_shared<CWSDiscoverySupport>();
```

File: xbmc/platform/win32/network/WSDiscoveryWin32.h [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+
+  HRESULT STDMETHODCALLTYPE Add(IWSDiscoveredService* service);
+  HRESULT STDMETHODCALLTYPE Remove(IWSDiscoveredService* service);
+  HRESULT STDMETHODCALLTYPE SearchFailed(HRESULT hr, LPCWSTR tag);
+  HRESULT STDMETHODCALLTYPE SearchComplete(LPCWSTR tag);
+  HRESULT STDMETHODCALLTYPE QueryInterface(REFIID riid, void** object);
+  ULONG STDMETHODCALLTYPE AddRef();
+  ULONG STDMETHODCALLTYPE Release();
+
+  bool ThereAreServers() { return m_serversIPs.size(); };
```
Comment (lrusak) [inline xbmc/platform/win32/network/WSDiscoveryWin32.h:35]:
```suggestion
  bool ThereAreServers() { return m_serversIPs.size() > 0; }
```

File: xbmc/platform/win32/network/WSDiscoveryWin32.cpp (hunk 4 above)
Comment (thexai) [reply xbmc/platform/win32/network/WSDiscoveryWin32.cpp]: Done!

File: xbmc/platform/win32/network/WSDiscoveryWin32.h (hunk 5 above)
Comment (thexai) [reply xbmc/platform/win32/network/WSDiscoveryWin32.h]: Done!

**Comment by thexai** [comment]
Added a new block to `CWSDiscoverySupport::ResolveHostName(const std::wstring serverIP)` because some users have reported hostName resolution failed. Is not a big problem because only difference is IPs listed instead of PC names and SMB conection works anyway, although I prefer fix it....

New code block is:

```c++
  else
  {
    CLog::LogF(LOGWARNING, "DnsQuery_W for '{}' failed. Trying an fallback method...", reverse);

    WCHAR host[NI_MAXHOST] = {};
    struct sockaddr_in sa = {};
    sa.sin_family = AF_INET;

    if (1 == InetPtonW(AF_INET, serverIP.c_str(), &sa.sin_addr))
    {
      if (0 == GetNameInfoW((const sockaddr*)(&sa), sizeof(sa), host, NI_MAXHOST, nullptr, 0, 0))
        hostName = host;
      else
        CLog::LogF(LOGERROR, "GetNameInfoW failed.");
    }
    else
      CLog::LogF(LOGERROR, "InetPtonW failed.");
  }
```

Not added into new commit so as not to break Jenkins again 😜

**Comment by thexai** [comment]
Is everything good?

@Paxxi, @lrusak 
Please take a final look. I would like to merge it soon.

**Review by lrusak — APPROVED** [review]
LGTM.

I noticed that you used `CLog::LogF` in a couple places, just be aware that this only logs the function name not the class so if the function name isn't very unique it can be pretty useless. That's up to you though and I'm fine with it as is.

**Comment by thexai** [comment]
This is something that I did not know but in the other PR it was using `LogF` for all and the name of the class did appear in the logs:

https://github.com/xbmc/xbmc/pull/19499#issuecomment-813082253   🤔

**Comment by lrusak** [comment]
> This is something that I did not know but in the other PR it was using `LogF` for all and the name of the class did appear in the logs:
> 
> [#19499 (comment)](https://github.com/xbmc/xbmc/pull/19499#issuecomment-813082253)

I'm not really sure how that's possible if you look at the function definition: https://github.com/xbmc/xbmc/blob/b3dd9c9d7410ba4ba12ddc9637c006ced0db2002/xbmc/utils/log.h#L143

You'll see it just uses the macro __FUNCTION__. This may do something different on windows I guess.

So for example `CLog::LogF(LOGERROR, "GetNameInfoW failed.");` I would expect to see:
```
2021-04-04 20:47:21.449 T:13196  ERROR <general>: ResolveHostName: GetNameInfoW failed.
```
