### PR TITLE
webOS: fix Cryptodome by adding site-packages to PYTHONPATH

### LINKED ISSUE #26814: webOS: No module named 'Crypto', No module named 'Cryptodome'
### Describe the bug
Here is a clear and concise description of what the problem is:

The webOS version seems to have an issue in finding the relevant python3 modules provided by script.module.pycryptodome, such as Crypto and Cryptodome.

This means plugins that use it's functionality such as https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore are not working when those modules are needed.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

The modules are present and should be found

## Actual Behavior

The plugin generates an exception, which is really unhelpful to the end user, but renders the part of the plugin not working.

## Possible Fix

Investigating but not known.

### To Reproduce

1. Compile kodi from source for webOS/install nightly
2. Install IPK to TV
3. Install plugin (e.g. catchup live TV plugin above)
4. Load catch-up TV and more plugin in kodi
5. Goto Live TV->UK->Channel 5 from My5
6. Throws error (need to check logs to get the actual error)

### Debuglog

The debuglog can be found here:
Full log is here but relevant is below: https://pastebin.com/8TmdnY8C
```
2025-05-30 09:54:41.200 T:3458    error <general>: [Catch-up-TV-&-More.support] 'unable to import route module: resources.lib.channels.uk.my5'
                                                   Traceback (most recent call last):
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/uk/my5.py", line 22, in <module>
                                                       from Crypto.Cipher import AES
                                                   ModuleNotFoundError: No module named 'Crypto'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 248, in get_route
                                                       importlib.import_module(module_path)
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/importlib/__init__.py", line 90, in import_module
                                                       return _bootstrap._gcd_import(name[level:], package, level)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
                                                     File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
                                                     File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
                                                     File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
                                                     File "<frozen importlib._bootstrap_external>", line 995, in exec_module
                                                     File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/plugin.video.catchuptvandmore/resources/lib/channels/uk/my5.py", line 26, in <module>
                                                       from Cryptodome.Cipher import AES
                                                   ModuleNotFoundError: No module named 'Cryptodome'
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 300, in run_callback
                                                       route = self.get_route(self.selector)
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/media/developer/apps/usr/palm/applications/org.xbmc.kodi/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 250, in get_route
                                                       raise RouteMissing("unable to import route module: %s" % module_path)
                                                   codequick.support.RouteMissing: 'unable to import route module: resources.lib.channels.uk.my5'
```

### Screenshots 
Here are some links or screenshots to help explain the problem:

N/A

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

Cryptodome on the TV:
```
~/apps/usr/palm/applications/org.xbmc.kodi/lib/python3.12/site-packages/Cryptodome $ ls -la
total 60
drwxrwxr-x   13 1005     1005          4096 May  9 06:15 .
drwxrwxr-x    4 1005     1005          4096 May  9 06:15 ..
drwxrwxr-x    3 1005     1005          4096 May  9 06:15 Cipher
drwxrwxr-x    3 1005     1005          4096 May  9 06:15 Hash
drwxrwxr-x    3 1005     1005          4096 May  9 06:15 IO
drwxrwxr-x    3 1005     1005          4096 May  9 06:15 Math
drwxrwxr-x    3 1005     1005          4096 May  9 06:15 Protocol
drwxrwxr-x    3 1005     1005          4096 May  9 06:15 PublicKey
drwxrwxr-x    3 1005     1005          4096 May  9 06:15 Random
drwxrwxr-x   12 1005     1005          4096 May  9 06:15 SelfTest
drwxrwxr-x    3 1005     1005          4096 May  9 06:15 Signature
drwxrwxr-x    3 1005     1005          4096 May  9 06:15 Util
-rwxrwxr-x    1 1005     1005           185 May  9 06:15 __init__.py
-rwxrwxr-x    1 1005     1005            99 May  9 06:15 __init__.pyi
drwxrwxr-x    2 1005     1005          4096 May  9 06:15 __pycache__
-rwxrwxr-x    1 1005     1005             0 May  9 06:15 py.typed
```

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: webOS 24
 - Kodi version:22.0-ALPHA1 (21.90.700)

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by cscd98**
## Description

Fixes Cryptodome not loading within addons on webOS

## Motivation and context

https://github.com/xbmc/xbmc/issues/26814

## How has this been tested?

1. Build kodi from source
2. Update IPK on TV
3. Install a plugin that needs Cryptodome e.g. https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore
4. Goto plugin->live TV->UK->my 5
5. No more exception is generated due to lack of Cryptodome

Python path now includes site-packages:

2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):   default python path:
```
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/site-packages
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/lib/python312.zip
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/lib/python3.12
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/lib/python3.12/lib-dynload
```

## What is the effect on users?

Allows you to use plugins that need Cryptodome

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by fuzzard** [comment]
Presumably tested and works?

**Comment by cscd98** [comment]
@fuzzard Yes this has been tested on my LG 55inch OLED and works.

File: xbmc/platform/linux/PlatformWebOS.cpp [hunk 1]
```diff
@@ -28,7 +28,12 @@ bool CPlatformWebOS::InitStageOne()
   setenv("XKB_CONFIG_ROOT", "/usr/share/X11/xkb", 1);
   setenv("WAYLAND_DISPLAY", "wayland-0", 1);
   setenv("PYTHONHOME", (HOME + "/lib/python3").c_str(), 1);
-  setenv("PYTHONPATH", (HOME + "/lib/python3").c_str(), 1);
+
+  std::string pythonPath;
+  pythonPath = (HOME + "/lib/python3").c_str();
+  pythonPath += (":" + pythonPath + "/site-packages").c_str();
```
Comment (fuzzard) [inline xbmc/platform/linux/PlatformWebOS.cpp]: i wouldnt expect you need the c_str() in either of the above two lines? Its going into a string, not a char*

Comment (cscd98) [reply xbmc/platform/linux/PlatformWebOS.cpp]: @fuzzard corrected and updated.

**Review by fuzzard — APPROVED** [review]
If it works, good by me

**Comment by sundermann** [comment]
I'm not against doing this change but there should be a symlink from `python3` to `python3.12` in the ipk. I'm pretty sure that Cryptodome (and other libraries) have been working in the past. Just wondering why it's breaking for you. Can you confirm that the symlink exists?

**Comment by cscd98** [comment]
@sundermann The symlink is still present and working:

```
lrwxr-xr-x    1 1000     1000            10 Jun  1 10:57 python3 -> python3.12
drwxrwxr-x   39 1005     1005          4096 Jun  1 10:59 python3.12
```

The problem is that site-packages sub-folder is not in PYTHONPATH anymore so the following is never found:

~/apps/usr/palm/applications/org.xbmc.kodi/lib/python3.12/site-packages/Cryptodome

I haven't had the need to use any plugins before so I don't know how or why this is broken, but its broken.

**PYTHONPATH**

Before patch example:
```
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/lib/python312.zip
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/lib/python3.12
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/lib/python3.12/lib-dynload
```

After patch:
```
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/site-packages
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/lib/python312.zip
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/lib/python3.12
2025-05-30 20:38:16.914 T:9528    debug <general>: CPythonInvoker(3):     /media/developer/apps/usr/palm/applications/org.xbmc.kodi/lib/python3/lib/python3.12/lib-dynload
```

**Review by sundermann — APPROVED** [review]
