### PR TITLE
[ffmpeg] Update to ffmpeg 8.0

### LINKED ISSUE #27245: Fast forward causes video to freeze and stop
### Describe the bug
Here is a clear and concise description of what the problem is:
When i push forward key video freeze and stop.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:
Have possibility to use forward key to navigate in video.

## Actual Behavior
Unable to naviage in video with Forward/Backward keys.

## Possible Fix
Maybe the "EXT-X-VERSION:7" tag in the manifest.m3u8 file is unknown to Kodi.

### To Reproduce
1. Video source:  https://www.dailymotion.com/video/x9qgg9c
2. Used Firefox to find real url of manifest.m3u8
3. Create strm file with this url. See example file _lcp_sans_isa.strm.txt_ below.
4. Launch strm file with kodi File Manager.

### Debuglog
The debuglog can be found here:
[kodi.log.txt](https://github.com/user-attachments/files/22346199/kodi.log.txt)
[lcp_sans_isa.strm.txt](https://github.com/user-attachments/files/22346200/lcp_sans_isa.strm.txt)
[manifest.m3u8.txt](https://github.com/user-attachments/files/22346201/manifest.m3u8.txt)

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Android 11, Windows 11
 - Kodi version: v21.2-omega, v22.0a1-Piers

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by sundermann**
## Description

Update to ffmpeg 8.0

Not that many changes necessary but one possibly major issue remains:
* libpostproc was removed from mainline ffmpeg. Currently it is merged back in using a patch and there is also a script in ffmpeg repository doing the same. The mailinglist states that libpostproc will remain in ffmpeg 8.0 so let's hope they add it to the tarball once released. Otherwise it will be painful to deal with the difference between ffmpeg 8.0 and 7.1 in cmake. In that case we would have to add libpostproc as a separate package in depends and deal with that in `FindFFmpeg.cmake`

## Motivation and context

Stay updated with ffmpeg

## How has this been tested?

webOS

## Types of change

- [ ] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [x] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **Student submission** (PR was done for educational purposes and will be treated as such)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [x] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by 78andyp** [comment]
Just trying on Win64. Noticed this whilst building ffmpeg:
image

Which then leads to:
image

**Comment by sundermann** [comment]
I've rebased all of the windows patches. But currently the buildserver is missing `nasm` which makes the build fail. I have added `nasm` to `download-msys2.bat` but I don't know if that file needs to be run manually to install it.

**Comment by 78andyp** [comment]
Thanks.
I'm still getting this with the latest push:
image

**Comment by sundermann** [comment]
I think this is due to another bad openssl check caused by the new `whip` muxer. I've disabled it as I don't think we have any use for such a muxer anyway.

**Comment by 78andyp** [comment]
This time I get:
image
Followed by:
image

**Comment by sundermann** [comment]
Right the `libpostproc` situation needs a patch for windows too.

**Comment by 78andyp** [comment]
Thanks. Builds and runs OK here now.

File: tools/buildsteps/windows/buildffmpeg.sh [hunk 1]
```diff
@@ -124,6 +124,7 @@ fi
 cd $LOCALBUILDDIR
 
 do_clean_get $1
+patch -p1 -d $LOCALSRCDIR -i /xbmc/tools/depends/target/ffmpeg/0001-libpostproc-plugin.patch -N -r -
```
Comment (thexai) [inline tools/buildsteps/windows/buildffmpeg.sh]: instead of this you can place the patch file in:

`tools/buildsteps/windows/patches`

with name:

`0006-ffmpeg-windows-libpostproc-plugin.patch`

and will be apply automatically

**Comment by thexai** [comment]
In Windows extension .gz is hardcoded in `buildhelpers.sh`

To properly pick same extension is need something like this:

```diff
diff --git a/tools/buildsteps/windows/buildhelpers.sh b/tools/buildsteps/windows/buildhelpers.sh
index 4815a00205..e48287920c 100644
--- a/tools/buildsteps/windows/buildhelpers.sh
+++ b/tools/buildsteps/windows/buildhelpers.sh
@@ -147,7 +147,8 @@ do_loaddeps() {
   LIBNAME=$(grep "LIBNAME=" $file | sed 's/LIBNAME=//g;s/#.*$//g;/^$/d')
   VERSION=$(grep "VERSION=" $file | sed 's/VERSION=//g;s/#.*$//g;/^$/d')
   SHA512=$(grep "SHA512=" $file | sed 's/SHA512=//g;s/#.*$//g;/^$/d')
-  ARCHIVE=$LIBNAME-$VERSION.tar.gz
+  EXT=$(grep "ARCHIVE=" $file | sed 's/ARCHIVE=//g;s/#.*$//g;/^$/d' | cut -d'.' -f2-3)
+  ARCHIVE=$LIBNAME-$VERSION.$EXT
 
   BASE_URL=$(grep "BASE_URL=" $file | sed 's/BASE_URL=//g;s/#.*$//g;/^$/d')
   if [ -z "$BASE_URL" ]; then
```

(to read extension from main FFMPEG-VERSION file)

This fixes:

```
 building FFmpeg x64
-------------------------------------------------
Hash of file 'ffmpeg-8.0.tar.gz' not match!
Expected: 96f01fc3b881e208e8d35d858b2f60627f298b06103195e3e753b1c6429810d7a484d4daeebad6d0810172616383d103dfb5fcadc4512726c3719800d24a3fde
Found: 31d5dffe7b4acd3b55193557e674fe1c2b54d89e4682bdcdd1cd6d2f2d06a5b08a82be224f97eeca5e09b15f93a93db177aeb072470a76ca2e782ba6a426d8bd
```

**Comment by thexai** [comment]
To force Jenkins create new MSYS2 build environment you can add this in a temp commit:

```diff
diff --git a/tools/buildsteps/windows/prepare-env.bat b/tools/buildsteps/windows/prepare-env.bat
index bcbaded7f9..866138435c 100644
--- a/tools/buildsteps/windows/prepare-env.bat
+++ b/tools/buildsteps/windows/prepare-env.bat
@@ -21,7 +21,7 @@ rem we assume git in path as this is a requirement
 rem git clean the untracked files and directories
 rem but keep the downloaded dependencies
 rem also keeps MSYS2 installation
-SET GIT_CLEAN_CMD=git clean -xffd -e "project/BuildDependencies/downloads" -e "project/BuildDependencies/downloads2" -e "project/BuildDependencies/mingwlibs" -e "project/BuildDependencies/msys64" -e "project/BuildDependencies/tools" -e "cmake/addons/build/download/msys2-base-*.tar.xz"
+SET GIT_CLEAN_CMD=git clean -xffd -e "project/BuildDependencies/downloads" -e "project/BuildDependencies/downloads2" -e "project/BuildDependencies/mingwlibs" -e "project/BuildDependencies/tools" -e "cmake/addons/build/download/msys2-base-*.tar.xz"
 
 ECHO running %GIT_CLEAN_CMD%
 %GIT_CLEAN_CMD%
```

File: tools/buildsteps/windows/buildffmpeg.sh (hunk 1 above)
Comment (sundermann) [reply tools/buildsteps/windows/buildffmpeg.sh]: My intention was to avoid having to carry the same patch twice. I was thinking if a symlink could work on windows here.

**Comment by CrystalP** [comment]
> I've rebased all of the windows patches. But currently the buildserver is missing `nasm` which makes the build fail. I have added `nasm` to `download-msys2.bat` but I don't know if that file needs to be run manually to install it.

Careful, requiring new msys/mingw packages may be a problem. Core is on the 20231026 release, which had some packages removed from msys mirrors due to age as @garbear found out for addons.
If the nasm package matching 20231026 is still available and can be uploaded to our mirrors, no problem.
Otherwise, the ability to build v22 will break at a random point in time. The solution to that, is an upgrade to 20250622, same version that garbear wants for addons (with the corresponding packages uploaded to our mirrors).

**Comment by thexai** [comment]
> (with the corresponding packages uploaded to our mirrors).

Or simply not use mirrors because MSYS2 is currently only downloaded once: it will not generate significant traffic on the source server.

**Comment by CrystalP** [comment]
The issue is not the traffic but the availability, as experienced by garbear for addons, and which prompted the last msys update.
image
nasm package not on Kodi mirrors but still available and needs to be uploaded.
https://repo.msys2.org/msys/x86_64/nasm-2.16.01-1-x86_64.pkg.tar.zst and https://repo.msys2.org/msys/x86_64/nasm-2.16.01-1-x86_64.pkg.tar.zst.sig
to https://mirrors.kodi.tv/build-deps/win32/msys2/repos/msys2/x86_64/
I added the info to #servers

File: tools/buildsteps/windows/buildffmpeg.sh (hunk 1 above)
Comment (sundermann) [reply tools/buildsteps/windows/buildffmpeg.sh]: I've added a copy of the patch as a symlink does not work on windows.

**Comment by thexai** [comment]
I opened a PR to update MSYS to 20250622 and now this builds fine in Jenkins:

```
20:39:17 INSTALL	build/src/ffmpeg-8.0/libavutil/tree.h
20:39:17 INSTALL	build/src/ffmpeg-8.0/libavutil/twofish.h
20:39:17 INSTALL	build/src/ffmpeg-8.0/libavutil/uuid.h
20:39:17 INSTALL	build/src/ffmpeg-8.0/libavutil/version.h
20:39:17 INSTALL	build/src/ffmpeg-8.0/libavutil/video_enc_params.h
20:39:17 INSTALL	build/src/ffmpeg-8.0/libavutil/xtea.h
20:39:17 INSTALL	build/src/ffmpeg-8.0/libavutil/tea.h
20:39:17 INSTALL	build/src/ffmpeg-8.0/libavutil/tx.h
20:39:17 INSTALL	build/src/ffmpeg-8.0/libavutil/video_hint.h
20:39:17 INSTALL	libavutil/avconfig.h
20:39:17 INSTALL	libavutil/ffversion.h
20:39:17 INSTALL	libavutil/libavutil.pc
20:39:17 [1mffmpeg-8.0 (x64)(B[m .................................................... [[32mDone(B[m]
20:39:17 -------------------------------------------------
20:39:17  building of FFmpeg x64 done...
20:39:17 -------------------------------------------------
20:39:17 -------------------------------------------------------------------------------
20:39:17  compile mingw libs x64 done...
20:39:17 -------------------------------------------------------------------------------
20:39:17 -------------------------------------------------------------------------------
20:39:17  compile all libs x64 done...
20:39:17 -------------------------------------------------------------------------------
20:39:17 ]0;compiling done...
20:39:17 
20:39:17 exiting msys environment
```

https://github.com/xbmc/xbmc/pull/27156

**Comment by sundermann** [comment]
Thanks!

**Review by neo1973 — APPROVED** [review]
Tested on Linux with VAAPI. All my test files still play. Not only that, Kodi can now play VVC encoded videos which didn't work before :slightly_smiling_face:

**Comment by sundermann** [comment]
Thanks for confirming `VAAPI` is fine!

The last remaining issue that I am not sure about is the `libpostproc` issue and how we want to handle it. Currently it is added back in a patch generated by [michaelni/FFmpeg@sourceplugin-libpostproc-8.0](https://github.com/michaelni/FFmpeg/tree/sourceplugin-libpostproc-8.0). This is similar to how ffmpeg's [merge-all-source-plugins](https://github.com/FFmpeg/FFmpeg/blob/master/tools/merge-all-source-plugins) works. I don't think this way is an issue for most platforms but it might be on linux. I don't know how linux packagers are going to provide `libpostproc` going forward. Currently there is no tagged release in the main [repository](https://github.com/michaelni/libpostproc) so it cannot be build out of tree. The ffmpeg 8.0 update however is fully backwards compatible with ffmpeg 7 so there is no immediate need for linux distributions to upgrade.

**Comment by CrystalP** [comment]
I think there was a misunderstanding with my previous statements and screenshot but with the refresh of msys to a more recent msys on the build bot, the issue was forced and an msys upgrade for all is now needed for consistency. Or did I misunderstand what happened?
Our current/old msys works fine, yol uploaded the package so there isn't even a warning now and it doesn't fallback on msys mirrors.

**Comment by sundermann** [comment]
@CrystalP can you follow up in #27156. I haven't applied the patch here because of your comment and its implications. Maybe you can better explain if the version bump should be done like that

**Comment by CrystalP** [comment]
Just did. The build of ffmpeg 8.0 is safe any way #27156 goes from what I can tell.

File: tools/buildsteps/windows/buildhelpers.sh [hunk 2]
```diff
@@ -147,7 +147,8 @@ do_loaddeps() {
   LIBNAME=$(grep "LIBNAME=" $file | sed 's/LIBNAME=//g;s/#.*$//g;/^$/d')
   VERSION=$(grep "VERSION=" $file | sed 's/VERSION=//g;s/#.*$//g;/^$/d')
   SHA512=$(grep "SHA512=" $file | sed 's/SHA512=//g;s/#.*$//g;/^$/d')
-  ARCHIVE=$LIBNAME-$VERSION.tar.gz
+  EXT=$(grep "ARCHIVE=" $file | sed 's/ARCHIVE=//g;s/#.*$//g;/^$/d' | cut -d'.' -f2-3)
+  ARCHIVE=$LIBNAME-$VERSION.$EXT
```
[the remark this answers is not in the document]
Comment (thexai) [reply tools/buildsteps/windows/buildhelpers.sh:151]: Yes, this demonstrate 12 lines of code can do near same as 2 lines...

**Comment by Portisch** [comment]
FFMPEG 8.0 is available now and `libpostproc` is not merged back into the release.
So Linux platform is broken right now and can't be updated to v8.0.

We did create a extra linux package for https://github.com/michaelni/libpostproc.
This does compile fine but for sure `FindFFMPEG` is need to be adapted.

We want to test ffmpeg 8 because of this: https://github.com/xbmc/xbmc/pull/27149#pullrequestreview-3148962525
The new S6, S905X5 Amlogic SoC will support VVC decode in hardware but current ffmpeg 7.1.1 does not work with any VVC samples.

**Comment by smp79** [comment]
Intel Lunar Lake (Core Ultra 200V) also supports VVC in hw via VAAPI. I suppose nobody has the hardware to implement VAAPI-VVC in Kodi.

**Comment by sundermann** [comment]
@Portisch Yes, Kodi can right now only be compiled against ffmpeg 7.1. So after merging this PR we can at least compile against 8.0. On Linux, as you pointed out, the situation is bad as there is no official release of `libpostproc`. I can't tell how distributions are going to bundle `libpostproc` going forward. Currently, neither debian nor arch have packaged ffmpeg 8.0 so it's hard to tell. But as it stands right now we simply cannot ship a standalone `libpostproc` simply due to a missing release. And also it's questionable if that is the recommended way of building the library when there is the official way of using sourceplugins (which essentially applies a patch). Right now, on Linux you can still build through depends or fallback to the internal build. If that is not possible then indeed ffmpeg 7.1 is the maximum version. But this PR does not raise the minimum ffmpeg version so I don't see this issue a blocker right now. Once the dust settles on the distros we can revisit how we want to tackle the `libpostproc` situation.

@smp79 Shouldn't that work on ffmpeg 8?

**Comment by smp79** [comment]
> Shouldn't that work on ffmpeg 8?

Software decode of VVC works on current master + ffmpeg 8. Hardware (VAAPI) would require something like this - https://github.com/xbmc/xbmc/pull/19661

**Comment by Portisch** [comment]
I got ffmpeg 8 now compiled on Linux by applying the patch directly. VVC is now decoded in hardware on Amlogic S905X5.
But there is another issue because ffmpeg do not supply codec extra data and Kodi will block until this data is received.
Not sure if this is a ffmpeg issue or if just no extra data does exist for VVC.

**Comment by Rechi** [comment]
Disabling yadif_videotoolbox filter for darwin_embedded shouldn't be required any more, with FFmpeg 8.0.
https://github.com/xbmc/xbmc/blob/72fe098c8436c96763f677b4c65d32988b931b5b/tools/depends/target/ffmpeg/CMakeLists.txt#L96


IMO commits should be reordered so that every commit can be built. Currently first commit is the version update and afterwards the required Kodi source code changes are added.

**Comment by sundermann** [comment]
Rebased and reordered the commits. Also enabled `yadif_videotoolbox`.

Not sure about VVC, @neo1973 mentioned it worked for him on Linux using VAAPI

**Comment by neo1973** [comment]
> Not sure about VVC, neo1973 mentioned it worked for him on Linux using VAAPI

VVC was software only, my hardware doesn't have a decoder.

**Comment by Portisch** [comment]
Yes, can confirm. For software decode ffmpeg 8 is need.
For VVC in hardware ffmpeg demuxer 7.1.1 is also already working well.

Only I am concern about is that there is no codec parameter extra data for VVC.
Not sure if this standard or a ffmpeg issue. But this becomes offtopic.

**Comment by ksooo** [comment]
@sundermann anything that speaks against merging this?

I for myself runtime-tested the PR on my NVidia Shield 2019 for couple of weeks and came not across a single problem or glitch.

**Comment by sundermann** [comment]
Not from my side, have also been running it for weeks now and haven't noticed any regressions.

**Comment by neo1973** [comment]
@sundermann: Please remove the `BASE_URL=https://ffmpeg.org/releases/` override. And if everything builds I'd say merge :slightly_smiling_face:

**Comment by 78andyp** [comment]
Has been working fine here on windows for a few weeks.

**Comment by fuzzard** [comment]
Please don't merge with duplicate 10k+ line patches. Totally unnecessary.

**Comment by sundermann** [comment]
@fuzzard What do you suggest doing instead? Patchset generated from https://github.com/FFmpeg/FFmpeg/compare/master...michaelni:FFmpeg:sourceplugin-libpostproc-8.0.diff

We can't use https://github.com/FFmpeg/FFmpeg/blob/master/tools/merge-all-source-plugins because the tarball is not a git repo. The libpostproc situation in general sucks

**Comment by fuzzard** [comment]
No problems with a patch, just don't have duplicate. Consolidate the windows patches into tools/depends/ffmpeg, alter the windows sh scripts for new location. It's partially done in #27237

**Comment by fuzzard** [comment]
If libpostproc is now an optional in ffmpeg, what is required to make our use of postproc optional. And what are the runtime/user ramifications of such a thing?

Id be hesitant to force this in, knowing full well that packagers (and even just normal linux users running ffmpeg8+) are then forced a shit hand to deal with it.

Arch appears to have ffmpeg 8 in [staging](https://archlinux.org/packages/extra-staging/x86_64/ffmpeg/), and it does not have libpostproc, so expect arch users to be here first with bug reports of not being able to compile. Surely its better to get ahead of an obvious issue?

**Comment by sundermann** [comment]
@fuzzard Would you mind taking a look at the latest fixup, especially the CMake related stuff? I did make libpostproc optional by falling back to an implementation that simply does nothing. However, UI related stuff isn't removed

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp [hunk 3]
```diff
@@ -309,7 +313,11 @@ enum AVPixelFormat CDVDVideoCodecFFmpeg::GetFormat(struct AVCodecContext * avctx
 CDVDVideoCodecFFmpeg::CDVDVideoCodecFFmpeg(CProcessInfo& processInfo)
   : CDVDVideoCodec(processInfo),
     m_videoBufferPool(std::make_shared<CVideoBufferPoolFFmpeg>()),
-    m_postProc(processInfo)
+#ifdef HAVE_LIBPOSTPROCe
```
Comment (HiassofT) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp]: Looks like a stray 'e' sneaked in here at the end

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp [hunk 4]
```diff
@@ -2971,19 +2971,33 @@ bool CFFmpegPostproc::Init(EINTERLACEMETHOD method)
...
-  if (av_opt_set_int_list(m_pFilterOut, "pix_fmts", pix_fmts,  AV_PIX_FMT_NONE, AV_OPT_SEARCH_CHILDREN) < 0)
+  if (av_opt_set_int_list(m_pFilterOut, "pix_fmts", pix_fmts, AV_PIX_FMT_NONE,
+                          AV_OPT_SEARCH_CHILDREN) < 0)
+#endif
   {
     CLog::Log(LOGERROR, "VAAPI::CFFmpegPostproc::Init  - failed settings pix formats");
     return false;
   }
 
+  if ((avfilter_init_str(m_pFilterOut, nullptr) < 0))
```
Comment (fuzzard) [inline xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp]: out of curiosity, why all the additional brackets everywhere?

**Comment by fuzzard** [comment]
> @fuzzard Would you mind taking a look at the latest fixup, especially the CMake related stuff? I did make libpostproc optional by falling back to an implementation that simply does nothing. However, UI related stuff isn't removed

it'll be fine as you have it. i'll clean it up with my other PR.

Im fine with the UI stuff not being removed in this PR personally, but i think it should be done before 22 final occurs. Whether that happens in this PR, or a followup, it doesnt bother me much

File: xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp (hunk 4 above)
Comment (sundermann) [reply xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp]: This pattern can hide bugs if you accidentally use `=` instead of `==` in a condition. Adding extra parentheses makes it clear the assignment is intentional and hides a warning in CLion. In this particular case however, it is indeed redundant.

**Comment by sundermann** [comment]
I prefer doing it in a followup

**Comment by sundermann** [comment]
Renamed and reordered the commit to make `libpostproc` optional. Should be good to go

**Comment by bkuhls** [comment]
> And what are the runtime/user ramifications of such a thing?

Maybe losing some vaapi/deinterlacing features? https://github.com/xbmc/xbmc/pull/5253

**Comment by sundermann** [comment]
Nothing we can do about that though. Get the maintainers of `libpostproc` to make a release so it can be packaged properly on linux.

**Comment by fuzzard** [comment]
That's fine. We as an app should just document somewhere (ie the wiki) that x/y features may not be available if your distro/packgemanager does not provide libpostproc


Its just another optional feature, as with every other optional we provide (cec, shairplay, etc).

We document so people understand, and don't just sweep it under the rug as "someone else's fault"

**Comment by bkuhls** [comment]
One unconditional include of libpostproc/postprocess.h is left: https://github.com/xbmc/xbmc/blob/d7d111363e6387245eebe201b30318e51a929dd0/xbmc/cores/FFmpeg.h#L21C11-L21C36

**Comment by bkuhls** [comment]
After removing the forementioned include a non-postproc build still fails
```
../../../../../../xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp: In constructor ‘CDVDVideoCodecFFmpeg::CDVDVideoCodecFFmpeg(CProcessInfo&)’:
../../../../../../xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp:318:1: error: expected identifier before ‘{’ token
  318 | {
```

**Comment by sundermann** [comment]
@bkuhls #27310
