### PR TITLE
[application] Fix and simplify application parameters handling.

### LINKED ISSUE #21284: IsStandAlone is set to late after PR #21200
### Describe the bug
Here is a clear and concise description of what the problem is:

Setting is hidden because of wrong status of requirement [IsStandAlone](https://github.com/xbmc/xbmc/blob/master/system/settings/settings.xml#L2503)

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

[IsStandAlone](https://github.com/xbmc/xbmc/blob/master/xbmc/Application.h#L271) need to be initialized before SettingsConditions get initialized.

## Actual Behavior

[m_bStandalone](https://github.com/xbmc/xbmc/blob/master/xbmc/Application.cpp#L335) is set to late.

### To Reproduce

1. Start kodi as standalone application and the `Refresh rate` setting is hidden

### Debuglog

The debuglog can be found here:
There is no debug log possible as CLog isn't initialized yet.
Debug prints by:
```c
diff --git a/xbmc/Application.cpp b/xbmc/Application.cpp
index bde74257ad..09d750b685 100644
--- a/xbmc/Application.cpp
+++ b/xbmc/Application.cpp
@@ -92,7 +92,6 @@
 #include "utils/SystemInfo.h"
 #include "utils/TimeUtils.h"
 #include "utils/XTimeUtils.h"
-#include "utils/log.h"
 #include "windowing/WinSystem.h"
 #include "windowing/WindowSystemFactory.h"
 
@@ -332,6 +331,7 @@ bool CApplication::Create(const CAppParamParser &params)
 
   m_bPlatformDirectories = params.HasPlatformDirectories();
   m_bTestMode = params.IsTestMode();
+  MYLOG(__FILE__, __FUNCTION__, __LINE__);
   m_bStandalone = params.IsStandAlone();
   m_windowing = params.GetWindowing();
   m_logTarget = params.GetLogTarget();
diff --git a/xbmc/Application.h b/xbmc/Application.h
index 1ddf3ca954..2123bf139e 100644
--- a/xbmc/Application.h
+++ b/xbmc/Application.h
@@ -28,6 +28,7 @@
 #include "threads/Thread.h"
 #include "utils/GlobalsHandling.h"
 #include "utils/Stopwatch.h"
+#include "utils/log.h"
 #include "windowing/OSScreenSaver.h"
 #include "windowing/Resolution.h"
 #include "windowing/XBMC_events.h"
@@ -268,7 +269,7 @@ public:
 
   int GlobalIdleTime();
 
-  bool IsStandAlone() { return m_bStandalone; }
+  bool IsStandAlone() { MYLOG(__FILE__, __FUNCTION__, __LINE__); return m_bStandalone; }
   bool IsEnableTestMode() { return m_bTestMode; }
 
   const std::string& GetLogTarget() const { return m_logTarget; }
diff --git a/xbmc/settings/SettingConditions.cpp b/xbmc/settings/SettingConditions.cpp
index fb4201f114..32182f44d8 100644
--- a/xbmc/settings/SettingConditions.cpp
+++ b/xbmc/settings/SettingConditions.cpp
@@ -28,6 +28,7 @@
 #include "utils/FontUtils.h"
 #include "utils/StringUtils.h"
 #include "windowing/WinSystem.h"
+#include "utils/log.h"
 
 bool AddonHasSettings(const std::string& condition,
                       const std::string& value,
@@ -420,8 +421,12 @@ void CSettingConditions::Initialize()
 #ifdef TARGET_ANDROID
   m_simpleConditions.insert("isstandalone");
 #else
+  MYLOG(__FILE__, __FUNCTION__, __LINE__);
   if (g_application.IsStandAlone())
+  {
+    MYLOG(__FILE__, __FUNCTION__, __LINE__);
     m_simpleConditions.insert("isstandalone");
+  }
 #endif
 
   m_simpleConditions.insert("has_ae_quality_levels");
diff --git a/xbmc/utils/log.h b/xbmc/utils/log.h
index 52e973e54e..58c2d24353 100644
--- a/xbmc/utils/log.h
+++ b/xbmc/utils/log.h
@@ -36,6 +36,11 @@
 
 #include <spdlog/spdlog.h>
 
+#include <iostream>
+static void MYLOG (const char* _file, const char* _function, const int line){
+   std::cerr << "[" << _function << "] " << line << " in " << _file << std::endl;
+}
+
 namespace spdlog
 {
 namespace sinks
```

In `log.h` prints these lines on console:
```text
[Initialize] 432 in xbmc/settings/SettingConditions.cpp
[IsStandAlone] 272 in xbmc/Application.h
[IsStandAlone] 272 in xbmc/Application.h
[IsStandAlone] 272 in xbmc/Application.h
[Create] 338 in xbmc/Application.cpp
[IsStandAlone] 272 in xbmc/Application.h
```

This shows clear the variable `m_bStandalone` is accessed before initialized.

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 - Kodi version:
Nexus Nightly

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by ksooo**
Fixes #21284 

Application parameters (for example passed by command line) are very very basic application data. Other very basic services like logging, settings, advanced settings etc. are dependent on app params.

In this PR, I factored out `CAppParams` from `CAppParamParser`, then made `CAppParams` the very first component registered at `CServiceBroker`so that the app params are available from the very beginning to other components. Furthermore I removed the app params "shadowed" at `CApplication` (members `m_standAlone` and others) which fixes some circular dependencies between `CApplication`and low level components like advanced settings. Last not least I factored the init/deinit of very basic app services (app params, settings, logging) into a new class `CAppEnvironment` which is now used at all the places which before worked with copied code (`BasicTestEnvironment`, `XMBC_Run`, tvOS main and iOS main).

I carefully runtime-tested on macOS and ensured Jenkins (including test suite) is green. 

@howie-f, @Portisch  maybe you could do a runtime-test on Linux?

@lrusak , @garbear anybody else, any comments regarding the general approach and the code changes?

### CODE REVIEW

**Comment by Portisch** [comment]
@ksooo I will and come back to you, but not before next week.

File: xbmc/ServiceBroker.cpp [hunk 1]
```diff
@@ -27,6 +27,21 @@ CServiceBroker::~CServiceBroker()
 {
 }
 
+std::shared_ptr<CAppParams> CServiceBroker::GetAppParams()
+{
+  return g_serviceBroker.m_appParams;
```
Comment (lrusak) [inline xbmc/ServiceBroker.cpp:32]: You don't seem to check for nullptr anywhere that `GetAppParams` is called. I believe it should always be available, however, do you think we should add a nullptr check here and throw or log if it is?

**Review by lrusak — APPROVED** [review]
Nice Cleanup and refactor. I had something similar in mind for `CAppParamParser`. I've only left a couple small comments.

**Review by garbear — APPROVED** [review]
Does this expose app params to Stage One? That's needed for https://github.com/xbmc/xbmc/pull/21182

**Comment by ksooo** [comment]
> Does this expose app params to Stage One? That's needed for https://github.com/xbmc/xbmc/pull/21182

Yes.

File: xbmc/AppParamParser.cpp [hunk 2]
```diff
@@ -47,12 +46,10 @@ constexpr const char* helpText =
 
 } // namespace
 
-CAppParamParser::CAppParamParser() : m_playlist(std::make_unique<CFileItemList>())
+CAppParamParser::CAppParamParser() : m_params(new CAppParams)
```
[the remark this answers is not in the document]
Comment (ksooo) [reply xbmc/AppParamParser.cpp:49]: yep, will change that

File: xbmc/ServiceBroker.cpp (hunk 1 above)
Comment (ksooo) [reply xbmc/ServiceBroker.cpp:32]: App params is supposed to be available as the very first "service" and calling it when it is not yet available is a logical error in the application, so we should throw a logic_error. Will change this.

**Review by howie-f — APPROVED** [review]
fixes missing `Refresh rate` setting when started with param `--standalone`

**Comment by Portisch** [comment]
@ksooo I can confirm the refresh rate setting is back with `standalone` parameter.  Just tested the PR on CoreELEC device. :ok_hand:
