### PR TITLE
PythonLanguageHook: safeguard against null __main__ PyModule

### LINKED ISSUE #19027: Kodi from Debian: segfault in PythonLanguageHook when shutting down
### Describe the bug

A Debian user reported a crash on Kodi shutdown in Debian testing (bullseye): https://bugs.debian.org/979367

## Expected Behavior

Kodi exits normally

## Actual Behavior

From the original Debian bug report:

```
I have configured kodi in standalone mode using lightdm autologin feature and the kodi.desktop xsession.
When I shutdown the PC using the kodi menu, kodi segfaults and thus lightdm restarts the session.
```

## Possible Fix

At a first glance, the problem lies in `XBMCAddon::Python::PythonLanguageHook::GetAddonId`:

https://github.com/xbmc/xbmc/blob/2d993a1e09427653dec6f2a7ab8972292a3e49e2/xbmc/interfaces/python/LanguageHook.cpp#L123

I think checking `main_module` and `global_dict` to be non-null is nice to have also in:

https://github.com/xbmc/xbmc/blob/2d993a1e09427653dec6f2a7ab8972292a3e49e2/xbmc/interfaces/python/LanguageHook.cpp#L137

and

https://github.com/xbmc/xbmc/blob/2d993a1e09427653dec6f2a7ab8972292a3e49e2/xbmc/interfaces/python/LanguageHook.cpp#L153

However, I could not reproduce the issue in my Debian testing VM yet.

### To Reproduce

1. Deploy a Debian testing VM with following Python addons:

```
CPythonInvoker(0, /home/kodi/.kodi/addons/plugin.video.netflix/service.py): script successfully run
2021-01-05 22:17:21.489 T:708      INFO <general>: Python interpreter interrupted by user
2021-01-05 22:17:21.489 T:709      INFO <general>: CPythonInvoker(1, /home/kodi/.kodi/addons/plugin.video.tubed/resources/lib/service.py): script successfully run
2021-01-05 22:17:21.494 T:709      INFO <general>: Python interpreter interrupted by user
2021-01-05 22:17:21.582 T:710      INFO <general>: CPythonInvoker(2, /home/kodi/.kodi/addons/plugin.video.youtube/resources/lib/startup.py): script successfully run
2021-01-05 22:17:21.602 T:710      INFO <general>: Python interpreter interrupted by user
2021-01-05 22:17:22.063 T:711      INFO <general>: CPythonInvoker(3, /home/kodi/.kodi/addons/script.common.plugin.cache/resources/lib/entry_point.py): script successfully run
2021-01-05 22:17:22.068 T:711      INFO <general>: Python interpreter interrupted by user
2021-01-05 22:17:22.280 T:712      INFO <general>: CPythonInvoker(4, /home/kodi/.kodi/addons/script.module.tubed.api/resources/lib/service.py): script successfully run
2021-01-05 22:17:22.295 T:712      INFO <general>: Python interpreter interrupted by user
2021-01-05 22:17:22.295 T:713      INFO <general>: [script.tubecast] ssdp: Stopping SSDP server
2021-01-05 22:17:22.578 T:713      INFO <general>: CPythonInvoker(5, /home/kodi/.kodi/addons/script.tubecast
```

2. Start Kodi and request to shut it down
3. Experience crash

### Debuglog

The debuglog can be found here: 
[kodi.log.txt](https://github.com/xbmc/xbmc/files/5773054/kodi.log.txt)

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [x] Linux
 - [ ] OSX
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name: Debian bullseye (testing)
 - Kodi version: 19.0 beta2

### PR DESCRIPTION
**Pull request by basilgello**
## Description

Fixes: #19027

## Motivation and Context

Fixes related Debian bug and makes Kodi for Debian great again 👍 
I expect it to be merged into 19.0-RC1 because it is a release-critical bug in Debian
that can destroy my efforts on getting Kodi into next stable Debian release (bullseye).

## How Has This Been Tested?

Built Debian package shutdowns cleanly on a bug reporter's HTPC.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [ ] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by basilgello** [comment]
@Paxxi @howie-f

File: xbmc/interfaces/python/LanguageHook.cpp [hunk 1]
```diff
@@ -120,6 +121,10 @@ namespace XBMCAddon
       // Get a reference to the main module
       // and global dictionary
       PyObject* main_module = PyImport_AddModule("__main__");
+      if (!main_module) {
+          CLog::Log(LOGERROR, "null __main__ module in PythonLanguageHook::GetAddonId()");
```
Comment (howie-f) [inline xbmc/interfaces/python/LanguageHook.cpp:125]: maybe change loglevels to debug:
```c
CLog::Log(LOGDEBUG, "PythonLanguageHook::{}: __main__ returns null", __FUNCTION__);
```

**Review by howie-f — COMMENTED** [review]
thanks for the fix @basilgello
not sure if this can be included in RC1

**Comment by basilgello** [comment]
> not sure if this can be included in RC1

I mean, in 19.0 release cycle. Actually I still can embed the patch into Debian packaging but I'd like to have it merged.

**Comment by basilgello** [comment]
@DaveTBlake any objections on merging this kind of patch into 19 ?

**Comment by lrusak** [comment]
you have some style issues, see https://jenkins.kodi.tv/job/BuildMulti-PR/18234/artifact/PR19036.diff

**Comment by basilgello** [comment]
The style should be fixed now, thanks!

**Review by Paxxi — APPROVED** [review]
Looking good. Nice work 😄
