### PR TITLE
Fix add-on setting references

### LINKED ISSUE #15252: Settings Across Categories
### Describe the bug
According to [https://kodi.wiki/view/Add-on_settings](https://kodi.wiki/view/Add-on_settings):

> Comparisons CANNOT be made across category/page boundaries. If one needs to compare to a setting on a different page, a copy of the setting with the same id can be placed on the page where the comparison is to take place and then hidden by setting visible to 'false'. The value is automatically updated when the setting on the other page is updated.

If you want to reference a certain setting from another page, you simply create a copy of that setting with the same ID in a different category. This worked perfectly in Kodi 17, but not at all in Kodi 18. It seems that if you create the non-visible copy of the setting and place it in a category **BEFORE** the actual visible element, the acutal visible element is never shown in the dialog.

## Expected Behavior
The setting's element should show in the settings dialog so that the user can change the value.

## Actual Behavior
The setting's element is not visible in the settings dialog so that the user cannot change the value.

## Possible Fix
I think that Kodi 18 uses the "visible" of the **FIRST** element in the XML, instead of checking if there are multiple elements with the same ID and applying their own respective "visible" attribute.

### To Reproduce
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<settings>
	<category label="category 1">
		<!-- The hidden copy of the setting to be referenced somewhere here in category1. It is hidden as expected by visible="false". -->
		<setting id="test" type="bool" visible="false" />
	</category>
	<category label="category 2">
		<!-- This is the actual setting that the user adjusts. This element is invisible in the settings dialog. Maybe Kodi uses the visible="false" from the previous reference . -->
		<setting id="test" type="bool" label="Test Setting" default="false" />
	</category>
</settings>
		
```

### Debuglog
Nothing in log.

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [x] Linux
 - [ ] OSX
 - [ ] Raspberry-Pi
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Window 10, Window 7, Ubuntu 16, Ubuntu 17, Ubuntu 18
 - Kodi version: Kodi 18 (this bug is not present in older versions)

### PR DESCRIPTION
**Pull request by Montellese**
## Description
This should finally fix the issues with "reference settings" in add-on settings using the old style settings format introduced with the original rework. There were two issues with the initial implementation of "reference settings":
* I assumed that the first appearence of a setting is a full definition of the setting with all its properties. But in reality the "full definition" of the setting is often not the first appearance which leads to a more or less empty setting definition (apart from the ID)
* I assumed that all references of a setting would be hidden / invisible because they only reference another setting due to limitations in the old add-on settings system. But in reality they are not always hidden and they even have their own visibility / enable conditions independent of the referenced setting.

The initial implementation of "reference settings" consisted of a `CSettingReference` class which pointed to the referenced setting. During loading of the add-on settings definition we used `CSettingReference` wherever a setting ID was re-used. When actually showing the add-on settings dialog we replaced all `CSettingReference` instances with pointers to the referenced setting.

This new implementation adds the possibility to mark any setting as a reference to another setting. This allows every "reference setting" to have their own visibility / enable conditions etc. During execution `CSettingsManager` keeps a list of all references and automatically triggers updates / events / callbacks on all reference-connected setting instances. Furthermore there is a merging functionality which allows to merge all setting definition details to be merged into the "main referenced setting".

## Motivation and Context
It fixes #15252.

## How Has This Been Tested?
I've tested it manually using the different versions of the settings test add-on provided by @Zomboided and @Zomboided has tested it as well.

## Types of change

- [x] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [x] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [x] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [x] All new and existing tests passed

### CODE REVIEW

**Comment by Montellese** [comment]
What's the status here? It's been two weeks without any feedback. In #15252 @Zomboided has confirmed that this solves his known problems.

**Comment by fuzzard** [comment]
Win32 failure. Logs gone to see what it was

Jenkins build this please

File: xbmc/addons/settings/AddonSettings.cpp [hunk 1]
```diff
@@ -593,21 +591,24 @@ std::shared_ptr<CSettingGroup> CAddonSettings::ParseOldSettingElement(const TiXm
...
-          setting = std::make_shared<CSettingReference>(settingId, GetSettingsManager());
+          setting->MakeReference();
         }
         else
         {
           // add the setting's identifier to the list of all identifiers
           settingIds.insert(setting->GetId());
         }
 
+        if (!settingWithConditions.enableCondition.empty() || !settingWithConditions.visibleCondition.empty())
```
Comment (Rechi) [inline xbmc/addons/settings/AddonSettings.cpp]: > The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

File: xbmc/settings/lib/SettingsManager.cpp [hunk 2]
```diff
@@ -769,7 +775,7 @@ bool CSettingsManager::Serialize(TiXmlNode *parent) const
 
   for (const auto& setting : m_settings)
   {
-    if (setting.second.setting->GetType() == SettingType::Action)
+    if (setting.second.setting->IsReference() || setting.second.setting->GetType() == SettingType::Action)
```
Comment (Rechi) [inline xbmc/settings/lib/SettingsManager.cpp]: > The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

File: xbmc/settings/lib/SettingsManager.cpp [hunk 3]
```diff
@@ -1225,37 +1266,97 @@ void CSettingsManager::AddSetting(std::shared_ptr<CSetting> setting)
...
+        {
+          auto referencedSettingId = setting->GetReferencedId();
+          auto itGroupedReferenceSetting = groupedReferenceSettings.find(referencedSettingId);
+          if (itGroupedReferenceSetting == groupedReferenceSettings.end())
+          {
+            SettingPtr referencedSetting = nullptr;
+            auto itReferencedSetting = FindSetting(referencedSettingId);
+            if (itReferencedSetting == m_settings.end())
+            {
+              CLog::Log(LOGWARNING, "CSettingsManager: missing referenced setting \"%s\"", referencedSettingId.c_str());
```
Comment (Rechi) [inline xbmc/settings/lib/SettingsManager.cpp]: > The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

File: xbmc/settings/lib/SettingsManager.cpp [hunk 4]
```diff
@@ -1225,37 +1266,97 @@ void CSettingsManager::AddSetting(std::shared_ptr<CSetting> setting)
...
+              continue;
+            }
+
+            GroupedReferenceSettings groupedReferenceSetting;
+            groupedReferenceSetting.referencedSetting = itReferencedSetting->second.setting;
+
+            itGroupedReferenceSetting = groupedReferenceSettings.insert(std::make_pair(referencedSettingId, groupedReferenceSetting)).first;
```
Comment (Rechi) [inline xbmc/settings/lib/SettingsManager.cpp]: > The `ColumnLimit` in `.clang-format` is set to `100` which defines line length [...]

https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md#3-formatting

File: xbmc/addons/settings/AddonSettings.cpp (hunk 1 above)
Comment (Montellese) [reply xbmc/addons/settings/AddonSettings.cpp]: Fixed

File: xbmc/settings/lib/SettingsManager.cpp (hunk 2 above)
Comment (Montellese) [reply xbmc/settings/lib/SettingsManager.cpp]: Fixed

File: xbmc/settings/lib/SettingsManager.cpp (hunk 4 above)
Comment (Montellese) [reply xbmc/settings/lib/SettingsManager.cpp]: Fixed

File: xbmc/settings/lib/SettingsManager.cpp (hunk 3 above)
Comment (Montellese) [reply xbmc/settings/lib/SettingsManager.cpp]: Fixed

**Comment by Montellese** [comment]
I've addressed all formatting comments. The last jenkins build failed because UWP Win64 could not find the Python 3.7 library. All other builds were fine.

**Comment by notspiff** [comment]
hi sascha :) uwp is known broken due to python. you can merge when everything else passes.
