### PR TITLE
[Subtitles] Fix WebVTT subtitles that make use of persistent overlay not shown after seek.

### LINKED ISSUE #27700: PR #27595 has broken WebVTT subtitles that make use of persistent overlay
### Describe the bug
Here is a clear and concise description of what the problem is:

After a video seek its possible that the overlay could be wrongly deleted and so subtitles are not visible anymore

after reverting commit about CDVDOverlayGroup change in PR #27595
subtitles are displayed correctly as usual after video seeks

### To Reproduce

1. Play this STRM, require InputStream Adaptive
[DASH_WebVTT_AsFile.strm.txt](https://github.com/user-attachments/files/24676733/DASH_WebVTT_AsFile.strm.txt)
2. set subtitles to english
2. wait first 10 seconds to see first subtitles displayed correctly
3. do some video seek and subtitles will be broken / not displayed anymore

### Debuglog

The debuglog can be found here:
https://paste.kodi.tv/umelelagiz.kodi

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

COverlayCodecWebVTT make use of a single persistent overlay 
where iPTSStartTime= 0 and iPTSStopTime = DVD_NOPTS_VALUE
and IsOverlayContainerFlushable is false

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [x] Windows
 - [ ] Windows UWP

 - Operating system version/name: Windows 11
 - Kodi version: v22 master branch

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

The flushable state was not being properly set and was assumed to be true.

## Motivation and context

Fix #27700.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] All new and existing tests passed

### CODE REVIEW

**Comment by 78andyp** [comment]
@claude review

**Comment by CastagnaIT** [comment]
i have a question with last PR #27595 change you are passing always a CDVDOverlayGroup instead of CDVDOverlay?
Have you checked what the OverlayRenderer receives?
because you could have broken also the other members since used on OverlayRenderer (from "Convert" method inner code)
https://github.com/xbmc/xbmc/blob/7e72aba3f4690dcb14dd5a26d78e5a9f6ba0ac71/xbmc/cores/VideoPlayer/VideoRenderers/OverlayRenderer.cpp#L150

these are:
IsForcedMargins
IsTextAlignEnabled

atm i have no time to debug nothing but if needed i will on next days

**Comment by 78andyp** [comment]
Thanks. You know more about this than I do.
Looking at the code it doesn't look like tetxt alignment is supported here:
```
  virtual void SetTextAlignEnabled(bool enable)
  {
    throw std::logic_error("EnableTextAlign method not implemented.");
  }
```
but I've added support for forced margins.

**Comment by CastagnaIT** [comment]
correct me if im wrong since i dont have time to verify
so for now i can place here only some questions

to me this new code about `InitialiseNewOverlayGroup` seem to do a wrong behavior

https://github.com/xbmc/xbmc/blob/7e72aba3f4690dcb14dd5a26d78e5a9f6ba0ac71/xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp#L69-L71

It seems that it makes a copy of the original overlay in to a new "group" overlay
but what happens to the original overlay object? Will it be lost?

fwik dont exist CDVDOverlay only, but it can also be derived objects such as for example CDVDOverlayLibass
a manual creation of this "group" will lost the original CDVDOverlay derived object or not? please check

also IMO you should not make a copy of each single data from InitialiseNewOverlayGroup method
but instead you should add or a new constructor into CDVDOverlayGroup where will copy relevant data, or as alternative a kind of clone method
but IMO here there could be a design problem in your solution done by previous PR

> Looking at the code it doesn't look like tetxt alignment is supported here

this is because of derived objects mentioned above such as CDVDOverlayLibass

I think @enen92 can also give you some advice here

File: xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp [hunk 1]
```diff
@@ -46,6 +46,8 @@ std::shared_ptr<CDVDOverlayGroup> InitialiseNewOverlayGroup(std::shared_ptr<CDVD
   group->iPTSStopTime = overlay->iPTSStopTime;
   group->bForced = overlay->bForced;
   group->replace = overlay->replace;
+  group->SetOverlayContainerFlushable(overlay->IsOverlayContainerFlushable());
+  group->SetForcedMargins(overlay->IsForcedMargins());
```
Comment (CastagnaIT) [inline xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp]: i finally found a bit of time to debug, so `IsForcedMargins`/`SetForcedMargins  ` copy can be removed

File: xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp [hunk 2]
```diff
@@ -72,7 +74,13 @@ void CVideoPlayerSubtitle::SendMessage(std::shared_ptr<CDVDMsg> pMsg, int priori
           while ((overlay = m_pOverlayCodec->GetOverlay()) != nullptr)
           {
             if (*group->m_overlays.back() == *overlay)
+            {
               group->m_overlays.emplace_back(overlay);
+              if (!overlay->IsOverlayContainerFlushable())
+                group->SetOverlayContainerFlushable(false);
+              if (!overlay->IsForcedMargins())
+                group->SetForcedMargins(false);
```
Comment (CastagnaIT) [inline xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp]: IMO I would avoid this overwriting within a loop it loses effectiveness
why not instead add m_overlayContainerFlushable comparison here?

```diff
diff --git a/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h b/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h
index 5ea6aba5e4..fee56f310b 100644
--- a/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h
+++ b/xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h
@@ -59,7 +59,7 @@ public:
     constexpr double epsilon{0.1};
     return std::abs(iPTSStartTime - other.iPTSStartTime) < epsilon &&
            std::abs(iPTSStopTime - other.iPTSStopTime) < epsilon && bForced == other.bForced &&
-           replace == other.replace;
+           replace == other.replace && m_overlayContainerFlushable == other.m_overlayContainerFlushable;
   }

   bool IsOverlayType(DVDOverlayType type) const { return (m_type == type); }
```

File: xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp (hunk 1 above)
Comment (78andyp) [reply xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp]: Done

File: xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp (hunk 2 above)
Comment (78andyp) [reply xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp]: Done

**Review by CastagnaIT — APPROVED** [review]
