### PR TITLE
[Android] Network: fix after "Listen to default network changes"

### LINKED ISSUE #23315: http web server won't start
### Describe the bug
Here is a clear and concise description of what the problem is:

When activating 'allow remote control via HTTP', there is a popup 'web server failed to start'

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

Web Service should start
(Was working in 20230329 build)

### To Reproduce

1. 
2.
3.

### Debuglog

The debuglog can be found here:
Nothing significant found in debug log

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ x] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP

 - Operating system version/name:
 Android TV 9 (firestick 4k max)
 - Kodi version:
Kodi 21 20230520

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by thexai**
## Description
Network: fix after "Listen to default network changes"

## Motivation and context
On Shield, at least, https://github.com/xbmc/xbmc/pull/23059 has broken the network because `m_defaultInterface` can be nullptr in some cases:

Callbacks only are received after network changes (lost, recovered, new) but not when app starts. This PR enables fallback to old enumeration method when `m_defaultInterface` is not yet initialized. 

## How has this been tested?
Runtime tested Shield 2019

## What is the effect on users?
Fix network not usable. The first symptom is that the web server for remote control fails to initialize when Kodi starts up.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)
- [ ] **Clean up** (non-breaking change which removes non-working, unmaintained functionality)
- [ ] **Improvement** (non-breaking change which improves existing functionality)
- [ ] **New feature** (non-breaking change which adds functionality)
- [ ] **Breaking change** (fix or feature that will cause existing functionality to change)
- [ ] **Cosmetic change** (non-breaking change that doesn't touch code)
- [ ] **None of the above** (please explain below)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [ ] My change requires a change to the documentation, either Doxygen or wiki
- [ ] I have updated the documentation accordingly
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [ ] I have added tests to cover my change
- [ ] All new and existing tests passed

### CODE REVIEW

**Comment by joseluismarti** [comment]
It's strange, the constructor registers the `CNetworkAndroid` class and immediately a notification is received (`onAvailable` callback) initializing `m_defaultInterface`.

Later, the first call to `GetFirstConnectedInterface()` is received, it should not give any issues, let's do more tests.

**Comment by fritsch** [comment]
This "immediately" is not atomic. Therefore a timespan exists where this ptrs is null.

**Comment by joseluismarti** [comment]
In my tests and now with daily use, the network is always available from the start.

Where in the code do you get `nullptr`? Could it only affect the webserver startup?

**Comment by thexai** [comment]
There are at least two problems:

- `CNetworkBase::GetInterfaceList` is core API (common to all platforms) and should be available also in Android.
- This code is NOT called on Shield when Kodi starts up:
https://github.com/xbmc/xbmc/blob/2f793e7f9ed32dbc63a6790bebebd58109c19d6d/xbmc/platform/android/network/NetworkAndroid.cpp#L368-L381

Only is called when network changes, then `m_defaultInterface` never is initialized in normal conditions (no network changes on wired permanent Ethernet).

File: xbmc/platform/android/network/NetworkAndroid.cpp [hunk 1]
```diff
@@ -279,7 +279,7 @@ CNetworkInterface* CNetworkAndroid::GetFirstConnectedInterface()
 {
   std::unique_lock<CCriticalSection> lock(m_refreshMutex);
 
-  if (CJNIBase::GetSDKVersion() >= 24)
+  if (CJNIBase::GetSDKVersion() >= 24 && m_defaultInterface)
```
Comment (thexai) [inline xbmc/platform/android/network/NetworkAndroid.cpp:282]: This condition can be simplified to:

` if (m_defaultInterface)` 

because in SDK < 24 guarantees that `m_defaultInterface`  never is initialized then is redundant check SDK here.

**Comment by joseluismarti** [comment]
> * This code is NOT called on Shield when Kodi starts up:

Startup log in Android Emulator and the same in FireTV:

```
D Kodi    : 2023-05-21 19:29:45.130 T:30110   debug <general>: virtual void CXBMCApp::onGainFocus(): 
D Kodi    : 2023-05-21 19:29:45.254 T:30111   debug <general>: CSettings: loaded settings definition from special://xbmc/system/settings/settings.xml
D Kodi    : 2023-05-21 19:29:45.495 T:30111   debug <general>: CSettings: loaded settings definition from special://xbmc/system/settings/android.xml
D Kodi    : 2023-05-21 19:29:45.533 T:30115   debug <general>: Thread Announce start, auto delete: false
D Kodi    : 2023-05-21 19:29:45.562 T:30116   debug <general>: CNetworkAndroid::onAvailable The default network is now: 134
I Kodi    : 2023-05-21 19:29:45.563 T:30111    info <general>: -----------------------------------------------------------------------
I Kodi    : 2023-05-21 19:29:45.566 T:30111    info <general>: Starting Kodi (21.0-ALPHA1 (20.90.101) Git:20230519-aefcb837ab-dirty). Platform: Android ARM 32-bit
...
```

File: xbmc/platform/android/network/NetworkAndroid.cpp (hunk 1 above)
Comment (joseluismarti) [reply xbmc/platform/android/network/NetworkAndroid.cpp]: Right, more simple

**Comment by thexai** [comment]
Is not only in Shield, this is in Google Pixel 5 with latest nightly (kodi-20230520-2f793e7f-master-arm64-v8a.apk):

Screenshot_20230521-204910

**Comment by joseluismarti** [comment]
This error message appears when we activate the Web server and occurs because `m_interfaces` (which contains all the available interfaces) is not initialized, it's the bug and is solved by adding `RetrieveInterfaces()`.

Regardless of this, the device should have network connectivity (see System Info > Network) and `m_defaultInterface` should be initialized.

I'm fine with the fix, go ahead :+1:
