### PR TITLE
[Video] Fix #27121 broke Bluray menus.

### LINKED ISSUE #27582: glitches and graphic errors in bluray menus
### Describe the bug
Here is a clear and concise description of what the problem is:

I have some bluray copies in .iso, but also as full extracted archive. When i play them, all looks good in the beginning, but when i use the browse functions to e.g. select a track, the glitches and graphic errors start to happen. For example, the new blu ray from pink floyd - wish you where here (50 years). I can open it, the menu starts and when i select anything, the cursor is like copied and then its impossible to see what was selected because every item i scroll to is selected and the cursor looks like as if it would stay there. I can create a picture if required.

## Expected Behavior
Here is a clear and concise description of what was expected to happen:

I would expect that, when i use the remote to jump to another selection, the cursor from the previous selection is removed.

## Actual Behavior

The cursor is not removed and then its impossible to see what is really selected.

### To Reproduce

1. Open any blu ray iso with a menu
2. Let kodi show the menu
3. Navigate in the menu

### Debuglog

The debuglog can be found here:
https://pastebin.com/yRVftXtz

### Screenshots 
Here are some links or screenshots to help explain the problem:

## Additional context or screenshots (if appropriate)
Here is some additional context or explanation that might help:

### Your Environment
Used Operating system:

 - [ ] Android
 - [ ] iOS
 - [ ] tvOS
 - [ ] Linux
 - [ ] macOS
 - [ ] Windows
 - [ ] Windows UWP
 - [ x ] CoreElec

 - Operating system version/name:
 - Kodi version: 22

*note: Once the issue is made we require you to update it with new information or Kodi versions should that be required.
Team Kodi will consider your problem report however, we will not make any promises the problem will be solved.*

### PR DESCRIPTION
**Pull request by 78andyp**
## Description

Group subtitles that share the same start/stop/forced/replace attributes prior to passing for processing.
(Thanks to @CrystalP for the tip)

Also, as part of understanding subtitle processing, refactored CDVDOverlayContainer.
Most is just moderninsing for C++20 but also cost of CleanUp() is now O(n log n) rather than O(n^2).

## Motivation and context

Fix #27582.

## How has this been tested?

Locally.
Against sample from #27095.
Against sample provided by @KarellenX.

## Types of change

- [X] **Bug fix** (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the **[Code Guidelines](https://github.com/xbmc/xbmc/blob/master/docs/CODE_GUIDELINES.md)** of this project 
- [X] I have read the **[Contributing](https://github.com/xbmc/xbmc/blob/master/docs/CONTRIBUTING.md)** document
- [X] All new and existing tests passed

### CODE REVIEW

File: xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp [hunk 1]
```diff
@@ -13,106 +13,91 @@
...
 }
+} // namespace
 
 void CDVDOverlayContainer::CleanUp(double pts)
 {
   std::unique_lock lock(*this);
 
-  auto it = m_overlays.begin();
-  while (it != m_overlays.end())
+  std::set<double> forcedStartTimes;
```
Comment (sundermann) [inline xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp]: This is not O(n) as claimed in the PR but O(n log n). Not sure how large the set is going to be but if it does have a lot of elements `std::unordered_set` can be worth it, for small sets though it is often slower.

Comment (78andyp) [reply xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp]: I'll be guided by you. Whilst debugging one video there were about 50 elements in m_overlays.

Comment (sundermann) [reply xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp]: 50 elements is probably better to just keep using `std::set`, but you should probably update the PR description

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h [hunk 2]
```diff
@@ -103,6 +101,12 @@ class CDVDOverlay : public std::enable_shared_from_this<CDVDOverlay>
   bool replace; // replace by next nomatter what stoptime it has
   unsigned long m_textureid;
 
+  bool operator==(const CDVDOverlay& other) const
+  {
+    return iPTSStartTime == other.iPTSStartTime && iPTSStopTime == other.iPTSStopTime &&
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h]: Done.

File: xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp [hunk 3]
```diff
@@ -52,12 +66,19 @@ void CVideoPlayerSubtitle::SendMessage(std::shared_ptr<CDVDMsg> pMsg, int priori
 
       if (result == OverlayMessage::OC_OVERLAY)
       {
-        std::shared_ptr<CDVDOverlay> overlay;
-
-        while ((overlay = m_pOverlayCodec->GetOverlay()))
+        std::shared_ptr<CDVDOverlay> overlay{m_pOverlayCodec->GetOverlay()};
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp]: There is always at least one overlay. Can't use continue but added a check anyway.

File: xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp [hunk 4]
```diff
@@ -13,106 +13,91 @@
...
+  for (auto it = m_overlays.end(); it != m_overlays.begin();)
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp]: Must be iterated in reverse. Have attempted to modify.

File: xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp [hunk 5]
```diff
@@ -13,106 +13,91 @@
 
 #include <memory>
```
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp:14]: Done

File: xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp (hunk 4 above)
[the remark this answers is not in the document]
Comment (78andyp) [reply xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp]: This is not correct. If it=m_overlays.erase(it) returns begin() then that will be detected by the loop conditions and if it = position N and this is erased then N+1 will be returned and on the next loop --it will return what was N-1.

**Comment by 78andyp** [comment]
@claude review. Specifically comment on the copilot issues and my comments.

File: xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h [hunk 6]
```diff
@@ -103,6 +101,14 @@ class CDVDOverlay : public std::enable_shared_from_this<CDVDOverlay>
   bool replace; // replace by next nomatter what stoptime it has
   unsigned long m_textureid;
 
+  bool operator==(const CDVDOverlay& other) const
+  {
+    constexpr double epsilon{0.1};
+    return std::abs(iPTSStartTime - other.iPTSStartTime) < epsilon &&
+           std::abs(iPTSStopTime - other.iPTSStopTime) < epsilon && bForced == other.bForced &&
+           replace == other.replace;
+  }
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/DVDCodecs/Overlay/DVDOverlay.h]: constructors/destructors/operators usually go at the top of the class (line 56 for example)

File: xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp [hunk 7]
```diff
@@ -52,11 +66,20 @@ void CVideoPlayerSubtitle::SendMessage(std::shared_ptr<CDVDMsg> pMsg, int priori
 
       if (result == OverlayMessage::OC_OVERLAY)
       {
-        std::shared_ptr<CDVDOverlay> overlay;
-
-        while ((overlay = m_pOverlayCodec->GetOverlay()))
+        if (std::shared_ptr<CDVDOverlay> overlay{m_pOverlayCodec->GetOverlay()}; overlay)
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/VideoPlayerSubtitle.cpp]: overlay != nullptr please

**Review by CrystalP — COMMENTED** [review]
Well done with the overlay group creation. See a couple small style comments. However the 1st commit is missing a crucial fix in DVDOverlayContainer: the removal of the condition pOverlay->iPTSStartTime != pOverlay2->iPTSStartTime that created the menu issue in 27121. The purpose of a refactor is not to fix. With those changes I'd have no problem approving the fix.

I'm much less confident about the refactor, especially CleanUp, and would prefer to evaluate it in a dedicated PR, ideally with some unit tests, the classes look like they might lend themselves to the exercise.

**Comment by 78andyp** [comment]
> Well done with the overlay group creation. See a couple small style comments. However the 1st commit is missing a crucial fix in DVDOverlayContainer: the removal of the condition pOverlay->iPTSStartTime != pOverlay2->iPTSStartTime that created the menu issue in 27121. The purpose of a refactor is not to fix. With those changes I'd have no problem approving the fix.
> 
> I'm much less confident about the refactor, especially CleanUp, and would prefer to evaluate it in a dedicated PR, ideally with some unit tests, the classes look like they might lend themselves to the exercise.

Will move refactor.

EDIT: Regarding the `pOverlay->iPTSStartTime != pOverlay2->iPTSStartTime` - actually removing this is part of the fix. When looking @KarellenX sample the subtitles used in the menu are all forced with a start time of -1 and an end time of 0. They persist of the screen because of the line above added in #27121.

With the fix included here there will be no subtitles (outside of a group) sharing the same start time - as they are grouped prior to DVDOverlayContainer - that statement is no longer needed.

I've used the sample video included in the bug report that led to #27171 to confirm that.

**Comment by 78andyp** [comment]
@claude review.

**Comment by CrystalP** [comment]
> EDIT: Regarding the `pOverlay->iPTSStartTime != pOverlay2->iPTSStartTime` - actually removing this is part of the fix. When looking @KarellenX sample the subtitles used in the menu are all forced with a start time of -1 and an end time of 0. They persist of the screen because of the line above added in #27121.
> 
> With the fix included here there will be no subtitles (outside of a group) sharing the same start time - as they are grouped prior to DVDOverlayContainer - that statement is no longer needed.
> 
> I've used the sample video included in the bug report that led to #27171 to confirm that.

My point is that removing that condition is necessary to fix menus and should be part of the first commit for a standalone fix commit and it should not be a silent change of the refactor.

I'm afraid of refactoring that code. There are unwritten assumptions and hidden tricks, and overlays are not Bluray only.
Claude can probably suggest a testing harness but don't know if it can be trusted for the content of the tests.

File: xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp [hunk 8]
```diff
@@ -13,106 +13,92 @@
...
-  while (it != m_overlays.end())
+  std::set<double> forcedStartTimes;
+  for (auto it = m_overlays.end(); it != m_overlays.begin();)
   {
-    const std::shared_ptr<CDVDOverlay>& pOverlay = *it;
-
-    // never delete forced overlays, they are used in menu's
-    // clear takes care of removing them
-    // also if stoptime = 0, it means the next subtitles will use its starttime as the stoptime
-    // which means we cannot delete overlays with stoptime 0
```
Comment (CrystalP) [inline xbmc/cores/VideoPlayer/DVDOverlayContainer.cpp:72]: I think preserving that part of the comment is important. The previous part is outdated and can go.
What little information is available should be preserved

**Review by CrystalP — APPROVED** [review]
Looks good, thanks!

**Comment by 78andyp** [comment]
> > EDIT: Regarding the `pOverlay->iPTSStartTime != pOverlay2->iPTSStartTime` - actually removing this is part of the fix. When looking @KarellenX sample the subtitles used in the menu are all forced with a start time of -1 and an end time of 0. They persist of the screen because of the line above added in #27121.
> > With the fix included here there will be no subtitles (outside of a group) sharing the same start time - as they are grouped prior to DVDOverlayContainer - that statement is no longer needed.
> > I've used the sample video included in the bug report that led to #27171 to confirm that.
> 
> My point is that removing that condition is necessary to fix menus and should be part of commit #1 for a standalone fix commit and it should not be a silent change of the refactor.
> 
> I'm afraid of refactoring that code. There are unwritten assumptions and tricks hidden, and overlays are not Bluray only. Claude can probably suggest a testing harness but don't know if it can be trusted for the content of the tests.

It's included now.

Isn't that a good reason to refactor and document??

**Comment by CrystalP** [comment]
> Isn't that a good reason to refactor and document??

Definitely but with caution as we don't really know the complete set of use cases and workarounds embedded in there.

**Review by thexai — APPROVED** [review]
Tested latest update of this PR and confirmed fixes menu issues in "Black Widow" UHD Blu-Ray.

**Comment by 78andyp** [comment]
> Tested latest update of this PR and confirmed fixes menu issues in "Black Widow" UHD Blu-Ray.

Thanks for confirming.
